### ISSUE TITLE
Knowledge sharing presentation about trackers

### ISSUE THREAD

**Issue by koernerfelicia** [RasaHQ/rasa#10000]
Presentation date TBD, ideally Nov. 4th

**Definition of Done**
Produce a presentation that includes:
- [ ] a review of how training data gets turned into trackers/tracker loading: what influences how it's done? In what order is it done?
- [ ] information on checkpoint resolution
- [ ] explanation of what the debug logs about augmentation rounds/trackers loaded/active trackers really mean?
(see [here](https://rasa-hq.slack.com/archives/CGN6B6MP0/p1630513378003600?thread_ts=1629969474.001700&cid=CGN6B6MP0) for discussion)

- [ ] optionally poll `#knowledge-sharing` to see what other questions people have

**Comment by dakshvar22** [comment]
@koernerfelicia Can we close this issue? I believe everything has been done?

**Comment by koernerfelicia** [comment]
Yep, thanks for pointing this out!
