### ISSUE TITLE
Compare the evaluation results from round 1.0 to those from round 1.1

### ISSUE THREAD

**Issue by koernerfelicia** [RasaHQ/rasa#10006]
Round 1.0:
- First round
Round 1.1:
- Same 60 conversations, but bot-builders switched

**Definition of Done**
- [ ] Compare the evaluation results from round 1.0 to those from round 1.1
- [ ] Produce a summary and discussion of this comparison
- [ ] We have answered - "Does the evaluation get affected by who the bot-builder is?"

**Comment by JEM-Mosig** [comment]
Closing this as the project closed.
