### ISSUE TITLE
Document assumptions in the E2E evaluation workflow

### ISSUE THREAD

**Issue by koernerfelicia** [RasaHQ/rasa#10008]
Workflow in question is the A/B testing workflow adopted as described [here](https://www.notion.so/rasa/Abstract-Round-1-A-B-Testing-543e05729ad6462199111af2df80bed8#ee0ac44e0f4240d78bac61ba13d24ea5).

For example:
1. users would quit after one incorrect action
2. users will only try to rephrase the same message up to two times...

**Definition of Done**
- [x] Assumptions in the E2E evaluation workflow are documented in the [research abstract](https://www.notion.so/rasa/Abstract-Round-1-A-B-Testing-543e05729ad6462199111af2df80bed8). For now, focus on the assumptions of the first iteration of the workflow (as opposed to any iterations we're thinking of making)

**Comment by dakshvar22** [comment]
Documented [here](https://www.notion.so/rasa/Abstract-Round-1-A-B-Testing-543e05729ad6462199111af2df80bed8#1b6d52015c3b41b5813cf874800c71ba)
