### ISSUE TITLE
`.get_default_config()` fails in unit tests

### ISSUE THREAD

**Issue by koaning** [RasaHQ/rasa#10004]
I'm working on the main branch for 3.0\. I have made a very basic tokenizer and I would like to make tests for it. This is something I'd advise to anybody who produces custom components. This is the tokenizer, saved in a `nlu_tok.py` file

<pre>from __future__ import annotations
 from typing import Any, Dict, List, Optional, Text

from rasa.engine.graph import ExecutionContext
 from rasa.engine.recipes.default_recipe import DefaultV1Recipe
 from rasa.engine.storage.resource import Resource
 from rasa.engine.storage.storage import ModelStorage
 from rasa.nlu.tokenizers.tokenizer import Token, Tokenizer
 from rasa.shared.nlu.training_data.message import Message

@DefaultV1Recipe.register(
 DefaultV1Recipe.ComponentType.MESSAGE_TOKENIZER, is_trainable=False
 )
 class AnotherWhitespaceTokenizer(Tokenizer):
 """Creates features for entity extraction."""

 @staticmethod
 def not_supported_languages() -> Optional[List<span class="error">[Text]</span>]:
 """The languages that are not supported."""
 return <span class="error">["zh", "ja", "th"]</span>

 @staticmethod
 def get_default_config() -> Dict<span class="error">[Text, Any]</span>:
 """Returns the component's default config."""
 return 

 { # This *must* be added due to the parent class. "intent_tokenization_flag": False, # This *must* be added due to the parent class. "intent_split_symbol": "_", # This is a, somewhat silly, config that we pass "only_alphanum": True, } 

 def __init__(self, config: Dict<span class="error">[Text, Any]</span>) -> None:
 """Initialize the tokenizer."""
 super().__init__(config)
 self.only_alphanum = config<span class="error">['only_alphanum']</span>

 def parse_string(self, s):
 if self.only_alphanum:
 return "".join(<span class="error">[c for c in s if str.isalnum(c)]</span>)
 return s

 @classmethod
 def create(
 cls,
 config: Dict<span class="error">[Text, Any]</span>,
 model_storage: ModelStorage,
 resource: Resource,
 execution_context: ExecutionContext,
 ) -> AnotherWhitespaceTokenizer:
 return cls(config)

 def tokenize(self, message: Message, attribute: Text) -> List<span class="error">[Token]</span>:
 text = self.parse_string(message.get(attribute))

 words = <span class="error">[w for w in text.split(" ") if w]</span>

1.  if we removed everything like smiles `![](/images/icons/emoticons/smile.png)`, use the whole text as 1 token
     if not words:
     words = <span class="error">[text]</span>

1.  the ._convert_words_to_tokens() method is from the parent class.
     tokens = self._convert_words_to_tokens(words, text)

 return self._apply_token_pattern(tokens)</pre>

This is my test file.

<pre>from nlu_tok import AnotherWhitespaceTokenizer
 from rasa.engine.storage.resource import Resource
 from rasa.engine.storage.local_model_storage import LocalModelStorage
 from rasa.engine.graph import ExecutionContext

node_storage = LocalModelStorage("tmp/storage")
 node_resource = Resource("tokenizer")
 context = ExecutionContext(node_storage, node_resource)

1.  Here I am using `.create()`
     tok_alphanum = AnotherWhitespaceTokenizer.create(
     config= {"only_alphanum": True} 

    , 
     model_storage=node_storage, 
     resource=node_resource,
     execution_context=context
     )

1.  Here I am using `.__init__()`
     tok_no_alphanum = AnotherWhitespaceTokenizer( {"only_alphanum": False} 

    )</pre>

When I try to run this test file, I get the following error:

 Traceback (most recent call last):
 File "components/test_tok.py", line 14, in <module>
 execution_context=context
 File "/home/vincent/Development/rasa-examples/rasa-ini/components/nlu_tok.py", line 53, in create
 return cls(config)
 File "/home/vincent/Development/rasa-examples/rasa-ini/components/nlu_tok.py", line 37, in __init__
 super().__init__(config)
 File "/home/vincent/Development/rasa-examples/venv/lib/python3.7/site-packages/rasa/nlu/tokenizers/tokenizer.py", line 97, in __init__
 self.intent_tokenization_flag = config<span class="error">["intent_tokenization_flag"]</span>
 KeyError: 'intent_tokenization_flag'

But that's strange! I've implemented `get_default_config()` on that class, so why aren't the default configs loaded in? This seems to break both when I use the new `.create()` method and when I use the `__init__()` method.

**Comment by m-vdb** [comment]
@joejuzl do you know if this issue was fixed in our QA pass?

**Comment by joejuzl** [comment]
This is not actually a bug, rather just a slightly strange design. To initialize components with default config you must do something like:
```
WhitespaceTokenizer(WhitespaceTokenizer.get_default_config())
```

This was initially decided because of how the graph serializes schemas and configs, but I do agree it is confusing, so might be worth changing. I think @ka-bu suggested this already too

**Comment by koaning** [comment]
@joejuzl so this is the correct usage?

```python
WhitespaceTokenizer.create(WhitespaceTokenizer.get_default_config())
```

**Comment by ka-bu** [comment]
>  I think @ka-bu suggested this already too

yes, I'd very much like to have a common __init__ for the graph component that takes care of defaults and configs :)  (and long term stuff like checks for unexpected params / types / .. ) -- since we're assuming that `get_default_config()` exist anyway and already pretty consistently use `config`/`componen_config` anyway

would also solve issue is here #10428 - wdyt @joejuzl ?
