### ISSUE TITLE
Re-evaluate bots from round 1.0 on real user conversations, including after bot failure

### ISSUE THREAD

**Issue by koernerfelicia** [RasaHQ/rasa#10007]
We should be able to use a similar script for this task as [this task](https://www.notion.so/rasa/E2E-Milestone-Meeting-4-0d6f845b54854343b33e1520cbf79ea8#b91c71725d89412680f3882c18e7353b) (running the 1.1 bots on the 60 conversations).

However, this script will need to insert a simple rephrase at points in the conversation where one of the bots broke. For example, if bot A broke on:
```
- USER: <rambling context that really just means I don't like this flight>
```
but bot B was able to handle this, and reached a later breaking user utterance, we would replace this "breaking utterance" with something bot A *can* handle, such that bot A can be tested on the later breaking user utterance.
```
- USER: I don't like this flight
```
This is similar to extending the "context story" (i.e., the part of the story the bot can handle) in order to be able to reach the later breaking utterances.

For each "breaking utterance", check if the next action was predicted correctly.  We can determine this based on the action predicted by the bot that held on for longer (B), until we reach the utterance that broke B, at which point we will need to determine by manual inspection/labeling whether A predicted the correct action for this particular utterance. We repeat this process for every utterance past the end of the context story, using a simpler utterance where one of the bots breaks down.

If bot A broke after the first turn, but bot B managed 4 turns before breaking down, bot B would have `4/5` correct predictions and bot A would have `?/5` where `?` is at most `4`.

**Definition of Done**
- [x] All conversations from round 1.0 have been fixed with the correct bot action
- [x] Figure out how to run the fixed conversation on the required bot (the one which broke down earlier in the conversation)
- [x] We have metrics for each utterance past the context story on whether the bots were able to successfully predict the next action correctly
- [x] Create a similar plot as [this](https://www.notion.so/rasa/Abstract-Round-1-A-B-Testing-543e05729ad6462199111af2df80bed8#c895c01fa49f4bd9b58bacbf6027b740) showing in which turns does the bot break.
- [x] Feed this information to https://github.com/RasaHQ/research/issues/239

Items Remaining:

- [x] Extract numbers on fallback analysis (0.5 day)
- [x] Extract numbers on "How many alternative user messages can each bot handle?" (1 day)
- [x] Summarize the learnings on the possible disadvantages of the current A/B test workflow from the above experiments. (1 day)

Total remaining time: 2.5 days

**Comment by JEM-Mosig** [comment]
Based on the replay analysis:
* The intent and e2e bots would each have been able to continue the conversation using rephrases that they didn't ask for in 5 cases and in 1 case, respectively
* The 5 continuations of the intent bot
    * never lead to a successful booking
    * increased the conversation lengths by [2, 2, 3, 5, 1] user-and-bot-turn steps (squares in the Figure)
    * If we count the survival time from the beginning of the conversation (for simplicity), the survival time increases from 4.4 to 4.6 steps
* The 1 continuation of the e2e bot 
    * lead to another ask-rephrase at the end of the replayed story - we don't know if the conversation would have been successful
    * increased the conversation length by 2 user-and-bot-turn steps
    * If we count the survival time from the beginning of the conversation (for simplicity), the survival time increases from 5.40 to 5.43 steps

Conclusion: The rephrase requests where an advantage for the intent bot, but e2e bot is clearly better even when this is taken into account.

**Comment by JEM-Mosig** [comment]
Here is the Figure again - for completeness.

[comparison_with_replay.pdf](https://github.com/RasaHQ/rasa/files/7506841/comparison_with_replay.pdf)
