### ISSUE TITLE
Make sure the coverage of stories from E2E bot is transferred over to the baseline bot

### ISSUE THREAD

**Issue by koernerfelicia** [RasaHQ/rasa#10005]
During analysis of round 1.0, we developed the hypothesis that Daksh's E2E bot may have had better coverage of happy paths (possibly due to the use of checkpoints). Before we begin round 1.1, we should transfer this coverage to the baseline bot, such that both bots developed in 1.1 have coverage of these stories as their starting point.

Note that this *does not* mean we are adding E2E data to the baseline bot, but rather extending the intent-based stories or using checkpoints in a similar fashion to the 1.0 E2E bot.

**Definition of Done**
- [ ] The baseline bot's training data is extended in such a way that the flows covered by Daksh's E2E bot are also covered in the baseline bot

**Comment by dakshvar22** [comment]
@dakshvar22 assigned as reviewer
