### ISSUE TITLE
Python SDK API dcumentation? 

### ISSUE THREAD

**Issue by solyarisoftware** [RasaHQ/rasa#10015]
### What problem are you trying to solve?

Hi,

I would like to use RASA NLU (and RASA Dialog Manager) through direct Python methods, avoiding to pass through HTTP servers, because I want to embed the RASA intent/entities classifier in my NLP standalone backend application (not a chatbot).

Incidentally I found two articles that explain how to do. The first one is by the great Vincent Warmerdam:

* [https://rasa.com/blog/evaluating-rasa-nlu-models-in-jupyter/](https://rasa.com/blog/evaluating-rasa-nlu-models-in-jupyter/) 
* [https://www.machinelearningplus.com/nlp/chatbot-with-rasa-and-spacy/](https://www.machinelearningplus.com/nlp/chatbot-with-rasa-and-spacy/)

So I already answered my specific problem, but my question is still: are

*   `rasa.*`
*   `rasa.nlu.*`
*   `rasa_core.*`

python modules documented somewhere? I didn't find anything in official web docs ([https://rasa.com/docs/rasa/](https://rasa.com/docs/rasa/)). I'm wrong?

> Minor complain: BTW, the term **RASA SDK** used in RASA docs, refers to the action (server) application custom functions (`rasa_sdk.*`, see: [https://rasa.com/docs/action-server/sdk-actions](https://rasa.com/docs/action-server/sdk-actions)).
 > 
 > I in my humble opinion is a misleading name. I'd call it in different name... maybe `action_sdk.**` I'd rather call *RASA Python SDK** the python modules set to and **RASA (Python) Actions SDK** the subset of method to be used in action development. ![](/images/icons/emoticons/smile.png)

Thanks

giorgio

**Comment by sara-tagger** [comment]
Thanks for submitting this feature request 🚀 @desmarchris will get back to you about it soon! ✨

**Comment by lucalazzaroni** [comment]
Hi, same issue here, did you manage to find a way to use rasa via Python APIs @solyarisoftware ?

**Comment by solyarisoftware** [comment]
Hi @lucalazzaroni, 

I partially solved, using examples in links I shared, 
but for me the general point is still open.

@desmarchris, someone else?

Thanks

**Comment by lucalazzaroni** [comment]
Hi @solyarisoftware and thank you for the answer and the links, would it be possible for you to also share the code you wrote? Otherwise no problem :)

**Comment by m-vdb** [comment]
At the moment we currently offer a documentation that is generated from the Python codebase. It's available [here](https://rasa.com/docs/rasa/reference/rasa/__main__). But we do not have plans to extend this documentation to something more "consumable".
