### ISSUE TITLE
`pip` installation can take 3+ hours

### ISSUE THREAD

**Issue by koaning** [RasaHQ/rasa#10050]
During today's open-source meeting we discussed that some users are having issues with pip. It seems to take 3+ hours in some cases. I've also noticed that installing the main branch also takes a very long time. It might be related.

I've made an issue so we don't forget to track it. @alopez keeping you in the loop.

**Comment by alopez** [comment]
@koaning I think there was an example from the forum? Can you link to it?
@TyDunn I think this either gets routed to Enable or Infra, but I'm not sure.

**Comment by koaning** [comment]
It seems to have been comments from Youtube that led to that number. To quote community pulse of Oct 25th:

- "I had the problem is when i type "pip install rasa" and it waiting for a long time. I wait for 20-30min and it keep stucking and I not sure is it processing or already failure”
- "I wasted my time and resources to install it as prescribed in video ...simply it didn't worked .It has lots of bugs . Got frustrated after 3.5 hours. Utilizing it one thing and running it another but if you could not install it how you can use it . Dammm..."

I couldn't find the links to the videos in question. @rctatman may know more but she's offline this week.

**Comment by rctatman** [comment]
The comments are on this video: https://www.youtube.com/watch?v=GlR60CvTh8A

Based on a discussion with @koernerfelicia it sounds like this might possibly be fixed by this commit pinning the pip version to 21: https://github.com/RasaHQ/rasa/commit/7aa48106f03be3624da316f63964460a560b92c4

**Comment by rgstephens** [comment]
I wonder if these could be pip cache related. I was working with someone last week that ran into a long install due to pip cache resolution issues. Creating a new conda environment resolved the issue.

**Comment by koaning** [comment]
I'm able to confirm that `--use-deprecated=legacy-resolver` hasn't worked for me on the main branch last week.
