### ISSUE TITLE
Documenting "the attribute stuff" for NLU components.

### ISSUE THREAD

**Issue by koaning** [RasaHQ/rasa#10051]
While working on custom components today I was reminded of an aspect that deserves documentation. So I figured mentioning it here. When you look in the Rasa NLU codebase you'll see a lot of this:

<pre>#. This is an example method from the countvectorizer 

    def _get_processed_message_tokens_by_attribute(
        self, message: Message, attribute: Text = TEXT
    ) -&gt; List[Text]:
        """Get processed text of attribute of a message"""

        if message.get(attribute) is None:
            # return empty list since sklearn countvectorizer does not like None
            # object while training and predicting
            return []

        tokens = self._get_message_tokens_by_attribute(message, attribute)
        tokens = self._process_tokens(tokens, attribute)
        tokens = self._replace_with_oov_token(tokens, attribute)

        return tokens</pre>

Lot's and lots of "attribute stuff". My impression is that this exists so that we may generate features for text, tokens, and response-selector separately. Also to my understanding, this hasn't ever really been documented anywhere. Might it be good to mention on our docs?

It's a bit of an advanced use-case perhaps, but then again, the community would look for source code examples to copy and get very confused by this. I'm also open to writing a blogpost to serve as a guide but I'd prefer to collaborate with somebody to make sure I explain it correctly.

**Comment by ka-bu** [comment]
Some of our notion pages related to that:
- [featurizers](https://www.notion.so/rasa/Featurizers-3de084fb437f4127814fe7f8f0a20fcc) treat attributes quite differently
- [tokenizers](https://www.notion.so/rasa/Tokenizers-c879724817d14791a122bcf90bed9056) all tokenize attributes the same way
- [messages](https://www.notion.so/rasa/Message-b02dba45103d4d6babeaf4c4f1a8d25e) holds all these attributes
