### ISSUE TITLE
Set up sentry alert for new major

### ISSUE THREAD

**Issue by wochinge** [RasaHQ/rasa#10068]
### Rasa Open Source version

3.0.0

### Rasa SDK version

3.0.0

### What happened?

Rasa Open Source 3.0 is introducing a lot of changes. Despite having these QA'ed extensively we should be extra alert for anything happening on Sentry to catch errors early on and to avoid that too many users are impacted by it and lose trust.

### Definition of Done
- [x] Determine threshold for impacted users
- [x] Sentry alert is set up which targets the 3.0 minor and sends an alert to #enable-squad-alerts as soon as x users are impacted by an issue

**Comment by m-vdb** [comment]
cc @joejuzl since you're captaining 3.0, probably a good idea to do this issue directly after releasing?
