### ISSUE TITLE
convert from dialogflow to yaml is the default option but fails

### ISSUE THREAD

**Issue by simonm3** [RasaHQ/rasa#10072]
### Rasa Open Source version

2.8

### Rasa SDK version

 _No response_ 

### Rasa X version

 _No response_ 

### Python version

3.8

### What operating system are you using?

Linux

### What happened?

Converting from dialogflow json format does not work

rasa data convert has default option yaml (as it now should be). However this does not work and just skips all the files. Can set the format to markdown which works except this format is deprecated so does not make sense to use that.

### Command / Request

 _No response_ 

### Relevant log output

 _No response_

**Comment by sara-tagger** [comment]
Thanks for raising this issue, @TyDunn will get back to you about it soon✨

###### Please also check out the [docs](https://rasa.com/docs/) and the [forum](https://forum.rasa.com/) in case your issue was raised there too 🤗
