### ISSUE TITLE
Add a "Cron on Dependencies" workflow. 

### ISSUE THREAD

**Issue by koaning** [RasaHQ/rasa#10082]
### What problem are you trying to solve?

There may be merit to adding a ["Cron on Dependencies" workflow](https://koaning.io/posts/cool-commits/#cron-on-dependencies).

A user for scikit-lego, a package that I maintain, discovered that the reason the code wasn’t working was that scikit-learn introduced a minor, but breaking, change. It was incredibly tricky to fix because we had to search our dependencies to figure out what broke where. It'd have been a lot better if we knew the date when something broke. That way, the rabbit hole is a lot shorter.

The same user made a great contribution to the library by adding a "cron-workflow". Before the PR, we had to hear from users when a dependency introduced breaking changes. By adding a cron job that would install the most recent packages via `pip` we were able to run our unit tests daily. This removed a blind spot from the project. Every day we now run the unit tests using the latest versions of our dependencies. If the tests break, we can quickly pinpoint what package caused it and create a fix.

I think this may also be a great idea for Rasa. If nothing else it may give us a bit of data on installation mishaps as well as data on installation times, which is [a problem at the time of writing this issue](https://github.com/RasaHQ/rasa/issues/10050).

### What's your suggested solution?

I would add a workflow that runs daily. It should install the most recent version of Rasa from pip and try to run the tests.

### Examples (if relevant)

Here's the workflow from [scikit-lego](https://github.com/koaning/scikit-lego/blob/main/.github/workflows/schedule-dependencies.yml).

### Is anything blocking this from being implemented? (if relevant)

 _No response_ 

### Definition of Done

 _No response_

**Comment by koaning** [comment]
@wochinge @joejuzl I'd be especially curious what your thoughts are on this idea.

**Comment by wochinge** [comment]
Was the breaking change in a minor or micro? An alternative might be to be more defensive about dependency ranges and always limit upper range to the currently tested minor 🤔 

I also like your proposal - just wondering if it's rather fixing symptoms 🤔

**Comment by koaning** [comment]
> An alternative might be to be more defensive about dependency ranges and always limit upper range to the currently tested minor 🤔

That could work. The way I experience this feature is that it's like a smoke test. It will tell you that "something is up". Actually fixing the dependency issue will remain an ongoing issue.

Technically ... we could even choose to add such a dependency in a separate repository if we're afraid of overpopulating this one. I might have some time to work on this one after this week by the way. Shall I make a proposal PR?

**Comment by koaning** [comment]
Funny anekdote. This is the scikit-lego repo this morning: 

![image](https://user-images.githubusercontent.com/1019791/144014753-2a7abea6-2db7-4a7d-b2d5-48e6080912fd.png)

It seems as of today something broke on Windows. 

![image](https://user-images.githubusercontent.com/1019791/144014889-a1957f15-a870-4bf7-8b21-ae019614d8e7.png)

Scikit-Lego isn't as big as Rasa, but it's really great that I know now what broke today because the rabbit hole is a lot shorter.
