### ISSUE TITLE
Get access to the output channel in the tracker in the action server

### ISSUE THREAD

**Issue by nbeuchat** [RasaHQ/rasa#10100]
### What problem are you trying to solve?

Currently, it is possible to get the latest input channel in the action server using `tracker.get_latest_input_channel`. Although this works well for most cases to know which channel the user is using in the conversation, it fails when starting a conversation ourselves using an externally triggered intent where we specify the output channel. In this case, the action server gets `None` as the input channel. Therefore, we cannot correctly change the action behavior depending on the channel.

### What's your suggested solution?

Provide access to the next output channel either as:

*   a field in the `metadata` of the latest message
*   a separate field in the tracker to store the next output channel and a method `get_next_output_channel`

### Examples (if relevant)

 _No response_ 

### Is anything blocking this from being implemented? (if relevant)

 _No response_ 

### Definition of Done

*   output channel name is available in the Tracker within the action server
*   this should work when starting a conversation using an externally triggered intent with a specified output channel

**Comment by sara-tagger** [comment]
Thanks for submitting this feature request 🚀 @koaning will get back to you about it soon! ✨
