### ISSUE TITLE
Rasa CLI help does not have description

### ISSUE THREAD

**Issue by tayfun** [RasaHQ/rasa#10103]
### What problem are you trying to solve?

Rasa CLI subcommands with `--help` does not print descriptions of command; it only prints arguments.

eg.

 $ rasa run -h
 usage: rasa run <span class="error">[-h]</span> <span class="error">[-v]</span> <span class="error">[-vv]</span> <span class="error">[--quiet]</span> <span class="error">[-m MODEL]</span> <span class="error">[--log-file LOG_FILE]</span> <span class="error">[--use-syslog]</span> <span class="error">[--syslog-address SYSLOG_ADDRESS]</span> <span class="error">[--syslog-port SYSLOG_PORT]</span> <span class="error">[--syslog-protocol SYSLOG_PROTOCOL]</span>
 <span class="error">[--endpoints ENDPOINTS]</span> <span class="error">[-i INTERFACE]</span> <span class="error">[-p PORT]</span> <span class="error">[-t AUTH_TOKEN]</span> [--cors [CORS <span class="error">[CORS ...]</span>]] <span class="error">[--enable-api]</span> <span class="error">[--response-timeout RESPONSE_TIMEOUT]</span> <span class="error">[--remote-storage REMOTE_STORAGE]</span>
 <span class="error">[--ssl-certificate SSL_CERTIFICATE]</span> <span class="error">[--ssl-keyfile SSL_KEYFILE]</span> <span class="error">[--ssl-ca-file SSL_CA_FILE]</span> <span class="error">[--ssl-password SSL_PASSWORD]</span> <span class="error">[--credentials CREDENTIALS]</span> <span class="error">[--connector CONNECTOR]</span>
 <span class="error">[--jwt-secret JWT_SECRET]</span> <span class="error">[--jwt-method JWT_METHOD]</span>

 {actions} ... <span class="error">[model-as-positional-argument]</span>

 positional arguments:

 {actions} 

 actions Runs the action server.
 model-as-positional-argument
 Path to a trained Rasa model. If a directory is specified, it will use the latest model in this directory. (default: None)

 optional arguments:
 -h, --help show this help message and exit
 -m MODEL, --model MODEL
 Path to a trained Rasa model. If a directory is specified, it will use the latest model in this directory. (default: models)
 --log-file LOG_FILE Store logs in specified file. (default: None)
 --use-syslog Add syslog as a log handler (default: False)
 --syslog-address SYSLOG_ADDRESS
 Address of the syslog server. --use-sylog flag is required (default: localhost)
 --syslog-port SYSLOG_PORT
 Port of the syslog server. --use-sylog flag is required (default: 514)
 --syslog-protocol SYSLOG_PROTOCOL
 Protocol used with the syslog server. Can be UDP (default) or TCP (default: UDP)
 --endpoints ENDPOINTS
 Configuration file for the model server and the connectors as a yml file. (default: endpoints.yml)

 Python Logging Options:
 -v, --verbose Be verbose. Sets logging level to INFO. (default: None)
 -vv, --debug Print lots of debugging statements. Sets logging level to DEBUG. (default: None)
 --quiet Be quiet! Sets logging level to WARNING. (default: None)

 Server Settings:
 -i INTERFACE, --interface INTERFACE
 Network interface to run the server on. (default: 0.0.0.0)
 -p PORT, --port PORT Port to run the server at. (default: 5005)
 -t AUTH_TOKEN, --auth-token AUTH_TOKEN
 Enable token based authentication. Requests need to provide the token to be accepted. (default: None)
 --cors [CORS <span class="error">[CORS ...]</span>]
 Enable CORS for the passed origin. Use * to whitelist all origins. (default: None)
 --enable-api Start the web server API in addition to the input channel. (default: False)
 --response-timeout RESPONSE_TIMEOUT
 Maximum time a response can take to process (sec). (default: 3600)
 --remote-storage REMOTE_STORAGE
 Set the remote location where your Rasa model is stored, e.g. on AWS. (default: None)
 --ssl-certificate SSL_CERTIFICATE
 Set the SSL Certificate to create a TLS secured server. (default: None)
 --ssl-keyfile SSL_KEYFILE
 Set the SSL Keyfile to create a TLS secured server. (default: None)
 --ssl-ca-file SSL_CA_FILE
 If your SSL certificate needs to be verified, you can specify the CA file using this parameter. (default: None)
 --ssl-password SSL_PASSWORD
 If your ssl-keyfile is protected by a password, you can specify it using this paramer. (default: None)

 Channels:
 --credentials CREDENTIALS
 Authentication credentials for the connector as a yml file. (default: None)
 --connector CONNECTOR
 Service to connect to. (default: None)

 JWT Authentication:
 --jwt-secret JWT_SECRET
 Public key for asymmetric JWT methods or shared secretfor symmetric methods. Please also make sure to use --jwt-method to select the method of the signature, otherwise this
 argument will be ignored.Note that this key is meant for securing the HTTP API. (default: None)
 --jwt-method JWT_METHOD
 Method used for the signature of the JWT authentication payload. (default: HS256)

There's nothing above which describes the command in prose.

### What's your suggested solution?

The problem is subparsers are added with argument `help` and not `description` in code. [Parsers should use `description` while arguments should use `help` I think.](https://docs.python.org/3/library/argparse.html)

 $ git diff
 diff --git a/rasa/cli/run.py b/rasa/cli/run.py
 index c83f1756856..76f77994bc0 100644
 — a/rasa/cli/run.py
 +++ b/rasa/cli/run.py
 @@ -33,7 +33,7 @@ def add_subparser(
 parents=parents,
 conflict_handler="resolve",
 formatter_class=argparse.ArgumentDefaultsHelpFormatter,

*   help="Starts a Rasa server with your trained model.",
     + description="Starts a Rasa server with your trained model.",
     )
     run_parser.set_defaults(func=run)

Without description:

 $ rasa run --help
 usage: rasa run <span class="error">[-h]</span> <span class="error">[-v]</span> <span class="error">[-vv]</span> <span class="error">[--quiet]</span> ...

 positional arguments:
 ...

With description:

 $ rasa run -h
 usage: rasa run <span class="error">[-h]</span> <span class="error">[-v]</span> <span class="error">[-vv]</span> <span class="error">[--quiet]</span> ...

 Starts a Rasa server with your trained model.

 positional arguments:
 ...

### Examples (if relevant)

 _No response_ 

### Is anything blocking this from being implemented? (if relevant)

 _No response_ 

### Definition of Done

*   [ ] Rasa CLI describes commands when run with `-h` argument

**Comment by koaning** [comment]
I've noticed this too today, it seems you beat me to it.

**Comment by gauravgandhi1315** [comment]
I noticed it today as well :)
