### ISSUE TITLE
2.X -> 3.0 QA: Loading a 2.X model with 3.0 produces an unexpected file not found error.

### ISSUE THREAD

**Issue by usc-m** [RasaHQ/rasa#10108]
Creating a model with rasa 2.8.X using `rasa init`, training it, and then attempting to load it with `rasa shell` after switching to a rasa 3.0 produces a file not found error:

`FileNotFoundException: Failed to read file, '/var/folders/4x/yjfd_jb15c55fy63yj53cjgm0000gn/T/tmphdo98uql/metadata.json' does not exist.`

**Steps to Reproduce**
1. Create a virtual environment and install rasa 2.8
2. Create another virtual environment and install rasa 3.0rc1
3. Using the rasa 2.8 venv, create a new project and train it
4. Using the rasa 3.0rc1 venv, attempt to run `rasa shell` on the project

**Comment by wochinge** [comment]
@ka-bu This issue covers the transition from 2.x to 3.x. However, we in general should check a models `MINIMUM_COMPATIBLE_VERSION` against the currently used Rasa Open Source version when loading a Rasa model. E.g. if the minimum compatible version is 3.1 and you try to load a 3.x model we should refuse loading this model. Basically implementing [this](https://github.com/RasaHQ/rasa/blob/427fd328d48b0adfe8b45a21c4ae390650aaf69f/rasa/nlu/model.py#L300) and [this](https://github.com/RasaHQ/rasa/blob/427fd328d48b0adfe8b45a21c4ae390650aaf69f/rasa/nlu/model.py#L292) for the new model architecture. A good place for this check would be [here](https://github.com/RasaHQ/rasa/blob/d143d702f0f1b710a2482aff1256b45017ed9f0a/rasa/engine/storage/local_model_storage.py#L44) or in anything calling this
