### ISSUE TITLE
Global Slot Mappings: Wrong warning for overriding custom slot mapping

### ISSUE THREAD

**Issue by wochinge** [RasaHQ/rasa#10116]
### Rasa Open Source version

3.0.0rc1

### Rasa SDK version

3.0.0rc1

### Python version

3.9

### What operating system are you using?

OSX

### What happened?

When using the `FormValidationAction` with a mapping of type 'custom' (see full warning on the inside) the SDK prints the warning below. It shouldn't as this is expected. Relevant code [here](https://github.com/RasaHQ/rasa-sdk/blob/1daa3f4a8c366b82b75e9e67313ac5e041080a1f/rasa_sdk/forms.py#L234)

```
UserWarning: Slot 'slot1' is mapped in the domain and your custom action defines 'extract_slot1'. 'extract_slot1' will override any extractions of the predefined slot mapping from the domain. It is suggested to define a slot mapping in only one of the two ways for clarity.
```

**Comment by ancalita** [comment]
@wochinge  or @alwx 
Does it make sense to either:
a) change the warning message and if statement so that all custom slots are defined in the domain, for example:
```
if extract_method and not slot_in_domain:
            warnings.warn(
                f"Slot '{slot_name}' is not mapped in the domain and your custom "
                f"action defines '{method_name}'. You must define a custom slot mapping "
                f"for slot '{slot_name}' in the domain. Please see the [docs](add link) for more information."
            )
```
b) remove the warning and if statement entirely, and don't replace with another warning?

**Comment by ancalita** [comment]
@alwx Tagged you as reviewer - in the end went with option b). I don't deem the new warning vital and could potentially cause headaches for those migrating from 2.x used to the 2.x instruction to not add the custom slot mappings defined in `FormValidationAction` in the domain 😅 WDYT?

**Comment by ancalita** [comment]
Closed via https://github.com/RasaHQ/rasa-sdk/pull/598
