### ISSUE TITLE
`--augmentation` parameter overwritten with default value

### ISSUE THREAD

**Issue by koernerfelicia** [RasaHQ/rasa#10132]
### Rasa Open Source version

3.0.0rc1

### Python version

3.8

### What operating system are you using?

OSX

### What happened?

The `--augmentation` parameter is not making it into the `TrainingDataGenerator` component but instead seems to be overwritten with the default value.

Here in `model_training.py` it is correctly passed to `train`:
<img width="1104" alt="Screenshot 2021-11-10 at 09 47 10" src="https://user-images.githubusercontent.com/45405119/141081341-11c8c8f2-2b7e-48f1-956a-35881f0a5fec.png">

Here in `TrainingTrackerProvider.provide` it has been overwritten with the default value of 50:
<img width="823" alt="Screenshot 2021-11-10 at 09 50 00" src="https://user-images.githubusercontent.com/45405119/141081314-f50581f5-d55b-419b-8029-59ea575c4a6c.png">

### Command / Request

```shell
rasa train --augmentation 200
```

**Comment by wochinge** [comment]
@joejuzl easy fix but needs to be done

**Comment by koernerfelicia** [comment]
Woah, so quick! Was just typing a message about this 😅

**Comment by koernerfelicia** [comment]
Should note I didn't try this out for any different parameters, it was just a coincidence I found it. Wanted to write a test to demonstrate but couldn't quite wrap my head around how to do it so figured screenshots would be quicker
