### ISSUE TITLE
API QA: `/status` endpoint returns a response body that's not consistent with the docs

### ISSUE THREAD

**Issue by ancalita** [RasaHQ/rasa#10130]
**Description of the problem**:
Sending a GET request to `/status` endpoint results in this response body that doesn't match the [docs](https://rasa.com/docs/rasa/pages/http-api#operation/getStatus):
```
{
    "model_file": "models",
    "fingerprint": "5e0a7a1433b84d53843518203cef922c",
    "num_active_training_jobs": 0
}
```
- Used a rasa init project for this test case.

**Comment by carlad** [comment]
Which is the source of truth? Should the docs be updated, or the endpoint response payload?

**Comment by ancalita** [comment]
@joejuzl Please see question ⏫  from @carlad

**Comment by joejuzl** [comment]
> Which is the source of truth? Should the docs be updated, or the endpoint response payload?

Good question - both need to be updated somewhat.

- "fingerprint" should now be called "model_id". The value is correct but the key needs to change, and the docs.
- "model_file" should return the model file name, not the directory name.

**Comment by carlad** [comment]
@ joejuzl, re:
> "model_file" should return the model file name, not the directory name.

At the moment the endpoint sets the `model_file` from the `Agent` class `model_name", however the `Agent.model_name` is the `model_path.name`, which I'm guessing is the name of the directory. Should the `Agent` class be updated?
```
@property
    def model_name(self) -> Optional[Text]:
        """Returns the model name from processor's model_path."""
        return self.processor.model_path.name if self.processor else None
```

**Comment by joejuzl** [comment]
We get the `model_tar` (which is the correct name) in `Processor._load_model`. So although it's a little annoying I think we just need to store it on the processor so we can access it later from the `Agent`.

**Comment by carlad** [comment]
So I'm not sure what I was looking at in my previous comment but after poking around with pdb while running `test_server.py` tests, it `app.agent.model_name` does actually return the name of the file in the test. @ancalita when you test this test case, do you have any models in the model directory or is it empty?

**Comment by ancalita** [comment]
@carlad Yup I tested the API endpoints on bot projects that I trained first so all had a model archive file in the models dir.

**Comment by carlad** [comment]
@ancalita a fix is merged now, so let me know if the issue persists.

**Comment by ancalita** [comment]
@carlad I think the only thing required is to mark it as fixed in the QA plan for architecture revamp, and then we'll see if this shows up when the 2nd QA pass is carried by the rest of the team.
