### ISSUE TITLE
Verify that Rasa OSS github project doesn't list py3.6 when 3.0 is out on pypi

### ISSUE THREAD

**Issue by joejuzl** [RasaHQ/rasa#10138]
We dropped support for py36 so we shouldn't have it in the repo badge.

<img width="850" alt="Screenshot 2021-11-10 at 10 20 58" src="https://user-images.githubusercontent.com/1702538/141086016-558fadcf-3ad8-486b-a99e-b0467f02d55f.png">

However it may be the case that we can't change this because of old release branches - so needs to be looked into.

**Comment by m-vdb** [comment]
@joejuzl as far as I can tell [the badge](https://github.com/RasaHQ/rasa/blame/main/README.md#L7) is going to be updated automatically when there is a newer version of `rasa` published on Pypi. I think the reason we're not seeing the badge updated right now is that the `3.0.0rc1` is a prerelease version, hence it's not treated as a stable latest version. **I will keep this ticket open, in the backlog for now and double check that it's updated when 3.0 is out.**

**Comment by TyDunn** [comment]
@m-vdb Is there anything we can do here? I don't see it updated on the GitHub repo

**Comment by m-vdb** [comment]
🤦🏻 apparently the Python 3.6 classifier was defined independently of the required python dependency.... I've put up a PR here: https://github.com/RasaHQ/rasa/pull/10405

**Comment by m-vdb** [comment]
<img width="844" alt="Screenshot 2021-12-03 at 16 19 34" src="https://user-images.githubusercontent.com/1931615/144627049-0e379b9c-4652-4aec-88ef-66e57e1a4d49.png">

It is fixed ✅  (will clean things up on the SDK though)
