### ISSUE TITLE
Warning when using custom slot mapping action

### ISSUE THREAD

**Issue by wochinge** [RasaHQ/rasa#10144]
### Rasa Open Source version

3.0.0rc1

### Python version

3.8

### What operating system are you using?

OSX

### What happened?

I ran into this warning when using a custom slot mapping action:

```python
2021-11-09 15:28:38 INFO     rasa.core.actions.action  - Running custom action 'action_validate_slot_mappings' has resulted in an event of type 'slot'. This is disallowed and the tracker will not be updated with this event.
```

I guess this happens because of the 

```
if (
    isinstance(event, SlotSet)
    # this triggers if the action extracted the same slot again
    and tracker.get_slot(event.key) != event.value
)
```

```python
class BetterConditionalResponseValidator(ValidationAction):

    async def extract_better(
        self,
        dispatcher: CollectingDispatcher,
        tracker: Tracker,
        domain: Dict[Text, Any],
    ) -> Dict[Text, Any]:

        return {"better": bool(len(tracker.events) % 2)}
```

**Comment by carlad** [comment]
@m-vdb What is the expected behaviour here?

**Comment by wochinge** [comment]
`slot` events are expected and shouldn't raise a warning. Means that this warning shouldn't appear when using custom slot mappings:

```
2021-11-09 15:28:38 INFO     rasa.core.actions.action  - Running custom action 'action_validate_slot_mappings' has resulted in an event of type 'slot'. This is disallowed and the tracker will not be updated with this event.
```

**Comment by ancalita** [comment]
@carlad @wochinge yup I just replicated myself (by testing something else) by creating a custom slot mapping that extracts the slot via a custom action extending sdk `Action` and then also using `ValidationAction` to write custom validation code for the extracted value. 

@carlad Let me know if you have any other questions otherwise happy to review the fix once ready 🙏🏼
