### ISSUE TITLE
Form actions stores duplicate entities as list in text slot

### ISSUE THREAD

**Issue by mleimeister** [RasaHQ/rasa#10188]
### Rasa Open Source version

2.8.12

### Rasa SDK version

 _No response_ 

### Rasa X version

 _No response_ 

### Python version

3.8

### What operating system are you using?

OSX

### What happened?

When using multiple entity extractors (e.g. `DIETClassifier` and `RegexEntityExtractor`) that can lead to entities being extracted twice. If the resulting entities are used to fill a slot of type `text` via a form action and duplicate entities got extracted, the slot gets filled with a list rather than a single element. This seems to contrast the [documentation](https://rasa.com/docs/rasa/components#entity-extractors) stating that the last entity extractor in the pipeline wins for `text` slots.

This behaviour has been reported before in the [forum](https://forum.rasa.com/t/slot-type-list-and-text/41187) for two distinct cases (list slot getting filled with single text element & text slot getting filled with list). The first case seems to have been addressed in this [PR](https://github.com/RasaHQ/rasa/pull/8675/files), but the second one still seems to happen.

Example bot leading to the issue:

config.yml

recipe: default.v1

1.  Configuration for Rasa NLU.
2.  [https://rasa.com/docs/rasa/nlu/components/](https://rasa.com/docs/rasa/nlu/components/) language: en

pipeline:

1.  # No configuration for the NLU pipeline was provided. The following default pipeline was used to train your model.

1.  # If you'd like to customize it, uncomment and adjust the pipeline.

1.  # See [https://rasa.com/docs/rasa/tuning-your-model](https://rasa.com/docs/rasa/tuning-your-model) for more information.

*   name: WhitespaceTokenizer
*   name: RegexFeaturizer
*   name: LexicalSyntacticFeaturizer
*   name: CountVectorsFeaturizer
*   name: CountVectorsFeaturizer analyzer: char_wb min_ngram: 1 max_ngram: 4
*   name: LanguageModelFeaturizer model_name: "distilbert" model_weights: "distilbert-base-multilingual-cased"
*   name: DIETClassifier entity_recognition: true epochs: 100
*   name: RegexEntityExtractor use_lookup_tables: true
*   name: FallbackClassifier threshold: 0.3 ambiguity_threshold: 0.1

1.  Configuration for Rasa Core.
2.  [https://rasa.com/docs/rasa/core/policies/](https://rasa.com/docs/rasa/core/policies/) policies:
3.  # No configuration for policies was provided. The following default policies were used to train your model.

1.  # If you'd like to customize them, uncomment and adjust the policies.

1.  # See [https://rasa.com/docs/rasa/policies](https://rasa.com/docs/rasa/policies) for more information.

1.  * name: MemoizationPolicy
2.  * name: RulePolicy
3.  * name: UnexpecTEDIntentPolicy
4.  max_history: 5
5.  epochs: 100
6.  * name: TEDPolicy
7.  max_history: 5
8.  epochs: 100
9.  constrain_similarities: true

domain.yml

version: "2.0"

forms: location_form: required_slots: location:

*   type: from_entity entity: location

slots: location: type: text influence_conversation: true

entities:

*   location

intents:

*   greet
*   goodbye
*   inform_location

responses: utter_goodbye:

*   text: "Goodbye"
*   text: "Have a good day!"

utter_ask_location:

*   text: "Hello. What is your location?"

utter_return_location:

*   text: "Ok, so you live in {location}

, correct?"

session_config: session_expiration_time: 60 carry_over_slots_to_new_session: true

rules.yml

version: "2.0"

rules:

*   rule: Say goodbye anytime the user says goodbye steps:

*   intent: goodbye

*   action: utter_goodbye

*   rule: Activate location form if user greets steps:

*   intent: greet

*   action: location_form

*   active_loop: location_form

*   rule: Confirm the location condition:

*   active_loop: location_form steps:

*   action: location_form

*   active_loop: null

*   slot_was_set:

*   requested_slot: null

*   action: utter_return_location

nlu.yml

version: "2.0"

nlu:

*   intent: greet examples: |

*   hey

*   hello

*   hi

*   hello there

*   good morning

*   good evening

*   moin

*   hey there

*   let's go

*   hey dude

*   goodmorning

*   goodevening

*   good afternoon

*   intent: goodbye examples: |

*   cu

*   good by

*   cee you later

*   good night

*   bye

*   goodbye

*   have a nice day

*   see you around

*   bye bye

*   see you later

*   intent: inform_location examples: |

*   I'm in <span class="error">[Berlin]</span>(location).

*   I live in <span class="error">[Potsdam]</span>(location).

*   I'm based in <span class="error">[Hamburg]</span>(location).

*   I live in <span class="error">[Frankfurt]</span>(location).

*   I live in <span class="error">[Bielefeld]</span>(location).

*   I live in <span class="error">[Nürnberg]</span>(location).

*   I'm here in <span class="error">[Munich]</span>(location).

*   I'm based in <span class="error">[Bremen]</span>(location).

*   I'm working from <span class="error">[Leipzig]</span>(location).

*   lookup: location examples: |

*   Berlin

*   Potsdam

*   Hamburg

stories.yml

version: "2.0"

stories:

*   story: happy path steps:
*   intent: greet
*   action: location_form
*   slot_was_set:
*   location: true
*   action: utter_return_location
*   intent: goodbye
*   action: utter_goodbye

### Command / Request

<pre>Bot loaded. Visualisation at [http://localhost:5006/visualization.html](http://localhost:5006/visualization.html)([http://localhost:5006/visualization.html](http://localhost:5006/visualization.html)) .
 Type a message and press enter (press 'Ctrl-c' to exit).
 ? Your input -> hello 
 ? Your NLU model classified 'hello' with intent 'greet' and there are no entities, is this correct? Yes 
 ------
 Chat History

1\. Bot You
 ────────────────────────────────────────────
 1 action_listen 
 ────────────────────────────────────────────
 2 hello 
 intent: greet 1.00

Current slots: 
 location: None, requested_slot: None, session_started_metadata: None

------
 ? The bot wants to run 'location_form', correct? Yes 
 ------
 Chat History

1\. Bot You
 ───────────────────────────────────────────────────────────────────
 1 action_listen 
 ───────────────────────────────────────────────────────────────────
 2 hello 
 intent: greet 1.00 
 ───────────────────────────────────────────────────────────────────
 3 location_form 1.00 
 active_loop 

 {"name": "location_form"} 

 slot

 {"requested_slot": "location"} 

 Hello. What is your location? 

Current slots: 
 location: None, requested_slot: location, session_started_metadata: None

------
 ? The bot wants to run 'action_listen', correct? Yes 
 ? Your input -> I live in Berlin 
 /Users/matthias/.pyenv/versions/3.8.6/envs/rasa/lib/python3.8/site-packages/rasa/shared/utils/io.py:97: UserWarning: Parsing of message: 'I live in Berlin' lead to overlapping entities: Berlin of type location extracted by DIETClassifier overlaps with Berlin of type location extracted by RegexEntityExtractor. This can lead to unintended filling of slots. Please refer to the documentation section on entity extractors and entities getting extracted multiple times:[https://rasa.com/docs/rasa/components#entity-extractors](https://rasa.com/docs/rasa/components#entity-extractors)([https://rasa.com/docs/rasa/components#entity-extractors](https://rasa.com/docs/rasa/components#entity-extractors))
 ? Is the intent 'inform_location' correct for 'I live in <span class="error">[Berlin]</span>(location)<span class="error">[Berlin]</span>(location)' and are all entities labeled correctly? Yes 
 ------
 Chat History

1\. Bot You
 ───────────────────────────────────────────────────────────────────────────────────────────────
 1 action_listen 
 ───────────────────────────────────────────────────────────────────────────────────────────────
 2 hello 
 intent: greet 1.00 
 ───────────────────────────────────────────────────────────────────────────────────────────────
 3 location_form 1.00 
 active_loop 

 {"name": "location_form"} 

 slot

 {"requested_slot": "location"} 

 Hello. What is your location? 
 action_listen 1.00 
 ───────────────────────────────────────────────────────────────────────────────────────────────
 4 I live in <span class="error">[Berlin]</span>(location)<span class="error">[Berlin]</span>(location) 
 intent: inform_location 1.00 
 ───────────────────────────────────────────────────────────────────────────────────────────────
 5 slot

 {"location": "Berlin"} 

Current slots: 
 location: Berlin, requested_slot: location, session_started_metadata: None

------
 ? The bot wants to run 'location_form', correct? Yes 
 ------
 Chat History

1\. Bot You
 ─────────────────────────────────────────────────────────────────────
 1 action_listen 
 ─────────────────────────────────────────────────────────────────────
 2 hello 
 intent: greet 1.00 
 ─────────────────────────────────────────────────────────────────────
 3 location_form 1.00 
 active_loop 

 {"name": "location_form"} 

 slot

 {"requested_slot": "location"} 

 Hello. What is your location? 
 slot

 {"location": "Berlin"} 

 slot

 {"location": ["Berlin", "Berlin"]} 

 slot

 {"requested_slot": null} 

 active_loop

 {"name": null} 

Current slots: 
 location: <span class="error">['Berlin', 'Berlin']</span>, requested_slot: None, session_started_metadata: None

------
 ? The bot wants to run 'utter_return_location', correct? Yes 
 ------
 Chat History

1\. Bot You
 ────────────────────────────────────────────────────────────────────────────────
 1 action_listen 
 ────────────────────────────────────────────────────────────────────────────────
 2 hello 
 intent: greet 1.00 
 ────────────────────────────────────────────────────────────────────────────────
 3 location_form 1.00 
 active_loop 

 {"name": "location_form"} 

 slot

 {"requested_slot": "location"} 

 Hello. What is your location? 
 slot

 {"location": "Berlin"} 

 slot

 {"location": ["Berlin", "Berlin"]} 

 slot

 {"requested_slot": null} 

 active_loop

 {"name": null} 

 utter_return_location 1.00 
 Ok, so you live in <span class="error">['Berlin', 'Berlin']</span>, correct? 

Current slots: 
 location: <span class="error">['Berlin', 'Berlin']</span>, requested_slot: None, session_started_metadata: None

------
 ? The bot wants to run 'action_listen', correct? Yes 
 ? Your input -></pre>

### Relevant log output

 _No response_

**Comment by mleimeister** [comment]
Possible fix: a local fix that addressed the problem for me, and would be in line with the documentation, is to change the code in https://github.com/RasaHQ/rasa/blob/main/rasa/core/actions/forms.py#L199 to

```
if len(value) >= 1:
    return value[0]
```

so that only the first element of the list of entities gets stored in the slot.

**Comment by melindaloubser1** [comment]
I'd suggest returning the last entity found, rather than the first; this is because it matches the behaviour outside of a form, with a slot autofilled by an entity of the same name. In that case, the last entity is used to fill the slot. 

Re. the ordering: It returns  all entities from each extractor in order. E.g. given a pipeline including RegexEntityExtractor, DIETClassifier, and DucklingEntityExtractor (in that order), all of which are trained to extract the `number` entity, 
a sentence like
```
65 and 75
```

will give you back the entities as 
```
['65' (RegexEntityExtractor) , '75' (RegexEntityExtractor), '65' (DIETClassifier), '75'  (DIETClassifier), 65 (DucklingEntityExtractor), 75 (DucklingEntityExtractor)]
```
