### ISSUE TITLE
Performance assessment of slot mappings feature

### ISSUE THREAD

**Issue by ancalita** [RasaHQ/rasa#10185]
**Definition of Done**:
- [ ] benchmark performance effects of running the default action `action_extract_slots` after every user utterance to check if this adds any extra latency

**Comment by m-vdb** [comment]
TODO:
- check with Research to get access to a bot in production
- have a 2.8 and 3.0 version of the bot
- compare performances

Ideas:
- maybe some of the bots used in model regression tests have been updated?

**Comment by m-vdb** [comment]
@ka-bu  can you link to the Slack thread that details the outcome of this ticket and close it? thanks!

**Comment by ka-bu** [comment]
https://rasa-hq.slack.com/archives/C01HHMR4X8S/p1637598593404600
