### ISSUE TITLE
Investigate TensorFlow model loading time

### ISSUE THREAD

**Issue by wochinge** [RasaHQ/rasa#10194]
### Rasa Open Source version

3.0.0

### Rasa SDK version

 _No response_ 

### Rasa X version

 _No response_ 

### Python version

3.8

### What operating system are you using?

OSX

### What happened?

The `rasa init` bot takes around 20seconds to load (around 6 seconds per TED,DIET policy/component). Especially in production it's important that new models are loaded quickly and ready asap to avoid any downtime.

Additional Context: [https://rasa-hq.slack.com/archives/C8LEHMTAM/p1636723935291100](https://rasa-hq.slack.com/archives/C8LEHMTAM/p1636723935291100)

### Command / Request

<pre>`rasa run`</pre>

### Relevant log output

 _No response_

**Comment by koaning** [comment]
I'm running 3.0RC1 locally and confirm this is prohibitively slow. It'll make demos a huge pain. 

Running `rasa shell` takes 52 seconds on my intel ubuntu machine at the moment.
