### ISSUE TITLE
Make it optional to save unfeaturized slots in Interactive Learning

### ISSUE THREAD

**Issue by melindaloubser1** [RasaHQ/rasa#10200]
### What problem are you trying to solve?

Building stories with Interactive Learning without having to manually edit them afterwards. In any bot with a large number of unfeaturized slots, stories built with IL become unreadable very quickly; this is especially so with forms, which usually set several unfeaturized slots.

However, there is a valid use case for saving unfeaturized slots in test conversations, when e.g. you want to be able to test that changes to the featurization of a slot have not changed existing behaviour.

### What's your suggested solution?

Slots that are unfeaturized should be excluded by default from the story persisted by interactive learning. There can be a flag to enable saving unfeaturized slots.

### Examples (if relevant)

 _No response_ 

### Is anything blocking this from being implemented? (if relevant)

None known

### Definition of Done

*   [ ] Unfeaturized slots are not persisted during interactive learning by default
*   [ ] A flag enables saving unfeaturized slots
*   [ ] Documentation updated

**Comment by rgstephens** [comment]
Removing them is tedious and error prone.
