### ISSUE TITLE
Error in rasa init

### ISSUE THREAD

**Issue by salaxieb** [RasaHQ/rasa#10206]
### Rasa Open Source version

2.8.13 Minimum Compatible Version: 2.8.9

### Rasa SDK version

2.8.2

### Rasa X version

None

### Python version

3.7

### What operating system are you using?

OSX

### What happened?

Rasa Version : 2.8.13 Minimum Compatible Version: 2.8.9 Rasa SDK Version : 2.8.2 Rasa X Version : None Python Version : 3.7.9 Operating System : Darwin-19.6.0-x86_64-i386-64bit virtualenv: 20.10.0

can't init or train model

### Command / Request

<pre>rasa train</pre>

### Relevant log output

<pre>2021-11-15 13:02:22.898603: E tensorflow/core/lib/monitoring/collection_registry.cc:77] Cannot register 2 metrics with the same name: /tensorflow/api/keras/optimizers
 Traceback (most recent call last):
 File "/Users/u18881587/rasa/.venv/bin/rasa", line 8, in 

 sys.exit(main())
 File "/Users/u18881587/rasa/.venv/lib/python3.7/site-packages/rasa/__main__.py", line 118, in main
 cmdline_arguments.func(cmdline_arguments)
 File "/Users/u18881587/rasa/.venv/lib/python3.7/site-packages/rasa/cli/scaffold.py", line 235, in run
 init_project(args, path)
 File "/Users/u18881587/rasa/.venv/lib/python3.7/site-packages/rasa/cli/scaffold.py", line 130, in init_project
 print_train_or_instructions(args, path)
 File "/Users/u18881587/rasa/.venv/lib/python3.7/site-packages/rasa/cli/scaffold.py", line 69, in print_train_or_instructions
 training_result = rasa.train(domain, config, training_files, output)
 File "/Users/u18881587/rasa/.venv/lib/python3.7/site-packages/rasa/api.py", line 106, in train
 from rasa.model_training import train_async
 File "/Users/u18881587/rasa/.venv/lib/python3.7/site-packages/rasa/model_training.py", line 22, in 

 from rasa.nlu.model import Interpreter
 File "/Users/u18881587/rasa/.venv/lib/python3.7/site-packages/rasa/nlu/model.py", line 14, in 

 from rasa.nlu import components, utils
 File "/Users/u18881587/rasa/.venv/lib/python3.7/site-packages/rasa/nlu/components.py", line 7, in 

 import rasa.utils.train_utils
 File "/Users/u18881587/rasa/.venv/lib/python3.7/site-packages/rasa/utils/train_utils.py", line 39, in 

 from rasa.utils.tensorflow.callback import RasaTrainingLogger, RasaModelCheckpoint
 File "/Users/u18881587/rasa/.venv/lib/python3.7/site-packages/rasa/utils/tensorflow/callback.py", line 13, in 

 class RasaTrainingLogger(tf.keras.callbacks.Callback): File "/Users/u18881587/rasa/.venv/lib/python3.7/site-packages/tensorflow/python/util/lazy_loader.py", line 62, in __getattr__ module = self._load() File "/Users/u18881587/rasa/.venv/lib/python3.7/site-packages/tensorflow/python/util/lazy_loader.py", line 45, in _load module = importlib.import_module(self.__name__) File "/Users/u18881587/.pyenv/versions/3.7.9/lib/python3.7/importlib/__init__.py", line 127, in import_module return _bootstrap._gcd_import(name<span class="error">[level:]</span>, package, level) File "/Users/u18881587/rasa/.venv/lib/python3.7/site-packages/keras/__init__.py", line 25, in 

 from keras import models File "/Users/u18881587/rasa/.venv/lib/python3.7/site-packages/keras/models.py", line 20, in 

 from keras import metrics as metrics_module File "/Users/u18881587/rasa/.venv/lib/python3.7/site-packages/keras/metrics.py", line 26, in 

 from keras import activations File "/Users/u18881587/rasa/.venv/lib/python3.7/site-packages/keras/activations.py", line 20, in 

 from keras.layers import advanced_activations File "/Users/u18881587/rasa/.venv/lib/python3.7/site-packages/keras/layers/__init__.py", line 23, in 

 from keras.engine.input_layer import Input File "/Users/u18881587/rasa/.venv/lib/python3.7/site-packages/keras/engine/input_layer.py", line 21, in 

 from keras.engine import base_layer File "/Users/u18881587/rasa/.venv/lib/python3.7/site-packages/keras/engine/base_layer.py", line 43, in 

 from keras.mixed_precision import loss_scale_optimizer File "/Users/u18881587/rasa/.venv/lib/python3.7/site-packages/keras/mixed_precision/loss_scale_optimizer.py", line 18, in 

 from keras import optimizers File "/Users/u18881587/rasa/.venv/lib/python3.7/site-packages/keras/optimizers.py", line 26, in 

 from keras.optimizer_v2 import adadelta as adadelta_v2 File "/Users/u18881587/rasa/.venv/lib/python3.7/site-packages/keras/optimizer_v2/adadelta.py", line 22, in 

 from keras.optimizer_v2 import optimizer_v2 File "/Users/u18881587/rasa/.venv/lib/python3.7/site-packages/keras/optimizer_v2/optimizer_v2.py", line 37, in 

 "/tensorflow/api/keras/optimizers", "keras optimizer usage", "method") File "/Users/u18881587/rasa/.venv/lib/python3.7/site-packages/tensorflow/python/eager/monitoring.py", line 361, in __init__ len(labels), name, description, *labels) File "/Users/u18881587/rasa/.venv/lib/python3.7/site-packages/tensorflow/python/eager/monitoring.py", line 135, in __init__ self._metric = self._metric_methods<span class="error">[self._label_length]</span>.create(*args) tensorflow.python.framework.errors_impl.AlreadyExistsError: Another metric with the same name already exists.

 </pre>

**Comment by tomhewitson** [comment]
Also having the same issue

Rasa Version      :         2.8.13
Minimum Compatible Version: 2.8.9
Rasa SDK Version  :         2.8.2
Rasa X Version    :         0.42.5
Python Version    :         3.8.3
Operating System  :         macOS-10.16-x86_64-i386-64bit

**Comment by m-vdb** [comment]
Closing as stale -- if the issue persists on 3.x, please reopen an issue 🙏🏻
