### ISSUE TITLE
`rasa interactive` saves slots twice in Rasa 3.0rc01.

### ISSUE THREAD

**Issue by koaning** [RasaHQ/rasa#10212]
I'm emulating what it might be like to work on a form from scratch. So I run `rasa interactive` and fill in my info. Here's the chatlog.

 ------
 Chat History

1.  Bot You
     ─────────────────────────────────────────────────────────────────────────────
     1 action_listen 
     ─────────────────────────────────────────────────────────────────────────────
     2 hi there 
     intent: greet 1.00 
     ─────────────────────────────────────────────────────────────────────────────
     3 utter_greet 1.00 
     Hey! How are you? 
     action_listen 1.00 
     ─────────────────────────────────────────────────────────────────────────────
     4 i want to buy a pizza 
     intent: buy_pizza 1.00 
     ─────────────────────────────────────────────────────────────────────────────
     5 simple_pizza_form 1.00 
     active_loop {"name": "simple_pizza_form"} 

     slot

     {"requested_slot": "pizza_size"} 

     What size would you like your pizza to be? 
     slot

     {"pizza_size": "large"} 

     OK! You want to have a large pizza. 
     slot

     {"pizza_size": "large"} 

     slot

     {"requested_slot": "pizza_type"} 

     What kind of pizza do you want? 
     Buttons: 
     1: pepperoni (pepperoni) 
     2: hawaii (hawaii) 
     Type out your own 
     message... 
     slot

     {"pizza_type": "pepperoni"} 

     OK! You want to have a pepperoni pizza. 
     slot

     {"pizza_type": "pepperoni"} 

     slot

     {"requested_slot": null} 

     active_loop

     {"name": null} 

     utter_submit 1.00 
     I will now order a pizza for you! 
     utter_pizza_slots 1.00 
     I will order a large pepperoni pizza. 
     action_listen 1.00 
     ─────────────────────────────────────────────────────────────────────────────
     6 thanks, bye! 
     intent: goodbye 1.00 
     ─────────────────────────────────────────────────────────────────────────────
     7 utter_goodbye 1.00 
     Bye 

 Current slots: 
 pizza_size: large, pizza_type: pepperoni, vegetarian: None, requested_slot: None, session_started_metadata: None

 ------
 ? The bot wants to run 'action_listen', correct? Yes 
 ? Your input -> 

 Cancelled by user

 ? Do you want to stop? Export & Quit 
 ? Export stories to (if file exists, this will append the stories) data/stories.yml 
 ? Export NLU data to (if file exists, this will merge learned data with previous training examples) data/nlu.yml 
 ? Export domain file to (if file exists, this will be overwritten) domain.yml 
 2021-11-15 14:38:59 INFO rasa.core.training.interactive - Successfully wrote stories and NLU data
 2021-11-15 14:38:59 INFO rasa.core.training.interactive - Killing Sanic server now.

Here's what the resulting story looks like in my `stories.yml` file.

*   story: interactive_story_1
     steps:
*   intent: greet
*   action: utter_greet
*   intent: buy_pizza
*   action: simple_pizza_form
*   active_loop: simple_pizza_form
*   slot_was_set:
*   requested_slot: pizza_size
*   slot_was_set:
*   pizza_size: large
*   slot_was_set:
*   pizza_size: large
*   slot_was_set:
*   requested_slot: pizza_type
*   slot_was_set:
*   pizza_type: pepperoni
*   slot_was_set:
*   pizza_type: pepperoni
*   slot_was_set:
*   requested_slot: null
*   active_loop: null
*   action: utter_submit
*   action: utter_pizza_slots
*   intent: goodbye
*   action: utter_goodbye

It lists the slots twice! Figured this must've been a bug.

**Comment by koaning** [comment]
Here's my Rasa info:

```
> python -m rasa --version
Rasa Version      :         3.0.0rc1
Minimum Compatible Version: 2.8.9
Rasa SDK Version  :         3.0.0rc1
Rasa X Version    :         None
Python Version    :         3.7.9
Operating System  :         Linux-5.11.0-7614-generic-x86_64-with-Pop-20.10-groovy
Python Path       :         /home/vincent/Development/how-to-rasa/venv/bin/python
```

**Comment by koaning** [comment]
I'm wondering, might this be caused by the validator?

**Comment by koaning** [comment]
Similar to https://github.com/RasaHQ/rasa/issues/10213, this issue is likely fixed by https://github.com/RasaHQ/rasa/pull/10252.

**Comment by ancalita** [comment]
This could potentially be linked to this issue: #9945
