### ISSUE TITLE
Order of commands broken in rc2 for succes markers

### ISSUE THREAD

**Issue by koaning** [RasaHQ/rasa#10227]
I'm trying out success markers, [per docs](https://github.com/RasaHQ/rasa/blob/main/docs/docs/markers.mdx):

```bash
rasa evaluate markers all --config marker.yml extracted_markers.csv
```

This results in an error in RC2 though. 

```
> python -m rasa evaluate markers all --config marker.yml extracted_markers.csv 

usage: rasa evaluate markers [-h] [-v] [-vv] [--quiet] [--config CONFIG]
                             [--no-stats | --stats-file-prefix [STATS_FILE_PREFIX]]
                             [--endpoints ENDPOINTS] [-d DOMAIN]
                             output_filename {first_n,sample,all} ...
rasa evaluate markers: error: argument strategy: invalid choice: 'extracted_markers.csv' (choose from 'first_n', 'sample', 'all')
```

If you flip the order around, then it does work. 

```
python -m rasa evaluate markers --config markers.yml extracted_markers.csv all
```

It seems like either the docs are faulty or the implementation needs to be changed.

**Comment by aeshky** [comment]
Thanks for submitting this @koaning 
Based on some feedback we received in the docs, we decided to reorder the command to make it more intuitive for users. However, we haven't impelmetned the changes yet. We discussed them here: https://github.com/RasaHQ/rasa/issues/10174
We'll create a PR to close both this issue and the one I linked. :)
