### ISSUE TITLE
`/model/test/intents` endpoint docs has incomplete example

### ISSUE THREAD

**Issue by melindaloubser1** [RasaHQ/rasa#10221]
### Rasa Open Source version

3.0.0rc2

### What happened?

The API docs for performing an intent evaluation do not include a complete JSON example, so it's hard to know what format it expects. [https://rasa.com/docs/rasa/pages/http-api#operation/testModelIntent](https://rasa.com/docs/rasa/pages/http-api#operation/testModelIntent)

I could get a YAML format to work, but there's no example of that at all

### Guess at a request that doesn't work

<pre>$ curl --request POST \
 --url [http://localhost:5005/model/test/intents](http://localhost:5005/model/test/intents) \
 --header 'Authorization: Bearer ' \
 --header 'Content-Type: application/json' \
 --data '{
 "rasa_nlu_data": {
 "common_examples": 

 {"greet":["hi"]} 

}
 }'</pre>

### Relevant log output

<pre>{
 "version": "3.0.0rc2",
 "status": "failure",
 "message": "An unexpected error occurred during evaluation. Error: 

 {'greet': ['hi']} 

 is not of type 'array'. Failed to validate data, make sure your data is valid. For more information about the format visit https:\/\/rasa.com\/docs\/rasa\/training-data-format.\n\nFailed validating 'type' in schema<span class="error">['properties']</span><span class="error">['rasa_nlu_data']</span><span class="error">['properties']</span><span class="error">['common_examples']</span>:\n {'items': {'properties': {'entities': {'items': {'properties': {'end': 

 {'type': 'number'} 

,\n 'entity': 

 {'type': 'string'} 

,\n 'group': 

 {'type': 'string'} 

,\n 'role': 

 {'type': 'string'} 

,\n 'start': 

 {'type': 'number'} 

,\n 'value': {'type': <span class="error">['string',\n 'number']</span>}},\n 'required': <span class="error">['start',\n 'end',\n 'entity']</span>,\n 'type': 'object'},\n 'type': 'array'},\n 'intent': {'type': 'string'}},\n 'type': 'object'},\n 'type': 'array'}\n\nOn instance<span class="error">['rasa_nlu_data']</span><span class="error">['common_examples']</span>:\n 

 {'greet': ['hi']} 

",
 "reason": "TestingError",
 "details": {},
 "help": null,
 "code": 500
 }</pre>

### Request that does work (no example in docs for yaml)

 $ curl --request POST \
 --url [http://localhost:5005/model/test/intents](http://localhost:5005/model/test/intents) \
 --header 'Authorization: Bearer ' \
 --header 'Content-Type: text/yaml' \
 --data 'nlu:

*   intent: greet
     examples: |
*   hey <span class="error">[Molly]</span>(name)
*   hello <span class="error">[Bob]</span>(name)
*   hi <span class="error">[Chris]</span>(name)
*   hello there <span class="error">[Jim]</span>(name)
*   good morning <span class="error">[Fred]</span>(name)
*   good evening <span class="error">[Sally]</span>(name)
*   moin
*   hey there
*   let'\''s go
*   hey dude
*   goodmorning
*   goodevening
*   good afternoon
*   hi'

**Comment by ThamaluM** [comment]
Came across the same issue. If there any update on this.

**Comment by PROrock** [comment]
I have tried to use this endpoint in rasa 3.2.2 - my quick summary:
* json example is now in the [documentation](https://rasa.com/docs/rasa/pages/http-api/#operation/testModelIntent)
* yaml example is still missing. This is curl command, which is working for me:
```shell
curl --location --request POST 'http://localhost:5005/model/test/intents' \
--header 'Content-Type: application/x-yaml' \
--data-raw 'version: "3.1"
nlu:
  - intent: greet
    examples: |
      - hello there
      - hey [Molly](name)
      - hello [Bob]{"entity": "name"}
  - intent: bot_challenge
    examples: |
      - are you a bot?
      - am I talking to a human?
'
```
Currently, there has to be at least 2 intents in the test data, otherwise the evaluation doesn't run and just returns nulls with no warnings (I don't know why, but that's not important for this ticket).
