### ISSUE TITLE
Selected button option not visible in Slack

### ISSUE THREAD

**Issue by gaganmanku96** [RasaHQ/rasa#10237]
### Rasa Open Source version

2.8.13

### Rasa SDK version

2.8.9

### Rasa X version

2.8.2

### Python version

3.8

### What operating system are you using?

Linux

### What happened?

[<span class="image-wrap" style="">![](https://user-images.githubusercontent.com/20324385/141982240-d3027dbb-a036-4118-8018-07ddce0a02e9.png)</span>](https://user-images.githubusercontent.com/20324385/141982240-d3027dbb-a036-4118-8018-07ddce0a02e9.png) I'm using slack as a channel and I've added some buttons. The problem is I cannot see the button I clicked.

Here is my domain.yml code for that part [<span class="image-wrap" style="">![](https://user-images.githubusercontent.com/20324385/141982505-c61b124e-17f4-4fef-b0d0-91bd80ebe5e1.png)</span>](https://user-images.githubusercontent.com/20324385/141982505-c61b124e-17f4-4fef-b0d0-91bd80ebe5e1.png)

So, my question is how do I show the selected button option in slack?

### Command / Request

 _No response_ 

### Relevant log output

 _No response_

**Comment by sara-tagger** [comment]
Thanks for the issue, @degiz will get back to you about it soon!

###### You may find help in the [docs](https://rasa.com/docs/) and the [forum,](https://forum.rasa.com/) too 🤗
