### ISSUE TITLE
Installing 3.0 rc2 with old version of pip hangs

### ISSUE THREAD

**Issue by dakshvar22** [RasaHQ/rasa#10230]
### Rasa Open Source version

3.0.0rc2

### Python version

3.8

### What operating system are you using?

OSX

### What happened?

I created a fresh virtual environment with miniconda and tried installing `3.0.0rc2` with `pip`. My `pip` version was `21.2.4`. The command `pip install rasa==3.0.0rc2` just gets stuck while trying to install the `rsa` library. Here are some logs of the relevant portion of the install:

```
Collecting rsa<5,>=3.1.4
  Downloading rsa-4.7.1-py3-none-any.whl (36 kB)
INFO: This is taking longer than usual. You might need to provide the dependency resolver with stricter constraints to reduce runtime. If you want to abort this run, you can press Ctrl + C to do so. To improve how pip performs, tell us what happened here: https://pip.pypa.io/surveys/backtracking
  Using cached rsa-4.7-py3-none-any.whl (34 kB)
  Using cached rsa-4.6-py3-none-any.whl (47 kB)
  Downloading rsa-4.5-py2.py3-none-any.whl (36 kB)
  Downloading rsa-4.4.1-py2.py3-none-any.whl (33 kB)
  Downloading rsa-4.3-py2.py3-none-any.whl (36 kB)
  Using cached rsa-4.2.tar.gz (46 kB)
INFO: pip is looking at multiple versions of rsa to determine which version is compatible with other requirements. This could take a while.
  Downloading rsa-4.1-py3-none-any.whl (32 kB)
  Using cached rsa-4.0-py2.py3-none-any.whl (38 kB)
  Downloading rsa-3.4.2-py2.py3-none-any.whl (46 kB)
     |████████████████████████████████| 46 kB 6.0 MB/s
  Downloading rsa-3.4.1-py2.py3-none-any.whl (46 kB)
     |████████████████████████████████| 46 kB 4.5 MB/s
  Downloading rsa-3.4-py2.py3-none-any.whl (46 kB)
     |████████████████████████████████| 46 kB 5.7 MB/s
```

I terminated the install after 25 mins or so.

Next, I upgraded my pip version with `pip install -U pip` and that brought in `pip==21.3.1` and re-executing `pip install rasa==3.0.0rc2` worked like a charm.

Can we put this known information in our docs or event better check if there is a fix?

### Command / Request

```shell
pip install rasa==3.0.0rc2
```

**Comment by Horizon733** [comment]
Yes, I face the same issue, with 
Pip version: 21.2.4
Python version: 3.8.12
Virtual Environment: Conda
