### ISSUE TITLE
Activating another form from within a form behaves differently in 3.0 (`rasa interactive`)

### ISSUE THREAD

**Issue by samsucik** [RasaHQ/rasa#10253]
This issue is similar to #10248 but in this case it is Rasa 3.0 that activates the new form when 2.8 does not.

The setup is the same as for #10248.

Steps:
1. `rasa train` the bot and `rasa interactive --debug` talk to it (confirming all predictions with `y`)
1. say `hi` (triggers `my_form`)
1. say `bye` -- this triggers first `my_form` and right after that `my_form_2`. In 2.8, `my_form_2` gets activated only after saying `bye` one more time. Effectively, Rasa 3.0 here ignores that the requested slot (`slot_0`) is mapped `from_text` and should be filled from whatever message. Instead, Rasa 3.0 considers the message's intent which activates `my_form_2`.

**Comment by ka-bu** [comment]
Closing this since I can't replicate it after merging in #10252 
```
 #    Bot                                                       You        
───────────────────────────────────────────────────────────────────────────
 1    action_listen                                                        
───────────────────────────────────────────────────────────────────────────
 2                                                                      hi 
                                                        intent: greet 1.00 
───────────────────────────────────────────────────────────────────────────
 3    my_form 1.00                                                         
      active_loop{"name": "my_form"}                                       
      slot{"requested_slot": "slot_0"}                                     
      Let's start this form. Say something!                                
      slot{"slot_0": "bye"}                                                
      slot{"slot_0": "bye"}                                                
      slot{"requested_slot": "slot_A"}                                     
      Could you, possibly, please, give me a city.   
```
The issue with the duplicate slot set events #10212  also happens here
