### ISSUE TITLE
Verify model confidences manually before 3.0 release

### ISSUE THREAD

**Issue by dakshvar22** [RasaHQ/rasa#10255]
[Slack Thread](https://rasa-hq.slack.com/archives/C01HHMR4X8S/p1637062630244900)

We have run model regression tests in the integration phase of architecture revamp. However, those tests do not check the distribution of confidences that are output by the models. This distribution can be generated by training and testing on a dataset and examining the plot generated in `intent_histogram.png`. The examination should check if the confidence distribution of correct and wrong predictions looks "approximately" the same when trained with `2.8.x` and `3.0.0` (They won't be exactly the same because of some changes that come with 3.0).

The datasets and configs (can be found in [training-data repo](https://github.com/RasaHQ/training-data)) on which this should be tested at at the least (covers english and german dataset + configs that are frequently used by customers):

Dataset: public/Sara Configs:

*   en/cvf_bert_diet_responset2t.yml
*   en/cvf_diet_responset2t.yml
*   en/cvf_embedding_responseb2b.yml
*   en/cvf_bert_embedding_responseb2b.yml

Dataset: private/service_faq Configs:

*   en/cvf_spacy_diet_responset2t.yml
*   en/cvf_diet_responset2t.yml
*   en/cvf_embedding_responseb2b.yml
*   en/cvf_spacy_embedding_responseb2b.yml

Definition of Done:

*   Training and evaluation run for the above dataset and config combo using `2.8.x` and a release candidate of `3.0.0` / `main` branch of Rasa OSS
*   Verified that `intent_histogram.png` look "approximately similar" in every unique instance of the dataset and config combo.

**Comment by joejuzl** [comment]
@dakshvar22 so for the first one we would run:
```
rasa train nlu --nlu public/Sara/train --config configs/en/nlu/cvf_bert_diet_responset2t.yml
rasa test nlu --nlu public/Sara/test --config configs/en/nlu/cvf_bert_diet_responset2t.yml --model the_model.tar.gz
```

for `2.8.x` and `3.0.0rc` and then compare the `intent_histogram.png` for each?

**Comment by dakshvar22** [comment]
Yep

**Comment by joejuzl** [comment]
`en/nlu/cvf_spacy_diet_responset2t.yml` and `en/nlu/cvf_spacy_embedding_responseb2b.yml` don't seem to exist. Did you mean `de/...` for both?

**Comment by dakshvar22** [comment]
Ahh, yes sorry my bad.

**Comment by joejuzl** [comment]
In fact I guess all the `private/service_faq` should be german configs right?

**Comment by dakshvar22** [comment]
Theoretically yes but you wouldn't need to for others because practically the `language` key does not matter for the other configs I mentioned. But specifically for `*_spacy_*` configs you'll have to necessarily use german configs since its only available for that.

**Comment by joejuzl** [comment]
[rasa_test_2_vs_3_results.zip](https://github.com/RasaHQ/rasa/files/7588351/rasa_test_2_vs_3_results.zip)

@dakshvar22 This zip contains all the results for all the configs in the description for `2.8.14` and `3.0.0rc3`. The histograms look comparable to me - although would be good to get another (more histogram experienced) pair of eyes on them.

**Comment by dakshvar22** [comment]
Looking at them now 👀

**Comment by dakshvar22** [comment]
They don't look abnormally different which is great! 

However, there is one interesting observation I could make: The histograms for configurations which use no transformer layers (`*_embedding_*`) look almost (and exactly in some cases) identical which does not seem to be the case for configurations which use transformer layers (`*_diet_*`). The difference is much more in the latter.
Do we know why this would be the case? I would like for us to at least know what we have changed that would result in such an observation?
Tagging @ka-bu since she might have more context here.

**Comment by ka-bu** [comment]
Does not sound that surprising that those runs with transformer layers yield larger differences in general, no? 

 To put the differences into perspective it might help to re-run the same experiment (e.g. just re-run training on 2.8.14 with one of the diet configs and re-evaluate a few times). Or are those results on 2.8.14 so stable / much more similar to what you saw on 2.8.x before (in comparison to 3.0) now @dakshvar22 ? 
 
 > They won't be exactly the same because of some changes that come with 3.0
 
Which changes would that be here? Cause we're testing only the NLU component here (and the same tf updates have been done in both branches), no?

**Comment by dakshvar22** [comment]
@m-vdb @joejuzl There are a few open questions here (apologies for not replying to Kathrin's question earlier) and I don't think the issue should be closed.
Do you want the conversation to happen anywhere else?

**Comment by m-vdb** [comment]
sounds good @dakshvar22 -- I closed it because it was in the "Done" column, surely a mistake.

It looks like @ka-bu had some questions for you to answer in [this comment](https://github.com/RasaHQ/rasa/issues/10255#issuecomment-976864923). Could you provide more input?

**Comment by dakshvar22** [comment]
> Does not sound that surprising that those runs with transformer layers yield larger differences in general, no?

@ka-bu Why should they yield large differences if we haven't touched the TF part of the codebase during the refactor? AFAIK, the featurization also hasn't changed or has it?

**Comment by ka-bu** [comment]
> > Does not sound that surprising that those runs with transformer layers yield larger differences in general, no?
> 
> @ka-bu Why should they yield large differences if we haven't touched the TF part of the codebase during the refactor? AFAIK, the featurization also hasn't changed or has it?

My thinking there was that more layers / computations (i.e. including transformer layers) imply more chances for differences due to numerical issues / non-deterministic operations. And no, the featurization should not have changed (the biggest changes related to featurization was the lookup table but that only affects the policies not the nlu part discussed here).

**Comment by dakshvar22** [comment]
If the featurization didn't change + random seed was set in the config (which it is if the configs were taken from the dataset repo) + experiment was run on CPU, the results should actually be completely reproducible.

Some operations are not deterministic only on GPU. They are still deterministic on CPU. @joejuzl Can you please confirm that you ran these experiments locally on a CPU machine?

My gut feeling is that the feature vectors produced by `CountVectorsFeaturizer` has changed. 🤔

**Comment by dakshvar22** [comment]
> Which changes would that be here?

Now that I think of it, I think I was really referring to just the lookup table bit but that shouldn't affect NLU components.

Another bit that can cause a difference: Is it possible that the order in which data points are read in 3.0 is different from the order in which they were read in 2.8.x?

**Comment by joejuzl** [comment]
>  @joejuzl Can you please confirm that you ran these experiments locally on a CPU machine?
Yeah I ran them locally on my macbook. 

Are you saying that the difference between 2.8.x and 3.0.x is more than the difference expected from e.g. re-running on 2.8.x?

**Comment by dakshvar22** [comment]
> Are you saying that the difference between 2.8.x and 3.0.x is more than the difference expected from e.g. re-running on 2.8.x?

Re-running on 2.8.x multiple times on CPU will yield exactly same model confidences (if run on CPU), and hence the confidence histograms will be exactly the same. So, we should really find out what is causing the difference in model confidences when the same config + dataset + CPU machine is used but with `2.8.x` and `3.0` installations of rasa.

I should emphasize that the differences don't appear to be large (for e.g. - in `private/service_faq` dataset, the distribution seems to be shifted for 10-11 training examples) so it isn't a high-priority investigation, but nevertheless it should be done at some point in time to prevent an unknown regression causing larger regressions in the future.

**Comment by joejuzl** [comment]
Makes sense - and yes I agree this needs to be investigated further. I will move this back to the inbox.
