### ISSUE TITLE
Unreasonable form rejection in a migrated project only with `rasa interactive`

### ISSUE THREAD

**Issue by samsucik** [RasaHQ/rasa#10251]
Somehow, when running an otherwise okay-looking simple project converted to 3.0 with `rasa data migrate`, a form gets rejected at a point where it happily proceeded in the 2.8 version.

An example setup is the same as in #10248.

Steps to reproduce the (3.0) behaviour:
1. `rasa train`
2. `rasa interactive`
3. utter these messages (while confirming all predictions with `y`)
   1. "hi"
   2. "Berlin"

The 2nd message causes the `my_form` to reject and Rasa predicts `action_default_fallback` instead of going ahead and asking for the next slot in the form (like Rasa 2.8 does). Note that when running with `rasa shell` (the 3.0 version of the bot), the form does not reject -- instead, all 3 of its slots get filled with `Berlin` and the form happily exits.

**Comment by ka-bu** [comment]
Closing because I can't replicate the issue anymore after #10252 (i.e. "Berlin" gets detected as a "city" and fills all slots)
