### ISSUE TITLE
Missing `partition_key` for connection to DynamoDB Tracker Store

### ISSUE THREAD

**Issue by carlad** [RasaHQ/rasa#10264]
### Rasa Open Source version

3.0.0rc2

### Rasa SDK version

 _No response_ 

### Rasa X version

 _No response_ 

### Python version

3.8

### What operating system are you using?

OSX

### What happened?

Rasa [Documentation](https://rasa.com/docs/rasa/tracker-stores) specifies this config for a DynamoDB Tracker store:

tracker_store: type: dynamo table_name: <name of the table to create, e.g. rasa> region: <name of the region associated with the client

However, when setting up the table in AWS, a requirement is to enter a `partition_key`: [<span class="image-wrap" style="">![](https://user-images.githubusercontent.com/1754975/142203352-2956e9f7-3cd3-4ba6-bda5-d5f8ea1dc009.png)</span>](https://user-images.githubusercontent.com/1754975/142203352-2956e9f7-3cd3-4ba6-bda5-d5f8ea1dc009.png)

When I try to converse with the chatbot, the attempt to save to the tracker store fails.

And even when updating the config to include a `partition_key`, that is:

tracker_store: type: dynamo table_name: rasa_QA2_3.0.0rc2 partition_key: tracker_store region: us-east-2

the Dynamo queries still fail.

### Command / Request

After running `rasa run -m models --endpoints endpoints.yml`, then `rasa shell` to create conversations, the following error is returned when attempting to chat with the bot (please note: the `partition_key` of my Dynamo Table is `tracker_store`):

### Relevant log output

ERROR rasa.core.tracker_store - Error happened when trying to save conversation tracker to 'DynamoTrackerStore'. Falling back to use the 'InMemoryTrackerStore'. Please investigate the following error: An error occurred (ValidationException) when calling the Query operation: Query condition missed key schema element: tracker_store.

**Comment by rocha-p** [comment]
Hello! Were you able to fix this problem?
