### ISSUE TITLE
Prepare Markers video for the 3.0 video content launch.

### ISSUE THREAD

**Issue by aeshky** [RasaHQ/rasa#10276]
Prepare a video for the [3.0 launch event](https://www.notion.so/rasa/Video-event-content-for-3-0-launch-3f56e1a749d347129a3416d5c7449af3) for Markers on the week of 29th of November, and send it to rachel before the 23rd.

**Comment by TyDunn** [comment]
@aeshky Can we work on the outline for this video together?

**Comment by aeshky** [comment]
I've now gone through the resources listed in [this page](https://www.notion.so/rasa/Video-event-content-for-3-0-launch-3f56e1a749d347129a3416d5c7449af3) and it looks like there isn't a [strict format for the presentation](https://www.notion.so/rasa/Creating-videos-showcasing-technical-content-1e50e097c4b04657ac7b0746a0b5da29#40041d80a6c948549d28baee73f42839). 
The structure of my talks usually evolves as I work on them and practice to make sure everything flows well, but I'll generally aim to give the motivation behind the feature, then do a short demo to get people excited to go read the full docs and try it out themselves. 
Is there anything in particular you wanted me to include / exclude? I know you said I should refer to it as an experimental feature. Anything else? I doubt that I'll include an actual outline for a 5-10 minute video :)

**Comment by aeshky** [comment]
@TyDunn let me know if you want to do this differently to what I suggested above, for example if you want to be involved in creating the content, or if you want to jump on a quick call to discuss. Otherwise if you're happy, I can do a dry run with you early Monday and incorporate your feedback during the rest of the day.

**Comment by TyDunn** [comment]
That structure sounds good to me. I was looking more for the content outline. I think our discussion [here](https://rasa-hq.slack.com/archives/C8LEHMTAM/p1637316042407100?thread_ts=1637314328.399200&cid=C8LEHMTAM) makes me believe we are aligned now :)

**Comment by aeshky** [comment]
Video shared, feedback incorporated, and final version uploaded to the launch event folder.
