### ISSUE TITLE
Add warning or error for incorrect training data version

### ISSUE THREAD

**Issue by TyDunn** [RasaHQ/rasa#10288]
Context [here](https://rasa-hq.slack.com/archives/C01HHMR4X8S/p1637313176350300)
Further Slack discussion [here](https://rasa-hq.slack.com/archives/C01HHMR4X8S/p1637333261368900)

For users who have not used `rasa data migrate` and have manually created or updated a domain that follows the 3.0 format (slot mappings defined in slots, form required_slots is a list) **but** who have not updated the version key in the `domain.yml`, everything will run smoothly without any prompt/ warnings for them to update version key too.

We want a warning when the user runs `rasa data validate` and / or `rasa train` with Rasa Open Source 3.0 and the version in training data files is not at least as high as the LATEST_TRAINING_DATA_FORMAT_VERSION.

**Comment by carlad** [comment]
While experimenting with [this repo](https://github.com/RasaHQ/rasa-3.x-form-examples/tree/main/06-custom-name-experience) on rasa main, which uses training data version 2.0, @ancalita noticed that there's no warning or error if the training data is not updated to 3.0. 

Do we want a warning or an error here? Do we want to enforce upgrading?

**Comment by ancalita** [comment]
Hey @carlad I don't have a strong opinion here, although I'd open a Slack thread to consult the whole squad for a more productive discussion.

**Comment by TyDunn** [comment]
> although I'd open a Slack thread to consult the whole squad for a more productive discussion.
@carlad I agree with Anca here. Creating a quick proposal for what you think would be a good approach here and asking `@enable` in Slack would be awesome
