### ISSUE TITLE
required_slots is called three times on form trigger in 3.0.0rc2

### ISSUE THREAD

**Issue by koaning** [RasaHQ/rasa#10281]
I have added a custom `required_slots` method for a form in 3.0.0RC2.

<pre>class ValidateNameForm(FormValidationAction):
 def name(self) -> Text:
 return "validate_name_form"

 async def required_slots(
 self,
 domain_slots: List<span class="error">[Text]</span>,
 dispatcher: "CollectingDispatcher",
 tracker: "Tracker",
 domain: "DomainDict",
 ) -> Optional[List<span class="error">[Text]</span>]:
 first_name = tracker.slots.get("first_name")
 print(f"required slots gets called, domain_slots:

 {domain_slots} 

 ")
 if first_name is not None:
 if first_name not in names:
 if "name_spelled_correctly" not in domain_slots:
 print("slot `name_spelled_correctly` added!")
 return <span class="error">["name_spelled_correctly"]</span> + domain_slots
 return domain_slots</pre>

It does some printing. And when we trigger the form we see these three print statements.

 required slots gets called, domain_slots:<span class="error">['first_name', 'last_name']</span> 
 required slots gets called, domain_slots:<span class="error">['first_name', 'last_name']</span> 
 required slots gets called, domain_slots:<span class="error">['first_name', 'last_name']</span>

On a zoom call with @ancalita we were wondering why it is triggered three times. It may be related to the `requested_slot`-slot but we felt it was best to make an issue to make sure that we understood this behavior and that it was not a bug.

**Comment by koaning** [comment]
The related Rasa project for this issue can be found [here](https://github.com/RasaHQ/rasa-3.x-form-examples/tree/main/06-custom-name-experience).

**Comment by mridullpandey** [comment]
@koaning  mentioned page relects 404

**Comment by koaning** [comment]
It doesn't if you're internal to Rasa.
