### ISSUE TITLE
Separate command for rule/story conflict validation

### ISSUE THREAD

**Issue by koernerfelicia** [RasaHQ/rasa#10286]
### What problem are you trying to solve?

Currently, rules aren't validated for conflicts with stories until training. This was a design decision: checking for conflicts is as intensive as training, so we don't do this during `rasa data validate`, but rather RulePolicy checks this during training.

We should be able to check for rule/story conflicts with a separate command before training.

### What's your suggested solution?

During an open source coffee, we discussed that thanks to the new architecture, it might be possible to re-use the "trained" RulePolicy from validation for training, so that the work is no longer duplicated.

### Examples (if relevant)

 _No response_ 

### Is anything blocking this from being implemented? (if relevant)

 _No response_ 

### Definition of Done

*   [ ] `rasa data validate` or similar command that is not `rasa train` checks for rule/story conflicts

**Comment by b-quachtran** [comment]
@TyDunn Do you know if this would be in-scope for 3.1?
