### ISSUE TITLE
Securing with SSL in docs  has missing steps.

### ISSUE THREAD

**Issue by vinishgeorge** [RasaHQ/rasa#10292]
### Rasa Open Source version

0.42.4

### Rasa SDK version

0.2.8

### Rasa X version

0.42.4

### Python version

3.7

### What operating system are you using?

Linux

### What happened?

Installation with docker: In the Documentation here [Secure using SSL ](https://rasa.com/docs/rasa-x/installation-and-setup/customize#securing-with-ssl) there are missing steps after renewal of certificates and copying the cert files to

 {RASA_HOME}/certs:

 h1\. We need to uncomment the lines in the {RASA_HOME} 

/nginx-config-files/ ssl.conf.template in ngnix-config-files

1.  ## listen 8443 ssl; server_name example.com; ssl_certificate /etc/nginx/certs/fullchain.pem; ssl_certificate_key /etc/nginx/certs/privkey.pem;
2.  We need to uncomment the line in {RASA_HOME} /nginx-config-files/rasax.ngnix.template to include the ssl.conf file.

     h2\. include /etc/nginx/conf.d/ssl.conf; # uncomment if using ssl; see ssl.conf.template for example

     h1\. In the {RASA_HOME}

/docker-composer.yml change the ngnix ->volume -> cert location to point to /etc/ngnix/certs eg:

nginx: restart: always image: "nginx:1.19" ports: - "80:8080" - "443:8443" volumes: - ./certs:/etc/ngnix/certs

### Command / Request

 _No response_ 

### Relevant log output

 _No response_

**Comment by sara-tagger** [comment]
Thanks for raising this issue, @joejuzl will get back to you about it soon✨

###### Please also check out the [docs](https://rasa.com/docs/) and the [forum](https://forum.rasa.com/) in case your issue was raised there too 🤗
