### ISSUE TITLE
`required_slots` deserve attention in migration guide

### ISSUE THREAD

**Issue by koaning** [RasaHQ/rasa#10291]
We've learned in https://github.com/RasaHQ/rasa/issues/10261#issuecomment-973999029 that users need to be aware of modest differences between 2.x and 3.x if they have forms that use`required_slots` in a `FormValidationAction`. 

This issue serves as a reminder while we think of a proper way to describe what to pay attention to.

**Comment by ancalita** [comment]
@m-vdb Yes, exactly.

**Comment by ancalita** [comment]
Closed by #10426
