### ISSUE TITLE
Should the cache be disabled for docker containers?

### ISSUE THREAD

**Issue by TyDunn** [RasaHQ/rasa#10293]
We need to decided if the new Rasa Open Source 3.0 model cache should be disabled for the docker containers by default and update the docs to explain this

**Comment by TyDunn** [comment]
@joejuzl @erohmensing I believe you two were discussing this? I moved to infrastructure board, since I think they should decide?

**Comment by joejuzl** [comment]
I think at least their input would definitely be important. Also happy to discuss the finer points with someone if that's helpful.
