### ISSUE TITLE
Rasa 2.8.14 Multiple Tokenizers in Pipeline

### ISSUE THREAD

**Issue by Olga-par** [RasaHQ/rasa#10297]
### Rasa Open Source version

2.8.14

### Rasa SDK version

 _No response_ 

### Rasa X version

 _No response_ 

### Python version

3.8

### What operating system are you using?

Windows

### What happened?

We have developed a project using rasa 1.5.3\. Now we want to migrate to rasa 2.8.14 for several reasons. In rasa 2.8.14 it is not possible to have multiple tokenizers in the same pipeline.

When we ran rasa train nlu --debug we got error

rasa.shared.exceptions.InvalidConfigException: The pipeline configuration contains more than one tokenizer, which is not possible at this time. You can only use one tokenizer. The pipeline contains the following tokenizers: <span class="error">['Whites paceTokenizer', 'SpacyLemmatization', 'SynonymReplacement', 'WhitespaceTokenizer']</span>.

Is it possible to include multiple tokenizers in our pipeline?

### Command / Request

 _No response_ 

### Relevant log output

 _No response_

**Comment by sara-tagger** [comment]
Thanks for the issue, @kalkbrennerei will get back to you about it soon!

###### You may find help in the [docs](https://rasa.com/docs/) and the [forum,](https://forum.rasa.com/) too 🤗

**Comment by koaning** [comment]
Could you expand on why you need to have two tokenizers in your pipeline? I think your pipeline contains the same tokenizer twice by the way.

**Comment by m-vdb** [comment]
Closing as stale
