### ISSUE TITLE
Clarify intent name `None` in `from_text` slot mapping

### ISSUE THREAD

**Issue by mleimeister** [RasaHQ/rasa#10342]
### What problem are you trying to solve?

Based on this [forum report](https://forum.rasa.com/t/slot-mapping-from-text-not-working/49280) the documentation of the `from_text` slot mapping [here](https://github.com/RasaHQ/rasa/blob/main/docs/docs/domain.mdx#from_text) seems misleading, as it suggests that one should use `intent_name: None` in order to fill the slot with text from any intent.

However, this seems to lead to the string `None` being interpreted as intent name. The desired behaviour can be seen if that line is just omitted.

### What's your suggested solution?

The documentation could be changed to the same wording as in the [from_intent](https://github.com/RasaHQ/rasa/blob/main/docs/docs/domain.mdx#from_intent) section:

 If you choose not to specify the parameter intent, the slot mapping will apply regardless of the intent of the message as long as the intent is not listed under not_intent parameter.

### Examples (if relevant)

 _No response_ 

### Is anything blocking this from being implemented? (if relevant)

 _No response_ 

### Definition of Done

*   [ ] Change documentation of `from_text` slot mapping to explain how to fill the slot independent of recognized intent.

**Comment by willstott101** [comment]
Perhaps this is a Python / yaml mis-translation - what if you use `null` in the yaml? `None` is interpreted as text - it is not a yaml keyword.
