### ISSUE TITLE
Improve form docs re: `required_slots`

### ISSUE THREAD

**Issue by samsucik** [RasaHQ/rasa#10353]
In the docs for defining forms, we should add something like:

> Each form needs to have at least one slot in the `required_slots` list.

Currently, it says "You will need to specify a list of slot names to the mandatory `required_slots` key.", which isn't 100% clear in cases where you try to define all slots dynamically and not include any in the domain under `required_slots`. See [this Slack thread](https://rasa-hq.slack.com/archives/C01HHMR4X8S/p1637238757326700?thread_ts=1637230993.325200&cid=C01HHMR4X8S) for context.

**Comment by itallogravina** [comment]
Hello, I would like to know if the document has been modified?

**Comment by samsucik** [comment]
@itallogravina since the issue is still open, I think this hasn't been tackled yet.

**Comment by vitordiniz25** [comment]
Hello, I would like to work on this issue.
