### ISSUE TITLE
Add Pytorch support to Rasa

### ISSUE THREAD

**Issue by MuhammadAlBarham** [RasaHQ/rasa#10350]
### What problem are you trying to solve?

Adding Pytorch models compatibility to Rasa.

### What's your suggested solution?

Write a backend using Pytorch code. So, adding pytorch models will be easy.

**Comment by koaning** [comment]
Technically we already support PyTorch models, you'd merely need to write a custom component that uses it. Could you further elaborate what you mean by PyTorch support?

**Comment by MuhammadAlBarham** [comment]
Ahhha, it makes sense. Since we just take care of inputs and outputs.
Is just adding custom component, then give it an input and take the output ?

**Comment by koaning** [comment]
> Is just adding custom component, then give it an input and take the output ?

Most functions can be given "an input" and return "an output", so it's hard to give a directed answer to this question. You may however gain some inspiration from having a look at the implementation of custom components [here](https://github.com/RasaHQ/rasa-nlu-examples/). At the time of writing these components support Rasa 2.x and may serve as a starting point.

**Comment by koaning** [comment]
I'll close the issue for now though, since it's technically already resolved.
