### ISSUE TITLE
rasa x deletes all the comments in yaml files

### ISSUE THREAD

**Issue by simonm3** [RasaHQ/rasa#10361]
### Rasa Open Source version

2.8.14

### Rasa SDK version

2.8.2

### Rasa X version

0.42.5

### Python version

3.8

### What operating system are you using?

Linux

### What happened?

Rasa X ignores all the comments in the config file and then if you make changes deletes all the comments.
This has been mentioned a lot on the forum but I don't see any issue filed so this is it. Really important to have comments when working in a team so you understand what is going on.

**Comment by sara-tagger** [comment]
Thanks for the issue, @koernerfelicia will get back to you about it soon!

###### You may find help in the [docs](https://rasa.com/docs/) and the [forum,](https://forum.rasa.com/) too 🤗

**Comment by koernerfelicia** [comment]
Hi @simonm3 thanks for the issue! This is something we already have an internal issue for [here](https://github.com/RasaHQ/rasa-x/issues/4182) (I know the title says just `config.yml`, but we're aware and have documented this is true for other files as well).

Closing this as a duplicate

**Comment by simonm3** [comment]
btw that link does not work for me and the issue does not come up in a
search. by "internal" issues do you mean there are issues not listed on
github? If so then better if they could be there to avoid duplicates.

**Comment by koernerfelicia** [comment]
Hi @simonm3, by "internal" I mean it's on a private repo, so only Rasa employees with access can see it. They're still listed on github, just on this private repo. That's because this is really a Rasa X (private repo) issue, not a Rasa Open Source (public repo) issue :)

**Comment by koernerfelicia** [comment]
But rest assured it is on our radar and we plan to address it!

**Comment by simonm3** [comment]
OK thanks. did not realise rasa x was not open source. will it continue to be available and free?

**Comment by koernerfelicia** [comment]
Yep, that's the plan! If you scroll down to the bottom of [this page](https://rasa.com/rasa-x/) you can get an overview of the differences between Rasa  Open Source (free), Rasa X (free), and Rasa Enterprise (paid)
<img width="1038" alt="Screenshot 2021-11-23 at 13 08 44" src="https://user-images.githubusercontent.com/45405119/143080508-642c301c-f563-4e7c-b4e1-91db503e24bd.png">
