### ISSUE TITLE
Update migration heading in docs introduction.

### ISSUE THREAD

**Issue by joejuzl** [RasaHQ/rasa#10368]
<img width="645" alt="Screenshot 2021-11-24 at 11 03 33" src="https://user-images.githubusercontent.com/1702538/143217310-aeafbd1c-72ce-489e-964a-bc71a2f02e64.png">

We need to update this to say migrate from 2.x to 3.x. It already links to the latest migration guide.

**Comment by m-vdb** [comment]
there's also the top banner
<img width="1312" alt="Screenshot 2021-11-24 at 11 07 52" src="https://user-images.githubusercontent.com/1931615/143217957-4185ad63-455d-4bc9-8fc1-004c006fe76c.png">
