### ISSUE TITLE
SQLALchemy Version constraints

### ISSUE THREAD

**Issue by souvikg10** [RasaHQ/rasa#10374]
### Rasa Open Source version

3.0.0

### Python version

3.8

### What operating system are you using?

Linux

### What happened?

It seems that the version constraint on SQLAlchemy on pyproject is between `>=1.3.3, <1.5.0` ,
However with a version `1.3.24`, i received the following error

```
ImportError: cannot import name 'URL' from 'sqlalchemy.engine'
```

Resolved upon upgrading to SQLAlchemy 1.4.27, thus the version constraint should `>=1.4.0, <1.5.0`

I am not sure what regression it might cause however on the tracker store.

### Relevant log output

```shell
ImportError: cannot import name 'URL' from 'sqlalchemy.engine'
```

**Definition of done**
- [x] Adjust version constraints for SQLAlchemy
- [x] Check that SQLAlchemy version range works with Rasa X

**Comment by sara-tagger** [comment]
Thanks for raising this issue, @samsucik will get back to you about it soon✨

###### Please also check out the [docs](https://rasa.com/docs/) and the [forum](https://forum.rasa.com/) in case your issue was raised there too 🤗
