### ISSUE TITLE
Bump dependency to TF 2.7

### ISSUE THREAD

**Issue by TyDunn** [RasaHQ/rasa#10378]
Blocking `transformers` dependency upgrade

**Defintion of done**
- [x] Verify with PM that performance implications are acceptable
- [x] Check that we don't need to upgrade this for 2.8
- [x] Ensure model regression test pass
- [ ] Dependency upgraded to TF2.7

**Comment by markus-hinsche** [comment]
For regression tests, it could make sense to use the current state of the regression testing tool to compare train/test runtimes and computational resources before and after. Reach out if you need any help with that.

**Comment by TyDunn** [comment]
cc @ka-bu @usc-m

**Comment by rgstephens** [comment]
Updating to 2.7 would also help with support of the Apple M1 and AWS Graviton, based on my recent [attempt](https://github.com/RasaHQ/rasa/issues/9199#issuecomment-991396904) so build `3.0.1`.

**Comment by setu4993** [comment]
https://github.com/RasaHQ/rasa/issues/9199 is affecting us, too. Is there a timeline on when an update with a fix for this will be released?
