### ISSUE TITLE
playground 'train' button hangs indefinitely

### ISSUE THREAD

**Issue by amn41** [RasaHQ/rasa#10372]
### Rasa Open Source version

main

### Python version

Other

### What operating system are you using?

Cloud (AWS / GCP / AZURE)

### What happened?

STR:

* go to https://rasa.com/docs/rasa/playground
* scroll down and hit train

observed: stuck in 'training' state indefinitely

**Comment by m-vdb** [comment]
I think the training data is 3.0 compatible, but the playground is not updated to 3.0 yet (cf. [this unmerged PR](https://github.com/RasaHQ/playground/pull/170))

**Comment by alwx** [comment]
@m-vdb checking the PR — might be easy enough to update it to make mergable

**Comment by m-vdb** [comment]
awesome 💯 I think there are a lot of other PRs that we can close on the repo once we update to 3.0

**Comment by alwx** [comment]
did [the PR](https://github.com/RasaHQ/playground/pull/171) to update Playground to 3.0: everything is okay except one test (figuring out how to fix it right now)

**Comment by m-vdb** [comment]
@alwx it seems that the playground is still not functional [here](https://rasa.com/docs/rasa/playground). Does it need to be released somehow or is there another issue happening?
