### ISSUE TITLE
Docs: Rasa Open Source opens in new tab when clicking from Rasa Action Server

### ISSUE THREAD

**Issue by ChrisRahme** [RasaHQ/rasa#10396]
### What problem are you trying to solve?

On the navbar in the docs, switching from "Rasa Action Server" ([docs/action-server/](https://rasa.com/docs/action-server/)) to "Rasa Open Source" ([docs/rasa/](https://rasa.com/docs/rasa/)) only opens it a new tab instead of the same tab

[<span class="image-wrap" style="">![](https://user-images.githubusercontent.com/28784897/143535843-59bf7775-437a-4d92-9a57-1d1e9892380e.png)</span>](https://user-images.githubusercontent.com/28784897/143535843-59bf7775-437a-4d92-9a57-1d1e9892380e.png)

### What's your suggested solution?

Don't open [docs/rasa/](https://rasa.com/docs/rasa/) in a new tab when in [docs/action-server/](https://rasa.com/docs/action-server/)

### Definition of Done

[docs/rasa/](https://rasa.com/docs/rasa/) opens in the current tab when clicked from [docs/action-server/](https://rasa.com/docs/action-server/), as well as all other combinations

**Comment by sara-tagger** [comment]
Thanks for submitting this feature request 🚀 @desmarchris will get back to you about it soon! ✨

**Comment by emysdias** [comment]
Hey, I would like to make this, it is possible?

**Comment by m-vdb** [comment]
Closing as it's now fixed.
