### ISSUE TITLE
Spike: Declarative project structures

### ISSUE THREAD

**Issue by TyDunn** [RasaHQ/rasa#10390]
*Note: This spike should be limited to half of the working week*

**Definition of done**
- [x] Gain context from starting scope doc (below)
- [x] Gain context from user interviews (within doc below)
- [x] Gain context by having a conversation with Tobias
- [x] Gain context by having a conversation with Ty
- [x] Create a list of the outstanding questions
- [x] Issue for more detailed spike for outstanding questions created

More context in [Notion](https://www.notion.so/rasa/Declarative-project-structures-13c830c7e6534a3fbe766f217ea8abbf)

**Comment by JulianGerhard21** [comment]
Hi @TyDunn ,

would be very interested in helping here. Pretty much awaited feature.

Kind regards
Julian

**Comment by m-vdb** [comment]
@ancalita for when you're back, would you like to take this one on?

**Comment by ancalita** [comment]
@m-vdb Yes definitely, I'll start working on this today 👍🏼

**Comment by ancalita** [comment]
Outstanding questions added to the original Notion doc.
