### ISSUE TITLE
Changelog documentation indentation issue

### ISSUE THREAD

**Issue by Horizon733** [RasaHQ/rasa#10399]
### Rasa Open Source version

NA

### Rasa SDK version

NA

### Rasa X version

NA

### Python version

Other

### What operating system are you using?

Windows

### What happened?

The below image shows us, that inside changelog docs for 3.0 there is issue with indentation and needs a line break to see the changes written there.
![image](https://user-images.githubusercontent.com/57827233/143550065-bfa52540-e3c0-468f-b8f3-2389b1530bf6.png)

### Command / Request

```shell
I would like to fix this issue by opening a PR if nobody is working on this.
```

**Comment by sara-tagger** [comment]
Thanks for raising this issue, @joejuzl will get back to you about it soon✨

###### Please also check out the [docs](https://rasa.com/docs/) and the [forum](https://forum.rasa.com/) in case your issue was raised there too 🤗
