### ISSUE TITLE
rasa dynamodb putitem error because of dynamodb item size increased more than 400kb

### ISSUE THREAD

**Issue by urvishs** [RasaHQ/rasa#10395]
### Rasa Open Source version

2.8.9

### Rasa SDK version

2.8.2

### Rasa X version

0.42.3

### Python version

3.7

### What operating system are you using?

Windows, Cloud (AWS / GCP / AZURE)

### What happened?

i am using rasa dynamodb tracker and when my rasa chat session is closed and the user try to communicate again the same sender id is assigned these leads to an issue as the chat data keeps on growing causing the item size to increase in dynamodb as dynamodb has a maximum capacity of 400 kb for a single item. these causes the action server to fail and causes issues in my slack bot application.

### Command / Request

```shell
kindly give a appropriate resolution to the issue
```

**Comment by sara-tagger** [comment]
Thanks for raising this issue, @rctatman will get back to you about it soon✨

###### Please also check out the [docs](https://rasa.com/docs/) and the [forum](https://forum.rasa.com/) in case your issue was raised there too 🤗

**Comment by rctatman** [comment]
I believe this is actually working as intended: we do want the same sender continuing to get the same sender id across conversations. If you'd like help with your dynamodb implementation I'd point you towards the forums instead: https://forum.rasa.com/
