### ISSUE TITLE
Wrong URL from Rasa X for uploading models via `curl` and uploading models with code 500

### ISSUE THREAD

**Issue by noopliez** [RasaHQ/rasa#10414]
### Rasa Open Source version

2.8.0

### Rasa SDK version

2.8.0

### Rasa X version

0.42.0

### Python version

3.8

### What operating system are you using?

Cloud (AWS / GCP / AZURE)

### What happened?

I wanted to upload my models via the `curl` tool. I used the command which is provided after clicking on the "Upload Models" button in the Rasa X admin panel:

<pre>curl -k -F "model=@my_model.tar.gz" "http://
 /projects/default/modelsapi_token=

 "

 </pre>

This resulted in nothing but the following output:

<pre> 

 <script>
 try

 {window.SERVER_DATA=__SERVER_DATA__} 

catch(_){}
 </script>
 <title>Rasa X</title>

 <script>
 !function(e){function r(r)

 {for(var n,a,i=r[0],c=r[1],f=r[2],s=0,p=[];s<i.length;s++)a=i[s],Object.prototype.hasOwnProperty.call(o,a)&&o[a]&&p.push(o[a][0]),o[a]=0;for(n in c)Object.prototype.hasOwnProperty.call(c,n)&&(e[n]=c[n]);for(l&&l(r);p.length;)p.shift()();return u.push.apply(u,f||[]),t()} 

function t(){for(var e,r=0;r<u.length;r+

<ins>){for(var t=u<span class="error">[r]</span>,n=!0,i=1;i</ins>

+)

 {var c=t[i];0!==o[c]&&(n=!1)} 

n&&(u.splice(r--,1),e=a(a.s=t<span class="error">[0]</span>))}return e}var n={},o=

 {1:0} 

,u=[];function a(r){if(n<span class="error">[r]</span>)return n<span class="error">[r]</span>.exports;var t=n<span class="error">[r]</span>={i:r,l:Unable to render embedded object: File ({}};return e<span class="error">[r]</span>.call(t.exports,t,t.exports,a),t.l=!0,t.exports}a.e=function(e){var r=[],t=o<span class="error">[e]</span>;if(0) not found.==t)if(t)r.push(t<span class="error">[2]</span>);else{var n=new Promise((function(r,n)

 {t=o[e]=[r,n]} 

));r.push(t<span class="error">[2]</span>=n);var u,i=document.createElement("script");i.charset="utf-8",i.timeout=120,a.nc&&i.setAttribute("nonce",a.nc),i.src=function(e){return a.p+"static/js/"

<ins>({}<span class="error">[e]</span>||e)</ins>

"."+

 {3:"84049f36",4:"170135d6",5:"e1ca92c0",6:"a0034672"} 

<span class="error">[e]</span>+".chunk.js"}(e);var c=new Error;u=function(r){i.onerror=i.onload=null,clearTimeout(f);var t=o<span class="error">[e]</span>;if(0!==t){if(t)

 {var n=r&&("load"===r.type?"missing":r.type),u=r&&r.target&&r.target.src;c.message="Loading chunk "+e+" failed.\n("+n+": "+u+")",c.name="ChunkLoadError",c.type=n,c.request=u,t[1| c]} 

o<span class="error">[e]</span>=void 0}};var f=setTimeout((function(){u(

 {type:"timeout",target:i} 

)}),12e4);i.onerror=i.onload=u,document.head.appendChild<span class="error">[!/images/icons/emoticons/information.png!| /images/icons/emoticons/information.png]</span>}return Promise.all(r)},a.m=e,a.c=n,a.d=function(e,r,t){a.o(e,r)||Object.defineProperty(e,r,

 {enumerable:!0,get:t} 

)},a.r=function(e){"undefined"!=typeof Symbol&&Symbol.toStringTag&&Object.defineProperty(e,Symbol.toStringTag,

 {value:"Module"} 

),Object.defineProperty(e,"__esModule",

 {value:!0} 

)},a.t=function(e,r){if(1&r&&(e=a(e)),8&r)return e;if(4&r&&"object"==typeof e&&e&&e.__esModule)return e;var t=Object.create(null);if(a.r(t),Object.defineProperty(t,"default",

 {enumerable:!0,value:e} 

),2&r&&"string"!=typeof e)for(var n in e)a.d(t,n,function(r)

 {return e[r]} 

.bind(null,n));return t},a.n=function(e){var r=e&&e.__esModule?function()

 {return e.default} 

:function()

 {return e} 

;return a.d(r,"a",r),r},a.o=function(e,r)

 {return Object.prototype.hasOwnProperty.call(e,r)} 

,a.p="/",a.oe=function(e)

 {throw console.error(e),e} 

;var i=this<span class="error">["webpackJsonprasa-frontend"]</span>=this<span class="error">["webpackJsonprasa-frontend"]</span>||[],c=i.push.bind<span class="error">[!/images/icons/emoticons/information.png!| /images/icons/emoticons/information.png]</span>;i.push=r,i=i.slice();for(var f=0;f<i.length;f++)r(i<span class="error">[f]</span>);var l=c;t()}([])
 </script>

 <script src="/static/js/2.eeabe9ea.chunk.js"></script>
 <script src="/static/js/main.78e93b78.chunk.js"></script>
 </pre>

After consulting the [Rasa X API Docs](https://rasa.com/docs/rasa-x/pages/http-api) I found out, that it was the wrong type of URL and that the `api` path was missing. This is the structure provided by the docs:

[https://api/projects/](https://api/projects/)

 {project_id} 

/models

So I tried that one out, too. I also provided the `project_id` I used in Google Cloud (yes, I know it's not the right one but see what's next).

<pre>curl -k -F "model=@my_model.tar.gz" "http://
 /api/projects/

 /modelsapi_token=

 "

 </pre>

This time the model was uploaded BUT I got a code `500` from the server:

<pre>{"version":"0.42.0","status":"failure","message":"See the server logs for more information.","reason":"The server encountered an internal error and cannot complete the request.","details":{},"help":null,"code":500}%</pre>

When checking the logs I got the log output shown below.

When changing the `project_id` back to `default` it worked as expected.

<pre>curl -k -F "model=@my_model.tar.gz" "http://
 /api/projects/default/modelsapi_token=

 "

 </pre>

So basically I encountered two things:

*   **Wrong URL** in Rasa X Admin Panel
*   **Code 500** when using a **non-existing Project ID** but still uploading the model

Maybe this is already fixed in newer versions of Rasa X, if not I hope I can help with this.

### Command / Request

<pre>curl -k -F "model=@my_model.tar.gz" "http://
 /projects/default/modelsapi_token=

 "

 </pre>

### Relevant log output

<pre>rasa-x_1 | Traceback (most recent call last):
 rasa-x_1 | File "/usr/local/lib/python3.8/dist-packages/sqlalchemy/engine/base.py", line 1771, in _execute_context
 rasa-x_1 | self.dialect.do_execute(
 rasa-x_1 | File "/usr/local/lib/python3.8/dist-packages/sqlalchemy/engine/default.py", line 717, in do_execute
 rasa-x_1 | cursor.execute(statement, parameters)
 rasa-x_1 | psycopg2.errors.ForeignKeyViolation: insert or update on table "domain" violates foreign key constraint "domain_project_id_fkey"
 rasa-x_1 | DETAIL: Key (project_id)=(
 ) is not present in table "project".
 </pre>

**Comment by sara-tagger** [comment]
Thanks for the issue, @jupyterjazz will get back to you about it soon!

###### You may find help in the [docs](https://rasa.com/docs/) and the [forum,](https://forum.rasa.com/) too 🤗
