### ISSUE TITLE
Train test split puts the same entity in both samples

### ISSUE THREAD

**Issue by simonm3** [RasaHQ/rasa#10410]
### Rasa Open Source version

2.8.14

### Rasa SDK version

 _No response_ 

### Rasa X version

 _No response_ 

### Python version

3.8

### What operating system are you using?

Linux

### What happened?

Entity evaluation scores from "rasa test" are overstating performance because training and test samples from train_test split include the same entities in both samples. To measure the ability to generalise it needs to be measured on unseen data. Otherwise it is like sitting an exam it has already seen.

Train_test_split needs to make sure the same entity does not appear in both.

### Command / Request

 _No response_ 

### Relevant log output

 _No response_

**Comment by simonm3** [comment]
Same applies to crossvalidation.

**Comment by sara-tagger** [comment]
Thanks for the issue, @erohmensing will get back to you about it soon!

###### You may find help in the [docs](https://rasa.com/docs/) and the [forum,](https://forum.rasa.com/) too 🤗

**Comment by erohmensing** [comment]
@simonm3 when you say that the same entity is there, is the actual NLU example still different? Maybe you can provide some datasets of before and after split and point out where you think there is an issue.

**Comment by simonm3** [comment]
NLU split is fine but the same entity can occur in multiple NLU examples
and these can be in both train and test. Whilst it is training both
together I suspect it overstates entity performance versus having in either
train or test rather than both.

e.g.
this is [person](simon)
that is [person](simon)
