### ISSUE TITLE
Rasa 3.0 version migration documentation

### ISSUE THREAD

**Issue by souvikg10** [RasaHQ/rasa#10435]
### Rasa Open Source version

3.0.0

### Python version

3.8

### What operating system are you using?

Linux

### What happened?

In the version migration, one point which seems to be missing for custom components migration is the fact the 
`process` method now accepts List[Message] instead of previously accepted Message object if your components depends on the featurizers or even tokenizers . 

Could be a useful addition since `process` method is quite a significant one. 

`def process(self, messages: List[Message]) -> List[Message]:`

Also Curious as to why? I always assumed only one message is processed at a time.

**Comment by sara-tagger** [comment]
Thanks for raising this issue, @TyDunn will get back to you about it soon✨

###### Please also check out the [docs](https://rasa.com/docs/) and the [forum](https://forum.rasa.com/) in case your issue was raised there too 🤗

**Comment by joejuzl** [comment]
Hi @souvikg10 please see the section "Handling Lists of Messages During Inference in an NLU Component" in the [migration guide](https://rasa.com/docs/rasa/migration-guide).
Does this cover what you're looking for?

**Comment by souvikg10** [comment]
Yeah that's exactly what i meant. I wonder how i missed it when i checked the documentation earlier.
