### ISSUE TITLE
Update the "Pipeline components" part of the documentation

### ISSUE THREAD

**Issue by s-montes-majorel** [RasaHQ/rasa#10445]
### What problem are you trying to solve?

I believe som parts of the documentation are out of date. The one that I find more salient is everything related to `linear_norm`. Even though it is not longer supported, the documentation says:

> Please try using `linear_norm` as the value for `model_confidence`. This should make it easier to tune fallback thresholds for the FallbackClassifier.

It would also be nice to have to update the comments regarding the selection of hyperparameters for the DIET component.

### What's your suggested solution?

 _No response_ 

### Examples (if relevant)

 _No response_ 

### Is anything blocking this from being implemented? (if relevant)

 _No response_ 

### Definition of Done

 _No response_

**Comment by sara-tagger** [comment]
Thanks for submitting this feature request 🚀 @b-quachtran will get back to you about it soon! ✨
