### ISSUE TITLE
fix `rasa test` when one token has multiple entity annotations

### ISSUE THREAD

**Issue by ka-bu** [RasaHQ/rasa#10451]
### Rasa Open Source version

2.8

### Python version

3.8

### What operating system are you using?

OSX

### What happened?

more context and initial solutions in #10394 (2.8.x) and #10404 (#3.0.x)

Definition of Done:
-  [x] The proposed solution investigated in terms of data format, generalizability across customers.
-  [x] Get other teams (CSE, Enable) aligned on the proposed solution
-  [x] #10780
    -  [x] Review the [PR](https://github.com/RasaHQ/rasa/pull/10475)
    -  [x] New version with enhancement released
    -  [x] Decide if the fix should be backported to `2.8.x`
    -  [x] Docs are updated

**Comment by JEM-Mosig** [comment]
We decided together with CSE that the proposed format is fine.

**Comment by JEM-Mosig** [comment]
PR merged into 2.8.x
