### ISSUE TITLE
Docs: Changelog entries since 2.8.14 have double links

### ISSUE THREAD

**Issue by erohmensing** [RasaHQ/rasa#10452]
See screenshot! I found these on the 2.x docs (the 3.x docs don't actually contain the changelog entries from 2.8.14 and 2.8.15

![image](https://user-images.githubusercontent.com/22333512/144606972-dbf66332-cd6b-4e2f-9eb6-4c721d82056d.png)

**Comment by m-vdb** [comment]
this is human error; I've commented on the PRs that led to the issue. The changelog can be fixed manually (on 2.x and main) now
