### ISSUE TITLE
Rasa 1.0 Forms stopped working in Rasa 2.8.x without change in code or version upgrade.

### ISSUE THREAD

**Issue by NareshDen** [RasaHQ/rasa#10457]
### Rasa Open Source version

> 2.8.0 ( also 2.7.0 )

### Rasa SDK version

2.8.0 ( 2.7.0 )

### Rasa X version

 _No response_ 

### Python version

3.6

### What operating system are you using?

Linux

### What happened?

Rasa 1.0 form were working, and suddenly it stopped working. The version of rasa was 2.8.2 and was tried on 2.8.0 and even 2.7.0 version also. Code was on production and it worked before November 10th. The temp solution was to remove forms 1.0 definition. The question is why the same code worked before. Here is the log for working and non working forms.

[not-working.log](https://github.com/RasaHQ/rasa/files/7656771/not-working.log) [working.log](https://github.com/RasaHQ/rasa/files/7656772/working.log)

### Command / Request

<pre>/initialise_conversation

version: "2.0"
 rules:

*   rule: Initialise a conversation
     conversation_start: true
     steps:
*   intent: initialise_conversation
*   action: voice_initialise_conversation_form
*   active_loop: voice_initialise_conversation_form
*   active_loop: null</pre>

### Relevant log output

<pre>Working logs, in non working forms it was missing.

021-11-11 08:53:41 DEBUG rasa_sdk.executor - Received request to run 'voice_initialise_conversation_form'
 2021-11-11 08:53:41 DEBUG rasa_sdk.forms - There is no active form
 2021-11-11 08:53:41 DEBUG rasa_sdk.forms - Activated the form 'voice_initialise_conversation_form'
 2021-11-11 08:53:41 DEBUG rasa_sdk.forms - No pre-filled required slots to validate.
 2021-11-11 08:53:41 DEBUG rasa_sdk.forms - Validating user input '{'intent': 

 {'name': 'initialise_conversation', 'confidence': 1.0} 

, 'entities': [], 'text': '/initialise_conversation', 'message_id': 'a879cdbd85f349958ed48ee6e9013514', 'metadata': {'slots': {'phone_number_type': 'mobile'}}, 'intent_ranking': [

 {'name': 'initialise_conversation', 'confidence': 1.0} 

]}'
 2021-11-11 08:53:41 DEBUG rasa_sdk.executor - Finished running 'voice_initialise_conversation_form'</pre>

**Comment by z-bodikova** [comment]
@alwx - this is the issue we talked about in #on-point - I think we should time-box it and was hoping you could give me an idea what an appropriate time box for this investigation (I was thinking maybe 4-6 hrs) would be and when you can spend that time on this - especially since you are not in the firefighting crew this week... Let me know.

**Comment by m-vdb** [comment]
Closing as 1.x is no longer supported.
