### ISSUE TITLE
Rasa Docker container stops responding

### ISSUE THREAD

**Issue by TheDome** [RasaHQ/rasa#10453]
### Rasa Open Source version

2.8.7

### Rasa SDK version

 _No response_ 

### Rasa X version

 _No response_ 

### Python version

3.8

### What operating system are you using?

Linux, Cloud (AWS / GCP / AZURE)

### What happened?

Hi there, I am currently using

<div class="table-wrap">
  | Rasa Open Source Docker Image | 2.8.7 | | Python | 3.8.10 | | asyncio-nats-client | 0.11.4 | | asyncio | 3.4.3 | | Docker | 20.10.11, build dea9396 | | Kernel | Linux server 5.11.0-1021-azure #22~20.04.1-Ubuntu SMP Fri Oct 29 01:11:25 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux | 
</div>

on my cloud server. Now I am running a Rasa instance to parse messages against my pre-trained model like the following code describes it:

<pre>from rasa.model import (
 get_latest_model,
 get_model,
 get_model_subdirectories,
 unpack_model,
 )
 import rasa
 import rasa.core.interpreter

1.  <span class="error">[... train the model externally and put the model in the model_path ...]</span>

model_path = get_model(str(model_path))

core_model, nlu_model = get_model_subdirectories(model_path)
 interpreter = rasa.core.interpreter.create_interpreter(nlu_model)

def parse(message)
 return interpreter.parse(message)

1.  while
     await NATS.subscribe(queue, cb=process_handler)("parse", parse)
2.  end</pre>

this works as intended, but sometimes it happens, that the Container hangs and does not respond to external events anymore. Even a `docker kill` or `SIGKILL` does not stop the process from existing. So I am left with a process, which seems be out of control and only a restart of the VM solved the problem. Since I plan to switch to Kubernetes I would like to know if anyone could help me resolve this issue. This kinda blocks me since I will not be able to restart worker nodes on the fly.

There is no relevant log from rasa nor tensoflow and I am out of idea on how to solve this issue. Any help is appreciated!

### Command / Request

 _No response_ 

### Relevant log output

 _No response_

**Comment by sara-tagger** [comment]
Thanks for the issue, @kalkbrennerei will get back to you about it soon!

###### You may find help in the [docs](https://rasa.com/docs/) and the [forum,](https://forum.rasa.com/) too 🤗

**Comment by RASADSA** [comment]
Hello @kalkbrennerei 👋 
can you provide some more input on Hardware / OS and also some logs of your system from docker to elaborate more the problem ?
thanks

**Comment by TheDome** [comment]
Of course! 
I am using
| Version | Component | 
|---|---| 
| Linux server 5.11.0-1021-azure #22~20.04.1-Ubuntu SMP Fri Oct 29 01:11:25 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux | OS |
| 4x Intel(R) Xeon(R) Platinum 8272CL CPU @ 2.60GHz | CPU |
| 8GiB | RAM |

RASA itself does not produce any logs except for 
```
[server.nlu.run_1] - [INFO] Received a message on 'nlu.parse'
[server.nlu.run_1] - [INFO] [de-DE] Parsing request: Objekt 4
```
which is a log I have implemented in my python server. 
However I am still digging through the system logs and will provide something if I find anything suspicious. 
I have created a stacktrace of the hanging process being stuck at:
```
(gdb) bt full
#0  0x00007fda04ead5ce in epoll_wait () from target:/lib/x86_64-linux-gnu/libc.so.6
No symbol table info available.
#1  0x00007fd9bdfd35d9 in uv__io_poll (loop=loop@entry=0x5af9cb0, timeout=119818) at src/unix/linux-core.c:309
        no_epoll_pwait = 0
        no_epoll_wait = 0
        events = {{events = 1074921472, data = {ptr = 0x4b14000040120000, fd = 1074921472, u32 = 1074921472, u64 = 5409949053453729792}}, {events = 0, data = {ptr = 0x4012000040120000, fd = 1074921472, u32 = 1074921472, u64 = 4616752569083101184}}, {events = 0, data = {ptr = 0x0, fd = 0, u32 = 0, u64 = 0}}
```
which does not seem to be a rasa issue by its own. However any other container I have created does not stop in this state.

**Comment by RASADSA** [comment]
Hello @TheDome 

this is just a hunch - it looks like a virtualisation issue from azure - if you use GPU resources make sure that they are booked 1:1 and dont overscale the provided resources.
beside that the GDB trace shove a problem a loobback device (?) - which is odd.

closing the issue since this is not rasa related from what information was provided.
