### ISSUE TITLE
Support spaCy `trf` models inside of Rasa

### ISSUE THREAD

**Issue by koaning** [RasaHQ/rasa#10477]
### What problem are you trying to solve?

SpaCy comes with transformer models. I've noticed people asking for them ([exhibit A](https://github.com/RasaHQ/rasa/issues/10449)) so maybe it's time to implement them. Supporting this feature would involve adding another dependency to the toolchain though.

@dakshvar22 do you have any strong opinions on this? I'm willing to pick this up if there's consensus on how we might want to support this.

**Comment by cqx931** [comment]
hi! Does rasa support the `trf` models now? The issue is closed without further explanation on the current state.

**Comment by m-vdb** [comment]
hello @cqx931 , no it doesn't, but if you read the comment above, the issue as been migrated to Jira 😄
