### ISSUE TITLE
Website UI bug on mobile web version

### ISSUE THREAD

**Issue by Horizon733** [RasaHQ/rasa#10474]
### Rasa Open Source version

Na

### Rasa SDK version

Na

### Rasa X version

Na

### Python version

Other

### What operating system are you using?

Other

### What happened?

[<span class="image-wrap" style="">![](https://user-images.githubusercontent.com/57827233/144892850-5ab156bc-72f0-4a52-9df6-373983d72124.jpg)</span>](https://user-images.githubusercontent.com/57827233/144892850-5ab156bc-72f0-4a52-9df6-373983d72124.jpg) In the above screenshot as you can see, the navbar is overlapping the menu box. Also, it doesn't stick on top of screen and it changes its position when clicked on hamburger. Please fix this, since looking at docs on mobile web version quite difficult.

### Command / Request

 _No response_ 

### Relevant log output

 _No response_

**Comment by sara-tagger** [comment]
Thanks for raising this issue, @desmarchris will get back to you about it soon✨

###### Please also check out the [docs](https://rasa.com/docs/) and the [forum](https://forum.rasa.com/) in case your issue was raised there too 🤗

**Comment by m-vdb** [comment]
Docs are currently not mobile friendly. Closing as won't fix
