### ISSUE TITLE
Unable to build the docker image for duckling 

### ISSUE THREAD

**Issue by swagat576** [RasaHQ/rasa#10489]
### Rasa Open Source version

2

### Rasa SDK version

 _No response_ 

### Rasa X version

 _No response_ 

### Python version

3.6

### What operating system are you using?

Linux

### What happened?

I m not able to build the docker image for the duckling repo. the [console log](https://github.com/swagat576/duckling/runs/4456476884?check_suite_focus=true) @sara-tagger please look into it.

### Command / Request

 _No response_ 

### Relevant log output

[ _No response_ | [https://github.com/swagat576/duckling/runs/4456476884?check_suite_focus=true](https://github.com/swagat576/duckling/runs/4456476884?check_suite_focus=true)]

**Comment by sara-tagger** [comment]
Thanks for raising this issue, @yennycheung will get back to you about it soon✨

###### Please also check out the [docs](https://rasa.com/docs/) and the [forum](https://forum.rasa.com/) in case your issue was raised there too 🤗
