### ISSUE TITLE
Allow use of env-variables in endpoints-configuration

### ISSUE THREAD

**Issue by IgNoRaNt23** [RasaHQ/rasa#10490]
### What problem are you trying to solve?

We're deploying and working with Rasa Bots in a lot of (slightly) different environments. It would be helpful if it was possible to use env variable placeholders in the endpoints-configuration.

### What's your suggested solution?

Allow env variable placeholders (example below) instead of explicit values in the endpoints configuration. These should be possible for every entry.

### Examples (if relevant)

Instead of having the url for the mongo tracker-store explicitly here like this

tracker_store: type: mongod url: mongodb://localhost:27017 ....

it like to be able to write something like this

tracker_store: type: mongod url: $MONGO_URL ....

On start, rasa should check if the env variable MONGO_URL is set and use it's value if it's set. In case it is not set (None), raise an exception.

### Is anything blocking this from being implemented? (if relevant)

I dont think so.

### Definition of Done

 _No response_

**Comment by sara-tagger** [comment]
Thanks for submitting this feature request 🚀 @alopez will get back to you about it soon! ✨

**Comment by IgNoRaNt23** [comment]
Does anyone ever look at this?

**Comment by mausch** [comment]
This issue is marked "closed as completed" with no explanation on where it was done, where the documentation is.

I went searching for it in Jira and turns out it's still an open issue: https://rasa-open-source.atlassian.net/jira/software/c/projects/OSS/issues/OSS-524

**Comment by m-vdb** [comment]
Hello @mausch, as per [my comment](https://github.com/RasaHQ/rasa/issues/10490#issuecomment-1354533104) above, we migrate this issue to Jira.

**Comment by mausch** [comment]
@m-vdb Problem is it says it's "completed" here, which leads to misunderstandings.
Also no link to the issue on jira.

My comment was just to clarify things for anyone else landing on this github issue from search (as I did)
