### ISSUE TITLE
Conversation flow builder for Rasa

### ISSUE THREAD

**Issue by srinivasupadhya** [RasaHQ/rasa#10520]
### What problem are you trying to solve?

Provide ability for non devs to setup conversation flow (story based, rule based etc.)

### What's your suggested solution?

Have a UX something like [https://github.com/alyssaxuu/flowy](https://github.com/alyssaxuu/flowy) . This is in line with what Microsoft Power Virtual Agent (PVA) / similar products provide users to help setup bots easily. This can enable RASA to become a SaaS solution for bots.

### Examples (if relevant)

*   [Microsoft PVA](https://powervirtualagents.microsoft.com/en-us/)
*   [Chatbot.com](https://www.chatbot.com/)
*   [Kairon](https://www.digite.com/kairon/)

### Is anything blocking this from being implemented? (if relevant)

Too much dev bandwidth being spent on setting up bot conversations

### Definition of Done

Non devs should be able to create, test & deploy RASA bots

**Comment by srinivasupadhya** [comment]
Wanted to understand from the team on challenges you anticipate if we go down the path of building a Tree based UX to enable non devs to setup RASA flows. Few we can see right away:
* Forms (validation, activating & deactivating)
* Custom actions (for now we are hoping to have ability to list all custom actions from which users can choose from)

**Comment by sara-tagger** [comment]
Thanks for submitting this feature request 🚀 @aeshky will get back to you about it soon! ✨

**Comment by srinivasupadhya** [comment]
@aeshky let me know if you need more info for this one
