### ISSUE TITLE
More robust solution for Hugging Face (LanguageModelFeaturizer) files used by CI pytest and CI model regression tests

### ISSUE THREAD

**Issue by koernerfelicia** [RasaHQ/rasa#10528]
### What problem are you trying to solve?

We download the required files for unit tests in the `make prepare-transformers` target. See [here](https://github.com/RasaHQ/rasa/pull/7768). However, there are some issues with this:

*   The cache file names are hard-coded based off of the default cache location for transformers. This isn't robust, for example, to updates to `transformers`, and will become a problem whenever we upgrade and the default location changes (this also already failed for Windows and was unnoticed for a while before it was fixed [here](https://github.com/RasaHQ/rasa/pull/10262))
*   if a pytest is added that requires a model not in that list it will result in flakey tests as the model now needs to be downloaded during the test itself
*   downloading within the pytest is often unsuccessful and when it fails, we see flakey and confusing tests because this crashes the workers (see [here](https://rasa-hq.slack.com/archives/C36SS4N8M/p1636978814322300))

For the model regression tests, we do not run this step, but download the model once training has started. This can cause failures as well (see [here](https://rasa-hq.slack.com/archives/C8LEHMTAM/p1638786577149900))

### What's your suggested solution?

A solution might:

*   safeguard against additions where a model is used that wasn't cached during by the target(maybe a failing CI check? some sort of registry that is checked before running a test?) OR programmatically determine which models will need to be downloaded and do this before tests are run.
*   programmatically determine default cache location and cache file naming, rather than hard-coding these. This may be dicey because we might have to call transformers code, and it would mean we need to install transformers before this step.
*   restore models from our own cache/mirror rather than getting them from hugging face
*   also be available to model regression tests
*   not be in the Makefile at all, but rather (for example) a ~~pytest setup type fixture~~ python script run before tests begin. The only reason this was done in Make initially was to mirror the Mitie and Spacy setup, but these are obviously simpler.
*   make some gains s.t. the models are only downloaded before tests that actually need them (atm we download all of them before any set of tests)

### Examples (if relevant)

 _No response_ 

### Is anything blocking this from being implemented? (if relevant)

 _No response_ 

### Definition of Done

 _No response_

**Comment by koernerfelicia** [comment]
I recognise this is a bunch of random ideas for improvement. I am happy to collaborate on this, but need some input from Infra/DevOps on how to go about a better solution.

Small helper I've used to determine these hard-coded values:

```
from rasa.nlu.utils.hugging_face.registry import model_tokenizer_dict, model_class_dict

MODEL_WEIGHTS = "rasa/LaBSE"
MODEL_NAME = "bert"

model_tokenizer_dict[MODEL_NAME].from_pretrained(MODEL_WEIGHTS)
model_class_dict[MODEL_NAME].from_pretrained(MODEL_WEIGHTS)

"""
Set breakpoints in transformers.modeling_tf_utils.from_pretrained and 
transformers.tokenization_utils.from_pretrained
"""
```

**Comment by tmbo** [comment]
Is there a way to place the needed files in a known location and do the setup parts in pytest fixtures as you said? I think that would even be a solution that doesn't require work by the infrastructure team.

**Comment by koernerfelicia** [comment]
Actually I think I was wrong about this (edited the original statement to clarify). Pytest fixtures are not suited: it's more of a one-time download step that should happen before pytests run (esp. because we parallelize pytest jobs).

It's a bit tricky because the files needed can only be determined by looking at the tests themselves: rn we need files A, B, C, D, but there is nothing stopping someone from adding a test that needs E. In fact, this has already happened, and resulted in flakiness. The current solution requires someone to figure out which files are needed by tracing transformers code 👎 

I'm not sure about the best way to do this without requiring devs to have to remember to expand a list of needed files, which is probably unrealistic. 

We could also consider just downloading all files one could possibly need. It's not totally fool-proof because the list may change, especially after upgrading transformers.

Again, happy to do legwork, but I do think I need some help brainstorming best ways to do this, main questions from me are:
- How do we determine what files will be needed *before* we run tests? All I need is the `LanguageModelFeaturizer` config for any configs that we will test with, and I can go from there.
- How do we download the files in the setup step of the workflow (i.e. before the pytests run)? IMO this would be easiest to do with a python script after transformers has been installed, is this acceptable?

**Comment by koernerfelicia** [comment]
Oh, and the third question would be:
- How to handle mirroring or whatever alternative to failed downloads?

But this could be saved for a V2 if the failed downloads become painful. Important thing to me is that we know that it failed because of a failed download, to avoid devs thinking that the test itself is failing.

So with that said, happy for this issue to be moved to a different squad's board as you see fit.

**Comment by tmbo** [comment]
> I'm not sure about the best way to do this without requiring devs to have to remember to expand a list of needed files (or configs), which is probably unrealistic.
> We could also consider just downloading all files one could possibly need. It's not totally fool-proof because the list may change, especially after upgrading transformers.

I mean, you can also just download the ones you need and in general prevent pytest from trying to download any non cached files. (e.g. taking inspiration from https://blog.jerrycodes.com/no-http-requests/) This gives you the benefit of sticking to the files that we actually need and also allows you to fail with a proper error message if a test tries to request a file that it shouldn't (e.g. because the library has been updated or because an additional feature has been added that requires additional files).

**Comment by koernerfelicia** [comment]
That's great! 💡 I think then we can just do this and keep a list of configs that people need to update, and they will get a failing test if they haven't.

As for downloading the models, can we do this in a python script to run after transformers has been installed, but before tests are run? This would do away with having to translate a config to the files that will be needed by hand

**Comment by tmbo** [comment]
I am not sure how this file lookup works, so this might be a naive question: why can't we put the files at a known location and point whoever needs them to that location? or is that not a single configuration but needs to be configured in multiple places?

**Comment by koernerfelicia** [comment]
I'll try to explain the problem better (bear with me, also happy to hop on a call if it is helpful):

We only ever specify a language model and optionally the weights in the config:
```
  - name: LanguageModelFeaturizer
    # Name of the language model to use
    model_name: "bert"
    # Pre-Trained weights to be loaded
    model_weights: "rasa/LaBSE"
```

We have a registry that lists the possible models, and it also lists the default weights for each model. However, we can also specify different weights that are not listed in the registry (see [here](https://github.com/RasaHQ/rasa/blob/main/tests/nlu/featurizers/test_lm_featurizer.py#L423), for example, we load weights for Chinese).

For each model/weights there are different files that need to be downloaded (see [here](https://github.com/RasaHQ/rasa/blob/main/data/test/hf_transformers_models.txt#L11-L16) for the `bert-base-chinese` files). Normally, the files being downloaded are hidden from the user as well as Rasa developers and in fact determining what files we need to check the cache for and resolving whether they are in the cache is taken care of by transformers. The config above corresponds to the files below being loaded from the cache. The list is of pairs: the first is the source of the file, and the second item the hash it needs to be renamed to for `transformers` to deal with it:

```
https://s3.amazonaws.com/models.huggingface.co/bert/rasa/LaBSE/vocab.txt
21aa38329c730774d9f45df9ec5443a9bd4abd2191e1d510c27647c151c5437f.f2539f82b1008971c6ea6574f078d95c6eead57223fc74fdc420013fa9de391a
https://s3.amazonaws.com/models.huggingface.co/bert/rasa/LaBSE/special_tokens_map.json
99497d78492c90ab7d824d695b9a8d043369fbc2bf1112dcc7cdef9a6c4fa691.275045728fbf41c11d3dae08b8742c054377e18d92cc7b72b6351152a99b64e4
https://s3.amazonaws.com/models.huggingface.co/bert/rasa/LaBSE/tokenizer_config.json
527f618330e845c9d31826e7d9ce983aa816fafcf4f29f8c52f8ae1fdd097219.1c61d5d3dc67d88e0c74c64cda9b17bc30bdbd1c373cceeb740b9953729709aa
https://s3.amazonaws.com/models.huggingface.co/bert/rasa/LaBSE/config.json
90984a8da5021905af8679644b61bc5428ef16e9a307469152c163ec873db240.f1ba7080a92fc164a144311742f36dfb6a724bc9da532264b30d87040e15cc9d
https://cdn.huggingface.co/rasa/LaBSE/tf_model.h5
fd2ff7409cd4abbce31d54b8acebc305939787751dd697b6f38a3bf1f197a614.2589e15ea34b96d9bdcc478748ae77b629487da363566089fe6a8cdb1e6ea284.h5
```

I am pretty sure these can't be determined without actually running the transformers methods `from_pretrained` for both the model and tokenizer, and this is just a massive method that does a bit more than what we want, i.e. also constructs the classes when all we really want is:
- what files are needed
- what filename they are cached as
- where to download fresh copies of files
 (see [here](https://github.com/huggingface/transformers/blob/v2.4.1/src/transformers/modeling_tf_utils.py#L192-L390) for the models).

I think easiest + most future-proof if we can load transformers and use the same methods they are using to resolve hosts and cache file names (iirc some sort of hash).

Once they are named the correct thing and in the default HF transformers cache location it's very easy, no pointing needed. We *could* specify a non-standard cache location, but I don't think this is necessary, and it is just an added complexity.

**Comment by koernerfelicia** [comment]
So tbc: lookup isn't really the problem, it's the bullets listed up there

**Comment by markus-hinsche** [comment]
We just merged https://github.com/RasaHQ/rasa/pull/10834 which is somewhat related to this
