### ISSUE TITLE
Support for MongoDB 5

### ISSUE THREAD

**Issue by IgNoRaNt23** [RasaHQ/rasa#10539]
### What problem are you trying to solve?

We need to switch to MongoDB 5, since it offers support for TLS 1.3\. We're using the MongoTrackerStore and unfortunately current Rasa (3.0.2) has a constraint for Pymongo (<3.11). PyMongo supports MongoDB 5 from version 3.12 onwards.

### What's your suggested solution?

Make rasa compatible with PyMongo 3.12+

### Examples (if relevant)

 _No response_ 

### Is anything blocking this from being implemented? (if relevant)

 _No response_ 

### Definition of Done

*   [ ] Rasa allows usage of PyMongo 3.12+

**Comment by sara-tagger** [comment]
Thanks for submitting this feature request 🚀 @melindaloubser1 will get back to you about it soon! ✨

**Comment by IgNoRaNt23** [comment]
So, what happens next @melindaloubser1 ?

**Comment by melindaloubser1** [comment]
It's been added to the backlog, but is likely only to be addressed in the future unless you or someone else would like to submit a PR for it.

**Comment by SamuelNoB** [comment]
@melindaloubser1  I would like to contribute in this problem, as soon as possible i will start a PR for this

**Comment by SamuelNoB** [comment]
@melindaloubser1 i've submited a PR and it's waiting for approval
