### ISSUE TITLE
Offer option to influence stories or rules based on custom condition

### ISSUE THREAD

**Issue by JulianGerhard21** [RasaHQ/rasa#10538]
### What problem are you trying to solve?

Hi folks,

based on a discussion with @dakshvar22 I would like to discuss an issue that has been bothering me for some time. If you currently want to influence the course of a `story`or a `rule`, you can achieve this in the case of stories for example with `intents`, `slot` events and `custom actions` - based on which defined follow-up actions are then executed, in the case of rules you still have the possibility to specify `conditions` in the case of which a rule may become active.

I have now tried to influence story progression based on detected emotions, as I believe this will play a role in conversation progressions in the future.

I'd like to be able to define e.g. a story like this:

*   story: joy path steps:
*   intent: mention_purpose
*   slot_was_set:
*   emotion:
*   joy
*   shame
*   action: utter_something_politely

I have evaluated the following options:

1.  creating an `entity` and a `slot` with the same name
2.  `conditional response variants` based on a slot value
3.  an NLU `GraphComponent` that classifies the tracker's last message for emotions at each iteration
4.  a Policy `GraphComponent`, which classifies the last message of the tracker for emotions at each iteration

The extraction of emotions is performed with a multi-label approach, i.e. a user input can contain up to n emotions, where n was fixed by me to 30.

Variant 1 was implemented in such a way that the NLU `GraphComponent` fills the `entity` in the process method at each iteration and by the deliberately used slot-auto-filling option the `slot` was also filled.

The problem here is that both the entity and the slot actually contain a list of emotions, and a story/rule where the slot value is to be considered per `influence_conversation` only checks whether the list is filled or not in comparison - thus one would have to fundamentally modify this approach to make it work as desired. In addition, there is the fact that an emotion is not strictly speaking an entity and I wanted to avoid this approach anyway.

After consulting with @dakshvar22 , I created a slot with a custom slot mapping whose featurization can take n emotions into account. In combination with variant 1 the whole scenario works now - but I am not satisfied with it, because you need:

1.  An entity
2.  A custom action or NLU GraphComponent that populates the entity
3.  A slot with the same name
4.  An active auto-slot-filling, so that the slot takes the value of the entity
5.  The CustomMapping definition of the slot

In my mind, I wanted to be able to include a GraphComponent that does most of the above directly, so there are fewer dependencies.

When I implemented variant 2 with the policy, I later realized that I also need a slot here, but unlike in the NLU GraphComponent, I can set it via optional_events directly from the policy. This works for each iteration, but the prediction of a follow-up-action is based on a point in time of the storyline where this slot has not been set yet. Since there is no way to write a policy whose "result" is taken into account, e.g. via optional_events, even if another policy wins the race and predicts a follow-up-action, I've discarded this way for now.

### What's your suggested solution?

In my opinion, it would be a good thing if you were able to define conditions that you want to use in a story or rule yourself. I'm not sure yet how to best implement this, but I would like to be able to write the following story:

*   story: frustration and anger route steps:
*   intent: request_status_update
*   conditions:
*   path_to_my_custom_condition.emotion:
*   anger
*   frustration
*   action: utter_appointment
*   action: action_listen

Where the requirement here would be, similar to slots, that a condition must return a feature vector that the TEDPolicy can use to make its decision, for example. The custom condition could be passed e.g. the tracker, so that you can get all the contextual information you need in the implementation.

With this suggestion - which please be sure to check for anything I might have forgotten - one would solve the boundaries that currently lie on conditions regarding the slot mechanics. I wouldn't need anything from the list above - just the custom condition.

### Examples (if relevant)

 _No response_ 

### Is anything blocking this from being implemented? (if relevant)

 _No response_ 

### Definition of Done

 _No response_

**Comment by sara-tagger** [comment]
Thanks for submitting this feature request 🚀 @pythenry will get back to you about it soon! ✨

**Comment by kedz** [comment]
@JulianGerhard21 putting this in the research team's inbox to look at, but we probably won't be able to look at this until January.

**Comment by JEM-Mosig** [comment]
@JulianGerhard21 I think one could resolve it with a custom emotion-classifier NLU component that adds the emotions as metadata to the message, a custom (global) slot mapping that moves this metadata into a slot, and a custom slot that featurizes the emotion labels for the policy.
