### ISSUE TITLE
Dynamic lookup tables

### ISSUE THREAD

**Issue by Maxinho96** [RasaHQ/rasa#10554]
### What problem are you trying to solve?

There is a particular kind of entities that are dynamic, in the sense that:

*   Have values impossible to be defined at training time because they vary often
*   Are very difficult to be detected by a machine learning model because values are not meaningful

An example of a dynamic entity is the name of a folder. It could be literally anything (e.g. `apple`), so it's impossible to create training data for a ML model, there is no meaningful information in the folder name that tells it is a folder name. Also, folder names are created and modified by users, so they vary too often to think about a model retrain.

Currently, lookup tables have to be defined at training time, so they cannot be used to solve the problem.

A solution that I found is defining a custom entity extractor component that fetches the entity values and then extracts them from the sentence, but it would be nice to have a native way in Rasa to do this.

### What's your suggested solution?

Add the possibility for lookup tables to be dynamic, by giving the developer the possibility to define a function that fetches the examples, rather than only a fixed list of examples. The fetch function will be called before the RegexEntityExtractor processes the input, at every interaction with the bot. It is responsibility of the developer to cache the data to avoid slow interactions in the case the fetch requires a relevant amount of time.

### Examples (if relevant)

 _No response_ 

### Is anything blocking this from being implemented? (if relevant)

 _No response_ 

### Definition of Done

 _No response_

**Comment by sara-tagger** [comment]
Thanks for submitting this feature request 🚀 @mvielkind will get back to you about it soon! ✨
