### ISSUE TITLE
How to using a custom path for web hooks in rasa custom connector?

### ISSUE THREAD

**Issue by gongshaojie12** [RasaHQ/rasa#10552]
### Rasa Open Source version

2.2.3

### Rasa SDK version

 _No response_ 

### Rasa X version

 _No response_ 

### Python version

3.6

### What operating system are you using?

Linux

### What happened?

I am using a custom channel connector, but the URL is `http://<host>:<port>/webhooks/myio/webhook`, I want to use a custom URL, for example: `http://<host>:<port>/chatbot/v1`. What should I do? Thanks!

### Command / Request

 _No response_ 

### Relevant log output

 _No response_

**Comment by sara-tagger** [comment]
Thanks for the issue, @ancalita will get back to you about it soon!

###### You may find help in the [docs](https://rasa.com/docs/) and the [forum,](https://forum.rasa.com/) too 🤗

**Comment by gongshaojie12** [comment]
I hope rasa can implement custom endpoints.Thanks!
