### ISSUE TITLE
Can i connect payment method in rasa? chat continue if user paid money

### ISSUE THREAD

**Issue by ganbaaelmer** [RasaHQ/rasa#10557]
### What problem are you trying to solve?

i mean i need to connect master card or visa card in rasa. so if user paid money to us then chat can continue. i mean paid Answer system.

### What's your suggested solution?

 _No response_ 

### Examples (if relevant)

 _No response_ 

### Is anything blocking this from being implemented? (if relevant)

 _No response_ 

### Definition of Done

 _No response_

**Comment by sara-tagger** [comment]
Thanks for submitting this feature request 🚀 @jupyterjazz will get back to you about it soon! ✨

**Comment by jupyterjazz** [comment]
hi @ganbaaelmer,
the Stripe API (for payment methods) with [custom actions](https://youtu.be/rvHg7N8ux2I) could be a way to go. However, I'd suggest to be careful with identity management.
