### ISSUE TITLE
Tokenizers section over-indented on the Components page 

### ISSUE THREAD

**Issue by Polaris000** [RasaHQ/rasa#10553]
### Rasa Open Source version

3.x

### What happened?

The "Tokenizers" section is over-indented on the Components page of the docs. Apart from the obvious inconsistency, it's causing the "Tokenizers" heading to not appear in the TOC on the right.

[Reference](https://rasa.com/docs/rasa/components#tokenizers)

**Comment by Polaris000** [comment]
This seems to be a very minor fix and would be happy to send a PR.

**Comment by sara-tagger** [comment]
Thanks for raising this issue, @rctatman will get back to you about it soon✨

###### Please also check out the [docs](https://rasa.com/docs/) and the [forum](https://forum.rasa.com/) in case your issue was raised there too 🤗

**Comment by Polaris000** [comment]
Hey @rctatman! Please have a look when you're available

**Comment by Polaris000** [comment]
Hi @rctatman. Any updates on this?
