### ISSUE TITLE
rasa.core.brokers.kafka Failed with error: encoding without a string argument

### ISSUE THREAD

**Issue by tvadim** [RasaHQ/rasa#10567]
### Rasa Open Source version

2.8.16

### Rasa SDK version

 _No response_ 

### Rasa X version

 _No response_ 

### Python version

3.8

### What operating system are you using?

Linux

### What happened?

We're using Azure Event Hub service to receive events from Rasa server. Event broker configuration:

event_broker: type: kafka security_protocol: SASL_SSL topic: $

 {BROKER_TOPIC} 

partition_by_sender: True url: $

 {BROKER_HOST} 

:9093 sasl_username: "$ConnectionString" sasl_password: $

 {BROKER_PASSWORD} 

sasl_mechanism: PLAIN

The configuration worked well until we upgraded to Rasa OSS 2.8.16

This [PR](https://github.com/RasaHQ/rasa/pull/10413) sends RASA_ENVIRONMENT as a header to Kafka producer. The problem occurs when RASA_ENVIRONMENT is not set:

"logger":"rasa.core.brokers.kafka","message":"Could not publish message to kafka url '...'. Failed with error: encoding without a string argument"

### Command / Request

 _No response_ 

### Relevant log output

 _No response_

**Comment by ePreda** [comment]
So, quick checking shows that this is essentially a NoneType error in 3.8. Simply setting a default to empty string would fix this.

As a side, we should be unit testing all the data handling before it reaches the producer, including things like header. Adding it in this fix.
