### ISSUE TITLE
RegexMessageHandler shoul be at the beginning of the pipeline

### ISSUE THREAD

**Issue by Maxinho96** [RasaHQ/rasa#10561]
### Rasa Open Source version

3.0.2

### Rasa SDK version

3.0.2

### Rasa X version

 _No response_ 

### Python version

3.8

### What operating system are you using?

Windows

### What happened?

The RegexMessageHandler component, that handles explicit intents like "/buy

 {"entity":"value"} 

", should process the text at the beginning of the pipeline, not at the end. Processing at the end might cause issues, for example I have a custom component in the pipeline that modifies the user text, and this leads to an incorrect detection of the intent.

### Command / Request

 _No response_ 

### Relevant log output

 _No response_

**Comment by sara-tagger** [comment]
Thanks for raising this issue, @aeshky will get back to you about it soon✨

###### Please also check out the [docs](https://rasa.com/docs/) and the [forum](https://forum.rasa.com/) in case your issue was raised there too 🤗

**Comment by JEM-Mosig** [comment]
Did this already trigger an actual bug / is this blocking you, or is this a hypothetical problem?

**Comment by Maxinho96** [comment]
> Did this already trigger an actual bug / is this blocking you, or is this a hypothetical problem?

I have a custom component in the pipeline that modifies the user text, and it modifies also the texts that start with /intent , so the RegexMessageHandler receives an altered text and misses the intent/entity detection.
As a workaround, I let my component skip the text substitution if the input starts with / , but it would be nice that RegexMessageHandler processes the text before all other components to avoid issues like this, and also to have a faster computation time (it is unnecessary that all rasa NLU components process the text if the intent and entities are explicitly stated).
