### ISSUE TITLE
Bert model with AlbertTokenizer problem

### ISSUE THREAD

**Issue by ganbaaelmer** [RasaHQ/rasa#10584]
### Rasa Open Source version

2.8.16

### Rasa SDK version

2.8.3

### Rasa X version

0.42.6

### Python version

3.8

### What operating system are you using?

Linux

### What happened?

the error came from a HF model using a different tokenizer  (e.g. BertModel with AlbertTokenizer), breaks due to the hard coded mapping in registry.py.

https://forum.rasa.com/t/how-to-import-huggingface-models-to-rasa/50238

**Comment by sara-tagger** [comment]
Thanks for raising this issue, @aeshky will get back to you about it soon✨

###### Please also check out the [docs](https://rasa.com/docs/) and the [forum](https://forum.rasa.com/) in case your issue was raised there too 🤗

**Comment by ganbaaelmer** [comment]
@aeshky please help us

**Comment by mleimeister** [comment]
This is not a bug but rather a known limitation of the current implementation. The documentation has been updated to clarify which models work with the current version of `LanguageModelFeaturizer` here: https://github.com/RasaHQ/rasa/issues/10385
Exploratory work on how it can be improved and allow loading arbitrary models is already happening (https://github.com/RasaHQ/rasa/issues/6307, https://github.com/RasaHQ/rasa/pull/10624), therefore this ticket could be closed imo.

**Comment by aeshky** [comment]
Thanks for looking into this @mleimeister. I'm closing this issue based on your comment.

**Comment by mleimeister** [comment]
@ganbaaelmer Please follow [this ticket](https://github.com/RasaHQ/rasa/issues/6307) for further updates on the progress.
