### ISSUE TITLE
is it possible to 100000 intents?

### ISSUE THREAD

**Issue by ganbaaelmer** [RasaHQ/rasa#10593]
### What problem are you trying to solve?

is it possible to 100000 intents? Rasa can handle 10000 response?

### What's your suggested solution?

 _No response_ 

### Examples (if relevant)

 _No response_ 

### Is anything blocking this from being implemented? (if relevant)

 _No response_ 

### Definition of Done

 _No response_

**Comment by sara-tagger** [comment]
Thanks for submitting this feature request 🚀 @joejuzl will get back to you about it soon! ✨

**Comment by koaning** [comment]
The word "possible" is always possible, but I'm more concerned if it's pragmatic. 

Just so I understand, what is the use-case? Do you have 100_000 intents with 20 examples each? What domain?

**Comment by ganbaaelmer** [comment]
@koaning  Law domain. Theres is so many cases in law domain. so need to divide specifically. i mean its around 10,000 answers and infinite questions (100,000).

**Comment by koaning** [comment]
Yeah, part of me is wondering if what you're trying to do here is perhaps more of a "search" problem than a "intent detection" problem. Is this like a FAQ kind of situation?

**Comment by ganbaaelmer** [comment]
@koaning  yes almost same as FAQ

**Comment by koaning** [comment]
Part of me is thinking this is perhaps best implemented with a custom action and using a tool like ElasticSearch in the backend. 

@dakshvar22 might know more about the limits of the response selector though.

**Comment by ganbaaelmer** [comment]
@koaning  Elastic search is for **keyword** search right?
i need context search not keyword search. Please help me? What should i do?

**Comment by koaning** [comment]
There's also tools like [jina](https://jina.ai/) that can add "more context" but it'll still be a search engine. Note that ElasticSearch also supports text similarity search with [vector fields](https://www.elastic.co/blog/text-similarity-search-with-vectors-in-elasticsearch).

Before investing in a lot of tech, I would try to test your use case with end-users as early as possible though. It might be that out of the 100_000 questions only 100 of them get asked 99% of the time.

**Comment by ganbaaelmer** [comment]
@koaning if i use elastic search in custom action. so how to train conversation after using elastic search? ( in my rasa x)
i think your DIET model is training my model after tagging intents correctly by rasa x?
Problem is elastic search is fixid vectors not updated by rasa x. i mean no more training is possible after using elastic search vector.

**Comment by ganbaaelmer** [comment]
@koaning @dakshvar22  please help me

**Comment by dakshvar22** [comment]
Can you show some examples of a few intents? I would like to see the granularity at which you are defining the intents.

**Comment by sky-2002** [comment]
> Exalate commented:
> 
> ganbaaelmer commented:
> 
> @koaning Elastic search is for **keyword** search right? i need context search not keyword search. Please help me? What should i do?

May be you could try out [weaviate](https://weaviate.io/) vector search engine and database. It vectorizes text based on BERT models so as to capture context.

**Comment by m-vdb** [comment]
Closing as this is more a question / discussion for the forum. If you're still interested in finding the answer, feel free to repost it here: https://forum.rasa.com/
