### ISSUE TITLE
rasa.shared.core.trackers  - Tried to set non existent slot '' Make sure you added all your slots to your domain file.

### ISSUE THREAD

**Issue by Hendler** [RasaHQ/rasa#10591]
### Rasa Open Source version

3.0.4

### Rasa SDK version

 _No response_ 

### Rasa X version

 _No response_ 

### Python version

3.8

### What operating system are you using?

OSX

### What happened?

Many replicated errors in the log `rasa.shared.core.trackers - Tried to set non existent slot '<span class="error"><span class="error">[removed_slot_name]</span></span>' Make sure you added all your slots to your domain file.`

Retraining, deleting cache, restarting all did not resolve the issue. Deleting the tracker store data (Postgresql) (all of events) resolved the issue.

My guess is that the loading of tracker data has a persisted slot with a sender_id, and upon loading in a session the data tries to set a slot, but the slot does not exist. I haven't dug into the rasa code that starts a session, but my guess is that a check to see if a slot exists before setting it could eliminate the issue.

I don't know if this issue was transient and that it would have disappeared after max_history, but even with what seemed to be one slot actually set, it would produce nearly a hundred log entries, somewhat alarming.

This occurred after removing a slotset from a custom action and removing the slot a domain and rule. See also [https://github.com/RasaHQ/rasa/issues/3294](https://github.com/RasaHQ/rasa/issues/3294) [https://github.com/RasaHQ/rasa/issues/10239](https://github.com/RasaHQ/rasa/issues/10239) [https://github.com/RasaHQ/rasa/issues/4887](https://github.com/RasaHQ/rasa/issues/4887)

### Command / Request

 _No response_ 

### Relevant log output

 _No response_

**Comment by sara-tagger** [comment]
Thanks for the issue, @NareshDen will get back to you about it soon!

###### You may find help in the [docs](https://rasa.com/docs/) and the [forum,](https://forum.rasa.com/) too 🤗
