### ISSUE TITLE
ERROR: rasa-sdk 3.0.2 has requirement urllib3<2.0.0,>=1.26.5, but you'll have urllib3 1.25.11 which is incompatible.

### ISSUE THREAD

**Issue by EgyptianM** [RasaHQ/rasa#10602]
### Rasa Open Source version

3.0.4

### Rasa SDK version

rasa-sdk<4.0.0,>=3.0.0

### Rasa X version

 _No response_ 

### Python version

3.7

### What operating system are you using?

Windows

### What happened?

ERROR: rasa-sdk 3.0.2 has requirement urllib3<2.0.0,>=1.26.5, but you'll have urllib3 1.25.11 which is incompatible.

### Command / Request

<pre>pip3 install -U --user pip && pip3 install rasa</pre>

### Relevant log output

<pre>(venv) D:\>pip3 install -U --user pip && pip3 install rasa
 Collecting pip
 Using cached pip-21.3.1-py3-none-any.whl (1.7 MB)
 Installing collected packages: pip
 Successfully installed pip-21.3.1
 WARNING: You are using pip version 20.1.1; however, version 21.3.1 is available.
 You should consider upgrading via the 'd:\venv\scripts\python.exe -m pip install --upgrade pip' command.
 Requirement already satisfied: rasa in d:\venv\lib\site-packages (3.0.4)
 Requirement already satisfied: requests=2.23 in d:\venv\lib\site-packages (from rasa) (2.23.0)
 Requirement already satisfied: google-auth=2.3.3 in d:\venv\lib\site-packages (from rasa) (2.3.3)
 Requirement already satisfied: boto3=1.12 in d:\venv\lib\site-packages (from rasa) (1.20.26)
 Requirement already satisfied: fbmessenger=6.0.0 in d:\venv\lib\site-packages (from rasa) (6.0.0)
 Requirement already satisfied: rasa-sdk=3.0.0 in d:\venv\lib\site-packages (from rasa) (3.0.2)
 Requirement already satisfied: matplotlib=3.1 in d:\venv\lib\site-packages (from rasa) (3.3.4)
 Requirement already satisfied: sentry-sdk=0.17.0 in d:\venv\lib\site-packages (from rasa) (1.3.1)
 Requirement already satisfied: jsonpickle=1.3 in d:\venv\lib\site-packages (from rasa) (2.0.0)
 Requirement already satisfied: aio-pika=6.7.1 in d:\venv\lib\site-packages (from rasa) (6.8.1)
 Requirement already satisfied: sklearn-crfsuite=0.3 in d:\venv\lib\site-packages (from rasa) (0.3.6)
 Requirement already satisfied: redis=3.4 in d:\venv\lib\site-packages (from rasa) (3.5.3)
 Requirement already satisfied: python-engineio!=5.0.0,=4 in d:\venv\lib\site-packages (from rasa) (4.3.0)
 Requirement already satisfied: tensorflow-addons=0.14 in d:\venv\lib\site-packages (from rasa) (0.14.0)
 Requirement already satisfied: webexteamssdk=1.1.1 in d:\venv\lib\site-packages (from rasa) (1.6)
 Requirement already satisfied: joblib=0.15.1 in d:\venv\lib\site-packages (from rasa) (1.0.1)
 Requirement already satisfied: prompt-toolkit=2.0 in d:\venv\lib\site-packages (from rasa) (2.0.10)
 Requirement already satisfied: typing-extensions=3.7.4 in d:\venv\lib\site-packages (from rasa) (3.7.4.3)
 Requirement already satisfied: scipy=1.4.1 in d:\venv\lib\site-packages (from rasa) (1.7.3)
 Requirement already satisfied: pykwalify=1.7 in d:\venv\lib\site-packages (from rasa) (1.8.0)
 Requirement already satisfied: CacheControl=0.12.9 in d:\venv\lib\site-packages (from rasa) (0.12.10)
 Requirement already satisfied: pydot=1.4 in d:\venv\lib\site-packages (from rasa) (1.4.2)
 Requirement already satisfied: python-socketio=4.4 in d:\venv\lib\site-packages (from rasa) (5.5.0)
 Requirement already satisfied: tarsafe=0.0.3 in d:\venv\lib\site-packages (from rasa) (0.0.3)
 Requirement already satisfied: sanic-routing=0.7.2 in d:\venv\lib\site-packages (from rasa) (0.7.2)
 Requirement already satisfied: typing-utils=0.1.0 in d:\venv\lib\site-packages (from rasa) (0.1.0)
 Requirement already satisfied: kafka-python=1.4 in d:\venv\lib\site-packages (from rasa) (2.0.2)
 Requirement already satisfied: apscheduler=3.6 in d:\venv\lib\site-packages (from rasa) (3.7.0)
 Requirement already satisfied: tensorflow_hub=0.10 in d:\venv\lib\site-packages (from rasa) (0.12.0)
 Requirement already satisfied: absl-py=0.9 in d:\venv\lib\site-packages (from rasa) (0.13.0)
 Requirement already satisfied: pymongo<span class="error">[srv,tls]</span>=3.8 in d:\venv\lib\site-packages (from rasa) (3.10.1)
 Requirement already satisfied: mattermostwrapper=2.2 in d:\venv\lib\site-packages (from rasa) (2.2)
 Requirement already satisfied: sanic-jwt=1.6.0 in d:\venv\lib\site-packages (from rasa) (1.7.0)
 Requirement already satisfied: colorama=0.4.4; sys_platform == "win32" in d:\venv\lib\site-packages (from rasa) (0.4.4)
 Requirement already satisfied: ruamel.yaml=0.16.5 in d:\venv\lib\site-packages (from rasa) (0.16.13)
 Requirement already satisfied: aiohttp!=3.7.4.post0,=3.6 in d:\venv\lib\site-packages (from rasa) (3.7.4)
 Requirement already satisfied: networkx=2.4 in d:\venv\lib\site-packages (from rasa) (2.6.3)
 Requirement already satisfied: sanic-cors=1.0.0 in d:\venv\lib\site-packages (from rasa) (1.0.1)
 Requirement already satisfied: rocketchat_API=0.6.31 in d:\venv\lib\site-packages (from rasa) (1.16.0)
 Requirement already satisfied: jsonschema=3.2 in d:\venv\lib\site-packages (from rasa) (3.2.0)
 Requirement already satisfied: colorclass=2.2 in d:\venv\lib\site-packages (from rasa) (2.2.2)
 Requirement already satisfied: scikit-learn=0.22 in d:\venv\lib\site-packages (from rasa) (0.24.2)
 Requirement already satisfied: python-dateutil=2.8 in d:\venv\lib\site-packages (from rasa) (2.8.2)
 Requirement already satisfied: setuptools>=41.0.0 in d:\venv\lib\site-packages (from rasa) (47.1.0)
 Requirement already satisfied: tensorflow=2.6 in d:\venv\lib\site-packages (from rasa) (2.6.1)
 Requirement already satisfied: pyTelegramBotAPI=3.7.3 in d:\venv\lib\site-packages (from rasa) (3.8.3)
 Requirement already satisfied: SQLAlchemy=1.4.0 in d:\venv\lib\site-packages (from rasa) (1.4.29)
 Requirement already satisfied: packaging=20.0 in d:\venv\lib\site-packages (from rasa) (20.9)
 Requirement already satisfied: sanic=21.6.0 in d:\venv\lib\site-packages (from rasa) (21.12.0)
 Requirement already satisfied: ujson=1.35 in d:\venv\lib\site-packages (from rasa) (4.3.0)
 Requirement already satisfied: numpy=1.19.2 in d:\venv\lib\site-packages (from rasa) (1.19.5)
 Requirement already satisfied: pytz=2019.1 in d:\venv\lib\site-packages (from rasa) (2021.3)
 Requirement already satisfied: slackclient=2.0.0 in d:\venv\lib\site-packages (from rasa) (2.9.3)
 Requirement already satisfied: tensorflow-probability=0.11 in d:\venv\lib\site-packages (from rasa) (0.13.0)
 Requirement already satisfied: keras=10 in d:\venv\lib\site-packages (from rasa) (15.0.1)
 Requirement already satisfied: regex=2020.6 in d:\venv\lib\site-packages (from rasa) (2021.8.28)
 Requirement already satisfied: colorhash=1.0.2 in d:\venv\lib\site-packages (from rasa) (1.0.4)
 Requirement already satisfied: tensorflow-estimator=2.6 in d:\venv\lib\site-packages (from rasa) (2.6.0)
 Requirement already satisfied: tqdm=4.31 in d:\venv\lib\site-packages (from rasa) (4.62.3)
 Requirement already satisfied: twilio=6.26 in d:\venv\lib\site-packages (from rasa) (6.50.1)
 Requirement already satisfied: questionary=1.5.1 in d:\venv\lib\site-packages (from rasa) (1.10.0)
 Requirement already satisfied: async_generator=1.10 in d:\venv\lib\site-packages (from rasa) (1.10)
 Requirement already satisfied: attrs=19.3 in d:\venv\lib\site-packages (from rasa) (21.2.0)
 Requirement already satisfied: cloudpickle=1.2 in d:\venv\lib\site-packages (from rasa) (1.6.0)
 Requirement already satisfied: psycopg2-binary=2.8.2 in d:\venv\lib\site-packages (from rasa) (2.9.2)
 Requirement already satisfied: dask==2021.11.2 in d:\venv\lib\site-packages (from rasa) (2021.11.2)
 Requirement already satisfied: terminaltables=3.1.0 in d:\venv\lib\site-packages (from rasa) (3.1.10)
 Requirement already satisfied: PyJWT<span class="error">[crypto]</span>=2.0.0 in d:\venv\lib\site-packages (from rasa) (2.3.0)
 Requirement already satisfied: randomname=0.1.5 in d:\venv\lib\site-packages (from rasa) (0.1.5)
 Requirement already satisfied: certifi>=2017.4.17 in d:\venv\lib\site-packages (from requests=2.23->rasa) (2021.10.8)
 Requirement already satisfied: chardet=3.0.2 in d:\venv\lib\site-packages (from requests=2.23->rasa) (3.0.4)
 Collecting urllib3!=1.25.0,!=1.25.1,=1.21.1
 Using cached urllib3-1.25.11-py2.py3-none-any.whl (127 kB)
 Requirement already satisfied: idna=2.5 in d:\venv\lib\site-packages (from requests=2.23->rasa) (2.10)
 Requirement already satisfied: pyasn1-modules>=0.2.1 in d:\venv\lib\site-packages (from google-auth=2.3.3->rasa) (0.2.8)
 Requirement already satisfied: cachetools=2.0.0 in d:\venv\lib\site-packages (from google-auth=2.3.3->rasa) (4.2.4)
 Requirement already satisfied: six>=1.9.0 in d:\venv\lib\site-packages (from google-auth=2.3.3->rasa) (1.15.0)
 Requirement already satisfied: rsa=3.1.4; python_version >= "3.6" in d:\venv\lib\site-packages (from google-auth=2.3.3->rasa) (4.8)
 Requirement already satisfied: s3transfer=0.5.0 in d:\venv\lib\site-packages (from boto3=1.12->rasa) (0.5.0)
 Requirement already satisfied: jmespath=0.7.1 in d:\venv\lib\site-packages (from boto3=1.12->rasa) (0.10.0)
 Requirement already satisfied: botocore=1.23.26 in d:\venv\lib\site-packages (from boto3=1.12->rasa) (1.23.26)
 Requirement already satisfied: pyparsing!=2.0.4,Unable to render embedded object: File (=2.1.2,) not found.=2.1.6,>=2.0.3 in d:\venv\lib\site-packages (from matplotlib=3.1->rasa) (3.0.6)
 Requirement already satisfied: cycler>=0.10 in d:\venv\lib\site-packages (from matplotlib=3.1->rasa) (0.11.0)
 Requirement already satisfied: pillow>=6.2.0 in d:\venv\lib\site-packages (from matplotlib=3.1->rasa) (8.4.0)
 Requirement already satisfied: kiwisolver>=1.0.1 in d:\venv\lib\site-packages (from matplotlib=3.1->rasa) (1.3.2)
 Requirement already satisfied: importlib-metadata; python_version =1.3->rasa) (4.10.0)
 Requirement already satisfied: aiormq=3.2.3 in d:\venv\lib\site-packages (from aio-pika=6.7.1->rasa) (3.3.1)
 Requirement already satisfied: yarl in d:\venv\lib\site-packages (from aio-pika=6.7.1->rasa) (1.7.2)
 Requirement already satisfied: tabulate in d:\venv\lib\site-packages (from sklearn-crfsuite=0.3->rasa) (0.8.9)
 Requirement already satisfied: python-crfsuite>=0.8.3 in d:\venv\lib\site-packages (from sklearn-crfsuite=0.3->rasa) (0.9.7)
 Requirement already satisfied: typeguard>=2.7 in d:\venv\lib\site-packages (from tensorflow-addons=0.14->rasa) (2.13.3)
 Requirement already satisfied: future in d:\venv\lib\site-packages (from webexteamssdk=1.1.1->rasa) (0.18.2)
 Requirement already satisfied: requests-toolbelt in d:\venv\lib\site-packages (from webexteamssdk=1.1.1->rasa) (0.9.1)
 Requirement already satisfied: wcwidth in d:\venv\lib\site-packages (from prompt-toolkit=2.0->rasa) (0.2.5)
 Requirement already satisfied: docopt>=0.6.2 in d:\venv\lib\site-packages (from pykwalify=1.7->rasa) (0.6.2)
 Requirement already satisfied: msgpack>=0.5.2 in d:\venv\lib\site-packages (from CacheControl=0.12.9->rasa) (1.0.3)
 Requirement already satisfied: bidict>=0.21.0 in d:\venv\lib\site-packages (from python-socketio=4.4->rasa) (0.21.4)
 Requirement already satisfied: tzlocal~=2.0 in d:\venv\lib\site-packages (from apscheduler=3.6->rasa) (2.1)
 Requirement already satisfied: protobuf>=3.8.0 in d:\venv\lib\site-packages (from tensorflow_hub=0.10->rasa) (3.19.1)
 Requirement already satisfied: dnspython=1.16.0; extra == "srv" in d:\venv\lib\site-packages (from pymongo<span class="error">[srv,tls]</span>=3.8->rasa) (1.16.0)
 Requirement already satisfied: ruamel.yaml.clib>=0.1.2; platform_python_implementation == "CPython" and python_version =0.16.5->rasa) (0.2.6)
 Requirement already satisfied: multidict=4.5 in d:\venv\lib\site-packages (from aiohttp!=3.7.4.post0,=3.6->rasa) (5.2.0)
 Requirement already satisfied: async-timeout=3.0 in d:\venv\lib\site-packages (from aiohttp!=3.7.4.post0,=3.6->rasa) (3.0.1)
 Requirement already satisfied: sanic-plugin-toolkit=1.2.0 in d:\venv\lib\site-packages (from sanic-cors=1.0.0->rasa) (1.2.0)
 Requirement already satisfied: pyrsistent>=0.14.0 in d:\venv\lib\site-packages (from jsonschema=3.2->rasa) (0.18.0)
 Requirement already satisfied: threadpoolctl>=2.0.0 in d:\venv\lib\site-packages (from scikit-learn=0.22->rasa) (3.0.0)
 Requirement already satisfied: termcolor~=1.1.0 in d:\venv\lib\site-packages (from tensorflow=2.6->rasa) (1.1.0)
 Requirement already satisfied: clang~=5.0 in d:\venv\lib\site-packages (from tensorflow=2.6->rasa) (5.0)
 Requirement already satisfied: astunparse~=1.6.3 in d:\venv\lib\site-packages (from tensorflow=2.6->rasa) (1.6.3)
 Requirement already satisfied: opt-einsum~=3.3.0 in d:\venv\lib\site-packages (from tensorflow=2.6->rasa) (3.3.0)
 Requirement already satisfied: flatbuffers~=1.12.0 in d:\venv\lib\site-packages (from tensorflow=2.6->rasa) (1.12)
 Requirement already satisfied: gast==0.4.0 in d:\venv\lib\site-packages (from tensorflow=2.6->rasa) (0.4.0)
 Requirement already satisfied: keras-preprocessing~=1.1.2 in d:\venv\lib\site-packages (from tensorflow=2.6->rasa) (1.1.2)
 Requirement already satisfied: wheel~=0.35 in d:\venv\lib\site-packages (from tensorflow=2.6->rasa) (0.37.1)
 Requirement already satisfied: tensorboard~=2.6 in d:\venv\lib\site-packages (from tensorflow=2.6->rasa) (2.7.0)
 Requirement already satisfied: google-pasta~=0.2 in d:\venv\lib\site-packages (from tensorflow=2.6->rasa) (0.2.0)
 Requirement already satisfied: wrapt~=1.12.1 in d:\venv\lib\site-packages (from tensorflow=2.6->rasa) (1.12.1)
 Requirement already satisfied: grpcio=1.37.0 in d:\venv\lib\site-packages (from tensorflow=2.6->rasa) (1.43.0)
 Requirement already satisfied: h5py~=3.1.0 in d:\venv\lib\site-packages (from tensorflow=2.6->rasa) (3.1.0)
 Requirement already satisfied: greenlet!=0.4.17; python_version >= "3" and (platform_machine == "aarch64" or (platform_machine == "ppc64le" or (platform_machine == "x86_64" or (platform_machine == "amd64" or (platform_machine == "AMD64" or (platform_machine == "win32" or platform_machine == "WIN32")))))) in d:\venv\lib\site-packages (from SQLAlchemy=1.4.0->rasa) (1.1.2)
 Requirement already satisfied: aiofiles>=0.6.0 in d:\venv\lib\site-packages (from sanic=21.6.0->rasa) (0.8.0)
 Requirement already satisfied: websockets>=10.0 in d:\venv\lib\site-packages (from sanic=21.6.0->rasa) (10.1)
 Requirement already satisfied: httptools>=0.0.10 in d:\venv\lib\site-packages (from sanic=21.6.0->rasa) (0.3.0)
 Requirement already satisfied: decorator in d:\venv\lib\site-packages (from tensorflow-probability=0.11->rasa) (5.1.0)
 Requirement already satisfied: dm-tree in d:\venv\lib\site-packages (from tensorflow-probability=0.11->rasa) (0.1.6)
 Requirement already satisfied: humanfriendly>=9.1 in d:\venv\lib\site-packages (from coloredlogs=10->rasa) (10.0)
 Requirement already satisfied: fsspec>=0.6.0 in d:\venv\lib\site-packages (from dask==2021.11.2->rasa) (2021.11.1)
 Requirement already satisfied: pyyaml in d:\venv\lib\site-packages (from dask==2021.11.2->rasa) (6.0)
 Requirement already satisfied: partd>=0.3.10 in d:\venv\lib\site-packages (from dask==2021.11.2->rasa) (1.2.0)
 Requirement already satisfied: toolz>=0.8.2 in d:\venv\lib\site-packages (from dask==2021.11.2->rasa) (0.11.2)
 Requirement already satisfied: cryptography>=3.3.1; extra == "crypto" in d:\venv\lib\site-packages (from PyJWT<span class="error">[crypto]</span>=2.0.0->rasa) (36.0.1)
 Requirement already satisfied: fire in d:\venv\lib\site-packages (from randomname=0.1.5->rasa) (0.4.0)
 Requirement already satisfied: pyasn1=0.4.6 in d:\venv\lib\site-packages (from pyasn1-modules>=0.2.1->google-auth=2.3.3->rasa) (0.4.8)
 Requirement already satisfied: zipp>=0.5 in d:\venv\lib\site-packages (from importlib-metadata; python_version jsonpickle=1.3~~>rasa) (3.6.0)
 Requirement already satisfied: pamqp==2.3.0 in d:\venv\lib\site-packages (from aiormq=3.2.3->aio-pika=6.7.1->rasa) (2.3.0)
 Requirement already satisfied: google-auth-oauthlib=0.4.1 in d:\venv\lib\site-packages (from tensorboard~=2.6->tensorflow=2.6->rasa) (0.4.6)
 Requirement already satisfied: markdown>=2.6.8 in d:\venv\lib\site-packages (from tensorboard~=2.6->tensorflow=2.6->rasa) (3.3.6)
 Requirement already satisfied: tensorboard-plugin-wit>=1.6.0 in d:\venv\lib\site-packages (from tensorboard~=2.6->tensorflow=2.6->rasa) (1.8.0)
 Requirement already satisfied: tensorboard-data-server=0.6.0 in d:\venv\lib\site-packages (from tensorboard~=2.6->tensorflow=2.6->rasa) (0.6.1)
 Requirement already satisfied: werkzeug>=0.11.15 in d:\venv\lib\site-packages (from tensorboard~=2.6->tensorflow=2.6->rasa) (2.0.2)
 Requirement already satisfied: cached-property; python_version tensorflow=2.6->rasa) (1.5.2)
 Requirement already satisfied: pyreadline; sys_platform == "win32" and python_version =9.1->coloredlogs=10->rasa) (2.1)
 Requirement already satisfied: locket in d:\venv\lib\site-packages (from partd>=0.3.10->dask==2021.11.2->rasa) (0.2.1)
 Requirement already satisfied: cffi>=1.12 in d:\venv\lib\site-packages (from cryptography>=3.3.1; extra == "crypto"~<sub>&gt;PyJWT<span class="error">[crypto]</span>=2.0.0</sub>~>rasa) (1.15.0)
 Requirement already satisfied: requests-oauthlib>=0.7.0 in d:\venv\lib\site-packages (from google-auth-oauthlib=0.4.1->tensorboard~=2.6->tensorflow=2.6->rasa) (1.3.0)
 Requirement already satisfied: pycparser in d:\venv\lib\site-packages (from cffi>=1.12->cryptography>=3.3.1; extra == "crypto"~<sub>&gt;PyJWT<span class="error">[crypto]</span>=2.0.0</sub>~>rasa) (2.21)
 Requirement already satisfied: oauthlib>=3.0.0 in d:\venv\lib\site-packages (from requests-oauthlib>=0.7.0->google-auth-oauthlib=0.4.1->tensorboard~=2.6->tensorflow=2.6->rasa) (3.1.1)
 ERROR: rasa-sdk 3.0.2 has requirement urllib3=1.26.5, but you'll have urllib3 1.25.11 which is incompatible.
 Installing collected packages: urllib3
 Attempting uninstall: urllib3
 Found existing installation: urllib3 1.26.5
 Uninstalling urllib3-1.26.5:
 Successfully uninstalled urllib3-1.26.5
 Successfully installed urllib3-1.25.11
 WARNING: You are using pip version 20.1.1; however, version 21.3.1 is available.
 You should consider upgrading via the 'd:\venv\scripts\python.exe -m pip install --upgrade pip' command.</pre>

**Comment by sara-tagger** [comment]
Thanks for raising this issue, @dakshvar22 will get back to you about it soon✨

###### Please also check out the [docs](https://rasa.com/docs/) and the [forum](https://forum.rasa.com/) in case your issue was raised there too 🤗

**Comment by koaning** [comment]
Are you using a clean virtual environment or a pre-existing one? The incompatibility might be caused by another package and it's recommended to install Rasa in a clean virtualenv. 

Virtualenvs are tricky beasts in general, if it's appreciated you may enjoy [this guide](https://calmcode.io/virtualenv/intro.html).

**Comment by EgyptianM** [comment]
> Are you using a clean virtual environment or a pre-existing one? The incompatibility might be caused by another package and it's recommended to install Rasa in a clean virtualenv.
> 
> Virtualenvs are tricky beasts in general, if it's appreciated you may enjoy [this guide](https://calmcode.io/virtualenv/intro.html).

A clean virtual environment

Thank you for the guide I'll watch it.

**Comment by HotThoughts** [comment]
Looks like the second part `pip3 install rasa` is still using the old version (20.1.1) although you upgraded `--user pip`. Could you try to update `pip3` and see how is going?
```
(venv) D:\>pip3 install -U --user pip && pip3 install rasa
Collecting pip
  Using cached pip-21.3.1-py3-none-any.whl (1.7 MB)
Installing collected packages: pip
Successfully installed pip-21.3.1
WARNING: You are using pip version 20.1.1; however, version 21.3.1 is available.
You should consider upgrading via the 'd:\venv\scripts\python.exe -m pip install --upgrade pip' command.
```

**Comment by Rhinoceroach** [comment]
Had the same error. Was able to get it working by specifying the version of pip, in your case:

pip3.7 install rasa

**Comment by m-vdb** [comment]
Closing as stale -- please reopen an issue if the bug persists in the latest version of the SDK
