### ISSUE TITLE
utter_message is not send after action_default_fallback

### ISSUE THREAD

**Issue by jonra1993** [RasaHQ/rasa#10615]
### Rasa Open Source version

3.0.4

### Rasa SDK version

 _No response_ 

### Rasa X version

 _No response_ 

### Python version

3.7

### What operating system are you using?

OSX

### What happened?

I am trying to show a bot utter_default message after action_default_fallback but when the action returns UserUtteranceReverted(), bot does not prompt anything. If I return[] it works as expected. According documentation: _You should include UserUtteranceReverted() as one of the events returned by your custom action_default_fallback_ [https://rasa.com/docs/rasa/fallback-handoff#4-defining-an-ultimate-fallback-action](https://rasa.com/docs/rasa/fallback-handoff#4-defining-an-ultimate-fallback-action)

config.yml

policies:

*   name: MemoizationPolicy
*   name: UnexpecTEDIntentPolicy max_history: 5 epochs: 100
*   name: TEDPolicy max_history: 5 epochs: 100 constrain_similarities: true
*   name: RulePolicy core_fallback_threshold: 0.1 core_fallback_action_name: "action_default_fallback" enable_fallback_prediction: True

domain.yml

responses: utter_default:

*   text: I'm sorry, I can't help you.

actions:

*   action_default_fallback

actions.yml

from typing import Any, Dict, List, Text

from rasa_sdk import Action, Tracker from rasa_sdk.events import UserUtteranceReverted from rasa_sdk.executor import CollectingDispatcher

class ActionDefaultFallback(Action): def name(self) -> Text: return "action_default_fallback"

def run( self, dispatcher: CollectingDispatcher, tracker: Tracker, domain: Dict<span class="error">[Text, Any]</span>, ) -> List[Dict<span class="error">[Text, Any]</span>]:

1.  tell the user they are being passed to a customer service agent dispatcher.utter_message(response="utter_default")

1.  pause the tracker so that the bot stops responding to user input return <span class="error">[UserUtteranceReverted()]</span>

1.  return []

This also happens using without overwriting the action_default_fallback as the documentation suggests.

[<span class="image-wrap" style="">![](https://user-images.githubusercontent.com/23468720/147835418-bf1f2d7a-53c0-4451-8fd9-9a1b621df235.png)</span>](https://user-images.githubusercontent.com/23468720/147835418-bf1f2d7a-53c0-4451-8fd9-9a1b621df235.png)

[<span class="image-wrap" style="">![](https://user-images.githubusercontent.com/23468720/147834695-3e4ae405-458d-4de3-8caa-a407fa6b4ed2.png)</span>](https://user-images.githubusercontent.com/23468720/147834695-3e4ae405-458d-4de3-8caa-a407fa6b4ed2.png)

### Command / Request

 _No response_ 

### Relevant log output

With return <span class="error">[UserUtteranceReverted()]</span> (no utter_default is prompt)

1.  action_default_fallback
2.  action_listen

With return [] (Expected output)

1.  action_default_fallback
2.  utter_default
3.  action_listen

**Comment by sara-tagger** [comment]
Thanks for raising this issue, @JustinaPetr will get back to you about it soon✨

###### Please also check out the [docs](https://rasa.com/docs/) and the [forum](https://forum.rasa.com/) in case your issue was raised there too 🤗
