### ISSUE TITLE
Regex extractor ending or staring with special character

### ISSUE THREAD

**Issue by azizullah2017** [RasaHQ/rasa#10617]
### Rasa Open Source version

2.8.8

### Rasa SDK version

 _No response_ 

### Rasa X version

 _No response_ 

### Python version

3.6

### What operating system are you using?

Linux

### What happened?

res = re.finditer("c+

<ins>", "c</ins>

<ins>") print(list(res)) [ </ins>

+"> ] </re.match>

res = re.finditer("\bc++ b", "c++") print(list(res)) []

### Command / Request

 _No response_ 

### Relevant log output

 _No response_

**Comment by sara-tagger** [comment]
Thanks for the issue, @samsucik will get back to you about it soon!

###### You may find help in the [docs](https://rasa.com/docs/) and the [forum,](https://forum.rasa.com/) too 🤗

**Comment by samsucik** [comment]
Hey @azizullah2017, what is the issue that you're facing? Please provide as much relevant info as possible (see the sections in the issue template).

**Comment by azizullah2017** [comment]
@samsucik I have added some examples in lookup and I am trying to extract them using RegexExtractor. The pattern is not matched as shown above. If the value starts/ends with a special character. the below will not be extracted by RegexExtractor 

like:
lookup:
- aziz (a)
- .cda
- c++

**Comment by azizullah2017** [comment]
https://stackoverflow.com/questions/30242709/matching-terms-that-contain-special-characters-with-re-findall

The problem is \b which is word boundary.In C++ there is no word boundary after +. So it will not match.Similarly for others.

**Comment by samsucik** [comment]
Thanks, @azizullah2017. I think someone will pick this up soon and fix it.

**Comment by JEM-Mosig** [comment]
@dakshvar22 is reviewer

**Comment by tttthomasssss** [comment]
Hey @azizullah2017 - thanks for raising this issue, I am currently looking into it. 

Could you share a complete minimal example here, including the relevant bits of the `nlu.yml` file(s) as well as your model config?

**Comment by azizullah2017** [comment]
@tttthomasssss there is not any issue with nlu.yml, I have created PR for this too, which is working fine.
RegexExtrator does not create proper regex.
the below lookups are not detected with current RegexExtrator.

```
lookup:
 - aziz (a)
 - .cda
 - c++
```

https://stackoverflow.com/questions/30242709/matching-terms-that-contain-special-characters-with-re-findall
The problem is \b which is word boundary.In C++ there is no word boundary after +. So it will not match.Similarly for others.

@tttthomasssss it would be, if you cloud review my PR.
