### ISSUE TITLE
Convert Diet classifier model into ONNX format

### ISSUE THREAD

**Issue by GaoQ1** [RasaHQ/rasa#10620]
### What problem are you trying to solve?

If i train a DIETmodel in CPU, the rasa service is so slowly. So can we convert diet model into onnx?

### What's your suggested solution?

 _No response_ 

### Examples (if relevant)

 _No response_ 

### Is anything blocking this from being implemented? (if relevant)

 _No response_ 

### Definition of Done

 _No response_

**Comment by sara-tagger** [comment]
Thanks for submitting this feature request 🚀 @kedz will get back to you about it soon! ✨

**Comment by koaning** [comment]
It's a bit unclear if the operations in DIET allow for easy conversion to the ONNX format. This could be investigated, but it's also unclear if ONNX will provide a significant speedup. Are you aware of a resource that lists proper comparisons of speedups across neural network architectures?

**Comment by koaning** [comment]
Also, could you share a bit more about your setup? How many examples/intents/stories do you have?

**Comment by dimidloc** [comment]
> It's a bit unclear if the operations in DIET allow for easy conversion to the ONNX format. This could be investigated, but it's also unclear if ONNX will provide a significant speedup. Are you aware of a resource that lists proper comparisons of speedups across neural network architectures?

https://blog.twitter.com/engineering/en_us/topics/insights/2021/speeding-up-transformer-cpu-inference-in-google-cloud
