### ISSUE TITLE
Error with runpy.py when executing rasa train

### ISSUE THREAD

**Issue by coffeebean27** [RasaHQ/rasa#10633]
### What problem are you trying to solve?

Hi, I encounter this error when executing rasa train my envs : Sys : Windows10 Python : 3.6 Rasa : 2.0 Tensorflow : 2.3.4

Error: PS C:\Users\corma\PycharmProjects\pharmacy_chatbot> rasa train Traceback (most recent call last): File "C:\Users\corma\AppData\Local\Programs\Python\Python36\lib\runpy.py", line 193, in _run_module_as_main "**main**", mod_spec) File "C:\Users\corma\AppData\Local\Programs\Python\Python36\lib\runpy.py", line 85, in _run_code exec(code, run_globals) File "C:\Users\corma\PycharmProjects\pharmacy_chatbot\venv\Scripts\rasa.exe_ _main_ _ .py", line 4, in File "c:\users\corma\pycharmprojects\pharmacy_chatbot\venv\lib\site-packages\rasa_ _init_ _ .py", line 8, in from rasa.run import run File "c:\users\corma\pycharmprojects\pharmacy_chatbot\venv\lib\site-packages\rasa\run.py", line 6, in from rasa.shared.utils.cli import print_warning File "c:\users\corma\pycharmprojects\pharmacy_chatbot\venv\lib\site-packages\rasa\shared\utils\cli.py", line 2, in from typing import Any, Text, NoReturn ImportError: cannot import name 'NoReturn'

### What's your suggested solution?

 _No response_ 

### Examples (if relevant)

 _No response_ 

### Is anything blocking this from being implemented? (if relevant)

 _No response_ 

### Definition of Done

 _No response_

**Comment by sara-tagger** [comment]
Thanks for submitting this feature request 🚀 @kalkbrennerei will get back to you about it soon! ✨

**Comment by kalkbrennerei** [comment]
Hi @coffeebean27! Which python version are you using exactly? Seems like `NoReturn` was added in python 3.6.2 ([link to python docs](https://docs.python.org/3/library/typing.html#typing.NoReturn)), so maybe you can update your python version?

Also with the rasaos `3.0` release, support for python 3.6 has been dropped. So if you want to upgrade to rasa `3.0` ([this is why you should!](https://rasa.com/blog/what-s-ahead-in-rasa-open-source-3-0/)) you also have to consider to update your python version

Hope this helps!! ✨
