### ISSUE TITLE
Plan to speed up CI

### ISSUE THREAD

**Issue by joejuzl** [RasaHQ/rasa#10636]
Following on from the CI improvement [spike]( https://github.com/RasaHQ/enable_squad/issues/70) we need to have concrete next steps to speed up the CI

### Definition of Done 
- [x] Determine plan to speed up the CI time (specifically the test suite) -- baseline: where we ended up to speed up last time 15-25 min?
- [x] Create tickets

**Comment by koaning** [comment]
You may enjoy checking with https://github.com/koaning/pytest-duration-insights. I've heard that the numpy folks have started playing with it.

**Comment by ancalita** [comment]
@joejuzl How granular should this plan be? 
For example, if one action item is to refactor fixtures (particularly the long-living ones), do I need to provide an analysis of which fixtures, or should this be a step in the DoD of the issue i will create? Or if another item is to further split tests into workflows/ diff test suites, should I explicitly provide the solution or should it be part of the DoD of the future issue?

**Comment by joejuzl** [comment]
@ancalita I would say you need to do enough analysis to determine if it's a correct/viable approach, and you can include whatever that is in the ticket - but no further is needed. WDYT?
