### ISSUE TITLE
Plan to fix flakey CI tests

### ISSUE THREAD

**Issue by joejuzl** [RasaHQ/rasa#10645]
Following on from the CI improvement [spike]( https://github.com/RasaHQ/enable_squad/issues/70) we want to figure out which flakey tests to fix.

### Definition of Done 
- [x] Determine which flakey tests to fix (with potential solutions)
- [x] Create tickets

**Comment by ancalita** [comment]
Looked at past 6 weeks' flaky CI runs and created new issues:
- #10668 (prioritised above the line since it's related to issue #9553 )
- #10671  (placed below the priority line, since observed very rarely in the sample I looked at)
Issue #8660 is still relevant.
