### ISSUE TITLE
Add LogisticRegression as a replacement for SKlearnIntentClassifier

### ISSUE THREAD

**Issue by koaning** [RasaHQ/rasa#10649]
### What problem are you trying to solve?

The current implementation for the `SklearnIntentClassifier` is a bit of an anti-pattern. It does a grid-search internally and it can only use the dense features in the Rasa pipeline. If we want to have an alternative to benchmark DIET, we may want to introduce another method.

### What's your suggested solution?

My proposal here is to replace it with a simple logistic regression classifier. This should train faster and it's also very lightweight.

### Examples (if relevant)

There's an implementation in [rasa nlu examples](https://github.com/RasaHQ/rasa-nlu-examples/blob/main/rasa_nlu_examples/classifiers/logistic_regression_intent_classifier.py) that we could go ahead and port.

### Is anything blocking this from being implemented? (if relevant)

 _No response_ 

### Definition of Done

We should make sure that:

*   [ ] the logistic regression gets a proper review
*   [ ] we also consider how we want to deprecate the original sklearn classifier

**Comment by dakshvar22** [comment]
Do we have any numbers to see how LR models perform compared to DIET on some datasets?

**Comment by koaning** [comment]
It's not hard to generate since we have an implementation. What might be good datasets? Sara?

**Comment by dakshvar22** [comment]
All the datasets on which we run model regression tests

**Comment by dakshvar22** [comment]
The original plan was to deprecate and remove `SklearnIntentClassifier` altogether and just keep DIET. If training times are a concern then features like incremental training can help there. The trade-off that I want to point to is that if we add a new component to Rasa, specifically an intent classifier, users have a new choice to make when deciding on the config and there is additional complexity in maintaining and guiding them on when and how to migrate to a different classifier. For those reasons, I'd like to see a very clear benefit in supporting two intent classifiers in the framework.

**Comment by koaning** [comment]
I can imagine that, while fine-tuning can help, the speed of the sklearn implementation will be very hard to beat. I imagine retraining with sklearn to be faster than training a single epoch for DIET. 

I suppose the main reason to add it is to allow Rasa users to run a benchmark against a bag of words approach. If the difference between DIET and BOW is very small then this indicates that you may have an easy dataset. I could argue that this is useful knowledge. 

Another reason perhaps is that this approach does not require Tensorflow, which might be helpful to some users that experience installation issues.
