### ISSUE TITLE
NER with tensorflow embedding?

### ISSUE THREAD

**Issue by ctrado18** [RasaHQ/rasa#1064]
Could you do somehow NER with hierarchical intent where last node would be an entity ideally?

Or furhermore using the word embedding as features for CRF. So, CRF would be more stable against typos mispelling, shortcuts?

**Comment by wrathagom** [comment]
@amn41 this one sound right up your alley.

**Comment by amn41** [comment]
I'll give it some thought :)

**Comment by souvikg10** [comment]
https://github.com/guillaumegenthial/sequence_tagging 
Some inspiration 😄 . I am also trying to load fastText vectors on spacy to see if makes better NER compared to the default ones. just following the thread, I am also interested in this discussion 🔥

**Comment by amn41** [comment]
We looked into a number of alternatives for doing this, specifically a bunch of character-level models (recurrent and convolutional) - so far nothing was meaningfully better than that standard setup. Still an active area of research for us
