### ISSUE TITLE
Add ability to set custom metadata field to new conversation tracker events

### ISSUE THREAD

**Issue by ePreda** [RasaHQ/rasa#10676]
### What problem are you trying to solve?

Rasa-X is using a workaround to allow the creation of interactive conversations using a tracker provided by calling `/conversations/

 {conversation_id}/tracker` in `server.py`. The conversation needs the interactive flag set immediately, so it cannot create a conversation as it would normally, and is interacting with the DB at an inappropriate level.

 h3\. What's your suggested solution?

 Adding the ability to set a custom `metadata` field to all Conversation Event messages created as a result of calling the `/conversations/{conversation_id} 

/tracker` endpoint to initiate a new conversation.

This can already be done when explicitly passing events to `/conversations/

 {conversation_id}/tracker/events`.

 h3\. Definition of Done

 When passing an argument to `/conversations/{conversation_id} 

/tracker` of the following shape: `{metadata : 

 { "rasa_x_interactive" : True } 

 }` results in Conversation Events returned by the message broker having the following format, with the new field included:

 {"sender_id": "29772ee4671549a8bbbe5b739f496e77", "event": "action", "timestamp": 1641979267.6448398, "metadata": 

 {"rasa_x_interactive": true} 

, "name": "action_session_start", "policy": null, "confidence": 1.0, "action_text": null, "hide_rule_turn": false}'
 {"sender_id": "29772ee4671549a8bbbe5b739f496e77", "event": "session_started", "timestamp": 1641979267.6448781, "metadata": {"rasa_x_interactive": true}}
 {"sender_id": "29772ee4671549a8bbbe5b739f496e77", "event": "action", "timestamp": 1641979267.6450124, "metadata": 

 {"rasa_x_interactive": true} 

, "name": "action_listen", "policy": null, "confidence": null, "action_text": null, "hide_rule_turn": false}

**Comment by joejuzl** [comment]
I'm a bit unclear on why this metadata key needs to be added in Rasa OSS - rather than just adding it to the events when it's received in Rasa X?

**Comment by ePreda** [comment]
@joejuzl 

Related to why : Rasa X starts `conversations` based on new events coming from the EventBroker without an existing conversation stored in the `Database`. `Interactive` conversations are special in that they need a fixed input channel referenced from the beginning, which means it has to be set in the `DB` on conversation creation. Current workaround is to request the events from Rasa OSS, then write them to a new conversation as quickly as possible in the `DB` with the added flag, before the same requested events come automatically in through the EventBroker. This is because the `/conversations/{conversation_id}/tracker` endpoint both returns events via the request and send them through the EventBroker at the same time.

Just a note, we can already add the `metadata` field to events posted through the `/conversations/{conversation_id}/tracker/events` endpoint to Rasa OSS. An alternative would be to send a set of "starting events" directly to Rasa OSS from Rasa X. The issue with this is that Rasa X doesn't know what a starting conversation should look like, and am not sure if the right idea is hardcoding a set of starting events in.

**Comment by joejuzl** [comment]
@ePreda thanks for the detailed explanation.

I don't see any major problems with adding functionality `/conversations/{conversation_id}/tracker` to initiate the events in the tracker with certain metadata.

However it does feel a little like a bandaid in a bigger issue i.e. the interaction between `Interactive` and the event broker. I wonder if there is a way to untangle them so that this is not necessary? Or maybe we do want _all_ events coming through the event broker for the sake of consistency, and this metadata approach is the best way?
