### ISSUE TITLE
Flaky CI: Fix `psutil.NoSuchProcess` exception in `test_for_memory_leak`

### ISSUE THREAD

**Issue by ancalita** [RasaHQ/rasa#10671]
**Context**: These CI runs were identified as flaky: [https://github.com/RasaHQ/rasa/runs/4597289941?check_suite_focus=true](https://github.com/RasaHQ/rasa/runs/4597289941?check_suite_focus=true) [https://github.com/RasaHQ/rasa/runs/4715199388?check_suite_focus=true](https://github.com/RasaHQ/rasa/runs/4715199388?check_suite_focus=true)

One possible cause behind the failure could be the process being killed by GH runner due to OOM errors.

To avoid this, we could adapt the test here in either/or 2 ways:

*   replace `subprocess.Popen` with [`psutil.Popen`](https://psutil.readthedocs.io/en/latest/index.html?highlight=psutil.Popen#psutil.Popen) to make use of [`psutil.Process.is_running()`](https://psutil.readthedocs.io/en/latest/index.html?highlight=is_running#psutil.Process.is_running) method in this [line](https://github.com/RasaHQ/rasa/blob/e13bc1a77617cd557a9c8b92c4002f22bff72402/tests/test_memory_leak.py#L82)
*   add a check/assertion that [`subprocess.Popen.poll()`](https://docs.python.org/3/library/subprocess.html#subprocess.Popen.poll) is None before using `memory_profiler.memory_usage`

**Definition of Done**:

*   [ ] test is adapted

**Comment by TyDunn** [comment]
test might be replaced with more sophisticated test, making this issue unnecessary
