### ISSUE TITLE
Message will be published twice upon successful Kafka broker reconnection

### ISSUE THREAD

**Issue by vpol** [RasaHQ/rasa#10672]
### Rasa Open Source version

3.0.4

### Rasa SDK version

 _No response_ 

### Rasa X version

 _No response_ 

### Python version

3.8

### What operating system are you using?

OSX

### What happened?

I [this](https://github.com/RasaHQ/rasa/blob/main/rasa/core/brokers/kafka.py#L115) loop

if second `self._publish(event)` is successful, loop continues and message is published one more time before return.

### Command / Request

 _No response_ 

### Relevant log output

 _No response_

**Comment by sara-tagger** [comment]
Thanks for raising this issue, @NareshDen will get back to you about it soon✨

###### Please also check out the [docs](https://rasa.com/docs/) and the [forum](https://forum.rasa.com/) in case your issue was raised there too 🤗
