### ISSUE TITLE
Cannot convert nlu from json to yaml file

### ISSUE THREAD

**Issue by PessiPess** [RasaHQ/rasa#10675]
### Rasa Open Source version

3.0.4

### Python version

3.8

### What operating system are you using?

Windows

### What happened?

I tried to convert nlu.json to yaml format by `rasa data convert nlu --format yaml`, but had an error: Could not recognize output format. Supported output formats: 'json' and 'yaml'. Specify the desired output format with '--format'.

![image](https://user-images.githubusercontent.com/31157257/149146912-ace46595-2fc7-46cb-b10b-4a7cbead25d6.png)

Also, i checked source code of this command(and nlu converter): 
![image](https://user-images.githubusercontent.com/31157257/149147247-8464703d-615d-4bd5-bb3d-afaccf6b5629.png)
![image](https://user-images.githubusercontent.com/31157257/149147329-d7f147e1-47e4-4fcd-9766-02bcbea34081.png)

Did converting nlu data to yaml support?

### Command / Request

```shell
rasa data convert nlu --format yaml
```

**Comment by sara-tagger** [comment]
Thanks for raising this issue, @hsm207 will get back to you about it soon✨

###### Please also check out the [docs](https://rasa.com/docs/) and the [forum](https://forum.rasa.com/) in case your issue was raised there too 🤗

**Comment by gabrielbotelhoo** [comment]
I'm facing the same issue here.

**Comment by xu-song** [comment]
+1

**Comment by macfernandez** [comment]
Hi! Is this issue open to the community? If it is, I would like to work on it.

**Comment by SamuelNoB** [comment]
hi this issue is active? i've developed an solution and would like to submit a PR

**Comment by wochinge** [comment]
fixed in #10991 . Will also create a backport for 2.8.x https://github.com/RasaHQ/rasa/pull/10995
