### ISSUE TITLE
Facebook channel elements (generic templates) are not filled with slot values

### ISSUE THREAD

**Issue by dsjaai** [RasaHQ/rasa#10686]
### Rasa Open Source version

3.0.4

### Rasa SDK version

 _No response_ 

### Rasa X version

 _No response_ 

### Python version

3.8

### What operating system are you using?

OSX

### What happened?

It is expected that references to slots are replaced with their current value in a response. Example `hello

 {name} 

`->`hello John Doe`. The Facebook channel responses can have a field `elements` which corresponds to the generic templates of the Facebook api.

The problem:

*   The field `elements` is not interpolated. Names of slots are not replaced with their value. I'm not sure if this is by design, but I assume `elements` should be interpolated as well.

Solution idea:

*   Adding `elements` to the list of `keys_to_interpolate` in `rasa.core.nlg.response.py` in the method `_fill_response` might fix this issue.

### Command / Request

 _No response_ 

### Relevant log output

 _No response_

**Comment by sara-tagger** [comment]
Thanks for the issue, @JustinaPetr will get back to you about it soon!

###### You may find help in the [docs](https://rasa.com/docs/) and the [forum,](https://forum.rasa.com/) too 🤗
