### ISSUE TITLE
Found solution: raise NotImplementedError while testing stories (Python 3.9, Rasa 3.x)

### ISSUE THREAD

**Issue by rochdikhalid** [RasaHQ/rasa#10698]
### What problem are you trying to solve?

I installed Rasa on my local machine using python 3.9\. After I trained my model, I run `rasa test` to test stories to see if the messages are classified correctly. The command generates the plots and some results but I ended up with the following error:

 Failed stories written to 'results/failed_test_stories.yml'
 Stories with prediction warnings written to 'results/stories_with_warnings.yml'
 ***Traceback (most recent call last):***

*   *   File "/home/.../anaconda3/envs/rasaenv/bin/rasa", line 5, in <module>**
    *   main()**
    *   File "/home/.../.../rasa/rasa/__main__.py", line 119, in main**
    *   cmdline_arguments.func(cmdline_arguments)**
    *   File "/home/.../.../rasa/rasa/cli/test.py", line 276, in test**
    *   run_core_test(args)**
    *   File "/home/.../.../rasa/rasa/cli/test.py", line 270, in run_core_test**
    *   asyncio.run(run_core_test_async(args))**
    *   File "/home/.../anaconda3/envs/rasaenv/lib/python3.9/asyncio/runners.py", line 49, in run**
    *   loop.run_until_complete(loop.shutdown_default_executor())**
    *   File "uvloop/loop.pyx", line 1456, in uvloop.loop.Loop.run_until_complete**
    *   File "/home/.../anaconda3/envs/rasaenv/lib/python3.9/asyncio/events.py", line 253, in shutdown_default_executor**
    *   raise NotImplementedError**
         ***NotImplementedError***

Link to the issue: [https://forum.rasa.com/t/notimplementederror-while-testing-stories/50592](https://forum.rasa.com/t/notimplementederror-while-testing-stories/50592)

### What's your suggested solution?

I figured out a solution for this bug but I'm not sure if it is accurate for the long term or there is a better solution for it. I created a new conda environment with a particular python version (3.7). The goal here is to examine the **events.py** and **runners.py** files where the **shutdown_default_executor** method is defined to see if those files are exactly similar to what I found in my rasaenv environment with python 3.9\. What I found is something unexpected, the **shutdown_default_executor** method does not exist and also there is an additional class called **SendfileNotAvailableError(RuntimeError)** defined at the beginning of events.py file. To solve this bug, I get rid of **shutdown_default_executor** method from the mentioned files and I added that **RunTimeError** class at the top of **events.py** after the dependencies (import ...). Then, `rasa test` command runs properly even in python 3.9 with no failed stories or prediction warnings and this is how the end of testing looks like in my terminal:

 ...
 ...

*   *   Failed stories written to 'results/failed_test_stories.yml'
    *   Stories with prediction warnings written to 'results/stories_with_warnings.yml'
    *   2022-01-18 10:19:06 INFO rasa.core.processor - Loading model models/20220117-113834-senior-link.tar.gz...
    *   2022-01-18 10:19:31 WARNING rasa.shared.utils.common - The UnexpecTED Intent Policy is currently experimental and might change or be removed in the future 🔬 Please share your feedback on it in the forum ([https://forum.rasa.com](https://forum.rasa.com)) to help us make this feature ready for production.
    *   2022-01-18 10:19:46 INFO rasa.nlu.test - Running model for predictions:
         100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████| 59/59 <span class="error">[00:04&lt;00:00, 12.29it/s]</span>
    *   2022-01-18 10:19:51 INFO rasa.nlu.test - Intent evaluation results:
    *   2022-01-18 10:19:51 INFO rasa.nlu.test - Intent Evaluation: Only considering those 59 examples that have a defined intent out of 59 examples.
    *   2022-01-18 10:19:51 INFO rasa.nlu.test - Classification report saved to results/intent_report.json.
    *   2022-01-18 10:19:51 INFO rasa.nlu.test - Every intent was predicted correctly by the model.
    *   2022-01-18 10:19:51 INFO rasa.utils.plotting - Confusion matrix, without normalization:
         [[ 7 0 0 0 0 0 0 0 0 0]
         [ 0 10 0 0 0 0 0 0 0 0]
         [ 0 0 3 0 0 0 0 0 0 0]
         [ 0 0 0 7 0 0 0 0 0 0]
         [ 0 0 0 0 6 0 0 0 0 0]
         [ 0 0 0 0 0 8 0 0 0 0]
         [ 0 0 0 0 0 0 5 0 0 0]
         [ 0 0 0 0 0 0 0 5 0 0]
         [ 0 0 0 0 0 0 0 0 4 0]
         [ 0 0 0 0 0 0 0 0 0 4]]
         /home/.../rasa/rasa/utils/plotting.py:284: UserWarning: Attempting to set identical left == right == 0 results in singular transformations; automatically expanding.
         axes<span class="error">[side]</span>.set(yticks=yticks, xlim=(0, x_ranges<span class="error">[side]</span>), ylim=y_range)

### Examples (if relevant)

 _No response_ 

### Is anything blocking this from being implemented? (if relevant)

 _No response_ 

### Definition of Done

 _No response_

**Comment by sara-tagger** [comment]
Thanks for submitting this feature request 🚀 @alopez will get back to you about it soon! ✨

**Comment by johnmalib** [comment]
In Python, NotImplementedError is an exception that is raised when a method or function is not implemented, or when a subclass does not implement an abstract method from its parent class. This exception can be raised intentionally to signal that the functionality is not yet implemented, or it can be raised accidentally due to a coding mistake.

Check if the method or function is intentionally not implemented: If the NotImplementedError is raised intentionally, you can leave the method or function as is, or provide a placeholder implementation that raises the NotImplementedError. However, if the NotImplementedError is raised accidentally, you need to provide a proper implementation.

If you are dealing with an [python](http://net-informations.com/python/iq/default.htm) abstract method, you can either provide a concrete implementation for the method in the subclass, or mark the subclass as abstract and force its children to implement the method.
