### ISSUE TITLE
CI regression tests don't work with alternative branch for pipeline config

### ISSUE THREAD

**Issue by mleimeister** [RasaHQ/rasa#10691]
### Rasa Open Source version

3.0.x

### Python version

3.8

### What operating system are you using?

OSX

### What happened?

When trying to use a newly added config in the regression tests, following the steps described [here](https://www.notion.so/rasa/The-CI-for-model-regression-tests-aa579d5524a544af992f97d132bcc2de#e6e13559df5c4b99ba82a468651c7891), only the dataset is pulled from the branch specified in `dataset_branch`, but the config is looked up on `main`.

This is likely due to the hard-coded branch [here](https://github.com/RasaHQ/rasa/blob/main/.github/workflows/ci-model-regression.yml#L43) and should be adapted to also use `dataset_branch`.

** Definition of Done **
- [x] Fix this on main
- [x] Test with some example (e.g. Vincent's logistic regression component)
- [ ] Get review from infrastructure squad

**Comment by JEM-Mosig** [comment]
Thomasz has seen this issue before (-> reviewer ?)
