### ISSUE TITLE
Rule policy consumes a lot of CPU at inference time

### ISSUE THREAD

**Issue by hsm207** [RasaHQ/rasa#10703]
### Rasa Open Source version

2.8.21

### Rasa SDK version

 _No response_ 

### Rasa X version

 _No response_ 

### Python version

3.8

### What operating system are you using?

Linux

### What happened?

Rule Policy consumes a lot of CPU cycles when there are a lot of rules

### Command / Request

Run this [bot](https://github.com/RasaHQ/rule_policy_spike_cpu).

### Relevant log output

 _No response_

**Comment by tayfun** [comment]
We can add unit tests to check no extra computations are made; probably we didn’t test with 4000 rules while developing RulePolicy? `_is_rule_applicable` seems to be the crux of rule policy and we seem to cache `_rule_key_to_state` for 1000 items (which means with 4000 keys it can have cache misses 1 in 4 random cases); we also run `list(reversed(state_list)`  on each run and this can be cached too I'm thinking. These are observations just by reading the code, detailed analysis is needed.

**Comment by dsjaai** [comment]
What do you think of using a decision tree structure to identify rules that can be applied?

For each rule in the training data one would add each condition and requirement (like last intent must be x) as decisions to the tree. 
In addition nodes hold all the rules that can be applied if all conditions from the root until that node are fulfilled or not fulfilled as defined by the path.
As we know by definition, there should be at most one rule, or at least, there should be only non contradicting rules that can be applied at the same time. So, we could simply run through the tree top-down (starting at the root) until a rule is found. If no rule is found until reaching a leave, no rule can be applied.

**Comment by tayfun** [comment]
I've closed the PR linked to this ticket, we can still check it out when we start working on this ticket. It has some guidance on what to look for.
