### ISSUE TITLE
Upgrade Poetry to 1.1.11

### ISSUE THREAD

**Issue by tayfun** [RasaHQ/rasa#10708]
### Rasa Open Source version

3

### Python version

3.8

### What operating system are you using?

OSX, Windows

### What happened?

Older poetry seems to fail to install some dependencies sometimes (for some OS/Python versions). @ancalita also run into this issue on Mac OS locally. 

See example CI failure in https://github.com/RasaHQ/rasa/runs/4867661448?check_suite_focus=true

This blocks https://github.com/RasaHQ/rasa/pull/10590

Definition of done:

- [ ] Update `.github/poetry_version.txt` to have 1.1.11

**Comment by HotThoughts** [comment]
FYI, also opened a PR in the rasa-x repo ☝️
