### ISSUE TITLE
API endpoint to delete data from the TrackerStore 

### ISSUE THREAD

**Issue by ghost** [RasaHQ/rasa#10719]
### What problem are you trying to solve?

To be compliant with GDPR, it must be possible to delete conversational data from the tracker store after a certain time period.

### What's your suggested solution?

Have an endpoint on the Rasa OSS server for deleting data in the tracker store according to passable parameters (timestamp or timespan).

Down the line, there would be a need to be able to remove all data for a specific user by a single request.

### Examples (if relevant)

 _No response_ 

### Is anything blocking this from being implemented? (if relevant)

 _No response_ 

### Definition of Done

 _No response_

**Comment by melindaloubser1** [comment]
Is this specific to the tracker store, or is the request for deletion from both the Rasa X DB and the Tracker store? 
see https://github.com/RasaHQ/rasa-x/issues/3050 for context

**Comment by melindaloubser1** [comment]
Suggestion: It'd make sense to start off with and endpoint for deleting a specific tracker, as a parallel to the endpoint for fetching a specific tracker. 

Then subsequently there could be a timestamp based deletion option.
