### ISSUE TITLE
Make sender_id accessible from custom NLU components

### ISSUE THREAD

**Issue by Maxinho96** [RasaHQ/rasa#10717]
### What problem are you trying to solve?

I need to access the sender_id from my custom NLU component, because I have an entity extractor that behaves differently depending on the user.

### What's your suggested solution?

nlu_message_converter should keep the sender_id when converting the messages.

### Examples (if relevant)

 _No response_ 

### Is anything blocking this from being implemented? (if relevant)

 _No response_ 

### Definition of Done

sender_id is accessible from a custom NLU component.

**Comment by ykiller2012** [comment]
Have you resolved this issue?

**Comment by Maxinho96** [comment]
> Have you resolved this issue?

Hi @ykiller2012 , you can check PR #10718 from [this](https://github.com/Maxinho96/rasa/tree/Access-sender_id-from-custom-NLU-components) branch for a workaround.
There is also another issue #11132 aimed to solve this problem, so I will close this one.
