### ISSUE TITLE
remove `_warn_and_correct_transformer_size` as it's not needed anymore

### ISSUE THREAD

**Issue by jupyterjazz** [RasaHQ/rasa#10712]
**What's the purpose of this function?** As the name suggests, `_warn_and_correct_transformer_size` corrects `transformer_size` parameter value in `ResponseSelector` and warns developers about this.

`transformer_size` is `None` by default. Hence, in case transformer layers are used inside `ResponseSelector` but `transformer_size` isn't specified in the config, we can't leave it to `None` and we correct it to a constant integer value.

**Why should we remove it?** The problem is that `_warn_and_correct_transformer_size` is only called during training. #10519 showed us that we need to correct the parameter during loading as well. #10651 solved the error by modifying this function [https://github.com/RasaHQ/rasa/blob/e522be7d989de94f5c2c57f86dd6fc1626941efb/rasa/utils/tensorflow/rasa_layers.py#L795](https://github.com/RasaHQ/rasa/blob/e522be7d989de94f5c2c57f86dd6fc1626941efb/rasa/utils/tensorflow/rasa_layers.py#L795) which is called during both training and prediction(loading). Thus, `_warn_and_correct_transformer_size` isn't needed anymore.

### Definition of Done

*   [ ] Remove `_warn_and_correct_transformer_size` and resolve failing tests caused by the removal
*   [ ] Move warning into [https://github.com/RasaHQ/rasa/blob/e522be7d989de94f5c2c57f86dd6fc1626941efb/rasa/utils/tensorflow/rasa_layers.py#L795](https://github.com/RasaHQ/rasa/blob/e522be7d989de94f5c2c57f86dd6fc1626941efb/rasa/utils/tensorflow/rasa_layers.py#L795)

**Comment by emysdias** [comment]
Hello there, I would like to work on this issue, can I?

**Comment by jupyterjazz** [comment]
Hi @emysdias, 
please go ahead and put me as a reviewer when you make a PR

**Comment by emysdias** [comment]
> Hi @emysdias, please go ahead and put me as a reviewer when you make a PR

ok, thanks
