### ISSUE TITLE
OpenTelemetry Tracing Instrumentation

### ISSUE THREAD

**Issue by joejuzl** [RasaHQ/rasa#10713]
h2.   Background

[Scope and implementation proposal| https://www.notion.so/rasa/Tracing-and-Telemetry-830d02a93bf14132918640e926480a71] We want to add OpenTelemetry support to Rasa. This ticket deals with adding instrumentation to the code base which will create the spans and traces when it runs. Configuring the collection of traces is covered in a [different issue| https://github.com/RasaHQ/rasa/issues/10714].

h2.   Description

For full list of code to trace and data to collect see the document linked in the *background* section. We want to add tracing to the following areas:

* Handling a message: 
  ** Receiving a message
** Locking the conversation
** Retrieving and saving the tracker
** Parsing the message
** Predicting the next action
** Running an action
** Running each graph component
** Publishing to the event broker
** Passing the trace context to the action server to link with tracing  _inside_  custom actions.
* Training a model 
  ** Training of each graph component 

To actually create the traces we should create a decorator that works something like:

<pre>@trace(paramters_to_capture=["a"])
def run(a, b):
	...</pre>

If there are code areas that we can not trace using a decorator, we should use the provided context manager, e.g.:

<pre>with tracer.start_as_current_span("Processor.handle_message", attributes={}):
    ...</pre>

If the configuration ticket has not yet been completed this can still be tested locally as shown in the document linked above.

h2.   Definition of Done

* [ ] All areas listed in the scope document are traced with the required data collected.
* [ ] Handling a message and training a model are tested locally to confirm that the structure of the traces make sense.

**Comment by rgstephens** [comment]
@joejuzl is this no longer a planned enhancement?

**Comment by m-vdb** [comment]
@rgstephens yes it is. We're tracking progress elsewhere though, this is why I closed the issue.

**Comment by rgstephens** [comment]
Does this mean enhancement requests are no longer tracked in GitHub, only bugs?

**Comment by m-vdb** [comment]
AFAIK the new process is still not rolled out. We still have some enhancement requests in GitHub today, I expect this could change in the future.
