### ISSUE TITLE
PikaEventBroker not supporting amqp full url and virtualhost after 3.0

### ISSUE THREAD

**Issue by venushong667** [RasaHQ/rasa#10724]
### Rasa Open Source version

3.0.4

### Rasa SDK version

 _No response_ 

### Rasa X version

 _No response_ 

### Python version

3.8

### What operating system are you using?

Windows

### What happened?

Before rasa 3.0, we can define amqp url with vhost

event_broker: type: "pika" url: amqp://user:password@localhost:5672/vhost username: user password: password queues:

*   rasa-event exchange_name: rasa-exchange

However, after rasa 3.0 the url definition is not working anymore From my findings, it is due to change of method parsing url, Rasa 2.X is assigning the complete url as url parameter, while the new parsing in Rasa 3.0 parsed the url become a not working url (I printed it manually in cli)

> Rasa 2.X pika.py

async def _connect(self) -> aio_pika.RobustConnection: url = None

1.  The `url` parameter will take precedence over parameters like `login` or
2.  `password`. if self.host.startswith("amqp"): url = self.host

> Rasa 3.X pika.py

async def _connect(self) -> aio_pika.RobustConnection: url = None

1.  The `url` parameter will take precedence over parameters like `login` or
2.  `password`. if self.host.startswith("amqp"):

parsed_host = urlparse(self.host) amqp_user = f"

 {self.username} 

:

 {self.password} 

" url = f"

 {parsed_host.scheme} 

://

 {amqp_user} 

@

 {parsed_host.netloc} 

:

 {self.port} 

"

> Ouput: url = amqp://user:password@user:password@localhost:5672 The parser in 3.X treat all the parameter before port as netloc and also removed /vhost

From documentation, currently it only support the definition of host, username and password, but I can't find any method to define vhost in Rasa 3.X May I know is there any other approach that I missing out or the issue above can be fixed?

### Command / Request

 _No response_ 

### Relevant log output

 _No response_

**Comment by sara-tagger** [comment]
Thanks for raising this issue, @sebwarnke will get back to you about it soon✨

###### Please also check out the [docs](https://rasa.com/docs/) and the [forum](https://forum.rasa.com/) in case your issue was raised there too 🤗
