### ISSUE TITLE
Rasa 3.x using significantly more memory

### ISSUE THREAD

**Issue by souvikg10** [RasaHQ/rasa#10727]
### Rasa Open Source version

3.0.4

### Rasa SDK version

 _No response_ 

### Rasa X version

 _No response_ 

### Python version

3.8

### What operating system are you using?

Linux

### What happened?

So i did a little memory profiler to compare the difference in memory usage in Rasa 3.0 compared to my previous version of Rasa 2.6.x since my K8s pods suddenly started issuing OOM kills in Rasa 3.0 after loading the model

I compared only loading the NLU models as that's what i was concered with and used the corresponding Rasa API in each of them to profile it

@tmbo - let me know your thoughts on it.. I mean the difference is quite significant in inference(almost double), also am i using the right methods to profile it?

# RASA 3.0 Line # Mem usage Increment Occurrences Line Contents

14 406.7 MiB 406.7 MiB 1 @profile 15 def get_interpreter(self, model_path): 16 406.7 MiB 0.0 MiB 1 try: 17 406.7 MiB 0.0 MiB 1 model = get_validated_path(model_path, "model", DEFAULT_MODELS_PATH) 18 1003.0 MiB 596.4 MiB 1 agent = Agent.load(model_path) 19 1003.0 MiB 0.0 MiB 1 return agent

RASA 2.6.1

15 332.1 MiB 332.1 MiB 1 @profile 16 def get_interpreter(self, model_path): 17 332.1 MiB 0.0 MiB 1 try: 18 332.1 MiB 0.0 MiB 1 model = get_validated_path(model_path, "model", DEFAULT_MODELS_PATH) 19 332.1 MiB 0.0 MiB 1 model_path = get_model(model) 20 332.1 MiB 0.0 MiB 1 _, nlu_model = get_model_subdirectories(model_path) 21 22 653.3 MiB 321.2 MiB 1 interpreter = Interpreter.load(nlu_model) 23 24 653.3 MiB 0.0 MiB 1 return interpreter

### Command / Request

 _No response_ 

### Relevant log output

 _No response_

**Comment by sara-tagger** [comment]
Thanks for the issue, @s-elsharkawy will get back to you about it soon!

###### You may find help in the [docs](https://rasa.com/docs/) and the [forum,](https://forum.rasa.com/) too 🤗

**Comment by souvikg10** [comment]
Some more realistic numbers after benchmarking.. Turns out @dakshvar22 it is due to tensorflow upgrade

Between Rasa 2.8.9 and Rasa 2.8.8, here is the memory and load time profile i did.. turns out for me even if the memory swelling is manageable but the load time is hard to explain because it practically doubles. ofcourse - this is not the pure load time of the model itself but the significant uptick is due to the version upgrade. 

```
Rasa 2.8.9
Line #    Mem usage    Increment  Occurrences   Line Contents
=============================================================
    15    341.4 MiB    341.4 MiB           1       @profile
    16                                             def get_interpreter(self, model_path):
    17    341.4 MiB      0.0 MiB           1           try:
    18    341.4 MiB      0.0 MiB           1               print(model_path)
    19    341.4 MiB      0.0 MiB           1               model = get_validated_path(model_path, "model", DEFAULT_MODELS_PATH)
    20    341.4 MiB      0.0 MiB           1               model_path = get_model(model)
    21    341.4 MiB      0.0 MiB           1               _, nlu_model = get_model_subdirectories(model_path)
    22                                         
    23    919.8 MiB    578.4 MiB           1               interpreter = Interpreter.load(nlu_model)
    24                                         
    25    919.8 MiB      0.0 MiB           1               return interpreter
    
Load Time upon startup - 24-Jan-22 14:54:52 - DEBUG - 127.47065615653992


Rasa 2.8.8
Line #    Mem usage    Increment  Occurrences   Line Contents
=============================================================
    15    327.8 MiB    327.8 MiB           1       @profile
    16                                             def get_interpreter(self, model_path):
    17    327.8 MiB      0.0 MiB           1           try:
    18    327.8 MiB      0.0 MiB           1               print(model_path)
    19    327.8 MiB      0.0 MiB           1               model = get_validated_path(model_path, "model", DEFAULT_MODELS_PATH)
    20    327.8 MiB      0.0 MiB           1               model_path = get_model(model)
    21    327.8 MiB      0.0 MiB           1               _, nlu_model = get_model_subdirectories(model_path)
    22                                         
    23    628.2 MiB    300.4 MiB           1               interpreter = Interpreter.load(nlu_model)
    24                                         
    25    628.2 MiB      0.0 MiB           1               return interpreter
    
Load Time upon startup - 24-Jan-22 15:14:35 - DEBUG - 60.485530376434326
```

**Comment by dakshvar22** [comment]
Thanks @souvikg10! What was the load time upon startup for `2.6.1` version that you were originally using?

**Comment by souvikg10** [comment]
Same as Rasa 2.8.8 ,the 2.6.1 version takes around 60 seconds on my laptop, which reduces down on the servers to 23-30 seconds which is acceptable for multiple respawns of k8s pods

**Comment by souvikg10** [comment]
@dakshvar22  - just an FYI the numbers you see in terms of load time is with the profiler enabled which eats up some of the time but the bottom line is that with DIET enabled for both intent and entity recognition, the load time doubled compared to Rasa 2.8.8 or Rasa 2.6.1 

I tried with DIET entity recognition as False and the performance was just as how it was with Rasa 2.6.1 again.. so i guess the issue is somewhere with how DIET entity recognition works with regards to tensorflow.. I suppose this is known to you guys.
