### ISSUE TITLE
Add failed test stories to artifact of model regression workflow

### ISSUE THREAD

**Issue by dakshvar22** [RasaHQ/rasa#10730]
### What problem are you trying to solve?

We have seen a couple of instances of performance drops in scheduled model regression workflow ([this](https://github.com/RasaHQ/rasa/issues/10415) and [this](https://github.com/RasaHQ/rasa/issues/10690)) over the past 2 months but we couldn't reproduce any of them post-hoc. We tried reproducing these by just re-running the workflow, however none of the manual re-runs (done at least 10 times) displayed a drop in performance.

Moreover, both the times the drop is observed only on the `sara` dataset with `rules + ted` config. [Here's a filtered view](https://metabase.rasa.com/question#eyJkYXRhc2V0X3F1ZXJ5Ijp7ImRhdGFiYXNlIjoyLCJxdWVyeSI6eyJzb3VyY2UtdGFibGUiOjE4NDMsImZpbHRlciI6WyJhbmQiLFsiPSIsWyJmaWVsZCIsMTI4MTYsbnVsbF0sIlNhcmEiXSxbIj0iLFsiZmllbGQiLDEyODUyLG51bGxdLCJSdWxlcyArIFRFRCJdLFsiPSIsWyJmaWVsZCIsMTI5MzAsbnVsbF0sInNjaGVkdWxlIl1dLCJmaWVsZHMiOltbImZpZWxkIiwxMjg1MixudWxsXSxbImZpZWxkIiwxMjgxNixudWxsXSxbImZpZWxkIiwxMjg1MSxudWxsXSxbImZpZWxkIiwxMjkzMCxudWxsXSxbImZpZWxkIiwxMjkwNCxudWxsXSxbImZpZWxkIiwxMjkwNixudWxsXSxbImZpZWxkIiwxMjgyNixudWxsXSxbImZpZWxkIiwxMjgzOCxudWxsXSxbImZpZWxkIiwxMjgxOSxudWxsXSxbImZpZWxkIiwxMjkwNSxudWxsXSxbImZpZWxkIiwxMjgyNyxudWxsXSxbImZpZWxkIiwxMjgzNyxudWxsXSxbImZpZWxkIiwxMjgzMixudWxsXSxbImZpZWxkIiwxMjgzMSxudWxsXSxbImZpZWxkIiwxNjg3MixudWxsXSxbImZpZWxkIiwxNjg3MyxudWxsXSxbImZpZWxkIiwxNjg3NCxudWxsXSxbImZpZWxkIiwxNzM2NSxudWxsXV19LCJ0eXBlIjoicXVlcnkifSwiZGlzcGxheSI6InRhYmxlIiwidmlzdWFsaXphdGlvbl9zZXR0aW5ncyI6e319) in metabase that shows the drop in two instances on this specific pair of config and dataset

We suspect this could be one of the two problems:

1. The test dataset has an unknown skew towards a particular action which sometimes is not being learnt by the pipeline resulting in a failure on particular test stories.
2. Something is problematic with the infrastructure on which the scheduled runs are carried out. There has been [some discussion](https://rasa-hq.slack.com/archives/C01H2UCNP2T/p1638965125238800) on this in the past but nothing conclusive came out.
3. There is a weird bug in how numbers are collected from the runs of `rasa test` and stored in metabase / how performance drop triggers are calculated.

We would like to be completely sure that its not a dataset / algorithmic issue to rule out the possibility of (1). While we have done multiple re-runs of these workflows in order to try and reproduce the drop but we haven't got any far with it. We would need to collect more diagnostic data as part of these runs in order to investigate further.

### What's your suggested solution?

When you [run `rasa test core`](https://rasa.com/docs/rasa/testing-your-assistant#evaluating-a-dialogue-model), it outputs two artifacts - `results/failed_test_stories.yml` and `results/story_confmat.png` (assuming `results` is the folder where the output is generated). It would be great if we can add these two artifacts to the output artifact bundle that is generated by the workflow run.

Since there will be many reports created (one for each combination of config and dataset), here's a suggestion on how this could be structured in the artifact bundle:

```
diagnostic_data
|
|--- <dataset-name>
|           |
|           |
|           |---- <config-name>
|           |             |
|           |             |
|           |             |------ failed_test_stories.yml
|           |             | ------ story_confmat.png
```

Note that these artifacts will only be generated for the configs which evaluate dialog policy performance, i.e. the ones present [here](https://github.com/RasaHQ/training-data/tree/main/configs/en/core) and mentioned in the config-map [here](https://github.com/RasaHQ/training-data/blob/main/dataset_config_mapping.json#L77)

### Definition of Done

- [ ] Above suggestion implemented for scheduled and on-demand (for debugging purposes) model regression workflow runs
- [ ] Tested by a member of the research team to verify if the output is indeed what's needed.

**Comment by koernerfelicia** [comment]
@dakshvar22 this isn't actually supposed to be on our board, right? I'm wondering if the `tool:model-regression-tests` label triggers rasabot to move it to our Inbox?

**Comment by dakshvar22** [comment]
Yeah looks like a "feature" of the automated setup. I'll move it to infra
