### ISSUE TITLE
Rasa webchat Widget can't connect, Sanic issues.

### ISSUE THREAD

**Issue by koaning** [RasaHQ/rasa#10741]
h2.   The Setup

I'm trying to get the Rasa web widget to work. I've checked [the docs| https://rasa.com/docs/rasa/connectors/your-own-website/#jwt-authentication] and followed the appropriate steps. I also used [jwt.io| https://jwt.io/] to generate the following credentials:

<pre>socketio:
  user_message_evt: user_uttered
  bot_message_evt: bot_uttered
  session_persistence: true
  jwt_key: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.e30.EbdFNTRirDsnHDszNTRBoWo806dW7m6mVob_s3sVnFo
  jwt_method: HS256</pre>

The `jwt_key` was generated by using `this-is-really-secret` as a secret key and using an empty payload on [jwt.io| https://jwt.io/].

Next, I run Rasa locally.

    python -m rasa run --cors '*' --jwt-method HS265 --jwt-secret "this-is-really-secret"

Given that Rasa is now running, I'll serve a static `index.html` file. This is the contents:

<pre>
 <div id="rasa-chat-widget" data-websocket-url="http://0.0.0.0:5005"></div>
<script src="https://unpkg.com/@rasahq/rasa-chat" type="application/javascript"></script></pre>

I've checked with @samgardner517 and confirmed that these settings seem to be correct. Given that I have a static HTML page, I serve it locally.

    python -m http.server

h2.   The Issue

When I try to chat in the widget, the server emits the following error.

<pre>Exception occurred while handling uri: 'ws://0.0.0.0:5005/socket.io/?EIO=4&amp;transport=websocket&amp;sid=XMfgTJct5OM1_MEAAAAK'
Traceback (most recent call last):
  File "/home/vincent/Development/rasa-web-widget/venv/lib/python3.7/site-packages/sanic/server/protocols/websocket_protocol.py", line 119, in websocket_handshake
    subprotocols = list(subprotocols)
  File "/usr/lib/python3.7/typing.py", line 254, in inner
    return func(*args, **kwds)
  File "/usr/lib/python3.7/typing.py", line 634, in __getitem__
    params = tuple(_type_check(p, msg) for p in params)
  File "/usr/lib/python3.7/typing.py", line 634, in <genexpr>

    params = tuple(_type_check(p, msg) for p in params)
  File "/usr/lib/python3.7/typing.py", line 142, in _type_check
    raise TypeError(f"{msg} Got {arg!r:.100}.")
TypeError: Parameters to generic types must be types. Got 0.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "handle_request", line 83, in handle_request
    class Sanic(BaseSanic, metaclass=TouchUpMeta):
  File "/home/vincent/Development/rasa-web-widget/venv/lib/python3.7/site-packages/engineio/asyncio_server.py", line 271, in handle_request
    packets = await socket.handle_get_request(environ)
  File "/home/vincent/Development/rasa-web-widget/venv/lib/python3.7/site-packages/engineio/asyncio_socket.py", line 89, in handle_get_request
    return await getattr(self, '_upgrade_' + transport)(environ)
  File "/home/vincent/Development/rasa-web-widget/venv/lib/python3.7/site-packages/engineio/asyncio_socket.py", line 142, in _upgrade_websocket
    return await ws(environ)
  File "/home/vincent/Development/rasa-web-widget/venv/lib/python3.7/site-packages/engineio/async_drivers/sanic.py", line 122, in __call__
    self._sock = await protocol.websocket_handshake(request)
  File "/home/vincent/Development/rasa-web-widget/venv/lib/python3.7/site-packages/sanic/server/protocols/websocket_protocol.py", line 132, in websocket_handshake
    raise ServerError(msg, status_code=500)
sanic.exceptions.ServerError: Failed to open a WebSocket connection.
See server log for more information.

The client is using an unsupported version of the Socket.IO or Engine.IO protocols (further occurrences of this error will be logged with level INFO)
 </genexpr></pre>

Sanic seems to have issues opening the WebSocket connection. So I figured opening an issue to track it.

h2.   Version Info

    Rasa Version      :         3.0.5
    Minimum Compatible Version: 3.0.0
    Rasa SDK Version  :         3.0.3
    Rasa X Version    :         None
    Python Version    :         3.7.9
    Operating System  :         Linux-5.11.0-7614-generic-x86_64-with-Pop-20.10-groovy
    Python Path       :         /home/vincent/Development/rasa-web-widget/venv/bin/python

**Comment by passtech** [comment]
Idem with Rasa 3.0.2

Rasa Version      :         3.0.2
Minimum Compatible Version: 3.0.0
Rasa SDK Version  :         3.0.2
Rasa X Version    :         None
Python Version    :         3.8.10
Operating System  :         Linux-5.4.0-100-generic-x86_64-with-glibc2.29
Python Path       :         /usr/bin/python3

**Comment by m-vdb** [comment]
@passtech can you check with 3.0.9? We've addressed a few issues with sockets in this version, and maybe this issue is solved now. Let me know!

**Comment by mikhail-skorikov** [comment]
I had a similar problem in which I was trying to connect to rasa's socket.io using a python client ([python-socketio](https://pypi.org/project/python-socketio/)) but it was failing with the same error as above. 

Upgrading rasa to 3.0.9 fixed it, so thank you for that!

**Comment by m-vdb** [comment]
thanks for confirming 🙏🏻 I'll close this issue then 😄
