### ISSUE TITLE
caching and response selector texts

### ISSUE THREAD

**Issue by amn41** [RasaHQ/rasa#10751]
### Rasa Open Source version

3.0.4

### Rasa SDK version

 _No response_ 

### Rasa X version

 _No response_ 

### Python version

3.7

### What operating system are you using?

OSX

### What happened?

STR:

*   Modified moodbot to add a retrieval intent
*   train a model
*   change the response text of one of the faq responses
*   re-run `rasa train`

expected behaviour: `ResponseSelector` component shouldn't need to be retrained, since `use_text_as_label` is set to False (the defailt).

observed behaviour: `ResponseSelector` component and `DIETClassifier` are both re-trained instead of being restored from cache.

### Command / Request

 _No response_ 

### Relevant log output

 _No response_ 

**Definition of done**

*   [ ] Determine if it is possible using existing fingerprinting approach
*   [ ] Changing the response text of response selector should not cause a retrain

**Comment by m-vdb** [comment]
@jupyterjazz could you take a look at this one? (let's sync when you're back)
