### ISSUE TITLE
[DaskGraphRunner] dask.threaded.get instead of dask.get

### ISSUE THREAD

**Issue by toza-mimoza** [RasaHQ/rasa#10754]
### What problem are you trying to solve?

I was trying to use Dask on Ray (see [docs](https://docs.ray.io/en/latest/data/dask-on-ray.html)) for distributing the graph training on multiple nodes when I noticed that DaskGraphRunner uses a synchronous "single-threaded" scheduler. Is there any specific reason why it is synchronous instead of threaded?

### What's your suggested solution?

Replace `dask.get(run_graph, run_targets)` line 101 of [dask.py](https://github.com/RasaHQ/rasa/blob/main/rasa/engine/runner/dask.py) with `dask.threaded.get(run_graph, run_targets)`.

Result is about 6-7s shorter training time when forcing complete training on my local machine and successful save of the training model.

### Examples (if relevant)

 _No response_ 

### Is anything blocking this from being implemented? (if relevant)

 _No response_ 

### Definition of Done

Schedulers are replaced and the training model is successfully saved.

**Comment by sara-tagger** [comment]
Thanks for submitting this feature request 🚀 @sebwarnke will get back to you about it soon! ✨
