### ISSUE TITLE
Rasa crashes after sending invalid intent

### ISSUE THREAD

**Issue by Ra0k** [RasaHQ/rasa#10778]
### Rasa Open Source version

2

### Rasa SDK version

 _No response_ 

### Rasa X version

 _No response_ 

### Python version

3.7

### What operating system are you using?

Linux

### What happened?

I have a Rasa program that is integrated with Telegram. After sending an invalid intent in the chat "/intent" the server crashes. Even restart doesn't solve the problem, as the events are stored in the database. The server just keeps picking up the last unprocessed message and fails again. I can solve the problem by erasing the message from the database and emptying the unseen messages from Telegram **BUT** isn't it a huge problem? What happens if a malicious user does the same? Can they crash my server by just sending an invalid intent? How could I prevent that?

### Command / Request

 _No response_ 

### Relevant log output

 _No response_

**Comment by sara-tagger** [comment]
Thanks for the issue, @sebwarnke will get back to you about it soon!

###### You may find help in the [docs](https://rasa.com/docs/) and the [forum,](https://forum.rasa.com/) too 🤗

**Comment by SamuelNoB** [comment]
can you put more info like the request and the log output?
