### ISSUE TITLE
Two stage fallback does not store entity values if user affirms their intent

### ISSUE THREAD

**Issue by hsm207** [RasaHQ/rasa#10776]
### Rasa Open Source version

2.8.22

### Rasa SDK version

2.8.4

### Rasa X version

 _No response_ 

### Python version

3.8

### What operating system are you using?

Linux

### What happened?

If a user utters an intent that has low confidence and affirms it, the conversation proceeds as if the user has uttered that intent but the slots that were extracted from the utterance is ignored.

To reproduce:

1.  Clone and train this [bot](https://github.com/hsm207/rasa_moodbot/tree/bug_twostage).
2.  Run `rasa shell -vv`
3.  Utter `🐝 hello I like chinese food 🐝🐝🐝🐝 bye` at the start of the conversation

[<span class="image-wrap" style="">![](https://user-images.githubusercontent.com/2398765/151583308-7964f7e5-09a7-4c79-9d01-757ae68ec3ee.png)</span>](https://user-images.githubusercontent.com/2398765/151583308-7964f7e5-09a7-4c79-9d01-757ae68ec3ee.png) [<span class="image-wrap" style="">![](https://user-images.githubusercontent.com/2398765/151583382-16d287b6-5467-49d2-a4e5-6f93b1ac26bf.png)</span>](https://user-images.githubusercontent.com/2398765/151583382-16d287b6-5467-49d2-a4e5-6f93b1ac26bf.png) notice that the `cuisine` slot is filled and the two stage action fallback action is activated.

1.  Select `yes` [<span class="image-wrap" style="">![](https://user-images.githubusercontent.com/2398765/151583692-ecd9e73c-d4e4-4768-b3a3-b7be14793936.png)</span>](https://user-images.githubusercontent.com/2398765/151583692-ecd9e73c-d4e4-4768-b3a3-b7be14793936.png)

[<span class="image-wrap" style="">![](https://user-images.githubusercontent.com/2398765/151583781-5ded46c8-d7cf-4861-94dc-8a5b14179073.png)</span>](https://user-images.githubusercontent.com/2398765/151583781-5ded46c8-d7cf-4861-94dc-8a5b14179073.png)

Notice that the bot correctly utters `Bye` but the `cuisine` slot is empty.

### Command / Request

 _No response_ 

### Relevant log output

 _No response_ 

### Overview of Solution

As can be seen in @hsm207's repo, this bug can be fixed by adding the entities to the button payload of the `ActionDefaultAskAffirmation` action. We should add this to the default `ActionDefaultAskAffirmation` so that it will work out-of-the-box and not require a custom action to save user entities.

### Definition of Done

*   [ ] Add json encoded entities to button payload of default `ActionDefaultAskAffirmation`
*   [ ] Unit test.

**Comment by sML-90** [comment]
Hi, 
Is there any update on the above issue ? How can we avoid this scenario to happen.

**Comment by m-vdb** [comment]
no update, but the task has been migrated to Jira here: https://rasa-open-source.atlassian.net/browse/OSS-572
