### ISSUE TITLE
Remove `linear_norm` from docs

### ISSUE THREAD

**Issue by mleimeister** [RasaHQ/rasa#10798]
### Rasa Open Source version

3.0.x

### Rasa SDK version

 _No response_ 

### Rasa X version

 _No response_ 

### Python version

3.8

### What operating system are you using?

OSX

### What happened?

The `linear_norm` setting is still listed as an option for the `model_confidence` parameter in `TEDPolicy` and `DIETClassifier`. However, it has been [removed](https://github.com/RasaHQ/rasa/blob/main/CHANGELOG.mdx#300---2021-11-23) in `3.0.0`. Therefore, the documentation around model confidences should be reformulated.

### Command / Request

 _No response_ 

### Relevant log output

 _No response_

**Comment by koernerfelicia** [comment]
I think this could be a good one for @s-elsharkawy. The small drawback is that it only involves docs, and not "actual" code

**Comment by s-elsharkawy** [comment]
Thanks @koernerfelicia . I am happy to take this one on Monday.
