### ISSUE TITLE
Docs recommend conveRT embeddings in "Tuning Your NLU Model"

### ISSUE THREAD

**Issue by rctatman** [RasaHQ/rasa#10805]
### What problem are you trying to solve?

In the "Tuning your NLU Model" docs there's a paragraph where we recommend conveRT embeddings, which [are no longer publicly available](https://github.com/PolyAI-LDN/polyai-models#convert).

Docs page: [https://rasa.com/docs/rasa/tuning-your-model/#pre-trained-embeddings](https://rasa.com/docs/rasa/tuning-your-model/#pre-trained-embeddings) File: rasa/docs/docs/tuning-your-model.mdx

### What's your suggested solution?

The paragraph should either be deleted or updated with the current embedding recommendation.

### Examples (if relevant)

 _No response_ 

### Is anything blocking this from being implemented? (if relevant)

 _No response_ 

### Definition of Done

 _No response_

**Comment by Matheus73** [comment]
I think it's important, what do you think about do this @SamuelNoB?

**Comment by SamuelNoB** [comment]
The docs already mention an alternative to the conveRT embeddings wich is the `LanguageModel`. Perhaps, changing the parts where `conveRT` is recommended to use `LanguageModel` is the way to go.
