### ISSUE TITLE
Slot mappings parameter becomes mandatory once used

### ISSUE THREAD

**Issue by ekon15** [RasaHQ/rasa#10801]
### Rasa Open Source version

3.0.6

### Rasa SDK version

 _No response_ 

### Rasa X version

 _No response_ 

### Python version

3.8

### What operating system are you using?

OSX

### What happened?

Using the `mappings` parameter for any slot throws an error for all other slots not using `mappings`.

Validates correctly:

slots: role_type: type: text influence_conversation: true

Validates correctly:

slots: change_from_currency: type: text mappings:

*   type: from_entity entity: currency role: change_from

Combining the slot definitions together throws an error:

slots: role_type: type: text influence_conversation: true change_from_currency: type: text mappings:

*   type: from_entity entity: currency role: change_from

Validation error message:

YamlValidationException: Failed to validate '/Users/eric/rasa_test/domain.yml'. Please make sure the file is correct and all mandatory parameters are specified. Here are the errors found during validation: in /Users/eric/rasa_test/domain.yml:26: Cannot find required key 'mappings'. Path: '/slots/role_type'

User expects consistent validation of `mappings` parameter

### Command / Request

 _No response_ 

### Relevant log output

 _No response_

**Comment by sara-tagger** [comment]
Thanks for raising this issue, @b-quachtran will get back to you about it soon✨

###### Please also check out the [docs](https://rasa.com/docs/) and the [forum](https://forum.rasa.com/) in case your issue was raised there too 🤗

**Comment by melindaloubser1** [comment]
The `mappings` key is always required in 3.x; see the [migration guide](https://rasa.com/docs/rasa/migration-guide/#slot-mappings). In version 3.1 you will get the same error for a single slot that doesn't have the mappings key, which is the expected behaviour.
