### ISSUE TITLE
Rasa Playground does not capture email

### ISSUE THREAD

**Issue by koaning** [RasaHQ/rasa#10800]
As mentioned on [our forum| https://forum.rasa.com/t/rasa-playground-v3/50084/11] it seems there's a glaring bug in our playground that prevents the email address from registering.

[!https://camo.githubusercontent.com/746c4e2b6027d433059fa1da7629612c8f2f87181c055548b29e9d45b0db3e54/68747470733a2f2f666f72756d2e726173612e636f6d2f75706c6f6164732f64656661756c742f6f726967696e616c2f33582f302f612f306135393138656664376164356439636532316435343030393437313937343036303433646265632e6a706567!| https://camo.githubusercontent.com/746c4e2b6027d433059fa1da7629612c8f2f87181c055548b29e9d45b0db3e54/68747470733a2f2f666f72756d2e726173612e636f6d2f75706c6f6164732f64656661756c742f6f726967696e616c2f33582f302f612f306135393138656664376164356439636532316435343030393437313937343036303433646265632e6a706567]

**Comment by aleSuglia** [comment]
Is this still an open issue?

**Comment by aleSuglia** [comment]
@m-vdb is it possible to fix this? At the moment it's not possible to use the library from the website!
