### ISSUE TITLE
empty conversation in rasa-x >= 1.0.0 when 'action_restart' is executed

### ISSUE THREAD

**Issue by TimWaWIT** [RasaHQ/rasa#10820]
### Rasa Open Source version

2.8.12

### Rasa SDK version

2.8.1

### Rasa X version

> = 1.0.0

### Python version

3.8

### What operating system are you using?

Linux, Self hosted Cloud (openshift)

### What happened?

When the action: action_restart is executed inside a conversation, the whole conversation-history is deleted (or at least empty in the UI). For further description with screenshots see: [<span class="error">[https://forum.rasa.com/t/empty-conversations-in-rasa-x-1-x-x/51079|| https://forum.rasa.com/t/empty-conversations-in-rasa-x-1-x-x/51079%7C]</span> url].

### Command / Request

 _No response_ 

### Relevant log output

 _No response_

**Comment by sara-tagger** [comment]
Thanks for raising this issue, @koaning will get back to you about it soon✨

###### Please also check out the [docs](https://rasa.com/docs/) and the [forum](https://forum.rasa.com/) in case your issue was raised there too 🤗

**Comment by TimWaWIT** [comment]
Is there any update? :) @koaning
