### ISSUE TITLE
Add test preparation for Arch based systems

### ISSUE THREAD

**Issue by SamuelNoB** [RasaHQ/rasa#10828]
### What problem are you trying to solve?

Currently there are only test preparation commands for ubuntu, macos and windows systems inside the project Makefile. The commands available are `make prepare-tests-macos`, `make prepare-tests-ubuntu`, `make prepare-tests-windows`.

However Arch based systems doesn't have support for these commands since `pacman` it's default package manager, hence running `make prepare-tests-ubuntu` will not work.

### What's your suggested solution?

Create a command `prepare-tests-arch`, inside the Makefile, for Arch based systems to prepare the test environment .

### Examples (if relevant)

 _No response_ 

### Is anything blocking this from being implemented? (if relevant)

 _No response_ 

### Definition of Done

*   [ ] Create command `prepare-tests-arch` inside the Makefile.
*   [ ] Append command to Makefile `help` command
*   [ ] Append command to Rasa README.md

**Comment by sara-tagger** [comment]
Thanks for submitting this feature request 🚀 @mvielkind will get back to you about it soon! ✨
