### ISSUE TITLE
test stories failing when entities with "from" and "to" fields are present

### ISSUE THREAD

**Issue by Polaris000** [RasaHQ/rasa#10842]
### Rasa Open Source version

2.6.0

### Rasa SDK version

2.7.0

### Rasa X version

0.38.1

### Python version

3.7

### What operating system are you using?

Linux

### What happened?

I’m using Duckling to extract amount-of-money and time (both of which are standard entities provided by duckling). My stories (training stories) are written like this with the from-to range:

*   intent: some_intent
*   slot_was_set:
*   amount-of-money: from: 1000 to: 1000

There are no issues in the training or performance of the bot when I have my stories set up like this. In fact, this is what Rasa - X generates.

The issue I’m referring to arises when I’m testing my bot. When I generate a test story using rasa -x, I get something that looks like this:

*   intent: some_intent user: |- some_intent ... <span class="error">[670-5101]</span>{"entity": "amount-of-money", "value": {"to": 5101, "from": 670}} ...
*   slot_was_set:
*   amount-of-money: to: 5101 from: 670

which is technically valid (at least based on what Rasa considers valid when it comes to training stories).

But, it throws an invalid error while running tests.

InvalidEntityFormatException: Incorrect training data format ('{"entity": "amount-of-money", "value":

 {"to": 5101, "from": 670} 

'). More info at [https://rasa.com/docs/rasa/training-data-format#nlu-training-data:](https://rasa.com/docs/rasa/training-data-format#nlu-training-data:) line 1 column 65 (char 64)

I had asked this on the forums but was told to create an issue. [link to forum post](https://forum.rasa.com/t/rasa-core-testing-fails-with-ranged-entities-from-to/50764)

### Command / Request

<pre>rasa test</pre>

### Relevant log output

<pre>InvalidEntityFormatException: Incorrect training data format ('{"entity": "amount-of-money", "value": 

 {"to": 5101, "from": 670} 

'). More info at [https://rasa.com/docs/rasa/training-data-format#nlu-training-data:](https://rasa.com/docs/rasa/training-data-format#nlu-training-data:)([https://rasa.com/docs/rasa/training-data-format#nlu-training-data:](https://rasa.com/docs/rasa/training-data-format#nlu-training-data:)) line 1 column 65 (char 64)</pre>

**Comment by sara-tagger** [comment]
Thanks for raising this issue, @carlad will get back to you about it soon✨

###### Please also check out the [docs](https://rasa.com/docs/) and the [forum](https://forum.rasa.com/) in case your issue was raised there too 🤗

**Comment by carlad** [comment]
@Polaris000 I've brought this issue to the attention of our Rasa Open Source team, who have added it to their inbox. Any updates can be followed by subscribing to notifications (see the right-hand column on this page). Thanks again for reporting this 😄

**Comment by Polaris000** [comment]
Thanks for the help @carlad

**Comment by melindaloubser1** [comment]
@Polaris000 The underlying issue is that Duckling entity values are not strings. If you change the entity annotation to the shorthand without the value e.g. `some_intent ... [670-5101]("amount-of-money")` it will work. You don't need these annotations in training data at all because Duckling is rule-based, but if you need them in test stories  you can get around it by using the short format.
