### ISSUE TITLE
Specify output file of annotated data for Rasa X

### ISSUE THREAD

**Issue by MarleenBor** [RasaHQ/rasa#10872]
### What problem are you trying to solve?

Currently, you can't specify which file the annotated data from Rasa X gets added to when you push the NLU data to your git repository. As far as I know, it depends on the order in which your OS reads the files in your directory. It seems to get added to the first yml file.

I would like to be able to specify the NLU file the data gets appended to inside the `data `folder. In my project, we have multiple NLU files in the `data `folder that we don't want to combine for various reasons (mostly because we don't want to mix real and synthetic data) and the annotated data gets appended to the "wrong" file. That means I then have to manually copy it to the correct file and push the changes which is not scalable. 

### What's your suggested solution?

I don't know the technical details but it would be great if you could specify the output file for annotated data via the Rasa X UI. 

### Definition of Done

The feature would be done once it is possible to specify the output file for the annotated data.

**Comment by sara-tagger** [comment]
Thanks for submitting this feature request 🚀 @akelad will get back to you about it soon! ✨

**Comment by hsm207** [comment]
closing and moving this to the rasa-x repo
