### ISSUE TITLE
Intent slot assign instead of  Requested slot(both intent slot and form slot have different name) when form is activated

### ISSUE THREAD

**Issue by Shailendrasnegi** [RasaHQ/rasa#10892]
### Rasa Open Source version

Rasa Version : 2.8.2

### Rasa SDK version

Rasa SDK Version : 2.8.4

### Rasa X version

Rasa X Version : None

### Python version

3.8

### What operating system are you using?

Windows

### What happened?

HI, Please support here. I have an "intent: my_subcategories" with entity name : "subcateg". I have a defined a form and when form is activated (type: from_text) and we type any message, ideally it should assign to requested slot (slot name: "description") but it assign to slot: subcateg since we are typing Intent example. I have tried to excluse intend but same issue happening.... +++++++++++++++++ slots: categ: type: text influence_conversation: false subcateg: type: text influence_conversation: false service: type: text influence_conversation: false description: type: text influence_conversation: false incident: type: text influence_conversation: false documnet: type: text influence_conversation: false ServiceRequest: type: text influence_conversation: false

+++++++++++++++++++++++++++ rule>>>>>

*   rule: User create incident form activate rule steps:

*   ** or: * intent: open_incident 
      *   *   intent: trigger_open_incident
    *   action: action_reset_slot
    *   action: create_incident_form
    *   active_loop: create_incident_form
*   rule: User create incident form submit rule condition:

# Condition that form is active.

*   ** active_loop: create_incident_form steps:

# Form is deactivated

*   ** action: create_incident_form 
      *   active_loop: null
    *   slot_was_set: * requested_slot: null
    *   action: action_create_incident ++++++++++++++++++++++++++++++++++++++ forms: create_incident_form: ignored_intents:stop required_slots: description: * type: from_text

### Command / Request

 _No response_ 

### Relevant log output

 _No response_

**Comment by sara-tagger** [comment]
Thanks for raising this issue, @sebwarnke will get back to you about it soon✨

###### Please also check out the [docs](https://rasa.com/docs/) and the [forum](https://forum.rasa.com/) in case your issue was raised there too 🤗
