### ISSUE TITLE
Add flag to disable training on GPU for TEDPolicy

### ISSUE THREAD

**Issue by melindaloubser1** [RasaHQ/rasa#10897]
### What problem are you trying to solve?

Since the bump to Tensorflow 2.6, training on TED on GPU is significantly (in one case 4X) slower than before. CPU training time is not affected to the same degree.

Because it is still advantageous to use GPU for DIETClassifier, it's desirable to disable training on GPU for TED only to save time.

### What's your suggested solution?

A parameter for TED like `use_gpu` that controls whether available GPUs are used or not.

### Examples (if relevant)

 _No response_ 

### Is anything blocking this from being implemented? (if relevant)

 _No response_ 

### Definition of Done

*   [ ] flag added

**Comment by WashingtonBispo** [comment]
Hello There. I have interest on work on this issue.

**Comment by melindaloubser1** [comment]
@WashingtonBispo Would you like to contribute a PR for this feature or do you mean you're interested in future work on it?

**Comment by WashingtonBispo** [comment]
I intent to contribute a PR. I will work on it this weekend.

**Comment by melindaloubser1** [comment]
Great, thanks! Please tag me in the PR and I'll make sure it gets reviewed

**Comment by WashingtonBispo** [comment]
Done. @melindaloubser1

**Comment by melindaloubser1** [comment]
For anyone who needs a workaround until the PR is merged, you can train NLU on GPU and core on CPU separately, by exporting `CUDA_VISIBLE_DEVICES=-1` before training core. Then you can combine the models:
```
# Default GPU NLU training
rasa train nlu --fixed-model-name nlu

# GPU excluded core training
# If this is inside a docker container possible that you'll additionally need `NVIDIA_VISIBLE_DEVICES=none`
export CUDA_VISIBLE_DEVICES="-1"
rasa train core --fixed-model-name core

# Combine NLU & Core models
cd models
mkdir nlu-model
tar xvf nlu.tar.gz -C nlu-model
mkdir core-model
tar xvf core.tar.gz -C core-model
mkdir combined
mv core-model/core combined
mv nlu-model/nlu combined
mv core-model/fingerprint.json combined
tar -C combined -cvzf combined.tar.gz .

```

**Comment by dakshvar22** [comment]
Closed by https://github.com/RasaHQ/rasa/pull/10944
