### ISSUE TITLE
Interactive mode breaking when correcting intent with entity explicitly describe in the example

### ISSUE THREAD

**Issue by EDunstonZoo** [RasaHQ/rasa#10895]
### Rasa Open Source version

3.0.0

### Rasa SDK version

 _No response_ 

### Rasa X version

 _No response_ 

### Python version

3.8

### What operating system are you using?

OSX

### What happened?

I hope this is not a duplicate... While running Interactive mode, I reached an error while correcting a bad intent classification with an entity described explicitly, i.e.` <span class="error"><span class="error">[value]</span></span>(entity_name)`.

In the relevant log output, I pasted two examples of interactive conversation flow:

1.  The one breaking, where I tried fixing the wrongly classified intent with the entity explicitly described.
2.  The one working, where I fixed the wrongly classified intent, removing the tag for the entity.

Shouldn't the interactive mode accept examples of intents with entities placed in them?

Link to toy example: [https://github.com/EDunstonZoo/namebot.git](https://github.com/EDunstonZoo/namebot.git)

### Command / Request

 _No response_ 

### Relevant log output

<pre>%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
 EXAMPLE 1:%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
 %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

Type a message and press enter (press 'Ctrl-c' to exit).
 ? Your input -> Hi 
 ? Your NLU model classified 'Hi' with intent 'greet' and there are no entities, is this correct? Yes 
 ------
 Chat History

1\. Bot You
 ────────────────────────────────────────────
 1 action_listen 
 ────────────────────────────────────────────
 2 Hi 
 intent: greet 1.00

Current slots: 
 name: Zorro the Incognito, session_started_metadata: None

------
 ? The bot wants to run 'utter_ask_name', correct? Yes 
 ------
 Chat History

1\. Bot You
 ─────────────────────────────────────────────────────
 1 action_listen 
 ─────────────────────────────────────────────────────
 2 Hi 
 intent: greet 1.00 
 ─────────────────────────────────────────────────────
 3 utter_ask_name 1.00 
 What do they call you?

Current slots: 
 name: Zorro the Incognito, session_started_metadata: None

------
 ? The bot wants to run 'action_listen', correct? Yes 
 ? Your input -> My name is Steve Mac Queen 
 ? Is the intent 'mood_unhappy' correct for 'My name is <span class="error">[Steve Mac Queen]</span>(PERSON)' and are all entities labeled correctly? No 
 ? What intent is it? 0.01 supply_name 
 ? Please mark the entities using <span class="error">[value]</span>(type) notation My name is <span class="error">[Steve Mac Queen]</span>(PERSON) 
 2022-02-15 13:43:23 ERROR rasa.server - Failed to validate the events format. For more information about the format visit the docs. Error: None is not of type 'number'

Failed validating 'type' in schema<span class="error">[0]</span><span class="error">['properties']</span><span class="error">['parse_data']</span><span class="error">['properties']</span><span class="error">['entities']</span><span class="error">['items']</span><span class="error">['properties']</span><span class="error">['confidence']</span>:

 {'type': 'number'} 

On instance<span class="error">['parse_data']</span><span class="error">['entities']</span><span class="error">[0]</span><span class="error">['confidence']</span>:
 None
 2022-02-15 13:43:23 ERROR rasa.core.training.interactive - An exception occurred while recording messages.
 Traceback (most recent call last):
 File "/Users/edunston/anaconda3/envs/rasa3/lib/python3.8/site-packages/rasa/core/training/interactive.py", line 1499, in record_messages
 await _validate_nlu(intents, endpoint, conversation_id)
 File "/Users/edunston/anaconda3/envs/rasa3/lib/python3.8/site-packages/rasa/core/training/interactive.py", line 1280, in _validate_nlu
 await _correct_wrong_nlu(corrected_nlu, events, endpoint, conversation_id)
 File "/Users/edunston/anaconda3/envs/rasa3/lib/python3.8/site-packages/rasa/core/training/interactive.py", line 1031, in _correct_wrong_nlu
 await send_event(
 File "/Users/edunston/anaconda3/envs/rasa3/lib/python3.8/site-packages/rasa/core/training/interactive.py", line 259, in send_event
 return await endpoint.request(json=evt, method="post", subpath=subpath)
 File "/Users/edunston/anaconda3/envs/rasa3/lib/python3.8/site-packages/rasa/utils/endpoints.py", line 173, in request
 raise ClientResponseError(
 rasa.utils.endpoints.ClientResponseError: 400, Bad Request, body='b'{"version":"3.0.0","status":"failure","message":"Failed to validate the events format. For more information about the format visit the docs. Error: None is not of type \'number\'
n
 nFailed validating \'type\' in schema<span class="error">[0]</span><span class="error">[\'properties\']</span><span class="error">[\'parse_data\']</span><span class="error">[\'properties\']</span><span class="error">[\'entities\']</span><span class="error">[\'items\']</span><span class="error">[\'properties\']</span><span class="error">[\'confidence\']</span>:
 n 

 {\'type\': \'number\'} 

n
 nOn instance<span class="error">[\'parse_data\']</span><span class="error">[\'entities\']</span><span class="error">[0]</span><span class="error">[\'confidence\']</span>:
 n None","reason":"BadRequest","details":{},"help":"https:\\/\\/rasa.com\\/docs\\/rasa
/pages
 /http-api","code":400}''
 2022-02-15 13:43:23 ERROR asyncio - Task exception was never retrieved
 future: 
 exception=ClientResponseError('400, Bad Request, body=\'b\'{"version":"3.0.0","status":"failure","message":"Failed to validate the events format. For more information about the format visit the docs. Error: None is not of type \\\'number\\\'\\\\n\\\\nFailed validating \\\'type\\\' in schema<span class="error">[0]</span>[\\\'properties\\\'](file:///'properties///')([file:///'properties///')[\\\'parse_data\\\'](file:///'parse_data///')[\\\'properties\\\'](file:///'properties///')[\\\'entities\\\'](file:///'entities///')[\\\'items\\\'](file:///'items///')[\\\'properties\\\'](file:///'properties///')[\\\'confidence\\\'](file:///'confidence///'):\\\\n](file:///'properties///')[\\'parse_data\\'](file:///'parse_data///')[\\'properties\\'](file:///'properties///')[\\'entities\\'](file:///'entities///')[\\'items\\'](file:///'items///')[\\'properties\\'](file:///'properties///')[\\'confidence\\'](file:///'confidence///'):\\\n) 

 {\\\'type\\\': \\\'number\\\'} 

\\\\n\\\\nOn instance[\\\'parse_data\\\'](file:///'parse_data///')([file:///'parse_data///')[\\\'entities\\\'](file:///'entities///')[0][\\\'confidence\\\'](file:///'confidence///'):\\\\n](file:///'parse_data///')[\\'entities\\'](file:///'entities///')[0][\\'confidence\\'](file:///'confidence///'):\\\n) None","reason":"BadRequest","details":{},"help":"https:\\\\/\\\\/rasa.com\\\\/docs\\\\/rasa\\\\/pages\\\\/http-api","code":400}\'\'')>
 Traceback (most recent call last):
 File "/Users/edunston/anaconda3/envs/rasa3/lib/python3.8/site-packages/sanic/signals.py", line 133, in _dispatch
 retval = await maybe_coroutine
 File "/Users/edunston/anaconda3/envs/rasa3/lib/python3.8/site-packages/sanic/app.py", line 1374, in run_delayed_task
 await prepped
 File "/Users/edunston/anaconda3/envs/rasa3/lib/python3.8/site-packages/rasa/core/training/interactive.py", line 1594, in run_interactive_io
 await record_messages(
 File "/Users/edunston/anaconda3/envs/rasa3/lib/python3.8/site-packages/rasa/core/training/interactive.py", line 1499, in record_messages
 await _validate_nlu(intents, endpoint, conversation_id)
 File "/Users/edunston/anaconda3/envs/rasa3/lib/python3.8/site-packages/rasa/core/training/interactive.py", line 1280, in _validate_nlu
 await _correct_wrong_nlu(corrected_nlu, events, endpoint, conversation_id)
 File "/Users/edunston/anaconda3/envs/rasa3/lib/python3.8/site-packages/rasa/core/training/interactive.py", line 1031, in _correct_wrong_nlu
 await send_event(
 File "/Users/edunston/anaconda3/envs/rasa3/lib/python3.8/site-packages/rasa/core/training/interactive.py", line 259, in send_event
 return await endpoint.request(json=evt, method="post", subpath=subpath)
 File "/Users/edunston/anaconda3/envs/rasa3/lib/python3.8/site-packages/rasa/utils/endpoints.py", line 173, in request
 raise ClientResponseError(
 rasa.utils.endpoints.ClientResponseError: 400, Bad Request, body='b'{"version":"3.0.0","status":"failure","message":"Failed to validate the events format. For more information about the format visit the docs. Error: None is not of type \'number\'
n
 nFailed validating \'type\' in schema<span class="error">[0]</span><span class="error">[\'properties\']</span><span class="error">[\'parse_data\']</span><span class="error">[\'properties\']</span><span class="error">[\'entities\']</span><span class="error">[\'items\']</span><span class="error">[\'properties\']</span><span class="error">[\'confidence\']</span>:
 n 

 {\'type\': \'number\'} 

n
 nOn instance<span class="error">[\'parse_data\']</span><span class="error">[\'entities\']</span><span class="error">[0]</span><span class="error">[\'confidence\']</span>:
 n None","reason":"BadRequest","details":{},"help":"https:\\/\\/rasa.com\\/docs\\/rasa
/pages
 /http-api","code":400}''

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
 EXAMPLE 2:%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
 %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

Type a message and press enter (press 'Ctrl-c' to exit).
 ? Your input -> Hi 
 ? Your NLU model classified 'Hi' with intent 'greet' and there are no entities, is this correct? Yes 
 ------
 Chat History

1\. Bot You
 ────────────────────────────────────────────
 1 action_listen 
 ────────────────────────────────────────────
 2 Hi 
 intent: greet 1.00

Current slots: 
 name: Zorro the Incognito, session_started_metadata: None

------
 ? The bot wants to run 'utter_ask_name', correct? Yes 
 ------
 Chat History

1\. Bot You
 ─────────────────────────────────────────────────────
 1 action_listen 
 ─────────────────────────────────────────────────────
 2 Hi 
 intent: greet 1.00 
 ─────────────────────────────────────────────────────
 3 utter_ask_name 1.00 
 What do they call you?

Current slots: 
 name: Zorro the Incognito, session_started_metadata: None

------
 ? The bot wants to run 'action_listen', correct? Yes 
 ? Your input -> My name is Steve Mac Queen 
 ? Is the intent 'mood_unhappy' correct for 'My name is <span class="error">[Steve Mac Queen]</span>(PERSON)' and are all entities labeled correctly? No 
 ? What intent is it? 0.01 affirm 
 ? Please mark the entities using <span class="error">[value]</span>(type) notation My name is Steve Mac Queen 
 ------
 Chat History

1\. Bot You
 ─────────────────────────────────────────────────────────────
 1 action_listen 
 ─────────────────────────────────────────────────────────────
 2 Hi 
 intent: greet 1.00 
 ─────────────────────────────────────────────────────────────
 3 utter_ask_name 1.00 
 What do they call you? 
 action_listen 
 ─────────────────────────────────────────────────────────────
 4 My name is Steve Mac Queen 
 intent: affirm 1.00

Current slots: 
 name: Zorro the Incognito, session_started_metadata: None

------
 ? The bot wants to run 'action_unlikely_intent' to indicate that the last user message was unexpected at this point in the conversation. Check o
 ut UnexpecTEDIntentPolicy ([https://rasa.com/docs/rasa/policies#unexpected-intent-policy](https://rasa.com/docs/rasa/policies#unexpected-intent-policy)([https://rasa.com/docs/rasa/policies#unexpected-intent-policy](https://rasa.com/docs/rasa/policies#unexpected-intent-policy))) to learn more. Is that correct? (Y/n)
 </pre>

**Comment by sara-tagger** [comment]
Thanks for raising this issue, @dakshvar22 will get back to you about it soon✨

###### Please also check out the [docs](https://rasa.com/docs/) and the [forum](https://forum.rasa.com/) in case your issue was raised there too 🤗

**Comment by melindaloubser1** [comment]
@EDunstonZoo thanks for your example code, that made it easy to test - it's not reproducible on `rasa==3.1.0`, can you verify that after upgrading everything is working for you and reopen this issue if there's still a problem?
