### ISSUE TITLE
rasa data validate should warn when checkpoints create loops in stories

### ISSUE THREAD

**Issue by hsm207** [RasaHQ/rasa#10925]
### What problem are you trying to solve?

Users may accidentally create circular logic in stories using checkpoints. `rasa data validate` should flag this if it occurs.

### What's your suggested solution?

`rasa data validate` throws a warning mentioning which checkpoints caused the loop

### Examples (if relevant)

For example, these stories:

 version: "2.0"

 stories:

*   story: happy path 1
     steps:
*   intent: greet
*   action: utter_greet
*   checkpoint: cp_a

*   story: happy path 2
     steps:
*   checkpoint: cp_a
*   intent: mood_great
*   action: utter_happy

*   story: sad path 1a
     steps:
*   checkpoint: cp_a
*   intent: mood_unhappy
*   action: utter_cheer_up
*   action: utter_did_that_help
*   checkpoint: cp_b

*   story: sad path 1b
     steps:
*   checkpoint: cp_b
*   intent: affirm
*   action: utter_happy
*   checkpoint: cp_a

*   story: sad path 1b
     steps:
*   checkpoint: cp_b
*   intent: deny
*   action: utter_goodbye

creates a loop as shown in this diagram:

[<span class="image-wrap" style="">![](https://user-images.githubusercontent.com/2398765/155102976-0a580a48-6f86-47c4-a4ac-fee2ab10f170.png)</span>](https://user-images.githubusercontent.com/2398765/155102976-0a580a48-6f86-47c4-a4ac-fee2ab10f170.png)

### Is anything blocking this from being implemented? (if relevant)

 _No response_ 

### Definition of Done

`rasa data validate` throws a warning mentioning which checkpoints caused the loop

**Comment by melindaloubser1** [comment]
May be related to https://github.com/RasaHQ/rasa/issues/7985

**Comment by emysdias** [comment]
hey, I would like to try this issue!

**Comment by emysdias** [comment]
he is going to help me @WashingtonBispo

**Comment by emysdias** [comment]
Whick is better to show, checkpoints or the story that is causing? @hsm207

**Comment by emysdias** [comment]
The pull request: https://github.com/RasaHQ/rasa/pull/10971
