### ISSUE TITLE
Allow custom dispatcher based on channel in utter_objects of ActionQueryKnowledgeBase

### ISSUE THREAD

**Issue by nyejon** [RasaHQ/rasa#10949]
### What problem are you trying to solve?

When using a knowledgebase, one can customize the utter_objects method of ActionQueryKnowledgeBase.

In the utter_objects method, one can customize how the objects are uttered.

It would be nice to be able to detect which channel the bot is currently using to be able to customize the output based on channel.

For example, carousel when using rasa-webchat, list when using shell.

### What's your suggested solution?

in the _query_objects method of ActionQueryKnowledgeBase pass the tracker to utter_objects

 await utils.call_potential_coroutine(
 self.utter_objects(dispatcher, object_type, objects, tracker)
 )

This would allow one to use the `input_channel = tracker.get_latest_input_channel()` in the customizable utter_objects method.

### Examples (if relevant)

 _No response_ 

### Is anything blocking this from being implemented? (if relevant)

 _No response_ 

### Definition of Done

The tracker is available in the utter_objects method of ActionQueryKnowledgeBase.

**Comment by sara-tagger** [comment]
Thanks for submitting this feature request 🚀 @rctatman will get back to you about it soon! ✨
