### ISSUE TITLE
Installation Document Having Spelling and Grammatical Errors.

### ISSUE THREAD

**Issue by Adarshsng** [RasaHQ/rasa#10954]
### Rasa Open Source version

Rasa --3.0

### Rasa SDK version

 _No response_ 

### Rasa X version

 _No response_ 

### Python version

3.8

### What operating system are you using?

Windows

### What happened?

Hello Team,

I am new to Rasa and trying to go through the documentation [link](https://rasa.com/docs/rasa/), so as to contribute in the coming future I found some spellings and grammatical errors in the documentation, which I wanted to bring forward even though I didn't find a Doc tag issue type.

At this location [link](https://rasa.com/docs/rasa/installation) I have observed multiple grammatical errors such as :

1.  It seems there is a pronoun problem here, You can explore Rasa Open Source online using the Rasa Playground even before you install **it**. [<span class="image-wrap" style="">![](https://user-images.githubusercontent.com/25716874/156029138-f9660562-1de6-4bad-b46a-a302ba4a8eeb.png)</span>](https://user-images.githubusercontent.com/25716874/156029138-f9660562-1de6-4bad-b46a-a302ba4a8eeb.png)

1.  The word "available" is misspelt [<span class="image-wrap" style="">![](https://user-images.githubusercontent.com/25716874/156029465-dd84b020-3f70-4530-ba31-67fbfdb3c35c.png)</span>](https://user-images.githubusercontent.com/25716874/156029465-dd84b020-3f70-4530-ba31-67fbfdb3c35c.png)

1.  Many sentences are missing punctuation like " , "

These issues might not be very trivial and surely must not fall into the bug report, but I wanted to bring it forward.

Do let me know if I can share a detailed PR on it.

Thanks Adarsh

### Command / Request

 _No response_ 

### Relevant log output

 _No response_

**Comment by sara-tagger** [comment]
Thanks for the issue, @mvielkind will get back to you about it soon!

###### You may find help in the [docs](https://rasa.com/docs/) and the [forum,](https://forum.rasa.com/) too 🤗

**Comment by Adarshsng** [comment]
Hey @mvielkind, any updates on this?

**Comment by m-vdb** [comment]
hey @Adarshsng 👋🏻 thanks for reporting this issue. If you're up for it, you can put up a PR to fix those issues. The doc files are versioned in [this repo under this folder](https://github.com/RasaHQ/rasa/tree/main/docs/docs). You can assign me or @mvielkind as a reviewer if you want!

**Comment by italovinicius18** [comment]
Hello, I would like to know if there has been any progress on this issue, if not, can I be responsible for resolving it?

**Comment by m-vdb** [comment]
yes do not hesitate to create a pull request targeting the `main` branch :)

**Comment by italovinicius18** [comment]
Thank you, can you or someone move this issue to "doing" column on kanban board?

**Comment by VpkPrasanna** [comment]
I guess this typo error has been fixed .

**Comment by m-vdb** [comment]
the point 1 and 3 of the issue description are still worth looking at, but the documentation has moved to this page FYI: https://rasa.com/docs/rasa/installation/installing-rasa-open-source

point 2 seems fixed now

**Comment by italovinicius18** [comment]
Hello, can @m-vdb review my PR?

**Comment by m-vdb** [comment]
done ✅ I've enabled auto-merge on your PR. Usually this keeps your branch up to date, but I'm not sure it'll work with your fork. You might need to merge `main` into your branch again, before we can merge it. Thanks again for your contribution!

**Comment by italovinicius18** [comment]
I've rebased the branch, but the workflow is awaiting approval
