### ISSUE TITLE
Telegram bot doesn't respond

### ISSUE THREAD

**Issue by BunnyNoBugs** [RasaHQ/rasa#10963]
### Rasa Open Source version

3.0.6

### Rasa SDK version

 _No response_ 

### Rasa X version

 _No response_ 

### Python version

3.8

### What operating system are you using?

Linux

### What happened?

I’ve configured Telegram connector precisely following the [instruction](https://rasa.com/docs/rasa/connectors/telegram/) in the docs, but the bot does not respond to any messages.

I've tried two different setups: with a proxy that made public a local port on my remote server and with ngrok. Plus, I've tried different ports: 8443 and 443\. Regardless of the combination, the behaviour is that the bot doesn't respond to any messages.

However, when I do `rasa run -vv`, the logs say that the connection is OK:

### Command / Request

 _No response_ 

### Relevant log output

<pre>[https://api.telegram.org:443](https://api.telegram.org:443)([https://api.telegram.org:443](https://api.telegram.org:443))"GET /bot
 /setWebhook?url=

 %2Fwebhooks%2Ftelegram%2Fwebhook HTTP/1.1" 200 64.

 </pre>

**Comment by sara-tagger** [comment]
Thanks for the issue, @melindaloubser1 will get back to you about it soon!

###### You may find help in the [docs](https://rasa.com/docs/) and the [forum,](https://forum.rasa.com/) too 🤗

**Comment by BunnyNoBugs** [comment]
@melindaloubser1, the issue still persists. Would be grateful for your help!

**Comment by melindaloubser1** [comment]
@BunnyNoBugs Can you post a more complete log from `rasa run -vv`? This will give context on what the bot is doing in the background and what would be expected as a response.

**Comment by melindaloubser1** [comment]
I just tested it with the same Rasa version, all works fine.
I see e.g. this log in `rasa run -vv` - I'm assuming the log above is from ngrok?
```
2022-03-09 10:46:19 DEBUG    urllib3.connectionpool  - https://api.telegram.org:443 "POST /bot<auth>/sendMessage?chat_id=5228192584&text=Hey%21+How+are+you%3F HTTP/1.1" 200 256
```


Note that I ngrokked port 5005, since that is the port my server is running on. Unless you specified `--port` for `rasa run`, you also need to use port 5005.
