### ISSUE TITLE
A cli tool to lint the bot's yaml files

### ISSUE THREAD

**Issue by hsm207** [RasaHQ/rasa#10967]
### What problem are you trying to solve?

Programming languages have linters to make sure people working on a project follow the coding conventions e.g. writing docstrings, naming functions, naming classes, etc

Why can't we build a cli tool to lint our yaml files to make it easy for large teams to make sure people are following the same convention when adding/editing their bot's content?

### What's your suggested solution?

A cli tool that can check:

1.  intent names follow a specified naming convention
2.  possibly not using entities to disambiguate intent e.g. problem_tv, problem_internet, problem_phone
3.  stories with very long names (use metadata to store additional info)
4.  loops in training stories
5.  stories consisting of only single turns (consider using rules)
6.  Warn about utterances that are over a configurable length (sentences longer than 25 words aren't [accessible](https://insidegovuk.blog.gov.uk/2014/08/04/sentence-length-why-25-words-is-our-limit/))

### Examples (if relevant)

 _No response_ 

### Is anything blocking this from being implemented? (if relevant)

 _No response_ 

### Definition of Done

a cli tool that can help people follow conventions when writing content for their bot

**Comment by hsm207** [comment]
@rgstephens thanks for the suggestion. I've added it to the issue.

I've found the following open source yaml linters that could be used as a starting point:
* [yamllint](https://github.com/adrienverge/yamllint)
* [kube-linter](https://github.com/stackrox/kube-linter)

**Comment by SamuelNoB** [comment]
Hi, I would like to contribute with this feature, is this open for the community?
We should add the cli yaml linter feature to the docs as well. The docs may contain a quick description, a list of capabilites and some basic examples of how the linter works
