### ISSUE TITLE
`rasa visualize` generates invalid javascript

### ISSUE THREAD

**Issue by rgstephens** [RasaHQ/rasa#10979]
### Rasa Open Source version

3.0.7

### Rasa SDK version

 _No response_ 

### Rasa X version

 _No response_ 

### Python version

3.8

### What operating system are you using?

OSX

### What happened?

When loading the `graph.html` in the browser, the browser shows a blank white page and the console produces the following error:

TypeError: undefined is not an object (evaluating 'document.getElementById('graph-style').sheet.cssRules')

The following code in the generated `graph.html` file is invalid.

<pre> cssRules = document.getElementById('graph-style').sheet.cssRules;
 cssRules<span class="error">[3]</span>.style.opacity = 1;
 cssRules<span class="error">[4]</span>.style.opacity = 1;</pre>

As a workaround, replace the above lines with:

<pre> cssRules = document.getElementById('graph-style');
 cssRules.style.opacity = 1;</pre>

### Command / Request

 _No response_ 

### Relevant log output

 _No response_

**Comment by itallogravina** [comment]
I would like to offer to make the change

**Comment by itallogravina** [comment]
> ### Versão de código aberto Rasa
> 3.0.7
> 
> ### Versão do SDK Rasa
> _Sem resposta_
> 
> ### Versão Rasa X
> _Sem resposta_
> 
> ### Versão do Python
> 3.8
> 
> ### Qual sistema operacional você está usando?
> OSX
> 
> ### O que aconteceu?
> Ao carregar o `graph.html`no navegador, o navegador mostra uma página branca em branco e o console o seguinte erro:
> 
> ```
> TypeError: undefined is not an object (evaluating 'document.getElementById('graph-style').sheet.cssRules')
> ```
> 
> O código a seguir no `graph.html`arquivo gerado é inválido.
> 
> ```js
>     cssRules  =  documento . getElementById ( 'graph-style' ) . folha . cssRegras ; 
>     cssRules [ 3 ] . estilo . opacidade  =  1 ; 
>     cssRules [ 4 ] . estilo . opacidade  =  1 ;
> ```
> 
> Como solução alternativa, substitui as linhas acima por:
> 
> ```js
>     cssRules  =  documento . getElementById ( 'gráfico-estilo' ) ; 
>     cssRules . estilo . opacidade  =  1 ;
> ```
> 
> ### Comando / Solicitação
> _Sem resposta_
> 
> ### Saída de registro relevante
> _Sem resposta_

This solution, I believe, is not feasible.
![image](https://user-images.githubusercontent.com/51856522/157567375-2bbf4d2a-5119-4382-be78-4d559fe07734.png)
