### ISSUE TITLE
Wrong indentation of YAML data written by rasa x 

### ISSUE THREAD

**Issue by raoulvm** [RasaHQ/rasa#11013]
### Rasa Open Source version

2.8.24

### Rasa SDK version

2.8.4

### Rasa X version

1.0.1

### Python version

3.8

### What operating system are you using?

Linux, OSX, Windows, Self hosted Cloud (openshift)

### What happened?

When Rasa X writes YAML, its indentations for list items is wrong:

```YAML
key: 
- entry1
- entry2
```
it should be
```YAML
key:
  - entry1
  - entry2
```
The important difference, which can be hardly seen here, are the two extra spaces required for list entries. In the [Rasa Forum the formatter immediately formats the wrong format red](https://forum.rasa.com/t/wrong-indentation-of-yaml-data-written-by-rasa-x/52060/3) though.

That seems to be a recent (like 5 yers ago) issue with ruamel.yaml:
https://stackoverflow.com/questions/44388701/how-get-the-sequences-properly-indented-with-ruamel-yaml

### Command / Request

```shell
Any change in Rasa X that will write back files, no matter if used locally or in Rasa X Enterprise to create a new git branch.
```

**Comment by ceromero05** [comment]
testing comment section to remove <p>

**Comment by alexweidauer** [comment]
Thank you for raising this issue about Rasa X. We decided to stop supporting the Community Edition (free version) of ‘Rasa X’ (see more info here: https://rasa.com/blog/rasa-x-community-edition-changes/). That’s why we’ve closed your issue. We suggest that Rasa Enterprise customers raise the issue with our customer support team if they haven’t done so already.

**Comment by raoulvm** [comment]
Thanks @alexweidauer and @amn41 this has been stale in Zendesk for 24 days now.

**Comment by amn41** [comment]
thanks @raoulvm  - will respond there!
