### ISSUE TITLE
Missing Rasa X API endpoints in documentation

### ISSUE THREAD

**Issue by FlorianFormentini** [RasaHQ/rasa#11044]
### Rasa Open Source version

2.8.15

### Rasa X version

1.0.1 (installed with docker-compose)

### Python version

3.8

### What operating system are you using?

Linux

### What happened?

I'm using the Rasa X API to get statistics on my chatbot usage and make some charts. But while running my script today, I got errors and found that the HTTP request to get all NLU samples still returns a 200 status code but no data.  
My script has not changed since the last run that worked and the versions of rasa and rasa X have not been updated recently.

```python
url = HOST + "/api/projects/default/training_examples"
r = requests.get(url, headers={"Authorization": f"Bearer {access_token}"})
r.raise_for_status()
print(r.status_code, r.json())
```
-> ```200 []```

When I checked [the documentation](https://rasa.com/docs/rasa-x/pages/http-api) I saw that many endpoints I use are no longer listed but still work in my script and nothing is indicated in the changelogs, for examples :
- `/api/conversations` -> GET: retrieve all conversations
- `/api/conversations/<conv_id>` -> DELETE: delete a conversation
- `/api/conversations/<conv_id>/messages` -> GET: return all messages of a conversation
- `/api/projects/default/intents` -> GET: return all chatbot intents
- `/api/conversations/<conv_id>/data-tags` -> GET request to retrieve tags (there is only the POST request to set tags listed in the doc for this endpoint but the GET request still works)
- and several others ...

But for me, `/api/projects/default/training_examples` is the only one that does not return what it should despite its 200 status code.

Have these endpoints become obsolete and the documentation is not up to date?

**Comment by sara-tagger** [comment]
Thanks for raising this issue, @rctatman will get back to you about it soon✨

###### Please also check out the [docs](https://rasa.com/docs/) and the [forum](https://forum.rasa.com/) in case your issue was raised there too 🤗

**Comment by alexweidauer** [comment]
Thank you for raising this issue about Rasa X. We decided to stop supporting the Community Edition (free version) of ‘Rasa X’ (see more info here: https://rasa.com/blog/rasa-x-community-edition-changes/). That’s why we’ve closed your issue. We suggest that Rasa Enterprise customers raise the issue with our customer support team if they haven’t done so already.
