### ISSUE TITLE
Compatibility Matrix is outdated 

### ISSUE THREAD

**Issue by jusce17** [RasaHQ/rasa#11047]
### What problem are you trying to solve?

I am currently installing rasa 3.1.0, however the Compatibility Matrix  on the [website](https://rasa.com/docs/rasa-x/changelog/compatibility-matrix/) seems to be  outdated, has it describe rasa 2.8.x as the highest version. I am in not condition to advise the company on how to install rasa 3.0.x as I am not sure about the compatibility erros that may occur.

**Comment by sara-tagger** [comment]
Thanks for submitting this feature request 🚀 @amn41 will get back to you about it soon! ✨

**Comment by virtualroot** [comment]
Thanks @jusce17 for your report. The compatibility matrix was recently updated with 3.1.
