### ISSUE TITLE
RASA interactive not appending story at the right indentation level

### ISSUE THREAD

**Issue by gitgithan** [RasaHQ/rasa#11058]
### Rasa Open Source version

2.8.25

### Rasa SDK version

2.8.4

### Python version

3.8

### What operating system are you using?

OSX

### What happened?

![image](https://user-images.githubusercontent.com/29853829/161684139-26bf0f52-bd95-462b-bc54-0c4306936c85.png)
After going going through a dialogue session in `rasa interactive` and ending with `Export & Quit`, the story is appended at the outermost level instead of 1 level in under `stories` key like the others, so I have to manually indent it to the right place.

Is it possible to automatically indent at the right level?

Are story names just labels for the developer and not being used by RASA in any way? The autogenerated names from `rasa interactive` are all called `interactive_story_1` and they don't seem to break anything.

**Comment by sara-tagger** [comment]
Thanks for raising this issue, @JustinaPetr will get back to you about it soon✨

###### Please also check out the [docs](https://rasa.com/docs/) and the [forum](https://forum.rasa.com/) in case your issue was raised there too 🤗
