### ISSUE TITLE
Deploy:How to deploy NLU and Policies on different GPUs?

### ISSUE THREAD

**Issue by gongshaojie12** [RasaHQ/rasa#11051]
### Rasa Open Source version

3.1.0

### Python version

3.9

### What operating system are you using?

Linux

### What happened?

After the rasa model is trained, the NLU model and the Policies model are in one tar.gz. How to deploy the NLU model and the Policies model on different GPUs? For example, the NLU model is deployed on GPU0, and the Policies model is deployed on GPU1. thanks

**Comment by sara-tagger** [comment]
Thanks for raising this issue, @losterloh will get back to you about it soon✨

###### Please also check out the [docs](https://rasa.com/docs/) and the [forum](https://forum.rasa.com/) in case your issue was raised there too 🤗
