### ISSUE TITLE
Training:How to use multiple GPUs for distributed training?

### ISSUE THREAD

**Issue by gongshaojie12** [RasaHQ/rasa#11050]
### Rasa Open Source version

3.1.0

### Python version

3.9

### What operating system are you using?

Linux

### What happened?

Now I have multiple GPUs, I want to use Rasa to do distributed training on multiple GPUs, I set the environment variable **TF_GPU_MEMORY_ALLOC="0:5120,1:5120"**, but the model is only trained on GPU0. GPU1 is just blocked and does not participate in the actual training. How can I perform distributed training on multiple GPUs? Thanks!

**Comment by sara-tagger** [comment]
Thanks for raising this issue, @b-quachtran will get back to you about it soon✨

###### Please also check out the [docs](https://rasa.com/docs/) and the [forum](https://forum.rasa.com/) in case your issue was raised there too 🤗

**Comment by m-vdb** [comment]
hey @gongshaojie12 , for all questions relating to how to use rasa, please go to the forum at https://forum.rasa.com/
