### ISSUE TITLE
types-rasa (typing stubs)

### ISSUE THREAD

**Issue by adamwojt** [RasaHQ/rasa#11057]
### What problem are you trying to solve?

use type-hinting and mypy linting. currently when setting up linting for mypy whole rasa package with all dependencies has to be installed in order to get types (takes long time in CI/CD pipelines).

### What's your suggested solution?

create seperate package for typing only for rasa

### Examples (if relevant)

[https://peps.python.org/pep-0561/](https://peps.python.org/pep-0561/) [https://github.com/python/typeshed/tree/master/stubs](https://github.com/python/typeshed/tree/master/stubs) [https://pypi.org/project/pandas-stubs/](https://pypi.org/project/pandas-stubs/) [https://pypi.org/project/types-click/](https://pypi.org/project/types-click/)

### Is anything blocking this from being implemented? (if relevant)

 _No response_ 

### Definition of Done

 _No response_

**Comment by sara-tagger** [comment]
Thanks for submitting this feature request 🚀 @melindaloubser1 will get back to you about it soon! ✨

**Comment by m-vdb** [comment]
@adamwojt thanks for your request. This is a cool idea but at this stage this would require a lot more changes in the ways we work internally at Rasa, so I don't think this is something that will happen in the short-term, realistically 😬 

You mentioned that this puts some burden on your CI, may I ask how much of a pain is it? In our own CI on GitHub the installation takes about ~5min including the required os libraries.

**Comment by adamwojt** [comment]
> @adamwojt thanks for your request. This is a cool idea but at this stage this would require a lot more changes in the ways we work internally at Rasa, so I don't think this is something that will happen in the short-term, realistically grimacing
> 
> You mentioned that this puts some burden on your CI, may I ask how much of a pain is it? In our own CI on GitHub the installation takes about ~5min including the required os libraries.

Yeah this is not high priority. I would say it's nice-to-have. It's not that much of pain :)
