### ISSUE TITLE
Comments that don't help much in rasa

### ISSUE THREAD

**Issue by emysdias** [RasaHQ/rasa#11062]
### What problem are you trying to solve?

In the code there are several comments that just changing the name of the function or just deleting it would help a lot to reduce the code of the pages and make the code cleaner.

### What's your suggested solution?

Deleting some comments, changing misspelled words, changing function names

### Examples (if relevant)

In file rasa/shared/core/constants.py

[<span class="image-wrap" style="">![](https://user-images.githubusercontent.com/52640974/161877930-389951ae-bf05-429a-8197-1eb32eed1e37.png)</span>](https://user-images.githubusercontent.com/52640974/161877930-389951ae-bf05-429a-8197-1eb32eed1e37.png) this function 'def is_predefined_type' the name says a lot, so I believe the comment is not so necessary. The word 'if' it's spelled wrong

In file rasa/shared/core/conversation.py [<span class="image-wrap" style="">![](https://user-images.githubusercontent.com/52640974/161878154-2c9f20b5-9693-4779-b874-71179e77b6f7.png)</span>](https://user-images.githubusercontent.com/52640974/161878154-2c9f20b5-9693-4779-b874-71179e77b6f7.png)

Maybe changing the function name would be interesting to 'create_dialogue_from_parameters' .

### Is anything blocking this from being implemented? (if relevant)

 _No response_ 

### Definition of Done

 _No response_

**Comment by emysdias** [comment]
I'm going to make some changes

**Comment by sara-tagger** [comment]
Thanks for submitting this feature request 🚀 @amn41 will get back to you about it soon! ✨

**Comment by tmbo** [comment]
Hey @emysdias,

thanks for the suggestions, overall code improvements / style improvements are always very much welcome :)  

For the specific examples, I am not sure if there is a lot to improve though:

@emysdias "iff" isn't misspelled, it means ["if and only if"](https://en.wikipedia.org/wiki/If_and_only_if).

> Maybe changing the function name would be interesting to 'create_dialogue_from_parameters'

If you look at the usage, it is going to be something like `Dialogue.from_parameters(...)`, adding another `dialogue` in there will make it harder to read.

Comments are also a requirement, in general they are quite helpful and yes in some places they aren't adding a lot. But we do have automated testing to ensure that there are comments everywhere.

**Comment by emysdias** [comment]
> Hey @emysdias,
> 
> thanks for the suggestions, overall code improvements / style improvements are always very much welcome :)
> 
> For the specific examples, I am not sure if there is a lot to improve though:
> 
> @emysdias "iff" isn't misspelled, it means ["if and only if"](https://en.wikipedia.org/wiki/If_and_only_if).
> 
> > Maybe changing the function name would be interesting to 'create_dialogue_from_parameters'
> 
> If you look at the usage, it is going to be something like `Dialogue.from_parameters(...)`, adding another `dialogue` in there will make it harder to read.
> 
> Comments are also a requirement, in general they are quite helpful and yes in some places they aren't adding a lot. But we do have automated testing to ensure that there are comments everywhere.

ok thanks, I didn't know. What do you suggest then?

**Comment by antoniotoineto** [comment]
Is this issue still available? Im interested in it. 👍
