### ISSUE TITLE
I can plot a learning curve for rasa test nlu providing only one config file

### ISSUE THREAD

**Issue by sebwarnke** [RasaHQ/rasa#11069]
### What problem are you trying to solve?

I found the below command in the [docs](https://rasa.com/docs/rasa/testing-your-assistant/#comparing-nlu-pipelines).
```
 rasa test nlu --nlu data/nlu.yml
   --config config.yml config2.yml
   --runs 4 --percentages 0 25 50 70 90
```
This creates a plot of the learning curves for each of the provided configuration files, see below.

[<span class="image-wrap" style="">![](https://user-images.githubusercontent.com/26740468/162716441-5f0cea14-d4ae-4fe6-89d3-5187801b4b80.png)</span>](https://user-images.githubusercontent.com/26740468/162716441-5f0cea14-d4ae-4fe6-89d3-5187801b4b80.png)

However, when i provide one config file, only, Rasa does not create the plot.

Please add the capability to create the plot when I provide only one config file.

### What's your suggested solution?

The command could look like this:
```
 rasa test nlu --nlu data/nlu.yml
   --config config.yml
   --runs 4 --percentages 0 25 50 70 90
```
### Examples (if relevant)

 _No response_ 

### Is anything blocking this from being implemented? (if relevant)

 _No response_ 

### Definition of Done

 _No response_

**Comment by soerenetler** [comment]
This sounds like a simple issue to solve and it would also come in handy for me.
I would offer to work on this and commit a PR if the Rasa team thinks this would be a good feature.
