### ISSUE TITLE
Incorrect variable assignment in Rasa X simple install script

### ISSUE THREAD

**Issue by ari-kohan** [RasaHQ/rasa#11065]
### Rasa Open Source version

2.8.11

### Rasa X version

0.42.6

### Python version

3.8

### What operating system are you using?

Cloud (AWS / GCP / AZURE)

### What happened?

I have encountered a bug in the rasa X simple install script, line 269:

"--set global.redis.password=${RABBITMQ_PASSWORD}"
﻿﻿"--set rabbitmq.rabbitmq.password=${REDIS_PASSWORD}"

### Command / Request

```shell
curl -s get-rasa-x.rasa.com | sudo bash
```

**Comment by sara-tagger** [comment]
Thanks for the issue, @amn41 will get back to you about it soon!

###### You may find help in the [docs](https://rasa.com/docs/) and the [forum,](https://forum.rasa.com/) too 🤗

**Comment by alexweidauer** [comment]
Thank you for raising this issue about Rasa X. We decided to stop supporting the Community Edition (free version) of ‘Rasa X’ (see more info here: https://rasa.com/blog/rasa-x-community-edition-changes/). That’s why we’ve closed your issue. We suggest that Rasa Enterprise customers raise the issue with our customer support team if they haven’t done so already.
