### ISSUE TITLE
All extract_<slot> functions get called in each loop iteration

### ISSUE THREAD

**Issue by NoxDv** [RasaHQ/rasa#11067]
### Rasa Open Source version

3.0.9

### Rasa SDK version

3.0.6

### Python version

3.8

### What operating system are you using?

Windows

### What happened?

Hi,

I tried to implement a form with multiple slots that use custom mappings so that I can extract all the entities by myself. 

When the form loop starts Rasa correctly detects that the first required slot has to be filled and I get promoted to enter the first sentence/word or whatever. After that, on each loop iteration all extract_<slot> functions get called although only the extract_<first_slot_that_has_to_be_filled> function should be called on the first iteration.

Domain
```yaml
actions:
  - validate_test_form

intents:
  - request_form

responses:
  utter_ask_one:
    - text: "give one"
  utter_ask_two:
    - text: "give two"
  utter_ask_three:
    - text: "give three"

slots:
  one:
    type: text
    influence_conversation: false
    mappings:
      - type: custom
        conditions:
          - active_loop: test_form
            requested_slot: one

  two:
    type: text
    influence_conversation: false
    mappings:
      - type: custom
        conditions:
          - active_loop: test_form
            requested_slot: two 

  three:
    type: text
    influence_conversation: false
    mappings:
      - type: custom
        conditions:
          - active_loop: test_form
            requested_slot: three 

forms:
  test_form:
    required_slots:
      - one
      - two
      - three
      

session_config:
  session_expiration_time: 60
  carry_over_slots_to_new_session: true
```

Rules:
```yaml
rules:
  - rule: Activate form
    steps:
      - intent: request_form
      - action: test_form
      - active_loop: test_form
      - slot_was_set:
          - requested_slot: one
          - requested_slot: two
          - requested_slot: three
```

Actions
```python
from typing import Any, Text, Dict, List
from rasa_sdk import Action, Tracker
from rasa_sdk.events import SlotSet, SessionStarted, ActionExecuted, EventType
from rasa_sdk import Tracker, FormValidationAction
from rasa_sdk.executor import CollectingDispatcher


class ValidateCustomSlotMappings(FormValidationAction):
    def name(self) -> Text:
        return "validate_test_form"

    async def extract_one(self, dispatcher: CollectingDispatcher, tracker: Tracker, domain: Dict) -> Dict[Text, Any]:
        print("extract one")
        text_of_last_user_message = tracker.latest_message.get("text")
        return {"one": text_of_last_user_message}

    async def extract_two(self, dispatcher: CollectingDispatcher, tracker: Tracker, domain: Dict) -> Dict[Text, Any]:
        print("extract two")
        text_of_last_user_message = tracker.latest_message.get("text")
        return {"two": text_of_last_user_message}

    async def extract_three(self, dispatcher: CollectingDispatcher, tracker: Tracker, domain: Dict) -> Dict[Text, Any]:
        print("extract three")
        text_of_last_user_message = tracker.latest_message.get("text")
        return {"three": text_of_last_user_message}
```

**Comment by sara-tagger** [comment]
Thanks for raising this issue, @losterloh will get back to you about it soon✨

###### Please also check out the [docs](https://rasa.com/docs/) and the [forum](https://forum.rasa.com/) in case your issue was raised there too 🤗

**Comment by kassm404** [comment]
Hi, I think I have the same issue. Did you manage to solve it?
Here's the issue I raised on the Rasa forum:
[](https://forum.rasa.com/t/custom-slot-extraction-and-validation-fails-using-custom-actions/52858?u=kassem404)

**Comment by NoxDv** [comment]
> Hi, I think I have the same issue. Did you manage to solve it? Here's the issue I raised on the Rasa forum: https://forum.rasa.com/t/custom-slot-extraction-and-validation-fails-using-custom-actions/52858?u=kassem404

I got it working with a simple workaround. In each extract function I implemented a conditional statement: `if tracker.slots["requested_slot"] == "one"`

**Comment by ancalita** [comment]
@NoxDv This is actually not a bug, but how the `rasa-sdk` was designed to handle custom extract functions, it loops through all the form `required_slots` (see both in `2.8.x` [branch ](https://github.com/RasaHQ/rasa-sdk/blob/2.8.x/rasa_sdk/forms.py#L738)as well as currently in `3.x` / `main` [branch](https://github.com/RasaHQ/rasa-sdk/blob/main/rasa_sdk/forms.py#L118) of the rasa-sdk).

If you want to suggest an enhancement of the current implementation, please open a new ticket in the `rasa-sdk` repo.
