### ISSUE TITLE
Inconsistency between total number of entity supports in report.json and test data

### ISSUE THREAD

**Issue by dhruvbhimani-2512** [RasaHQ/rasa#11068]
### Rasa Open Source version

2.6.0

### Rasa SDK version

2.7.0

### Python version

3.7

### What operating system are you using?

Linux

### What happened?

I am comparing two NLU pipelines using `rasa test` command. When I evaluate final report for entity classification, total supports present in my testing data `test.md` and in the entity report do not match. I am always getting ~1 to 3 additional supports than test data in the report.

**Comment by sara-tagger** [comment]
Thanks for raising this issue, @rctatman will get back to you about it soon✨

###### Please also check out the [docs](https://rasa.com/docs/) and the [forum](https://forum.rasa.com/) in case your issue was raised there too 🤗

**Comment by ancalita** [comment]
@dhruvbhimani-2512 The last minor we currently support in the `2.x` series is `2.8.x`. Could you please try again with the latest version and confirm if you're running in the same issue? If so please provide your training data files via a public repo that I can use to reproduce this issue. Also please confirm the full `rasa test` command with all the arguments.
