### ISSUE TITLE
Remove comments from code that does not agregaten 

### ISSUE THREAD

**Issue by WashingtonBispo** [RasaHQ/rasa#11063]
### What problem are you trying to solve?

Certain files have comments that doesn't explain well or is redudant.

### What's your suggested solution?

Remove this type of comments.

### Examples (if relevant)

[<span class="image-wrap" style="">![](https://user-images.githubusercontent.com/43673797/162058939-b993c99a-9f24-461b-b6ee-7a1bd384924e.png)</span>](https://user-images.githubusercontent.com/43673797/162058939-b993c99a-9f24-461b-b6ee-7a1bd384924e.png)

### Is anything blocking this from being implemented? (if relevant)

 _No response_ 

### Definition of Done

 _No response_

**Comment by sara-tagger** [comment]
Thanks for submitting this feature request 🚀 @losterloh will get back to you about it soon! ✨

**Comment by vitordiniz25** [comment]
Hello, I would like to contribute to this issue.
