### ISSUE TITLE
Enable user site-packages in docker images 

### ISSUE THREAD

**Issue by Kamaradeivanov** [RasaHQ/rasa#11073]
### What problem are you trying to solve?

Enable user site-packages to be able to use --user parameter with official images.

### What's your suggested solution?

Give the virtual environment access to the system site-packages dir

### Examples (if relevant)

In your dockerfiles, do

`RUN python -m venv /opt/venv --system-site-packages && \`

instead of 

`RUN python -m venv /opt/venv && \`

**Comment by sara-tagger** [comment]
Thanks for submitting this feature request 🚀 @joejuzl will get back to you about it soon! ✨
