### ISSUE TITLE
Rasa duckling image

### ISSUE THREAD

**Issue by arotena** [RasaHQ/rasa#11092]
### What problem are you trying to solve?

I am using the rasa/duckling and we have detected 4 high vulnerabilities in the image. I have seen that the images was updated 7 months ago. Do you have any spected date to patch this vulnerabilities? [https://hub.docker.com/r/rasa/duckling](url)

`✗ High severity vulnerability found in zlib/zlib1g
  Description: Out-of-bounds Write
  Info: https://snyk.io/vuln/SNYK-DEBIAN10-ZLIB-2433934
  Introduced through: meta-common-packages@meta
  From: meta-common-packages@meta > zlib/zlib1g@1:1.2.11.dfsg-1
  Fixed in: 1:1.2.11.dfsg-1+deb10u1

✗ High severity vulnerability found in openssl/libssl1.1
  Description: Loop with Unreachable Exit Condition ('Infinite Loop')
  Info: https://snyk.io/vuln/SNYK-DEBIAN10-OPENSSL-2426310
  Introduced through: openssl/libssl-dev@1.1.1d-0+deb10u7
  From: openssl/libssl-dev@1.1.1d-0+deb10u7 > openssl/libssl1.1@1.1.1d-0+deb10u7
  From: openssl/libssl-dev@1.1.1d-0+deb10u7
  Fixed in: 1.1.1d-0+deb10u8

✗ High severity vulnerability found in gmp/libgmp10
  Description: Integer Overflow or Wraparound
  Info: https://snyk.io/vuln/SNYK-DEBIAN10-GMP-1920939
  Introduced through: gmp/libgmp10@2:6.1.2+dfsg-4, apt@1.8.2.3
  From: gmp/libgmp10@2:6.1.2+dfsg-4
  From: apt@1.8.2.3 > gnutls28/libgnutls30@3.6.7-4+deb10u7 > gmp/libgmp10@2:6.1.2+dfsg-4
  From: apt@1.8.2.3 > gnutls28/libgnutls30@3.6.7-4+deb10u7 > nettle/libhogweed4@3.4.1-1+deb10u1 > gmp/libgmp10@2:6.1.2+dfsg-4
  Fixed in: 2:6.1.2+dfsg-4+deb10u1

✗ High severity vulnerability found in gcc-8/libstdc++6
  Description: Information Exposure
  Info: https://snyk.io/vuln/SNYK-DEBIAN10-GCC8-347558
  Introduced through: gcc-8/libstdc++6@8.3.0-6, apt@1.8.2.3, meta-common-packages@meta
  From: gcc-8/libstdc++6@8.3.0-6
  From: apt@1.8.2.3 > gcc-8/libstdc++6@8.3.0-6
  From: apt@1.8.2.3 > apt/libapt-pkg5.0@1.8.2.3 > gcc-8/libstdc++6@8.3.0-6`

### What's your suggested solution?

Update the image

**Comment by sara-tagger** [comment]
Thanks for submitting this feature request 🚀 @ancalita will get back to you about it soon! ✨

**Comment by virtualroot** [comment]
A new duckling build is on its way. I'll come back with more information once that is done.

**Comment by virtualroot** [comment]
Fresh from the oven 👨‍🍳 🍪 

`docker pull rasa/duckling:0.2.0.2`

---

We plan to set up a workflow that automatically rebuilds Docker images when there is a system vulnerability.
We want to implement it in [duckling](https://github.com/rasahq/duckling/), Rasa, Rasa X, etc.

For the time being, we do it on request basis.
