### ISSUE TITLE
Cannot run Rasa shell server and rasa action server simultaneously. 

### ISSUE THREAD

**Issue by ChetanKhanna767** [RasaHQ/rasa#11106]
### Rasa Open Source version

3.1.0

### Rasa SDK version

3.1.1

### Rasa X version

None

### Python version

3.9

### What operating system are you using?

OSX

### What happened?

Basically I am able run only one server(action or shell) at a time. So how can I run custom actions

This the error I get when I try to run them.

`OSError: [Errno 48] error while attempting to bind on address ('0.0.0.0', 5005): address already in use
`
Command used for rasa server :
`rasa shell
`
Command used for rasa action :
`rasa run actions`

### Command / Request

```shell
rasa shell
```

### Relevant log output

```shell
OSError: [Errno 48] error while attempting to bind on address ('0.0.0.0', 5005): address already in use
```

**Comment by sara-tagger** [comment]
Thanks for raising this issue, @hsm207 will get back to you about it soon✨

###### Please also check out the [docs](https://rasa.com/docs/) and the [forum](https://forum.rasa.com/) in case your issue was raised there too 🤗

**Comment by hsm207** [comment]
I am not able to reproduce this issue.

`rasa shell` uses port 5005.

`rasa run actions` uses port 5055.

So, you can run both servers at the same time.

It is likely that you have another `rasa shell` already running. You can check with `pgrep rasa -a`.

**Comment by ChetanKhanna767** [comment]
I was using python 3.9 version, that's why I was facing this error most probably. When I switched to python 3.8. This is issue was resloved
