### ISSUE TITLE
Not able to update min_gram of CountVectorsFeaturizer

### ISSUE THREAD

**Issue by Asma-droid** [RasaHQ/rasa#11115]
### Rasa Open Source version

3

### Python version

3.8

### What operating system are you using?

Linux

### What happened?

Error when set min_ngram to a value greater than 1  for analyzer: "word"

I have obtained error running graph component for node  CountVectorsFeaturizer

**Comment by sara-tagger** [comment]
Thanks for the issue, @losterloh will get back to you about it soon!

###### You may find help in the [docs](https://rasa.com/docs/) and the [forum,](https://forum.rasa.com/) too 🤗

**Comment by Asma-droid** [comment]
@sara-tagger Hello Sarah and @losterloh  any help please!
