### ISSUE TITLE
Google Hangouts Channel allow to extract sender email

### ISSUE THREAD

**Issue by ribeiropdiogo** [RasaHQ/rasa#11111]
### What problem are you trying to solve?

The Google Hangouts/Google Chat Channel `_extract_sender` method only allows to extract the user's display name. In some cases it may be necessary to extract the user's email instead.

### What's your suggested solution?

An interesting idea to solve this problem would be to allow the specification of the field to be returned(display name or email) in the credentials file.

### Definition of Done

This feature is done when it becomes possible to specify in the credentials file the field that the `_extract_sender` method should return.

**Comment by sara-tagger** [comment]
Thanks for submitting this feature request 🚀 @kedz will get back to you about it soon! ✨
