### ISSUE TITLE
Inputs to NLU not flexible in a custom graph recipe

### ISSUE THREAD

**Issue by dakshvar22** [RasaHQ/rasa#11132]
### Rasa Open Source version

3.1

### Python version

3.8

### What operating system are you using?

OSX

### What happened?

I created a custom graph recipe since I wanted to pass the tracker to a custom NLU component. Writing the graph recipe was easy because you can add `tracker: __tracker__` to the `needs` section of the component's node definition. However, it turns out that rasa open source [does not](https://github.com/RasaHQ/rasa/compare/main...fed_dev_prototype#diff-3df24afb24f79ba33cbfdd550a9efb012491f66d306ef5480d60e2aff5a3155bL660) dynamically figure out the inputs to be passed to the NLU components during inference. Only messages can be passed as input and this is hardcoded.

If you would like to replicate the problem, check out `fed-dev-prototype` branch of `financial-demo` repo and run training + inference using `custom_config.yml`. The inference will fail to run.

A [hacky fix](https://github.com/RasaHQ/rasa/compare/main...fed_dev_prototype#diff-3df24afb24f79ba33cbfdd550a9efb012491f66d306ef5480d60e2aff5a3155bL660) for this is implemented on `fed-dev-prototype` branch of rasa oss.

(Adding the `bug` label since it seems from the docs that custom graph recipes are supported and I would expect this to behaviour to be implemented naturally since the docs don't specify otherwise. Feel free to change the label if you all think otherwise 🙂 )

**Comment by Maxinho96** [comment]
This would be nice, I also need to have at least the sender_id from a NLU component to handle different entity extraction based on the user. It would solve #10717

**Comment by Maxinho96** [comment]
Hello @dakshvar22, could you please elaborate more how is it possible to define a custom recipe that gets the tracker? There are many methods with the "needs" key and I don't really get what is the correct one.
