### ISSUE TITLE
Buttons + Text + Image in rasa shell

### ISSUE THREAD

**Issue by itsjhonny** [RasaHQ/rasa#11144]
h3\.   What happened?

Hi guys!

I’m using rasa shell to make some test and I think found something wrong when to use Buttons with image and text

    responses:
      utter_greet:
      - image: https://i.imgur.com/nGF1K8f.jpg
        text: 'Here is something to cheer that will cheer you up...'
        buttons:
          - title: "👋"
            payload: "hi"

but Rasa shell not showing buttons [!https://user-images.githubusercontent.com/48738642/170065286-6980ed6e-b14b-4e84-9bc3-c2ba53b93972.png!| https://user-images.githubusercontent.com/48738642/170065286-6980ed6e-b14b-4e84-9bc3-c2ba53b93972.png]

Rasa widget working fine. This problem just happen in rasa shell I’m not test in rasa X

I’m missing something or this not working in shell?

[Rasa forum community thread| https://forum.rasa.com/t/buttons-text-image/53351]

h3\.   Relevant log output

<pre>Rasa Version      :         3.1.0
Minimum Compatible Version: 3.0.0
Rasa SDK Version  :         3.1.0
Rasa X Version    :         None
Python Version    :         3.8.12
Operating System  :         macOS-12.3.1-arm64-arm-64bit</pre>

**Comment by sanchariGr** [comment]
Hi @itsjhonny, can you give some more details, for instance when you say rasa widget working fine what do you see there as opposed to the screenshot attached here?

**Comment by rasabot-exalate** [comment]
Sanchari Ghosh commented: Need more clarity about the error, added a comment [here|https://github.com/RasaHQ/rasa/issues/11144#issuecomment-1150030261].

**Comment by melindaloubser1** [comment]
Closing as non-reproducible on `rasa==3.1.1` - this is the response I see in `rasa shell`, given the same response format posted in the description:
```
Your input ->  /greet                                                                                                                               
Buttons:
1: 👋 (hi)
Here is something to cheer that will cheer you up...
Image: https://i.imgur.com/nGF1K8f.jpg
```
