### ISSUE TITLE
rasa.core.policies.two_stage_fallback imported but doesn't exist

### ISSUE THREAD

**Issue by ozgurdogan646** [RasaHQ/rasa#11182]
### Rasa Open Source version

3.1.0

### Python version

3.8

### What operating system are you using?

Windows

### What happened?

Hi there,

I've got a "No module named 'rasa.core.policies.two_stage_fallback' " error message when trying to use my custom action. When I check the source code there is an import in **rasa/core/actions/action.py line 835** which is 
`from rasa.core.policies.two_stage_fallback import has_user_rephrased`
But there is no two_stage_fallback in **rasa/core/policies**.  There is a .py file in **rasa/core/actions** named **two_stage_fallback** but also it doesn't have the has_user_rephrased function. I don't know is this the cause of this issue. But anyone can help?

**Comment by ozgurdogan646** [comment]
Hi @ancalita. I solved my problem with deleting cache files and previous models. Thank you anyway 😄

**Comment by melindaloubser1** [comment]
Closing as solved
