### ISSUE TITLE
Look up and Synonyms are not working in RASA

### ISSUE THREAD

**Issue by abdiansah** [RasaHQ/rasa#11186]
### Rasa Open Source version

3.1.1

### Rasa SDK version

3.1.1

### Python version

3.9

### What operating system are you using?

Linux

### What happened?

I have used lookup table and synonyms, but the entities mentioned in the lookup are not detected by RASA, neither synonyms worked.

It works correctly for "I would like to place an order for large blue shoes", but if the input is "**medium**" (which is the lookup table) instead, it wont recognize.

it wont work if synonyms of "large" like "big" is used.

### Command / Request

```shell
nlu:
- intent: place_order
  examples: |
    - wanna [large](size) shoes for husky
    - need a [small](size) size [green](color) boots for pupps
    - have [blue](color) socks
    - would like to place an order

- lookup: size
  examples: |
    - small
    - medium
    - large

- synonym: small
  examples: |
    - small
    - s
    - tiny

- synonym: large
  examples: |
    - large
    - l
    - big

- synonym: medium
  examples: |
    - medium
    - m
    - average
    - normal

- lookup: color
  examples: |
    - black
    - blue
    - white
    - red
    - green
    - orange
    - yellow
    - purple
```

**Comment by ancalita** [comment]
@abdiansah My advice in your case is to increase your nlu examples with annotated entity examples sourced from the different lookup table options as well as synonyms. This allows the model to learn to use the generated regular expression as a feature. Once I added a few more nlu examples for intent `place_order` the issue you reported disappeared.
