### ISSUE TITLE
RASA HTTP model train not doing train properly 

### ISSUE THREAD

**Issue by kalpa277** [RasaHQ/rasa#11204]
### Rasa Open Source version

3

### Python version

3.8

### What operating system are you using?

Windows

### What happened?

[Beginner  in rasa ]
Hi [#Rasa]I am using *Rasa http* ...when I  train in rasa model *http://localhost:5005/model/train*  using POSTMAN it is trained succesfully in rasa 3.0 but when I am using *http://localhost:5005/model/parse* passing the body parameters as per documentation  the actual intent  it doesn't show but when I train l in command prompt the actual intent is shown. {https://rasa.com/docs/rasa/pages/http-api/#operation/trainModel

![sad](https://user-images.githubusercontent.com/94000670/174320050-e6e3fedc-25f3-4765-82ea-1f864ce38c98.png)
}

### Command / Request

```shell
rasa run --enable-api
```

**Comment by kalpa277** [comment]
Hi @melindaloubser1  when I train the model using postman I get warning as well   also as when I **parse**  get wrong intent .You can view from the screenshots.

The actual reason is model training  using postman not doing training properly and similarly the model parse request also showing wrong intent as per the text passing through body parameters.

 ![sad21](https://user-images.githubusercontent.com/94000670/175194488-4b1d446d-2946-4f60-b5c3-5d4d762e8384.png)(Model parse)
![sed](https://user-images.githubusercontent.com/94000670/175195077-aa09570d-f71d-4b46-8478-e34193444a0e.png)(Model traininging response 200)
![eds](https://user-images.githubusercontent.com/94000670/175195107-e86a0f5f-56c7-4740-943b-ce5fd8753cdb.png)(Intent)
![wed](https://user-images.githubusercontent.com/94000670/175195301-d7bba906-cf94-41d9-8390-c6ba3b206d36.png)(warnings when I train in postman )But when I train in terminal the model training works properly .
(Note:Becacuse in our prod enviroment we want to train through  api and server needs to restart every time  when we add new intent .)

**Comment by melindaloubser1** [comment]
Tip: In Postman, you can choose "Copy as `curl`" and post that instead, it is much easier to read than screenshots.

It looks like the format of your training request is somehow incorrect. The entire body of the request is not visible in the screenshots; to debug the format one needs to look at the entire request.
I do not think this is an issue with the endpoint itself, it's a usage issue. As such I'm marking this issue as a "question" not a bug. Questions generally belong on the [forum](https://forum.rasa.com/); however to wrap this up, please do post the full request, including training data body.

**Comment by kalpa277** [comment]
`curl --location --request POST 'http://localhost:5005/model/train' \
--header 'Content-Type: application/yaml' \
--data-raw 'pipeline: []

policies: []

intents:
  - greet
  - mood_great
  - subscribe
  - inform_email
  - inform_frequency
  - chitchat
  - affirm
  - deny
  - ask_price
  - explain
  - mood_bad
  - goodbye
  - ask_how_i_feel
  - confirm
  - thankyou
  - dominoer
  
entities: []
slots: {}
actions: []
forms: {}
e2e_actions: []

responses:
  utter_greet:
  - text: "Hey! How are you?"

  utter_goodbye:
  - text: "Bye"

session_config:
  session_expiration_time: 60
  carry_over_slots_to_new_session: true

nlu:
  - intent: greet
    examples: |
      - hey
      - hello
      - hi
      - hello there
      - good morning
      - good evening
      - moin
      - hey there
      - let'\''s go
      - hey dude
      - goodmorning
      - goodevening
      - good afternoon

  - intent: mood_great
    examples: |
      - perfect
      - great
      - amazing
      - feeling like a king
      - wonderful
      - I am feeling very good
      - I am great
      - I am amazing
      - I am going to save the world
      - super stoked
      - extremely good
      - so so perfect
      - so good
      - so perfect

  - intent: mood_bad
    examples: |
      - my day was horrible
      - I am sad
      - I don'\''t feel very well
      - I am disappointed
      - super sad
      - I'\''m so sad
      - sad
      - very sad
      - unhappy
      - not good
      - not very good
      - extremly sad
      - so saad
      - so sad

  - intent: goodbye
    examples: |
      - cu
      - good by
      - cee you later
      - good night
      - bye
      - goodbye
      - have a nice day
      - see you around
      - bye bye
      - see you later

  - intent: ask_how_i_feel
    examples: |
      - Ask me how I feel
      - Do you want to know how I feel?
      - Ask me about my feelings

  - intent: subscribe
    examples: |
      - I want to get the newsletter
      - Can you send me the newsletter?
      - Can you sign me up for the newsletter?
      - I want to subscribe to a newsletter.




  - synonym: once a week
    examples: |
      - once
      - once per week

  - intent: chitchat
    examples: |
      - that'\''s not what I want to do
      - wait stop
      - you'\''re no help
      - this is no help at all
      - how old are you
      - I want to order a pizza
      - tell me the weather
      - this isn'\''t working
      - I already told you that
      - don'\''t like that
      - I don'\''t want to tell you that
      - none of your business
      - that'\''s not right
      - stop asking
      - nevermind
      - I want to do something else
      - I changed my mind

  - intent: affirm
    examples: |
      - yes
      - indeed
      - of course
      - that sounds good
      - correct
      - sure
      - ok
      - why not
      - ok great
      - yes I did
      - yeah, great
      - pretty good
      - fine
      - You bet
      - I sure did
      - more or less

  - intent: deny
    examples: |
      - no
      - never
      - I don'\''t think so
      - no way
      - not really
      - none
      - absolutely not
      - no thanks
      - didn'\''t do any
      - no I didn'\''t
      - could have been better
      - not great
      - nope

  - intent: ask_price
    examples: |
      - how much will it be
      - what'\''s the price
      - how much will it cost
      - How much will I pay?

  - intent: explain
    examples: |
      - why
      - why do you need to know that
      - why should i give you this information
      - why are you asking?
      - why is this needed?

  - intent: confirm
    examples: |
      - can I confirm
      - I want to confirm
      - I would like to confirm that

  - intent: thankyou
    examples: |
      - thank you
      - thanks
      - thanks a lot
      - thank you so much!

  - intent: dominoer
    examples: |
      - I want to order pizza
      - pizza is delicious
      - I love pizzahut
      - I am pizza


rules:

- rule: Say goodbye anytime the user says goodbye
  steps:
  - intent: goodbye
  - action: utter_goodbye

stories:

- story: happy path
  steps:
  - intent: greet
  - action: utter_greet

'`
@melindaloubser1  pls check

**Comment by melindaloubser1** [comment]
Ok, I see the problem, it's training a model with no pipeline at all. If you leave out the `pipeline` and `policies` keys and instead just put 
```
recipe: default.v1
language: en
```

in the request, that should get you the default pipeline/policies. In that case I see all intents when running `rasa shell nlu`.
