### ISSUE TITLE
Possible memory leak

### ISSUE THREAD

**Issue by saswat0** [RasaHQ/rasa#11313]
### Rasa Open Source version

2.8.26

### Python version

3.6

### What operating system are you using?

Linux

### What happened?

I've deployed the demo chatbot at a certain endpoint and am using locust to stress test it. I have a single user (with 1 hatch rate) and am sending the message "hello" to the above endpoint to benchmark the application. Each time the server receives a request, the NLP engine tries to classify the intent and then responds back with an appropriate reply.

Here's my locust script:
```
class LoadCreate(HttpUser):
    wait_time = between(0.5, 0.51)

    @task
    def sayHello(self):
        payload = {"sender": self.name, "message": "Hello!"}
        response = self.client.post(apiUrl, json=payload)
        print(response.text)
```

The results from locust are quite abnormal to my understanding. Even when the number of users is constant (1), the response time keeps on increasing. Is there any explanation for this behaviour? I'm attaching the obtained plots herewith.

![image](https://user-images.githubusercontent.com/32325136/178222619-32dd75ed-2393-43a3-9d63-5236b906730f.png)

### Command / Request

```shell
rasa run --enable-api
```

**Comment by saswat0** [comment]
I tried hitting the NLU server (/model/parse) to find the root of this behaviour. Seems like rasa core is responsible for it
Below plot shows two runs. First one (on the left) is the response time when only NLU is at play. Run 2 (right) shows the response time when both NLU and core are running.

![total_requests_per_second_1657688198](https://user-images.githubusercontent.com/32325136/178655072-70f1d42e-7938-401d-83a7-2c4407d581ae.png)

**Comment by losterloh** [comment]
hey @saswat0 , I'd be interested in trying to reproducing this - which bot did you use exactly when referencing the "demo bot"? Is there anything you changed config wise?

**Comment by saswat0** [comment]
No, I didn't make any modifications to any of the scripts. I installed rasa via and ran `rasa run --enable-api`
