### ISSUE TITLE
Access Denied for All Rasa Commands

### ISSUE THREAD

**Issue by oliverblane** [RasaHQ/rasa#11383]
### Rasa Open Source version

2.8.2

### Rasa SDK version

2.8.6

### Python version

3.7

### What operating system are you using?

Windows

### What happened?

Every Rasa command I run is met with "Access Denied". I am not sure why this has suddenly started. I have tried running as Administrator with no luck. I have tried creating a new virtual environment but I am still receiving this same message.

### Relevant log output

```shell
Access Denied
```

**Comment by rgstephens** [comment]
This is not likely a Rasa issue. Please post questions on forum.rasa.com.
