### ISSUE TITLE
Individual characters as intent names in interactive mode

### ISSUE THREAD

**Issue by ryszardtuora** [RasaHQ/rasa#11415]
### Rasa Open Source version

3.2.1

### Python version

3.8

### What operating system are you using?

Linux

### What happened?

While in interactive mode, the user can try to correct the bot's proposed intent classification of a message, and then a list of hypotheses is presented along with their respective confidences. Besides the standard intents defined in the `domain.yml`, some individual characters appear on the list, with 0.00 confidences, e.g.

```
? What intent is it?  (Use arrow keys)                                                                                                                                                                               
 » <create_new_intent>
   0.93 intent1                        
   0.06 intent2                            
   ...                                           
   0.00 a                                       
   0.00 a                         
   0.00 c                                       
   0.00 c                                       
   0.00 c                                       
   0.00 d                                       
   0.00 d                                       
   0.00 g                                       
   0.00 g
   ...  
```                                                             
This is not intrusive, and does not seem to lead to any problems down the line, but can be misleading to the user, who can interpret this as a symptom of errors in the `domain.yml`.

I tracked this down to these lines in the `core/training/interactive.py`:

```
1478         domain_intents = domain.get("intents", []) if domain is not None else []
1479 
1480         intents = [next(iter(i)) for i in domain_intents]
```

According to the definition of `Domain` in `shared/core/domain.py` `.intents` should always return a list of strings (corresponding to intents), so I see no reason to create iterators out of these strings, and then take the first element of each (i.e. the first character of the intent name). It seems to me that substituting the lines cited above with this one would do the trick, and not break anything down the line:
```
intents = domain.get("intents", []) if domain is not None else []
```

I can submit a PR if this would be acceptable.

**Comment by ancalita** [comment]
@ryszardtuora Thanks for raising this! 
We actually identified a different solution, which is creating an instance of the domain `domain_obj = Domain.from_dict(domain)` then retrieving `intents = domain_obj.intents` which gives a list of strings, let us know if you're happy to submit a PR 💯

**Comment by ryszardtuora** [comment]
It seems to me that your proposition would break in the case where `domain` is `None`. Can we assume that this will not be the case?

**Comment by ancalita** [comment]
@ryszardtuora That sounds like a great topic for a unit test actually.
Looking at the code, however I think it's handled:
- `retrieve_domain` will always return a dict.
-  if this returns an empty dict, then creating a Domain instance using `Domain.from_dict` will not return `None`, but always a Domain object, albeit empty.

**Comment by weizhenzhao** [comment]
I also met that bug 
how could I fix it ?
If any one can help .
感激不尽

Thanks
weizhen
