### ISSUE TITLE
Utter and action sequence not respected.

### ISSUE THREAD

**Issue by adamwojt** [RasaHQ/rasa#11414]
### Rasa Open Source version

3.1.0

### Rasa SDK version

3.1.1

### Python version

3.8

### What operating system are you using?

Linux

### What happened?

We have hand-off mechanism that (re)-tries to call API to trigger hand-off in chat system we are using. Action `action_handoff` is async and it either completes hand-off successfully or if all retries failed it utters message saying "It seems I was unable ..."

There is also `utter_handoff.email_change` defined in rasa `domain` `responses` that should trigger first saying "One moment, I'll get a live agent ...". The stories are written like this:
![image](https://user-images.githubusercontent.com/45100954/182800790-df60efe1-71b1-4d39-9863-c833a77d1474.png)

When testing out what happens is that when bot attempts to hand-off when hand-off API is not available both messages are sent at same time after pause (for retries) which means that **rasa somehow waits for `action_handoff` to complete before triggering `utter_handoff.email_change`**. Is this expected behaviour ? How to fix it?

Below are sent at same time after long pause (caused by async function retrying handoff API calls)
![image](https://user-images.githubusercontent.com/45100954/182801386-77d2639f-6912-44d0-af71-2003fd8298eb.png)

### Command / Request

```shell
N/A
```

### Relevant log output

```shell
N/A
```

**Comment by ancalita** [comment]
@adamwojt Could you share more details about your input channel implementation? Some of the channels which are async should send the `utter_` responses straightaway, however there are channels that work synchronously and hence the issue you're encountering.

**Comment by adamwojt** [comment]
@ancalita Currently using Rasa HTTP webhook.

**Comment by ancalita** [comment]
@adamwojt We strongly recommend to use [socketio ](https://rasa.com/docs/rasa/connectors/your-own-website#websocket-channel) as an async channel instead. Let us know if you encounter the same issue with this channel.
