### ISSUE TITLE
Installing Rasa 3.2.7 using Poetry

### ISSUE THREAD

**Issue by bobvanderlinden** [RasaHQ/rasa#11544]
### Rasa Open Source version

3.2.7

### Python version

3.9

### What operating system are you using?

Linux

### What happened?

I'd like to use Rasa using Poetry. I have a poetry project (`pyproject.toml`) created using:

```
$ poetry init
# This creates pyproject.toml
$ poetry add rasa
# This adds rasa ^3.2.7
```

When I run `poetry run rasa` I get the following error:

```
$ poetry run rasa                            
Traceback (most recent call last):
...
    class CeilTimeout(async_timeout.timeout):
TypeError: function() argument 'code' must be code, not str
```

This seems to be an incompatibility of `aiohttp` and `async-timeout`: https://github.com/aio-libs/aiohttp/issues/6794#issuecomment-1180493371

Upgrading `aiohttp` seems to be the solution, however:

```
$ poetry add aiohttp@3.8.1

Updating dependencies
Resolving dependencies... (0.2s)

  SolverProblemError

  Because rasa-test depends on rasa (3.1.7) which depends on aiohttp (>=3.6,<3.7.4.post0 || >3.7.4.post0,<3.8), aiohttp is required.
  So, because rasa-test depends on aiohttp (3.8.1), version solving failed.
```

I see https://github.com/RasaHQ/rasa/pull/11225 upped the aiohttp version in Rasa.

### Command / Request

```shell
A new minor release of Rasa with the new aiohttp dependency (as already merged) would probably help.

Any suggestion to work around this problem would also be very much appreciated.
```

**Comment by ancalita** [comment]
Hey @bobvanderlinden 

I've just tried reproducing the bug you reported by going through all the steps you reported, however when I run `poetry run rasa` this command works fine with rasa `3.2.7`. Also running any `rasa` command works fine as well, without having to use `poetry run`.

I'd advise creating a new virtual environment from scratch, it seems from the log you gave you actually have rasa `3.1.7` installed in your environment, and not the latest version.

**Comment by bobvanderlinden** [comment]
Ah, you're absolutely right. My env was created using a different python version. Sorry for the confusion!
