### ISSUE TITLE
KeywordIntentClassifier overwride the result of DIETClassifier

### ISSUE THREAD

**Issue by yijinsheng** [RasaHQ/rasa#11540]
### Rasa Open Source version

3.2.4

### Python version

3.8

### What operating system are you using?

OSX

### What happened?

I add the KeywordIntentClassifier after DIETClassifier  in my config.yml. when i  post "good morning" , I expect rasa return 
{"intent":"greet","confidence":0.99}. but I get {"intent":"null"}. so I check the code in KeywordIntentClassifier in line 123~132.
```
for message in messages:
            intent_name = self._map_keyword_to_intent(message.get(TEXT))

            confidence = 0.0 if intent_name is None else 1.0
            intent = {"name": intent_name, "confidence": confidence}

            if message.get(INTENT) is None or intent is not None:
                message.set(INTENT, intent, add_to_output=True)

        return messages
```
The intent_name here may be None ,but the intent here will never be None.so is it better to change it to 

` if message.get(INTENT) is None or intent_name is not None:
`

**Comment by ancalita** [comment]
@yijinsheng This issue was fixed by PR #11542 which recently got merged. It will be released in the next rasa-oss micro release `3.2.x`.
