### ISSUE TITLE
Facing Error running graph component for node run_FallbackClassifier0 

### ISSUE THREAD

**Issue by arjun-234** [RasaHQ/rasa#11629]
### Rasa Open Source version

3.2.6

### Rasa SDK version

3.2.0

### Python version

3.7

### What operating system are you using?

Windows

### What happened?

Greetings, I am trying to add FallbackClassifier in my pipeline(rasa 3x), but it’s giving me error like : rasa.engine.exceptions.GraphComponentException: Error running graph component for node run_FallbackClassifier0

Here is my config file,

![Screenshot (248)](https://user-images.githubusercontent.com/103405661/194531466-2510e381-6eb5-45cb-a70f-3e515d8fb78b.png)
error:

![Uploading Screenshot (247).png…]()
please help me to solve this issue.

**Comment by amn41** [comment]
hi @arjun-234  - for usage questions, please ask on the forum. We use github for bugs and feature requests. 
When posting there, please also include the error message you get and/or a stack trace, and it is better to copy-paste your code in to triple backticks (```) rather than a screenshot, so that it can be indexed. 

For what it's worth, I suspect your error is that the fallbackclassifier expects another intent classifier to be present in the pipeline (before it) so that it can override its predictions when necessary. Your pipeline currently only has 1 component.
