### ISSUE TITLE
Get all Conversations from Tracker Store

### ISSUE THREAD

**Issue by soerenetler** [RasaHQ/rasa#11688]
### What problem are you trying to solve?

I am curently building a small dashboard for a client to display some analytics on the conversatation customers had with the Rasa chatbot. There is no endpoint to list all conversation ids.

### What's your suggested solution?

There is (even not officially documented) such an endpoint for Rasa Enterprise. Why doesn't Rasa have the same endpoint? I know it would be possible to have the tracker store in a database and query it directly, but this would allow external access to the database and would need different approaches for every kind of tracker store. It would be great to add such an endpoint!

### Definition of Done

The /conversations endpoint provides all conversation ids in the tracker store.

**Comment by sanchariGr** [comment]
@soerenetler we currently donot have this planned in our roadmap, but since we depend on community contributors like yourself to improve rasa would you be willing to work on this and send it over as a contribution?

**Comment by sanchariGr** [comment]
@soerenetler in order for us to understand the problem better could you please share more context on your business use-case?

**Comment by soerenetler** [comment]
Hi @sanchariGr,
The goal is to create a dashboard, most probably using streamlit, that displays statistics on the chatbot usage. Not only basic intent counts but also like "people who asked this also asked about" and showing changes in intents over time. For that to be possible I would need an API to get all conversations (potentially filtered by time) from the tracker store. I could query the database directly, but a much better approach would be to have a standardized endpoint within Rasa. It could be similar to the `/conversations` endpoint in Rasa X/Enterprise.

What are your thoughts on that? What more information do you need?

**Comment by sp-rasa** [comment]
Hi @soerenetler,
The features that you are talking about here are already present or under development in Rasa Pro. You can find the forum announcement [here](https://forum.rasa.com/t/community-memo-on-rasa-pro-launch/55923?u=sonam).

**Comment by soerenetler** [comment]
Yes it is, but in my oppinion it should also be a feature in the Open Source version. Can you tell me the reasoning why it is limited to the pro plan? In my oppinion it is a very basic functionality to get the previous conversations.

**Comment by stramec** [comment]
Hi @sp-rasa - can you list some links to where we can find this info. I've just started looking at the RASA OSS api documentation, I can find getting a conversation from the tracker by ID, but nothing about where I could for instance get a list of conversation IDs.

@soerenetler - did you make any progress with this, I'm looking for very similar functionality to which you have described.
