### ISSUE TITLE
Significantly longer response times from rasa server on versions 3.2.x and 3.3.0

### ISSUE THREAD

**Issue by daanzdev** [RasaHQ/rasa#11717]
### Rasa Open Source version

3.3.0

### Rasa SDK version

3.3.0

### Python version

3.9

### What operating system are you using?

Linux, OSX

### What happened?

There are much longer response times from rasa server on versions `3.2.x` and `3.3.0` comparing to `3.1.2` (~ 70-80% longer on my machine).
The workaround I have found is to downgrade `jsonschema` to version `3.2.0`.

(I'm running core-only model, trained with `rasa train core` command, sending messages in `/intent{"entity_name":"entity_value"}` format using `rest/webhook` endpoint)

**Comment by ancalita** [comment]
@daanzdev To clarify, you are observing longer response times by running `rasa run --enable-api` and sending requests to the webhook endpoint? Would be great to understand how you measured the speed also and what is the metric you're using for duration (ms/s).
