### ISSUE TITLE
ModuleNotFoundError: No module named '_bz2'

### ISSUE THREAD

**Issue by ltfschoen** [RasaHQ/rasa#11757]
### Rasa Open Source version

3.3.1

### Python version

3.7

### What operating system are you using?

Linux

### What happened?

I am using Ubuntu 22.04.1 LTS.
In the README.md it says to install Python 3.7.9.
But when I ran `rasa interactive` it gave error `ModuleNotFoundError: No module named '_bz2'`
So it was necessary to update to Python 3.9.15 to be able to run `rasa interactive` without that error

### Command / Request

```shell
rasa interactive
```

### Relevant log output

```shell
ModuleNotFoundError: No module named '_bz2'
```

**Comment by ancalita** [comment]
@ltfschoen Thanks for flagging, could you please share the full error traceback when running `rasa interactive` with Python 3.7?
