### ISSUE TITLE
Explain-ability with LIME or SHAP

### ISSUE THREAD

**Issue by sandeepbhutaniexl** [RasaHQ/rasa#11873]
### What problem are you trying to solve?

I want to explain the reason for correct or wrong predictions done by rasa. I want to know what words in input sentence have led to a specific prediction class

### What's your suggested solution?

How can we use explainability libraries like LIME or SHAP?
These libraries seem to work with predict functions, which is not available directly with dietclassifer

### Definition of Done

If there is alternate way to SHAP or LIME or something else for rasa please suggest. 
or please provide code sample, how to use these libraries with rasa mode having DietClassifer

**Comment by radovanZRasa** [comment]
Hi @sandeepbhutaniexl 
Thank you for submitting this feature request.
We will look into it and let you know our findings.
