### ISSUE TITLE
AttributeError: module 'rasa_nlu.config' has no attribute 'load'

### ISSUE THREAD

**Issue by vignesh-013** [RasaHQ/rasa#11872]
### What problem are you trying to solve?

AttributeError: module 'rasa_nlu.config' has no attribute 'load'

**Comment by m-vdb** [comment]
@vignesh-013 `rasa_nlu` is not a module in the recent versions of Rasa Open Source. I suspect you're on a very old version here. I'll close the ticket, but please let me know if I was wrong :)
