### ISSUE TITLE
Problems with rasa installation on Python 3.10

### ISSUE THREAD

**Issue by AlvaroLeles** [RasaHQ/rasa#11888]
### Rasa Open Source version

3.3.3

### Python version

3.10

### What operating system are you using?

Linux

### What happened?

When trying to install Rasa with ```pip3 install rasa``` command, I get an error saying that "python setup.py egg_info did not run successfully." and "RuntimeError: Python version 2.7 or 3.4+ is required." even though I had Python 3.10 in my machine.

I saw some comments in internet saying that Rasa does not support Python 3.10, would it be interesting to put this information in the README and in the documentation?

### Command / Request

```shell
pip3 install rasa
```

### Relevant log output

```shell
Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [6 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/tmp/pip-install-j_1vpkc3/absl-py_6f5c88f1b9304f94bc8868753911364e/setup.py", line 34, in <module>
          raise RuntimeError('Python version 2.7 or 3.4+ is required.')
      RuntimeError: Python version 2.7 or 3.4+ is required.
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
```

**Comment by radovanZRasa** [comment]
@AlvaroLeles 
Hello, thank you for reaching out!
Rasa supports python 3.10 from version 3.4.0.
