### ISSUE TITLE
Improving README.md steps in Development Internals

### ISSUE THREAD

**Issue by antoniotoineto** [RasaHQ/rasa#11894]
### Rasa Open Source version

3.3.3

### Python version

3.8

### What operating system are you using?

Linux

### What happened?

When I was intalling the environment to contribute with Rasa, first I got some instruction at [this link](https://rasa.com/docs/rasa/installation/environment-set-up), on the Rasa website.

On the site says we should install one of these Python supported versions: ```3.7, 3.8, 3.9``` or ```3.10```

And if we need to create a new virtual environment manually using those Python3 version, we can use the 2 command below:
```
python3 -m venv ./venv
source ./venv/bin/activate
```

But if we follow the steps at the official [README.md](https://github.com/RasaHQ/rasa#managing-environments), there says we should run the following command: ```python -m venv ./venv```
Running this, we should get a "command not found" as this is not about the phython version 3.x we have (that is supported by Rasa) 

This section at README.md should get updated to the Python3 command, as it happens on the official site rasa.com

**Comment by radovanZRasa** [comment]
Hi @antoniotoineto
Thank you for reporting the issue!
We will look into it as soon as possible.

**Comment by antoniotoineto** [comment]
Hi @radovanZRasa
I've opened the [PR #11908](https://github.com/RasaHQ/rasa/pull/11908) to get this done!
