### ISSUE TITLE
Training model not working on mac m1: 9284 illegal hardware instruction

### ISSUE THREAD

**Issue by vitordiniz25** [RasaHQ/rasa#11897]
### Rasa Open Source version

3.3.1

### Rasa SDK version

3.3.0

### Python version

3.9

### What operating system are you using?

OSX

### What happened?

I have install Rasa on my M1 Macbook Air, and i'm getting the following problem when I try to use rasa init to train a model.

`[1]    9284 illegal hardware instruction  rasa init`

I have found some solutions on the internet but I couldn't find an official approach to solve this.

### Command / Request

```shell
rasa init
```

### Relevant log output

```shell
rasa init
Welcome to Rasa! 🤖

To get started quickly, an initial project will be created.
If you need some help, check out the documentation at https://rasa.com/docs/rasa.
Now let's start! 👇🏽

? Please enter a path where the project will be created [default: current direc
tory]
? Directory '/Users/vitordiniz' is not empty. Continue? Yes
Created project directory at '/Users/vitordiniz'.
Finished creating project structure.
? Do you want to train an initial model? 💪🏽 Yes
Training an initial model...
[1]    9284 illegal hardware instruction  rasa init
```

**Comment by radovanZRasa** [comment]
@vitordiniz25 Hi, thank you for your report.
Unfortunately I am not able to reproduce the issue on Mac M1 OS Monterey 12.6.1, Python 3.9.14, Poetry 1.1.13 with virtual environment created with pyenv.

Could you provide us with a bit more information:
1. What have you used to create your virtual environment?
2. What version of poetry did you use to install dependencies?
3. Have you installed your dependencies in a clean virtual environment?
4. What version of Mac OS are you running?
