### ISSUE TITLE
Cython installation issue in arm processor.

### ISSUE THREAD

**Issue by kranthi419** [RasaHQ/rasa#11925]
When I build an image in an arm processor, I'm getting the below error.
#24 4770.         from Cython.Build import cythonize
#24 4770.     ModuleNotFoundError: No module named 'Cython'

then, I specified cython = "~0.29.14" in the poetry file and was facing the below error.
Because rasa depends on cython (~0.29.14) which doesn't match any versions, version solving failed.

Can someone help on resolving this, thanks in advance.

**Comment by faso-dev** [comment]
Sorry for this, but i'm not able to open a new issue.

I'm working on M1 PRO and my OS is Mac OS Ventura, my python version is : 3.11.1

When i try to install this package with pip, i get this error : 

` error: subprocess-exited-with-error

  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [6 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/private/var/folders/qd/2bzhxq4j2nj7z0khl22y7gvh0000gn/T/pip-install-1lr66dp8/absl-py_e186e8b71d72477aa1413652585ea91d/setup.py", line 34, in <module>
          raise RuntimeError('Python version 2.7 or 3.4+ is required.')
      RuntimeError: Python version 2.7 or 3.4+ is required.
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
`

I know that it's not the same error, but i need help

**Comment by m-vdb** [comment]
Hi there, thanks for the bug report. I'm confused as to how you were able to open a new issue on our repo. We've moved all our issues to Jira (see [this pinned issue](https://github.com/RasaHQ/rasa/issues/11921)). Can you let me know how you were able to create this GitHub issue?

At first sight, if I understand correctly, you're trying to install rasa with python 3.11. 3.11 is not a version we support at the moment (we support 3.7, 3.8, 3.9 and 3.10).

**Comment by m-vdb** [comment]
I'll close this issue for now. Feel free to reopen it on Jira 🙏🏻
