### ISSUE TITLE
RASA NLU trainer error

### ISSUE THREAD

**Issue by antonioabrantes** [RasaHQ/rasa#12342]
config,json
{
    "pipeline":"tensorflow_embedding",
    "path":"./models/nlu",
    "data":"./data/data.json",
    "component_names":[
        "nlp_spacy",
        "tokenizer_spacy",
        "intent_entity_featurizer_regex",
        "intent_featurizer_count_vectors",
        "ner_crf",
        "intent_classifier_tensorflow_embedding"
    ]
}

from rasa_nlu.training_data import load_data
from rasa_nlu.model import Trainer
from rasa_nlu import config
from rasa_nlu.model import Interpreter

def train_horoscopebot3(data_json, config_file, model_dir):
    training_data = load_data(data_json)
    config_data = config.load(config_file)
    trainer = Trainer(config=config_data)
    trainer.train(training_data)
    model_directory = trainer.persist(model_dir, fixed_model_name = 'horoscopebot')

train_horoscopebot3('./data/data.json', 'config.json', './models/nlu')

How to solve this error? 

---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
Cell In[12], line 1
----> 1 train_horoscopebot3('./data/data.json', 'config.json', './models/nlu')

Cell In[11], line 37, in train_horoscopebot3(data_json, config_file, model_dir)
     22 training_data = load_data(data_json)
     24 #trainer = Trainer(config.load(config_file))
     25 
     26 #trainer = Trainer(config.load(config_file, 'yaml', {}))
   (...)
     34 ##    config_data = yaml.load(f, Loader=yaml.SafeLoader)
     35 ##trainer = Trainer(config=config_data)    
---> 37 config_data = config.load(config_file)
     38 trainer = Trainer(config=config_data)
     40 trainer.train(training_data)

File ~\anaconda3\lib\site-packages\rasa_nlu\config.py:44, in load(filename, **kwargs)
     42 if filename is not None:
     43     try:
---> 44         file_config = utils.read_yaml_file(filename)
     45     except yaml.parser.ParserError as e:
     46         raise InvalidConfigError("Failed to read configuration file "
     47                                  "'{}'. Error: {}".format(filename, e))

File ~\anaconda3\lib\site-packages\rasa_nlu\utils\__init__.py:236, in read_yaml_file(filename)
    234 def read_yaml_file(filename):
    235     fix_yaml_loader()
--> 236     return yaml.load(read_file(filename, "utf-8"))

TypeError: load() missing 1 required positional argument: 'Loader'

**Comment by Vivekt719** [comment]
def train_horoscopebot3(data_json, config_file, model_dir):
    training_data = load_data(data_json)
    config_data = config.load(config_file, loader=yaml.SafeLoader)
    trainer = Trainer(config=config_data)
    trainer.train(training_data)
    model_directory = trainer.persist(model_dir, fixed_model_name='horoscopebot')
In this updated code, we're passing the yaml.SafeLoader parser as the loader argument to the config.load() function, which should resolve the TypeError.

**Comment by antonioabrantes** [comment]
I run and there is still another error:
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
Cell In[6], line 1
----> 1 train_horoscopebot3('./data/data.json', 'config.json', './models/nlu')

Cell In[5], line 50, in train_horoscopebot3(data_json, config_file, model_dir)
     32 training_data = load_data(data_json)
     34 #trainer = Trainer(config.load(config_file))
     35 
     36 #trainer = Trainer(config.load(config_file, 'yaml', {}))
   (...)
     47 #config_data = config.load(config_file)
     48 #trainer = Trainer(config=config_data)
---> 50 config_data = config.load(config_file, loader=yaml.SafeLoader)
     51 trainer = Trainer(config=config_data)
     53 trainer.train(training_data)

File ~\anaconda3\lib\site-packages\rasa_nlu\config.py:44, in load(filename, **kwargs)
     42 if filename is not None:
     43     try:
---> 44         file_config = utils.read_yaml_file(filename)
     45     except yaml.parser.ParserError as e:
     46         raise InvalidConfigError("Failed to read configuration file "
     47                                  "'{}'. Error: {}".format(filename, e))

File ~\anaconda3\lib\site-packages\rasa_nlu\utils\__init__.py:236, in read_yaml_file(filename)
    234 def read_yaml_file(filename):
    235     fix_yaml_loader()
--> 236     return yaml.load(read_file(filename, "utf-8"))

TypeError: load() missing 1 required positional argument: 'Loader'

train_horoscopebot3('./data/data.json', 'config.json', './models/nlu')

my config.json:
{
    "pipeline":"tensorflow_embedding",
    "path":"./models/nlu",
    "data":"./data/data.json",
    "component_names":[
        "nlp_spacy",
        "tokenizer_spacy",
        "intent_entity_featurizer_regex",
        "intent_featurizer_count_vectors",
        "ner_crf",
        "intent_classifier_tensorflow_embedding"
    ]
}

**Comment by m-vdb** [comment]
Hi there, thanks for raising this. I kindly ask you to create your issue on Jira: https://rasa-open-source.atlassian.net/jira/software/c/projects/OSS/boards/1 . Thanks!
