### ISSUE TITLE
option --pre_load all only loads fallback model on s3

### ISSUE THREAD

**Issue by asauray** [RasaHQ/rasa#1300]
**Rasa NLU version**: 0.13.1

**Operating system** (windows, osx, ...): MacOS

**Issue**:
When using the `--pre_load` option, the models being loaded by Rasa are only the fallback models. Rasa ignores the others. Is there a way to load **all** the models stored on s3 ?

**Comment by akelad** [comment]
Thanks for raising this issue, @amn41 will get back to you about it soon.

**Comment by antoinesauray** [comment]
@amn41 is there anything new for this issue ?

**Comment by amn41** [comment]
@antoinesauray sorry for the slow response. No, this is not something you can do automatically via command line flags. 

However if you write your own start up script you can manually call the `Project`'s `dynamic_load_model` method for each model

**Comment by souvikg10** [comment]
```
--pre_load PRE_LOAD [PRE_LOAD ...]
                        Preload models into memory before starting the server.
                        If given `all` as input all the models will be loaded.
                        Else you can specify a list of specific project names.
                        Eg: python -m rasa_nlu.server --pre_load project1
                        --path projects -c config.yaml
```

I actually had the same confusion and I think it came from the documentation here. In my understanding I thought we can pre_load specific models but intact it will be specific project that should have the default model naming convention. 

If I understand well, won't be a nice feature to be able to precise the project and it loads all models in it instead of only the fallback ones?

**Comment by amn41** [comment]
I can certainly see the use case for wanting to load a specific model rather than the default one, but what's the use case for wanting to pre-load every single model on startup?

**Comment by souvikg10** [comment]
Based on the code I saw, i thought it would be easier first step but yeah if we can specify a specific model on pre load, that would be great

**Comment by amn41** [comment]
cool - this would be an awesome contribution of someone wanted to work on it :)

**Comment by wochinge** [comment]
closed by https://github.com/RasaHQ/rasa/pull/1410
