### ISSUE TITLE
Developing custom pipeline

### ISSUE THREAD

**Issue by Srivemu** [RasaHQ/rasa#1435]
Hi,

I have been trying to create a custom pipeline with a reference provided in the following link.

https://rasa.com/docs/nlu/customcomponents/#section-customcomponents

However, I haven't been successful yet. Can someone provide any sample code for a custom pipeline that works?

Thanks,
SR.

**Comment by akelad** [comment]
Thanks for raising this issue, @JustinaPetr will get back to you about it soon.

**Comment by swagat-panda** [comment]
while creating a custom component pipeline an exception is creating in config.py for index.
can you resolve it
