### ISSUE TITLE
TrainingData.merge() doesn't check for duplicate examples per intent

### ISSUE THREAD

**Issue by MetcalfeTom** [RasaHQ/rasa#1446]
e.g. by merging

```
## intent:greet
- hi
```

with

```
## intent:greet
- hi

```
we get

```
## intent:greet
- hi
- hi
```

**Comment by MetcalfeTom** [comment]
You're right, there's nothing implemented.  The only data processing done for the intents upon building `TrainingData()` is in `sanitize_examples()` which removes whitespace

**Comment by akelad** [comment]
@MetcalfeTom is this still relevant?

**Comment by MetcalfeTom** [comment]
It is still relevant for features like interactive learning where we dump new NLU data.  I think it functions well as a community issue

**Comment by hsm207** [comment]
I want to work on this

**Comment by akelad** [comment]
awesome! let us know if we can help with anything

**Comment by hsm207** [comment]
@akelad what would the unit test using @MetcalfeTom example look like? Should I create a markdown file containing the given examples or can each intent be represented as an instance of `TrainingData`?

**Comment by akelad** [comment]
@hsm207 you can take a look at the tests written here: https://github.com/RasaHQ/rasa/blob/master/tests/nlu/base/test_training_data.py

**Comment by hsm207** [comment]
@akelad I've made PR #4414 for your review.

**Comment by hsm207** [comment]
This issue can be closed now.
