### ISSUE TITLE
rasa_nlu tries to load an `entity_synonyms.json` file even when none exists (

### ISSUE THREAD

**Issue by amn41** [RasaHQ/rasa#1450]
rasa_nlu tries to load an `entity_synonyms.json` file even when none exists (entry is still added to `metadata.json` but it shouldn't be )

**Comment by i3games** [comment]
This also means the "Try it out" tutorial is currently broken 

<img width="898" alt="screen shot 2018-10-10 at 01 59 33" src="https://user-images.githubusercontent.com/830492/46707113-62082e80-cc30-11e8-82c3-b60df2ee4654.png">

**Comment by amn41** [comment]
thanks @i3games  - what do you mean that it's broken? From your screenshot it looks like it works, but just throws a warning.

**Comment by i3games** [comment]
I see. I misinterpreted the output.
