### ISSUE TITLE
Standart HTTP component

### ISSUE THREAD

**Issue by abdelrahman-t** [RasaHQ/rasa#1580]
taking a look at the docs it seems that sub-classing "Component" is the only way to add a custom component (and registering it [here](https://github.com/RasaHQ/rasa_nlu/blob/master/rasa_nlu/registry.py#L49) which requires modifying the project source code, I was wondering if its possible to just add a generic HTTP component. The HTTP component would then be able to communicate with any back-end for integrating any pre-existing pipelines, in this case users would just need to add a simple REST interface which RASA can send incoming messages to.

**Comment by abdelrahman-t** [comment]
if you think that's a good idea, I would be willing to make a pull request.

**Comment by akelad** [comment]
Thanks for raising this issue, @tmbo  will get back to you about it soon.

**Comment by tmbo** [comment]
You do not need to change the code, you can also reference the component without putting it into the registry (referencing it by full class path) - should be stated like that in the docs.

But I think the http component might still be useful. What would be your use case for that?

**Comment by abdelrahman-t** [comment]
We had a pre-existing pipeline that does some preprocessing specific to our use case, I was just thinking about making a simple REST that RASA could send messages to for preprocessing. what I ended up doing is that I retrofitted our pre-existing code to be in the form of RASA components, on the same note I was wondering what would be the idiomatic why to feed an audio input into RASA?

I can work on implementation, if you decide to add this component.

**Comment by akelad** [comment]
@abdelrahman-t is this something you're still working on?

**Comment by abdelrahman-t** [comment]
no, I am happy to work on it though If you decide to add this feature to RASA.

**Comment by akelad** [comment]
hm actually wait, does the REST channel not cover this? https://rasa.com/docs/core/connectors/#rest-channels

**Comment by abdelrahman-t** [comment]
I think this is only used to receive message and send back bot responses, however this feature proposes a way to plug any pre-existing component to RASA-NLU pipeline, any component that implements a REST API can be integrated, for instance my original use case was that we had pre-existing pipeline written in Java and we needed to migrate to RASA, so I was thinking about just making A REST API that wraps the pipline and then add an HTTP component to RASA-NLU that would just send message to the API.

**Comment by akelad** [comment]
ah got it. @tmbo what do you think, does it make sense to add this?
