### ISSUE TITLE
add model server description to docs

### ISSUE THREAD

**Issue by wochinge** [RasaHQ/rasa#1591]
https://rasa.com/docs/nlu/master/endpoint_configuration/#model-server does not include any description what a model server does, how its response should look like etc (unlike it's done here: https://rasa.com/docs/core/server/#fetching-models-from-a-server)

**Comment by tmbo** [comment]
Let's not do this now

**Comment by akelad** [comment]
@wochinge is this still relevant?

**Comment by wochinge** [comment]
yes, please. But let's revisit this after the docs update.
