### ISSUE TITLE
Entity Extraction - Exact Match

### ISSUE THREAD

**Issue by odannyc** [RasaHQ/rasa#1626]
I am running into issues with `ner_crf` and `ner_synonyms`.
the CRF entity extractor will extract entities which don't exactly match with the synonyms that I have defined. I am using Dialogflow format for training if that matters. For example:

This is an example of one of my entities with synonyms:
```
 {
    "value": "NYC",
    "synonyms": [
      "New York City",
      "NY",
     "Times Square"
    ]
  },
```

If I ask the phrase: "find restaurants in new yorkcity"

Rasa will find the entity `new yorkcity` and return that in the entities field, like so:

```
"entities": [
    {
      "start": 20,
      "end": 33,
      "value": "new yorkcity",
      "entity": "cities",
      "confidence": 0.9363500367814994,
      "extractor": "ner_crf"
    }
  ]
```

As you can tell the problem is that it didn't match on any of the synonyms so it just passed it over to me as the user typed it. The isse is that it is not the behavior that I am expecting. I want the entity extractor to *ONLY* match what's in my entity synonyms. Is there an entity extractor I can use, or a way to modify `ner_crf` to only directly match whats in synonyms?

Thanks.

**Comment by akelad** [comment]
Thanks for raising this issue, @MetcalfeTom  will get back to you about it soon.

**Comment by odannyc** [comment]
I found a decent solution/workaround. [In `entity_synonyms`](https://github.com/RasaHQ/rasa_nlu/blob/master/rasa_nlu/extractors/entity_synonyms.py#L96-L98) we can have a flag to either match exactly with the equality operator (`==`) or do fuzzy matching, kinda like I have it [setup in this fork](https://github.com/Revmaker/rasa_nlu/blob/6191588fa49af5f956e9f7da5b6c47c6f8bc5115/rasa_nlu/extractors/entity_synonyms.py#L97-L100).

**Comment by MetcalfeTom** [comment]
Hi @odannyc,

Nice work!  I can see this being a valuable feature for the repo if you are willing to set up a PR, however:

1. [We experimented with fuzzy matching before](http://blog.rasa.com/improving-entity-extraction/#fuzzymatching) and found it to slow performance for large numbers of examples
2. We are always wary of incorporating unmaintained dependencies

So we'd default this flag to the equality operator, but apart from that I think it would be (another) great contribution from your team ☺
