### ISSUE TITLE
Caching dosen't works with docker image for custom component

### ISSUE THREAD

**Issue by devendrasoni18** [RasaHQ/rasa#1688]
**Rasa NLU version**: 0.14.0a1

**Operating system** (windows, osx, ...): windows

**Content of model configuration file**: yml
```yml

```

**Issue**:

Hello,

I am facing an issue with caching while running rasa_nlu within docker. I have created a custom component for sentiment analysis and loaded a pre-trained model. Due to which each time when I train the model in docker, the memory increases.

As a workaround, I implemented cache_key() method to cache the custom component so that it would not load the pre-trained model again. This trick works when I run rasa_nlu project directly from my machine. But **caching doesn't works** while I run the same with my custom **Docker image**. Each time when I train rasa, it passes `cached_component` as None within `load()` function of the custom component.
`customComponent

    @classmethod
    def cache_key(cls, model_metadata):
        # type: (Metadata) -> Optional[Text]
        return cls.name
    @classmethod
    def load(cls, model_dir=None, model_metadata=None, cached_component=None, **kwargs):
        if cached_component:
            return cached_component
        else:
            # Do something else
`
Is there any known issue with docker for caching?
Kindly help me with the same. 
Thanks in advance!!

**Comment by akelad** [comment]
Thanks for raising this issue, @wochinge   will get back to you about it soon.

**Comment by wochinge** [comment]
@devendrasoni18 Please ask questions which are not related to bugs in our forum: https://forum.rasa.com

> Due to which each time when I train the model in docker, the memory increases.
This sounds like it could be a bug. Can you please describe what happens and why this brought you to implement your custom component?

**Comment by devendrasoni18** [comment]
Hello @wochinge , @akelad,
Any updates or review on it?

**Comment by devendrasoni18** [comment]
Hi @akelad ,
Please let me know if you are looking into it. Its being long since no one replied.

Thanks in advance!

**Comment by wochinge** [comment]
@devendrasoni18 What are your steps to train with docker image?
Shouldn't you be starting a new docker container everytime you are training?

**Comment by devendrasoni18** [comment]
HI @wochinge Thanks for your reply.
No, the container is created once and it is used through out.
I am running rasa_nlu using docker-compose on server. I have also created a web app for training purpose. So I give a rest call for training to the running rasa_nlu server. So I think it is not possible restarting docker container for each training call.

**Comment by wochinge** [comment]
@devendrasoni18 
* Should it not  be `cls.__name__` instead of `cls.name` in your provided snippet of the `cache_key` method?
* How do you start NLU? Are you using a custom python script for that?
* can you share your custom component? Seems like your are loading something into memory and don't unload it which lets the memory increase over time

**Comment by devendrasoni18** [comment]
Hello @wochinge 

- I have used the cache_key() code from spacy_utils.py. Anyways I will update `cls.name` to `cls.__name__`

- I am creating a docker image using the base image rasa_nlu and copied the custom component file into container. Also copied some pretrained model pickle files
 
```
# DockerFile
FROM rasa/rasa_nlu:0.14.0a1-tensorflow

COPY rasa_nlu/rasa_nlu/sentiment/ ${RASA_NLU_HOME}/rasa_nlu/customComponentName/
COPY rasa_nlu/customModels/ ${RASA_NLU_HOME}/customModels/
RUN tar -C ${RASA_NLU_HOME}/customModels -zxvf ${RASA_NLU_HOME}/customModels/model_file.tar.gz 
```
and then running the docker run command: `docker run -p 5000:5000 1ca7e5b17bd8`

- Here's the load function of my custom component in which I am loading pretrained model.

```
# custom component class
class customComponent(Component):
@classmethod
    def create(cls, config):
        component_config = config.for_component(cls.name, cls.defaults)
        return customComponentClass(component_config)

    def train(self, training_data, cfg=None, **kwargs):
        # No need to train anything in the pipeline, that's why left blank
        pass

    def persist(self, model_dir):
        # Called after train function
        return {"classifier_file": MODEL_FILE_NAME,
                "training_dtm_file": DTM_FILE_NAME}

    @classmethod
    def load(cls,
             model_dir=None,  # type: Optional[Text]
             model_metadata=None,  # type: Optional[Metadata]
             cached_component=None,  # type: Optional[Component]
             **kwargs  # type: **Any
             ):
        meta = model_metadata.for_component(cls.name)
        clf_file_name = meta.get("classifier_file", MODEL_FILE_NAME)
        dtm_file_name = meta.get("dtm_file", DTM_FILE_NAME)

        # Path for the model is rasa_nlu/projects/
        model_path = os.path.join(model_dir, '../../../', MODEL_PATH)

        classifier_file = os.path.join(model_path, clf_file_name)
        dtm_file = os.path.join(model_path, dtm_file_name)
        if cached_component:
            return cached_component
        elif os.path.exists(classifier_file):
            clf = utils.pycloud_unpickle(classifier_file)
            training_dtm = utils.pycloud_unpickle(dtm_file)
            return cls(
                component_config=meta,
                clf=clf,
                training_dtm=training_dtm,
            )
        else:
            return cls(component_config=meta)
```

**Comment by devendrasoni18** [comment]
Hi @wochinge ,

Have you got a chance to look into it?

**Comment by wochinge** [comment]
@devendrasoni18 Is there a file called `metadata.json` in the zipped model? What's is content?

**Comment by wochinge** [comment]
Maybe this tutorial can also help you further: https://blog.rasa.com/enhancing-rasa-nlu-with-custom-components/
