### ISSUE TITLE
[feature request] add evaluation output for cross-validation

### ISSUE THREAD

**Issue by jstriebel** [RasaHQ/rasa#1708]
Currently the nlu evaluation script supports different evaluation metrics and outputs (which are very useful :+1:) solely for training- / test-data splits, and not for crossvalidation mode. Those are:
* `--confmat`
* `--errors`
* `--successes`
* `--report`
* `--histogram`

This is partially documented [here](https://rasa.com/docs/nlu/evaluation/#intent-classification), but as an initial step the `evaluate` command should also warn about superfluous arguments, that can not be used, or even abort then.
Even more important would be to support those outputs also for crossvalidation mode. This seems straightforward to me:
* `--confmat`: sum across all cv runs (or average for relative percentages)
* `--errors`: combine across all runs
* `--successes`: combine across all runs
* `--report`: just format the output
* `--histogram`: combine confidences and build histogram on that

It seems to be possible to reuse the functions for normal runs on the combined results of the cv runs.
Did I miss something that makes this more complicated or undesirable? Or is this on your roadmap anyways? Thanks for considering this.

**Comment by akelad** [comment]
@jstriebel this is definitely something that would make sense to do -- is this something you're willing to work on?

**Comment by jstriebel** [comment]
As I currently don't need it, it doesn't have a priority. If it comes up again next time, I will tackle this, though :+1:

**Comment by nimf** [comment]
Hey. I'm working on it. Will create a PR soon.

**Comment by nimf** [comment]
Ok, I've opened the PR. Please, check it out when you have a chance.
