### ISSUE TITLE
Python 3.7 support

### ISSUE THREAD

**Issue by parthsharma1996** [RasaHQ/rasa#1709]
**Issue**: When can we expect python 3.7 support?
I see that `tensorflow 1.12` is required for installing the tensorflow pipeline. Are there any breaking changes in `tensorflow 1.13` which is preventing the upgrade to `tensorflow 1.13`? 

The rest of my team is switching so `python 3.7` support would be nice.

**Comment by akelad** [comment]
Thanks for raising this issue, @tmbo  will get back to you about it soon.

**Comment by tmbo** [comment]
Yes, def - thanks for the headsup wasn't aware that the new 1,13rc1 finally contains this (ref https://github.com/tensorflow/tensorflow/issues/17022).

So I guess it is time for us to support it as well :rocket: - I'll create a branch and a WIP PR just to check if tests pass.

**Comment by nmstoker** [comment]
*Good news:* 1.13.1 is released now, no longer just RC:
https://github.com/tensorflow/tensorflow/releases/tag/v1.13.1

**Comment by tmbo** [comment]
awesome, @Ghostvv how did the 1.13 tensorflow work out for you locally?

**Comment by Ghostvv** [comment]
I installed the latest version of `numpy` with `pip install -U numpy` and there were another library, I don't remember, also upgraded to latest
