### ISSUE TITLE
Make evaluation script more VM-friendly

### ISSUE THREAD

**Issue by MetcalfeTom** [RasaHQ/rasa#1750]
Right now, plotting the graphs causes crashes on VMs.

My suggestion is to export the graphs into the `/reports` folder with the intent/entity results.  Make this default behaviour, and show the graphs with another flag.

Also, store files in separate directories according to model name

**Comment by akelad** [comment]
I think just saving the graphs also causes an error no?

**Comment by alwx** [comment]
Closing it due to inactivity.
