### ISSUE TITLE
Remove duckling from interpreter instead of extractors in test.py

### ISSUE THREAD

**Issue by erohmensing** [RasaHQ/rasa#1772]
Currently, the entity predictions are parsed while duckling is still part of the pipeline, even though we don't want to evaluate duckling. This involves unnecessary calls to the http server (throwing a million errors if you don't have the server running), as well as unnecessarily removing the parsed duckling entities from the predictions. 

To check:
 - check to see if duckling entities are in the entity_targets, if so, remove them upon getting the targets

**Comment by erohmensing** [comment]
Should we also remove SpacyEntityExtractor and MitieEntityExtractor from the pipeline as they don't return confidences? -- while we're at it, why is their confidence `None` while duckling's is 1?

**Comment by erohmensing** [comment]
Ah yeah you're correct, I see now that mitie is for custom entities, so I'll leave that in there and take spacy out

**Comment by tmbo** [comment]
@erohmensing can you please update this issue, e.g. link to the updated PR?

**Comment by erohmensing** [comment]
Yes sorry, let me make a draft PR out of the new branch (haven't worked on that since closing the old branch friday, hence the no new PR)
