### ISSUE TITLE
Luis Schema Version incompatibility

### ISSUE THREAD

**Issue by akshaya-venkatesh8** [RasaHQ/rasa#1790]
**Rasa NLU version**: 0.14.4

On Mac OSX
**Issue**:

Exception: Invalid luis data schema version 3.2.0, should be 2.x.x. Make sure to use the latest luis version (e.g. by downloading your data again).
make: *** [train-nlu] Error 1

I am seeing this issue when I train my rasa nlu using an app exported from LUIS. Is there a fix delivered for this? Please advice.

Thanks in advance.
[rasa-issue.txt](https://github.com/RasaHQ/rasa_nlu/files/2988379/rasa-issue.txt)

**Comment by imLew** [comment]
Rasa currently does not accept LUIS data schemata that are not of version "2.x.x".
This will change in the future but for now you will have to use and older LUIS data schema.

**Comment by imLew** [comment]
@LucasPenido of course! We'd love it if you made a PR fixing this :D

**Comment by LucasPenido** [comment]
Hi @imLew, I have a doubt. It is important to Rasa accept both versions 2 and 3, or it has to just accept the latest version?

**Comment by imLew** [comment]
Hi @LucasPenido, yes, even thought rasa would ideally be compatible with all version, if it's up to version 4 now then version 4 compatibility is more important than version 3 compatibility. 
It is however important that we maintain version 2 compatibility, since it's already there.

**Comment by LucasPenido** [comment]
@imLew, recently Microsoft released version 5 of Luis. It seems that versions are periodicaly released, althought the new version, there is no diference in the JSONs files, so I think that is important to find another approach to this. Since the latest version is always exported.

**Comment by imLew** [comment]
@LucasPenido going up two versions since march is quite fast, do you know they plan to continue incrementing versions so quickly?
Do you have suggestions how we should handle this?
I would suggest adding a list of versions for which `LuisReader` is known to work and maybe replacing the exception with a warning and trying to load any unknown version with the version reader that is closest to it.

**Comment by LucasPenido** [comment]
@imLew Thanks for the suggestion! Together with this warning we could check if the JSON that LUIS exports is compatible that LuisReader supports, if so, only a warning is thrown, if not, we throw a exception.

**Comment by imLew** [comment]
I don't understand what you mean. If the version of the schema file is compatible (and we know it is) there should be no warning. 
However as you described the situation can arise where the version is unknown to LuisReader but compatible. A priori thi is indistinguishable from the situation of an unknown version that isn't compatible. So I would cover the whole "unkown version" case with a warning.
