### ISSUE TITLE
Adapt docker files for new Rasa CLI and core merge

### ISSUE THREAD

**Issue by tmbo** [RasaHQ/rasa#1795]
The dockerfiles need some love on the master branch. They should use the rasa CLI to manage the data and project inside the container.

**Comment by wochinge** [comment]
We should also check whether all the libraries in `apt-get install` are

- actually needed

- can be deinstalled after the installation of Rasa (e.g. the dev packages)

**Comment by tmbo** [comment]
done, docks need an update though
