### ISSUE TITLE
Allow to train policy on actual user messages

### ISSUE THREAD

**Issue by tmbo** [RasaHQ/rasa#1980]
Right now the policy is trained on intents, the labels assigned to the incoming messages from NLU.

There are models we want to try out that would benefit from the additional information the whole message provides. The training data passed into the Rasa Core policy should contain the nlu user message.

**Comment by wochinge** [comment]
Closed in Rasa Open Source 2.2 with the introduction of [end-to-end](https://rasa.com/docs/rasa/stories#end-to-end-training)
