### ISSUE TITLE
Train rasa_core with dialogflow files

### ISSUE THREAD

**Issue by Priprocks** [RasaHQ/rasa#2152]
**Rasa Core version**:
0.9.a3
**Python version**: 
3.6
**Operating system** (windows, osx, ...):
Windows 10
**Issue**:
Is there any way I could use the dialogflow files to train the rasa_core dialog model as well?
I mean I am using these files to train the rasa_nlu model and it seems to work fine.

**Content of domain file** (if used & relevant):
```yaml

```

**Comment by akelad** [comment]
@Priprocks is this still something you're working on?
