### ISSUE TITLE
XMPP support

### ISSUE THREAD

**Issue by tigre-bleu** [RasaHQ/rasa#2171]
Currently there is facebook, slack, telegram, mattermost and twilio connections.

This is good, however lots of organisations also run XMPP servers. Do you plan to add such a channel?

**Comment by erohmensing** [comment]
At this point, it would be great for someone to create a connector for this, but would make more sense if it were implemented as its own library, instead of a new connector in the rasa repository.

**Comment by jehnes** [comment]
Funny that a framework for chat bots has all sorts of interfaces to different websites and apps but not for the standard messaging/chat protocol.
