### ISSUE TITLE
install_requires

### ISSUE THREAD

**Issue by dfee** [RasaHQ/rasa#2268]
**Rasa Core version**:
master

**Python version**: 
n/a

**Operating system** (windows, osx, ...):
n/a

**Issue**:
[`install_requires`](https://github.com/RasaHQ/rasa_core/blob/93101815832cc00dc81d71f6e9d5eccd7f96ca17/setup.py#L28) includes packages that really aren't (or shouldn't be) required. Consider using [`extras_require`](https://setuptools.readthedocs.io/en/latest/setuptools.html#declaring-extras-optional-features-with-their-own-dependencies).

E.g.
```
    'jsonpickle~=0.9.0',
    'six~=1.0',
    'redis~=2.0',
    'fakeredis~=0.10.0',  # what is this doing in here?
    'future~=0.16',
    'numpy~=1.13',
    'typing~=3.0',
    'requests~=2.15',
    'graphviz~=0.8.0',
    'keras~=2.0',
    'tensorflow>=1.7,<1.9',
    'h5py~=2.0',
    'apscheduler~=3.0',
    'tqdm~=4.0',
    'ConfigArgParse~=0.13.0',
    'networkx~=2.0',
    'fbmessenger~=5.0', # shouldn't be here
    'pykwalify<=1.6.0',
    'coloredlogs~=10.0', # (probably) shouldn't be here
    'ruamel.yaml~=0.15.0',
    'flask~=1.0', # (almost certainly) shouldn't be here
    'flask_cors~=3.0', # (alongside flask, probably...) shouldn't be here
    'scikit-learn~=0.19.0',
    'rasa_nlu~=0.12.0',
    'slackclient~=1.0', # shouldn't be here
    'python-telegram-bot~=10.0', # shouldn't be here
    'twilio~=6.0', # shouldn't be here
    'mattermostwrapper~=2.0', # shouldn't be here
    'colorhash~=1.0', # (probably) shouldn't be here
```

I know this is a critique of package architecture, but hopefully this is well received.

**Comment by akelad** [comment]
@tmbo is this still relevant?

**Comment by tmbo** [comment]
It is a very valid point, but it is a tradeoff: ease of use vs cleanliness. Given that the IO channel connector libraries (slack, facebook, mattermost, telagram) are rather lightweight I'd argue for ease of use atm. But certainly something we might need to rethink the more connectors there are.

**Comment by akelad** [comment]
ok will leave it open then
