### ISSUE TITLE
reminder's response messages don't show up when chatting with the bot on commandline

### ISSUE THREAD

**Issue by Ghostvv** [RasaHQ/rasa#2429]
**Rasa Core version**: `dispatcher`

**Python version**: `3.6`

**Operating system** (windows, osx, ...): `osx`

**Issue**:

when using reminders the response messages don't show up when chatting with the bot on commandline

**Content of domain file** (if used & relevant):
```yaml

```

**Comment by akelad** [comment]
@Ghostvv is this still relevant?

**Comment by Ghostvv** [comment]
yes I believe so

**Comment by akelad** [comment]
how about now @Ghostvv ?

**Comment by Ghostvv** [comment]
I think it is still relevant, but we can probably close the issue, @tmbo?

**Comment by akelad** [comment]
he's on holiday, so you'll need to decide :D

**Comment by Ghostvv** [comment]
just leave it open for now
