### ISSUE TITLE
Compound word entity handling

### ISSUE THREAD

**Issue by tmbo** [RasaHQ/rasa#267]
In wit.ai it is possible to annotate parts of words as an entity e.g. in the sentence: `I am looking for a cocktaildress` one could annotate `dress` as being some kind of `clothing`.

Although, this isn't as big of an issue with the english language, it becomes more interesting with german compounds.

**Comment by wrathagom** [comment]
@tmbo does the regex feature address this at all?

**Comment by malte-b** [comment]
Is this feature still being worked on? It would be really useful for my current project in german!

**Comment by ftyers** [comment]
This would also be useful for polysynthetic languages, like most indigenous languages of North America, which often have productive [incorporation](https://en.wikipedia.org/wiki/Incorporation_(linguistics)).

**Comment by akelad** [comment]
@tmbo do we think this is still relevant?

**Comment by tmbo** [comment]
Yes, I think this is still a relevant and possible improvement.

**Comment by wochinge** [comment]
@tabergma Is there a board for the research team?

**Comment by tabergma** [comment]
Yes, https://github.com/orgs/RasaHQ/projects/21

**Comment by ftyers** [comment]
I get a 404 on that.

**Comment by wochinge** [comment]
Sorry, that's a link to an internal project board @ftyers . That's why you get the 404 :-)
