### ISSUE TITLE
`categorical` slot should have category `other` so that other values could be mapped to it

### ISSUE THREAD

**Issue by Ghostvv** [RasaHQ/rasa#2674]
**Rasa Core version**: `master`

**Python version**: `0.3.6`

**Operating system** (windows, osx, ...): `macOS`

**Issue**:
Right now `categorical` slot requires to name its all possible values in domain.yml, though for practical reasons it is convenient to have general category like other, to which all values not mentioned in the list are mapped

**Content of domain file** (if used & relevant):
```yaml

```

**Comment by wochinge** [comment]
Makes sense to me 👍 Should we remove the `discussion` label?

**Comment by Ghostvv** [comment]
if it makes sense to do, then we can consider it to be discussed 😀

but then I would allow to create a slot with only one category, then effectively it'll become two categories due to addition of other

**Comment by melindaloubser1** [comment]
should there be any warning for values mapped to other? and what should happen if someone puts a literal "other" as a value in the domain?

**Comment by melindaloubser1** [comment]
@Ghostvv
