### ISSUE TITLE
Japanese Text with RASA (Mecab)

### ISSUE THREAD

**Issue by pbkh-pidor** [RasaHQ/rasa#2688]
**Rasa Core version**: 0.11.12

**Python version**: 2.7.0/3.6.0

**Operating system** : Ubuntu 16.04

**Issue**: Japanese Text with RASA (Mecab)

**Content of domain file** (if used & relevant):

###
I have try RASA for a while, I find out that it's amazing both NLU + Core, I proceed with some next steps such as other languages than space-separated ones. I selected Japanese which is alpha under alpha support from spacy and the Mecab lib seem to be enough for tokenization. 
I have investigated around, I know there is no easy way to work with it, I know it required some though work such as self-written custom component. I now, want to use it with Tensorflow backend. I also wonder beside tokenization stag, there's also tokenization in component: "intent_featurizer_count_vectors"

I find out that is no such a clear and working demonstration yet, so if anyone experience it.
Please discussion together, I really want to try it with Japanese Language

**Comment by nabito** [comment]
I'm having the same problem for other non-ascii language after successfully integrated custom component for tokenizer.

I suspect it would be this issue:
https://www.tensorflow.org/tutorials/representation/unicode

Need to dig deeper other day, let's solve this.

**Comment by mahbubcseju** [comment]
I have added a custom component using Mecab tokenizer. It works fine for me for Japanese text.

Link: [https://github.com/mahbubcseju/Rasa_Japanese](url)
