### ISSUE TITLE
Authentication for input channels

### ISSUE THREAD

**Issue by ErikTromp** [RasaHQ/rasa#2689]
**Rasa Core version**: 0.11.12

**Python version**: 3.6

**Operating system**: Windows/Ubuntu

**Issue**:
Hi, I am trying to get my rasa core to secure through JWT, but it doesn’t seem to work at all.

I am running rasa core as REST via: `python -m rasa_core.run --enable_api --credentials credentials.yml --jwt_secret thisismysecret -d models/dialogue -u models/nlu -o out.log`

Then I make a request without any JWT header: `curl -d '{"sender":"me", "message":"hi"}' -X POST -H "Content-Type: application/json" http://localhost:5005/webhooks/rest/webhook`

And I just get a response perfectly fine.

How can I enforce JWT? Using rasa-core 0.11.12

EDIT: So I realized the same holds for auth_token. Apparently the /conversations endpoints are protected, but the actual webhook is not. This makes little sense since /conversations manipulates state directly but of course the webhook does so as well but indirectly… Is this by design? How can I secure my rasa API?

**Comment by VasaviGunnam** [comment]
I'm also facing the same issue. I started the server using the following command 
rasa run \
    -m models \
    --enable-api \
    --log-file out.log \
    --auth-token thisismysecret
 and I'm getting the response without passing the token in the request. Is there any update regarding this issue?

**Comment by rabeenj007** [comment]
I am facing the same issue. Any update regarding the issue? Any alternatives to sort out the issues

**Comment by akelad** [comment]
@tmbo ?

**Comment by tmbo** [comment]
@VasaviGunnam  @rabeenj007 can you explain your use case a bit more detailed please? (this is not a bug but a new feature) I agree with you though that we need some sort of authentication for the webhook endpoints (the ones for the input channels). Which channel are you using and how are you connecting to the channel (e.g. from the browser, another server, ...)?

**Comment by jasonkuhrt** [comment]
For people in a position to easily put up small microservices quickly, the following might be an option whilst this issue gets hashed out:

We're in a situation where our custom channel connector (rest webhook) needs to receive data over a public network, but otherwise our Rasa API does not need to be public. In this scenario we're going to be putting up a microservice proxy ingesting this traffic, using our own auth mechanism, and forwarding over internal network to Rasa API.

**Comment by wochinge** [comment]
@jasonkuhrt Could you also put Rasa behind a Nginx which does the jwt validation and then forwards the requests?

**Comment by jasonkuhrt** [comment]
@wochinge we certainly could but we're in k8s environment and the easiest thing to get going for us was a new microservice.

**Comment by tmbo** [comment]
I don't think we should implement the authentication in Rasa directly - at least I don't see a general enough way to do it atm. I'd rather go for good documentation on a solution like the one suggested by @jasonkuhrt

**Comment by wochinge** [comment]
A general way would be to have different `Authenticator` implementations which could be specified in the `credentials.yml`. In each channel we could do sth like 

```
if self.authenticator:
   try: 
      valid_user = self.authenticator.validate(<whatever each channel decides>)
   except:
       # handle exception, e.g. if validate function does not accept the given paremeters
```

We could load the authenticator from strings as we do it with custom components. Users could then quickly plug in their own authenticator implementations

**Comment by jasonkuhrt** [comment]
I personally am not a fan of configuration-driven application development. Feedback (e.g. field typo) is generally non-existent (JSON Schema+vscode plugin can help with that) and developer dev tooling stack isn't leveraged (e.g. mypy).

I would expect to be able to simply register my own http middleware into rasa api using whatever framework its in play (sanic in this case I guess).

**Comment by wochinge** [comment]
> I personally am not a fan of configuration-driven application development insofar as its usually not executed well.

I can understand you, but that would be quite against the way we have done it for the other customizable components which is why I'd like to keep it consistent.

**Comment by tmbo** [comment]
I still don't think there is an easy win here and we should not add more authentication:
- the API can be secured using a token (at some point in the near future we should do this properly and use e.g. a JWT - in this case we could use different scopes for API and webhook, so you could issue JWTs which would only be valid for the chat webhook but not for API calls. I think this is the most flexible solution we can offer)
- if you need any more advanced outh you can always ship your own channel OR put a reverse proxy in front of the rasa server

I think the JWT solution is opinionated but would at least provide one easy way to use the authentication to secure the whole server without any reverse proxy.

**Comment by selvamshan** [comment]
JWT can be  implemented in rest customer connetor with PyJwt.  
```
@custom_webhook.route("/bot_auth", methods=["POST"])        
        async def auth_token(request: Request):                        
            if not request.json:
                return response.json({"error":"Missing sender"}, 400)
            
            sender_id = await self._extract_sender(request)
            utcnow = datetime.utcnow() + timedelta(seconds=-5)
            expires = utcnow + timedelta(hours=24)                     
            try:
                payload = {'iat': utcnow,'sender_id': sender_id, 'role':'user', 'exp':expires}
                bot_token = jwt.encode( payload,
                                    'thisismysecret', 
                                    algorithm='HS256').decode("utf-8")
            except Exception as e:
                return response.json({'error':str(e)}, 400)
```
decrator function required for authentication

**Comment by 1000sprites** [comment]
I'm also facing the same issue.

**Comment by quest4next** [comment]
> The `rasa` input channel (very similar to the `rest` input channel) uses JWT auth to secure the endpoint. Keep in mind though, that rasa core is not a chat server. E.g. if you run a web chat on your website you should use a proper webchat implementation and only forward the messages to rasa core on the backend.

@tmbo Hello Tom, could you suggest a good open source webchat implementation, if there are existing ones?

**Comment by vivek65k** [comment]
I passed everything but not working
rasa run \
    -m models \
    --enable-api \
    --log-file out.log \
    --auth-token thisismysecret\

**Comment by vatsal-mi** [comment]
I am using rasa 3.1, there is decode_jwt function we can use.
