### ISSUE TITLE
Add validation_split to embedding policy (same as in keras)

### ISSUE THREAD

**Issue by tmbo** [RasaHQ/rasa#2725]

**Comment by sibbsnb** [comment]
embedding policy uses tensorflow and way more complicated than the Keras policy. Do you think the policy will be better by adding the validation split?

**Comment by wochinge** [comment]
@Ghostvv is this done for the new embedding policy?

**Comment by Ghostvv** [comment]
yes that's actually implemented in `1.3` `EmbeddingPolicy`
