### ISSUE TITLE
Split long modules / Improve directory structure

### ISSUE THREAD

**Issue by wochinge** [RasaHQ/rasa#2811]
The project has some modules which are too long or have several classes in them which don't relate:

*   `rasa_core/actions/action.py`: 11 classes, > 490 lines
*   `rasa_core/events/.__init__.py`: 18 classes, > 950 lines
*   `rasa_core/utils.py`:4 classes, > 700 lines
*   `rasa_core/evaluate.py`: > 660 lines
*   `tests/test_policies`: > 600 lines

In case of the test modules it might also be worth to mirror the directory structure of the source code to ease finding tests.

**Comment by amn41** [comment]
@wochinge what's the status?

**Comment by wochinge** [comment]
Still has to be done. We made some progress for the `utils`, but not for the rest.

**Comment by MarthaDs** [comment]
There is someone on it? Can I work on it?

**Comment by wochinge** [comment]
@MarthaDs There is currently nobody working on it so it would be a great help if you could support us 🎉  One thing: I think it would be great if we could do this in small iterations, e.g. one PR per module split. This makes it easier to review and to give feedback on the changes.

**Comment by MarthaDs** [comment]
> @MarthaDs There is currently nobody working on it so it would be a great help if you could support us  One thing: I think it would be great if we could do this in small iterations, e.g. one PR per module split. This makes it easier to review and to give feedback on the changes.
Alright :)

**Comment by MarthaDs** [comment]
> @MarthaDs There is currently nobody working on it so it would be a great help if you could support us  One thing: I think it would be great if we could do this in small iterations, e.g. one PR per module split. This makes it easier to review and to give feedback on the changes.

Alright :)
