### ISSUE TITLE
Exporting interactive training session failes if intent 'None' appears during training

### ISSUE THREAD

**Issue by smn-snkl** [RasaHQ/rasa#2821]
**Rasa Core version**:
0.12.x
**Python version**: 
3.6
**Operating system** (windows, osx, ...):
ubuntu
**Issue**:
Exporting fails if e.g. during a FormAction you only provide an answer for a slot, without assigning the answer to an intent. In this case the story has an element like this:

> * shopping.add_items_to_wishlist
>     - form_shopping.search_items
>     - form{"name": "form_shopping.search_items"}
>     - slot{"requested_slot": "shopping.item"}
> * form: None

In that scenario, once you try to quit & export the execution crashes.

I think it should be either OK to not declare an intent or the user should be forced to do it. Otherwise it might crash after a long training session and you need to start all over.

**Comment by erohmensing** [comment]
Just ran into this issue, still relevant -- looks like we handled this by asking the user for the intent, but it still allows you not to input anything, which leads to the fail.
```
? Your input -> asdlfkj
The NLU classification for 'asdlfkj' returned 'None'
? What intent is it?  <create_new_intent>
? Please type the intent name:
? Please mark the entities using [value](type) notation asdlfkjasf
```
leads to same error traceback above.

**Comment by erohmensing** [comment]
@wochinge can we use the new validation method to make sure the user enters *anything* for the intent name?
