### ISSUE TITLE
Upgrading to py-redis 3

### ISSUE THREAD

**Issue by ThewBear** [RasaHQ/rasa#2865]
Any plan to upgrade `rasa_core` to `py-redis` 3 ?
I'm using `rq` and it conflicts with rasa.

**Comment by hsm207** [comment]
@akelad @tmbo can I work on this?

**Comment by akelad** [comment]
sure - @tmbo is this still valid?

**Comment by tmbo** [comment]
Yes still very relevant, would love to see a PR ⭐️

**Comment by hsm207** [comment]
@tmbo 

I have a couple of questions:

1. Is the package name really `py-redis` or is it `redis-py` ([website](https://github.com/andymccurdy/redis-py))?
2. The [requirements.txt](https://github.com/RasaHQ/rasa/blob/25abb47abb4e126f015f0dbba81ce9a4f0daf355/requirements.txt#L7) file on master has `redis==3.3.5`. Doesn't this fix this issue?

**Comment by hsm207** [comment]
@tmbo @akelad any thoughts on my previous comment?

**Comment by tmbo** [comment]
Sorry, I didn't check earlier. We are using the `redis` pypi package https://pypi.org/project/redis/ (so `redis-py`). The package is already updated to 3.x - I do not see anything else we need to do there :+1:

Thanks @hsm207 for looking into this and getting to a clarification.
