### ISSUE TITLE
FallbackPolicy should jump in when the top n intents have similar confidence

### ISSUE THREAD

**Issue by akelad** [RasaHQ/rasa#2899]
Right now it only jumps in if the NLU confidence is below a certain threshold. It should however also jump in if the top 2 intents have a confidence of 0.98 and 0.80 for example.
I've already started looking into this for the rasa-demo

**Comment by msamogh** [comment]
> That should also be applied to third highest confidence

@alan Doesn't simply checking if the top 2 confidences are close enough remove the need to look at the predictions at positions >2? I'm not sure I understand why the third highest confidence would be relevant here.

**Comment by msamogh** [comment]
> It should however also jump in if the top 2 intents have a confidence of 0.98 and 0.80 for example.

Also, won't the output from the intent classifiers always sum up to 1?

**Comment by msamogh** [comment]
cc @tmbo

**Comment by msamogh** [comment]
> So even if not using Core, still makes sense to configure that. Wdyt ?

@amn41 Since changing the metrics won't change the fact that you would still need some downstream logic to resolve it, I can't think of a good reason to include it as part of the NLU output.

**Comment by amn41** [comment]
my point was that instead of using the raw score produced by the model, we could have NLU report a confidence value that already takes this into account. But letting Core handle it is probably better  because otherwise the logic is a bit obscured.

**Comment by msamogh** [comment]
@alan Yeah, the metric would need to take into account both the absolute and the relative difference, and the only way to do that I can think of is to have them side-by-side, which would be messy.
