### ISSUE TITLE
Rasa "packs" a way to combine different bot parts to a combined bot 

### ISSUE THREAD

**Issue by tmbo** [RasaHQ/rasa#2916]
The idea is to make it possible to easily combine parts from different bots to create a new bot. A "part" (naming preliminary) would consist of:
- domain file
- nlu training data
- story file 

A bot can be trained based on multiple of these "parts", combining the different pieces in one trained model. If I remember correctly, merging of multiple nlu training data files is already implemented as well as combining story data files. The main work is combining domain files. 

Idea on how the skills could be structured:
```
# multiple skills
skills/
	restaurant_booking/
		stories.md
 		nlu.md
		domain.yml
	hotel_booking/
		stories.md
 		nlu.md
		domain.yml
        integration_stories.md
	integration_domain.yml
config.yml

# single skill
skills/
	nlu.md
	stories.md
	domain.yml
config.yml
```
Open question:
How to do conflict resolution (intents / entities / slots / actions of the same name).

**Comment by tmbo** [comment]
@lgrinberg these are some really good thoughts, thanks a lot for adding them. I think a first version implementation will just be merge and go with that (just pretending there are no conflicts, and if there are just merge the data). And then we can iterate from there to better handle the situations you described above :rocket:

**Comment by akelad** [comment]
@wochinge this is still somewhat relevant right?

**Comment by wochinge** [comment]
That's done in the experimental multi skill feature
