### ISSUE TITLE
Multiple channels per channel type 

### ISSUE THREAD

**Issue by wochinge** [RasaHQ/rasa#2927]
Currently it's not possible to serve multiple channels of the same type, e.g. it is not possible to provide two Slack credentials and thereby supply to Slack channels.

Ideally something like this should be possible:

<pre>slack:
 slack_token: "1234"
 slack_channel: "@my_channel"
 slack:
 slack_token: "5678"
 slack_channel: "@another_channel"</pre>

**Comment by wochinge** [comment]
@erohmensing You didn't do this, right?

**Comment by erohmensing** [comment]
no, not two channels at once. i think this would go into that question how the bot handles multiple users at once. as of my changes the slack channel posted to can be dynamic though, it's not restricted to that defined in credentials

**Comment by akelad** [comment]
so what happens with this issue? Maintenance?

**Comment by erohmensing** [comment]
@wochinge do you remember who was asking for this? the slack token isn't per channel so I don't think that would be the implementation to handle this, but i guess this is how we could handle multiple workspaces, not sure if we want to do that

**Comment by erohmensing** [comment]
well someone literally just asked for this: https://forum.rasa.com/t/setting-up-multiple-facebook-chatbots-pages/11844

**Comment by wochinge** [comment]
I put in maintenance. Could be a bit tricky if the same user is speaking to multiple bots. Probably some sender_id prefix would be required.

**Comment by tmbo** [comment]
I don't think this is a very common scenario and I doubt we should implement this right now. But if someone wants to do it, I'd rather use an array:
```
slack:
- slack_token: "1234"
  slack_channel: "@my_channel"
- slack_token: "5678"
  slack_channel: "@another_channel"
```

**Comment by cristianmtr** [comment]
My company would be very interested in this being supported. We have one Facebook app that we want to connect to multiple pages. 

We then want to use the `conversations/{{sender_id}}/execute` API to send custom messages to specific senders. However, in the handler we do not have access to the `sender_id` anymore. We need this in order to obtain the `page id` from our storage.

Having a list of subchannels per channel would be very handy :)

**Comment by wochinge** [comment]
Issue is up for grabs 👍🏻 
@TyDunn Are you okay with the format? Seems sensible to me.

**Comment by TyDunn** [comment]
Yep, it seems sensible to me too. This would be an awesome contribution, @ErickGiffoni and @jjuliolitwin!
