### ISSUE TITLE
Connector parameter overwrites credentials parameter.

### ISSUE THREAD

**Issue by wochinge** [RasaHQ/rasa#2929]
When running Rasa Core any connector specified with `-c` or `--connector` will overwrite anything specified with `--credentials`.

This is the location where it happens:
https://github.com/RasaHQ/rasa_core/blob/780bd4d115d3cb89f87c1b6732680572fe86c69d/rasa_core/run.py#L107

There should either be a warning or both configurations should be used.

**Comment by erohmensing** [comment]
closed in #3901, thanks @lmaczulajtys! Next time claim it on this board, just like you already did for the next one. 🙂
