### ISSUE TITLE
TwoStageFallbackPolicy: Treat affirmation response with low confidence as rephrasing

### ISSUE THREAD

**Issue by wochinge** [RasaHQ/rasa#2934]
If the user responds to the affirmation request with a message with low confidence, the twostagefallbackpolicy immediately does the "ultimate" fallback. Instead the user should get one more chance.

Current flow:

```
* intent with low confidence
  - affirmation_action
* intent with low confidence
  - action_default_fallback
```

Better would be: 
```
* intent with low confidence
  - affirmation_action
* intent with low confidence
  - affirmation_action
* intent with high confidence (revert and continue) / intent with low confidence (action default fallback)
```

**Comment by akelad** [comment]
hm, if this has been in the backlog since 25 june shouldn't someone have implemented it by now 😂it's not super urgent imo, so let's close it
