### ISSUE TITLE
update list of events in docs

### ISSUE THREAD

**Issue by wochinge** [RasaHQ/rasa#2962]
The list of events in [https://rasa.com/docs/core/master/api/events/](https://rasa.com/docs/core/master/api/events/) misses the events

*   StoryExported
*   Form
*   FormValidation
*   ActionExecutionRejected
*   [https://rasa.com/docs/core/master/api/events/#schedule-a-reminder](https://rasa.com/docs/core/master/api/events/#schedule-a-reminder) should have a lower case boolean value for `kill_on_user_msg`

**Comment by akelad** [comment]
@wochinge is that not more a user success thing?

**Comment by wochinge** [comment]
You're right. Still getting used to processes 💥

**Comment by wochinge** [comment]
@akelad Why is it removed from the user success board? Where should it go or should it be closed?

**Comment by akelad** [comment]
i don't know what happened there haha
