### ISSUE TITLE
Feature Request: Restoring Rasa core apscheduler functionality when upgrading code on a CI/CD pipeline

### ISSUE THREAD

**Issue by aanchan** [RasaHQ/rasa#2971]
Related to forum post : https://forum.rasa.com/t/restore-py-rasa-and-rasa-with-ci-cd/2977

What does the feature need to do?
Work with apscheduler and the redistracker store to seamlessly restore rasa core during a CI/CD deploy. So this would allow code updates to say actions.py and domain.yml, but allow the application to keep the existing reminders going. There is apparently an issue with the agent code that needs a fix for this to happen as commented by @tmbo on the forum post.

**Comment by cristianmtr** [comment]
Hey.

My company is trying to use reminders and we need them to persist across restarting / deploying of the bot itself.

Did I understand it correctly that this is currently not supported? Any updates? Any way we could achieve this? (It could also be a temporary solution/hack ;) )

**Comment by wochinge** [comment]
@tmbo

**Comment by tmbo** [comment]
Well, it is technically possible, you can use a persisted jobstore (https://apscheduler.readthedocs.io/en/latest/userguide.html#configuring-the-scheduler). The downside is, that for the reminder itself, even after a restart, the reminder will use the old agent.

**Comment by KaitCrawford** [comment]
Hi, has there been any movement on this or is there an updated workaround?
We're investigating using Rasa for a project that requires daily and monthly reminders so we really need them to be persistent.

**Comment by wochinge** [comment]
Mhm, I'd suggest to use an external component which then calls the Rasa Open Source to inform the user as described [here](https://rasa.com/docs/rasa/reaching-out-to-user#external-events). Also closing this issue as I think the thing which I just described is the preferred way to do so.
