### ISSUE TITLE
Add out of the box emoji handling

### ISSUE THREAD

**Issue by tooaverage** [RasaHQ/rasa#301]
I think it'd be be helpful to have basic emoji handling. And eventually understanding positive
 <g-emoji class="g-emoji" alias="smiley" fallback-src="https://github.githubassets.com/images/icons/emoji/unicode/1f603.png">
 😃 
 </g-emoji>/negative
 <g-emoji class="g-emoji" alias="rage" fallback-src="https://github.githubassets.com/images/icons/emoji/unicode/1f621.png">
 😡 
 </g-emoji>/neutral
 <g-emoji class="g-emoji" alias="poodle" fallback-src="https://github.githubassets.com/images/icons/emoji/unicode/1f429.png">
 🐩 
 </g-emoji> emoji.

Can assign to me 
 <g-emoji class="g-emoji" alias="innocent" fallback-src="https://github.githubassets.com/images/icons/emoji/unicode/1f607.png">
 😇 
 </g-emoji>

**Comment by tmbo** [comment]
@tooaverage yes that would be an awesome contribution 🎆 😃

**Comment by tooaverage** [comment]
Weo @tmbo What is the best/leanest way to integrate this?

**Comment by amn41** [comment]
one pretty lean solution would be to replace the emoji with words, for example taking the short name or keywords http://unicode.org/emoji/charts/full-emoji-list.html

**Comment by tmbo** [comment]
Best to probably add punctuation before and after as well? i think makes sense for most cases

**Comment by perezmunoz** [comment]
Hello @tooaverage, any update on this issue?

I trained the model using both unicode (\U0001f37a) and the actual emoji (🍺) within the training data, and set synonyms to map to my named entity. No success (tried just in case).

**Comment by nicksahler** [comment]
This project seems to have built a dictionary of vectors for emoji - 

is this useful? 

https://raw.githubusercontent.com/uclmr/emoji2vec/master/pre-trained/emoji2vec.txt

Is there a way I can assign these vectors to emoji tokens if they're found?

**Comment by amn41** [comment]
spacymoji would be helpful here: https://pypi.python.org/pypi/spacymoji/1.0.0

**Comment by giorgobiani** [comment]
Any progress on this? 😊

**Comment by tmbo** [comment]
We have not been working on this, but it would be a great contribution :wink:

**Comment by parthsharma1996** [comment]
Might be a little off-topic but how are emoji's handled currently by the NLU? I would like the include emojis in our current chatbot's training data. 

Are they currently simply ignored while predicting the intent?

**Comment by parthsharma1996** [comment]
@tmbo In the `tensorflow_embedding` pipeline my guess is that the vectors for the emojis should also be learned from the training data, since that pipeline learns the word embedding from only the training data anyway (thus able to handle OOV words). 
Guesses aside, would be interesting to know how actually happens though

**Comment by giorgobiani** [comment]
I tried with tensorflow_embedding but no luck so far

**Comment by akelad** [comment]
I think the tensorflow embedding policy also ignores them, because it only looks at words with a certain amount of characters. You can change that in the `token_pattern` parameter of the `intent_featurizer_count_vectors` though

**Comment by Ghostvv** [comment]
Yes, it depends whether a python string that stores emoji is falling under `token_pattern` or not

**Comment by kirtisynap19** [comment]
Hey @Ghostvv for now I am using token_pattern as "(?u)\b\w+\b" for words. However, I also want to add a capability to recognize emoji, what should be the token_pattern then? 
Secondly, what would the training data be like for emojis, "👍" or "U+1F44D"?

**Comment by Ghostvv** [comment]
@kirtisynap19 in this case token pattern should correspond to regex that also picks emojis

**Comment by kirtisynap19** [comment]
@Ghostvv thanks for your response. And what goes in the training data? Is it '👍' or 'U+1F44D' or 'u"\U0001F44D"'?

**Comment by Ghostvv** [comment]
@kirtisynap19 I'm not sure, try both. You can print vocabulary of CounntVectorizer to check

**Comment by mbslet** [comment]
Hi, this issue is available? @lucasdutraf, @Henrike100, and I to work on it! :)

**Comment by saikiran2603** [comment]
@mbslet Are you working on this change ? or is it okay if i pick it up ?

**Comment by chiranshu14** [comment]
Has there been any progress on this? Or should I just do rule-based intent classification for this? :)

**Comment by giorgobiani** [comment]
We've used pretrained emoji embeddings (emoji2vec) and wrote custom featurizer. After you just add it to your pipeline and provide relevant examples (as you do for the text). It also should be noted that it's better to do text preprocessing before featurizing it, because if you have something like "Hello there 😈😈😈" where text and emoji are mixed, the final classification result is not always good. So what we do for example, is that we strip emojis if they are with text and classify only text and if there's no text and only emojis, we classify emoji, which gives consistent results. Overall it may sound hard, but it's not, it's just a cycle of trial and error while you get the version that works for you best.

**Comment by mishra011** [comment]
> We've used pretrained emoji embeddings (emoji2vec) and wrote custom featurizer. After you just add it to your pipeline and provide relevant examples (as you do for the text). It also should be noted that it's better to do text preprocessing before featurizing it, because if you have something like "Hello there 😈😈😈" where text and emoji are mixed, the final classification result is not always good. So what we do for example, is that we strip emojis if they are with text and classify only text and if there's no text and only emojis, we classify emoji, which gives consistent results. Overall it may sound hard, but it's not, it's just a cycle of trial and error while you get the version that works for you best.

Please explain it with an example. That will be helpful. Thanks @giorgobiani
