### ISSUE TITLE
Profile imports

### ISSUE THREAD

**Issue by wochinge** [RasaHQ/rasa#3010]
Python 3.7 adds the option to [profile the import statements.](https://docs.python.org/3/using/cmdline.html#envvar-PYTHONPROFILEIMPORTTIME)
When Rasa Core is compatible with Python 3.7 this should be used to scope the imports and so improve the performance.

**Comment by federicotdn** [comment]
Are we interested in moving this into the Maintenance board?

**Comment by wochinge** [comment]
done @federicotdn

**Comment by federicotdn** [comment]
An interesting visualization of import times using [tuna](https://github.com/nschloe/tuna):
```bash
$ cd /to/the/rasa/repo
$ pip install tuna
$ python -X importtime -c 'import rasa' 2> imports.txt
$ tuna imports.txt
```

**Comment by wochinge** [comment]
Wow, that looks cool! Weird that `rasa.nlu.test` takes so much time / is loaded at all. I put the issue in the backlog, if you you want to work on it 🙂
