### ISSUE TITLE
Tracker gets very big for long conversations

### ISSUE THREAD

**Issue by wochinge** [RasaHQ/rasa#3011]
When a user conversation gets very long, the tracker will get huge and might slow down everything.
**Possible solutions**:
* implement some sort of session concept for the tracker
* only return the last `x` events

**Potential Difficulties**:
- we need at least `max_history` action events for the predictions, but there can be revert events in between, which requires us to pull more events from the database
- users might need more than `max_history` events in the action server to access certain information

Things do when tackling this issue:
- [ ] Creating an implementation proposal
- [ ] discuss the proposal
- [ ] implementation

**Comment by wochinge** [comment]
Also community members are facing this issue: https://forum.rasa.com/t/rasa-performance-for-increasingly-large-trackers/11126/2

Think we should deal with this in near future.

**Comment by lingvisa** [comment]
I want to added my exactly same issue here:

https://forum.rasa.com/t/my-bot-is-running-slow-very-quickly/13018

Rasa Team: it would be great if a solution can be implemented sooner for this and thanks.

**Comment by msamogh** [comment]
Related #3648

**Comment by GaoQ1** [comment]
@wochinge so how to solve this problem? i try to set max_event_history=100, but it will loss slot info when events length is higher 100. so i think we can save slot info in other store and meanwhile set max_event_history can reduce the huge of tracker.

**Comment by thepurpleowl** [comment]
Can we also look into this issue? This will happen even with max_history = 0, if there are a lot of checkpoints.

https://github.com/RasaHQ/rasa/issues/2765

**Comment by wochinge** [comment]
Sorry guys, we are currently discussing how to best solve this.

@thepurpleowl We highly recommend to not overuse checkpoints (https://rasa.com/docs/rasa/core/stories/#checkpoints). How many steps do your stories have that you run into this problem?

@GaoQ1 
Changing the `max_event_history` currently has no effect on the stored number of events in the tracker store, but only on the prediction itself.

**Comment by GaoQ1** [comment]
> Sorry guys, we are currently discussing how to best solve this.
> 
> @thepurpleowl We highly recommend to not overuse checkpoints (https://rasa.com/docs/rasa/core/stories/#checkpoints). How many steps do your stories have that you run into this problem?
> 
> @GaoQ1
> Changing the `max_event_history` currently has no effect on the stored number of events in the tracker store, but only on the prediction itself.

yes, the max_event_history has no effect on the events in the tracker store. but when events number exceeds the max_event_history, it will loss the previous events. that's a question.

**Comment by JialiuXu** [comment]
@wochinge I got the same problem, is there a solution now?

**Comment by wochinge** [comment]
> . but when events number exceeds the max_event_history, it will loss the previous events. that's a question

No, it won't lose this event. They are just not considered in the prediction anymore.

> @wochinge I got the same problem, is there a solution now?

We are working on a solution and will add this to one of the next minors (see the referenced PRs).
Out of curiosity: How many events are in your tracker?

**Comment by JialiuXu** [comment]
> > . but when events number exceeds the max_event_history, it will loss the previous events. that's a question
> 
> No, it won't lose this event. They are just not considered in the prediction anymore.
> 
> > @wochinge I got the same problem, is there a solution now?
> 
> We are working on a solution and will add this to one of the next minors (see the referenced PRs).
> Out of curiosity: How many events are in your tracker?
When I was running rasa locally, there are 374 events in total until the conversation finished. When I was running rasa in docker in production mode, I was using the same sender_id to test the bot, so the number of the events is up to more than 17000, about 400 for each conversation. The bot response really fast when I just start a new conversation (even if there are already 16000 events from the same sender_id), but become slower when the conversation goes deep, I am wondering what else I can do? Shoud I change the configuration of max_history for Keras and AugmentedMemoizationPolicy?

**Comment by wochinge** [comment]
@JialiuXu What's your current max_history?
As a workaround I'd not use the same sender_id for every test until we've released the session support.

**Comment by JialiuXu** [comment]
> @JialiuXu What's your current max_history?
> As a workaround I'd not use the same sender_id for every test until we've released the session support.

Thanks, my max_history is 3. I'll avoid using the same sender_id, but even if I run rasa locally using different sender_id the bot still get very slow

**Comment by wochinge** [comment]
This was implemented and released with Rasa 1.6. Please check the docs for it here: https://rasa.com/docs/rasa/core/domains/#session-configuration

**Comment by benos** [comment]
As I mentioned on https://github.com/RasaHQ/rasa/issues/4713 (probably the wrong ticket), I don't think this issue is fixed as far as the action server is concerned.

In the screenshot is the count of the events in the tracker sent to my action server (note that it is a custom one written in node.js and not the Python SDK). Within that sequence, multiple session restarts happen.

![image](https://user-images.githubusercontent.com/1001662/75166386-10c4e600-5724-11ea-982a-adb9252c2dad.png)

Not a massive expert on the RASA codebase, but it seems to me this is the guilty line in action.py:

![image](https://user-images.githubusercontent.com/1001662/75166435-233f1f80-5724-11ea-9877-7fce31e56f2a.png)

I think EventVerbosity.AFTER_RESTART would be the correct one.

Using RASA 1.7.0, in memory tracker and a custom action server.

**Comment by tangochris** [comment]
@wochinge I'd like to second @benos comments. We have a user with over 4000 events, even though session max is set at 720 minutes. Any time he uses the bot, Rasa completely freezes as it "Launches Delorean" for 90-120 seconds.

The issue was resolved in 1.6.0 and re-appeared in 1.7.0.

**Comment by tangochris** [comment]
![Screen Shot 2020-02-21 at 5 13 19 PM](https://user-images.githubusercontent.com/19203848/75169928-33cca700-56de-11ea-8b03-e9b9f42989d5.png)

**Comment by tangochris** [comment]
@wochinge @benos You know what, in our case, I think what I'm seeing is a different issue. Rasa is getting in a loop where it keeps on adding events without user intervention, so the session never ends. I believe it is isolated to the Facebook channel. We'll do more digging before opening a separate issue.

**Comment by wochinge** [comment]
Which tracker store are you using @tangochris ? It is very  unlikely that this is channel specific

**Comment by tangochris** [comment]
@wochinge Postgres. Yeah it's interesting. I see this one user's tracker go from nothing to 4500 events. Every minute or so, another 3 events are added. Attached screenshot is at 2 in the morning, when our team is sleeping (chatbot is in QA, planned launch March 15).

<img width="933" alt="Screen Shot 2020-02-24 at 9 55 15 AM" src="https://user-images.githubusercontent.com/19203848/75177975-04bd3200-56ec-11ea-804a-b37050ca86e5.png">

**Comment by tangochris** [comment]
@wochinge I'm seeing errors in facebook.py. See attached log. We modified it to handle buttons and quick replies more effectively, so it could be our error. Working on it...
[log-excerpt.log](https://github.com/RasaHQ/rasa/files/4246017/log-excerpt.log)

**Comment by wochinge** [comment]
@tangochris Seems something is going wrong with the lock store as well. Do you have any logs in redis? 

> Every minute or so, another 3 events are added. 

Are these added without you doing anything?

**Comment by tangochris** [comment]
@wochinge 

> Do you have any logs in redis?

No, just the startup logs. Otherwise it's empty.

>> Every minute or so, another 3 events are added.

> Are these added without you doing anything?

When the bot gets into a bad state, they are added without anyone doing anything. It's some sort of infinite loop.

> Seems something is going wrong with the lock store as well. 

When the bot is in a bad state, I see "Could not delete lock" messages. When the bot is functioning well, the lock store behaves normally.

Currently, our bot is functioning normally. We reduced session length from 720 to 60 minutes. We also upgraded to Rasa 1.7.4, which included a fix for #5068 — we are not sure if that issue is related.

**Comment by teremterem** [comment]
> As I mentioned on #4713 (probably the wrong ticket), I don't think this issue is fixed as far as the action server is concerned.
> 
> In the screenshot is the count of the events in the tracker sent to my action server (note that it is a custom one written in node.js and not the Python SDK). Within that sequence, multiple session restarts happen.
> 
> ![image](https://user-images.githubusercontent.com/1001662/75166386-10c4e600-5724-11ea-982a-adb9252c2dad.png)
> 
> Not a massive expert on the RASA codebase, but it seems to me this is the guilty line in action.py:
> 
> ![image](https://user-images.githubusercontent.com/1001662/75166435-233f1f80-5724-11ea-9877-7fce31e56f2a.png)
> 
> I think EventVerbosity.AFTER_RESTART would be the correct one.
> 
> Using RASA 1.7.0, in memory tracker and a custom action server.

I'm using Rasa X 0.41.1 and it seems to only send to action server events from the **two** latest sessions (the previous one and the current one). This seems to be a pretty smart way to handle the problem - action server is not overwhelmed with full history of events but still has access to events from the previous session if needed.

**Comment by wochinge** [comment]
> Not a massive expert on the RASA codebase, but it seems to me this is the guilty line in action.py:

The tracker should only contain data from the last 1 or 2 sessions. Hence, this line is okay. 

> When the bot gets into a bad state, they are added without anyone doing anything. It's some sort of infinite loop.

What do you mean by "bad state"?

**Comment by benos** [comment]
@teremterem @wochinge Any reason we are re-awakening an 18 month old thread?

**Comment by teremterem** [comment]
@benos It's always useful to share findings, even if the thread is old. This information may then be googled by someone later. This is why I chose to comment.
