### ISSUE TITLE
Interactive learning navigation documentation

### ISSUE THREAD

**Issue by Spenhouet** [RasaHQ/rasa#3029]
The current interactive learning navigation consists of the following options:

```
Do you want to stop?  (Use arrow keys)
   Continue
   Undo Last
   Fork
   Start Fresh
   Export & Quit
```

I couldn't find any documentation on any of these navigation options.
Some of these are intuitive (continue, undo last, export & quit).
But for others it is just not clear what choosing these options entails (Fork, Start Fresh).
From other issues here on GitHub I could gather what these options are supposed to do but **what I wish for is an addition to the documentation where all navigation options are described.**

For example:
- Start Fresh: Starts a new conversation and story. The last story will still be saved.

**Comment by Spenhouet** [comment]
This is still an issue

**Comment by akelad** [comment]
well, would you be willing to submit a PR for it?

**Comment by Spenhouet** [comment]
@akelad I did not planned to. Doesn't mean it is not an issue worth improving. Don't get me wrong but this is your product and not a community project. You are responsible to develop it. I'm just reporting flaws.

**Comment by akelad** [comment]
well, it is somewhat a community project in that we allow contributors to contribute. I was simply asking you whether you wanted to make a contribution

**Comment by Spenhouet** [comment]
@akelad Sorry for the misunderstanding. I thought you meant that either I'm resolving this issue or it is gonna be closed. Thanks for the clarification.
