### ISSUE TITLE
Interactive Learning: Return Type as JSON or Dictionary.

### ISSUE THREAD

**Issue by Aliyss** [RasaHQ/rasa#3049]
**Rasa Core version**:
0.13.3
**Python version**: 
3.6
**Operating system** (windows, osx, ...):
Windows
**Request**:
Returning Interactive Learning Values as a json or dictionary instead of handling questions and answers in the command line.

**General Idea**:
I want to give certain users the possibility to start the interactive learning process. for this to be used it would be quite handy to get the responses as a json or a dictionary from the questionary instead of having it run questions.ask() or questions.text(). This way front-end users have a possibility of training the bot.

**Comment by paulaWesselmann** [comment]
@akelad do you think this is a feature rasa should implement? I think it is a good idea to allow the user to run interactive learning through a channel.

**Comment by akelad** [comment]
running it through a front end is possible, not sure how easy it would be to do with a variety of channels. @ricwo maybe you can comment

**Comment by Aliyss** [comment]
Is this still open?

**Comment by amn41** [comment]
you can use [Rasa X](https://rasa.com/docs/rasa-x/) to do interactive learning via a GUI. If you want to implement your own version, the API endpoints are all documented [here](http://rasa.com/docs/rasa-x/api/rasa-x-http-api/)
