### ISSUE TITLE
Endpoint to retrieve the loaded config

### ISSUE THREAD

**Issue by huberrom** [RasaHQ/rasa#3055]
**Rasa Core version**: 0.13.2

Pretty sure there is no endpoint yet to get the policy, just like it used to have a /config endpoint for the NLU.

My usecase is that we are logging the confidence + intention to Rasa-ui, and with the current implementation there is no way for the user to know if the detected intent have a greater confidence than the threshold, or if it's a "miss match".

Did I miss a way to get this threshold, or is this something that you plan to implement ? If not, I'll look for an another solution, but it would be great.

Thank you !

**Comment by matthyk** [comment]
I would like to work on it. 
but I'm not sure I fully understand the proposal. The goal is to provide an endpoint where the currently configured policies can be retrieved?
