### ISSUE TITLE
Interactive learning Crashes with Reminders

### ISSUE THREAD

**Issue by tahamr83** [RasaHQ/rasa#3056]
**Rasa Core version**:
0.13.3
**Python version**: 
3.6.6
**Operating system** (windows, osx, ...):
Mac OS
**Issue**:
Interactive Learning crashes when a scheduled reminder is executed. After the reminder is executed and the user enters an utterance. After NLU validation the program crashes. Apparently it is unable to print the chat history table and _plot_trackers() after the reminder's execution. 

(I was able to almost bypass it by returning a '\n' string for _as_md_message() if parse data has a None for the 'text' field. But then the _plot_trackers() method crashed which I by passed by simply commenting out)

**Content of domain file** (if used & relevant):
```yaml

```

**Comment by tahamr83** [comment]
Any fix for this issue for Rasa 1.1.x ? 
@akelad @tmbo

**Comment by akelad** [comment]
not sure -- @tmbo ?

**Comment by tmbo** [comment]
We did not test this yet it might work but I suspect there is still an issue with this. @tahamr83 did you try it out, were there any issues?
