### ISSUE TITLE
Rasa API / CLI community feedback

### ISSUE THREAD

**Issue by wochinge** [RasaHQ/rasa#3069]
Hi there 🎉 

If you tried out the new Rasa API / CLI, please leave any feedback (bugs, suggestions) in this issue.

Thanks for your support!

**Comment by btotharye** [comment]
I'd probably add to the instructions the following:

```
python3 -m venv .venv
source .venv/bin/activate
pip3 install -r requirements.txt
```

Or something like this just to rule out any issues you might see from people with newer tensor flow libraries, etc.

**Comment by btotharye** [comment]
Everything went great with the test I like this a lot and the CLI is gonna make stuff super easy to get going without having to build the structure out.  I think I'd probably add a few more models in so you can have a real back and forth convo like how are you doing, I'm ok, great that's good to hear, goodbye kinda thing.  Other than that solid work!

**Comment by arthurTemporim** [comment]
Hello, guys, I tested the rasa stack and added my `jupyter-notebook` in my GitHub, you can read it [here](https://github.com/arthurTemporim/rasa_playground/blob/master/API.ipynb) I made some comments about it and in my jupyter has my reasoning I think it's a better way to understand how other people will use it.

summing up, I really liked the `rasa init` and the tests are important but it needs time to understand all the test output.

If have any other activity to do about it, please let me know.

**Comment by wochinge** [comment]
@arthurTemporim 
> I did not like the way that the tests outputs are given, it's hard to understand and find issues, maybe some green and red colors can make this easier. 

Awesome idea! We should definitely do that

> what means "Speak to separately trained models"?
The new commands put the core and nlu model in one tar-file, but we still want to be compatible with the old way (training core and nlu separately)

> I didn't find documentation about the rasa_core.test what is the difference between this command and Rasa e2e tests?

We will create some documentation on it as soon as we finalize the commands.  If you set the parameter `e2e=True` it's the same command as the end to end tests. We just wanted to make the API easier to use that's why it's `rasa.test(...)` and not `rasa.test.test(...)`

**Comment by arthurTemporim** [comment]
Awesome! This step with the Rasa API / CLI will make the chatbot development with Rasa much easier to beginners. It's clear that many changes have been done and it's clear too, the care with each piece of code, **congratulations**!

**Comment by wochinge** [comment]
We can close that, the goal of this issue was to iterate on the CLI before we publish Rasa 1.0, what's what happened
