### ISSUE TITLE
pull model from server

### ISSUE THREAD

**Issue by jeanveau** [RasaHQ/rasa#3086]
**Rasa Core version**:  0.13.2

**Python version**: 3.6

**Operating system** (windows, osx, ...): Ubuntu 16

**Issue**:

the method _pull_model_and_fingerprint return always a etag, even the last one is not changed.
```python
    if response.status_code in [204, 304]:
        logger.debug("Model server returned {} status code, indicating "
                     "that no new model is available. "
                     "Current fingerprint: {}"
                     "".format(response.status_code, fingerprint))
        return response.headers.get("ETag")
```

The returned etag will trigger the updating of agent later in _update_model_from_server:

```python
new_model_fingerprint = _pull_model_and_fingerprint(
        model_server, model_directory, agent.fingerprint)
    if new_model_fingerprint:
        domain_path = os.path.join(os.path.abspath(model_directory),
                                   "domain.yml")
        domain = Domain.load(domain_path)
        policy_ensemble = PolicyEnsemble.load(model_directory)
        agent.update_model(domain, policy_ensemble, new_model_fingerprint)
```

This will make an File not found error as no zipped model has been pulled from server, but `_update_model_from_server` tries to load the model in a non-existing tmp directory.

Or did I missed something ?

**Content of domain file** (if used & relevant):
```yaml

```

**Comment by ricwo** [comment]
thanks @jeanveau for raising these issues. both points you mentioned should be fixed. we need to 1. move the temp dir creation so that it's only executed when a new model is found, and 2. not return the `Etag` when no new model is returned. We'd of course welcome your contribution if you'd like to fix these issues

**Comment by akelad** [comment]
@jeanveau are you interested in submitting a PR for this?

**Comment by jeanveau** [comment]
> @jeanveau are you interested in submitting a PR for this?

Hi, sorry that I was on vocation last week, yes I'd like to fix this bug

**Comment by akelad** [comment]
sounds great :)

**Comment by jeanveau** [comment]
I just create a pull request to fix this bug, please check
