### ISSUE TITLE
Logging Error when non ascii character is used in intent name

### ISSUE THREAD

**Issue by varshakirani** [RasaHQ/rasa#3088]
--debug flag in rasa_core.run throws log `UnicodeEncodeError` for intent names having nonascii characters.

**Comment by akelad** [comment]
@erohmensing what's the status here?

**Comment by erohmensing** [comment]
Looks like the issue might be with `.format()` which we use... in all of our logging: https://stackoverflow.com/questions/27150858/print-succeeds-but-logging-module-throws-exception
not sure how to handle it in this case

**Comment by erohmensing** [comment]
Update, intent name isn't the issue, in an ascii codec environment I got the following with no error: 
```
2019-06-20 12:57:40 DEBUG    rasa.core.processor  - Received user message 'hi' with intent '{'name': 'greet\U0001f919', 'confidence': 0.9477102160453796}' and entities '[]'
```

**Comment by akelad** [comment]
closing then
