### ISSUE TITLE
Git clone takes too long

### ISSUE THREAD

**Issue by tabergma** [RasaHQ/rasa#3095]
`git clone` currently takes quite some time as it downloads over 700k objects. 

We need to figure out why it takes so long.

**Comment by akelad** [comment]
@tabergma still relevant right?

**Comment by tabergma** [comment]
Just tried it again: It took me roughly 3 minutes to clone. The number of objects was reduced to 288133. Before it was taking up to 30 minutes. If you agree, I guess we can close this.

**Comment by akelad** [comment]
ok then closing
