### ISSUE TITLE
Unable to save named_entity_extractor to the file

### ISSUE THREAD

**Issue by bofengshuimen77** [RasaHQ/rasa#3122]
mitie version: 0.7.0
when i was train nlu.model, i met a question as below:

 File "C:\Users\lenovo\Anaconda3\lib\site-packages\mitie\mitie.py", line 272, in save_to_disk
    raise Exception("Unable to save named_entity_extractor to the file " + to_default_str_type(filename));
Exception: Unable to save named_entity_extractor to the file C:\Users\lenovo\Desktop\平安实习\2019_3_15Rasa\rasa_law\models\current\nlu\entity_extrac
tor.dat

**Comment by akelad** [comment]
Please provide some more details, such as the full stack trace and what commands you're running etc

**Comment by bofengshuimen77** [comment]
Thank you for your response. When I try to put my python file in the full English path, the error is canceled. So the procedure maybe does not support the Chinese path.

**Comment by akelad** [comment]
hm yeah might be some parsing error -- whih NLU/Core versions are you using?

**Comment by bofengshuimen77** [comment]
Thank you for your reply. The version is as follows.
![rasa_version](https://user-images.githubusercontent.com/43233374/55207801-b15e0d80-5216-11e9-9f5e-04d5a0833233.PNG)

**Comment by akelad** [comment]
ok we'll look into this, thanks for letting us know!

**Comment by tmbo** [comment]
mhm this looks more like a mitie issue, does the directory ` C:\Users\lenovo\Desktop\平安实习\2019_3_15Rasa\rasa_law\models\current\nlu` exist?
