### ISSUE TITLE
Rasa core build broken on mybinder.org

### ISSUE THREAD

**Issue by betatim** [RasaHQ/rasa#3134]
Hey there 👋,

I am one of the devs of mybinder.org and while looking at our logs noticed that your rasa_core repository doesn't build any more. It seems to get a fair bit of traffic (I think you use it in the docs for the interactive code examples).

The error is:
```
  Could not find a version that satisfies the requirement tensorflow==1.12.0 (from -r binder/../requirements.txt (line 10)) (from versions: 1.13.0rc1, 1.13.0rc2, 1.13.1, 2.0.0a0)
No matching distribution found for tensorflow==1.12.0 (from -r binder/../requirements.txt (line 10))
```

The actual repo that is being built is `rasa_core` and it seems you are in the process of moving things so maybe this is already solved?

To see the build logs visit https://mybinder.org/v2/gh/rasahq/rasa_core/master or install [repo2docker](http://repo2docker.readthedocs.io/) locally (I find that easier for debugging) and run `repo2docker https://mybinder.org/v2/gh/rasahq/rasa_core/master`.

**Comment by akelad** [comment]
Thanks for raising this issue, @JustinaPetr  will get back to you about it soon.

**Comment by Ghostvv** [comment]
do you use python 3.7?

**Comment by JustinaPetr** [comment]
Hey @betatim. Thanks a lot for raising this. My first question is the same as @Ghostvv has - is mybinder by default now uses python 3.7 as an interpreter?

**Comment by JustinaPetr** [comment]
Oh, yes. Just checked that it's a python version issue - some dependencies don't run on python 3.7. We will add the necessary specs to run it on Python 3.6.

**Comment by betatim** [comment]
Yes we switched to Python 3.7 as default last weekend.

**Comment by betatim** [comment]
Do you plan on fixing the `rasa_core` repository? A lot of people are trying to launch it on mybinder.org but the build fails. This isn't a super experience for users and uses up resources on mybinder.org because `rasa_core` is quite popular so there are a lot of attempts to build the repo which all eventually fail.

If you don't plan on updating the repo, would you be Ok with us marking the repo as "banned"? Users would instantly see a note saying that they can't currently launch that repo.

**Comment by JustinaPetr** [comment]
Hey @benhoff. Yes, we definitely plan on fixing the repo. In fact, we already pushed the fix but seems like the issue still persists which we will fix ASAP.

**Comment by JustinaPetr** [comment]
@benhoff just a heads-up - the fix we pushed should now be effective on the main part of our docs (the one that gets the most traffic). However, since we use binder in more that one place on our docs, some parts are yet to be released for the fix to become effective.  This should be done throughout the upcoming week.

**Comment by betatim** [comment]
Do you mean to mentio nbenhoff or is he getting notifications and being very puzzled? :) Thanks for working on this and being a good neighbour 👍

**Comment by JustinaPetr** [comment]
Hi @betatim. I can see that the RasaHQ repository was banned for now. Yesterday we made a release which should fix the remaining issues with binder. Is there a way I can test that it's definitely the case?

**Comment by betatim** [comment]
You could try and build it locally with http://repo2docker.readthedocs.io/ which is the tool we use to build repos on mybinder.org. For example with `repo2docker https://github.com/rasahq/rasa`. Should eventually print a link you can copy&paste into your browser to see the notebook.

Ping me when things work again and we can unban it again.

**Comment by JustinaPetr** [comment]
@betatim Cool, thanks. So I tested the repo and everything should be back up again. Since we are using the latest release of our repo, https://github.com/rasahq/rasa_core branch 0.14.x should be built (I tested and it built successfully).

**Comment by betatim** [comment]
@JustinaPetr removed the ban :)

**Comment by akelad** [comment]
awesome thanks! will close this
