### ISSUE TITLE
Add training script options to NLU Docs

### ISSUE THREAD

**Issue by paulaWesselmann** [RasaHQ/rasa#3166]
This only exists for Core in the docs: https://rasa.com/docs/core/policies/#training-script-options

The commands can be found using:
`python -m rasa_nlu.train --help`

It might also be useful to find those things under the same search keywords. currently you find the paramters for `nlu.evaluate` under `evaluation parameters` and for `core.train` under `training script options`.

**Comment by erohmensing** [comment]
we should also add the output for `rasa_core.run` (probably just any command with lots of parameters tbh), would help avoid issues like #3198

**Comment by amn41** [comment]
now covered in the docs see e.g. https://rasa.com/docs/rasa/user-guide/command-line-interface/#train-a-model
