### ISSUE TITLE
cmd interface: train command should not fail if data folder contains more than train files

### ISSUE THREAD

**Issue by tabergma** [RasaHQ/rasa#3173]
Currently, the command line interface fails to train the `nlu` or `core` model, if the data folder contains more than the expected training file.

Example:
Data folder contains `stories.md` and `nlu.md` and you execute the command `rasa nlu train`. The execution will fail with the following error:
```
ValueError: Unknown data format for file data/stories.md
```
If you run `rasa core train`, the execution fails with
```
TypeError: expected str, bytes or os.PathLike object, not NoneType
```

Current solution:
The data folder should contain only the training file you need to train your model. E.g. if you want to run `rasa train nlu`, the data folder should just contain `nlu.md`.

What needs to be done:
Ignore files in the data folder if they are not in the expected format, so that you don't have to move files before training any model.

**Comment by tabergma** [comment]
@erohmensing Your comment https://github.com/RasaHQ/rasa/issues/3272#issuecomment-486993949 is a duplicate of this issue, I belief. I started looking into this today and it does not seem to be that trivial as you might think.
We already validate the training data when training an nlu model. This can be easily adapted to skip invalid files. However, for core models such a validation does not exist. And looking into the data, I'm also not sure, how you can say a `nlu.md` file is not a valid `stories.md` file as the syntax itself is valid. Do you have any ideas on how to recognize a `nlu.md` file when looking for `stories.md` files?

**Comment by erohmensing** [comment]
The reason it breaks on `train core` and `train nlu` but not `train` is because `train` always trains core and nlu in temporary directories in which it's only copied over the relevant files. Is there any reason we dont want to do this in core and nlu by default? I think this issue could be fixed in like 2 lines of code actually.

**Comment by tabergma** [comment]
Not that I'm aware of. But how would you detect "relevant" files? As the files are not always named `nlu.md` and `stories.md` you need to check the content to see, if this file is a valid training data file or not. But maybe I'm missing something... Please go ahead if you already have a simple solution in mind.

**Comment by erohmensing** [comment]
the logic is already there because `rasa train` does it -- it basically pulls training data files, checks which are nlu, and then puts what's left in stories. check out my branch 
https://github.com/RasaHQ/rasa/tree/data-files
