### ISSUE TITLE
Make form information easier to find

### ISSUE THREAD

**Issue by erohmensing** [RasaHQ/rasa#3185]
like @paulaWesselmann said, we should be able to find information about forms without having to search `formaction`. Since the `Slot Filling` page is almost all about forms, I'd suggest renaming this `Forms` or `Using Forms`. The `Using Slots` page should link to the form page as another method by which slots are set (under `Slots set by Actions`), and the `Interactive Learning with Forms` link should be `Form Basics`, not `Basics`.

**Comment by paulaWesselmann** [comment]
The only change that still needs to be addressed in the current docs is:
>The Using Slots page should link to the form page as another method by which slots are set (under Slots set by Actions)
