### ISSUE TITLE
embedding policy showing warnings without reason

### ISSUE THREAD

**Issue by SILENTVOICE976** [RasaHQ/rasa#3190]
![issue embedding](https://user-images.githubusercontent.com/47219855/55353651-7e02d380-54e1-11e9-9fde-096fc940f060.PNG)

embedding policy throw warning like this. but when i train  the same data,domain using keras policy everything runs as expected why is this?

![issue](https://user-images.githubusercontent.com/47219855/55353748-b86c7080-54e1-11e9-8582-c3cf41c1ba30.PNG)

**Comment by akelad** [comment]
Thanks for raising this issue, @Ghostvv  will get back to you about it soon.

**Comment by Ghostvv** [comment]
Thanks for spotting it, there is a bug in `LabelTokenizerSingleStateFeaturizer`, it doesn't take form features into account here: https://github.com/RasaHQ/rasa_nlu/blob/6a1afe1f4a67426224e7b5ce033c99f31c2bb7dc/rasa/core/featurizers.py#L229
