### ISSUE TITLE
Proposal: Using a tracker to start interactive learning at a certain point

### ISSUE THREAD

**Issue by tahamr83** [RasaHQ/rasa#3197]
Testing and creating stories for long conversations can be tedious using interactive learning if the you want to create several paths that fork from a particular point of a long conversation. After importing stories you have to recreate the dialogue state every time to get it at a certain point.

I propose to enhance the interactive learning that starts from a specific point in a conversation using a persisted tracker.

**Comment by akelad** [comment]
Thanks for raising this issue, @tmbo  will get back to you about it soon.

**Comment by tmbo** [comment]
I like that idea. Helpful for me to understand the workflow: where would you get that tracker from?

**Comment by tahamr83** [comment]
So one thing that we do is create a tracker file when we export the stories using interactive learning. We save these files and name it accordingly. Then depending on the use case we pass an optional "tracker" file name parameter to interactive learning. Using the `replace_events` method to  recreate the state of the tracker. We then fork from our desired conversation state. This method of creating trackers I think cleanly integrates with this feature.

We can also recreate trackers using the e2e story format using methods from `evaluate.py` module.

Let us know you thoughts.

**Comment by lgrinberg** [comment]
I have made a script based on eavluate.py that creates a tracker out of a story file in e2e format, based on tahamr83's suggestion, and stores it in a file as a python object using pickle.    That part is not difficult.  The question is what is the best way of getting that information into the agent and MessageProcessor?

**Comment by tahamr83** [comment]
@lgrinberg that part in my opinion is part of the problem where we want to start an actual conversation at a particular state. The use-case for this is mostly falls when were are testing the bot, right?. The proposal of this issue is mainly concerned for interactive training. We already have changes for interactive script. They are quite minimal and do not require any changes to message processor or the Agent. 
However for the problem of starting an actual 'conversation' using a tracker state, you are right we will need to somehow get that information to the Agent or MessageProcessor class. I am not sure but #3199 issue when resolved could be the solution. We could have the tracker state as a metadata field in the UserMessage class and use that field accordingly in `handle_message(self, message: UserMessage)`. But that's just a preliminary hunch from my side.

**Comment by antoniotoineto** [comment]
Hey guys, I was taking a look at this issue and I considering it in some level of state and maybe **it can be closed**!

If we take a look at the `rasa/shared/core/trackers.py` file we can see that there is a development envolving the tracker commented in this issue.

<img src='https://user-images.githubusercontent.com/54555684/215674074-f57111bd-7743-47f1-9985-72fc368f9780.png' width=600 />

The `rasa/core/action.py` file uses the _DialogueStateTracker_ class from `trackers.py` file to maintain the state of a conversation.

<img src='https://user-images.githubusercontent.com/54555684/215674936-98527cab-ba40-4967-848d-4805327fa2b4.png' width=600 />
 
The _DialogueStateTracker_ is used in several parts in the action.py classes to set the tracker state.

<img src='https://user-images.githubusercontent.com/54555684/215675583-8841dc63-a0e9-43ab-b6a6-b4271645c7a3.png' width=600 />
