### ISSUE TITLE
add metadata field to user message

### ISSUE THREAD

**Issue by wochinge** [RasaHQ/rasa#3199]
We should a metadata field to the user message class so that you can add custom information (tokens, user info) to the user message in the input channel and use it in custom actions.

- [x] Add field in UserMessage class
- [x] Make sure it does not get dropped on the way to the action server
- [ ] Optional: Create some functions to get it on the action server

**Comment by mounabenayed** [comment]
Yes I am blocked right now because my external Api call in my custom action needs an access token for every user so this field may be a solution.

**Comment by tahamr83** [comment]
You can set an unfeaturized slot at the start by calling the core's event http endpoint (conversations/<sender_id>/tracker/events)

**Comment by wochinge** [comment]
I think we should add this to the `UserUttered` event data as well (and make sure the `message_id` is also considered in the `as_dict` )

**Comment by wochinge** [comment]
@arthurTemporim To make sure that the event actually goes to the action server you have to include in the `UserUttered` event data
