### ISSUE TITLE
Cross validation endpoint implementation

### ISSUE THREAD

**Issue by sorayabh** [RasaHQ/rasa#3226]
**Rasa version**: 0.15.0a1

**Python version**: 3.6

**Operating system** (windows, osx, ...): osx

**Issue**: Enhancement : Cross validation endpoint implementation
I didn't find how to run cross validation directly through the server router API. If you think that this feature should be implemented, I would be happy to contribute.

**Content of configuration file (config.yml)**:
```yml

```

**Content of domain file (domain.yml)** (if used & relevant):
```yaml

```

**Comment by akelad** [comment]
Thanks for raising this issue, @ricwo  will get back to you about it soon.

**Comment by ricwo** [comment]
Hi @sorayabh, thanks for bringing this up. Adding cross-validation capabilities to the existing `/intentEvaluation` would be a nice addition. Looking forward to your contribution!

**Comment by wochinge** [comment]
closed by #7408
