### ISSUE TITLE
Dockerfile executes rasa core by default

### ISSUE THREAD

**Issue by souvikg10** [RasaHQ/rasa#3229]
**Rasa version**: latest

**Python version**: 3.6

**Operating system** (windows, osx, ...): osx

**Issue**:
Linking the forum discussion - https://forum.rasa.com/t/training-an-assistant-in-portuguese-rasa-nlu-not-running-with-docker/6792/4 

It seems that the default command for rasa nlu docker image is start which executes entrypoint.sh where the command shows ```exec python3 -m rasa.core.run --enable_api "${@:2}"```

is it intentional? because then the docker image has a dependency on rasa core for rasa nlu image?

**Comment by akelad** [comment]
@tmbo have we updated our docker files yet?

**Comment by tmbo** [comment]
Yes, but they need some more work. This should only happen for the published container labelled with `latest`, all other containers should be working fine. @souvikg10 which one are you using?

**Comment by souvikg10** [comment]
It is linked to the latest. But shouldn’t the default command of a Rasa nlu container be linked to executing Rasa nlu only?

**Comment by tmbo** [comment]
yes and no - we merged the core code into this repo (we'll also rename it soon) so there is only a stack container (no separate core / nlu ones).

We didn't update the dockerfile yet though, it should rather use the command line interface and start the server @tabergma is currently working on (a combined core / nlu webserver)

**Comment by souvikg10** [comment]
Interesting. I need to follow suit. I’m starting up a new project soon on my own and perhaps I should take note of this :D I think the idea of spinning one container for both as a starter sounds great. But perhaps it needs to be elaborated in the docs as well, which tag can start which kind of container
