### ISSUE TITLE
Docs on Rasa Core SDK

### ISSUE THREAD

**Issue by wochinge** [RasaHQ/rasa#3242]
The docs on the usage of the rasa_core_sdk are very sparse.
We should include examples for
  * using different event types (the event docs are all for rasa core which confuses more than it helps)
* accessing the raw event list
* accessing the intent names / action domains
* accessing the domain file

**Comment by erohmensing** [comment]
lol https://rasa.com/docs/action-server

**Comment by wochinge** [comment]
1.5 years later 🙈  Great that we finally tackled this boy

**Comment by erohmensing** [comment]
hahahhaa, and it still needs more work tbh! though Nikolai did add a page on this at one point at least :)
