### ISSUE TITLE
Minor issues with interactive mode on Docker

### ISSUE THREAD

**Issue by ortsaCniveK** [RasaHQ/rasa#3245]
**Rasa Core version**: 0.13.7 (from `rasa/rasa_core:stable`)

**Rasa NLU version**: 0.15.0a4 (from `rasa/rasa_nlu:stable-full`)

**Python version**: 3.6

**Operating system** (windows, osx, ...): Docker image

**Issues**:

I've been able to get interactive mode set up with Docker-compose and persisting data (see below), just have a few things I ran into that might help those who want to develop with Docker images in the future.

1. Interactive mode will fail to persist data if `data/nlu.md` does not exist.  It will prompt the user to retry with `data/nlu_interactive.md` and succeed.  Not sure if that's intended behavior.

2. Interactive mode does not exit out of the container after persisting data.  After running the below docker-compose command to run interactive mode, it will persist data and provide messaging (see below), then just leave terminal open -- is there an exit code being returned, or is it something wrong with the way I'm using interactive mode using docker?

3. Interactive mode also doesn't seem to respect the output path provided to it despite passing something other than `-o data` -- it will still try and save the data to `data/stories.md` or `data/nlu.md` (or in my case `data/nlu_interactive.md`), and if provided a different path, will throw a `FileNotFoundError`.

### Sample Output from interactive mode

```
? Do you want to stop?  Export & Quit                                                                                                                 
? Export stories to (if file exists, this will append the stories) data/stories.md                                                                    
? Export NLU data to (if file exists, this will merge learned data with previous training examples) data/nlu.md                                       
? Export domain file to (if file exists, this will be overwritten) domain.yml                                                                         
2019-04-11 23:07:54 ERROR    rasa_core.training.interactive  - An exception occurred while trying to load the NLU data.
Traceback (most recent call last):
  File "/app/rasa_core/training/interactive.py", line 725, in _write_nlu_to_file
    previous_examples = load_data(export_nlu_path)
  File "/usr/local/lib/python3.6/site-packages/rasa_nlu/training_data/loading.py", line 54, in load_data
    files = utils.list_files(resource_name)
  File "/usr/local/lib/python3.6/site-packages/rasa_nlu/utils/__init__.py", line 117, in list_files
    return [fn for fn in list_directory(path) if os.path.isfile(fn)]
  File "/usr/local/lib/python3.6/site-packages/rasa_nlu/utils/__init__.py", line 108, in list_directory
    "".format(os.path.abspath(path)))
ValueError: Could not locate the resource '/app/data/nlu.md'.
? Could not load existing NLU data, please specify where to store NLU data learned in this session (this will overwrite any existing file). Could not 
locate the resource '/app/data/nlu.md'. data/nlu_interactive.md                                                                                       
2019-04-11 23:08:00 INFO     rasa_nlu.training_data.training_data  - Training data stats: 
        - intent examples: 0 (0 distinct intents)
        - Found intents: 
        - entity examples: 0 (0 distinct entities)
        - found entities: 

2019-04-11 23:08:00 INFO     rasa_nlu.training_data.training_data  - Training data stats: 
        - intent examples: 0 (0 distinct intents)
        - Found intents: 
        - entity examples: 0 (0 distinct entities)
        - found entities: 

2019-04-11 23:08:00 INFO     rasa_nlu.training_data.training_data  - Training data stats: 
        - intent examples: 0 (0 distinct intents)
        - Found intents: 
        - entity examples: 0 (0 distinct entities)
        - found entities: 

2019-04-11 23:08:00 INFO     rasa_core.training.interactive  - Successfully wrote stories and NLU data
```

### Docker-compose contents:

```yaml
version: '3.0'

services:
  rasa-core:
    image: rasa/rasa_core:stable # avoiding using latest for dev
    ports:
      - "5005:5005"
    networks: ['rasa-network']
    volumes:
      - ./data/stories:/app/stories
      - ./models/rasa_core:/app/model
      - ./config:/app/config
      - ./logs/core:/app/logs
      - ./data/interactive:/app/data
      - ./:/app/project
    command:
      - start
      - --core
      - model
      - -c
      - rest
      - --endpoints
      - config/endpoints.yml
      - -u
      - local/
      - -o
      - /app/logs/server.log
      - -vv
    depends_on:
      - rasa-nlu
      - action-server
  rasa-nlu:
    image: rasa/rasa_nlu:stable-full # avoiding using latest for dev
    volumes:
      - ./models/rasa_nlu:/app/models/
      - ./logs/nlu:/app/logs
      - ./config:/app/config
      - ./:/app/project
    ports:
      - "5000:5000"
    networks: ['rasa-network']
    command:
      - start
      - --path
      - models
      - --response_log
      - logs/
      - -v
  action-server:
    image: rasa/rasa_core_sdk:latest # have to use latest b/c no stable tag
    volumes:
      - ./actions:/app/actions
    ports:
      - "5055:5055"
    networks: ['rasa-network']
    command:
      - start
      - --actions
      - actions

networks: {rasa-network: {}}
```

### Interactive mode command with Docker-compose:

```sh
docker-compose run --rm --service-ports \
  rasa-core run \
  python -m rasa_core.train interactive \
    --core model/local \
    -o data \
    --nlu local/ \
    --endpoints config/endpoints.yml
```

**Comment by akelad** [comment]
Thanks for raising this issue, @wochinge  will get back to you about it soon.

**Comment by wochinge** [comment]
> interactive mode will fail to persist data if data/nlu.md does not exist. It will prompt the user to retry with data/nlu_interactive.md and succeed. Not sure if that's intended behavior.

The idea is that we want to avoid overwritting any existing data. That's why we store in `data/nlu_interactive.md`. So it's actually intended 👍 What would your expected behavior be?

> Interactive mode does not exit out of the container after persisting data. After running the below docker-compose command to run interactive mode, it will persist data and provide messaging (see below), then just leave terminal open -- is there an exit code being returned, or is it something wrong with the way I'm using interactive mode using docker?

In version `0.13.x` it runs forever by default: https://github.com/RasaHQ/rasa_core/blob/85f59f3a645750f67a4a231dd422de1d0a2766f3/rasa_core/training/interactive.py#L1292 . this behavior is changed on current master (please don't try the latest master, it's currently very alpha)

> Interactive mode also doesn't seem to respect the output path provided to it despite passing something other than -o data -- it will still try and save the data to data/stories.md or data/nlu.md (or in my case data/nlu_interactive.md), and if provided a different path, will throw a FileNotFoundError

The output paths for the interactive learning cannot be passed through the cli at the moment, there is currently a PR to change that.

**Comment by ortsaCniveK** [comment]
Well I was thinking that if `data/nlu.md` doesn't exist, creating the file wouldn't be bad, since there's nothing to overwrite 😉.  But the below could be avoided as well once #2741 PR is merged, since Rasa will look in the output path for `nlu.md`.

```
ValueError: Could not locate the resource '/app/data/nlu.md'.
? Could not load existing NLU data, please specify where to store NLU data learned in this session (this will overwrite any existing file). Could not 
locate the resource '/app/data/nlu.md'. data/nlu_interactive.md
```

Good to hear that it's just a 0.13.x issue for not closing out of, excited to migrate to 0.14.x once you get to stable release, and the other issue I had run into already has a PR open for it.

I think since most of this has already been encountered and is actively being worked on, I'll just close the issue.  I may come back to this to update the docs with a small walkthrough on setting up interactive mode through Rasa, but I'll need to check the changes in 0.14 to make sure things will continue to work.  Thanks again @wochinge!
