### ISSUE TITLE
update example bots' makefiles

### ISSUE THREAD

**Issue by erohmensing** [RasaHQ/rasa#3251]
the makefiles of the bots don't work after a recent merge, the one that leads to this error:
```
RuntimeError: Calling `rasa.nlu.train` directly is no longer supported. Please use `rasa train nlu` instead.
```
The way I see it, we have two options:
1. update the makefiles to, for example, change `rasa.nlu.train` to `rasa train nlu`, with the relevant updated parameters
2. make sure all of the relevant files (domain, config, etc.) are in the default locations, get rid of makefiles and write in the docs about how to use these example bots, i.e. they would be used directly with the `rasa train nlu` type commands instead of the makefiles. the idea with putting everything in the default spot is to make it as easy as possible for users to use the example bots, similar to why the makefiles existed.

I think option 2 would be great, since it would get people to interact with the example bots in the same way that they (probably) interact with their own bots -- directly through the CLI.

**Comment by tabergma** [comment]
closed via https://github.com/RasaHQ/rasa/pull/3257
