### ISSUE TITLE
Remove codestyle check

### ISSUE THREAD

**Issue by tabergma** [RasaHQ/rasa#3256]
As we recently introduced black (see https://github.com/RasaHQ/rasa_nlu/issues/3205), we can safely remove `codestyle`. black reformats the code in a way that almost every pep8 rule is followed. 

- [ ] Remove travis stage
- [ ] Remove `codestyle` parameter in `setup.cfg`

**Comment by tmbo** [comment]
I think we already did this, right?

**Comment by tabergma** [comment]
yes, looks like it
