### ISSUE TITLE
Interactive Learning becomes quite slow for large conversations

### ISSUE THREAD

**Issue by tahamr83** [RasaHQ/rasa#3260]
**Rasa version**:
Latest
**Python version**: 
3.6.5
**Operating system** (windows, osx, ...):
MacOS
**Issue**:

Interactive learning becomes quite slow for large conversations. I think this is particularly due to the huge amount of chat history that has to be printed on the console. There could be an option to print only a certain amount of previous messages with an option/key binding to print the complete chat history.

**Comment by akelad** [comment]
Thanks for raising this issue, @tmbo  will get back to you about it soon.

**Comment by tmbo** [comment]
Yes I agree, I don't think it is necessary to print the whole history. Do you want to create a PR?

**Comment by tahamr83** [comment]
Sure I can work on it :)
