### ISSUE TITLE
SQL Tracker Store credentials

### ISSUE THREAD

**Issue by Robertjbc** [RasaHQ/rasa#3262]
**core=0.14.0a1
    nlu= 0.15.0a4**:

**3.6.5**: 

**windows10** 

**Issue**: hello rasa friend i have a issue for how to work the tracker store 
i´ll see what this version of rasa core supports SQL database and i don´t know how to connect 
anyone know, i´ll put al the tracker store credentials in the endpoints.yml but i have no answers

**Comment by akelad** [comment]
Thanks for raising this issue, @wochinge  will get back to you about it soon.

**Comment by wochinge** [comment]
Can you share your endpoints.yml with us?

**Comment by Robertjbc** [comment]
`tracker_store:
    type: SQL
    dialect: "sqlite"  # the dialect used to interact with the db
    url: "localhost"  # (optional) host of the sql db
    db: "rasa.db"  # path to your db
    username:  # username used for authentication
    password:  # password used for authentication`

thanks for answering, the other issue i have is: there is a posibilty to extract entities for this method and what are the step to follow

regards

**Comment by wochinge** [comment]
If you have another issue, please create another issue. If it's a question please check out our forum: https://forum.rasa.com.

What exactly is your error message?

**Comment by Robertjbc** [comment]
i not have error message, the bot run normally the only thing is the tracker don´t  save the
 flow that should keep, 

so i´ll suposse what i put something wrong in the endpoints.yml

**Comment by wochinge** [comment]
Should be clear now with the new Rasa 1.0 docs
