### ISSUE TITLE
i add the jieba's stopword,It might work.

### ISSUE THREAD

**Issue by zhangyanbo2007** [RasaHQ/rasa#3263]
**Rasa version**:0.14.4

**Python version**: 3.6

**Operating system** (windows, osx, ...):ubuntu 16.04

**Issue**:
i add the jieba's stopword,It might work.
[jieba_tokenizer.zip](https://github.com/RasaHQ/rasa_nlu/files/3082736/jieba_tokenizer.zip)
it look like this
`   

    provides = ["tokens"]

    language_list = ["zh"]

    defaults = {
        "dictionary_path": None,  # default don't load custom dictionary
        "stopword_path": None  # default don't load custom stopword
    }

`
the pipeline like this:
**Content of configuration file (config.yml)**:
language: "zh"

pipeline:
- name: "tokenizer_jieba"
  dictionary_path: "data/dictionary"
  stopword_path: "data/stopword"
- name: "ner_crf"
- name: "ner_synonyms"
- name: "intent_featurizer_count_vectors"
  OOV_token: oov
  token_pattern: '(?u)\b\w+\b'
- name: "intent_classifier_tensorflow_embedding"
```yml

```

**Content of domain file (domain.yml)** (if used & relevant):
```yaml

```

**Comment by akelad** [comment]
Not sure I understand what the issue is, could you explain a bit more?
