### ISSUE TITLE
Adding delays between multiple actions of a story

### ISSUE THREAD

**Issue by gunagg** [RasaHQ/rasa#3269]
rasa-core           0.13.7   
rasa-core-sdk       0.12.2   
rasa-nlu            0.14.6 

**Python version**: 3.6

**Operating system** (windows, osx, ...): osx

**Issue**: My story has multiple actions and I want to add delay in between the execution of the actions such that my system is not stalled. Adding a delay in the first action could be a solution, but in that case I want to stop sending BOT response if I get a message from the user.

**Content of configuration file (config.yml)**:
```
import os

policy_model_dir = os.environ.get("POLICY_MODEL_DIR", "models/dialogue/")

rasa_nlu_config = os.environ.get("RASA_NLU_CONFIG", "nlu_config.yml")

account_sid = os.environ.get("ACCOUNT_SID", "")

auth_token = os.environ.get("AUTH_TOKEN", "")

twilio_number = os.environ.get("TWILIO_NUMBER", "")

platform_api = os.environ.get("RASA_API_ENDPOINT_URL", "")

self_port = int(os.environ.get("SELF_PORT", "5001"))

core_model_dir = os.environ.get("CORE_MODEL_DIR", "models/dialogue/")

remote_core_endpoint = os.environ.get("RASA_REMOTE_CORE_ENDPOINT_URL", "")

rasa_core_token = os.environ.get("RASA_CORE_TOKEN", "")

mailchimp_api_key = os.environ.get("MAILCHIMP_API_KEY", "")

mailchimp_list = os.environ.get("MAILCHIMP_LIST", "")

gdrive_credentials = os.environ.get("GDRIVE_CREDENTIALS", "")

access_token = os.environ.get("TELEGRAM_TOKEN", "")

verify = os.environ.get("TELEGRAM_VERIFY", "rasas_bot")

webhook_url = os.environ.get("WEBHOOK_URL",
                             "https://website-demo.rasa.com/webhook")

rasa_platform_token = os.environ.get("RASA_PLATFORM_TOKEN", "")

rasa_nlg_endpoint = os.environ.get("RASA_NLG_ENDPOINT_URL", "")


```

**Comment by akelad** [comment]
Thanks for raising this issue, @MetcalfeTom  will get back to you about it soon.

**Comment by MetcalfeTom** [comment]
Hi @gunagg, what do you mean by "stalling"?  Are you calling endpoints with your actions?  A better option there would be to use [Python's in-built library ayncio](https://docs.python.org/3/library/asyncio.html)

To answer your question, the bot doesn't respond to any user messages until its current action has completed, so a sleep timer or delay works fine here.

**Comment by psds01** [comment]
Hi @MetcalfeTom @akelad @gunagg ,
I am having a similar issue. I have an action which asks for two things (say `city` and `state`). User may provide city and state together in a single reply or she may provide `city` in a message and `state` in the next message. I want to give user `10 seconds` to type in their state, but if they don't, I want to "remind" them that even though they have provided `city`, I still need `state` to move ahead. Is there any way to achieve this?

```
 - bot_ask_for_city_and_state
* inform{"city":"New York"}
 - custom_action_which_waits_for_10_seconds_and_if_no_user_input_reminds_about_state
```
This could play out as follows :
```
## Story_1. 
 - bot_ask_city_and_state
* inform{"city":"New York City"}
* inform{"state":New York"}

## Story_2
 - bot_ask_city_and_state
* inform{"state":New York","city":"New York City"}

## Story_3 *and this is of my interest!!*
 - bot_ask_city_and_state
* inform{"city":"New York City"}
 ---"10 seconds have passed"---
 - bot_remind_state
* inform{"state":New York"}
```
How do I implement Story_3? Waiting for some time and triggering some action inside a bot?

Thanks, any help will be appreciated!

**Comment by gunagg** [comment]
Hi @psds01 ,
There is an event for scheduling a reminder action in Rasa which maybe you can leverage for your condition:
http://rasa.com/docs/rasa/api/events/#schedule-a-reminder
Maybe you can use this to set a reminder for 10 seconds from the time you receive the city slot value. 
By setting "kill_on_user_msg" to true, it should ideally kill the reminder event. (I haven't tried this, but ideally it should work this way!)

**Comment by psds01** [comment]
Thanks @gunagg for the info. Any idea on how to include this in my core/stories? I mean how do I activate a remind? Also, how to make the time dynamic, instead of hard-coding it as given in the example.

**Comment by gunagg** [comment]
You have to return the ReminderScheduled event with parameters in your custom action. You can use python libraries to get the current time and increment by x seconds to set the future time.

**Comment by psds01** [comment]
@gunagg Thanks! Thanks! :-)
