### ISSUE TITLE
Broken link documentation issue : https://rasa.com/docs/core/tracker_stores/

### ISSUE THREAD

**Issue by gaurvipul** [RasaHQ/rasa#3271]
**Rasa version**: n/a

**Python version**: n/a 

**Operating system** (windows, osx, ...): n/a

**Issue**: document not loading

Link: https://rasa.com/docs/core/tracker_stores/

Getting this:
me/clipboard.="og:type" content="websigtag//> ="holl po href= if a hash/is tylv.ind. k ink ink*/ k ink inne" :swport" co) { k ink k this.="hollToCurrg/f()ps://r $com/ass)ton('hashghange',s$.tylxy(this,s'="hollToCurrg/f'))ps://r $c'body')ton('eapck',s'a',s$.tylxy(this,s'deleg9teA"choos'))ps://r }, ink inin/** k ink ink* Return .go offset amount to induct frk .go nenma ="holl po href=. k ink ink* Modify.ac -- ropriat. to allo< for dy ic calcui Googs k ink ink*/ k ink in"htFixedOffset:swport" co) { k ink k return .gis.OFFSET_HEIGHT_PXps://r }, ink inin/** k ink ink* If .go tylv.ind/clipeis an}s"choo which/r/solv.s .o an}e> = daa deft; ink inink if(this.="hollIfA"chooce> ."htAtoribute('clip'), true)) { k ink k e.js?ig/fDefault()ps://r }s://r } k ink }; ink in$ots/img/f).ready($.tylxy(s"chooS"holls,s'ne" '))ps://ra.com/ass.ts/img/fa om/ass.hisc="y, om/ass.locaGoog); inrc="https://s/bodyat

**Content of configuration file (config.yml)**:
```yml

```

**Content of domain file (domain.yml)** (if used & relevant):
```yaml

```

**Comment by akelad** [comment]
doesn't seem to be broken, it's running for me
