### ISSUE TITLE
I get the following error for my custom action 

### ISSUE THREAD

**Issue by SandraAnildas** [RasaHQ/rasa#3276]
ERROR:rasa_core.actions.action:Failed to run custom action 'booking'. Couldn't connect to the server at 'http://localhost:50455/webhook'. Is the server running? Error: HTTPConnectionPool(host='localhost', port=50455): Max retries exceeded with url: /webhook (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000002ADB58D65C0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',))
ERROR:rasa_core.processor:Encountered an exception while running action 'booking'. Bot will continue, but the actions events are lost. Make sure to fix the exception in your custom code.

booking.py

from __future__ import absolute_import
from __future__ import division
from __future__ import unicode_literals

from rasa_core_sdk import Action
from rasa_core_sdk.events import SlotSet

import pymysql

class BookAppointment(Action):
	def name(self):
		return 'action_book_appointment'
		
	def run(self, dispatcher, tracker, domain):
		
		app_date = tracker.get_slot('date')
		db = pymysql.connect('localhost', 'root','quinn_doctor')
		cursor = db.cursor()
		sql = "INSERT INTO appointment VALUES('AAA',app_date)"
		try:
			if(cursor.execute(sql)):
				sql1="Select token from appointment where patient_name='AAA' and date=app_date"
				cursor.execute(sql1)
				token = cursor.fetch()
			else:
				print("Error")
		except:
			print("Error fetching data.")
		finally:
			db.close()
		return token

		response = """Your appointment on {} is confirmed. Your token number is {} """.format(date,token)
						
		dispatcher.utter_message(response)
		return [SlotSet('date',date)]

**Comment by akelad** [comment]
Thanks for raising this issue, @erohmensing  will get back to you about it soon.

**Comment by erohmensing** [comment]
Hi there @SandraAnildas, are you running the action server? The command usually looks something like `python -m rasa_core_sdk.endpoint --actions <action file path>`
When you run this command, you should get a message in your terminal like this:
```
2019-04-18 16:59:14 INFO     __main__  - Action endpoint is up and running. on ('0.0.0.0', 5055)
```
This tells you what port it's running on. 

If you are running your action server, make sure to check that the endpoint in `endpoints.yml` matches the port where your action server is running -- normally our action servers run on 5055, as you can see above, so you want your `endpoints.yml` to contain
```
action_endpoint:
  url: "http://localhost:5055/webhook"
```

**Comment by SandraAnildas** [comment]
Thank you so much.. The issue is solved. I had specified 50455 in my endpoint.yml which I changed to 5055...

**Comment by erohmensing** [comment]
Great! Glad you got it figured out 🚀
