### ISSUE TITLE
Typo in repository description

### ISSUE THREAD

**Issue by dynbit** [RasaHQ/rasa#3278]
In word `framwork` - letter `e` is missing.

`framwork` -> `framework`

**Comment by akelad** [comment]
could you submit a PR? i'm not sure where this is

**Comment by dynbit** [comment]
Sadly, but this part can not be done via PR.  Attached screenshot, it should help.

<img width="1246" alt="RasaHQ_rasa__💬_Open_source_library_for_natural_language_understanding_and_machine_learning-based_dialogue_management__-_All_things_around_intent_classification__entity_extraction_and_action_predictions_-_DIY_NLP_and_chatbot_framwork_" src="https://user-images.githubusercontent.com/213547/56368449-758ae800-61c5-11e9-97c9-ee0150ad895b.png">

**Comment by akelad** [comment]
fixed thank you :D
