### ISSUE TITLE
interactive training cursor marking entities 

### ISSUE THREAD

**Issue by liloup1789** [RasaHQ/rasa#3283]
Hello, 
one silly question : 
When you have to mark with the arrowkeys the good entity : please mark the entities using [value](type) notation 

Where do you have to stop the arrowkey before using the Enter button ? at the beginning of the word, at the end of the word or it whatever ? 

Thanks

**Comment by akelad** [comment]
Thanks for raising this issue, @paulaWesselmann  will get back to you about it soon.

**Comment by paulaWesselmann** [comment]
Hey @liloup1789,
 for this kind of questions maybe join the Rasa forum: https://forum.rasa.com/

If I understand your question correctly: After annotating the entity like this `[blabla](entity_name)` you can have your arrowkey wherever in the text when you press enter, the position does not impact what is send upon pressing enter.
