### ISSUE TITLE
Session issue in rasa

### ISSUE THREAD

**Issue by adityasingh1993** [RasaHQ/rasa#3286]
**Rasa version**:
rasa-core                     0.13.2     
rasa-core-sdk                 0.12.1     
rasa-nlu                      0.14.4  
**Python version**: 
Python                      3.6
**Operating system** (windows, osx, ...):
ubuntu16.04
**Issue**:
When we are calling the http://localhost:5005/conversations/<session_id>/respond. with same session id and same message, it is returning blank. If we are changing the session_id it's working. So kindly suggest how to overcome this issue, why it is returning blank and how to solve this problem. I have attached the  test code

`Output :[{'recipient_id':'{}' , 'text': '{}'}] `

```
import requests
URL = 'http://192.168.1.83:5005/conversations/ahshsh/respond'
chat_input={"q":"goa"}
r = requests.post(url=URL, json=chat_input)
data = r.json()
print(data,"\n")

```
**Content of configuration file (config.yml)**:
```yml

```

**Content of domain file (domain.yml)** (if used & relevant):
```yaml

```

**Comment by akelad** [comment]
This is because rasa core takes into account the state of the conversation. You probably don't have a story where this interaction occurs twice. Please ask any further usage questions in our [forum](https://forum.rasa.com)

**Comment by adityasingh1993** [comment]
Thank you.. :)
