### ISSUE TITLE
Exception: Passing policy configuration parameters to `agent.train(...)` is not supported anymore.

### ISSUE THREAD

**Issue by Rabinpal1** [RasaHQ/rasa#3289]
@akelad 
I am facing the same issue while trying to training dialogue management model online for a simple weather chatbot:

Traceback (most recent call last):
  File "train_init.py", line 27, in <module>
    validation_split = 0.2)
  File "C:\Users\swapnali_bagal\AppData\Roaming\Python\Python36\site-packages\rasa_core\agent.py", line 501, in train raise Exception("Passing policy configuration parameters "
Exception: Passing policy configuration parameters to `agent.train(...)` is not supported anymore. Specify parameters directly in the policy configuration instead. More info https://rasa.com/docs/core/migrations.html

**Rasa Core version**:  0.13.2
**Rasa Core sdk version**:  0.12.1
**rasa-nlu:** 0.14.3
**Python version**: python 3.6.3
**Operating system** : windows 10
**Domain File:**
slots:
  location:
    type: text

intents:
 - greet
 - goodbye
 - inform

entities:
 - location

templates:
  utter_greet:
    - 'Hello! How can I help?'
  utter_goodbye:
    - 'Talk to you later.'
    - 'Bye bye :('
  utter_ask_location:
    - 'In what location?'

actions:
 - utter_greet
 - utter_goodbye
 - utter_ask_location
 - actions.ActionWeather

_Originally posted by @swapbagal1 in https://github.com/RasaHQ/rasa/issues/2980#issuecomment-465134099_

**Comment by Rabinpal1** [comment]
Facing similar issue ,no clear solution found 
Traceback (most recent call last):
  File ".\train_init.py", line 27, in <module>
    validation_split = 0.2)
  File "C:\Users\admin\AppData\Local\Programs\Python\Python36\lib\site-packages\rasa_core\agent.py", line 501, in train
    raise Exception("Passing policy configuration parameters "
Exception: Passing policy configuration parameters to `agent.train(...)` is not supported anymore. Specify parameters directly in the policy configuration instead. More info https://rasa.com/docs/core/migrations.html

**Comment by akelad** [comment]
Hi, please take a look at the migration guide as specified in the exception. It seems `train_init` doesn't have the correct code in it anymore and is still passing arguments to the train method
