### ISSUE TITLE
Unwanted webhook logs coming on chatbot CLI

### ISSUE THREAD

**Issue by vjcalling** [RasaHQ/rasa#3291]
**Rasa version**:0.13.7

**Python version**: 3.6.0

**Operating system** (windows, osx, ...):Windows

**Issue**:NLU and core parts are trained. I'm hosting my action server separately. Now, when I turn on my chatbot CLI, basic functionality is working fine but with every response I'm getting webhooks related logs like "127.0.0.1 - - [2019-04-20 18:43:30] "POST /webhooks/rest/webhook?stream=true&token= HTTP/1.1" 200 272 0.021942". How to disable these?

**Content of configuration file (config.yml)**:
```yml
language: "en"

pipeline: spacy_sklearn

```

**Content of domain file (domain.yml)** (if used & relevant):
```yaml

```

**Comment by akelad** [comment]
you can't, this is just registering that it received a request
