### ISSUE TITLE
Support for Negative feedback for entities

### ISSUE THREAD

**Issue by uahmad235** [RasaHQ/rasa#3300]
**0.14.6**:

**Python 3.6.8**: 

**Ubuntu 16.04.5 LTS** 

**Issue**:
Negative feedback for entities.
I am using RASA to extract custom entities from a text corpus. Spacy, by default provides support for negative feedback (i.e., marking False Positive entity as negative and retrain model for improvement ). The pipeline i am using also uses spacy, then why is it that the RASA does not support Negative Feedback for entities too. This feature is very vital for the scenarios where you want to improve precision through the help of a human in the (feedback) loop.

**Content of configuration file (config.yml)**:
language: "en"
pipeline: "spacy_sklearn"

**Comment by akelad** [comment]
Thanks for raising this issue, @Ghostvv  will get back to you about it soon.

**Comment by Ghostvv** [comment]
What do you mean by negative feedback at which point it should be introduced?

**Comment by uahmad235** [comment]
> What do you mean by negative feedback at which point it should be introduced?

@Ghostvv  By negative Feedback i mean than if a NER model is making False Negatives, we can add more data to prevent that from happening or so. But what if Precision is much more important in some cases, What if a model is making False Positives, how are we going to tell model that this output is wrong. I mean we should have some mechanism by which we should tell our model that this predicted entity is wrong and should not be predicted in future, that this entity is negative. There is a mechanism in spacy, which helps doing such kind of feedback.
Check out this thread for more clarification:
https://stackoverflow.com/questions/49121064/feeding-spacy-ner-model-negative-examples-to-improve-training

**Comment by Ghostvv** [comment]
`crf` not only learns when to pick up an entity but also when *not* to pick it up. Therefore, if you add examples where these entities are not marked as such, it should learn not to pick them up. However, it is very important not to create contradicting examples

**Comment by uahmad235** [comment]
What if a scenario does have contradicting examples by default. I mean its a pretty common scenario in NLP.
For Instance, lets look at a couple of examples from Spacy's official documentation:
![image](https://user-images.githubusercontent.com/30628125/56945177-98ab8500-6b3f-11e9-84d5-86f9aeeb4193.png)
This example contains the contradicting examples naturally.
So how do we handle such scenarios?
Any ideas?

**Comment by Ghostvv** [comment]
the context is not contradicting, so in first two sentences you'd not mark it as an entity, while in the second two, you would in hope that context is different enough to pick a difference

**Comment by uahmad235** [comment]
Normally a CRF is fed only the context of next and previous one or two token(s).  
What you are implying means that the CRF is using the context of whole sentence instead of next and previous token only. Am i right?
Another thing i have to ask is that Is RASA directly using spaCy's model under the hood or is it using other models alongwith spaCy's to improve performance, speed etc?
Your help is really Appreciated!

**Comment by uahmad235** [comment]
I have tried giving model the feedback sentences (previously predicted as False Positives) with empty labels (as you have mentioned that a crf not only learns when to pick up an entity but also when not to pick it up). Doesn't seem to help much, instead the Recall was dropped. The model started missing the actual entities which were similar(context was different, though) to the feedback sentences.
 The issue may be due to the fact that training data is small (15-20 examples in training). Any ideas on this one?

**Comment by Ghostvv** [comment]
well, it is up to how much context is different, etc. Does spacy manage to differentiate your entities?
regarding using spacy please refer to the code of particular component of Rasa NLU

**Comment by uahmad235** [comment]
Spacy too confuses entities at first, but with feedback it manages to differentiate entities to some extent. But it does suffer from "catastrophic forgetting" problem, which is even worst.
The examples being confused are:
1) You will have 30 days to cancel your reservation.  (entity: 30 days)
2) You have 30 days to go to U.K.                             (no entity must be tagged)
Both of sentences have different context (or so i think), but RASA extracts 30 days from both sentences. I, however, want the entity only from first, and not the second sentence. Training data only contains sentences similar to the first sentence.
What do you say about a scenario like this? How could this be prevented?

**Comment by Ghostvv** [comment]
to me the context is identical in both cases
