### ISSUE TITLE
Import specific subskills

### ISSUE THREAD

**Issue by wochinge** [RasaHQ/rasa#3302]
In a naive multi skill setup, all training data / domains of subdirectories get imported and are used for the training of the bot.

```
multi\ domain\ example
├── Bot\ A
│   ├── config.yml
│   ├── data
│   └── domain.yml
├── Bot\ B
│   ├── Bot\ B1
│   │   ├── config.yml
│   │   ├── data
│   │   └── domain.yml
│   ├── config.yml
│   ├── data
│   └── domain.yml
├── config.yml
├── data
└── domain.yml
```

As part of this issue, we want to add the capability to use only certain subdirectories / sub bots (e.g. only include Bot `A` and Bot `B1`).

Where to specify the imports:
* domain file -> access and loading wise that's the better option
* config file

**Comment by saikiran2603** [comment]
Hi , I was trying to find some documentation on how to get this working , i could not find anything in the new rasa 1.0 docs but i stumbled across a document explaining this on the master branch https://github.com/RasaHQ/rasa/blob/master/docs/multi-skill-assistants.rst  is this ready to be used ? if yes could you point me to some code sample on how to use it via python. And this would not be supported via HTTP API to train right ?

**Comment by wochinge** [comment]
@saikiran2603 That's currently a highly experimental feature and very likely changes in the future (so please don't use it in an important / longterm project). However, if you want to give it a shot, checkout the docs you found and this example: https://github.com/RasaHQ/rasa/tree/master/data/test_multi_domain . Happy to hear your feedback 🎉

**Comment by saikiran2603** [comment]
Thanks for the link :) i am trying it out ! will get back on this !
