### ISSUE TITLE
FileNotFoundError on End-to-end evaluation

### ISSUE THREAD

**Issue by anoop2503** [RasaHQ/rasa#3308]
**Rasa version**: Rasa master branch

**Python version**: Python 3.6.7

**Operating system** (windows, osx, ...): 
Distributor ID: Ubuntu
Description:    Ubuntu 18.04.2 LTS
Release:        18.04
Codename:       bionic

**Issue**:
I am getting following error while trying to do End-to-end evaluation

Steps to reproduce the issue:
- Creatd a new story file for e2e evaluation.  The content of the e2e_stories.md file is given below:

  ```
 ## Generated Story 1
 * check_everything_ok: How are you?
     - utter_aswer_fine
     - utter_check_fine
     - action_restart  
```

- Execute following command.
  rasa test core -m models --stories e2e_stories.md --e2e

Please find the logs below:

```
$ rasa test core -m models --stories e2e_stories.md --e2e

'None' not found. Using default location 'endpoints.yml' instead.
2019-04-24 06:25:23 INFO     root  - Generating grammar tables from /usr/lib/python3.6/lib2to3/Grammar.txt
2019-04-24 06:25:23 INFO     root  - Generating grammar tables from /usr/lib/python3.6/lib2to3/PatternGrammar.txt

WARNING: The TensorFlow contrib module will not be included in TensorFlow 2.0.
For more information, please see:
  * https://github.com/tensorflow/community/blob/master/rfcs/20180907-contrib-sunset.md
  * https://github.com/tensorflow/addons
If you depend on functionality not listed there, please file an issue.

/home/ubuntu/rasa/rasa/test.py:72: RuntimeWarning: coroutine 'compare' was never awaited
  compare(model, stories, output)
Traceback (most recent call last):
  File "/home/ubuntu/virtual_env/bin/rasa", line 11, in <module>
    load_entry_point('rasa', 'console_scripts', 'rasa')()
  File "/home/ubuntu/rasa/rasa/__main__.py", line 64, in main
    cmdline_arguments.func(cmdline_arguments)
  File "/home/ubuntu/rasa/rasa/cli/test.py", line 184, in test_core
    test_core(model_path=model_path, **vars(args))
  File "/home/ubuntu/rasa/rasa/test.py", line 76, in test_core
    number_of_stories = core_utils.read_json_file(story_n_path)
  File "/home/ubuntu/rasa/rasa/core/utils.py", line 277, in read_json_file
    with open(filename) as f:
FileNotFoundError: [Errno 2] No such file or directory: 'models/num_stories.json'
```

**Comment by anoop2503** [comment]
Kindly note that I have already trained the model using following command
rasa train -c config.yml -o models

**Comment by akelad** [comment]
Thanks for raising this issue, @wochinge  will get back to you about it soon.

**Comment by anoop2503** [comment]
@akelad / @wochinge, please let me know if you have any update on this issue?

**Comment by wochinge** [comment]
@anoop2503 Please note that you are using the `master` branch which is under heavy development and not stable. 

Also: can you try to specify the model path to the concrete zip file with `-m models/my_model.zip`?

**Comment by anoop2503** [comment]
yes @wochinge the model path is models/my_model.zip only

**Comment by wochinge** [comment]
@anoop2503 Can you please retry with the latest stable version `1.0.6`?
