### ISSUE TITLE
Unknown data format for file renamed.json

### ISSUE THREAD

**Issue by vinaykumarpns** [RasaHQ/rasa#3310]
![Screenshot_1](https://user-images.githubusercontent.com/11782592/56660097-5e179780-66bc-11e9-9ef6-d64ab8f0f46f.jpg)
Error: "ValueError: Unknown data format for file renamed.json"

I checked the data in https://jsonlint.com for JSON validation. It's showing valid JSON but not working.
Here configuration
language: "en"

pipeline:
- name: "nlp_mitie"
  model: "MITIE-models/english/total_word_feature_extractor.dat"
- name: "tokenizer_mitie"
- name: "ner_mitie"
- name: "ner_synonyms"
- name: "intent_entity_featurizer_regex"
- name: "intent_classifier_mitie"

Rasa version: 0.15

**Comment by akelad** [comment]
Thanks for raising this issue, @erohmensing  will get back to you about it soon.

**Comment by erohmensing** [comment]
@vinaykumarpns hm, is your training data correctly formatted for rasa format? Should look something like 
```python
{
    "rasa_nlu_data": {
        "common_examples": [],
        "regex_features" : [],
        "lookup_tables"  : [],
        "entity_synonyms": []
    }
}
```
https://rasa.com/docs/nlu/dataformat/#json-format

**Comment by vinaykumarpns** [comment]
@erohmensing Yeah, My data format is same as you mentioned. actually, this data working for this configuration :
language: en
pipeline: spacy_sklearn

but not working for the above-mentioned configuration

Here I've attached a link for file(renamed.json) for your reference.
Thank you for your time :)

Link: https://drive.google.com/open?id=1CPuZz0U9P2F2NllyVjt_x4oUXdbqKTzm

**Comment by vinaykumarpns** [comment]
Hey, Magic happened it's working now. I just changed import rasa.nlu to rasa_nlu :)
Thanks for your time and sorry for the inconvenience happened by me.

**Comment by erohmensing** [comment]
Ahh thats no problem, I'm glad you got it figured out! I'm surprised that import worked -- you probably have the `rasa` pypi package installed when you don't need it if you have `rasa_nlu` and `rasa_core`, it can cause issues if it's lying around.

**Comment by vinaykumarpns** [comment]
Yeah, I forgot that I cloned library. @erohmensing Can you help me out. Still, I'm not getting the result(It's not detecting Entities). I think this is not the right platform. I will post in Rasa Forum. Thank you :)
