### ISSUE TITLE
Cannot connect rasa bot to Mattermost Server

### ISSUE THREAD

**Issue by jbmcfarlin31** [RasaHQ/rasa#3311]
**Rasa version**: `0.13.7`

**Python version**:  `3.6.5`

**Operating system** (windows, osx, ...): `Ubuntu 16.04`

**Issue**:  
I created this same issue over in the [start-pack-rasa-stack](https://github.com/RasaHQ/starter-pack-rasa-stack/issues/58) repo before I knew this one existed. So if this is considered a duplicate, I will close out the other one and leave this one.

I have followed the starter-kit guide and successfully got the rasa bot chatting locally using the `make cmdline` feature. I want to now apply that same test case to my Mattermost server.

I have been following the [documentation for using the Mattermost connector](https://rasa.com/docs/core/connectors/#mattermost-connector) with the Rasa bot. I created the `credentials.yml` file in my virutalenv with the following:
**NOTE: "my.example.com" has been subbed in place of actual values.**
```
mattermost:
  url: "https://my.example.com/api/v4"
  team: "testing"
  user: "rasabot@example.com"
  pw: "password"
```

I also created an outgoing webhook in my testing team using all of the defaults. I made my callback url `https://my.example.com/webhooks/mattermost/webhook`. 

When I run the `python -m rasa_core.run -d models/current/dialogue/ -u models/current/nlu/ --port 5002 --credentials credentials.yml` command everything starts accordingly to my knowledge:
```
2019-04-15 14:49:16 INFO     root  - Rasa process starting
2019-04-15 14:49:16 INFO     rasa_nlu.components  - Added 'nlp_spacy' to component cache. Key 'nlp_spacy-en'.
2019-04-15 14:49:23.431212: I tensorflow/core/platform/cpu_feature_guard.cc:141] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
2019-04-15 14:49:25 INFO     root  - Rasa Core server is up and running on http://localhost:5002
```

However when I try to @ my bot name nothing happens. I am confused on the purpose of the webhook, when it is not used anywhere in the credentials file or the python run command. I would've expected a token and callback url to be passed in somewhere since those would be our "credentials". The docs are pretty weak in this regard, or I am doing something wrong.

Help is much appreciated!

**Comment by akelad** [comment]
Thanks for raising this issue, @erohmensing  will get back to you about it soon.

**Comment by erohmensing** [comment]
Hey there @jbmcfarlin31, sorry for the late response. Are you routing the endpoint to the core server through ngrok?

If so what does your ngrok server say when you try to talk to the bot? Looking at that, as well as running your run command with the `--debug` flag, can help us figure out if the bot is not receiving the message or if it is receiving it but the response isn't making it to the channel.

**Comment by jbmcfarlin31** [comment]
@erohmensing thank you for the reply. I have no idea if I am routing my endpoints, and I am not really even sure if I am using ngrok. I just followed the start-pack guide to get the bot talking locally, and then I ran across the mattermost docs and followed that. Does ngrok come by default? Is that something I need to install and configure?

**Comment by erohmensing** [comment]
Ah okay. From the docs here:

> For the callback url this needs to be your ngrok url where you have your webhook running in core or your public address, e.g. http://test.example.com/webhooks/mattermost/webhook

Basically what ngrok does is creates a fake url that routes any requests sent to it to a local port where you're running your rasa core server -- this is how you can get your local server connected to the internet, without having to host your own domain to do it. 


Here's a short tutorial adapted from the tutorial in our [Medicare Bot]
(https://github.com/RasaHQ/medicare_locator):

You will need to connect to Mattermost via a webhook. To create a local webhook from your machine you can use [Ngrok](https://ngrok.com/). Follow the instructions on their site to set it up on your computer. Move ngrok to your working directory and in a new terminal run:
```
./ngrok http 5002
```
(the port above should match the `--port` argument of your run command)

Ngrok will create a http address for your computer. For Mattermost you need the address in this format: `http://xxxxxx.ngrok.io/webhooks/mattermost/webhook`

You will have to update the callback url every time your ngrok url changes.

Let me know if you need any clarification :)

**Comment by jbmcfarlin31** [comment]
Thank you for pointing to the docs around ngrok. Could you clarify a little bit on where you quoted:

> For the callback url this needs to be your ngrok url where you have your webhook running in core or your public address, e.g. http://test.example.com/webhooks/mattermost/webhook

Specifically, the "or your public ip address" part? Do you need to run ngrok to route the requests, or could you pass it to the public address? And if so, is that public address the address of your mattermost server or where your bot is running? 

If it is the latter, I have the rasa bot running on the same machine as my mattermost instance. Is there a way to configure the bot to talk across the local machine?

**Comment by erohmensing** [comment]
Hmm, I believe you could route it directly if you make the callback url `http://localhost:5002/webhooks/mattermost/webhook` (try it out and see, I'm not 100% sure) -- but I believe that would only work on your machine. I might be wrong because mattermost has its own url -- if it does work locally then i'd test it from another ip to see if it gets through.

**Comment by jbmcfarlin31** [comment]
So I made the callback url within mattermost the one above that you had mentioned `http://localhost:5002/webhooks/mattermost/webhook`, and then started my virtualenv that is running the bot, and I still don't get any form of a reply from the bot within mattermost itself.

**Comment by erohmensing** [comment]
Hm I haven't been able to test it locally since I don't have a mattermost channel quickly at my disposal, so honestly I'm not 100% if that will work. But can you run the core server with the `--debug` flag to see if your bot is receiving the message?
Do you have something against using ngrok? Just wondering.

**Comment by jbmcfarlin31** [comment]
This is all I see when running the core server with the `--debug` flag:
```
2019-04-29 18:29:38 INFO     root  - Rasa process starting
2019-04-29 18:29:38 INFO     rasa_nlu.components  - Added 'nlp_spacy' to component cache. Key 'nlp_spacy-en'.
2019-04-29 18:29:45.331148: I tensorflow/core/platform/cpu_feature_guard.cc:141] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
2019-04-29 18:29:47 DEBUG    rasa_core.utils  - Available web server routes:
static                                             OPTIONS, GET, HEAD             /static/[filename]
mattermost_webhook.health                          OPTIONS, GET, HEAD             /webhooks/mattermost/
mattermost_webhook.webhook                         OPTIONS, POST                  /webhooks/mattermost/webhook
2019-04-29 18:29:47 INFO     root  - Rasa Core server is up and running on http://localhost:5002
```
If I do `@botname hello` I do not see anything output to the logs.

I don't have anything against ngrok, so I could try that route. But was just curious to see if it was needed or if you could do it locally if both instances were on the same machine.

**Comment by jbmcfarlin31** [comment]
@erohmensing so I installed ngrok and got it started. It is forwarding to the localhost:5002 address. I updated my mattermost callback url to be the one generated by ngrok. I ran the same commands as above including the `--debug` command, but still don't get any additional output from the rasa core server or the ngrok output.

**Comment by erohmensing** [comment]
Hm okay, so what does the debug log look like on your core server when you call your bot? Also on ngrok, there should be something like this:
```
Web Interface                 http://127.0.0.1:4040
```
where you can go to see all the calls going through to your ngrok server. Is anything showing up there?

It's also possible that the wrapper dependency used to connect to Mattermost is out of date, as it's latest release was over a year ago. If we can't get your bot working, we'll have to look into that.

**Comment by jbmcfarlin31** [comment]
So in troubleshooting I was able to find out that ngrok is blocked by our corporate security policy and more than likely will not be able to be used. Is there another way to proceed?

**Comment by erohmensing** [comment]
Does your company have any sort of host domain you can host it on? It's not usually customary for people to be hosting bots on their local machines, right?

**Comment by jbmcfarlin31** [comment]
Okay so since I am running my mattermost behind a reverse proxy, I was able to make an entry to redirect the `/webhooks/mattermost/webhook` url. So now when I run the core server, I see the following:
```
python -m rasa_core.run -d models/current/dialogue -u models/current/nlu --credentials credentials.yml --port 5002 --debug
/opt/rasa-bot/starter-pack-rasa-stack/rasa-env/lib/python3.6/site-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
https://my.example.com/webhooks/mattermost/webhook2019-05-06 20:03:48 INFO     root  - Rasa process starting
2019-05-06 20:03:49 INFO     rasa_nlu.components  - Added 'nlp_spacy' to component cache. Key 'nlp_spacy-en'.
2019-05-06 20:03:55.530608: I tensorflow/core/platform/cpu_feature_guard.cc:141] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
2019-05-06 20:03:57 DEBUG    rasa_core.utils  - Available web server routes:
static                                             OPTIONS, GET, HEAD             /static/[filename]
mattermost_webhook.health                          OPTIONS, GET, HEAD             /webhooks/mattermost/
mattermost_webhook.webhook                         POST, OPTIONS                  /webhooks/mattermost/webhook
2019-05-06 20:03:57 INFO     root  - Rasa Core server is up and running on http://localhost:5002
```
Notice the `https://dsomattermost.sandia.gov/webhooks/mattermost/webhook2019-05-06 20:03:48` line? That was never there before. So, this leads me to believe that it registered the mattermost client - however, I still don't get a reply from the bot when I tell it `@rasabot hello`.

**Comment by erohmensing** [comment]
Do you have anywhere where you can see the HTTP requests hitting your webhook? Maybe in your reverse proxy?

**Comment by jbmcfarlin31** [comment]
I've been looking at my nginx logs as that is what is handling my reverse proxy. I do not see anything hitting my webhook. The `rasa_core.log` file doesn't show anything also. It's almost as if whenever I make a chat call like `@rasabot hello`, it is not doing the post to the callback URL.

**Comment by jbmcfarlin31** [comment]
So if I curl the callback url on the local box that is running mattermost and the bot, I receive the following output:
```
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 3.2 Final//EN">
<title>405 Method Not Allowed</title>
<h1>Method Not Allowed</h1>
<p>The method is not allowed for the requested URL.</p>
```

However, while the rasa core server is running, I see the following in the output:
```
2019-05-07 14:54:01 INFO     root  - Rasa process starting
2019-05-07 14:54:02 INFO     rasa_nlu.components  - Added 'nlp_spacy' to component cache. Key 'nlp_spacy-en'.
2019-05-07 14:54:09.185178: I tensorflow/core/platform/cpu_feature_guard.cc:141] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
2019-05-07 14:54:11 DEBUG    rasa_core.utils  - Available web server routes:
static                                             OPTIONS, GET, HEAD             /static/[filename]
mattermost_webhook.health                          OPTIONS, GET, HEAD             /webhooks/mattermost/
mattermost_webhook.webhook                         OPTIONS, POST                  /webhooks/mattermost/webhook
2019-05-07 14:54:11 INFO     root  - Rasa Core server is up and running on http://localhost:5002
127.0.0.1 - - [2019-05-07 14:58:20] "GET /webhooks/mattermost/webhook HTTP/1.0" 405 337 0.001110
```
I believe this tells me that my reverse proxy configuration is in fact working, since it is being routed to the `localhost:5002` endpoint since I am seeing it in the rasa core output.

**Comment by jbmcfarlin31** [comment]
Adding on to this furthermore, if I build out the "payload" and "request" just through curl, I get a lot more output in the rasa logs.

For example, if I run the following curl command:
```
curl -X POST \
-H "Content-Type: application/json" \
-d '{"user_id": "my_user_id_went_here","text": "@rasabot hello", "channel_id": "town-square"}' \
https://my.example.com/webhooks/mattermost/webhook
```

The following output is displayed in the rasa core debug:
```
127.0.0.1 - - [2019-05-07 15:22:20] "POST /webhooks/mattermost/webhook HTTP/1.0" 500 430 0.001575
2019-05-07 15:23:19 DEBUG    rasa_core.tracker_store  - Creating a new tracker for id '365y1euqziyb3kapgmejxmcpur'.
2019-05-07 15:23:19 DEBUG    rasa_core.processor  - Received user message 'hello' with intent '{'name': 'greet', 'confidence': 0.8928632431091775}' and entities '[]'
2019-05-07 15:23:19 DEBUG    rasa_core.processor  - Logged UserUtterance - tracker now has 2 events
2019-05-07 15:23:19 DEBUG    rasa_core.processor  - Current slot values:
        name: None
2019-05-07 15:23:19 DEBUG    rasa_core.policies.memoization  - Current tracker state [None, None, None, {}, {'intent_greet': 1.0, 'prev_action_listen': 1.0}]
2019-05-07 15:23:19 DEBUG    rasa_core.policies.memoization  - There is a memorised next action '7'
2019-05-07 15:23:19 DEBUG    rasa_core.policies.form_policy  - There is no active form
2019-05-07 15:23:19 DEBUG    rasa_core.policies.ensemble  - Predicted next action using policy_2_MemoizationPolicy
2019-05-07 15:23:19 DEBUG    rasa_core.processor  - Predicted next action 'utter_name' with prob 1.00.
2019-05-07 15:23:19 DEBUG    rasa_core.processor  - Action 'utter_name' ended with events '[]'
2019-05-07 15:23:19 DEBUG    rasa_core.processor  - Bot utterance 'BotUttered(text: Hey there! Tell me your name., data: {
  "elements": null,
  "buttons": null,
  "attachment": null
})'
2019-05-07 15:23:19 DEBUG    rasa_core.policies.memoization  - Current tracker state [None, None, {}, {'intent_greet': 1.0, 'prev_action_listen': 1.0}, {'intent_greet': 1.0, 'prev_utter_name': 1.0}]
2019-05-07 15:23:19 DEBUG    rasa_core.policies.memoization  - There is a memorised next action '0'
2019-05-07 15:23:19 DEBUG    rasa_core.policies.form_policy  - There is no active form
2019-05-07 15:23:19 DEBUG    rasa_core.policies.ensemble  - Predicted next action using policy_2_MemoizationPolicy
2019-05-07 15:23:19 DEBUG    rasa_core.processor  - Predicted next action 'action_listen' with prob 1.00.
2019-05-07 15:23:19 DEBUG    rasa_core.processor  - Action 'action_listen' ended with events '[]'
127.0.0.1 - - [2019-05-07 15:23:19] "POST /webhooks/mattermost/webhook HTTP/1.0" 200 134 0.333230
```

This almost seems as if mattermost itself is not making the request to the callback URL specified... do you have anything thoughts or suggestions @erohmensing? The other thing is, I would've expected my curl command to return an output to the terminal with `Hey there! Tell me your name.` - but I could be wrong on that.

**Comment by jbmcfarlin31** [comment]
Alright I got this working, finally! I kept playing with the curl commands since that is where I was getting results. I noticed that in my `mattermost.log` file (which I didn't realize I had) it was outputting an error each time the bot tried to reply, it had an entry with something like: `"msg":"You do not have the appropriate permissions"`. I figured out this was because I was using `town-square` as the `channel_id` instead of the actual ID for town-square. To find this, I had to create a personal access token for mattermost to interact with the API and then I had to get the team ID so I knew where to look for the right town-square.

1) Create personal access token for accessing API
2) `curl -H "Authorization: Bearer <personal_access_token>" https://my.example.com/api/v4/teams` this will give you a list of teams. Find the ID of your team.
3) `curl -H "Authorization: Bearer <personal_access_token>" https://my.example.com/api/v4/channels` this will give you a list of channels with their ID's, look for town square under your team ID. Copy this
4) Replace the `channel_id: town-square` data portion of the curl command with the ID:
     `curl -i -X POST -H "Content-Type: application/json" -d '{"user_id": "<my_user_id>","text": "@rasabot hello", "channel_id": "<my_town_square_id>"}' https://my.example.com/webhooks/mattermost/webhook`

This allowed me to start being able to curl a POST request to the callback url, and see the bot post to the channel. However, I still was not able to do `@rasabot hello` and receive a reply. I figured this out next. In the same `mattermost.log`, when I did a `@rasabot hello` I got an error saying:
`err=Post https://my.example.com/webhooks/mattermost/webhook: address forbidden, you may need to set AllowedUntrustedInternalConnections to allow an integration access to your internal network"`

So I went into the mattermost `config.json` and looked for the `AllowedUntrustedInternalConnections` setting and typed in `my.example.com` and then restarted mattermost `service mattermost restart`. Now when I do `@rasabot hello` I get a reply from the rasabot that says `Hey There! Tell me your name.`.

**Comment by erohmensing** [comment]
Awesome, I'm so glad you got it sorted out. Sounds complicated, thanks for the detailed explanation of how you fixed it, it'll be really helpful for anyone else who runs into the problem!
