### ISSUE TITLE
Composite Entites : Support for multiple training files

### ISSUE THREAD

**Issue by shashank94** [RasaHQ/rasa#3325]
Hi,

I'm trying to train data from multiple files for composite entities. Currently I'm unable to do so and getting the following message - 'The CompositeEntityExtractor could not load the train file.'.

Please let me know if in case there is any alternate method or way to train the data from multiple files for composite entities.

Thanks in advance.

**Comment by akelad** [comment]
@shashank94 please post an issue on the repo of the library you're using for composite entities, we didn't write the code for that

**Comment by shashank94** [comment]
Sure. Thank You.
