### ISSUE TITLE
check_duplicate_synonym throws up unnecessary warnings during training_data.merge

### ISSUE THREAD

**Issue by MetcalfeTom** [RasaHQ/rasa#3326]
When merging entity synonyms upon building training data, the synonyms are checked one by one, which leads to situations like this:
```
WARNING  rasa.nlu.training_data.util  - Found inconsistent entity synonyms while reading markdown, overwriting proof->copy_of_policy with proof->declarations_page during merge
WARNING  rasa.nlu.training_data.util  - Found inconsistent entity synonyms while reading markdown, overwriting proof->declarations_page with proof->copy_of_policy during merge
WARNING  rasa.nlu.training_data.util  - Found inconsistent entity synonyms while reading markdown, overwriting proof->copy_of_policy with proof->declarations_page during merge
```
We should probably check the counts of both synonyms first, then merge the smaller category into the larger

**Comment by TyDunn** [comment]
This was a problem in markdown. Please reopen if it's still an issue with the yaml format

**Comment by scordee** [comment]
I still have this issue with yaml format. In my case the synonyms are in the same file as the training data is in. Not sure if that is a problem.

**Comment by deepaktunuguntla** [comment]
I still get this issue when using the yml format. This happens when I change the name of a synonym from A to B. Then I end up with the 

UserWarning: Found inconsistent entity synonyms while reading markdown, synonymous_word->A with synonymous_word->B during merge.

**Comment by TyDunn** [comment]
> UserWarning: Found inconsistent entity synonyms while reading markdown, synonymous_word->A with synonymous_word->B during merge.

@deepaktunuguntla Why does this say "while reading markdown" if you are using yml?

**Comment by deepaktunuguntla** [comment]
I am asking the same question to myself tbh .. i'm using rasa 2.5.0

**Comment by TyDunn** [comment]
Very odd. Thanks for reporting this. Can you please open a [new bug report](https://github.com/RasaHQ/rasa/issues/new?assignees=&labels=area%3Arasa-oss+%3Aferris_wheel%3A%2Ctype%3Abug+%3Abug%3A&template=bug_report.md&title=) with steps to reproduce?

**Comment by deepaktunuguntla** [comment]
Sure.
