### ISSUE TITLE
AttributeError: 'Namespace' object has no attribute 'percentages'

### ISSUE THREAD

**Issue by anoop2503** [RasaHQ/rasa#3335]
**Rasa version**:
-e git+https://github.com/RasaHQ/rasa.git@5a6050a20a1d6ca33204dd8e9dec27004562548a#egg=rasa
rasa-core-sdk==0.13.1
rasa-nlu==0.15.0

**Python version**:  Python 3.6.7

**Operating system** (windows, osx, ...):
Distributor ID: Ubuntu
Description: Ubuntu 18.04.2 LTS
Release: 18.04
Codename: bionic

**Issue**: I am getting the following error when I try to train the models using following command after the fresh installation.

rasa train -c config.yml -o models

```
Traceback (most recent call last):
  File "/home/ubuntu/virtual_env/bin/rasa", line 10, in <module>
    sys.exit(main())
  File "/home/ubuntu/virtual_env/lib/python3.6/site-packages/rasa/__main__.py", line 64, in main
    cmdline_arguments.func(cmdline_arguments)
  File "/home/ubuntu/virtual_env/lib/python3.6/site-packages/rasa/cli/train.py", line 127, in train
    extract_additional_arguments(args),
  File "/home/ubuntu/virtual_env/lib/python3.6/site-packages/rasa/cli/train.py", line 186, in extract_additional_arguments
    "percentages": args.percentages,
AttributeError: 'Namespace' object has no attribute 'percentages'
```

But, the training is working fine, when I tried an older version. The following version is working fine for me.

```
-e git+https://github.com/RasaHQ/rasa.git@747683b0314b63a801456de2a00776af2a33d948#egg=rasa
rasa-core-sdk==0.13.1
rasa-nlu==0.15.0
```

So, I believe, some of the recent commits are breaking it. Could you please confirm?

**Comment by akelad** [comment]
Thanks for raising this issue, @tabergma  will get back to you about it soon.

**Comment by tabergma** [comment]
@anoop2503 Yes, `rasa train` was broken on master. It was fixed this morning, so you should be able to train again via the command line.

**Comment by anoop2503** [comment]
thank you @tabergma, thisis working fine now. Hence, closing the ticket.
