### ISSUE TITLE
Delay in bot response causing unexpected behavior

### ISSUE THREAD

**Issue by anoop2503** [RasaHQ/rasa#3340]
**Rasa version**: Rasa master branch

**Python version**: Python 3.6.7

**Operating system** (windows, osx, ...):
Distributor ID: Ubuntu
Description: Ubuntu 18.04.2 LTS
Release: 18.04
Codename: bionic

**Issue**:
I am trying to integrate the bot with SLACK channel. But, if there is any delay in response (say 3 seconds, since the normal timeout delay for the slack is 3 seconds, I believe) from bot causing unexpected behavior and the bot keep sending response to the slack multiple times.

Steps to reproduce the issue:
- Create an intent
- Create a custom action just to return a dispatcher.utter_message("Test response")
- Create a story to execute the custom action for the intent.
- In the custom action, just before the utter_message, add a time.sleep for 5 seconds.
- Train the model and run
- Now test it from slack. When the user sends a message (for that intent), it will execute the custom action and respond with the message "Test response" after 5 seconds. Please wait some more time to see the unexpected behavior. The bot will continue posting messages to the slack after some time interval.

Please note that the issue is appearing only with Master branch. I could not see any issue like this, when I try the same scenario with an old version. It is working fine with the below version.
rasa-core==0.13.7
rasa-core-sdk==0.12.2
rasa-nlu==0.14.6

Thank you,

**Comment by akelad** [comment]
Thanks for raising this issue, @wochinge  will get back to you about it soon.

**Comment by anoop2503** [comment]
@akelad / @wochinge, please let me know if you have any update on this issue?

**Comment by wochinge** [comment]
@anoop2503 Please use the stable versions of Core, like `0.14.1` and not the `master` branch since this branch is currently under heavy development.
