### ISSUE TITLE
NLU documentation has duplicate text

### ISSUE THREAD

**Issue by mohdsanadzakirizvi** [RasaHQ/rasa#3342]
**Rasa version**:
0.15
**Python version**: 
3.6
**Operating system** (windows, osx, ...):
Doc bug so doesn't matter
**Issue**:
The  [NLU Installation document](https://rasa.com/docs/nlu/installation/) has duplicate text in the end.

**Content of configuration file (config.yml)**:
```yml
NA
```

**Content of domain file (domain.yml)** (if used & relevant):
```yaml
NA
```
I have created pull request [#3999 ](https://github.com/RasaHQ/rasa/pull/3339)to fix this. Please guide me how to contribute.

Thanks!

**Comment by akelad** [comment]
submitting the PR is enough, as mentioned on the PR, we'll review it asap :)
