### ISSUE TITLE
Late normalisation makes FallbackPolicy threshold difficult to set

### ISSUE THREAD

**Issue by einarbmag** [RasaHQ/rasa#3344]
**Rasa version**:
rasa-core==0.14.0
rasa-core-sdk==0.13.1
rasa-nlu==0.15.0
**Python version**: 
Python 3.6.5 :: Anaconda, Inc.
**Operating system** (windows, osx, ...):
OS X
**Issue**:

I've been very confused for half an hour trying to figure out why the thresholds in the FallbackPolicy don't seem to work as expected... actions are being accepted with probability 0.26 even when my `core_threshold` config parameter is 0.3... so I looked into the code, and the culprit is the normalisation of probabilities that happens **after** the best policy has been chosen, line 383 in ensemble.py. I.e., the raw number from the policy (I was using the EmbeddingPolicy) was 0.70, but after normalisation it's 0.26. 

Wouldn't it make sense for the policies to always output normalised probabilities? Especially as they get normalised anyway before being returned by the ensemble policy. It makes for a very frustrating guessing game to select the threshold this way, without knowing what the actual number being compared is.

**Comment by akelad** [comment]
@einarbmag thanks for spotting this, I think this is some leftover code from when we used probabilities like "1.1" to override policies. @erohmensing you worked on policy priority right, could you take a look please?

**Comment by Ghostvv** [comment]
indeed, it’s artefact of multiplying probabilities. We should remove it. Embedding policy doesn’t model probabilities therefore normalization doesn’t give probability-like number, in case of cosine it is better to leave it as is

**Comment by Ghostvv** [comment]
@einarbmag thank you for raising the issue, I removed it in above PR. Could you please let me know why did you decide to use `EmbeddingPolicy`? Does it perform better?
