### ISSUE TITLE
Slot value is not getting updated while using SlotSet in rasa_core=0.9.6

### ISSUE THREAD

**Issue by vinayakray1** [RasaHQ/rasa#3346]
**Rasa version**: rasa_core=0.9.6, rasa_nlu=0.12.3

**Python version**: 3.6.3

**Operating system** (windows, osx, ...): RedHat RHEL 7.1 x86_64

**Issue**: In the serve.py endpoint, I am trying to update the value of a slot "summary" with the text input the user would put in. I have used the following code snippet:

@custom_webhook.route("/", methods=['POST', 'GET'])
        def receive():       
            sender_id = request.form.get("sender")
            text = request.form.get("message")
            out = CollectingOutputChannel()
            print("The text is" + text)
            global message
            message = ""
            summary = ""
            if "wwwwwwwwww" in text:
                summary = text
                SlotSet("summary", summary)
                message += "user: " + text + "  " + str(datetime.datetime.now())
                on_new_message(UserMessage("acknowledge IT Helpdesk Ticket", out, sender_id))

Here, the summary slot is not getting updated.

**Content of configuration file (config.yml)**:
```yml

```

**Content of domain file (domain.json)** (if used & relevant):
```yaml

{
"slots":{
"summary":{
"type":"text",
"initial_value": "DEFAULT SUMMARY OF IT HELPDESK TICKET"
}
},
"templates":{
"utter_IT_helpdesk_ticket_acknowledge_resp":[
{
"text":"Thanks, please acknowledge the summary you entered so that IT ticket could be created. <br/><br/> {summary} <br/> <br/>"
}
]
},
"entities":[
"summary"
],
"intents" : [
"IT_helpdesk_ticket_acknowledge"
],
"actions": [
"utter_IT_helpdesk_ticket_acknowledge_resp"
]
}
```

**Comment by akelad** [comment]
@vinayakray1 could you please upgrade to a newer version, this version is not really supported anymore. Apart from that, setting slots should happen from custom actions, not from an endpoint as you've specified here
