### ISSUE TITLE
Rasa nlu: RuntimeError: Calling `rasa.nlu.train` using docker

### ISSUE THREAD

**Issue by anurag53** [RasaHQ/rasa#3350]
Hi,

I am using rasa-nlu for my project. I am running rasa-nlu using docker. I am using the below command to train the rasa-nlu.

docker run 
-v $(pwd):/app/project 
-v $(pwd)/models:/app/models 
rasa/rasa_nlu:latest 
run 
python -m rasa_nlu.train -c config.yml --data project/data/MyModel -o models --fixed_model_name MyProject --project current --verbose

Whenever I am trying to train the rasa-nlu model I getting the following issue:

/app/rasa_nlu/init.py:12: UserWarning: The ‘rasa_nlu’ package hase been renamed. You should change your imports to use ‘rasa.nlu’ instead.
RuntimeError: Calling rasa.nlu.train directly is no longer supported. Please use rasa train nlu instead.
I was not facing the issue earlier while using the same command. I think issue is because of the latest update on 23 April 2019 [Ref. Link: https://rasa.com/docs/nlu/changelog/].

Please help me to resolve this.

**Comment by azazdeaz** [comment]
Hi, i got it working by migrating the command to use rasa shell:
```
docker run \
    -v $(pwd):/app/project \
    -v $(pwd)/models:/app/model \
    rasa/rasa_nlu:latest \
    run \
        rasa train nlu \
            --config /app/project/nlu/config.yml \
            --nlu /app/project/data/nlu.md \
            --out /app/model
```
But it's probably better to revert to a previous tag for now. I use `rasa/rasa_nlu:0.14.4-full`

**Comment by anurag53** [comment]
Hi @azazdeaz,
Thank you so much for the solution. rasa/rasa_nlu:0.14.4-full helped for me.

**Comment by akelad** [comment]
glad you figured it out, i'll close this issue

**Comment by NerdJain** [comment]
Not running rasa_nlu using docker, but getting the same issue on windows.

**Here is the error:**
C:\Users\DELL\iplbot\practice_version>python -m rasa_nlu.train -c nlu_config.yml --data data/nlu_data.md -o models --fixed_model_name nlu --project current --verbose
C:\Users\DELL\AppData\Local\Programs\Python\Python37\lib\site-packages\rasa_nlu\__init__.py:12: UserWarning: The 'rasa_nlu' package has been renamed. You should change your imports to use 'rasa.nlu' instead.
  UserWarning,
Traceback (most recent call last):
  File "C:\Users\DELL\AppData\Local\Programs\Python\Python37\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\Users\DELL\AppData\Local\Programs\Python\Python37\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\DELL\AppData\Local\Programs\Python\Python37\lib\site-packages\rasa\nlu\train.py", line 101, in <module>
    "Calling `rasa.nlu.train` directly is no longer supported. Please use "
RuntimeError: Calling `rasa.nlu.train` directly is no longer supported. Please use `rasa train` to train a combined Core and NLU model or `rasa train nlu` to train an NLU model.
