### ISSUE TITLE
Add support for custom json response in custom action response.

### ISSUE THREAD

**Issue by BlankRain** [RasaHQ/rasa#3353]
Rasa support text,image,attachment,buttons as response entity.
However , for the frontend ,It's not enough. developer need more tags like "video" ,"selector","msgbox",something else, whatever...
now,the response struct is 
```
{
recipient_id: string  required
text: string required
image: string optional
buttons: array  optional
attachment: object optional
}
```
what I want is add a key "graphql" to the response entity.
```
{
recipient_id: string  required
text: string required
image: string optional
buttons: array  optional
attachment: object optional

// what I want 
graphql: object optional

}
```
so ,I can put my own JSON data into the response via custom action response.

the frontend can render a rich UI by using `response.graphql` 's data.

**Comment by akelad** [comment]
Please see my comment on your PR
