### ISSUE TITLE
Docker image dockerhub rasa/rasa only provides `latest` tag

### ISSUE THREAD

**Issue by mbelang** [RasaHQ/rasa#3356]
Would it be possible to publish a rasa docker image tag that matches the python version and the actual rasa package version?

Relying on a rolling tag is a very bad practice in docker world.

Thank you.

**Comment by akelad** [comment]
These are available for the separate packages `rasa_core` and `rasa_nlu`. We haven't finished setting up the single docker image for `rasa`, but will do this as soon as we have
