### ISSUE TITLE
Rasa installed but rasa_nlu.converters not found

### ISSUE THREAD

**Issue by agrawal-mohit** [RasaHQ/rasa#3361]
**Rasa version**: 0.14.6

**Python version**:  3.6.4

**Operating system** (windows, osx, ...): osx

**Issue**: Running a snippet with this line : 

`from rasa_nlu.converters import load_data`

Getting this error : 

> Traceback (most recent call last):
>   File "nlu_model.py", line 1, in <module>
>     from rasa_nlu.converters import load_data
> ModuleNotFoundError: No module named 'rasa_nlu.converters'

However, `pip freeze | grep rasa-nlu` returns 

> rasa-nlu==0.14.6

**Content of configuration file (config.yml)**:
```yml
language: "en"

pipeline: spacy_sklearn 


```

**Content of domain file (domain.yml)** (if used & relevant):
```yaml

```

**Comment by kiranramsingh** [comment]
Hi , I guess you are following a  wrong documentation as you are using v0.14.6 the appropriate way to import load_data is : 

`from rasa_nlu.training_data import load_data`

kindly try this and let us know
thank you
