### ISSUE TITLE
SocketIO Response With 200 Ok, But can't return any data.

### ISSUE THREAD

**Issue by controlmachine** [RasaHQ/rasa#3368]
Hello, 
I have configured my Rasa-NLU and Core, I added everything, everything works well except some small issues.

I've posted Rasa Forum but no one returns. This issue has to be solved asap.

`    input_channel = SocketIOInput(
    	# event name for messages sent from the user
    	user_message_evt="user_uttered",
    	# event name for messages sent from the bot
    	bot_message_evt="message",
    	# socket.io namespace to use for the messages
    	namespace = "/"
    )
    s = agent.handle_channels([input_channel], 5004, serve_forever=True)`

This is just a tutorial which I watch and researched. I have two major problems in it.

I use Socket IO when I write Core Python but I don't know how Rasa use this. 

1-) I requested socket.emit with Javascript with given events, it posts 200 OK, but nothing returns, even data I sent. How can I see response from my model? Like Slack Bot entegration?
2-) When I send it as a JSON , it works, but when I send to string, it will raise error from rasa/socketio. So where should I handle data after user enter their string?

**Comment by akelad** [comment]
Thanks for raising this issue, @paulaWesselmann  will get back to you about it soon.

**Comment by paulaWesselmann** [comment]
Hey @controlmachine, 
What rasa versions are you using?
Also check out the Docs about [SocketIO](https://rasa.com/docs/core/connectors/#socketio-connector) and make sure you have the action server running.

**Comment by controlmachine** [comment]
Hey @paulaWesselmann,
I use rasa_core 0.13.3 version. I checked everything inside that. I opened my port to my friend with ngrok, he sent a request and it is submitted 200 ok. Also I can test with locally. But I don't know where can I find returning data from my question. As I said before , I need a endpoint which web and mobile side will request to my endpoint, and I have to return bot utterance.

**Comment by paulaWesselmann** [comment]
I'm sorry I don't think I understand your setup. 
I guess you have something as described [here](https://github.com/mrbot-ai/rasa-webchat)?
Does your bot work when you run it through the command line not using any external channels?
`python3 -m rasa_core_sdk.endpoint --actions actions` 
and in a new window:
`python3 -m rasa_core.run -d models/current/dialogue -u models/current/nlu --endpoints endpoints.yml`
(You'll have to change the the model paths depending on where you have your trained models saved)

**Comment by controlmachine** [comment]
python3 -m rasa_core.run -d models/current/dialogue -u models/current/nlu --endpoints endpoints.yml
This works.

But rasa_core_sdk.enpoint has a problem. That's because my test.py file contains rasa_core.channels.socketio library says there is no attribute named "channels" in rasa_core.

> python3.6/site-packages/rasa_core/agent.py", line 535, in handle_channels 

Thanks for your help. @paulaWesselmann @akelad .

**Comment by controlmachine** [comment]
> 2019-05-04 17:07:50 INFO     __main__  - Starting action endpoint server...
> 2019-05-04 17:07:51 INFO     apscheduler.scheduler  - Scheduler started
> 2019-05-04 17:07:51 INFO     rasa_nlu.components  - Added 'nlp_spacy' to component cache. Key 'nlp_spacy-en'.
> 2019-05-04 17:07:56.826813: I tensorflow/core/platform/cpu_feature_guard.cc:141] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
> 2019-05-04 17:07:58 INFO     rasa_core_sdk.executor  - Registered function for 'action_currency'.
> 2019-05-04 17:07:58 INFO     rasa_core_sdk.executor  - Registered function for 'action_checkout'.
> 2019-05-04 17:07:58 INFO     __main__  - Action endpoint is up and running. on ('0.0.0.0', 5055)

But as you can see @paulaWesselmann if I delete importing rasa_core.channels.socketio in my socket io file, sdk endpoint works at the port given.

**Comment by controlmachine** [comment]
@akelad @paulaWesselmann

Sorry for that but I have to configure my bot as soon as possible, can we solve my problem?
Firstly, where is rasa_core socketio file?

**Comment by paulaWesselmann** [comment]
Sorry for the delayed response, I hope you closing the issue means it is solved?

The `socketio.py` file is under `rasa_core.channels`.
https://github.com/RasaHQ/rasa_core/blob/0.13.x/rasa_core/channels/socketio.py

**Comment by krati5** [comment]
@controlmachine 
How did you solve the problem ?
I am using the following command to run the bot:

python -m rasa_core.run --enable_api -d models/dialogue -u models/nlu/default/EMSnlu --credentials credentials.yml --endpoints endpoints.yml -o out.log --port 5005 --debug --cors *

**credentials.yml**
socketio:
    user_message_evt: user_uttered
    bot_message_evt: bot_uttered
    session_persistence: false

rest:
*******************************
Also, I have not added anything extra in actions.py file. and i don't know why **rasa_core.channels** has to be imported? since i am sending the response back by **dispatcher.utter_message**

python3 -m rasa_core_sdk.endpoint --actions actions

**Comment by paulaWesselmann** [comment]
Hey @krati5,
Are you having the same problem as @controlmachine? using  SocketIO and getting a 200 response but no returned data?

**Comment by krati5** [comment]
@paulaWesselmann 
Hey, not exactly. I am able to get responses for **templates** present in my **domain.yml file**, for example:

> templates:
>          utter_greet:
>         - text: 'Hey! How can i help?'
>         - text: 'Hello! How may I help?'

---------------------------------------------------------
However, not getting any response for any of the custom actions in actions.py file, here is one of the action present in actions.py

  # class action_rel(Action):
	def name(self):
		return 'action_rel'

	def run(self,dispatcher, tracker, domain):
		query=tracker.get_slot('search_query')
		response="some-response-string"
		dispatcher.utter_message(response)
		return [SlotSet('search_query',None)]

**Comment by controlmachine** [comment]
@paulaWesselmann 
Hey, I solved my problems into my python files(Syntax errors, library errors). I run my endpoints, test.py(Which is includes my socket io configuration), but when I connect my port, it returns 200 ok, but any data can't be received. What can I do to handle this problem. Does Rasa Socketio response any data or is it just listener? 

This what I have to do;
"message":"hello", and socket have to return what returned before in my rasa_core.run. Do I need to make any backend to take returning value from that.

I reopened issue. For your information. @paulaWesselmann @akelad .

**Comment by controlmachine** [comment]
@paulaWesselmann Still waiting your response to get data from my chatbot.

Am I clear to what the problem was? If socket io channel is endpoint, it has to able to response according to my inputs  which is I send it their port.

**Comment by paulaWesselmann** [comment]
@controlmachine I'm sorry to keep you waiting, but I didn't get to this issue again yet. 
I will post a response as soon as I get to it.

**Comment by controlmachine** [comment]
No problem, I am waiting , is it a general issue ? If I connect socket io, it isn't just a  request listener right? Did any other developers face with this problem like I faced before? Because I don't know what are you waiting for getting issue?

**Comment by controlmachine** [comment]
And second think I have to say, when I implement with web-chat, it works, but I have to implement it for android, that's why I am trying to get response from url, if I use Rest Channels, It works sometimes, and generally "action events are lost" error message comes. I need real-time and stable url.
