### ISSUE TITLE
Issue when connecting to slack using the botframework from core

### ISSUE THREAD

**Issue by ice2tricky** [RasaHQ/rasa#3370]
**Rasa version**:
rasa_core_sdk~=0.13.0a1
latest version from nlu and core
**Python version**: 
3.7.2
**Operating system** (windows, osx, ...):
windows
**Issue**:
So I have a bot hosted through azure and created with the botframework and LUIS, etc..

I have unhooked everything on the backend and I am using Rasa for everything now. To keep the channel support and the setup, I  use your implementation to connect to the botservice using AppId, etc. All of this work perfectly, I check my existing FB, Skype, webintegration, webchat everything works, except the Slack integration, so to connect from the azure bot service to the slack channel it throws this error 

ERROR    rasa_core.channels.botframework  - Error trying to send botframework messge. Response: {
  "error": {
    "code": "ServiceError",
    "message": "Invalid ChannelData"
  }
}

If I use my botframework endpoint and my C# code this works without a problem.

It's just to report this bug, to help me further I will just make a different slackapp and connect Rasa to there. Side note as mentioned earlier on one of the posts by someone else, better to call your integration with botframework to botservice, since you are not using the botframework at all. Ty for your time

**Content of configuration file (config.yml)**:
```yml
not relevant
```

**Content of domain file (domain.yml)** (if used & relevant):
```yaml
not relevant
```

**Comment by akelad** [comment]
Thanks for raising this issue, @paulaWesselmann  will get back to you about it soon.

**Comment by paulaWesselmann** [comment]
Hey @ice2tricky, 
Did you also try using the slack channel instead of botframework?
Also what do you mean by this?
>Side note as mentioned earlier on one of the posts by someone else, better to call your integration with botframework to botservice, since you are not using the botframework at all. 

can you maybe also post the link to the issue you are referring to?
Thank you!

**Comment by ice2tricky** [comment]
Yes, to get myself further I implemented the slack channel. As previously stated it was just to let you know there is a bug there. 

As for the post I can't instantly locate it, but it comes down to this.  You are referring to the botframework in your documentation, while you actually mean the the botservice from Azure. The Botframework is for making your bot and then it connects to the botservice, like Rasa also connects to the botservice. The botservice is for integrating your bot with channels.

**Comment by erohmensing** [comment]
Closing, this was brought up again in 4426
