### ISSUE TITLE
Rasa NLU:Issues found in SonarQube report

### ISSUE THREAD

**Issue by SnehaG10** [RasaHQ/rasa#3371]
In SonarQube report we are getting code smell issues( Critical and Major) for the below rules 

•	Refactor this function to reduce its Cognitive Complexity from 40 to the 15 allowed
•	Method "__init__" has 11 parameters, which is greater than the 7 authorized
•	Make this method static
•	Refactor this code to not nest more than 4 "if", "for", "while", "try" and "with" statements.

**Comment by akelad** [comment]
Thanks for pointing this out, but we're working on moving around some code anyways, so i don't think these are changes we'll be making
