### ISSUE TITLE
RocketChat integration

### ISSUE THREAD

**Issue by cassiofariasmachado** [RasaHQ/rasa#3375]
**Rasa version**:
```
rasa-core                 0.14.1                   pypi_0    pypi
rasa-core-sdk             0.13.1                   pypi_0    pypi
rasa-nlu                  0.15.0                   pypi_0    pypi
```

**Python version**: 
```
Python 3.7.3
```

**Operating system**:
```
Linux Mint 19.1 Tessa
```

**Issue**:

I'm trying to connect Rasa with an on-premises instance of RocketChat but this integration seems to be broken, the webhook is triggered but without response from my Rasa bot.

``` bash
2019-05-03 16:52:31 INFO     root  - Rasa Core server is up and running on http://localhost:5005
10.0.100.65 - - [2019-05-03 16:52:56] "POST /webhooks/rocketchat/webhook? HTTP/1.1" 200 115 0.001003
```

I'm using the [starter pack example](https://github.com/RasaHQ/starter-pack-rasa-stack) and just made the extra configuration of connecting it to Rocket based on this [documentation](https://rasa.com/docs/core/connectors/#rocketchat-setup).

In webhook's history from RocketChat I have a success message (200 status code)  but the data of the response is `null`, as following:

``` json
{
  "statusCode": 200,
  "content": "",
  "headers": {
    "content-type": "text/html; charset=utf-8",
    "content-length": "0",
    "date": "Fri, 03 May 2019 19:52:56 GMT"
  },
  "data": null
}
```

**Content of credentials file**:

```yml
rocketchat:
  user: "username"
  password: "password"
  server_url: "https://myinstance.com"
```

**Content of configuration file (config.yml)**:

It's the default config.yml from [starter-pack-rasa-stack](https://github.com/RasaHQ/starter-pack-rasa-stack/blob/master/nlu_config.yml).

```yml
language: "en"
pipeline: spacy_sklearn
```
**Content of domain file (domain.yml)**:

It's the default domain.yml from [starter-pack-rasa-stack](https://github.com/RasaHQ/starter-pack-rasa-stack/blob/master/domain.yml).

**Comment by akelad** [comment]
Thanks for raising this issue, @MetcalfeTom  will get back to you about it soon.

**Comment by cassiofariasmachado** [comment]
Updating... in version 0.14.2 of `rasa-core` the RocketChat connector have back to working. 
So, we can close this issue. 
Thanks!
