### ISSUE TITLE
Rasa buttons appearing as text in Slack

### ISSUE THREAD

**Issue by Mounika2405** [RasaHQ/rasa#3376]
**Rasa version**: 0.11.4 (NLU) 0.8.2(CORE)

**Python version**: 3.5.6

**Operating system** (windows, osx, ...): Windows

**Issue**: Rasa buttons appearing as text in Slack
I’ve created buttons in RASA as shown below:
templates:
  utter_greet:
  - text: 'Hello! How can I help?'
    buttons:
    - title: "Technical"
      payload: '/Technical'
    - title: "Enquiry"
      payload: '/Enquiry'
    - title: "Orientation"
      payload: '/Orientation'
    - title: "Help Desk"
      payload: '/Help'
It works fine in console(if i type “/Technical” it matches with Technical intent and performs the corresponding action correctly) but when I integrate it with slack the buttons still appear as text as shown below:

Mounika [12:58 PM]
Hi

XYZ APP [12:58 PM]
Hello! How can I help?
1: Technical (/Technical)
2: Enquiry (/Enquiry)
3: Orientation (/Orientation)
4: Help Desk (/Help)

Any help on how to replicate buttons in slack?

**Content of configuration file (config.yml)**:
```yml
{
  "pipeline":"spacy_sklearn",
  "path":"/models/nlu",
  "data":"./data/data.json"
}
```

**Comment by akelad** [comment]
Thanks for raising this issue, @erohmensing  will get back to you about it soon.

**Comment by erohmensing** [comment]
Hey @Mounika2405, the slack connector has gone through a bunch of changes in the past year -- your rasa core version is really old. I'd recommend updating to the latest versions and then let me know if you still are having the same problem.
