### ISSUE TITLE
How to keep the Twisted server running forever to improve performance?

### ISSUE THREAD

**Issue by axchanda** [RasaHQ/rasa#3387]
**Rasa version**: Current

**Python version**:  3.6.5

**Operating system** (windows, osx, ...): Windows/Ubuntu/ AWS Linux

**Issue**: The twisted server seems to time out very often and not give a stable performance. When reconnected it takes time to process the request and that's a considerable cold start for the app to run!

**Content of configuration file (config.yml)**:
```pipeline:
- name: tokenizer_whitespace
- name: ner_crf
- name: intent_featurizer_count_vectors
  OOV_token: oov
  token_pattern: (?u)\b\w+\b
- name: intent_classifier_tensorflow_embedding
  epochs: 50
- name: ner_duckling_http
  url: http://localhost:8000
  locale: "NL_Nothing"
  dimensions: ["time"]
- name: ner_synonyms
  language: en
```

**Content of domain file (domain.yml)** (if used & relevant):
```yaml

```

**Comment by axchanda** [comment]
![1](https://user-images.githubusercontent.com/20764675/57238123-4b02b100-7046-11e9-9fc0-35c977ab94ce.PNG)

**Comment by ricwo** [comment]
@axchanda Which version of rasa are you running and what command exactly does it time out on? 

We have moved to a unified Core + NLU server which runs `Sanic` on master branch. Can you try to switching that and see if the issue still occurs?
