### ISSUE TITLE
only re-train the core or nlu that was updated in config

### ISSUE THREAD

**Issue by erohmensing** [RasaHQ/rasa#3388]
If you change only one part of the config (in this case I added a policy), you get

2019-05-05 14:55:17 INFO     rasa.model  - Data (config) for dialogue model changed.
2019-05-05 14:55:17 INFO     rasa.model  - Data (config) for NLU model changed.
it seems to check the file/overall dict instead of the contents of each sub-dictionary. It would be great if in this case it noticed that I didn't actually change the config for the NLU model and it didn't go through re-training.

**Comment by tmbo** [comment]
@tabergma I think you already merged that in right?

**Comment by tabergma** [comment]
yes, this is merged
