### ISSUE TITLE
FormAction: Slots are not filled when named other than entity name  

### ISSUE THREAD

**Issue by NomanSaleem4** [RasaHQ/rasa#3395]
Slot mappings only works if the entity name matches the slot name.
But there are many use cases where same entity is used for filling different Slots depending on the intent. How should I resolve this problem?
Code of my form action that includes slot mappings is given below:

`class ActionGetTestPriceForm(FormAction):
    def name(self):
        return "action_get_test_price_form"

    @staticmethod
    def required_slots(tracker):
        if tracker.get_slot("test_type") is None:
            return ["get_test_price.test_type"]
        return []    

    def slot_mappings(self):
        print("\n ---------2--------")
        # type: () -> Dict[Text: Union[Dict, List[Dict]]]
        """A dictionary to map required slots to
            - an extracted entity
            - intent: value pairs
            - a whole message
            or a list of them, where a first match will be picked"""
        print(" \n ------------------TEST TYPE CALL CHECK------------------")
        return {"get_test_price.test_type": self.from_entity(entity="test_type",
                                            not_intent="chitchat")}`

II have a test_type as an entity. We also have a slots test_type and get_test_price.test_type.
Idea is to create multiple slots for same entity. 
This slot gets filled when we talk in following manner:

Me: please tell me price, 
Bot: Please specify test type (in this case our required slot is get_test_price.test_type not test_type)
Me: cbc(test_type entity)
Bot: cbc costs XYZ ( it filled both our slots required one get_test_price.test_type and slot test_type that is not required)
But when we simply ask as
Me: price of cbc(ner-crf does extract cbc as test_type but the slot get_test_price.test_type does not get filled, even though we have mapped it to test_type entity in the slot mappings function)
Bot says: please specify test type
Although we did mention the test type initially.

So for now to move forward we are using test_type slot to get the value from test_type entity and use it for get_test_price.test_type and we feel its not a proper solution. Why doesn't our slotmappings function works? Thanks. Waiting for you reply.

**Comment by Ghostvv** [comment]
slot mapping works only if this slot is requested, so the context is very clear to the bot. In your second example, the bot doesn't know which slot was requested there it cannot fill arbitrary slot with arbitrary entity. You can customize this behavior in your custom `FormAction`

**Comment by NomanSaleem4** [comment]
ok even if i agree that slot mapping works only if this slot is requested and change my required slots function to 
`@staticmethod
def required_slots(tracker):
    return ["get_test_price.test_type"] `

with same slot mappings function 
`def slot_mappings(self):
    print("\n ---------2--------")
    # type: () -> Dict[Text: Union[Dict, List[Dict]]]
    """A dictionary to map required slots to
        - an extracted entity
        - intent: value pairs
        - a whole message
        or a list of them, where a first match will be picked"""
    print(" \n ------------------TEST TYPE CALL CHECK------------------")
    return {"get_test_price.test_type": self.from_entity(entity="test_type",
                                        not_intent="chitchat")}``
Even then get_test_price.test_type slot does not get filled in the second case (Me: price of cbc) but test_type slot gets filled automatically with test_type entity. I assume that rasa should set get_test_price.test_type using slot mappings as it set test_type slots automatically. can we achieve this behavior?

**Comment by Ghostvv** [comment]
of course, because in the second case it is trigger message, so the form doesn't know yet which slot was activated

**Comment by NomanSaleem4** [comment]
ok I think i have grasped it to some extent now, one last thing, can you please elaborate the word "trigger message" what actually it does?  with respect to rasa so that i can fully grasp the idea. Thanks @Ghostvv

**Comment by NomanSaleem4** [comment]
and why does this trigger message filled the slot test_type with entity having the same name test_type?

**Comment by Ghostvv** [comment]
because in the case when the name is the same, there is no ambiguity

**Comment by NomanSaleem4** [comment]
so when the names are same , rasa by default fills the slots first then starts the form action and then check out for the required slots? am i right

**Comment by Ghostvv** [comment]
depends on autofill property of the slot. But, regardless, the form do it again for its every input including trigger message: it finds all the entities that has the same name as required slots and fill these slots

**Comment by NomanSaleem4** [comment]
So can't we change the calling order of the functions in form actions as now the required slots functions runs first then validate and then slot mappings function. so if slot mappings functions runs first then if a form gets an entity against the slot mapped in slot mappings  it should automatically change the required slots in the required slots function? I that way form will not ask for the slot again and it seems like a better way.

**Comment by Ghostvv** [comment]
how the user knows which slot is requested, but you can do it in your custom form. `FormAction` is fully customizable.

I'll close this issue, since original problem is resolved, and this is a discussion now. Please go to [our forum](forum.rasa.com) for discussions how to use rasa and best practices

**Comment by NomanSaleem4** [comment]
ok Fine. Thanks for your precious time.

**Comment by sheggamharshith** [comment]
> requested,
hey there how to disable the option of grabbing all the slots i want it to constraint to certain intent how can i do that
