### ISSUE TITLE
Rasa NLU training using docker : IsADirectoryError: [Errno 21] Is a directory: 'config/nlu_config.yml'

### ISSUE THREAD

**Issue by theakshaygupta** [RasaHQ/rasa#3404]
**Rasa NLU version**: 0.15.0a1

**Rasa NLU Docker Image**: rasa/rasa_nlu:latest-spacy 

**Python version**: 3.6.8

**Operating system** (windows, osx, ...):  Ubuntu 18.04.2 LTS

**Issue**: 
I am trying to train RASA NLU with docker.
My train command looks like this:
```
docker run \
  -v /app/mounts/chatbot:/app/project \
  -v /app/mounts/chatbot/models/chatbot-models/nlu:/app/models \
  -v /app/mounts/chatbot/nlu_config.yml:/app/config/nlu_config.yml \
  rasa/rasa_nlu:latest-spacy \
  run \
    python -m rasa_nlu.train \
    -c config/nlu_config.yml \
    -d project/data/nlu_data.md \
    -o models \
    --project default
```
Running this command suddenly gives me an error 
```
 IsADirectoryError: [Errno 21] Is a directory: 'config/nlu_config.yml'
```

I understand that this error means rasa_nlu is using `with io.open(filename, ) as f:` so filename reaching it i.e. `config/nlu_config.yml` is not a file but a directory. But it is a weird error to come since path to a yaml file cannot be a directory!

*Full Stack Trace:*
```
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/local/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/app/rasa_nlu/train.py", line 163, in <module>
    do_train(config.load(cmdline_args.config),
  File "/app/rasa_nlu/config.py", line 36, in load
    file_config = utils.read_yaml_file(filename)
  File "/app/rasa_nlu/utils/__init__.py", line 268, in read_yaml_file
    return read_yaml(read_file(filename, "utf-8"))
  File "/app/rasa_nlu/utils/__init__.py", line 189, in read_file
    with io.open(filename, encoding=encoding) as f:
IsADirectoryError: [Errno 21] Is a directory: 'config/nlu_config.yml'
```
I tried running `io.open` inside the container and reading file config/nlu_config.yml and it worked without any problem. The problem seems to be coming when I train!
```
>>> import io
>>> with io.open('config/nlu_config.yml') as f:
...     print(f.read())
... 
<_io.TextIOWrapper name='/app/config/nlu_config.yml' mode='r' encoding='UTF-8'>
```

**Content of configuration file (nlu_config.yml)**:
```yml
language: "en"

pipeline: "spacy_sklearn"
```

I am not sure what is going wrong.
Please tell me if any other relevant information is needed to figure out what is going wrong
Thanks.

Note: The volume might seem off that's because I am running this train commnad from another docker container in which I have mounted my chatbot data like so:

docker-compose.yml
```yml
version: '3.0'
services:
  api:
    .
    .
    .
    volumes:
      - ./chatbot:/app/mounts/chatbot
      - /var/run/docker.sock:/var/run/docker.sock
    .
    .
```

**Comment by akelad** [comment]
@theakshaygupta can you try using a pinned version of the docker image rather than `latest`? it's possible there's some broken code in there

**Comment by theakshaygupta** [comment]
Hi, I tried with `0.15.0-spacy` & `0.14.4-spacy ` and I am still getting the same error.
Could you tell me what more information is needed to debug and I shall provide you

**Comment by akelad** [comment]
does nlu_config.yml exist on your local folder?

**Comment by theakshaygupta** [comment]
Hi, I found out the bug. It was in my code. 
I was actually stopping my nlu container and then running the training through `docker run` which would take the image and spin up a new container. And then I would try to start the old container up!

Mistake from my end! But as a beginner in docker I would say the documentation can be improved a little. What I mean is for running nlu + core + action_server , the obvious choice would be to use compose. So maybe the more informative way to explain the training would be for compose environment only. 

I had to use `docker cp` to transfer the changed files to the container and then ran
`$ docker exec -it rasa_nlu_container sh -c " python -m rasa_nlu.train -c config/nlu_config.yml -d project/data/nlu_data.md -o models --project default"`

But I see that `docker cp` is much slower than mounting the volume but alas we cannot mount while doing `docker exec`. Can you suggest a way around ?
Thanks for the help.

**Comment by akelad** [comment]
Thanks for the suggestions, I think we have this covered in the docs update we're working on. 
You probably shouldn't use docker exec, but docker run, and mount volumes to there
