### ISSUE TITLE
stop running bot

### ISSUE THREAD

**Issue by soundaraj** [RasaHQ/rasa#3406]
**Rasa version**:0.13.0a3

**Python version**: 3.7

**Operating system** (windows, osx, ...):ubuntu

**Issue**: i want to stop the running bot via flask api, so i use common shutdown "werkzeug.server.shutdown" method in channels/facebook.py code, it was not shutdown the server, any other method to shutdown the server

**Comment by akelad** [comment]
Please ask these kind of questions in our [forum](https://forum.rasa.com)

**Comment by soundaraj** [comment]
I am already posted in forum,but no one reply
