### ISSUE TITLE
`utter_*` action creation through interactive learning is not working

### ISSUE THREAD

**Issue by anoop2503** [RasaHQ/rasa#3407]
**Rasa version**: rasa-core==0.14.1

**Python version**: Python 3.6.7

**Operating system** (windows, osx, ...):
Distributor ID: Ubuntu
Description: Ubuntu 18.04.2 LTS
Release: 18.04
Codename: bionic

**Issue**: Getting following error when trying to create a new utter_ action through interactive learning.

```
2019-05-08 13:55:01 ERROR    rasa_core.server  - Encountered an exception while running action 'utter_test'. Bot will continue, but the actions events are lost. Make sure to fix the exception in your custom code.
? WARNING: You have created a new action: 'utter_test', which was not successfully executed. If this action does not return any
 events, you do not need to do anything. If this is a custom action which returns events, you are recommended to implement this
 action in your action server and try again.  (Y/n)
```

I think this has been fixed in rasa master branch as part of [3178](https://github.com/RasaHQ/rasa/issues/3178). But, It would be great if you could fix th issue in rasa_core version also, since the rasa master version is not released yet?

**Comment by akelad** [comment]
we won't be releasing this in a minor, too much code has changed since then. Right now you can just ignore this warning and add the template to your domain file
