### ISSUE TITLE
handle printing in non-utf-8 shells

### ISSUE THREAD

**Issue by erohmensing** [RasaHQ/rasa#3408]
We should make sure that when we print things to the console (`rasa init`), interactive learning, etc., any ascii characters out of normal, like accents or emojis, are handled correctly so that they don't break the method 

cc https://forum.rasa.com/t/unicodeencodeerror-ascii-codec-cant-encode-character-u0001f916-in-position-22-ordinal-not-in-range-128/9478, maybe also https://github.com/RasaHQ/rasa/issues/3088

Other codecs I've run into: `ascii`, `gcb`, `charmap`

**Comment by erohmensing** [comment]
@tmbo I think this should be handled soon, as it has shown to break `rasa init` [here](https://github.com/RasaHQ/rasa/issues/3553) and [here](https://forum.rasa.com/t/unicodeencodeerror-ascii-codec-cant-encode-character-u0001f916-in-position-22-ordinal-not-in-range-128/9478)

**Comment by erohmensing** [comment]
Current fix from user side: instead of running `rasa {command}`, run `PYTHONIOENCODING='utf8' rasa {command}`.

**Comment by erohmensing** [comment]
We also need to make sure input (e.g. reading NLU files) is read correctly

**Comment by wahab250** [comment]
UnicodeDecodeError: 'gbk' codec can't decode byte 0xa0 in position 2388110: illegal multibyte sequence.having this issue while reading text file please help

**Comment by erohmensing** [comment]
@wahab250 please open a new issue with all of the relevant info (traceback, content of data file etc) that the issue template asks you for
