### ISSUE TITLE
optionally output interactive learning stories in e2e format

### ISSUE THREAD

**Issue by erohmensing** [RasaHQ/rasa#3410]
In interactive learning, we already have user input and the intent, validated by the user. We could output these stories in end-to-end format if the user desires so that they don't have to write e2e stories or turn regular ones into e2e ones on their own.

Perhaps this could happen under the flag `rasa interactive --e2e`.

**Comment by chidauri** [comment]
@erohmensing Hi, i would like to work on this.

**Comment by erohmensing** [comment]
Awesome, @chidauri! Let me know if you need any help. I think [this function](https://github.com/RasaHQ/rasa/blob/0354dcf1dc46689f048d3f7dbfca51b6d27e638d/rasa/core/events/__init__.py#L289) will be super useful!

**Comment by chidauri** [comment]
@erohmensing how do i test the changes and how should the output look?

**Comment by erohmensing** [comment]
Thanks for your contribution @chidauri 🎉
