### ISSUE TITLE
optionally name stories generated from interactive learning

### ISSUE THREAD

**Issue by erohmensing** [RasaHQ/rasa#3411]
We recommend that users name their stories based on what happens, to make them easier to understand, but then output something not useful -- "generated story xxxxxx". We should allow the user to add a name for the story if they want, with the "generated story xxxx" as the default value if they decide not to provide a name.

**Comment by chidauri** [comment]
Hi @erohmensing i would like to work on this.

**Comment by erohmensing** [comment]
Sounds good @chidauri! Let me know if you need any help.

**Comment by erohmensing** [comment]
Doable, but not necessary and probably adds more code and input from the user than it's worth, see #4399
