### ISSUE TITLE
Make Slack Channel failure visible

### ISSUE THREAD

**Issue by naoko** [RasaHQ/rasa#3412]
**Rasa version**:
I'm running rasa-core 0.14.2 but I verified the version on master has same code

**Python version**: 
3.7

**Operating system** (windows, osx, ...):
Ubuntu

**Issue**:

Slack client was returning {"ok" False} with error message but not exposing that from rasa_core/channels/slack 

https://github.com/RasaHQ/rasa/blob/49bbb8f06daad0bdec05664cc1eb9eaf7e4407da/rasa/core/channels/slack.py#L30

so I like to propose something like this....
```
    def _api_call(self, metohd, **kwargs):
        result = super(SlackBot, self).api_call(metohd, **kwargs)
        if not result.get("ok", False):
            logger.exception(f"Error {result['error']}\n{kwargs}")
```

on the side note:Once I got {'ok': True} returned, now slack is not posting message although api call to slack shows successful. I'm asking slackclient community but if anyone have idea I'm all  ear.
Thank you!

**Comment by akelad** [comment]
Thanks for raising this issue, @MetcalfeTom  will get back to you about it soon.

**Comment by naoko** [comment]
About the "side note" I posted on the initial post, I figure it out but I'm not sure when this change took place. 
My installed version is `slackclient==1.3.1` and requirements on rasa shows `slackclient==1.3.0` (not sure how I got 1.3.1 bot per release note, it should function the same way).
but the key seems to be you now need to post Channel ID instead of Channel name.
and the Channel can be different depends on where user talk to the bot (directly to the bot or via a mention in some other channel)
So the local changes I made to make it work was to 
in InputChannel,
1. extract channel from `output['event']['channel']` in `webhook` function 
2. pass to process_message and pass to SlackBot instantiation instead of self.slack_channel

I'm wondering if anyone else is experiencing.... but I didn't see issue has been filed.
Also looks like Slack client 2.0 is released so maybe not worth fiddling with this version...?

**Comment by MetcalfeTom** [comment]
Hi @naoko,

Does the code you proposed in message 1 worked?  Would be a welcome contribution if you would open up a PR.

If slack returns "ok" but nothing is posted, that leaves me to believe there is some kind of formatting problem with the message that the Slack frontend doesn't handle.

It makes more sense for us to leapfrog `slackclient==1.3.1` and upgrade directly to `slackclient==2.0.0` in that case.

**Comment by naoko** [comment]
Slack was returning `ok==False` because channel name was invalid but that information was not revealed via rasa slack channel cause it is not checking `ok` value. 
I should be able to find some time to contribute and I agree that we should upgrade to `slackclinet==2.x`
