### ISSUE TITLE
 Can’t we call multiple actions against single intent in a story? 

### ISSUE THREAD

**Issue by NomanSaleem4** [RasaHQ/rasa#3414]
**Rasa Core version**: 0.13.2

**Operating system** (windows, osx, ...): Ubuntu

**Issue**:  Right now i have this story

Generated` Story 89334267679325026
*out_of_scope
    - action_default_fallback
    - utter_ask_continue

Bot always predicts the action_listen as my next action instead of utter_ask_continue, but i want the bot to call utter_ask_continue instead of action_listen. And how can i generate stories manually because interactive learning is a very tedious process. Do we get any benefit using interactive learning. Also this story gets failed when i evaluate it. Any solutions would be highly appreciated . Thanks.

**Content of configuration file (config.yml)**:
language: en
pipeline:
- name: tokenizer_whitespace
- name: ner_crf
- name: intent_featurizer_count_vectors
  token_pattern: (?u)\b\w+\b
- name: intent_classifier_tensorflow_embedding
- name: ner_synonyms
- name: "ner_duckling_http"
  url: "http://duckling:7000"
  dimensions: ["time" , "phone-number", "number"]

**Comment by akelad** [comment]
Please ask these kind of questions in our [forum](https://forum.rasa.com)

**Comment by NomanSaleem4** [comment]
I have asked it first on the form but i didn't get any response there. That is why i have asked here.
