### ISSUE TITLE
Include story source filename in core output for failed stories

### ISSUE THREAD

**Issue by erohmensing** [RasaHQ/rasa#3419]
```
## story 2
* greet
    - action_greet_user
* signup_newsletter
    - utter_can_do
    - subscribe_newsletter_form
    - form{"name": "subscribe_newsletter_form"}
* form: ask_weather
    - form: action_chitchat   <!-- predicted: subscribe_newsletter_form -->
```
If I have multiple story files like our demobot does, it would help me find the story more easily if  above the story name it told me which story file it came from, since my stories might have same names in different files.

**Comment by lmaczulajtys** [comment]
Hi @erohmensing 
I can't self assigin this issue but I'm working on it so it can be moved do "Doing".

**Comment by erohmensing** [comment]
Cool, I will assign you! Awesome that you're taking this on :) just ping me if you have questions.

**Comment by erohmensing** [comment]
Hey @lmaczulajtys, are you still working on this? Let me know if you need any pointers :)

**Comment by lmaczulajtys** [comment]
Hi @erohmensing, I'll submit PR in two days. Sorry it took so long. Hard time at work.

**Comment by erohmensing** [comment]
No worries. Looking forward to your contribution!

**Comment by cheemingli** [comment]
Hi @erohmensing , I want to try working on this.

Any requirements on the output of the `failed_stories.md`? Full file path above the story name like below?
```
<!-- full file path here  -->
## sad path 2
...
```

**Comment by erohmensing** [comment]
Sure! I'd go with relative path though. Maybe something like 

## sad path 2 (relative file path)
...

I'll assign you to it. Let me know if you have any other questions :)

**Comment by cheemingli** [comment]
I already looked in to it and a relative path does not seem possible. At the start of the process the stories are copied to a temporary directory and prefixed with a unique id. So probably the best will be:
```
## sad path 2 (file.path)
...
```
If you use same story filenames in different folders it will still be hard to tell in which file it is.

I still need to figure out how to pass the file name to the output for the failed stories.
I already looked into the previous PR (and review comment) to get a better understanding.

**Comment by erohmensing** [comment]
> If you use same story filenames in different folders it will still be hard to tell in which file it is.

interesting edge case! i hadn't even thought about that.

> At the start of the process the stories are copied to a temporary directory and prefixed with a unique id. 
what do the filenames in the tmp directory look like?

**Comment by cheemingli** [comment]
Files look like `2952489d94ad4a33a0222423084f5d98_stories.md`.

**Comment by cheemingli** [comment]
I've submitted a PR. It is based on the previous PR of @lmaczulajtys but taken into account the review comment that was made.

**Comment by wochinge** [comment]
closed by https://github.com/RasaHQ/rasa/pull/5496
