### ISSUE TITLE
Stories gets failed

### ISSUE THREAD

**Issue by NomanSaleem4** [RasaHQ/rasa#3428]
Here is my story in story files :
```
## Get test price DENY and deactivated
* get_test_price
    - action_get_test_price_form
    - form{"name": "action_get_test_price_form"}
    - slot{"requested_slot": "get_test_price.test_type"}
* deny
    - utter_continue
* deny
    - utter_deny_reply
    - action_deactivate_form
    - form{"name": null}
    - slot{"requested_slot": null}
```

and here is the same story after evaluation:

```
## Get test price DENY and deactivated
* get_test_price
    - action_get_test_price_form
    - form{"name": "action_get_test_price_form"}
    - slot{"requested_slot": "get_test_price.test_type"}
* form: deny
    - form: utter_continue   <!-- predicted: action_get_test_price_form -->
    - form: action_listen   <!-- predicted: action_get_test_price_form -->
* form: deny
    - form: utter_deny_reply   <!-- predicted: action_get_test_price_form -->
    - form: action_deactivate_form   <!-- predicted: action_get_test_price_form -->
    - form{"name": null}
    - slot{"requested_slot": null}
```

so first why does there is a form keyword in the failed story after evaluating it, though there is no form keyword in the actual story. Secondly this is a failed story but still bot is predicting actions exactly according to the failed story. So what does fail means in this context? Thanks

**Comment by akelad** [comment]
@NomanSaleem4 which version of rasa are you using?

**Comment by NomanSaleem4** [comment]
rasa (0.0.5)
rasa-addons (0.5.5)
rasa-core (0.13.2)
rasa-core-sdk (0.12.1)
rasa-nlu (0.14.3)

**Comment by akelad** [comment]
you'll need to use rasa_core 0.14.x -- that branch has a fix for this issue, and we'll be releasing a minor with the fix today

**Comment by NomanSaleem4** [comment]
ok Thank you so much.

**Comment by erohmensing** [comment]
@NomanSaleem4 fix for this was just pushed to the latest version of rasa_core, 0.14.4, on pypi.

**Comment by NomanSaleem4** [comment]
Oh great,i just had updated my core to 0.14.3 and i was about to ask that now when i evaluate my stories all the stories gets passed but when i train my stories i get a loss of 0.6. It will be great if this issue has been resolved . thanks

**Comment by NomanSaleem4** [comment]
unfortunately the same issue persists with rasa_core 0.14.4. all stories passed while evaluation but training loss is 0.6 that is very poor and bot goes into fallback on every time. :/

**Comment by erohmensing** [comment]
As long as the stories are passing and not incorrectly adding the `form: ` prefix to your `deny` intent and the following `utter_continue`, this does not sound like the result of a bug. I would recommend asking on the [forum](http://forum.rasa.com) about how to increase the accuracy in your core evaluation.

**Comment by NomanSaleem4** [comment]
I usually post there but never get replies. like this the issues i have posted recently.
https://forum.rasa.com/t/how-to-utter-validation-response-for-the-slots-instead-of-their-default-response-utter-ask-slot-name/9632

**Comment by NomanSaleem4** [comment]
Facing the same issue in the newer version of rasa core: 0.14.4 
Here is my story : 

`## Generated Story 3513378223536552140
* get_test_price
    - action_get_test_price_form
    - form{"name": "action_get_test_price_form"}
    - slot{"requested_slot": "get_test_price.test_type"}
* check_report_status
    - utter_validation_failed
    - action_get_test_price_form
    - slot{"requested_slot": "get_test_price.test_type"}
* check_report_status
    - action_default_fallback
    - rewind
    - action_restart`

and here is the failed story:

`## Generated Story 3513378223536552140
* get_test_price
    - action_get_test_price_form
    - form{"name": "action_get_test_price_form"}
    - slot{"requested_slot": "get_test_price.test_type"}
* check_report_status
    - utter_validation_failed
    - action_listen
    - action_get_test_price_form
    - slot{"requested_slot": "get_test_price.test_type"}
    - form: action_restart   
    - form: action_listen   `

**Comment by NomanSaleem4** [comment]
So the problem is that whenever action_default_fallback action gets triggered next action predicted is always action_listen instead of action_restart in this case and  all other actions otherwise. so bot gets stucked as previous form is activated in the tracker and action_restart is not getting called. So the solution i have found is not to use action_default_fallback in the stories

**Comment by NomanSaleem4** [comment]
whats you say on this?

**Comment by erohmensing** [comment]
Yes, I don't think `action_default_fallback` should be in the stories, the point of Interactive learning is that you can correct the intents/actions with low confidence so that the bot does not fall back.

**Comment by NomanSaleem4** [comment]
So now i have a story with that includes OR keyword and it gets failed for every intent.
*Intent1 OR intent2 OR intent3
  - some_action
  - some_action

Its get failed  for all the three intents while evaluation

**Comment by erohmensing** [comment]
Can you post the failure?

**Comment by NomanSaleem4** [comment]
also i have created a story using interactive learning but it gets failed with action_default_fallback in the story, then i have used utter_default as an alternative to it.

**Comment by NomanSaleem4** [comment]
Ok it was not the problem with OR keyword
