### ISSUE TITLE
Utterance templates are never verified before training

### ISSUE THREAD

**Issue by MetcalfeTom** [RasaHQ/rasa#3432]
If utterance templates are missing, no warnings get thrown.  Then the domain is copied to the model as is and the bot silently fails during conversation

**Comment by erohmensing** [comment]
Do you mean if utterances are defined in stories or in the `actions:` in the domain? In any case I think we should check for both (isn't this something the validator should take care of?)

**Comment by MetcalfeTom** [comment]
The `templates:` section of the domain.

The validator shouldn't take care of this, because it should halt training when it happens - no point copying the domain file to the model directory if it is incomplete

**Comment by erohmensing** [comment]
Ah okay so if i say 
```
templates:
    utter_greet:
    utter_howareyou:
    - text: "how are you?"
```
or are you saying if there are no templates at all in `templates:`(we should check for both)
