### ISSUE TITLE
NameError: Cannot access action 'action_weather', as that name is not a registered action for this domain. Available actions are: 

### ISSUE THREAD

**Issue by shammy45** [RasaHQ/rasa#3438]
Python version - python3.7

Here is my domain file 
slots:
  location:
    type: text

intents:
 - greet
 - goodbye
 - inform

entities:
 - location

templates:
  utter_greet:
    - 'Hello! How can I help?'
  utter_goodbye:
    - 'Talk to you later.'
    - 'Bye bye :('
  utter_ask_location:
    - 'In what location?'

actions:
 - utter_greet
 - utter_goodbye
 - utter_ask_location
 - custom_action_weather

Here is my action python code
from __future__ import absolute_import
from __future__ import division
from __future__ import unicode_literals

from rasa_core.actions.action import Action
from rasa_core.events import SlotSet

class ActionWeather(Action):
    def name(self):
        return 'action_weather'

def run(self, dispatcher, tracker, domain):
    from apixu.client import ApixuClient
    api_key = 'rt5677791294257191205' #your apixu key
    client = ApixuClient(api_key)

    loc = tracker.get_slot('location')
    current = client.getcurrent(q=loc)

    country = current['location']['country']
    city = current['location']['name']
    condition = current['current']['condition']['text']
    temperature_c = current['current']['temp_c']
    humidity = current['current']['humidity']
    wind_mph = current['current']['wind_mph']
    response = """It is currently {} in {} at the moment. The temperature is {} degrees, the humidity is {}% and the wind speed is {} mph.""".format(condition, city, temperature_c, humidity, wind_mph)
    dispatcher.utter_message(response)
    return [SlotSet('location',loc)]

Here is my training data 

  ##story 001
*greet
    -utter_greet
*inform    
    -utter_greet     
    -utter_ask_location
*goodbye
      -utter_goodbye
      -export
      
    ##story 002
* greet
    - utter_greet
* inform
    - utter_ask_location
* inform{"location": "italy"}
    - slot{"location": "italy"}
    - action_weather
    - slot{"location": "italy"}
* goodbye
    - utter_goodbye
    - export

**Comment by shammy45** [comment]
Here is the error logNameError: Cannot access action 'action_weather', as that name is not a registered action for this domain. Available actions are: 
	 - action_listen
	 - action_restart
	 - action_default_fallback
	 - action_deactivate_form
	 - action_revert_fallback_events
	 - action_default_ask_affirmation
	 - action_default_ask_rephrase
	 - action_back
	 - utter_greet
	 - utter_goodbye
	 - utter_ask_location
	 - custom_action_weather

**Comment by shammy45** [comment]
Rather than Class name ActionWeather, new version needs action_weather , it works

**Comment by visamsundaram** [comment]
Hi, I am testing my custom action too. For instance I tested with this:

from __future__ import absolute_import
from __future__ import division
from __future__ import unicode_literals
from rasa_core_sdk import Tracker
from rasa_core.actions.action import Action
from rasa_core.events import SlotSet
import pandas as pd

class action_get_answer(Action):
    def name(self):
        return 'action_get_answer'	
    def run(self, dispatcher, Tracker, domain):	
        dispatcher.utter_message("test test")

I am still getting not regsitered action error!

**Comment by Aashaybane** [comment]
can you please share the format @shammy45  for how to write in domain file

**Comment by rahul-kallil** [comment]
I have the same issue 
"NameError: Cannot access action 'action_weather', as that name is not a registered action for this domain. Available actions are:       
         - action_listen
         - action_restart
         - action_default_fallback
         - action_deactivate_form
         - action_revert_fallback_events
         - action_default_ask_affirmation
         - action_default_ask_rephrase
         - action_back
         - utter_greet
         - utter_goodbye
         - utter_ask_location
         - actions.ActionWeather


My stories.md file is:
## story 01
* greet
    - utter_greet
    
## story 02
* goodbye
    - utter_goodbye

## story 03
* inform
    - action_weather


and my domain file contains:-
slots:
  location:
    type: text


intents:
 - greet
 - goodbye
 - inform


entities:
 - location

templates:
  utter_greet:
    - 'Hello! How can I help?'
  utter_goodbye:
    - 'Talk to you later.'
    - 'Bye bye :('
  utter_ask_location:
    - 'In what location?'



actions:
 - utter_greet
 - utter_goodbye
 - utter_ask_location
 - actions.ActionWeather


Can u please help how to use the custom actions. I am stuck for 2 days with this issue.
