### ISSUE TITLE
Preprocessor components

### ISSUE THREAD

**Issue by MetcalfeTom** [RasaHQ/rasa#3439]
Currently we lowercase and perform other token processing operations within the `CountVectorFeaturizer`, which only affects the features and not the tokens.  This means entity extractors don't have access to the same preprocessing.  Would be good to include component pipelines so that it's clear what processing happens to the tokens at which point.  Two would include:

- `LowercasePreprocessor`
- `AccentStripPreproccessor`

(and then remove this functionality from the components in which this processing currently happens e.g. `strip_accents` in the `CountVectorsFeaturizer`)

**Comment by wochinge** [comment]
Mhm, but on this level we would end up with hundreds of tiny preprocesser components 🤔

**Comment by MetcalfeTom** [comment]
What other kinds of preprocessing would you include?  So far only these two come to mind as important

**Comment by Ghostvv** [comment]
@tabergma what do you think about it in the light of the new pipeline?

**Comment by tabergma** [comment]
I would say it is not needed. We don't have a component that depends on the plain token text as far as I know, all components depend on the features.

**Comment by tabergma** [comment]
Should we close the issue?

**Comment by wochinge** [comment]
How about the case when you want to strip accents from a word before it's passed to the featurizer @tabergma ? The `CountVectorizer` can do this itself, but not sure about the other ones?

**Comment by wochinge** [comment]
For me it's
- adding it to the tokenizer, means applying the same change to every tokenizer
- adding a new component could result in too many components

I think I'd prefer the first option + finding a scalable way to add things to multiple components at once

**Comment by tabergma** [comment]
Agree.

We could add it to the main class `Tokenizer` and reuse the function in every tokenizer. I just did a similar thing on a branch (see https://github.com/RasaHQ/rasa/blob/combined-entity-intent-model/rasa/nlu/tokenizers/tokenizer.py#L36).

**Comment by wochinge** [comment]
That was just one specific case 😄 It's more about the general topic.

**Comment by wochinge** [comment]
I'll close this one then.
