### ISSUE TITLE
option to strip accents in tokenizer

### ISSUE THREAD

**Issue by wochinge** [RasaHQ/rasa#3450]
Adding an option to strip accents in the tokenizer components:
accénto -> accento

In languages such as french the accents and the possible combinations make it hard to annotate intent / entity data.

**Comment by akelad** [comment]
@MetcalfeTom does this duplicate your other issue you opened?

**Comment by MetcalfeTom** [comment]
Yes, IMO the `Preprocessor` is a more sustainable solution, since the gives the user the option to do these kinds of token processing at any point in their pipeline https://github.com/RasaHQ/rasa/issues/3439
