### ISSUE TITLE
add description for the default behaviour  of  `slot_mappings` to docs

### ISSUE THREAD

**Issue by wochinge** [RasaHQ/rasa#3453]
If extending the `FormAction` one should overwrite the function `slot_mappings`. If this is not done, the action server should give a warning

**Comment by erohmensing** [comment]
@wochinge I updated this when rewriting form docs -- clear enough to close? https://rasa.com/docs/rasa/core/forms/#custom-slot-mappings

**Comment by wochinge** [comment]
Thanks for thinking of this, Ella!
