### ISSUE TITLE
Feature Request: Custom Policies

### ISSUE THREAD

**Issue by siddu9501** [RasaHQ/rasa#3454]
**Rasa version**:
0.15
**Python version**: 
3.6
**Operating system** (windows, osx, ...):
Ubuntu 18.04 
**Issue**:
Allowing for custom policies. If I have a model, the only way to add that to a list of policies now is to add the model to the policies directory and update the policies/__init__.py file. Would be great to have a way around this.

**Comment by akelad** [comment]
You can have a custom policy: https://rasa.com/docs/core/policies/#configuring-polices-using-a-configuration-file
