### ISSUE TITLE
Output of Interactive training (RASA Core) is not directed to the console 

### ISSUE THREAD

**Issue by shammy45** [RasaHQ/rasa#3456]
rasa-core                          0.14.3
rasa-core-sdk                      0.14.0
rasa-nlu                           0.15.0

python3.7

When I execute the following code, 

from __future__ import absolute_import
from __future__ import division
from __future__ import print_function
from __future__ import unicode_literals

import logging
import rasa_core

from rasa_core.run import serve_application
from rasa_core import config
from rasa_core.agent import Agent
#from rasa_core.channels.console import ConsoleInputChannel
from rasa_core.interpreter import RegexInterpreter
from rasa_core.policies.keras_policy import KerasPolicy
from rasa_core.policies.memoization import MemoizationPolicy
from rasa_core.interpreter import RasaNLUInterpreter

logger = logging.getLogger(__name__)

def run_weather_online(input_channel, interpreter,
                          domain_file="weather_domain.yml",
                          training_data_file='data/stories.md'):
            agent = Agent('weather_domain.yml', policies = [MemoizationPolicy(max_history=2), KerasPolicy(max_history=4)])
            data = agent.load_data(training_data_file)
            agent.train(data)
            rasa_core.run.serve_application(agent ,channel='cmdline')
            #interactive.run_interactive_learning(agent, training_data_file)
            return agent 

if __name__ == '__main__':
    logging.basicConfig(level="INFO")
    nlu_interpreter = RasaNLUInterpreter('./models/nlu/default/weatherbot')
    #run_weather_online(ConsoleInputChannel(), nlu_interpreter)
    run_weather_online('cmdline', nlu_interpreter)

Output from Bot is not directed to the console

**********
NFO:rasa_core.policies.keras_policy:Done fitting keras policy model
INFO:root:Rasa Core server is up and running on http://localhost:5005
Bot loaded. Type a message and press enter (use '/stop' to exit):
Your input ->  Hello
Hello! How can I help?
127.0.0.1 - - [2019-05-14 00:09:00] "POST /webhooks/rest/webhook?stream=true&token= HTTP/1.1" 200 222 0.212841
Your input ->  how is weather in Italy
127.0.0.1 - - [2019-05-14 00:09:10] "POST /webhooks/rest/webhook?stream=true&token= HTTP/1.1" 200 154 0.009423
Your input ->  127.0.0.1 - - [2019-05-14 00:09:23] "GET / HTTP/1.1" 200 144 0.000800
127.0.0.1 - - [2019-05-14 00:09:32] "GET / HTTP/1.1" 200 144 0.000892
Your input ->  ok
127.0.0.1 - - [2019-05-14 00:10:07] "POST /webhooks/rest/webhook?stream=true&token= HTTP/1.1" 200 154 0.011861
Your input ->
********
What correction needs to be done to the code

**Comment by akelad** [comment]
What do you mean, I think your bot just isn't responding because you don't have enough training data.

Please post usage questions in our [forum](https://forum.rasa.com)

**Comment by shammy45** [comment]
Hi ,  I have sufficient training data, however as you see from teh dump, responses are not directed to the console, I am not sure how to direct the output of the bot to the console

**Comment by akelad** [comment]
but it is directed to the console:
```
Bot loaded. Type a message and press enter (use '/stop' to exit):
Your input -> Hello
Hello! How can I help?
```

**Comment by shammy45** [comment]
Thank you, was able to successfully execute in console

Best Regards
Shammy
