### ISSUE TITLE
update to slackclient 2.0

### ISSUE THREAD

**Issue by erohmensing** [RasaHQ/rasa#3464]
The version we have is supported through december 2019 but we should look into updating. Right now the only thing that looks to stop us is the question of python 3.5 support.

https://github.com/slackapi/python-slackclient/blob/master/docs-src/changelog.rst

https://github.com/slackapi/python-slackclient/issues/384

**Comment by erohmensing** [comment]
come back to this when https://github.com/RasaHQ/rasa/issues/4437 is implemented

**Comment by erohmensing** [comment]
@tmbo do i just add this to a project? or assign tobi to pick one?

**Comment by tmbo** [comment]
you can directly assign this to a project - if you are unsure where to put it you can alternatively assign tobias

**Comment by tmbo** [comment]
Removed the future label as we dropped py 3.5 support, so it should be possible now to update the dependency

**Comment by erohmensing** [comment]
Removed enhancement bc the one we're on isn't supported anymore so it really should be updated. Also is the `dependency` tag really only for PRs? Seems like it would be helpful for issues as well.

**Comment by tmbo** [comment]
we shouldn't use that, it is a relict from depandabot. I don't see a reason why we need to differentiate between maintenance and dependency right now.
