### ISSUE TITLE
Make bot utterances predicted by the mapping policy optionally revertible

### ISSUE THREAD

**Issue by erohmensing** [RasaHQ/rasa#3468]
the idea is to add a `revert` boolean field to the `triggers` field of the intent which would decide whether the triggered action should revert itself by returning a UserUtteranceReverted or not. This should apply for bot utterances and custom actions.

**Comment by hypernote** [comment]
That would be great!

**Comment by erohmensing** [comment]
@hypernote if you're looking for a workaround until this is implemented, check out this [forum post](https://forum.rasa.com/t/how-to-create-a-partially-rule-based-conversation-within-a-chat-dialogue/6418/13?u=erohmensing)

**Comment by hypernote** [comment]
Looks good, even with a lot more code =). Thanks so much, @erohmensing and have a great one!

**Comment by tmbo** [comment]
I don't think we should do this. There is a way to do this with a custom action, I think we should keep it that way for now and avoid introducing new properties to the domain.

**Comment by akelad** [comment]
@tmbo what about if you don't want to have to write a custom action every time you just want to send a simple message to the user?
