### ISSUE TITLE
Use rasa-core chatbots with many intents

### ISSUE THREAD

**Issue by JohnMal93** [RasaHQ/rasa#3477]
**Rasa version**:
rasa                0.1.1
rasa-core           0.13.7
rasa-core-sdk       0.12.2
rasa-nlu            0.14.6

**Python version**: 
Python 3.6.8

**Operating system** (windows, osx, ...):
macOS

**Issue**:
Hello everyone, 

In my Q&A chatbot that uses rasa-core, I have a number of different intents and also some entities that are shared between those intents (two intents could require the date entity for example). How can I use rasa-core to handle a user doing the following:

1) User message with intent but without providing the entity. The bot will prompt the user to enter the entity for that intent and then the user might just enter the entity only.

2) The user can change his mind and enter a message with a different intent at any time, even at times when he is prompted to just enter the missing entity (just as in the previous example). The new message's intent might require an entity as well. This entity could either be provided from the first time or, if it is missing, be entered after the bot prompts the user to. 

I know that users changing their intents should be handled in stories but I have multiple intents (more than 20) and I can't control/create stories for all the possible combinations of them, so I mainly just write one story for each intent. 

I also know how forms can be used to fill the missing slots/entities, but what if the entities are shared between the different intents? The examples I found always map entities to a single intent only like [here](https://blog.rasa.com/building-contextual-assistants-with-rasa-formaction/). But, the intents for my chatbot share entities amongst them. Also, in the chatbot, the user can skip filling the missing entity when prompted and just enter another message with a different intent and (possibly) a different entity type. 

I am facing a hard time trying to implement rasa-core in this way, and I think a number of people have some related issues, [example](https://forum.rasa.com/t/ask-for-missing-entity/9183/3), another [example](https://forum.rasa.com/t/how-to-call-a-form-action-from-another-form-action/7034) and also this [example](https://forum.rasa.com/t/how-to-configure-stories-and-actions-to-get-shared-requested-slots/7105). 

**Content of configuration file (config.yml)**:
```yml

pipeline:
- name: "nlp_spacy"
- name: "tokenizer_spacy"
- name: "intent_featurizer_count_vectors"
- name: "intent_entity_featurizer_regex"
- name: "intent_classifier_tensorflow_embedding"
- name: "ner_crf"

language: "en"
```

**Content of domain file (domain.yml)** (if used & relevant):
```yaml

```

**Comment by akelad** [comment]
Please ask these kind of questions in our [forum](https://forum.rasa.com)

**Comment by JohnMal93** [comment]
Thank you @akelad for replying. I noticed that the similar problems discussed in the forum [here](https://forum.rasa.com/t/ask-for-missing-entity/9183/3), [here](https://forum.rasa.com/t/how-to-call-a-form-action-from-another-form-action/7034) and [here](https://forum.rasa.com/t/how-to-configure-stories-and-actions-to-get-shared-requested-slots/7105), are not resolved. So I thought it might be more helpful to state the problem here and look for an answer that can help others who are facing the same issues.
