### ISSUE TITLE
Help to create a custom tracker store

### ISSUE THREAD

**Issue by Robertjbc** [RasaHQ/rasa#3480]
**0.14.4**:

**3.6**: 

*windows, osx, 

**Hi there, I am trying to create a Custom Tracker Store, cause i want to develoment a oracle application but i need to save the data

I have read Tracker Stores but I don’t understand the following:

How to extend the TrackerStore base class
Where to put my file that extends the TrackerStore base class
How to set the store_type in endpoints.yml to be the path to my module Class 4
Please can somebody show me examples of the above?

Many thanks

**:

**Comment by akelad** [comment]
Please ask these kind of questions in our [forum](https://forum.rasa.com)
