### ISSUE TITLE
NLU Training Problem

### ISSUE THREAD

**Issue by Rajskc** [RasaHQ/rasa#3482]
**Rasa version**: 0.1.1

**Rasa version**: 0.15.0

**Python version**: 3.7.3

**Operating system** (windows, osx, ...): windows

**Issue**: When Training the nlu model, I am getting below error:
Command used to train: python -m rasa_nlu.train -c spacy_pipeline.yml --data data/data.json -o models --fixed_model_name nlu --project current

"""
C:\Users\Julien\Anaconda3\lib\runpy.py:125: RuntimeWarning: 'rasa_nlu.train' found in sys.modules after import of package 'rasa_nlu', but prior to execution of 'rasa_nlu.train'; this may result in unpredictable behaviour
  warn(RuntimeWarning(msg))
Fitting 2 folds for each of 6 candidates, totalling 12 fits
[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.
[Parallel(n_jobs=1)]: Done  12 out of  12 | elapsed:    0.5s finished
Traceback (most recent call last):
  File "C:\Users\Julien\Anaconda3\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\Users\Julien\Anaconda3\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\Julien\Anaconda3\lib\site-packages\rasa_nlu\train.py", line 173, in <module>
    num_threads=cmdline_args.num_threads)
  File "C:\Users\Julien\Anaconda3\lib\site-packages\rasa_nlu\train.py", line 149, in train
    fixed_model_name)
  File "C:\Users\Julien\Anaconda3\lib\site-packages\rasa_nlu\model.py", line 237, in persist
    update = component.persist(file_name, dir_name)
TypeError: persist() takes 2 positional arguments but 3 were given
"""

**Content of configuration file (config.yml)**:
```
language: "en"

pipeline:
- name: "SpacyNLP"
- name: "SpacyTokenizer"
- name: "RegexFeaturizer"
- name: "SpacyFeaturizer"
- name: "CRFEntityExtractor"
- name: "SklearnIntentClassifier"
- name: "onto_parser"
```
I am using a custom component in nlu part.

**Comment by akelad** [comment]
I assume there's an issue with your `onto_parser`, can you make sure to update the `persist` function in there to only take the two arguments: `(file_name, dir_name)`

**Comment by Rajskc** [comment]
I updated the persist function. It's resolved now. Thanks a lot! Closing the issue.

**Comment by GraphGrailAi** [comment]
@akelad i have the same issue, tried to reimplement component from https://blog.rasa.com/enhancing-rasa-nlu-with-custom-components
```

    def persist(file_name, dir_name):
        """Pass because a pre-trained model is already persisted"""
        pass
```
but this change still produce an error. I removed def persist and training was completed

**Comment by rasaworkshop** [comment]
> @akelad i have the same issue, tried to reimplement component from https://blog.rasa.com/enhancing-rasa-nlu-with-custom-components
> 
> ```
> 
>     def persist(file_name, dir_name):
>         """Pass because a pre-trained model is already persisted"""
>         pass
> ```
> 
> but this change still produce an error. I removed def persist and training was completed

Even I am facing same issue

**Comment by aadiraju** [comment]
@rasaworkshop I changed my function definition to the following and it resolved the issue:
`def persist(self, file_name, model_dir):`
