### ISSUE TITLE
Pass an Image as RASA button payload

### ISSUE THREAD

**Issue by AnandDev8** [RasaHQ/rasa#3483]
**Rasa version**:

**Python version**: 

**Operating system** (windows, osx, ...):

**Issue**:
So how do i pass an image inside a button payload to my domain.yml
Example of domain.yml

templates:
   utter_ask_detail_report:
    - text: 'Could you please give a detailed report'
      buttons:
          - title: 'Hint'
            payload: **(Here i need to display an image when user press the hint button)**

In the above example when user press the hint button an image should be dispayed
Is something like this possible in domain.yml file?

**Content of configuration file (config.yml)**:
```yml

```

**Content of domain file (domain.yml)** (if used & relevant):
```yaml

```

**Comment by akelad** [comment]
Please ask these kind of questions in our [forum](https://forum.rasa.com)
