### ISSUE TITLE
please make sure you've installed the correct tensorflow version, listed in our requirements.txt (and compatible with your current version of rasa)

### ISSUE THREAD

**Issue by itsanshul** [RasaHQ/rasa#3488]
please make sure you've installed the correct tensorflow version, listed in our requirements.txt (and compatible with your current version of rasa)

_Originally posted by @akelad in https://github.com/RasaHQ/rasa/issues/3484#issuecomment-492997199_

------------------------------------------------------------------------------------------------

can you provide me with the latest requirements.txt. I am not able to find and also python or pip versions compatible

**Comment by akelad** [comment]
please don't duplicate issues, we'll keep the conversation in the other one
