### ISSUE TITLE
story retrieved by http API does not respect Story Data Format 

### ISSUE THREAD

**Issue by jeanveau** [RasaHQ/rasa#3497]
**Rasa version**:
0.13.3
**Python version**: 
3.6.5
**Operating system** (windows, osx, ...):
Ubuntu 16.04
**Issue**:

Hi, 

I'm using rasa core 0.13.3, according [this](https://rasa.com/docs/core/server/#operation/getStory) We can retrieve story by using HTTP API, but the story fetched can not be used in further training

this is the story data format on website:
```
## story
...
  - utter_ask_confirm
* affirm OR thankyou
  - action_handle_affirmation
```

and this is the story retrieved by API:
```
## story_name * intent_name: [](entity_name:value)[](entity_name:value)[](entity_name:value)[](entity_name:value)[](entity_name:value)[](entity_name:value) - 
...
```

I see in 0.14, this request send back the story in new format:

```
## story_00055028
* greet: hello
 - utter_ask_howcanhelp
* inform: I'm looking for a [moderately priced](price:moderate)  [Indian](cuisine) restaurant for [two](people) people
 - utter_on_it
 - utter_ask_location
```

but it isn't the right story format neither. I wonder is there a convenient way to retrieve the story in right format that I did not found, or this is a bug in rasa_core ?

thanks

**Comment by akelad** [comment]
i'm not quite sure what you mean with the "website"? you can use the endpoint, but only if you've got these stories stored somewhere. I would assume you don't when just running the rasa core server

**Comment by akelad** [comment]
i'm going to close this now because this is something that has changed in master

**Comment by jeanveau** [comment]
> i'm not quite sure what you mean with the "website"? you can use the endpoint, but only if you've got these stories stored somewhere. I would assume you don't when just running the rasa core server

By website I mean documentations: https://rasa.com/docs/core/stories/

The problem is I can't retrieve story in right format (described in [ https://rasa.com/docs/core/stories/]( https://rasa.com/docs/core/stories/) ) by using  `/conversations/{sender_id}/story`

Is this the only way to get the story ?

**Comment by akelad** [comment]
Should be yeah, but again this won't work with the current rasa core server by itself. You can try using master though, there you'll be able to do this
