### ISSUE TITLE
rasa_nlu duckling extractor: incorrect answer deserialization

### ISSUE THREAD

**Issue by marekkosta** [RasaHQ/rasa#3498]
**Rasa version**: rasa_nlu 0.15.0

**Python version**: 3.6.7

**Operating system** (windows, osx, ...): Ubuntu 18.04.2 LTS

**Issue**:
Answer from duckling is incorrectly deserialized.
The culprit is the method `DucklingHTTPExtractor._duckling_parse` and that in this method 
`return simplejson.loads(response.text)`
is used instead of
`return response.json()`

If extracted entities contain bodies with accents, incorrect deserialization is done by
the method simplejson.loads. The following script isolates and shows the problem:
```
import requests
import logging
from rasa_nlu.utils import configure_colored_logging
import simplejson


def main():
    url = 'http://localhost:5000/parse'
    payload = {
        'text': "9 metrů",
        'locale': 'cs_CS',
        'tz': None,
        'reftime': 1558015069000
    }
    headers = {"Content-Type": "application/x-www-form-urlencoded; charset=UTF-8"}
    response = requests.post(url, data=payload, headers=headers)
    d_1 = simplejson.loads(response.text)
    d_2 = response.json()
    print(d_1)
    print(d_2)
    if d_1 == d_2:
        print('EQUAL')
    else:
        print('NOT EQUAL')


if __name__ == '__main__':
    configure_colored_logging(logging.DEBUG)
    main()

```

The solution should be to use `response.json()` instead of `simplejson.loads` in the above-mentioned method `DucklingHTTPExtractor._duckling_parse`.

**Content of configuration file (config.yml)**:
```yml
irrelevant
```

**Content of domain file (domain.yml)** (if used & relevant):
```yaml
irrelevant
```

**Comment by akelad** [comment]
Thanks for raising this issue, @erohmensing  will get back to you about it soon.

**Comment by erohmensing** [comment]
Yes, you're right @marekkosta -- I thought it might just be stripping accents, but that doesn't seem to be the case. Thanks for the fix (and the helpful testing script)!
