### ISSUE TITLE
Ideas: multilingual models, training, personality - how to add

### ISSUE THREAD

**Issue by GraphGrailAi** [RasaHQ/rasa#3500]
**Rasa version**: 0.15
**Python version**: 3.6.8 anaconda
**Operating system** (windows, osx, ...): ubuntu 19.04
**Issue**:

Hi, i am new to Rasa, but not new to Ai dev.
I have experience docs and want to ask several questions that are not clear from docs and blog posts i read recently. Asked on forum, but no answer, i see most posts too

1) Why dont you use Polyglot python library for multilingual support of NER, sentiment, etc ?
https://pypi.org/project/polyglot/ 
For me its a crucial part when i try to choose what framework to use. Spacy is good, but little lang supported.
Is there a simple path to implement Polyglot?

    Tokenization (165 Languages)
    Language detection (196 Languages)
    Named Entity Recognition (40 Languages)
    Part of Speech Tagging (16 Languages)
    Sentiment Analysis (136 Languages)
    Word Embeddings (137 Languages)
    Morphological analysis (135 Languages)
    Transliteration (69 Languages)

2) Can i use non-official language pack for Rasa, for example this for RU: https://github.com/buriy/spacy-ru/  ?

3)  Rule-based bot is bad approach, i agree with level 5 paradigm from blog, but cannot find extensive tutorial how do i implement pretrained models for my language as a helpers and then supply these with domain-trained model on LSTM from Rasa core
Take  a look https://github.com/Desklop/Voice_ChatBot
here several bin pretrained models, how do i integrate them to get Ai bot up and running, no teaching from zero.
i need a bot that GENERATE answers, not stupid repeat from list of predefined

4) Personality: how do i add personality to bot, to be able reproduce character and general knowledge and skills? I mean emotional bot, not business, example: https://github.com/jddunn/emoter

**Content of configuration file (config.yml)**:
```yml
language: "ru"

pipeline: pretrained_embeddings_spacy

**Comment by akelad** [comment]
Hi @GraphGrailAi most of these questions belong on the forum, and someone will get back to you there eventually.
As for polyglot, we've never looked into that yet. However, you can use any sort of word vectors you want. So for example you can use the fast text vectors and load those into your model.
Alternatively our `supervised_embeddings` pipeline can be used for any language.

I'm gonna close this as we can have further discussions on the forum
