### ISSUE TITLE
Training model from checkpoint in RASA NLU

### ISSUE THREAD

**Issue by spiralswimmer** [RasaHQ/rasa#3509]
**Issue**:
For very large datasets training the model can take a lot of time. Currently with 380,000 data points my RASA NLU takes over 2 hours. A lot of problems with that as my actual production data set would be even bigger than that. 

Looked inside the library but didn't really find any method/option to continue training on top of an existing model. Would be much better to generate models iteratively

**Comment by akelad** [comment]
This isn't possible with the libraries we use right now. We are working on speeding up rasa nlu training/making it less memory intensive though.
Can I ask why you have 380,000 examples? how many intents do you have?

**Comment by spiralswimmer** [comment]
Reasons for these many data points: 

1. We have two intents but query shapes that have multiple entities of the same type (think of a grocery list with multiple products, counts and brands). 

2. The product list is around 400-500 products which leads to 10s of millions of combinations, we are using chatito to generate synthetic data. 

3. To make it work we used a subset of all possibilities because chatito cannot generate the entire training data without requiring significant changes and training time was too much. 

As per our last set of testing even the subset is working fine but we aren't sure how little is too little.

**Comment by amn41** [comment]
I would highly recommend you switch to using [lookup tables](https://blog.rasa.com/improving-entity-extraction/) instead for extracting your entities.

especially for just 2 intents there is no need to generate so much synthetic data.
