### ISSUE TITLE
Executing more than 10 actions in a story

### ISSUE THREAD

**Issue by gunagg** [RasaHQ/rasa#3514]
rasa-core           0.13.7   
rasa-core-sdk       0.12.2   
rasa-nlu            0.14.6  

**Python version**:  3.6.6

**Operating system** (windows, osx, ...): OSX

**Issue**: I want to execute more than 10 actions for an intent in a story, is there a way to do this without introducing action_listen?

**Content of configuration file (config.yml)**:
```yml

```

**Content of domain file (domain.yml)** (if used & relevant):
```yaml

```

**Comment by akelad** [comment]
Please ask these kind of questions in our [forum](https://forum.rasa.com)
