### ISSUE TITLE
Intents training 

### ISSUE THREAD

**Issue by mandarsuryavanshi** [RasaHQ/rasa#3536]
**Rasa version**:

**Python version**: 3.7.4

**Operating system** (windows, osx, ...):WIndows10

**Issue**:
Warning: Intent 'story' has only 1 training examples! Minimum is 2, training may fail.
  self.MIN_EXAMPLES_PER_INTENT))

**Content of configuration file (config.yml)**:
```yml

```

**Content of domain file (domain.yml)** (if used & relevant):
```yaml

```

**Comment by akelad** [comment]
Please fill out the issue template

**Rasa Core version**:

**Python version**: 

**Operating system** (windows, osx, ...):

**Issue**:



**Content of domain file** (if used & relevant):
```yaml

```
