### ISSUE TITLE
Check for duplicate data before dumping from IL

### ISSUE THREAD

**Issue by erohmensing** [RasaHQ/rasa#3540]
Ideally, we wouldn't add duplicate data to the NLU data or to stories. Related code: [https://github.com/RasaHQ/rasa_core/pull/1651](https://github.com/RasaHQ/rasa_core/pull/1651) – we should also remove events added by IL as well as any unfeaturized slot events, etc. before comparing for whether stories are equal or not.

**Comment by MetcalfeTom** [comment]
Probably best to attack the NLU via this and close two issues: https://github.com/RasaHQ/rasa/issues/1446

**Comment by erohmensing** [comment]
I reckon the code for these will probably be re0used from https://github.com/RasaHQ/roadmap/issues/456

**Comment by erohmensing** [comment]
check if this is still the case
