### ISSUE TITLE
Run New RASA X

### ISSUE THREAD

**Issue by yaput** [RasaHQ/rasa#3541]
**Rasa version**: Rasa 1.0

**Python version**: 3.6

**Operating system** (windows, osx, ...): OSX

**Issue**:
```
pip install rasa-x
Requirement already satisfied: rasa-x in /Users/bluelogic2/anaconda3/envs/bluebot2/lib/python3.6/site-packages (0.0.0)
```

But when i tried `rasa x` command got:
```
rasa x
Rasa X is not installed. The `rasa x` command requires an installation of Rasa X
```

**Content of configuration file (config.yml)**:
```yml

```

**Content of domain file (domain.yml)** (if used & relevant):
```yaml

```

**Comment by amn41** [comment]
hi @yaput ! the correct install command is:

```
pip install rasa-x --extra-index-url https://pypi.rasa.com
```

**Comment by yaput** [comment]
hi @amn41 
```
pip install rasa-x --extra-index-url https://pypi.rasa.com
Looking in indexes: https://pypi.org/simple, https://pypi.rasa.com
Requirement already satisfied: rasa-x in /Users/bluelogic2/anaconda3/envs/bluebot2/lib/python3.6/site-packages (0.0.0)
```
Yup did that already before

**Comment by plattenschieber** [comment]
It seems that your pypicloud return a version with the tag `0.0.0`:

``` 
pip install rasa-x --extra-index-url https://pypi.rasa.com --no-cache-dir
Looking in indexes: https://pypi.org/simple, https://pypi.rasa.com
Collecting rasa-x
  Downloading https://files.pythonhosted.org/packages/00/90/7b46d9b6b5ac1174113f87644d97b1111100043079e86d68e6d305876fc1/rasa_x-0.0.0-py3-none-any.whl
Installing collected packages: rasa-x
Successfully installed rasa-x-0.0.0
```

Trying to install the version `0.19.0` directly doesn't work either: 
```
pip install -Iv rasa-x==0.19.0 --extra-index-url https://pypi.rasa.com --no-cache-dir     
Could not find a version that satisfies the requirement rasa-x==0.19.0 (from versions: 0.0.0, 0.0.1)
No matching distribution found for rasa-x==0.19.0

```

**Comment by akelad** [comment]
@plattenschieber sorry about this the installation url in the docs was wrong, we've updated this  now and it'll get pushed shortly. This is the correct installation command:
`pip install rasa-x --extra-index-url https://pypi.rasa.com/simple`

**Comment by plattenschieber** [comment]
Did you already fix this @amn41? I just got the RuntimeError indicating to use the following way: 
```
raise RuntimeError('Please use `pip install rasa-x -i https://pypi.rasa.com/simple` instead to install the rasa-x package')
```
So `pip install rasa-x -i https://pypi.rasa.com/simple` seems to work for me.

**Comment by akelad** [comment]
@plattenschieber yes we did, we commented at the same time  :D i'll leave this open until the new docs are published

**Comment by plattenschieber** [comment]
👍  😄

**Comment by tuanvuvo** [comment]
Working 

pip install rasa-x --extra-index-url https://pypi.rasa.com/simple

Thanks @akelad

**Comment by akelad** [comment]
will close now as docs have been pushed

**Comment by GhadyAlhamad** [comment]
Actully for me not working:

`pip install rasa-x --extra-index-url https://pypi.rasa.com/simple
Looking in indexes: https://pypi.org/simple, https://pypi.rasa.com/simple
Requirement already satisfied: rasa-x in c:\programdata\miniconda3\envs\hellorasa\lib\site-packages (0.0.1)`

please help
