### ISSUE TITLE
Validate domain file for repeat intents, entities, slots

### ISSUE THREAD

**Issue by erohmensing** [RasaHQ/rasa#3544]
sql for `rasa-x` does not like this. we should validate on training and also before upload to rasa x.

**Comment by erohmensing** [comment]
currently in rasa, you can have templates with no - text properly if they don't have any other properties, as they just get turned into text ones in the processing. But this throws an issue when loading the domain into rasa x: https://forum.rasa.com/t/error-while-running-rasa-x-command/10173

I think the better way to handle this is to just deprecate the ability to provide templates without the text attribute, instead of also working to handle this in rasa x

**Comment by tmbo** [comment]
Why isn't rasa x just using the rasa way of loading the domain, normalizing it on the way?

**Comment by erohmensing** [comment]
@tmbo i have no idea, you'd have to ask whoever implemented that in rasa x

**Comment by tmbo** [comment]
I guess that might be @ricwo

**Comment by erohmensing** [comment]
@tabergma this can be closed right?

**Comment by tabergma** [comment]
closed via https://github.com/RasaHQ/rasa/pull/3601
