### ISSUE TITLE
Rasa NLU + Rasa Core AWS Cloud 9 Deploy

### ISSUE THREAD

**Issue by itsanshul** [RasaHQ/rasa#3547]
I have deployed my local rasa files to AWS and having many dependency errors. EC2 is running python 2.7 and i have used 3.6.1. I cannot update pip to 10.0.1 . Several more errors are being faced . Can you provide me a quick solution?

Thank you in advance

**Comment by akelad** [comment]
Please ask these kind of questions in our [forum](https://forum.rasa.com)
