### ISSUE TITLE
add a flag to disable plotting confusion matrix in test

### ISSUE THREAD

**Issue by Ghostvv** [RasaHQ/rasa#3549]
**Rasa version**: `master`

**Python version**: `3.7`

**Operating system** (windows, osx, ...): `macos`

**Issue**:
Plotting confusion matrix can be time consuming and sometimes we don't care for it, therefore it makes sense to add an option to ignore the plot. Also, for nlu, I think it is better to create pdf directly instead of creating matplotlib windows first (it doesn't work on gcloud from terminal)

in case of `--debug` option, still turn off matplotlib debug

Another thing right now confusion matrix is unreadable (at least for core), color boxes and numbers are not aligned, also numbers overlay:
![story_confmat](https://user-images.githubusercontent.com/4136956/58162483-8d510280-7c82-11e9-9ae3-3c860cd9c4b9.jpg)

**Comment by degiz** [comment]
I've tested current (master) behaviour in our docker image (that would pick up Matplotlib TkAgg backend), here are results:
1. "rasa test nlu" renders confmat.png and hist.png, no issues with pup-up window
2. "rasa test coe" renders story_confmat.pdf, no issues pop-up window

On Mac OS I also don't have any pop-ups for both of the commands.
So if there was an issue with creating pop-up window on headless environments, it's not there anymore.

So I'd suggest that this ticket's goal is to introduce "--no-plot" flag with default value set to "false" that would completely skip rendering of confusion matrix and histogram.

@Ghostvv if there's an issue with readability of confusion matrix I think we should create a separate "enhancement" issue and track it separately.

**Comment by Ghostvv** [comment]
sure, we should tackle them separately

**Comment by wochinge** [comment]
@degiz moved this to `review-required`
