### ISSUE TITLE
Passing custom pipeline through during train for Rasa v0.15

### ISSUE THREAD

**Issue by xueyongg** [RasaHQ/rasa#3551]
Rasa version: 0.15-full

was trying to pass my custom pipeline through along with my training data as such:
```
"language: "${language}"

pipeline:
- name: "JiebaTokenizer"
- name: "RegexFeaturizer"
- name: "CRFEntityExtractor"
- name: "EntitySynonymMapper"
- name: "CountVectorsFeaturizer"
- name: "EmbeddingIntentClassifier"

data: {
    "rasa_nlu_data": {
        "common_examples": "<stringified examples>"
    }
}"
```
And it returned me this error:

```
<span>rasa_nlu.config.InvalidConfigError</span>: <span>No pipeline specified and unknown pipeline template '-&#160;name:&#160;"JiebaTokenizer" -&#160;name:&#160;"RegexFeaturizer" -&#160;name:&#160;"CRFEntityExtractor" -&#160;name:&#160;"EntitySynonymMapper" -&#160;name:&#160;"CountVectorsFeaturizer" -&#160;name:&#160;"EmbeddingIntentClassifier"' passed. Known pipeline templates: pretrained_embeddings_spacy, keyword, supervised_embeddings</span>
```
based on the the documentation from http://legacy-docs.rasa.com/docs/nlu/choosing_pipeline/

I understand we can declare custom pipeline when we pass our training data through? But am encountering error. Hope to hear from you soon!

**Comment by akelad** [comment]
what command were you using for training?

**Comment by xueyongg** [comment]
im using http post /train, and sending this information as the request body.

**Comment by akelad** [comment]
@tmbo is this a bug? this is in version 0.15 of rasa_nlu

**Comment by xueyongg** [comment]
May i know what is the status for this issue? (:

**Comment by tmbo** [comment]
didn't have time yet to take a closer look at this. would it be possible for you to check if the issue persists with 1.0 ? would be good to know if we already fixed this.

**Comment by xueyongg** [comment]
version 1.0 does not support the concept of projects in which is crucial for our usecase. The ability to create custom pipelines on v0.15 would be really useful

**Comment by akelad** [comment]
@xueyongg i don't think projects is related to this issue. And I'm not sure what you mean about creating custom pipelines? Please create a new issue in any case, as this one is old and related to rasa 0.15

**Comment by sahibpreetsingh12** [comment]
what?
