### ISSUE TITLE
Geeting error while running rasa x and rasa init commands

### ISSUE THREAD

**Issue by NomanSaleem4** [RasaHQ/rasa#3553]
**Rasa version**: 1.0.1

**Python version**: 3.6.7

**Operating system** (windows, osx, ...): Ubuntu

**Issue**: Getting the error i while running the command rasa init and rasa x . screen shot attached
![a](https://user-images.githubusercontent.com/17758473/58170797-e4b89800-7cad-11e9-81c8-528cee42c9be.png)

and secondly, should we uninstall the rasa core and nlu now?

**Comment by markusgl** [comment]
I was able to fix this error by adjusting my project directory to meet the structure as described here: https://blog.rasa.com/rasa-x-getting-started-as-a-current-rasa-user/
(in my case I had to rename the formerly named nlu_config.yml to config.yml)

**Comment by erohmensing** [comment]
Glad you figured it out. That `config.yml` should include any policies you have, by the way! (So e.g. if you previously had a `nlu_config.yml` and a `core_config.yml`, just copy the policies into the new config.

**Comment by NomanSaleem4** [comment]
oh Thanks, and why can't i run the rasa init command?

**Comment by erohmensing** [comment]
Oh my I'm sorry, I didn't notice that error above, was only looking at the red one on the bottom.

Can you try setting the environment variable `PYTHONIOENCODING='utf8'`?

**Comment by NomanSaleem4** [comment]
sure let me try

**Comment by NomanSaleem4** [comment]
i tried PYTHONIOENCODING='utf8' but it didnt work, will try others as well.

also should we uninstall the rasa core and nlu now?
and how shall we replace the following imports ?

 `from rasa_core import utils
from rasa_core.agent import Agent
from rasa_core.featurizers import BinarySingleStateFeaturizer, MaxHistoryTrackerFeaturizer
from rasa_core.policies import FormPolicy
from rasa_core.policies.keras_policy import KerasPolicy
from rasa_core.policies.memoization import MemoizationPolicy
from rasa_core.policies.two_stage_fallback import TwoStageFallbackPolicy`

**Comment by erohmensing** [comment]
You can also try putting it directly in the command, like:
```
PYTHONIOENCODING='utf8' rasa init
```
thank you for testing for me!

**Comment by NomanSaleem4** [comment]
It worked this way. may be i was doing something wrong. Thanks.
and should i create a new issue for the concerns in the previous message or you can answer in this thread?

**Comment by NomanSaleem4** [comment]
now
![c](https://user-images.githubusercontent.com/17758473/58187813-f495a380-7cd0-11e9-917f-9a85f7edd7f8.png)
 the link is not working for rasa x

**Comment by erohmensing** [comment]
What do you mean by the link is not working, what happens if you copy and paste it? (it is actually supposed to pop up)

**Comment by NomanSaleem4** [comment]
it doesn't work not even popped up

**Comment by NomanSaleem4** [comment]
i think there is aneed of alot of improvements for still. i am going back to rasa==0.1.1 for now. will be happy to use rasa 1.0.1 with rasa x once it gets stable

**Comment by erohmensing** [comment]
When you said "it doesn't even work" what exactly does it show? And yes actually please create a new issue for this so that we can track it.

**Comment by Sonia2016** [comment]
I have kind of the same issue:

> 
d-172-25-16-132:chatbot soniabaee$ rasa init
Welcome to Rasa! 🤖

To get started quickly, an initial project will be created.
If you need some help, check out the documentation at https://rasa.com/docs/rasa.
Now let's start! 👇🏽

Traceback (most recent call last):
  File "/Users/sonia/anaconda3/bin/rasa", line 10, in <module>
    sys.exit(main())
  File "/Users/sonia/anaconda3/lib/python3.6/site-packages/rasa/__main__.py", line 70, in main
    cmdline_arguments.func(cmdline_arguments)
  File "/Users/sonia/anaconda3/lib/python3.6/site-packages/rasa/cli/scaffold.py", line 179, in run
    default=".",
AttributeError: 'Question' object has no attribute 'skip_if'

>
