### ISSUE TITLE
Tensorflow version incompatibility with centOS

### ISSUE THREAD

**Issue by pnandhini11** [RasaHQ/rasa#3556]
**Rasa version**: 0.14.4

**Python version**: 3.6

**Operating system** (windows, osx, ...): centOS 7

**Issue**:  Recently we moved from Windows to Cent OS server. Until then we were using tensorflow 1.13version. But after moved to Cent OS, during installation there was an incompatibility between tensorflow and OS. Because of it we installed tensorflow 1.12.   Is there any issue in future using this tensorflow version? Please confirm.   

**Content of configuration file (config.yml)**:
```yml

```

**Content of domain file (domain.yml)** (if used & relevant):
```yaml

```

**Comment by akelad** [comment]
tensorflow 1.12 doesn't support python 3.7, but i think you should probably be fine with 1.12 on py36
