### ISSUE TITLE
botframework not working with Rasa 1.0.1

### ISSUE THREAD

**Issue by ice2tricky** [RasaHQ/rasa#3557]
**Rasa version**:
1.0.1
**Python version**: 
3.7.3
**Operating system** (windows, osx, ...):

**Issue**:
None of the botframework channels are working. I am getting this issue since new Rasa release.
It receives the response good, but something is not handling it good.

![image](https://user-images.githubusercontent.com/31984496/58185448-6232d700-7cb3-11e9-9561-e5d6d4ce293d.png)

**Content of configuration file (config.yml)**:
```yml

```

**Content of domain file (domain.yml)** (if used & relevant):
```yaml

```

**Comment by akelad** [comment]
Thanks for raising this issue, @erohmensing  will get back to you about it soon.

**Comment by erohmensing** [comment]
Hey there @ice2tricky, I'm sorry for the late response. This seems to be a bug that showed up when we switched request types from flask to Sanic. Do you get any more information from that error message, for example, an error traceback or anything like that? I notice you're running in heroku -- any chance you could try to run it locally using `rasa run --connector botframework` to see if there's any more error information in the rasa server?

**Comment by ice2tricky** [comment]
This is what I get when running locally
![image](https://user-images.githubusercontent.com/31984496/58419437-e528a880-808a-11e9-9758-a2e1b8cece13.png)

**Comment by erohmensing** [comment]
Great thank you, that's actually really helpful, looks like we missed a few `awaits`, we'll get on to fixing this! 

In the meantime, if you're looking for a temporary fix, you can try adding the word `await` before any calls of `self.prepare_message()` in `rasa/core/channels/botframework.py`. So that would be e.g. in line 111:
```python3
message = self.prepare_message(recipient_id, text_message)
```
would become 
```
message = await self.prepare_message(recipient_id, text_message)
```
then the same in lines 123, 139, and 145. 

Then let me know if you run into any other problems :)

**Comment by ice2tricky** [comment]
Not working, now i'm getting this. 
![image](https://user-images.githubusercontent.com/31984496/58421755-20c67100-8091-11e9-8304-2d3129748c3e.png)

**Comment by erohmensing** [comment]
Hmm, you'll probably need the entire fix then, I'm sorry about that. We'll have to test it on our own instance of a botframework bot. That's the only error you got -- no errors from rasa?

**Comment by ice2tricky** [comment]
It broke the code, so it’s normal to get just this error.

**Comment by erohmensing** [comment]
Yes but in this case, we're still using flask requests to get the headers and send the message so I'm surprised the payload has changed. Ah well, I'll get on to fixing it and make sure that it's all working -- sorry there's no quick fix at the moment then.

**Comment by ice2tricky** [comment]
It's ok, for me there is no rush on it.

**Comment by tmbo** [comment]
@erohmensing did you already get around fixing this?

**Comment by erohmensing** [comment]
@tmbo I havent, as I haven't had time to set up a botframework bot to test

**Comment by 1tupac** [comment]
Hi there! Are you using templates or actions? Rasa recently introduced some changes to the dispatcher and depreciated some methods that don't work with BotFramework connector.

**Comment by ice2tricky** [comment]
ofcourse I am using templates and actions

**Comment by 1tupac** [comment]
None of them work are working? I'm working with Rasa 1.1.8 and everything works fine. Did you try to update Rasa?

**Comment by ice2tricky** [comment]
have to check again, it's been a while since I tested the botframework connector

**Comment by erohmensing** [comment]
If @1tupac is able to use it fine, I will close this. @ice2tricky if you try again and update to the latest vesion and still run into problems, let us know
