### ISSUE TITLE
The links added to the utter template action is not displaying as link in slack channel

### ISSUE THREAD

**Issue by anoop2503** [RasaHQ/rasa#3562]
**Rasa version**: rasa==1.0.1

**Python version**: Python 3.6.7

**Operating system** (windows, osx, ...):
Distributor ID: Ubuntu
Description: Ubuntu 18.04.2 LTS
Release: 18.04
Codename: bionic

**Issue**:
If you add a template utter action with a link in the text, the link is displaying as plain text in the slack channel. This was showing correctly as hyperlink in the rasa_core version. 

For Ex:

```
templates:
  utter_rasa_url:
    - text: "Hey, this is the url of rasa \n  https://github.com/RasaHQ/rasa/issues"
```

Kindly note that I have to display it as two lines. The first line will only display the text "Hey, this is the url of rasa"  and the second line will display the url "https://github.com/RasaHQ/rasa/issues". In this case, the url should actually be displayed as hyperlink.  

I am using slack integration and this was working correctly, if you check the rasa_core 0.14 versions. Please let me know, if this is a configuration issue only.

**Comment by akelad** [comment]
Thanks for raising this issue, @erohmensing will get back to you about it soon.

**Comment by erohmensing** [comment]
Not a configuration issue, I can see where this is going wrong, it's another block thing 😅Thanks!

**Comment by anoop2503** [comment]
yes found that the block is using "plain_text" type. Thanks for fixing it  :)

**Comment by anoop2503** [comment]
In btw, it will be really helpful, if you could answer a [question](https://forum.rasa.com/t/customize-slack-integration-code/10317) which I have asked in the forum. Expecting your help on this case. Thanks in adv :)
