### ISSUE TITLE
 The slack displays only around 89 characters in one line and remaining characters are break to next line

### ISSUE THREAD

**Issue by anoop2503** [RasaHQ/rasa#3565]
**Rasa version**: rasa==1.0.1

**Python version**: Python 3.6.7

**Operating system** (windows, osx, ...):
Distributor ID: Ubuntu
Description: Ubuntu 18.04.2 LTS
Release: 18.04
Codename: bionic

**Issue**:
It seems like now the slack displays max of 89 characters in a line and the remaining characters break to the next line. This was working fine without any issues in the rasa_core 0.14 versions.
In the case of plain text bot response, we may not consider this as a big issue.  But if the bot response has any hyperlink and a break in between that link may not be appearing as good. Hence, it would be great, if we can fix this in the codebase (if possible) :)

**Comment by akelad** [comment]
Thanks for raising this issue, @erohmensing  will get back to you about it soon.

**Comment by erohmensing** [comment]
Yes, this is one of the bugs related to the new blocks. I'm going to check out these bugs today and clean them up. When you say it was working before, how do you mean -- did it break to the new line on spaces?
