### ISSUE TITLE
how can specified nlu model path in 'rasa shell or rasa run '?

### ISSUE THREAD

**Issue by rockey2016** [RasaHQ/rasa#3566]
**Rasa version**:
rasa 1.0.1
**Python version**: 
python=3.7.3
**Operating system** (windows, osx, ...):
os=ubuntu
**Issue**:
I use commands {rasa train, rasa run} in my own project reffered to the document,it works ok.
In old release,nlu and core model can be trained sepreately,then use 'python -m rasa_core.run -d {core-modle} -u {nlu-model} --endpoints endpoints.yml'. However,new release i can also train two models sepreately,i cannot run then together.My question is:
how can i specified the nlu model path parameter in  such commands 'rasa shell or rasa run'?

**Comment by akelad** [comment]
@rockey2016 you should train your core and NLU models together, you can't load up separate ones anymore. Running `rasa train` in the directory where all your data lives will create a packaged model of both. Does that help?
