### ISSUE TITLE
HTTP train endpoint not displaying body

### ISSUE THREAD

**Issue by lizembo** [RasaHQ/rasa#3568]
**Rasa version**:  1.0.1    

**Python version**: 3.6.8

**Operating system** (windows, osx, ...): osx

**Issue**: 

I am trying to Train a Rasa model using the HTTP /train endpoint as documented [here](http://rasa.com/docs/rasa/api/http-api/#tag/Model).

I am not sure what to pass in as the JSON Body to the requess as Swagger or OpenAPI is not showing correctly. It is just displaying the Schema references `“$ref”: “#/components/examples/TrainingRequest”` rather than the actual JSON body.

Is it possible for this to be corrected please?

Many thanks,
Liz

**Comment by akelad** [comment]
i'll close this then since we already have an issue for it :D
