### ISSUE TITLE
No response received in slack, if there is a delay in custom action execution

### ISSUE THREAD

**Issue by anoop2503** [RasaHQ/rasa#3569]
**Rasa version**: rasa==1.0.1

**Python version**: Python 3.6.7

**Operating system** (windows, osx, ...):
Distributor ID: Ubuntu
Description: Ubuntu 18.04.2 LTS
Release: 18.04
Codename: bionic

**Issue**:
If there is a delay (say 3 seconds) in executing a logic written in a custom action, then no response will be sending back to the slack channel after executing that custom action.

Steps to reproduce the issue?
  - Integrate to slack
  - Create a custom action with three minutes delay for executing the logic (easy way is to add time.sleep(3))
  - Then execute dispatcher.utter_message
  - Now, test it from slack and check the server logs. It keeps trying to execute the same custom action multiple times due to the timeout and no response will be sending back to slack.

  This is mainly affecting some scenario where we need custom action to call some third party APIs, since it may takes more than 2 seconds to get response from third party APIs. In this case, it continuously executing the same custom action and multiple API calls being made to the third party service. Kindly let me know, if there any way to avoid this situation, when creating custom actions.

Please let me know, if you need anymore details.

**Comment by akelad** [comment]
Thanks for raising this issue, @erohmensing  will get back to you about it soon.

**Comment by erohmensing** [comment]
First of all, thanks so much for all the feedback on the slack channel! Clearly there are a few more adjustments we have to make as of switching to slack's new "blocks". This is an interesting problem that might need discussion, because the timeout is there to help it handle cases where something goes wrong, so we do want it there. However I've run into a similar problem where if a custom action takes a long time, the post will actually come in twice. So clearly there is an issue with our current timeout, just don't know if I would feel comfortable getting rid of it completely (but it's hard to choose a timeout since custom actions can take an arbitrary amount of time 🤔)

**Comment by anoop2503** [comment]
Thank you @erohmensing. 

Yes, I too had faced the same issue that the messages are being posted to slack multiple times, if there is any delay in the response from custom action, but with rasa_core version only. I had raised an [issue](https://github.com/RasaHQ/rasa/issues/3340) for that.  

I completely agree that we can't avoid the timeout mechanism, but would like to know if there anyway to increase that timeout value atleast. Just like a configuration settings :)

**Comment by akelad** [comment]
@erohmensing how long is the timeout right now?

**Comment by erohmensing** [comment]
@akelad looks like 3 seconds: https://api.slack.com/events-api (search "error handling", "http_timeout")

**Comment by tmbo** [comment]
I mean instead of waiting for the action to complete we can also respond to slack that we received the message and then do the action handling async to avoid a timeout. this might also be an issue for other channels.

**Comment by anoop2503** [comment]
@tmbo Not sure, if that is so easy to respond to slack as you mentioned, at least for some cases. For example, if you are planning to create a FormAction to collect some inputs from the user and  call an external API with these user inputs and then finally respond back to slack with the result of API execution. In this case, we may not be able to send a response back to slack in between the form utter_ask actions and API call. I believe, even if you add an utter_message action before performing the API call, the despatcher won't respond to slack immediately only with that utter_message. I think it will still wait for finishing the API execution and sends the output back to slack with all responses (utter_message + API response message)

**Comment by cyrilthank** [comment]
@anoop2503  can you please share the workaround you are using
please feel free to email me at cyril_thank@yahoo.com

**Comment by erohmensing** [comment]
No response received and multiple responses should be fixed now, tested with a 30s sleep action. @anoop2503 please let me know if you are still running into issues
