### ISSUE TITLE
swagger API spec is not rendering references

### ISSUE THREAD

**Issue by erohmensing** [RasaHQ/rasa#3572]
Eg [here](http://rasa.com/docs/rasa/api/http-api/#tag/Model/paths/~1model~1train/post):

<img width="498" alt="Screen Shot 2019-05-23 at 15 52 55" src="https://user-images.githubusercontent.com/22333512/58258337-d84a4300-7d72-11e9-9200-6acf76848f72.png">

**Comment by lizembo** [comment]
Is the example body available anywhere else? 

This is blocking us from using the `/model/train` endpoint at the moment as I not sure what format to send the data in.

**Comment by jamallij** [comment]
not resolved yet

**Comment by tmbo** [comment]
This is resolved, but not released yet.
