### ISSUE TITLE
How to invoke a custom action inside another custom action?

### ISSUE THREAD

**Issue by aditya-xq** [RasaHQ/rasa#3574]
**Rasa version**: 1.0.1

**Python version**: 3.6.4

**Operating system** (windows, osx, ...): Windows

**Issue**: Suppose if I have an if-else statement inside a custom action and want to call another custom action if a particular condition is met, how do I call/invoke that other custom action inside that if condition?

**Content of configuration file (config.yml)**:
```yml

```

**Content of domain file (domain.yml)** (if used & relevant):
```yaml

```

**Comment by akelad** [comment]
Please ask these kind of questions in our [forum](https://forum.rasa.com)
