### ISSUE TITLE
No module named 'rasa_nlu.converters'; 'rasa_nlu' is not a package   or   No module named 'rasa_nlu.training_data'; 'rasa_nlu' is not a package

### ISSUE THREAD

**Issue by gadisridhar** [RasaHQ/rasa#3575]
**Rasa version**: 0.14.6

**Python version**:  3.5.4

**Operating system** (windows, osx, ...): windows 10

**Issue**:
Have tried and tested all the versions of rasa-nlu with no success. sources say upgrade and downgrade. 

ISSUE -
No module named 'rasa_nlu.converters'; 'rasa_nlu' is not a package  

 or   

No module named 'rasa_nlu.training_data'; 'rasa_nlu' is not a package

**Content of configuration file (config.yml)**:
```yml
{'pipeline': 'spacy_sklearn'}
```

Wanted to use rasa-nlu to build models which can be further interpreted for classification.

Anyone going through this issue, kindly help.

Many Thanks  
Thumbs High

**Comment by akelad** [comment]
@gadisridhar it looks like something went wrong with your installation, because rasa_nlu doesn't seem to be installed properly. How did you install it?

**Comment by gadisridhar** [comment]
@akelad Thank u for the response. I have installed rasa_nlu using - pip install rasa_nlu. this installed Rasa version - 015.0 currently i am using rasa-nlu - 0.15.0, python - 3.5.4.

**Comment by tmbo** [comment]
Can you check what `pip show rasa_nlu` prints? And while you are at it, please also check `pip show rasa` and `pip show rasa_core`

**Comment by gadisridhar** [comment]
Thanks @tmbo for your reply.  details for
1. pip show rasa_nlu 
Name: rasa-nlu
Version: 0.14.4
Summary: Rasa NLU a natural language parser for bots
Home-page: https://rasa.com
Author: Rasa Technologies GmbH
Author-email: hi@rasa.com
License: Apache 2.0
Location: d:\vinci3\vinci\mlengine\venv1\lib\site-packages
Requires: future, gevent, typing, tqdm, numpy, klein, simplejson, requests, boto3, matplotlib, six, ruamel.yaml, jsonschema, cloudpickle, scikit-learn, packaging, coloredlogs
Required-by: rasa-core


2. Name: rasa-core
Version: 0.14.4
Summary: Machine learning based dialogue engine for conversational software.
Home-page: https://rasa.com
Author: Rasa Technologies GmbH
Author-email: hi@rasa.com
License: Apache 2.0
Location: d:\vinci3\vinci\mlengine\venv1\lib\site-packages
Requires: gevent, fakeredis, slackclient, scipy, fbmessenger, pydot, pymongo, flask-jwt-simple, mattermostwrapper, scikit-learn, python-telegram-bot, tensorflow, tqdm, numpy, rocketchat-
API, webexteamssdk, rasa-nlu, colorclass, flask, python-socketio, questionary, jsonpickle, python-dateutil, redis, ruamel.yaml, packaging, pytz, twilio, requests, jsonschema, typing, col
orhash, networkx, coloredlogs, pika, terminaltables, pykwalify, rasa-core-sdk, flask-cors, apscheduler
Required-by:

**Comment by tmbo** [comment]
This looks perfectly fine. What does `python -c "import rasa_nlu; print rasa.nlu.__version__"` say?

**Comment by tmbo** [comment]
Which command are you running to train a model? It looks a lot like you are running that with the wrong python interpreter in the wrong environment (basically in an env where rasa_nlu is not installed).

**Comment by royhuang9** [comment]
I encountered this same issue today. After two hour struggling, I even wrote a long comment here before I realised my mistake. The root cause of my problem was I named my own file as rasa_nlu.py. When I changed my file to another name, it worked fine.

**Comment by khanali21** [comment]
> I encountered this same issue today. After two hour struggling, I even wrote a long comment here before I realised my mistake. The root cause of my problem was I named my own file as rasa_nlu.py. When I changed my file to another name, it worked fine.

Could you believe that I made the same mistake and spent two hours searching until I reached your comment. Thanks.
