### ISSUE TITLE
How to run multiple projects on one NLU server

### ISSUE THREAD

**Issue by BoyanH** [RasaHQ/rasa#3576]
**Rasa version**: 1.0.1

**Python version**: 3.7.3

**Operating system** (windows, osx, ...): linux

**Issue**:
I am migrating from **rasa_nlu=0.15.0** to **rasa=1.0.1**. I used to run multiple projects on one nlu server in oder to handle multiple languages. Is it possible to do something similar out of the box with the new rasa version?

**Comment by akelad** [comment]
Hi @BoyanH, I'm afraid this is no longer possible. You'll have to run multiple instances of rasa for the separate languages

**Comment by amn41** [comment]
discussion is here https://github.com/RasaHQ/rasa/issues/3259
