### ISSUE TITLE
NameError: name 'Agent' is not defined

### ISSUE THREAD

**Issue by ravikrcs** [RasaHQ/rasa#3582]
**Rasa version**:1.0.1

**Python version**: 3.6.8

**Operating system** (windows, osx, ...):windows

**Issue**:
from rasa.jupyter import chat
chat(model_path)

NameError                                 Traceback (most recent call last)
<ipython-input-13-9b68c86f9192> in <module>()
----> 1 chat(model_path)

1 frames
/usr/local/lib/python3.6/dist-packages/rasa/run.py in create_agent(model, endpoints)
     82     )
     83 
---> 84     return Agent.load(
     85         model,
     86         generator=_endpoints.nlg,

NameError: name 'Agent' is not defined

**Content of configuration file (config.yml)**:
```yml

```

**Content of domain file (domain.yml)** (if used & relevant):
```yaml

```

**Comment by akelad** [comment]
Can you provide some more details? what code are you running?

**Comment by ravikrcs** [comment]
config = "config.yml"
file1 = "nlu.md"
file2 = "stories.md"
domain = "domain.yml"
output = "20190523-125822.tar.gz"

import rasa
model_path = rasa.train(domain, config, [file1, file2], output)

from rasa.jupyter import chat
chat(model_path)

---------------------------------------------------------------------------
NameError                                 Traceback (most recent call last)
<ipython-input-12-55e84fc68831> in <module>()
      1 from rasa.jupyter import chat
----> 2 chat(model_path,agent,interpreter)

NameError: name 'agent' is not defined

**Comment by tmbo** [comment]
in the snippet in your issue description you are missing an import for `Agent` (`from rasa.core.agent import Agent`).

in the code you posted above, you are missing a variable declaration for the agent `agent` variable.

**Comment by ravikrcs** [comment]
http://rasa.com/docs/rasa/api/jupyter-notebooks/

**Comment by tmbo** [comment]
This sounds a bit like the same issue as https://github.com/RasaHQ/rasa/issues/3579

**Comment by akelad** [comment]
looks like it is, will close this

**Comment by alinazhanguwo** [comment]
In the doc http://rasa.com/docs/rasa/api/jupyter-notebooks/ , it does not mention about "Agent (from rasa.core.agent import Agent)".
I have the same issue with ravikrcs. 
Can you update above doc page? Just run 
from rasa.jupyter import chat
chat(model_path)
will cause the agent error.

**Comment by yeshwanth-mandla** [comment]
I have the same issue, causing agent error,  what is the solution!

**Comment by x9694242151819** [comment]
I'm running into the same issue as well:

```
from rasa.core.agent import Agent

from rasa.jupyter import chat
chat(model_path)
```

**Error output**
```
NameError                                 Traceback (most recent call last)
<ipython-input-3-36eb690b0901> in <module>
      2 
      3 from rasa.jupyter import chat
----> 4 chat(model_path)

~/.local/lib/python3.6/site-packages/rasa/jupyter.py in chat(model_path, agent, interpreter)
     33 
     34         unpacked = model.get_model(model_path)
---> 35         agent = create_agent(unpacked)
     36 
     37     elif agent is not None and interpreter is not None:

~/.local/lib/python3.6/site-packages/rasa/run.py in create_agent(model, endpoints)
     77     )
     78 
---> 79     return Agent.load(
     80         model,
     81         generator=_endpoints.nlg,

NameError: name 'Agent' is not defined
```

How do you fix this error?
