### ISSUE TITLE
rasa-nlu 0.15.0 has requirement matplotlib~=2.2, but you'll have matplotlib 3.1.0 which is incompatible.

### ISSUE THREAD

**Issue by MEGHA5** [RasaHQ/rasa#3583]
**Rasa version**: 0.15.0

**Python version**: 3.6.7

**Operating system** (windows, osx, ...):

**Issue**: "unable to install rasa-x with the commandline because of follwoign incompatibility"
rasa-nlu 0.15.0 has requirement matplotlib~=2.2, but you'll have matplotlib 3.1.0 which is incompatible.

**Content of configuration file (config.yml)**:
```yml

```

**Content of domain file (domain.yml)** (if used & relevant):
```yaml

```

**Comment by akelad** [comment]
Please uninstall rasa_nlu 0.15 or install rasa-x in a new terminal :)
