### ISSUE TITLE
rasa creates files with root permissions

### ISSUE THREAD

**Issue by LoganDungeon** [RasaHQ/rasa#3584]
**Rasa version**:  1.0.1 (as docker rasa/rasa:latest-full)

**Python version**: 3.7.3 

**Operating system** (windows, osx, ...): Arch Linux

**Issue**:

Following [this](http://rasa.com/docs/rasa/user-guide/running-rasa-with-docker/) tutorial, I noticed that rasa creates files with root permissions, so the user has to either a) change permissions or b) if he has no root access can't edit the files.

**Comment by akelad** [comment]
Thanks for raising this issue, @wochinge  will get back to you about it soon.

**Comment by wochinge** [comment]
@LoganDungeon What exactly do you mean?
Docker by default runs as `root` user, which means all files created by containers will be created by `root`. What you can do is not running the containers as `root` users, e.g. as described here https://medium.com/redbubble/running-a-docker-container-as-a-non-root-user-7d2e00f8ee15 .

**Comment by wochinge** [comment]
@tmbo Why did you label this as bug? For me it would only be a bug, if rasa fails if not running as `root`. In the draft which I started a while ago, I changed to not run as `root` by default. Could also continue that https://github.com/RasaHQ/rasa/pull/3332/files (files might still be owned by a different user (e.g`1001`) then)

**Comment by tmbo** [comment]
Ok, sounded like a bug on first sight, feel free to change it. Is there anything we can do to fix this? (e.g. change docs)

**Comment by wochinge** [comment]
@LoganDungeon What do you think? Is there a point in the docs where we should make this more obvious?

In my opinion we shouldn't complicate the tutorial by including settings / configurations for Docker users. However, we could add a note or so.

**Comment by LoganDungeon** [comment]
Alright, i did not know docker runs as root, so i was confused. I guess you could maybe add a warning to the tutorial, that the files created by docker have root permissions, so users, that that could lead to problems.

**Comment by wochinge** [comment]
ok, will do :+1: Thanks for the suggestion!
