### ISSUE TITLE
Failing to install Rasa X on Raspberry Pi (3B) - memory error

### ISSUE THREAD

**Issue by Truemedia** [RasaHQ/rasa#3595]
**Rasa version**:
X

**Python version**: 
3.5.3

**Operating system** (windows, osx, ...):
Raspian (linux)

**Issue**:
Failing to install Rasa X on Raspberry Pi (3B) - memory error.

Tensorflow dependency reaches 99% then throws a memory error. Tried installing separately but always tries to download a fresh copy when running the Rasa X install one-liner.

 Is there anyway around this? already tried --no-cache-dir and custom cache conf.

**Content of configuration file (config.yml)**:
```yml
N/A
```

**Content of domain file (domain.yml)** (if used & relevant):
```yaml
N/A
```

**Comment by akelad** [comment]
How much memory do you have on the Raspberry Pi?

**Comment by Truemedia** [comment]
It’s 1gb of RAM as standard, think most models apart from the zero which is 512mb have the same capacity.

**Comment by akelad** [comment]
Yeah I'm afraid I don't think you'll be able to run rasa on there. @ricwo you tried this one right?

**Comment by Truemedia** [comment]
The thing is I did manage to install the tensorflow version it requested separately fine and that works without any problems. Also I managed to get the original rasa NLU working fine. Will try again this afternoon and let you know

**Comment by tmbo** [comment]
If it reinstalls tensorflow, this usually means you installed a different version to the one rasa is expecting to be installed. can you try installing the exact version that rasa is trying to fetch during the pip install?

**Comment by akelad** [comment]
Regardless of whether you're able to install it on there though -- 1GB of memory definitely isn't going to be enough to run rasa nlu though i don't think.

**Comment by Truemedia** [comment]
Just an update on this Raspberry PI 4 has been released.

This model has RAM ranging from 1gb to 4gb, so eventually when I purchase the 4gb model will attempt again and hopefully will be fine.

**Comment by akelad** [comment]
cool! i'm gonna close this issue for now, feel free to let us know how the 4gb version goes though :D
