### ISSUE TITLE
raise an error if `-c` argument is used in rasa train

### ISSUE THREAD

**Issue by Ghostvv** [RasaHQ/rasa#3600]
**Rasa version**: `master`

**Python version**: `3.7`

**Operating system** (windows, osx, ...): `macOS`
 
**Issue**:
If `-c` argument is used, but config file cannot be found, `rasa train` uses default config, I think it is better to raise an error instead

**Comment by tabergma** [comment]
@Ghostvv This was actually a feature request from @erohmensing (see https://github.com/RasaHQ/rasa/issues/3272). 

Currently, 
1) if you train without any config a default config is used
2) if you train an NLU model and your config misses the parameter pipeline, the config gets enriched with the default pipeline
3) if you train a Core model and your config misses the parameter policies, the config gets enriched with the default policies
4) if a complete and valid config is provided, that config is taken

So, in case 1) we should not use the default config but raise an error. Is that correct? Or should we only raise an error if you specify the config via `-c` and the specified config is incomplete/invalid? And in case you did not specify the config via `-c`, but there is also no `config.yml` in your project, it is still fine to use the default config.

**Comment by Ghostvv** [comment]
I think if `-c` is specified, but there is smth wrong, we should raise, otherwise use default with a warning maybe
