### ISSUE TITLE
RASA X UI Bug : `NLU Training` -> `Training Data` UI deletes intent types after I scroll down

### ISSUE THREAD

**Issue by psds01** [RasaHQ/rasa#3603]
**Rasa version**: 1.0.1

**Python version**: Python 3.6.8 |Anaconda

**Operating system** (windows, osx, ...): Ubuntu

**Issue**:
Bug in the `NLU Training` -> `Training Data` UI
Say I have 10 sentences in my `nlu.json` file. If I tag first sentences, and then scroll down to the 10th sentence to tag it, I loose the intent_type of the first sentence.

Tagging first few sentences:
![Screenshot from 2019-05-27 16-47-32](https://user-images.githubusercontent.com/49634935/58416523-7b66c980-809f-11e9-8039-c0989576833d.png)
Scrolling down, adding intent to last text the coming back up, I get:
![Screenshot from 2019-05-27 16-48-00](https://user-images.githubusercontent.com/49634935/58416594-bbc64780-809f-11e9-9007-c2ceed9b5936.png)

**Content of configuration file (config.yml)**:
```yml

```

**Content of domain file (domain.yml)** (if used & relevant):
```yaml

```

**Comment by akelad** [comment]
Thanks for raising this! @gausie will look into what's going wrong there

In the meantime, would you be up for filling out a [form](https://rasahq.typeform.com/to/NSJvZM) to give us some feedback about Rasa X so far?

**Comment by psds01** [comment]
You are welcome.

Done @akelad. I love Rasa!

**Comment by gausie** [comment]
Sorry for taking a while to get to this @psds01! I haven't been able to replicate your issue - is it still a problem? Do you have any more information that might help me make it happen on my machine?
