### ISSUE TITLE
Unable to send formatted html as utter response from custom actions

### ISSUE THREAD

**Issue by hnithyanandam** [RasaHQ/rasa#3607]
**Rasa version**:0.14.0

**Python version**: 3.7.3

**Operating system** (windows, osx, ...):ubuntu 16.04

**Issue**: I am sending html formatted text as response in custom action. I am not able to see the formatted text in the React UI chatroom

**Content of configuration file (config.yml)**:
```
language: "en"

pipeline: "tensorflow_embedding"

```

**Content of domain file (domain.yml)** (if used & relevant):
```
actions:
 - utter_greet
 - utter_greetings
 - utter_cheer_up
 - utter_ask_email

```

From custom actions , how can i send response as html or format the text like bold

```
response = "<b>HelloWorld</b>" 
        dispatcher.utter_message(response)
```

**Comment by tmbo** [comment]
Which react chat UI are you using? This is probably more an "issue" with the chat client than it is with Rasa - because in general it is quite good that the chat lib doesn't just render arbitrary html :wink:

**Comment by hnithyanandam** [comment]
thanks was able to fix the issue by using markdown instead of html.It would be great if it supports html as well. I am using Scalable minds react chatroom
