### ISSUE TITLE
AttributeError: module 'rasa.nlu.utils' has no attribute 'pycloud_pickle'

### ISSUE THREAD

**Issue by chaitaliprabhu** [RasaHQ/rasa#3608]
**Rasa version**: 1.0.1

**Python version**: 3.6

**Operating system** (windows, osx, ...):windows

**Issue**:
In the **persist** method for Sentiment_Analyzer, the following error occurs when for 
--> utils.pycloud_pickle(classifier_file, self)

AttributeError: module 'rasa.nlu.utils' has no attribute 'pycloud_pickle'
In the newer version of rasa, is there a method that replaces this function?

**Content of configuration file (config.yml)**:
language: en
pipeline:
- name: WhitespaceTokenizer
- name: CRFEntityExtractor
- name: EntitySynonymMapper
- name: CountVectorsFeaturizer
- name: sentiment.SentimentAnalyzer
policies:
- batch_size: 50
  epochs: 200
  max_training_samples: 300
  name: KerasPolicy
- max_history: 5
  name: MemoizationPolicy

**Comment by tmbo** [comment]
Yes, rather use `rasa.nlu.utils.json_pickle` and the corresponding `json_unpickle` - it creates an output that it is less dependent on python versions and which we could possibly migrate between versions.

**Comment by chaitaliprabhu** [comment]
Thank you :)
