### ISSUE TITLE
Refined response from chatbot

### ISSUE THREAD

**Issue by LKiera** [RasaHQ/rasa#3615]
**Rasa version**:
rasa-core (0.14.3)
rasa-core-sdk (1.0.0rc2)
rasa-nlu (0.15.0)

**Python version**: Python 3.6.7

**Operating system** (windows, osx, ...): Ubuntu 18.04

**Issue**:
The chatbot is running fine, just want to know how to remove the below thing from the response we get from chatbot on cmdline

127.0.0.1 - - [2019-05-28 11:52:06] "POST /webhooks/rest/webhook?stream=true&token= HTTP/1.1" 200 154 0.561174

**Content of configuration file (config.yml)**:
```yml
{
  "pipeline":"spacy_sklearn",
  "path":"./models/nlu",
  "data":"./data/data.json"
}
```

**Content of domain file (domain.yml)** (if used & relevant):
```yaml

```

**Comment by akelad** [comment]
This isn't a response, but rather a log of the requests sent by the bot. You can't turn it off in your versions of rasa-core/nlu but those logs are suppressed in rasa 1.0
