### ISSUE TITLE
Requested URL /conversations not found  

### ISSUE THREAD

**Issue by akshayrana1139** [RasaHQ/rasa#3616]
**Rasa version**:1.0

**Python version**: 3.6

**Operating system** (windows, osx, ...): Windows

**Issue**: Error: Requested URL /conversations not found 

```
rasa run -m models --enable-api --debug
```
The above command starts the RASA Core server but none of the /conversations API works(using CURL or PostMan) and gives the below exception, but few APIs like /model/parse,  /status seems to be working. 

```
 [ERROR] Exception occurred while handling uri: 'http://localhost:5005/conversations'
Traceback (most recent call last):
  File "c:\users\j.sree.kalyani\appdata\local\continuum\anaconda3\lib\site-packages\sanic\app.py", line 893, in handle_request
    handler, args, kwargs, uri = self.router.get(request)
  File "c:\users\j.sree.kalyani\appdata\local\continuum\anaconda3\lib\site-packages\sanic\router.py", line 407, in get
    return self._get(request.path, request.method, "")
  File "c:\users\j.sree.kalyani\appdata\local\continuum\anaconda3\lib\site-packages\sanic\router.py", line 469, in _get
    raise NotFound("Requested URL {} not found".format(url))
sanic.exceptions.NotFound: Requested URL /conversations not found
```

Strangely when I run the RASA X, the core seems to be working fine on the user interface at least.   

**Content of configuration file (config.yml)**:
```yml
language: en
pipeline: pretrained_embeddings_spacy

# Configuration for Rasa Core.
# https://rasa.com/docs/rasa/core/policies/
policies:
  - name: MemoizationPolicy
  - name: KerasPolicy
  - name: MappingPolicy
  - name: FormPolicy 
```

**Content of domain file (domain.yml)** (if used & relevant):
```yaml

```

**Comment by akelad** [comment]
@akshayrana1139 the `/conversations` endpoint is only available with Rasa X -- this is intentional.

Good to see you're trying out Rasa X -- would you be willing to give us some feedback via this [form](https://rasahq.typeform.com/to/NSJvZM)?

**Comment by akshayrana1139** [comment]
How are we suppose to use these APIs then? Prior to RASA X, I was using /conversations/<conversation_id>/ to converse with my bot.

**Comment by akshayrana1139** [comment]
I guess we'll have to use our own secret key using **--jwt-secret thisismysecret** and create our own JWT tokens for it to work. Is that correct?

**Comment by akelad** [comment]
@akshayagarwal sorry I misspoke, so the `/conversations` endpoints do exist in `rasa` -- but only if you use it in combination with a sender id to get the tracker/conversation if it's stored somewhere. Which it is with rasa x, but not with rasa on its own

But in any case `/conversations` by itself shouldn't work on `rasa`, only on `rasa-x` :D 

You can hit the `/api/auth` endpoint to get an access token to go to conversations

**Comment by akshayrana1139** [comment]
Even if I try rasa-x server with  /api/conversation/<conversation_id>/messages , it always comes back with a  recipient_id for "me" and uses the tracker for "me". It does not uses the latest tracker for new conversation id.

**Comment by akelad** [comment]
@wochinge could you take a look at that?

**Comment by OwaisRaza1** [comment]
I am facing issue when I run rasa UI with nlu server, when I start rasa UI and it hits to the nlu server at port 5000 it throws following exception:

[5860] [ERROR] Exception occurred while handling uri: 'http://localhost:5000/config'
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/sanic/app.py", line 893, in handle_request
    handler, args, kwargs, uri = self.router.get(request)
  File "/usr/local/lib/python3.6/dist-packages/sanic/router.py", line 407, in get
    return self._get(request.path, request.method, "")
  File "/usr/local/lib/python3.6/dist-packages/sanic/router.py", line 469, in _get
    raise NotFound("Requested URL {} not found".format(url))
sanic.exceptions.NotFound: Requested URL /config not found

Unable to find its solution can you please help ???

**Comment by akelad** [comment]
@OwaisRaza1 this is not related to this issue, please create a new one

**Comment by Akhil1278** [comment]
I am trying to implement a form using custom actions but getting this error : 
![Screenshot (27)](https://user-images.githubusercontent.com/65960157/82906763-53949500-9f83-11ea-81b1-738817d91be1.png)

**Comment by wochinge** [comment]
@Akhil1278 Unless you changed the port, it should be `5055` and please remember to run the action server separately.
