### ISSUE TITLE
Rasa X - annotate new data - doubles

### ISSUE THREAD

**Issue by PhilippeBaert** [RasaHQ/rasa#3619]
**Rasa version**: 1.0.1

**Rasa X version**: 0.19.0

**Python version**: 3.6.7

**Operating system** (windows, osx, ...): Windows 10 

**Issue**:

Hello,

Imagine the following flow:
1) I talk to the bot through Interactive learning and save a couple of stories
2) I go to Training => NLU Training => Annotate new data
3) I want to add new sentences I generated in interactive learning to my NLU training data

Issue: the sentences I used in interactive learning, are added **twice**.
Once for the NLU prediction, once for the intent that I set through interactive learning.

You will see for example, the first sentence: "Am I talking to a chatbot?"
This was wrongly classified as "goodbye". So I manually changed it to "ask_isbot" in interactive learning. 

In my opinion, if both the NLU predicted intent, and the intent I set through interactive learning are the same, it shouldn't be added twice to the annotate screen.

![rasa-bug](https://user-images.githubusercontent.com/9559193/58466334-be757b00-8139-11e9-9301-e562189a6cf0.PNG)

Thanks for looking into this.

Cheers,
Philippe

**Comment by akelad** [comment]
Thanks for raising this issue -- we'll look into fixing it for the next release

**Comment by tmbo** [comment]
I think if you correct something in interactive learning, it should be added to the training data and shouldn't be shown in the inbox at all.

**Comment by wochinge** [comment]
@TyDunn Why is this reopened?

**Comment by TyDunn** [comment]
My apologies. I was adding it to a ZenHub milestone board and did not realize moving it to the done column would reopen it. Just closed it. Sorry for the noise @wochinge

**Comment by wochinge** [comment]
No worries 😄
