### ISSUE TITLE
Lookup table file failed to load if the file name or directory name contains hyphen ("-")

### ISSUE THREAD

**Issue by carlostse** [RasaHQ/rasa#3622]
**Rasa version**: 0.14 - current

**Python version**:  Python 3.6

**Operating system** (windows, osx, ...): Any

**Issue**:
Fail to load the lookup table file if the file name or directory name contains hyphen ("-"), 
e.g. exception will be thrown during training for the example below
```
## lookup:additional_currencies
/path-to/currencies.txt
```
PR for the fix: https://github.com/RasaHQ/rasa/pull/3623

**Content of configuration file (config.yml)**:
```yml

```

**Content of domain file (domain.yml)** (if used & relevant):
```yaml

```

**Comment by akelad** [comment]
Thanks for spotting + fixing this!
