### ISSUE TITLE
Multi Domain loading not importing data directory of root project

### ISSUE THREAD

**Issue by wochinge** [RasaHQ/rasa#3633]
Currently the experimental multi bot feature does only load data specified in imported bots or in the root project directory. It should also load data in the data directory of the root project (project in which the command is executed).

**Comment by alexissmirnov** [comment]
Great work Tobias. What would happen in case of name conflicts between skills? Should skills be namespaced eg. action would be called `GreetBot.bye`, same with slots.

**Comment by wochinge** [comment]
At the moment, everything is merged. But we plan to add some support to scope the imports.
