### ISSUE TITLE
The tracker does not change for new conversation-id in rasa-x

### ISSUE THREAD

**Issue by akshayrana1139** [RasaHQ/rasa#3639]
**Rasa version**:1.0

**Python version**: 3.5

**Operating system** (windows, osx, ...):Windows

**Issue**: The tracker in rasa-x does not get refreshed, instead it always return "me" in recipient ID.  When I hit **/api/conversations/ < conversation - id > /messages,** the tracker and the recipient ID used here works only for "me" instead of the new conversation-id.

**Content of configuration file (config.yml)**:
```yml
language: en
pipeline: pretrained_embeddings_spacy

# Configuration for Rasa Core.
# https://rasa.com/docs/rasa/core/policies/
policies:
  - name: MemoizationPolicy
  - name: KerasPolicy
  - name: MappingPolicy
  - name: FormPolicy 
```

**Content of domain file (domain.yml)** (if used & relevant):
```yaml

```

**Comment by akshayrana1139** [comment]
I think it is intentionally restricted as seen in the code.  There are multiple methods for "/conversations/<conversation_id>/messages"
1. The one with GET and HEAD request uses the conversation id to fetch tracker details from the conversation_id.
```
@stack_endpoints.route("/conversations/<conversation_id>/messages",
                           methods=['GET', 'HEAD'])
    @platform_scoped('clientMessages.list')
    @inject_rasa_x_user()
    async def get_messages(request, conversation_id, user=None):

...
tracker = await _stack_service(request, "production").tracker_json(
                conversation_id,
                event_verbosity,
                until=until_time)
...
 return response.json(tracker,
                                 headers={"X-Total-Count": len(messages)})
```

2. But in the POST message, the conversation_id is clearly ignored and the request is passed to the /chat api
```
 @stack_endpoints.route("/conversations/<conversation_id>/messages",
                           methods=['POST'])
    @platform_scoped('messages.create')
    async def send_message(request, conversation_id, user=None):
        return await chat_to_bot(request)
```

Is this intentional to block chats based on conversation_id and rather focus them on user_id i.e. "me" by default.

**Comment by akelad** [comment]
Thanks for raising this issue, @tabergma  will get back to you about it soon.

**Comment by wochinge** [comment]
@akshayrana1139 Rasa X CE only supports one Rasa X user (`me`). Users who want to use your chatbot should use the regular Rasa channels (http://rasa.com/docs/rasa/user-guide/messaging-and-voice-channels/) to connect to the chatbot and send messages.
