### ISSUE TITLE
Clarify if component method required_packages returns module names or requirements

### ISSUE THREAD

**Issue by merwok** [RasaHQ/rasa#3647]
**Rasa version**: 1.0.2

**Python version**: 3.7.3

**Operating system** (windows, osx, ...): Debian testing

**Issue**: The doc at http://rasa.com/docs/rasa/api/custom-nlu-components/#rasa.nlu.components.Component.required_packages doesn’t make clear whether the strings returned should be module names (i.e. importable, like sklearn) or requirements (i.e. checked using packaging introspection methods, e.g. scikit-learn).

**Comment by akelad** [comment]
could you clarify what you mean? it specifies the names of python packages

**Comment by merwok** [comment]
«package» is ambiguous: is it something you install (requirement, e.g. scikit-learn, maybe with a version specifier) or something you import (Python module, e.g. sklearn)

**Comment by akelad** [comment]
We'd be happy to accept a PR phrasing this in a clearer way. This is the method that tries to import them fyi: https://github.com/RasaHQ/rasa/blob/master/rasa/nlu/components.py#L14

**Comment by akelad** [comment]
Yeah I know, are you willing to create a PR for this to make it clearer in the docs?

**Comment by merwok** [comment]
I found the source of the docs (https://github.com/RasaHQ/rasa/blob/master/rasa/nlu/components.py#L200-L204) but I think more work may be needed to avoid ambiguity here.  For example, the method that checks these required modules may produce an error message that is super unclear about modules vs requirements: https://github.com/RasaHQ/rasa/blob/master/rasa/nlu/components.py#L28

**Comment by akelad** [comment]
ok before we look into this ourselves would you be willing to submit a PR for that as well? we're always happy about community contributions

**Comment by akelad** [comment]
ok before we start looking into this, would you be up for working on this as well? We're always happy to accept community contributions

**Comment by merwok** [comment]
Sure, but maybe not before a few weeks.

**Comment by hsm207** [comment]
I want to work on this

**Comment by hsm207** [comment]
> I found the source of the docs (https://github.com/RasaHQ/rasa/blob/master/rasa/nlu/components.py#L200-L204) but I think more work may be needed to avoid ambiguity here.  For example, the method that checks these required modules may produce an error message that is super unclear about modules vs requirements: https://github.com/RasaHQ/rasa/blob/master/rasa/nlu/components.py#L28

@merwok what are the changes that should be made? I don't see how the exception raised by [validate_requirements](https://github.com/RasaHQ/rasa/blob/f3480aa384740c58d4b98f6498938faecf39bbe1/rasa/nlu/components.py#L28) can be unclear.

**Comment by merwok** [comment]
I don’t know how to explain the same idea differently!

To repeat my initial message:  if `import sklearn` fails, it is not correct to say `you need to run pip install sklearn`, because the (importable) module name is not the same as the (installable) package name (here: scikit-learn).

**Comment by hsm207** [comment]
> I don’t know how to say the same thing in a different way 🙁
> To repeat my initial message:  if import sklearn fails, it is not correct to say you need to run pip install sklearn, because the (importable) module name is not the same as the (installable) package name (here: scikit-learn).

But `pip install sklearn`  will run and will actually install scikit-learn. 

Do you have any other examples?

What do you think of updating the exception message in [validate_requirements](https://github.com/RasaHQ/rasa/blob/f3480aa384740c58d4b98f6498938faecf39bbe1/rasa/nlu/components.py#L28) to something like:


`Please install the package that contains the module sklearn`

?

**Comment by merwok** [comment]
Maybe that particular example is not valid anymore :slightly_smiling_face: but the general idea still stands.

**Comment by hsm207** [comment]
So just update the exception message from `validate_requirements` is sufficient for now?

**Comment by merwok** [comment]
The exception message and also the doc I linked from my first message.

**Comment by hsm207** [comment]
I guess we can close this issue now since the pull request has been merged.

**Comment by merwok** [comment]
Thanks for improving the docs! :slightly_smiling_face:
