### ISSUE TITLE
OS requirement for RASA Installation. 

### ISSUE THREAD

**Issue by pnandhini11** [RasaHQ/rasa#3651]
**Rasa version**:

**Python version**: 

**Operating system** (windows, osx, ...):

**Issue**:

This is not about an issue. But we are trying to understand RASA OS requirement. We are in the process of setting up our new server and want to install RASA application for our business.  Will you provide tech support for Debian 9.7 or Ubuntu 18.04 LS or 19.04 ? Pls confirm. 

**Content of configuration file (config.yml)**:
```yml

```

**Content of domain file (domain.yml)** (if used & relevant):
```yaml

```

**Comment by akelad** [comment]
Yes these are supported
