### ISSUE TITLE
ERROR! Syntax Error while loading YAML.

### ISSUE THREAD

**Issue by harunkelesoglu** [RasaHQ/rasa#3653]
I'm trying install the rasa x community according to this  http://rasa.com/docs/rasa-x/deploy/#quick-installation
But  ı getting the following error after run <code>sudo bash ./install.sh</code> command
**Python version**: 
python 3.6.7
**Operating system** (windows, osx, ...):
linux  ubuntu 4.15.0-42-generic
**Issue**:
```
ERROR! Syntax Error while loading YAML.
  mapping values are not allowed here

The error appears to be in '/home/harun/rasa/rasax/rasa_x_playbook.yml': line 57, column 11, but may
be elsewhere in the file depending on the exact syntax problem.

The offending line appears to be:

  - name: Create the directory for the database persistence
      file:
          ^ here

```

**Comment by harunkelesoglu** [comment]
I solved.The problem is incorrect syntax of the yaml file. I fixed it for now. 
https://github.com/harunkelesoglu/rasa-x-release/blob/master/rasa_x_playbook.yml

**Comment by akelad** [comment]
That should be part of the latest release by now, right @wochinge?

**Comment by wochinge** [comment]
Yes, this will be part of the next release (0.19.1)

**Comment by akelad** [comment]
i'll close this then
