### ISSUE TITLE
Internal Server Error

### ISSUE THREAD

**Issue by harunkelesoglu** [RasaHQ/rasa#3661]
**Rasa version**:
Rasa 1.0.0
**Python version**: 
Python 3.6.8
**Operating system** (windows, osx, ...):
Ubuntu Linux
**Issue**:
I installed rasa x to server. when I click on the training button or try to upload the model, I get this error
```
  <h1>Internal Server Error</h1>
    <p>
        The server encountered an internal error and cannot complete
        your request.
    </p>
```
my command for upload the trained model
```
curl -k -F "model=@models/20190527-232302.tar.
gz" http://servr_ipaddress/api/projects/default/models?api_token=0d7d2da93c1c494603e8d8
74efe23630e3473e45
```

**Comment by akelad** [comment]
Is there any other messages in your logs? And also how was the zip file created?

**Comment by tweety101** [comment]
Hi, I have the same problem. The logs show:

File "/usr/local/lib/python3.6/shutil.py", line 550, in move
rasa-x_1           |     os.rename(src, real_dst)
rasa-x_1           | OSError: [Errno 18] Invalid cross-device link: '/tmp/tmpd67k3i7w/20190604-221048.tar.gz' -> '/app/models/20190604-221048.tar.gz'
rasa-x_1           | 
rasa-x_1           | During handling of the above exception, another exception occurred:

The zip file was created by the "rasa train" command

Thanks!

**Comment by akelad** [comment]
@ricwo any ideas? I think training on the server not working is intentional right now (obviously a bug, which we're working on fixing), but uploading a model should work.

**Comment by ricwo** [comment]
This is odd, because `shutil.move()` as of python 3.6 should handle different file systems correctly. 
we'll look into this further

@tweety101 are you also running Ubuntu? If so, which version?
@harunkelesoglu what version of Ubuntu are you running?

**Comment by tweety101** [comment]
Hi, Ricwo. I am using Ubuntu 18.04 from a fresh Digitalocean install. 

Uploading the model using scp did make it available in rasa x. However I keep running into errors when trying the talk to bot. 

The logs show: 

ERROR] Exception occurred while handling uri: 'http://rasa-production:5005/webhooks/rasa/webhook'
rasa-production_1  | Traceback (most recent call last):
rasa-production_1  |   File "/usr/local/lib/python3.6/site-packages/aiohttp/connector.py", line 924, in _wrap_create_connection
rasa-production_1  |     await self._loop.create_connection(*args, **kwargs))
rasa-production_1  |   File "uvloop/loop.pyx", line 1904, in create_connection
rasa-production_1  |   File "uvloop/loop.pyx", line 1882, in uvloop.loop.Loop.create_connection
rasa-production_1  |   File "uvloop/handles/tcp.pyx", line 179, in uvloop.loop.TCPTransport.connect
rasa-production_1  |   File "uvloop/handles/tcp.pyx", line 201, in uvloop.loop._TCPConnectRequest.connect
rasa-production_1  | OSError: [Errno 99] Cannot assign requested address
rasa-production_1  | 
rasa-production_1  | The above exception was the direct cause of the following exception:
rasa-production_1  | 
rasa-production_1  | Traceback (most recent call last):
rasa-production_1  |   File "/usr/local/lib/python3.6/site-packages/sanic/app.py", line 917, in handle_request
rasa-production_1  |     response = await response
rasa-production_1  |   File "/usr/local/lib/python3.6/site-packages/rasa/core/channels/channel.py", line 430, in receive
rasa-production_1  |     sender_id = await self._extract_sender(request)
rasa-production_1  |   File "/usr/local/lib/python3.6/site-packages/rasa/core/channels/rasa_chat.py", line 50, in _extract_sender
rasa-production_1  |     user = await self._check_token(req.headers.get("Authorization"))
rasa-production_1  |   File "/usr/local/lib/python3.6/site-packages/rasa/core/channels/rasa_chat.py", line 35, in _check_token
rasa-production_1  |     url, headers=headers, timeout=DEFAULT_REQUEST_TIMEOUT
rasa-production_1  |   File "/usr/local/lib/python3.6/site-packages/aiohttp/client.py", line 1005, in __aenter__
rasa-production_1  |     self._resp = await self._coro
rasa-production_1  |   File "/usr/local/lib/python3.6/site-packages/aiohttp/client.py", line 476, in _request
rasa-production_1  |     timeout=real_timeout
rasa-production_1  |   File "/usr/local/lib/python3.6/site-packages/aiohttp/connector.py", line 522, in connect
rasa-production_1  |     proto = await self._create_connection(req, traces, timeout)
rasa-production_1  |   File "/usr/local/lib/python3.6/site-packages/aiohttp/connector.py", line 854, in _create_connection
rasa-production_1  |     req, traces, timeout)
rasa-production_1  |   File "/usr/local/lib/python3.6/site-packages/aiohttp/connector.py", line 992, in _create_direct_connection
rasa-production_1  |     raise last_exc
rasa-production_1  |   File "/usr/local/lib/python3.6/site-packages/aiohttp/connector.py", line 974, in _create_direct_connection
rasa-production_1  |     req=req, client_error=client_error)
rasa-production_1  |   File "/usr/local/lib/python3.6/site-packages/aiohttp/connector.py", line 931, in _wrap_create_connection
rasa-production_1  |     raise client_error(req.connection_key, exc) from exc
rasa-production_1  | aiohttp.client_exceptions.ClientConnectorError: Cannot connect to host localhost:5002 ssl:None [Cannot assign requested address]
rasa-x_1           | Failed to send message to Rasa Chat webhook with status 500. Response:
rasa-x_1           | 
rasa-x_1           |     <h1>Internal Server Error</h1>
rasa-x_1           |     <p>
rasa-x_1           |         The server encountered an internal error and cannot complete
rasa-x_1           |         your request.
rasa-x_1           |     </p>
rasa-x_1           | 
rasa-x_1           | [2019-06-09 18:30:05 +0000] - (sanic.access)[INFO][172.24.0.9:34654]: POST http://138.197.69.142/api/chat?environment=production  404 178

I have tried different configurations of the environment variables and environments.yml, using localhost, 0.0.0.0, and the server's ip. 

When I try the interactive learning mode, the intents are recognized but any functionality after that fails. 

Let me know if you have any tips on where to look.

**Comment by harunkelesoglu** [comment]
Hi @ricwo I am using Ubuntu 16.04.6 LTS

**Comment by harunkelesoglu** [comment]
When I load the trained data and click Train, I get the following error in the logs:

Error:
```
 PermissionError: [Errno 13] Permission denied: '/app/models/20190610-072003.tar.gz'
```

Logs:
```
rasa-worker_1      | 2019-06-10 07:19:57 WARNING  rasa.nlu.extractors.crf_entity_extractor  - Misaligned entity annotation for 'başiktaşa' in sentence 'beni başiktaşa götür' with intent 'address'. Make sure the start and end values of the annotated training examples end at token boundaries (e.g. don't include trailing whitespaces or punctuation).
rasa-worker_1      | 2019-06-10 07:19:57 WARNING  rasa.nlu.extractors.crf_entity_extractor  - Misaligned entity annotation for 'nişantaşı üniversitesi' in sentence 'nişantaşı üniversitesi nerede' with intent 'address'. Make sure the start and end values of the annotated training examples end at token boundaries (e.g. don't include trailing whitespaces or punctuation).
rasa-x_1           | [2019-06-10 07:20:02 +0000] - (sanic.access)[INFO][172.18.0.9:36600]: GET http://116.203.186.246/api/projects/default/entities  200 70
nginx_1            | 178.251.45.188 - - [10/Jun/2019:07:20:02 +0000] "GET /api/projects/default/entities HTTP/1.1" 200 70 "http://116.203.186.246/data/training-data" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/74.0.3729.169 Safari/537.36"
rasa-x_1           | [2019-06-10 07:20:02 +0000] - (sanic.access)[INFO][172.18.0.9:36602]: GET http://116.203.186.246/api/projects/default/data?q=&intent=&limit=20&offset=0  200 3160
nginx_1            | 178.251.45.188 - - [10/Jun/2019:07:20:02 +0000] "GET /api/projects/default/data?q=&intent=&limit=20&offset=0 HTTP/1.1" 200 582 "http://116.203.186.246/data/training-data" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/74.0.3729.169 Safari/537.36"
rasa-x_1           | [2019-06-10 07:20:03 +0000] [21] [ERROR] Exception occurred while handling uri: 'http://116.203.186.246/api/projects/default/models/jobs'
rasa-x_1           | Traceback (most recent call last):
rasa-x_1           |   File "/usr/local/lib/python3.6/site-packages/sanic/app.py", line 917, in handle_request
rasa-x_1           |     response = await response
rasa-x_1           |   File "/usr/local/lib/python3.6/site-packages/rasax/community/api/decorators.py", line 184, in decorated_function
rasa-x_1           |     return await await_and_return_response(args, kwargs, request)
rasa-x_1           |   File "/usr/local/lib/python3.6/site-packages/rasax/community/api/decorators.py", line 114, in await_and_return_response
rasa-x_1           |     response = await response
rasa-x_1           |   File "/usr/local/lib/python3.6/site-packages/rasax/community/api/blueprints/models.py", line 174, in train_model
rasa-x_1           |     write_bytes_to_file(model_path, content)
rasa-x_1           |   File "/usr/local/lib/python3.6/site-packages/rasax/community/utils.py", line 315, in write_bytes_to_file
rasa-x_1           |     with io.open(filename, 'wb') as f:
rasa-x_1           | PermissionError: [Errno 13] Permission denied: '/app/models/20190610-072003.tar.gz'
rasa-x_1           | [2019-06-10 07:20:03 +0000] - (sanic.access)[INFO][172.18.0.9:36596]: POST http://116.203.186.246/api/projects/default/models/jobs  500 144
nginx_1            | 178.251.45.188 - - [10/Jun/2019:07:20:03 +0000] "POST /api/projects/default/models/jobs HTTP/1.1" 500 144 "http://116.203.186.246/data/new" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/74.0.3729.169 Safari/537.36"
rasa-x_1           | [2019-06-10 07:20:05 +0000] - (sanic.access)[INFO][172.18.0.6:39344]: GET http://rasa-x:5002/api/projects/default/models/tags/production?token=r79MGgdr1MhKIJd  404 160
rasa-x_1           | [2019-06-10 07:20:05 +0000] - (sanic.access)[INFO][172.18.0.7:38490]: GET http://rasa-x:5002/api/projects/default/models/tags/production?token=r79MGgdr1MhKIJd  404 160
rasa-x_1           | [2019-06-10 07:20:15 +0000] - (sanic.access)[INFO][172.18.0.6:39348]: GET http://rasa-x:5002/api/projects/default/models/tags/production?token=r79MGgdr1MhKIJd  404 160
rasa-x_1           | [2019-06-10 07:20:15 +0000] - (sanic.access)[INFO][172.18.0.7:38494]: GET http://rasa-x:5002/api/projects/default/models/tags/production?token=r79MGgdr1MhKIJd  404 160
```

**Comment by ricwo** [comment]
@harunkelesoglu can you please try 
```bash
sudo chown -R 1001 models && sudo chmod 777 -R models
```
and restarting rasa X with `sudo docker-compose down && sudo docker-compose up -d`?

**Comment by harunkelesoglu** [comment]
Thanks @ricwo. solved it.

**Comment by ZhengHe-MD** [comment]
> Hi, Ricwo. I am using Ubuntu 18.04 from a fresh Digitalocean install.
> 
> Uploading the model using scp did make it available in rasa x. However I keep running into errors when trying the talk to bot.
> 
> The logs show:
> 
> ERROR] Exception occurred while handling uri: 'http://rasa-production:5005/webhooks/rasa/webhook'
> rasa-production_1 | Traceback (most recent call last):
> rasa-production_1 | File "/usr/local/lib/python3.6/site-packages/aiohttp/connector.py", line 924, in _wrap_create_connection
> rasa-production_1 | await self._loop.create_connection(*args, **kwargs))
> rasa-production_1 | File "uvloop/loop.pyx", line 1904, in create_connection
> rasa-production_1 | File "uvloop/loop.pyx", line 1882, in uvloop.loop.Loop.create_connection
> rasa-production_1 | File "uvloop/handles/tcp.pyx", line 179, in uvloop.loop.TCPTransport.connect
> rasa-production_1 | File "uvloop/handles/tcp.pyx", line 201, in uvloop.loop._TCPConnectRequest.connect
> rasa-production_1 | OSError: [Errno 99] Cannot assign requested address
> rasa-production_1 |
> rasa-production_1 | The above exception was the direct cause of the following exception:
> rasa-production_1 |
> rasa-production_1 | Traceback (most recent call last):
> rasa-production_1 | File "/usr/local/lib/python3.6/site-packages/sanic/app.py", line 917, in handle_request
> rasa-production_1 | response = await response
> rasa-production_1 | File "/usr/local/lib/python3.6/site-packages/rasa/core/channels/channel.py", line 430, in receive
> rasa-production_1 | sender_id = await self._extract_sender(request)
> rasa-production_1 | File "/usr/local/lib/python3.6/site-packages/rasa/core/channels/rasa_chat.py", line 50, in _extract_sender
> rasa-production_1 | user = await self._check_token(req.headers.get("Authorization"))
> rasa-production_1 | File "/usr/local/lib/python3.6/site-packages/rasa/core/channels/rasa_chat.py", line 35, in _check_token
> rasa-production_1 | url, headers=headers, timeout=DEFAULT_REQUEST_TIMEOUT
> rasa-production_1 | File "/usr/local/lib/python3.6/site-packages/aiohttp/client.py", line 1005, in **aenter**
> rasa-production_1 | self._resp = await self._coro
> rasa-production_1 | File "/usr/local/lib/python3.6/site-packages/aiohttp/client.py", line 476, in _request
> rasa-production_1 | timeout=real_timeout
> rasa-production_1 | File "/usr/local/lib/python3.6/site-packages/aiohttp/connector.py", line 522, in connect
> rasa-production_1 | proto = await self._create_connection(req, traces, timeout)
> rasa-production_1 | File "/usr/local/lib/python3.6/site-packages/aiohttp/connector.py", line 854, in _create_connection
> rasa-production_1 | req, traces, timeout)
> rasa-production_1 | File "/usr/local/lib/python3.6/site-packages/aiohttp/connector.py", line 992, in _create_direct_connection
> rasa-production_1 | raise last_exc
> rasa-production_1 | File "/usr/local/lib/python3.6/site-packages/aiohttp/connector.py", line 974, in _create_direct_connection
> rasa-production_1 | req=req, client_error=client_error)
> rasa-production_1 | File "/usr/local/lib/python3.6/site-packages/aiohttp/connector.py", line 931, in _wrap_create_connection
> rasa-production_1 | raise client_error(req.connection_key, exc) from exc
> rasa-production_1 | aiohttp.client_exceptions.ClientConnectorError: Cannot connect to host localhost:5002 ssl:None [Cannot assign requested address]
> rasa-x_1 | Failed to send message to Rasa Chat webhook with status 500. Response:
> rasa-x_1 |
> rasa-x_1 |
> 
> # Internal Server Error
> 
> rasa-x_1 |
> 
> rasa-x_1 | The server encountered an internal error and cannot complete
> rasa-x_1 | your request.
> rasa-x_1 |
> 
> 
> rasa-x_1 |
> rasa-x_1 | [2019-06-09 18:30:05 +0000] - (sanic.access)[INFO][172.24.0.9:34654]: POST http://138.197.69.142/api/chat?environment=production 404 178
> I have tried different configurations of the environment variables and environments.yml, using localhost, 0.0.0.0, and the server's ip.
> 
> When I try the interactive learning mode, the intents are recognized but any functionality after that fails.
> 
> Let me know if you have any tips on where to look.

did you solved the problem? Any ideas, I'm also facing the same issue
