### ISSUE TITLE
 Failed to find component class for 'supervised_embeddings'. Unknown component name.

### ISSUE THREAD

**Issue by TheGlobalist** [RasaHQ/rasa#3662]
**Rasa version**: 1.0

**Python version**:  3.6

**Operating system** (windows, osx, ...): Windows

**Issue**: I'd like to test SpacyNLP pipeline combined with the supervised_embeddings. If I try to launch it, though, I'm getting this stack trace. This does not happen if, in the config.yml, I just keep supervised_embeddings only. 
If I try to leave the SpacyNLP pipeline only, though, I get this error:

InvalidConfigError: No pipeline specified and unknown pipeline template 'SpacyNLP' passed. Known pipeline templates: pretrained_embeddings_spacy, keyword, supervised_embeddings

Is there something that I am missing?

```---------------------------------------------------------------------------
KeyError                                  Traceback (most recent call last)
~\Anaconda3\lib\site-packages\rasa\nlu\registry.py in get_component_class(component_name)
    140             try:
--> 141                 return utils.class_from_module_path(component_name)
    142             except Exception:

~\Anaconda3\lib\site-packages\rasa\nlu\utils\__init__.py in class_from_module_path(module_path)
    143     else:
--> 144         return globals()[module_path]
    145

KeyError: 'supervised_embeddings'

During handling of the above exception, another exception occurred:

Exception                                 Traceback (most recent call last)
<ipython-input-109-971025f984ec> in <module>
      8
      9 # trainer to educate our pipeline
---> 10 trainer = Trainer(config.load("config.yml"))
     11
     12 # train the model!

~\Anaconda3\lib\site-packages\rasa\nlu\model.py in __init__(self, cfg, component_builder, skip_validation)
    146         # required packages are available
    147         if not self.skip_validation:
--> 148             components.validate_requirements(cfg.component_names)
    149
    150         # build pipeline

~\Anaconda3\lib\site-packages\rasa\nlu\components.py in validate_requirements(component_names)
     34     failed_imports = set()
     35     for component_name in component_names:
---> 36         component_class = registry.get_component_class(component_name)
     37         failed_imports.update(
     38             find_unavailable_packages(component_class.required_packages())

~\Anaconda3\lib\site-packages\rasa\nlu\registry.py in get_component_class(component_name)
    148                     "listed as part of the `component_classes` in "
    149                     "`rasa.nlu.registry.py` or is a proper name of a class "
--> 150                     "in a module.".format(component_name)
    151                 )
    152         else:

Exception: Failed to find component class for 'supervised_embeddings'. Unknown component name. Check your configured pipeline and make sure the mentioned component is not misspelled. If you are creating your own component, make sure it is either listed as part of the `component_classes` in `rasa.nlu.registry.py` or is a proper name of a class in a module.

```

**Content of configuration file (config.yml)**:
```# Configuration for Rasa NLU.
# https://rasa.com/docs/rasa/nlu/components/
language: it_core_news_sm
pipeline:
  - name: supervised_embeddings
  - name: SpacyNLP

# Configuration for Rasa Core.
# https://rasa.com/docs/rasa/core/policies/
policies:
  - name: MemoizationPolicy
  - name: KerasPolicy
  - name: MappingPolicy


```

**Content of domain file (domain.yml)** (if used & relevant):
```intents:
  - salutare
  - congedarsi
  - affermare
  - rifiutare
  - sentirsi_felice
  - sentirsi_triste
  - chiedere_info

actions:
- utter_saluto
- utter_rallegrarsi
- utter_utile
- utter_felice
- utter_congedarsi

templates:
  utter_saluto:
  - text: "Hey! Come stai?"

  utter_rallegrarsi:
  - text: "Ecco qualcosa per tirarti su il morale:"
    image: "https://i.imgur.com/nGF1K8f.jpg"

  utter_utile:
  - text: "Ti è stato utile?"

  utter_felice:
  - text: "Eddaje!"

  utter_congedarsi:
  - text: "Ciao"
```

**Comment by amn41** [comment]
Couple of things which aren’t quite right here. The name of the spacy-based pipeline is “pretrained_embeddings_spacy”. 

There is a single component called “SpacyNLP”, which is there to load the spacy language model. 

I think what you want is to combine the spacy word vectors with the classifier from supervised embeddings, is that right?

language: "en"

pipeline:
- name: "CountVectorsFeaturizer"
- name: "EmbeddingIntentClassifier"
  intent_tokenization_flag: true
  intent_split_symbol: "+"

**Comment by agarwalmridul09** [comment]
`KeyError                                  Traceback (most recent call last)
/usr/local/lib/python3.6/dist-packages/rasa_nlu/registry.py in get_component_class(component_name)
    106         try:
--> 107             return utils.class_from_module_path(component_name)
    108         except Exception:

/usr/local/lib/python3.6/dist-packages/rasa_nlu/utils/__init__.py in class_from_module_path(module_path)
    175     else:
--> 176         return globals()[module_path]
    177 

KeyError: 'SpacyNLP'
`

I get this error in this pipeline

**Comment by agarwalmridul09** [comment]
> Couple of things which aren’t quite right here. The name of the spacy-based pipeline is “pretrained_embeddings_spacy”.
> 
> There is a single component called “SpacyNLP”, which is there to load the spacy language model.
> 
> I think what you want is to combine the spacy word vectors with the classifier from supervised embeddings, is that right? Maybe something like:
> 
> ```
> language: "en"
> 
> pipeline:
> - name: "SpacyNLP"
> - name: “SpacyFeaturizer”
> - name: "EmbeddingIntentClassifier"
>   intent_tokenization_flag: true
>   intent_split_symbol: "+"
> ```
KeyError Traceback (most recent call last)
/usr/local/lib/python3.6/dist-packages/rasa_nlu/registry.py in get_component_class(component_name)
106 try:
--> 107 return utils.class_from_module_path(component_name)
108 except Exception:

/usr/local/lib/python3.6/dist-packages/rasa_nlu/utils/init.py in class_from_module_path(module_path)
175 else:
--> 176 return globals()[module_path]
177

KeyError: 'SpacyNLP'

I get this error in this pipeline

**Comment by akelad** [comment]
@agarwalmridul09 what training command are you running? Looks like it's using the `rasa_nlu` package as opposed to the `rasa` package

**Comment by akelad** [comment]
Actually sorry, you're not the original poster -- I assume you still have an old version of `rasa_nlu` installed -- it's likely the component names are different there

**Comment by ice2tricky** [comment]
supervised_embedings is a template from several components bundled together to make it easier to use
here is the overview from the components of this template
"WhitespaceTokenizer",
        "RegexFeaturizer",
        "CRFEntityExtractor",
        "EntitySynonymMapper",
        "CountVectorsFeaturizer",
        "EmbeddingIntentClassifier"

if you would like to change this flow, I think you will need to add all components together yourself, since I haven't found anywhere that you can use the template and the components together. According to the code when you use the following syntax "name: supervised_embeddings "it has to be in the list below or a custom component under rasa/nlu/utils. And this template is not there so it can't work.

# utils
    SpacyNLP,
    MitieNLP,
    # tokenizers
    MitieTokenizer,
    SpacyTokenizer,
    WhitespaceTokenizer,
    JiebaTokenizer,
    # extractors
    SpacyEntityExtractor,
    MitieEntityExtractor,
    CRFEntityExtractor,
    DucklingHTTPExtractor,
    EntitySynonymMapper,
    # featurizers
    SpacyFeaturizer,
    MitieFeaturizer,
    NGramFeaturizer,
    RegexFeaturizer,
    CountVectorsFeaturizer,
    # classifiers
    SklearnIntentClassifier,
    MitieIntentClassifier,
    KeywordIntentClassifier,
    EmbeddingIntentClassifier,
