### ISSUE TITLE
Configuring the value of `max_number_of_predictions` in `rasa_core.processor`

### ISSUE THREAD

**Issue by LucasLLC** [RasaHQ/rasa#3664]
**Rasa version**:
0.13.8
**Python version**: 
3.6.8
**Operating system** (windows, osx, ...):
Mac OsX
**Issue**:

I have a use case which requires more then 10 actions to be predicted in a row, and because of the default value of `max_number_of_predictions` in `rasa_core.processor`, I'm tripping the `circuit_breaker`. Is there any way to set this value from a configuration file?

**Content of configuration file (config.yml)**:
```yml

```

**Content of domain file (domain.yml)** (if used & relevant):
```yaml

```

**Comment by akelad** [comment]
Thanks for raising this issue, @tabergma  will get back to you about it soon.

**Comment by tabergma** [comment]
@LucasLLC It seems like that this value is fix. It is always set to 10. There is no way to set it from outside the code. 
I'll add a way to update this value for Rasa 1.0. Are you considering updating your Rasa version?

**Comment by LucasLLC** [comment]
Absolutely! Thanks!
