### ISSUE TITLE
Rasa installation on Windows 2016

### ISSUE THREAD

**Issue by narenmk** [RasaHQ/rasa#3665]
**Rasa version**: 1.0.3

**Python version**: 3.7.3

**Operating system** (windows, osx, ...): Windows 2016

**Issue**:

While installing rasa using pip install rasa facing below issue. 

**Content of configuration file (config.yml)**:
```yml

```

**Content of domain file (domain.yml)** (if used & relevant):
```yaml

```
Building wheels for collected packages: httptools
  Building wheel for httptools (setup.py) ... error
  ERROR: Complete output from command 'c:\python37\python.exe' -u -c 'import setuptools, tokenize;__file__='"'"'C:\\Users\\ADMINI~1\\AppData\\Local\\Temp\\pip-install-azwo3y4k\\httptools\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d 'C:\Users\ADMINI~1\AppData\Local\Temp\pip-wheel-9yjynf6b' --python-tag cp37:
  ERROR: running bdist_wheel
  running build
  running build_py
  creating build
  creating build\lib.win-amd64-3.7
  creating build\lib.win-amd64-3.7\httptools
  copying httptools\__init__.py -> build\lib.win-amd64-3.7\httptools
  creating build\lib.win-amd64-3.7\httptools\parser
  copying httptools\parser\errors.py -> build\lib.win-amd64-3.7\httptools\parser
  copying httptools\parser\__init__.py -> build\lib.win-amd64-3.7\httptools\parser
  running egg_info
  writing httptools.egg-info\PKG-INFO
  writing dependency_links to httptools.egg-info\dependency_links.txt
  writing top-level names to httptools.egg-info\top_level.txt
  reading manifest file 'httptools.egg-info\SOURCES.txt'
  reading manifest template 'MANIFEST.in'
  writing manifest file 'httptools.egg-info\SOURCES.txt'
  copying httptools\parser\parser.c -> build\lib.win-amd64-3.7\httptools\parser
  running build_ext
  building 'httptools.parser.parser' extension
  creating build\temp.win-amd64-3.7
  creating build\temp.win-amd64-3.7\Release
  creating build\temp.win-amd64-3.7\Release\httptools
  creating build\temp.win-amd64-3.7\Release\httptools\parser
  creating build\temp.win-amd64-3.7\Release\vendor
  creating build\temp.win-amd64-3.7\Release\vendor\http-parser
  C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\VC\Tools\MSVC\14.21.27702\bin\HostX86\x64\cl.exe /c /nologo /Ox /W3 /GL /DNDEBUG /MD -Ic:\python37\include -Ic:\python37\include "-IC:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\VC\Tools\MSVC\14.21.27702\include" "-IC:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\VC\Tools\MSVC\14.21.27702\include" "-IC:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\VC\Tools\MSVC\14.21.27702\bin\Hostx86\x64" /Tchttptools/parser/parser.c /Fobuild\temp.win-amd64-3.7\Release\httptools/parser/parser.obj -O2
  parser.c
  c:\python37\include\pyconfig.h(59): fatal error C1083: Cannot open include file: 'io.h': No such file or directory
  error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\BuildTools\\VC\\Tools\\MSVC\\14.21.27702\\bin\\HostX86\\x64\\cl.exe' failed with exit status 2
  ----------------------------------------
  ERROR: Failed building wheel for httptools
  Running setup.py clean for httptools
Failed to build httptools
Installing collected packages: httptools, sanic, sanic-plugins-framework, sanic-cors, kafka-python, rasa
  Running setup.py install for httptools ... error
    ERROR: Complete output from command 'c:\python37\python.exe' -u -c 'import setuptools, tokenize;__file__='"'"'C:\\Users\\ADMINI~1\\AppData\\Local\\Temp\\pip-install-azwo3y4k\\httptools\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\ADMINI~1\AppData\Local\Temp\pip-record-l_oe3g6s\install-record.txt' --single-version-externally-managed --compile:
    ERROR: running install
    running build
    running build_py
    creating build
    creating build\lib.win-amd64-3.7
    creating build\lib.win-amd64-3.7\httptools
    copying httptools\__init__.py -> build\lib.win-amd64-3.7\httptools
    creating build\lib.win-amd64-3.7\httptools\parser
    copying httptools\parser\errors.py -> build\lib.win-amd64-3.7\httptools\parser
    copying httptools\parser\__init__.py -> build\lib.win-amd64-3.7\httptools\parser
    running egg_info
    writing httptools.egg-info\PKG-INFO
    writing dependency_links to httptools.egg-info\dependency_links.txt
    writing top-level names to httptools.egg-info\top_level.txt
    reading manifest file 'httptools.egg-info\SOURCES.txt'
    reading manifest template 'MANIFEST.in'
    writing manifest file 'httptools.egg-info\SOURCES.txt'
    copying httptools\parser\parser.c -> build\lib.win-amd64-3.7\httptools\parser
    running build_ext
    building 'httptools.parser.parser' extension
    creating build\temp.win-amd64-3.7
    creating build\temp.win-amd64-3.7\Release
    creating build\temp.win-amd64-3.7\Release\httptools
    creating build\temp.win-amd64-3.7\Release\httptools\parser
    creating build\temp.win-amd64-3.7\Release\vendor
    creating build\temp.win-amd64-3.7\Release\vendor\http-parser
    C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\VC\Tools\MSVC\14.21.27702\bin\HostX86\x64\cl.exe /c /nologo /Ox /W3 /GL /DNDEBUG /MD -Ic:\python37\include -Ic:\python37\include "-IC:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\VC\Tools\MSVC\14.21.27702\include" "-IC:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\VC\Tools\MSVC\14.21.27702\include" "-IC:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\VC\Tools\MSVC\14.21.27702\bin\Hostx86\x64" /Tchttptools/parser/parser.c /Fobuild\temp.win-amd64-3.7\Release\httptools/parser/parser.obj -O2
    parser.c
    c:\python37\include\pyconfig.h(59): fatal error C1083: Cannot open include file: 'io.h': No such file or directory
    error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\BuildTools\\VC\\Tools\\MSVC\\14.21.27702\\bin\\HostX86\\x64\\cl.exe' failed with exit status 2
    ----------------------------------------
ERROR: Command "'c:\python37\python.exe' -u -c 'import setuptools, tokenize;__file__='"'"'C:\\Users\\ADMINI~1\\AppData\\Local\\Temp\\pip-install-azwo3y4k\\httptools\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\ADMINI~1\AppData\Local\Temp\pip-record-l_oe3g6s\install-record.txt' --single-version-externally-managed --compile" failed with error code 1 in C:\Users\ADMINI~1\AppData\Local\Temp\pip-install-azwo3y4k\httptools\

**Comment by akelad** [comment]
Could you take a look at this and see if that helps: https://stackoverflow.com/questions/40018405/cython-cannot-open-include-file-io-h-no-such-file-or-directory ?

**Comment by narenmk** [comment]
I tied the options mentioned in the above url but didn't work however I was able install on Win10 successfully but no tin WS2K16. Can you please help?

**Comment by akelad** [comment]
i'm honestly not sure, and i don't think this is a Rasa specific issue to be honest. I'd suggest you raise this issue with `httptools` instead, or on stackoverflow
