### ISSUE TITLE
How to run rasa x without docker as background process on Linux?

### ISSUE THREAD

**Issue by harunkelesoglu** [RasaHQ/rasa#3669]
I installed it on rasa x server. I can run it on background with following command.But ı can not see login password on nohup output.
```
nohup rasa x &
```
nohup.out
```
WARNING: The TensorFlow contrib module will not be included in TensorFlow 2.0.
For more information, please see:
  * https://github.com/tensorflow/community/blob/master/rfcs/20180907-contrib-sunset.md
  * https://github.com/tensorflow/addons
If you depend on functionality not listed there, please file an issue.

2019-05-31 11:57:53 INFO     root  - Starting Rasa Core server on http://localhost:5005
[92mStarting Rasa X in local mode... 🚀[0m
2019-05-31 11:57:55.682861: I tensorflow/core/platform/cpu_feature_guard.cc:141] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
INFO:apscheduler.scheduler:Scheduler started
```
**Rasa version**:
Rasa 1.0.3 

**Rasa X version** (if used & relevant):
Rasa 1.0.3 

**Python version**:
Python 3.6.8

**Operating system** (windows, osx, ...):
Linux Ubuntu

**Comment by akelad** [comment]
Thanks for raising this issue, @tabergma  will get back to you about it soon.

**Comment by amn41** [comment]
fyi you can also set the password with the `RASAX_PASSWORD` env var, so:
```
export RASAX_PASSWORD=mypassword; nohup rasa x &
```
should work. Then you can log in at `hostname/login?username=me&password=mypassword`

**Comment by harunkelesoglu** [comment]
@amn41  Unfortunately. 'export RASAX_PASSWORD=mypassword' command did not work.

**Comment by tabergma** [comment]
The environment variable is called `RASA_X_PASSWORD`. Can you try again?

**Comment by harunkelesoglu** [comment]
Thanks @tabergma it solved
