### ISSUE TITLE
CLI: --log-file not working

### ISSUE THREAD

**Issue by tabergma** [RasaHQ/rasa#3670]
**Rasa version**: 1.0

**Issue**:
According to the CLI you can specify a log file via `--log-file` for the commands `rasa run` and `rasa shell`. The logs should be stored in that file. However, after running, for example, `rasa run --log-file rasa.log` there is no log file at all.

Looking at the code, it seems like that the command line argument `log_file` is never used.

**Comment by tmbo** [comment]
Server actually uses it here https://github.com/RasaHQ/rasa/blob/master/rasa/server.py#L279 but probably gets lost somewhere on the way

**Comment by tabergma** [comment]
closed via https://github.com/RasaHQ/rasa/pull/3688

**Comment by Krogsager** [comment]
I'm experiencing this problem with rasa x 0.22.2.
No file is created when I run ` rasa run --log-file actions.log actions `
