### ISSUE TITLE
How do I run rasa x docker image?

### ISSUE THREAD

**Issue by harunkelesoglu** [RasaHQ/rasa#3671]
I took a look deploy on server. You said  "The Docker images for Rasa X Community Edition are freely available via Docker Hub". I got image from docker hub. Can you explain how it should be run? What is the What are the environments variable rasa x needs?
**Rasa version**:
1.0.13

**Rasa X version** (if used & relevant):
1.0.13

**Python version**:
3.6.5

**Operating system** (windows, osx, ...):
Linux Ubuntu

**Comment by akelad** [comment]
Please ask these kind of questions in our [forum](https://forum.rasa.com)
