### ISSUE TITLE
Custom NLU Components Failed to find component class

### ISSUE THREAD

**Issue by SalAlba** [RasaHQ/rasa#3673]
**Rasa version**: ``` 0.14```

**Rasa X version** (if used & relevant):

**Python version**: ``` 3.6```

**Operating system**: ``` Ubuntu ```

**Issue**:
I'm trying to make own Custom NLU Components, but rasa_nlu can't find my component, probably I miss something

```
rasa_nlu : 
├── classifiers
│   ├── ....
├── emulators
│   ├── ...
├── extractors
│   ├── ...
├── featurizers
│   ├── ...
├── schemas
│   └── ...
├── tokenizers
│   ├── ...
├── training_data
│   ├── ...
├── utils
│   ├── ...
│
│ 
├── customcomponents
│   ├── __init__.py
│   └── sentiment.py
│
│
├── __init__.py
├── registry.py
├── config.json
│
│
├── components.py
├── config.py
├── convert.py
├── data_router.py
├── evaluate.py
├── model.py
├── persistor.py
├── project.py
├── run.py
├── server.py
├── train.py
└── version.py
```

**My Custom component sentiment.py :**
```python

from rasa_nlu.components import Component
# all import needed

class MySentimentAnalyzer(Component):
    """A pre-trained sentiment component"""

    name = "MySentimentAnalyzer"
    provides = ["entities"]
    requires = ["tokens"]
    defaults = {}
    language_list = ["en"]

    def __init__(self, component_config=None):
        super(MySentimentAnalyzer, self).__init__(component_config)

  ## THE REST OF CODE ...
```

**registry.py :**

```python

from rasa_nlu.customcomponents.sentiment import MySentimentAnalyzer
# all import needed

component_classes = [
#
# all rasa components added no change
#
MySentimentAnalyzer
]

## THE REST OF COD
```

**Error (including full traceback)**:
```
{
  "error": "Failed to find component class for 'customcomponents.sentiment.MySentimentAnalyzer'. Unknown component name. Check your configured pipeline and make sure the mentioned component is not misspelled. If you are creating your own component, make sure it is either listed as part of the `component_classes` in `rasa_nlu.registry.py` or is a proper name of a class in a module."
}

```

**Command or request that led to error**: (Python)
```python

requests.post(
                url='http://0.0.0.0:5000/train',
                params = (('project', PROJECT_NAME), ('model', MODEL_NAME)),
                headers = {'content-type': 'application/x-yml'},
                data = data
            )
```

**Content of configuration file (config.json)** (if relevant):
```json
{
   "language":"pl",
   "pipeline":[
      {
         "name":"tokenizer_whitespace"
      },
      {
         "name":"customcomponents.sentiment.MySentimentAnalyzer"
      },
      {
         "name":"ner_duckling_http",
         "locale":"pl_Pl",
         "url":"http://127.0.0.1:8000",
         "dimensions":[
            "time",
            "number",
            "money"
         ]
      }
   ]
}
```

# NEED HELP :

in config file try different combinations, still rasa can't find my component :/ any ide wht's wrong ??

**Content of configuration file (config.json) which I try :** 

- name:"customcomponents.sentiment.MySentimentAnalyzer"
- name:"sentiment.MySentimentAnalyzer"
- name:".MySentimentAnalyzer"

All of them don't work for me :/

**Comment by therahulkumar** [comment]
@SalAlba I faced similar issue when I was working with a custom component, I solved it using exporting the custom component path as PYTHON_PATH.

**Comment by akelad** [comment]
@SalAlba does that suggestion help?

**Comment by SalAlba** [comment]
@therahulkumar Thank for advice, I do this

I add to ~/.bashrc 

``` bash

export PYTHONPATH=/home/sal/Python/rasa/rasa_nlu/customcomponents

```

then I check in in small python script

``` python
import sys
import os

from sentiment import MySentimentAnalyzer

print(os.environ['PYTHONPATH'])

print(MySentimentAnalyzer)

print(sys.path)

```


**Outputs :**

``` bash

## print(os.environ['PYTHONPATH'])
>>> /home/sal/Python/rasa/rasa_nlu/customcomponents

## print(MySentimentAnalyzer)
>>> <class 'sentiment.MySentimentAnalyzer'>

## print(sys.path)
>>> 
[
'/home/sal/Python/trainData', 
'/home/sal/Python/rasa/rasa_nlu/customcomponents', 
'/home/sal/Python/rasa_env/lib/python36.zip',
.
.
.
]
```


@akelad  Still I'm facing this problem with rasa can't find my component

**Error**:
```
{
  "error": "Failed to find component class for 'customcomponents.sentiment.MySentimentAnalyzer'. 
Unknown component name. Check your configured pipeline and make sure the mentioned component is 
not misspelled. If you are creating your own component, make sure it is either listed as part of the 
`component_classes` in `rasa_nlu.registry.py` or is a proper name of a class in a module."

}

```

**Comment by akelad** [comment]
Can I ask why you're using the json format for configuration? Also if you've added that dir to the python path, maybe try using just `sentiment.MySentimentAnalyzer` instead?

**Comment by mjspeck** [comment]
I've had a similar problem. The path to my sentiment analyzer is this: `nlu.custom_components.sentiment.SentimentAnalyzer`, but when I run `rasa train` I get this error: 

```python
Exception: Failed to find component class for 'nlu.custom_components.sentiment.SentimentAnalyzer'. Unknown component name. Check your configured pipeline and make sure the mentioned component is not misspelled. If you are creating your own component, make sure it is either listed as part of the `component_classes` in `rasa.nlu.registry.py` or is a proper name of a class in a module.
```

I haven't added the directory to my Python path, but I shouldn't need to do that, right?

**Comment by akelad** [comment]
@mjspeck can I ask you to post your directory structure as well, and also where you're running the command from?

**Comment by elyase** [comment]
The error message can be misleading. You will see the same error if your component fails to import for any reason i.e. missing dependencies or any syntax or other error you might have in your custom component. To debug try:

```
❯ python                                                                                                                     
>>> import importlib;importlib.import_module('your_custom_component')
```
Also check that you can import any dependencies you declared in `required_packages` . For example if your `required_packages` looks like:
```
    @classmethod
    def required_packages(cls) -> List[Text]:
        return ["nltk"]
```

check that you can import `nltk`.

**Comment by vitalyuf** [comment]
I faced the same problem.

The reason was that custom component code contained
`from rasa.nlu.featurizers import Featurizer`
line.
But after upgrading RASA version this import failes.
After replacement a line to the correct one the problem disappeared.
