### ISSUE TITLE
Apply Context in RASA

### ISSUE THREAD

**Issue by illi88** [RasaHQ/rasa#3675]
Hello  guys !!
I'm working with RASA, and I need to keep track of what has already happened in the conversation, like , user asks : **"what's the color of the house "** ,after he asks: **"and its price ?"** , I want to know that he meant the price of the house
I know that dialogflow uses the notion of **context** to solve this type of problem,I**s there any solution to solve that in RASA?**          
Please I need a quieck answer !!

**Comment by alexissmirnov** [comment]
Sorry I don't think it's a quick answer or solution but please see the discussion and a PR here: https://github.com/RasaHQ/rasa/issues/3015

What you're describing can be implemented as an extension to what I did in that PR. The NLU server would need to receive the tracker state. In your example, you would need to resolve the co-reference "its" in "and its price?" based on the previously-collected state. It may be that you'd need to pass the previous messages and/or the slots and handle it on NLU side.

Also, note I'm not a core committer so I may be wrong, but I'm also interested in this use-case.

**Comment by akelad** [comment]
Please ask these kind of questions in our [forum](https://forum.rasa.com)
