### ISSUE TITLE
Exception: Visualization has failed. Please refresh the page.

### ISSUE THREAD

**Issue by true1337** [RasaHQ/rasa#3685]
**Rasa version**: 1.0.3

**Rasa X version**: 0.19.0

**Python version**: 3.6

**Operating system**: Ubuntu

**Issue**:

Can't visualize story tree

**Error (including full traceback)**:

![image](https://user-images.githubusercontent.com/26603018/58800826-97271e00-8611-11e9-8f1c-18f12aab6e34.png)

tell me what else I have to provide

**Comment by akelad** [comment]
Thanks for raising this issue, @gausie  will get back to you about it soon.

**Comment by tmbo** [comment]
@true1337 do you mind adding the story that led to the error?

**Comment by true1337** [comment]
@tmbo Sure, i'm getting this error even in [rasa-demo](https://github.com/RasaHQ/rasa-demo) repository.

Seems to me this line causes the error

```
* enter_data{"number":5}
```
Full story:
```
## story number 18
* greet
    - action_greet_user
* ask_weather
    - action_chitchat
* ask_whatspossible
    - action_chitchat
* deny
    - utter_nohelp
* enter_data
    - utter_not_sure
    - utter_possibilities
* deny
    - utter_nohelp
* out_of_scope
    - utter_out_of_scope
    - utter_possibilities
* enter_data{"number":5}
    - utter_not_sure
    - utter_possibilities
* enter_data
    - utter_not_sure
    - utter_possibilities
```

**Comment by tmbo** [comment]
I think this is a backend issue, might be that the visualisation code doesn't escape something properly when dumping the dot file.

**Comment by akelad** [comment]
ok to whoever fixes this: i can reproduce it on our deployed instance of Rasa X with Sara, please ping me on Slack so I can give you more details if you need them

**Comment by msamogh** [comment]
I tried installing the versions of Rasa and Rasa X specified by @true1337, but wasn't able to reproduce it with the story in the image.

I also tried using this story https://github.com/RasaHQ/rasa/issues/3685#issuecomment-502989201 on the deployed instance of Sara as @akelad mentioned, but I couldn't reproduce it there either.

**Comment by akelad** [comment]
@msamogh just try clicking on some stories that already exist on that instance, it should happen eventually

**Comment by msamogh** [comment]
@akelad I wasn't able to reproduce this in the latest version of Rasa X (after performing a native installation). Could this be a 0.19.0 specific issue?

**Comment by msamogh** [comment]
@akelad I checked the network logs when this happens and the dot file content in the response seems to be valid (checked it on an online visualizer). So does that mean it's a frontend issue?

**Comment by gausie** [comment]
This has since become stale and been fixed. Future unexpected visualization failures now do not require the page to be refreshed.

**Comment by true1337** [comment]
This issue is not about rendering but the impossibility to render the story.
Upgraded to rasa 1.1.8 and rasa-x 0.20.0 still have this problem.

![image](https://user-images.githubusercontent.com/26603018/62117242-3db33680-b2c4-11e9-857e-dd6b50dc961b.png)

**Comment by tmbo** [comment]
I think the error is slightly different. Can you please create a new issue, attaching the screenshot as well as the whole story you are trying to render?

**Comment by true1337** [comment]
Sure

**Comment by gausie** [comment]
Yes, we should open a separate issue on that specific bug. It occurs because the backend currently generates malformed DOT for any visualization with an intent + entity like `* choose{"topic":"domain"}`. I think it might also only be for certain python versions.

I closed this issue because we stopped the exception from crashing the page though.
