### ISSUE TITLE
RASA X removing my Entity Synonyms

### ISSUE THREAD

**Issue by IsaacEllum** [RasaHQ/rasa#3687]
**Rasa version**: 1.0.1

**Rasa X version** (if used & relevant):0.19.0

**Python version**:3.7.3

**Operating system** (windows, osx, ...):Windows

**Issue**:My original model was train using a JSON file. However, when using RASA X it generates a MarkDown file with any new conversational data, then when I retrain it only looks at this new .MD file.

I got around this by just uploading my JSON file to RASA X and it added all the data to the .MD file, however it ignored all of the synonyms. I tried to then add the synonyms manually into the .MD file, but every time I run RASA X it removed all the synonym values. Is there a way to add synonyms straight into RASA X?

**Command or request that led to error**:rasa x

**Comment by akelad** [comment]
Thanks for raising this issue, @ricwo  will get back to you about it soon.

**Comment by ricwo** [comment]
Thanks for spotting this @IsaacEllum - I can confirm that uploaded entity synonyms aren't persisted to markdown. We'll be looking into this

**Comment by TyDunn** [comment]
@IsaacEllum This was fixed in the latest version of Rasa X: `Release 0.19.1`. You should upgrade to this new version!
