### ISSUE TITLE
How to serve multiple NLU models from an NLU-only server in 1.0.x?

### ISSUE THREAD

**Issue by ynouri** [RasaHQ/rasa#3689]
**Rasa version**: 1.0.4

**Issue**:

Hi,

Thanks for the awesome work you guys are doing. We really appreciate the effort put in the recent releases of Rasa 1.0 and Rasa X.

I'm trying out 1.0.4 (upgrading from 0.14.4) and I am realizing that an important feature our deployments are relying on seems to have changed in 1.0.x: the ability for the NLU server to load and serve multiple models simultaneously.

* In 0.14.4, we can serve multiple models by running the NLU server with a path pointing to a folder (e.g. `./models`) containing multiple models using:
`python -m rasa_nlu.server --path models`
Then multiple models can be called (and loaded) by the NLU server by using a POST on /parse endpoint:
`{"q": "Some text", "project": "my_project", "model": "nlu_model_01"}`
`{"q": "Some text", "project": "my_project", "model": "nlu_model_02"}`

* In 1.0.x, I can serve a single model using the command:
`rasa run --enable-api -m models/nlu-20190603-135554.tar.gz`
but it's unclear to me how serving multiple models can be achieved. The [documentation ](https://rasa.com/docs/rasa/user-guide/running-the-server/#fetching-models-from-a-server) seems to mention a notion of tag: `default@latest` but I'm not sure if that provides the same functionality.

Note: it looks like the change was done through PR #3373.

Any guidance on this would be much appreciated.

Thanks!

**Comment by amn41** [comment]
correct, we took that functionality out, please see this issue https://github.com/RasaHQ/rasa/issues/3259 for a discussion, would love to hear your thoughts
