### ISSUE TITLE
Iterative answering 

### ISSUE THREAD

**Issue by LKiera** [RasaHQ/rasa#3693]
**Rasa version**:
rasa-core                     0.14.3             
rasa-core-sdk                 1.0.0rc2           
rasa-nlu                      0.15.

**Rasa X version** (if used & relevant):

**Python version**:
Python 3.6.7
**Operating system** (windows, osx, ...):
Ubuntu 18.04
**Issue**:
Is there any way we can get an answer by the question sent by the back end function?

**Error (including full traceback)**:
```

```

**Command or request that led to error**:
```

```

**Content of configuration file (config.yml)** (if relevant):
```yml

```

**Content of domain file (domain.yml)** (if relevant):
```yml

```

**Comment by akelad** [comment]
Not sure I understand the question, but these types of usage questions should be posted in the [forum](https://forum.rasa.com)
