### ISSUE TITLE
how to use numeric values in rasa

### ISSUE THREAD

**Issue by ravisurapati** [RasaHQ/rasa#3696]
**Rasa version**: rasa x

**Rasa X version** (if used & relevant):

**Python version**: 3.6

**Operating system** (windows, osx, ...): linux

**Issue**:
when i am trying to use numbers for two different intents, it only accepts first one only, i want to build a application that only accept numbers instead of strings, i am facing issues and , if i want to mention numbers from 1 to 1000  in an intent and two intents have the same values, i am not able to run my story, please help me

**Error (including full traceback)**:
```

```

**Command or request that led to error**:
```

```

**Content of configuration file (config.yml)** (if relevant):
```yml

```

**Content of domain file (domain.yml)** (if relevant):
```yml

```

**Comment by akelad** [comment]
Please ask these kind of questions in our [forum](https://forum.rasa.com)
