### ISSUE TITLE
SQLite event stream

### ISSUE THREAD

**Issue by tmbo** [RasaHQ/rasa#3702]
Currently we are using the sqlite tracker store to stream events from Rasa to Rasa X. This has the downside, that Rasa X locally only works with the sqlite db.

Instread of using the sqlite tracker store to access the events, there should be a separate `EventChannel` implementation which dumps these events. Rasa X should then read the events and after processing them delete them from the table. This way the file will stay small and seeks are fast.

**Comment by wochinge** [comment]
@federicotdn Please update the ticket status

**Comment by federicotdn** [comment]
GH closed the issue but the changes on Rasa X have not yet been merged in.
