### ISSUE TITLE
Docker error : Container is restarting

### ISSUE THREAD

**Issue by Amagali** [RasaHQ/rasa#3704]
**Rasa version**:
Rasa 1.0.6
**Rasa X version**:
I can't see the version anywhere
**Python version**:
Python 2.7.15rc1
**Operating system**:
Ubuntu 18.04.2 LTS
**Issue**:
Error response from daemon: Container is restarting, wait until the container is running

**Error (including full traceback)**:
Error response from daemon: Container is restarting, wait until the container is running
ERROR:__main__:Failed to create user.

**Command or request that led to error**:
```
sudo python rasa_x_commands.py create admin me password
```
Tried to deploy a Rasa X instance on a server for test purposes directly from [here](https://rasa.com/docs/rasa-x/deploy/#quick-installation)

Maybe I need to install another thing before or check something else?

**Comment by akelad** [comment]
This sounds like the container isn't running properly. What commands did you use to start the container? And can you post the logs of whichever container is restarting?

**Comment by Amagali** [comment]
I've just cleaned my installation and proceed to reinstall again but I got the same error again when trying to run
`sudo python rasa_x_commands.py admin username password`

Thre previously command was:
`sudo docker-compose up -d`

Which did this:
`Creating network "rasa_default" with the default driver
Pulling duckling (rasa/duckling:latest)...
latest: Pulling from rasa/duckling
c5e155d5a1d1: Pull complete
5e301be12a0a: Pull complete
23656e988c30: Pull complete
c11a3cc602f9: Pull complete
225543a43426: Pull complete
ffd25465ce24: Pull complete
0fcf3df9c031: Pull complete
1def84b5fb36: Pull complete
420c6bffd96c: Pull complete
Digest: sha256:98724994d3e028dc22a7d3faffc8d773b9a7b56e934c27f8e4d881724282ac30
Status: Downloaded newer image for rasa/duckling:latest
Pulling db (bitnami/postgresql:11.2.0)...
11.2.0: Pulling from bitnami/postgresql
566f5be5c416: Pull complete
dc54b0ea6f88: Pull complete
c1a99f6f41a0: Pull complete
9d68af7b836b: Pull complete
2db371054a03: Pull complete
0ef919c3d7c7: Pull complete
9bc21622db62: Pull complete
ef8ee26eb485: Pull complete
8b47f78bf978: Pull complete
201e494b646f: Pull complete
Digest: sha256:0031128f9451ab3243e115ecb7ade6ba9386b0df061ae2e704ad8e22aed681f8
Status: Downloaded newer image for bitnami/postgresql:11.2.0
Pulling rasa-x (rasa/rasa-x:latest)...
latest: Pulling from rasa/rasa-x
743f2d6c1f65: Pull complete
977e13fc7449: Pull complete
5cb966e905c8: Pull complete
1d6fd464f33f: Pull complete
28d1c2388e9d: Pull complete
c438a52f0abe: Pull complete
c00e580262e5: Pull complete
cdd88a93d403: Pull complete
15c53341e01d: Pull complete
6f2a19a91998: Pull complete
29c6372f35f8: Pull complete
Digest: sha256:e69499cb3ce6a06942af4ca77f55f18da47d3fad24294a54a78d5cd963340ab0
Status: Downloaded newer image for rasa/rasa-x:latest
Pulling rabbit (bitnami/rabbitmq:3.7.5)...
3.7.5: Pulling from bitnami/rabbitmq
c407efbb570c: Pull complete
36cc7b4bfcaa: Pull complete
4f2f12564285: Pull complete
09c161fb3e38: Pull complete
fed5923b5a7d: Pull complete
2f63c92dcfcf: Pull complete
5eb42eed7e08: Pull complete
9895636bd4a0: Pull complete
ae7e96c73cc6: Pull complete
70accba91d14: Pull complete
72ec77cf641a: Pull complete
Digest: sha256:8253f8263a8eeefba09af3320b1526965bf5f9311de6a5e738dd9a3699ba534b
Status: Downloaded newer image for bitnami/rabbitmq:3.7.5
Pulling rasa-production (rasa/rasa:1.0.0-full)...
1.0.0-full: Pulling from rasa/rasa
743f2d6c1f65: Already exists
977e13fc7449: Already exists
5cb966e905c8: Already exists
1d6fd464f33f: Already exists
28d1c2388e9d: Already exists
5acf0eb4d182: Pull complete
2f0555b93310: Pull complete
4c9e6d5284e8: Pull complete
593a4e0a1c02: Pull complete
4971b8fc1027: Pull complete
4b2a1db12931: Pull complete
2c9c35f4cf1f: Pull complete
6bad0d53649b: Pull complete
111c07f0302d: Pull complete
Digest: sha256:5b998e2bc665cac09dae7070fd972ccbfa947760d58e0b7adfd0262540bc0e0f
Status: Downloaded newer image for rasa/rasa:1.0.0-full
Pulling app (rasa/rasa-x-demo:0.19.0)...
0.19.0: Pulling from rasa/rasa-x-demo
743f2d6c1f65: Already exists
977e13fc7449: Already exists
5cb966e905c8: Already exists
1d6fd464f33f: Already exists
28d1c2388e9d: Already exists
5d98ee6c100f: Pull complete
d0add5b7e500: Pull complete
5b0a56633876: Pull complete
6be4321caa43: Pull complete
97823c5efc6a: Pull complete
424106cb0773: Pull complete
Digest: sha256:ce085d0f9e39e5d0314ccaaf37336fcaa716ea4d24ec08b95029b712fac1f483
Status: Downloaded newer image for rasa/rasa-x-demo:0.19.0
Pulling nginx (rasa/nginx:latest)...
latest: Pulling from rasa/nginx
cf0573f82455: Pull complete
5e911cd09c10: Pull complete
94e25fc31920: Pull complete
f1c62dbf5b6d: Pull complete
dfc2d5f70b88: Pull complete
7b4f76c6aba2: Pull complete
ace422244d61: Pull complete
5c82478e6c22: Pull complete
0221d4bab8b4: Pull complete
8af694f1e142: Pull complete
d70624fa4149: Pull complete
45e101d8b756: Pull complete
33d08fcade19: Pull complete
328ccfba9c74: Pull complete
12089e99af7d: Pull complete
53c83af9d117: Pull complete
9a876b4ab03d: Pull complete
Digest: sha256:09adf86eee3a10b6a9fb25826f3a4c09fb2c8b6c6dad772e77b6ff35409074b0
Status: Downloaded newer image for rasa/nginx:latest
Pulling logger (rasa/logger:latest)...
latest: Pulling from rasa/logger
c87736221ed0: Pull complete
e97df4b4a1f1: Pull complete
Digest: sha256:c0ed05bd295a8a298cb971fba47f8b3acf25fb7861ab3c7476c1d4642e9779b6
Status: Downloaded newer image for rasa/logger:latest
Creating rasa_db_1       ... done
Creating rasa_rabbit_1   ... done
Creating rasa_duckling_1 ... done
Creating rasa_rasa-x_1   ... done
Creating rasa_rasa-worker_1     ... done
Creating rasa_rasa-production_1 ... done
Creating rasa_app_1             ... done
Creating rasa_nginx_1           ... done
Creating rasa_logger_1          ... done
`
The container that is restarting is the rasa/rasa-x:latest
`dccd5b81e587        rasa/rasa-x:latest          "python -m rasax.com…"   17 minutes ago      Restarting (1) 4 seconds ago                                                 rasa_rasa-x_1
`
Note 1: On install.sh, I changed the "stable" for "latest", since stable has problems. If this has errors, please can you tell me a version that is actually working?

Note 2: It's worth mentioning that I'm trying to use Community edition, but the docs are wrong and instead of using the set password command, I'm using what it's inside the rasa_x_commands.py "create role username pass"

**Comment by akelad** [comment]
the command for creating a password is broken, we're aware of that and it'll be fixed in the next release.
Can you post the output of `sudo docker-compose logs rasa-x`? Because that seems like a separate issue to the password creation. I wouldn't advise using latest, that's likely to contain bugs as well

**Comment by Amagali** [comment]
Here you have:

```
rasa-x_1           | WARNING: The TensorFlow contrib module will not be included in TensorFlow 2.0.
rasa-x_1           | For more information, please see:
rasa-x_1           |   * https://github.com/tensorflow/community/blob/master/rfcs/20180907-contrib-sunset.md
rasa-x_1           |   * https://github.com/tensorflow/addons
rasa-x_1           | If you depend on functionality not listed there, please file an issue.
rasa-x_1           | 
rasa-x_1           | Traceback (most recent call last):
rasa-x_1           |   File "/usr/local/lib/python3.6/runpy.py", line 193, in _run_module_as_main
rasa-x_1           |     "__main__", mod_spec)
rasa-x_1           |   File "/usr/local/lib/python3.6/runpy.py", line 85, in _run_code
rasa-x_1           |     exec(code, run_globals)
rasa-x_1           |   File "/usr/local/lib/python3.6/site-packages/rasax/community/server.py", line 56, in <module>
rasa-x_1           |     main()
rasa-x_1           |   File "/usr/local/lib/python3.6/site-packages/rasax/community/server.py", line 23, in main
rasa-x_1           |     sql_migrations.run_migrations(session)
rasa-x_1           |   File "/usr/local/lib/python3.6/site-packages/rasax/community/sql_migrations.py", line 25, in run_migrations
rasa-x_1           |     _run_schema_migrations(session)
rasa-x_1           |   File "/usr/local/lib/python3.6/site-packages/rasax/community/sql_migrations.py", line 41, in _run_schema_migrations
rasa-x_1           |     alembic_config.set_main_option("sqlalchemy.url", str(session.bind.url))
rasa-x_1           |   File "/usr/local/lib/python3.6/site-packages/alembic/config.py", line 237, in set_main_option
rasa-x_1           |     self.set_section_option(self.config_ini_section, name, value)
rasa-x_1           |   File "/usr/local/lib/python3.6/site-packages/alembic/config.py", line 264, in set_section_option
rasa-x_1           |     self.file_config.set(section, name, value)
rasa-x_1           |   File "/usr/local/lib/python3.6/configparser.py", line 1193, in set
rasa-x_1           |     super().set(section, option, value)
rasa-x_1           |   File "/usr/local/lib/python3.6/configparser.py", line 894, in set
rasa-x_1           |     value)
rasa-x_1           |   File "/usr/local/lib/python3.6/configparser.py", line 402, in before_set
rasa-x_1           |     "position %d" % (value, tmp_value.find('%')))
rasa-x_1           | ValueError: invalid interpolation syntax in 'postgresql://admin:I%3An_WdrCnqQGdKy@db:5432/rasa' at position 20
rasa-x_1           | INFO:apscheduler.scheduler:Scheduler started

```

Again, which version should I try? Because stable doesn't work either.

**Comment by akelad** [comment]
@wochinge any idea what's going wrong there?

**Comment by wochinge** [comment]
Please use version`0.19.0` instead of the `latest` tag. For me it seems sth is wrong with your endpoints config. Can you share it with us?

**Comment by mloetscher** [comment]
I have the same problem, my endpoints config is:

models:
   url: ${RASA_MODEL_SERVER}
   token: ${RASA_X_TOKEN}
   wait_time_between_pulls: ${RASA_MODEL_PULL_INTERVAL}
tracker_store:
   type: sql
   dialect: "postgresql"
   url: ${DB_HOST}
   port: ${DB_PORT}
   username: ${DB_USER}
   password: ${DB_PASSWORD}
   db: ${DB_DATABASE}
   login_db: ${DB_LOGIN_DB}
event_broker:
   type: "pika"
   url: ${RABBITMQ_HOST}
   username: ${RABBITMQ_USERNAME}
   password: ${RABBITMQ_PASSWORD}
   queue: ${RABBITMQ_QUEUE}
action_endpoint:
   url: ${RASA_USER_APP}/webhook
   token:  ""
