### ISSUE TITLE
Buttons are not displayed in Rasa X UI if followed by another message in custom action

### ISSUE THREAD

**Issue by lomarceau** [RasaHQ/rasa#3710]
**Rasa version**: 1.0.1

**Rasa X version** (if used & relevant): 0.19

**Python version**: 3.6.8

**Operating system** (windows, osx, ...): Centos 7

**Issue**:
When running a custom action with following code :
```
dispatcher.utter_button_message(text, buttons=buttons)
dispatcher.utter_message(transition_message)
```
The buttons from utter_button_message are not displayed in Rasa X UI. The text from utter_button_message followed directly by utter_message will be displayed. When removing the transition_message, the buttons show up correctly, so the quick succession of the dispatcher commands might be the cause of the problem.

**Comment by akelad** [comment]
This is intended, they usually disappear in different platforms such as facebook messenger or telegram as well. Because you don't want the user pressing buttons that are no longer relevant to the conversation.
Does that make sense?

**Comment by lomarceau** [comment]
Fair enough, on the downside it prevents the use of transition messages after buttons like "if the answer you are looking for is not in the options, please rephrase" but I understand the logic and they can always be added to text coming before the buttons even though it's not as clean. Thank you, I will close the issue.

**Comment by koaning** [comment]
@lomarceau and anybody looking at this issue. You have a clean syntax nowadays.

```python
buttons = generate_appropriate_buttons()
dispatcher.utter_message(
    text="It wasn't 100% clear what you meant. Could you speficy/rephrase?", 
    buttons=buttons
)
```
