### ISSUE TITLE
don't require model if model server is given

### ISSUE THREAD

**Issue by wochinge** [RasaHQ/rasa#3722]
If Rasa uses a model server endpoint it should not require a model path when running even if `--enable-api` is `False` (or not specified).

**Comment by erohmensing** [comment]
@tabergma your PR handled this right?

**Comment by tabergma** [comment]
closed by https://github.com/RasaHQ/rasa/pull/3942

**Comment by wochinge** [comment]
Mhm, but rasa run with no model in models/ would still fail right? Cause we have the check in cli/run whether a model is present.

**Comment by tabergma** [comment]
If you start `rasa run` without `--enable-api` you still need to have a valid model in the models directory. That is correct. You need to have a local model in that case.

**Comment by wochinge** [comment]
But then we should reopen this issue since specifying `--enable-api` in order to run with a remote model is quite weird.

**Comment by tabergma** [comment]
Agree. Should we update the description/title to make clear it is only about the case when `rasa run` is executed without `--enable-api`?
