### ISSUE TITLE
Multiple issues regarding Jupyter notebooks

### ISSUE THREAD

**Issue by ricardopieper** [RasaHQ/rasa#3724]
**Rasa version**: 1.0.7

**Rasa X version** (if used & relevant):

**Python version**: 3.7.3

**Operating system** (windows, osx, ...): osx

**Issue**: This is not related to #3579. I can't fit this issue in the format you asked, but I'll try to picture what I'm going through. I'm not very proficient with python but here are my findings:

### Case 1: Rasa is not found

The setup is as follows:

- `/home/ricardo/nlu-experiments`: my virtualenv folder where I installed Rasa 1.0.7
- `/home/ricardo/nlu-experiments/rasa`: Folder where I run rasa stuff (where I ran `rasa init --no-prompt`)
- `/home/ricardo/nlu-experiments/rasa/notebook.ipynb`: Notebook file

I run `jupyter notebook` on `/home/ricardo/nlu-experiments`. Then I navigate to the `rasa` folder in the jupyter UI, and open the notebook.ipynb file. A simple `import rasa` results in:

    ModuleNotFoundError: No module named 'rasa'

I suppose this has something to do with Virtualenv (update: removing virtualenv did not fix the issue). I could just move my notebook out of the Rasa folder then... which then becomes Case 2:

### Case 2: Empty rasa module

The setup is roughly similar:

`/home/ricardo/nlu-experiments`: my virtualenv folder where I installed Rasa 1.0.7
`/home/ricardo/nlu-experiments/rasa`: Folder where I have some .md files and a CSV containing (text, intent) pairs which I want to check against Rasa.
`/home/ricardo/nlu-experiments/notebook.ipynb`: Notebook file

I run `jupyter notebook` on `/home/ricardo/nlu-experiments` and open the notebook.ipynb file.  Notebook contents are:

```
import rasa #works fine
rasa.train()
```

Of course this call to rasa.train() is invalid because I'm not passing any parameters. But the actual error is:

```
AttributeError: module 'rasa' has no attribute 'train'
````

That is weird. I then run `dir(rasa)` and the output is:

```
['__builtins__',
 '__cached__',
 '__doc__',
 '__file__',
 '__loader__',
 '__name__',
 '__package__',
 '__path__',
 '__spec__']
```

Seems like the module is empty and there are no functions to call. Is this normal? I'll try running everything without virtualenv to see what happens.

Update: running without virtualenv changes nothing.

**Error (including full traceback)**:
```
Not applicable
```

**Command or request that led to error**:
```
import rasa, or rasa.train()
```

**Content of configuration file (config.yml)** (if relevant):
```yml
language: en
pipeline: supervised_embeddings
```

**Content of domain file (domain.yml)** (if relevant):
```yml
```

**Comment by akelad** [comment]
Thanks for raising this issue, @amn41  will get back to you about it soon.

**Comment by amn41** [comment]
I suspect in case 2 python is trying to load the `rasa` package from the path `rasa`. 
I would recommend the following:
- create a new virtualenv
- install rasa in it
- make sure you have a jupyter kernel for your virtualenv, see [here](https://ipython.readthedocs.io/en/stable/install/kernel_install.html)
- run `jupyter notebook` in a dir where there isn't anything called `rasa`
- select the correct kernel from the dropdown once you're in the jupyter notebook UI

**Comment by ricardopieper** [comment]
Yes, it was all my fault. Renaming the `rasa` folder to `rasa_test` solved the issue.

Thanks @amn41
