### ISSUE TITLE
Add info that python >= 3.5.3 is required

### ISSUE THREAD

**Issue by akelad** [RasaHQ/rasa#3730]
aiohttp has a requirement of >= 3.5.3, therefore we also do. We should update this in our docs, the README and on pypi

**Comment by jp8042** [comment]
I would like to work on it. If the issue is open.

**Comment by akelad** [comment]
Not sure this is the best issue to work on for a community member -- you can check out issues labelled with `help wanted` or `good first issue` though, we'd love a community contribution from you!
