### ISSUE TITLE
Encountered an exception while running action 'action_get_answer'. Bot will continue, but the actions events are lost. Make sure to fix the exception in your custom code.

### ISSUE THREAD

**Issue by agrawal-mohit** [RasaHQ/rasa#3737]
I'm trying to implement custom actions and have added `action_get_answer` to **`domain.yml`**.
```
actions:
- utter_greet
- utter_cheer_up
- utter_did_that_help
- utter_happy
- utter_goodbye
- actions.GetAnswer
```

Added the action in **`actions.py`** :

```
class GetAnswer(Action):

    def name(self) -> Text:
        return "action_get_answer"


    def run(self, dispatcher: CollectingDispatcher,
            tracker: Tracker,
            domain: Dict[Text, Any]) -> List[Dict[Text, Any]]:
    
        dispatcher.utter_message("action_get_answer")

        return []
```
Ran the action server: 
`$ rasa run actions`

Upon running rasa server : 
`$ rasa x`

 i get this error and `GetAnswer` is not triggered -

> ERROR    rasa.core.processor  - Encountered an exception while running action 'action_get_answer'. Bot will continue, but the actions events are lost. Make sure to fix the exception in your custom code.

How do I make this work? 

Thanks

**Comment by amn41** [comment]
can you please show the logs of your action server? that should show what the exception is

**Comment by agrawal-mohit** [comment]
Hi @amn41 , the `rasa_core.log` file is empty. Could you help me locate the log you are asking about ?

**Comment by amn41** [comment]
I mean the output of the process which you started by running `rasa run actions`

**Comment by a461925358** [comment]
解决没,我也有这样的问题

**Comment by amn41** [comment]
Hi @a461925358 - please post your question in english.

**Comment by Akhil1278** [comment]
i am trying to implement a form using custom actions
but i am getting this error
![Screenshot (27)](https://user-images.githubusercontent.com/65960157/82906630-2ba53180-9f83-11ea-9263-bc1b158ab9d9.png)

**Comment by 1535966643** [comment]
> 解决没,我也有这样的问题

这就是高版本的代码 到低版本运行的错误

**Comment by premchopra1098** [comment]
could any one please share solution of above error?please
