### ISSUE TITLE
--data option fails.

### ISSUE THREAD

**Issue by studiocardo** [RasaHQ/rasa#3741]
**Rasa version**: 1.0.1

**Rasa X version** (if used & relevant):

**Python version**: 3.6.7

**Operating system** (windows, osx, ...): Ubuntu 16.04

**Issue**:
1. --data option does not work in "rasa train"
2. err msg misleading: No NLU data given. Please provide NLU data in order to train a Rasa NLU model using the '--nlu' argument.

Per http://rasa.com/docs/rasa/user-guide/command-line-interface/

If the ./data directory is present, "rasa train" builds by grabbing data from ./data, however, if ./data is removed, the build fails and displays the err msg despite the explicit use of --data option

And there is no such an option '--nlu' in 1.0.

**Error (including full traceback)**:
```
No NLU data given. Please provide NLU data in order to train a Rasa NLU model using the '--nlu' argument.

```

**Command or request that led to error**:
```
#!/bin/bash

rasa train -v \
    --config ./nlu_config.yml \
    --data ./NLU_train_data \
    --out ./models \
    nlu

```

**Content of configuration file (config.yml)** (if relevant):
```yml
language: "en"

pipeline: "supervised_embedding"

```

**Content of domain file (domain.yml)** (if relevant):
```yml

```

**Comment by lahsuk** [comment]
The argument has changed from `--data` to `-u | --nlu`. So, in your case, it should be
`rasa train -v --config ./nlu_config.yml --nlu ./NLU_train_data --out ./models`

**Comment by studiocardo** [comment]
Thx Iahsuk, I'll give it a try.  In the meantime, hopefully Rasa can update

http://rasa.com/docs/rasa/user-guide/command-line-interface/

as well as the command line err msg with the new options.

Best,
J

**Comment by akelad** [comment]
`rasa train` works with the `--data` flag, are you sure your training file is in the correct format? the `--nlu` flag only works with the `rasa train nlu` command

**Comment by Lambik** [comment]
I have this same issue.

My command line is this: `rasa train --data /mnt/hgfs/backend/storage/app/rasa/nlu_test --out /mnt/hgfs/backend/storage/app/rasa --fixed-model-name nlu_test_model nlu`

My nlu file ("nlu_test") is simple:

```
## intent:16
- yes
- indeed
- of course
- that sounds good
- correct

## intent:7
- no
- never
- I don't think so
- don't like that
- no way
- not really

## intent:1
- bye
- goodbye
- see you around
- see you later

## intent:22
- hey
- hello
- hi
- good morning
- good evening
- hey there

## intent:30
- perfect
- very good
- great
- amazing
- wonderful
- I am feeling very good
- I am great
- I'm good

## intent:39
- sad
- very sad
- unhappy
- bad
- very bad
- awful
- terrible
- not very good
- extremely sad
- so sad

```

And I get the error `No NLU data given. Please provide NLU data in order to train a Rasa NLU model using the '--nlu' argument.`

There is no such thing as an `--nlu` parameter.

**Comment by Lambik** [comment]
Oh, through digging through the source code... I got it working, so this is a post for future google searchers:

There is indeed an --nlu option, that is not in the manual.
The other thing that is important, is that my model filename **has to end with .md**

The final train command is: `rasa train nlu --nlu /mnt/hgfs/backend/storage/app/rasa/nlu_test.md --out /mnt/hgfs/backend/storage/app/rasa --fixed-model-name nlu_test_model`

The final model name will automatically get a `.tar.gz` extension.

So this issue can remain closed :-) but maybe docs could be updated a bit.
