### ISSUE TITLE
There was an error loading messages and polling has been stopped in rasa x.

### ISSUE THREAD

**Issue by ravikrcs** [RasaHQ/rasa#3744]
**Rasa version**: 1.0.1

**Rasa X version** (if used & relevant):

**Python version**: 3.6.8

**Operating system** (windows, osx, ...): windows

**Issue**:
There was an error loading messages and polling has been stopped in rasa x.

**Error (including full traceback)**:
```
raise client_error<req.connection_key, exc> from excaiohttp.client_exceptions.ClientError:
cannot connect to host localhost:5005 ssl:None [connect call failed <'127.0.0.1', 50005>]


```

**Command or request that led to error**:
```

```

**Content of configuration file (config.yml)** (if relevant):
```yml

```

**Content of domain file (domain.yml)** (if relevant):
```yml

```

**Comment by akelad** [comment]
Please post the full error trace and fill out the rest of the fields in the issue template

**Comment by ravikrcs** [comment]
i got it.solved
