### ISSUE TITLE
Unable to scroll where large story is displayed

### ISSUE THREAD

**Issue by andrewrobertday** [RasaHQ/rasa#3752]
**Rasa version**:1.0.1

**Rasa X version** (if used & relevant):

**Python version**3.6.7

**Operating system** (windows, osx, ...):ubuntu 

**Issue**:
When using Rasa-x and the story exceeds the height of the display, there is no ability to scroll down to see the later part of the story. 

**Error (including full traceback)**:
```

```

**Command or request that led to error**:
```

```

**Content of configuration file (config.yml)** (if relevant):
```yml

```

**Content of domain file (domain.yml)** (if relevant):
```yml

```

**Comment by akelad** [comment]
Thanks for raising this issue -- @gausie are we aware of this bug?

**Comment by erohmensing** [comment]
This also applies to interactive learning, if the story is too long you cannot scroll and lose the "Save" button
