### ISSUE TITLE
Rasa-X UI - Interactive Training 

### ISSUE THREAD

**Issue by andrewrobertday** [RasaHQ/rasa#3753]
**Rasa version**:1.0.1

**Rasa X version** (if used & relevant):1

**Python version**:3.6.7

**Operating system** (windows, osx, ...):Ubuntu

**Issue**:
When using interactive trainng, after selecting a next action and clicking to continue, the display jumps back to the top of the conversation and the user has to scroll back to the bottom of the conversation to continue. 

**Error (including full traceback)**:
```

```

**Command or request that led to error**:
```

```

**Content of configuration file (config.yml)** (if relevant):
```yml

```

**Content of domain file (domain.yml)** (if relevant):
```yml

```

**Comment by akelad** [comment]
we're working on getting this fixed in an upcoming release, thanks for letting us know though!

**Comment by akelad** [comment]
will leave it open for now until the release is out

**Comment by akelad** [comment]
@tmbo that's not fixed, it's a separate issue

**Comment by tmbo** [comment]
> will leave it open for now until the release is out
this sounded like it is fixed?

**Comment by akelad** [comment]
yeah but this fix didn't end up going in the release, it'll be in the next one

**Comment by tmbo** [comment]
the issue should be closed when it is merged, not when it is released

**Comment by akelad** [comment]
it's not merged in any case, bad communication on my part with my earlier comment. However, I think Rasa X issues should stay open until there's a release out with the fix, since the fix isn't accessible to the community until there's a tagged release
