### ISSUE TITLE
Response to Rasa BOT via Custom Actions comes in every 3 iteration of conversation

### ISSUE THREAD

**Issue by LKiera** [RasaHQ/rasa#3756]
**Rasa version**:
rasa-core 0.14.3
rasa-core-sdk 1.0.0rc2
rasa-nlu 0.15.

**Rasa X version** (if used & relevant):

**Python version**:
python 3.6.7
**Operating system** (windows, osx, ...):
Ubuntu 18.04
**Issue**:
Custom Actions reply after every three iteration of conversation of chatbot

**Error (including full traceback)**:
```

```

**Command or request that led to error**:
```

```

**Content of configuration file (config.yml)** (if relevant):
```yml

```

**Content of domain file (domain.yml)** (if relevant):
```yml

```

**Comment by akelad** [comment]
Please ask these kind of questions in our [forum](https://forum.rasa.com)
