### ISSUE TITLE
Error While training model

### ISSUE THREAD

**Issue by PYGR** [RasaHQ/rasa#3758]
Hello All,

I am newbie to Rasa. Exploring some existing stuff and got stuck with below error. 

Please help to resolve.   

ValueError: Action 'utter_did_that_help' doesn't correspond to a template / action

**Comment by akelad** [comment]
If you think this is a bug, please submit a new issue from the "Bug report" template and fill out the fields. Though this sounds more like a usage question, my guess is that you don't have `utter_did_that_help` listed in your domain file. If that doesn't fix it, please post a question on our [forum](https://forum.rasa.com)
