### ISSUE TITLE
Rasa Init Error after Rasa installed correctly

### ISSUE THREAD

**Issue by ArupMukherjee** [RasaHQ/rasa#3760]

**Comment by ArupMukherjee** [comment]
(nlp_env1) C:\>rasa init --no-prompt
Welcome to Rasa! 🤖

To get started quickly, an initial project will be created.
If you need some help, check out the documentation at https://rasa.com/docs/rasa.

Created project directory at 'C:\'.
Finished creating project structure.
Training an initial model...
Training Core model...
Traceback (most recent call last):
  File "c:\python_anaconda\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\python_anaconda\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Python_Anaconda\Scripts\rasa.exe\__main__.py", line 9, in <module>
  File "c:\python_anaconda\lib\site-packages\rasa\__main__.py", line 70, in main
    cmdline_arguments.func(cmdline_arguments)
  File "c:\python_anaconda\lib\site-packages\rasa\cli\scaffold.py", line 194, in run
    init_project(args, path)
  File "c:\python_anaconda\lib\site-packages\rasa\cli\scaffold.py", line 112, in init_project
    print_train_or_instructions(args, path)
  File "c:\python_anaconda\lib\site-packages\rasa\cli\scaffold.py", line 50, in print_train_or_instructions
    args.model = rasa.train(domain, config, training_files, output)
  File "c:\python_anaconda\lib\site-packages\rasa\train.py", line 48, in train
    kwargs=kwargs,
  File "c:\python_anaconda\lib\asyncio\base_events.py", line 584, in run_until_complete
    return future.result()
  File "c:\python_anaconda\lib\site-packages\rasa\train.py", line 144, in train_async
    kwargs=kwargs,
  File "c:\python_anaconda\lib\site-packages\rasa\train.py", line 183, in _do_training
    kwargs=kwargs,
  File "c:\python_anaconda\lib\site-packages\rasa\train.py", line 313, in _train_core_with_validated_data
    kwargs=kwargs,
  File "c:\python_anaconda\lib\site-packages\rasa\core\train.py", line 25, in train
    from rasa.core.agent import Agent
  File "c:\python_anaconda\lib\site-packages\rasa\core\agent.py", line 27, in <module>
    from rasa.core.policies import FormPolicy, Policy
  File "c:\python_anaconda\lib\site-packages\rasa\core\policies\__init__.py", line 11, in <module>
    from rasa.core.policies.sklearn_policy import SklearnPolicy
  File "c:\python_anaconda\lib\site-packages\rasa\core\policies\sklearn_policy.py", line 8, in <module>
    from sklearn.base import clone
  File "c:\python_anaconda\lib\site-packages\sklearn\__init__.py", line 64, in <module>
    from .base import clone
  File "c:\python_anaconda\lib\site-packages\sklearn\base.py", line 13, in <module>
    from .utils.fixes import signature
  File "c:\python_anaconda\lib\site-packages\sklearn\utils\__init__.py", line 16, in <module>
    from .fixes import _Sequence as Sequence
  File "c:\python_anaconda\lib\site-packages\sklearn\utils\fixes.py", line 85, in <module>
    from scipy.special import boxcox  # noqa
  File "c:\python_anaconda\lib\site-packages\scipy\special\__init__.py", line 641, in <module>
    from ._ufuncs import *
ImportError: DLL load failed: The specified module could not be found.

(nlp_env1) C:\>pip list
Package                            Version
---------------------------------- --------
absl-py                            0.7.1
aiofiles                           0.4.0
aiohttp                            3.5.4
alabaster                          0.7.12
anaconda-client                    1.7.2
anaconda-navigator                 1.9.7
anaconda-project                   0.8.2
aniso8601                          6.0.0
APScheduler                        3.6.0
asn1crypto                         0.24.0
astor                              0.8.0
astroid                            2.2.5
astropy                            3.1.2
async-generator                    1.10
async-timeout                      3.0.1
atomicwrites                       1.3.0
attrs                              19.1.0
Babel                              2.6.0
backcall                           0.1.0
backports.os                       0.1.1
backports.shutil-get-terminal-size 1.0.0
beautifulsoup4                     4.7.1
bitarray                           0.8.3
bkcharts                           0.2
bleach                             3.1.0
blis                               0.2.4
bokeh                              1.0.4
boto                               2.49.0
boto3                              1.9.146
botocore                           1.12.165
Bottleneck                         1.2.1
certifi                            2019.3.9
cffi                               1.12.2
chardet                            3.0.4
Click                              7.0
cloudpickle                        0.8.0
clyent                             1.2.2
colorama                           0.4.1
colorclass                         2.2.0
coloredlogs                        10.0
colorhash                          1.0.2
comtypes                           1.1.7
conda                              4.6.11
conda-build                        3.17.8
conda-verify                       3.1.1
ConfigArgParse                     0.14.0
contextlib2                        0.5.5
cryptography                       2.6.1
cycler                             0.10.0
cymem                              2.0.2
Cython                             0.29.6
cytoolz                            0.9.0.1
dask                               1.1.4
decorator                          4.4.0
defusedxml                         0.5.0
distributed                        1.26.0
docopt                             0.6.2
docutils                           0.14
entrypoints                        0.3
et-xmlfile                         1.0.1
fakeredis                          1.0.3
fastcache                          1.0.2
fbmessenger                        6.0.0
filelock                           3.0.10
Flask                              1.0.2
Flask-Cors                         3.0.8
Flask-RESTful                      0.3.7
future                             0.17.1
gast                               0.2.2
gevent                             1.4.0
glob2                              0.6
greenlet                           0.4.15
grpcio                             1.21.1
h5py                               2.9.0
heapdict                           1.0.0
html5lib                           1.0.1
httptools                          0.0.13
humanfriendly                      4.18
idna                               2.8
imageio                            2.5.0
imagesize                          1.1.0
importlib-metadata                 0.0.0
ipykernel                          5.1.0
ipython                            7.4.0
ipython-genutils                   0.2.0
ipywidgets                         7.4.2
isort                              4.3.16
itsdangerous                       1.1.0
jdcal                              1.4
jedi                               0.13.3
Jinja2                             2.10
jmespath                           0.9.4
jsonpickle                         1.1
jsonschema                         2.6.0
jupyter                            1.0.0
jupyter-client                     5.2.4
jupyter-console                    6.0.0
jupyter-core                       4.4.0
jupyterlab                         0.35.4
jupyterlab-server                  0.2.0
kafka-python                       1.4.6
Keras-Applications                 1.0.8
Keras-Preprocessing                1.1.0
keyring                            18.0.0
kiwisolver                         1.0.1
lazy-object-proxy                  1.3.1
libarchive-c                       2.8
llvmlite                           0.28.0
locket                             0.2.0
lxml                               4.3.2
Markdown                           3.1.1
MarkupSafe                         1.1.1
matplotlib                         3.0.3
mattermostwrapper                  2.1
mccabe                             0.6.1
menuinst                           1.4.16
mistune                            0.8.4
mkl-fft                            1.0.10
mkl-random                         1.0.2
mock                               3.0.5
more-itertools                     6.0.0
mpmath                             1.1.0
msgpack                            0.6.1
multidict                          4.5.2
multipledispatch                   0.6.0
murmurhash                         1.0.2
navigator-updater                  0.2.1
nbconvert                          5.4.1
nbformat                           4.4.0
networkx                           2.3
nltk                               3.4
nose                               1.3.7
notebook                           5.7.8
numba                              0.43.1
numexpr                            2.6.9
numpy                              1.16.3
numpydoc                           0.8.0
olefile                            0.46
openpyxl                           2.6.1
packaging                          19.0
pandas                             0.24.2
pandocfilters                      1.4.2
parso                              0.3.4
partd                              0.3.10
path.py                            11.5.0
pathlib2                           2.3.3
patsy                              0.5.1
pep8                               1.7.1
pickleshare                        0.7.5
pika                               1.0.1
Pillow                             5.4.1
pip                                19.0.3
pip-autoremove                     0.9.1
pkginfo                            1.5.0.1
plac                               0.9.6
pluggy                             0.9.0
ply                                3.11
preshed                            2.0.1
prometheus-client                  0.6.0
prompt-toolkit                     2.0.9
protobuf                           3.8.0
psutil                             5.6.1
psycopg2-binary                    2.8.2
py                                 1.8.0
pycodestyle                        2.5.0
pycosat                            0.6.3
pycparser                          2.19
pycrypto                           2.6.1
pycurl                             7.43.0.2
pydot                              1.4.1
pyflakes                           2.1.1
Pygments                           2.3.1
PyJWT                              1.7.1
pykwalify                          1.7.0
pylint                             2.3.1
pymongo                            3.8.0
pyodbc                             4.0.26
pyOpenSSL                          19.0.0
pyparsing                          2.3.1
pyreadline                         2.1
pyrsistent                         0.14.11
PySocks                            1.6.8
pytest                             4.3.1
pytest-arraydiff                   0.3
pytest-astropy                     0.5.0
pytest-doctestplus                 0.3.0
pytest-openfiles                   0.3.2
pytest-remotedata                  0.3.1
python-crfsuite                    0.9.6
python-dateutil                    2.8.0
python-engineio                    3.8.1
python-socketio                    4.0.1
python-telegram-bot                11.1.0
pytz                               2019.1
PyWavelets                         1.0.2
pywin32                            223
pywinpty                           0.5.5
PyYAML                             5.1
pyzmq                              18.0.0
QtAwesome                          0.5.7
qtconsole                          4.4.3
QtPy                               1.7.0
questionary                        1.1.1
rasa                               1.0.9
rasa-sdk                           1.0.0
redis                              3.2.1
requests                           2.22.0
requests-toolbelt                  0.9.1
rocketchat-API                     0.6.31
rope                               0.12.0
ruamel-yaml                        0.15.46
ruamel.yaml                        0.15.94
s3transfer                         0.2.1
sanic                              19.3.1
Sanic-Cors                         0.9.8
sanic-jwt                          1.3.1
Sanic-Plugins-Framework            0.7.0
scikit-image                       0.14.2
scikit-learn                       0.20.2
scipy                              1.2.1
seaborn                            0.9.0
Send2Trash                         1.5.0
setuptools                         40.8.0
simplegeneric                      0.8.1
simplejson                         3.16.0
singledispatch                     3.4.0.3
six                                1.12.0
sklearn-crfsuite                   0.3.6
slackclient                        1.3.1
snowballstemmer                    1.2.1
sortedcollections                  1.1.2
sortedcontainers                   2.1.0
soupsieve                          1.8
spacy                              2.1.4
Sphinx                             1.8.5
sphinxcontrib-websupport           1.1.0
spyder                             3.3.3
spyder-kernels                     0.4.2
SQLAlchemy                         1.3.4
srsly                              0.0.6
statsmodels                        0.9.0
sympy                              1.3
tables                             3.5.1
tabulate                           0.8.3
tblib                              1.3.2
tensorboard                        1.13.1
tensorflow                         1.13.1
tensorflow-estimator               1.13.0
termcolor                          1.1.0
terminado                          0.8.1
terminaltables                     3.1.0
testpath                           0.4.2
thinc                              7.0.4
toolz                              0.9.0
tornado                            6.0.2
tqdm                               4.31.0
traitlets                          4.3.2
twilio                             6.26.3
tzlocal                            1.5.1
unicodecsv                         0.14.1
urllib3                            1.24.1
wasabi                             0.2.2
wcwidth                            0.1.7
webencodings                       0.5.1
webexteamssdk                      1.1.1
websocket-client                   0.54.0
websockets                         6.0
Werkzeug                           0.14.1
wheel                              0.33.1
widgetsnbextension                 3.4.2
win-inet-pton                      1.1.0
win-unicode-console                0.5
wincertstore                       0.2
wrapt                              1.11.1
xlrd                               1.2.0
XlsxWriter                         1.1.5
xlwings                            0.15.4
xlwt                               1.3.0
yarl                               1.3.0
zict                               0.1.4
zipp                               0.3.3

**Comment by akelad** [comment]
Please open a new issue from the "Bug report" template and fill out the fields
