### ISSUE TITLE
Fill slots in other parts of utterance templates than text

### ISSUE THREAD

**Issue by erohmensing** [RasaHQ/rasa#3763]
Right now, we only fill the {slot} format of utterance templates in the `- text` attribute of utterance templates. We could extend this to also fill keywords in other templates, e.g. "image" and "buttons", so that someone can use kwargs to fill them dynamically from their actions code.

Example use case: 
https://forum.rasa.com/t/how-to-send-image-url-to-templates-dynamically/11074

**Comment by RanaMostafaAbdElMohsen** [comment]
Hey @erohmensing ,
I began investigating the issue. 
What I concluded so far from slots.py there are slot formats for type names below :
```
- text
- float
- boolean
- List
- unfeaturized
- categorical
```

I believe what is required here to extend for `- images` and `- buttons` as well, correct?

**Comment by erohmensing** [comment]
Hi @RanaMostafaAbdElMohsen! This isn't about slot types, but rather about which utterance fields get filled. The logic happens here: https://github.com/RasaHQ/rasa/blob/ea76c3de8dd714c41e11f122f49f5dbde804b9de/rasa/core/nlg/template.py#L114

As you can see, only the `text` field of the template is getting updated with slot values. However, templates can also have `images`, `buttons`, `quick_replies`, `attachment`, and `custom` fields (custom will be a dict that has anything in it)

A template is a dictionary, where its keys are `text`, etc -- in order to merge this PR, we would make sure it did that replacing in every key, value pair of the template. Then for custom, we would have to go one step further and make sure that every key, value within the custom dict has replacement too (probably recursively)

Does that help? I promise I've made it sound much more complicated than it probably would be :)

**Comment by RanaMostafaAbdElMohsen** [comment]
> Does that help? I promise I've made it sound much more complicated than it probably would be :)

Yes it helped :) Thanks @erohmensing

**Comment by akelad** [comment]
@RanaMostafaAbdElMohsen any progress on this yet?

**Comment by RanaMostafaAbdElMohsen** [comment]
I was working on resolving an issue and was recently resolved. Currently, I am investigating this issue and hopefully there will be a progress in it soon.

**Comment by RanaMostafaAbdElMohsen** [comment]
Hi @erohmensing ,
I have made a PR initially for filling slot utterance templates for` image`. Can you please advise me if I am on right track to support other fields ?

**Comment by erohmensing** [comment]
closed in https://github.com/RasaHQ/rasa/pull/4077 and https://github.com/RasaHQ/rasa/pull/4079 -- thanks guys!
