### ISSUE TITLE
Support AWS Kinesis as event broker

### ISSUE THREAD

**Issue by alexissmirnov** [RasaHQ/rasa#3764]
**Description of Problem**: RabbitMQ, Kafra are good choices, but some architectures already rely on Kinesis.

**Overview of the Solution**: Implement the support for Kinesis, use Kafka as the template for the implementation

**Definition of Done**:

*   [ ] Tests are added
*   [ ] Feature is documented

**Comment by akelad** [comment]
Thanks for the suggestion @alexissmirnov! @ricwo you know more about this, could you comment on whether this makes sense?

**Comment by ricwo** [comment]
Hi @alexissmirnov, thanks for your suggestion. Yes, I think Kinesis as an additional event broker would be a worthwhile addition. Would you be interested in making a contribution?
