### ISSUE TITLE
PUT /model with model_server fails: 'dict' object has no attribute 'url'

### ISSUE THREAD

**Issue by mmalhotra** [RasaHQ/rasa#3770]
**Rasa version**: Rasa 1.1.0a1

**Python version**: Python 3.6.8

**Operating system** (windows, osx, ...): Docker image rasa/rasa:latest-full
Linux 6f5ab25d1c4d 4.15.0-47-generic #50-Ubuntu SMP Wed Mar 13 10:44:52 UTC 2019 x86_64 GNU/Linux

**Issue**: using model_server endpoint for https://rasa.com/docs/rasa/api/http-api/#tag/Model/paths/~1model/put leads to error 
AttributeError: 'dict' object has no attribute 'url'

**Error (including full traceback)**:
```
  File "/usr/local/lib/python3.6/site-packages/rasa/server.py", line 258, in _load_agent
    action_endpoint=action_endpoint,
  File "/usr/local/lib/python3.6/asyncio/coroutines.py", line 110, in __next__
    return self.gen.send(None)
  File "/usr/local/lib/python3.6/site-packages/rasa/core/agent.py", line 246, in load_agent
    model_server,
  File "/usr/local/lib/python3.6/asyncio/coroutines.py", line 110, in __next__
    return self.gen.send(None)
  File "/usr/local/lib/python3.6/site-packages/rasa/core/agent.py", line 53, in load_from_server
    await _update_model_from_server(model_server, agent)
  File "/usr/local/lib/python3.6/asyncio/coroutines.py", line 110, in __next__
    return self.gen.send(None)
  File "/usr/local/lib/python3.6/site-packages/rasa/core/agent.py", line 107, in _update_model_from_server
    if not is_url(model_server.url):
AttributeError: 'dict' object has no attribute 'url'
```

**Command or request that led to error**:
```
curl -X PUT -H 'Content-Type: application/json' -i http://localhost:5005/model --data '{"model_file": null, "model_server": {"url": "http://localhost:5000/model/8b200dad622c4ed9b9636e8ec7b12660", "params": {}, "headers": {}, "basic_auth": {}, "token": "", "token_name": "", "wait_time_between_pulls": 0}}'
```

Issue seems to be because of following files:

https://github.com/RasaHQ/rasa/blob/e4d3335a7834b56ab52c68bb30ae58b94e9b6ddd/rasa/server.py#L818

model_server is just a get on json, never converted to an object.

https://github.com/RasaHQ/rasa/blob/e4d3335a7834b56ab52c68bb30ae58b94e9b6ddd/rasa/core/agent.py#L107

Accessing the json object (dict) as if its an EndpointConfig

This pull request fixes it: https://github.com/RasaHQ/rasa/pull/3769

**Comment by akelad** [comment]
Thanks for raising this and providing a great level of detail! As mentioned in the PR, we'll review it asap :)

**Comment by illi88** [comment]
Hello, @mmalhotra I have the same issue, if you solved it, can you guide me please !!

**Comment by mmalhotra** [comment]
@illi88 this is fixed in the latest docker image: 
I can confirm it in the following sha:
"Id": "sha256:a4e11142877cd6f14361f1ba27c4e2dffa7746526f17435f1f54a04e575a62a3"
