### ISSUE TITLE
When use interactive learning

### ISSUE THREAD

**Issue by harunkelesoglu** [RasaHQ/rasa#3774]
**Rasa version**:
Rasa 1.0.8
**Rasa X version** (if used & relevant):
Rasa 1.0.8
**Python version**:
Python 3.6.8
**Operating system** (windows, osx, ...):
Distributor ID:	Ubuntu
Description:	Ubuntu 16.04.6 LTS
Release:	16.04
Codename:	xenial
**Issue**:
I trained the model in local and upload to server. I am using docker-compose on server. When i use interactive learning I noticed this error. 
![Screen Shot 2019-06-13 at 11 52 19](https://user-images.githubusercontent.com/9349762/59419122-e9ff9300-8dd2-11e9-9f73-29593affd83c.png)

**Comment by akelad** [comment]
Thanks for raising this. We're aware of these issues and are working on getting them fixed. I'll leave this open in case anyone else comes across it

**Comment by tmbo** [comment]
I think this is referring to the duplicated messages. This is fixed as part of #sql
