### ISSUE TITLE
Removing trailing slash results in weird behavior

### ISSUE THREAD

**Issue by wenig** [RasaHQ/rasa#3776]
**Description of Problem**:
That change https://github.com/RasaHQ/rasa/commit/7fbc08b504b51976f8e5299113ad283c9e1a87ed#diff-c66e6bc1dfd15c342f53b163376f7270R48 results in weird behavior. If I define an url in endpoints.yml (for example the nlg endpoint) which is required to end with a slash, the slash is removed and a request without a slash is sent. This shouldn't be a problem as my nlg server redirects this request to the path with a slash. However, the library _aiohttp_ which is used to request has the following behavior https://github.com/aio-libs/aiohttp/issues/3082. It will change the method from POST to GET after a redirect. This results in a "405 Method not allowed".

**Overview of the Solution**:
Of course, I can adapt my nlg server to not redirect and directly take the path without slash but it is still not right in my opinion to change the urls which are defined in some config files. I'd rather have the obvious behavior and requests to the urls I defined.

**Definition of Done**:
- [x] `return base.rstrip("/")` --> `return base`

**Comment by akelad** [comment]
this sounds more like a bug report than an enhancement right?

@wochinge since you merged that PR, can you take a look at it?

**Comment by wochinge** [comment]
@wenig Thanks for this detailed bug report! I'm reverting the stripping here and replacing it with a debug message: https://github.com/RasaHQ/rasa/pull/3824
