### ISSUE TITLE
How can i run actions on docker-compose?

### ISSUE THREAD

**Issue by harunkelesoglu** [RasaHQ/rasa#3777]
Hi,
I deployed rasa with docker-compose by http://rasa.com/docs/rasa-x/deploy/.
But I did not see a mounted actions file.

**Comment by akelad** [comment]
The docker-compose file contains an `app` service, which is where you reference an image that runs your actions.
Please ask usage questions in the [forum](https://forum.rasa.com), as mentioned in the issue template

**Comment by harunkelesoglu** [comment]
i asked in the forum. https://forum.rasa.com/t/how-can-i-run-actions-on-docker-compose/11477
