### ISSUE TITLE
metadata.json changed to contain absolute path to training_data.json

### ISSUE THREAD

**Issue by gthb** [RasaHQ/rasa#3778]
**Rasa version**: 1.0.9

**Python version**: 3.7.3

**Operating system** (windows, osx, ...): osx

**Issue**:

After training, `metadata.json` has an absolute path to `training_data.json` in the `training_data` attribute, e.g. `/Users/gthb/git/rasaproject/.../training_data.json`.

This path used to be relative to the model directory, matching what's described in https://github.com/RasaHQ/rasa/blob/master/docs/nlu/old-nlu-migration-guide.rst “All paths are now relative with respect to the path specified in the configuration during training and loading”.

The regression happened in https://github.com/RasaHQ/rasa/commit/194d449bbaca8f7bbbca2e561309b064e6d6d3dd because `data_file` is always an absolute path, coming out of `data_file = os.path.join(dir_name, filename)`, and that `dir_name` comes from https://github.com/RasaHQ/rasa/blob/6c9a3202c04b18440e47cb952b588637e5d0edf1/rasa/nlu/model.py#L222

```python
        path = os.path.abspath(path)
        dir_name = os.path.join(path, model_name)
```

**Error (including full traceback)**:

N/A

**Command or request that led to error**:

```bash
$ rasa init --no-prompt
$ tar -xOzf models/*.tar.gz nlu/metadata.json | grep training_data
```

Before commit 194d449bba that yields:

```
    "training_data": "training_data.json",
```

whereas at and after that commit, it yields something like:

```
    "training_data": "/var/folders/_g/f_zc9wdj6vqcbsk1h62bwxmd9xsbxj/T/tmptz08li2n/nlu/training_data.json",
```

In a real usage scenario (not `rasa init`), that path will be a real absolute path into somebody's project directory, with username etc.

**Comment by tmbo** [comment]
Do you mind creating a PR changing the path before we add it to the metadata?

**Comment by gthb** [comment]
> Do you mind creating a PR changing the path before we add it to the metadata?

Done ⬆️  (and just got the go-ahead for the CLA, so we're good.)
