### ISSUE TITLE
check at which endpoint a model is required

### ISSUE THREAD

**Issue by wochinge** [RasaHQ/rasa#3787]
When an endpoint uses `ensure_loaded_agent`, the decorator checks in `agent.is_ready` if the model is loaded`. We don't need that for some endpoints, e.g.

- retrieve tracker (only tracker story is needed)
- ...

**Comment by tmbo** [comment]
I think retrieve tracker needs it because the tracker store needs a domain to properly instantiate a tracker with slots.

**Comment by wochinge** [comment]
OK, that applies also to all the other ones 👍
