### ISSUE TITLE
deprecate `handle_channels` on agent class

### ISSUE THREAD

**Issue by wochinge** [RasaHQ/rasa#3790]
This function (https://github.com/RasaHQ/rasa/blob/ad66510dbebf7888602a87f2be2428b7090ae878/rasa/core/agent.py#L668)  is currently only used in tests.
We should either 
- remove it and rewrite the tests
- move it to `tests`

**Comment by tmbo** [comment]
It needs to be deprecated first though as the Agent class should be considered a public API.

In addition to deprecation, we should add instructions on how to migrate away from using the function.

**Comment by adhikariastha5** [comment]
@wochinge i did not understand what do you mean by remove and tests. And also I could not find any link how train_init, dialogue management and train_online has been migrated in the new rasa version? So many issues and not a single solution. Please help me.

**Comment by wochinge** [comment]
@adhikariastha5 Can you please ask this question in our forum (https://forum.rasa.com) including what you want to achieve, what's not working for you currently?

**Comment by akelad** [comment]
@adhikariastha5 please don't put duplicates of your question on different issues which aren't relevant to your question
