### ISSUE TITLE
Migration Guide config.yml information

### ISSUE THREAD

**Issue by rgstephens** [RasaHQ/rasa#3793]
The migration guide should tell us that the config.yml for NLU and Core has been merged. See [post](https://forum.rasa.com/t/migrating-to-1-0/11489)

**Rasa version**: 1.0

**Comment by akelad** [comment]
Thanks for the feedback, would you mind submitting a PR for this?

**Comment by adhikariastha5** [comment]
@akelad I could not find any link how to train_init, dialogue management and train_online has been migrated in the new rasa version? So many issues and not a single solution. Please help me.

**Comment by akelad** [comment]
@adhikariastha5 could you clarify what you mean? are you talking about calling functions from python code? https://rasa.com/docs/rasa/migration-guide/

**Comment by rgstephens** [comment]
I assume you're referring to my proposed addition concerning the HTTP API?  I've come across several API endpoints so far that have changed.  I think there should be a complete list of the endpoints that have changed but here are the ones that I have come across:

| API    | Old         | New            |
| ------ | ----------- | -------------- |
| POST   | `/parse`    | `/model/parse` |
| POST   | `/train`    | `/model/train` |

**Comment by akelad** [comment]
i was asking the other person that commented :) but would you be willing to submit a PR with your suggested changes?

**Comment by rgstephens** [comment]
I would have done that but I don't think my list is complete.  I haven't gone thru every endpoint and tried to compare.  I just noted two of them that I use.

It would be best to have the person that made the API changes give us a complete list of the endpoints that changed.
