### ISSUE TITLE
Entity Not recognized 

### ISSUE THREAD

**Issue by Aswinprabhakaran** [RasaHQ/rasa#3797]
Attached my training data json files where all the intents and entities are labelled.
[training-data-json.txt](https://github.com/RasaHQ/rasa/files/3293051/training-data-json.txt)
 

My Question for that chatbot that i made is "What is the average ratings of movies produced by Karan JOhar in last 10 years ?" 

In this case "Karan Johar" should be recognizd as "producer" entity .

In many cases i have marked "Karan JOhar" as "director " entity. 

But when a phrase " produced by " or "director by " comes, in those case  the name after the phrase should belong to "producer"/"director" depending on the phrase preffixed. 

Below is the result that i got from my model.

{'intent': {'name': 'rating_search', 'confidence': 0.9789842971636689}, 'entities': [{'start': 12, 'end': 27, 'value': 'average ratings', 'entity': 'aggmethod', 'confidence': 0.9984705847092747, 'extractor': 'CRFEntityExtractor'}, {'start': 38, 'end': 49, 'value': 'produced by', 'entity': 'role', 'confidence': 0.970444154132258, 'extractor': 'CRFEntityExtractor'}, {'start': 50, 'end': 61, 'value': '**karan johar', 'entity': 'director'**, 'confidence': 0.9519798163153366, 'extractor': 'CRFEntityExtractor'}, {'start': 62, 'end': 78, 'value': 'in last 10 years', 'entity': 'time', 'confidence': 0.8693345972879974, 'extractor': 'CRFEntityExtractor'}], 'intent_ranking': [{'name': 'rating_search', 'confidence': 0.9789842971636689}, {'name': 'movie_search', 'confidence': 0.011960894645934217}, {'name': 'actor_search', 'confidence': 0.0029286358141673865}, {'name': 'producer_search', 'confidence': 0.0018446370991670315}, {'name': 'director_search', 'confidence': 0.001321095084823971}, {'name': 'coworker_search', 'confidence': 0.0009156458042880051}, {'name': 'affirm', 'confidence': 0.0007931370517594824}, {'name': 'actress_search', 'confidence': 0.000524613144352204}, {'name': 'goodbye', 'confidence': 0.0004869859850510281}, {'name': 'greet', 'confidence': 0.0002400582067874318}], 'text': 'What is the average ratings of movies produced by Karan JOhar in last 10 years ?'}

If you c , Karan Johar is marked as director entity inspite of the phrase "produced by" preffixing  it. So my question is what does the model learn then ? 

And if you see the result, there are other intents rankings . Similarly how to check the other  for entities rankings ? Bcz i believe that entities are picked upon based on the entity confidence.

Does my model doesnt recognize Karan Johar as a producer because there is not enough training sample cases as him pointing to a producer?

**Comment by akelad** [comment]
Please ask these kind of questions in our [forum](https://forum.rasa.com), as mentioned in the issue template
