### ISSUE TITLE
How to add custom payload in request to webhook

### ISSUE THREAD

**Issue by GauravGaikwad94** [RasaHQ/rasa#3800]
Hi,

I want to add custom payload in webhook request, so that I can pass some information to the bot and that information will be used in the actions.
I want to add something like this to [http://localhost:5005/webhooks/rest/webhook](http://localhost:5005/webhooks/rest/webhook)
`{
  "sender": "1234",
  "message": "Hi there!",
  "payload":{
  	"key":"value"
  }
}`
I want to use this key value pair in the custom actions.
How to achieve this or do we have any other way to pass data to actions?

**Comment by lahsuk** [comment]
Hi, @GauravGaikwad94 
One of the ways you could do this is by creating a custom slot. The slot could be set by pressing a button or just sending another request altogether. 
The message to set the slot will be in the format `/{"slot_type": "value"}`.
The slot value would then be passed to the action server too. Oh, and you probably should set the `slot_type` to `unfeturized` if you don't want it to influence stories.
Right now, I do not know any other way to pass the custom value to the action server.
Hope this helps.

**Comment by akelad** [comment]
Please ask these kind of questions in our [forum](https://forum.rasa.com)

**Comment by GauravGaikwad94** [comment]
Thanks @lahsuk for the alternative solution.
 @akelad I'll keep in mind :)
