### ISSUE TITLE
Allow passing the model tar.gz file directly to Agent.load and RasaNLUInterpreter's constructor

### ISSUE THREAD

**Issue by msamogh** [RasaHQ/rasa#3807]
Currently, the model has to be extracted in a separate step before and the extracted path has to be fed to these methods.

If the frequency of usage doesn't warrant it, perhaps at least an error message might be helpful.

**Comment by sumyatthitsar** [comment]
Did you mean the model created your own from spacy?

**Comment by msamogh** [comment]
@sumyatthitsar Any model in general

**Comment by akelad** [comment]
we're talking about the model generated from `rasa train`

**Comment by Mazyod** [comment]
What about RasaNLUInterpreter's constructor?
