### ISSUE TITLE
Exception: Passing policy configuration parameters to agent.train(...) is not supported anymore. Specify parameters directly in the policy configuration instead. More info http://legacy-docs.rasa.com/core/migrations.html

### ISSUE THREAD

**Issue by abhiyushshrestha** [RasaHQ/rasa#3809]
Rasa version = 1.1.3
Python version = 3.6.5
ubuntu version = 16.04

Issue: I have tried to configure the rasa policy to resolve this but no effect so far I keep on getting this error, please help.

Exception: Passing policy configuration parameters to agent.train(...) is not supported anymore. Specify parameters directly in the policy configuration instead. More info http://legacy-docs.rasa.com/core/migrations.html

Here's the code:

from rasa_core.policies import FallbackPolicy, KerasPolicy, MemoizationPolicy
from rasa_core.agent import Agent
from rasa_core import config as policy_config

fallback = FallbackPolicy(fallback_action_name="utter_unclear",
core_threshold=0.2,
nlu_threshold=0.1)

policies = policy_config.load("policies.yml")
agent = Agent("domain.yml", policies=policies)

training_data_file = './data/stories.md'
agent.train(
training_data_file,
augmentation_factor=50,
max_history=2,
epochs=500,
batch_size=10,
validation_split=0.2)

agent.persist('./models/dialogue')

Inside policies.yml file I have included:

policies.yml

policies:

name: KerasPolicy
epochs: 100
max_history: 5
name: FallbackPolicy
fallback_action_name: 'action_default_fallback'
name: MemoizationPolicy
max_history: 5
name: FormPolicy
name: MappingPolicy

**Comment by erohmensing** [comment]
I have already answered your question in your comment here https://github.com/RasaHQ/rasa/issues/3201#issuecomment-503057474. You are using very old code that does not correspond to your rasa version. I recommend you check out our [docs](rasa.com/docs) and ask the [forum](forum.rasa.com) for advice on any other "how do I?" questions.
