### ISSUE TITLE
Why does Rasa X make two different types of API calls to the RASA core servers? 

### ISSUE THREAD

**Issue by psds01** [RasaHQ/rasa#3810]
I am wondering why is Rasa X (UI) making two different kinds of calls to rasa core servers? I can see that all it whatever `BotUtterance`s it needs, it can get those as response to the POST itself. Then why GET? What does UI "get" from CORE/GET that it can't "get" from CORE/POST?  

I would love a broader perspective on "architectural design" behind this or any such systems.

**Comment by akelad** [comment]
Please ask these kind of questions in our [forum](https://forum.rasa.com)
