### ISSUE TITLE
Config file error

### ISSUE THREAD

**Issue by OwaisRaza1** [RasaHQ/rasa#3825]
**Rasa version**:1.0.9

**Rasa X version** (if used & relevant): not used

**Python version**: 3.6

**Operating system** (windows, osx, ...): Ubuntu 18.4

**Issue**: I am facing issue when I run rasa UI with nlu server, when I start rasa UI and it hits to the nlu server at port 5000 it throws following exception:

[5860] [ERROR] Exception occurred while handling uri: 'http://localhost:5000/config'
Traceback (most recent call last):
File "/usr/local/lib/python3.6/dist-packages/sanic/app.py", line 893, in handle_request
handler, args, kwargs, uri = self.router.get(request)
File "/usr/local/lib/python3.6/dist-packages/sanic/router.py", line 407, in get
return self._get(request.path, request.method, "")
File "/usr/local/lib/python3.6/dist-packages/sanic/router.py", line 469, in _get
raise NotFound("Requested URL {} not found".format(url))
sanic.exceptions.NotFound: Requested URL /config not found

Unable to find its solution can you please help ???

**Error (including full traceback)**:
(```raise NotFound("Requested URL {} not found".format(url))
sanic.exceptions.NotFound: Requested URL /config not found
```)

**Command or request that led to error**:
```npm start
```

**Comment by akelad** [comment]
Thanks for raising this issue, @tabergma  will get back to you about it soon.

**Comment by tabergma** [comment]
@OwaisRaza1 What do you mean by `run rasa UI with nlu server`? What command do you execute?

If you start the rasa server via `rasa run --enable-api`, the endpoints listed [here](https://rasa.com/docs/rasa/api/http-api/) are exposed. We don't have an endpoint `/config`. So not sure what exactly you mean.

**Comment by OwaisRaza1** [comment]
I am using '''https://github.com/paschmann/rasa-ui''' rasa UI  when I start it by npm start command it throws an above mentioned error exception to NLU server which I run by command ''' rasa run --enable-api -m nlu-20190618-170731.tar.gz -p 5000'''.  Can't understand why ??? cause in previous version of rasa core and nlu(0.14) it didn't give any error when I updated it on rasa 1.0 it starts to give an error.

**Comment by OwaisRaza1** [comment]
@tabergma any update???

**Comment by tabergma** [comment]
We don't have a `/config` endpoint anymore. You can find all available endpoints [here](https://rasa.com/docs/rasa/api/http-api/). You cannot retrieve the config file via the API. The endpoint was removed in version 0.15.0.

**Comment by akelad** [comment]
The Rasa UI is a contributor project, so we're not sure what version that runs on etc -- I assume it's still on an old version. You might be better off opening an issue on that repo? 
Rasa X is the tool we maintain, that'll work with Rasa 1.0

I'll close this issue now as it's not related to Rasa or Rasa X
