### ISSUE TITLE
Relax the "requests" library version requirement

### ISSUE THREAD

**Issue by nlhkh** [RasaHQ/rasa#3826]
**Description of Problem**:
I cannot install rasa into most projects due to "requests" version conflict.

**Overview of the Solution**:
Relax the version requirement in requirements.txt instead of strict requests==2.22.0.

**Definition of Done**:
rasa can be installed along with other libraries like "sagemaker"

**Comment by akelad** [comment]
Thanks for raising this issue, @tmbo  will get back to you about it soon.

**Comment by tmbo** [comment]
The requirements.txt is intended to pin exact versions. Do you run into the same issue if you install using `pip install rasa` or (after cloning) `pip install -e .`?

**Comment by nlhkh** [comment]
Hi @tmbo , sorry for the late reply.
I ran into the issue when installing rasa on SageMaker. The latest SageMaker, and some of its dependencies also pin the version of `requests` to be 2.21 and before.

**Comment by iainelder** [comment]
This appears to be preventing me from using rasa in Amazon Sagemaker.

Repro:

* Create a new notebook in the Sagemaker console
* Create a new terminal in the notebook
* In the terminal activate conda's Python 3 environment:

    ```
    echo ". /home/ec2-user/anaconda3/etc/profile.d/conda.sh" >> ~/.bashrc
    souce ~/.bashrc
    conda activate python3
    ```

* Attempt to install rasa. This fails with version conflicts:

    ```
    $ pip install --quiet rasa
    sagemaker 1.28.3 has requirement requests<2.21,>=2.20.0, but you'll have requests 2.22.0 which is incompatible.
    jupyter-console 5.2.0 has requirement prompt_toolkit<2.0.0,>=1.0.0, but you'll have prompt-toolkit 2.0.9 which is incompatible.
    ipython 6.4.0 has requirement prompt-toolkit<2.0.0,>=1.0.15, but you'll have prompt-toolkit 2.0.9 which is incompatible.
    docker-compose 1.24.0 has requirement requests!=2.11.0,!=2.12.2,!=2.18.0,<2.21,>=2.6.1, but you'll have requests 2.22.0 which is incompatible.
    fakeredis 1.0.3 has requirement six>=1.12, but you'll have six 1.11.0 which is incompatible.
    Cannot uninstall 'greenlet'. It is a distutils installed project and thus we cannot accurately determine which files belong to it which would lead to only a partial uninstall.
    You are using pip version 10.0.1, however version 19.1.1 is available.
    You should consider upgrading via the 'pip install --upgrade pip' command.
```

**Comment by ezequielpaura** [comment]
Hello @akelad @tmbo, do you have any updates on this issue? 
Sorry for the insistence!  We want to use Rasa in Amazon Sagemaker, but because of this incompatibility, we are forced to use Docker + Fargate as workaround. Is there something else we need to do to install Rasa in Sagemaker?
Thanks in advance!

**Comment by tmbo** [comment]
I don't think there should be an issue with requests 2.20 or 2.21.

do you mind creating a PR changing setup py to contain something like `requests >= 2.20`?

**Comment by iainelder** [comment]
Hi @tmbo , thanks for the response.

Before we prepare a PR, how can we test the change?

I'm imagining the following process:

* Activate conda's Python 3 environment in a new Sagemaker notebook
* Clone the master branch of this repo
* Change requirements.txt as you suggested
* Install rasa using `pip install -e`

Please let us know if there's something else we should do.

**Comment by tmbo** [comment]
Sounds about right, although if you run `pip install -e .` you need to change `setup.py` instead of the requirements file (that one should actually stay the same, you only need to change `setup.py`)

**Comment by ezequielpaura** [comment]
Hi @tmbo 

We did try to modify `setup.py` but other issues arose. There is still a conflict with `requests`. Is there something else that we have to do?
The error with `requests` is: 

```rasa-sdk 1.3.0a1 has requirement requests~=2.22, but you'll have requests 2.20.0 which is incompatible.```

The whole test: 

```
(python3) [ec2-user@ip-172-16-54-79 ~]$ git clone https://github.com/RasaHQ/rasa.git

(python3) [ec2-user@ip-172-16-54-79 rasa]$ git diff
diff --git a/setup.py b/setup.py
index b96b77dda7..40c9387aef 100644
--- a/setup.py
+++ b/setup.py
@@ -26,7 +26,7 @@ tests_requires = [
 ]

 install_requires = [
-    "requests~=2.22",
+    "requests>=2.20",
     "boto3~=1.9",
     "matplotlib~=3.0",
     "simplejson~=3.16",
(python3) [ec2-user@ip-172-16-54-79 rasa]$ pip install -e .

jupyter-console 5.2.0 has requirement prompt_toolkit<2.0.0,>=1.0.0, but you'll have prompt-toolkit 2.0.9 which is incompatible.
ipython 6.4.0 has requirement prompt-toolkit<2.0.0,>=1.0.15, but you'll have prompt-toolkit 2.0.9 which is incompatible.
tensorflow-metadata 0.14.0 has requirement protobuf<4,>=3.7, but you'll have protobuf 3.6.1 which is incompatible.
rasa-sdk 1.3.0a1 has requirement requests~=2.22, but you'll have requests 2.20.0 which is incompatible.

Cannot uninstall 'wrapt'. It is a distutils installed project and thus we cannot accurately determine which files belong to it which would lead to only a partial uninstall.```

**Comment by tmbo** [comment]
Ah right, needs to be changed in rasahq/rasa-sdk as well. Just did that as well as here in rasa. 

Will be part of the next patch release.
