### ISSUE TITLE
Add case_sensitive option to WhitespaceTokenizer

### ISSUE THREAD

**Issue by ccelotto** [RasaHQ/rasa#3827]
**Description of Problem**:
WhitespaceTokenizer does not have the `case_sensitive` option. This is in reference to a discussion on the Rasa Community Forum https://forum.rasa.com/t/case-sensitivity/2541/8 with @Ghostvv 

**Overview of the Solution**:
Add the `case_sensitive` option to WhitespaceTokenizer to allow models using this tokenizer to be case insensitive.

**Examples** (if relevant):
If a user types "Burger" when the WhitespaceTokenizer `case_sensitive: false`, the slot should fill regardless even if training only contains "burger".

**Blockers** (if relevant):
Not sure.

**Definition of Done**:
- Add the `case_sensitive` option to the WhitespaceTokenizer
- Test a model and ensure that when this option is specified in the pipeline configuration, then a slot is filled regardless of case (so it should be case insensitive).

**Comment by akelad** [comment]
Thanks for raising this issue, @Ghostvv  will get back to you about it soon.

**Comment by Ghostvv** [comment]
Thanks for creating the issue. Would you like to make a PR for it?

**Comment by ccelotto** [comment]
I'll give it a go, but I'm more of a conversational designer, so I may not know how to fix this 😩 I'll update you on this post within the next day or two if I figure it out, and if not, maybe someone else can pick it up!

**Comment by ccelotto** [comment]
Hi @Ghostvv - unfortunately no luck fixing this. Hopefully someone else can pick it up! Thank you for your help in raising this issue.

**Comment by sibbsnb** [comment]
@Ghostvv should the train part also change in the WhiteSpaceTokenizer or just the process part? Is this tokenizer used during training?

**Comment by Ghostvv** [comment]
@sibbsnb both parts

**Comment by sibbsnb** [comment]
Thanks @Ghostvv. I don’t see where I can put the tests for training for this tokenizer. Any pointers?

**Comment by Ghostvv** [comment]
what do you mean?

**Comment by sibbsnb** [comment]
I see a test file for the process part of whitespace tokenizer but not for how training method is invoked

**Comment by sibbsnb** [comment]
Never mind, figured it out. Raised the PR: https://github.com/RasaHQ/rasa/pull/4020

**Comment by sibbsnb** [comment]
Closed the PR comments

**Comment by ccelotto** [comment]
Thank you everyone! I have tested this functionality and it is working as intended.
