### ISSUE TITLE
Could I only use MappingPolicy in my config ?

### ISSUE THREAD

**Issue by Highwall2016** [RasaHQ/rasa#3828]
in my config.yml just like:

# Configuration for Rasa NLU.
language: "zh"

pipeline:
- name: "MitieNLP"
  model: "total_word_feature_extractor.dat"
- name: "MitieTokenizer"
- name: "MitieEntityExtractor"
- name: "EntitySynonymMapper"
- name: "RegexFeaturizer"
- name: "MitieFeaturizer"
- name: "SklearnIntentClassifier"
- name: "MitieIntentClassifier"

# Configuration for Rasa Core.
policies:
  - name: MappingPolicy

**Comment by akelad** [comment]
Please ask these kind of questions in our [forum](https://forum.rasa.com)
