### ISSUE TITLE
Remove/deprecate AgentUttered event class

### ISSUE THREAD

**Issue by erohmensing** [RasaHQ/rasa#3832]
The [AgentUttered class](https://github.com/RasaHQ/rasa/blob/master/rasa/core/events/__init__.py#L889) is not used anymore anywhere but tests. @tmbo do we need to deprecate it rather than remove it, as the Events API is public? I'm not sure if we actually support it anymore, it's no longer in the docs 

To do: 
- [ ] also remove/deprecate same class in sdk

**Comment by tmbo** [comment]
Should be deprecated, once we remove it we also need to make sure we can still properly load trackers that have this event in their history.
