### ISSUE TITLE
RasaNLUHttpInterpreter makes call to wrong URL for parsing intent

### ISSUE THREAD

**Issue by fz-29** [RasaHQ/rasa#3836]
**Rasa version**: 1.1.3

**Rasa X version** (if used & relevant):

**Python version**: 3.6

**Operating system** (windows, osx, ...): OSX

**Issue**:

RASA allows a custom URL for NLU endpoint, by specifying the NLU endpoint in endpoints.yml. But currently, at the time of making HTTP call to the NLU endpoint, the URL constructed is not right.
If one aims to set up an NLU endpoint at ``` http://localhost:8080/a/b/c/model/parse/ ```, so they will have the following endpoint configuration for NLU endpoint.

```
nlu:
  url: 'http://localhost:8080/a/b/c/'
```
But the issue happens in the code while doing URL join for 
```urljoin(self.endpoint.url, "/model/parse")```

Sample Code Issue Snippet:
For Python 3.6 and 3.7 as well

```
>>> urljoin('http://localhost:8080/a/b/c/','/model/parse')
'http://localhost:8080/model/parse'
>>> # Clearly, we have lost a part from URL, which is a bug
...
>>>
>>>
>>> urljoin('http://localhost:8080/a/b/c/','model/parse')
'http://localhost:8080/a/b/c/model/parse'
>>> # Removing forward slash from the second argument, fixes the issue
```

Code Issue in Rasa: https://github.com/RasaHQ/rasa/blob/master/rasa/core/interpreter.py#L212

Proposal:

Change from:
```urljoin(self.endpoint.url, "/model/parse") ```
to
```urljoin(self.endpoint.url, "model/parse") ```

**Comment by psds01** [comment]
Maybe instead of specifying your endpoint as
```yml
nlu:
  url: "http://localhost:8080/a/b/c/"
```
You might want to specify it as
```yml
nlu:
  url: "http://localhost:8080/a/b/c"
```
Without the slash after `c`.
That's what rasa demo bots have : https://github.com/RasaHQ/rasa/blob/master/examples/restaurantbot/endpoints.yml#L2
https://github.com/RasaHQ/rasa/blob/master/examples/formbot/endpoints.yml#L2
https://github.com/RasaHQ/rasa/blob/master/examples/concertbot/endpoints.yml#L5

**Comment by fz-29** [comment]
@psds01 Thanks, but it does not work.

**Comment by akelad** [comment]
we'll look into this -- thanks for the PR!

**Comment by akelad** [comment]
update: contributor can't sign CLA so we have to look into this

**Comment by RanaMostafaAbdElMohsen** [comment]
Hi, @akelad ,
Can I work on this issue ?

**Comment by akelad** [comment]
Sure! we'd love your contribution

**Comment by RanaMostafaAbdElMohsen** [comment]
@akelad ,
Can you please provide assistance on how to reproduce same issue, I have trouble finding documentation that references custom url for nlu endpoint

**Comment by RanaMostafaAbdElMohsen** [comment]
Hi @akelad ,

I investigated this issue. The problem is indeed with urljoin function.
The problem urljoin function just take domain and ignores if anything written after slash

Examples:

`>>> urljoin(https://localhost:8080/a, "/model/parse") `
`https://localhost:8080/model/parse`

`>>> urljoin(https://localhost:8080/a/b/c/, "/model/parse") `
`https://localhost:8080/model/parse`

In both cases it just joins `https://localhost:8080` with `/model/parse`

My suggested change to resolve this conflict in `rasa/core/interpreter.py` :
        ```
if self.endpoint.url.endswith('/'):
            url = urljoin(self.endpoint.url, "model/parse")
        else:
            url = urljoin(self.endpoint.url, "/model/parse")
```

**Comment by psds01** [comment]
Tests for both of these PRs:
```python
>>> assert urljoin('http://localhost:8080/a/b/c/', "d/e") == 'http://localhost:8080/a/b/c/d/e'
??
>>> assert urljoin('http://localhost:8080/a/b/c', "d/e") == 'http://localhost:8080/a/b/c/d/e'
??
>>> assert urljoin('http://localhost:8080/a/b/c', "/d/e") == 'http://localhost:8080/a/b/c/d/e'
??
>>> assert urljoin('http://localhost:8080/a/b/c/', "/d/e") == 'http://localhost:8080/a/b/c/d/e'
??
```

**Comment by psds01** [comment]
Solution [to the problem](https://github.com/RasaHQ/rasa/blob/3b578879479b52aac43ed0e43d887e60464d156d/rasa/core/interpreter.py#L214) might look something like:

From
```python
url = urljoin(self.endpoint.url, "/model/parse")
``` 
to
```python
base_url = self.endpoint.url if self.endpoint.url.endswith("/") else self.endpoint.url+"/"
parse_path = "model/parse"
url = urljoin(base_url, parse_path)
```

**Comment by RanaMostafaAbdElMohsen** [comment]
> 
> 
> Solution [to the problem](https://github.com/RasaHQ/rasa/blob/3b578879479b52aac43ed0e43d887e60464d156d/rasa/core/interpreter.py#L214) might look something like:
> 
> From
> 
> ```python
> url = urljoin(self.endpoint.url, "/model/parse")
> ```
> 
> to
> 
> ```python
> base_url = self.endpoint.url if self.endpoint.url.endswith("/") else self.endpoint.url+"/"
> parse_path = "model/parse"
> url = urljoin(base_url, parse_path)
> ```

Yes, I checked your answer and it is also a possible solution. Thanks @psds01 for your assistance.
