### ISSUE TITLE
About the function of the FAQ

### ISSUE THREAD

**Issue by HatuneMiku** [RasaHQ/rasa#3840]
In the current situation, rasa is better able to solve task-oriented conversations, just like the example restaurant robot.

However, in practical applications, there are a large number of conversation scenarios that are not well accomplished using task-oriented ideas. These conversations may be just some inquiries about the information. A simple and independent information inquiry.

For example, customers may ask when ordering food: "Will Chinese food be spicy?"  or "what food is suitable for eating in the summer?"

The information I have obtained from rasa currently indicates that there are two possible solutions.

All of the intent to develop a categorization FAQ is one of the solutions.
(But because the FAQ's intent is more than the task-oriented, there are a lot of intentions, usually more than a few thousand, and the current RASA can't use this solution.
Because the current rasa will throw a memory error. Related reference: #968 #1621)

Another solution is to use a separate FAQ component and FAQ policy, refer to #379 #3224 #414 , which requires new ideas to introduce additional components and requires better interaction with task-driven dialog logic. But currently there are no clear development plans for the components and strategies of faq.

In the current situation, the absence of rasa on faq leads to unsatisfactory performance in real-world applications, often requiring additional dialog frames as an aid.

I hope that a larger amount of FAQ data can be effectively utilized in rasa. But at the moment I use rasa and there is no better way to solve this problem.

There are also many people in the issue who ask for similar needs, because faq and task orientation are almost equally important in real business.

If there is any solution for FAQ that I don't know, or the progress of the faq, please let me know.

**THANKS!** @akelad

**Comment by wochinge** [comment]
Thanks for raising this issue, @Ghostvv  will get back to you about it soon.

**Comment by Ghostvv** [comment]
We're currently experimenting with possible solutions to treat faq and chitchat as sequence2sequence without context.

Regarding many intents of faq, there is not too much that can be done right now, since you still need to come up with limited number of template answers

**Comment by akelad** [comment]
I'll close this as it's something we're working on and more of a question
