### ISSUE TITLE
Command line interactive learning session erased all my intent triggers during export

### ISSUE THREAD

**Issue by aaronshieh** [RasaHQ/rasa#3841]
**Rasa version**: 1.1.3

**Rasa X version** (if used & relevant): n/a

**Python version**: 3.6.8

**Operating system** (windows, osx, ...): Win10

**Issue**: After using interactive session to generate new stories and exporting, all my intent triggers were lost (domain.yml file). Everything else seems to be fine during the export overwrite.

For example, before using interactive session
```
intents:
 - ask_is_bot:
     triggers: action_is_bot
```
after interactive session export:
```
intents:
 - ask_is_bot
```

**Command or request that led to error**:
```
rasa interactive
```

**Comment by erohmensing** [comment]
Hi @aaronshieh, thanks for pointing this out. This issue has already been reported and a [PR](https://github.com/RasaHQ/rasa/pull/3792) is awaiting merge to fix it!
