### ISSUE TITLE
Predict the next action

### ISSUE THREAD

**Issue by yuxuan2015** [RasaHQ/rasa#3844]
![Screenshot from 2019-06-21 18-40-28](https://user-images.githubusercontent.com/15645056/59917269-1a3ed580-9454-11e9-9329-377b51426079.png)

How to set the correct parameters?

**Comment by wochinge** [comment]
Thanks for raising this issue, @Saladdin  will get back to you about it soon.

**Comment by akelad** [comment]
Please ask these kind of questions in our [forum](https://forum.rasa.com)
