### ISSUE TITLE
Webexteam issue when no room is provided 

### ISSUE THREAD

**Issue by obarbier** [RasaHQ/rasa#3846]
**Rasa version**: Rasa 1.1.3

**Python version**: Python 3.7.3

**Operating system** :windows

**Issue**: 

**Error (including full traceback)**:
```
webexteamssdk.exceptions.ApiError: [404] Not Found - The requested resource could not be found.
2019-06-21 14:47:23 ERROR    rasa.core.channels.webexteams  - Exception when trying to handle message.[404] Not Found - The requested resource could not be found.
2019-06-21 14:47:23 ERROR    rasa.core.channels.webexteams  - [404] Not Found - The requested resource could not be found.
```

**Command or request that led to error**: Provided secret with no room
```
rasa run --credentials credentials.yml
```
According to [Webexteam Documentation](http://rasa.com/docs/rasa/user-guide/connectors/cisco-webex-teams/). **If you do not set the room keyword argument, messages will by delivered back to the user who sent them.**
In my understanding the expected functionality when no room is provided is that Rasa message will be routed to PersonID
the Function declaration for CreateMessage is 

create(roomId=None, toPersonId=None, toPersonEmail=None, text=None, markdown=None, files=None, **request_parameters)

However below code explicitly sending message to roomID even when self.room is not set
```python
    async def send_text_message(
        self, recipient_id: Text, text: Text, **kwargs: Any
    ) -> None:
        recipient = self.room or recipient_id
        for message_part in text.split("\n\n"):
            self.api.messages.create(roomid=recipient, text=message_part)
``` 
For my use case I am using this
```
  async def send_text_message(
        self, recipient_id: Text, text: Text, **kwargs: Any
    ) -> None:
        recipient = self.room or recipient_id
        for message_part in text.split("\n\n"):
			self.api.messages.create(roomid=recipient, text=message_part) if self.room else self.api.messages.create(toPersonId=recipient, text=message_part)

```

**Comment by wochinge** [comment]
Thanks for raising this issue, @dakshvar22  will get back to you about it soon.

**Comment by dakshvar22** [comment]
@obarbier Thanks for bringing this up. Are you up for sending a quick PR with a fix?

**Comment by snbuchholz** [comment]
This shouldn't be closed, it's a bug that has not been resolved. There seems to be a PR, the contributor has signed the CLA, what needs to happen now?

**Comment by dakshvar22** [comment]
@obarbier Are you interested in resuming your work fixing this issue through your PR?

**Comment by lluchini** [comment]
> @obarbier Are you interested in resuming your work fixing this issue through your PR?

@dakshvar22 
I was looking at the changes, they are simple, if you guys want, I can take from where he left.

I just don't know the policies about taking from where someone stoped... Can I just copy his changes, fix and submit a PR?

**Comment by isaac-philip** [comment]
This issue seems solved at https://github.com/RasaHQ/rasa/pull/5460/files

May seem fine to close this issue

**Question** is when will the latest code be deployed to pypi since the package of rasa - **1.10.2** - I upgraded too does not have the changes in that PR - any help as to why ? thanks!
