### ISSUE TITLE
Rasa X version 0.19.2 get error in interactive mode

### ISSUE THREAD

**Issue by ngduyanhece** [RasaHQ/rasa#3855]
**Rasa version**: 1.13

**Rasa X version** (if used & relevant): 0.19.2

**Python version**: 3.7

**Operating system** (windows, osx, ...): osx

**Issue**: cannot use interactive learning in rasa x
<img width="1040" alt="Screen Shot 2019-06-24 at 16 09 38" src="https://user-images.githubusercontent.com/10491651/60006533-d5f14680-969a-11e9-80c5-e33c06d0d210.png">
when i start rasa x and change to interactive learning mode; got this issue 

**Error (including full traceback)**:
```

```

**Command or request that led to error**:
```

```

**Content of configuration file (config.yml)** (if relevant):
```yml

```

**Content of domain file (domain.yml)** (if relevant):
```yml

```

**Comment by wochinge** [comment]
Thanks for raising this issue, @tabergma  will get back to you about it soon.

**Comment by tabergma** [comment]
@ngduyanhece Did you start rasa x on a new rasa project, e.g. `rasa init`? If not, can you please try it on a new rasa project? Does the error still occur?
