### ISSUE TITLE
Update pytype version

### ISSUE THREAD

**Issue by federicotdn** [RasaHQ/rasa#3860]
With pytype version `2019.6.21`, the Travis build fails with the following error message:
```
[27/239] check rasa.core.channels.channel
FAILED: /home/travis/build/RasaHQ/rasa/.pytype/pyi/rasa/core/channels/channel.pyi 
pytype-single --imports_info /home/travis/build/RasaHQ/rasa/.pytype/imports/rasa.core.channels.channel.imports --module-name rasa.core.channels.channel -V 3.6 -o /home/travis/build/RasaHQ/rasa/.pytype/pyi/rasa/core/channels/channel.pyi --analyze-annotated --nofail --quick /home/travis/build/RasaHQ/rasa/rasa/core/channels/channel.py
File "/home/travis/build/RasaHQ/rasa/rasa/core/channels/channel.py", line 422, in stream: Name 'result' is not defined [name-error]
File "/home/travis/build/RasaHQ/rasa/rasa/core/channels/channel.py", line 425, in stream: Name 'result' is not defined [name-error]
```

With `2019.5.31`, however, it works correctly. The pytype version should be updated to `2019.6.21`, pinned, and all type checks should pass correctly.

**Comment by wochinge** [comment]
@federicotdn that's covered by https://github.com/RasaHQ/rasa/pull/3994 , isn't it?

**Comment by federicotdn** [comment]
https://github.com/RasaHQ/rasa/pull/3994 pins the pytype version, but does not update it.

**Comment by arthurTemporim** [comment]
@federicotdn I have updated the pytype version to `2019.7.11` and the error is the same. But I just added `result = None` [here](https://github.com/RasaHQ/rasa/blob/2d7092536aaadc130a33374c515b8529505b8b81/rasa/core/channels/channel.py#L414) and the error has gone locally. I created the brach [improve_pytype](https://github.com/RasaHQ/rasa/tree/improve_pytype) to verify if this error still exists on Travis.
