### ISSUE TITLE
don't require local model if remote storage is given

### ISSUE THREAD

**Issue by wochinge** [RasaHQ/rasa#3861]
If a remote storage for models is specified, it should not be required to have a local model.

```
    2019-06-23 15:08:34 INFO     root  - Starting Rasa Core server on http://localhost:5000
    2019-06-23 15:08:34 WARNING  rasa.core.agent  - Could not load local model in 'models'
```

**Comment by tabergma** [comment]
@wochinge The description of the issue is missing a not, isn't it? E.g.: 
If a remote storage for models is specified, it should **not** be required to have a local model.

**Comment by wochinge** [comment]
yes, you are totally right 🙈

**Comment by tabergma** [comment]
was fixed by https://github.com/RasaHQ/rasa/pull/3942
