### ISSUE TITLE
socketio channel should also support attachments

### ISSUE THREAD

**Issue by mechko** [RasaHQ/rasa#3863]
**Description of Problem**:
Socketio channel cannot handle attachments. Because of this, attachments are handled as text messages, which cannot be parsed by Webchat JS clients.

**Overview of the Solution**:
add send_attachment method to socketio.py, like so: 

```
async def send_attachment(
        self, recipient_id: Text, attachment: Iterable[Dict[Text, Any]], **kwargs: Any
    ) -> None:
        """Sends attachment to the output."""        
        await self._send_message(self.sid, {"attachment" : attachment})
```

I can create a pull request if needed. 

**Definition of Done**:
- [ ] Tested with webchat JS clients
- [ ] Feature is documented

**Comment by wochinge** [comment]
@mechko Thanks for this enhancement proposition. A pr would be great and highly appreciated! 🚀
