### ISSUE TITLE
misleading error message with `actions` folder

### ISSUE THREAD

**Issue by erohmensing** [RasaHQ/rasa#3865]
if you run `rasa run actions` with no `actions.py` file, you get a helpful:
```
(rasa) ellas-mbp-2:formbot erohmensing$ rasa run actions
The path 'actions.py' does not exist. Please make sure to use the default location ('actions') or specify it with '--action'.
```
However, if your actions files are in an `actions` folder, you get this confusing message:
```
(rasa) ellas-mbp-2:formbot erohmensing$ rasa run actions
No model found. Train a model before running the server using `rasa train`.
```

Either this should be fixed, or we should just support loading files from an `actions` directory as well as from `actions.py`.

**Comment by SamuelJaulin** [comment]
I have a similar error when I try to custom action server on a specific folder.

> $ rasa run actions --actions data.actions -v
The path 'data/actions.py' does not exist. Please make sure to use the default location ('actions') or specify it with '--action'.

On rasa 1.1.4, in file **rasa/cli/run.py**, line 54 (function run_actions), removing `+ ".py"` solves my error and loads my custom action.

> $ rasa run actions --actions actionss -v
2019-06-27 17:12:09 INFO     rasa_sdk.endpoint  - Starting action endpoint server...
2019-06-27 17:12:09 INFO     rasa_sdk.executor  - Registered function for 'action_feedback'.
2019-06-27 17:12:09 INFO     rasa_sdk.executor  - Registered function for 'action_feedback_oui'.
2019-06-27 17:12:09 INFO     rasa_sdk.executor  - Registered function for 'action_feedback_non'.
2019-06-27 17:12:09 INFO     rasa_sdk.executor  - Registered function for 'action_chat_restart'.
2019-06-27 17:12:09 INFO     rasa_sdk.executor  - Registered function for 'action_welcome'.
2019-06-27 17:12:09 INFO     rasa_sdk.endpoint  - Action endpoint is up and running. on ('0.0.0.0', 5055)

So the modify function that works for me is :

```python
def run_actions(args: argparse.Namespace):
    import rasa_sdk.__main__ as sdk
    import sys
    args.actions = args.actions or DEFAULT_ACTIONS_PATH
    # insert current path in syspath so module is found
    sys.path.insert(1, os.getcwd())
    path = args.actions.replace(".", os.sep)
    _ = get_validated_path(path, "action", DEFAULT_ACTIONS_PATH)
    sdk.main_from_args(args)
```

So this modification enable loading a specific folder but break loading a specific file like `action.py`.

**Comment by evgeniiaraz** [comment]
I would like to take up on the issue. I have started looking into it.

**Comment by erohmensing** [comment]
Awesome @evgeniiaraz! I will assign it to you. Let me know if you have any questions!

**Comment by erohmensing** [comment]
Hey @evgeniiaraz are you still working on this? Anything I can do to help?

**Comment by evgeniiaraz** [comment]
Hi, I am really sorry! I’ll finish it within the next week. Is there a deadline by which you would like it done? When I make the changes, which brunch should I push the changes to?

**Comment by erohmensing** [comment]
It's not too urgent, next week is fine. I just wanted to check in to make sure that you were still committed to it, otherwise I would open it up for someone else to work on.

As it's a bug fix, it would be great if you could push it to our patch branch, which at the moment is `1.2.x`. It's possible by the time you are ready to open the PR that we will have released `1.3.0`, in which case the new patch branch should already exist at `1.3.x` (if it doesn't that's our fault, ping me and i'll take care of it)

**Comment by wochinge** [comment]
@@evgeniiaraz I unassign you for now. Just re-assign yourself in case you start doing it :-)

**Comment by tjpalmer** [comment]
In testing on 1.4.x, I don't see the described behavior. To explore, I created a folder called `actions` with `actions/__init__.py` that imports actions from `actions/custom.py`. These all work:

- `rasa run actions --actions actions`
- `rasa run actions --actions actions.custom`
- `rasa run actions -v`

This fails (with the "No model found" error):

- `rasa run actions`

I don't see anything in git blame that suggests recent changes that would have changed the behavior either. But I didn't test older versions.

The problem that I experience above seems to be in the `run_actions` function not getting called at all. I haven't dug into the `argparse` fix for this. Just reporting what I found so far, since it seems to be different than the behavior described by others above.

**Comment by tjpalmer** [comment]
The problem I've described above is due to `parse_last_positional_argument_as_model_path()`.

**Comment by wochinge** [comment]
> The problem I've described above is due to parse_last_positional_argument_as_model_path().

Thanks for digging into this! 

> And there are several ways to go about fixing this, so I still won't touch code yet. 

Which ones do you see? I would just adapt `parse_last_positional_argument_as_model_path` to not apply to the `rasa run actions` case.

**Comment by tjpalmer** [comment]
If that's your preferred solution, I'll try to fit some time in on it this weekend. The simple solution is a one liner, of course, but I'd want to be sure to update tests properly, too, etc.

**Comment by tjpalmer** [comment]
For my pull request, I added a bit of documentation on using an `actions` subdir, though this support already existed. It might be good to add an explicit example or test sometime on using an actions dir, too.

**Comment by pnandhini11** [comment]
Hi Rasa Team, I would like to take up this issue and work on this to solve it.  This is the first time I am trying to contribute to Rasa Application.

**Comment by erohmensing** [comment]
Hi there @pnandhini11, sorry this issue is a little out of date! This one was actually closed in https://github.com/RasaHQ/rasa/pull/4675, so I will close this issue. However, we'd still love for you to contribute -- check out the other open issues, or perhaps something like [this](https://forum.rasa.com/t/how-to-run-rasa-interactive-in-a-different-port/10517/6) would be another option.
