### ISSUE TITLE
Dockerfile drop ENTRYPOINT

### ISSUE THREAD

**Issue by rgstephens** [RasaHQ/rasa#3870]
**Description of Problem**:
The current Dockerfile uses the `ENTRYPOINT` command to invoke rasa and then the `CMD` to invoke the `--help` option in case the user doesn't pass rasa command options. Using `ENTRYPOINT` reduces the flexibility of using the standard rasa container because it means the developer can only use this container when they want to invoke `rasa`. 

I'm running into lots of issues migrating an existing Rasa bot to 1.0. To troubleshoot these issues, I'd like to use the your rasa image and execute the shell.

**Overview of the Solution**:
My proposal is to drop the use of `ENTRYPOINT` in your Dockerfile and change CMD to:

```
CMD ["rasa", "--help"]
```

**Comment by wochinge** [comment]
Hi @rgstephens . You can also overwriter the entrypoint when running a docker container using `--entrypoint=bash`. I put your issue out for discussion since I agree that overwriting the command might be more intuitive. I could even reflect this in https://github.com/RasaHQ/rasa/pull/3332

**Comment by MetcalfeTom** [comment]
I am also for dropping it, does having the `ENTRYPOINT` allow for any benefit over putting the full `rasa` command in `CMD`?  If anything, separating `rasa` from the invocation (as it is now) may just lead to more confusion.

**Comment by tmbo** [comment]
the benefit of using the entrypoint is that the run commands using docker are very similar to the ones on the commandlien
`docker run rasa/rasa train`

given that there is a way to change the entrypoint using `--entrypoint=bash` I don't think this is something we need to change.

**Comment by wochinge** [comment]
I close that for now. If there any further arguments which should be heard, feel free to re-open the issue :-)
