### ISSUE TITLE
How do I do interactive training while creating conversational chatbot

### ISSUE THREAD

**Issue by ruchiawasthi63** [RasaHQ/rasa#3873]
I've successfully run the training procedure for creating the chat bot  but I want to train my bot using interactive learning. I tried understanding https://rasa.com/docs/rasa/core/interactive-learning/ but the command prompt is giving the error that rasa is not recognized as an internal or external command.

When i do pip install rasa and pip install rasa-x, it shows that it has successfully installed the packages. I'm not able to figure out how "rasa interactive \
  -m models/20190515-135859.tar.gz \
  --endpoints endpoints.yml" this works.

**Comment by wochinge** [comment]
Thanks for raising this issue. @msamogh will come back to you soon.

**Comment by msamogh** [comment]
Ok that's weird. Could you try creating a [virtualenv](https://docs.python-guide.org/dev/virtualenvs/), install Rasa inside it, and then try running your command again?

**Comment by ruchiawasthi63** [comment]
Is there any other way of doing interactive learning other than writing "
   `rasa interactive \ -m models/20190515-135859.tar.gz \ --endpoints endpoints.yml `
in command prompt? Can we do it somehow in jupyter notebook?

**Comment by akelad** [comment]
@ruchiawasthi63 please reopen your issue as a bug report and fill out the corresponding template to help us resolve this
