### ISSUE TITLE
Not able to connect to ACTION SERVER

### ISSUE THREAD

**Issue by ruchiawasthi63** [RasaHQ/rasa#3885]
I have created actions.py file in the same folder where all my other files - domain.yml, policies.yml etc are located. But while running the bot I'm encountering the following error:
    `2019-06-27 16:38:33 ERROR    rasa_core.actions.action  - Failed to run custom action 
    'Repayment_form'. Couldn't connect to the server at 'http://0.0.0.0:5055'. Is the 
    server running? Error: HTTPConnectionPool(host='0.0.0.0', port=5055): Max retries exceeded 
    with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection 
    object at 0x000001CCCF4CEDA0>: Failed to establish a new connection: [WinError 10049] The 
    requested address is not valid in its context'))
    2019-06-27 16:38:33 ERROR    rasa_core.processor  - Encountered an exception while running 
    action 'Repayment_form'. Bot will continue, but the actions events are lost. Make sure to fix 
    the exception in your custom code.`
This is my domain file:
[domain_bot_action.txt](https://github.com/RasaHQ/rasa/files/3334333/domain_bot_action.txt)
This is my stories file
[stories_bot_action.txt](https://github.com/RasaHQ/rasa/files/3334336/stories_bot_action.txt)
My actions.py file looks like this. 
    `from typing import Dict, Text, Any, List, Union, Optional
     from rasa_sdk import Tracker
     from rasa_sdk.executor import CollectingDispatcher
     from rasa_sdk.forms import FormAction

     class RepaymentForm(FormAction):
         def name(self) -> Text:
             return "Repayment_form"
    
         def required_slots(tracker: Tracker) -> List[Text]:
             return ["sub_class"]
    
         def slot_mappings(self) -> Dict[Text, Union[Dict, List[Dict]]]:
             return {"sub_class": [self.from_text()],}
    
         def db() -> List[Text]:
             return ['pre-close','pre-closure','preclose','preclosure', 'pre close', 'no' , 'loan repayment 
     methods', 'repay loan methods', 'interest rate', 'interest']
    
         def validate_sub_class( self, value: Text, dispatcher: CollectingDispatcher, tracker: Tracker, 
     domain: Dict[Text, Any],) -> Optional[Text]:
             if value.lower() in self.db:
                 return {"sub_class" : value}
        
             else:
                 dispatcher.utter_template("utter_wrong_format", tracker)
                 return {"sub_class": None}
    
         def submit(self,dispatcher: CollectingDispatcher,tracker: Tracker, domain: Dict[Text, Any],) - 
    > List[Dict]:
        """Define what the form has to do
            after all required slots are filled"""
        # utter submit template
             dispatcher.utter_template("utter_submit", tracker)
             return []`

This is how the bot has responded to other inputs. It's successfully running but it fails as soon as it has to perform any custom action
![image](https://user-images.githubusercontent.com/42084784/60262499-eb18e000-98fb-11e9-8eb3-424310f4cf7e.png)

**Comment by MahmoudNasr95** [comment]
What about your endpoints.yml?
Make sure that you uncomment the following lines:
```
action_endpoint:
 url: "http://localhost:5055/webhook"
```

Also, you did not mention if you made sure to run the action server by
`rasa run actions`

**Comment by ruchiawasthi63** [comment]
This is my endpoints file
[endpoints_bot.txt](https://github.com/RasaHQ/rasa/files/3335918/endpoints_bot.txt)

Also, according to the documentation  https://rasa.com/docs/rasa/core/actions/
![image](https://user-images.githubusercontent.com/42084784/60286741-c50c3380-992d-11e9-827e-3c5ec7b7907e.png)
I'm running `python -m rasa_sdk --actions actions` this command so I dont see why will I be required to run `rasa run actions`

**Comment by lahsuk** [comment]
It doesn't look like it is finding your custom actions. 
It should have said something like `Registered function for 'Repayment_form'.`

When you start the actions server, it should point to either the `actions` module or the `actions.py` file.
e.g> If you have just single custom action, you could do something like `rasa run actions --actions repayment_form.py`

**Comment by ruchiawasthi63** [comment]
@lahsuk  On doing so i encounter the following error
    
    `C:\Users\user\Downloads\tutorial-tf-pipeline-master\tutorial-tf-pipeline-master\My_bot>python` -m 
    rasa_sdk.endpoint --actions actions.py -p 5055
    2019-06-28 12:35:28 INFO     rasa_sdk.endpoint  - Starting action endpoint server...
    2019-06-28 12:35:28 ERROR    rasa_sdk.executor  - Failed to register package 'actions.py'.
    Traceback (most recent call last):
      File "C:\ProgramData\Anaconda3\lib\site-packages\rasa_sdk\executor.py", line 175, `in` 
      register_package
      self._import_submodules(package)
      File "C:\ProgramData\Anaconda3\lib\site-packages\rasa_sdk\executor.py", line 162, in _ 
      import_submodules
      package = importlib.import_module(package)
      File "C:\ProgramData\Anaconda3\lib\importlib\__init__.py", line 127, in import_module
        return _bootstrap._gcd_import(name[level:], package, level)
      File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
      File "<frozen importlib._bootstrap>", line 983, in _find_and_load
      File "<frozen importlib._bootstrap>", line 962, in _find_and_load_unlocked
    ModuleNotFoundError: No module named 'actions.py'; 'actions' is not a package`
```

**Comment by ruchiawasthi63** [comment]
The same error comes when i try `python -m rasa_sdk.endpoint --actions Repaymentform.py -p 5055`
Error:  `No module named 'Repaymentform'`

**Comment by lahsuk** [comment]
@ruchiawasthi63 Sorry, that was my mistake.
You need to run it this way:
`python -m rasa run actions --actions Repaymentform` # no need for the `.py` part.

**Comment by ruchiawasthi63** [comment]
The same error @lahsuk 
![image](https://user-images.githubusercontent.com/42084784/60329304-ba917e80-99ad-11e9-9cf8-95904a5927a0.png)

**Comment by ruchiawasthi63** [comment]
I don't understand where is my endpoints.yml file getting used if Action endpoint is running on the port that is given to me while running `python -m rasa run actions --actions Repaymentform`  i.e. `0.0.0.0 , 5055`
My endpoints file instead contains `"http://localhost:5055/webhook"

**Comment by akelad** [comment]
Please ask these kind of questions in our [forum](https://forum.rasa.com)

**Comment by lahsuk** [comment]
The endpoints.yml file is used by your rasa server. You need to run both instance of rasa and rasa_sdk server.
`python -m rasa run actions --actions Repaymentform`
The Repayment form is the name of your python file. Not the class name. (I should have elaborated more here). Do you have a file name `Repaymetform.py` from where you're running your action server?

**Comment by ruchiawasthi63** [comment]
@lahsuk  So the server in my endpoints file and the server generated on running `python -m rasa run actions --actions Repaymentform` should be on same port?
Also, is my actions.py file correct because I'm not able to find anything wrong it. I'm unable to understand if there's a problem in getting the appropriate data once the rasa server sends my server a POST request or are the two servers not able to connect only! 

No, i dont have Repaymentform.py file. I have one actions.py file in the same folder where i have all the other files like endpoint, config, domain etc.

**Comment by lahsuk** [comment]
I'm running your code with `python -m rasa_sdk.endpoint --actions actions` and it runs correctly. 
![image](https://user-images.githubusercontent.com/29747785/60335131-cafd2580-99bc-11e9-95cd-4a1ac47db6d7.png)

The code is here: https://gist.github.com/lahsuk/1f73454b3edf424aba4c7231ce6ccd64

Maybe it's a windows only problem...

**Comment by ruchiawasthi63** [comment]
Yes, even I'm able to run your file properly :/ 
Anyways, thanks for helping out! 
@lahsuk

**Comment by Pavucsan** [comment]
> @MahmoudNasr95 The server is setting up correctly but its not responding.
> ![image](https://user-images.githubusercontent.com/42084784/60286955-554a7880-992e-11e9-8493-cacd5264b27f.png)

did you found the solution for this...

**Comment by mayurkuwar43** [comment]
I am facing same error,please help. 
 Failed to run custom action 'lead_form_p1'. Couldn't connect to the server at 'http://localhost:5055/webhook'. Is the server running? Error: Cannot connect to host localhost:5055 ssl:default [Connect call failed ('127.0.0.1', 5055)]
2020-07-31 18:39:55 ERROR    rasa.core.processor  - Encountered an exception while running action 'lead_form_p1'. Bot will continue, but the actions events are lost. Please check the logs of your action server for more information.
@ruchiawasthi63

**Comment by mayurkuwar43** [comment]
I am facing same error,please help.
Failed to run custom action 'lead_form_p1'. Couldn't connect to the server at 'http://localhost:5055/webhook'. Is the server running? Error: Cannot connect to host localhost:5055 ssl:default [Connect call failed ('127.0.0.1', 5055)]
2020-07-31 18:39:55 ERROR rasa.core.processor - Encountered an exception while running action 'lead_form_p1'. Bot will continue, but the actions events are lost. Please check the logs of your action server for more information.
[stories.txt](https://github.com/RasaHQ/rasa/files/5010276/stories.txt)
[domain.txt](https://github.com/RasaHQ/rasa/files/5010278/domain.txt)
[endpoint.txt](https://github.com/RasaHQ/rasa/files/5010279/endpoint.txt)

**Comment by Shivappa** [comment]
I am facing same issue.
2022-04-13 13:32:38 ERROR rasa.core.actions.action - Failed to run custom action 'action_ask_main_form_topic_main'. Couldn't connect to the server at 'http://action_server:5055/webhook'. Is the server running? Error: Cannot connect to host action_server:5055 ssl:default [Temporary failure in name resolution]

If I replace  `http://action_server:5055/webhook` with  `http://<IPAddressof my PC>:5055/webhook`, it works.

Not working cases:
- `http://action_server:5055/webhook`
- `http://localhost:5055/webhook`

Working cases:
- `http://<IPAddressof my PC>:5055/webhook`

But I am running in Azure webapp, there I cannot use IP address. Any body has an idea why the action_server endpoint does't work with hostname of servicename and works only with IP address ?

**Comment by rgstephens** [comment]
@Shivappa This isn't a Rasa bug. You could post it on the Rasa forum or an Azure forum.
