### ISSUE TITLE
Display warning about missing component/policy in config whenever possible

### ISSUE THREAD

**Issue by msamogh** [RasaHQ/rasa#3886]
**Description of Problem**:
In most instances, it is straightforward to infer from the domain file or the training data that the user is trying to use a feature that is conditional on a component/policy being included in the `config.yml` file.

Identifying these situations while training and displaying preemptive warnings could potentially save the user effort/time by avoiding unnecessary retraining in that case.

**Overview of the Solution**:
Display appropriate warnings during the respective parsing steps by comparing it against the config file. It could be something along the lines of `"Found usage of triggers in domain file, but could not find MappingPolicy in config.yml that is needed for it to work"`.

**Examples** (if relevant):
The example that brought me here was triggers. An intent in the domain file that looks like this:
`- request_human: {"triggers": "action_human_handoff"}` without `MappingPolicy` being included in `config.yml`. But there are many more examples.

**Blockers** (if relevant):

**Definition of Done**:
- [x] Perform checking for policies
- [ ] Perform checking for NLU pipeline features

**Comment by amn41** [comment]
This is a cool suggestion !

**Comment by akelad** [comment]
@msamogh is this complete?

**Comment by msamogh** [comment]
No, `Perform checking for NLU pipeline features` is still remaining in the checklist.

**Comment by akelad** [comment]
ok next time i think it's better to have two separate issues if two separate PRs are going to fix it :)

**Comment by btotharye** [comment]
maybe too much for this issue but from reading our docs it appears we have some recommendations on certain pipelines to use based on your training data set.

Do you think it would make sense to also maybe give a message in the console if there is a better pipeline configuration they could use?

Wasn't sure if we could really make any determination on how much training data they have but seemed like an interesting idea.

**Comment by btotharye** [comment]
@msamogh do you have any examples on the NLU pipeline config?  I'm reading through our docs on the pipeline stuff and I don't see a ton of real config options other than setting what you are using.

I'm trying to figure out how this relates to what I should be checking against, anything you could point me to even in code or docs to help me out?

**Comment by msamogh** [comment]
> Do you think it would make sense to also maybe give a message in the console if there is a better pipeline configuration they could use?

Definitely out-of-scope for this issue.

**Comment by msamogh** [comment]
> do you have any examples on the NLU pipeline config?

What sort of examples?

**Comment by akelad** [comment]
I would say: `RegexFeaturizer` for both regex and lookup table definitions. `EntitySynonymMapper` for synonyms. `ResponseSelector` (i think that one might already throw warnings if you don't include it, but not sure). `CRFEntityExtractor` for any sort of entities that are present maybe too. 
I think that's all, but may be worth double checking here: https://rasa.com/docs/rasa/nlu/components/#components

**Comment by btotharye** [comment]
@akelad I guess it does a warning for the `ResponseSelector` if its missing in the config.yml but your training data includes response selector data.  So I can just use this as an example for the others I guess.

```
UserWarning: Training data consists examples for training a response selector but no response selector component specified inside NLU pipeline
  "Training data consists examples for training a response selector but "
```

**Comment by btotharye** [comment]
I'm going to work on the `RegexFeaturizer` first does anyone know if it also requires `CRFEntityExtractor` as well?  It seems like from the doc's you would need both but from testing with a basic zipcode I can get either to work by only supplying one or the other in the config.  Just wanted to verify so I ensure what warnings to specifically check for.  I'll start with both being required for now until I hear otherwise.

**Comment by btotharye** [comment]
So looks like from the initial testing for the object it only gives `text_features` when it finds things related to text including the regex so that will be hard to verify in current state.

I am however able to get the regex pattern info out of the training data if we can just find an easy way to update this `components.provides` object to have a regex specific option, I'm looking into this part now.

Output from my branch:

```
The component object is ['tokens', 'intent_tokens', 'response_tokens']
The regex object is: [{'name': 'zipcode', 'pattern': '[0-9]{5}'}]
The component object is ['text_features', 'intent_features', 'response_features']
The regex object is: [{'name': 'zipcode', 'pattern': '[0-9]{5}'}]
The component object is ['intent', 'intent_ranking']
The regex object is: [{'name': 'zipcode', 'pattern': '[0-9]{5}'}]
The component object is ['response', 'response_ranking']
The regex object is: [{'name': 'zipcode', 'pattern': '[0-9]{5}'}]
The component object is ['text_features']
The regex object is: [{'name': 'zipcode', 'pattern': '[0-9]{5}'}]
```

https://github.com/RasaHQ/rasa/blob/issue_3886/rasa/nlu/components.py#L93

**Comment by btotharye** [comment]
I was able to get around the issue and for now found one of the objects was for `RegexFeaturizer` so I have that working now.

**Comment by btotharye** [comment]
ok I have a PR now for all the checks mentioned and awaiting review at https://github.com/RasaHQ/rasa/pull/4706

**Comment by btotharye** [comment]
Still need to finish writing tests for the PR https://github.com/RasaHQ/rasa/pull/4706

**Comment by wochinge** [comment]
@btotharye Is this the stale pr you wanted to talk about?

**Comment by btotharye** [comment]
@wochinge yep!
