### ISSUE TITLE
Rasa NLU run not generating logs on parse

### ISSUE THREAD

**Issue by mgcostaParedes** [RasaHQ/rasa#3888]
Hi, 
I am trying to generate a log file with the user parse on a trained model, but once i make the request to localhost:5005/model/parse , there´s no log fixe with the intent results.

I am using this to run the server
`python3 -m rasa run --model models/${LAST_MODEL_FILE} --enable-api --log-file logs`

already tried with logs.log, still the same.

I am using the latest rasa.

**Comment by akelad** [comment]
Please ask these kind of questions in our [forum](https://forum.rasa.com)
