### ISSUE TITLE
How do I deploy my bot with Cloud Foundry ?

### ISSUE THREAD

**Issue by upirlot** [RasaHQ/rasa#3892]
How can I deploy my rasa bot on CloudFoundry ? I have set up the requirements to install rasa 1.0.9 on my app and put a command in my app manifest as : “rasa run” however the command does’nt work and during the staging I get an error like “app has no start command”. From the logs I got I saw that install directory of rasa was not on the PATH so I ran the command from that directory but I still have the same "app has no start command" meaning it didn't work. Hope you can help me to figure out how to deploy a bot with cloud foundry.

**Comment by imLew** [comment]
Hi @upirlot, we only use Github issues for bugs and feature requests.
Please ask your question in the forum (https://forum.rasa.com).
