### ISSUE TITLE
Unable to run standalone NLU HTTP server

### ISSUE THREAD

**Issue by lgrinberg** [RasaHQ/rasa#3894]
**Rasa version**: 1.1.4

**Rasa X version** (if used & relevant):

**Python version**:  3.6

**Operating system** (windows, osx, ...):  Windows 10

**Issue**:
Trying to run a standalone Rasa NLU HTTP server by runnng "rasa run --enable-api -m models/nlu-20190627-164514.tar.gz" as described in the "Running NLU Server" section here http://rasa.com/docs/rasa/nlu/using-nlu-only/

Instead the core server is run.  I need to run a standalone NLU HTTP server that I can then pass to my Core server in the endpoints.yml file.

**Error (including full traceback)**:

(py36) C:\Users\lgrin\bots\health-quote-ml\aify-health-quote>rasa run --enable-api -m models/nlu-20190627-164514.tar.gz
No chat connector configured, falling back to the REST input channel. To connect your bot to another channel, read the docs here: https://rasa.com/docs/rasa/user-guide/messaging-and-voice-channels
2019-06-27 16:47:01 INFO     root  - Starting Rasa Core server on http://localhost:5005

**Command or request that led to error**:
rasa run --enable-api -m models/nlu-20190627-164514.tar.gz

```

```

**Content of configuration file (config.yml)** (if relevant):
```yml

```

**Content of domain file (domain.yml)** (if relevant):
```yml

```

**Comment by imLew** [comment]
@lgrinberg is it actually not working for you?
I just tried it with our moodbot example and I indeed also get the log message `Starting Rasa Core server` but it nonetheless works when I query the server.

**Comment by lgrinberg** [comment]
Yes, thank you for that  tip.   I tried it again and it is actually going to the NLU server.  So the documentation is correct, but the output is wrong.  Should say "Rasa NLU Server"

**Comment by akelad** [comment]
Cool, could you reopen an issue or a PR describing that issue? Since the original issue is resolved.
