### ISSUE TITLE
Rasa X doesn't have 'Share with guest testers' button

### ISSUE THREAD

**Issue by TatianaParshina** [RasaHQ/rasa#3895]
**Rasa version**:
rasa==1.1.4
**Rasa X version** (if used & relevant):
rasa-x==0.19.2
**Python version**:
Python 3.6.8
**Operating system** (windows, osx, ...):
Windows 8.1
**Issue**:
Rasa X UI doesn't display 'Share with guest testers' button in the models table (Google Chrome browser).

![share_with_tester](https://user-images.githubusercontent.com/42603622/60343245-3266a580-99bc-11e9-8344-047552a09347.jpg)

**Command or request that led to error**:
I used ngrok to create a connection to my local computer that is publicly available on the internet:
```
ngrok http 5002
export RASA_X_HOSTNAME=https://xxxxxx.ngrok.io; rasa x
```

**Comment by erohmensing** [comment]
Hey @TatianaParshina, soryr, this screenshot is out of date. Find the fix here: https://forum.rasa.com/t/share-button-in-models-table/11618/4

**Comment by TatianaParshina** [comment]
Hi @erohmensing , thank you a lot for the information! I found the button in the Conversations tab now. 
I will close the issue
