### ISSUE TITLE
Error in Microsoft LUIS nlu format version

### ISSUE THREAD

**Issue by arthurTemporim** [RasaHQ/rasa#3899]
**Rasa version**: Rasa 1.1.4

**Rasa X version** (if used & relevant): Not used.

**Python version**: 3.6.6

**Operating system** (windows, osx, ...): Arch Linux

**Issue**: When you create a Microsoft Luis bot and export the .json file nlu data it cames with version 3.2.0 but Rasa only understands version 2.x.x.

**Error (including full traceback)**:
```
No NLU data given. Please provide NLU data in order to train a Rasa NLU model using the '--nlu' argument.
```

**Command or request that led to error**:
```
rasa train nlu
```

**Comment by arthurTemporim** [comment]
[Here](https://github.com/RasaHQ/rasa/blob/6cbcd1732e9c9d62665347119af0a5bb0f1fcb6e/rasa/nlu/training_data/formats/luis.py#L22) the version of the Microsoft LUIS is checked, it is needed to handle version 3 too and update the `LuisReader` with the new version changes.
```
        # Simple check to ensure we support this luis data schema version
        if not js["luis_schema_version"].startswith("2"):
            raise Exception(
                "Invalid luis data schema version {}, "
                "should be 2.x.x. "
                "Make sure to use the latest luis version "
                "(e.g. by downloading your data again)."
                "".format(js["luis_schema_version"])
            )
```

**Comment by imLew** [comment]
This is a known issue, it's in the maintenance inbox as #1790.
