### ISSUE TITLE
Encountered an exception while running action 'action_retrieve_bank'. Bot will continue, but the actions events are lost. Make sure to fix the exception in your custom code.

### ISSUE THREAD

**Issue by ravikrcs** [RasaHQ/rasa#3902]
**Rasa version**: 1.1.4

**Rasa X version** (if used & relevant):

**Python version**:3.6.8

**Operating system** (windows, osx, ...):windows

**Issue**:

Encountered an exception while running action 'action_retrieve_bank'. Bot will continue, but the actions events are lost. Make sure to fix the exception in your custom code.

**Error (including full traceback)**:
```

```

**Command or request that led to error**:
```

```

**Content of configuration file (config.yml)** (if relevant):
```yml

```

**Content of domain file (domain.yml)** (if relevant):
```yml

```

**Comment by ravikrcs** [comment]
it is working in jupyter notebook or rasa x. but not on cmdline or interactive shell

**Comment by ravikrcs** [comment]
this is my actions:

class ApiActionBank(Action):
    def name(self):
        return "action_retrieve_bank"

    def output_string(bnk):
        return article_df[my_dict.get(bnk)][0]
    
    def run(self, dispatcher, tracker, domain):
        
        my_dict = {'motorbike_':'automotive', 'car_':'automotive', 'ai_':'it_digital', \
               'saas_':'it_digital', 'retail_':'business', 'consumer_':'business'}

        article_df = pd.read_csv("data/industry_report.csv")
        bnk = tracker.get_slot('bnk')
        #group = tracker.get_slot('group')
        
        #display(Image(response[0], height=550, width=520))
        dispatcher.utter_message("Here is something to help your search for Banking: {}".format(article_df[my_dict.get(bnk)][0]))
        return []

**Comment by ravikrcs** [comment]
domain file and config file is perfect according to rasa documents.

**Comment by imLew** [comment]
Hi @ravikrcs, 

the command you are running is `rasa shell`? Please try adding the `--debug` flag and posting the output.

**Comment by ravikrcs** [comment]
same thing happen

**Comment by imLew** [comment]
Yes, adding the `--debug` option is not a solution but a way to obtain more information. Rasa should print a lot more messages when run with this option. Please copy the relevant parts and post them here.

**Comment by ravikrcs** [comment]
i got it.
it is solved by exposing the port on which the action server is running. i.e., 5055
i am using NGROK for exposing port.
ngrok http 5055

**Comment by imLew** [comment]
Glad you could solve it!

**Comment by Deepak-Perla** [comment]
@ravikrcs

> i got it.
> it is solved by exposing the port on which the action server is running. i.e., 5055
> i am using NGROK for exposing port.
> ngrok http 5055

hey help me please I couldn't understand
