### ISSUE TITLE
Inserting slots into template uses regex and not string.format

### ISSUE THREAD

**Issue by Bennie-higuru** [RasaHQ/rasa#3903]
**Rasa version**: 1.0.7

**Rasa X version** (if used & relevant): None

**Python version**: 3.6

**Operating system** (windows, osx, ...): Linux / Ubuntu

**Issue**: Rasa does not handle string formatting anymore. Instead it was changed to regex which is less resilient then string.format

**Error (including full traceback)**:
```
2019-07-01 12:15:57 ERROR    rasa.core.nlg.template  - Failed to fill utterance template '{'text': '`system`:bot-terminate `body`:Payment of R{amount} for your order was received successfully. {{Your order number is #{order_id}}}.'}'. Tried to replace '{Your order number is #{order_id' but could not find a value for it. There is no slot with this name nor did you pass the value explicitly when calling the template. Return template without filling the template. 
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/rasa/core/nlg/template.py", line 115, in _fill_template_text
    template["text"] = text.format(template_vars)
KeyError: '{Your order number is #{order_id'

```

**Command or request that led to error**:
```
 {"system": "venue-payment-received", "body": {"venue_order_total_cost":0, "venue_order_id":503}} 
```

**Content of domain file (domain.yml)** (if relevant):
```yml
 utter_payment_success:
    - text: '`system`:bot-terminate
             `body`:Payment of R{amount} for your order was received successfully. {{Your order number is #{order_id}}}.'
```

After some research I found that this bug arose when someone copied a stackoverflow comment into the rasa Language generation class.
Location: rasa/core/nlg/template.py line 109 - 115:
```
            try:
                # transforming template tags from
                # "{tag_name}" to "{0[tag_name]}"
                # as described here:
                # https://stackoverflow.com/questions/7934620/python-dots-in-the-name-of-variable-in-a-format-string#comment9695339_7934969
                # assuming that slot_name do not contain newline character here
                text = re.sub(r"{([^\n]+?)}", r"{0[\1]}", template["text"])
                template["text"] = text.format(template_vars)
```
should be changed to:
```
        try:
             template["text"] = template["text"].format(**template_vars)
```

**Comment by akelad** [comment]
Thanks for raising this issue, @imLew  will get back to you about it soon.

**Comment by imLew** [comment]
I'm looking into it. @Bennie-higuru you are right that your use case is broken by the regex, however it seems that this change was made in order to allow for names that did not get through with `.format`.

I will try to find something that addresses both problem soon, until then I recommend you implement the fix that was suggested on the forum. Or if you know a robust solution already you can of course create a PR as well :)

**Comment by imLew** [comment]
Looks like this will be solved by https://github.com/RasaHQ/rasa/pull/3951.
