### ISSUE TITLE
Missing 'Azure Storage' support in the introduction sentence of Rasa model cloud storage user guide doc

### ISSUE THREAD

**Issue by utkalsinha** [RasaHQ/rasa#3905]
**Rasa version**:

**Rasa X version** (if used & relevant):

**Python version**:

**Operating system** (windows, osx, ...):

**Issue**: Missing 'Azure Storage' support in the introduction sentence of Rasa model cloud storage user guide doc. Page reference link: https://rasa.com/docs/rasa/user-guide/cloud-storage/. Missing statement in that page: 

> Rasa supports using S3 and GCS to save your models.

**Error (including full traceback)**:
```

```

**Command or request that led to error**:
```

```

**Content of configuration file (config.yml)** (if relevant):
```yml

```

**Content of domain file (domain.yml)** (if relevant):
```yml

```

**Comment by utkalsinha** [comment]
Created a pull request for the same: https://github.com/RasaHQ/rasa/pull/3904

**Comment by akelad** [comment]
Awesome, thanks!

**Comment by utkalsinha** [comment]
PR is [approved ](https://github.com/RasaHQ/rasa/pull/3904) and merged to master, so closing this bug.
