### ISSUE TITLE
How to reduce the training time?

### ISSUE THREAD

**Issue by rajeshborra8** [RasaHQ/rasa#3907]
- I am using rasa with the pipeline spacy_sklearn.

- ner is the main motto of my project everything is going good but training for only two son files its taking around 1hr

- The size of two json files are 15mb each

- How to reduce the training time pls anyone help me out

and how to increase parallel jobs = 1 to 10

**Comment by akelad** [comment]
Please ask these kind of questions in our [forum](https://forum.rasa.com)
