### ISSUE TITLE
Webhooks broken in 0.19.2 nginx Docker Images

### ISSUE THREAD

**Issue by JanThiel** [RasaHQ/rasa#3909]
**Rasa version**: 
1.1.3

**Rasa X version** (if used & relevant): 
0.19.2

**Python version**: 
3.6

**Operating system** (windows, osx, ...): 
RHEL 8.6

**Issue**: 
The rasa/nginx Docker image contains proxy_pass rules to allow a connection of **[OUR-RASA-X-HOST]/core/(.... webhooks/rest/webhook)** to **rasa-production:5005**. This is configured in /opt/bitnami/nginx/conf/conf.d/rasax.nginx
The nginx location is configured as following:

```
 location /core {
    proxy_set_header X-Real-IP  $remote_addr;
    proxy_set_header X-Forwarded-For $remote_addr;
    proxy_set_header X-Forwarded-Proto $scheme;
    proxy_set_header Host $host;
    proxy_pass http://docker-stack/;
  }
```

Accessing [OUR-RASA-HOST]/core/webhooks results in upstream calls in this format: **rasa-production:5005//webhooks** . <-- Mind the double "/".
This will return an url resolution failure.

The nginx location block has to strip one / within the location matching directive.

Changed location from `/core` to `/core/`
``` 
 location /core/ {
    proxy_set_header X-Real-IP  $remote_addr;
    proxy_set_header X-Forwarded-For $remote_addr;
    proxy_set_header X-Forwarded-Proto $scheme;
    proxy_set_header Host $host;
    proxy_pass http://docker-stack/;
  }
```

Best Jan

**Comment by akelad** [comment]
Thanks for raising this issue, @wochinge  will get back to you about it soon.

**Comment by wochinge** [comment]
@JanThiel Thanks for digging into this, will change it in Rasa X so that it's fixed in the next version (not sure whether I'll be able to get it into the next though)

**Comment by JanThiel** [comment]
@wochinge Great to hear! Would be great if this could be shipped asap as currently we have to manually patch the container after each and every docker-compose.. You can imagine this is hell of no fun and lots of work...

**Comment by wochinge** [comment]
Already did the pr for it :-)

**Comment by wochinge** [comment]
PR is merged and this will be fixed in the next version 👍 You can also use `rasa/nginx:latest` if you want to have it asap (might take a few more minutes until the container is built)
