### ISSUE TITLE
readme: `installation` broken link

### ISSUE THREAD

**Issue by tormath1** [RasaHQ/rasa#3911]
**Rasa version**: N/A

**Rasa X version** (if used & relevant): N/A

**Python version**: N/A

**Operating system** (windows, osx, ...): N/A

**Issue**: broken link for installation.
```
- **I'm ready to install Rasa 🚀**
  [Installation](https://rasa.com/docs/rasa/installation/)
```
It should be: https://rasa.com/docs/rasa/user-guide/installation/

**Error (including full traceback)**:
```
404
```

**Command or request that led to error**:
```
$ curl -i -s -o /dev/null -w %{http_code} https://rasa.com/docs/rasa/installation/ 
```

**Content of configuration file (config.yml)** (if relevant):
```yml

```

**Content of domain file (domain.yml)** (if relevant):
```yml

```

**Comment by amn41** [comment]
thanks for spotting this! could you please create a PR to fix the link?

**Comment by tormath1** [comment]
Sure: https://github.com/RasaHQ/rasa/pull/3930 :wave:
