### ISSUE TITLE
AttributeError: 'RasaNLUModelConfig' object has no attribute 'load_component'

### ISSUE THREAD

**Issue by amit91116** [RasaHQ/rasa#3913]
Code >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>

from rasa_nlu.training_data import load_data
from rasa_nlu.model import Trainer
from rasa_nlu import config
from rasa_nlu.model import Metadata, Interpreter

def train_nlu(data,config_spacy,model_dir):
    training_data = load_data(data)
    trainer = Trainer(config.load(config_spacy))
    trainer.train(training_data)
    model_directory = trainer.persist(model_dir,fixed_model_name = 'weathernlu')

def run_nlu():
    interpreter = Interpreter.load('./models/nlu/default/weathernlu', config.load('config_spacy.json'))
    print(interpreter.parse(u"I am planning my holiday to Delhi. I wonder what is the weather out there"))

if __name__ == '__main__':
   run_nlu()

Output>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>

Traceback (most recent call last):
  File "nlu_model.py", line 19, in <module>
    run_nlu()
  File "nlu_model.py", line 13, in run_nlu
    interpreter = Interpreter.load('./models/nlu/default/weathernlu', config.load('config_spacy.json'))
  File "/home/amit/.local/lib/python3.6/site-packages/rasa_nlu/model.py", line 304, in load
    skip_validation)
  File "/home/amit/.local/lib/python3.6/site-packages/rasa_nlu/model.py", line 329, in create
    component = component_builder.load_component(
AttributeError: 'RasaNLUModelConfig' object has no attribute 'load_component'

**Comment by nikhilcss97** [comment]
I am getting the same error.

**Comment by akelad** [comment]
Please ask these kind of questions in our [forum](https://forum.rasa.com)
