### ISSUE TITLE
rasie error of domain specification has changed when load agent

### ISSUE THREAD

**Issue by ghostHBL** [RasaHQ/rasa#3917]
**Rasa version**:
rasa 1.1.3

**Rasa X version** (if used & relevant):

**Python version**:
3.6.8

**Operating system** (windows, osx, ...):
windows

**Issue**:
I get error when load agent, the log is 

```
rasa.core.domain.InvalidDomain: Domain specification has changed. You MUST retrain the policy. Detected mismatch in domain specification. The following states have been

         - removed:
         - added:
```
The removed and added is empty, it seems the  domain specification hasn't changed, I check the code in domain.py and focus on the code in function compare_with_specification:
```
        if states != self.input_states:
            missing = ",".join(set(states) - set(self.input_states))
            additional = ",".join(set(self.input_states) - set(states))
            raise InvalidDomain(
                "Domain specification has changed. "
                "You MUST retrain the policy. "
                + "Detected mismatch in domain specification. "
                + "The following states have been \n"
                "\t - removed: {} \n"
                "\t - added:   {} ".format(missing, additional)
            )
        else:
            return True
```
In my case, states and self.input_states are two list with same elements but different order, like [1,2,3] != [2,1,3], I think here should be  ` if sorted(states) != sorted(self.input_states):`  or ` if set(states) != set(self.input_states):` to ignored order problem. Do you think so?

**Comment by akelad** [comment]
Thanks for raising this issue, @tabergma  will get back to you about it soon.

**Comment by tabergma** [comment]
@ghostHBL Thanks for pointing this out. Seems to be a valid addition. Are you up for fixing this yourself? Thanks.

**Comment by akelad** [comment]
to clarify: "fixing this yourself" means submitting a PR with the fix :)

**Comment by ghostHBL** [comment]
@tabergma I create a PR for this issues, please help to follow up.
