### ISSUE TITLE
ERR_NGROK_108

### ISSUE THREAD

**Issue by ravikrcs** [RasaHQ/rasa#3921]
![ngrok_error](https://user-images.githubusercontent.com/31586794/60587987-71796a00-9db3-11e9-889c-9532e703febb.PNG)

**Comment by ravikrcs** [comment]
How can i expose two ports using ngrok, like...
ngrok http 5055   and 
ngrok http 5002

**Comment by ravikrcs** [comment]
answer please

**Comment by akelad** [comment]
Closing because this is unrelated to Rasa, please ask this on the appropriate ngrok forums
