### ISSUE TITLE
refactor `use_entities` and `ignore_entities`

### ISSUE THREAD

**Issue by imLew** [RasaHQ/rasa#3923]
**Description of Problem**:
In `domain.py` intents are dictionaries which store dictionaries of their properties. There are currently three properties: `use_entities`, `ignore_entities` and `triggers`. The first was originally a boolean which decided whether or not to use entities. This was changed recently and at the same time `ignore_entities` was introduced, which is basically the complement, it stores a list of entities which are not to be used for a given intent.
https://github.com/RasaHQ/rasa/blob/edece267f1b3aab904f4ea937e781e2f4716c7af/rasa/core/domain.py#L213

**Overview of the Solution**:
While these are both useful options for configuration they should be merged into one property in the code. The new property should be a list of the entities that are detected with the intent and should be called `used_entities` or just `entities`

**Definition of Done**:
- [ ] Remove all references to the `use_entities` and `ignore_entities` properties outside of the
method linked above.
- [ ] check that tests cover the behavior 
- [ ] Changelog

**Comment by msamogh** [comment]
What if you want to include all but one entity? With `ignore_entities`, you can just list that one entity, whereas this would require you to go through the domain and list all the other ones.

**Comment by imLew** [comment]
Yes, I think they should be merged internally only, i.e. we still have both options in the domain config but after the `collect_intent_properties` function (or w/e it's called now) it should be one. Currently both `use_entities` and `ignore_entities` are passed on to other functions.

**Comment by msamogh** [comment]
Got it.
