### ISSUE TITLE
Issue with docker-compose.yml 

### ISSUE THREAD

**Issue by ferozewaris** [RasaHQ/rasa#3928]
Hi,

I am have downloaded the Rasa-1.1.4 and using its docker-compose.yml file to deploy Rasa on ubuntu machine. The content on docker-compose is as follows. 

![Screen Shot 2019-07-04 at 12 14 04 PM](https://user-images.githubusercontent.com/22313397/60646638-48111a80-9e55-11e9-8f26-3af6b655ed61.png)

When i start the images with docker-compose up -d my rasa container does not start and giving me following error 
![Screen Shot 2019-07-04 at 12 14 18 PM](https://user-images.githubusercontent.com/22313397/60646652-4e9f9200-9e55-11e9-8c8b-e2f331eb8070.png)

Seems like it is not recognizing the start command. Can anyone please tell me the alternative

**Comment by sdu-2044** [comment]
I think you should replace "start" with "run"

**Comment by akelad** [comment]
Where did you get this docker-compose.yml from? Also please don't delete the issue template, and fill it out to give us more information on what your issues are
