### ISSUE TITLE
coroutine was never awaited

### ISSUE THREAD

**Issue by vinayak-sg** [RasaHQ/rasa#3929]
train_interactive.py:41: RuntimeWarning: coroutine 'run_weather_online' was never awaited
  run_weather_online(nlu_interpreter)

from __future__ import absolute_import
from __future__ import division
from __future__ import print_function
from __future__ import unicode_literals

import logging
import asyncio

from rasa.core.agent import Agent
from rasa.core.policies.keras_policy import KerasPolicy
from rasa.core.policies.memoization import MemoizationPolicy
from rasa.core.interpreter import RasaNLUInterpreter
from rasa.core.training import interactive
from rasa.utils.endpoints import EndpointConfig

logger = logging.getLogger(__name__)

async def run_weather_online(interpreter,
                          domain_file="weather_domain.yml",
                          training_data_file='data/stories.md'):
    # model_path = './model/dialogue'
    action_endpoint = EndpointConfig(url="http://localhost:5055/webhook")						  
    agent = Agent(domain_file,
                  policies=[MemoizationPolicy(max_history=2), KerasPolicy(max_history=3, epochs=3, batch_size=50)],
                  interpreter=interpreter,
				  action_endpoint=action_endpoint)

    loop = asyncio.get_event_loop()	
    task = loop.creat_task(agent.load_data(training_data_file))			  
    data = loop.run_until_complete(task)		   
    agent.train(data)
    # agent.persist(model_path)
    interactive.run_interactive_learning(agent, training_data_file)
    return agent

if __name__ == '__main__':
    logging.basicConfig(level="INFO")
    nlu_interpreter = RasaNLUInterpreter('./model/nlu/weathernlu')
    run_weather_online(nlu_interpreter)

**Comment by akelad** [comment]
Please fill out the correct issue template

**Comment by Traeyee** [comment]
> Please fill out the correct issue template

Useless staff, copy forever, resolution never
