### ISSUE TITLE
use endpoints.yml to fetch model from server

### ISSUE THREAD

**Issue by sdu-2044** [RasaHQ/rasa#3931]
**Rasa version**:1.1.4

**Rasa X version** (if used & relevant):

**Python version**:3.6.8

**Operating system** (windows, osx, ...):centos 7

**Issue**:I recently use the endpoints.yml to fetch model from server just as what the  [https://rasa.com/docs/rasa/user-guide/running-the-server/](document) says.Here is my endpoints.yml
 `models:
    url: http://127.0.0.1:8088/download
    wait_time_between_pulls: 10
`
But when I excute the command "rasa run --enable-api -endpoints endpoints.yml".I got the following message
 `rasa.cli.run  - 'models' not found. Using default location 'models' instead.rasa.core.agent  
 Could not load local model in 'models'`
And it create a directory called "models" automatic.
By reading the source code.In  rasa/cli/run.py  line 59 to line 73

 `def _validate_model_path(model_path: Text, parameter: Text, default: Text):

    if model_path is not None and not os.path.exists(model_path):
        reason_str = "'{}' not found.".format(model_path)
        if model_path is None:
            reason_str = "Parameter '{}' not set.".format(parameter)

        logger.debug(
            "{} Using default location '{}' instead.".format(reason_str, default)
        )

        os.makedirs(default, exist_ok=True)
        model_path = default

    return model_path`
It create a defalut model_path .That is all right until now.But  in rasa/core/agent.py line 224 to line 261. 
`    try:
        if model_path is not None and os.path.exists(model_path):
            return Agent.load_local_model(
                model_path,
                interpreter=interpreter,
                generator=generator,
                tracker_store=tracker_store,
                action_endpoint=action_endpoint,
                model_server=model_server,
                remote_storage=remote_storage,
            )

        elif model_server is not None:
            return await load_from_server(
                Agent(
                    interpreter=interpreter,
                    generator=generator,
                    tracker_store=tracker_store,
                    action_endpoint=action_endpoint,
                    model_server=model_server,
                    remote_storage=remote_storage,
                ),
                model_server,
            )

        elif remote_storage is not None:
            return Agent.load_from_remote_storage(
                remote_storage,
                model_path,
                interpreter=interpreter,
                generator=generator,
                tracker_store=tracker_store,
                action_endpoint=action_endpoint,
                model_server=model_server,
            )

        else:
            logger.warning("No valid configuration given to load agent.")
            return None

    except Exception as e:
        logger.error("Could not load model due to {}.".format(e))
        raise
`
Just as what the documention tells me 
`Rasa can load your model in three different ways:
1.Load the model specified via -m from your local storage system,
2.Fetch the model from a server (see Fetching Models from a Server), or
3.Fetch the model from a remote storage (see Cloud Storage).`

But the code wii always run into the first if branch because in rasa/cli/run.py,it has already create the default model_path.
So I change the code to force it to run into the second branch .The endpoints works for me now.
I wonder if this is a bug.
Hopes for reply!!!

**Error (including full traceback)**:
```

```

**Command or request that led to error**:
```

```

**Content of configuration file (config.yml)** (if relevant):
```yml

```

**Content of domain file (domain.yml)** (if relevant):
```yml

```

**Comment by tabergma** [comment]
@sdu-2044 Thanks for reporting this. This issue is indeed a bug. I'll have a look at it.
