### ISSUE TITLE
user guide > rasa tutorial > unable to run examples

### ISSUE THREAD

**Issue by monkeypants** [RasaHQ/rasa#3934]
**Rasa version**:
unknown - whatever the web site is using

**Python version**:
unknown - whatever the web site is using

**Operating system** (windows, osx, ...):
I am using ubuntu, with chromium browser.

**Issue**:
This page https://rasa.com/docs/rasa/user-guide/rasa-tutorial/ has 6 code blocks with a **run** button. When I click the run button, I expect to the output of the code's execution to be printed in the black box following the code block. Instead I get an error

**Error (including full traceback)**:
```
Connecting failed. Please reload and try again.
```

**Command or request that led to error**:
Clicking the "run" buttons on the page (any of them, from sections 1 through to 6 inclusive).

Reloading the page does not seem to help.

**Comment by akelad** [comment]
Thanks for raising this issue, @amn41  will get back to you about it soon.

**Comment by amn41** [comment]
related to https://github.com/RasaHQ/rasa/pull/3850
