### ISSUE TITLE
Using Microsoft Teams Reaction - Not received message type

### ISSUE THREAD

**Issue by glaulom** [RasaHQ/rasa#3935]
**Rasa version**: 0.14.0

**Python version**: 3.6

**Operating system** (windows, osx, ...): Ubuntu

**Issue**:
I have a Rasa Bot connected to Microsoft Teams, when a user try to use the "reaction" feature from Teams (see image below), I've got the following issue : rasa_core.channels.botframework  - Not received message type

Is it possible to use this Teams feature or is it not yet implemented ?

![image](https://user-images.githubusercontent.com/25532110/60671767-1491b880-9e74-11e9-83d0-14cf769e0192.png)

**Error (including full traceback)**:
```
[2019-07-04 13:49:37] "POST /webhooks/botframework/webhook HTTP/1.1" 200 154 0.001734
2019-07-04 13:49:51 INFO     rasa_core.channels.botframework  - Not received message type
```

**Comment by akelad** [comment]
Thanks for raising this issue, @erohmensing will get back to you about it soon.

**Comment by erohmensing** [comment]
I don’t think it’s implemented, as we only receive messages `if request.json["type"] == "message":` — what information could you get from this reaction that you would use in your bot?

**Comment by glaulom** [comment]
The reaction would be a way for user to give feedback on bot's responses, helping to catch when the bot didn't answer properly (with an angry emoji). This would give great feedback to the people in charge of the bot's capabilities.

**Comment by erohmensing** [comment]
Hm, it's quite specific through, as there's no explicit way of deciding whether that is user input or not (for most other people, this would totally interrupt their bot with unexpected input and screw it up). I think it makes more sense for you to extend the MSteams channel as a custom connector that supports this. 

It wouldn't be hard, essentially you have to add functionality to the webhook that parses other types of input other than `message`. https://github.com/RasaHQ/rasa/blob/master/rasa/core/channels/botframework.py#L203
Then if you received an emoji, you could pass a `UserMessage` like `/react_negative` or something like that.

**Comment by glaulom** [comment]
Thank you for the answer, I'll probably implement this !

**Comment by erohmensing** [comment]
Awesome! If you open source it, maybe others will be interested too. If you have any questions during implementation, ask on the forum and we'll help out!

**Comment by glaulom** [comment]
I'm starting to do it and I have opened a discussion on the forum to get some advice.
https://forum.rasa.com/t/using-microsoft-teams-reaction-as-feedback/14096

**Comment by gitgithan** [comment]
@glaulom Do you have any updates on how this can be implemented? I see no one has replied on the forums
