### ISSUE TITLE
Rasa X UI issues after deploy to Google Cloud

### ISSUE THREAD

**Issue by TatianaParshina** [RasaHQ/rasa#3936]
**Rasa X version** (if used & relevant):
From:
https://storage.googleapis.com/rasa-x-releases/stable/install.sh

**Python version**:
Python 2.7.13

**Operating system** (windows, osx, ...):
Debian 4.9.168

**Issue**:
I have downloaded and run the Rasa X install the script on the Google Cloud VM. 
I was able to open the Rasa X UI.

However, I have issues:
1. When I type the message, the bot is not replying. I have to refresh the page and then I can see the correct reply. 
2. Replies are displayed in another order. The latest replies are displayed on top.
3. After a while, I couldn't see any other tabs except "Talk to bot" and "Conversations"

![rasa_x_ui_issues](https://user-images.githubusercontent.com/42603622/60675102-46128000-9e84-11e9-89ea-ca6c2ec2ca2f.jpg)

**Command or request that led to error**:
I have downloaded and run the Rasa X install the script on the Google Cloud VM using commands:
```
curl -sSL -o install.sh https://storage.googleapis.com/rasa-x-releases/stable/install.sh
sudo bash ./install.sh
cd /etc/rasa
sudo docker-compose up -d
sudo python rasa_x_commands.py create --update admin me ...
```
Then I have uploaded my model using:
```
curl -k -F "model=@model-name.tar.gz" http://ipXXXX/api/projects/default/models?api_token=b07a533ff517ace23603386414c0851d1d2c8631
```

**Comment by akelad** [comment]
Thanks for raising this issue, @wochinge  will get back to you about it soon.

**Comment by wochinge** [comment]
@TatianaParshina Could please try to install using a pinned version, e.g. `https://storage.googleapis.com/rasa-x-releases/0.19.2/install.sh`?

**Comment by TatianaParshina** [comment]
@wochinge thank you for information!
I have tried to install the proposed version but I still have the same issues.

I ran the commands:
```
curl -sSL -o install.sh https://storage.googleapis.com/rasa-x-releases/0.19.2/install.sh
sudo bash ./install.sh
cd /etc/rasa
sudo docker-compose up -d
```
I had info in logs:
```
rasa_duckling_1 is up-to-date
rasa_db_1 is up-to-date
rasa_rabbit_1 is up-to-date
rasa_rasa-x_1 is up-to-date
rasa_rasa-worker_1 is up-to-date
rasa_rasa-production_1 is up-to-date
rasa_app_1 is up-to-date
rasa_nginx_1 is up-to-date
rasa_logger_1 is up-to-date
```

Should I delete something before the update?

**Comment by wochinge** [comment]
A `docker-compose pull` would be great to make sure all images are the right ones. 
Which logs do you get when you do `docker-compose logs -f` after starting Rasa X with `docker-compose up`?

**Comment by TatianaParshina** [comment]
Now remaining only 1 issue (2 others were solved after update):

1. When I type the message, the bot is not replying (only showing loading picture). I have to refresh the page and then I can see the correct reply.

I ran commands to stop, remove containers and pull image:
```
sudo docker-compose stop
sudo docker-compose rm -f
sudo docker-compose pull 
sudo docker-compose up -d
```

Logs `docker-compose logs -f` don't show errors. It shows that received user message and predicted correct next action:
```
rasa-production_1  | 2019-07-08 16:28:22 DEBUG    rasa.core.processor  - Received user message 'Hello' with intent '{'name': 'greet', 'confidence': 0.9646536707878113}' and entities '[]'
rasa-production_1  | 2019-07-08 16:28:22 DEBUG    rasa.core.processor  - Logged UserUtterance - tracker now has 58 events
rasa-production_1  | 2019-07-08 16:28:22 DEBUG    rasa.core.broker  - Published pika events to queue rasa_production_events at rabbit:
rasa-production_1  | {"sender_id": "me", "event": "user", "timestamp": 1562603302.0229087, "text": "Hello", "parse_data": {"intent": {"name": "greet", "confidence": 0.9646536707878113}, "entities": [], "intent_ranking": [{"name": "greet", "confidence": 0.9646536707878113}, {"name": "Price", "confidence": 0.15406298637390137}, {"name": "CheckOutInfo", "confidence": 0.1359877735376358}, {"name": "goodbye", "confidence": 0.13479392230510712}, {"name": "LuggageInfo", "confidence": 0.1098005473613739}, {"name": "deny", "confidence": 0.10157600045204163}, {"name": "FoodOptions", "confidence": 0.09821294248104095}, {"name": "SpecificResponseSafe", "confidence": 0.08491893112659454}, {"name": "ComplimentaryInfo", "confidence": 0.079591304063797}, {"name": "BarInfo", "confidence": 0.07771992683410645}], "text": "Hello"}, "input_channel": "rasa"}
rasa-production_1  | 2019-07-08 16:28:22 DEBUG    rasa.core.tracker_store  - Tracker with sender_id 'me' stored to database
rasa-production_1  | 2019-07-08 16:28:22 DEBUG    rasa.core.policies.memoization  - Current tracker state [None, None, None, {}, {'intent_greet': 1.0, 'prev_action_listen': 1.0}]
rasa-production_1  | 2019-07-08 16:28:22 DEBUG    rasa.core.policies.memoization  - There is a memorised next action '35'
rasa-production_1  | 2019-07-08 16:28:22 DEBUG    rasa.core.policies.two_stage_fallback  - NLU confidence threshold met, confidence of fallback action set to core threshold (0.5).
rasa-production_1  | 2019-07-08 16:28:22 DEBUG    rasa.core.policies.ensemble  - Predicted next action using policy_0_MemoizationPolicy
rasa-production_1  | 2019-07-08 16:28:22 DEBUG    rasa.core.processor  - Predicted next action 'utter_greet' with confidence 1.00.
rasa-production_1  | 2019-07-08 16:28:22 DEBUG    rasa.core.processor  - Action 'utter_greet' ended with events '['BotUttered(text: Hi, hope you\'re enjoying your stay, data: {"elements": null, "quick_replies": null, "buttons": null, "attachment": null, "image": null, "custom": null}, metadata: {})']'
```

Then I checked that there are an error and warning in Google Chrome dev console:
```
Errors:
Unchecked runtime.lastError: The message port closed before a response was received
DevTools failed to parse SourceMap: http://35.196.228.78/static/js/2.bf1eb599.chunk.js.map
```
Then I opened Rasa X in Mozilla browser. It is still the same behavior there. I could see the message in dev console:
```
Source map error: SyntaxError: JSON.parse: unexpected character at line 1 column 1 of the JSON data
Resource URL: http://35.196.228.78/static/js/2.bf1eb599.chunk.js
Source Map URL: 2.bf1eb599.chunk.js.map
```
On the network tab I could see the status 200 and correct response with greet intent:
```
Request URL:http://IPxxx/api/conversations/me
Request method:GET
Remote address:IPxxx
Status code: 200
```

**Comment by erohmensing** [comment]
Looks like maybe a little more error msg about that `bf1eb599.chunk.js.map` [here](https://forum.rasa.com/t/rasa-x-error/12633) -- its JS so probably a @gausie thing

**Comment by gausie** [comment]
The .js.map issue is not a terminal error

**Comment by alvisGTJ** [comment]
@erohmensing, can we expect any updates on this issue soon?

**Comment by gausie** [comment]
Hey! We are aware of the issue where sometimes you have to refresh the conversation to see new messages. We have a fix waiting for a few extra parts to slot in place and will be releasing it soon.

My quick message about a terminal error before was partly because I misunderstood the issue!

**Comment by alvisGTJ** [comment]
@gausie - thank you!

**Comment by TatianaParshina** [comment]
I have updated the latest version of Rasa X on Google Cloud using install.sh [script](https://storage.googleapis.com/rasa-x-releases/latest/install.sh). The issue is resolved there. I don't need to refresh the page after every bot reply now.
Thank you!
