### ISSUE TITLE
refactor _copy_files_to_new_dir to always delete tmp directories

### ISSUE THREAD

**Issue by erohmensing** [RasaHQ/rasa#3944]
We currently avoid temp directories in `rasa train` commands by making sure that each of the different functions in training delete all temporary files upon exiting. However this isn’t super scalable, as we would also have to do the same for `rasa data`, `rasa interactive`, `rata test`, etc. commands. Instead we should refactor the method that actually creates these directories. 

From @federicotdn:

> The problem comes from the usage of function _copy_files_to_new_dir in rasa/data.py. The function you mentioned, get_core_nlu_directories, uses this function, and other do as well.

> A call to these functions in data.py implies creating a temp directory and returning some path relative to it. The definitive solution to the problem would be making _copy_files_to_new_dir return a context manager and then change all uses of the functions in data.py to enter/exit the context manager appropriately.

**Comment by federicotdn** [comment]
A valid way to do this would be changing `_copy_files_to_new_dir` to return a `TempDirectoryPath` (once https://github.com/RasaHQ/rasa/pull/3887 is merged), and then slowly change the rest of the codebase to use the return value as a context manager. `TempDirectoryPath` can also be used as a regular string, so nothing should break after changing this.

**Comment by wochinge** [comment]
I am probably tackling this here https://github.com/orgs/RasaHQ/projects/25. So please wait with this issue @federicotdn

**Comment by wochinge** [comment]
I think we still have to do this for interactive learning. `train` should be fixed

**Comment by wochinge** [comment]
I'll close this as it didn't come up again and we can just re-open it in case it becomes a problem again.

**Comment by wochinge** [comment]
Reopening this due to this [forum thread](https://forum.rasa.com/t/rasa-is-slowly-filling-disk-space/36583/3)

**Comment by Chichidimo** [comment]
Any solution to this?

**Comment by erohmensing** [comment]
@wochinge I think the forum issue that re-opened this one was resolved by [this one](https://github.com/RasaHQ/rasa/pull/6925) right? does it still make sense to keep this one?

**Comment by erohmensing** [comment]
Hm, good point, I'm not sure. It does say "on my server" and the logs of their action server look like they could come from docker-compose

**Comment by wochinge** [comment]
Fine to close this with the model architecture revamp in my opinion.
