### ISSUE TITLE
Restrict the scope of a synonym to a specific entity

### ISSUE THREAD

**Issue by msamogh** [RasaHQ/rasa#3946]
**Description of Problem**:

When a word's synonyms are defined in the NLU training data, any occurrence of the synonyms are replaced by that word with no regard to what entity it has been recognized as. Essentially, two words that are synonyms in the context of one entity need not necessarily be synonyms in the context of another entity. This can *especially* be a problem when the volume of NLU training data is large and such conflicts are not easily visible.

**Overview of the Solution**:

There are currently two ways to define synonyms.
```md
<!-- First -->
## intent:mention_expertise
- [machine learning](expertise:ML)

<!-- Second -->
## intent:mention_expertise
- machine learning

## synonym:ML
- machine learning
```
While defining synonyms using the first syntax, the current behavior is completely unintuitive since there's nothing to indicate that it might apply outside the entity to which it has been attached to. With the second syntax, however, the global nature of synonym-mapping is more obvious.

Proposed solution 1: If syntax 1 is used, perform synonym mapping just for that entity. If syntax 2 is used, perform global synonym mapping.

Proposed solution 2: Another alternative could be to list the synonyms to use under an entity in the domain file.

**Examples:**

Example 1:

```md
## intent:inform
- My name is [Indiana](fname) Jones
- I am from [Indiana](state:IN)
- i come from [indiana](state:IN)
- The name's Jones. [Indiana](fname) Jones.
- My state is [IN](state)
```
With the above snippet in the training data, if you type in `"My name is Indiana Jones"`, the slot value for `fname` would be set to `"IN"`.

Example 2:
```md
## intent:find_a_professional
- find a [doctor](professional) for me
- get me a [doctor](professional)
- pls find me a [dr](professional:doctor)

## intent:inform_salutation
- [Mrs](salutation)
- Preferred one is [Dr](salutation)
- Use [Mr](salutation)
```
Similarly, there'll be an unintended replacement of "Dr" in the second case.

**Blockers** (if relevant): Might be a breaking change for cases where syntax 1 is deliberately used for global definitions of synonyms.

**Comment by amn41** [comment]
cc @tabergma

**Comment by TyDunn** [comment]
Will this still be the case when support for synonyms has been added to Rasa X?

**Comment by amn41** [comment]
yes this will still be the case.

I see this could be an issue in theory but has this ever actually happened?

**Comment by TyDunn** [comment]
My guess is that it very rarely, if ever, happens. Have you come across this @msamogh?

The current designs for synonyms in Rasa X will make it appear like synonyms are defined for each entity though

**Comment by wochinge** [comment]
So that's a `won't do` for now @TyDunn @amn41 @tabergma  ?

**Comment by TyDunn** [comment]
@wochinge I think we have leave it as `unplanned` for now until we get some more feedback on this problem

**Comment by alwx** [comment]
Closing it due to inactivity and lack of feedback.

**Comment by kormoczi** [comment]
I would like to re-open this issue, because I think this is still a problem (at least I do not know how to solve it).
Is there any solution for / progress on this issue?

**Comment by FrankKnighty** [comment]
> My guess is that it very rarely, if ever, happens. Have you come across this @msamogh?

I am just trying to convert my bot from another NLU system, and this issue makes it nearly impossible. I would say it's not theoretical at all.

I support kormoczi's request to re-open this ticket, unless someone can confirm it has been solved with Rasa X.
