### ISSUE TITLE
Soft reset while maintaining slot values

### ISSUE THREAD

**Issue by ortsaCniveK** [RasaHQ/rasa#3949]
**Description of Problem**:

For [projects](https://forum.rasa.com/t/any-way-to-set-a-story-at-the-beginning-of-every-training-story-or-soft-reset-a-user-message/12567?u=nivek) that require starting actions that set slots on page load and is used for slot-based conditional utterances down the line, this would be useful as it would improve detection by removing a utility custom action that shouldn't really affect conversation history.

This is especially useful, while the MappingPolicy helps some, returning `UserUtteranceReverted()` at the end undoes the side effects of the action as well, thereby nullifying any slot set events.

If you return `UserUtteranceReverted()` first before `SlotSet` or `FollowUpAction` events, you can approach this sort of behavior, but it would be best to scrub the bot actions from the history as well, as that would just remove the triggering user intent.

**Overview of the Solution**:

Create a new event called `RevertConversation` or `RewindConversation` where the conversation history is reverted, but the slot state is preserved.  May need to use something similar to the dialogue state tracker's `travel_back_in_time()` method.

**Definition of Done**:
- [ ] Tests are added for `RewindConversation`
- [ ] `RewindConversation` is implemented to meet tests, modeled after `travel_back_in_time`
- [ ] `RewindConversation` is added to the Event docs

**Comment by akelad** [comment]
Hi @ortsaCniveK thanks for the suggestion. I'm not 100% clear in what kind of situations you would want this to happen, could you provide a more detailed example? The example with UserUtteranceReverted -- there I don't understand why you would want to keep the slots that were set by the user

**Comment by ortsaCniveK** [comment]
Essentially, I'd like to have a soft-reset that maintains slots.  My bot has conditional utterances that are triggered based on slots, but I'd like to remove the welcome action I have set up to fill those slots from the tracker history as it shouldn't affect conversation prediction.

Let me know if that clarifies :)

**Comment by akelad** [comment]
i'm still not sure i understand. For me this feature doesn't really make sense, what exactly are you trying to do by resetting the tracker history but not the slots? Maybe an example of an interaction would help

**Comment by ortsaCniveK** [comment]
Sure.

## Basic user story

> User opens chat, which triggers a message to be sent to rasa with a slash command like "/welcome"
> Rasa processes that intent and sets slots based on a user profile, time of day, location, etc.

`Bot: Welcome! I can help with all your booking needs 😄`

> Soft reset happens here to simply remove that action from the tracker history while keeping slot values to allow for marginally better detection 

`User: Hello, can you help me book a flight from SFO to BER?`

> conversation continues as normal

**Comment by akelad** [comment]
Ok so the underlying issue is about action prediction -- I think the `AugmentedMemoizationPolicy` may help you here, along with separating your stories out into shorter blocks, so e.g. having a short one turn story for welcome, and then another one for booking

I'm gonna close this issue as I don't think we'll be implementing something like what was described in the original issue

**Comment by ortsaCniveK** [comment]
Sorry, can't find information about the `AugmentedMemoizationPolicy` anywhere in the docs; is that related to [data augmentation](https://rasa.com/docs/rasa/core/policies/#data-augmentation) in general?

**Comment by akelad** [comment]
yeah sorry we're gonna be adding that to the documentation soon. In the meantime you can take a look at this forum post: https://forum.rasa.com/t/policies-and-stories-problem/12779/2 
In other words, no it doesn't relate to data augmentation
