### ISSUE TITLE
Broken links in your documentation

### ISSUE THREAD

**Issue by boqnognqnov** [RasaHQ/rasa#3952]
Hello,
Today I found some broken links in your documentation. I think everything was fine yesterday.
1. https://rasa.com/docs/rasa/rasa-x/  -> 404

2. I attached links to the issue:
https://prnt.sc/obsfen
https://prnt.sc/obsfw2

3. starter-pack-rasa-nlu -> 404
https://github.com/RasaHQ/starter-pack-rasa-nlu

**Comment by erohmensing** [comment]
Hey @boqnognqnov! Thanks for pointing these out. Number 3 is indeed newly broken, as we've deprecated that repo, so we should remove that from the documentation. Number 1 looks like a bad link, the correct should be https://rasa.com/docs/rasa-x. As for number 2, that seems to be an issue connecting to the server on which we host the interactive tutorials. 

Could you please let me know what pages you found links #1 and #3 on?

**Comment by boqnognqnov** [comment]
I attached a file related to #1.
About #3, obviously it is not a real issue because I tried to open one of
my stored bookmarks in my browser.
Thank you!

**Comment by erohmensing** [comment]
Hi, I don't think attachments to emails make it into the github threads unfortunately -- just a link to the docs page in the reply, or even the name of the page in the docs would be fine :) thanks!

**Comment by boqnognqnov** [comment]
Oh, yes. I'm sorry
This is the screenshot url: https://prnt.sc/obzki1

This is on page: https://rasa.com/docs/rasa/user-guide/rasa-tutorial/
The button "Try Rasa X" bellow on the page

**Comment by erohmensing** [comment]
Awesome, thanks! Would you be interested in contributing a PR to fix that broken link? Here’s the file you’d have to change (the button path at the bottom): https://github.com/RasaHQ/rasa/blob/master/docs/user-guide/rasa-tutorial.rst
