### ISSUE TITLE
Include favicon for Rasa docs pages

### ISSUE THREAD

**Issue by msamogh** [RasaHQ/rasa#3954]
We can include the favicon that's used for the homepage.

**Comment by akelad** [comment]
what do you mean?

**Comment by erohmensing** [comment]
@samsucik pointed this out too, the little icon in your tab:
<img width="475" alt="Screenshot 2019-07-08 at 14 14 44" src="https://user-images.githubusercontent.com/22333512/60809364-c984e780-a18a-11e9-86cb-154d7aa50681.png">

**Comment by akelad** [comment]
ah ok! not sure how one goes about this, is that a docs thing or something more fancy?

**Comment by erohmensing** [comment]
my guess is this is something @eliseboyd might know more about

**Comment by eliseboyd** [comment]
ah, I'm surprised it's not set up already. yes, it looks like there's a theme setting. I just opened this which should fix it https://github.com/RasaHQ/rasabaster/pull/43
