### ISSUE TITLE
Run a story end-to-end in *Talk* mode in Rasa x

### ISSUE THREAD

**Issue by psds01** [RasaHQ/rasa#3955]
**Description of Problem**:

I would like to run a story end-to-end in either `Talk` mode or `Interactive Learning`. I am currently testing out my bot and some of the features I want to test for are at the very end of the story. I would like to run a story or part of a story end-to-end.

**Overview of the Solution**:

1.  Select a story or part of the story
2.  Show a button which says "run selected part as a new/independent story".
3.  It will run the selected part again, with scope for continuing the conversation after that.

**Examples** (if relevant):

**Blockers** (if relevant):

**Definition of Done**:

**Comment by akelad** [comment]
Thanks for submitting this feature request, we'll discuss this and get back to you

**Comment by alexweidauer** [comment]
Thank you for raising this issue about Rasa X. We decided to stop supporting the Community Edition (free version) of ‘Rasa X’ (see more info here: https://rasa.com/blog/rasa-x-community-edition-changes/). That’s why we’ve closed your issue. We suggest that Rasa Enterprise customers raise the issue with our customer support team if they haven’t done so already.
