### ISSUE TITLE
_GenericHTTPChannelProtocol,3,192.168.50.26  error in twisted defer.py

### ISSUE THREAD

**Issue by weizhenzhao** [RasaHQ/rasa#3962]
**Rasa version**:Rasa NLU 0.13.8 

**Rasa X version** (if used & relevant):

**Python version**:Python 3.5

**Operating system** (windows, osx, ...):windows

**Issue**:
![image](https://user-images.githubusercontent.com/13706689/60867337-2f41a400-a25d-11e9-9ac1-ab4483e29913.png)
![image](https://user-images.githubusercontent.com/13706689/60867527-a840fb80-a25d-11e9-9bf0-defc8cae1fe1.png)

I met an error after finishing online trainning the rasa model calling train api,
and when I call the parse apithe server will report the error as above

I also find an issue report on the rasa forum
https://forum.rasa.com/t/rasa-nlu-server-not-stable/4864/5
it seems not solved yet

Thanks
Weizhen

**Comment by akelad** [comment]
@weizhenzhao any chance you can try this with the newer version of Rasa 1.0? Or even Rasa NLU 0.15.x, I'm afraid this old version may have some bugs

**Comment by weizhenzhao** [comment]
dear @akelad 

sorry, I correct my version , my rasa version is 3.1

thanks
weizhen

**Comment by akelad** [comment]
what version is 3.1? that version doesn't exist
