### ISSUE TITLE
Passing policy configuration parameters to `agent.train(...)` is not supported anymore

### ISSUE THREAD

**Issue by capgos17** [RasaHQ/rasa#3974]
I have the code from [rasa  pyData conference](https://www.youtube.com/watch?v=S2LO08QRPSI&t=2757s)

from rasa_core.policies import KerasPolicy, MemoizationPolicy
from rasa.core.agent import Agent

agent = Agent('domain.yml',
              policies=[MemoizationPolicy(max_history=5),
                        KerasPolicy()])
training_data = agent.load_data('stories.md')

agent.train(
    training_data,
    validation_split=0.0,
    epochs=200
)

agent.persist('models/dialogue')

I'm getting the error that agent.train isn't supported anymore. @JustinaPetr please help
#Error 
Passing policy configuration parameters to `agent.train(...)` is not supported anymore. Specify parameters directly in the policy configuration instead. More info http://legacy-docs.rasa.com/core/migrations.html

**Comment by akelad** [comment]
Please ask these kind of questions in our [forum](https://forum.rasa.com)
