### ISSUE TITLE
Add `sender_id` argument shell and interactive command line tools

### ISSUE THREAD

**Issue by djwessel** [RasaHQ/rasa#3975]
**Description of Problem**:

Both `rasa shell` and `rasa interactive` do not support the ability to set the `sender_id` field. Instead for shell, the `sender_id` is just set to the default value of `default`, where as for interactive, the field is set to a uuid. To test stories/run interactive learning with custom actions that rely on the `sender_id` field value, the current tools lack the ability to customize this field. 

**Overview of the Solution**:

A straightforward solution would be to add a `--sender_id` command line argument to `rasa shell` and `rasa interactive`. This argument would then be passed to the respective `record_messages` function, which already supports the `sender_id` parameter.

Furthermore, the default value for this argument should not change the functionality of the current implementation (shell defaults to `default` and interactive defaults to a uuid).

**Examples** (if relevant):

An example of a custom action that would rely on the value of the `sender_id` is as follows.
```python
import logging

from rasa_sdk import Action

logger = logging.getLogger(__name__)

class ActionLogSenderId(Action):

  def name(self):
    return "action_log_sender_id"

  def run(self, dispatcher, tracker, domain):
    logger.info("Sender id: {}".format(tracker.sender_id))
```

Currently, when running `rasa shell`, the logged value would be `Sender id: default`, whereas when running `rasa interactive`, the logged value would be `Sender id: {some random uuid.uuid4().hex}`. 

With the proposed change, when the user runs `rasa shell --sender_id unique123` or `rasa interactive --sender_id unique123`, the logged value would be `Sender id: unique123`

**Blockers** (if relevant):

None

**Definition of Done**:

- [ ] Tests are implemented for shell and interactive.
- [ ] The `--sender_id` argument is implemented and meets tests.
- [ ] The `--sender_id` argument is added to the Command Line Interface docs for both shell and interactive.

**Comment by akelad** [comment]
Can I ask why you would need this though? What would you need to test with respect to the sender id in interactive learning or when just chatting to the bot?

**Comment by djwessel** [comment]
Hey, similar to the custom `FetchProfileAction` action in the docs [here](https://rasa.com/docs/rasa/core/slots/#slots-set-by-actions), we use the `sender_id` to fetch information about the user, which then sets a slot which is used to inform the following actions to take. In order to use interactive learning, or even just chat with the bot using the shell, we need to be able to customize the `sender_id`.

**Comment by akelad** [comment]
You could probably use some dummy information for the default sender id for testing. I'll discuss this enhancement with our team though and let you know whether we think it makes sense to add

**Comment by sjtilney** [comment]
Not having the ability to set the sender_id at run time has also caused a lot of headache for our team.
Our Rasa actions interact with many different REST services. Many of those services require a valid user id (sender_id) in order to get a successful response.
Furthermore, we expect different responses depending on the region that the user is in or preferences they may have set. It's impossible to test these cases without being able to change the sender_id on the go.

For example, if someone asks a bot, "when is the next holiday?" we would expect a different response for a user in Germany versus a user in the United States. The only way to test that these cases are working properly during interactive training is to change the sender_id to one associated with a user in the various countries.

**Comment by wochinge** [comment]
- for `rasa shell` I would add this configuration to the `credentials.yml` 
- for `rasa interactive` we can add a cli parameter as you suggested. An environment variables is probably to hidden

**Comment by djwessel** [comment]
@wochinge I should be able to set up a pull request in the next few days.

**Comment by wochinge** [comment]
@djwessel That's amazing! Thanks for proposing this, discussing and contributing 💯 Let me know if you need any help on the way (you can also tag me here and I can have a look at an early draft 👍 )

**Comment by DiegoProtec** [comment]
I need to pass ```sender_id``` to cmdline channel. It would be possible to adapt the param 'sender_id' on method 'record_messages' in 'console.py' as optional to receive the sender from credentials?

**Comment by wochinge** [comment]
@DiegoProtec Sorry, for the late response. I was on vacation.

> It would be possible to adapt the param sender_id on console.py as optional to receive the sender from credentials.yml?

Yes, that we would definitely be possible, but as I discussed with the team, the preferred solution would be to pass this information via the command line. Hence, I would suggest to add a parameter `sender_id` to `configure_app` and `serve_application` and then use this one in `record_messages`. Do you have any more thoughts on that @tabergma ?

**Comment by DiegoProtec** [comment]
Thank you, I solved this, passed this attribute in my tracker_store in my endpoints.yml, by the environment variable.
________________________________
De: Tobias Wochinger <notifications@github.com>
Enviado: sexta-feira, 13 de setembro de 2019 09:32
Para: RasaHQ/rasa <rasa@noreply.github.com>
Cc: Diego de Santana Fernandes <diegoprotec@hotmail.com>; Mention <mention@noreply.github.com>
Assunto: Re: [RasaHQ/rasa] Add `sender_id` argument shell and interactive command line tools (#3975)


@DiegoProtec<https://github.com/DiegoProtec> Sorry, for the late response. I was on vacation.

It would be possible to adapt the param sender_id on console.py as optional to receive the sender from credentials.yml?

Yes, that we would definitely be possible, but as I discussed with the team, the preferred solution would be to pass this information via the command line. Hence, I would suggest to add a parameter sender_id to configure_app and serve_application and then use this one in record_messages. Do you have any more thoughts on that @tabergma<https://github.com/tabergma> ?

**Comment by tabergma** [comment]
Adding a new parameter to the command line sound good 👍 However, I would name it `--sender-id` instead of `--sender_id` due to naming convention. Seems like a straight forward solution.

**Comment by wochinge** [comment]
@DiegoProtec Could you please clarify your solution a bit or share your pr? I think that would make it easier to discuss your changes :-)

**Comment by wochinge** [comment]
@DiegoProtec How is it going? Is there anything I can help you with?

**Comment by wochinge** [comment]
@DiegoProtec What's your current state? can I help you?

**Comment by wochinge** [comment]
hm, do you have a draft pr where I can have a look at the proposed changes? I think that would be easier for giving feedback.

**Comment by wochinge** [comment]
@DiegoProtec How is it going? If you don't have time, I'd assign it to one of my colleagues

**Comment by wochinge** [comment]
@ChristinaKoss When you start with it, I'd split in two PRs
- add sender id to `rasa interactive`
- add sender id to `rasa shell`

**Comment by wochinge** [comment]
@tmbo Should we use `conversation-id` or `sender-id` as parameter (in relation to this issue https://github.com/RasaHQ/rasa/issues/4683) ? I'd opt for sender-id since it's shorter

**Comment by tmbo** [comment]
as far as I know we always expose it as `sender id` in our storage formats / events / apis, so should stick with that (even though nowadays conversation-id is probably the more descriptive name...)

**Comment by wochinge** [comment]
The `rasa shell` part is handled by https://github.com/RasaHQ/rasa/pull/5117

**Comment by chkoss** [comment]
The `rasa interactive` part is done now (#5243)
