### ISSUE TITLE
train.py: error: one of the arguements -d/--data -u/url is required

### ISSUE THREAD

**Issue by ravikrcs** [RasaHQ/rasa#3978]
**Rasa version**:0.9.6    rasa nlu-0.12.3

**Rasa X version** (if used & relevant):

**Python version**:3.6

**Operating system** (windows, osx, ...):windows
![err1](https://user-images.githubusercontent.com/31586794/60963990-d727a200-a32f-11e9-90e3-121eebd46e4b.PNG)

**Issue**:

**Error (including full traceback)**:
```
![err1](https://user-images.githubusercontent.com/31586794/60964031-eeff2600-a32f-11e9-95d3-55a6fb05129f.PNG)

```

**Command or request that led to error**:
```

```

**Content of configuration file (config.yml)** (if relevant):
```yml

```

**Content of domain file (domain.yml)** (if relevant):
```yml

```

**Comment by ravikrcs** [comment]
while training this command it gives trai.py:error
python -m rasa_nlu.train -c config.json

**Comment by RanaMostafaAbdElMohsen** [comment]
Hi @ravikrcs ,
You propose to fix it by displaying a warning message instead of error, correct?

**Comment by akelad** [comment]
This is not a bug, you need to pass a training data file to your command
