### ISSUE TITLE
RuntimeError: Calling `rasa.core.train` directly is no longer supported.

### ISSUE THREAD

**Issue by RaufJavid** [RasaHQ/rasa#3980]
Hi, I am facing the following issue... May you please check it.

**RuntimeError: Calling `rasa.core.train` directly is no longer supported. Please use `rasa train` to train a combined Core and NLU model or `rasa train core` to train a Core model.**

PFA.
![Pakerror](https://user-images.githubusercontent.com/21277031/60972148-1e695f00-a33f-11e9-8636-a0864bcc6262.png)

**Comment by akelad** [comment]
Please ask these kind of questions in our [forum](https://forum.rasa.com)
