### ISSUE TITLE
Rasa Core train command in comparison mode not creating models in the format "model.tar.gz"

### ISSUE THREAD

**Issue by guillecarc** [RasaHQ/rasa#3983]
**Rasa version**: 1.1.4

**Python version**: 3.6

**Operating system**: macOS Mojave 10.14.5
**Issue**: the comparison mode for rasa core using `train` command does not create compressed models in the file extension "tar.gz".

**Error (including full traceback)**:
This is essentially the output stored in `core_comparison_results/` folder
<img width="1058" alt="Screen Shot 2019-07-10 at 11 06 39" src="https://user-images.githubusercontent.com/39458745/60983215-db58bd00-a339-11e9-835c-0327114dc7f8.png">

**Command or request that led to error**:
```rasa train core -c config/keras.yml config/embbeding.yml -d domain.yml -s data/100/stories.md --out core_comparison_results/ --runs 3 --percentages 0 25 50 75 95 --augmentation 10```

**Comment by akelad** [comment]
Thanks for spotting this bug! We'll look into fixing this

**Comment by wochinge** [comment]
also testing does not work properly https://github.com/RasaHQ/rasa/issues/4016
