### ISSUE TITLE
Broken link for "license scan" shield on README.md

### ISSUE THREAD

**Issue by federicotdn** [RasaHQ/rasa#3985]
When I click on [![FOSSA Status](https://app.fossa.com/api/projects/custom%2B8141%2Fgit%40github.com%3ARasaHQ%2Frasa.git.svg?type=shield)](https://app.fossa.com/projects/custom%2B8141%2Fgit%40github.com%3ARasaHQ%2Frasa.git?ref=badge_shield) in README.md, I get a "404 Project not found" page.

**Comment by nike47** [comment]
Can I work on this?
