### ISSUE TITLE
No matching distribution found for aiohttp~=3.5 (from rasa-x)

### ISSUE THREAD

**Issue by prasannaonchip** [RasaHQ/rasa#3987]
i am also getting the same error
i used python version is 3.5.2
pip uninstall rasa-x --extra-index-url https://pypi.rasa.com/simple

Error is

Collecting rasa-x
Downloading https://pypi.rasa.com/api/package/rasa-x/rasa-x-0.19.5.tar.gz (1.8MB)
|████████████████████████████████| 1.8MB 1.7MB/s
Installing build dependencies ... done
Getting requirements to build wheel ... done
Preparing wheel metadata ... done
Collecting simplejson~=3.16 (from rasa-x)
Downloading https://files.pythonhosted.org/packages/e3/24/c35fb1c1c315fc0fffe61ea00d3f88e85469004713dab488dee4f35b0aff/simplejson-3.16.0.tar.gz (81kB)
|████████████████████████████████| 81kB 560kB/s
Collecting python-dateutil~=2.8 (from rasa-x)
Using cached https://files.pythonhosted.org/packages/41/17/c62faccbfbd163c7f57f3844689e3a78bae1f403648a6afb1d0866d87fbb/python_dateutil-2.8.0-py2.py3-none-any.whl
Collecting sanic~=19.3.1 (from rasa-x)
Downloading https://files.pythonhosted.org/packages/90/11/31382617b33f89df0caca396f104628d256689a58a63c75d3e46663a8c8f/sanic-19.3.1-py3-none-any.whl (60kB)
|████████████████████████████████| 61kB 349kB/s
Collecting pika~=1.0.0 (from rasa-x)
Downloading https://files.pythonhosted.org/packages/78/1a/28c98ee8b211be21d4a9f4ef1687c4d36f9302d47fcc28b81f9591abf6d8/pika-1.0.1-py2.py3-none-any.whl (148kB)
|████████████████████████████████| 153kB 828kB/s
Collecting mixpanel~=4.3 (from rasa-x)
Downloading https://files.pythonhosted.org/packages/26/c0/7f234cafdb19e515c62a17dd8ed27dba782b68a93790af659553f37b4496/mixpanel-4.4.0-py2.py3-none-any.whl
Collecting SQLAlchemy~=1.3.0 (from rasa-x)
Downloading https://files.pythonhosted.org/packages/62/3c/9dda60fd99dbdcbc6312c799a3ec9a261f95bc12f2874a35818f04db2dd9/SQLAlchemy-1.3.5.tar.gz (5.9MB)
|████████████████████████████████| 5.9MB 451kB/s
Collecting alembic~=1.0.10 (from rasa-x)
Downloading https://files.pythonhosted.org/packages/7b/8b/0c98c378d93165d9809193f274c3c6e2151120d955b752419c7d43e4d857/alembic-1.0.11.tar.gz (1.0MB)
|████████████████████████████████| 1.0MB 322kB/s
Collecting sanic-jwt~=1.3 (from rasa-x)
Downloading https://files.pythonhosted.org/packages/9a/14/451e1e1ad90fd12a3e2bb41dd7acdbee2865012d841f4a5455a82c2d255a/sanic-jwt-1.3.2.tar.gz
Collecting rasa~=1.1.0 (from rasa-x)
Downloading https://files.pythonhosted.org/packages/4f/17/96c26432b3968b0a6e08fba87661f7b22ee58c79d4c054a09b9f4f75b9f2/rasa-1.1.4-py3-none-any.whl (447kB)
|████████████████████████████████| 450kB 431kB/s
Collecting questionary>=1.1.0 (from rasa-x)
Downloading https://files.pythonhosted.org/packages/1e/e2/eda18deed2410a4ac243ad13e375d1f0023288e0872310164a772d09c622/questionary-1.1.1-py3-none-any.whl
Collecting sanic-cors~=0.9.6 (from rasa-x)
Downloading https://files.pythonhosted.org/packages/33/c3/a0f3448627e5aa8e085b34c51f2e12d8fa17f0d345836ff0e7f262fe7571/Sanic_Cors-0.9.8.post1-py2.py3-none-any.whl
Collecting apscheduler~=3.5 (from rasa-x)
Downloading https://files.pythonhosted.org/packages/93/09/ffc2ed85fa578cd0d4428e9c421407e5d91a4464bbaa44f789941416ae42/APScheduler-3.6.0-py2.py3-none-any.whl (58kB)
|████████████████████████████████| 61kB 758kB/s
Collecting isodate~=0.6.0 (from rasa-x)
Downloading https://files.pythonhosted.org/packages/9b/9f/b36f7774ff5ea8e428fdcfc4bb332c39ee5b9362ddd3d40d9516a55221b2/isodate-0.6.0-py2.py3-none-any.whl (45kB)
|████████████████████████████████| 51kB 669kB/s
Collecting jsonschema~=2.6.0 (from rasa-x)
Downloading https://files.pythonhosted.org/packages/77/de/47e35a97b2b05c2fadbec67d44cfcdcd09b8086951b331d82de90d2912da/jsonschema-2.6.0-py2.py3-none-any.whl
Collecting pyjwt (from rasa-x)
Downloading https://files.pythonhosted.org/packages/87/8b/6a9f14b5f781697e51259d81657e6048fd31a113229cf346880bb7545565/PyJWT-1.7.1-py2.py3-none-any.whl
Collecting requests~=2.22 (from rasa-x)
Downloading https://files.pythonhosted.org/packages/51/bd/23c926cd341ea6b7dd0b2a00aba99ae0f828be89d72b2190f27c11d4b7fb/requests-2.22.0-py2.py3-none-any.whl (57kB)
|████████████████████████████████| 61kB 905kB/s
Collecting aiohttp~=3.5 (from rasa-x)
ERROR: Could not find a version that satisfies the requirement aiohttp~=3.5 (from rasa-x) (from versions: 0.1, 0.2, 0.3, 0.4, 0.4.1, 0.4.2, 0.4.3, 0.4.4, 0.5.0, 0.6.0, 0.6.1, 0.6.2, 0.6.3, 0.6.4, 0.6.5, 0.7.0, 0.7.1, 0.7.2, 0.7.3, 0.8.0, 0.8.1, 0.8.2, 0.8.3, 0.8.4, 0.9.0, 0.9.1, 0.9.2, 0.9.3, 0.10.0, 0.10.1, 0.10.2, 0.11.0, 0.12.0, 0.13.0, 0.13.1, 0.14.0, 0.14.1, 0.14.2, 0.14.3, 0.14.4, 0.15.0, 0.15.1, 0.15.2, 0.15.3, 0.16.0, 0.16.1, 0.16.2, 0.16.3, 0.16.4, 0.16.5, 0.16.6, 0.17.0, 0.17.1, 0.17.2, 0.17.3, 0.17.4, 0.18.0, 0.18.1, 0.18.2, 0.18.3, 0.18.4, 0.19.0, 0.20.0, 0.20.1, 0.20.2, 0.21.0, 0.21.1, 0.21.2, 0.21.4, 0.21.5, 0.21.6, 0.22.0a0, 0.22.0b0, 0.22.0b1, 0.22.0b2, 0.22.0b3, 0.22.0b4, 0.22.0b5, 0.22.0b6, 0.22.0, 0.22.1, 0.22.2, 0.22.3, 0.22.4, 0.22.5, 1.0.0, 1.0.1, 1.0.2, 1.0.3, 1.0.5, 1.1.0, 1.1.1, 1.1.2, 1.1.3, 1.1.4, 1.1.5, 1.1.6, 1.2.0, 1.3.0, 1.3.1, 1.3.2, 1.3.3, 1.3.4, 1.3.5, 2.0.0rc1, 2.0.0, 2.0.1, 2.0.2, 2.0.3, 2.0.4, 2.0.5, 2.0.6, 2.0.6.post1, 2.0.7, 2.1.0, 2.2.0, 2.2.1, 2.2.2, 2.2.3, 2.2.4, 2.2.5, 2.3.0a1, 2.3.0a2, 2.3.0a4, 2.3.0, 2.3.1a1, 2.3.1, 2.3.2b2, 2.3.2b3, 2.3.2, 2.3.3, 2.3.4, 2.3.5, 2.3.6, 2.3.7, 2.3.8, 2.3.9, 2.3.10, 3.0.0b0)
ERROR: No matching distribution found for aiohttp~=3.5 (from rasa-x)

**Comment by Sarvin92** [comment]
I am also getting the same error @prasannaonchip
I am using python version == 3.7.4
I have tried to install 'aiohttp' separately using pip install aiohttp, but it has been failed to install. In the official installation website of aiohttp, it has shown that the latest version is aiohttp == 3.5.4, in the error it shows the distribution version of aiohttp only upto 3.0.0b0

**Comment by prasannaonchip** [comment]
but it is installed in python version == 3.6.8

**Comment by Sarvin92** [comment]
This problem has solved for me by installing python == 3.7.4 (64-bit), which has suggested in the provided link (https://stackoverflow.com/questions/38896424/tensorflow-not-found-using-pip?page=1&tab=votes#tab-top)
Though it meant for the installation problems for tensorflow, it worked for me @prasannaonchip

**Comment by akelad** [comment]
yeah python versions below 3.5.3 are unsupported i'm afraid
