### ISSUE TITLE
Feature enhancement: Inclusion of max_connection setter in rasa core

### ISSUE THREAD

**Issue by guilherme-mendes** [RasaHQ/rasa#3992]
Rasa NLU version: 0.13.4

When the construction of rasa is made the max connection is automatically set to 40 connections with webhook with this it is necessary to set in the webhook the number of maximum connections manually in the webhook url (using Telegram).

**Comment by guilherme-mendes** [comment]
For instance:

``https://api.telegram.org/bot123456:ABC-DEF1234ghIkl-zyx57W2v1u123ew11/setWebhook?url=https://www.example.com/my-telegram-bot``

You should see something like this:

``{
 "ok":true,
 "result": 
 {
   "url":"
https://www.example.com/my-telegram-bot/",
   "has_custom_certificate":false,
   "pending_update_count":0,
   "max_connections":40
 }
}``

Setting the number of connections preventing the application from dropping by code.

**Comment by akelad** [comment]
hi @guilherme-mendes thanks for bringing this up -- rasa nlu is unmaintaned right now, so do you think you could try with the latest rasa==1.1.5 and let me know if this is still an issue?
