### ISSUE TITLE
weightless docker image

### ISSUE THREAD

**Issue by tormath1** [RasaHQ/rasa#3995]
**Description of Problem**: `rasa/rasa` image is big (~1.3GB). I'm trying to shrink the image, would you be interested if the weight difference is important ? 

**Overview of the Solution**: build requirements from scratch on an alpine image and remove non-necessary runtime system dependencies

**Examples** (if relevant):

**Blockers** (if relevant):

**Definition of Done**:

- [ ] install scipy / openblas https://github.com/scipy/scipy/issues/9481#issuecomment-510540522
- [ ] install tensorflow / bazel
- [ ] clean up non-necessary runtime dependencies once builded

**Comment by akelad** [comment]
@tormath1 sure, that would be interesting to see. Not sure how many of the requirements you can actually get rid of. Is this something you want to test out yourself?

**Comment by tormath1** [comment]
Yes, totally. I would be glad to share the result with you !

**Comment by wochinge** [comment]
@tormath1 Thanks for your offer! Could you please also check with https://github.com/RasaHQ/rasa/pull/3332 ? In this pr I'm trying to achieve the same :-) Let me know if you have suggestions!

**Comment by wochinge** [comment]
@tormath1 One more question:
Building tensorflow from scratch in an alpine image is quite tedious. Don't you think the resulting image definition would be quite complex / hard to maintain?

**Comment by tormath1** [comment]
@wochinge, well I guess I won't be harder than any dependencies. Actually, tf should release an Alpine wheel. :sweat_smile: 
Building dependencies from sources could optimize built wheels as we are compiling through GCC. I'll let you know how's going. 
Good work for your slim image. :+1:

**Comment by wochinge** [comment]
> This is my first stage:

Do you have some estimates regarding the image size?

**Comment by kronos-cm** [comment]
Hi guys, I have already built an alpine version and the estimated size is a bit under 2G decompressed as opposed to the 2.7G from rasa/rasa:latest-full. I think it's not a huge reduction and definitely not worth the build time if it's just for space optimization, however, there are other arguments in favor of alpine based images, particularly for enterprises. In our case, our private registry vulnerability scan complains about anything but alpine and from scratch. Too paranoid? Maybe, as I say it takes about an hour to build on CI/CD runners.

**Comment by wochinge** [comment]
@kronos-cm seems about the space reduction I got in https://github.com/RasaHQ/rasa/pull/3332

**Comment by HariTeneti** [comment]
> Hi guys, I have already built an alpine version and the estimated size is a bit under 2G decompressed as opposed to the 2.7G from rasa/rasa:latest-full. I think it's not a huge reduction and definitely not worth the build time if it's just for space optimization, however, there are other arguments in favor of alpine based images, particularly for enterprises. In our case, our private registry vulnerability scan complains about anything but alpine and from scratch. Too paranoid? Maybe, as I say it takes about an hour to build on CI/CD runners.

@kronos-cm: We are running into the same vulnerability scan issues and most of the issues are around Debian OS. I am trying to built on alpine version. It seems you were able to successfully built BOT Servers on alpine. Could you please share your docker file. Thank you.

**Comment by kronos-cm** [comment]
Hi @HariTeneti, yes, we were able to do it compiling tf==1.14 from scratch with bazel, and rasa=1.2.3. Unfortunately, per my contract, I am not able to share any files publicly, though I would love to I've you a hand if possible.
