### ISSUE TITLE
Print out "Failed stories written to results/failed_stories.md" at the end of running rasa test core

### ISSUE THREAD

**Issue by msamogh** [RasaHQ/rasa#3998]
There's no message indicating if/where the `failed_stories.md` has been saved.

**Comment by nike47** [comment]
I am new to open source would really like to work on an issue, and I think this is a good one. So can I work on this?

**Comment by msamogh** [comment]
@nike47 Absolutely! Please let us know if you need any help along the way.

**Comment by Henrike100** [comment]
Is someone working on this issue?
I'm new to Rasa community and code contribution. Can I work on this?
