### ISSUE TITLE
I need to implement Bot Thinking Indicator

### ISSUE THREAD

**Issue by nikhilkapavarapu** [RasaHQ/rasa#4007]
In my chatbot, I want to have "thinking indicator" (similar to typing animation we see while messaging)  so that user knows Bot is actually functioning if it is taking more time to respond.

I want that indicator to be displayed just above the input text box.
If the bot returns with response, then i want that indicator animation to be cleared off from the chat window.

How do we implement this functionality in RASA?. Do we have any in-built function for that ?

**Comment by erohmensing** [comment]
Hi @nikhilkapavarapu, this is completely dependent on whether your output channel supports this, so there is no built-in function for this. This is something you would e.g. configure in a custom output channel. Please ask questions like this on the [forum](http://forum.rasa.com).
