### ISSUE TITLE
Have the validator dump data errors to file

### ISSUE THREAD

**Issue by MetcalfeTom** [RasaHQ/rasa#4011]
**Description of Problem**:
`rasa data validate` only prints data errors to shell

**Overview of the Solution**:
Would be nice to dump to a file so users can begin iterating on their data.  Or append them to the current data files somehow.

**Definition of Done**:
- [x] Tests are added
- [x] Feature is documented

**Comment by gabibguedes** [comment]
Hi @MetcalfeTom I've opened a PR for this issue.
