### ISSUE TITLE
"No model found" error message when model was loaded correctly

### ISSUE THREAD

**Issue by federicotdn** [RasaHQ/rasa#4012]
**Rasa version**: `1.1.6`

**Python version**: `3.7.4`

**Operating system** (windows, osx, ...): macOS Mojave

**Issue**:
After creating a new project using `rasa init --no-prompt`, and running `rasa shell`, the bot is loaded correctly and it can respond correctly to my messages. However, after I use the `/stop` command to quit, an error message appears saying that no model could be loaded.

**Error (including full traceback)**:
```shell
2019-07-15 15:41:56 INFO     root  - Connecting to channel 'cmdline' which was specified by the '--connector' argument. Any other channels will be ignored. To connect to all given channels, omit the '--connector' argument.
2019-07-15 15:41:56 INFO     root  - Starting Rasa Core server on http://localhost:5005
Bot loaded. Type a message and press enter (use '/stop' to exit):
Your input ->  hello
Hey! How are you?
Your input ->  /stop
2019-07-15 15:42:03 INFO     root  - Killing Sanic server now.

No model found. You have three options to provide a model:
1. Configure a model server in the endpoint configuration and provide the configuration via '--endpoints'.
2. Specify a remote storage via '--remote-storage' to load the model from.
3. Train a model before running the server using `rasa train` and use '--model' to provide the model path.
For more information check https://rasa.com/docs/rasa/user-guide/running-the-server/.
```

**Command or request that led to error**:
```
rasa shell
```

**Comment by federicotdn** [comment]
Initial fix: in function `run()` in `rasa/cli/run.py`, add a `return` statement after each call to `rasa.run(**vars(args))`.

**Comment by Mayankgbrc** [comment]
Hi, I'm getting the same error, Where to find the folder rasa/cli/ ?

**Comment by federicotdn** [comment]
Hey @Mayankgbrc I was referring to the file in the library, not in users' projects (https://github.com/RasaHQ/rasa/blob/master/rasa/cli/run.py).

**Comment by Mayankgbrc** [comment]
My run.py file in the rasa/cli/ directory looks like this.


`import argparse
import logging
import os
from typing import List, Text
from rasa.cli.arguments import run as arguments
from rasa.cli.utils import get_validated_path, print_error
from rasa.constants import (
    DEFAULT_ACTIONS_PATH,
    DEFAULT_CREDENTIALS_PATH,
    DEFAULT_ENDPOINTS_PATH,
    DEFAULT_MODELS_PATH,
    DOCS_BASE_URL,
)
from rasa.exceptions import ModelNotFound

logger = logging.getLogger(__name__)


# noinspection PyProtectedMember
def add_subparser(
    subparsers: argparse._SubParsersAction, parents: List[argparse.ArgumentParser]
):
    run_parser = subparsers.add_parser(
        "run",
        parents=parents,
        conflict_handler="resolve",
        formatter_class=argparse.ArgumentDefaultsHelpFormatter,
        help="Starts a Rasa server with your trained model.",
    )
    run_parser.set_defaults(func=run)

    run_subparsers = run_parser.add_subparsers()
    sdk_subparser = run_subparsers.add_parser(
        "actions",
        parents=parents,
        conflict_handler="resolve",
        formatter_class=argparse.ArgumentDefaultsHelpFormatter,
        help="Runs the action server.",
    )
    sdk_subparser.set_defaults(func=run_actions)

    arguments.set_run_arguments(run_parser)
    arguments.set_run_action_arguments(sdk_subparser)


def run_actions(args: argparse.Namespace):
    import rasa_sdk.__main__ as sdk

    args.actions = args.actions or DEFAULT_ACTIONS_PATH

    path = args.actions.replace(".", os.sep) + ".py"
    _ = get_validated_path(path, "action", DEFAULT_ACTIONS_PATH)

    sdk.main_from_args(args)


def _validate_model_path(model_path: Text, parameter: Text, default: Text):

    if model_path is not None and not os.path.exists(model_path):
        reason_str = "'{}' not found.".format(model_path)
        if model_path is None:
            reason_str = "Parameter '{}' not set.".format(parameter)

        logger.debug(
            "{} Using default location '{}' instead.".format(reason_str, default)
        )

        os.makedirs(default, exist_ok=True)
        model_path = default

    return model_path


def run(args: argparse.Namespace):
    import rasa.run

    args.endpoints = get_validated_path(
        args.endpoints, "endpoints", DEFAULT_ENDPOINTS_PATH, True
    )
    args.credentials = get_validated_path(
        args.credentials, "credentials", DEFAULT_CREDENTIALS_PATH, True
    )

    if args.enable_api:
        if not args.remote_storage:
            args.model = _validate_model_path(args.model, "model", DEFAULT_MODELS_PATH)
        rasa.run(**vars(args))
        return

    # if the API is not enable you cannot start without a model
    # make sure either a model server, a remote storage, or a local model is
    # configured

    from rasa.model import get_model
    from rasa.core.utils import AvailableEndpoints

    # start server if remote storage is configured
    if args.remote_storage is not None:
        rasa.run(**vars(args))
        return

    # start server if model server is configured
    endpoints = AvailableEndpoints.read_endpoints(args.endpoints)
    model_server = endpoints.model if endpoints and endpoints.model else None
    if model_server is not None:
        rasa.run(**vars(args))
        return

    # start server if local model found
    args.model = _validate_model_path(args.model, "model", DEFAULT_MODELS_PATH)
    local_model_set = True
    try:
        get_model(args.model)
    except ModelNotFound:
        local_model_set = False

    if local_model_set:
        rasa.run(**vars(args))
        return

    print_error(
        "No model found. You have three options to provide a model:\n"
        "1. Configure a model server in the endpoint configuration and provide "
        "the configuration via '--endpoints'.\n"
        "2. Specify a remote storage via '--remote-storage' to load the model "
        "from.\n"
        "3. Train a model before running the server using `rasa train` and "
        "use '--model' to provide the model path.\n"
        "For more information check {}.".format(
            DOCS_BASE_URL + "/user-guide/running-the-server/"
        )
    )`

Now there is no error but there is no response from the bot and also it exits the shell when I type a message.
Please have a look at the screenshot where I dont get back any message from the bot
![screenshot_rasa](https://user-images.githubusercontent.com/25427732/61274158-d461fc80-a7c8-11e9-8721-be0662abeb0b.png)

**Comment by Mayankgbrc** [comment]
Hi @federicotdn , thanks for the reply.
Once go through this link - mayankgbrc.com/run.py to check my code. 
Still I'm getting this error.
![Screenshot from 2019-07-16 13-08-07](https://user-images.githubusercontent.com/25427732/61275101-ca40fd80-a7ca-11e9-8ec3-6217792f9a8b.png)

**Comment by federicotdn** [comment]
@Mayankgbrc thanks for trying that out. I'll be working today to see if I can solve this issue.
