### ISSUE TITLE
need a help to how add data for realconversation

### ISSUE THREAD

**Issue by prasannaonchip** [RasaHQ/rasa#4022]
## intent:current_matches
- which cricket match is happening right now 
- which ipl match is next 
- which teams are playing next in ipl 
- tell me some ipl news 
- i want ipl updates 
- what are the latest match updates 
- who won the last ipl match 
- how is ipl going 
- what was the result of the last match 
- when is the next match

i am giving this data in the file names as data/nlu.md

## news path 1
* greet
  - utter_greet
* current_matches
  - action_match_news
  - utter_did_that_help
* affirm or thanks
  - utter_gratitude
* goodbye
  - utter_goodbye

## news path 2
* current_matches
  - action_match_news
  - utter_did_that_help
* affirm or thanks
  - utter_gratitude
* goodbye
  - utter_goodbye

## news path 3
* greet
  - utter_greet
* current_matches
  - action_match_news
  - utter_did_that_help
* deny
  - utter_ask_again
* current_matches
  - action_match_news
  - utter_did_that_help
* affirm or thanks
  - utter_gratitude
* goodbye
  - utter_goodbye

## greet path
* greet
  - utter_greet

## goodbye path
* goodbye
  - utter_goodbye

i am  giving this data in the file named as data/stories.md

for  this data change my config.yml and domine.yml file 
please suggest me to how to add new data to rasa x tool 
and also how check for this data  with assistance .

please reply fast
thanks in adavnce.

**Comment by akelad** [comment]
Please ask these kind of questions in our [forum](https://forum.rasa.com)
