### ISSUE TITLE
NLU server - ParsingError

### ISSUE THREAD

**Issue by tbx0912** [RasaHQ/rasa#4024]
**Rasa version**: Rasa 1.1.4

**Python version**: Python 3.6.9

**Operating system**: Ubuntu Bionic (18.04)

**Docker version**: 18.09.7, build 2d0083d

**Issue**:
I want to use the NLU only with the latest Rasa version in a Docker container. I followed the instructions given in the [Rasa docs](https://rasa.com/docs/rasa/nlu/using-nlu-only/). 
The training is OK, running the server without error too.

The issue appears when I try to reach the "/model/parse" endpoint on the NLU server to get predictions.
If the cURL command is executed locally (on the machine which runs the container), everything runs smoothly (this behavior is strange by the way, why is it different from a call from a remote machine?).

Example of a working request and its answer:
```
curl -XPOST http://xx.xx.xx.xx:pppp/model/parse -d '{"text":"Hello"}'
{"intent":{"name":"greet","confidence":0.9316552877},"entities":[],"intent_ranking":[...],"text":"Hello"}
```

On the other hand, when I try to call the NLU server remotely, I get the following error:

**Error**:
```
{"version":"1.1.4","status":"failure","message":"An unexpected error occurred. Error: Failed when parsing body as json","reason":"ParsingError","details":{},"help":null,"code":500}
```
Important clarification: The content of the body between local and remote requests is __exactly the same__.

Nothing special regarding this problem is printed in the console output or written in the _.logs_ files.

**Command or request that led to error**:
I tried to call the "parse" endpoint with both cURL and Python (because my final application needs to call the NLU server from Python).

Here is the cURL call from a distant machine:
```
curl -X POST http://xx.xx.xx.xx:pppp/model/parse/ -H 'Content-Type: application/json' -d '{"text": "Hello"}'
```

Here is the simple Python code using _requests_:
```
import requests
url = "http://xx.xx.xx.xx:pppp/model/parse/"

payload = '{"text\": \"Hello\"}'
headers = {'Content-Type': "application/json"}

response = requests.request("POST", url, data=payload, headers=headers)

print(response.text)
```

Both requests lead to the abovementioned error...

**[Additional] Command to run the NLU server**:
```
docker run --detach \
  -p [my_port]:5005 \
  --name [my_container_name] \
  -v $(pwd):/app \
  rasa/rasa:latest-full \
  run --enable-api -m nlu_models/[my_last_model_name]
```

**[Additional] Content of credentials file (credentials.yml)**:
```yml
# This file contains the credentials for the voice & chat platforms
# which your bot is using.
# https://rasa.com/docs/rasa/user-guide/messaging-and-voice-channels/

rest:
#  # you don't need to provide anything here - this channel doesn't
#  # require any credentials
```

Thanks in advance for you help 💪

**Comment by akelad** [comment]
Thanks for raising this issue, @msamogh  will get back to you about it soon.

**Comment by msamogh** [comment]
@tbx0912 I'm unable to reproduce this. I ran the same commands as you did on both the local and remote settings.
