### ISSUE TITLE
NameError: Cannot access action 'action_restaurant'

### ISSUE THREAD

**Issue by manojrustagi79** [RasaHQ/rasa#4026]
Hi All,

Need help in resolving the error NameError: Cannot access action 'action_restaurant'.

My Domain File is:
slots:
  location:
    type: text
  cuisine:
    type: text
  budget:
    type: text

entities:
- location
- cuisine
- budget

intents:
 - greet
 - affirm
 - deny
 - goodbye
 - thankyou
 - restaurant_search

templates:
  utter_greet:
    - hey there! How may i help you
    - Hi, How can I help you!
    - Hey, How is it going. How May I help you Today
    - hey
    - howdy
    - hey there
    - hello
    - hi
    - good day
    - namastein"
    - hi !! how can i help you
    - welcome ! how can i help you
    - hi!! how may i help you
    - great to see you here!! how can i help you?
  utter_goodbye:
    - bye bye
    - goodbye
    - good bye
    - see you around
    - see you later
    - talk to you later
    - stop
    - end
    - see you again
    - looking forward to see you again
    - thank you for visiting us
  utter_default:
    - "Please bear with me still I am learning"
  utter_ask_cuisine: 
    - text: "what kind of cuisine would you like?"
      buttons:
      - title: "Chinese"
        payload: "Chinese"
      - title: "Italian"
        payload: "Italian"
      - title: "South Indian"
        payload: "South Indian"
      - title: "North Indian"
        payload: "North Indian"
  utter_ask_howcanhelp:
    - "how can I help you?"
  utter_ask_location:
    - "In what location?"

actions:
- utter_greet
- utter_goodbye
- utter_default
- utter_ask_howcanhelp
- utter_ask_location
- utter_ask_cuisine
- actions.ActionSearchRestaurants

**and my action file is:**

from __future__ import absolute_import
from __future__ import division
from __future__ import unicode_literals

from rasa.core.actions.action import Action
from rasa.core.events import SlotSet
import zomatopy
import json

class ActionSearchRestaurants(Action):
	def name(self):
		return 'action_restaurant'
		
	def run(self, dispatcher, tracker, domain):
		config={ "user_key":"b00cecabc1218c6bddde14655c3d277b"}
		zomato = zomatopy.initialize_app(config)
		loc = tracker.get_slot('location')
		cuisine = tracker.get_slot('cuisine')
		location_detail=zomato.get_location(loc, 1)
		d1 = json.loads(location_detail)
		lat=d1["location_suggestions"][0]["latitude"]
		lon=d1["location_suggestions"][0]["longitude"]
		cuisines_dict={'bakery':5,'chinese':25,'cafe':30,'italian':55,'biryani':7,'north indian':50,'south indian':85}
		results=zomato.restaurant_search("", lat, lon, str(cuisines_dict.get(cuisine)), 5)
		d = json.loads(results)
		response=""
		if d['results_found'] == 0:
			response= "no results"
		else:
			for restaurant in d['restaurants']:
				response=response+ "Found "+ restaurant['restaurant']['name']+ " in "+ restaurant['restaurant']['location']['address']+"\n"
		
		dispatcher.utter_message("-----"+response)
		return [SlotSet('location',loc)]

**Comment by psds01** [comment]
replace `actions.ActionSearchRestaurants` with `action_restaurant`

**Comment by akelad** [comment]
Please ask these kind of questions in our [forum](https://forum.rasa.com)
