### ISSUE TITLE
Form_bot and restaurant_bot require many dependencies

### ISSUE THREAD

**Issue by TQuy** [RasaHQ/rasa#4027]
**Description of Problem**:
I want to run the example bots to get a better understanding of rasa. However, it seems like they require duckling, docker container to run. Those two don't support my language well so I really don't want to install them.

**Overview of the Solution**:
Can you remove those dependencies so that the example bots can run easier

**Comment by akelad** [comment]
Hi, estaurant bot doesn't require it as far as i can tell. I don't think we'll be removing it from formbot, but you can still test out those bots without it. Also consider checking out the rasa_demo repo: https://github.com/RasaHQ/rasa-demo
