### ISSUE TITLE
Expose a http end point in rasa-x or rasa to add/modify/delete action

### ISSUE THREAD

**Issue by cyrilthank** [RasaHQ/rasa#4031]
**Description of Problem**:

 https://forum.rasa.com/t/rasax-enterprise-have-any-additional-http-endpoints-to-support-ongoing-maintenance/13056
**Overview of the Solution**:

 Expose a http end point in rasa-x or rasa to add/modify/delete action

**Examples** (if relevant):

Currently we have the below to upload new intents 
http://localhost:5008/api/projects/default/data
to upload new stories 
http://localhost:5008/api/stories
**Blockers** (if relevant):

**Definition of Done**:

**Comment by akelad** [comment]
you mean custom actions? how would this work? actions are written in a custom actions file and aren't configurable in rasa-x, so that's not something that's possible

**Comment by cyrilthank** [comment]
Thank you for your response
Understood the need for this question to go the forum route 
Appreciate your replying as I haven’t seen any response to my queries on forum
I was hoping the enterprise edition may have an UI to expose/upload a new actionsx.py
Is this feasible as a potential feature in future version atleast ?
Asking since I am not completely familiar with the code which powers this piece
Thank you
Cyril
    On Saturday, July 20, 2019, 2:13:57 AM GMT+5:30, Akela Drissner-Schmid <notifications@github.com> wrote:  
 
 
you mean custom actions? how would this work? actions are written in a custom actions file and aren't configurable in rasa-x, so that's not something that's possible

**Comment by akelad** [comment]
No, this is not something we're going to be implementing. Custom actions should be written in python/whichever other language you're comfortable with. We think creating a UI for that will complicate things if anything, as this part is written in actual code
