### ISSUE TITLE
Rasa x enterprise expose additional http end points 

### ISSUE THREAD

**Issue by cyrilthank** [RasaHQ/rasa#4039]
follow up to 
https://forum.rasa.com/t/rasax-enterprise-have-any-additional-http-endpoints-to-support-ongoing-maintenance/13056

what additional http apis does rasax enterprise have 
  for example for monitoring failed conversations
posting here to translate it as feature request if not available

**Comment by akelad** [comment]
Please ask these kind of questions in our [forum](https://forum.rasa.com)

**Comment by cyrilthank** [comment]
Thank you i have asked here
https://forum.rasa.com/t/rasax-enterprise-have-any-additional-http-endpoints-to-support-ongoing-maintenance/13056
