### ISSUE TITLE
Credentials.yml can't find my custom RestInput

### ISSUE THREAD

**Issue by dmlapteacru** [RasaHQ/rasa#4044]
**Rasa version:** 1.0.6

**Python version:** Python 3.6.8

**Operating system (windows, osx, ...):** Windows

**Issue:**
Hello Team. 
Created the custom RestInput channel, but got the error 'module not found'.
What am I doing wrong?

**credentials.yml** - added the raw
`channel.RestInput:
`

**channel.py** - the same as original one from rasa.core.channels

**Project structure:**
![image](https://user-images.githubusercontent.com/33374107/61491836-c1ae1a00-a9b8-11e9-95dd-c060fd1973c2.png)

When I use rasa.core.channels.channel.RestInput it works. But it can't find in local folder.

**Comment by akelad** [comment]
Please ask these kind of questions in our [forum](https://forum.rasa.com)
