### ISSUE TITLE
socket.io channel keeps connections open

### ISSUE THREAD

**Issue by akelad** [RasaHQ/rasa#4060]
Despite having a persistent tracker store configured, both we (with Sara) and a user experienced increasing memory usage as more users were talking to the bot. It's very likely a bug in the socket.io channel where it keeps connections open for longer than necessary

**Comment by akelad** [comment]
@wochinge not sure if you had any other comments

**Comment by wochinge** [comment]
Nope, I guess this would have to be double checked

**Comment by wochinge** [comment]
@akelad have you seen this again / is this fixed by now?

**Comment by akelad** [comment]
i haven't really looked at it since, but no idea if it's fixed
