### ISSUE TITLE
rasa shell doesn't throw any errors

### ISSUE THREAD

**Issue by akelad** [RasaHQ/rasa#4061]
Last week I was demonstrating something with `rasa shell` and it just got stuck on the first message without replying anything. Upon further investigation, I noticed that when using `rasa run` with the same data, it threw an error when I sent a message. So I believe errors are somehow being suppressed with `rasa shell`

To reproduce: add `TwoStageFallbackPolicy` to your config and make sure you don't have the `out_of_scope` intent in your domain. This should throw an error (it does in rasa run, but not in rasa shell)

Potentially related issue: https://github.com/RasaHQ/rasa/issues/3856

**Comment by wochinge** [comment]
fixed by https://github.com/RasaHQ/rasa/pull/4071
