### ISSUE TITLE
Rework the NLU training data page

### ISSUE THREAD

**Issue by akelad** [RasaHQ/rasa#4063]
We should rewrite that to use markdown examples for most of the features -- right now it uses json, which is very strange.
I think ideally we could have an element where you can switch from markdown to json, but the primary one should be markdown
https://rasa.com/docs/rasa/nlu/training-data-format/

**Comment by akelad** [comment]
@msamogh this also covers any general improvements that you think could be made to the page

**Comment by akelad** [comment]
@msamogh we talked about having examples of *both* json and markdown - and being able to switch between them, what happened to that?

**Comment by msamogh** [comment]
For now, I've just replaced them with Markdown. I'm guessing the switching component would need a separate extension, so I didn't look at it right away. But I found some examples here that we could try out - https://sublime-and-sphinx-guide.readthedocs.io/en/latest/code_blocks.html.

**Comment by erohmensing** [comment]
@msamogh good find -- would be cool if you could try it out, doesn't look like it'll even need any updates to rasabaster. but feel free to ask me if you run into trouble with sphinx

**Comment by akelad** [comment]
Ok I'm not really sure having only markdown is that great, we should look into fully reworking the page, not just making a quick fix

**Comment by akelad** [comment]
so let's look into adding this kind of component
