### ISSUE TITLE
Rework Language support page

### ISSUE THREAD

**Issue by akelad** [RasaHQ/rasa#4070]
It should be obvious that we support any language, it currently isn't. Here are some thoughts I had: 

* “We want to make the process of adding new languages as simple as possible to increase the number of supported languages. Nevertheless, to use a language you either need trained word representations or you need to train your own representations using a large corpus of text data in that language.” — misleading, not sure what we want to say with this
* I don’t think we need an example of how to write training data here 
* “adding a new language” is a weird section
* why all the Chinese specific stuff?

**Comment by pratikh07** [comment]
AttributeError: 'ApixuClient' object has no attribute 'getcurrent'

im facing this issue help me mam
