### ISSUE TITLE
Rasa X's NLU Post API Should Support Markdown

### ISSUE THREAD

**Issue by rgstephens** [RasaHQ/rasa#4076]
**Description of Problem**: The stated direction of Rasa is to use Markdown not JSON but the http `POST` [API](https://rasa.com/docs/rasa-x/api/rasa-x-http-api/#operation/addData) for training data supports only JSON. This API call also lacks symmetry with the adding of stories via it's `POST` call which takes a [markdown file](https://rasa.com/docs/rasa-x/api/rasa-x-http-api/#operation/uploadStories).

**Overview of the Solution**: There should be a post that allows upload of markdown like the stories post.

**Comment by msamogh** [comment]
Thanks for raising this issue, @MetcalfeTom will get back to you about it soon.

**Comment by MetcalfeTom** [comment]
Hi @rgstephens,

Is this for Rasa X?  The Rasa NLU HTTP API should already support both file types.

**Comment by rgstephens** [comment]
Yes, for Rasa X.

**Comment by MetcalfeTom** [comment]
Seems valuable, I'll add it to our maintenance

**Comment by rgstephens** [comment]
I just realized that the `GET` call also only returns json. It would be nice to support markdown there also.  Probably applies `PUT` too.

**Comment by msamogh** [comment]
I believe you can upload NLU data in bulk using Markdown to Rasa X as of now. Only single examples should be restricted to JSON.

**Comment by msamogh** [comment]
I agree about the `GET` call, though.

**Comment by rgstephens** [comment]
@msamogh I assume you're referring to the Rasa X UI import button which does allow you to import markdown. I'm referring to the API [POST](https://rasa.com/docs/rasa-x/api/rasa-x-http-api/#operation/addData) call which supports a json payload only.

**Comment by rgstephens** [comment]
@MetcalfeTom can you give an estimate on where this feature is?  I'm working on one of my bots that has NLU data in six markdown files with 300 intents.

I'd like to import this with the API and the Rasa X NLU Import has issues described in #3580. The workaround I'm using is to merge my markdown files and use the UI but both this API issue and the UI import issue need to be addressed.

**Comment by msamogh** [comment]
@rgstephens I was referring to this https://rasa.com/docs/rasa-x/api/rasa-x-http-api/#operation/replaceBulkData

**Comment by rgstephens** [comment]
@msamogh The payload for the PUT call you referenced is also json. This is a request to support the markdown format that has been recommended by Rasa for the past 9 months or so.

**Comment by msamogh** [comment]
@rgstephens You just have to set the `Content-Type` to `text/markdown`.

**Comment by rgstephens** [comment]
Thanks, I didn't notice the `text/markdown` option. That's a good workaround for me until `POST` with markdown is available.

**Comment by alexweidauer** [comment]
Thank you for raising this issue about Rasa X. We decided to stop supporting the Community Edition (free version) of ‘Rasa X’ (see more info here: https://rasa.com/blog/rasa-x-community-edition-changes/). That’s why we’ve closed your issue. We suggest that Rasa Enterprise customers raise the issue with our customer support team if they haven’t done so already.
