### ISSUE TITLE
Cannot import functions from rasa_nlu.test after update

### ISSUE THREAD

**Issue by ktoetotam** [RasaHQ/rasa#4085]
Hi,

I have updated to the latest version of rasa and now I cannot run the evaluation code:

```
from rasa_nlu.evaluate import combine_intent_result, combine_entity_result, \
    logger, return_results, return_entity_results, CVEvaluationResult, \
    get_intent_targets, get_intent_predictions, evaluate_intents
```

I understood that rasa_nlu.evaluate moved to rasa_nlu.test but this functions do not seem to be there. 

```
  File "/app/scripts/manual_cross_validation.py", line 10, in <module>
    from rasa_nlu.evaluate import combine_intent_result, combine_entity_result, \
ImportError: cannot import name 'combine_intent_result'
```

How do I get this code back running?

**Comment by ktoetotam** [comment]
So after some searching I found that:

The combine_intent_result, combine_entity_result are now one function combine_result and changed the code as follows:

```
 train_results,entity_train_results = combine_result(train_results,entity_train_results,
                                                     interpreter, train)
train_results, entity_test_results = combine_result(test_results,entity_test_results,
                                                    interpreter, test)
```

I still get:

`ImportError: cannot import name 'get_intent_predictions'`

**Comment by msamogh** [comment]
Thanks for raising this issue, @MetcalfeTom will get back to you about it soon.
