### ISSUE TITLE
Update tensorflow to 1.14.x

### ISSUE THREAD

**Issue by wochinge** [RasaHQ/rasa#4089]
- [ ] update requirements + setup.py
- [ ] check if the new release breaks anything

**Comment by dakshvar22** [comment]
@Ghostvv is planning to do this with the TEDP policy merge.
What's the best way to perform 'check if the new release breaks anything' ? I mean any particular tests?

**Comment by wochinge** [comment]
> How have we been completing 'check if the new release breaks anything' 

Good question 😄 I would to a couple of manual checks with tensorflow components / policies to check if there are now any warnings which we have to fix + travis should pass.
