### ISSUE TITLE
Make affirm and rephrase actions configurable in TwoStageFallbackPolicy

### ISSUE THREAD

**Issue by skumagai** [RasaHQ/rasa#4105]
**Description of Problem**: For two stage fallback policy, actions for affirmation and rephrase are not configurable from `config.yml`. Please make them configurable like `fallback_core_action_name` is.

**Overview of the Solution**: Add `affirmation_action_name` and `rephrase_action_name` in `TwoStageFallbackPolicy.__init__` with default arguments `ACTION_DEFAULT_ASK_AFFIRMATION_NAME` and `ACTION_DEFAULT_ASK_REPHRASE_NAME`, respectively. Then, replace occurrence of these constants in the class by instance variables such a self.affirmation_action_name (for example).

**Definition of Done**:

*   When I can use custom actions for affirmation and revert step easily via a configuration file.

**Comment by mjspeck** [comment]
Can't you just overwrite the actions as demonstrated in [this](https://blog.rasa.com/failing-gracefully-with-rasa-core/) blog post? I've written my own custom rephrase action. Not quite as simple as configuring the yaml, but those actions would probably need custom code anyway.

**Comment by skumagai** [comment]
Thanks for your reply.

I can. And in fact I do now. The thing is I need to add another bot while sharing the same action server between them. These bots need to have different implementation of affirmation and rephrase actions. Because only one custom action can take the name "action_default_ask_affirmation," I can't achieve my goal easily.

As you said these actions oftentimes need to be overwritten. Would it hurt to make them simpler to customize?

On a lighter note, I find it strange to call my custom action "action_default_ask_*". My custom code is not default implementation, and I'd like to reflect the action name to reflect the fact.

**Comment by msamogh** [comment]
Thanks for raising this issue, @wochinge will get back to you about it soon.

**Comment by wochinge** [comment]
@skumagai The names for these actions are hardcoded, because they are used by the internal action `action_revert_fallback_events` 🤔 Why not using two different action servers for different bots? The rasa-sdk image is pretty lightweight.

**Comment by skumagai** [comment]
@wochinge Thanks for the response.
I didn't realize `action_revert_fallback_events` uses the hard-coded names. I guess that makes making the names of affirmation and rephrase actions very difficult to configurable.

As for your suggestion of separate action servers, I'll take it back to my team if it's feasible.
