### ISSUE TITLE
HTTP Training in legacy Rasa_Core

### ISSUE THREAD

**Issue by saucepleez** [RasaHQ/rasa#4110]
**Rasa version**: 0.8.2

**Python version**: 3.6.3

**Operating system** (windows, osx, ...): Windows using Anaconda Prompt

**Issue**: I am using the HTTP API and training does not always seem to finish in 0.8.2 and return the 200 result with the model info.  It seems like the process hangs.  I understand this is an older version of Rasa, but I was wondering if this is a known issue that has been fixed.

The console typically outputs a line similar to the following:

``[Parallel(n_jobs=1)]: done 12 out of 12 | elapsed 0.0s finished``

Then a 200 response is generally returned.  Occasionally, however, the Anaconda prompt seems to hang at this line and does not appear to progress.

**Error (including full traceback)**:

No error is output to console

**Command or request that led to error**:

Calling /Train API and training a model

**Content of configuration file (config.yml)** (if relevant):

N/A

**Content of domain file (domain.yml)** (if relevant):

N/A

**Comment by msamogh** [comment]
Is it possible for you to update to the latest version and see if the issue persists?

**Comment by saucepleez** [comment]
@msamogh  The problem with updating is that the latest version does not support multiple projects (correct?).  We are using the HTTP API to train and score models which are used by our application.  Implementing this new version of Rasa will require architecture changes. Today:

- We bring up services using Anaconda on localhost:5006 (start python -m rasa_nlu.server)
- We support an array of projects, each with a project ID and model name.  Users compile data into a configuration which gets transformed into the training .YML file.  We generally have 2 models at any given time: a "Testing" model tied to a testing configuration and a "Deployed" model tied to a "deployed" configuration.
- We talk to localhost:5006 with any training requests (/Train API)
- We talk to localhost:5006 with any scoring requests (/Parse API)

In this way, a single instance of Rasa is training, loading and scoring models.  I am not quite sure how we will re architect this process to accommodate as each project would need at least 2 dedicated ports or IP addresses -- this is not something we can automatically bring up as today we invoke via CLI on Windows Server.

**Comment by msamogh** [comment]
Supporting multiple projects again is currently under discussion.

But reading the description of your workflow, it seems like for now, you could just use multiple instances of Rasa to achieve the same result (with a bit of tweaking on your side, of course).

**Comment by saucepleez** [comment]
@msamogh Thanks for your feedback.  The challenge for us now is regarding how to dynamically spawn more Rasa instances automatically (if we add more projects) as we do not have direct access to controlled environments or ready access to containers.
