### ISSUE TITLE
Can not interrupt rasa run server by Ctrl+C on winodws

### ISSUE THREAD

**Issue by HatuneMiku** [RasaHQ/rasa#4118]
**Rasa version**:
1.1.8

**Python version**:
Python 3.6
**Operating system** (windows, osx, ...):
Windows 10 1903 
**Issue**:

Can not interrupt rasa run server by Ctrl+C on winodws immediately, after I send something to the server, it raise KeyboardInterrupt. can it be Interrupt immediately by Ctrl+C ?

Maybe we need something like :
```python
try:
    tornado.ioloop.IOLoop.instance().start()
except KeyboardInterrupt:
    tornado.ioloop.IOLoop.instance().stop()
```
https://stackoverflow.com/questions/17101502/how-to-stop-the-tornado-web-server-with-ctrlc

Thanks!

**Comment by msamogh** [comment]
Thanks for raising this issue, @tabergma will get back to you about it soon.

**Comment by mohankumargx** [comment]
@HatuneMiku  You can use Ctrl+Pause to interrupt

**Comment by tabergma** [comment]
@HatuneMiku Does Ctrl+Pause work for you? We are using a Sanic server. There seems to be an ongoing discussion around that topic (https://github.com/huge-success/sanic/issues/108).

**Comment by HatuneMiku** [comment]
@tabergma Ctrl+Pause not work for me at 1.1.8 just like   Ctrl+C .

**Comment by tabergma** [comment]
@HatuneMiku Are you willing to invest some time and check how the problem could be solved? The server is started here: https://github.com/RasaHQ/rasa/blob/master/rasa/core/run.py#L186

**Comment by HatuneMiku** [comment]
I've tried again using `Ctrl+Pause`,  which actually works fine in cmd, but doesn't work in the cmd of the terminal of vscode. And it looks like this is a bug in vscode-python https://github.com/microsoft/vscode-python/issues/4100. 

@mohankumargx @tabergma Thanks!

**Comment by TQuy** [comment]
I have exactly the same issue, I even tried to reset my window but it doesn't solve the problem

**Comment by florardu** [comment]
I have this issue too. ctrl + c does not stop the server.

**Comment by nkabram** [comment]
I have the same issue running rasa action server on windows powershell
