### ISSUE TITLE
NameError: Cannot access action 'utter_....', as that name is not a registered action for this domain

### ISSUE THREAD

**Issue by TatianaParshina** [RasaHQ/rasa#4120]
**Rasa version**:
Rasa 1.1.4

**Rasa X version** (if used & relevant):
Rasa X 0.19.5

**Python version**:
Python 3.6.8

**Operating system** (windows, osx, ...):
Windows 8.1

**Issue**:
Rasa X domain is not in sync with domain.yml file.
Rasa X domain contains 'utter_zoo' that I have added manually from UI and saved to domain.yml.  Then I removed it manually from all local files -  domain.yml, nlu.md and stories.md. However, it still appears in the Rasa X domain and leading to the error while training.

Where does Rasa X save information about the domain? I have tried to remove all models, db files but Rasa X is still displaying this 'utter_zoo' that is not saved in local files.

**Error (including full traceback)**:
```
  File "C:\ProgramData\Anaconda3\envs\myenv\lib\site-packages\rasa\core\domain.p
y", line 380, in index_for_action
    return self.action_names.index(action_name)
ValueError: 'utter_zoo' is not in list

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\envs\myenv\lib\runpy.py", line 193, in _run_mod
ule_as_main
    "__main__", mod_spec)
  File "C:\ProgramData\Anaconda3\envs\myenv\lib\runpy.py", line 85, in _run_code

    exec(code, run_globals)
  File "C:\ProgramData\Anaconda3\envs\myenv\lib\site-packages\rasa\__main__.py",
 line 81, in <module>
    main()
  File "C:\ProgramData\Anaconda3\envs\myenv\lib\site-packages\rasa\__main__.py",
 line 70, in main
    cmdline_arguments.func(cmdline_arguments)
  File "C:\ProgramData\Anaconda3\envs\myenv\lib\site-packages\rasa\cli\train.py"
, line 84, in train
    kwargs=extract_additional_arguments(args),
  File "C:\ProgramData\Anaconda3\envs\myenv\lib\site-packages\rasa\train.py", li
ne 40, in train
    kwargs=kwargs,
  File "C:\ProgramData\Anaconda3\envs\myenv\lib\asyncio\base_events.py", line 48
4, in run_until_complete
    return future.result()
  File "C:\ProgramData\Anaconda3\envs\myenv\lib\site-packages\rasa\train.py", li
ne 135, in train_async
    kwargs=kwargs,
  File "C:\ProgramData\Anaconda3\envs\myenv\lib\site-packages\rasa\train.py", li
ne 174, in _do_training
    kwargs=kwargs,
  File "C:\ProgramData\Anaconda3\envs\myenv\lib\site-packages\rasa\train.py", li
ne 303, in _train_core_with_validated_data
    kwargs=kwargs,
  File "C:\ProgramData\Anaconda3\envs\myenv\lib\site-packages\rasa\core\train.py
", line 60, in train
    agent.train(training_data, **kwargs)
  File "C:\ProgramData\Anaconda3\envs\myenv\lib\site-packages\rasa\core\agent.py
", line 665, in train
    self.policy_ensemble.train(training_trackers, self.domain, **kwargs)
  File "C:\ProgramData\Anaconda3\envs\myenv\lib\site-packages\rasa\core\policies
\ensemble.py", line 90, in train
    policy.train(training_trackers, domain, **kwargs)
  File "C:\ProgramData\Anaconda3\envs\myenv\lib\site-packages\rasa\core\policies
\memoization.py", line 159, in train
    self._add_states_to_lookup(trackers_as_states, trackers_as_actions, domain)
  File "C:\ProgramData\Anaconda3\envs\myenv\lib\site-packages\rasa\core\policies
\memoization.py", line 108, in _add_states_to_lookup
    feature_item = domain.index_for_action(action)
  File "C:\ProgramData\Anaconda3\envs\myenv\lib\site-packages\rasa\core\domain.p
y", line 382, in index_for_action
    self._raise_action_not_found_exception(action_name)
  File "C:\ProgramData\Anaconda3\envs\myenv\lib\site-packages\rasa\core\domain.p
y", line 391, in _raise_action_not_found_exception
    "".format(action_name, action_names)
NameError: Cannot access action 'utter_zoo', as that name is not a registered ac
tion for this domain. Available actions are:
         - action_listen
         - action_restart
         - action_default_fallback
```

**Command or request that led to error**:
```
rasa train
```

**Comment by msamogh** [comment]
As of now, the `domain.yml` file on your filesystem reflects the _latest_ change that you made from Rasa X. So it might be possible that the `domain.yml` file that you're seeing on your local filesystem is different from that of your `Active` model on Rasa X.

**Comment by TatianaParshina** [comment]
@msamogh thank you for your reply!

I still have the question:
1. Where does Rasa X save information about domain if it doesn't use domain.yml?
2. How to update the Rasa X domain from domain.yml file? I have the actual information in domain.yml file. 
Use case: different team members are working on domain.yml and commit changes to the Github project. Then these changes should be reflected from domain.yml to Rasa X domain.

**Comment by psds01** [comment]
`1. Where does Rasa X save information about domain if it doesn't use domain.yml?`
-> /model/xxxx.tar.gz/core/domain.yml
2. You should train the bot again after any changes to `domain` or `config` or `nlu` or `stories`.

FYI : you can find _all_ the info about the "trained" bot in `/model/xxxx.tar.gz/`. `/core/` has core related info and `/nlu/` has nlu related info.

**Comment by TatianaParshina** [comment]
@psds01  thank you for your reply! 
I can't train the model because of the error that I mentioned in the body. Rasa X domain is not in sync with `domain.yml` file and doesn't use the data from the local filesystem (but I need to use data from the local `domain.yml`). 
I have found that `rasa.db` stores information about Rasa X domain (it is different from `domain.yml`). I have deleted `rasa.db` , `tracker.db`, all models from models folder but I still have the error. It seems that cache information is stored somewhere. Where?

**Comment by psds01** [comment]
There's no cache, per se. There's tmp storage: https://github.com/RasaHQ/rasa/issues/3851

But it looks like not all `utter_zoo`s are deleted from either `nlu` or from `stories` file. Could you please double check?

**Comment by TatianaParshina** [comment]
I still have the error.

- I have removed 'rasa.db' and 'tracker.db' files. 
- I have removed all models in the 'models' folder
- I have removed almost all intents. Remaining only 'greet' and 'goodbye' intents in 'nlu.md', 'domain.yml', 'stories.md'.

**Comment by msamogh** [comment]
@TatianaParshina Sorry for the late response, but could you try moving all your bot-related files into a new directory (just the config, endpoints, credentials, domain, stories and nlu data) and launch Rasa X from there? And could you maybe just describe the exact steps to reproduce it from there?

**Comment by TatianaParshina** [comment]
@msamogh , I was able to avoid the issue by removing all files, restarting computer and etc. But definitely, it is not the correct way. 
I did a lot of different steps in Rasa X UI and in the local filesystem. 
To reproduce the issue, I think steps should be as following:
1. Open Rasa X UI.
2. In UI add new template 'utter_zoo' in the domain, add new intent and story. Save it.
3. Train model from Rasa X UI.
4. Remove manually 'utter_zoo' from domain.yml, nlu.md and stories.md on the local filesystem. 
5. Train model using the command `rasa train`

**Comment by msamogh** [comment]
@TatianaParshina Thanks for the clear description.

Changes made from within Rasa X are saved to the filesystem the moment you hit the save button. However, the changes you make directly in the filesystem are not reflected in Rasa X until the next restart. 

This is because, during startup, Rasa X loads the contents of the files onto the database and from there, the UI.

**Comment by TatianaParshina** [comment]
@msamogh thank you for the explanation! 
1. What do you mean by `until the next restart`? I closed Rasa X, run train command and then it failed.  Should I close Rasa X, run Rasa X, close Rasa X and then run train command?
2. I understand that Rasa X saves information in DB files. I removed `rasa.db` and `tracker.db` files but I still had the error. Do you use some other place (cache) to save this information?

**Comment by TatianaParshina** [comment]
We still face the issue. Is there any way to avoid it?

**Comment by msamogh** [comment]
Are you sure you removed the correct `rasa.db` (`tracker.db` shouldn't cause an issue here)? Because there's no other place where it stores this data (no cache either).

**Comment by msamogh** [comment]
Ok I tried following your steps, and it seems like `utter_zoo` gets populated onto the filesystem when Rasa X loads.

**Comment by msamogh** [comment]
@TatianaParshina The issue went away once I removed the stories that contained `utter_zoo`. So I think Rasa X automatically adds those templates to the domain if it's part of the stories. I'm yet to confirm that in the code, but it looks like that's what's happening.
