### ISSUE TITLE
Docs: HTTP API - reloading after training?

### ISSUE THREAD

**Issue by Polarisation** [RasaHQ/rasa#4131]
**Rasa version**: 1.1.8

**Issue**:
In the docs for the HTTP API, the [Train a Rasa Model](https://rasa.com/docs/rasa/api/http-api/#tag/Model/paths/~1model~1train/post) call states that "The trained model is not loaded by default."

What happens if the model being trained is already loaded? Is it necessary to reload with "[Replace the currently loaded model](https://rasa.com/docs/rasa/api/http-api/#tag/Model/paths/~1model/put)"? Or is that only for switching to a different model?

Please could this be clarified in the docs?

**Comment by msamogh** [comment]
Thanks for raising this issue, @erohmensing will get back to you about it soon.

**Comment by erohmensing** [comment]
Hi @Polarisation, yes, training a model will just train it and store it, you would actually have to replace the model for it to be used in e.g. the /model/parse endpoint. What could we say that would make it more clear? You can open a PR to edit the description in the spec here: https://github.com/RasaHQ/rasa/blob/master/docs/_static/spec/rasa.yml

**Comment by Polarisation** [comment]
Hi, thanks for the reply. But that's still not quite clear to me.

There's two different scenarios:

**First scenario: training a model that is not currently loaded.**
I currently have **ModelA** loaded, but I want to train **ModelB**.
In this scenario it's clear that **ModelB** will not be loaded, unless I replace the model.

**Second scenario: re-training a model that is currently loaded**
I currently have **ModelA** loaded, and I want to re-train it (**ModelA**).
In this scenario it is not clear from the documentation if I need to replace the model or not.
If this works like a typical application, I wouldn't need to re-load a file from disk if it is already open.

In the second scenario, if the model needs to be replaced, I suggest the following wording:

> The trained model is not loaded by default (even if it is the currently loaded model).

If the model does not need to be replaced, I suggest:

> The trained model is not loaded by default (unless already loaded).

(this would seem ideal, as it's how it worked prior to v1.0 - it was possible to call a single endpoint to retrain the model, and it could be used immediately)

**Comment by erohmensing** [comment]
You don't _train_ a specific model, you take a bunch of data and create a model out of it. If you "retrain a loaded model", you're actually just creating a duplicate model with the same data. Does that make sense?

**Comment by Polarisation** [comment]
I see. Yes, you're right, I've just checked and the legacy docs say "By default the latest trained model for the project will be loaded".

With the old API it felt like I was "re-training a model", but in fact I was training a new model for a specific project, which was loaded automatically. Sorry for the confusion.

I think the docs would be clearer if the API description said "Trains a **new** Rasa model".

**Comment by Polarisation** [comment]
Also opened #4163 which is a related feature request

**Comment by tabergma** [comment]
@erohmensing You explained everything correctly 😄 

@Polarisation I like the idea you proposed in the feature request. Thanks for creating the issue. I guess we can close this issue, can't we?

**Comment by Polarisation** [comment]
I submitted a small PR to clarify the documentation. If that is accepted I'd then consider this issue fixed 🙂
