### ISSUE TITLE
Exception: This visualization cannot be rendered.

### ISSUE THREAD

**Issue by true1337** [RasaHQ/rasa#4132]
**Rasa version**: 1.1.8

**Rasa X version** (if used & relevant): 0.20.0

**Python version**: 3.6.7

**Operating system** (windows, osx, ...): Ubuntu, Centos

**Issue**:
The story constructor can't render following story:
```
## happy path
* greet
    - utter_greet
    - topic_suggestion_form
    - slot{"requested_slot":"topic"}
* choose{"topic":"domain"}
    - slot{"topic":"domain"}
    - topic_suggestion_form
    - slot{"topic":"domain"}
    - slot{"requested_slot":null}
    - feedback_form
    - slot{"requested_slot":"is_satisfied"}
* affirm
    - feedback_form
```

We know that line below causes the error.
```
choose{"topic":"domain"}
```
Connected issue [3685](https://github.com/RasaHQ/rasa/issues/3685)

**Error (including full traceback)**:
I don't see any traceback in console

![image](https://user-images.githubusercontent.com/26603018/62118530-7d7b1d80-b2c6-11e9-8e56-454204d9ec96.png)

**Comment by msamogh** [comment]
Thanks for raising this issue, @gausie will get back to you about it soon.

**Comment by gausie** [comment]
This is because of an issue we're having rendering slots with entities. We're aware of the issue and working on it.

**Comment by erohmensing** [comment]
@true1337 this should be fixed in 0.20.2. Can you upgrade and check whether your stories now render?

**Comment by true1337** [comment]
No, it doesn't work.

![image](https://user-images.githubusercontent.com/26603018/64152123-9aaa8b00-ce34-11e9-9940-46071d44bcf0.png)
![image](https://user-images.githubusercontent.com/26603018/64152174-b9a91d00-ce34-11e9-98d4-7b2309826e21.png)

**Comment by erohmensing** [comment]
Hm this is strange. I've tested locally and it seems to work fine. Just to be sure, if you were to remove the `{"topic": "domain"}` from `* choose {"topic":"domain"}` does it then visualize?

**Comment by true1337** [comment]
@erohmensing Yes, in that way it works.

**Comment by erohmensing** [comment]
@true1337 what browser are you using?

**Comment by msamogh** [comment]
I haven't confirmed it myself, but I was told by a Windows user that it works fine on Windows and the issue only appears on Linux.

**Comment by true1337** [comment]
OS: Ubuntu, Centos
Browser: Mozilla Firefox

**Comment by erohmensing** [comment]
Sorry do you mean that the same issue happens on CentOS and Ubuntu? Can't be both at once -- also what versions?

**Comment by true1337** [comment]
I have DEV (Ubuntu) and STAGE (CentOS) environments.
```
pip list | grep rasa
rasa                    1.2.8      
rasa-sdk                1.2.0      
rasa-x                  0.20.2   
```

**Comment by erohmensing** [comment]
Got it, thanks for the clarification. I rather meant what versions of CentOS and Ubuntu (e.g. 16.04, 18.04)

**Comment by true1337** [comment]
Ok :) 
Ubuntu - 16.04.5
CentOS - centos-release-7-5.1804.el7.centos.2.x86_64

**Comment by psi43** [comment]
I have the same issue. Whenever slots are involved, it won't render. 
I'm using Ubuntu - 16.04.6 LTS

For some reason I just assumed this was normal, whenever slots were involved.

**Comment by JEM-Mosig** [comment]
I've got the same issue, but _only_ when Rasa X runs on the server. 
The story 
```
## interactive_story_2
* start
    - utter_meta_privacy
* meta_set_privacy{"allow_datacollection": "False"}
    - slot{"allow_datacollection": "False"}
    - utter_meta_acknowledge_privacy
    - utter_general_greet
    - utter_general_about
    - utter_ask_whattodo
* general_deny
    - utter_general_emotional_resigned
    - utter_ask_helpdevelopers
* general_deny
    - utter_general_emotional_resigned
    - utter_general_goodbye
```
renders fine on my MacBook with 
```
Brave Browser [Version 0.68.139 Chromium: 77.0.3865.90 (Official Build) (64-bit)] 
MacOS Mojave 10.14.6 (18G95)
Rasa 1.2.7
{"rasa":{"production":"1.2.7","worker":"1.2.7"},"rasa-x":"0.20.2"}
```
But on Google Cloud Platform with 
```
Ubuntu 16.04.6 LTS, 
{"rasa":{"production":"1.2.9","worker":"1.2.9"},"rasa-x":"0.20.3"}
```
the same story only appears as "This visualization cannot be rendered".

**Comment by wochinge** [comment]
fixed by https://github.com/RasaHQ/rasa/pull/4600
