### ISSUE TITLE
FAQ component to handle questions

### ISSUE THREAD

**Issue by tmbo** [RasaHQ/rasa#414]

**Comment by tmbo** [comment]
Actually, this should work way better using the new tensorflow model. It should be able to better differentiate between questions that are very similar but different.

**Comment by sibbsnb** [comment]
Any solutions planned for this?

**Comment by dakshvar22** [comment]
Hi @sibbsnb We are actually very close to releasing a new component which aims at simplifying this. Check out this PR - https://github.com/RasaHQ/rasa/pull/4233
