### ISSUE TITLE
Unable to use TemplatedNaturalLanguageGenerator in NLG due to Sanic/uvicorn conflict

### ISSUE THREAD

**Issue by moaazsidat** [RasaHQ/rasa#4140]
Does it make more sense to put TemplatedNaturalLanguageGenerator as part of rasa_sdk instead of rasa.core.nlg, since it is used like so:
https://github.com/RasaHQ/rasa/blob/master/examples/nlg_server/nlg_server.py#L57

The reason being that we're using something other than Sanic for our NLG server and are running into conflicting dependencies when trying to install rasa with the latest uvicorn installation due to the following Sanic/uvicorn incompatibility:
huge-success/sanic#1629

Anyone with more knowledge of how rasa works internally comment on if this be relatively easily extracted to be part of rasa_sdk?
https://github.com/RasaHQ/rasa/tree/master/rasa/core/nlg

Or alternatively, should there be a rasa_nlg package?

**Comment by msamogh** [comment]
Thanks for raising this issue, @ricwo will get back to you about it soon.

**Comment by ricwo** [comment]
Hi @moaazsidat, 

> The reason being that we're using something other than Sanic for our NLG server and are running into conflicting dependencies when trying to install rasa with the latest uvicorn installation due to the following Sanic/uvicorn incompatibility

I'm confused about this issue, since the built-in NLG server in `rasa-sdk` uses flask. Where are you running into the issue? Isn't simply running `python -m rasa_sdk --actions actions.py` an option for you, which would not require a sanic installation?

The NLG module is used extensively in the `rasa.core` module, and `rasa-sdk` is in general not a dependency of `rasa` (an installation is only required for running the custom action server _out of rasa_). It sounds like a fix is being worked on for `sanic 19.9`: https://github.com/huge-success/sanic/issues/1629#issuecomment-510122757

**Comment by moaazsidat** [comment]
We're using our own NLG service that's built using FastAPI and Uvicorn. It's just a web service that given an utterance, returns the template as json. 

We want to return `TemplatedNaturalLanguageGenerator` as the response so that the templates returned by this NLG service can be filled in with slot values as they're being returned (since TemplatedNaturalLanguageGenerator let's us do that)

The limitation right now is that we have to install the entire `rasa` package to our NLG service, just to access `TemplatedNaturalLanguageGenerator`, but installing `rasa` also installs `Sanic` which then conflicts with `Uvicorn`. 

Regardless of how Sanic resolves this, I still think it highlights a need to separate `rasa.core.nlg` into a separate package because it should be able to be used in any pythonic web service. 

Let me know if that makes sense, happy to elaborate further.

**Comment by ricwo** [comment]
You'd still require an installation of rasa, even if `rasa.core.nlg` were its own package (it needs the `Domain` and `EndpointConfig` for example). 

As a temporary solution until Sanic fixes the issue, can you just install rasa without Sanic for your Uvicorn webservice? I mean just cloning the repository and removing `Sanic` from `setup.py` and `requirements.txt`

**Comment by moaazsidat** [comment]
hmm, fair enough, yeah, had a feeling that it may be less trivial to extract it into a lib.

**Comment by akelad** [comment]
@ricwo can this be closed?
