### ISSUE TITLE
CLI No longer accepts "num_threads" as a parameter for the sklearn intent classifier

### ISSUE THREAD

**Issue by egiglio** [RasaHQ/rasa#4141]
Rasa does not support num_threads as the parameter anymore. This is a parameter that gets picked up from kwargs by the sklearn intent classifier as seen here https://github.com/RasaHQ/rasa/blob/master/rasa/nlu/classifiers/sklearn_intent_classifier.py#L83

When passing in the num_threads parameter in the CLI it now returns the following error.

"rasa: error: unrecognized arguments: --num_threads 8"

This should be a valid CLI parameter as the intent classifier uses it.

**Comment by sara-from-rasa** [comment]
Thanks for raising this issue, @amn41 will get back to you about it soon!

**Comment by chidauri** [comment]
@amn41 I would like to work on this.

**Comment by amn41** [comment]
awesome!

**Comment by chidauri** [comment]
@amn41 I am thinking of implementing it in the same way as kwargs is passed in `train_core` using this line https://github.com/RasaHQ/rasa/blob/82142fe7c18faca792c1f09c9fd398cc3b3e160a/rasa/cli/train.py#L94
We can store the `num_threads` in kwargs and then pass in `train_nlu`? 
Is this the correct way?

**Comment by neelkes** [comment]
@chidauri just wanted to check if there are any progress on adding num_threads back to CLI?

**Comment by lucianaribeiro** [comment]
Hi, is this issue still need to be done?

**Comment by erohmensing** [comment]
@lucianaribeiro I think so! Looks like someone has run into it here: https://forum.rasa.com/t/how-to-increase-parallel-jobs-while-training/12407/9?u=erohmensing

**Comment by aleronupe** [comment]
Hi, @tmbo! Is this issue still open? It seems to be completed on the merged branch but it hasn't been closed yet

**Comment by tmbo** [comment]
Yes 👍
