### ISSUE TITLE
output NLU results to results folder by default

### ISSUE THREAD

**Issue by erohmensing** [RasaHQ/rasa#4144]
The core evaluation, by default, outputs all of its files to a results folder. the NLU evaluation doesn't. It would be nice if they were in the same spot so that you can easily find all of the files, as well as read them more programmatically (e.g. here: https://rasa.com/docs/rasa/api/jupyter-notebooks/)

**Comment by ismaeelBM** [comment]
If no one started working on this issue, may I pick it up as my first issue?

**Comment by erohmensing** [comment]
I'd love that @ismaeelBM! Let me know if you have any questions :)

**Comment by erohmensing** [comment]
Thanks for your work on this issue, @ismaeelBM! We'd love to see more contributions from you in the future 🚀

**Comment by ismaeelBM** [comment]
@erohmensing Not a problem! I look forward to making more contributions! 😊
