### ISSUE TITLE
Define a Rasa command that bundles all the relevant files for a bot in an archive file

### ISSUE THREAD

**Issue by msamogh** [RasaHQ/rasa#4153]
**Description of Problem**:
Have a CLI command to package all the relevant files for a bot (NLU + Stories training data, configuration, domain, endpoints, credentials, and anything else I might have missed) into an archive (like a tar.gz)

**Definition of Done**:
- [ ] Tests are added
- [ ] Feature is documented
- [ ] Update changelog

**Comment by wochinge** [comment]
Can't they just use `zip`?

**Comment by msamogh** [comment]
Yes, but the target demography for this that I had in mind (people new to Rasa) might not know what files to include.

**Comment by wochinge** [comment]
Mhm, so this would pack everything except logs and `models`?

**Comment by msamogh** [comment]
Yeah

**Comment by wochinge** [comment]
@msamogh I put it in discussion since I am not convinced by the use case behind that and would like to hear the opinion of the others. 

@MetcalfeTom You reacted with a thumbs up, what's your take on this?

**Comment by imLew** [comment]
When would people use this? Assembled everything on their laptop and want to send it somewhere else to train?
Also, this command would be something someone new to rasa doesn't know either; they'd have to either look up what files are required or how to run this command. So basically if this is neccessary it'd be better to clarify what's needed in the docs rather than add this command.

**Comment by msamogh** [comment]
> Assembled everything on their laptop and want to send it somewhere else to train?

Yes, that's one of the use cases in mind.

> Also, this command would be something someone new to rasa doesn't know either; they'd have to either look up what files are required or how to run this command.

Agreed. But it's also just a matter of convenience. It's simpler to, say, do a `rasa bundle` rather than handpicking the files.

**Comment by tmbo** [comment]
mhm atm I'd say we rather go and add the command to do this to the documentation. I am not sure we have figured out this workflow of sharing the bot. Initially, I thought this is meant to provide insights and help if there is an issue and that this should be attached to a created gh issue.

**Comment by msamogh** [comment]
So, shall I remove the discussion tag, then?

**Comment by wochinge** [comment]
> mhm atm I'd say we rather go and add the command to do this to the documentation

This sounds more like adding the `zip` command to the docs for me?

**Comment by tmbo** [comment]
yes, that was my intention: do not change code but describe how to achieve the result using standard tools like zip or tar

**Comment by tmbo** [comment]
I think we can remove the discussion label and move this to unplan. 

I think it is a good idea, but I think the need isn't strong enough at the moment
