### ISSUE TITLE
Training in compare mode with wrong params

### ISSUE THREAD

**Issue by ruiconti** [RasaHQ/rasa#4156]
**Rasa version**: 1.1.8

**Rasa X version** (if used & relevant):

**Python version**: 3.6.8

**Operating system** (windows, osx, ...): macOs

**Issue**:

When training in compare mode, I noticed that exclusion percentages weren't being applied. Shouldn't this line https://github.com/RasaHQ/rasa/blob/73336bf9b522b3aeafb3e88eea71c667de349e09/rasa/core/train.py#L121 reference `percentage` instead of `current_run`?

**Error (including full traceback)**:
```

```

**Command or request that led to error**:
```

```

**Content of configuration file (config.yml)** (if relevant):
```yml

```

**Content of domain file (domain.yml)** (if relevant):
```yml

```

**Comment by sara-from-rasa** [comment]
Thanks for raising this issue, @imLew will get back to you about it soon!

**Comment by imLew** [comment]
Yes, it should be. This has already been fixed in the master branch and will be in the next release.
