### ISSUE TITLE
HTTP API - option to load a model after training

### ISSUE THREAD

**Issue by Polarisation** [RasaHQ/rasa#4163]
**Description of Problem**: Prior to v1.0 a model would be loaded after training it, and automatically used for parsing unless otherwise specified. Now I would have to: `POST /model/train` `PUT /model` It would be nice to be able to do this with one API call as before.

**Overview of the Solution**: I suggest adding an request body parameter to `POST /model/train` which would load the new model after training.

This could be a boolean named **load**.

**Definition of Done**:

**Comment by sara-tagger** [comment]
Thanks for submitting this feature request 🚀@tyd will get back to you about it soon!✨

**Comment by erohmensing** [comment]
I'd almost prefer these to be two separate options, i.e. you could `POST model/train` to create a new model and `PUT model/train` to create a new model _and_ load it. Thoughts? (also i'm not the best at what should be puts vs posts)

**Comment by Polarisation** [comment]
I don't think PUT would be correct, because [the spec](https://www.w3.org/Protocols/rfc2616/rfc2616-sec9.html#sec9.6) says:

> If the Request-URI refers to an already existing resource, the enclosed entity SHOULD be considered as a modified version of the one residing on the origin server.

In this case, it's not a modified version of the previous model, but a new model (the old one still remains on the server, as I understand). So strictly speaking I think POST is more correct.

**Comment by erohmensing** [comment]
Okay, that's fair! Then yeah, i think a request body parameter sounds fine! Go for it 🚀

**Comment by Polarisation** [comment]
>  Go for it

To be clear, I'm not currently planning to work on this. I'm not so familiar with Python development, that's why I'm using the HTTP API 😊

So if someone wants to tackle this, please go ahead!

**Comment by erohmensing** [comment]
Got it. Thanks for the heads up!

**Comment by samzer** [comment]
If no one is working on this currently, can I pick this one up?

**Comment by erohmensing** [comment]
Sure thing @samzer! I don't think anyone is working on it. Will assign to you.

**Comment by samzer** [comment]
@erohmensing Thanks!

**Comment by erohmensing** [comment]
Hey @samzer, how is it going? Are you still working on this issue, and if so, anything we can do to help?

**Comment by samzer** [comment]
Hey Ella, 

Sorry, for not completing this. Yes, I'm working on this. I figured out the part of the code to make the updates. 

So I'll do the following:-
- Update the code
- Update the documentation corresponding to this

Anything else that I should take care of?

**Comment by erohmensing** [comment]
No worries! Just wanted to make sure you still wanted to tackle it, or I would have opened it up to someone else. Those steps look good, just a few things to add
* update API spec (https://github.com/RasaHQ/rasa/blob/master/docs/_static/spec/rasa.yml) though this is probably where all of the documentation corresponding to this issue will be anyway
* add a changelog entry

**Comment by samzer** [comment]
Sure.

**Comment by dingusagar** [comment]
hi @erohmensing , would like to pick this up if no one else is working on it.

**Comment by dingusagar** [comment]
Have added a request param - load_model to the existing /model/train API. If this param is set to true, the trained model is loaded to the agent. Here is the PR #8538 . please review and suggest improvements if any.  Thanks :)
