### ISSUE TITLE
rasa-sdk is behind in versioning when compared to rasa-1.2.0

### ISSUE THREAD

**Issue by krasi0** [RasaHQ/rasa#4167]
I observe the following warning once having updated to rasa 1.2.0

` WARNING  rasa_sdk.endpoint  - Your versions of rasa and rasa_sdk might not be compatible. You are currently running rasa version 1.2.0 and rasa_sdk version 1.1.1.`

Additionally, there is a new exception that I had never seen using 1.1.x:
`Exception occurred while handling uri: unknown
NoneType: None`
I am not sure what's causing it...

**Comment by sara-tagger** [comment]
Thanks for raising this issue, @erohmensing will get back to you about it soon✨

Please also check out the [docs](https://rasa.com/docs/) and the [forum](https://forum.rasa.com/) in case your issue was raised there too 🤓

**Comment by erohmensing** [comment]
You've got a very good point on the first one -- we'll release an sdk release to match!

Regarding the second issue, is there  more of a traceback to that error that might help me figure out what's causing it?

**Comment by krasi0** [comment]
Great! Thanks!

With regards to the second issue, I believe that it was because of some
misconfiguration on my side so no worries

**Comment by erohmensing** [comment]
Ok, no prob. Yeah i've seen that issue a few times, but it seems to always be cleaned up in peoples' custom action code :) Will close this when we release sdk
