### ISSUE TITLE
RASA-X API - PUT stories does add instead of replace

### ISSUE THREAD

**Issue by rgstephens** [RasaHQ/rasa#4168]
**Rasa version**: 1.1.4

**Rasa X version**: 0.20.0

**Issue**:

With the `stories.md` file below, and with no stories loaded in my Rasa X instances I do the following:

1. call [PUT](https://rasa.com/docs/rasa-x/api/rasa-x-http-api/#operation/replaceStories) and the stories are added.  Since the stories don't exist, shouldn't this report an eror and do nothing instead of adding the stories?
2. I then call PUT again with the same stories and I end up with two copies of each story for a total of four stories. This should replace the existing stories.

PUT appears to be identical to POST for stories.

**Content of stories file** (if relevant):
```md
# new story 1, stories1.md
* hello
  - utter_hi_there

# new story 2, stories1.md
* hello
  - utter_hi_there
```

**Comment by sara-tagger** [comment]
Thanks for the issue, @JustinaPetr will get back to you about it soon!

You may find help in the [docs](https://rasa.com/docs/) and the [forum,](https://forum.rasa.com/) too 🤗

**Comment by MetcalfeTom** [comment]
Hi @rgstephens,

Thanks for letting us know about this bug, I tested it on my end with the same result so I'll add it to the backlog.
Checking through the source code, seems like the stories aren't deleted with the query we execute upon receiving the `PUT` request.

**Comment by wochinge** [comment]
@erohmensing I overlooked that you already assigned yourself. Did you already fix it? Otherwise I found the error 🙈 The username doesn't get passed as `username` to `replace_stories`, but as `filename`

**Comment by erohmensing** [comment]
Hahaha i just picked it as my maintenance task for the week but if you already have the solution, go for it 😋 just let me know and i'll switch the assignment

**Comment by wochinge** [comment]
>  i haven't looked at it yet
phew 👍 

Ok, will ask for your review then :-)

**Comment by wochinge** [comment]
@rgstephens I fixed the problem that stories are added when they should be updated.

The endpoint deletes all the old stories and adds the new ones (means it there stories are replaced). How could we make this behaviour more obvious? The API spec describes the endpoint by saying it `Replace stories`
