### ISSUE TITLE
TypeError: t.find is not a function 

### ISSUE THREAD

**Issue by harunkelesoglu** [RasaHQ/rasa#4170]
**Rasa version**:
1.0.8
**Rasa X version** (if used & relevant):
stable version
**Python version**:
3.6.8
**Operating system** (windows, osx, ...):
Ubuntu 16.04.6 LTS
**Issue**:
When i tried access the rasa x page, i got the following error.

ScreenShot:
![Screen Shot 2019-08-05 at 09 04 44](https://user-images.githubusercontent.com/9349762/62442262-18a94280-b760-11e9-86aa-1e66e5e76044.png)

**Comment by sara-tagger** [comment]
Thanks for raising this issue, @Saladdin will get back to you about it soon✨

###### Please also check out the [docs](https://rasa.com/docs/) and the [forum](https://forum.rasa.com/) in case your issue was raised there too 🤗
