### ISSUE TITLE
Restart action is not working

### ISSUE THREAD

**Issue by stefandi94** [RasaHQ/rasa#4174]
**Rasa version**:
1.1.8(sdk - 1.1.1)

**Rasa X version** (if used & relevant):
0.19.0

**Python version**:
3.6.8

**Operating system** (windows, osx, ...):
Linux Mint 18.3

**Issue**:
Restart action is not working. When I want to restart a conversation with "/restart" I get the following error: 
"W0805 15:59:15.651196 140599820920576 featurizers.py:239] Feature 'intent_restart' could not be found in feature map."
I have in domain action_restart listed in actions, and the problem is that conversation always continues where I have stopped.

**Error (including full traceback)**:
```
![Screenshot from 2019-08-05 16-08-20](https://user-images.githubusercontent.com/23586529/62470955-cf76e400-b79b-11e9-9cf1-fd35e8e4e8d4.png)

```

**Command or request that led to error**:
```
 /restart
```

**Content of domain file (domain.yml)** (if relevant):
```yml
actions:
- action_restart
```

**Comment by msamogh** [comment]
Do you have `MappingPolicy` included in your `config.yml`?

**Comment by stefandi94** [comment]
No, is it necessary in order to use restart action?

**Comment by msamogh** [comment]
Sorry, I didn't realize you were having `action_restart` included by yourself in the domain file. That is not necessary as this is a built-in action. Please remove it and retry.

**Comment by stefandi94** [comment]
I removed it, but still is working the same. Maybe have something because it uses FormPolicy and order of activation of polices cause this problem?

**Comment by msamogh** [comment]
Could you post the full contents of your domain, config and stories file(s)?
