### ISSUE TITLE
Rasa X Entity synonyms not deleted

### ISSUE THREAD

**Issue by rgstephens** [RasaHQ/rasa#4175]
**Rasa version**: 1.1.4

**Rasa X version**: 0.20.0

**Issue**:

I have a running Rasa X instance where I imported NLU data, a domain and stories. I then removed all of the data.

The Rasa X UI shows no NLU, Stories or domain data.

When I call get JSON [API](https://rasa.com/docs/rasa-x/api/rasa-x-http-api/#operation/getDataJson) there are no training examples but it shows that my entity synonyms are still in Rasa X.

This raises a couple of questions:

* Why doesn't the UI show my entity synonym data which is clearly still in the system?
* How do I delete my synonym data?

**Comment by sara-tagger** [comment]
Thanks for raising this issue, @gausie will get back to you about it soon✨

###### Please also check out the [docs](https://rasa.com/docs/) and the [forum](https://forum.rasa.com/) in case your issue was raised there too 🤗
