### ISSUE TITLE
Rasa X Domain & NLU Data Sync

### ISSUE THREAD

**Issue by rgstephens** [RasaHQ/rasa#4176]
**Description of Problem**: The Rasa X UI has separate Domain and NLU data. If you remove an intent from the domain, you will naturally get an inconsistency error until you remove the associated training data and visa versa.

**Overview of the Solution**: It would be nice to have the UI manage this for the user. Maybe remove the intents from that domain section and make an improved training (and stories) UI that allows the user to better manage bots with large amounts of data.

Show the hierarchy of intents and examples in the NLU training section. Allow the user to delete an intent at the top level and all underlying examples would be removed along with the associated domain declaration.

**Comment by sara-tagger** [comment]
Thanks for submitting this feature request 🚀@tmbo will get back to you about it soon!✨

**Comment by tmbo** [comment]
I think that is a great idea and should make removing intents / entities easier :+1: cc @abhilasharoy

**Comment by amn41** [comment]
I don't think this is something we should do in the UI. Consider some of the possible scenarios:
1. you want split an intent up into two intents, and you need to update the relevant stories and NLU data, and domain. 
2. you want to merge half of the utterances of intent A into intent B, and discard the other half. 
3. you actually want to remove an intent altogether and update all of the stories that contain it. 

Making bigger, disruptive changes is something you want to do locally on a branch, which means you have access to your text editor, find & replace, etc. There is no way we could cover all of these cases 'automagically' in the Rasa X UI so better off letting the developer have the flexibility of the tools they know.

**Comment by alexweidauer** [comment]
Thank you for raising this issue about Rasa X. We decided to stop supporting the Community Edition (free version) of ‘Rasa X’ (see more info here: https://rasa.com/blog/rasa-x-community-edition-changes/). That’s why we’ve closed your issue. We suggest that Rasa Enterprise customers raise the issue with our customer support team if they haven’t done so already.
