### ISSUE TITLE
Rasa X Deploy to a Server 

### ISSUE THREAD

**Issue by lenpetlyak** [RasaHQ/rasa#4181]
I'm running this example https://rasa.com/docs/rasa-x/deploy/ on Ubuntu 19.04 on localhost. 
But it doesn't run the app, so I didn't see UI in my localhost.
To reproduce the error, the following commands can be run: 
curl -sSL -o install.sh https://storage.googleapis.com/rasa-x-releases/stable/install.sh
sudo bash ./install.s
cd /etc/rasa
sudo docker-compose up -d

As the app I used https://github.com/RasaHQ/rasa-x-demo
Thanks

**Comment by sara-tagger** [comment]
Thanks for raising this question, @Saladdin will get back to you about it soon!✨

###### The [forum](https://forum.rasa.com/) might also be a good place for this discussion 🙂
