### ISSUE TITLE
Custom component is not working after uploading model via Rasa X

### ISSUE THREAD

**Issue by TatianaParshina** [RasaHQ/rasa#4183]
**Rasa X version** (if used & relevant):
0.19.5 Installed using docker:
https://storage.googleapis.com/rasa-x-releases/0.19.5/install.sh

**Python version**:
3.6

**Operating system** (windows, osx, ...):
Debian 4.9.168

**Issue**:
I have uploaded the model on my Google Cloud VM instance with Rasa X by using the command:
```
curl -k -F "model=@model_name" http://hostname/api/projects/default/models?api_token=xxxxxxx
```
I have run `docker down` and `docker up` command after it and changed the model to Production in UI. The bot is working and replying correctly in most cases. 
However, the logic of the custom component is not applied. 
1. I have checked the configuration in Rasa X UI. It has a default configuration and doesn't have my custom configuration. Can I check config file somewhere on the instance? Because /etc/rasa directory doesn't have it.
```
pipeline: supervised_embeddings
language: en
policies:
- name: MemoizationPolicy
- name: KerasPolicy
- name: MappingPolicy
```
2. The second issue is the error that `ModuleNotFoundError: No module named 'components'`.
Should I manually save custom components in the /etc/rasa/ dir (the same as for actions)?

**Error**:
Logs from 'sudo docker-compose logs -f'
```
rasa-worker_1      | 2019-08-07 06:20:51 ERROR    rasa.core.agent  - An exception was raised while fetching a model. Continuing anyways...
rasa-worker_1      | Traceback (most recent call last):
rasa-worker_1      |   File "/usr/local/lib/python3.6/site-packages/rasa/nlu/registry.py", line 141, in get_component_class
rasa-worker_1      |     return class_from_module_path(component_name)
rasa-production_1  |   File "/usr/local/lib/python3.6/site-packages/rasa/core/interpreter.py", line 245, in __init__
rasa-production_1  |     self._load_interpreter()
rasa-production_1  |   File "/usr/local/lib/python3.6/site-packages/rasa/core/interpreter.py", line 265, in _load_interpreter
rasa-worker_1      |   File "/usr/local/lib/python3.6/site-packages/rasa/utils/common.py", line 188, in class_from_module_path
rasa-production_1  |     self.interpreter = Interpreter.load(self.model_directory)
rasa-worker_1      |     m = importlib.import_module(module_name)
rasa-production_1  |   File "/usr/local/lib/python3.6/site-packages/rasa/nlu/model.py", line 301, in load
rasa-worker_1      |   File "/usr/local/lib/python3.6/importlib/__init__.py", line 126, in import_module
rasa-production_1  |     return Interpreter.create(model_metadata, component_builder, skip_validation)
rasa-worker_1      |     return _bootstrap._gcd_import(name[level:], package, level)
rasa-production_1  |   File "/usr/local/lib/python3.6/site-packages/rasa/nlu/model.py", line 323, in create
rasa-production_1  |     components.validate_requirements(model_metadata.component_classes)
rasa-worker_1      |   File "<frozen importlib._bootstrap>", line 994, in _gcd_import
rasa-worker_1      |   File "<frozen importlib._bootstrap>", line 971, in _find_and_load
rasa-production_1  |   File "/usr/local/lib/python3.6/site-packages/rasa/nlu/components.py", line 36, in validate_requirements
rasa-production_1  |     component_class = registry.get_component_class(component_name)
rasa-production_1  |   File "/usr/local/lib/python3.6/site-packages/rasa/nlu/registry.py", line 150, in get_component_class
rasa-worker_1      |   File "<frozen importlib._bootstrap>", line 941, in _find_and_load_unlocked
rasa-worker_1      |   File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
rasa-worker_1      |   File "<frozen importlib._bootstrap>", line 994, in _gcd_import
rasa-worker_1      |   File "<frozen importlib._bootstrap>", line 971, in _find_and_load
rasa-worker_1      |   File "<frozen importlib._bootstrap>", line 953, in _find_and_load_unlocked
rasa-worker_1      | ModuleNotFoundError: No module named 'components'
```

**Comment by psds01** [comment]
Does this custom component work on your local system local?
Was is "registered"?
After pushing the new model with custom component, did you restart `rasa x`? If not, it might be using the old configs and all.

**Comment by TatianaParshina** [comment]
@psds01 thank you for your reply! I have updated the issue with stack trace from the docker with the error. 
Yes, my custom component works on the local system. Yes, I restarted docker using `docker-compose down` and `docker-compose up -d` commands. 
How can I find config.yml if I uploaded model via UI?

**Comment by psds01** [comment]
**Component**:
Sorry, little confused. Are these components not written _inside_ the rasa library?
If not, it will not work. These components have to be written in `/rasa/nlu/xxx` where `xxx` is the relevant component `module` like `classifiers` or `extractors`. After that, "register" that component class in `/rasa/nlu/registry.py` manually or add it as a part of the pipeline.
Check this out: https://github.com/psds01/rasa_custom/

**Comment by psds01** [comment]
Check this out for adding custom components to rasa: https://github.com/psds01/rasa_custom

**Comment by TatianaParshina** [comment]
@psds01 thank you for the proposed package. But I am not going to replace rasa code. 
I want to use the official rasa code. I want to know how to run a custom component on Google Cloud if I installed rasa x using docker and uploaded model via UI.

**Comment by psds01** [comment]
In that case, check this out: https://blog.rasa.com/enhancing-rasa-nlu-with-custom-components/

1) Write the components in the bot folder and add bot folder path to PYTHONPATH
2) then
```yml
pipeline:
 ...
- name: "my_custom_component_file.MyCustomComponentClass"
 ... 
```

**Comment by akelad** [comment]
@TatianaParshina sorry about not getting back to you sooner, have you tried with a newer Rasa X version? 0.20.1 for example. There was a bug with loading custom components before. You also need to mount the custom component to your container

**Comment by TatianaParshina** [comment]
@akelad , it is still not working. What I did:
- Updated Rasa X stable version using https://storage.googleapis.com/rasa-x-releases/stable/install.sh
- Mounted `components` folder with custom py script to my image in `docker-compose.override.yml` file:
```
services:
  app:
    restart: always
    image: "image-name:latest"
    volumes:
      - ./actions:/app/actions
      - ./components:/app/components
    expose:
      - "5055"
    depends_on:
      - rasa-production
```
- I tried to copy `components` folder with custom py script to image as well in Dockerfile:
```
FROM rasa/rasa-sdk:latest
COPY ./components/ /app/components/
```

**Comment by akelad** [comment]
how do you refer to the custom component in your config? and also, was there any extra python packages you use in your custom code?

**Comment by TatianaParshina** [comment]
@akelad  Config is working on the local environment:
`- name: "components.spell_checker.SpellCheckerTokenizer"`

Yes, I have extra python packages, for example, `pandas`. I install them by using `RUN` command in Dockerfile: 

`RUN pip install pandas`

Do you have any example of `Dockerfile` and `docker-compose.override.yml` with the custom component? I saw only examples of custom actions. Custom actions with extra python packages work fine for me.

**Comment by akelad** [comment]
oh wait, actually are you just loading this in the custom actions docker image? It should be the `rasa` image you're extending, since that's where the model will be loaded. So basically extending the dockerfile to install that, and mounting the custom component to it

**Comment by TatianaParshina** [comment]
@akelad yes, I load it in the custom actions docker image. Do you have any example of how to do it for the custom component (rasa demo code or tutorials)?

**Comment by akelad** [comment]
It's pretty much the exact same procedure as with the actions image, but you do it with the rasa image instead. So e.g. build a docker image with this Dockerfile:

```
FROM rasa/rasa:1.2.7-full
RUN pip install pandas
```

And then in the docker-compose.override.yml:
```
services:
  rasa-production:
    restart: always
    image: "new-rasa-image"
    volumes:
      - ./components:/app/components
  rasa-worker:
    restart: always
    image: "new-rasa-image"
    volumes:
      - ./components:/app/components
```

**Comment by akelad** [comment]
i'm gonna close this issue now as it's more of a usage question. If you need further help, please post on the [forum](https://forum.rasa.com) and we'll get back to you there
