### ISSUE TITLE
Fast rabbit publishing

### ISSUE THREAD

**Issue by wochinge** [RasaHQ/rasa#4193]
based on https://github.com/RasaHQ/rasa-x/issues/1065#issue-476191091

- [ ] keep rabbitmq message open and don't create a new one for every message
- [ ] check whether to use `SelectionConnection` from pika instead of the synchronous one

**Comment by wochinge** [comment]
@ricwo Are you tackling this issue this week or should I?

**Comment by ricwo** [comment]
I can do it this week 👍
