### ISSUE TITLE
Rasa X custom action found in domain but not in training data

### ISSUE THREAD

**Issue by rgstephens** [RasaHQ/rasa#4200]
**Rasa version**: 1.1.4

**Rasa X version**: 0.20.0

**Issue**:

I'm migrating existing bots to Rasa X and I'm receiving warnings under the Domain section of the UI for response templates/utterances associated with custom actions. The warning is:

`The action utter_xyzzy was found in the domain but is missing in the training data`

*training data* in this case is referring to the bot stories and the message is correct that I don't have any example stories that use `utter_xyzzy`.

The problem is, I've never seen any Rasa docs or example bots where utterances associated with custom actions are used in stories. The Rasa documentation for custom actions shows stories associated with the custom actions and these stories don't include the custom action utterances.

I also reviewed the recent [medicare_locator](https://github.com/RasaHQ/medicare_locator) example bot which has some custom actions and associated utterances and there are no stories that show the utterances.

I think either these warnings should be removed or the Rasa docs and migration/upgrade documentation needs to address the value or requirement for stories that use these custom action utterances. **Is there any value in putting the utterances in these stories?** My thinking is that it's not a good idea because the utterances are coded into the bots actions.py file and that putting it into stories is an unnecessary duplication.

**Comment by sara-tagger** [comment]
Thanks for the issue, @tmbo will get back to you about it soon!

###### You may find help in the [docs](https://rasa.com/docs/) and the [forum,](https://forum.rasa.com/) too 🤗

**Comment by tmbo** [comment]
I think the warning is correct, it is referring to the actions section, not the templates:
* you need to list all your utterance in the `templates` section
* **only if** you are using the template directly as an action, you need to list it in `actions`

So in your case, you only need to list the templates in the templates section and remove them from the actions list (it has always been like that, in earlier versions there was no warning though).

**Comment by rgstephens** [comment]
Thanks, I think my confusion is in the use of the term `training data` in the message.

It would be more helpful to the user if the message said:

`The action utter_xyzzy was found in the **actions** but is missing in the **templates**`

I also have instances where my data is in the template but missing in actions so it would be more clear if that message said:

`The action utter_xyzzy was found in the **templates** but is missing in the **actions**`

**Comment by rgstephens** [comment]
I just updated to `0.20.2` and am having more problems with importing response templates. I have about 300 response templates in a `domain.yml`. Of those **10** are used as a template in an action.

If I remove the 290 that are not used as templates in actions, I get 290 errors stating that the template is missing from the domain. If I click on the `Copy to the domain` option next to the warning, it adds the template to the `actions` section but @tmbo stated above that it should not be in the actions section, only the `templates` section.
