### ISSUE TITLE
Multiple projects for a single rasa instance

### ISSUE THREAD

**Issue by jahirfiquitiva** [RasaHQ/rasa#4201]
**Description of Problem**:
In pre-1.x versions of rasa, one could train different projects with different models and of course different training data.

When one initialized rasa, one could specify the models folders containing each one of those projects.

Then the HTTP API also allowed specifying which project to run actions against to ... for example, the `parse` endpoint could be used like:
```bash
curl -X POST localhost:5000/parse -d '{"query":"Hola", "project": "myproject"}'
```

I'm unable to find documentation to achieve the same with a single rasa 1.x instance

Thanks in advance

**Comment by sara-tagger** [comment]
Thanks for submitting this feature request 🚀@Ghostvv will get back to you about it soon!✨

**Comment by amn41** [comment]
hi @jahirfiquitiva ! discussion is here https://github.com/RasaHQ/rasa/issues/3259
