### ISSUE TITLE
Rasa X Response template display issues

### ISSUE THREAD

**Issue by rgstephens** [RasaHQ/rasa#4202]
**Rasa version**: 1.1.4

**Rasa X version**: 0.20.0

I've imported a domain file that is 3,000 lines long and 2,100 of those lines are associated with 280 response templates. The domain page of the UI only shows the first 13 lines of the templates. The remaining ~2,080 lines are displayed as blank lines (the UI essentially display 2,080 new lines or <p>).

I think the real issue here is best addressed by not showing templates, see #4185, but if templates are going to be displayed, this issue should be addressed.

There's a similar issue with the Responses page of the Rasa X UI. When I browse to that page, it shows 61 of my 280 templates followed by a bunch (20-40) of empty template blocks. If I start browsing around the page, doing browser and UI searches, more of my templates start showing up.  Seems like there's a pagination issue associated with the UI retrieving the templates from the database.

**Comment by sara-tagger** [comment]
Thanks for the issue, @MetcalfeTom will get back to you about it soon!

###### You may find help in the [docs](https://rasa.com/docs/) and the [forum,](https://forum.rasa.com/) too 🤗

**Comment by MetcalfeTom** [comment]
Also added to the backlog.  Thanks for your continued reporting @rgstephens

**Comment by akelad** [comment]
@gausie you may have some input on what's going on there?

**Comment by gausie** [comment]
@akelad I'm not sure, we'll need to try to set up a similar set of data on our end

**Comment by akelad** [comment]
@rgstephens do you know if this is still an issue?

**Comment by rgstephens** [comment]
No, I haven't tried this in a while. I will make a note to test it on the latest release.

**Comment by welkin91** [comment]
the issue still exist!
