### ISSUE TITLE
RASA NLU not extracting entities 

### ISSUE THREAD

**Issue by prathap9000** [RasaHQ/rasa#4203]
rasa-core                 0.13.8               
rasa-core-sdk             0.12.2                 
rasa-nlu                  0.14.6  

i have created training data and trained my model using spacy_sklearn pipeline .
entity extraction is working for keywords mentioned in training data , but for other keywords it is not 
attached my training data file
 
below is the sample conversation

```
Your input ->  show traffic news                                                                          
i can definitely help you , the top 5 news of the traffic

Your input ->  show office news                                                                           
surely,I can help you , the top 5 news of the traffic
```

below is config file i have used 

```
language: "en"

pipeline: "spacy_sklearn"
```

[nul_data.txt](https://github.com/RasaHQ/rasa/files/3480126/nul_data.txt)

**Comment by sara-tagger** [comment]
Thanks for raising this question, @tabergma will get back to you about it soon!✨

###### The [forum](https://forum.rasa.com/) might also be a good place for this discussion 🙂

**Comment by tabergma** [comment]
@prathap9000 You should ask questions in our [forum](https://forum.rasa.com/). GitHub is only for bugs and feature requests.
I'll close this issue. Please ask the question in the forum. Thanks.
