### ISSUE TITLE
Fatal error - engineio.server  - https://mysite.com is not an accepted origin. after upgrade

### ISSUE THREAD

**Issue by EmannuelRoque** [RasaHQ/rasa#4204]
**Rasa version**:
Rasa 1.2.2

**Rasa X version** (if used & relevant):

**Python version**:
Python 3.6.8

**Operating system** (windows, osx, ...):
ubuntu server

**Issue**:

After run 
pip3 install rasa --upgrade

I started to get the message:
engineio.server  - https://mysite.com is not an accepted origin.

Now my webchat is broken and I'm stuck !!!

It seems to be related to cors but I tried the command above and still it didn't work.

rasa run --m models/dialogue --enable-api --debug --endpoints endpoints.yml --credentials credentials.yml --cors '*'

Thanks !

**Error (including full traceback)**:
```
2019-08-08 06:37:12 DEBUG    pykwalify.compat  - Using yaml library: /usr/local/lib/python3.6/dist-packages/ruamel/yaml/__init__.py
2019-08-08 06:37:19 INFO     engineio.server  - https://myip.com is not an accepted origin.


```

**Command or request that led to error**:
```
        rasa run --m models/dialogue --enable-api --debug --endpoints endpoints.yml --credentials credentials.yml --cors '*'

```

**Content of configuration file (config.yml)** (if relevant):
```yml

```

**Content of domain file (domain.yml)** (if relevant):
```yml

```

**Comment by sara-tagger** [comment]
Thanks for the issue, @wochinge will get back to you about it soon!

###### You may find help in the [docs](https://rasa.com/docs/) and the [forum,](https://forum.rasa.com/) too 🤗

**Comment by wochinge** [comment]
@EmannuelRoque On which machine is your Rasa server running and on which machine is the socketio input running?

**Comment by EmannuelRoque** [comment]
I have the following structure:
- webchat (hosted on site)
- nginx proxy server (to generate https)
- server running core (proxy redirects from internal board)
- server running actions (internal card)

The chrome console shows this message:

chatb-ibegi.php?c=1041100906&p=363&t=bBsul:1 Access to XMLHttpRequest at 'https://bot.ctips.biz/ibegi/socket.io/?EIO=3&transport=polling&t=MnnxFS0' from origin 'https://resolveja.com' has been blocked by CORS policy: The value of the 'Access-Control-Allow-Credentials' header in the response is '' which must be 'true' when the request's credentials mode is 'include'. The credentials mode of requests initiated by the XMLHttpRequest is controlled by the withCredentials attribute.
webchat-5.js:33 GET https://bot.ctips.biz/ibegi/socket.io/?EIO=3&transport=polling&t=MnnxFS0 net::ERR_FAILED
l.create @ webchat-5.js:33
l @ webchat-5.js:33
c.request @ webchat-5.js:33
c.doPoll @ webchat-5.js:33
l.poll @ webchat-5.js:26
l.doOpen @ webchat-5.js:26
i.open @ webchat-5.js:6
l.open @ webchat-5.js:33
l @ webchat-5.js:33
l @ webchat-5.js:33
h.open.h.connect @ webchat-5.js:26
(anonymous) @ webchat-5.js:26
setTimeout (async)
h.reconnect @ webchat-5.js:26
(anonymous) @ webchat-5.js:26
(anonymous) @ webchat-5.js:26
r.emit @ webchat-5.js:6
l.onError @ webchat-5.js:33
(anonymous) @ webchat-5.js:33
r.emit @ webchat-5.js:6
i.onError @ webchat-5.js:6
(anonymous) @ webchat-5.js:33
r.emit @ webchat-5.js:6
l.onError @ webchat-5.js:33
(anonymous) @ webchat-5.js:33
setTimeout (async)
hasXDR.n.onreadystatechange @ webchat-5.js:33
XMLHttpRequest.send (async)
l.create @ webchat-5.js:33
l @ webchat-5.js:33
c.request @ webchat-5.js:33
c.doPoll @ webchat-5.js:33
l.poll @ webchat-5.js:26
l.doOpen @ webchat-5.js:26
i.open @ webchat-5.js:6
l.open @ webchat-5.js:33
l @ webchat-5.js:33
l @ webchat-5.js:33
h.open.h.connect @ webchat-5.js:26
(anonymous) @ webchat-5.js:26
setTimeout (async)
h.reconnect @ webchat-5.js:26
(anonymous) @ webchat-5.js:26
(anonymous) @ webchat-5.js:26
r.emit @ webchat-5.js:6
l.onError @ webchat-5.js:33
(anonymous) @ webchat-5.js:33
r.emit @ webchat-5.js:6
i.onError @ webchat-5.js:6
(anonymous) @ webchat-5.js:33
r.emit @ webchat-5.js:6
l.onError @ webchat-5.js:33
(anonymous) @ webchat-5.js:33
setTimeout (async)
hasXDR.n.onreadystatechange @ webchat-5.js:33
XMLHttpRequest.send (async)
l.create @ webchat-5.js:33
l @ webchat-5.js:33
c.request @ webchat-5.js:33
c.doPoll @ webchat-5.js:33
l.poll @ webchat-5.js:26
l.doOpen @ webchat-5.js:26
i.open @ webchat-5.js:6
l.open @ webchat-5.js:33
l @ webchat-5.js:33
l @ webchat-5.js:33
h.open.h.connect @ webchat-5.js:26
(anonymous) @ webchat-5.js:26
setTimeout (async)
h.reconnect @ webchat-5.js:26
(anonymous) @ webchat-5.js:26
(anonymous) @ webchat-5.js:26
r.emit @ webchat-5.js:6
l.onError @ webchat-5.js:33
(anonymous) @ webchat-5.js:33
r.emit @ webchat-5.js:6
i.onError @ webchat-5.js:6
(anonymous) @ webchat-5.js:33
r.emit @ webchat-5.js:6
l.onError @ webchat-5.js:33
(anonymous) @ webchat-5.js:33
setTimeout (async)
hasXDR.n.onreadystatechange @ webchat-5.js:33
XMLHttpRequest.send (async)
l.create @ webchat-5.js:33
l @ webchat-5.js:33
c.request @ webchat-5.js:33
c.doPoll @ webchat-5.js:33
l.poll @ webchat-5.js:26
l.doOpen @ webchat-5.js:26
i.open @ webchat-5.js:6
l.open @ webchat-5.js:33
l @ webchat-5.js:33
l @ webchat-5.js:33
h.open.h.connect @ webchat-5.js:26
(anonymous) @ webchat-5.js:26
setTimeout (async)
h.reconnect @ webchat-5.js:26
(anonymous) @ webchat-5.js:26
(anonymous) @ webchat-5.js:26
r.emit @ webchat-5.js:6
l.onError @ webchat-5.js:33
(anonymous) @ webchat-5.js:33
r.emit @ webchat-5.js:6
i.onError @ webchat-5.js:6
(anonymous) @ webchat-5.js:33
r.emit @ webchat-5.js:6
l.onError @ webchat-5.js:33
(anonymous) @ webchat-5.js:33
setTimeout (async)
hasXDR.n.onreadystatechange @ webchat-5.js:33
XMLHttpRequest.send (async)
l.create @ webchat-5.js:33
l @ webchat-5.js:33
c.request @ webchat-5.js:33
c.doPoll @ webchat-5.js:33
l.poll @ webchat-5.js:26
l.doOpen @ webchat-5.js:26
i.open @ webchat-5.js:6
l.open @ webchat-5.js:33
l @ webchat-5.js:33
l @ webchat-5.js:33
h.open.h.connect @ webchat-5.js:26
(anonymous) @ webchat-5.js:26
setTimeout (async)
h.reconnect @ webchat-5.js:26
(anonymous) @ webchat-5.js:26
(anonymous) @ webchat-5.js:26
r.emit @ webchat-5.js:6
l.onError @ webchat-5.js:33
(anonymous) @ webchat-5.js:33
r.emit @ webchat-5.js:6
i.onError @ webchat-5.js:6
(anonymous) @ webchat-5.js:33
r.emit @ webchat-5.js:6
l.onError @ webchat-5.js:33
(anonymous) @ webchat-5.js:33
setTimeout (async)
hasXDR.n.onreadystatechange @ webchat-5.js:33
XMLHttpRequest.send (async)
l.create @ webchat-5.js:33
l @ webchat-5.js:33
c.request @ webchat-5.js:33
c.doPoll @ webchat-5.js:33
l.poll @ webchat-5.js:26
l.doOpen @ webchat-5.js:26
i.open @ webchat-5.js:6
l.open @ webchat-5.js:33
l @ webchat-5.js:33
l @ webchat-5.js:33
h.open.h.connect @ webchat-5.js:26
(anonymous) @ webchat-5.js:26
setTimeout (async)
h.reconnect @ webchat-5.js:26
(anonymous) @ webchat-5.js:26
(anonymous) @ webchat-5.js:26
r.emit @ webchat-5.js:6
l.onError @ webchat-5.js:33
(anonymous) @ webchat-5.js:33
r.emit @ webchat-5.js:6
i.onError @ webchat-5.js:6
(anonymous) @ webchat-5.js:33
r.emit @ webchat-5.js:6
l.onError @ webchat-5.js:33
(anonymous) @ webchat-5.js:33
setTimeout (async)
hasXDR.n.onreadystatechange @ webchat-5.js:33
XMLHttpRequest.send (async)
l.create @ webchat-5.js:33
l @ webchat-5.js:33
c.request @ webchat-5.js:33
c.doPoll @ webchat-5.js:33
l.poll @ webchat-5.js:26
l.doOpen @ webchat-5.js:26
i.open @ webchat-5.js:6
l.open @ webchat-5.js:33
l @ webchat-5.js:33
l @ webchat-5.js:33
h.open.h.connect @ webchat-5.js:26
(anonymous) @ webchat-5.js:26
setTimeout (async)
h.reconnect @ webchat-5.js:26
(anonymous) @ webchat-5.js:26
(anonymous) @ webchat-5.js:26
r.emit @ webchat-5.js:6
l.onError @ webchat-5.js:33
(anonymous) @ webchat-5.js:33
r.emit @ webchat-5.js:6
i.onError @ webchat-5.js:6
(anonymous) @ webchat-5.js:33
r.emit @ webchat-5.js:6
l.onError @ webchat-5.js:33
(anonymous) @ webchat-5.js:33
setTimeout (async)
hasXDR.n.onreadystatechange @ webchat-5.js:33
XMLHttpRequest.send (async)
l.create @ webchat-5.js:33
l @ webchat-5.js:33
c.request @ webchat-5.js:33
c.doPoll @ webchat-5.js:33
l.poll @ webchat-5.js:26
l.doOpen @ webchat-5.js:26
i.open @ webchat-5.js:6
l.open @ webchat-5.js:33
l @ webchat-5.js:33
l @ webchat-5.js:33
h.open.h.connect @ webchat-5.js:26
(anonymous) @ webchat-5.js:26
setTimeout (async)
h.reconnect @ webchat-5.js:26
(anonymous) @ webchat-5.js:26
(anonymous) @ webchat-5.js:26
r.emit @ webchat-5.js:6
l.onError @ webchat-5.js:33
(anonymous) @ webchat-5.js:33
r.emit @ webchat-5.js:6
i.onError @ webchat-5.js:6
(anonymous) @ webchat-5.js:33
r.emit @ webchat-5.js:6
l.onError @ webchat-5.js:33
(anonymous) @ webchat-5.js:33
setTimeout (async)
hasXDR.n.onreadystatechange @ webchat-5.js:33
XMLHttpRequest.send (async)
l.create @ webchat-5.js:33
l @ webchat-5.js:33
c.request @ webchat-5.js:33
c.doPoll @ webchat-5.js:33
l.poll @ webchat-5.js:26
l.doOpen @ webchat-5.js:26
i.open @ webchat-5.js:6
l.open @ webchat-5.js:33
l @ webchat-5.js:33
l @ webchat-5.js:33
h.open.h.connect @ webchat-5.js:26
(anonymous) @ webchat-5.js:26
setTimeout (async)
h.reconnect @ webchat-5.js:26
(anonymous) @ webchat-5.js:26
(anonymous) @ webchat-5.js:26
r.emit @ webchat-5.js:6
l.onError @ webchat-5.js:33
(anonymous) @ webchat-5.js:33
r.emit @ webchat-5.js:6
i.onError @ webchat-5.js:6
(anonymous) @ webchat-5.js:33
r.emit @ webchat-5.js:6
l.onError @ webchat-5.js:33
(anonymous) @ webchat-5.js:33chatb-ibegi.php?c=1041100906&p=363&t=bBsul:1 Access to XMLHttpRequest at 'https://bot.ctips.biz/ibegi/socket.io/?EIO=3&transport=polling&t=MnnxFS0' from origin 'https://resolveja.com' has been blocked by CORS policy: The value of the 'Access-Control-Allow-Credentials' header in the response is '' which must be 'true' when the request's credentials mode is 'include'. The credentials mode of requests initiated by the XMLHttpRequest is controlled by the withCredentials attribute.
webchat-5.js:33 GET https://bot.ctips.biz/ibegi/socket.io/?EIO=3&transport=polling&t=MnnxFS0 net::ERR_FAILED
l.create @ webchat-5.js:33
l @ webchat-5.js:33
c.request @ webchat-5.js:33
c.doPoll @ webchat-5.js:33
l.poll @ webchat-5.js:26
l.doOpen @ webchat-5.js:26
i.open @ webchat-5.js:6
l.open @ webchat-5.js:33
l @ webchat-5.js:33
l @ webchat-5.js:33
h.open.h.connect @ webchat-5.js:26
(anonymous) @ webchat-5.js:26
setTimeout (async)
h.reconnect @ webchat-5.js:26
(anonymous) @ webchat-5.js:26
(anonymous) @ webchat-5.js:26
r.emit @ webchat-5.js:6
l.onError @ webchat-5.js:33
(anonymous) @ webchat-5.js:33
r.emit @ webchat-5.js:6
i.onError @ webchat-5.js:6
(anonymous) @ webchat-5.js:33
r.emit @ webchat-5.js:6
l.onError @ webchat-5.js:33
(anonymous) @ webchat-5.js:33
setTimeout (async)
hasXDR.n.onreadystatechange @ webchat-5.js:33
XMLHttpRequest.send (async)
l.create @ webchat-5.js:33
l @ webchat-5.js:33
c.request @ webchat-5.js:33
c.doPoll @ webchat-5.js:33
l.poll @ webchat-5.js:26
l.doOpen @ webchat-5.js:26
i.open @ webchat-5.js:6
l.open @ webchat-5.js:33
l @ webchat-5.js:33
l @ webchat-5.js:33
h.open.h.connect @ webchat-5.js:26
(anonymous) @ webchat-5.js:26
setTimeout (async)
h.reconnect @ webchat-5.js:26
(anonymous) @ webchat-5.js:26
(anonymous) @ webchat-5.js:26
r.emit @ webchat-5.js:6
l.onError @ webchat-5.js:33
(anonymous) @ webchat-5.js:33
r.emit @ webchat-5.js:6
i.onError @ webchat-5.js:6
(anonymous) @ webchat-5.js:33
r.emit @ webchat-5.js:6
l.onError @ webchat-5.js:33
(anonymous) @ webchat-5.js:33
setTimeout (async)
hasXDR.n.onreadystatechange @ webchat-5.js:33
XMLHttpRequest.send (async)
l.create @ webchat-5.js:33
l @ webchat-5.js:33
c.request @ webchat-5.js:33
c.doPoll @ webchat-5.js:33
l.poll @ webchat-5.js:26
l.doOpen @ webchat-5.js:26
i.open @ webchat-5.js:6
l.open @ webchat-5.js:33
l @ webchat-5.js:33
l @ webchat-5.js:33
h.open.h.connect @ webchat-5.js:26
(anonymous) @ webchat-5.js:26
setTimeout (async)
h.reconnect @ webchat-5.js:26
(anonymous) @ webchat-5.js:26
(anonymous) @ webchat-5.js:26
r.emit @ webchat-5.js:6
l.onError @ webchat-5.js:33
(anonymous) @ webchat-5.js:33
r.emit @ webchat-5.js:6
i.onError @ webchat-5.js:6
(anonymous) @ webchat-5.js:33
r.emit @ webchat-5.js:6
l.onError @ webchat-5.js:33
(anonymous) @ webchat-5.js:33
setTimeout (async)
hasXDR.n.onreadystatechange @ webchat-5.js:33
XMLHttpRequest.send (async)
l.create @ webchat-5.js:33
l @ webchat-5.js:33
c.request @ webchat-5.js:33
c.doPoll @ webchat-5.js:33
l.poll @ webchat-5.js:26
l.doOpen @ webchat-5.js:26
i.open @ webchat-5.js:6
l.open @ webchat-5.js:33
l @ webchat-5.js:33
l @ webchat-5.js:33
h.open.h.connect @ webchat-5.js:26
(anonymous) @ webchat-5.js:26
setTimeout (async)
h.reconnect @ webchat-5.js:26
(anonymous) @ webchat-5.js:26
(anonymous) @ webchat-5.js:26
r.emit @ webchat-5.js:6
l.onError @ webchat-5.js:33
(anonymous) @ webchat-5.js:33
r.emit @ webchat-5.js:6
i.onError @ webchat-5.js:6
(anonymous) @ webchat-5.js:33
r.emit @ webchat-5.js:6
l.onError @ webchat-5.js:33
(anonymous) @ webchat-5.js:33
setTimeout (async)
hasXDR.n.onreadystatechange @ webchat-5.js:33
XMLHttpRequest.send (async)
l.create @ webchat-5.js:33
l @ webchat-5.js:33
c.request @ webchat-5.js:33
c.doPoll @ webchat-5.js:33
l.poll @ webchat-5.js:26
l.doOpen @ webchat-5.js:26
i.open @ webchat-5.js:6
l.open @ webchat-5.js:33
l @ webchat-5.js:33
l @ webchat-5.js:33
h.open.h.connect @ webchat-5.js:26
(anonymous) @ webchat-5.js:26
setTimeout (async)
h.reconnect @ webchat-5.js:26
(anonymous) @ webchat-5.js:26
(anonymous) @ webchat-5.js:26
r.emit @ webchat-5.js:6
l.onError @ webchat-5.js:33
(anonymous) @ webchat-5.js:33
r.emit @ webchat-5.js:6
i.onError @ webchat-5.js:6
(anonymous) @ webchat-5.js:33
r.emit @ webchat-5.js:6
l.onError @ webchat-5.js:33
(anonymous) @ webchat-5.js:33
setTimeout (async)
hasXDR.n.onreadystatechange @ webchat-5.js:33
XMLHttpRequest.send (async)
l.create @ webchat-5.js:33
l @ webchat-5.js:33
c.request @ webchat-5.js:33
c.doPoll @ webchat-5.js:33
l.poll @ webchat-5.js:26
l.doOpen @ webchat-5.js:26
i.open @ webchat-5.js:6
l.open @ webchat-5.js:33
l @ webchat-5.js:33
l @ webchat-5.js:33
h.open.h.connect @ webchat-5.js:26
(anonymous) @ webchat-5.js:26
setTimeout (async)
h.reconnect @ webchat-5.js:26
(anonymous) @ webchat-5.js:26
(anonymous) @ webchat-5.js:26
r.emit @ webchat-5.js:6
l.onError @ webchat-5.js:33
(anonymous) @ webchat-5.js:33
r.emit @ webchat-5.js:6
i.onError @ webchat-5.js:6
(anonymous) @ webchat-5.js:33
r.emit @ webchat-5.js:6
l.onError @ webchat-5.js:33
(anonymous) @ webchat-5.js:33
setTimeout (async)
hasXDR.n.onreadystatechange @ webchat-5.js:33
XMLHttpRequest.send (async)
l.create @ webchat-5.js:33
l @ webchat-5.js:33
c.request @ webchat-5.js:33
c.doPoll @ webchat-5.js:33
l.poll @ webchat-5.js:26
l.doOpen @ webchat-5.js:26
i.open @ webchat-5.js:6
l.open @ webchat-5.js:33
l @ webchat-5.js:33
l @ webchat-5.js:33
h.open.h.connect @ webchat-5.js:26
(anonymous) @ webchat-5.js:26
setTimeout (async)
h.reconnect @ webchat-5.js:26
(anonymous) @ webchat-5.js:26
(anonymous) @ webchat-5.js:26
r.emit @ webchat-5.js:6
l.onError @ webchat-5.js:33
(anonymous) @ webchat-5.js:33
r.emit @ webchat-5.js:6
i.onError @ webchat-5.js:6
(anonymous) @ webchat-5.js:33
r.emit @ webchat-5.js:6
l.onError @ webchat-5.js:33
(anonymous) @ webchat-5.js:33
setTimeout (async)
hasXDR.n.onreadystatechange @ webchat-5.js:33
XMLHttpRequest.send (async)
l.create @ webchat-5.js:33
l @ webchat-5.js:33
c.request @ webchat-5.js:33
c.doPoll @ webchat-5.js:33
l.poll @ webchat-5.js:26
l.doOpen @ webchat-5.js:26
i.open @ webchat-5.js:6
l.open @ webchat-5.js:33
l @ webchat-5.js:33
l @ webchat-5.js:33
h.open.h.connect @ webchat-5.js:26
(anonymous) @ webchat-5.js:26
setTimeout (async)
h.reconnect @ webchat-5.js:26
(anonymous) @ webchat-5.js:26
(anonymous) @ webchat-5.js:26
r.emit @ webchat-5.js:6
l.onError @ webchat-5.js:33
(anonymous) @ webchat-5.js:33
r.emit @ webchat-5.js:6
i.onError @ webchat-5.js:6
(anonymous) @ webchat-5.js:33
r.emit @ webchat-5.js:6
l.onError @ webchat-5.js:33
(anonymous) @ webchat-5.js:33
setTimeout (async)
hasXDR.n.onreadystatechange @ webchat-5.js:33
XMLHttpRequest.send (async)
l.create @ webchat-5.js:33
l @ webchat-5.js:33
c.request @ webchat-5.js:33
c.doPoll @ webchat-5.js:33
l.poll @ webchat-5.js:26
l.doOpen @ webchat-5.js:26
i.open @ webchat-5.js:6
l.open @ webchat-5.js:33
l @ webchat-5.js:33
l @ webchat-5.js:33
h.open.h.connect @ webchat-5.js:26
(anonymous) @ webchat-5.js:26
setTimeout (async)
h.reconnect @ webchat-5.js:26
(anonymous) @ webchat-5.js:26
(anonymous) @ webchat-5.js:26
r.emit @ webchat-5.js:6
l.onError @ webchat-5.js:33
(anonymous) @ webchat-5.js:33
r.emit @ webchat-5.js:6
i.onError @ webchat-5.js:6
(anonymous) @ webchat-5.js:33
r.emit @ webchat-5.js:6
l.onError @ webchat-5.js:33
(anonymous) @ webchat-5.js:33
setTimeout (async)
hasXDR.n.onreadystatechange @ webchat-5.js:33
XMLHttpRequest.send (async)
l.create @ webchat-5.js:33
l @ webchat-5.js:33
c.request @ webchat-5.js:33
c.doPoll @ webchat-5.js:33
l.poll @ webchat-5.js:26
l.doOpen @ webchat-5.js:26
i.open @ webchat-5.js:6
l.open @ webchat-5.js:33
l @ webchat-5.js:33
l @ webchat-5.js:33
h.open.h.connect @ webchat-5.js:26
(anonymous) @ webchat-5.js:26
setTimeout (async)
h.reconnect @ webchat-5.js:26
(anonymous) @ webchat-5.js:26
(anonymous) @ webchat-5.js:26
r.emit @ webchat-5.js:6
l.onError @ webchat-5.js:33
(anonymous) @ webchat-5.js:33
r.emit @ webchat-5.js:6
i.onError @ webchat-5.js:6
(anonymous) @ webchat-5.js:33
r.emit @ webchat-5.js:6
l.onError @ webchat-5.js:33
(anonymous) @ webchat-5.js:33
setTimeout (async)
hasXDR.n.onreadystatechange @ webchat-5.js:33
XMLHttpRequest.send (async)
l.create @ webchat-5.js:33
l @ webchat-5.js:33
c.request @ webchat-5.js:33
c.doPoll @ webchat-5.js:33
l.poll @ webchat-5.js:26
l.doOpen @ webchat-5.js:26
i.open @ webchat-5.js:6
l.open @ webchat-5.js:33
l @ webchat-5.js:33
l @ webchat-5.js:33
h.open.h.connect @ webchat-5.js:26
(anonymous) @ webchat-5.js:26
setTimeout (async)
h.reconnect @ webchat-5.js:26
(anonymous) @ webchat-5.js:26
(anonymous) @ webchat-5.js:26
r.emit @ webchat-5.js:6
l.onError @ webchat-5.js:33
(anonymous) @ webchat-5.js:33
r.emit @ webchat-5.js:6
i.onError @ webchat-5.js:6
(anonymous) @ webchat-5.js:33
r.emit @ webchat-5.js:6
l.onError @ webchat-5.js:33
(anonymous) @ webchat-5.js:33
setTimeout (async)
hasXDR.n.onreadystatechange @ webchat-5.js:33
webchat-5.js:33 Error: xhr poll error
    at c.i.onError (webchat-5.js:6)
    at l.<anonymous> (webchat-5.js:33)
    at l.r.emit (webchat-5.js:6)
    at l.onError (webchat-5.js:33)
    at webchat-5.js:33
setTimeout (async)
hasXDR.n.onreadystatechange @ webchat-5.js:33
XMLHttpRequest.send (async)
l.create @ webchat-5.js:33
l @ webchat-5.js:33
c.request @ webchat-5.js:33
c.doPoll @ webchat-5.js:33
l.poll @ webchat-5.js:26
l.doOpen @ webchat-5.js:26
i.open @ webchat-5.js:6
l.open @ webchat-5.js:33
l @ webchat-5.js:33
l @ webchat-5.js:33
h.open.h.connect @ webchat-5.js:26
(anonymous) @ webchat-5.js:26
setTimeout (async)
h.reconnect @ webchat-5.js:26
(anonymous) @ webchat-5.js:26
(anonymous) @ webchat-5.js:26
r.emit @ webchat-5.js:6
l.onError @ webchat-5.js:33
(anonymous) @ webchat-5.js:33
r.emit @ webchat-5.js:6
i.onError @ webchat-5.js:6
(anonymous) @ webchat-5.js:33
r.emit @ webchat-5.js:6
l.onError @ webchat-5.js:33
(anonymous) @ webchat-5.js:33
setTimeout (async)
hasXDR.n.onreadystatechange @ webchat-5.js:33
XMLHttpRequest.send (async)
l.create @ webchat-5.js:33
l @ webchat-5.js:33
c.request @ webchat-5.js:33
c.doPoll @ webchat-5.js:33
l.poll @ webchat-5.js:26
l.doOpen @ webchat-5.js:26
i.open @ webchat-5.js:6
l.open @ webchat-5.js:33
l @ webchat-5.js:33
l @ webchat-5.js:33
h.open.h.connect @ webchat-5.js:26
(anonymous) @ webchat-5.js:26
setTimeout (async)
h.reconnect @ webchat-5.js:26
(anonymous) @ webchat-5.js:26
(anonymous) @ webchat-5.js:26
r.emit @ webchat-5.js:6
l.onError @ webchat-5.js:33
(anonymous) @ webchat-5.js:33
r.emit @ webchat-5.js:6
i.onError @ webchat-5.js:6
(anonymous) @ webchat-5.js:33
r.emit @ webchat-5.js:6
l.onError @ webchat-5.js:33
(anonymous) @ webchat-5.js:33
setTimeout (async)
hasXDR.n.onreadystatechange @ webchat-5.js:33
webchat-5.js:33 Error: xhr poll error
    at c.i.onError (webchat-5.js:6)
    at l.<anonymous> (webchat-5.js:33)
    at l.r.emit (webchat-5.js:6)
    at l.onError (webchat-5.js:33)
    at webchat-5.js:33

**Comment by EmannuelRoque** [comment]
Work around:
pip3 uninstall python-engineio
pip3 install python-socketio==4.2.0

**Comment by jwjuven** [comment]
I had same issues in ubuntu 18.0.4. It worked fine in windows platform.
My environment is as follows:
Rasa version: Rasa 1.2.1
Rasa X version (if used & relevant):
Python version: Python 3.6.8
Operating system (windows, osx, ...): ubuntu server 18.0.4
Chat: webchat
I started rasa in ubuntu 18.0.4 to get the message:
engineio.server - http://jw.ngrok2.xiaomiqiu..cn is not an accepted origin.(http://jw.ngrok2.xiaomiqiu..cn is my ngrok tunnel for http://localhost:80).

**Comment by jwjuven** [comment]
I have solved the issues. Because the version of python-engineio is 3.9.2 in ubuntu, it will work fine after I downgraded python-engineio from 3.9.2 to 3.8.1.

**Comment by wochinge** [comment]
@jwjuven Did you get any insights why `python-engineio` does not support this?

**Comment by whiteyhat** [comment]
No Idea why is this happening, but I got the same issue..

**Comment by guilherme1guy** [comment]
Just updated to Rasa 1.2.3 and this started to happen to me too. Downgrading `python-engineio` to 3.8.1 worked for me.

**Comment by wochinge** [comment]
We will release a new version `1.2.4` which should fix this. Could you please check if that resolves your issue? 
The PR for that is https://github.com/RasaHQ/rasa/pulls?q=is%3Apr+is%3Aclosed

**Comment by whiteyhat** [comment]
> We will release a new version `1.2.4` which should fix this. Could you please check if that resolves your issue?
> The PR for that is https://github.com/RasaHQ/rasa/pulls?q=is%3Apr+is%3Aclosed

Wonderful news! Any estimation about when this new release is coming out?

**Comment by wochinge** [comment]
Already released https://pypi.org/project/rasa/1.2.4/ 🎉

**Comment by avinash10xds** [comment]
This is what I got when i installed the latest rasa = 1.2.4 , please help me

![engine](https://user-images.githubusercontent.com/50192566/63668888-12096a80-c7f6-11e9-9fdc-f406af5b38e4.jpg)

**Comment by wochinge** [comment]
@akelad Not entirely sure from the message of you and Tom in the PR, but did we have time to test it with `4.3.1`?

**Comment by akelad** [comment]
Yes I tested it with that and the python-engineio method that’s pinned and it worked fine
