### ISSUE TITLE
rasa test nlu -u option doesn't handle exception correctly

### ISSUE THREAD

**Issue by wangjin2000** [RasaHQ/rasa#4206]
**Rasa version**: 1.1.8

**Rasa X version** (if used & relevant):

**Python version**: 3.73

**Operating system** (windows, osx, ...): Linux version 4.4.0-139-generic (buildd@lcy01-amd64-006) (gcc version 5.4.0 20160609 (Ubuntu 5.4.0-6ubuntu1~16.04.10) ) #165-Ubuntu SMP Wed Oct 24 10:58:50 UTC 2018

**Issue**:
When run command:
 rasa test nlu -u ./train_test_split/test_file, 
if the test_file doesn't exist, the program didn't generate an exception message, instead, it uses the default folder "data" as testing data source and generate a set of performance metrics. This will confuse users for the incorrect testing results.

**Error (including full traceback)**:
```

```

**Command or request that led to error**:
```

```

**Content of configuration file (config.yml)** (if relevant):
```yml

```

**Content of domain file (domain.yml)** (if relevant):
```yml

```

**Comment by sara-tagger** [comment]
Thanks for raising this issue, @Ghostvv will get back to you about it soon✨

###### Please also check out the [docs](https://rasa.com/docs/) and the [forum](https://forum.rasa.com/) in case your issue was raised there too 🤗

**Comment by tabergma** [comment]
@wangjin2000 This is actually the behaviour for almost all rasa commands. So, I would not necessarily throw an exception. But we should at least print a warning, informing the user about that the provided file was not found and the default location was used instead.

Do you want to tackle this yourself and submit a PR for this?

**Comment by wangjin2000** [comment]
Thanks for your response. In my point of view, the default value only be used is the parameter is not specified.  If the parameter is used but not correct, we should report it as an error, other than a warning and continue running.Anyway, I would like let you handle this issue.Thanks again!
Jin
    On Friday, August 9, 2019, 06:49:34 PM GMT+8, Tanja <notifications@github.com> wrote:  
 
 
@wangjin2000 This is actually the behaviour for almost all rasa commands. So, I would not necessarily throw an exception. But we should at least print a warning, informing the user about that the provided file was not found and the default location was used instead.

Do you want to tackle this yourself and submit a PR for this?
