### ISSUE TITLE
Rasa exception whentrying to handle webhook for facebook messenger

### ISSUE THREAD

**Issue by akasha1618** [RasaHQ/rasa#4207]
Hello ! I got an error when I message my bot on facebook and it's not working.Secret,Callback,verify everything is set ok. I used ngrok for public callback url so i replaced http://localhost:5005/webhooks/facebook/webhook with http://8d78102e/webhooks/facebook/webhook . 

this is what I got on the ngrok terminal:
```
ngrok by @inconshreveable                                                                          

Session Status                online
Session Expires               7 hours, 41 minutes
Version                       2.3.34
Region                        United States (us)
Web Interface                 http://127.0.0.1:4040
Forwarding                    http://8d78102e.ngrok.io -> http://localhost:5005
Forwarding                    https://8d78102e.ngrok.io -> http://localhost:5005

Connections                   ttl     opn     rt1     rt5     p50     p90
                              7       0       0.00    0.00    2.16    5.40

HTTP Requests
-------------

POST /webhooks/facebook/webhook 200 OK
GET  /webhooks/facebook/webhook 200 OK
GET  /                          404 Not Found
GET  /                          404 Not Found
GET  /                          404 Not Found
GET  /favicon.ico               404 Not Found
GET  /webhooks/facebook/webhook 200 OK
```

**Rasa version**: Rasa 1.1.5

**Python version**:3.7

**Operating system** (windows, osx, ...): windows 

**Issue**: Exception when trying to handle webhook for facebook messenger

**Error (including full traceback)**: 

```
2019-08-08 14:33:49 ERROR    rasa.core.channels.facebook  - Exception when trying to handle webhook for facebook message.
Traceback (most recent call last):
  File "c:\program files\python37\lib\site-packages\rasa\core\channels\facebook.py", line 108, in _handle_user_message
    await self.on_new_message(user_msg)
  File "c:\program files\python37\lib\site-packages\rasa\core\channels\channel.py", line 65, in handler
    await app.agent.handle_message(*args, **kwargs)
  File "c:\program files\python37\lib\site-packages\rasa\core\agent.py", line 448, in handle_message
    return await processor.handle_message(message)
  File "c:\program files\python37\lib\site-packages\rasa\core\processor.py", line 84, in handle_message
    await self._predict_and_execute_next_action(message, tracker)
  File "c:\program files\python37\lib\site-packages\rasa\core\processor.py", line 350, in _predict_and_execute_next_action
    action, tracker, message.output_channel, self.nlg, policy, confidence
  File "c:\program files\python37\lib\site-packages\rasa\core\processor.py", line 460, in _run_action
    await self._send_bot_messages(events, tracker, output_channel)
  File "c:\program files\python37\lib\site-packages\rasa\core\processor.py", line 382, in _send_bot_messages
    await output_channel.send_response(tracker.sender_id, e.message())
  File "c:\program files\python37\lib\site-packages\rasa\core\channels\channel.py", line 172, in send_response
    await self.send_text_message(recipient_id, message.pop("text"), **message)
  File "c:\program files\python37\lib\site-packages\rasa\core\channels\facebook.py", line 142, in send_text_message
    self.send(recipient_id, FBText(text=message_part))
  File "c:\program files\python37\lib\site-packages\rasa\core\channels\facebook.py", line 134, in send
    self.messenger_client.send(element.to_dict(), recipient_id, "RESPONSE")
  File "c:\program files\python37\lib\site-packages\fbmessenger\__init__.py", line 89, in send
    'id': entry['sender']['id']
TypeError: string indices must be integers
```

**credentials.yml**
```
rest:
#  # you don't need to provide anything here - this channel doesn't
#  # require any credentials


facebook:
  verify: "rasa-bot"
  secret: "SECRET"
  page-access-token: "TOKEN"


rasa:
  url: "http://localhost:5002/api"
```

**Comment by sara-tagger** [comment]
Thanks for raising this issue, @Ghostvv will get back to you about it soon✨

###### Please also check out the [docs](https://rasa.com/docs/) and the [forum](https://forum.rasa.com/) in case your issue was raised there too 🤗

**Comment by akasha1618** [comment]
@sara-tagger  @Ghostvv  any answer??

**Comment by Ghostvv** [comment]
@akasha1618 sorry for late reply. Is this discussion relevant: https://github.com/RasaHQ/rasa/issues/4103?

**Comment by MetcalfeTom** [comment]
@akasha1618 can you try updating to the latest rasa release?

Also what version of `fbmessenger` is installed?

**Comment by erohmensing** [comment]
That callback url doesn't look quite right either, I think it should be 
`http://8d78102e.ngrok.io/webhooks/facebook/webhook`

**Comment by akasha1618** [comment]
> That callback url doesn't look quite right either, I think it should be
> `http://8d78102e.ngrok.io/webhooks/facebook/webhook`

The callback URL on the messenger app is https://8d78102e.ngrok.io/webhooks/facebook/webhook
Still not working. What should be to problem?

**Comment by erohmensing** [comment]
Are you still getting the "string indices must be integers" problem or a new one? What versions of `rasa` and `fbmessenger` are installed?

**Comment by collinsonyemaobi** [comment]
Hello, Any Solution To this not working https://8d78102e.ngrok.io/webhooks/facebook/webhook - I am having a similar issue infact i have also tried with  ngrok http 5005 -bind-tls=true
 and still did not work

**Comment by collinsonyemaobi** [comment]
> That callback url doesn't look quite right either, I think it should be
> `http://8d78102e.ngrok.io/webhooks/facebook/webhook`

This hasn't worked for me

**Comment by akasha1618** [comment]
Try to  do this:
Rasa run
Rasa run actions
Open ngrok http 5005
Go to developers facebook and verifiy if the token is the same as in your credentials, copy from facebook and paste it again in uour crrdentials.yml (this is important, because the token will change on developers.facebook.com and you have to change it to your credentials again) I think this is the problem


When you close your Visual studio or terminal or pc do this steps again and I recommened a free accont with ngrok. 
I hope this helps!

**Comment by akasha1618** [comment]
http://8d78102e.ngrok.io/webhooks/facebook/webhook Is not working you need the https version.

**Comment by collinsonyemaobi** [comment]
Thanks but even
By testing the below locally still didn't work.

http://localhost:5005/webhooks/facebook/webhook

**Comment by collinsonyemaobi** [comment]
> Try to do this:
> Rasa run
> Rasa run actions
> Open ngrok http 5005
> Go to developers facebook and verifiy if the token is the same as in your credentials, copy from facebook and paste it again in uour crrdentials.yml (this is important, because the token will change on developers.facebook.com and you have to change it to your credentials again) I think this is the problem
> 
> When you close your Visual studio or terminal or pc do this steps again and I recommened a free accont with ngrok.
> I hope this helps!

Thanks for your response,

I Have repeated all the steps again and it is still unable to validate the url

I am not sure it is an issue with ngrok because the local link is also not working well
http://localhost:5005/webhooks/facebook/webhook

I also suspect I might not be doing things right on endpoints.yml

action_endpoint:
  url: http://localhost:5005/webhook


Please is the action_endpoint correct? Could that make the webhook url not working?

Thanks

**Comment by erohmensing** [comment]
So to be clear @akasha1618 you were able to get it running right?

**Comment by kbirkbr** [comment]
Any solution to this? I am also facing this issue.
