### ISSUE TITLE
making it easier to debug custom action code

### ISSUE THREAD

**Issue by TyDunn** [RasaHQ/rasa#4212]
It is very difficult to debug custom action code because each time you test, you have to start the action server, start rasa shell, chat with your bot until you get to the point were the custom action is triggered, and then see if it works.

It would be great if you could create a derivative of the UnitTest class that loads an exported conversation state and calls the action that you want to test.

This would be a small abstraction that serves as a test helper to create a tracker from a dumped state and runs the action.

**Comment by sara-tagger** [comment]
Thanks for submitting this feature request 🚀@tyd will get back to you about it soon!✨

**Comment by Krogsager** [comment]
I don't mean to dump my broken code on you, but I was trying to write a test yesterday, and maybe it is in the right path? (I only started using mock last week so it is not working correctly)

```
from actions.actions import ActionLibraryOpeningHours as aloh
from unittest.mock import Mock, patch


class Test_message_output(unittest.TestCase):

    def fake_get_slot(self, slot):
        #support function
        return {'location': 'risskov','time': '2019-12-12'}[slot] # the action needs two slots
        
    @patch('actions.actions.Tracker.get_slot', side_effect=fake_get_slot)
    @patch('actions.actions.CollectingDispatcher.utter_message', side_effect= lambda x: print(x))
    def test_actions_run(self,mock_dispatcher, mock_tracker): #decorators are applied buttom-up.
        """
        The test should return true.
        The custom action gets two slots from fake_get_slot() and return a message. For this test 
        nothing is asserted, but the message is printed to the console.
        """

        aloh().run(dispatcher=mock_dispatcher, tracker=mock_tracker, domain=None)

        self.assertIsNotNone([])


```

**Comment by JulianGerhard21** [comment]
Hi @TyDunn ,

wouldn't a more or less "simple" solution to write a test that does:

```
exported_tracker_state = load_exported_tracker_state()
sys.path.insert(1, os.environ['BOT_EXECUTION_PATH'])
executor = ActionExecutor()
executor.register_package('actions')
try:
    response = await executor.run(json_body)
except:
    action_name = json_body.get("next_action")
    exception = ActionExecutionRejection(
        action_name, "Modified CustomAction threw ActionExecutionRejection."
    )
    logger.error(exception.message)
    raise exception
validate_action_Response(response)
```
This way, there's won't be the neccessity to explicitely start the ActionServer. I am not familiar however, with the current best practice to load a conversation state hence I only hinted it.

Kind regards
Julian

**Comment by tmbo** [comment]
@JulianGerhard21 yes exactly. the goal is to make it easier to test and provide some tooling around making the testing of custom actions easier.

**Comment by koaning** [comment]
I was thinking about this today as well. A source of inspiration might be [fastapi](https://fastapi.tiangolo.com/tutorial/testing/) and [click](https://click.palletsprojects.com/en/7.x/testing/). Both of these tools offer a testing client. 

Maybe something like; 

```
from action import MyCustomAction
from rasa.testing import Client 

@pytest.fixture()
def action_client():
    return Client(CustomAction())

def test_hello(action_client): 
    action_client.invoke({entitties: ..., text: ...})
```

**Comment by ArjaanBuijk** [comment]
What if `rasa test` would include the action server during testing of e2e stories.

Then debugging actions would become very easy.

Just start up the action server in your favorite IDE, and in a separate terminal run rasa test with a story that triggers the action you want to debug.

**Comment by koaning** [comment]
I sort of wrote an idea for this while working on a [demo bot](https://github.com/RasaHQ/stroopbot). The goal of the custom action is to behave like a fallback. It show buttons representing intents that it is considering. 

```python
from typing import Any, Text, Dict, List

from rasa_sdk import Action, Tracker
from rasa_sdk.executor import CollectingDispatcher


class ActionCustomFallback(Action):

    def name(self) -> Text:
        return "action_custom_fallback"

    def run(self, dispatcher: CollectingDispatcher,
            tracker: Tracker,
            domain: Dict[Text, Any]) -> List[Dict[Text, Any]]:
        
        intents = [i for i in tracker.current_state()['latest_message']['intent_ranking'] if i['name'] != 'nlu_fallback']
        print(intents[:5])
        allowed_intents = ["new_order", "what_happened", "inform"]
        message = {
            "new_order": "Do you want to place a new order?",
            "what_happened": "Do you want to ask about a previous order?",
            "inform": "Would you like more information about stroopwafels?"
        }
        buttons = [{'payload': i['name'], 'title': message[i['name']]} for i in intents[:3] if i['name'] in allowed_intents]
        dispatcher.utter_message(text="It wasn't 100% clear what you meant. Could you speficy/rephrase?")
        dispatcher.utter_message(buttons = buttons)
        return []
```

I wanted to test this, so I hashed this together. 

```python
class TestClient:
    def __init__(self, action):
        self.action = action
    
    def invoke_message(self, message, slots=tuple()):
        dispatcher = CollectingDispatcher()
        
        tracker = Tracker(
            sender_id=str(uuid.uuid4()), 
            slots=slots, 
            latest_message=message, 
            events=[], 
            paused=False, 
            followup_action=False, 
            active_loop={}, 
            latest_action_name=None
        )
        
        domain = {}
        
        slots = self.action.run(dispatcher=dispatcher, tracker=tracker, domain=domain)
        return dispatcher.messages, slots
```

This allowed me to write a test like; 

```python
def test_basic_usecase():
    action = ActionCustomFallback()
    client = TestClient(action=action)
    messages, slots = client.invoke_message(message=message)
    text_msg, button_msg = messages
    
    assert "Could you speficy/rephrase?" in text_msg["text"]
    assert len(button_msg['buttons']) == 3
```

It's nowhere near general, but it suits my purposes for now. Just to check though; @ArjaanBuijk @wochinge @TyDunn might this be something worthwhile for me to explore more generally? Feel free to say no, but it feels like a `TestClient` object can prevent a whole lot of bugs.

**Comment by Vishal-Malo** [comment]
> It is very difficult to debug custom action code because each time you test, you have to start the action server, start rasa shell, chat with your bot until you get to the point were the custom action is triggered, and then see if it works.
> 
> It would be great if you could create a derivative of the UnitTest class that loads an exported conversation state and calls the action that you want to test.
> 
> This would be a small abstraction that serves as a test helper to create a tracker from a dumped state and runs the action.

Is this issue open? I wan't to contribute.
