### ISSUE TITLE
The whole Core model is retrained even if only the templates section is changed

### ISSUE THREAD

**Issue by msamogh** [RasaHQ/rasa#4216]
**Description of Problem**:
Having to retrain the Core ML model every time templates are changed is unnecessary and can be very expensive for a large project with lots of stories.

**Overview of the Solution**:
Create a separate, more granular fingerprint for the templates section in the domain and if only that has changed, simply replace that section in the new model and not retrain Core.

**Examples** (if relevant):

**Blockers** (if relevant):

**Definition of Done**:
- [ ] Tests are added
- [ ] Features described in the docs
- [ ] Feature mentioned in the changelog
- [ ] Any updates in Rasa X?

**Comment by ortsaCniveK** [comment]
This is the default behavior;  the way to avoid retraining with template changes is to use an [External CMS](https://rasa.com/docs/rasa/core/responses/#managing-assistant-utterances-using-an-external-cms).

If there are no changes to the domain or the training data Rasa already prevents redundant training.

**Comment by nbeuchat** [comment]
> This is the default behavior; the way to avoid retraining with template changes is to use an External CMS.
I don't think the choice of using an external CMS or not should penalize you with unnecessary training time. A change in the text or triggers of the template does not change the outcome of the core model training and is therefore unnecessary, don't you think?

**Comment by wochinge** [comment]
@msamogh this should be `in progress`, shouldn't it?

**Comment by msamogh** [comment]
Yes. Thanks for noticing!

**Comment by akelad** [comment]
@btotharye additionally to what it says in the issue description here, someone mentioned recently that sometimes NLU retrains if some parts of the domain are changed as well. So we should look into what's going on there

**Comment by wochinge** [comment]
So @btotharye is gonna finish up https://github.com/RasaHQ/rasa/pull/4251 ?

**Comment by btotharye** [comment]
> So @btotharye is gonna finish up #4251 ?

Hrm didn't know that was already out there, should I start with that PR code?

**Comment by wochinge** [comment]
Why isn't @msamogh finishing this up and you @btotharye tackle the NLU part from @akelad 's comment?

**Comment by btotharye** [comment]
I'm good with that if everyone agrees

**Comment by akelad** [comment]
haha my bad - i assumed this wasn't being tackled since @msamogh had unassigned himself

**Comment by akelad** [comment]
@btotharye have you looked into the other part yet?

**Comment by wochinge** [comment]
I close this issue now since the nlu part is covered in #4691
