### ISSUE TITLE
Incompatibility error doesn't show minimum version 

### ISSUE THREAD

**Issue by msamogh** [RasaHQ/rasa#4220]
**Rasa version**: 1.1.7

**Rasa X version** (if used & relevant): 0.19.1

**Python version**:

**Operating system** (windows, osx, ...):

**Issue**:
This warning is displayed every time Rasa X is started.
```python
rasa-x_1  | Version of model model.tar.gz version is not compatible. The model was trained with Rasa version 1.1.7 but the current Rasa requires a minimum version of None.Please retrain your model with a more recent Rasa version.
```

**Command or request that led to error**:
```
rasa x
```

**Comment by wochinge** [comment]
it's a timing problem since the Rasa server is not ready yet.
