### ISSUE TITLE
rasa core and rasa nlu

### ISSUE THREAD

**Issue by pratikh07** [RasaHQ/rasa#4224]
AttributeError: 'ApixuClient' object has no attribute 'getcurrent'

im facing this error please help me

**Comment by sara-tagger** [comment]
Thanks for the question, our Github issue board is for **bugs and feature requests only,** though 😕
Please ask this question in the [forum✨](https://forum.rasa.com/c/rasa)

###### If you were describing a bug, please create a [report](https://github.com/RasaHQ/rasa/issues/new?labels=bug&template=bug_report.md) and fill out the template
