### ISSUE TITLE
rasa chatbot duckling implementation issue

### ISSUE THREAD

**Issue by IKhushi** [RasaHQ/rasa#4227]
I'm currently working on rasa chatbot , I can install duckling but can not implement it in for time and date entity so pls help me if any one had already use it.
thank you

**Comment by sara-tagger** [comment]
Thanks for the question, our Github issue board is for **bugs and feature requests only,** though 😕
Please ask this question in the [forum✨](https://forum.rasa.com/c/rasa)

###### If you were describing a bug, please create a [report](https://github.com/RasaHQ/rasa/issues/new?labels=bug&template=bug_report.md) and fill out the template
