### ISSUE TITLE
Mapping Policy always predicts `action_listen` after finishing

### ISSUE THREAD

**Issue by dakshvar22** [RasaHQ/rasa#4247]
**Rasa version**: 1.2.2

**Python version**: 3.6

**Operating system** (windows, osx, ...): osx

**Issue**: Mapping Policy always predicts `action_listen` after it has executed the mapped action. This should be relaxed and a next action should be picked if predicted by any other policy.
Corresponding line - https://github.com/RasaHQ/rasa/blob/master/rasa/core/policies/mapping_policy.py#L112

Documentation also mentions this - https://rasa.com/docs/rasa/core/policies/#mapping-policy

**Content of domain file (domain.yml)** (if relevant):
```yml
intents:
  - chitchat:
      triggers: action_chitchat
```

**Comment by Ghostvv** [comment]
it looks like we should simply invert priorities between memo and mapping policies

**Comment by iszainab** [comment]
Hi, has this issue been resolved? I have ver 1.10.1 and I'm still facing the issue where mapping policy predicts action_listen every time after executing a mapped action.

**Comment by Ghostvv** [comment]
yes, it still does it. In Rasa 2.0, we substituted `MappingPolicy` with `RulePolicy` where prediction of `action_listen` can be configured
