### ISSUE TITLE
HTTP API - Cannot fetch /status for NLU-only model

### ISSUE THREAD

**Issue by Polarisation** [RasaHQ/rasa#4250]
**Rasa version**:
1.2.2 
(via Docker container: rasa/rasa:1.2.2-spacy-en)

**Issue**:
There is an endpoint /status as part of the HTTP API.
https://rasa.com/docs/rasa/api/http-api/#tag/Server-Information/paths/~1status/get

This returns some metadata about the currently loaded model, including the model file, trained date, Rasa version used for training, and more. (I'm mostly interested in obtaining the trained date).

After loading an NLU only model, the /status endpoint returns this error:

```
{
  ​code: 409,
  help: "https://rasa.com/docs/rasa/user-guide/running-the-server/",
  message: "No agent loaded. To continue processing, a model of a trained agent needs to be loaded.",
  reason: "Conflict",
  status: "failure",
  version: "1.2.2"
}
```

The error message is not particularly clear, but the referenced documentation page contains the following:

> If you start the server with an NLU-only model, not all the available endpoints can be called. Be aware that some endpoints will return a 409 status code, as a trained Core model is needed to process the request.

It looks to me like the /status endpoint is one of the endpoints that returns the 409 status code when an NLU-only model is loaded. But surely status should be available for any kind of model? Some of the metadata properties might not be relevant for an NLU-only model, but much of it is still useful.

It was possible to retrieve the model status in Rasa NLU 0.14.x. I believe the same should be possible in Rasa 1.x.

**Error (including full traceback)**:
```
{
  ​code: 409,
  help: "https://rasa.com/docs/rasa/user-guide/running-the-server/",
  message: "No agent loaded. To continue processing, a model of a trained agent needs to be loaded.",
  reason: "Conflict",
  status: "failure",
  version: "1.2.2"
}
```

**Command or request that led to error**:
```
HTTP GET /status
```

**Comment by sara-tagger** [comment]
Thanks for raising this issue, @dakshvar22 will get back to you about it soon✨

###### Please also check out the [docs](https://rasa.com/docs/) and the [forum](https://forum.rasa.com/) in case your issue was raised there too 🤗

**Comment by Polarisation** [comment]
See fix in the above pull request. I've tried the fix out with an NLU-only model and it now returns a 200 success response with all the expected fields. The bug was just a case of extra validation where it wasn't wanted.

**Comment by dakshvar22** [comment]
@Polarisation thanks for reporting this and sending a fix. The PR is under review internally. Thanks

**Comment by wochinge** [comment]
suggested solutions are in here https://github.com/RasaHQ/rasa/pull/4256#issuecomment-522496554

**Comment by tabergma** [comment]
fixed in https://github.com/RasaHQ/rasa/pull/4383
