### ISSUE TITLE
Allow for wildcard intents

### ISSUE THREAD

**Issue by ErikTromp** [RasaHQ/rasa#4255]
**Description of Problem**:
I have a use case where in some point in the dialogue flow, I do not care about the intent expressed by a user (nor NER). See: https://forum.rasa.com/t/wildcard-intent-without-form/14039/3.

**Overview of the Solution**:
A solution I am using now is to exhaustively list ALL known intents in my dialogue so it will always continue. This blows up training time and makes maintenance a lot harder. I would like to have a way to ignore the NLU output, modelling a wildcard intent like:

```
* question_i_do_not_care_about
- /ignore_intent
* another_question_i_do_not_care_about
- /ignore_intent
```

**Examples** (if relevant):
See forum post

**Blockers** (if relevant):

**Definition of Done**:
Wildcard intent must be present and documented

**Comment by akelad** [comment]
@ErikTromp thanks for the feature request, have you considered using forms for this?

**Comment by ErikTromp** [comment]
Yes I have considered it but correct me if I am wrong here - that would require me to make a unique field for every question I ask to store the response in, right? I would be against that for the same reason of exhaustively specifying all intents I have in my model: it's error-prone and hard to maintain.

**Comment by akelad** [comment]
forms are designed for slot filling, so if you're asking a user for a bunch of information.

Can you give an example of your use case? Because wildcard intents are not something that's easy to add, and we'd need to see a clear use case for it

**Comment by tmbo** [comment]
without a new use case, this gets resolved by https://github.com/RasaHQ/rasa/issues/1800
