### ISSUE TITLE
Rasa X Install Script

### ISSUE THREAD

**Issue by rgstephens** [RasaHQ/rasa#4261]
**Description of Problem**:
The docker install script cannot but run from RASA_HOME. There also seems to be an assumption that you might be running it from the home directory of an existing Rasa bot. Is that right? 

In step two of the docker install instructions, the user is told to run install.sh. That script will copy a credentials file to the RASA_HOME/credentials directory. If you're RASA_HOME this will fail.

Also, there's no mention before step #2 about copying an credentials file.

**Overview of the Solution**:
Document the fact that it cannot be run from RASA_HOME. Document copying of an existing credentials file and any other assumptions about migrating existing files/content.

Ideally, start over with a better documented install based around a couple of docker-compose files (CE & Enterprise). Don't use python and ansible. Tell the developer more details about the containers, images and volumes.

The bash and ansible scripts create more problems than they solve.

**Comment by sara-tagger** [comment]
Thanks for submitting this feature request 🚀@gausie will get back to you about it soon!✨

**Comment by TyDunn** [comment]
@rgstephens @tczekajlo Is this issue still relevant?

**Comment by tczekajlo** [comment]
> @rgstephens @tczekajlo Is this issue still relevant?

@TyDunn AFAIK nothing's changed (nothing that resolves described issue) in the ansible/install.sh script since @rgstephens created this issue.

**Comment by tmbo** [comment]
@tczekajlo Is this one actionable in a sense that we know what we want? 

I think with the helm changes incoming and the work on a dead simple way to deploy (e.g. all in one docker container) i am not sure there will be a need for the ansible / single line install scripts is there? Instead we should have good documentation on the helm charts as well as the all-in-one-docker. I don't think docker compose is a setup we'd want to support once we have the other two in place.

**Comment by tczekajlo** [comment]
It's a great question, I think the docker-compose and ansible is something that we'd like to drop at some point. I'll put the issue on hold for now until we clarified the future for ansible and docker-compose.

**Comment by tczekajlo** [comment]
This method is going to be dropped.
