### ISSUE TITLE
Adding support for running rasa in a single process

### ISSUE THREAD

**Issue by vonSchweetz** [RasaHQ/rasa#4262]
Follow up on (https://github.com/RasaHQ/rasa/issues/1601)

Hello! We are currently attempting to deploy our chatbot that uses RASA NLU (the latest version 1.2.3) on a VPS machine that does not support multi-processing. The issue and errors are exactly the same as the thread linked above since it is the same project.

Are there any updates on support for allowing running RASA in a single process? We can't deploy our chatbot until this feature is added. 

I don't have a lot of experience, but I can make the necessary modifications if some instructions are given. Thanks a lot!

**Comment by sara-tagger** [comment]
Thanks for submitting this feature request 🚀@dakshvar22 will get back to you about it soon!✨

**Comment by dakshvar22** [comment]
@vonSchweetz The training process runs in a single process as of now. That shouldn't be a problem. What part are you facing issues on?

**Comment by vonSchweetz** [comment]
@dakshvar22 You are right. I messed up and was working with the wrong (older) virtual environment. I checked with the new version and it seems to work fine. Thanks a lot ! (and sorry for the mistake)

**Comment by dakshvar22** [comment]
@vonSchweetz No problem. Good luck :)
