### ISSUE TITLE
Using liblinear instead of libsvm when kernal is `linear`

### ISSUE THREAD

**Issue by wegamekinglc** [RasaHQ/rasa#4268]
**Description of Problem**:
Currently no matter which kernal is used,  `SklearnIntentClassifier` will always `SVC` from the `libsvm` . However `LinearSVC` from `liblinear` will scale better to a large number of training samples

**Comment by sara-tagger** [comment]
Thanks for submitting this feature request 🚀@erohmensing will get back to you about it soon!✨

**Comment by Ghostvv** [comment]
`SklearnPolicy` will be deprecated in `3.0`
