### ISSUE TITLE
Starting a custom action server

### ISSUE THREAD

**Issue by PanderBoy18** [RasaHQ/rasa#4272]
How can I start my custom actions server?

My actions.py file is in /home/me/chatbot/actions.py
But when I run: `rasa run --actions /home/me/chatbot/actions.py` it says:

> rasa run: error: invalid choice: '/home/me/chatbot/actions.py' (choose from 'actions')

What am I doing wrong?

**Comment by dsmackie** [comment]
`rasa run actions`

**Comment by PanderBoy18** [comment]
That gives me this error:

> The path 'actions.py' does not exist. Please make sure to use the default location ('actions') or specify it with '--action'.

**Comment by dsmackie** [comment]
Where are you running the `rasa run actions` command from?

Can you verify that you are in the `/home/me/chatbot/` folder.

**Comment by PanderBoy18** [comment]
Thank you, I thought by giving the full path rasa had enough data... Didn't use cd /home/me/chatbot
