### ISSUE TITLE
Rasa X HTTP API Payload Schema is invalid

### ISSUE THREAD

**Issue by hungph-dev-ict** [RasaHQ/rasa#4275]
**Rasa version**:
1.2.3
**Rasa X version** (if used & relevant):
0.20.1
**Python version**:
3.7
**Operating system** (windows, osx, ...):
Ubuntu
**Issue**:
Error on call API /api/chat on port 5002 with Rasa X.
The payload schema is invalid.Please check the API specification.
With previous version, I don't got this error. Call chat API successful and return response text.
![image](https://user-images.githubusercontent.com/32316323/63235753-14ebe480-c265-11e9-86bc-e938ee59996d.png)

**Error (including full traceback)**:
```{"version":"0.20.1","status":"failure","message":"The payload schema is invalid.Please check the API specification at https:\/\/rasa.com\/docs\/rasa-x\/api\/rasa-x-http-api\/ for the correct schema.","reason":"WrongSchema","details":{"absolute_path":[],"absolute_schema_path":["required"],"args":["'message' is a required property",{},[],null,[],{},{},{},[],null],"cause":null,"context":[],"instance":{"messages":"Hi"},"message":"'message' is a required property","parent":null,"path":[],"relative_path":[],"relative_schema_path":["required"],"schema":{"type":"object","required":["message"],"properties":{"message":{"type":"string"}}},"schema_path":["required"],"validator":"required","validator_value":["message"]},"help":null,"code":400}%                                                                                                                                                               (base)  hani@hani-laptop  ~/Documents/hani_va/hani_rasa_vi  cur

```

**Command or request that led to error**:
```

```

**Content of configuration file (config.yml)** (if relevant):
```yml

```

**Content of domain file (domain.yml)** (if relevant):
```yml

```

**Comment by sara-tagger** [comment]
Thanks for the issue, @Saladdin will get back to you about it soon!

###### You may find help in the [docs](https://rasa.com/docs/) and the [forum,](https://forum.rasa.com/) too 🤗
