### ISSUE TITLE
how do I stop the training of RASA

### ISSUE THREAD

**Issue by Indranil-hue** [RasaHQ/rasa#4276]

**Comment by hungph-dev-ict** [comment]
No description in here but I think you can press Ctrl + C from ur command line

**Comment by Indranil-hue** [comment]
thanks @hungph-dev-ict  , can the same procedure be applied for disconnecting the ngrok server ,i am not able to disconnect the ngorok server

**Comment by hungph-dev-ict** [comment]
I think when you press Ctrl C, your model has not been trained and old models wil still be reused

**Comment by Indranil-hue** [comment]
thaanks @hungph-dev-ict
