### ISSUE TITLE
Windows installation from pip not working 

### ISSUE THREAD

**Issue by ccsv** [RasaHQ/rasa#4279]
The documentation is not clear on the needs for window prerequisites it says that you need to install "Microsoft VC++ Compiler"

I created a virtualenv and pip installed rasa as the directions instructed

The issue comes up when you pip install httptools.

"Error: Microsoft Visual C++ 14.0 is required. Get it with "Microsoft Visual C++ Build Tools:" https://visualstudio.microsoft.com/downloads/"

I tried installing the Visual C++ from https://visualstudio.microsoft.com/visual-cpp-build-tools/
but it did not work.

I also looked at installing Visual Studio from https://visualstudio.microsoft.com/downloads/ but it seems like there are lots of unnecessary programs about 2GB that I do not plan to use and I am not sure which is useful.

Can anyone update the documentation to work with pip + virtual environments.

**Comment by sara-tagger** [comment]
Thanks for the question, our Github issue board is for **bugs and feature requests only,** though 😕
Please ask this question in the [forum✨](https://forum.rasa.com/c/rasa)

###### If you were describing a bug, please create a [report](https://github.com/RasaHQ/rasa/issues/new?labels=bug&template=bug_report.md) and fill out the template
