### ISSUE TITLE
Improve Rasa CLI start-up time

### ISSUE THREAD

**Issue by federicotdn** [RasaHQ/rasa#4280]
**Rasa version**: `master`

**Python version**: `3.5`, `3.6`, `3.7`

**Operating system** (windows, osx, ...): GNU/Linux, macOS, Windows

**Issue**:

After a fresh `rasa` install, the `rasa` CLI can take up to 1.5 seconds (on my system) to show any output, even when no action has been specified (e.g. `rasa --help`). For workflows that involve running the `rasa` command various times, this can be an inconvenience. We should aim to lower the start-up time for the CLI to under 1 second, or another set number that users will be comfortable with.

Related to: https://github.com/RasaHQ/rasa/pull/4248 and https://github.com/RasaHQ/rasa/issues/3010.

Tools that could be useful:
- https://docs.python.org/3.7/library/profile.html
- https://github.com/jrfonseca/gprof2dot
- https://github.com/joerick/pyinstrument

**Comment by koaning** [comment]
During a recording I just noticed 10+ seconds. Now, we need to be careful here because the recording is most likely influencing the timing but it seems like Rasa currently can take an order of magnitude more than the 1.5 seconds mentioned in the issue.
