### ISSUE TITLE
Issue in mysql connection

### ISSUE THREAD

**Issue by shahad-bit** [RasaHQ/rasa#4284]
Rasa version: master
Rasa X version (if used & relevant): n/a
Python version: 3.6
Operating system (windows, osx, ...): centos

Hi, I am using MySQL tracker store. The chatbot is running in a docker container. it works fine at the beginning, but after a couple of hours,  sqlalchmey throws "lost connection error" when interacting with the chatbot, which causes "Can't reconnect until invalid transaction is rolled back" for the rest of the interactions.

I think it is due to wait session time, but I am not sure how to fix it.

here is lost connection error log:
```
 Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1244, in _execute_context
    cursor, statement, parameters, context
  File "/usr/local/lib/python3.6/site-packages/sqlalchemy/engine/default.py", line 550, in do_execute
    cursor.execute(statement, parameters)
  File "/usr/local/lib/python3.6/site-packages/pymysql/cursors.py", line 170, in execute
    result = self._query(query)
  File "/usr/local/lib/python3.6/site-packages/pymysql/cursors.py", line 328, in _query
    conn.query(q)
  File "/usr/local/lib/python3.6/site-packages/pymysql/connections.py", line 517, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "/usr/local/lib/python3.6/site-packages/pymysql/connections.py", line 732, in _read_query_result
    result.read()
  File "/usr/local/lib/python3.6/site-packages/pymysql/connections.py", line 1075, in read
    first_packet = self.connection._read_packet()
  File "/usr/local/lib/python3.6/site-packages/pymysql/connections.py", line 657, in _read_packet
    packet_header = self._read_bytes(4)
  File "/usr/local/lib/python3.6/site-packages/pymysql/connections.py", line 707, in _read_bytes
    CR.CR_SERVER_LOST, "Lost connection to MySQL server during query")
pymysql.err.OperationalError: (2013, 'Lost connection to MySQL server during query')

```

Thank you!

**Comment by sara-tagger** [comment]
Thanks for the question, our Github issue board is for **bugs and feature requests only,** though 😕
Please ask this question in the [forum✨](https://forum.rasa.com/c/rasa)

###### If you were describing a bug, please create a [report](https://github.com/RasaHQ/rasa/issues/new?labels=bug&template=bug_report.md) and fill out the template

**Comment by shahad-bit** [comment]
Thanks for the prompt reply.
I fixed it by extending session wait_timeout, though i think that it could be fixed from rasa. 
It seems that rasa creates only one connection with the database -for tracker stores-, which means that when it loses the connection, it will lose it forever -which causes this error-. (please correct me if i'm wrong). If this is the case, then reconnecting to the db from rasa, whenever the connection is lost, and adding rollback would fix the problem.

**Comment by alistefano** [comment]
I have some issue.
After some time I need to kill and restart my docker container with rasa/rasa-x. I don’t think it depends on the database: I tried both postgresql and sqlite. I think that it depends on how the connection is managed by rasa/sqlalchemy orm when rasa is deployed on docker.
If the connection is lost rasa can't recover it automatically and the chatbot stops to working.

other users have the same issue: https://forum.rasa.com/t/error-when-connect-rasa-to-postgresql-tracker-db/13914

**Comment by alebeta90** [comment]
Hi,

I have the same issue, with my docker deployment using pgsql. Maybe I could try @shahad-bit work around, but it should be fixed inside of Rasa code.
