### ISSUE TITLE
Make Domain accessible in NLU Pipeline

### ISSUE THREAD

**Issue by dakshvar22** [RasaHQ/rasa#4285]
**Description of Problem**:
Currently the `domain.yml` file is read and made accessible only in the Core pipeline. As we include more features into the complete stack, there may be some which do not follow the clear boundary between NLU and Core. One such example feature is [Supervised Response Selector](https://github.com/RasaHQ/rasa/issues/4266). The particular part where the domain file is needed is described in this [comment](https://github.com/RasaHQ/rasa/issues/4266#issuecomment-522460773) .
There may be more such use cases where this might be necessary.

**Overview of the Solution**:
* We'll need to move out `domain.py` outside of `rasa.core` since it would be shared between NLU and Core. 
* For the training phase, similar to how domain is loaded inside `_train_core_with_validated_data()` function we can load it inside `train_nlu_with_validated_data()` and pass it to `rasa.nlu.train()` function.
* Both `Trainer` and `TrainingData` could potentially need access to the `Domain` instance.
* During inference, individual components may need to use the domain data for processing the message.

**Blockers** (if relevant):
Any ideas?

**Definition of Done**:
- [ ] Tests are added
- [ ] Feature described the docs
- [ ] Feature mentioned in the changlog
- [ ] Compatibility test for existing features

**Comment by msamogh** [comment]
You'd also need to ensure the fingerprints don't step on each other, because right now, the whole domain just gets one single fingerprint.

**Comment by dakshvar22** [comment]
Not pursuing this for now, as the primary use case was solved in a different way https://github.com/RasaHQ/rasa/pull/4233
