### ISSUE TITLE
Compare stories button not accessible for long story names

### ISSUE THREAD

**Issue by ggdupont** [RasaHQ/rasa#4286]
**Rasa version**:
rasa==1.2.3
rasa-sdk==1.1.1

**Rasa X version** (if used & relevant):
rasa-x==0.20.1

**Python version**:
Python 3.7.4

**Operating system** (windows, osx, ...):
ubuntu 16.04

**Browser** 
Firefox 68.0.2

**Issue**:
In the Training>Stories panel, in the stories list, the width of the panel cannot be adjusted. If the stories titles are too long, we can't access the button for "Compare Multiple Stories".

<img width="813" alt="Screenshot 2019-08-20 at 16 14 02" src="https://user-images.githubusercontent.com/5583410/63354976-af335180-c365-11e9-9f80-15fda7c5730d.png">

**Error (including full traceback)**:
NA

**Command or request that led to error**:
NA

**Content of configuration file (config.yml)** (if relevant):
NA

**Content of domain file (domain.yml)** (if relevant):
NA

**Comment by sara-tagger** [comment]
Thanks for the issue, @tmbo will get back to you about it soon!

###### You may find help in the [docs](https://rasa.com/docs/) and the [forum,](https://forum.rasa.com/) too 🤗

**Comment by tmbo** [comment]
Yes that's a bug, we should fix that - thanks a lot for reporting :rocket:
