### ISSUE TITLE
Rasa x uploading train data doesn't provide any feedback

### ISSUE THREAD

**Issue by ggdupont** [RasaHQ/rasa#4287]
**Rasa version**:
rasa==1.2.3
rasa-sdk==1.1.1

**Rasa X version** (if used & relevant):
rasa-x==0.20.1

**Python version**:
Python 3.7.4

**Operating system** (windows, osx, ...):
ubuntu 16.04

**Browser** 
Firefox 68.0.2

**Issue**:
When uploading large training set (few thousands samples), it takes time to upload and then to update the samples list. In the meantime, there is no feedback on the status of the upload.

If it succeed, the time to reload the conversation is still not indicated.
If it failed, it is not clear where the error is (during upload? on the data format?)

**Error (including full traceback)**:
NA

**Command or request that led to error**:
NA
**Content of configuration file (config.yml)** (if relevant):
NA
**Content of domain file (domain.yml)** (if relevant):
NA

**Comment by sara-tagger** [comment]
Thanks for raising this issue, @gausie will get back to you about it soon✨

###### Please also check out the [docs](https://rasa.com/docs/) and the [forum](https://forum.rasa.com/) in case your issue was raised there too 🤗

**Comment by gausie** [comment]
Thanks for making the issue. You're right, we should get some feedback going, certainly in the case of success/failure.

**Comment by gausie** [comment]
This will be shipped in the next release!
