### ISSUE TITLE
Problem training NLU

### ISSUE THREAD

**Issue by BrunoRoth95** [RasaHQ/rasa#4289]
**Rasa version**: 1.2.3

**Python version**: 3.6.8

**Operating system** (windows, osx, ...): ubuntu 18.04

**Issue**:

I'm having a weird problem when training my core and NLU. The `rasa train` don't train my current NLU file, instead it trains an old one. I know that because when I open the `models/20190820-114838.tar.gz/nlu/training_data.json` the data there is from an old NLU that I used to have. Even if I delete the whole NLU data it keeps using the same old data. 

the nlu.md file is the only nlu file that I have in my folder, and I already tried specifying the paths with `rasa train --data ./data --config config.yml --domain domain` but still no success.

I also tried deleting the tmp models files, no success.

**Comment by sara-tagger** [comment]
Thanks for raising this issue, @Ghostvv will get back to you about it soon✨

###### Please also check out the [docs](https://rasa.com/docs/) and the [forum](https://forum.rasa.com/) in case your issue was raised there too 🤗

**Comment by Ghostvv** [comment]
what do you mean if you delete an old data, it still uses it? Where does it come from?

**Comment by BrunoRoth95** [comment]
I have no idea @Ghostvv. The training was using some old data... I don't if this was a rasa bug or just my computer, because It was training even though I deleted the nlu.md file (maybe it was an nlu.md hidden file??). 

What I did I just replaced the whole data folder with an backup that I had.

Thank you for the attention!
