### ISSUE TITLE
Make metadata of user messages more accessible

### ISSUE THREAD

**Issue by akelad** [RasaHQ/rasa#4294]
Right now, in a custom action you have to loop through the events in the tracker to access it like this:

 for e in tracker.events<span class="error">[::-1]</span>:
 if e<span class="error">["event"]</span> == "user":
 message_metadata = e<span class="error">["metadata"]</span>
 break

Ideally, we should be able to access it with `tracker.latest_message.metadata` or similar

**Comment by tmbo** [comment]
I think this is a larger issue of handling conversation-long state and should be handled as such finding a general solution.

**Comment by akelad** [comment]
not sure i understand what you mean?

**Comment by elyase** [comment]
@tmbo do you mean that there should be a way to have metadata that is associated to a conversation (tracker) while now the metadata is associated to individual events?

**Comment by wochinge** [comment]
@tmbo What did you mean? :-D

**Comment by tmbo** [comment]
exactly what @elyase mentioned. There might be a use case for conversation wide metadata. But that is something different to the metadata of a single user message.

The code akela posted basically treats the latest messages metadata as the conversation wide metadata.

**Comment by wochinge** [comment]
Ok, but what speaks against handling it the way Akela suggested? It's important to know which message the metadata is describing and making that state of the conversation doesn't make sense to me. Users should set conversation metadata using slots imo.

**Comment by tmbo** [comment]
Don't get me wrong, I am not saying we should not implement something like `tracker.latest_message.metadata`, I just wanted to mention there might be some underlying need to be able to store metadata on a conversation.

To some extent, this is what slots are for, so might make sense to make it easier to store unfeaturized metadata in slots.

**Comment by akelad** [comment]
yeah as far as i've seen most people use metadata per message, rather than something that's global

**Comment by tmbo** [comment]
interesting, can you add a couple of examples of things you have seen them store in there?

**Comment by tmbo** [comment]
prob https://github.com/RasaHQ/rasa/issues/4884#issuecomment-577610744 is also indicating that people want a way to have an easier way to attach data to a conversation that does not influence the prediction

**Comment by akelad** [comment]
i'll ask.

**Comment by akelad** [comment]
one example just now: a user uses this field for multi bot routing, to indicate where the user message came from (i.e. which bot it came from)

**Comment by regel** [comment]
First use-case: Real example of metadata (slots?) **per conversation**: fetching the user profile from an AD when the conversation starts. For bookeeping, we need to have this metadata inside the conversation: uid, first_name, last_name, other unique identifiers. Right now, we're using hidden slots and a ad-hoc '/bootstrap' actions to set these slots. Some of them influence predictions, others don't.

Second use-case: Real example of metadata **per message**: using a [custom channel](https://rasa.com/docs/rasa/user-guide/connectors/custom-connectors/) to store the JWS value found in authorization header of the POST http call.

In this second use-case, frontend is authorized and receives a signed JWS token > calls Springboot app (verifies the JWS) > calls Rasa-X (rasa-production webhook) > calls Rasa app (Actions) > calls other backend APIs using the same JWS value. We need the same JWS token end-to-end from the frontend application down to Rasa app Actions handlers. This is a real enterprise use-case. Do you think custom connector + message metadata holding JWS value is correct, or did I miss a more elegant solution in Rasa documentation?

**Comment by HarmanDotpy** [comment]
Hi
I wanted to know if there is a way to get user metadata in the DialogueStateTracker which is being used in policies.
I want the metadata information so that I can do something in the custom policy based on that metadata (which will contain user profile data)
