### ISSUE TITLE
Config and NLU pipeline in RasaX

### ISSUE THREAD

**Issue by ferozewaris** [RasaHQ/rasa#4298]
Hello, 
I am using RasaX 0.19.5 with Rasa 1.1.4 running on docker. On GUI of RasaX i can not see config tab. What to do if i want to change the Rasa NLU pipeline or change the language. I even cant see nlu config file on server side mounted to some docker volume. What to do if i want to change the pipelne.

Regards 
Feroze

**Comment by sara-tagger** [comment]
Thanks for the question, our Github issue board is for **bugs and feature requests only,** though 😕
Please ask this question in the [forum✨](https://forum.rasa.com/c/rasa)

###### If you were describing a bug, please create a [report](https://github.com/RasaHQ/rasa/issues/new?labels=bug&template=bug_report.md) and fill out the template

**Comment by ferozewaris** [comment]
I have asked this question on forum as well. Its been more than 24 hours passed since i asked and no one cared to response there that is why i am asking there. 
FYI
https://forum.rasa.com/t/config-and-nlu-pipeline-in-rasax/14556
