### ISSUE TITLE
Rasa trained model does not work with AWS multiple replicas.

### ISSUE THREAD

**Issue by VikasSinghaiAndroid** [RasaHQ/rasa#4301]
**Rasa version**: 1.1.3

**Rasa X version** (if used & relevant):

**Python version**: Python 3.6.8

**Operating system** (windows, osx, ...): Windows 10

**Issue**:
I have already Started my Rasa model in AWS container with 2 replicas after that i am retraining the rasa model with new utterance it is tarining the rasa model but it is training only in 1 replica it is not training in another replica ideally it should training in both the replicas.

Can anyone guide what we need to do to fix this issue.

**Error (including full traceback)**:
```

```

**Command or request that led to error**:
```

```

**Content of configuration file (config.yml)** (if relevant):
```yml

```

**Content of domain file (domain.yml)** (if relevant):
```yml

```

**Comment by sara-tagger** [comment]
Thanks for the issue, @tabergma will get back to you about it soon!

###### You may find help in the [docs](https://rasa.com/docs/) and the [forum,](https://forum.rasa.com/) too 🤗

**Comment by tabergma** [comment]
What error message do you get?

**Comment by VikasSinghaiAndroid** [comment]
We are not getting any errors with with 1 replica newly added utterance is working but in another replica utterance is not detecting we are getting intent null, basically when we train rasa it is only training in replica 1, but ideally it should train in both the replicas.

Please suggest.

**Comment by tabergma** [comment]
@VikasSinghaiAndroid As this is not really a bug but more a question on how to train Rasa on AWS replicas, can you please open a thread in the https://forum.rasa.com/ and close this issue. We will be happy to help you there. Thanks.

**Comment by VikasSinghaiAndroid** [comment]
Thank you!
