### ISSUE TITLE
Error after e2e test 'Feature could not be found in feature map`

### ISSUE THREAD

**Issue by TatianaParshina** [RasaHQ/rasa#4312]
**Rasa version**:
Rasa 1.1.4
**Rasa X version** (if used & relevant):
Rasa X 0.19.5
**Python version**:
Python 3.6.8
**Operating system** (windows, osx, ...):
Windows 8.1
**Issue**:
I have the file `e2e_stories.md` for e2e test. I run the command `rasa test --stories data/e2e_stories.md --e2e` . 
After the test, I run the training command 'rasa train'. 
As a result, I had a lot of messages in logs with phrases from `e2e_stories.md`: `Feature 'intent_deny: no'(value: '1.0') could not be found in feature map`.
Also phrases from `e2e_stories.md` were added to `domain.yml` as new intents.

**Error (including full traceback)**:
```
2019-08-23 18:24:05 DEBUG    rasa.core.featurizers  - Feature 'intent_deny: no'(value: '1.0') could not be found in feature map. Make sure you added all intents and entities to the domain
```

**Command or request that led to error**:
```
rasa test --stories data/e2e_stories.md --e2e
rasa train
```

**Comment by sara-tagger** [comment]
Thanks for the issue, @dakshvar22 will get back to you about it soon!

###### You may find help in the [docs](https://rasa.com/docs/) and the [forum,](https://forum.rasa.com/) too 🤗

**Comment by dakshvar22** [comment]
Hi, 
Can you post a snippet of your data as well please?

**Comment by TatianaParshina** [comment]
Hi @dakshvar22 ,
I have reproduced the error with default content that was created by `rasa init`. 
Then I run 
`rasa test --stories data/e2e_stories.md --e2e`
Then I run `rasa train`.
Errors in the log during training:
`2019-09-08 23:18:26 DEBUG    rasa.core.featurizers  - Feature 'intent_goodbye: bye' (value: '1.0') could not be found in feature map. Make sure you added all intents and entities to the domain`

Then I run `rasa x`

After the Rasa X running, `domain.yml` file started to have new values:
```
intents:
- greet
- goodbye
- affirm
- deny
- mood_great
- mood_unhappy
- 'greet: hello bot'
- 'affirm: yes'
- 'goodbye: bye'
- 'mood_great: perfect'
- 'mood_unhappy: sad'
- 'deny: no'
```

**Comment by TatianaParshina** [comment]
@dakshvar22 were you able to reproduce the issue or should I provide more information?

**Comment by federicotdn** [comment]
Hi @TatianaParshina, I noticed this issue was created in August, are you still using the same Rasa and Rasa X versions? If not, would it be possible to update them to the newest one? (Rasa X 0.21.1)

**Comment by erohmensing** [comment]
@TatianaParshina looks like you have end-to-end stories in the same data directory that you are passing to `rasa train`. As of now, e2e format is only supported for testing, not training, but it's interpreting the end-to-end format as a new intent. I think this is something we should pick up on and warn/error on our part, but in the mean time, probably best if you keep your test data in a different folder like `test_data`.

**Comment by wink94** [comment]
I'm getting this issue even though I have not included end to end stories
