### ISSUE TITLE
Failed to load model metadata

### ISSUE THREAD

**Issue by ShakyaWork** [RasaHQ/rasa#4314]
After training my rasa nlu model, I wanted to test it against an utterance which was not present in my training dataset. Following was the code.

> def run_nlu():

	interpreter = Interpreter.load('.\model\nlu\default\weathernlu', config.load('config_spacy.json'))
	print(interpreter.parse(u"I am planning my holiday to Barcelona. I wonder what is the weather out there."))

However, I am getting the following error message:
Failed to load model metadata from 'C:\Users\shakya.munghate\Desktop\Weatherbot\model
lu\default\weathernlu\metadata.json'. [Errno 22] Invalid argument: '.\\model\nlu\\default\\weathernlu\\metadata.json'

metadata.json file is present in the destination folder, still it is not able to read it.
Can anyone please help?

**Comment by sara-tagger** [comment]
Thanks for the question, our Github issue board is for **bugs and feature requests only,** though 😕
Please ask this question in the [forum✨](https://forum.rasa.com/c/rasa)

###### If you were describing a bug, please create a [report](https://github.com/RasaHQ/rasa/issues/new?labels=bug&template=bug_report.md) and fill out the template
