### ISSUE TITLE
What is this weird error? 

### ISSUE THREAD

**Issue by psds01** [RasaHQ/rasa#4315]
What is this weird error? 

When I run `rasa x`, I get this error printed on terminal:

`[2019-08-23 xx:xx:xx +0000] [2693] [ERROR] Exception occurred while handling uri: unknown
NoneType: None`

No more, no less

**Comment by sara-tagger** [comment]
Thanks for the question, our Github issue board is for **bugs and feature requests only,** though 😕
Please ask this question in the [forum✨](https://forum.rasa.com/c/rasa)

###### If you were describing a bug, please create a [report](https://github.com/RasaHQ/rasa/issues/new?labels=bug&template=bug_report.md) and fill out the template
