### ISSUE TITLE
Rasa Visualize stories command png gives a "file damaged, corrupted, too large" error on windows

### ISSUE THREAD

**Issue by miliaxy** [RasaHQ/rasa#4319]
Rasa NLU Version : 0.15.0
Rasa Core Version : 0.14.4
Python Version : 3.5.2
OS : Windows 32

When I run the following command to visualize my stories : 
`python -m rasa_core.visualize -s data/core/ -d domain.yml -o story_graph.png`

It runs successfully : 
```
C:\01_rasa_color_cb-master>python -m rasa_core.visualize -s data/core/ -d domain
.yml -o story_graph.png
2019-08-23 16:04:32 INFO     apscheduler.scheduler  - Scheduler started

WARNING: The TensorFlow contrib module will not be included in TensorFlow 2.0.
For more information, please see:
  * https://github.com/tensorflow/community/blob/master/rfcs/20180907-contrib-su
nset.md
  * https://github.com/tensorflow/addons
If you depend on functionality not listed there, please file an issue.

2019-08-23 16:04:34 INFO     __main__  - Starting to visualize stories...
Processed Story Blocks: 100%|##| 35/35 [00:00<00:00, 2243.56it/s, # trackers=1]
2019-08-23 16:04:35 INFO     __main__  - Finished graph creation. Saved into fil
e://C:\01_rasa_color_cb-master\story_graph.png
```

But when I try to open the png, it gives me the error :  "Windows Photo Viewer cant open this picture because the file appears to be damaged, corrupted, or is too large"

Alternatively, tried saving this file as .html, but nothing shows up in the picture.

**Comment by sara-tagger** [comment]
Thanks for raising this issue, @msamogh will get back to you about it soon✨

###### Please also check out the [docs](https://rasa.com/docs/) and the [forum](https://forum.rasa.com/) in case your issue was raised there too 🤗

**Comment by msamogh** [comment]
Could you please update to the latest Rasa version and try again?
