### ISSUE TITLE
fallback policy is not working as explained ,can more elaborations be given on nlu_threshold and nlu_core ?

### ISSUE THREAD

**Issue by Indranil-hue** [RasaHQ/rasa#4321]

**Comment by sara-tagger** [comment]
Thanks for the question, our Github issue board is for **bugs and feature requests only,** though 😕
Please ask this question in the [forum✨](https://forum.rasa.com/c/rasa)

###### If you were describing a bug, please create a [report](https://github.com/RasaHQ/rasa/issues/new?labels=bug&template=bug_report.md) and fill out the template
