### ISSUE TITLE
Multiple Choice buttons in rasa

### ISSUE THREAD

**Issue by nikhilcss97** [RasaHQ/rasa#4324]
Hi,

I wanted to know if there is any functionality for selecting multiple choices using buttons. The user can select multiple buttons and we get all the selected options in a list. 

Thank You.

**Comment by erohmensing** [comment]
Hi there @nikhilcss97, this would have to be something that your UI handles, as rasa wouldn't know when to stop waiting for input (as well as the channel would have to have UI for multiple choices in any case!). Check out [this thread](https://forum.rasa.com/t/using-list-with-buttons-or-doing-multiple-selects/13684) for more info.

**Comment by nikhilcss97** [comment]
Could you please give a code example for implementing this on Slack?

**Comment by erohmensing** [comment]
Slack doesn't currently support multiple choice input as far as I know. No channel that I know off the top of my head does. You would have to look into their messaging APIs to see what is possible. 

In any case, our GitHub is for bug reports and feature requests (as we can't support this, it's not a feature request), so I'll close this. Feel free to do some research and let us know on the [forum](forum.rasa.com) if you create a channel that supports this input, but I don't think you'll find someone with a  ready code example for this UX. Its likely much simpler to handle with either buttons for each combination or a thread of yes/no buttons.
