### ISSUE TITLE
Accept pathlib model path

### ISSUE THREAD

**Issue by Batalex** [RasaHQ/rasa#4341]
**Description of Problem**:
I am fond of pathlib and of this particular snippet to load the newest model I have:
```python
import pathlib

from rasa.core.agent import Agent

models_folder = pathlib.Path("models")
latest_model = max(models_folder.glob("*.tar.gz"), key=lambda p: p.stat().st_ctime)

agent = Agent.load(str(latest_model))
```

The only friction here is `str(latest_model)`. Adding support for pathlib paths would be quite convenient.

**Overview of the Solution**:

 Since `os.path` functions are compatible with `pathlib`, the only change we would need to do is right there https://github.com/RasaHQ/rasa/blob/master/rasa/core/agent.py#L355:
```python
model_path = get_model(str(model_path))
```
I could submit a PR if the feedback is positive.
The interrogation left would be about the type hints: `model_path` is a `Text` right now, would a `Union[Text, Path]` type be acceptable?

**Comment by sara-tagger** [comment]
Thanks for submitting this feature request 🚀@JustinaPetr will get back to you about it soon!✨

**Comment by silvasara** [comment]
Hi, @Henrike100 and I are interested in taking this issue and will start working on it

**Comment by JustinaPetr** [comment]
That's great @silvasara. Please let us know if you need any help with this.

**Comment by Batalex** [comment]
Thanks @silvasara and @Henrike100, it works like a charm 👍 
I am closing the issue.
