### ISSUE TITLE
is_binary_training in featurizer

### ISSUE THREAD

**Issue by jeanveau** [RasaHQ/rasa#4344]
**Rasa version**: 1.2

**Rasa X version** (if used & relevant):

**Python version**: 3.6

**Operating system** (windows, osx, ...): Ubuntu

**Issue**:
I found in the trained MemoizationPolicy model, in lookup table all tracker states are using reel intent confidence predicted by interpreter, although  in method `training_states_and_actions`, when calling `_create_states`, we do set `is_binary_training` to `True` (in `rasa.core.featurizer.py` at line 585)

So I looked into `_create_state` method:
```python
    def _create_states(
        self,
        tracker: DialogueStateTracker,
        domain: Domain,
        is_binary_training: bool = False,
    ) -> List[Dict[Text, float]]:
        """Create states: a list of dictionaries.
            If use_intent_probabilities is False (default behaviour),
            pick the most probable intent out of all provided ones and
            set its probability to 1.0, while all the others to 0.0."""
        states = tracker.past_states(domain)

        # during training we encounter only 1 or 0
        if not self.use_intent_probabilities and not is_binary_training:
            bin_states = []
            for state in states:
                # copy state dict to preserve internal order of keys
                bin_state = dict(state)
                best_intent = None
                best_intent_prob = -1.0
                for state_name, prob in state:
                    if state_name.startswith("intent_"):
                        if prob > best_intent_prob:
                            # finding the maximum confidence intent
                            if best_intent is not None:
                                # delete previous best intent
                                del bin_state[best_intent]
                            best_intent = state_name
                            best_intent_prob = prob
                        else:
                            # delete other intents
                            del bin_state[state_name]

                if best_intent is not None:
                    # set the confidence of best intent to 1.0
                    bin_state[best_intent] = 1.0

                bin_states.append(bin_state)
            return bin_states
        else:
            return [dict(state) for state in states]
```

The first if condition will never be executed as it asks `is_binary_training` should NOT be True.

So unless I misunderstand what `is_binary_training` means, I thinks we should remove the second `not` from that `if` condition  

**Error (including full traceback)**:
```

```

**Command or request that led to error**:
```

```

**Content of configuration file (config.yml)** (if relevant):
```yml

```

**Content of domain file (domain.yml)** (if relevant):
```yml

```

**Comment by sara-tagger** [comment]
Thanks for the issue, @federicotdn will get back to you about it soon!

###### You may find help in the [docs](https://rasa.com/docs/) and the [forum,](https://forum.rasa.com/) too 🤗

**Comment by Ghostvv** [comment]
`is_binary_training` is used during training of core model, when the input anyhow is binary so there is no need to binarize it
