### ISSUE TITLE
Option of not including nlu training data in models

### ISSUE THREAD

**Issue by ronancummins** [RasaHQ/rasa#4347]
**Description of Problem**:
Given that training data is often very sensitive, it would be nice to have an option to not include it in the trained models that rasa produces. Anyone with access to the model files (tar.gz) can view the training data using zcat model.tar.gz | grep -a "text" which could be problematic if shipping/storing models on certain servers.  

**Overview of the Solution**:
Add a (default) config variable persist_training_data : bool to the Trainer class in rasa/nlu/model.py, which can be used to control whether the training data gets persisted to the model in the persist method of the same class. Depending on the default value of this, the input to rasa.nlu.train may need to be modified aswell. I suggest that the default value should be false. 

**Examples** (if relevant):

**Blockers** (if relevant):
Nope

**Definition of Done**:
- [ ] Tests are added
- [ ] Feature described the docs
- [ ] Feature mentioned in the changlog

**Comment by sara-tagger** [comment]
Thanks for submitting this feature request 🚀@akelad will get back to you about it soon!✨

**Comment by akelad** [comment]
Hey @ronancummins that's a good point. We actually have something like this for the stories already, I don't see why we wouldn't include something like that for the NLU training data. Would you be up for making this contribution?

**Comment by ronancummins** [comment]
Yes I would... I'll have a look at the way it works for stories, work on getting it to a PR, and review then...

**Comment by akelad** [comment]
awesome!

**Comment by ronancummins** [comment]
This has been successfully merged into master by tmbo in PR #4394
