### ISSUE TITLE
ModuleNotFoundError: No module named 'rasa.nlu' error occurs in remote server but not locally

### ISSUE THREAD

**Issue by bhargavat** [RasaHQ/rasa#4351]
[requirements.txt](https://github.com/RasaHQ/rasa/files/3556983/requirements.txt)

I was running my rasa model fine under my local environment (macOS 10.14.5 using PyCharm, Python 3.7.3). I exported the requirements.txt file under the venv used for executing my python script and installed packages through that in the remote server (centOS 7 with Python 2.7.5 at system level). I had the exact same Python version installed in the remote server's virtual environment too (i.e. Python 3.7.3). However, when I try to run my script, I get the module not found error. Below is the rasa-related code I attempted to use. 

```
from rasa.nlu.model import Interpreter
interpreter = Interpreter.load(model_directory)
```

Any reason why this issue is only persisting in my remote machine and not in my local macOS-based machine? Had someone else import my python script into this macOS machine and pip install from the `requirements.txt` and their environment was running it fine. Let me know what other details you need besides this. 

Update: I noticed a difference in gcc compiler which may be the culprit. 

Local machine:

> Python 3.7.3 (v3.7.3:ef4ec6ed12, Mar 25 2019, 16:52:21) 
> [Clang 6.0 (clang-600.0.57)] on darwin

Remote machine: 

> Python 3.7.3 (default, Aug 28 2019, 14:13:03) 
> [GCC 4.8.5 20150623 (Red Hat 4.8.5-36)] on linux

**Comment by sara-tagger** [comment]
Thanks for the question, our Github issue board is for **bugs and feature requests only,** though 😕
Please ask this question in the [forum✨](https://forum.rasa.com/c/rasa)

###### If you were describing a bug, please create a [report](https://github.com/RasaHQ/rasa/issues/new?labels=bug&template=bug_report.md) and fill out the template
