### ISSUE TITLE
Rasa train should detect changes is external dataset used by custom NLU component

### ISSUE THREAD

**Issue by cajoek** [RasaHQ/rasa#4353]
**Description of Problem**: I have created a custom RASA NLU component that loads additional training data from a file. Both for debugging and in production it would be nice if the command "rasa train" could detect changes in the NLU component code or the data file and retain it. Similar to how it detects changes in config, domain etc. Most important is to detect changes in the external training dataset.

**Overview of the Solution**: Maybe RASA components could also be fingerprinted in a way to optionally include other files?

**Comment by sara-tagger** [comment]
Thanks for submitting this feature request 🚀@Ghostvv will get back to you about it soon!✨

**Comment by Ghostvv** [comment]
I don't think it is a research issue

**Comment by twerkmeister** [comment]
this could be related to #7581 . Potentially there could be an architectural change in the cards where components decide if they need retraining or not? Not sure how common this kind of setup is however.
