### ISSUE TITLE
failing tests for expected warnings

### ISSUE THREAD

**Issue by imLew** [RasaHQ/rasa#4356]
Some tests are supposed to check for the printing of warning or error messages, therefore if such a message is printed during testing the tests do currently not fail. However this effectively hides warnings and error that are not supposed to be occur.

Testing should be changed such that 
1) when a warning or error message is expected during tests it is not printed to the test log
2) if a warning or error message is unexpectedly printed during testing the tests fail

Update:
This seems to be blocked by a problem with cython.
Other than that the way forward is to:
1) start using `rasa.utils.common.raise_warn` instead of `warnings.warn`.
2) add formatting to the above method by locally overwriting `_formatwarnings`
3) Use `with pytest.warns` to handle expected warnings in tests
4) mark all tests currently raising warnings with `@pytest.mark.filterwarnings` and #TODO and check their warnings and then either fix them or handle them correctly
see also https://github.com/RasaHQ/rasa/issues/4356#issuecomment-565431258

**Comment by imLew** [comment]
We have a util function `rasa.utils.common.set_log_level` which sets the log level for all the different loggers in rasa and sets a log level env var.
Because of this, during some tests the `log_level` changes.
Specifically `tests.test_server.py::test_load_model_from_model_server` and `tests.core.test_agent.py::test_agent_with_model_server_in_thread`/`test_wait_time_between_pulls_without_interval` seem to be guilty of this.

**Comment by federicotdn** [comment]
From what was discussed by chat, one way we could implement this would be:
- Add the [`@pytest.mark.filterwarnings()`](https://docs.pytest.org/en/latest/warnings.html?highlight=warnings#pytest-mark-filterwarnings) annotation to current tests that print warnings. After running the test suite, no warnings should have been printed.
- Add [`-W`](https://docs.pytest.org/en/latest/warnings.html) to the pytest invokation in Makefile. If any new test emits a warnings, testing will fail.
- Slowly re-visit old tests that emitted warnings and correct them (that is, find why the warnings are being produced).

**Comment by imLew** [comment]
One this about this though: it only filters warnings raised by `warnings.warn` right? We also have a couple `logger.warning`s. Should we replace them?

**Comment by federicotdn** [comment]
Yes, I think it's only for `warnings.warn`. Not sure what to do about the `logger.warnings`, it would be nice to treat them exactly the same (mute existing ones, fail on new ones).

**Comment by imLew** [comment]
So the plan of attack on this issue is:
1) Fail on warnings (this is the `-W`)
2) Ignore the warnings that we currently have (by adding the `filterwarnings` decorator)
3) Fix the warnings

**Comment by imLew** [comment]
Based on the fact that `filterwarnings` only filters `warnings.warn` the question was raised what we should be using in our code.
According to official [documentation](https://docs.python.org/3.7/howto/logging.html)
"""warnings.warn() in library code if the issue is avoidable and the client application should be modified to eliminate the warning

logging.warning() if there is nothing the client application can do about the situation, but the event should still be noted"""

**Comment by federicotdn** [comment]
I feel like if we are already using `logger.info`, `logger.debug`, `logger.error` in our code, then it also makes a lot of sense to use `logger.warning` as well. The only problem with this is that the `filterwarnings` tool won't help us there (like you mentioned).

**Comment by imLew** [comment]
Yes, it would not be good to use `warnings.warn` just because we can easily filter it during testing.
However I do think there a merit to distinction made in the docs and we should consider following this convention unless we have a reason not to do so.
Either way it seems we will not stop using `logger.warning` so we have to figure out how to filter these during testing.

**Comment by imLew** [comment]
@tmbo for the messages from the `warnings` module the plan was to hide the ones we currently have and make the tests fail on any new ones.
Warnings that are supposed to be printed should then be captured, presumably this would be done by adding `pytest.mark.filterwarnings("irgnore")` to the test in question. However, that is also the way we would hide those warnings that we want to get rid of later. How should we differentiate between those two cases? Are you ok with with something `#TODO solve warning and remove filter` above every test that currently prints a warning?

**Comment by tmbo** [comment]
@imLew I'd add a more specific filter to the ones we want to really ignore because we expect them to happen (I think you can provide a regex or something for the `filterwarnings`).

For all other ones adding `ignore` and a TODO sounds good :+1:

**Comment by imLew** [comment]
Just to document and keep this up to date:
We have decided not to fail on `logger.warning` messages as these are defined as messages that should be printed in case the user cannot do anything about it, which would mean we cannot do anything about it either.
The status is now that I will somehow have to go through all the warnings currently being printed and add `@filterwarnings` to them. And I will go through all the `logger.warnings` to see which ones should be `warnings.warn` instead.

**Comment by imLew** [comment]
two more things that have come up:
1) the output of warnings.warn not being colored is not ideal, we should change that if possible
2) the `stack_level` parameter can be used to control how much is shown in the traceback, the default includes the line throwing the warnings which is quite useless as that is usually just as f-string

**Comment by imLew** [comment]
The PR https://github.com/RasaHQ/rasa/pull/4780 contains the latest work on this.

What has changed is that we decided to create our own function for raising warnings (currently called `rasa.util.common.raise_warn`) as this allows us to set a better default for the `stacklevel` and to choose our own formatting. (https://docs.python.org/3/library/warnings.html the warnings module seems to recommend overwriting the `_formatwarning` method globally, however this is a bad idea as it would cause problems for people who use rasa together with other libraries) see also https://github.com/python/cpython/blob/cfe172dc6bd0a02d36db31ffabcc38f9320a4510/Lib/warnings.py#L35 

For capturing logs during testing there is a context manager provided by pytest (https://docs.pytest.org/en/3.0.5/recwarn.html)
```
    with pytest.warns(UserWarning) as record:
        print_warning("some message")
    assert len(record) == 1
    assert (
        "some message" in record[0].message.args[0]
    )
```
this should be used to handle expected warnings.
(In the current version this also hides the warnings from the console log, if it does not: there is another context manager provided by the warnings module that can be used to to hide warnings locally.)

**Comment by imLew** [comment]
Unfortunately adding
```
filterwarnings:
    error
```
to setup.cfg currently results in a strange bug, causing errors that are not present when testing normally and not due to warnings being raised. The most common one is that imports of policies fail with the root cause being `E   AttributeError: type object 'scipy.sparse._csparsetools.array' has no attribute '__reduce_cython__'`.

A similar issue is described on the cython github page https://github.com/cython/cython/issues/2985
