### ISSUE TITLE
consistent signature across core and nlu `persist` methods

### ISSUE THREAD

**Issue by imLew** [RasaHQ/rasa#4358]
Both core policies and nlu components are persisted with a method called `persist`, however their signatures are inconsistent, i.e. core `persist`s usually take only a single string that is the path where the component should be saved (i.e. including the filename), while in nlu `persist`s it is mixed between path and path+filename.
(Also the path variable sometimes called something else)

**Comment by tabergma** [comment]
I would argue that the signature is a bit different: For core the `path` is actually a directory. The file name is not provided. All files are stored inside that directory with custom names. For nlu you have the `model_dir` and `file_name` (without ending). The files are stored inside the `model_dir` with `file_name` as the basename of the file. So, the main difference is that core creates sub-directories whereas nlu creates multiple files with the same basename. 

Except for renaming you cannot change the signature that easily. I would argue that storing files in sub-directories is a bit cleaner. However, if we want to adapt the way of storing nlu files, we would introduce a breaking change. Do we want that?

As @imLew already mentioned, I would propose to rename `path` to `model_dir`.

**Comment by imLew** [comment]
Yes, my bad, path is in deed a dir.
It would definitely be breaking but I think it's worth considering for 2.0 as a having similar components of an api work in similar ways makes it more useable imo.

**Comment by wochinge** [comment]
I propose a component `TrainingDataExporter` which mirrors the `TrainingDataImporter`.

```python

class TrainingDataExporter:

    @staticmethod
    def save_domain(domain: Domain, path: Text) -> None:
        pass

    @staticmethod
    def save_training_data(training_data: TrainingData, path: Text) -> None:
        pass

    @staticmethod
    def save_stories(stories: List[Story], path: Text) -> None:
        pass

    @staticmethod
    def save_config(config: Dict, path: Text) -> None:
        pass

```

Goals:
- have the option to change the export behavior globally
- users should be able to implement their own module for exporting data
- we should move out the persistence stuff out of our domain objects

Implementations:
- one which exports markdown / yaml
- one which overwrites the last one and exports NLU as json

I'd specify the exporter in `config.yml` and then probably monkey patch this class globally. 

Thoughts, @imLew @tabergma ?

**Comment by tabergma** [comment]
@wochinge I think this issue is more about saving the model not the training data files. However, the `TrainingDataExporter` idea sounds great.

**Comment by imLew** [comment]
@wochinge exactly what @tabergma said, this issue is only a small refactoring suggestion for current features (saving the model components), but having an easy flexible way to export training data would be awesome!

**Comment by wochinge** [comment]
Ah, sorry! Will create a new issue then for it :-)

**Comment by MarthaDs** [comment]
> I propose a component `TrainingDataExporter` which mirrors the `TrainingDataImporter`.
> 
> ```python
> class TrainingDataExporter:
> 
>     @staticmethod
>     def save_domain(domain: Domain, path: Text) -> None:
>         pass
> 
>     @staticmethod
>     def save_training_data(training_data: TrainingData, path: Text) -> None:
>         pass
> 
>     @staticmethod
>     def save_stories(stories: List[Story], path: Text) -> None:
>         pass
> 
>     @staticmethod
>     def save_config(config: Dict, path: Text) -> None:
>         pass
> ```
> 
> Goals:
> 
> * have the option to change the export behavior globally
> * users should be able to implement their own module for exporting data
> * we should move out the persistence stuff out of our domain objects
> 
> Implementations:
> 
> * one which exports markdown / yaml
> * one which overwrites the last one and exports NLU as json
> 
> I'd specify the exporter in `config.yml` and then probably monkey patch this class globally.
> 
> Thoughts, @imLew @tabergma ?

It was created a new Issue for this?

**Comment by karen-pal** [comment]
Hello! I'm trying to think a strategy to tackle this, I would love to contribute with a pull request.

I looked at the code, trying to answer this question: Is it desirable for `core`'s `persist` to also allow for the subdirectory approach to signature?

from the` ted policy` file:

![image](https://user-images.githubusercontent.com/55008020/108773189-bfb91f00-753c-11eb-926f-5e26539e1a90.png)



I see in the code you usually extract the `model_dir` from the path argument and have the `file_name` as a constant at the beginning of the file, or just provide it right there and then. 

You seem to have the same behavior in `nlu` even with different signatures. **In both cases you create a subdirectory**. From the `diet classifier` file:
![image](https://user-images.githubusercontent.com/55008020/108773261-d2cbef00-753c-11eb-8087-2bbe4ad8e8b7.png)



So if I would have a go at it, I would change `core`s' `persist` signature to be consistent with `nlu`'s. It would look something like this (new `ted policy` with `nlu`'s signature):
![image](https://user-images.githubusercontent.com/55008020/108773462-28080080-753d-11eb-86d3-f052c9c5515c.png)


What do you think? If you think that's a good idea I could start right away!

**Comment by wochinge** [comment]
Will be tackled by the model architecture revamp.
