### ISSUE TITLE
Simple story misbehave or does not work.

### ISSUE THREAD

**Issue by dtsonov** [RasaHQ/rasa#4359]
I have the following simple story:

## predefined_path_1
*greet
  - utter_greet
  - utter_ask_name
* inform{"pname":""}  
  - utter_ask_age
* inform{"page":""} 
  - utter_ask_weight
* inform{"pweight":""}
  - utter_how_you_feel

## say goodbye
* goodbye
  - utter_goodbye

When train and start the model it displays only the greet utter after I typed "hi" which is defined under greet intent in nlu.md after that it executes utter_ask_name, when I type in name everything stops, the bot displays only right arrow ->
The flow/story does not proceed further with  utter_ask_age and and so on.
I have correctly defined my domain.yml and stories.md according documentation and the examples I did review.

I did read the docs, also reviewed the rasa examples, but can't see in my simple case what is the problem.

Any hint/help is welcome.

**Comment by sara-tagger** [comment]
Thanks for the question, our Github issue board is for **bugs and feature requests only,** though 😕
Please ask this question in the [forum✨](https://forum.rasa.com/c/rasa)

###### If you were describing a bug, please create a [report](https://github.com/RasaHQ/rasa/issues/new?labels=bug&template=bug_report.md) and fill out the template
