### ISSUE TITLE
twilio return text "success" in whatsapp after send message in bot

### ISSUE THREAD

**Issue by kunci115** [RasaHQ/rasa#4365]
**Error (including full traceback)**:
https://github.com/RasaHQ/rasa/pull/4364/files#diff-041947069f3348b1e47348e3a3e90f3b
```
            return response.text("success") 
```
it suppose to be just response without text, because text would be appear when you chat to the bot from whatsapp twilio

**Comment by sara-tagger** [comment]
Thanks for the issue, @tmbo will get back to you about it soon!

###### You may find help in the [docs](https://rasa.com/docs/) and the [forum,](https://forum.rasa.com/) too 🤗

**Comment by kunci115** [comment]
but sanic to get out returning something, how to solve this? if we erase "success"there, its work, but in backend there would be an error from sanic Invalid response object for url b'/webhooks/twilio/webhook', Expected Type: HTTPResponse, Actual Type: <class 'NoneType'>
Exception occurred while handling uri: 'http://ea92ff87.ngrok.io/webhooks/twilio/webhook'
Traceback (most recent call last):
  File "/Users/bluelogic/PycharmProjects/KumpulinVenv/rasa/lib/python3.7/site-packages/sanic/server.py", line 417, in write_response
    response.output(
AttributeError: 'NoneType' object has no attribute 'output'

**Comment by kunci115** [comment]
refer to this https://github.com/RasaHQ/rasa/pull/4364/commits

**Comment by tmbo** [comment]
fixed as part of https://github.com/RasaHQ/rasa/pull/4364
