### ISSUE TITLE
Rasa end-to-end test does not evaluate the NLU model on the provided end-to-end stories

### ISSUE THREAD

**Issue by nbeuchat** [RasaHQ/rasa#4372]
**Rasa version**: 1.2.5

**Python version**: 3.6

**Operating system** (windows, osx, ...): Ubuntu (through WSL)

**Issue**:
When testing an end-to-end story with `rasa test` and the `--e2e` flag, the NLU evaluation is done on the normal training data instead of on the data in my end-to-end story files. The Core evaluation works as expected on my end-to-end stories.

The [documentation](https://rasa.com/docs/rasa/user-guide/evaluating-models/#end-to-end-evaluation) reads:

> Rasa lets you evaluate dialogues end-to-end, running through test conversations and making sure that both NLU and Core make correct predictions.
>
>To do this, you need some stories in the end-to-end format, which includes both the NLU output and the original text.

Therefore, my expectation was to have:
- The Core evaluation creating the `failed_stories.md` and `story_confmat.pdf` for the stories in `data_test`
- The NLU evaluation creating the `confmat.png`, `errors.json`, and `hist.png` only for the sentences that are in the `data_test/happy.md` file. Right now, it evaluates the NLU model on the data in the `data/nlu.md` file. 

FYI, our folder structure is:
```
data
|_ stories.md
|_ nlu.md
data_test
|_ happy.md
|_ etc.
```

Please note that I do have the test data in end-to-end format (which we got using the `/conversations/{{sender_id}}/story` endpoint). Here is a small sample of such an conversation:

```data_test/happy.md
## 2373134909417533
* greeting: Hello
    - utter_greet

...

* form: affirm: Yes it does
    - form: form_apartment_interest
    - slot{"apt_interested": true}
    - slot{"requested_slot": "user_email"}
* explain: why do you need this?
    - action_explain
    - action_listen
    - form_apartment_interest
    - slot{"requested_slot": "user_email"}
```

Did I misunderstand how the end-to-end evaluation works?

**Command or request that led to error**:
```
rasa test --stories data_test --e2e --out results
```

I also tried the following:
```
rasa test --stories data_test --nlu data_test --e2e --out results
```
In this case, nothing is returned for the NLU evalutation.

**Comment by sara-tagger** [comment]
Thanks for raising this issue, @JustinaPetr will get back to you about it soon✨

###### Please also check out the [docs](https://rasa.com/docs/) and the [forum](https://forum.rasa.com/) in case your issue was raised there too 🤗

**Comment by nbeuchat** [comment]
@JustinaPetr do you have an idea of what can be happening? Thanks for your help

**Comment by JustinaPetr** [comment]
Hi @nbeuchat . Seems like you are doing everything right. Do you see some misclassified intents in the /results/failed_stories.md? I think what is happening is that rasa runs end-to-end evaluation and writes out the results in failed_stories.md for both NLU and Core, however, the results that are printed in your console are only for your Core model. I'll open an issue for this so we can have it fixed.

**Comment by nbeuchat** [comment]
Thanks for your answer @JustinaPetr. I have tried to intentionally put wrong intents in the test stories but nothing is shown in the `failed_stories.md`

**Comment by nbeuchat** [comment]
Thanks for your answer @JustinaPetr. I have tried to intentionally put wrong intents in the test stories but nothing is shown in the `failed_stories.md`

Example:

```
## happy path 2
* greeting: goodbye
- utter_greet   
- ...
```

In the `failed_stories`, I indeed see the wrong prediction:
```
## happy path 2
* greeting: goodbye   <!-- predicted: goodbye: goodbye -->
    - utter_greet   <!-- predicted: utter_goodbye -->
```

In the classification report in the console, I get:
```
goodbye       0.00      0.00      0.00         0
greeting       1.00      0.50      0.67         2
```

However, I do not have a NLU-specific report as I would have without specifying the `--nlu data_test`.

Should I provide a list of test intents in the `data_test` folder then to test the NLU?
