### ISSUE TITLE
Sender for cmdline channel

### ISSUE THREAD

**Issue by DiegoProtec** [RasaHQ/rasa#4375]
**sender default**:
We need the cmdline channel sender id parameter to be entered.

**Overview of the Solution**:
file: ```rasa.core.channels.consolep.py```
version: 1.2.6
```
async def record_messages(
    server_url=DEFAULT_SERVER_URL,
    auth_token=None,
    sender_id=UserMessage.DEFAULT_SENDER_ID,
    max_message_limit=None,
    use_response_stream=True,
):
    """Read messages from the command line and print bot responses."""
```
suggest: include **'sender_id = sender_id or UserMessage.DEFAULT_SENDER_ID'**
```
async def record_messages(
    server_url=DEFAULT_SERVER_URL,
    auth_token=None,
    sender_id=None,
    max_message_limit=None,
    use_response_stream=True,
):
    """Read messages from the command line and print bot responses."""
    
    sender_id = sender_id or UserMessage.DEFAULT_SENDER_ID
```

**Comment by sara-tagger** [comment]
Thanks for submitting this feature request 🚀@dakshvar22 will get back to you about it soon!✨

**Comment by erohmensing** [comment]
Hi @DiegoProtec, why do you need the command line channel sender id to be entered?

**Comment by DiegoProtec** [comment]
I don't need anymore, thanks!
________________________________
De: Ella Rohm-Ensing <notifications@github.com>
Enviado: terça-feira, 3 de setembro de 2019 06:26
Para: RasaHQ/rasa <rasa@noreply.github.com>
Cc: Diego de Santana Fernandes <diegoprotec@hotmail.com>; Mention <mention@noreply.github.com>
Assunto: Re: [RasaHQ/rasa] Sender for cmdline channel (#4375)


Hi @DiegoProtec<https://github.com/DiegoProtec>, why do you need the command line channel sender id to be entered?
