### ISSUE TITLE
Secure API using a JWT instead of token auth

### ISSUE THREAD

**Issue by tmbo** [RasaHQ/rasa#4379]
**Description of Problem**: Currently, the webserver is either unsecured or secured using token authentication. The token authentication is non-standard. Rather than using our own token-based authentication, it would be good to switch to a standard method for securing these endpoints.

**Overview of the Solution**: Instead of using tokens to authenticate a request, we can use JWT tokens. To make the switch easier, we can start using symetric encryption and a PW - this would mimic the token authentication.

This issue is related to [https://github.com/RasaHQ/rasa/issues/2689](https://github.com/RasaHQ/rasa/issues/2689) and should apply to REST input channels as well.

**Definition of Done**:

*   [ ] Tests are added
*   [ ] Feature described the docs
*   [ ] Feature mentioned in the changlog

**Comment by ricwo** [comment]
This should probably also apply to socketio

**Comment by selvamshan** [comment]
JWT can be implemented in rest customer connetor with PyJwt.

```
@custom_webhook.route("/bot_auth", methods=["POST"])        
        async def auth_token(request: Request):                        
            if not request.json:
                return response.json({"error":"Missing sender"}, 400)
            
            sender_id = await self._extract_sender(request)
            utcnow = datetime.utcnow() + timedelta(seconds=-5)
            expires = utcnow + timedelta(hours=24)                     
            try:
                payload = {'iat': utcnow,'sender_id': sender_id, 'role':'user', 'exp':expires}
                bot_token = jwt.encode( payload,
                                    'thisismysecret', 
                                    algorithm='HS256').decode("utf-8")
            except Exception as e:
                return response.json({'error':str(e)}, 400)
            return response.json({"bot_token":bot_token}, 200)
```
decorator function required for authentication

**Comment by wochinge** [comment]
@tmbo You mean that Rasa should generate the jwt tokens since Rasa already values existing tokens?

**Comment by tmbo** [comment]
mhm I am not sure what is missing in our current implementation, because we already support JWT authentication in the Rasa OSS server API. I mean we could check and make sure that in Rasa X we are using jwt instead of tokens when communicating with Rasa - but all in all I think we are good and this can be closed.

**Comment by rgstephens** [comment]
There's related request for the action server to validate a token that is passed around other [microservices](https://livebook.manning.com/book/microservices-security-in-action/chapter-7/v-4/6). Could we add an optional `jwt` value to the rest channel.

**Comment by tmbo** [comment]
yes I think securing the action server in some way is a good push :+1:

**Comment by rgstephens** [comment]
@tmbo Is there any reason why the JWT couldn't be stored in the sender id for now?

**Comment by wochinge** [comment]
Would probably break the SQLTrackerStore because that would make the sender id field insanely long

**Comment by b-quachtran** [comment]
Just a note, a few customers have requested this as a feature enhancement on our end.

**Comment by pnandhini11** [comment]
Hi, Is anyone working on this? Can I take this enhancement?

**Comment by wochinge** [comment]
@pnandhini11 Yes, fell free to take this one 💯

**Comment by pnandhini11** [comment]
Can you assign this issue to me?

**Comment by pnandhini11** [comment]
@wochinge Can some assign this issue to me?

**Comment by wochinge** [comment]
@pnandhini11 Sure! Can you please write down a short implementation proposal before starting the implementation? Would be great if we align on the general direction as this is a pretty significant change.

**Comment by pnandhini11** [comment]
@wochinge Sure will do.  I will do it over the weekend.

**Comment by pnandhini11** [comment]
@wochinge Pls correct my understanding about this issue before I get into it and work for a solution. 

Rasa already provided an option to secure APIs using JWT authentication.  And I believe its working fine.  Now we need to secure action server and Rest channel with the JWT authentication.

**Comment by itcnj** [comment]
@pnandhini11 Hi Padma, are you able to secure the general RASA bot webhook api? A custom channel is allowed only in RASA-X which is a commercial product.

**Comment by wochinge** [comment]
@b-quachtran What exactly have customers requested? Token authentication with the action server or for the REST channel?
