### ISSUE TITLE
i don't know how to load train model through api and i want to load data through api

### ISSUE THREAD

**Issue by mlcode-jeevan** [RasaHQ/rasa#4384]

**Comment by sara-tagger** [comment]
Thanks for raising this issue, @amn41 will get back to you about it soon✨

###### Please also check out the [docs](https://rasa.com/docs/) and the [forum](https://forum.rasa.com/) in case your issue was raised there too 🤗

**Comment by erohmensing** [comment]
@mlcode-jeevan this is a usage question, not a bug or feature request -- you can ask questions on our [forum](http://forum.rasa.com), and please don't ignore the issue template when it tells you to do so. The rasa API is also documented [here](https://rasa.com/docs/rasa/api/http-api/).
