### ISSUE TITLE
Silent failure when the number of intents is less than 2

### ISSUE THREAD

**Issue by furqan-shakoor** [RasaHQ/rasa#4390]
**Rasa version**: '0.15.1'

**Rasa X version** (if used & relevant):

**Python version**: 3.7

**Operating system** (windows, osx, ...): MacOS

**Issue**:
If the number of intents in an application is less than 2, the application does not correctly classify any inputs to an intent.

The endpoints `/train` and `/parse` both return 200 in such a case, indicating no errors. But the server logs show the following errors when `/parse` is called

```
2019-09-04 17:16:23+0200 [-] 2019-09-04 17:16:23 WARNING  rasa_nlu.classifiers.embedding_intent_classifier  - Failed to load nlu model. Maybe path /Users/furqan/sandbox/furqs/a3ea383570354a609776bbfeb26493dd/2 doesn't exist
2019-09-04 17:16:23+0200 [-] 2019-09-04 17:16:23 ERROR    rasa_nlu.classifiers.embedding_intent_classifier  - There is no trained tf.session: component is either not trained or didn't receive enough training data
```

I traced the error to the following snippet of code in `embedding_intent_classifier.py`, in the function `train`

```
        intent_dict = self._create_intent_dict(training_data)
        if len(intent_dict) < 2:
            logger.error("Can not train an intent classifier. "
                         "Need at least 2 different classes. "
                         "Skipping training of intent classifier.")
            return
```

Since this block bails out of the train function, as a consequence the training of the EmbeddingIntentClassifier never goes through and the relevant training files are never saved.

Eventually when `/train` is called, the `load` function of `EmbeddingIntentClassifier` fails because of the snippet `if model_dir and meta.get("file")`. This translates into the `session` attribute not being set and then the `process` method failing because `self.session is None`

I believe the `/train` endpoint should return an error in such a case and let the user know that train was in fact not successful

**Comment by sara-tagger** [comment]
Thanks for the issue, @Ghostvv will get back to you about it soon!

###### You may find help in the [docs](https://rasa.com/docs/) and the [forum,](https://forum.rasa.com/) too 🤗

**Comment by erohmensing** [comment]
This makes sense. Would you be interested in contributing a fix @furqan-shakoor ?

**Comment by jeanfrancois8512** [comment]
I have reproduced the behavior in 0.15.1. If failing early is the good behavior when training a component, one way to do it is:

```python
        intent_dict = self._create_intent_dict(training_data)
        if len(intent_dict) < 2:
            raise Exception("Can not train an intent classifier. "
                         "Need at least 2 different classes. "
                         "Skipping training of intent classifier.")
```
This will make the server return a 500 status code with the message as content. I haven't tested this in master. The server has changed since 0.15.1 and more test will be needed.

**Comment by lucianaribeiro** [comment]
I would like to work on that

**Comment by erohmensing** [comment]
awesome @lucianaribeiro 🎉would be great if you could look into this issue on master. Let us know if you need any help! Maybe @jeanfrancois8512 can also help!

**Comment by erohmensing** [comment]
not stale, in discussion atm
