### ISSUE TITLE
where is the code for bert pruning?

### ISSUE THREAD

**Issue by Jasperty** [RasaHQ/rasa#4397]
https://blog.rasa.com/pruning-bert-to-accelerate-inference/

**Comment by JulianGerhard21** [comment]
Hi @Jasperty ,

after investigating the branch mentioned in the blog post, you could take a look at:

* folder **bert**
* folder **fake_neuron_pruning**
* file **compression_utils.py**

[here](https://github.com/RasaHQ/rasa/tree/compressing-bert/rasa/nlu/classifiers).

Regards
Julian

**Comment by Jasperty** [comment]
i change to compress-bert branch, but i cannot find the folder you mentioned.

**Comment by Jasperty** [comment]
Thanks a lot, i get it

**Comment by jianqianzhou** [comment]
> Hi @Jasperty ,
> 
> after investigating the branch mentioned in the blog post, you could take a look at:
> 
> * folder **bert**
> * folder **fake_neuron_pruning**
> * file **compression_utils.py**
> 
> [here](https://github.com/RasaHQ/rasa/tree/compressing-bert/rasa/nlu/classifiers).
> 
> Regards
> Julian

There have any docs or examples to start bert pruning？
