### ISSUE TITLE
Intent as optional field in nlu.json

### ISSUE THREAD

**Issue by smar10** [RasaHQ/rasa#4398]
Hey guys,
I'm trying to create an nlu.json file without define the "intent" field, only entities. 

The documentation https://rasa.com/docs/nlu/dataformat/ says that intent is an optional field: 

> The intent is the intent that should be associated with the text [optional]

so it should work - however , i've tried that in multiple ways (with empty field, none, null) but none of them work.

Any ideas how to solve that ?
Many thanks

**Comment by sara-tagger** [comment]
Thanks for the question, our Github issue board is for **bugs and feature requests only,** though 😕
Please ask this question in the [forum✨](https://forum.rasa.com/c/rasa)

###### If you were describing a bug, please create a [report](https://github.com/RasaHQ/rasa/issues/new?labels=bug&template=bug_report.md) and fill out the template
