### ISSUE TITLE
Run tests in parallel

### ISSUE THREAD

**Issue by icaropires** [RasaHQ/rasa#4402]
**Description of Problem**:

I noticed that the tests are run on a single core which can be much slower on a multi-core machine. I've run the tests with `make tests` on my machine which has a `Intel Core i5-4210U` and it took 1769.57 seconds and running in parallel took 1054.12 which is a great improvement ! It spent 59% of the original time. This gain can improve the development time for all the developers.

**Overview of the Solution**:

The solution involves installing `pytest-xdist` and running the tests with `-n auto` flag. If this is a wanted feature, I'd like to code it.

**Blockers** (if relevant):

There is a problem. When running the tests in parallel, 7 tests failed. It's related to more than one server at different tests binding to the same port. I believe this is not so hard to solve. 

**Definition of Done**:

- [ ] Describe on docs how to run the tests in parallel and sequentially
- [ ] Do not slowdown the CI build
- [ ] Fix broken network tests

**Comment by sara-tagger** [comment]
Thanks for submitting this feature request 🚀@msamogh will get back to you about it soon!✨

**Comment by tmbo** [comment]
I think this is a good idea. Prob won't make a huge difference on travis due to vm limitations but I agree that locally its a good idea.

**Comment by icaropires** [comment]
> I think this is a good idea. Prob won't make a huge difference on travis due to vm limitations but I agree that locally its a good idea.

Indeed, on travis the benefit will be reduced because the VMs only have 2 cores according to [this](https://docs.travis-ci.com/user/reference/overview/#virtualisation-environment-vs-operating-system). But there will be some gain, the travis itself give [some tips](https://docs.travis-ci.com/user/speeding-up-the-build/#makefile-parallelization-example).

Those flags added means that I can work on this issue or there will be more discussion?

**Comment by tmbo** [comment]
yes sounds good :+1:
