### ISSUE TITLE
how can we speed up weight pruning for bert?

### ISSUE THREAD

**Issue by Jasperty** [RasaHQ/rasa#4405]
on your blog https://blog.rasa.com/pruning-bert-to-accelerate-inference/, 
weight pruning will not speed up BERT, because we can not remove the pruned weights, so what about applying spared-matrix speed methods to it? do you have a try?

**Comment by sara-tagger** [comment]
Thanks for the question, our Github issue board is for **bugs and feature requests only,** though 😕
Please ask this question in the [forum✨](https://forum.rasa.com/c/rasa)

###### If you were describing a bug, please create a [report](https://github.com/RasaHQ/rasa/issues/new?labels=bug&template=bug_report.md) and fill out the template
