### ISSUE TITLE
I am installing rasa nlu but showing error during building wheel for spacy

### ISSUE THREAD

**Issue by ihtisham0331** [RasaHQ/rasa#4406]

**Comment by sara-tagger** [comment]
Thanks for the question, our Github issue board is for **bugs and feature requests only,** though 😕
Please ask this question in the [forum✨](https://forum.rasa.com/c/rasa)

###### If you were describing a bug, please create a [report](https://github.com/RasaHQ/rasa/issues/new?labels=bug&template=bug_report.md) and fill out the template
