### ISSUE TITLE
webchat is not working

### ISSUE THREAD

**Issue by ice2tricky** [RasaHQ/rasa#4407]
Webchat is not working anymore with the 1.3 release

**Comment by sara-tagger** [comment]
Thanks for raising this issue, @erohmensing will get back to you about it soon✨

###### Please also check out the [docs](https://rasa.com/docs/) and the [forum](https://forum.rasa.com/) in case your issue was raised there too 🤗

**Comment by erohmensing** [comment]
@ice2tricky you'll have to be a little more descriptive if you want help -- what is going wrong? What is different between 1.2.7 and 1.3.0?

**Comment by erohmensing** [comment]
As described in the issue template

> THIS INFORMATION IS MANDATORY - YOUR ISSUE WILL BE CLOSED IF IT IS MISSING. 

please fill out the issue template so we can help you.
