### ISSUE TITLE
Rasa X Logger Exit

### ISSUE THREAD

**Issue by rgstephens** [RasaHQ/rasa#4412]
**Rasa X version**: 0.20.2

For the docker CE deployment, I've found that the logger has not been working the past few releases. I just updated to the current release this morning and it continues to fail.  With the docker container setting to `always` Docker is constantly re-starting the logging container.

```
rasax_logger_1 exited with code 0
```

The output file from this container is created but always zero. Because of the restarts, the logs directory is full of empty files that are created once per 4 seconds on my system.

**Comment by sara-tagger** [comment]
Thanks for the issue, @tmbo will get back to you about it soon!

###### You may find help in the [docs](https://rasa.com/docs/) and the [forum,](https://forum.rasa.com/) too 🤗
