### ISSUE TITLE
Domain validation fails to look for duplicate entries

### ISSUE THREAD

**Issue by ruiconti** [RasaHQ/rasa#4417]
**Rasa version**: 1.2.3

**Python version**: 3.6.8

**Operating system** (windows, osx, ...): macOS

**Issue**: The cause to this issue was that there were duplicate definitions under `actions` section. Validator should accurately point out that this was the case, which it didn't. Method [verify_all()](https://github.com/RasaHQ/rasa/blob/master/rasa/core/validator.py#L165) fails to verify if an action is defined more than once.

**Error (including full traceback)**:
```
2019-09-09 09:52:21 ERROR    rasa.core.validator  - The intent 'room_reservation+new' is in the NLU training data, but is not listed in the domain.
2019-09-09 09:52:21 ERROR    rasa.core.validator  - The intent 'enter_data' is in the NLU training data, but is not listed in the domain.
2019-09-09 09:52:21 ERROR    rasa.core.validator  - The intent 'bye' is in the NLU training data, but is not listed in the domain.
...
```

**Command or request that led to error**:
```
rasa data validate --domain config/domain.yml --data data
```

**Content of domain file (domain.yml)** (if relevant):
```yml
intents:
- greet
- enter_data
- affirm
- deny
- bye
- deny+unsure
...
```

**Comment by ruiconti** [comment]
Another thing (kinda related): When validating utterances, Validator doesn't exclude Form-related utterances that almost always aren't used in stories:

```
2019-09-09 10:09:02 WARNING  rasa.core.validator  - The utterance 'utter_ask_reservation_duration' is not used in any story.
2019-09-09 10:09:02 WARNING  rasa.core.validator  - The utterance 'utter_ask_reservation_start_hour' is not used in any story.
2019-09-09 10:09:02 WARNING  rasa.core.validator  - The utterance 'utter_ask_reservation_participants' is not used in any story.
```

**Comment by sara-tagger** [comment]
Thanks for raising this issue, @tmbo will get back to you about it soon✨

###### Please also check out the [docs](https://rasa.com/docs/) and the [forum](https://forum.rasa.com/) in case your issue was raised there too 🤗

**Comment by tmbo** [comment]
Very good point we should def add some rules to fix these two issues. Do you mind creating a PR?

**Comment by erohmensing** [comment]
For what it is worth regarding the second point, there's no way for the validator to know which utterances are associated with forms and which aren't -- it's also quite possible that someone, after creating a form with `utter_ask_{}` methods, also creates other similar ones (e.g. `utter_ask_continue_newsletter` and `utter_ask_feedback` in our [demo bot stories](https://github.com/RasaHQ/rasa-demo/blob/master/data/core/handoff.md).

Not sure exactly what the solution is there, but wanted to bring it up.

**Comment by ruiconti** [comment]
@tmbo absolutely. Will do in a few days

@erohmensing That's a good point. In my view, there are two possible ways:
1. Include the option to reference `actions.py` in `rasa validate`. Then if it finds Forms declarations in that file, calls `slot_mapping` (that doesn't asks for any parameter) and removes `utter_ask_{slot_name}`, specifically.
Although I'm not sure if it's worth adding this complexity as it is just a warning.
2. Looks for unfeaturized slots in `domain.yml`, creates `utter_ask_{slot_name}` and removes any matching result

**Comment by tmbo** [comment]
This should be fixed as far as I know, the domain should emit warnings for duplicated intents, entities and actions as soon as it gets loaded (which happens during validation).
