### ISSUE TITLE
improve slack sanitization

### ISSUE THREAD

**Issue by erohmensing** [RasaHQ/rasa#4418]
we already do some sanitization of slack input [here](https://github.com/RasaHQ/rasa/blob/master/rasa/core/channels/slack.py#L181) where we clear out some mentions. 

Entity extraction can be sometimes influenced by the way slack processes user input, for example links or emails provided by the user. There should be regex sanitization that cleans these and brings them back to what the user originally input so that the extractors and intent classifiers are not affected. 

See the forum posts for more information:
https://forum.rasa.com/t/entity-extraction-problem-due-to-slack-adding-link/3691/6
https://forum.rasa.com/t/entity-extraction-for-hostnames-with-punctuations/15430

**Comment by vigneshp826** [comment]
https://github.com/RasaHQ/rasa/pull/4475 submitted. Please review and let me know for any changes

**Comment by erohmensing** [comment]
Awesome @vigneshp826, thanks!

**Comment by erohmensing** [comment]
closed in #4475
