### ISSUE TITLE
Add template id to bot event

### ISSUE THREAD

**Issue by mdimercurio** [RasaHQ/rasa#4424]
**Description of Problem**:

Right now, [bot events](https://rasa.com/docs/rasa/api/events/#bot-responded-message) only include the message text. It would be useful to also include the template id (eg: `utter_[action]` ) to make it easier to get all events for a single utterance. We are using events for analysis purposes with multi-language bots so having a common ID across languages would make it easier to analyze questions/answers. Also when copy of a template changes, the event would still keep the same template id.

**Overview of the Solution**:

Add templates to bot utterance events

**Definition of Done**:
- [ ] Templates are added as a property in the bot events
- [ ] Tests are added
- [ ] Feature described the docs
- [ ] Feature mentioned in the changlog

**Comment by sara-tagger** [comment]
Thanks for submitting this feature request 🚀@tabergma will get back to you about it soon!✨

**Comment by tabergma** [comment]
I guess, we could add the template name to the metadata of the bot utterance (https://github.com/RasaHQ/rasa/blob/master/rasa/core/events/__init__.py#L325). That way we do not influence existing behaviour.

Are you up adding the template name to the metadata yourself?
