### ISSUE TITLE
Rasa X UI to show version info

### ISSUE THREAD

**Issue by rgstephens** [RasaHQ/rasa#4425]
**Description of Problem**: An end user (non developer) can't easily determine which version of Rasa X and Rasa they are using from the UI. The current Support option opens a link to a forum issue. This assumes we have a live connection to forum. It also only shows the Rasa X version and in my 0.20.2 install of Rasa X it reports the version as `dev-CC` instead of `0.20.2`

**Overview of the Solution**: Provide a Rasa X UI `about` or other menu item that shows the version of Rasa X, Rasa, Postgres, etc.

**Comment by sara-tagger** [comment]
Thanks for submitting this feature request 🚀@erohmensing will get back to you about it soon!✨
###### Caw! 🐧

**Comment by erohmensing** [comment]
Thanks for the suggestion! I agree that it would be nice to have in the UI. For now, you can find the rasa x and rasa versions at http://host/api/version (I assume you know this because of your first sentence, but just for anyone else looking for this info...) I'll add it to the inbox.

> It also only shows the Rasa X version and in my 0.20.2 install of Rasa X it reports the version as dev-CC instead of 0.20.2

You see `dev-CC` when hitting the version endpoint?

**Comment by JEM-Mosig** [comment]
It might also come in handy to have a "Copy debug information to clipboard" button somewhere, where it copies rasa version, rasa x version, browser, OS, etc. all at once in a standard format, so people can directly paste this in the forum, GitHub, or wherever they need it.

**Comment by gausie** [comment]
The reason we're getting `dev` being reported as the version is because I think `REACT_APP_GIT_SHA` is no longer being set in Travis - it should be reporting the git commit hash that gets read by the frontend.

**Comment by rgstephens** [comment]
I think it would be good to display the output of /api/version. In troubleshooting conversations on the forum, this is one of the more common requests, for users to go to this endpoint and report the versions.

**Comment by abhilasharoy** [comment]
This should be solved once this is implemented.

https://github.com/RasaHQ/rasa-x/issues/2298

**Comment by erohmensing** [comment]
@abhilasharoy as mentioned in slack, i wouldn't agree with that comment as in the current design, you can not see your version info if you are not running an outdated version

**Comment by abhilasharoy** [comment]
Yea makes sense @erohmensing  - this problem is not solved for people on the latest version.

**Comment by edmacovaz** [comment]
Looking at this as part of #2768 

![Latest version](https://user-images.githubusercontent.com/129265/82066196-5ebc0b00-96cf-11ea-8b52-53c6a4cab067.png)

**Comment by alexweidauer** [comment]
Thank you for raising this issue about Rasa X. We decided to stop supporting the Community Edition (free version) of ‘Rasa X’ (see more info here: https://rasa.com/blog/rasa-x-community-edition-changes/). That’s why we’ve closed your issue. We suggest that Rasa Enterprise customers raise the issue with our customer support team if they haven’t done so already.
