### ISSUE TITLE
slack integration through bot frame work not working and buttons through facebook also not working using the botframework

### ISSUE THREAD

**Issue by ice2tricky** [RasaHQ/rasa#4426]
Rasa version: 1.2.5 - 1.3.0

Rasa X version (if used & relevant):

Python version: 3.7

Operating system (windows, osx, ...): windows

Issue:
slack still not working if you go through the bot framework and buttons are not working on facebook through the botframework 

**Error (including full traceback)**:
```
slack error:

2019-09-10 09:40:03 ERROR    rasa.core.channels.botframework  - Error trying to send botframework messge. Response: {
  "error": {
    "code": "ServiceError",
    "message": "Invalid ChannelData"
  }
}



facebook error: 
2019-09-10 09:35:50 ERROR    rasa.core.channels.botframework  - Error trying to send botframework messge. Response: {
  "error": {
    "code": "ServiceError",
    "message": "Facebook API error",
    "innerHttpError": {
      "statusCode": 400,
      "body": {
        "message": "(#100) Web url cannot be empty for url type button",
        "type": "OAuthException",
        "code": 100,
        "error_subcode": 2018041,
        "fbtrace_id": "APJCiYJpJRcLJGkIXoi6aE2"
      }
    }

```

**Command or request that led to error**:
```

```

**Content of configuration file (config.yml)** (if relevant):
```yml

```

**Content of domain file (domain.yml)** (if relevant):
```yml

```

**Comment by sara-tagger** [comment]
Thanks for raising this issue, @gausie will get back to you about it soon✨

###### Please also check out the [docs](https://rasa.com/docs/) and the [forum](https://forum.rasa.com/) in case your issue was raised there too 🤗

**Comment by akelad** [comment]
@ice2tricky can I ask why you're using the bot framework channel instead of the facebook channel if you're trying to connect to facebook?

**Comment by ice2tricky** [comment]
I have all channels setup on botframework and if i tunnel with ngrok I only have to change one address. Instead of going to each of them seperately.

Outlook voor Android downloaden<https://aka.ms/ghei36>

________________________________

**Comment by akelad** [comment]
I assume you mean Microsoft botframework right? Can you show me your credentials file?
But in general this won’t work, because sending messages looks different for each end channel
