### ISSUE TITLE
Drop python 3.5 support

### ISSUE THREAD

**Issue by ricwo** [RasaHQ/rasa#4437]
Version 19.6 of Sanic [drops](https://sanic.readthedocs.io/en/latest/sanic/changelog.html#deprecations-and-removals) support for Python 3.5. Does anyone depend on python 3.5 or have any objections?

**Comment by wochinge** [comment]
@erohmensing What did our customers say?
@tmbo Any objections?

When dropping the support, we can also clean up / remove stuff which we we did for Python 3.5 compatibility:
- manual ordering of dicts (e.g. in Domain, TrainingData
- casting Path

From Ella:
> and all the tests where we had to say the result was one of a few different possible dicts (goes along with dict ordering)

**Comment by erohmensing** [comment]
No qualms from the customers yet!

**Comment by wochinge** [comment]
Okay, please give a go in here as soon as you have all the feedback.

**Comment by erohmensing** [comment]
@wochinge I'll collect and make sure we hear from everyone on our customer board -- can you check in with Ergo and Helvitia

**Comment by wochinge** [comment]
Scalable + Ergo are fine
