### ISSUE TITLE
Intent Featurization when using SpacyNLP components

### ISSUE THREAD

**Issue by dakshvar22** [RasaHQ/rasa#4443]
**Rasa version**: 1.3.2

**Python version**: 3.6

**Operating system** (windows, osx, ...): osx

**Issue**: We currently rely on spacy doc of the intent - `intent_spacy_doc` for featurization of intent by extracting `vector` attribute from the spacy doc. This is not ideal because intent labels can have gibberish text for which lemmas won't exist and hence result in a zero vector.

**Comment by dakshvar22** [comment]
After discussing internally a possible solution:

Completely do away with `intent_spacy_doc` and handle intent featurization and tokenization inside `EmbeddingIntentClassifier`. That mandates people to use a `CountVectorizer` and `WhitespaceTokenizer`(if handling multiple intents) always for intent classification.

This brings up an edge case:

Let’s say the developer's configuration was like this -
```
- name: SpacyNLP
- name: SpacyTokenizer
- name: WhitespaceTokenizer
  intent_tokenization_flag: True
  intent_split_symbol: '_'
- name: SpacyFeaturizer
- name: CountVectorFeaturizer
- name: EmbeddingIntentClassifier
```
Now whitespace tokenizer and spacy tokenizer both will tokenize text. Is it certain that for all type of characters in the text, the tokenization result from both components will be the same? Because otherwise one would overwrite the other.
`WhitespaceTokenizer` may be needed compulsorily to handle multiple intents, and the user may want to augment spacy features with count vector features for `text` attribute of message and hence needs SpacyNLP.

**Comment by dakshvar22** [comment]
We can avoid the ambiguity by still keeping `intent_spacy_doc`, let `SpacyTokenizer` do the intent tokenization for all three attributes as it does now and featurization of intent skipped inside `SpacyFeaturizer` and done by CountVectorFeaturizer if it exists(as in the above case) and if not then by EmbeddingIntentClassifier(default fallback to one hot representation). We don’t need `WhitespaceTokenizer` then.

**Comment by dakshvar22** [comment]
There are two valid requirements driving the above configuration -
1. Handling multiple intents
2. Augmenting Spacy features with BOW features.

**Comment by Ghostvv** [comment]
1. tokenizers override themselves
2. if `SpacyNLP` is there, `CountVectorizer` will use `spacy_doc.lemma_` regardless of the tokenizer, so the presence of whitespace and/or spacy tokenizer will not influence text features.
3. I'm not sure `SpacyTokenizer` correctly tokenizes gibberish words like intent labels could be
4. Using `spacy` for tokenization without using `spacy` features is counterintuitive

**Comment by Ghostvv** [comment]
Related to https://github.com/RasaHQ/rasa/issues/4440
