### ISSUE TITLE
Update to rasa-1.3.2 give me the ERROR: rasa-x 0.20.2 has requirement rasa~=1.2.5, but you'll have rasa 1.3.2 which is incompatible.

### ISSUE THREAD

**Issue by dptelecom** [RasaHQ/rasa#4447]
**rasa-1.3.2**:

**Rasa X version 0.20.2** (if used & relevant):

**Python version3.7**:

**Osx** (windows, osx, ...):

**Update to rasa-1.3.2 
give me the 
ERROR: rasa-x 0.20.2 has requirement rasa~=1.2.5, but you'll have rasa 1.3.2 which is incompatible.**:

**Error (including full traceback)**:
```

```

**Command or request that led to error: sudo -H pip3 install -U rasa
![Screen Shot 2019-09-12 at 15 21 35](https://user-images.githubusercontent.com/42352742/64788345-8d974580-d572-11e9-9cc8-26ea8de8ffdf.jpg)
**:
```

```

**Content of configuration file (config.yml)** (if relevant):
```yml

```

**Content of domain file (domain.yml)** (if relevant):
```yml

```

**Comment by federicotdn** [comment]
Hi @dptelecom, we recommend you install Rasa X and Rasa on separate virtual environments, as Rasa X has a dependency on a specific Rasa version. If you install both globally, then you might accidentally install an incompatible Rasa version for Rasa X.
