### ISSUE TITLE
Fallback Threshold Based on Entity Confidence

### ISSUE THREAD

**Issue by rjtmehta99** [RasaHQ/rasa#4453]
Hi !
While implementing FallbackPolicy, we have the option to trigger fallback when intent confidence is below the threshold. How can we trigger fallback when the entity confidence is below a threshold ?

The brute force way would be:
1. Add a custom action for every intent.
2. Retrieve entity confidence.
3. Respond based on the value from previous step.

But if the intents are higher in value, it would be cumbersome. 

Any suggestions will be helpful.

**Comment by sara-tagger** [comment]
Thanks for the question, our Github issue board is for **bugs and feature requests only,** though 😕
Please ask this question in the [forum✨](https://forum.rasa.com/c/rasa)

###### If you were describing a bug, please create a [report](https://github.com/RasaHQ/rasa/issues/new?labels=bug&template=bug_report.md) and fill out the template
