### ISSUE TITLE
Fallback Threshold Based on Entity Confidence

### ISSUE THREAD

**Issue by rjtmehta99** [RasaHQ/rasa#4454]
Hi !
While implementing FallbackPolicy, we have the option to trigger fallback when intent confidence is below the threshold. How can we trigger fallback when the entity confidence is below a threshold ? If there no such feature available can it be added in future releases?

The brute force way would be:

    Add a custom action for every intent.
    Retrieve entity confidence.
    Respond based on the value from previous step.

But if the intents are higher in value, it would be cumbersome.

Any suggestions will be helpful.

**Comment by sara-tagger** [comment]
Thanks for submitting this feature request 🚀@federicotdn will get back to you about it soon!✨
