### ISSUE TITLE
Implement buttons for Mattermost channel

### ISSUE THREAD

**Issue by mexophantes** [RasaHQ/rasa#4455]
**Description of Problem**:

Buttons in Mattermost appear currently only as text message, not as clickable buttons. See also 
this thread in the [forum](https://forum.rasa.com/t/rasa-buttons-not-appearing-in-mattermost/12984/3).

**Overview of the Solution**:

Changes are necessary in 
* rasa\core\channels\mattermost.py
    * Implement `send_text_with_buttons()` in `MattermostBot `class according to [mattermost message buttons docs](https://docs.mattermost.com/developer/interactive-messages.html#message-buttons)
   * Initialize `MattermostBot `and `MattermostInput `with an additional parameter `webhook_url`
* rasa\cli\initial_project\credentials.yml (not really necessary, but very helpful for an easy start)
    * add Mattermost example with additional `webhook_url`

**Examples** (if relevant):

Current state:
![image](https://user-images.githubusercontent.com/26031391/64861112-6783ab00-d62f-11e9-8fa0-d472be9e48ef.png)

Future state:
![image](https://user-images.githubusercontent.com/26031391/64861046-458a2880-d62f-11e9-8f33-9649b0234772.png)

**Blockers** (if relevant):

**Definition of Done**:

- [ ] Tests are added
- [ ] Feature described the doc
- [ ] Feature mentioned in the changelog

**Comment by sara-tagger** [comment]
Thanks for submitting this feature request 🚀@tabergma will get back to you about it soon!✨

**Comment by tabergma** [comment]
Sounds like a good addition! Do you want to add this yourself and open a PR for it?

**Comment by mexophantes** [comment]
> Sounds like a good addition! Do you want to add this yourself and open a PR for it?

The PR is already created: https://github.com/RasaHQ/rasa/pull/4456
