### ISSUE TITLE
unfortunate use of kwarg 'kwargs' results in some arguments not having effect

### ISSUE THREAD

**Issue by imLew** [RasaHQ/rasa#4458]
In a couple of places (e.g. `rasa.train` and `rasa.core.train`) we have a keyword argument called `kwargs`.
This is a confusing name as `**kwargs` is conventionally used to capture 0 or more additional, optional keyword arguments. 
These function signatures should be changed, either by using a different name for this variable (`additional_arguments`) or by adapting them to use `**kwargs`.

This also causes the argument `dump_stories` of `rasa.train` to have no effect at all. (See https://forum.rasa.com/t/how-can-i-use-dump-stories-from-script/15433)

Update:
Another place where we use `kwargs` as a name for a dict instead of a container for optional keyword arguments is https://github.com/RasaHQ/rasa/blob/bd83681222f6ad60997df40964c51bf79858df2e/rasa/test.py#L37

**Comment by AlvaroMonteagudo** [comment]
Any thoughts on this, it's been a while

**Comment by imLew** [comment]
I'm sorry @AlvaroMonteagudo, we haven't had time to address this yet. 
Were you not able to fix it locally?
