### ISSUE TITLE
blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource

### ISSUE THREAD

**Issue by piyush29programmer** [RasaHQ/rasa#4459]
**Rasa version**: 1.3.2

**Rasa X version** (if used & relevant):

**Python version**:3.6

**Operating system** (windows, osx, ...): Windows 10

**Issue**:

We are not able to connect MR.bot widget with rasa using socketio.

I had faced the same issue in rasa = 1.2.0 but after downgrading the python-engineio==3.8.1 .

After seeing a lot of articles that this issue is fixed in the new version. I tried to install the rasa =1.3.2

but the issue is same and looks like it's not fixed. Could anybody please help?

**Mr bot script**
```
<script>
    WebChat.default.init({
        selector: "#webchat",
        initPayload:
            "/get_started",
        interval: 1000, 
        socketUrl: "http://localhost:5005", 
        socketPath: "/socket.io/",
        title: "Chat ",
        subtitle: "",
        inputTextFieldHint: "Type a message...",
        connectingText: "Waiting for server...",
        hideWhenNotConnected: false,
        fullScreenMode: false,
        profileAvatar: "Images/User.png",
        openLauncherImage:
            "",
        closeLauncherImage: "",
        params: {
            images: {
                dims: {
                    width: 300,
                    height: 200,
                }
            },
            storage: "session"
        }
    });
</script>
```
**Credentials.yml**
```

socketio:
  user_message_evt: user_uttered
  bot_message_evt: bot_uttered
  session_persistence: true
```

**Error (including full traceback)**:
Access to XMLHttpRequest at 'http://localhost:5005/socket.io/?EIO=3&transport=polling&t=MqhDu8m' from origin 'http://localhost:3073' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.

**Command or request that led to error**:
```
rasa run -m models --credentials credentials.yml --cors '*'

```

**Comment by sara-tagger** [comment]
Thanks for raising this issue, @TyDunn will get back to you about it soon✨

###### Please also check out the [docs](https://rasa.com/docs/) and the [forum](https://forum.rasa.com/) in case your issue was raised there too 🤗

**Comment by erohmensing** [comment]
Can you try adding `--enable-api` to the command? You shouldn't need to, but right now it is part of a workaround: https://github.com/RasaHQ/rasa/issues/4463

**Comment by piyush29programmer** [comment]
@erohmensing  thank you for the workaround and its working now.
We are planning to upgrade the rasa in production to 1.3.2 but is this workaround is good enough to upgrade or should we wait for the bug fix.

**Comment by erohmensing** [comment]
It shouldn't be an issue in production, you can also secure the API with a token so that there aren't any erroneous requests coming in. Are you using Rasa x at all? If so, there currently isn't a version that runs on Rasa>=1.3

**Comment by piyush29programmer** [comment]
No we are using rasa only .

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by erohmensing** [comment]
closed in https://github.com/RasaHQ/rasa/pull/4521

**Comment by MohammedAyanTheGreat** [comment]
I m facing this issue i m not able to fix it
