### ISSUE TITLE
Text from telegram custom json not saved to the tracker store

### ISSUE THREAD

**Issue by r-m-n** [RasaHQ/rasa#4461]
**Rasa version**: 1.3.3

**Rasa X version** (if used & relevant):

**Python version**:

**Operating system** (windows, osx, ...):

**Issue**: 
I send a markdown message in telegram with `utter_custom_json`:
```python
dispatcher.utter_custom_json({
    "text": "*hello world*",
    "parse_mode": 'Markdown',
})
```
But only `parse_mode` field is saved in tracker store:
```python
{"data":
    {
        "attachment": None,
        "buttons": None,
        "custom": {"parse_mode": "Markdown"},
        "elements": None,
        "image": None,
        "quick_replies": None
    }
}
```

**Error (including full traceback)**:
```

```

**Command or request that led to error**:
```

```

**Content of configuration file (config.yml)** (if relevant):
```yml

```

**Content of domain file (domain.yml)** (if relevant):
```yml

```

**Comment by sara-tagger** [comment]
Thanks for the issue, @imLew will get back to you about it soon!

###### You may find help in the [docs](https://rasa.com/docs/) and the [forum,](https://forum.rasa.com/) too 🤗

**Comment by imLew** [comment]
Hi @r-m-n, thanks for raising this issue and creating a PR for it. We'll get back to you about the PR asap.
