### ISSUE TITLE
Verbose message when domain.yml parsing fails.

### ISSUE THREAD

**Issue by lahsuk** [RasaHQ/rasa#4465]
When there is a mistake in the format in the domain file, training for core fails silently. All it prints is a single message saying: `DEBUG    rasa.importers.rasa  - Loading domain from 'domain.yml' failed. Using empty domain.` It doesn't provide any information on where the parsing failed.

```
- utter_answer
  - text: "You have typed the word "mango" wrong".  # the double quotes make this invalid
```

Rather than failing silently, it could at least give the line number where the parsing fails.

**Comment by sara-tagger** [comment]
Thanks for submitting this feature request 🚀@akelad will get back to you about it soon!✨

**Comment by akelad** [comment]
That's a good point, thanks for the suggestion! Is this something you'd be willing to work on?

**Comment by arni5na** [comment]
@akelad Is there a workaround for this issue? It's crazy that you'll give this error and not point where. I got more than a thousand lines in my domain file. How am I supposed to find which line went wrong?

**Comment by akelad** [comment]
You can use a yaml validator for now - we're open to community members working on this issue, otherwise we will get around to fixing it eventually.

**Comment by arni5na** [comment]
Yes, but it's not only happening for syntax errors. It's throwing the same error if there are any duplicates in the domain file. I was able to get around it after a couple of hours of tinkering. Now, when I tried to train, it couldn't find the stories file. It's just right there in the data folder. I suspect this is the same issue. Another couple hours of my life wasted on this. Such a nuisance.
