### ISSUE TITLE
Rasa data.json doesn't support any format other than ANSI 

### ISSUE THREAD

**Issue by indranil180** [RasaHQ/rasa#4474]
I found a bug in RASA it is an unusual behaviour RASA data.json throws error when the data format is other than ANSI.
I am using RASA 1.0.6 and i tried the same in older versions as well the issue persist. It would be great if RASA handles this behaviour.

**Comment by sara-tagger** [comment]
Thanks for raising this issue, @tabergma will get back to you about it soon✨

###### Please also check out the [docs](https://rasa.com/docs/) and the [forum](https://forum.rasa.com/) in case your issue was raised there too 🤗

**Comment by tabergma** [comment]
@indranil180 Please, share some more information:
- Does `data.json` refer to the NLU data file? Or what do you store in that file?
- Can you paste the error message here? 
- What command did you execute? (In order to reproduce the problem.)
Thanks.

**Comment by indranil180** [comment]
Yes from `data.json` i meant NLU data file.
I have created the data.json file in below format.

```
{
    "rasa_nlu_data": {
        "common_examples": [],
        "regex_features" : [],
        "lookup_tables"  : [],
        "entity_synonyms": []
    }
}
```
When i run `rasa train` to train i am getting below error.

> ValueError: Unknown data format for file “data\data.json”

When i changed my data.json encoding to ANSI it started working. I checked in the community a lot of people are facing this same issue. I have guided them in solving the issue. Below is the link from rasa forum where someone solved it using my method. I am using RASA 1.1.6

[RASA Forum](https://forum.rasa.com/t/unknow-data-format-error-during-nlu-training-and-format-conversion/12485)

**Comment by tabergma** [comment]
Thanks for the details! 

Do you want to fix the issue yourself and open a PR for it?

**Comment by indranil180** [comment]
> Thanks for the details!
> 
> Do you want to fix the issue yourself and open a PR for it?

**Comment by indranil180** [comment]
Please open a PR for it.

**Comment by tabergma** [comment]
I added the issue to our backlog. We will have a look in the near feature.

**Comment by wochinge** [comment]
@tabergma Just to clarify: currently we are only supporting `utf-8` and we should also support other encodings?

**Comment by indranil180** [comment]
@wochinge it is working with `ANSI` only it is throwing error `ValueError: Unknown data format for file “data\data.json”` with other encodings.

**Comment by tmbo** [comment]
I don't think we should use different formats, it should always be utf-8. I don't see a benefit in supporting different encodings beyond utf-8 - which means we should check why this one is ANSI in the first place.

**Comment by wochinge** [comment]
@indranil180 Do you have any more input on that? Otherwise I'd close this.
