### ISSUE TITLE
embedding_response_selector has not installed with the installation procedures mentioned in the documentation

### ISSUE THREAD

**Issue by Sarvin92** [RasaHQ/rasa#4482]
I have used the below command line to install new version of rasa,

    $ pip install rasa-x --extra-index-url https://pypi.rasa.com/simple

The embedding_response_selector has not installed in rasa.nlu.selectors. To be specific no folders for selectors has been found after installation.

**Comment by dakshvar22** [comment]
@Sarvin92 `rasa.nlu.selectors` was added in `Rasa 1.3.0`. Since `Rasa-X` is currently not compatible with `Rasa 1.3.0`, pip install fetches `Rasa 1.2.5`.
We are working on getting `Rasa-X` compatible with `Rasa 1.3.0` and releasing it.

**Comment by Sarvin92** [comment]
Thanks for the clarification @dakshvar22 

The installation has achieved by building from source, using the following command,

    $ git clone https://github.com/RasaHQ/rasa.git
    $ cd rasa
    $ pip install -r requirements.txt
    $ pip install -e .
