### ISSUE TITLE
Waiting for messages to come from users when integrated with the slack

### ISSUE THREAD

**Issue by hungph-dev-ict** [RasaHQ/rasa#4485]
Hello everyone, currently after integrating rasa into slack, I realize a problem like the following.
When the bot replies to the user, 'What did you do yesterday?'
Users reply to many actions, but in the form of many messages.
For example, the user replies as follows:
I played football -> then press enter
And then I went fishing. -> press enter
But when the user first presses the message has been put in rasa to reply, while I want it to merge the other two messages.
I think the solution is to mark the user's response message as a fixed word, then wait for that word in the action, when it receives it, it will process.
Does anyone have a better solution?
Thanks everyone.

**Comment by sara-tagger** [comment]
Thanks for the question, our Github issue board is for **bugs and feature requests only,** though 😕
Please ask this question in the [forum✨](https://forum.rasa.com/c/rasa)

###### If you were describing a bug, please create a [report](https://github.com/RasaHQ/rasa/issues/new?labels=bug&template=bug_report.md) and fill out the template
