### ISSUE TITLE
Rasa-core and Rasa-nlu has requirement of jsonschema 2.6, but jupyterlab-server has requirement of jsonschema 3.0.1

### ISSUE THREAD

**Issue by aravindan84** [RasaHQ/rasa#4486]
I am setting up a chatbot application using the attached Installation.txt file. While installing, I get error 
ERROR: jupyterlab-server 1.0.0 has requirement jsonschema>=3.0.1, but you'll have jsonschema 2.6.0 which is incompatible.

If I change the version of jsonschema in installation.txt to 3.0.1, I get the below error, while installing:
ERROR: rasa-nlu 0.15.0 has requirement jsonschema~=2.6, but you'll have jsonschema 3.0.1 which is incompatible.
ERROR: rasa-core 0.14.4 has requirement jsonschema~=2.6, but you'll have jsonschema 3.0.1 which is incompatible.

[Installation.txt](https://github.com/RasaHQ/rasa/files/3629903/Installation.txt)

**Comment by aravindan84** [comment]
I added the jupyterlab-server 0.3.4 version for testing purpose. Still it keeps failing.

**Comment by sara-tagger** [comment]
Thanks for the question, our Github issue board is for **bugs and feature requests only,** though 😕
Please ask this question in the [forum✨](https://forum.rasa.com/c/rasa)

###### If you were describing a bug, please create a [report](https://github.com/RasaHQ/rasa/issues/new?labels=bug&template=bug_report.md) and fill out the template
