### ISSUE TITLE
Running socket client throws errors during Interactive Learning

### ISSUE THREAD

**Issue by erohmensing** [RasaHQ/rasa#4487]
The socket client points to the rasa server, and if you don't change the defaults, `rasa interactive` runs on the same port as `rasa run` – therefore, socket is listening for events during `rasa interactive`. However, since the socket endpoint is not available during this, it leads to an error:

 <span class="error">[2019-08-01 11:45:37 +0200]</span> <span class="error">[23200]</span> <span class="error">[ERROR]</span> Exception occurred while handling uri: 'http://localhost:5005/socket.io/?EIO=3&transport=polling&t=MnCaWoQ'
 Traceback (most recent call last):
 File "c:\users\appdata\local\continuum\anaconda3\lib\site-packages\sanic\app.py", line 893, in handle_request
 handler, args, kwargs, uri = self.router.get(request)
 File "c:\users\appdata\local\continuum\anaconda3\lib\site-packages\sanic\router.py", line 407, in get
 return self._get(request.path, request.method, "")
 File "c:\users\appdata\local\continuum\anaconda3\lib\site-packages\sanic\router.py", line 469, in _get
 raise NotFound("Requested URL {} not found".format(url))
 sanic.exceptions.NotFound: Requested URL /socket.io/ not found
 <span class="error">[2019-08-01 11:45:37 +0200]</span> <span class="error">[23200]</span> <span class="error">[ERROR]</span> Exception occurred while handling uri: 'http://localhost:5005/socket.io/?EIO=3&transport=polling&t=MnCaXHh'
 Traceback (most recent call last):
 File "c:\users\appdata\local\continuum\anaconda3\lib\site-packages\sanic\app.py", line 893, in handle_request
 handler, args, kwargs, uri = self.router.get(request)
 File "c:\users\appdata\local\continuum\anaconda3\lib\site-packages\sanic\router.py", line 407, in get
 return self._get(request.path, request.method, "")
 File "c:\users\appdata\local\continuum\anaconda3\lib\site-packages\sanic\router.py", line 469, in _get
 raise NotFound("Requested URL {} not found".format(url))
 sanic.exceptions.NotFound: Requested URL /socket.io/ not found
 <span class="error">[2019-08-01 11:45:37 +0200]</span> <span class="error">[23200]</span> <span class="error">[ERROR]</span> Exception occurred while handling uri: 'http://localhost:5005/socket.io/?EIO=3&transport=polling&t=MnCaXHi'

If we are in interactive mode, we should probably consume this exception since it's not relevant.

**Comment by soundaraj** [comment]
@erohmensing you can disconnect the socket client during the `rasa interactive` in progress, because socket client was retrying every seconds so this error was raised.

**Comment by erohmensing** [comment]
@soundaraj I know you can, but it would be nice if it didn't raise the error since it shouldn't matter whether or not the client is connected while you're using interactive mode via the CLI

**Comment by erohmensing** [comment]
This also happens if you are using a different connector, e.g. If you normally run with socket and then are testing in `rasa shell`. So we should only show the exception if the `socketio` channel is active.

**Comment by optimiztik** [comment]
I have the same exception " sanic.exceptions.NotFound: Requested URL /socket.io/ not found " . Do we have any workaround for this also when can we expect this issue to be closed.

**Comment by erohmensing** [comment]
@optimiztik the exception does not cause any issues in the bot, it is only because your websocket it still open. The workaround, as @soundaraj said, is to disconnect the socket (close the page with the bot widget) while in interactive mode.  

The issue is open as a help wanted issue, which means it is not top priority for us to work on (seeing as it is annoying, but doesn't cause buggy behavior) and will be closed if someone decides to take it on and surpress the warning.

**Comment by erohmensing** [comment]
Still valid, IMO

**Comment by MadPr0grammer** [comment]
Hi @erohmensing !

I would like to work on this. May I please take this up?

**Comment by erohmensing** [comment]
HI @MadPr0grammer! Sorry for missing your message. You absolutely can, i'll assign you to the issue.

**Comment by eanile** [comment]
Since this issue has been inactive for some time, may I work on it?

**Comment by UTkzhang** [comment]
@erohmensing @tmbo can I take a look at this issue since it’s probably not actively worked on?

**Comment by erohmensing** [comment]
Totally @UTkzhang. You're right, I haven't seen any PRs around it so should be safe to take up!

**Comment by TyDunn** [comment]
@shadow-blade-X Are you still working on this?

**Comment by PedroLucasCM** [comment]
Hi, is this issue still worth resolving?
