### ISSUE TITLE
Rasa X removes blank lines from domain.yaml and replaces with 2 newline characters, preventing multiple speech bubbles

### ISSUE THREAD

**Issue by tangochris** [RasaHQ/rasa#4496]
**Rasa version**: 1.2.8

**Rasa X version**: 0.20.2

**Target channel**: Facebook Messenger

**Issue**: Rasa X strips blank lines from domain.yaml on load and replaces them with 2 newlines. This prevents us from specifying multiple messages / multiple speech bubbles in a template. 

_(Aside: The workaround is to specify multiple utterances in response to an intent, but this is not satisfactory because we are ultimately going to use an nlg server. A single utterance corresponds to a single record in the nlg CMS, which may respond with 1 or more paragraphs. As we build out the model, we are working within Rasa X, and we don't want to rewrite all the stories once we fully connect the nlg server.)_

Domain.yaml before loading to Rasa X:
```
- text: >-
    1. Most contracts don’t have to be in writing


    A contract for services doesn’t always need to be in writing. In most cases,
    it can be an oral agreement. When you hire a babysitter (for example), you’re
    making a contract for services. Anytime you buy and receive a service, you’re
    making a contract.


    Your rights and obligations depend on the terms of the contract you make,
    and on what the law says.
  buttons:
  - title: Next
    payload: Next
```

Domain.yaml after loading to Rasa X:
```
- text: "1. Most contracts don’t have to be in writing\n\nA contract for services\
      \ doesn’t always need to be in writing. In most cases, it can be an oral agreement.\
      \ When you hire a babysitter (for example), you’re making a contract for services.\
      \ Anytime you buy and receive a service, you’re making a contract.\n\nYour rights\
      \ and obligations depend on the terms of the contract you make, and on what\
      \ the law says."
  buttons:
  - title: Next
    payload: Next
```

We tried both a folded text block `- text: >` and a wrapped text block `- text: |` and the results were the same. The three implicit newlines are converted to 2 newline characters `\n\n` and the content is delivered as a single message.

Significantly, if we edit the message from the Rasa X Responses UI and insert 2 blank lines (i.e. 3 implicit newlines) by hitting the Enter key, then save, the message is properly delivered as a series of speech bubbles.

**Comment by sara-tagger** [comment]
Thanks for the issue, @akelad will get back to you about it soon!

###### You may find help in the [docs](https://rasa.com/docs/) and the [forum,](https://forum.rasa.com/) too 🤗

**Comment by akelad** [comment]
hm, that sounds like a bug indeed - @federicotdn any ideas what's going on there?
