### ISSUE TITLE
I'm getting too many warnigs but my project is getting started 

### ISSUE THREAD

**Issue by ajinkyah** [RasaHQ/rasa#4498]
![111](https://user-images.githubusercontent.com/32433638/65299254-651fd480-db8c-11e9-9b39-e95489f7f7e5.png)
![222](https://user-images.githubusercontent.com/32433638/65299258-694bf200-db8c-11e9-8b3d-2b6d274514a9.png)

Just want to know is it okay to ignore this ?

**Comment by sara-tagger** [comment]
Thanks for the question, our Github issue board is for **bugs and feature requests only,** though 😕
Please ask this question in the [forum✨](https://forum.rasa.com/c/rasa)

###### If you were describing a bug, please create a [report](https://github.com/RasaHQ/rasa/issues/new?labels=bug&template=bug_report.md) and fill out the template
