### ISSUE TITLE
How to use URDU (Non supported) language with rasa?

### ISSUE THREAD

**Issue by Talhamian** [RasaHQ/rasa#4505]
Urdu is not officially supported language by Rasa stack and I cannot find any documentation that present usage of unsupported languages.

**Comment by sara-tagger** [comment]
Thanks for the question, our Github issue board is for **bugs and feature requests only,** though 😕
Please ask this question in the [forum✨](https://forum.rasa.com/c/rasa)

###### If you were describing a bug, please create a [report](https://github.com/RasaHQ/rasa/issues/new?labels=bug&template=bug_report.md) and fill out the template
