### ISSUE TITLE
Integration of Rasa with Couchbase

### ISSUE THREAD

**Issue by mbzebra** [RasaHQ/rasa#4508]
**Description of Problem**:

Couchbase is widely getting popular as an enterprise No-SQL solution. It would be great to provide out of the box integration for users who would like to leverage Couchbase for Rasa to store users conversation history.

**Overview of the Solution**:

- Need to introduce a new Tracker Store named CouchTrackerStore. 
- Need to implement the CouchTrackerStore
- Add test cases to test the CouchTrackerStore
- Users would be able to access the new CouchTrackerStore from the configuration in endpoints.yml

**Examples** (if relevant):

Below code is a reference from enpdoints.yml of the new implementations for Couch

`tracker_store:
    type: couch
    url: http://localhost:8091
    db: bucket
    username: user
    password: pass`

**Blockers** (if relevant):

None known at this time. 

**Definition of Done**:

- [ ] Code a new entry for CouchTrackerStore in TrackerStore
- [ ] Code the CouchTrackerStore implementation
- [ ] Tests are added
- [ ] Feature described the docs
- [ ] Feature mentioned in the changlog

**Comment by sara-tagger** [comment]
Thanks for submitting this feature request 🚀@TyDunn will get back to you about it soon!✨
###### Caw! 🐧

**Comment by wochinge** [comment]
@mbzebra 
Thanks for for your feature request! It sounds like a great idea and a great addition to rasa. However, I suggest to ship this as an additional library (not including it in rasa by default ) because
keeping a small core makes it easier to maintain `rasa` and lets us iterate faster. If you wanna do the change yourself, this could also be great chance for you to create your own opensource project. I'd be happy to support you on the way (tag me in an issue there or send me a message on linkedin)

**Comment by mbzebra** [comment]
Thank You @wochinge I have forked the project and in the process of creating a PR for this change. Love to collaborate to understand the process of shipping additional library.

**Comment by wochinge** [comment]
@mbzebra You don't need to fork the project for that. All you should need is 
- a new module for the `CouchTrackerStore`
- a setup.py with `rasa` as dependency (and potential rasa 
- some short readme on how to put your tracker store in the `endpoints.yml` 
- publish your project on Pypi
(https://rasa.com/docs/rasa/api/tracker-stores/#custom-tracker-store)

**Comment by mbzebra** [comment]
Thank You @wochinge , will follow the suggested steps.
