### ISSUE TITLE
Add a new Travis job that tests Rasa commands with just the bare-bones requirements

### ISSUE THREAD

**Issue by msamogh** [RasaHQ/rasa#4509]
The current Travis jobs are run after installing all the packages in `requirements_full.txt`, but it needs to be ensured that no commands fail even if the extra spaCy and MITIE dependencies are not installed.

One way of going about it could be (as @federicotdn suggested):
- Create a virtual environment
- Install only `requirements.txt` in it
- Test out various Rasa commands in it

**Comment by wochinge** [comment]
@msamogh Which commands should be covered? I assume `rasa init`, but besides?

**Comment by msamogh** [comment]
Why not all of them - `{init,run,shell,train,interactive,test,visualize,data,x}`?

**Comment by wochinge** [comment]
depending on the config / trained model the additional dependencies are required (which applies to `run`, `shell`, `train`, `interactive`, `test`). I'm not sure about `visualize` and `x`. `data` definitely could also be tested

**Comment by msamogh** [comment]
> depending on the config / trained model the additional dependencies are required
So we could run these on the default config that requires no additional dependencies.

**Comment by wochinge** [comment]
@tmbo Do you think that's worth doing? I am in favor of closing this.

**Comment by tmbo** [comment]
I am with you on this :+1: I think this should be covered in unit tests
