### ISSUE TITLE
update jsonschema dependency

### ISSUE THREAD

**Issue by wochinge** [RasaHQ/rasa#4512]
- https://forum.rasa.com/t/rasa-core-and-rasa-nlu-has-requirement-of-jsonschema-2-6-but-jupyterlab-server-has-requirement-of-jsonschema-3-0-1/15905
- optional: also check other dependencies if they are outdated / can be updated

maybe worth doing https://github.com/RasaHQ/roadmap/issues/695 before doing this one

**Comment by eric-bonfadini** [comment]
I had a look at the requirements + requirements_dev in current master, and installing version 3.0.2 should be fine:
```bash
pipdeptree -r -p jsonschema
jsonschema==3.0.2
  - aws-sam-translator==1.15.1 [requires: jsonschema~=3.0]
    - cfn-lint==0.24.6 [requires: aws-sam-translator>=1.15.1]
      - moto==1.3.8 [requires: cfn-lint]
  - cfn-lint==0.24.6 [requires: jsonschema~=3.0]
    - moto==1.3.8 [requires: cfn-lint]
  - nbformat==4.4.0 [requires: jsonschema>=2.4,!=2.5.0]
    - nbconvert==5.6.1 [requires: nbformat>=4.4]
      - nbsphinx==0.3.2 [requires: nbconvert]
    - nbsphinx==0.3.2 [requires: nbformat]
  - spacy==2.1.4 [requires: jsonschema>=2.6.0,<3.1.0]
```
It looks like it's the only conflicting the requirement, as far as I can see.

Compatibility scores from dependabot (e.g [this for 3.0.1](https://dependabot.com/compatibility-score/?dependency-name=jsonschema&package-manager=pip&previous-version=2.6.0&new-version=3.0.1) and [this for 3.0.0](https://dependabot.com/compatibility-score/?dependency-name=jsonschema&package-manager=pip&previous-version=2.6.0&new-version=3.0.0)) looks fine too (I checked KO PRs).

**Comment by wochinge** [comment]
Thanks for checking that! Would you be willing to submit a PR for the required changes? (Means changing that in `requirements.txt` + `setup.py`?

**Comment by eric-bonfadini** [comment]
Here you go!

I don't have access to the URL mentioned in the original ticket (RasaHQ/roadmap#695), therefore if this PR won't close the issue and some work is still missing, please modify the PR's description accordingly.
