### ISSUE TITLE
Rasa X is not updating stories.md after story is removed in UI

### ISSUE THREAD

**Issue by neumann-d** [RasaHQ/rasa#4516]
**Rasa version**: 1.2.8

**Rasa X version**:  0.20.2

**Operating system** (windows, osx, ...): Linux/Docker

**Issue**: 
When editing stories in Rasa X, it also updates the `stories.md` file after clicking the "Save" button. But when removing a story via "Trash" icon button, the `stories.md` file is not updated.

**Comment by sara-tagger** [comment]
Thanks for raising this issue, @Saladdin will get back to you about it soon✨

###### Please also check out the [docs](https://rasa.com/docs/) and the [forum](https://forum.rasa.com/) in case your issue was raised there too 🤗
