### ISSUE TITLE
Rasa X Model upload from file via button

### ISSUE THREAD

**Issue by neumann-d** [RasaHQ/rasa#4517]
**Description of Problem**:
For uploading NLU,Stories and Domain Rasa X allows direct file upload when clicking on respective upload button. But for model it only shows a terminal command to upload the model via api.

**Overview of the Solution**:
Add direct file upload in UI for models too, to allow an easier workflow. 

**Examples**:
For example when different users work either with Rasa X or Rasa CLI on the same chatbot, then it would be possible for Rasa X users to load the latest model into Rasa X without using the command line.

**Blockers**:
Users who have no access to the command line can currently not load an external updated model file into Rasa X.

**Comment by sara-tagger** [comment]
Thanks for submitting this feature request 🚀@gausie will get back to you about it soon!✨

**Comment by wochinge** [comment]
Hi @neumann-d ,

sorry for the delay 🙏 Thanks for this great idea and suggestion! 🎉
I'll talk to the team to make this happen and will keep you updated 👍

**Comment by KStephenyang** [comment]
> Hi @neumann-d ,
> 
> sorry for the delay 🙏 Thanks for this great idea and suggestion! 🎉
> I'll talk to the team to make this happen and will keep you updated 👍

Hi，have this feature in development? Which version will release this feature?
Thank you!

**Comment by wochinge** [comment]
Unfortunately this is not yet in development @KStephenyang . So you have to go with the `curl` command for now.

**Comment by abhilasharoy** [comment]
@Saladdin This is what we have currently decided on:

<img width="318" alt="Screen Shot 2020-03-30 at 9 29 02 AM" src="https://user-images.githubusercontent.com/44964694/77886318-f0c79b80-7268-11ea-9249-4456c0822482.png">

**Comment by Saladdin** [comment]
Closing because the feature will be released as part of Rasa X `0.28` 👍

**Comment by kjonnalagadda** [comment]
Hi, @neumann-d , have we published this enhancement or it is in WIP.
We are working on RASA using web widget via BOTFRONT and this feature for uploading files / uploading multiple files wile enhance the UX for the processes being delivered by the bot.

Any idea on this ? it will be helpful
