### ISSUE TITLE
Upgrade Sanic dependency

### ISSUE THREAD

**Issue by wibimaster** [RasaHQ/rasa#4523]
**Description of Problem**:
Sanic dependency is lock to 19.3.1, which use websockets <7
Sanic is now at 19.6.3 and supports websockets <8 (not the last, but at least more recent)

**Overview of the Solution**:
Could you update setup.py with new minor version of Sanic ?

**Comment by sara-tagger** [comment]
Thanks for submitting this feature request 🚀@federicotdn will get back to you about it soon!✨

**Comment by erohmensing** [comment]
Hi @wibimaster, I'm sorry that we never answered your enhancement request. We hope not to miss any of these in the future! I'm closing this issue as the sanic version was upgraded to 19.6.3 last month.
