### ISSUE TITLE
Make Rasa X model pull interval configurable in local mode

### ISSUE THREAD

**Issue by ricwo** [RasaHQ/rasa#4524]
The model pull interval should be configurable. We overwrite `endpoints.yml` in local mode, meaning the `models` section in that file supporting `wait_time_between_pulls` is not respected.

**Comment by btotharye** [comment]
I was going to start looking at this, any idea where in the code this all starts so I have a decent jumping off point?  If not I'll start looking for it just thought I'd ask first.

**Comment by btotharye** [comment]
Starting to work on this, I figured out where the code was.

**Comment by btotharye** [comment]
has been merged, closing
