### ISSUE TITLE
How to let bot start the conversation

### ISSUE THREAD

**Issue by Asma-droid** [RasaHQ/rasa#4525]
Hello,

i use  slack as a channel and i'd like to know if there is a way to let bot send the first message?

**Comment by sara-tagger** [comment]
Thanks for the question, our Github issue board is for **bugs and feature requests only,** though 😕
Please ask this question in the [forum✨](https://forum.rasa.com/c/rasa)

###### If you were describing a bug, please create a [report](https://github.com/RasaHQ/rasa/issues/new?labels=bug&template=bug_report.md) and fill out the template
