### ISSUE TITLE
Reduce Channel Dependencies

### ISSUE THREAD

**Issue by akshay2000** [RasaHQ/rasa#4526]
**Description of Problem**: Please refer to [this](https://forum.rasa.com/t/using-rasa-without-transitive-dependencies/15996) forum thread. Currently, Rasa has a bunch of dependencies for various chat integrations. This is the list from `setup.py` from `master` branch.

 slackclient~=1.3
 python-telegram-bot~=11.0
 twilio~=6.0
 webexteamssdk~=1.1
 mattermostwrapper~=2.0
 rocketchat_API~=0.6.0

These packages, in turn, pull in a lot of other packages. All these dependencies are unused for the bots that use their own custom channels. This called all sorts of issues, like bigger deployment packages, dependency version conflicts with other libraries, etc.

**Overview of the Solution**: We could remove the aforementioned dependencies from `setup.py` and do a dynamic load at runtime. This would be similar to what Rasa does for loading pipeline components. For example, Rasa logs an error message that Spacy needs to be installed if the user tries to attempt a Spacy based pipeline.

**Definition of Done**:

*   [ ] Dependencies are removed
*   [ ] Tests are added
*   [ ] Feature described the docs
*   [ ] Feature mentioned in the changlog

**Comment by sara-tagger** [comment]
Thanks for submitting this feature request 🚀@tmbo will get back to you about it soon!✨

**Comment by tmbo** [comment]
I like the idea of that :+1: its something I had in the back of my mind for a while, but we just didn't get to it yet.

**Comment by akshay2000** [comment]
@tmbo Does that mean I can start working on this now?

**Comment by tmbo** [comment]
Yes, that would be perfect :rocket:

I'd suggest we should
- remove the dependencies from install requires in setup.py
- move the dependencies to extra sections in setup.py (this depends a bit on the use case, we could either have one extra per channel or one extra for all the channels - up for discussion)
- add checks and errors to the channels to make sure the needed packages are available

**Comment by akshay2000** [comment]
@tmbo I have started work on this. Here's a simple way I can think of to address this:

```
try:
    from telegram import (
        Bot,
        InlineKeyboardButton,
        Update,
        InlineKeyboardMarkup,
        KeyboardButton,
        ReplyKeyboardMarkup,
    )
except ImportError as e:
    logger.error(
        "Please install package 'python-telegram-bot' to use Telegram channel."
    )
    raise e
```

Is this alright? Or do we need some sort of "channel loader" that validates dependencies before loading the modules? I personally think that's an overkill.

**Comment by staticdev** [comment]
I think it is a good idea for not having a bloated package. One common workaround is removing from requirements and putting it as optional in the setup.py. Eg: https://github.com/slackapi/python-slackclient/pull/440/files

**Comment by souvikg10** [comment]
Anyone wokring on this?? Can I move the channel dependencies to extra installs? as suggested by @tmbo

**Comment by akshay2000** [comment]
@souvikg10 I'm sorry, I was working on it and then life happened. Feel free to take it over!

**Comment by tmbo** [comment]
I am not sure we should do this. It complicates installation for a minor benefit of fewer libraries during installation. I think all of these libraries are pretty small (just wrappers around HTTP API) - but good to double check. For the project it doesn't make a difference, as they will still stay dependencies we need to maintain, so all in all I don't think it is worth to make the installation harder.

**Comment by akshay2000** [comment]
@tmbo While I generally agree, there were specific reasons that led me to do this.

One of the major reasons is transitive dependencies. We have an internal platform SDKs for various stuff. Their dependency versions keep clashing with Rasa and friends' dependency versions. Python does not have a good way of keeping multiple package versions at the same time. 

Also, I think (and I may be misremembering) some of the packages listed above have non-pure-Python dependencies - making them platform dependent. That causes different kinda of issues with the versions of underlying C libraries.

While reducing overall dependencies will not solve the problems above, it does mitigate it somewhat. From deployment perspective, we always want to keep the containers as lean as possible. Extra dependencies is extra headache to monitor security vulnerabilities, etc.

With that said, if there's a strong feeling towards *not* doing it, I completely understand.

**Comment by tmbo** [comment]
I'd be happy to e.g. remove certain libraries and call HTTP APIs directly or replace them with alternatives that have a smaller footprint (esp. if they depend on C code, but not sure which actually do).

To sum it up: I think removing / replacing dependencies, to avoid these conflicts/system dependencies is a great idea - optional dependencies will only solve these issues for some part of the people but not the ones that need these connectors.

**Comment by souvikg10** [comment]
@tmbo,
I think some of these channel connector libraries(telegram client for example) are not particularly written with robustness or security in mind. We have a number of flagged libraries in our internal system.I will request our security team to tell me what they have found as vulnerabilities but not much can be done about them except reporting to the package's maintainers. As python is going more and more mainstream in large enterprises, checks are enabled and some glaring security risks are coming up in many packages.I reported one for Flask-AppBuilder few months ago too.  

From Rasa as a platform perspective, I believe connectors should be pick and choose for the projects who want them. Kind of like airflow has done too. i don't think every project is released in multiple channels. I also understand that for packages that are very much at the heart of the platform needs to monitored and transitive dependencies are carefully managed. i don't think making them optional is a good idea. 

For me, connectors, databases client, event bridges(which are not core, kafka for example) are detachable dependencies from the core package. Let me know, i started working on this last week :D
