### ISSUE TITLE
Failed building wheel for httptools - pyconfig.h(222): fatal error C1083: Cannot open include file: 'basetsd.h': No such file or directory     error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio 14.0\\VC\\BIN\\x86_amd64\\cl.exe' failed with exit status 2

### ISSUE THREAD

**Issue by SanthoshKumarKatta** [RasaHQ/rasa#4531]
Hi, Tried most of the solutions and failed to get ride of this issue. Please find the following console logs help me on this.

++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++

Building wheels for collected packages: httptools
  Running setup.py bdist_wheel for httptools ... error
  Complete output from command c:\users\katta\appdata\local\programs\python\python36\python.exe -u -c "import setuptools, tokenize;__file__='C:\\Users\\Katta\\AppData\\Local\\Temp\\pip-install-5v9dler4\\httptools\\setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" bdist_wheel -d C:\Users\Katta\AppData\Local\Temp\pip-wheel-xn5f4tpk --python-tag cp36:
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build\lib.win-amd64-3.6
  creating build\lib.win-amd64-3.6\httptools
  copying httptools\__init__.py -> build\lib.win-amd64-3.6\httptools
  creating build\lib.win-amd64-3.6\httptools\parser
  copying httptools\parser\errors.py -> build\lib.win-amd64-3.6\httptools\parser
  copying httptools\parser\__init__.py -> build\lib.win-amd64-3.6\httptools\parser
  running egg_info
  writing httptools.egg-info\PKG-INFO
  writing dependency_links to httptools.egg-info\dependency_links.txt
  writing top-level names to httptools.egg-info\top_level.txt
  reading manifest file 'httptools.egg-info\SOURCES.txt'
  reading manifest template 'MANIFEST.in'
  writing manifest file 'httptools.egg-info\SOURCES.txt'
  copying httptools\parser\parser.c -> build\lib.win-amd64-3.6\httptools\parser
  running build_ext
  building 'httptools.parser.parser' extension
  creating build\temp.win-amd64-3.6
  creating build\temp.win-amd64-3.6\Release
  creating build\temp.win-amd64-3.6\Release\httptools
  creating build\temp.win-amd64-3.6\Release\httptools\parser
  creating build\temp.win-amd64-3.6\Release\vendor
  creating build\temp.win-amd64-3.6\Release\vendor\http-parser
  C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\BIN\x86_amd64\cl.exe /c /nologo /Ox /W3 /GL /DNDEBUG /MD -Ic:\users\katta\appdata\local\programs\python\python36\include -Ic:\users\katta\appdata\local\programs\python\python36\include "-IC:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\INCLUDE" "-IC:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\ATLMFC\INCLUDE" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.10240.0\ucrt" "-IC:\Program Files (x86)\Windows Kits\NETFXSDK\4.6.1\include\um" /Tchttptools/parser/parser.c /Fobuild\temp.win-amd64-3.6\Release\httptools/parser/parser.obj -O2
  parser.c
  c:\users\katta\appdata\local\programs\python\python36\include\pyconfig.h(222): fatal error C1083: Cannot open include file: 'basetsd.h': No such file or directory
  error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio 14.0\\VC\\BIN\\x86_amd64\\cl.exe' failed with exit status 2

  ----------------------------------------
  Failed building wheel for httptools
  Running setup.py clean for httptools
Failed to build httptools
Installing collected packages: httptools, sanic, sanic-plugins-framework, sanic-cors, sanic-jwt, flask-cors, ConfigArgParse, rasa-sdk, websocket-client, slackclient, docutils, jmespath, botocore, s3transfer, boto3, colorhash, rasa
  Running setup.py install for httptools ... error
    Complete output from command c:\users\katta\appdata\local\programs\python\python36\python.exe -u -c "import setuptools, tokenize;__file__='C:\\Users\\Katta\\AppData\\Local\\Temp\\pip-install-5v9dler4\\httptools\\setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record C:\Users\Katta\AppData\Local\Temp\pip-record-awls3tvv\install-record.txt --single-version-externally-managed --compile:
    running install
    running build
    running build_py
    creating build
    creating build\lib.win-amd64-3.6
    creating build\lib.win-amd64-3.6\httptools
    copying httptools\__init__.py -> build\lib.win-amd64-3.6\httptools
    creating build\lib.win-amd64-3.6\httptools\parser
    copying httptools\parser\errors.py -> build\lib.win-amd64-3.6\httptools\parser
    copying httptools\parser\__init__.py -> build\lib.win-amd64-3.6\httptools\parser
    running egg_info
    writing httptools.egg-info\PKG-INFO
    writing dependency_links to httptools.egg-info\dependency_links.txt
    writing top-level names to httptools.egg-info\top_level.txt
    reading manifest file 'httptools.egg-info\SOURCES.txt'
    reading manifest template 'MANIFEST.in'
    writing manifest file 'httptools.egg-info\SOURCES.txt'
    copying httptools\parser\parser.c -> build\lib.win-amd64-3.6\httptools\parser
    running build_ext
    building 'httptools.parser.parser' extension
    creating build\temp.win-amd64-3.6
    creating build\temp.win-amd64-3.6\Release
    creating build\temp.win-amd64-3.6\Release\httptools
    creating build\temp.win-amd64-3.6\Release\httptools\parser
    creating build\temp.win-amd64-3.6\Release\vendor
    creating build\temp.win-amd64-3.6\Release\vendor\http-parser
    C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\BIN\x86_amd64\cl.exe /c /nologo /Ox /W3 /GL /DNDEBUG /MD -Ic:\users\katta\appdata\local\programs\python\python36\include -Ic:\users\katta\appdata\local\programs\python\python36\include "-IC:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\INCLUDE" "-IC:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\ATLMFC\INCLUDE" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.10240.0\ucrt" "-IC:\Program Files (x86)\Windows Kits\NETFXSDK\4.6.1\include\um" /Tchttptools/parser/parser.c /Fobuild\temp.win-amd64-3.6\Release\httptools/parser/parser.obj -O2
    parser.c
    c:\users\katta\appdata\local\programs\python\python36\include\pyconfig.h(222): fatal error C1083: Cannot open include file: 'basetsd.h': No such file or directory
    error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio 14.0\\VC\\BIN\\x86_amd64\\cl.exe' failed with exit status 2

    ----------------------------------------
Command "c:\users\katta\appdata\local\programs\python\python36\python.exe -u -c "import setuptools, tokenize;__file__='C:\\Users\\Katta\\AppData\\Local\\Temp\\pip-install-5v9dler4\\httptools\\setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record C:\Users\Katta\AppData\Local\Temp\pip-record-awls3tvv\install-record.txt --single-version-externally-managed --compile" failed with error code 1 in C:\Users\Katta\AppData\Local\Temp\pip-install-5v9dler4\httptools\

**Comment by sara-tagger** [comment]
Thanks for the question, our Github issue board is for **bugs and feature requests only,** though 😕
Please ask this question in the [forum✨](https://forum.rasa.com/c/rasa)

###### If you were describing a bug, please create a [report](https://github.com/RasaHQ/rasa/issues/new?labels=bug&template=bug_report.md) and fill out the template
