### ISSUE TITLE
Python 3.8 support

### ISSUE THREAD

**Issue by ricwo** [RasaHQ/rasa#4536]
**Description of Problem**: Python 3.8 is expected to be released on October 21, 2019. We should ensure compatibility by then.

**Definition of Done**: Passing `python: 3.8-dev` test stage in `.travis.yml`

**Comment by wochinge** [comment]
currently blocked by tensorflow

**Comment by ricwo** [comment]
No longer blocked, tf 2.2.0 is available

**Comment by arunabh09** [comment]
Hi, how soon can we expect a RASA compatible version with Python 3.8.2?

**Comment by ricwo** [comment]
this is unfortunately still blocked by https://github.com/tensorflow/text

**Comment by sharpchris** [comment]
The PyPI page lists Python 3.8 as supported, so that should probably be updated if Rasa cannot be run in that environment: https://pypi.org/project/rasa/

**Comment by n2718281** [comment]
Refs:
https://github.com/tensorflow/text/issues/284
