### ISSUE TITLE
Custom pipeline for spell correction

### ISSUE THREAD

**Issue by nicolasfarina** [RasaHQ/rasa#4539]
Hi i need create a Custom pipeline for spell correction, is there any implemented for example fuzzywuzzy python library or is necessary write a new Custom pipeline. I listen opinions.

**Comment by sara-tagger** [comment]
Thanks for the issue, @Ghostvv will get back to you about it soon!

###### You may find help in the [docs](https://rasa.com/docs/) and the [forum,](https://forum.rasa.com/) too 🤗

**Comment by Ghostvv** [comment]
Currently, we don't have spell corrector component in rasa. For now, you need to create your custom component.

**Comment by msamogh** [comment]
@nicolasfarina 

Fuzzywuzzy could work. You can also try out https://pypi.org/project/autocorrect/. Nevertheless, please ask these kinds of questions in our [forum](https://forum.rasa.com) going forward.
