### ISSUE TITLE
Memory explosion from 1.2 to 1.3 

### ISSUE THREAD

**Issue by boristhescot** [RasaHQ/rasa#4540]
**Rasa version**: 1.2.4 and 1.3.3

**Rasa X version** (if used & relevant): Not used

**Python version**: 3.6

**Operating system** (windows, osx, ...): Windows and Linux

**Issue**:
@wochinge We spoke of this at the developer summit. 

Here is the pipeline:

language: en
pipeline:
  - name: "WhitespaceTokenizer"
  - name: "RegexFeaturizer"
  - name: "CRFEntityExtractor"
  - name: "CountVectorsFeaturizer"
    max_features: 2000
  - name: "EmbeddingIntentClassifier"

policies:
  - name: MemoizationPolicy
  - name: KerasPolicy
  - name: MappingPolicy

On my desktop windows machine (4 cores, 16 g memory) moving from 1.2.4 to 1.3.3 my training results are better, but it uses almost all of my memory and I can only just barely complete training if I shut down absolutely everything. On my Linux training box with 16 cores and 64 g memory and a couple of gpus, I get a memory error and cannot complete training

I am training NLU only on just over 400 intents and 84860 lines in my nlu.md

**Comment by sara-tagger** [comment]
Thanks for raising this issue, @msamogh will get back to you about it soon✨

###### Please also check out the [docs](https://rasa.com/docs/) and the [forum](https://forum.rasa.com/) in case your issue was raised there too 🤗

**Comment by Ghostvv** [comment]
This is because we added `balanced` batching strategy: https://rasa.com/docs/rasa/nlu/choosing-a-pipeline/#class-imbalance

Please follow the docs to see how it can be turned off

**Comment by wochinge** [comment]
Is there anything we can do to make the `balanced` strategy more efficient @Ghostvv ?

**Comment by Ghostvv** [comment]
as usual, it's a trade off between computational efficiency (training time) and memory efficiency. Right now, it is optimized for lower training times

**Comment by rgstephens** [comment]
I suspect the issue I just opened, #4616, is also related to changes in the `EmbeddingIntentClassifier` between 1.2 & 1.3. I cannot train larger data sets under 1.3.

I have tried turning off the `balanced` strategy and it still fails. Are there other changes in the hyper parameters passed to `EmbeddingIntentClassifier` between 1.2 & 1.3?

**Comment by Ghostvv** [comment]
we also added char level count vectorizer, that could create rather large feature space, causing memory issues

**Comment by wochinge** [comment]
@rgstephens Did you try changing the settings for the count vectorizer to count words instead of chars? Does this help?

**Comment by rgstephens** [comment]
Yes, I should have posted that info.  Here are some stats on 1.3.9 with 278 unique intents. The config files for the two train/test runs are below. **The default settings are not working well for this data set.  The training time, memory requirements and test results are all significantly worse.**

| Vers   | Config        | Time  | Mem  | errors | Model Size                            |
| ------ | ------------- | ----- | ---- | ------ | ------------------------------- |
| 1.3.9  | default       | **19:40** | **4.6G** | **32/549** | 34Mb |
| 1.3.9  | word | 10:53 | 1.8G | 19/549 | 8Mb  |

default config:

```yml
pipeline: supervised_embeddings
language: en
```

word vec

```yml
language: "en"
pipeline:
 - name: "WhitespaceTokenizer"
 - name: "RegexFeaturizer"
 - name: "CRFEntityExtractor"
 - name: "EntitySynonymMapper"
 - name: "CountVectorsFeaturizer"
 - name: "EmbeddingIntentClassifier"
   num_neg: 277
```

**Comment by wochinge** [comment]
@Ghostvv Any input on Greg's response?

**Comment by rgstephens** [comment]
I think we can close this.  In the future, we should document changes that can cause significant changes in resource requirements for the pre-conifgured pipelines.
