### ISSUE TITLE
Setting up a Reverse Proxy using Nginx with Webchat Widget

### ISSUE THREAD

**Issue by firewater334** [RasaHQ/rasa#4541]
Hi,

I am attempting to set up a reverse proxy using Nginx for my Kubernetes Deployment.  However, regardless of my debugging attempts, I am still stuck on the issue of sanic.exceptions.NotFound: Requested URL /nova/socket.io/ not found if I set up a reverse proxy using /nova in my nginx.conf.  My question is, is it even possible to set up a reverse proxy with the webchat widget and rasa?  I have tried out numerous permutations of playing around with the path, and I am unable to get my deployment to work successfully.  Any insights would be great!  I have attached my index.html file below.  
![Screen Shot 2019-09-30 at 1 22 52 PM](https://user-images.githubusercontent.com/47159809/65905081-797e8100-e385-11e9-9e88-cd2c39e1a5ae.png)
@znat @wochinge

**Comment by znat** [comment]
Yes, we do it all the time.
I guess you're using nginx-ingress, can you share an ingress?

**Comment by dasxx179** [comment]
> Yes, we do it all the time.
> I guess you're using nginx-ingress, can you share an ingress?

@znat 

Thanks for the reply.  I have attached my ingress/egress policies, as well as my conf for my chatbot that is used by my nginx and conf for nginx.  
**Novabot Conf (used by Nginx)**
![image](https://user-images.githubusercontent.com/54422044/65919657-9ecdb800-e3a2-11e9-9743-f00ae82c46c2.png)


**Nginx Conf**
![image](https://user-images.githubusercontent.com/54422044/65919687-b442e200-e3a2-11e9-99f3-9411878f368a.png)

**Services for K8s**
![image](https://user-images.githubusercontent.com/54422044/65919734-d63c6480-e3a2-11e9-8a89-d7e0a3b08f95.png)

**Policies for K8s**
![image](https://user-images.githubusercontent.com/54422044/65919761-e5231700-e3a2-11e9-9441-68feeaa980c2.png)

**Comment by sara-tagger** [comment]
Thanks for the question, our Github issue board is for **bugs and feature requests only,** though 😕
Please ask this question in the [forum✨](https://forum.rasa.com/c/rasa)

###### If you were describing a bug, please create a [report](https://github.com/RasaHQ/rasa/issues/new?labels=bug&template=bug_report.md) and fill out the template
