### ISSUE TITLE
Reverse Proxy Setup Issue Path not Found

### ISSUE THREAD

**Issue by dasxx179** [RasaHQ/rasa#4547]
Hi,
I am attempting to set up a reverse proxy using Nginx for my Kubernetes Deployment. However, regardless of my debugging attempts, I am still stuck on the issue of 
**sanic.exceptions.NotFound: Requested URL /nova/socket.io/** if I set up a reverse proxy using /nova in my nginx.conf.  I have attached my conf for my chatbot that is used by my nginx, conf for nginx, my services file for k8s, my ingress/egress policies for k8s, my index.html file, and finally my policies for K8s.  
**Novabot Conf (used by Nginx)**
![image](https://user-images.githubusercontent.com/54422044/65919657-9ecdb800-e3a2-11e9-9743-f00ae82c46c2.png)

**Nginx Conf**
![image](https://user-images.githubusercontent.com/54422044/65919687-b442e200-e3a2-11e9-99f3-9411878f368a.png)

**Services for K8s**
![image](https://user-images.githubusercontent.com/54422044/65919734-d63c6480-e3a2-11e9-8a89-d7e0a3b08f95.png)

**Index.html file**
![image](https://user-images.githubusercontent.com/54422044/65963092-ab442600-e41f-11e9-9432-bd741980a36c.png)

**Policies for K8s**
![image](https://user-images.githubusercontent.com/54422044/65919761-e5231700-e3a2-11e9-9441-68feeaa980c2.png)

@znat

**Comment by erohmensing** [comment]
Please open questions about implementation on the forum, we will try our best to help you out there. We reserve the github for bug reports in the rasa or rasa x libraries or feature requests.
