### ISSUE TITLE
error pip3 install -r requirements-dev.txt  

### ISSUE THREAD

**Issue by chrisbangun** [RasaHQ/rasa#4548]
**Rasa version**:

**Rasa X version** (if used & relevant):

**Python version**: 3.7

**Operating system** (windows, osx, ...): osx

**Issue**: encountered some errors with dependencies compatibility issues while using pip3 in conda virtual environment. Apparently the pip3 doesn't refer to the pip in the virtualenv.

**Error (including full traceback)**:
```
ERROR: rasa-x 0.20.2 has requirement rasa~=1.2.5, but you'll have rasa 1.3.6 which is incompatible.
ERROR: rasa-x 0.20.2 has requirement sanic~=19.3.1, but you'll have sanic 19.6.3 which is incompatible.
ERROR: tensorflow-metadata 0.14.0 has requirement protobuf<4,>=3.7, but you'll have protobuf 3.6.1 which is incompatible.
Installing collected packages: wrapt, tensorflow, cloudpickle, tensorflow-probability, promise, googleapis-common-protos, tensorflow-metadata, tensorflow-datasets, gin-config, pyasn1, pyasn1-modules, httplib2, rsa, oauth2client, mesh-tensorflow, pyglet, gym, cachetools, google-auth, google-auth-httplib2, uritemplate, google-api-python-client, dopamine-rl, kfac, tensorflow-gan, pypng, tensor2tensor, rasa-sdk, websockets, hyperframe, hpack, h2, h11, rfc3986, httpcore, requests-async, sanic, rasa
  Found existing installation: wrapt 1.10.11
ERROR: Cannot uninstall 'wrapt'. It is a distutils installed project and thus we cannot accurately determine which files belong to it which would lead to only a partial uninstall.
```

**Command or request that led to error**:
```
pip3 install -r requirements-dev.txt
```

**Content of configuration file (config.yml)** (if relevant):
```yml

```

**Content of domain file (domain.yml)** (if relevant):
```yml

```

The above errors can be fixed by using pip assuming that we installed python3 in our conda virtualenv. However, I noticed that the `make prepare-tests-macos` uses pip3 which refers to the global pip3 not in the conda env, hence gave similar errors above.

Not sure if this is a bug or whether I missed something. Thanks

**Comment by sara-tagger** [comment]
Thanks for the issue, @ricwo will get back to you about it soon!

###### You may find help in the [docs](https://rasa.com/docs/) and the [forum,](https://forum.rasa.com/) too 🤗

**Comment by ricwo** [comment]
Hi @chrisbangun, this seems to be tensorflow issue. Can you please try if the following works:

```bash
pip install wrapt --upgrade --ignore-installed
pip install tensorflow==1.14.0
```

(from https://github.com/tensorflow/tensorflow/issues/30191#issuecomment-516192882)

I can see you're trying to install rasa x 0.20.2 with rasa 1.3.6 - I'd recommend you upgrade to `rasa-x==0.21.2` and `rasa==1.3.7`. I hope that helps!

**Comment by chrisbangun** [comment]
hi @ricwo , thanks for the response. As for the rasa-x, I didn't install it explicitly (manually). I just execute the `pip3 install -r requirements-dev.txt` after creating my conda environment.

I'll try the suggestion above, however, I would like to point out that if I changed it to `pip`, it works just fine.
