### ISSUE TITLE
Error in interpolate_text when value contains 0[

### ISSUE THREAD

**Issue by pbouda** [RasaHQ/rasa#4550]
**Rasa version**:

1.3.4

**Rasa X version** (if used & relevant):

**Python version**:

3.7

**Operating system** (windows, osx, ...):

Windows

**Issue**:

Rasa fails to interpolate a template when one of the values contains a `0[`. The code that triggers the error is here:

https://github.com/RasaHQ/rasa/blob/master/rasa/core/nlg/interpolator.py#L19

My response contains an a string `np0[0...n]` in one of the values (the `{result}` placeholder in the traceback below). All values are inserted correctly into the template, so the additional `template.format({})` fails and triggers the `except`. Even the error message is wrong, as Rasa complains a missing value but inserted all values happily before. So the traceback below shows a wrong error, but at least the correct line.

**Error (including full traceback)**:

```
2019-10-02 10:26:32 ERROR    rasa.core.nlg.interpolator  - Failed to fill utterance template 'Top {number_of_results} {documents} zum Thema {topic}:
{result}'. Tried to replace 'number_of_results' but could not find a value for it. There is no slot with this name nor did you pass the value explicitly when calling the template. Return template without filling the template.
Traceback (most recent call last):
  File "c:\users\z003y0rv\projects\code.siemens\ai4am-chatbot\venv\lib\site-packages\rasa\core\nlg\interpolator.py", line 25, in interpolate_text
    return template.format({})
KeyError: 'number_of_results'
```

**Comment by sara-tagger** [comment]
Thanks for raising this issue, @msamogh will get back to you about it soon✨

###### Please also check out the [docs](https://rasa.com/docs/) and the [forum](https://forum.rasa.com/) in case your issue was raised there too 🤗

**Comment by msamogh** [comment]
I ran this and didn't get any errors.
```python
>>> template = 'Top {number_of_results} {documents} zum Thema {topic}: {result}'
>>> template = re.sub(r"{([^\n{}]+?)}", r"{0[\1]}", template)
>>> template
'Top {0[number_of_results]} {0[documents]} zum Thema {0[topic]}: {0[result]}'
>>> text = template.format({'number_of_results': 2, 'documents': 'x', 'topic': 'y', 'result': 'np0[0...n]'})
>>> text
'Top 2 x zum Thema y: np0[0...n]'
>>> text.format({})
'Top 2 x zum Thema y: np0[0...n]'
```

Could you also post the values of the others slots?

**Comment by pbouda** [comment]
Oh interesting... I have to check on another computer, I have no access atm, will get back to you next week.

**Comment by erohmensing** [comment]
@pbouda were you able to get past this issue?

**Comment by pbouda** [comment]
At the moment I do not have access to the code of the project unfortunately. Before I got passed the issue by replacing all `0[` in my texts, though. I will get back to the project later this month and try to reproduce, then I can compare check all the slots and see why the error occurs exactly.

**Comment by pbouda** [comment]
@msamogh I could reproduce, and the code in `interpolator.py` triggers the `KeyError` because it calls `template.format({})` not `text.format({})` as in your example:

```
>>> template = 'Top {number_of_results} {documents} zum Thema {topic}: {result}'
>>> template.format({})
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
KeyError: 'number_of_results'
```

So as soon as there is a `0[` in the filled in template the error occurs.

**Comment by erohmensing** [comment]
Got it, would you be able to create a PR for the fix?

**Comment by pbouda** [comment]
I could do, but I am not sure what the best behaviour would be here. There will be a trade-off, as soon as there is for example double curly braces in the template *and* `0[` in some value that was replaced. As a quick fix I would just remove the full `if` block which makes the problem with double curly braces at least visible and does not throw an error with `[0` values. But that would result in non-backwards-compatible behaviour, so it's not just a fix...
