### ISSUE TITLE
Move code out of __init__.py

### ISSUE THREAD

**Issue by tabergma** [RasaHQ/rasa#4552]
Some `__init__.py` files contain quite a lot of code. We should move the code to proper files.

**Comment by icaropires** [comment]
Hi, this issue is opened to community?

**Comment by tabergma** [comment]
Yes, feel free to work on it 😃 If you need any help, please let me know.

**Comment by icaropires** [comment]
Hi @tabergma  , I'm very sorry for the delay, I ended up getting busier than I expected and that's why I couldn't finish this issue yet. And unfortunately, I will be very busy for at least another month.

No problem if you unassign this issue from me but I expect to be able to contribute again soon.
Sorry again for the delay.

**Comment by tabergma** [comment]
@icaropires No problem. Thanks for the heads up!

**Comment by pranavdurai10** [comment]
Hello @tabergma, is this issue still open for working on?

**Comment by tabergma** [comment]
@pranavdurai10 Sure. Thanks for taking this over 👍

**Comment by pranavdurai10** [comment]
@tabergma Are we talking about just the __init__.py file or the __main__.py file, too?

**Comment by tabergma** [comment]
Just about the `__init__.py` files, for example, this one [here](https://github.com/RasaHQ/rasa/blob/master/rasa/core/events/__init__.py).

**Comment by pranavdurai10** [comment]
> Just about the `__init__.py` files, for example, this one [here](https://github.com/RasaHQ/rasa/blob/master/rasa/core/events/__init__.py).

@tabergma Got it. I'm having a look at it.

**Comment by ericoBandeira** [comment]
Hi, this issue is opened to community?

**Comment by jps12** [comment]
Hi, 
Is this issue still open?
I would like to work on. :smiley:
