### ISSUE TITLE
Couldn't train rasa core with custom model_architecture in keras policy

### ISSUE THREAD

**Issue by Sarvin92** [RasaHQ/rasa#4554]
I have to use a custom keras policy for dialog management using rasa core. I have tried to implement it using a sequential model in as per documentation in keras. I have trained the model using my custom dataset externally without using rasa. But when I have tried to integrate this architecture in model_architecture method of KerasPolicy of rasa. I have attached the code below,

    from __future__ import print_function

    from keras.models import Model
    from keras.layers import Input, LSTM, Dense
    import numpy as np

    batch_size = 64  # Batch size for training.
    epochs = 100  # Number of epochs to train for.
    latent_dim = 256  # Latent dimensionality of the encoding space.
    num_samples = 10000  # Number of samples to train on.
    # Path to the data txt file on disk.
    data_path = 'fra-eng/fra.txt'

    class RestaurantPolicy(Policy):
        def model_architecture(self, input_shape, output_shape):
            input_texts = []
            target_texts = []
            flatten_input_texts = []
            flatten_target_texts = []
            input_intent_sv = set()
            target_intent_sv = set()
            with open(data_path, 'r', encoding='utf-8') as f:
                 lines = f.read().split('\n')
            for line in lines[: min(num_samples, len(lines) - 1)]:
                input_text, target_text = line.split('\t')
                # We use "tab" as the "start sequence" character
                # for the targets, and "\n" as "end sequence" character.
                target_text = '\t' + target_text + '\n'
               input_texts.append(input_text)
                target_texts.append(target_text)
                for char in input_text:
                    if char not in input_characters:
                       input_characters.add(char)
                for char in target_text:
                    if char not in target_characters:
                        target_characters.add(char)
                
            input_intent_sv = sorted(list(input_intent_sv))
            target_intent_sv = sorted(list(target_intent_sv))
            num_encoder_tokens = len(input_intent_sv)
            num_decoder_tokens = len(target_intent_sv)
            max_encoder_seq_length = max([len(txt) for txt in flatten_input_texts])
            max_decoder_seq_length = max([len(txt) for txt in flatten_target_texts])
                
            print('Number of samples:', len(input_texts))
            print('Number of unique input tokens:', num_encoder_tokens)
            print('Number of unique output tokens:', num_decoder_tokens)
            print('Max sequence length for inputs:', max_encoder_seq_length)
            print('Max sequence length for outputs:', max_decoder_seq_length)
        
            input_token_index = dict(
                [(intent_sv, i) for i, intent_sv in enumerate(input_intent_sv)])
            target_token_index = dict(
                [(intent_sv, i) for i, intent_sv in enumerate(target_intent_sv)])      
        
            encoder_input_data = np.zeros(
                (len(flatten_input_texts), max_encoder_seq_length, num_encoder_tokens),
                dtype='float32')
            decoder_input_data = np.zeros(
                (len(flatten_input_texts), max_decoder_seq_length, num_decoder_tokens),
                dtype='float32')
            decoder_target_data = np.zeros(
                (len(flatten_input_texts), max_decoder_seq_length, num_decoder_tokens),
                dtype='float32')
            
            for i, (input_text, target_text) in enumerate(zip(flatten_input_texts, flatten_target_texts)):
                for t, char in enumerate(input_text):
                    encoder_input_data[i, t, input_token_index[char]] = 1.
                encoder_input_data[i, t + 1:, input_token_index[' ']] = 1.
                for t, char in enumerate(target_text):
                    # decoder_target_data is ahead of decoder_input_data by one timestep
                    decoder_input_data[i, t, target_token_index[char]] = 1.
                    if t > 0:
                        # decoder_target_data will be ahead by one timestep
                        # and will not include the start character.
                        decoder_target_data[i, t - 1, target_token_index[char]] = 1.
                decoder_input_data[i, t + 1:, target_token_index[' ']] = 1.
                decoder_target_data[i, t:, target_token_index[' ']] = 1.
        
            # Define an input sequence and process it.
            encoder_inputs = Input(shape=(None, num_encoder_tokens))
            encoder =  LSTM(latent_dim, return_state=True)
            encoder_outputs, state_h, state_c = encoder(encoder_inputs)
            # We discard `encoder_outputs` and only keep the states.
            encoder_states = [state_h, state_c]
                
            # Set up the decoder, using `encoder_states` as initial state.
            decoder_inputs = Input(shape=(None, num_decoder_tokens))
            # We set up our decoder to return full output sequences,
            # and to return internal states as well. We don't use the
            # return states in the training model, but we will use them in inference.
            decoder = LSTM(latent_dim, return_sequences=True, return_state=True)
            decoder_outputs, _, _ = decoder(decoder_inputs,
                                                     initial_state=encoder_states)
            decoder_dense = Dense(num_decoder_tokens, activation='softmax')
            decoder_outputs = decoder_dense(decoder_outputs)
                
            # Define the model that will turn
            # `encoder_input_data` & `decoder_input_data` into `decoder_target_data`
            model = Model([encoder_inputs, decoder_inputs], decoder_outputs)
                
            # Run training
            model.compile(optimizer='rmsprop', loss='categorical_crossentropy',
                        metrics=['accuracy'])
            logger.debug(model.summary())
            return model

I get an error, which is as below:

    ValueError: Error when checking model input: the list of Numpy arrays that you are passing to         your model is not the size the model expected. Expected to see 2 array(s), but instead got the following list of 1 arrays
I have searched regarding this issue, but there were no answers for it (https://datascience.stackexchange.com/questions/39648/valueerror-numpy-arrays-that-you-are-passing-to-your-model-is-not-the-size-the)

Hence, I tried to customize the train method in the KerasPolicy as shown below,

    def train(self,
        training_trackers: List[DialogueStateTracker],
        domain: Domain,
        **kwargs: Any
    ) -> None:

        # set numpy random seed
        np.random.seed(self.random_seed)

        training_data = self.featurize_for_training(training_trackers, domain, **kwargs)
        # noinspection PyPep8Naming
        shuffled_X, shuffled_y = training_data.shuffled_X_y()
        self.graph = tf.Graph()

        with self.graph.as_default():
            # set random seed in tf
            tf.set_random_seed(self.random_seed)
            self.session = tf.Session(config=self._tf_config)

        with self.session.as_default():
            if self.model is None:
                model, encoder_input_data, decoder_input_data, decoder_target_data = self.model_architecture(
                    shuffled_X.shape[1:], shuffled_y.shape[1:]
                )
            logger.info(
                    "Fitting model with {} total samples and a "
                    "validation split of {}"
                    "".format(training_data.num_examples(), self.validation_split)
                )

            # filter out kwargs that cannot be passed to fit
            #self._train_params = self._get_valid_params(
                #self.model.fit, **self._train_params
            #)

            self.model.fit(
                np.array([encoder_input_data, decoder_input_data]), 
                np.array(decoder_target_data),
                epochs=self.epochs,
                batch_size=self.batch_size,
                shuffle=False,
                verbose=obtain_verbosity(),
                #**self._train_params
            )
                # the default parameter for epochs in keras fit is 1
            self.current_epoch = self.defaults.get("epochs", 1)
            logger.info("Done fitting keras policy model")

This throws an error as below,

    custom_policy  - Fitting model with 21562 total samples and a validation split of 0.2
Traceback (most recent call last):
  File "C:\Apps\sa\Scripts\rasa-script.py", line 11, in <module>
    load_entry_point('rasa', 'console_scripts', 'rasa')()
  File "C:\Users\SA\AppData\Roaming\Python\Python37\site-packages\rasa\__main__.py", line 76, in main
    cmdline_arguments.func(cmdline_arguments)
  File "C:\Users\SA\AppData\Roaming\Python\Python37\site-packages\rasa\cli\train.py", line 77, in train
    kwargs=extract_additional_arguments(args),
  File "C:\Users\SA\AppData\Roaming\Python\Python37\site-packages\rasa\train.py", line 40, in train
    kwargs=kwargs,
  File "c:\apps\sa\lib\asyncio\base_events.py", line 579, in run_until_complete
    return future.result()
  File "C:\Users\SA\AppData\Roaming\Python\Python37\site-packages\rasa\train.py", line 87, in train_async
    kwargs,
  File "C:\Users\SA\AppData\Roaming\Python\Python37\site-packages\rasa\train.py", line 169, in _train_async_internal
    kwargs=kwargs,
  File "C:\Users\SA\AppData\Roaming\Python\Python37\site-packages\rasa\train.py", line 203, in _do_training
    kwargs=kwargs,
  File "C:\Users\SA\AppData\Roaming\Python\Python37\site-packages\rasa\train.py", line 331, in _train_core_with_validated_data
    kwargs=kwargs,
  File "C:\Users\SA\AppData\Roaming\Python\Python37\site-packages\rasa\core\train.py", line 66, in train
    agent.train(training_data, **kwargs)
  File "C:\Users\SA\AppData\Roaming\Python\Python37\site-packages\rasa\core\agent.py", line 713, in train
    self.policy_ensemble.train(training_trackers, self.domain, **kwargs)
  File "C:\Users\SA\AppData\Roaming\Python\Python37\site-packages\rasa\core\policies\ensemble.py", line 90, in train
    policy.train(training_trackers, domain, **kwargs)
  File "C:\ICA\restaurantbot\custom_policy.py", line 286, in train
    self.model.fit(
AttributeError: 'NoneType' object has no attribute 'fit

   

Could I get help to solve this issue?

**Comment by sara-tagger** [comment]
Thanks for the question, our Github issue board is for **bugs and feature requests only,** though 😕
Please ask this question in the [forum✨](https://forum.rasa.com/c/rasa)

###### If you were describing a bug, please create a [report](https://github.com/RasaHQ/rasa/issues/new?labels=bug&template=bug_report.md) and fill out the template
