### ISSUE TITLE
Rasa X does not use forms: prefix when doing interactive learning with forms

### ISSUE THREAD

**Issue by amaurymercier** [RasaHQ/rasa#4561]
Hi, I'm trying out Rasa X for interactive learning and it turns out integration with Forms is not done yet from a stories point of view ?

**Rasa version**: 1.1.8

**Rasa X version** (if used & relevant): 0.19.5

**Python version**: 3.6.7

**Operating system** (windows, osx, ...): Ubuntu 18.04

**Issue**: When doing interactive learning with a form-powered chatbot, resulting stories do not have the forms: prefix as expected.

**Error (including full traceback)**:
```

```

**Command or request that led to error**: Doing interactive learning using local Rasa X
```

```

**Content of configuration file (config.yml)** (if relevant):
```yml

```

**Content of domain file (domain.yml)** (if relevant):
```yml

```

**Comment by amn41** [comment]
the `form:` prefix should definitely be in there. Can you please share a minimal reproducible example ?

**Comment by amaurymercier** [comment]
I upgraded to rasa==1.3.7 and rasa-x==0.21.3, and I still have the bug. The whole app is much better in this version though, thanks!

I'll check how it goes with FormBot for the minimal reproducible example, and hopefully post it tomorrow.

**Comment by amn41** [comment]
awesome, thanks!

**Comment by amaurymercier** [comment]
I used the formbot example chat from the master branch in the rasa repository, and the stories issued from interactive training look the same : 

```
## New Story

* greet
    - utter_greet
* request_restaurant
    - restaurant_form
    - form{"name":"restaurant_form"}
    - slot{"requested_slot":"cuisine"}
* inform{"cuisine":"italian"}
    - restaurant_form
    - slot{"cuisine":"italian"}
    - slot{"requested_slot":"num_people"}
```

So likewise, there is no `form:` prefix :)

**Comment by amn41** [comment]
cc @gausie is this still relevant?
