### ISSUE TITLE
Cannot connect to Action server with K8s deployment

### ISSUE THREAD

**Issue by firewater334** [RasaHQ/rasa#4563]
**Rasa version**:
rasa                     1.4.0a1
rasa-sdk                 1.3.2
**Operating system** (windows, osx, ...):
MacOs
**Issue**:
Hi,

So I am trying to execute my Custom Actions in my Kubernetes Deployment.  However, I get the error of "cannot connect to host action-service:5055".  I have specified my action endpoint in my endpoints.yml file.  Perhaps I am incorrectly specifying my endpoint?  I have tried action_server:5055 and action-server:5055 as well, but I have attached the error as well as current service file.  Is this a bug?  Thank you!

**Action Endpoint**
action_endpoint:
  url: "http://action-service:5055/webhook"

**Services File**
![image](https://user-images.githubusercontent.com/47159809/66216988-16923000-e68c-11e9-89c0-061caa019021.png)

**Error (including full traceback)**:

![image](https://user-images.githubusercontent.com/47159809/66217053-31fd3b00-e68c-11e9-96e1-b71c301b54e9.png)

Command I am executing in my action server deployment is (in multiline yml format)
        - start
        - --actions
        - demo.actions
        - --debug

**Comment by sara-tagger** [comment]
Thanks for raising this issue, @erohmensing will get back to you about it soon✨

###### Please also check out the [docs](https://rasa.com/docs/) and the [forum](https://forum.rasa.com/) in case your issue was raised there too 🤗

**Comment by erohmensing** [comment]
Sorry to have missed this, I got tagged just when going on vacation. Is this still a relevant issue? However, as far as I'm concerned this is a usage issue, which should be on the forum. 

However I think the issue is likely that you're missing the `/webhook` on the endpoint url.
