### ISSUE TITLE
Utterance Replication Checker

### ISSUE THREAD

**Issue by serdarbozoglan** [RasaHQ/rasa#4566]
**Description of Problem**:
I just wonder, if Rasa would have an feature which checks if an utterances added before to the training set before. If so, it may warn the developer. This enables utterance duplication/replication in the training set. Otherwise same utterance may be added to different intents accidentally, particularly if the intents are similar to each other and if you have a large training set. So this might hurt the model performance. 

**Overview of the Solution**:

**Examples** 
For example: 

**## intent: payBill**
- pay bill

**## intent: payment_Verification**
- pay bill

Developer my put the same utterance under the different intents.

**Comment by amn41** [comment]
this would be a nice addition to the `rasa data validate` command https://rasa.com/docs/rasa/user-guide/validate-files/#validate-files - would you be up for contributing this ?
