### ISSUE TITLE
NLU difference between 1.2.x and 1.3.x

### ISSUE THREAD

**Issue by Lambik** [RasaHQ/rasa#4573]
**Rasa version**: 1.2.9 and 1.3.6

**Rasa X version** (if used & relevant): -

**Python version**: 3.6.8

**Operating system** (windows, osx, ...): ubuntu 18

**Issue**:

When training an NLU in 1.2.9, I can use it as expected. When training in 1.3.6 with the same .md file, I always get the same intent as output.

My training markdown file is [here on pastebin](https://pastebin.com/TKzfVj3U).

**Command or request that led to error**:
```
rasa train nlu --config config.yml --nlu FILE
```

**Content of configuration file (config.yml)** (if relevant):
```yml
# Configuration for Rasa NLU.
language: nl
pipeline: supervised_embeddings

# Configuration for Rasa Core.
# https://rasa.com/docs/rasa/core/policies/
policies:
  - name: MemoizationPolicy
  - name: KerasPolicy
  - name: MappingPolicy
```

**Testrun in shell of 1.3.6**:
```
Next message:
Is er een virtuele rondleiding mogelijk?
{
  "intent": {
    "name": "9",
    "confidence": 0.125
  },
  "entities": [],
  "intent_ranking": [
    {
      "name": "9",
      "confidence": 0.125
    },
    {
      "name": "77",
      "confidence": 0.125
    },
    {
      "name": "71",
      "confidence": 0.125
    },
    {
      "name": "61",
      "confidence": 0.125
    },
    {
      "name": "54",
      "confidence": 0.125
    },
    {
      "name": "48",
      "confidence": 0.125
    },
    {
      "name": "33",
      "confidence": 0.125
    },
    {
      "name": "1",
      "confidence": 0.125
    }
  ],
  "text": "Is er een virtuele rondleiding mogelijk?"
}
```

As you can see, everything has the same confidence, which is quite illogical.

**Testrun in shell of 1.2.9**:
```
Next message:
Is er een virtuele rondleiding mogelijk?
{
  "intent": {
    "name": "71",
    "confidence": 0.957551121711731
  },
  "entities": [],
  "intent_ranking": [
    {
      "name": "71",
      "confidence": 0.957551121711731
    },
    {
      "name": "77",
      "confidence": 0.05605613812804222
    },
    {
      "name": "33",
      "confidence": 0.025996943935751915
    },
    {
      "name": "9",
      "confidence": 0.023518487811088562
    },
    {
      "name": "48",
      "confidence": 0.0
    },
    {
      "name": "61",
      "confidence": 0.0
    },
    {
      "name": "1",
      "confidence": 0.0
    },
    {
      "name": "54",
      "confidence": 0.0
    }
  ],
  "text": "Is er een virtuele rondleiding mogelijk?"
}
```

What did I do wrong?

**Comment by sara-tagger** [comment]
Thanks for the issue, @dakshvar22 will get back to you about it soon!

###### You may find help in the [docs](https://rasa.com/docs/) and the [forum,](https://forum.rasa.com/) too 🤗

**Comment by dakshvar22** [comment]
@Lambik Thanks for pointing this out.
Seems like a bug. Will release a patch fix soon.

**Comment by Lambik** [comment]
@dakshvar22 I looked at your fix, was it because my intents are numbers only?

I have them as numbers, because they correspond to the IDs of answers in my database, that's why...

**Comment by dakshvar22** [comment]
@Lambik Yes, there was a bug which wrongly processes intent labels. It got surfaced by your example where intents contained only numbers. It should work fine now.

**Comment by Lambik** [comment]
@dakshvar22 thanks for fixing it <3 
When will I be able to use it? (just did `pip3 install --upgrade rasa`, got 1.3.8, still the same issue after retraining the model)

**Comment by dakshvar22** [comment]
@Lambik Should be out with 1.3.9, in a day at the most.
