### ISSUE TITLE
When I run the file train_init.py it shows the following error.Please help me to resolve this.Thanks 

### ISSUE THREAD

**Issue by ihtisham0331** [RasaHQ/rasa#4574]
C:\Users\syed shah Shah\Desktop\Weatherbot>python train_init.py Using TensorFlow backend. Traceback (most recent call last):   File "train_init.py", line 17, in <module>     agent = Agent('weather_domain.yml', policies = [MemoizationPolicy(), KerasPo licy()])   File "C:\Users\syed shah Shah\Anaconda3\lib\site-packages\rasa_core\policies\k eras_policy.py", line 26, in __init__     import keras   File "C:\Users\syed shah Shah\Anaconda3\lib\site-packages\keras\__init__.py", line 3, in <module>     from . import utils   File "C:\Users\syed shah Shah\Anaconda3\lib\site-packages\keras\utils\__init__ .py", line 6, in <module>     from . import conv_utils   File "C:\Users\syed shah Shah\Anaconda3\lib\site-packages\keras\utils\conv_uti ls.py", line 9, in <module>     from .. import backend as K   File "C:\Users\syed shah Shah\Anaconda3\lib\site-packages\keras\backend\__init __.py", line 1, in <module>     from .load_backend import epsilon   File "C:\Users\syed shah Shah\Anaconda3\lib\site-packages\keras\backend\load_b ackend.py", line 90, in <module>     from .tensorflow_backend import *   File "C:\Users\syed shah Shah\Anaconda3\lib\site-packages\keras\backend\tensor flow_backend.py", line 5, in <module>     import tensorflow as tf   File "C:\Users\syed shah Shah\Anaconda3\lib\site-packages\tensorflow\__init__. py", line 22, in <module>     from tensorflow.python import pywrap_tensorflow  # pylint: disable=unused-im port   File "C:\Users\syed shah Shah\Anaconda3\lib\site-packages\tensorflow\python\__ init__.py", line 49, in <module>     from tensorflow.python import pywrap_tensorflow   File "C:\Users\syed shah Shah\Anaconda3\lib\site-packages\tensorflow\python\py wrap_tensorflow.py", line 58, in <module>     from tensorflow.python.pywrap_tensorflow_internal import *   File "C:\Users\syed shah Shah\Anaconda3\lib\site-packages\tensorflow\python\py wrap_tensorflow_internal.py", line 114     def TFE_ContextOptionsSetAsync(arg1, async):                                              ^ SyntaxError: invalid syntax  (base)

**Comment by sara-tagger** [comment]
Thanks for the issue, @tmbo will get back to you about it soon!

###### You may find help in the [docs](https://rasa.com/docs/) and the [forum,](https://forum.rasa.com/) too 🤗

**Comment by ihtisham0331** [comment]
I have resolved the issue

**Comment by munizaimran** [comment]
> I have resolved the issue

how, please help
