### ISSUE TITLE
Custom tracker store should be passed with optional event_broker instance

### ISSUE THREAD

**Issue by AppliedSoul** [RasaHQ/rasa#4577]
**Description of Problem**:
Currently event_broker instance is not passed to custom tracker store when creating it:
https://github.com/RasaHQ/rasa/blob/master/rasa/core/tracker_store.py#L75

It would be desirable like others , if optional event_broker instance be passed to it.

**Overview of the Solution**:
pass optional event_broker instance when initializing custom tracker 

**Examples** (if relevant):
N/A

**Blockers** (if relevant):
N/A

**Definition of Done**:
N/A

**Comment by AppliedSoul** [comment]
If needed I would be happy to submit pull request for this change

**Comment by sara-tagger** [comment]
Thanks for submitting this feature request 🚀@akelad will get back to you about it soon!✨

**Comment by akelad** [comment]
i believe that does make sense, we'd be happy to accept a PR from you!

**Comment by erohmensing** [comment]
fixed in #4593
