### ISSUE TITLE
Flattened stories are not exported when training with dump-stories flag

### ISSUE THREAD

**Issue by nbeuchat** [RasaHQ/rasa#4583]
**Rasa version**: 1.3.3

**Python version**: 3.6

**Operating system** (windows, osx, ...): Ubuntu

**Issue**:
When training using the `--dump-stories` flag, I cannot find the flattened stories anywhere. I tried looking in the final models zip folder (also in the all of the subfolders) and in the /tmp folder during and after the training. 

**Error (including full traceback)**:
```

```

**Command or request that led to error**:
```
rasa train --dump-stories --debug
```

**Content of configuration file (config.yml)** (if relevant):
```yml

```

**Content of domain file (domain.yml)** (if relevant):
```yml

```

**Comment by cristianmtr** [comment]
I debugged this and the flag `dump-stories` is not passed correctly down to the `rasa.core.policies.ensemble.PolicyEnsemble._persist_metadata`. It seems at some point the `kwargs` of `dump_stories` is ignored and a new parameter `dump_flattened_stories` is set. This parameter has the default value of `False`

**Comment by cristianmtr** [comment]
Unless this was explicitly fixed, it's most likely still a problem
