### ISSUE TITLE
Synchronizing Rasa message ID with Teams/BotFramework ID

### ISSUE THREAD

**Issue by glaulom** [RasaHQ/rasa#4585]
**Description of Problem**: Actually, messages IDs stored in the database by the tracker store are different from the one generated by Microsoft Teams (through BotFramework). It would be very nice to synchronize both IDs.

**Overview of the Solution**: Just re-use Teams IDs rather than creating new ones.

**Blockers** (if relevant): Is BotFramework getting messages ID ?

**Definition of Done**:

*   [ ] Feature implemented
*   [ ] Tests are added

**Comment by sara-tagger** [comment]
Thanks for submitting this feature request 🚀@dakshvar22 will get back to you about it soon!✨

**Comment by wochinge** [comment]
@glaulom Is this something you want to work on?

**Comment by glaulom** [comment]
@wochinge I actually don't have any time to work on this, so it's a proposition to the community.

**Comment by pnandhini11** [comment]
Hi, Is this issue closed? Can I work on this?

**Comment by wochinge** [comment]
Sure - go for it @pnandhini11 ! 🚀

**Comment by pnandhini11** [comment]
Hi @wochinge, 
                In botframework channel, message id (sender_id) that we use for conversation is the ID retrieved from json received in webhook. What exactly in the "FROM ID"  in botframework channel?  How different that from the Microsoft Teams ID? 

Check this:

 @botframework_webhook.route("/webhook", methods=["POST"])
        async def webhook(request: Request) -> HTTPResponse:
            **postdata = request.json**
            metadata = self.get_metadata(request)

            metadata_with_attachments = self.add_attachments_to_metadata(
                postdata, metadata
            )

            try:
                if postdata["type"] == "message":
                    out_channel = BotFramework(
                        self.app_id,
                        self.app_password,
                        postdata["conversation"],
                        postdata["recipient"],
                        postdata["serviceUrl"],
                    )

                    user_msg = UserMessage(
                        text=postdata.get("text", ""),
                        output_channel=out_channel,
                        **sender_id=postdata["from"]["id"],**
                        input_channel=self.name(),
                        metadata=metadata_with_attachments,
                    )
