### ISSUE TITLE
Support plain yaml in Rasa X config settings API

### ISSUE THREAD

**Issue by rgstephens** [RasaHQ/rasa#4588]
**Description of Problem**:
As discussed in this series of [forum posts](https://forum.rasa.com/t/nlu-config-put-api-call-400-error/19362), the existing settings call requires the yaml to be embedded in json.

Both the domain and config put calls pass yaml data. Unfortunately, the format of the data in those calls is not consistent. I think the domain call passing the yaml directly is better because the code can suck up the users domain.yml file without having to manipulate the file.

**Overview of the Solution**:
Provide a config settings endpoint that supports passing plain yaml liked the domain PUT.

**Comment by sara-tagger** [comment]
Thanks for submitting this feature request 🚀@ricwo will get back to you about it soon!✨

**Comment by ricwo** [comment]
Thanks a lot for your suggestion - makes sense 👍

**Comment by rgstephens** [comment]
@ricwo, Has this featured been added as part of a PR or is it being dropped?

**Comment by ricwo** [comment]
@rgstephens it's been implemented and will be part of our next minor release (rasa X 0.22.0)
