### ISSUE TITLE
Problem using forms

### ISSUE THREAD

**Issue by alessandrarequena** [RasaHQ/rasa#4589]
**Rasa version**:
1.2.7

**Rasa X version** (if used & relevant):

**Python version**:
3.6

**Operating system** (windows, osx, ...):
Windows 10

**Issue**:
The form executes extract_other_slots, it does not extract slots that maps to entities with different name from the slot.
For example, the scenario is a service that give answers about a person. The user enter the name of the person and the chatbot give some information about he/she.

So, the user enters a message like "Jose Alves" and an entity called person is recognized. The form has two slots - parameter and confirmation. The mapping for parameter is the entity person and confirmation are intents that confirm or not the query. 
When the form is activated, it reads parameter from the entity person and asks for the slot confirmation. But if the user, instead of confirming que query, changes his mind and enter another name. In this case, the form is already active, will try to extract the confirmation slot, will fail, and then will try to extract other slots. However, when it tries to extract other slots, it has the following check:

```
# check whether the slot should be filled
# by entity with the same name
should_fill_entity_slot = (
           other_slot_mapping["type"] == "from_entity"
           and other_slot_mapping.get("entity") == slot
           and self.intent_is_desired(other_slot_mapping, tracker)
)
```

This evaluates to false if the slot maps to an entity with a different name and that's what is said in the comment. **But why the slot will be only extracted if it maps to an entity with the same name?** 
With this code in place, the new name that the user entered in the second time will not be extracted by the form, and the form will ask for confirmation on an old parameter. 

In our use case, we need to do this because our parameter in the form can come from different entities. So, commenting out this line - "and other_slot_mapping.get("entity") == slot" - solves our problem.

**Error (including full traceback)**:
```
The problem is described above. No exception is generated, just a malfuncioning.
```

**Command or request that led to error**:
```
python -m rasa shell --debug --endpoints endpoints-dev.yml
```

**Content of configuration file (config.yml)** (if relevant):
```yml

```

**Content of domain file (domain.yml)** (if relevant):
```yml

```

**Comment by sara-tagger** [comment]
Thanks for raising this issue, @tabergma will get back to you about it soon✨

###### Please also check out the [docs](https://rasa.com/docs/) and the [forum](https://forum.rasa.com/) in case your issue was raised there too 🤗

**Comment by Ghostvv** [comment]
because when you try to extract additional information not related to currently `requested_slot` from some entity that doesn't have the same name as any slot, how do you which slot this entity should fill?

**Comment by Ghostvv** [comment]
the code snippet above, is from `extract_other_slots` method that is responsible to extracting information not related to requested slot. In order to extract requested slot there is `extract_requested_slot` method

**Comment by alessandrarequena** [comment]
But that's the problem. The method is about extracting other slots, rather than the requested slot. 
In validate method, when rasa validates the value of the requested slot, there are these lines (348-350):

# extract other slots that were not requested
# but set by corresponding entity or trigger intent mapping
slot_values = self.extract_other_slots(dispatcher, tracker, domain)

So, as I understand, rasa will extract the other slots that are required but not requested. However, in the method extract_other_slots, the slots that are mapped to entities are only extracted if the entity has the same name as the slot. And this does't work for our use case, because our slot come from three different entities, it depends on the scenario.

**Comment by Ghostvv** [comment]
there is exactly the reason why other slots are extracted

> So, as I understand, rasa will extract the other slots that are required but not requested. 
yes

> because our slot come from three different entities **it depends on the scenario.**
that is exactly the reason why entity name should correspond to slot name, because there is no way to know which slot to populate with recognized entity (e.g. entity `number` could correspond to several slots)

This is a discussion now, so please post this question on our [forum](https://forum.rasa.com) if you want to continue discussion.
