### ISSUE TITLE
Tensorflow issue in rasa

### ISSUE THREAD

**Issue by ihtisham0331** [RasaHQ/rasa#4594]
When i run training file Train_init.py  it failed and show error "Failed to run native tensorflow runtime".Please help me how resolve this issue.Thanks in advance

**Comment by sara-tagger** [comment]
Thanks for the question, our Github issue board is for **bugs and feature requests only,** though 😕
Please ask this question in the [forum✨](https://forum.rasa.com/c/rasa)

###### If you were describing a bug, please create a [report](https://github.com/RasaHQ/rasa/issues/new?labels=bug&template=bug_report.md) and fill out the template
