### ISSUE TITLE
Rasa Docker - Adding Custom Dependencies Problems

### ISSUE THREAD

**Issue by SpyrosKptanopulos** [RasaHQ/rasa#4595]
Hello everyone, 

I have a question about Rasa in Docker, I have to install the pymssql to connect Rasa to SQL Server, which without Docker works perfectly, but when trying to put everything in Docker I get the following error:

```
$ sudo docker run -v $ (pwd): / app rasabot shell
docker: Error response from daemon: OCI runtime create failed: container_linux.go: 345: starting container process caused "exec: \" ./ entrypoint.sh \ ": stat ./entrypoint.sh: no such file or directory": unknown .
ERRO [0001] error waiting for container: context canceled
```

and the Dockerfile is like that

```
FROM rasa / rasa-sdk: latest

# Add a custom system library (e.g. git)
RUN apt-get update && \
     apt-get install -y git

# Add a custom python library (e.g. jupyter)
RUN pip install --no-cache-dir pymssql
```

As shown in the Rasa with Docker Documentation:

[](https://rasa.com/docs/rasa/user-guide/running-rasa-with-docker/#adding-custom-dependencies)

I hope you can help me.

A pleasure and thanks!

**Comment by sara-tagger** [comment]
Thanks for the question, our Github issue board is for **bugs and feature requests only,** though 😕
Please ask this question in the [forum✨](https://forum.rasa.com/c/rasa)

###### If you were describing a bug, please create a [report](https://github.com/RasaHQ/rasa/issues/new?labels=bug&template=bug_report.md) and fill out the template
