### ISSUE TITLE
Enable kwargs for service post("/model/train")

### ISSUE THREAD

**Issue by lsgome** [RasaHQ/rasa#4596]
**Description of Problem**:
Currently the http / model / train service does not allow you to define extra parameters that exist on the command line, for example the augmentation_factor.

**Overview of the Solution**:
Change the / model / train service to include in the request body a dictionary where the kwargs parameter can be set. Pass the parameter to train_async.

**Examples** (if relevant):
Request:
{
  "domain": ...
 "config": ...
  "nlu": ...
  "kwargs": ...
}

**Definition of Done**:
Test training by changing the augmentation_factor parameter

**Comment by sara-tagger** [comment]
Thanks for submitting this feature request 🚀@msamogh will get back to you about it soon!✨

**Comment by wochinge** [comment]
Hi @lsgome , sounds like a great idea! Do you want to work on it?

**Comment by lsgome** [comment]
Yes, I can do.

**Comment by wochinge** [comment]
Amazing @lsgome ! Let me know if you need any help! I assign you for now so that nobody starts working on it at the same time, but feel free to un-assign you in case you change your mind.

**Comment by theanht1** [comment]
@wochinge does anyone take this issue? I could work for this enhancement

**Comment by wochinge** [comment]
Feel free to start working on it @theanht1 You can also share an early draft in case you need feedback / help. Just tag me in the PR then 🚀

**Comment by m-vdb** [comment]
Fixed in https://github.com/RasaHQ/rasa/pull/8132
