### ISSUE TITLE
Add flag to CLI to persist NLU data

### ISSUE THREAD

**Issue by akelad** [RasaHQ/rasa#4599]
With this PR https://github.com/RasaHQ/rasa/pull/4388 the feature of optionally persisting NLU training data was introduced. However, there is currently no flag you can use in the CLI to enable this, so it would be good to add that.

**Comment by akelad** [comment]
@ronancummins

**Comment by ronancummins** [comment]
@akelad Awaiting review..

**Comment by akelad** [comment]
merged 🚀
