### ISSUE TITLE
Incorrect warning about WhitespaceTokenizer

### ISSUE THREAD

**Issue by tabergma** [RasaHQ/rasa#4605]
The warning in https://rasa.com/docs/rasa/user-guide/evaluating-models/#intent-classification is not true anymore. Our `WhitespaceTokenizer` splits `Brian's` into multiple tokens.

We should update or remove the warning.

**Comment by michiboo** [comment]
Hi Can I have a go at this issue?

**Comment by tabergma** [comment]
@michiboo Sure, go ahead 🚀 Thanks!

**Comment by erohmensing** [comment]
@michiboo are you still interested in working on this issue?

**Comment by michiboo** [comment]
@erohmensing  Hi yes, sorry for the delay I will open a PR soon

**Comment by tabergma** [comment]
fixed in https://github.com/RasaHQ/rasa/pull/5643
