### ISSUE TITLE
Error in config_spacy.json file 

### ISSUE THREAD

**Issue by sanchit892** [RasaHQ/rasa#4609]
while training a model there is an issue with config_spacy.json file 

error
ValueError: unknown training file format : unk for file config_spacy.json

inside the json file 
{
 "pipeline":"spacy_sklearn",
 "path":".models/nlu",
 "data":".data/data.json"
}

please help

**Comment by sara-tagger** [comment]
Thanks for the question, our Github issue board is for **bugs and feature requests only,** though 😕
Please ask this question in the [forum✨](https://forum.rasa.com/c/rasa)

###### If you were describing a bug, please create a [report](https://github.com/RasaHQ/rasa/issues/new?labels=bug&template=bug_report.md) and fill out the template
