### ISSUE TITLE
Bot stops repying per intent on RASA Shell

### ISSUE THREAD

**Issue by JECasillas** [RasaHQ/rasa#4610]
**Rasa version**: Rasa 1.2.9

**Python version**: 3.6.9

**Operating system** : Ubuntu 16.04

I've just recently began exploring Rasa after having used Dialogflow for a long while. Once I get a better understanding of it's more intimate components, I may customize the models on the pipeline with my own embeddings or of the sort for better classification in Spanish. 

However, having tested it on different installations of rasa using the english sample demo chatbot that's generated as a project when running `rasa init --no-prompt`, I'm finding that every time such sample replies only a limited number of times for every intent triggered when trying the bot on the shell. 

Normally and from my experience using other services and providers, the bot replies every time the intent is triggered, and stories should be able to be repeated instead of triggered only once, which doesn't happen in this case, along with other unusual behavior, like triggering the wrong intents or even replying with the same intent to completely nonsensical strings.

Example 1
![Screenshot from 2019-10-14 18-27-39](https://user-images.githubusercontent.com/9041251/66789625-124aeb80-eeb2-11e9-8730-2dfcc96d165d.png)

Example 2
![Screenshot from 2019-10-14 18-24-09](https://user-images.githubusercontent.com/9041251/66789629-14ad4580-eeb2-11e9-9826-0456048ee2cb.png)

I happen to get these warnings as well any time I make use of rasa, even when just getting the version. 
I don't know what to make of them, so I'll attach them in case it could be relevant to this.
`/home/user/rasaenv/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:526: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint8 = np.dtype([("qint8", np.int8, 1)])
/home/user/rasaenv/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:527: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint8 = np.dtype([("quint8", np.uint8, 1)])
/home/user/rasaenv/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:528: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint16 = np.dtype([("qint16", np.int16, 1)])
/home/user/rasaenv/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:529: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint16 = np.dtype([("quint16", np.uint16, 1)])
/home/user/rasaenv/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:530: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint32 = np.dtype([("qint32", np.int32, 1)])
/home/user/rasaenv/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:535: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  np_resource = np.dtype([("resource", np.ubyte, 1)])
`

Now as to the contents of the config, nlu, stories and domain files, they're the same than the samples anyone can get and see for themselves, but I include them here anyway to outline how little there is for me to make changes to see if the issue is on any of them.

config.yml:
![Screenshot from 2019-10-14 18-40-48](https://user-images.githubusercontent.com/9041251/66789720-77064600-eeb2-11e9-849c-4cdc6b011062.png)

domain.yml:
![Screenshot from 2019-10-14 18-42-10](https://user-images.githubusercontent.com/9041251/66789733-81284480-eeb2-11e9-8e25-59642fed5d79.png)

stories.md:
![Screenshot from 2019-10-14 18-40-56](https://user-images.githubusercontent.com/9041251/66789740-87b6bc00-eeb2-11e9-9e6b-fcca66b595f0.png)

since it is presenting this behavior right out of the box, I don't see much else to try before fixing this issue.

**Comment by sara-tagger** [comment]
Thanks for the issue, @btotharye will get back to you about it soon!

###### You may find help in the [docs](https://rasa.com/docs/) and the [forum,](https://forum.rasa.com/) too 🤗

**Comment by btotharye** [comment]
hello @JECasillas this is actually not a bug but more how the product and stories work.  Rasa uses stories to train the bot the type of conversation flow.  So if it already answered a flow or such it wouldn't respond back again.  You can read more about this at https://rasa.com/docs/rasa/core/stories/

If you have further questions about this I would open up a post on the https://forum.rasa.com/ and we can help there.

I'm going to close out this issue for now since its not a real bug.

Thanks
