### ISSUE TITLE
rest api error 

### ISSUE THREAD

**Issue by mlcode-jeevan** [RasaHQ/rasa#4611]
from __future__ import absolute_import
from __future__ import division
from __future__ import print_function
from __future__ import unicode_literals

import logging

from rasa_core.channels.channel import InputChannel
from rasa_core import utils
from rasa_core.agent import Agent
from rasa_core.interpreter import RasaNLUInterpreter
from rasa_core.channels.channel import UserMessage
from rasa_core.channels.channel import CollectingOutputChannel
from rasa_core.channels import RestInput 
from flask import Blueprint, request, jsonify

logger = logging.getLogger(__name__)
class SimpleWebBot(RestInput):

    """A simple web bot that listens on a url and responds."""

    def blueprint(self, on_new_message):
        custom_webhook = Blueprint('custom_webhook', __name__)

        @custom_webhook.route("/status", methods=['GET'])
        def health():
            return jsonify({"status": "ok"})

        @custom_webhook.route("/", methods=['POST'])
        def receive():
            payload = request.json
            sender_id = payload.get("sender", None)
            text = payload.get("message", None)
            out = CollectingOutputChannel()
            on_new_message(UserMessage(text, out, sender_id))
            responses = [m["text"] for _, m in out.messages]
            return jsonify(responses)

        return custom_webhook

def run(serve_forever=True):

    #path to your NLU model
    interpreter = RasaNLUInterpreter("models/nlu/default/current")
    # path to your dialogues models
    agent = Agent.load("models/dialogue", interpreter=interpreter)
    #http api endpoint for responses
    input_channel = SimpleWebBot()
    if serve_forever:
        agent.handle_channels(InputChannel(5005, "/chat", input_channel))
    return agent

if __name__ == '__main__':

    utils.configure_colored_logging(loglevel="INFO")
    run()

the above code giving the below response 

![Capture](https://user-images.githubusercontent.com/53812699/66821713-817f1900-ef60-11e9-9a66-9d8bffe9333c.PNG)

**Comment by sara-tagger** [comment]
Thanks for the question, our Github issue board is for **bugs and feature requests only,** though 😕
Please ask this question in the [forum✨](https://forum.rasa.com/c/rasa)

###### If you were describing a bug, please create a [report](https://github.com/RasaHQ/rasa/issues/new?labels=bug&template=bug_report.md) and fill out the template
