### ISSUE TITLE
Rasa X NLU Training Search by Intent

### ISSUE THREAD

**Issue by rgstephens** [RasaHQ/rasa#4613]
**Description of Problem**:
It can be hard to find an intent as the size of the bot content grows.

**Overview of the Solution**:
It would be nice to if the NLU Training Data page, `/data/training-data`, would search the intent name in addition to the example utterance. I thought this request had been discussed in another issue but I could not find it.

**Comment by sara-tagger** [comment]
Thanks for submitting this feature request 🚀@wochinge will get back to you about it soon!✨

**Comment by samsucik** [comment]
I think this can now be closed as the filter-by-intent feature has been added.
