### ISSUE TITLE
1.3.x EmbeddingIntentClassifier Failure

### ISSUE THREAD

**Issue by rgstephens** [RasaHQ/rasa#4616]
**Rasa version**: 1.3.9

**Python version**: 3.6.9

**Operating system**: Docker image `rasa/rasa:1.3.9-full`

**Issue**:
Model training is crashing on under 1.3.9 during `EmbeddingIntentClassifier` phase. The last few lines before the abort are below.

I have no problems using the 1.3.9 version with a smaller bot (19 unique intents) but with this larger (279 intents) bot it is failing. The training runs fine under 1.2.11

**Error (including full traceback)**:
```
2019-10-14 15:40:44 INFO     rasa.nlu.model  - Starting to train component CountVectorsFeaturizer
2019-10-14 15:40:45 INFO     rasa.nlu.model  - Finished training component.
2019-10-14 15:40:45 INFO     rasa.nlu.model  - Starting to train component EmbeddingIntentClassifier
Epochs:   0%|          | 1/300 [00:14<1:12:17, 14.51s/it, loss=62.778, acc=0.237]/home/ubuntu >
```

**Command or request that led to error**:
```
docker run -v $(pwd):/app rasa/rasa:1.3.9-full train --config /app/data/config.yml --out /app/models --domain /app/data/domain.yml --data /app/data/training /app/data/stories -vv
```

**Content of configuration file (config.yml)** (if relevant):
```yml
pipeline: supervised_embeddings
language: en
policies:
- name: MemoizationPolicy
- name: KerasPolicy
- name: MappingPolicy
- name: FormPolicy
```

**Content of domain file (domain.yml)** (if relevant):
I can share this privately if necessary.

**Comment by sara-tagger** [comment]
Thanks for the issue, @dakshvar22 will get back to you about it soon!

###### You may find help in the [docs](https://rasa.com/docs/) and the [forum,](https://forum.rasa.com/) too 🤗

**Comment by Ghostvv** [comment]
could you please post the error here

**Comment by rgstephens** [comment]
It was a memory issue as noted in the [forum discussion](https://forum.rasa.com/t/1-3-training-crash-during-embeddingintentclassifier/19775).

There was no error message, the train stop without a message.

I have 12Gb of memory and my docker engine has a default memory allocation of 2Gb. I increased that to 6Gb and restarted the docker engine and ran the training and it worked. Thanks!
