### ISSUE TITLE
Full docummentation Jupyter

### ISSUE THREAD

**Issue by ilqxa** [RasaHQ/rasa#4617]
Please help me find the full API documentation for Jupiter Notebook. Does it even exist?

**Comment by sara-tagger** [comment]
Thanks for the question, our Github issue board is for **bugs and feature requests only,** though 😕
Please ask this question in the [forum✨](https://forum.rasa.com/c/rasa)

###### If you were describing a bug, please create a [report](https://github.com/RasaHQ/rasa/issues/new?labels=bug&template=bug_report.md) and fill out the template
