### ISSUE TITLE
rasa data validate should fail early if domain cannot be read

### ISSUE THREAD

**Issue by amn41** [RasaHQ/rasa#4619]
**Description of Problem**:
Currently, if there is a syntax error in your domain, `rasa data validate` will load an empty domain and return a whole bunch of errors. Not super user friendly because you have to scroll through a bunch of errors to get to the top and see that yaml parsing failed. 

**Overview of the Solution**:
It would be nice if this command exited early if the domain can't be loaded (invalid yaml, duplicate actions, etc)

**Definition of Done**:
- [ ] Tests are added
- [ ] Feature mentioned in the changlog

**Comment by joaorobson** [comment]
I would like to work on this. Are you already assigned to this?

**Comment by amn41** [comment]
certainly not! would be awesome if you could work on it :)
