### ISSUE TITLE
Docs: a table and a list are ill formatted

### ISSUE THREAD

**Issue by ju-sh** [RasaHQ/rasa#4620]
**Rasa version**: 1.3.9

**Python version**: 3.7

**Operating system** (windows, osx, ...): linux

**Issue**:
A table and a list in the docs for policies at https://rasa.com/docs/rasa/core/policies/ is not being rendered properly.
![ill formatted table](https://i.imgur.com/nmspSzD.png)

and

![ill formatted list](https://imgur.com/rqwvP5R.png)

---

We can make it

![good table](https://imgur.com/ok3mEmW.png)

and 

![good list](https://imgur.com/I2FUxwK.png)

**Comment by sara-tagger** [comment]
Thanks for raising this issue, @amn41 will get back to you about it soon✨

###### Please also check out the [docs](https://rasa.com/docs/) and the [forum](https://forum.rasa.com/) in case your issue was raised there too 🤗

**Comment by btotharye** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Work on github issue #4586 status response doesn't show original model file](https://trello.com/c/pJr9lom4/13-work-on-github-issue-4586-status-response-doesnt-show-original-model-file)

**Comment by ju-sh** [comment]
I think this issue has been fixed. Closing.
