### ISSUE TITLE
Buttons in Rasa X messages launch new browser tab

### ISSUE THREAD

**Issue by tangochris** [RasaHQ/rasa#4622]
**Rasa version**: 1.3.9

**Rasa X version**: 0.21.4

**Operating system**: Rasa X on OSX (Chrome)

**Issue**: Clicking buttons in messages launches a new browser tab.

**Error**: See screencast: https://www.dropbox.com/s/oibcw15hfuu2g1o/screen%20recording%202019-10-16%20at%2010.23.53%20am.mov?dl=0

In the source HTML, I see a `target="_blank"` on the button link. I believe that is the wrong target.

**Command or request that led to error**: Clicking any button in a message causes error. 

This error has persisted through every point release of Rasa X 0.21. Prior to 0.21, it didn't happen.

**Comment by sara-tagger** [comment]
Thanks for raising this issue, @wochinge will get back to you about it soon✨

###### Please also check out the [docs](https://rasa.com/docs/) and the [forum](https://forum.rasa.com/) in case your issue was raised there too 🤗

**Comment by wochinge** [comment]
Hi @tangochris ,

thanks for bringing up. One of our researchers ran into the same problem yesterday 😄 I linked both issues (the other one is internal cause it was directly opened for Rasa X, and will keep that one open until it's fixed 🎉

**Comment by gausie** [comment]
This is fixed in the 0.21.x branch
