### ISSUE TITLE
Rasa shell hangs forever on `/stop`

### ISSUE THREAD

**Issue by icaropires** [RasaHQ/rasa#4630]
**Rasa version**: 1.3.8

**Rasa X version** (if used & relevant):

**Python version**: 3.7.4

**Operating system** (windows, osx, ...): Fedora 30

**Issue**: The rasa shell hangs forever with the message `Killing Sanic server now`.

**Error (including full traceback)**:
```
(env) ✔︎ tmp (master) ✗ rasa shell
2019-10-17 16:37:42 INFO     root  - Connecting to channel 'cmdline' which was specified by the '--connector' argument. Any other channels will be ignored. To connect to all given channels, omit the '--connector' argument.
2019-10-17 16:37:42 INFO     root  - Starting Rasa server on http://localhost:5005
Bot loaded. Type a message and press enter (use '/stop' to exit): 
Your input ->  /stop                                                                                                                                   
2019-10-17 16:37:51 INFO     root  - Killing Sanic server now.
^C
```

**Command or request that led to error**:
Inside the rasa shell
```
/stop
```

**Content of configuration file (config.yml)** (if relevant):
```yml

```

**Content of domain file (domain.yml)** (if relevant):
```yml

```

I'd like to contribute if possible :smiley:

**Comment by sara-tagger** [comment]
Thanks for the issue, @Ghostvv will get back to you about it soon!

###### You may find help in the [docs](https://rasa.com/docs/) and the [forum,](https://forum.rasa.com/) too 🤗

**Comment by icaropires** [comment]
I found out that it just happen if you try to exit the shell without sending any messages :thinking:

**Comment by Ghostvv** [comment]
@wochinge @tabergma could you please comment on this

**Comment by wochinge** [comment]
@icaropires Thanks for the detailed error description. Would be down for tackling this issue yourself or should we add it our backlog?

**Comment by icaropires** [comment]
> @icaropires Thanks for the detailed error description. Would be down for tackling this issue yourself or should we add it our backlog?

@wochinge I'll tackle it

**Comment by wochinge** [comment]
Great news @icaropires ! Thanks a lot! Please let me know if you need any feedback / help 🙂

**Comment by icaropires** [comment]
@wochinge the PR is ready for review :wink:
