### ISSUE TITLE
hey i am trying to run this train_online.py(https://github.com/RasaHQ/rasa-workshop-pydata-berlin/blob/master/train_online.py) but I am getting error I am using rasa nlu - 0.15.1 rasa_core - 0.14.5 python 3.6.

### ISSUE THREAD

**Issue by sanchit892** [RasaHQ/rasa#4631]

**Comment by sara-tagger** [comment]
Thanks for the question, our Github issue board is for **bugs and feature requests only,** though 😕
Please ask this question in the [forum✨](https://forum.rasa.com/c/rasa)

###### If you were describing a bug, please create a [report](https://github.com/RasaHQ/rasa/issues/new?labels=bug&template=bug_report.md) and fill out the template
