### ISSUE TITLE
Forms: allow slots to be filled from entities present in the trigger intent

### ISSUE THREAD

**Issue by akelad** [RasaHQ/rasa#4644]
Currently, slots only get filled from entities that are present in the trigger intent if they have the same name as the slot. We should add an option that allows the user to fill a slot from any entity that is present in the trigger intent. This is similar to the `from_trigger_intent` option in `slot_mappings`: [https://rasa.com/docs/rasa/core/forms/#custom-slot-mappings](https://rasa.com/docs/rasa/core/forms/#custom-slot-mappings)

**Comment by ancalita** [comment]
With the changes brought in 3.x for slot mappings, it is now possible to explicitly specify which slots should be filled by which entities (outside forms too).
