### ISSUE TITLE
Deactivate Forms after Timeout

### ISSUE THREAD

**Issue by nikhilkapavarapu** [RasaHQ/rasa#4646]
My Complete functionality is based on FormActions.
My Requirement is whenever a form is in active state, if user doesn't respond within 10 minutes, then **automatically** bot should say "Session Timeout Happened" and form should be deactivated. 
Lets suppose think, if I enter "update case", bot will respond as "Please enter Case Number". If user doesnt enter any value within 10 minutes, in that case, the bot should automatically reply as "Timeout Happened" and should deactivate the form.
My Actions has following methods(required_slots,slot_mappings,slot_ask_messages,submit). 
Can anyone help me on how to implement this and in which method of FormAction, do we need to incorporate the changes ?

**Comment by sara-tagger** [comment]
Thanks for the question, our Github issue board is for **bugs and feature requests only,** though 😕
Please ask this question in the [forum✨](https://forum.rasa.com/c/rasa)

###### If you were describing a bug, please create a [report](https://github.com/RasaHQ/rasa/issues/new?labels=bug&template=bug_report.md) and fill out the template
