### ISSUE TITLE
ERROR: Could not find a version that satisfies the requirement rasa-sdk~=1.4.0

### ISSUE THREAD

**Issue by cclaudine** [RasaHQ/rasa#4651]
Python version: 3.5.2

Operating system: Linux (Ubuntu 16.4)

Issue: Running "pip3 install -r requirements-dev.txt" command gives error:

ERROR: Could not find a version that satisfies the requirement rasa-sdk~=1.4.0 (from -r alt_requirements/../requirements.txt (line 39)) (from versions: 1.0.0rc3, 1.0.0rc4, 1.0.0, 1.1.0, 1.1.1, 1.2.0, 1.3.0a1, 1.3.0, 1.3.1, 1.3.2, 1.3.3)
ERROR: No matching distribution found for rasa-sdk~=1.4.0 (from -r alt_requirements/../requirements.txt (line 39))

**Comment by sara-tagger** [comment]
Thanks for raising this issue, @amn41 will get back to you about it soon✨

###### Please also check out the [docs](https://rasa.com/docs/) and the [forum](https://forum.rasa.com/) in case your issue was raised there too 🤗

**Comment by erohmensing** [comment]
Thanks @cclaudine, you must have tried to download in between when we released rasa 1.4.0 and rasa-sdk 1.4.0. Should be fixed now, could you try again?

**Comment by erohmensing** [comment]
Closing as rasa-sdk 1.4.0 is released

Also, just to let you know, python 3.5 support was dropped in rasa 1.4.0: https://rasa.com/docs/rasa/changelog/#removed

**Comment by sanjayrjs16** [comment]
ERROR: Could not find a version that satisfies the requirement rasa-sdk~=1.4.0 (from -r requirements.txt (line 39)) (from versions: 1.0.0rc3, 1.0.0rc4, 1.0.0, 1.1.0, 1.1.1, 1.2.0, 1.3.0a1, 1.3.0, 1.3.1, 1.3.2, 1.3.3)
ERROR: No matching distribution found for rasa-sdk~=1.4.0 (from -r requirements.txt (line 39))


I still keep getting this error.
ubuntu 16.04
installed in a venv.

Please help.

**Comment by erohmensing** [comment]
@sanjayrjs16 what's your pip version?

**Comment by sanjayrjs16** [comment]
Hi,

On running whereis pip I get :+1: 
pip: /usr/local/bin/pip3.6 /usr/local/bin/pip

On running pip3 --version I get : 

pip3 --version
pip 19.3.1 from /home/sanjay/.local/lib/python3.5/site-packages/pip (python 3.5)

but pip --version says 
pip --version
bash: /home/sanjay/.local/bin/pip: No such file or directory


I am new to this , sounds stupid...But I can't get it figured out...

**Comment by erohmensing** [comment]
Hm, I can't get it figured out either, because even `pip3 install rasa-sdk==1.4.0` works fine for me 🤔
