### ISSUE TITLE
Unfeaturized slot type convert type of value to Single value.

### ISSUE THREAD

**Issue by DivyashaAgrawal** [RasaHQ/rasa#4652]
**Rasa version**: 0.14.3

**Rasa X version** (if used & relevant):

**Python version**: 3.6

**Operating system** (windows, osx, ...):Windows

**Issue**: I have slots which are supposed to take list as value and are unfeaturized. But during story they get converted to one single value.

Example:
domain.yml:

entities:
   - airline // this takes list value ["vistara", "indigo"]
slots:
 airline:
     type: unfeaturized

Story conversion:
* inform: {"airline": ["vistara", "indigo"],
- slot{"airline":  "indigo"}

**Comment by sara-tagger** [comment]
Thanks for the issue, @msamogh will get back to you about it soon!

###### You may find help in the [docs](https://rasa.com/docs/) and the [forum,](https://forum.rasa.com/) too 🤗

**Comment by msamogh** [comment]
Yes, this shouldn't happen.

**Comment by DivyashaAgrawal** [comment]
Transferred this [https://github.com/RasaHQ/rasa/issues/4660](url)

**Comment by DivyashaAgrawal** [comment]
Transferred this here: [https://github.com/RasaHQ/rasa/issues/](4660)
