### ISSUE TITLE
Some async tests are not properly run

### ISSUE THREAD

**Issue by erohmensing** [RasaHQ/rasa#4664]
5 asynchronous test methods are currently never awaited, so the tests pass pytest regardless of if the method itself should actually pass. Example: https://travis-ci.com/RasaHQ/rasa/jobs/248702574#L4028

In the case of slack, this might have been introduced during the change from `httpretty` to `responses`.

**Comment by tmbo** [comment]
mhm that is odd, usually this should be done through the https://github.com/yunstanford/pytest-sanic#quick-start plugin
