### ISSUE TITLE
Sometimes NLU requires retraining when domain file is changed

### ISSUE THREAD

**Issue by btotharye** [RasaHQ/rasa#4691]
**Issue**:
Branching off #4216 it has been brought up that changes to the domain file can lead to un-necessary retraining of the NLU data so need to investigate why changes to the domain file require retraining

Examples are changing of just the utterance leads to a retrain which should not occur

**Comment by DiegoProtec** [comment]
Something about #4659?

**Comment by btotharye** [comment]
so @wochinge it appears if there is a syntax issue in the domain file that the code at https://github.com/RasaHQ/rasa/blob/master/rasa/importers/rasa.py#L63 keeps the domain in an empty state and so this then at https://github.com/RasaHQ/rasa/blob/master/rasa/train.py#L84 which I believe causes the NLU training to be kicked off still investigating but this is what I'm seeing so far

**Comment by wochinge** [comment]
@btotharye In case the domain is empty (e.g. due to a syntax error as you pointed out) it runs into https://github.com/RasaHQ/rasa/blob/f472c195e06ee8c2db9f104f047f97eda77364b7/rasa/train.py#L100 and it's not checked if the nlu part changed. We have to add / reuse a check whether the nlu sections changed.

**Comment by akelad** [comment]
as we discussed, this is kind of expected. but @wochinge if there's a syntax error imo training should fail, and not just continue with training an NLU model instead.

**Comment by akelad** [comment]
@wochinge i guess this is still relevant?

**Comment by wochinge** [comment]
I think so, but should be re-validated after 2.0

**Comment by TyDunn** [comment]
Has this been re-validated?

**Comment by wochinge** [comment]
Will be fixed by the model architecture revamp
