### ISSUE TITLE
Rasa init shows traceback error on CTRL + C

### ISSUE THREAD

**Issue by jplpereira** [RasaHQ/rasa#4694]
**Rasa version**: 1.4.0

**Rasa X version** (if used & relevant):

**Python version**: 3.6.8

**Operating system** (windows, osx, ...): Ubuntu 18.04.3 LTS

**Issue**:

Rasa init shows traceback error on CTRL + C

**Error (including full traceback)**:
```
root@09ae8b4f9d96:/unb/gces/robot# rasa init
Welcome to Rasa! 🤖

To get started quickly, an initial project will be created.
If you need some help, check out the documentation at https://rasa.com/docs/rasa.
Now let's start! 👇🏽

? Please enter a path where the project will be created [default: current directory] .

Cancelled by user

Traceback (most recent call last):
  File "/usr/local/bin/rasa", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.6/dist-packages/rasa/__main__.py", line 76, in main
    cmdline_arguments.func(cmdline_arguments)
  File "/usr/local/lib/python3.6/dist-packages/rasa/cli/scaffold.py", line 186, in run
    if not os.path.isdir(path):
  File "/usr/lib/python3.6/genericpath.py", line 42, in isdir
    st = os.stat(s)
TypeError: stat: path should be string, bytes, os.PathLike or integer, not NoneType
root@09ae8b4f9d96:/unb/gces/robot#
```

**Command or request that led to error**:
```
rasa init
^C
```

**Content of configuration file (config.yml)** (if relevant):
```yml

```

**Content of domain file (domain.yml)** (if relevant):
```yml

```

**Comment by sara-tagger** [comment]
Thanks for raising this issue, @federicotdn will get back to you about it soon✨

###### Please also check out the [docs](https://rasa.com/docs/) and the [forum](https://forum.rasa.com/) in case your issue was raised there too 🤗

**Comment by jplpereira** [comment]
I already solved the bug. I'll send the PR for review soon.
