### ISSUE TITLE
 Inspecting data from the shell!

### ISSUE THREAD

**Issue by vsraptor** [RasaHQ/rasa#4695]
**Description of Problem**:

https://forum.rasa.com/t/inspecting-data-from-the-shell/20607

**Overview of the Solution**:

**Examples** (if relevant):

Would it be very hard to inspect original data from the shell. Let me give example :

> /show intent greet
 hi
 hello
 howdy
 ....

#pipe is grep
> /show i greet | he
hello

look in the forum for more ...
**Blockers** (if relevant):

**Definition of Done**:

**Comment by sara-tagger** [comment]
Thanks for submitting this feature request 🚀@amn41 will get back to you about it soon!✨

**Comment by amn41** [comment]
It sounds like you are suggesting to extend the `cli` command to add functionality for exploring training data. I'm not sure what this would add beyond opening a text editor and running control+F ?
