### ISSUE TITLE
Rasa - not has param event_broker for CustomTrackerStore

### ISSUE THREAD

**Issue by DiegoProtec** [RasaHQ/rasa#4698]
**Description of Problem**:
Im using the Rasa X 0.21.4, your default version Rasa is 1.3.9 that not has event_broker param.
I can't set event_brocker using Raxa X version 0.21.4.

**Overview of the Solution**:
Update version Rasa 1.4.1 to Rasa X 0.21.4.

**Examples** (if relevant):
I need to pass the param event_broker for CustromTrackerStore like [there](https://github.com/RasaHQ/rasa/blob/master/rasa/core/tracker_store.py#L71)

**Blockers** (if relevant):

**Definition of Done**:

**Comment by DiegoProtec** [comment]
Im using the Rasa X 0.21.4, your default version Rasa is 1.3.9 that not has event_broker param.

**Comment by sara-tagger** [comment]
Thanks for submitting this feature request 🚀@erohmensing will get back to you about it soon!✨

**Comment by erohmensing** [comment]
Hi @DiegoProtec, If you want to use rasa >=1.4.0, you should update to Rasa X >= 0.22.0. The rasa dependency of Rasa X 0.21.4 will not get updated.

**Comment by DiegoProtec** [comment]
Hi @erohmensing, the version 0.21.4 is installed when I dont especific it, where can I see the Rasa X latest version?

**Comment by erohmensing** [comment]
Ah no problem, the issue is that you have to pass the ``--upgrade`` flag to pip. e.g.
```
pip install -U rasa-x
``

**Comment by DiegoProtec** [comment]
@erohmensing Thank you so much!!!

**Comment by erohmensing** [comment]
Sure thing!
