### ISSUE TITLE
Run Rasa X on HTTPS

### ISSUE THREAD

**Issue by kapoorh** [RasaHQ/rasa#4703]
Hi,

I enable https of rasa core with the below command and rasa core is now running on HTTPS.

rasa run --ssl-certificate <.crt> --ssl-keyfile <.key> --enable-api -m models/

https://localhost:5005

But when I am trying to do the same stuff with rasa X 
rasa x --ssl-certificate <.crt> --ssl-keyfile <.key> 

then still its showing running on http://localhost:5002 not on HTTPS.

**Comment by erohmensing** [comment]
hi @kapoorh, running rasa x on SSL is currently only supported on Rasa X EE. https://rasa.com/docs/rasa-x/rasa-x-changelog/#id28

**Comment by amn41** [comment]
@kapoorh  check out step 9 here for how to put everything behind https https://rasa.com/docs/rasa-x/deploy/ - you just need to provide some certs. What @erohmensing says is right but that's only if you want SSL termination inside the container. In a normal Rasa X setup you have nginx acting as a proxy and that can hold your ssl certs

**Comment by kapoorh** [comment]
Hi @amn41 , @erohmensing ,
Thanks for the quick reply. And got your point to raise the same such type of questions on rasa forum and I did the same. https://forum.rasa.com/t/run-rasa-x-on-https/20680

I want to run rasa x on https without docker.

**Comment by amn41** [comment]
you can do this without docker, but you will still have to run a proxy server in front of rasa x to do the ssl termination. Rasa X CE doesn't handle SSL certs

**Comment by kapoorh** [comment]
Thanks Alan!!
I think this feature should be in Rasa X CE version as well :)
