### ISSUE TITLE
default intents should not raise undefined parsing error

### ISSUE THREAD

**Issue by erohmensing** [RasaHQ/rasa#4710]
these aren't defined in the domain, but they are valid intents, and should not log an error. In addition, I think if you add default intents to your domain it might actually break things... (unconfirmed)
```
Your input ->  /restart
2019-11-01 11:50:14 WARNING  rasa.core.processor  - Interpreter parsed an intent 'restart' that is not defined in the domain.
Your input ->  /back
2019-11-01 11:50:32 WARNING  rasa.core.processor  - Interpreter parsed an intent 'back' that is not defined in the domain.
Your input ->
```

**Comment by shubham3582** [comment]
Hi @erohmensing , following function in rasa/core/processor.py contains this feature.

1. These are valid intents but rasa shows them as warnings. If any developer forget them to add in domain.yml. I suggest it should be there, its very helpful specially in the last moment.

2. If you add default intents to your domain.yml, it didn't break things.

 `def _log_unseen_intent(self, parse_data: Dict[Text, Any]) -> None:
        """check if the NLU picks up intent that aren't in the domain.
        """
        intent = parse_data["intent"]["name"]
        if intent and self.domain and intent not in self.domain.intents:
            logger.warning(
                "Interpreter parsed an intent '{}' "
                "that is not defined in the domain.".format(intent)`

**Comment by erohmensing** [comment]
My suggestion here is that you _shouldn't_ have to add the valid default intents to the domain in order to get them to work (this is the case right now). So it would be nice if `_log_unseen_intent` would take those intents (e.g.`restart`, `back`) into account as well as those in `self.domain.intents`.

**Comment by shubham3582** [comment]
This can be taken care of in the code.

**Comment by erohmensing** [comment]
Would love for you to contribute a PR for it!
