### ISSUE TITLE
template processing for facebook channel 

### ISSUE THREAD

**Issue by tschnoelzer** [RasaHQ/rasa#4712]
**Rasa version**: Rasa 1.4.0

**Python version**: Python 3.7.3

**Operating system** (windows, osx, ...): MacOS

**Issue**: template generator in facebook.py is not taking into account, that field "buttons" in list of "elements" is optional.

**Error (including full traceback)**:
```
    await output_channel.send_response(tracker.sender_id, e.message())
  File "/Users/tschnoelzer/Documents/development/CmbEnterprise/venv/lib/python3.7/site-packages/rasa/core/channels/channel.py", line 200, in send_response
    await self.send_elements(recipient_id, message.pop("elements"), **message)
  File "/Users/tschnoelzer/Documents/development/CmbEnterprise/venv/lib/python3.7/site-packages/rasa/core/channels/facebook.py", line 212, in send_elements
    self._add_postback_info(element["buttons"])
KeyError: 'buttons'
```

**Command or request that led to error**:
```
in Domain.yml:

utter_goodbye:
      - custom:
        elements:
          - title: "demotitle"
            subtitle: "hi for everyone."
```

The cause is identified in facebook.py as the iterator tries to loop a null value variable.

```
async def send_elements(
        self, recipient_id: Text, elements: Iterable[Dict[Text, Any]], **kwargs: Any
    ) -> None:
        """Sends elements to the output."""

        for element in elements:
                self._add_postback_info(element["buttons"])

        payload = {
            "attachment": {
                "type": "template",
                "payload": {"template_type": "generic", "elements": elements},
            }
        }
        self.messenger_client.send(payload, recipient_id, "RESPONSE")
```

My knowledge concerning python is still limited, I suggest to add the condition ```if "buttons" in element:``` as follows:

```
async def send_elements(
        self, recipient_id: Text, elements: Iterable[Dict[Text, Any]], **kwargs: Any
    ) -> None:
        """Sends elements to the output."""

        for element in elements:
            if "buttons" in element:
                self._add_postback_info(element["buttons"])

        payload = {
            "attachment": {
                "type": "template",
                "payload": {"template_type": "generic", "elements": elements},
            }
        }
        self.messenger_client.send(payload, recipient_id, "RESPONSE")
``` 

This is tested with condition added and working against my template now. The other optional elements like subtitle, default_action and image_url were untouched and working as expected.

best

Timo

**Comment by sara-tagger** [comment]
Thanks for raising this issue, @wochinge will get back to you about it soon✨

###### Please also check out the [docs](https://rasa.com/docs/) and the [forum](https://forum.rasa.com/) in case your issue was raised there too 🤗

**Comment by wochinge** [comment]
Thanks for the detailed error description! `element.get("buttons")`  should also fix it. Would you mind doing a PR with a fix? That would be great 🎉
