### ISSUE TITLE
Support for withLatent duckling option

### ISSUE THREAD

**Issue by llermaly** [RasaHQ/rasa#4716]
**Description of Problem**:

withLatent option in duckling (search for latent dates) comes disabled by default

**Overview of the Solution**:

Add withLatent option to duckling pipeline configuration

**Examples** (if relevant):

search for '2019' doesnt work search for 'in 2019' grabs the date duckling website grabs the date without the "in" because uses the old version of duckling

Thanks

**Comment by sara-tagger** [comment]
Thanks for submitting this feature request 🚀@btotharye will get back to you about it soon!✨

**Comment by btotharye** [comment]
hey @llermaly do you mind sharing more info around how you have your training data setup for this as well so I can confirm a few things before I add this to our list.

I just mainly want to reproduce this and have some information to supply with the issue.

Thanks

**Comment by llermaly** [comment]
Hello @btotharye , this are the files I'm using : 

https://gist.github.com/llermaly/2593545187b6478694be54aad1d579d3

What I did was to download and compile duckling and change the withLatent value to True in the Time/Types.hs file : 

https://github.com/facebook/duckling/blob/master/Duckling/Time/Types.hs

Would be nice to have this option in the pipeline or duckling container itself.

Regards

**Comment by btotharye** [comment]
ok thanks yea I'm testing out a few things and seeing what we can do for that.

**Comment by btotharye** [comment]
so @llermaly this would require us updating our fork we use which I'm working on and after that would then require the customization you are talking about.  Would you be up for tackling that after we get the repo updated to support the `withLatent` option?

**Comment by llermaly** [comment]
@btotharye sure, I'm glad to help in all I can. This project is finishing soon so I hope to hear news from you before it finishes

**Comment by btotharye** [comment]
@llermaly I have a PR in now to update our duckling, once that happens you should be good to go to work on this.

**Comment by btotharye** [comment]
@llermaly this should be ready for you to look at now
