### ISSUE TITLE
Flatten my .md file !!

### ISSUE THREAD

**Issue by vsraptor** [RasaHQ/rasa#4719]
**Rasa version**: 1.3.9

**Rasa X version** (if used & relevant): 
how do I get it ?

**Python version**:
3.6
**Operating system** (windows, osx, ...):
linux
**Issue**:

Let say I have  retrevial-response .md intent file : 

```

## intent: faq/basic_syntax+identifier
- what is Python identifier ?
- what is identifier

## intent: faq/basic_syntax+identifier_format
- what is the format of identifier ?
- how do you format python identifier

....
```

It seems that when I do something (dont know exactly what ) in RasaX it flattens my .md file !!?
It also reorders my nlu.md file !?!? makes it harder finding stuff
```
## intent: faq
- what is Python identifier ?
- what is identifier
- what is the format of identifier ?
- how do you format python identifier
....
```

**Error (including full traceback)**:
```

```

**Command or request that led to error**:
```

```

**Content of configuration file (config.yml)** (if relevant):
```yml

```

**Content of domain file (domain.yml)** (if relevant):
```yml

```

**Comment by sara-tagger** [comment]
Thanks for the issue, @Ghostvv will get back to you about it soon!

###### You may find help in the [docs](https://rasa.com/docs/) and the [forum,](https://forum.rasa.com/) too 🤗

**Comment by Ghostvv** [comment]
Thank you for raising the issue, unfortunately response selector format is not yet supported by rasa-x

**Comment by vsraptor** [comment]
i see ... but the nlu file for response selector have the same format ... it looks like a problem with the complex intent on the surface !!

`## intent: faq/basic_syntax+identifier_format`

**Comment by Ghostvv** [comment]
the problem is with response selector id after intent, rasa-x doesn't support printing it yet

**Comment by tmbo** [comment]
It's not a bug, will be implemented when supporting response selector as a feature in Rasa X
