### ISSUE TITLE
Mattermost request not being parsed.  Error: raise InvalidUsage("Failed when parsing body as json")

### ISSUE THREAD

**Issue by sarmilaupadhyaya** [RasaHQ/rasa#4720]
I am trying to add matter most as the bot platform for RASA. Meanwhile, my request from matter most is 

b'channel_id=channelid&channel_name=channelname&file_ids=&post_id=postid&team_domain=name&team_id=team-id&text=%40testbot++hello&timestamp=1572845451&token=token-id&trigger_word=&user_id=user-id&user_name=username'

And Iam getting error:

![image](https://user-images.githubusercontent.com/8464924/68101388-85fe7800-fef5-11e9-8720-18bc8bbe0250.png)

My matter most version is:  5.15.1

**Comment by sara-tagger** [comment]
Thanks for the question, our Github issue board is for **bugs and feature requests only,** though 😕
Please ask this question in the [forum✨](https://forum.rasa.com/c/rasa)

###### If you were describing a bug, please create a [report](https://github.com/RasaHQ/rasa/issues/new?labels=bug&template=bug_report.md) and fill out the template.
