### ISSUE TITLE
Cannot train initial Rasa model. Please provide NLU and Core data using the '--data' argument.

### ISSUE THREAD

**Issue by harini1191** [RasaHQ/rasa#4723]
hi 
my rasa model is not working and throwing the error 
Cannot train initial Rasa model. Please provide NLU and Core data using the '--data' argument

**Comment by sara-tagger** [comment]
Thanks for the question, our Github issue board is for **bugs and feature requests only,** though 😕
Please ask this question in the [forum✨](https://forum.rasa.com/c/rasa)

###### If you were describing a bug, please create a [report](https://github.com/RasaHQ/rasa/issues/new?labels=bug&template=bug_report.md) and fill out the template.
