### ISSUE TITLE
nlu/story file detection (regex)

### ISSUE THREAD

**Issue by IzidoroBaltazar** [RasaHQ/rasa#4731]
**Rasa version**:
1.4.3

**Rasa X version** (if used & relevant):

**Python version**:
3.6
**Operating system** (windows, osx, ...):
linux

**Issue**:
When rasa decides whether given file is NLU or story file, it uses newly introduced regex.
file: `rasa/nlu/training_data/loading.py`
```
54 _nlg_markdown_marker_regex = re.compile(r"##\s*.*\n\*.*\/.*\n\s*\t*\-.*")
...
143 def _is_nlg_story_format(content: Text) -> bool:
144
145     match = re.search(_nlg_markdown_marker_regex, content)
146     if match:
147         return True
```
This regex incorrectly detects some files as NLU instead of story.

This behavior is unfortunate. I would prefer to decide whether file is story or NLU based on the folder structure, name or some other `explicit` identifier. It came as a big surprise that rasa decides on each file whether it is story or NLU.

**Error (including full traceback)**:
Story file below is incorrectly classified as NLU file.
```
## menu only one url link
* url_link{"url_link": "example-url.com/static"}
    - action_listen
```

**Command or request that led to error**:
```
rasa data validate
rasa train
```

**Content of configuration file (config.yml)** (if relevant):
```yml

```

**Content of domain file (domain.yml)** (if relevant):
```yml

```

**Comment by sara-tagger** [comment]
Thanks for raising this issue, @btotharye will get back to you about it soon✨

###### Please also check out the [docs](https://rasa.com/docs/) and the [forum](https://forum.rasa.com/) in case your issue was raised there too 🤗

**Comment by btotharye** [comment]
@IzidoroBaltazar we have made quite a few improvements since the version you found this in, do you mind testing this on the newer releases?

**Comment by IzidoroBaltazar** [comment]
It works now. Story files is correctly identified.
