### ISSUE TITLE
Error: Requested URL /socket.io/ not found

### ISSUE THREAD

**Issue by saravananselvamohan** [RasaHQ/rasa#4747]
While running rasa run command it's giving me the following error

....line 470, in _get     raise NotFound("Requested URL {} not found".format(url)) sanic.exceptions.NotFound: Requested URL /socket.io/ not found

**Comment by sara-tagger** [comment]
Thanks for the question, our Github issue board is for **bugs and feature requests only,** though 😕
Please ask this question in the [forum✨](https://forum.rasa.com/c/rasa)

###### If you were describing a bug, please create a [report](https://github.com/RasaHQ/rasa/issues/new?labels=bug&template=bug_report.md) and fill out the template.
