### ISSUE TITLE
Internal Server error 500 Training from Rasa X UI - version 0.22.2

### ISSUE THREAD

**Issue by kapoorh** [RasaHQ/rasa#4749]
Hi,

I have update a Rasa X version to latest (0.22.2), so when i am doing training from Rasa X UI then after sometime below error is coming:

**{"version":"0.22.2","status":"failure","message":"Failed to train a Rasa model.","reason":"StackTrainingFailed","details":{"args":["500, Internal Server Error, body='b'{\"version\":\"1.4.3\",\"status\":\"failure\",\"message\":\"An unexpected error occurred during training. Error: [Errno 5] Input\\\\\/output error\",\"reason\":\"TrainingError\",\"details\":{},\"help\":null,\"code\":500}''"],"message":"Internal Server Error","status":500,"text":"{\"version\":\"1.4.3\",\"status\":\"failure\",\"message\":\"An unexpected error occurred during training. Error: [Errno 5] Input\\\/output error\",\"reason\":\"TrainingError\",\"details\":{},\"help\":null,\"code\":500}"},"help":null,"code":500}**

while from command line **"rasa train"** is working fine.

**Comment by sara-tagger** [comment]
Thanks for raising this issue, @Ghostvv will get back to you about it soon✨

###### Please also check out the [docs](https://rasa.com/docs/) and the [forum](https://forum.rasa.com/) in case your issue was raised there too 🤗

**Comment by kapoorh** [comment]
I created new project then its working fine. May be on older project after upgrading the version its not taking it up.

**Comment by kapoorh** [comment]
Hi @Ghostvv ,

Yesterday, It was working but today again I am facing an issue:

**{"version":"0.22.2","status":"failure","message":"Failed to train a Rasa model.","reason":"StackTrainingFailed","details":{"args":["500, Internal Server Error, body='b'{\"version\":\"1.4.3\",\"status\":\"failure\",\"message\":\"An unexpected error occurred during training. Error: [Errno 5] Input\\\\\/output error\",\"reason\":\"TrainingError\",\"details\":{},\"help\":null,\"code\":500}''"],"message":"Internal Server Error","status":500,"text":"{\"version\":\"1.4.3\",\"status\":\"failure\",\"message\":\"An unexpected error occurred during training. Error: [Errno 5] Input\\\/output error\",\"reason\":\"TrainingError\",\"details\":{},\"help\":null,\"code\":500}"},"help":null,"code":500}**

I run the following command:
rasa x --enable-api &

and while doing the training from UI the above error is coming. when I am doing from backend training is working fine but taking a time approx 12 mins for 107 intents with 2227 examples.

**Comment by wochinge** [comment]
Hi @kapoorh ,

do you please share the output of the rasa logs with us? Thanks 🙏

**Comment by kapoorh** [comment]
I am just running rasa x from command line in the background, not in docker.

I noticed one thing this error comes if I don't run rasa core. So in brief if i run the below commands then it works fine
1. rasa run --enable-api &
2. rasa x &
but in this Newly model doesn't reflect as an active model from Rasa X UI.

and If I run only
1. rasa x &
then it throws an error.

**Comment by wochinge** [comment]
> I am just running rasa x from command line in the background, not in docker.

Can you please run it in the foreground and share the logs of that? :-) 

> I noticed one thing this error comes if I don't run rasa core

What do you mean with "run rasa core"

**Comment by kapoorh** [comment]
Hi @wochinge ,

Foreground error:
ERROR rasax.community.api.blueprints.models

{"version":"0.22.2","status":"failure","message":"Failed to train a Rasa model.","reason":"StackTrainingFailed","details":{"args":["500, Internal Server Error, body='b'{"version":"1.4.3","status":"failure","message":"An unexpected error occurred during training. Error: [Errno 5] Input\\/output error","reason":"TrainingError","details":{},"help":null,"code":500}''"],"message":"Internal Server Error","status":500,"text":"{"version":"1.4.3","status":"failure","message":"An unexpected error occurred during training. Error: [Errno 5] Input\/output error","reason":"TrainingError","details":{},"help":null,"code":500}"},"help":null,"code":500}

2. run rasa core means - run rasa server with : rasa run --enable-api

**Comment by wochinge** [comment]
@kapoorh Do you see `rasa` training logs in your output? Is there any further error? In which environment are you running? Do you get the same error when you do it in a clean directory with a bot trained on the data from `rasa init`?

**Comment by kapoorh** [comment]
Yes the above mentioned error came. Right now, i am running all three commands in this format:
1. rasa run --enable-api &
2. rasa run -m models --enable-api --log-file rasalogs.log --endpoints endpoints.yml actions &
3. rasa x &

but with this after training, I must kill the session of rasa run from backend and again start. Nothing happened if I make new model as active from Rasa UI.

**Comment by wochinge** [comment]
Can you please run `rasa run --enable-api` without sending it to the background and check the logs?

**Comment by kapoorh** [comment]
Sorry I couldn't check this. I will update you..

**Comment by kapoorh** [comment]
closing this incident

**Comment by rashmimetri** [comment]
How was this resolved? @kapoorh

**Comment by kapoorh** [comment]
Hi @rashmimetri ,

Instead of updating the rasa version into the same project, I created new project and trained the model.

Thanks and Regards
Harsh

**Comment by rashmimetri** [comment]
> Hi @rashmimetri ,
> 
> Instead of updating the rasa version into the same project, I created new project and trained the model.
> 
> Thanks and Regards
> Harsh

Thank you.. Will try it

**Comment by wochinge** [comment]
What was your log trace @kapoorh ? Which version of Rasa Open Source were you using?

**Comment by kapoorh** [comment]
Hi @wochinge ,

The issue was with older version of Rasa X 0.22.2. Now I am not facing any issue.

Thanks and Regards
Harsh

**Comment by rabinpoudyal** [comment]
seems shortage of resources is the issue. It still persists

**Comment by wochinge** [comment]
@rabinpoudyal Can you please create a new issue with a detailed error description? Thanks 🙌
