### ISSUE TITLE
Improve Training Time 

### ISSUE THREAD

**Issue by kapoorh** [RasaHQ/rasa#4753]
Hi,

When I was using < 1 rasa version then training time was good. for approx 107 intents with 2231 examples it was taking 1-2 mins to complete the training. Now I have upgrade the version with the latest one 1.4.3 and now it takes 10-12 mins for the same data set.

In both the versions I am using pipeline: supervised_embeddings.

Thanks,
Harsh

**Comment by sara-tagger** [comment]
Thanks for submitting this feature request 🚀@akelad will get back to you about it soon!✨

**Comment by akelad** [comment]
@Ghostvv do you have any comments on that?

**Comment by kapoorh** [comment]
@akelad, @Ghostvv : NLU training takes a time.

**Comment by Ghostvv** [comment]
we updated standard pipeline to include char ngrams, which drastically increases feature space and therefore training time

**Comment by kapoorh** [comment]
@Ghostvv : I am afraid now, we are increasing our intents and use cases day to day, then training time will also increase. And because of this when I do training from Rasa X UI then it hangs all the window while doing training. Even user cant do conversation with the bot.

I think performance shouldn't be degrade with the new releases.

**Comment by Ghostvv** [comment]
you can try the old config:
```
pipeline:
- name: WhitespaceTokenizer
- name: RegexFeaturizer
- name: CRFEntityExtractor
- name: EntitySynonymMapper
- name: CountVectorsFeaturizer
- name: EmbeddingIntentClassifier
```

with the ever increasing complexity of the architectures training time will keep increasing. Even if you keep the old architecture, with new data arriving, the training time will increase anyhow. It is a better practice to train your models separately from production system

**Comment by akelad** [comment]
@kapoorh training happens on a separate container with Rasa X, it shouldn't block users from talking to the bot
