### ISSUE TITLE
make Rasa Open Source response timeout configurable

### ISSUE THREAD

**Issue by xyzdcgan** [RasaHQ/rasa#4756]
Hello, 

I am using RASA NLU in local instance. 

I am currently training the model for 15000 questions and 500 intent.
After 1 hour of training it displays the error :- 

"
Training NLU model...
2019-11-12 16:33:06 ERROR    sanic.root  - Exception occurred while handling uri:
'http://localhost:5002/api/projects/default/models/jobs'
NoneType: None
"
My current PC configuration is 16 GB ram and i5 7th gen.

I tried with 7000 question and 80 intent and for that it was working without any error

**Comment by sara-tagger** [comment]
Thanks for raising this issue, @akelad will get back to you about it soon✨

###### Please also check out the [docs](https://rasa.com/docs/) and the [forum](https://forum.rasa.com/) in case your issue was raised there too 🤗

**Comment by akelad** [comment]
@xyzdcgan what command did you use for training?

**Comment by xyzdcgan** [comment]
@akelad I trained the model using the train button in ui. 

![Screenshot from 2019-11-18 11-18-51](https://user-images.githubusercontent.com/44637302/69027681-ca117280-09f5-11ea-91d4-7f22b4c43ac4.png)

Update: Currently i am able to train with 425 intent but with only 3000, 
But it failed when i trained with 425 intent and 4500 question. 

I am generating question using: https://rodrigopivi.github.io/Chatito/

**Comment by akelad** [comment]
I assume the server times out after an hour - we have a default timeout hour of one hour: https://github.com/RasaHQ/rasa/blob/ff0848419d780b042bf2aa14f932fe1a2050f5ea/rasa/constants.py#L13
@wochinge do you know if that's configurable?

**Comment by wochinge** [comment]
We have to make this line configurable https://github.com/RasaHQ/rasa/blob/8c176f22709bb3996da2b454a7200a396d2ed5e8/rasa/server.py#L382

**Comment by mmalhotra** [comment]
#5358
