### ISSUE TITLE
FileEventProducer

### ISSUE THREAD

**Issue by rgstephens** [RasaHQ/rasa#4764]
**Description of Problem**:
This is a follow-up to a forum [discussion](https://www.notion.so/rasa/Project-List-05655e5517fd40bab443e10408c95fe7#79d192996f964738902043a12c7ecd18) between @ricwo and me. I would like to send the conversation tracker log to a file that can be consumed by other tools. In my case, I want to forward the conversation data to the ELK stack via Filebeat/Logstash to present a Kibana dashboard showing Rasa bot activity.

Rasa supports only a single event broker and under Rasa X that is used for a RabbitMQ broker.

**Overview of the Solution**:
Create a new `FileEventProducer` end point which would be defined in `endpoints.yml` like this:

```
file_producer:
  filename: "tracker_log.json"
```

**Examples** (if relevant):
I can show a sample Kibana dashboard offline

**Definition of Done**:
- [ ] Tests are added
- [ ] Feature described the docs
- [ ] Feature mentioned in the changlog

**Comment by amn41** [comment]
cc @tmbo

**Comment by ricwo** [comment]
@rgstephens Logstash has a [RabbitMQ plugin](https://www.elastic.co/guide/en/logstash/current/plugins-inputs-rabbitmq.html). for this to work, we'd have to be able to publish to multiple queues in the Pika producer. That would be a more lightweight solution than the file-based event broker _and_ the ability to publish to multiple event brokers. Have you explored the RabbitMQ plugin yet?

what exactly would be the use case for an event broker for filebeat? filebeat also has a rabbitMQ module but I'm not exactly sure which logs you had in mind

**Comment by rgstephens** [comment]
The use case is someone who is using Rasa X and also wants the Rasa tracker events sent to a file for further processing. Maybe consumed by filebeat/logstash on to Kibana. Or, read by Sumo Logic, Splunk and Tableau.

**Comment by ricwo** [comment]
Right, but most of these tools have a RabbitMQ integration, so I'm not sure there's a need for a file broker in the first instance
