### ISSUE TITLE
Rasa X: Buttons shaped like fish

### ISSUE THREAD

**Issue by tangochris** [RasaHQ/rasa#4769]
**Rasa version**: 1.4.4

**Rasa X version**: 0.22.1

**Issue**: Multiple buttons squish together and form a rather pleasing fish-like shape. Please add a new configuration option, e.g. `MAKE_BUTTONS_LOOK_LIKE_FISH: false;`

**Error (including full traceback)**:

# Clownfish
![Screen Shot 2019-11-13 at 12 16 41 PM](https://user-images.githubusercontent.com/19203848/68801191-67446380-0610-11ea-8d3f-46a9b43a7750.png)

# Swordfish
![a926986a3611eb1dfe244a16d52929d790b7b8a8](https://user-images.githubusercontent.com/19203848/68801245-8a6f1300-0610-11ea-9e34-a25d038de4ca.png)

# Boxfish
![Screen Shot 2019-11-13 at 12 26 03 PM](https://user-images.githubusercontent.com/19203848/68801369-d3bf6280-0610-11ea-87af-8947c5f179d1.png)

**Command or request that led to error**: Any message with multiple buttons

**Comment by sara-tagger** [comment]
Thanks for raising this issue about Rasa X 🔧@Saladdin will get back to you about it soon!

###### In the meantime, you may find some useful information in the [Rasa X docs](https://rasa.com/docs/rasa-x/) or by searching our [forum](https://forum.rasa.com/c/rasa-x) 😊

**Comment by Saladdin** [comment]
Hey @tangochris! I can't help but admire your skill 😃You have my respect 🙇 
We are actually already working on a fix for this issue, I will get back to you once a patch is available.

**Comment by Saladdin** [comment]
The bug is fixed in Rasa X 0.23  👍
