### ISSUE TITLE
#Rasa My model is not saving my training in stories in interactive learning

### ISSUE THREAD

**Issue by ihtisham0331** [RasaHQ/rasa#4772]
I am developing rasa chatbot but the issue is that when I trained my model it is not saving my training in  stories.When i press 0 to export the conversation and quit it did not save the model

**Comment by sara-tagger** [comment]
Thanks for the question, our Github issue board is for **bugs and feature requests only,** though 😕
Please ask this question in the [forum✨](https://forum.rasa.com/c/rasa)

###### If you were describing a bug, please create a [report](https://github.com/RasaHQ/rasa/issues/new?labels=bug&template=bug_report.md) and fill out the template.
