### ISSUE TITLE
Rasa X add ability to set training parameters

### ISSUE THREAD

**Issue by andrew-tangowork** [RasaHQ/rasa#4775]
**Description of Problem**:
Our team is running our Rasa files from docker on AWS. I would like to be able to set augmentation to 0 but can't without connecting to docker container and I am assuming that the train button just runs a default 'rasa train' on the cli. 

**Overview of the Solution**:
Make a file that holds the arguments that you want run with rasa train. It could be in a yml or md format or JS, and support multiple named argument lines

From a UI perspective it could be either a similar approach to models where you just mark the line you want run when you click the train button. 

The other I see could add a second quick element. Maybe a small dropdown box that has a named variable of the arguments and you can select a tickbox of the one you want run. It could be toggled from a small icon like a gear (settings) and put around or beside the train button. Though a tab would work fine too.

If none are set it would continue to use the default currently used. 'rasa train'

**Comment by sara-tagger** [comment]
Thanks for submitting this feature request 🚀@tabergma will get back to you about it soon!✨

**Comment by tabergma** [comment]
@federicotdn What do you think about this?

**Comment by federicotdn** [comment]
I think this is a question @TyDunn could answer better, but it definitely sounds like a useful features to have (we would need to update the `/model/train` endpoint of Rasa so that it accepts an `augmentation` parameter).
