### ISSUE TITLE
Inspecting data from the shell!

### ISSUE THREAD

**Issue by vsraptor** [RasaHQ/rasa#4776]
**Description of Problem**:

https://forum.rasa.com/t/inspecting-data-from-the-shell/20607

**Overview of the Solution**:

Would it be very hard to inspect original data from the shell.
Let me give example : 

    > /show intent greet
     hi
     hello
     howdy
     ....

    #pipe is grep
    > /show i greet | he
    hello

    #!  greps the story name i.e. matches "happy path"
    >/show story !happy 
    * greet
      - utter_greet
    .....

    #show story ..
    >/s s sad
    ...

    #show 
    >/s utter !bye
    Bye

    #and now for the most important ...resolving some stuff
    >?show story !happy
    * hello
      - Hey! how are you?
    * fine
      - Great, carry on !

you get the gist .....

here is quick example :
(I'm slurping the files into arrays)

[shell_cmds.py|attachment](upload://y1L5sJJnj8GxUas55nD8bdDSlAt.py) (2.3 KB) 

    In [72]:  from shell_cmds import *

    In [73]: c = ShellCmds('nlu.md','stories.md','../domain.yml')

    In [74]: print c.find_utter('example')
    (63, '  utter_example:\n')

    In [75]: print c.show_utter('example')
      utter_example:
      - text: "example : {etype}"

    In [80]: print c.show_story('code example')
    ## code example
    * example
     - action_example
    * explain
     - utter_explain
    * gotit
     - utter_gotit

    In [78]: print c.show_story('code example', resolve=True)
    ## code example
    * example
     - action_example
    * explain
     - "explain : {etype}" 
    * gotit
     - "gotit : {etype}"

    In [79]: print c.show_intent('example')
    ## intent: example
    - [assign](etype) example
    - [sum](etype) example
    - [multiplication](etype) example
    - [conditional](etype)
    - [loop](etype) example
    - [eqvseq2](etype) example
    - show me [assignment](etype:assign) example
    - can you tell me [loop](etype) example
    - do you have [sum](etype) code example
    - i'm looking for code example of [assignment](etype:assign)

    In [81]: c.grep('domain', 'howdy')
    Out[81]: [[34, '  - text: howdy !\n']]

    In [83]: print c.show_intent('greet')
    ## intent:greet
    - hey
    - hello
    - hi
    - good morning
    - good evening
    - hey there
    - howdy

    In [84]: print c.show_intent('greet', 'h')
    - hey
    - hello
    - hi
    - hey there
    - howdy
**Examples** (if relevant):

**Blockers** (if relevant):

**Definition of Done**:

**Comment by sara-tagger** [comment]
Thanks for submitting this feature request 🚀@JustinaPetr will get back to you about it soon!✨

**Comment by erohmensing** [comment]
Hi @vsraptor, please do not create duplicate issues. Your last issue https://github.com/RasaHQ/rasa/issues/4695 is awaiting your response to a question, please continue the discussion there if you want to follow up with this enhancement request.
