### ISSUE TITLE
Can't install tensorflow v1.15.0 from requirements.txt

### ISSUE THREAD

**Issue by mrjazz** [RasaHQ/rasa#4782]
```
Collecting tensorflow~=1.15.0 (from rasa==1.5.0a1)
  Could not find a version that satisfies the requirement tensorflow~=1.15.0 (from rasa==1.5.0a1) (from versions: 0.12.1, 1.0.0, 1.0.1, 1.1.0rc0, 1.1.0rc1, 1.1.0rc2, 1.1.0, 1.2.0rc0, 1.2.0rc1, 1.2.0rc2, 1.2.0, 1.2.1, 1.3.0rc0, 1.3.0rc1, 1.3.0rc2, 1.3.0, 1.4.0rc0, 1.4.0rc1, 1.4.0, 1.4.1, 1.5.0rc0, 1.5.0rc1, 1.5.0, 1.5.1, 1.6.0rc0, 1.6.0rc1, 1.6.0, 1.7.0rc0, 1.7.0rc1, 1.7.0, 1.7.1, 1.8.0rc0, 1.8.0rc1, 1.8.0, 1.9.0rc0, 1.9.0rc1, 1.9.0rc2, 1.9.0, 1.10.0rc0, 1.10.0rc1, 1.10.0, 1.10.1, 1.11.0rc0, 1.11.0rc1, 1.11.0rc2, 1.11.0, 1.12.0rc0, 1.12.0rc1, 1.12.0rc2, 1.12.0, 1.12.2, 1.12.3, 1.13.0rc0, 1.13.0rc1, 1.13.0rc2, 1.13.1, 1.13.2, 1.14.0rc0, 1.14.0rc1, 1.14.0, 2.0.0a0, 2.0.0b0, 2.0.0b1)
```

**Comment by danielsouzat** [comment]
Which is your pip version?

TensorFlow from > 1.15 changed to "manylinux2010" tag and does requires pip > 19.0 
https://www.python.org/dev/peps/pep-0571/

**Comment by AmalM7** [comment]
I have the same error using python 3.7.3 and upgrading the pip to pip==19.3.1, How I could fix this issue.

ERROR: Could not find a version that satisfies the requirement tensorflow~=1.15.0 (from rasa) (from versions: none)
ERROR: No matching distribution found for tensorflow~=1.15.0 (from rasa)

**Comment by amarflybot18** [comment]
pip 9.0.1 from /usr/lib/python3/dist-packages (python 3.7)
Python 3.7.5

Error:
Collecting tensorflow~=1.15.0 (from rasa)
  Could not find a version that satisfies the requirement tensorflow~=1.15.0 (from rasa) (from versions: 1.13.0rc1, 1.13.0rc2, 1.13.1, 1.13.2, 1.14.0rc0, 1.14.0rc1, 1.14.0, 2.0.0a0, 2.0.0b0, 2.0.0b1)
No matching distribution found for tensorflow~=1.15.0 (from rasa)

**Comment by amarflybot18** [comment]
Got this working!
```
sudo curl https://bootstrap.pypa.io/get-pip.py -o get-pip.py
python3 get-pip.py
```

Installing collected packages: pip
  Found existing installation: pip 9.0.1
    Uninstalling pip-9.0.1:
      Successfully uninstalled pip-9.0.1
Successfully installed pip-19.3.1

**Comment by AmalM7** [comment]
Thank you for you reply @amarflybot18 I have installed pip-19.3.1 but I still have the same Error.

**Comment by amarflybot18** [comment]
Whats your version of python?

**Comment by danielsouzat** [comment]
You can upgrade PIP by removing the system python-package and then running:
`sudo python3 -m pip install --upgrade pip`

You can install it locally with "--user" but the system wide installation for PIP is the recommended AFAIK.

@AmalM7 can you run: `pip --version` just to be sure about it?

**Comment by amarflybot18** [comment]
I have pip and pip3 both, But here I have used pip3.

**Comment by danielsouzat** [comment]
Me too @amarflybot18. It have to be pip3 cause rasa requires Python 3.6/3.7. That may be your problem @AmalM7 .

**Comment by AmalM7** [comment]
after running pip --version :  pip 19.3.1 from c:\users\asus\my-venv\lib\site-packages\pip (python 3.7)

**Comment by sara-tagger** [comment]
Thanks for the question, our Github issue board is for **bugs and feature requests only,** though 😕
Please ask this question in the [forum✨](https://forum.rasa.com/c/rasa)

###### If you were describing a bug, please create a [report](https://github.com/RasaHQ/rasa/issues/new?labels=bug&template=bug_report.md) and fill out the template.

**Comment by mrjazz** [comment]
Thanks @amarflybot18. The issue was in pip 9.0.1. It works.

**Comment by jniyaz** [comment]
Downgrade Python version to <= 3.6.7.

**Comment by testforpepper** [comment]
@AmalM7 did you manage to solve it? I have the same problem. I'm running pip 19.3.1 with python 3.7 and still have that issue.

**Comment by mrjazz** [comment]
@testforpepper did you upgrade your pip?

**Comment by testforpepper** [comment]
@mrjazz yes, it's pip 19.3.1

**Comment by UmerMIB** [comment]
> Got this working!
> 
> ```
> sudo curl https://bootstrap.pypa.io/get-pip.py -o get-pip.py
> python3 get-pip.py
> ```
> 
> Installing collected packages: pip
> Found existing installation: pip 9.0.1
> Uninstalling pip-9.0.1:
> Successfully uninstalled pip-9.0.1
> Successfully installed pip-19.3.1
> 
> Then:
> `pip3 install rasa`

Can you please tell me for windows10?

**Comment by AmalM7** [comment]
@testforpepper I am using windows 10, even with upgrading pip it doesn't work. However, it works fine with Ubuntu.

**Comment by testforpepper** [comment]
@AmalM7 Thank you very much for your repIy! tried it on Raspbian and it still doesn't work

**Comment by UmerMIB** [comment]
> @testforpepper I am using windows 10, even with upgrading pip it doesn't work. However, it works fine with Ubuntu.

Its work fine by creating a virtual environment of python 3.6.10 by command ```conda create -n myenv python=3.6```  then ``` conda activate myenv```

**Comment by testforpepper** [comment]
> @UmerMIB  Its work fine by creating a virtual environment of python 3.6.10 by command `conda create -n myenv python=3.6` then ` conda activate myenv`
Should I use the virtual environment for the whole rasa installation or just upgrading pip?

**Comment by UmerMIB** [comment]
> > @UmerMIB  Its work fine by creating a virtual environment of python 3.6.10 by command `conda create -n myenv python=3.6` then ` conda activate myenv`
> 
> Thank you! Should I use the virtual environment for the whole rasa installation or just upgrading pip?

I am new to RASA I can't guide well , well this creating environment is effective for me this time

**Comment by rahulsattar** [comment]
Looks like the problem is with Python 3.8. Use Python 3.7 instead. Steps I took to solve this.

Created a python 3.7 environment with conda
Installed rasa using pip install rasa within the environment.
Worked for me.

**Comment by santosha86** [comment]
Dear's 
I tried all the above solutions but still i am getting the below error.
ERROR: Could not find a version that satisfies the requirement tensorflow-cpu~=1.15.0 (from rasa<=1.7,>=1.6.1->rasa-x) (from versions: none)


ERROR: No matching distribution found for tensorflow-cpu~=1.15.0 (from rasa<=1.7,>=1.6.1->rasa-x)

I have pip version 20.0.2
I tried installing rasa with both tensorflow 1.12.0 and tensorflow 2.1.0
I installed below from Tensor flow website for mac os and for python 3.6
https://storage.googleapis.com/tensorflow/mac/cpu/tensorflow-2.1.0-cp36-cp36m-macosx_10_9_x86_64.whl

please help me to resolve this issue.

**Comment by danyaljj** [comment]
Still have the same error, with pip 20.0.2 and have tried Python 3.7 & 3.6.

**Comment by HsGaurav** [comment]
okay, guys here is the simple solution that I found out with it. 
In Windows, your TensorFlow version would be installed on the python that you have available for all users (ie. which is in system variable PATH not in user variable PATH in environment variable section). So make a new environment with something like virtualenv venv which will use your system variable PATH python, and then try installing TensorFlow.
In Linux, it's pretty much the same.

**Comment by ses4j** [comment]
Old tensorflow wheels can be downloaded from https://pypi.org/project/tensorflow/1.15.2/#files and installed directly with pip, `pip install <downloaded file>`.
