### ISSUE TITLE
No matching distribution found for tensorflow==1.15.0

### ISSUE THREAD

**Issue by Poojan66** [RasaHQ/rasa#4784]
Python version: 3.6.8

Operating system (linux): ubuntu

Issue:
I keep getting this tensorflow error whenever I run requirement.txt file. example pip3 install -r requirement.txt

>Could not find a version that satisfies the requirement tensorflow==1.15.0 (from versions: 0.12.1, 1.0.0, 1.0.1, 1.1.0rc0, 1.1.0rc1, 1.1.0rc2, 1.1.0, 1.2.0rc0, 1.2.0rc1, 1.2.0rc2, 1.2.0, 1.2.1, 1.3.0rc0, 1.3.0rc1, 1.3.0rc2, 1.3.0, 1.4.0rc0, 1.4.0rc1, 1.4.0, 1.4.1, 1.5.0rc0, 1.5.0rc1, 1.5.0, 1.5.1, 1.6.0rc0, 1.6.0rc1, 1.6.0, 1.7.0rc0, 1.7.0rc1, 1.7.0, 1.7.1, 1.8.0rc0, 1.8.0rc1, 1.8.0, 1.9.0rc0, 1.9.0rc1, 1.9.0rc2, 1.9.0, 1.10.0rc0, 1.10.0rc1, 1.10.0, 1.10.1, 1.11.0rc0, 1.11.0rc1, 1.11.0rc2, 1.11.0, 1.12.0rc0, 1.12.0rc1, 1.12.0rc2, 1.12.0, 1.12.2, 1.12.3, 1.13.0rc0, 1.13.0rc1, 1.13.0rc2, 1.13.1, 1.13.2, 1.14.0rc0, 1.14.0rc1, 1.14.0, 2.0.0a0, 2.0.0b0, 2.0.0b1)
No matching distribution found for tensorflow==1.15.0

**Comment by sara-tagger** [comment]
Thanks for the issue, @amn41 will get back to you about it soon!

###### You may find help in the [docs](https://rasa.com/docs/) and the [forum,](https://forum.rasa.com/) too 🤗

**Comment by erohmensing** [comment]
@Poojan66 do you get any notice about you being able to update your pip? Try `pip install -U pip`, as tensorflow 1.15.0 is first available in pip 19.0.0.

**Comment by ChristianStornowski** [comment]
@Poojan66 what version of ubuntu do you use? 32 or 64 Bit edition?

This overview is important: https://www.tensorflow.org/install/pip?lang=python3#package-location

**Comment by Poojan66** [comment]
@ChristianStornowski  Its 64 Bit.

**Comment by Poojan66** [comment]
@erohmensing @ChristianStornowski  Thanks a lot for replying, upgrading pip to latest solves the problem.

**Comment by hjelga** [comment]
But can we do when deploying requirements.txt to heroku we get the same error

**Comment by Chronosms** [comment]
I have the same problem too
Debian 10
Python 3.7, latest pip version

**Comment by sirius0503** [comment]
> @Poojan66 do you get any notice about you being able to update your pip? Try `pip install -U pip`, as tensorflow 1.15.0 is first available in pip 19.0.0.

My pip doesn't show any pip update messages, but the problem was solved by following what you said also `pip --version` clearly shows a pretty old version for `python 3.6`
