### ISSUE TITLE
english spaCy models not found in spacy-en docker image

### ISSUE THREAD

**Issue by Syndace** [RasaHQ/rasa#4789]
**Rasa version**: latest (1.5.0a1), also tested on 1.4.5 (most recent stable release)

**Operating system** (windows, osx, ...): running docker-ce on debian 10

**Issue**: When using the `rasa/rasa:latest-spacy-en` docker image, starting the HTTP API and trying to train NLU, the server reports that the spaCy models are not installed/linked. (Note: I also tried version 1.4.5). When using the `rasa/rasa:latest-full` docker image instead, there are no issues.

**Error (including full traceback)**:
```JSON
{"version":"1.5.0a1","status":"failure","message":"An unexpected error occurred during training. Error: Model 'en' is not a linked spaCy model.  Please download and\/or link a spaCy model, e.g. by running:\npython -m spacy download en_core_web_md\npython -m spacy link en_core_web_md en","reason":"TrainingError","details":{},"help":null,"code":500}
```

**Command or request that led to error**:
```Bash
$ docker run -p 5005:5005 rasa/rasa:latest-spacy-en run --enable-api
$ curl --header "Content-Type: application/json" \
    --request POST \
    --data '{"config": "language: en\npipeline: pretrained_embeddings_spacy", "nlu": "## intent:test\n- Please run the tests\n", "force": true, "save_to_default_model_directory": true}' \
    http://localhost:5005/model/train
```

**Content of configuration file (config.yml)** (if relevant):
```yml
language: "en"
pipeline: "pretrained_embeddings_spacy"
```

**Comment by Syndace** [comment]
I'm sorry, it looks like `latest-full` in fact has the same issue. It works as expected in version `1.4.1-full`. Im going to test a few more tags and report my results by editing this comment.

**Comment by sara-tagger** [comment]
Thanks for raising this issue, @erohmensing will get back to you about it soon✨

###### Please also check out the [docs](https://rasa.com/docs/) and the [forum](https://forum.rasa.com/) in case your issue was raised there too 🤗

**Comment by erohmensing** [comment]
Thanks for the detailed write up of what works! I'm looking into it, so far the linking seems to work fine when i build locally from master but will check it out.

**Comment by Syndace** [comment]
The issue is fixed in the current `latest`-image, thanks!
