### ISSUE TITLE
How to reset a slot in Story

### ISSUE THREAD

**Issue by palomacmamede** [RasaHQ/rasa#4793]
**Description of Problem**:

Sometimes we have situations that need to be reset for efficient conversation, for example if agency and account are filled in a slot, the bot can make a transaction that the user doesn't want to do. So the Slot must be reset after the interaction. In the Rasa documentation I didn't find an example of how to reset a Slot, but I learned how to do it.

**Overview of the Solution**:
```
# story_01
* greet
  - action_fetch_profile
  - slot{"account_type" : "premium"}
  - slot{"account_type" : null}
  - utter_welcome_premium
```
**Definition of Done**:

- [ ] Create a exemple of how to reset a slot in Rasa documentation

**Comment by sara-tagger** [comment]
Thanks for submitting this feature request 🚀@JustinaPetr will get back to you about it soon!✨

**Comment by filipedfs** [comment]
Is this still valid in Rasa 2.x? How to achieve this?
