### ISSUE TITLE
AttributeError: module 'rasa_nlu.utils' has no attribute 'list_files'

### ISSUE THREAD

**Issue by KakSeto** [RasaHQ/rasa#4796]
Hello, im new with RASA
i would like to create simple chatbot
when i try to train my stories with this code : 

```
def train_dialog(dialog_training_data_file, domain_file, path_to_model = 'models/dialogue'):
    logging.basicConfig(level='INFO')
    agent = Agent(domain_file,
              policies=[MemoizationPolicy(max_history=1)])
    training_data = agent.load_data(dialog_training_data_file)
    agent.train(
        training_data,
        augmentation_factor=50,
        epochs=200,
        batch_size=10,
        validation_split=0.2)
    agent.persist(path_to_model)

train_dialog('data/stories.md', 'domain.yml')
```
just got this error : 

**AttributeError: module 'rasa_nlu.utils' has no attribute 'list_files'**

Thanks :)

**Comment by sara-tagger** [comment]
Thanks for the question, our Github issue board is for **bugs and feature requests only,** though 😕
Please ask this question in the [forum✨](https://forum.rasa.com/c/rasa)

###### If you were describing a bug, please create a [report](https://github.com/RasaHQ/rasa/issues/new?labels=bug&template=bug_report.md) and fill out the template.
