### ISSUE TITLE
Cannot train model in docker on centOS; models folder not created (silent failure)

### ISSUE THREAD

**Issue by miohana** [RasaHQ/rasa#4797]
**Rasa version**:
using docker-full-latest

**Operating system** (windows, osx, ...):
CentOS Linux 7 (Core)

**Issue**:
I'm trying to deploy my locally trained model to remote server using docker to run the pretrained model from local machine.

**Error (including full traceback)**:

Command:
```
$ sudo docker run -v $(pwd):/app rasa/rasa init --no-prompt
```
Traceback:
```
Warning: Output is not to a terminal (fd=1).
Warning: Input is not to a terminal (fd=0).
Welcome to Rasa! 🤖

To get started quickly, an initial project will be created.
If you need some help, check out the documentation at https://rasa.com/docs/rasa.

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/distutils/file_util.py", line 41, in _copy_file_contents
    fdst = open(dst, 'wb')
PermissionError: [Errno 13] Permission denied: './__init__.py'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/build/bin/rasa", line 11, in <module>
    load_entry_point('rasa==1.5.0a1', 'console_scripts', 'rasa')()
  File "/build/lib/python3.6/site-packages/rasa/__main__.py", line 76, in main
    cmdline_arguments.func(cmdline_arguments)
  File "/build/lib/python3.6/site-packages/rasa/cli/scaffold.py", line 195, in run
    init_project(args, path)
  File "/build/lib/python3.6/site-packages/rasa/cli/scaffold.py", line 111, in init_project
    create_initial_project(path)
  File "/build/lib/python3.6/site-packages/rasa/cli/scaffold.py", line 119, in create_initial_project
    copy_tree(scaffold_path(), path)
  File "/usr/local/lib/python3.6/distutils/dir_util.py", line 163, in copy_tree
    dry_run=dry_run)
  File "/usr/local/lib/python3.6/distutils/file_util.py", line 151, in copy_file
    _copy_file_contents(src, dst)
  File "/usr/local/lib/python3.6/distutils/file_util.py", line 44, in _copy_file_contents
    "could not create '%s': %s" % (dst, e.strerror))
distutils.errors.DistutilsFileError: could not create './__init__.py': Permission denied
```

Thanks in advance!

**Comment by aggarwalrahul86** [comment]
i am facing the same issue, creared an ubuntu lts vm in azure and tried to install rasa using docker

**Comment by sara-tagger** [comment]
Thanks for the issue, @tmbo will get back to you about it soon!

###### You may find help in the [docs](https://rasa.com/docs/) and the [forum,](https://forum.rasa.com/) too 🤗

**Comment by tmbo** [comment]
Puh, no idea where this is coming from - @aleerizw, do you know what might be causing this?

@miohana: why are you running `rasa init` in the first place if all you want to do is deploy an already trained model?

**Comment by miohana** [comment]
@tmbo because I was following rasa instructions, with the command located [here](https://rasa.com/docs/rasa/user-guide/running-rasa-with-docker/), in the section _Setup_:
```
docker run -v $(pwd):/app rasa/rasa init --no-prompt
```
With what I saw in the documentation, I need to create a docker image with an empty rasa and add my pretrained model after.

**Comment by tmbo** [comment]
@erohmensing this seems to be a docs issue then as well as a permission one. Because it is not necessary to run `rasa init` in the container to deploy a model.

**Comment by erohmensing** [comment]
Got it, will give it an update. I reckon if you already have a rasa model, as long as it is in the `models/` folder, you can skip to [Running the Rasa Server](https://rasa.com/docs/rasa/user-guide/running-rasa-with-docker/#running-the-rasa-server), sound good?

**Comment by sunchuanjia** [comment]
replace`docker run -v $(pwd):/app rasa/rasa init --no-prompt` with `docker run -v myrasa:/app rasa/rasa init --no-prompt` ,then it will create a dir at `/www/server/docker/volumes`,it works.

**Comment by thainh107** [comment]
i am facing the same issue

**Comment by anbasile** [comment]
Same issue here

**Comment by kristiankolthoff** [comment]
It seems to be a problem of writing permission for the `$(pwd)` directory. If I give permissions to write contents to `$(pwd)` or any directory you want to use than `sudo docker run -v $(pwd):/app rasa/rasa init --no-prompt` works fine and can create the corresponding files in the `$(pwd)`.

**Comment by goyalrahul31** [comment]
I am facing the same Issue even after  i give the permissions to the folder. 
`docker run -v $(pwd):/app rasa/rasa init --no-prompt`
The create Commands works but it does not seem to create the Models folder due to which i am not able to run the Shell Command:- 
`docker run -it -v $(pwd):/app rasa/rasa shell`
Please Rectify the Issue if anyone has resolved the specific problem.

**Comment by RielKIM** [comment]
Hi, this error could be fixed by modifying ``Dockerfile``.
Please refer this(https://github.com/RasaHQ/rasa/pull/5298).
Then, ``docker build -t <your image name>:latest .``
And restart it.

**Comment by erohmensing** [comment]
Hi everyone, for this command, that creates new files and directories, the user (`1001`) apparently does not have permission to create these files in the local directory. 

If you already have models, you don't need to use `rasa init` to deploy a model. If you are creating a new one, you can use the `-u` flag to let this one command act as root to create files. 
```
docker run -v $(pwd):/app -u root rasa/rasa init --no-prompt
```

Plan to clear this up in the documentation 👍

**Comment by erohmensing** [comment]
> The create Commands works but it does not seem to create the Models folder due to which i am not able to run the Shell Command:-

Interesting, I ran into this as well. When I ran into the general permission error on Ubuntu, the `-u root` fixed it, and correctly created the models folder. But I can't get the models folder to appear on CentOS, even if I run the `train` command in the container as root. We'll keep looking into this.

**Comment by tczekajlo** [comment]
@erohmensing Can you reproduce the error? If yes can you give me the steps/commands that you executed? Additionally, a version of docker, image, CentOS will be useful. 

I've checked the latest docker image (`rasa/rasa`) with `CentOS 7 Core` using docker with `root` permission and I couldn't reproduce the same behavior that you described :)
