### ISSUE TITLE
Issue with kwargs unpacking in rasa.test()

### ISSUE THREAD

**Issue by mrkaaa** [RasaHQ/rasa#4798]
**Rasa version**: 1.4.5

**Rasa X version** (if used & relevant): not relevant

**Python version**: 3.7.5

**Operating system** (windows, osx, ...): osx

**Issue**:
Passing nlu-related `kwargs` to rasa.test() function causes fail presumably because of unnecessary `kwargs` unpacking in test_core() call.

**Error (including full traceback)**:
```
...
rasa.test(
     model=model_path,
     stories=stories_path,
     nlu_data=nlu_test_path,
     output=results_path,
     kwargs={"errors": True}
)
```
```
ERROR:TrainWorker:Action train-rasa-agent failed!
ERROR:TrainWorker:test_core() got an unexpected keyword argument 'errors'
Traceback (most recent call last):
  File "/Users/ruagval/PycharmProjects/chatbot/event_core/workers/train.py", line 52, in user_callback
    model_id, return_message = process_train_message(input_params)
  File "/Users/ruagval/PycharmProjects/chatbot/rasa_custom/train_processor.py", line 150, in process_train_message
    validation_results_tmp_path)
  File "/Users/ruagval/PycharmProjects/chatbot/rasa_custom/train_processor.py", line 175, in evaluate_rasa_agent
    kwargs={"errors": True}
  File "/Users/ruagval/PycharmProjects/venv/lib/python3.7/site-packages/rasa/test.py", line 48, in test
    test_core(model, stories, endpoints, output, **kwargs)
TypeError: test_core() got an unexpected keyword argument 'errors'
```

**Command or request that led to error**:
```
test_core(model, stories, endpoints, output, **kwargs)
```

**Comment by sara-tagger** [comment]
Thanks for raising this issue, @tmbo will get back to you about it soon✨

###### Please also check out the [docs](https://rasa.com/docs/) and the [forum](https://forum.rasa.com/) in case your issue was raised there too 🤗

**Comment by tmbo** [comment]
Yes this is a bug. @mrkaaa do you mind providing a PR with a fix?

**Comment by mrkaaa** [comment]
> Yes this is a bug. @mrkaaa do you mind providing a PR with a fix?

@tmbo Sure. Made a PR, pls have a look.
