### ISSUE TITLE
`rasa interactive` does not work without nlu data

### ISSUE THREAD

**Issue by wochinge** [RasaHQ/rasa#4799]
Setup:
- only stories in `data`, but no `nlu` file
- run `rasa interactive`

Result:
```
Cannot train initial Rasa model. Please provide NLU and Core data using the '--data' argument.
```

**Comment by erohmensing** [comment]
did you have a core model trained already?

**Comment by wochinge** [comment]
no, I deleted `models`

**Comment by erohmensing** [comment]
got it. Seems `rasa train` handles this correctly, we probably just jump into the logic too deep in interactive 
```
rasa ❯ rasa train
No NLU data present. Just a Rasa Core model will be trained.
Training Core model...
```
