### ISSUE TITLE
`action_restart` does not stop predictions during `rasa test`

### ISSUE THREAD

**Issue by JEM-Mosig** [RasaHQ/rasa#4805]
**Rasa version**: 1.4.3

**Python version**: 3.6.9

**Operating system** (windows, osx, ...): MacOS Mojave

**Issue**: 
Define a custom action `action_restart` that utters a message and then sends `Restarted()`. This functionality cannot be tested with test stories, because rasa **keeps making predictions after `action_restart`**. Specifically, see this example on Carbon Bot: https://github.com/RasaHQ/carbon-assistant/pull/67#issuecomment-556050749

**Error (including full traceback)**:
```
## faq, restart
* faq
    - respond_faq
* thank
    - utter_express_positive-emo
* faq
    - respond_faq
* restart
    - action_restart
    - action_listen   <!-- predicted: utter_acknowledge -->
```

**Command or request that led to error**:
```
rasa test --fail-on-prediction-errors
```

**Comment by alwx** [comment]
It's actually not the case any longer.
I tried overriding restart_action for the default `formbot` and modified stories accordingly. I also made several test stories and got the following:

```> rasa test --fail-on-prediction-errors --stories test_stories/stories.md```

```
## unhappy path
* greet
    - utter_greet
* request_restaurant
    - restaurant_form
    - form{"name": "restaurant_form"}
* chitchat
    - utter_chitchat
    - restaurant_form
    - form{"name": null}
    - utter_slots_values
* thankyou
    - utter_noworries
* thankyou
    - action_restart
    - utter_noworries   <!-- predicted: action_listen -->
```

In this case, rasa correctly predicts that `action_listen` follows `action_restart`. Here are the modifications I made to check this behavior: https://github.com/RasaHQ/rasa/commit/acb2333169f8c2375178b26865144bec27b4e6b0

**Comment by wochinge** [comment]
@JEM-Mosig
