### ISSUE TITLE
Unable to install rasa development version --ERROR: No matching distribution found for rasa-sdk~=1.4.0 (from -r requirements.txt (line 39))

### ISSUE THREAD

**Issue by sanjayrjs16** [RasaHQ/rasa#4810]
I was trying to install the rasa development verion on ubuntu 16.04 LTS.
Python version is python 3.6.5

When I run pip install -r requirements.txt , I get the following error:

ERROR: Could not find a version that satisfies the requirement rasa-sdk~=1.4.0 (from -r requirements.txt (line 39)) (from versions: 1.0.0rc3, 1.0.0rc4, 1.0.0, 1.1.0, 1.1.1, 1.2.0, 1.3.0a1, 1.3.0, 1.3.1, 1.3.2, 1.3.3)
ERROR: No matching distribution found for rasa-sdk~=1.4.0 (from -r requirements.txt (line 39))

Please help.

**Comment by sara-tagger** [comment]
Thanks for the question, our Github issue board is for **bugs and feature requests only,** though 😕
Please ask this question in the [forum✨](https://forum.rasa.com/c/rasa)

###### If you were describing a bug, please create a [report](https://github.com/RasaHQ/rasa/issues/new?labels=bug&template=bug_report.md) and fill out the template.
