### ISSUE TITLE
Slack Connector: support app mentions and direct messaging

### ISSUE THREAD

**Issue by kearnsw** [RasaHQ/rasa#4811]
**Description of Problem**: I experienced the same issue as [#3085](https://github.com/RasaHQ/rasa/issues/3085) and [#3252](https://github.com/RasaHQ/rasa/issues/3252). Both went unsolved, and I believe the root cause is that the bot should be reading the channel information from the JSON request. From my perspective, the default behavior would look something like:

1.  The bot responds when mentioned
2.  The bot responds to direct messages
3.  If configured, the bot will respond on a channel regardless of 1 and 2.

**Overview of the Solution**: I took the first steps toward this solution by reading the incoming channel, channel type, and message type from the JSON request. I used this data to implement items 1-3 above.

**Definition of Done**: Currently, this solves the immediate issue of the bot not responding. However, I am not yet certain about how sessions are managed. I would propose that the bot should also be monitoring who is speaking in the case of a direct message and saving the sessions to a tracker store. In the case of multiparty dialog, another solution would be needed.

**Comment by sara-tagger** [comment]
Thanks for submitting this feature request 🚀@tabergma will get back to you about it soon!✨

**Comment by erohmensing** [comment]
Hey @kearnsw, overall I think this is a great idea. To clarify, you think the default behavior should be:

Channel configred:
- bot listens in channel and responds there

No channel configured:
- bot is available via DM and also responds in any channel when mentioned 

Is that correct?


> I would propose that the bot should also be monitoring who is speaking in the case of a direct message and saving the sessions to a tracker store

Agreed. 

With respect to the bot responding when mentioned though, how do you expect that to look? I feel like that goes along with `In the case of multiparty dialog, another solution would be needed.` -- if you mention the bot in a channel with other people, how do you want it to know who in the channel is talking to the bot -- does the user have to mention the bot at every conversation turn?

**Comment by kearnsw** [comment]
In case of channel configured, I’m suggesting all three, at least if the docs stay the way they are. I think this is causing the confusion since people assume they can test the bot through DM.

Yes, as currently configured in the PR, the bot would need to be mentioned during each turn unless the bot is configured to respond on that channel. In my organizations, everyone tends to tag each other in each post anyway so this wouldn’t be outside the norm in our case.
Unless the bot is a super human conversationalist, I’d anticipate the user wanting others to continue the conversation past a couple turns in most cases.

**Comment by mehdiHadji** [comment]
I'm too facing this issue, generally what i do is install the bot on slack in every block (no response from the bot).
I noticed that the bot really respond to the user msg but the problem is the responf is not displayed on slack...

**Comment by zaidalvi** [comment]
Hi guys. I too am facing this issue. Rasa is receiving my message through but is unable to display the message that is sent back from Rasa. Any update on this issue?

**Comment by kearnsw** [comment]
@zaidalvi  are you triyng to send as a direct message or using the @ symbol? Can you share your config? There is a fix that is under review, but I should be able to help you get it running in the short-term.

**Comment by zaidalvi** [comment]
I am sending a direct message. 
In my terminal it says 200 ok but I can't see a response on slack.

<img width="734" alt="Screen Shot 2020-02-10 at 12 31 11 AM" src="https://user-images.githubusercontent.com/36755611/74108511-fbd14a00-4b9c-11ea-971f-1d6b8d75b1f9.png">
<img width="559" alt="Screen Shot 2020-02-10 at 12 31 52 AM" src="https://user-images.githubusercontent.com/36755611/74108513-01c72b00-4b9d-11ea-8b22-a7498154c886.png">
<img width="733" alt="Screen Shot 2020-02-10 at 12 32 50 AM" src="https://user-images.githubusercontent.com/36755611/74108514-068bdf00-4b9d-11ea-8f38-56838b44a71a.png">
<img width="1606" alt="Screen Shot 2020-02-07 at 11 28 39 PM" src="https://user-images.githubusercontent.com/36755611/74108515-0a1f6600-4b9d-11ea-84d1-1871e96b1744.png">

**Comment by kearnsw** [comment]
Thanks! This is most likely the same issue that I experienced. Try using this build with an updated slack connector that should resolve the issue (with no changes on your part): https://github.com/kearnsw/rasa 
It should be merged with the main project soon, so please let me know if you run into any issues with it.

**Comment by zaidalvi** [comment]
Thank you for your fast reply @kearnsw. I'm sorry I am really new to rasa and slack. Can you please tell me what I have to do to use the new connector or if there's a some sort of a tutorial?

**Comment by co-learning-lounge** [comment]
@zaidalvi Check [this](https://github.com/kearnsw/rasa/blob/3ffd78dc7b4c4a19a399558c6eebe6b291f69152/docs/user-guide/connectors/slack.rst).

**Comment by glauciams** [comment]
@kearnsw I've been having the same issue, followed what's suggested on the threads but still nothing. Is this solved or not yet? I wanted to deploy the bot to have a few (3) users testing it, is there another easy way to deploy it? I've tried rasa x with ngrok but it's too slow, the bot does not work properly (don't recognize intents, for example) and I can't keep track of the questions being asked. Thank you!

**Comment by kearnsw** [comment]
Hi @glauciams , this was partially solved in #4812 . There is still need for support to maintain sessions with multiple users. Although, I know there were several additional changes from the Rasa team in recent weeks. As for not recognizing intents, that should be unrelated to the problem described on this thread. You've followed this guide correct ([Slack Connector](https://rasa.com/docs/rasa/user-guide/connectors/slack/))?

**Comment by alwx** [comment]
@kearnsw are you still working on this one?

**Comment by kearnsw** [comment]
@alwx , I am not currently working on this issue. I think everything listed in this issue is now resolved, as I have a bot currently handling sessions with multiple slack users which appears to be the only remaining concern of this issue last time I checked. Did you run into any problem with the slack connector related to this issue? If not, I can go ahead and close it.
