### ISSUE TITLE
What is happening here?

### ISSUE THREAD

**Issue by juanmariareina** [RasaHQ/rasa#4825]
Hi all!

I'm trying to install RASA on Ubuntu 16.04.6

python3 is 3.6.8
And this is how I've installed pip3: 

sudo apt-get install python3-pip

Then I do

pip3 install rasa-x --extra-index-url https://pypi.rasa.com/simple

And the installation process finishes with the following error:

Collecting tensorflow~=1.15.0 (from rasa~=1.4.0->rasa-x)
  Could not find a version that satisfies the requirement tensorflow~=1.15.0 (from rasa~=1.4.0->rasa-x) (from versions: 0.12.1, 1.0.0, 1.0.1, 1.1.0rc0, 1.1.0rc1, 1.1.0rc2, 1.1.0, 1.2.0rc0, 1.2.0rc1, 1.2.0rc2, 1.2.0, 1.2.1, 1.3.0rc0, 1.3.0rc1, 1.3.0rc2, 1.3.0, 1.4.0rc0, 1.4.0rc1, 1.4.0, 1.4.1, 1.5.0rc0, 1.5.0rc1, 1.5.0, 1.5.1, 1.6.0rc0, 1.6.0rc1, 1.6.0, 1.7.0rc0, 1.7.0rc1, 1.7.0, 1.7.1, 1.8.0rc0, 1.8.0rc1, 1.8.0, 1.9.0rc0, 1.9.0rc1, 1.9.0rc2, 1.9.0, 1.10.0rc0, 1.10.0rc1, 1.10.0, 1.10.1, 1.11.0rc0, 1.11.0rc1, 1.11.0rc2, 1.11.0, 1.12.0rc0, 1.12.0rc1, 1.12.0rc2, 1.12.0, 1.12.2, 1.12.3, 1.13.0rc0, 1.13.0rc1, 1.13.0rc2, 1.13.1, 1.13.2, 1.14.0rc0, 1.14.0rc1, 1.14.0, 2.0.0a0, 2.0.0b0, 2.0.0b1)
No matching distribution found for tensorflow~=1.15.0 (from rasa~=1.4.0->rasa-x)
You are using pip version 8.1.1, however version 19.3.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.

(to be continued)

**Comment by juanmariareina** [comment]
So I've tried to do this:
sudo pip3 install --upgrade pip

Then things get worse:

$ pip3 -V
Traceback (most recent call last):
  File "/usr/bin/pip3", line 9, in <module>
    from pip import main
ImportError: cannot import name 'main'
Error in sys.excepthook:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/apport_python_hook.py", line 63, in apport_excepthook
    from apport.fileutils import likely_packaged, get_recent_crashes
  File "/usr/lib/python3/dist-packages/apport/__init__.py", line 5, in <module>
    from apport.report import Report
  File "/usr/lib/python3/dist-packages/apport/report.py", line 30, in <module>
    import apport.fileutils
  File "/usr/lib/python3/dist-packages/apport/fileutils.py", line 23, in <module>
    from apport.packaging_impl import impl as packaging
  File "/usr/lib/python3/dist-packages/apport/packaging_impl.py", line 23, in <module>
    import apt
  File "/usr/lib/python3/dist-packages/apt/__init__.py", line 23, in <module>
    import apt_pkg
ModuleNotFoundError: No module named 'apt_pkg'

Original exception was:
Traceback (most recent call last):
  File "/usr/bin/pip3", line 9, in <module>
    from pip import main
ImportError: cannot import name 'main'

**Comment by juanmariareina** [comment]
(CONT)

Things are different if I try with pip -V (not pip3), so let's try to install rasa with

$ pip install rasa-x --extra-index-url https://pypi.rasa.com/simple

Now the error is different:
ERROR: gym 0.15.4 requires enum34~=1.1.6, which is not installed.
ERROR: promise 2.2.1 requires typing>=3.6.4, which is not installed.
ERROR: markdown 3.1.1 has requirement setuptools>=36, but you'll have setuptools 20.7.0 which is incompatible.
ERROR: tensorboard 1.15.0 has requirement setuptools>=41.0.0, but you'll have setuptools 20.7.0 which is incompatible.
ERROR: google-auth 1.7.1 has requirement setuptools>=40.3.0, but you'll have setuptools 20.7.0 which is incompatible.
ERROR: botocore 1.13.26 has requirement python-dateutil<2.8.1,>=2.1; python_version >= "2.7", but you'll have python-dateutil 2.8.1 which is incompatible.
ERROR: rasa 1.4.6 has requirement setuptools>=41.0.0, but you'll have setuptools 20.7.0 which is incompatible.

**Comment by juanmariareina** [comment]
I'm managing to fix it by myself. Next time I will be more patient

**Comment by achantavy** [comment]
How did you fix it?

**Comment by aaronbriel** [comment]
Quick and dirty fix is to throw python-dateutil<2.8.1 in your requirements.txt.

**Comment by aaronbriel** [comment]
From what I found out, the issue is here: https://github.com/boto/botocore/issues/1872
