### ISSUE TITLE
Retrieval intent needs to store full intent name in tracker

### ISSUE THREAD

**Issue by rgstephens** [RasaHQ/rasa#4826]
**Description of Problem**:
The intent `ask_faq/python_version` is grouped into a single retriever event and placed in the tracker store as `ask_faq`. If you are using the TwoStageFallbackPolicy and the `ActionDefaultAskAffirmation` to further contextualize the conversation with the user, lack of the full intent name means you cannot determine the users intent.

**Overview of the Solution**:
Store the full intent name in the tracker store when using retrieval intents.

**Comment by amn41** [comment]
it should be available in the `tracker.latest_message` right? that should contain the top predicted response for the retrieval action

**Comment by erohmensing** [comment]
@amn41 maybe so, but not sure that solves all the problems this issue causes:

> `ask_faq/python_version` is grouped into the single retriever intent and placed in the tracker store as `ask_faq`
This seems less than ideal, i’ve also been talking to a customer who ran into this. Their use case involves lots of FAQs, but they want to know which ones are being asked the most so they can turn those into further contextual conversations to continue to help the user. as of now it is impossible when looking in the tracker store to filter by the specific faq.

**Comment by amn41** [comment]
right, but that isn't the use case for retrieval actions. Retrieval actions are there to cover all the things where context _doesn't_ matter. If you need to handle it differently, it should be a separate intent

**Comment by erohmensing** [comment]
The idea here is to be able to decide, out of these questions, which ones _should_ actually be handled differently, which they can't do without conversations with real users, to see which paths should have further information. I guess you could do that by having them all as separate intents, but it IMO feels like we're missing an easy win here by not letting you filter by the sub-intent

**Comment by amn41** [comment]
ok, I get it now! Yeah it would be great to have a way to find out which faqs should be "promoted" to real intents

**Comment by erohmensing** [comment]
I think that fits super well into "Moving from step 2 to step 3" dialogue as well -- first start with handling a bunch of faqs, then see what ones your users have follow-up questions for

**Comment by erohmensing** [comment]
cc @akelad ideas for moving from step 2 to 3

**Comment by erohmensing** [comment]
@rgstephens is this still happening?

**Comment by akelad** [comment]
not by Greg probably. Do you want to take it on instead? Or should this be on a different board?

**Comment by rgstephens** [comment]
@erohmensing do you want to do a code walkthrough on where I left this?

**Comment by akelad** [comment]
@melindaloubser1 is gonna look into this, so maybe you two can chat

**Comment by melindaloubser1** [comment]
@erohmensing should this be based off of master and go into 1.9? I've transferred the work Greg and Daksh did to a branch off of 1.8.x but I realize it will break loading old models since it will look for an extra file (`response_text_key-dict`) to load from and won't find it.
