### ISSUE TITLE
Not able to train rasa model

### ISSUE THREAD

**Issue by chandrakanthab** [RasaHQ/rasa#4828]
Hi ,
this is Chandrakanth
Iam new to rasa
below are the steps i followed
**i**. In C:\Users\my_name  directory i created virtual environment with below command
   python -m venv --system-site-packages ./rasachatbot

**ii**. I activated the virtual environment
  .\venv\Scripts\activate
 now iam in virtual environment which looks
    (rasachatbot) C:\Users\my_name

**iii.**
     Now i create a project with below command
     (rasachatbot) C:\Users\my_name > rasa init
   here new project got created and model trained 
   all files like "nlu.md","stories.md"(in data folder) 
    and "domain.yml" , "actio.py" all the files got created in below folder

   **C:\Users\my_name\rasachatbot\Lib\site-packages\rasa\cli\initial_project**

**iv**.  Now i train the model using below command
         Now i did changes  in "nlu.md", "stories.md" and "action.py" files as per video mentioned 
     and saved all the files
       below
       "https://www.youtube.com/watch?v=W7jdIeyIPcU"

       again iam training the model
     with below command 

   (rasachatbot)C:\Users\my_name>rasa train

here iam getting  below message

**"Nothing changed. You can use the old model stored at 'C:\Users\Bachu\models\20191124-093112.tar.gz'.**"

Please help someone how to train the model if we did changes in  data files and action.py file

Thanks in advance

![rasa_issue1](https://user-images.githubusercontent.com/13232033/69491265-c039b480-0eb8-11ea-8074-39c4c4a23fcb.PNG)
![rasa_issue2](https://user-images.githubusercontent.com/13232033/69491266-c039b480-0eb8-11ea-9a6b-f18adba19e6c.PNG)

**Comment by sara-tagger** [comment]
Thanks for the question, our Github issue board is for **bugs and feature requests only,** though 😕
Please ask this question in the [forum✨](https://forum.rasa.com/c/rasa)

###### If you were describing a bug, please create a [report](https://github.com/RasaHQ/rasa/issues/new?labels=bug&template=bug_report.md) and fill out the template.
