### ISSUE TITLE
Allow OR Statement in E2E stories

### ISSUE THREAD

**Issue by TomVanWemmel** [RasaHQ/rasa#4829]
**Description of Problem**:
I have a model that has difficulties distinguishing between two intents. 
Both of them have 40-50% confidence on one of the user messages in my E2E stories. About half the models I train fail on the E2E stories because the message is misclassified. In both cases, the conversation continues as I want it to go. Entities are also correctly labelled. 
**Side Note**: I know I can avoid this issue by merging two intents into one.

**Overview of the Solution**:
Allow OR statements in E2E stories for user messages. 

**Examples**:
`* request_restaurant OR inform: I want to eat at a [Lebanese](cuisine) restaurant`

**Definition of Done**:
- [ ] Tests are added
- [ ] Feature described the docs
- [ ] Feature mentioned in the changlog

**Comment by sara-tagger** [comment]
Thanks for submitting this feature request 🚀@Ghostvv will get back to you about it soon!✨

**Comment by Ghostvv** [comment]
e2e stories are designed to pass user inout text to nlu system and check that intent is correct. Prediction is deterministic, so  `I want to eat at a [Lebanese](cuisine) restaurant` should always have same intent

**Comment by TomVanWemmel** [comment]
> e2e stories are designed to pass user inout text to nlu system and check that intent is correct. Prediction is deterministic, so `I want to eat at a [Lebanese](cuisine) restaurant` should always have same intent

Thanks for your feedback. You're definitly right that ideally the result should be the same. 
In some situations, NLU alone might not be able to determine the correct intent. For instance in Dutch, "Dag" can mean both "Hello" and "Goodbye". Should I then consider this the same intent? 

I think the "e2e" part is an indication that the interaction between the bot and the user should be validated (as a black box). 
It should indicate the quality of the conversation, regardless of the intermediate NLU process. A user doesn't see to which intent the message is mapped. The user doesn't care about that, but does care about the answer from the bot.

**Comment by Ghostvv** [comment]
yes but `e2e` evaluation also evaluates intent classification for you, so that you could improve that

**Comment by joejuzl** [comment]
Closing as there doesn't seem to be any further action.
