### ISSUE TITLE
Edits on documentation made for university student project

### ISSUE THREAD

**Issue by compSciKai** [RasaHQ/rasa#4836]
For a university school project I will be making some edits to your documentation which will aim to make writing more technical

Please add edits if you would like :)

**Comment by sara-tagger** [comment]
Thanks for the issue, @dakshvar22 will get back to you about it soon!

###### You may find help in the [docs](https://rasa.com/docs/) and the [forum,](https://forum.rasa.com/) too 🤗

**Comment by dakshvar22** [comment]
@compSciKai what sections of the docs do you plan to edit and could you briefly tell the motivation behind it?
Thanks
