### ISSUE TITLE
re-enable pytest parallel workers

### ISSUE THREAD

**Issue by wochinge** [RasaHQ/rasa#4839]
When running with multiple pytest workers we ran into the following issue on travis

```
_______________________ tests/nlu/training/test_train.py _______________________
[gw0] linux -- Python 3.6.7 /home/travis/virtualenv/python3.6.7/bin/python
worker 'gw0' crashed while running 'tests/nlu/training/test_train.py::test_train_model_on_test_pipelines[en-pipeline0]'
```
(yes, there was not any better / more log output)

We fixed it in https://github.com/RasaHQ/rasa/pull/4833 by setting the number of workers to 1. We should investigate if there is a better fix which let's us re-enable parallel testing again.

**Comment by wochinge** [comment]
cc @federicotdn

**Comment by federicotdn** [comment]
The plugin we're using for allowing multiple pytest workers is https://github.com/pytest-dev/pytest-xdist. I've changed the JOBS variable to be 1 by default, but ideally it should be `auto` (in Travis `auto` would mean use 2 workers, but that's currently breaking that test).

**Comment by icaropires** [comment]
When I was working on #4504 I've had this problem occasionally with Python 3.5, but when support to it was removed everything worked fine

**Comment by federicotdn** [comment]
Hey @icaropires, yep, we were discussing this the other day. We tested: 1) running the tests with one worker only and 2) running only the failing test (`test_train_model_on_test_pipelines`), and in both cases everything worked correctly. So it seems that there's an issue with either the VM resources as you said, or with the test sharing a resource (file?) with another test that's running at the same time. For the moment we decided to use JOBS=1 in our Travis setup, but left the option for other users to use any number they want.

**Comment by icaropires** [comment]
> Hey @icaropires, yep, we were discussing this the other day. We tested: 1) running the tests with one worker only and 2) running only the failing test (`test_train_model_on_test_pipelines`), and in both cases everything worked correctly. So it seems that there's an issue with either the VM resources as you said, or with the test sharing a resource (file?) with another test that's running at the same time. For the moment we decided to use JOBS=1 in our Travis setup, but left the option for other users to use any number they want.

@federicotdn The only problem with this strategy is that one can break the parallel tests without breaking the serial and the CI wouldn't alert :thinking: . But I understand that is just for the moment

**Comment by wochinge** [comment]
idea: run pytest as module, (`python -m pytest`)

**Comment by m-vdb** [comment]
It has been re-enabled since then:

https://github.com/RasaHQ/rasa/blob/4d4c28aeb1be1fea9abd00e392eb62cbf1a3c660/.github/workflows/continous-integration.yml#L184-L189

I think we can close this 🎉
