### ISSUE TITLE
dispatcher.utter_message() does not work in version 1.5.0

### ISSUE THREAD

**Issue by Disha-Patil** [RasaHQ/rasa#4853]
**Rasa version**: 1.5.0

**Python version**:3.7

**Operating system** (windows, osx, ...):ubuntu

**Issue**:
dispatcher.utter_message() does not give any message when running custom actions.
The action gets triggered and there is no error as well. But the message is returned. 

**Error (including full traceback)**:
no error shown. action runs successfully. 

**Command or request that led to error**:
dispatcher.utter_message()

**Comment by erohmensing** [comment]
What do you mean by `does not give any message`, `but the message is returned`? Can you provide the action code where you used `dispatcher.utter_message()`?

**Comment by JulianGerhard21** [comment]
Hi @erohmensing ,

I guess this is related to: https://github.com/RasaHQ/rasa/issues/4852

Regards
Julian

**Comment by erohmensing** [comment]
cc @wochinge

**Comment by Disha-Patil** [comment]
> What do you mean by `does not give any message`, `but the message is returned`? Can you provide the action code where you used `dispatcher.utter_message()`?

sorry for confusing words. 

In action code I have following line ``` dispatcher.utter_message("Some message")```
The action gets triggered and I can verify this in Rasa interactive, also there are no errors shown. 
However, since action is triggered and completed successfully I should be getting the output as "some message" which I fail to get. 

I have now installed rasa version 1.4.6 where it works as expected.

**Comment by erohmensing** [comment]
No worries. Thanks for the info! We are already on top of fixing it :) Will update you when a fix is released.

**Comment by JulianGerhard21** [comment]
Hi @Disha-Patil ,

this issue should be fixed with Rasa 1.5.1 which is already installable, @erohmensing told me ! :-)

Regards

**Comment by wochinge** [comment]
fixed by https://github.com/RasaHQ/rasa/pull/4855 and available in rasa 1.5.1 as Julian said :-)
