### ISSUE TITLE
Add comment to credentials.yml

### ISSUE THREAD

**Issue by tabergma** [RasaHQ/rasa#4854]
Add a comment to https://github.com/RasaHQ/rasa/blob/master/rasa/cli/initial_project/credentials.yml#L31
describing what this entry does.

The entry is needed if you are using Rasa X. There are the credentials for the Rasa X “channel”, i.e. talk to your bot and share your bot.

**Comment by arbazkhan971** [comment]
I am interested to contribute for this issue
Could you please assign this to me

**Comment by arbazkhan971** [comment]
what exactly is entry?
any reference for same?

**Comment by tabergma** [comment]
@arbazkhan971 You can write something similar as in the description of this issue:
Needed for Rasa X: Credentials for the Rasa X “channel”, i.e. talk to your bot and share your bot.

**Comment by kr-sundaram** [comment]
@arbazkhan971 & @tabergma  - Hi Both, I would like to work on this issue if any progress has not been made so far.

Thanks.

**Comment by tabergma** [comment]
@kr-sundaram Great 🎉  The issue is still open, feel free to work on it. Let me know if you need any help.

**Comment by kr-sundaram** [comment]
Thanks, @tabergma for responding. :)

I would like to know if I understand this issue correctly or not.
Issue: Currently, once rasa-x runs, comments of entries like- dialogue server talking to a Chatbot or vice versa, are not being printed in the log file or so. Kindly let me know me if I missed somewhere.

Cheers!

**Comment by tabergma** [comment]
When you create a project using `rasa init` an example `creadentials.yml` file (besides a lot of other files) is created. It can be found here: https://github.com/RasaHQ/rasa/blob/master/rasa/cli/initial_project/credentials.yml
As it is unclear what the entry `rasa` is doing, we want to add comment over there. The comment should clarify when this entry is used and what it is for.

**Comment by kr-sundaram** [comment]
Could you please help us out with where this 'credentials.yml' file is getting generated from?

Could you also give us a clear picture of the problem as it is still unclear to me what the meaning of 'rasa entries' is and in which file (log file?) the comment should be there?

Is this entry all about the different endpoints and credentials generated in the 'endpoints.yml' and the 'credentials.yml' files respectively?

**Comment by tabergma** [comment]
You need to update this file: https://github.com/RasaHQ/rasa/blob/master/rasa/cli/initial_project/credentials.yml
This file is copied whenever `rasa init` is executed.

You should add a comment before line 29 (https://github.com/RasaHQ/rasa/blob/master/rasa/cli/initial_project/credentials.yml#L29), saying what the entry does. For example, something like: 
```
# The "rasa" entry is needed if you are using Rasa X. The entry represents the credentials for the Rasa X “channel”, i.e. talk to your bot and share your bot.
```
We want to add this kind of comment, so that users get an idea what this entry is used for.
