### ISSUE TITLE
Character level CountVectorFeaturizer + oov

### ISSUE THREAD

**Issue by akelad** [RasaHQ/rasa#4856]
With the character level CountVectorFeaturizer, if there's out-of-vocabulary words the classifier will still predict an intent with a confidence. This isn't really ideal behaviour, because it often means matching to a completely random intent. With the word level featurizer, the intent would always be predicted as `None` with oov words.

There's no obvious solution to this, but if anyone has any ideas...

**Comment by tabergma** [comment]
@akelad Is this still relevant?

**Comment by akelad** [comment]
i mean it still happens no?
