### ISSUE TITLE
Rasa Core - Stories - User Messages with multiple intents and entities

### ISSUE THREAD

**Issue by mailong25** [RasaHQ/rasa#4875]
Hi
I just wonder if RasaCore support handling User Messages with multiple intents

For example "I want to book a table at King restaurant. What is their phone number ?"
So, there are two intents: inform(restaurant_name = King) and request(phone_number)

How can I define it in Rasa story format. Will it looks like this ?
* inform{"restaurant_name": "King"} AND request("phone_number")
   - action_book_table
   - action_provide_phone_number

**Comment by amn41** [comment]
yes! there is a tutorial on this https://blog.rasa.com/how-to-handle-multiple-intents-per-input-using-rasa-nlu-tensorflow-pipeline/

**Comment by amn41** [comment]
but in future please ask questions in the forum
