### ISSUE TITLE
Allow addition of unfeaturized slots at runtime

### ISSUE THREAD

**Issue by IgNoRaNt23** [RasaHQ/rasa#4884]
**Description of Problem**:

[https://forum.rasa.com/t/generate-new-slots-at-runtime/21485](https://forum.rasa.com/t/generate-new-slots-at-runtime/21485)

**Overview of the Solution**:

As suggested, it should be an optional flag. How is a user supposed the set such flag?

So far I used a modified version of the AnySlotDict (just with unfeaturized instead of generic slots) and it seems to work as expected.

**Definition of Done**:

*   [ ] Create PR
*   [ ] Tests are added
*   [ ] Feature described in the docs
*   [ ] Feature mentioned in the changelog

**Comment by sara-tagger** [comment]
Thanks for submitting this feature request 🚀@amn41 will get back to you about it soon!✨

**Comment by amn41** [comment]
Yes, I suspect the `anyslotdict` is what you  want. @tmbo looks like you added that one. I guess we would have to add an equivalent in `rasa-sdk` ?

**Comment by IgNoRaNt23** [comment]
How is such a flag supposed to be set by a user?

**Comment by IgNoRaNt23** [comment]
I still like to implement this, so what is the next step? @amn41 @tmbo

**Comment by tmbo** [comment]
I think this could fit into the `domain.yml` as part of the `config` key:
```
config:
  store_entities_as_slots: true
```
(this is how this key currently looks like) should be fine to add another key there which disables the errors for unknown slots

**Comment by IgNoRaNt23** [comment]
So, can I start to work on this?

@amn41

**Comment by amn41** [comment]
For sure! Let us know if you need some help

**Comment by IgNoRaNt23** [comment]
> I think this could fit into the `domain.yml` as part of the `config` key:
> 
> ```
> config:
>   store_entities_as_slots: true
> ```
> 
> (this is how this key currently looks like) should be fine to add another key there which disables the errors for unknown slots

Found a bug:
It is not possible to change the value of 'store_entities_as_slots'. If I set it to true, it always gets overwritten with the default value. Observed this when trying to pass my new key.
When I train with a domain file, where 'store_entities_as_slots' is set to false, the domain file in the model tar, will show 'true' again.

Need to fix this in order to make my change work (not as default).

Other than that, if I take my change as default its working as expected.

**Comment by IgNoRaNt23** [comment]
Thought the problem is the call of the merge function in Domain's load

https://github.com/RasaHQ/rasa/blob/4bbf78bedc7ee229693d65c172f49226e59142e0/rasa/core/domain.py#L90

since the config settings are just overwritten with defaults from the empty Domain. But setting 'override=True' in the merge-call doesnt solve it. (Even though the resulting domain now got the correct settings, its not the used later on).

**Comment by IgNoRaNt23** [comment]
So, how should I go on with this?
