### ISSUE TITLE
Unable to get rasa 1.5.1 working through Docker

### ISSUE THREAD

**Issue by ganeshviyer** [RasaHQ/rasa#4891]
**Rasa version**: 1.5.1

**Rasa X version** (if used & relevant): (not relevant here)

**Python version**: 3.7.4

**Operating system** (windows, osx, ...): OS X Catalina 10.15.1

**Issue**:
I'm getting quite a few errors while trying to run rasa interactive through docker.  I had recently upgraded to 1.5.1 for both rasa and rasa-sdk.  

Can someone help me how to fix?  Am I missing a step in the overall upgrade to 1.5.x?

**Error (including full traceback)**:
I first get the Tensorflow error as noted here - https://forum.rasa.com/t/tensorflow-driver-unknown-error-303/21661.

And then when I try to run rasa interactive through docker (full command below), I get these errors -
```
ERROR    rasa.core.training.interactive  - An exception occurred while recording messages.
Traceback (most recent call last):
  File "/build/lib/python3.6/site-packages/yarl/__init__.py", line 667, in _encode_host
    ip = ip_address(ip)
  File "/usr/local/lib/python3.6/ipaddress.py", line 54, in ip_address
    address)
ValueError: 'localhost' does not appear to be an IPv4 or IPv6 address
```
and 
```
AttributeError: 'str' object has no attribute 'isascii'
2019-12-02 21:30:19 ERROR    asyncio  - Task exception was never retrieved
future: <Task finished coro=<_serve_application.<locals>.run_interactive_io() done, defined at /build/lib/python3.6/site-packages/rasa/core/training/interactive.py:1452> exception=AttributeError("'str' object has no attribute 'isascii'",)>
```

**Command or request that led to error**:
The tensorflow error I get upon executing this command
```
docker build -t sample-rasa-core . && docker build -t sample-rasa-action-server -f Dockerfile.actionserver . && docker-compose -f rasa-compose.yml up
```

I run rasa interactive through this command -
```
docker run -it -v $(pwd):/app --name=rasa-interactive --network=rasa_default sample-rasa-core interactive
```

**Content of rasa-compose.yml:**
```
    version: '3.4'
    services:
      rasa:
        image: sample-rasa-core:latest
        ports:
          - 5005:5005
        command: ["run", "--enable-api", "--cors", " \"*\"", "--verbose"]

      rasa-duckling:
        image: rasa/duckling:latest

      rasa-action-server:
        image: sample-rasa-action-server:latest
        command: ["start", "--actions", "actions", "-vv"]
        # volumes:
        #   - ./actions.py:/app/actions.py
```

**Content of docker files:**
```
    FROM rasa/rasa:latest-full
    EXPOSE 5005
    COPY . /app/
```
```
    FROM rasa/rasa-sdk:latest
    EXPOSE 5055
    COPY actions.py /app/actions/actions.py
```

**Comment by sara-tagger** [comment]
Thanks for the issue, @wochinge will get back to you about it soon!

###### You may find help in the [docs](https://rasa.com/docs/) and the [forum,](https://forum.rasa.com/) too 🤗

**Comment by wochinge** [comment]
hi @ganeshviyer ,

- please don't use the `latest` tag and pin your docker image to a proper version number (`latest` is master and although we try to keep `master` stable, your setup might change with every time to you upgrade things)
- how does your `endpoints.yml` look like? seems you're referring to `localhost` somewhere
- Are you running `sample-rasa-core interactive` while you are already running `rasa run --enable-api` ?

**Comment by ganeshviyer** [comment]
Hello @wochinge, thanks for your response!  I was following the documentation here and used the `latest` tag as it was written here - https://rasa.com/docs/rasa/user-guide/running-rasa-with-docker/.

What version should I use for rasa-sdk?  Is it safe to use 1.5.1 for rasa?

My endpoints.yml file looks like this -
```
action_endpoint:
  url: "http://rasa-action-server:5055/webhook"
```

I'm also not running `rasa run` separately.  I had restarted my computer and pruned all containers and images before running these commands.

**Comment by ganeshviyer** [comment]
@wochinge Looks like defaulting the version to 1.5.1 for both rasa and rasa-sdk did the trick.  However, when I compose the docker file, I still get the Tensorflow error (that does not seem to be blocking).

```
E tensorflow/stream_executor/cuda/cuda_driver.cc:318] failed call to cuInit: UNKNOWN ERROR (303)
```

**Comment by wochinge** [comment]
@dakshvar22 Have you any idea why the log message above happens on a non-gpu version of  tensorflow?

**Comment by dakshvar22** [comment]
@wochinge Not sure. 
@ganeshviyer Have you installed `tensorflow-gpu` instead of `tensorflow`. This could come up if you are using `tensorflow-gpu` with a non-compatible GPU driver.
