### ISSUE TITLE
Text with two line breaks  (\n\n) results in the message being broken into multiple parts.

### ISSUE THREAD

**Issue by thusithaC** [RasaHQ/rasa#4895]
**Rasa version**: rasa==1.4.3

**Rasa SDK version** (if used & relevant): rasa-sdk==1.4.0

**Python version**: 3.6.8

**Operating system** (windows, osx, ...): ubuntu 18.04, linux

**Issue**:

I have text content which has multiple newline components. This formatting is important because it seems like this is the only way I can make a specific Front-End (Cannot change or edit the FE) parse Markdown formatted text. 

Example sentence text : 
```
A **fund** is a form of collective investment plan managed by professionals. \n\nA Fund can include multiple types of assets like Stocks\n- Bonds\n- Money Market instruments, etc. 
```

My issue is Rasa seems to be breaking down this sentence into multiple messages when I use 
```
dispatcher.utter_message(output)
```

example: 
```
[
    {
        "recipient_id": "fadsf",
        "text": "A **fund** is a form of collective investment plan managed by professionals. "
    },
    {
        "recipient_id": "fadsf",
        "text": "**Assets in a fund could be**: "
    },
    {
        "recipient_id": "fadsf",
        "text": "- Stocks\n- Bonds\n- Money Market instruments, etc. "
    },
]
```  

However, weird thing is if a buttons are present, this gets send correctly. 
i.e. the code is: 
```
dispatcher.utter_message(output, buttons=buttons)
```

The return will be: 
```
[
    {
        "recipient_id": "fadsf",
        "text": "A **fund** is a form of collective investment plan managed by professionals. \n\n**Assets in a fund could be**: \n\n- Stocks\n- Bonds\n- Money Market instruments, etc. \n\nWhen investors subscribe for funds, they will be given a certain number of fund units or shares whose value will change with the fluctuation of the net asset value of the funds.",
        "buttons": [
            {
                "choice": "single",
                "payload": "What is the types of fund offered by bank",
                "title": "Types of funds"
            },
            {
                "choice": "single",
                "payload": "What is the major risk of fund",
                "title": "Fund risks"
            },
            {
                "choice": "single",
                "payload": "How can i invest to fund",
                "title": "Fund subscription"
            }
        ]
    },
]
```

The second form of representation is the desired because I do not want Rasa to break down text into multiple parts based on any internal characters. 

Can someone please have a look into this? How can I get the second representation without adding buttons? The text utterance is dynamically generated and cannot be a templated as well. Breaking down text into multiple parts only when buttons are not present feels like a bug or an unexpected surprise feature ;) 

Thanks
Thusitha

**Comment by sara-tagger** [comment]
Thanks for the issue, @rgstephens will get back to you about it soon!

###### You may find help in the [docs](https://rasa.com/docs/) and the [forum,](https://forum.rasa.com/) too 🤗

**Comment by tangochris** [comment]
I don't think this is a bug. 2 newlines indicates a new paragraph, and each paragraph should be a separate message. We rely on this behavior in Rasa.

> However, weird thing is if a buttons are present, this gets send correctly.

*This* is the bug. If buttons are present, text should continue to get split into multiple messages on two newlines. We've written a custom handler to work around this.

**Comment by rgstephens** [comment]
Thanks @tangochris, I think you're referring to #4496, is that right?

**Comment by tangochris** [comment]
@rgstephens 

> I think you're referring to #4496, is that right?

No. I haven't looked at #4496 for a long time as we are now using an nlg server. The issue is moot for us.

Here I'm referring to @thusithaC's issue title, "two line breaks (\n\n) results in the message being broken into multiple parts". That is not a bug, it's a feature. It's also the way we've seen other chatbot frameworks interpret newlines.

Further, @thusithaC's comment "weird thing is if buttons are present, this gets send correctly." It is _not_ sent correctly. Two newlines should consistently be used as a demarcation for paragraphs/speech bubbles, whether or not buttons are present.

**Comment by thusithaC** [comment]
Thanks for the clarification. 

Could not find any details in the forum or documentation about how markdown formatted content are handled by rasa. 

I managed to salvage my issue by replacing '\n\n'  characters with '  \n' which caused the line break to appear in our FE. 
But yes, I agree that different behaviors with and without buttons was a bit misleading. I'll close this issue for now. 

Thanks!
Thusitha

**Comment by thusithaC** [comment]
While on the topic of output formatting, If I want a  create a "catch-all" kind of function that can custom  format all output messages from Rasa, is there a way I can do that?  ideally this should catch and apply the custom formatting/post processing to messages originating from dispatcher.utter_template,  dispatcher.utter_button_message, dispatcher.utter_message etc.

**Comment by teremterem** [comment]
Hi, but is there any way I can instruct Rasa to preserve **all** the blank lines? I need my response to be displayed in a single message:
```
Hi, my name is ...
                    <- blank line
I can help you with ...
```
Can I preserve this blank line and still have it all in one message?
I'm using Telegram as FE and my responses are defined in `domain.yml`.

**Comment by teremterem** [comment]
I found a bit of a hacky way to do this. I am putting an extra space between my line breaks, like this:
```
responses:
  utter_xxx:
  - text: "Hi, my name is ...\n \nI can help you with ..."
```
Notice the space between `\n` and `\n`.
This prevents paragraphs from being sent as separate messages.

**Comment by simplymanas** [comment]
This above solution by @teremterem  works , even I was facing similar issues

**Comment by rikhoffbauer** [comment]
My hacky solution was to use the [0x200e unicode character](https://unicodemap.org/details/0x200E/index.html) as seen on https://emptycharacter.com/.

The advantage of this approach is that it keeps the yaml more readable.

<img width="289" alt="Screenshot 2021-07-30 at 00 20 14" src="https://user-images.githubusercontent.com/62353999/127573062-1a6db2a4-e9d0-40db-97d5-8844441903e2.png">

**Comment by teremterem** [comment]
> My hacky solution was to use the [0x200e unicode character](https://unicodemap.org/details/0x200E/index.html) as seen on https://emptycharacter.com/.
> 
> The advantage of this approach is that it keeps the yaml more readable.
> 
> <img alt="Screenshot 2021-07-30 at 00 20 14" width="289" src="https://user-images.githubusercontent.com/62353999/127573062-1a6db2a4-e9d0-40db-97d5-8844441903e2.png">

I would be VERY careful with non-standard invisible characters, though. They might make someone loose quite a bunch of time trying to debug some weird problem if their IDE doesn't show such characters in any special way. I'm not saying that your approach is going to lead to any specific problem. I'm just saying that you never know and I do think that characters like that are generally an enemy of a developer.
