### ISSUE TITLE
Persistent Menu +  Get started button not supported for Facebook Messenger

### ISSUE THREAD

**Issue by RogersNtr** [RasaHQ/rasa#4904]
Actually, it is not possible to send a **Persistent Menu **and** get started button** in Rasa. So I worked on it and implemented it successful. However, I have a small trouble when trying to open a pull request. As I had already forked the repository before for another PR, when trying to fork it sends me back to the state 6 months before. I wonder how I can get the current state of the application in my new repository.

Thanks.
Your sincerely.

**Comment by sara-tagger** [comment]
Thanks for the question, our Github issue board is for **bugs and feature requests only,** though 😕
Please ask this question in the [forum✨](https://forum.rasa.com/c/rasa)

###### If you were describing a bug, please create a [report](https://github.com/RasaHQ/rasa/issues/new?labels=bug&template=bug_report.md) and fill out the template.
