### ISSUE TITLE
An error message saying "Could not find endpoint.yml" shows up

### ISSUE THREAD

**Issue by abhilasharoy** [RasaHQ/rasa#4911]
This happens even though the endpoint.yml file exists.

<img width="1149" alt="Screenshot 2019-12-05 at 11 08 59" src="https://user-images.githubusercontent.com/44964694/70229563-c05a6f80-1756-11ea-95a7-83de6829f5c9.png">

**Comment by sara-tagger** [comment]
Thanks for the issue, @amn41 will get back to you about it soon!

###### You may find help in the [docs](https://rasa.com/docs/) and the [forum,](https://forum.rasa.com/) too 🤗

**Comment by Krogsager** [comment]
This was [discussed on the forum](https://forum.rasa.com/t/rasa-x-0-23-0-error-in-endpoints-yml/21744) and is a false positive. The endpoints file are found and work correctly, and the error message should be ignored.

**Comment by ricwo** [comment]
this has been fixed and will be released with rasa X `0.23.4`
