### ISSUE TITLE
"rasa init" doesn't ask if user wants to train a model

### ISSUE THREAD

**Issue by degiz** [RasaHQ/rasa#4925]
**Rasa version**: Rasa 1.6.0a1

**Python version**: Python 3.7.4

**Operating system**: macOs Catalina 

**Issue**:

According to the docs "rasa init" should ask user if the model has to be trained, in fact that doesn't happen and the model is trained anyway.

**Command or request that led to error**:
```
rasa init
```

**Comment by sara-tagger** [comment]
Thanks for the issue, @akelad will get back to you about it soon!

###### You may find help in the [docs](https://rasa.com/docs/) and the [forum,](https://forum.rasa.com/) too 🤗
