### ISSUE TITLE
Feature Request: multiple retrieval_intent values on `ResponseSelector`

### ISSUE THREAD

**Issue by jamesmf** [RasaHQ/rasa#4926]
**Description of Problem**:
It would be valuable to be able to specify multiple `retrieval_intent` values in the config of a `ResponseSelector`. This would let you say that `intent_A` and `intent_B` should both trigger the `ResponseSelector`, but not responses C through Z. Being able to leave `ResponseSelector.retrieval_intent` as `None` is great, but if I have 100 intents and only 5 intents trigger responses, it doesn't feel good to create 5 `ResponseSelectors` or to trigger one `ResponseSelector` on the other 95 intents.

**Overview of the Solution**:
Allow the `ResponseSelector` to take an array of `retrieval_intent` values.

**Definition of Done**:
- [ ] Tests are added
- [ ] Feature described the docs
- [ ] Feature mentioned in the changlog
- [ ] `response` values only show up on responses when `intent` is in `retrieval_intent` array.

**Comment by sara-tagger** [comment]
Thanks for submitting this feature request 🚀@tabergma will get back to you about it soon!✨

**Comment by tabergma** [comment]
@dakshvar22 What do you think about this?

**Comment by dakshvar22** [comment]
I think it makes sense in some cases but would involve a large refactoring because it would involve building multiple response selector models inside one instance of `ResponseSelector` component. I would note this as feedback and revisit this when we promote `ResponseSelector` to a fully supported feature in Rasa.

**Comment by jamesmf** [comment]
Is there a reason that it needs multiple models?

My thought would be that if you specified `intent_A` and `intent_B`, it would work just like `retrieval_intent: None` for `intent_A` and `intent_B` while not firing for any other intent. So instead of training 2 models within the same `ResponseSelector` component, you'd simply train 1 (since there's only 1 in the `config.yml`). But you'd still only let that model provide responses when the intent is in  `("intent_A", "intent_B")`

**Comment by dakshvar22** [comment]
@jamesmf In that case, may I know what benefit you get by keeping them as separate intents? Does merging them into one intent harm the intent classification accuracy? Just trying to explore all possibilities before arriving at a conclusion on this. :)

**Comment by dakshvar22** [comment]
Or the other factor to think about is that based on your dataset what would be better - one common response selector for both intents v/s individual response selectors for both . 
Both may have their pros and cons like inter example confusion for the first variant and lack of data for the latter.

**Comment by jamesmf** [comment]
For the separate intent example, the one from the documentation works: a `chitchat` intent and `FAQ` intent. They're unrelated, and might likely have very different semantic representations, so separate intents would probably both help classification and allow you to take different actions with `core`.

Similarly, this lets you convert non-retrieval intents to retrieval intents really easily (add a `/response-type` to your `.chatito` file, say) without having to change any application logic depending on that intent.
