### ISSUE TITLE
Training crashes if intent name contains more than 1 slash

### ISSUE THREAD

**Issue by Nicky31** [RasaHQ/rasa#4928]
**Rasa version**: 1.5.1

**Python version**: 3.6.8

**Operating system** (windows, osx, ...): Linux

**Issue**:
If given a file with any intent name containing more than 1 slash ("/"), Rasa raises an exception
Training file that reproduces this bug :
```
{
    "rasa_nlu_data": {
        "common_examples": [{
            "text": "Hello you !",
            "intent": "My/Intent/Name"
        }],
        "entity_synonyms": [],
        "regex_features": [],
        "lookup_tables": []
    }
}
```
If you replace "My/Intent/Name" with "My/IntentName", everything works as expected.

**Error (including full traceback)**:
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python3.7/site-packages/rasa/nlu/training_data/loading.py", line 67, in load_data
    data_sets = [_load(f, language) for f in files]
  File "/usr/lib/python3.7/site-packages/rasa/nlu/training_data/loading.py", line 67, in <listcomp>
    data_sets = [_load(f, language) for f in files]
  File "/usr/lib/python3.7/site-packages/rasa/nlu/training_data/loading.py", line 138, in _load
    return reader.read(filename, language=language, fformat=fformat)
  File "/usr/lib/python3.7/site-packages/rasa/nlu/training_data/formats/readerwriter.py", line 10, in read
    return self.reads(rasa.utils.io.read_file(filename), **kwargs)
  File "/usr/lib/python3.7/site-packages/rasa/nlu/training_data/formats/readerwriter.py", line 32, in reads
    return self.read_from_json(js, **kwargs)
  File "/usr/lib/python3.7/site-packages/rasa/nlu/training_data/formats/rasa.py", line 59, in read_from_json
    msg = Message.build(ex["text"], ex.get("intent"), ex.get("entities"))
  File "/usr/lib/python3.7/site-packages/rasa/nlu/training_data/message.py", line 72, in build
    split_intent, response_key = cls.separate_intent_response_key(intent)
TypeError: cannot unpack non-iterable NoneType object
```

**Command or request that led to error**:
```
from rasa.nlu import load_data
load_data("/path/training_file")
```

**Comment by sara-tagger** [comment]
Thanks for the issue, @btotharye will get back to you about it soon!

###### You may find help in the [docs](https://rasa.com/docs/) and the [forum,](https://forum.rasa.com/) too 🤗

**Comment by dakshvar22** [comment]
@Nicky31 character `/` is reserved for defining retrieval intents as mentioned here in the docs https://rasa.com/docs/rasa/nlu/training-data-format/#markdown-format.

**Comment by Nicky31** [comment]
I didn't notice that part, thank you for the information. If that doesn't noticeably affects training performance, a clear error message indicating forbidden characters would have been greatly appreciated in such situation, saving the time I spent truncating my training dataset to find the faulty intent. 

From what I understand, even if having 1 character / in my intent name doesn't raise any exception, the intent might be impossible to learn for rasa ?

**Comment by dakshvar22** [comment]
If you 1 character `/` it would have been interpreted as a `retrieval intent` https://rasa.com/docs/rasa/core/retrieval-actions/#training-data
