### ISSUE TITLE
If I want to access an external NLU service to get the text analysis results and then do interactive learning on the rasa framework, how do I modify the code?

### ISSUE THREAD

**Issue by QiuSYang** [RasaHQ/rasa#4931]
If I want to access an external NLU service to get the text analysis results and then do interactive learning on the rasa framework, how do I modify the code?

**Comment by sara-tagger** [comment]
Thanks for the question, our Github issue board is for **bugs and feature requests only,** though 😕
Please ask this question in the [forum✨](https://forum.rasa.com/c/rasa)

###### If you were describing a bug, please create a [report](https://github.com/RasaHQ/rasa/issues/new?labels=bug&template=bug_report.md) and fill out the template.
