### ISSUE TITLE
Rasa X: Getting TimeoutError, MaxRetryError, ConnectionError when calling HTTP API

### ISSUE THREAD

**Issue by psds01** [RasaHQ/rasa#4937]
Hi,

I am trying to call the [/api/conversations/<conversation_id>](https://rasa.com/docs/rasa-x/api/rasa-x-http-api/#operation/getConversations) api to get the tracker/conversation history for a given conversation_id but I am getting a bunch of errors when I make a request call:
```
---------------------------------------------------------------------------
TimeoutError                              Traceback (most recent call last)

...

TimeoutError: [Errno 110] Connection timed out

During handling of the above exception, another exception occurred:

NewConnectionError                        Traceback (most recent call last)

...

NewConnectionError: <urllib3.connection.HTTPConnection object at 0x7f3b29df5cc0>: Failed to establish a new connection: [Errno 110] Connection timed out

During handling of the above exception, another exception occurred:

MaxRetryError                             Traceback (most recent call last)

...

MaxRetryError: HTTPConnectionPool(host='localhost.com', port=5002): Max retries exceeded with url: /api/conversations/<OMITTED> (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f3b29df5cc0>: Failed to establish a new connection: [Errno 110] Connection timed out',))

During handling of the above exception, another exception occurred:

ConnectionError                           Traceback (most recent call last)
...

ConnectionError: HTTPConnectionPool(host='localhost.com', port=5002): Max retries exceeded with url: /api/conversations/<OMITTED> (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f3b29df5cc0>: Failed to establish a new connection: [Errno 110] Connection timed out',))
```

Context:
This is with rasa x (rasa=1.0.1). Was working seamlessly before but since I got a few thousand conversations, it started giving these errors. What goes along with this is that the rasa x front-end does not load as well and keeps giving 502s and 504s when trying to log in, polling errors and takes prohibitively large time to scroll down on the `/conversations` page.

My guess is that since rasa x uses SQLite as the frontent DB, this is the one that's giving timeouts. Storage sizes: `rasa.db` -> 120MB, `tracker.db` -> 80MB.

Would love to know the reason for this.

**Comment by sara-tagger** [comment]
Thanks for the question, our Github issue board is for **bugs and feature requests only,** though 😕
Please ask this question in the [forum✨](https://forum.rasa.com/c/rasa)

###### If you were describing a bug, please create a [report](https://github.com/RasaHQ/rasa/issues/new?labels=bug&template=bug_report.md) and fill out the template.
