### ISSUE TITLE
Set Slot From Story not working

### ISSUE THREAD

**Issue by JointVentureJones** [RasaHQ/rasa#4941]
**Rasa version**:
1.4.5
**Rasa SDK version** (if used & relevant):
1.4.0
**Rasa X version** (if used & relevant):

**Python version**:
3.6.8
**Operating system** (windows, osx, ...):
ubuntu
**Issue**:
Set Slot from Story not working.
Including 

* intent
 - slot{"slotName" : "value"}
 - utter_something

in stories should set the slot slotName to value, but its not working. It also cannot be set to null with slot{"slotName": null}

**Error (including full traceback)**:
```
No Error. The slot just doesnt change as it is supposed to do.
```

**Command or request that led to error**:
```
slot{"slotName" : "value"}
```

**Content of configuration file (config.yml)** (if relevant):
```yml
default
```

**Content of domain file (domain.yml)** (if relevant):
```yml
slots:
  slotName:
  type: text
```

**Comment by erohmensing** [comment]
Hi there, this is not a bug but rather a misunderstanding in how slots are set. Please check out the [how slots get set](https://rasa.com/docs/rasa/core/slots/#how-slots-get-set) information in our docs -- slots are not set by by putting them in the stories, but rather those slot events in the stories reflect events that happen either on the NLU side or from core actions. 

As this is a usage question and not a bug, if you have further questions about how to use slots, please ask them on our [forum](http://forum.rasa.com).
