### ISSUE TITLE
Improved Rasa X shareable chat UI for mobile devices

### ISSUE THREAD

**Issue by Krogsager** [RasaHQ/rasa#4943]
**Description of Problem**:
The UI is poor for users who are testing a bot on their phone (iphone 6 in example)
The welcome text is taking a lot of space. There is a lot of padding around the UI elements. The 'send' button disappears because of some zoom-effect that happens when typing. Finally, the 'restart' button confuses new users.

**chatting with keyboard closed**
![IMG_0291](https://user-images.githubusercontent.com/27994384/70619570-96e98a00-1c15-11ea-99ed-09c854120987.png)

**chatting with keyboard open**
![IMG_0292](https://user-images.githubusercontent.com/27994384/70619569-96e98a00-1c15-11ea-8e31-8c1eebab700d.png)

**Overview of the Solution**:
A more slim styling on narrow devices. Hide or explain the 'restart' button

**Definition of Done**:

**Comment by sara-tagger** [comment]
Thanks for submitting this feature request 🚀@dakshvar22 will get back to you about it soon!✨

**Comment by TyDunn** [comment]
Hi @Krogsager. As you have pointed out, we have not optimised the `share your bot` feature in Rasa X for mobile devices. I like the idea though. Why is it important that your test users be able to use it on their phones?

**Comment by Krogsager** [comment]
When we share a bot URL for wider audience testing, the users are most likely to be using a mobile device, rather sitting at a desktop/laptop. And first impression is key - if they get frustrated by the UI I'm afraid that they will be less likely to try again later.

**Comment by TyDunn** [comment]
@Krogsager That is very true. What do you mean by `wider audience testing`?

**Comment by Krogsager** [comment]
The bot is meant as a citizen service and we don't have an existing chat channel. So to test if the bot is competent enough we will be publish it for testing to random people. (after internal testing of course)

**Comment by TyDunn** [comment]
Nice. So you publish it somewhere on the Internet and then random people test it?

**Comment by Krogsager** [comment]
We haven't decided how to target our users, but it could be a mix of random invitations by approaching people in public, a link on our website and banners/ads to invite people to test. It is for public library services.

**Comment by Saladdin** [comment]
Hey @Krogsager, the UI of the shareable chat on mobile devices has been improved in Rasa X `@0.27`, please feel free to create a new issue if you encounter any more issues with it.
