### ISSUE TITLE
failed call to cuInit: CUDA_ERROR_NO_DEVICE: no CUDA-capable device is detected (rasa-x 0.23)

### ISSUE THREAD

**Issue by kvbulusu** [RasaHQ/rasa#4955]
I'm using rasa-x (ver 0.23.3) and when I do rasa run,  I'm seeing CUDA_ERROR_NO_DEVICE errors. I checked and using tensorflow only and not tensorflow-gpu .  BTW, I'm running inside a VM (ubuntu 18.03 ) and so it doesnt have any access to host GPU (which is Nvidia). Any suggestions?

%rasa run -m models --enable-api --log-file out.log --cors "*" --credentials credentials.yml
2019-12-11 21:50:52 INFO     root  - Starting Rasa server on http://localhost:5005
2019-12-11 21:50:56 INFO     absl  - Entry Point [tensor2tensor.envs.tic_tac_toe_env:TicTacToeEnv] registered with id [T2TEnv-TicTacToeEnv-v0]
2019-12-11 21:51:21 INFO     rasa.nlu.components  - Added 'SpacyNLP' to component cache. Key 'SpacyNLP-en'.
2019-12-11 21:51:22.111707: E tensorflow/stream_executor/cuda/cuda_driver.cc:318] failed call to cuInit: CUDA_ERROR_NO_DEVICE: no CUDA-capable device is detected

**Comment by sara-tagger** [comment]
Thanks for raising this issue, @btotharye will get back to you about it soon✨

###### Please also check out the [docs](https://rasa.com/docs/) and the [forum](https://forum.rasa.com/) in case your issue was raised there too 🤗

**Comment by btotharye** [comment]
hello @kvbulusu do you have any details around what tensorflow version you installed or your installation process so far that got you here?

Thanks

**Comment by kvbulusu** [comment]
I didn't install tensorflow separately. I followed the installation on the rasa website and then had to do some addln steps noted below else it was complaining with the error below:
rasa.core.policies.ensemble.InvalidPolicyConfig: Module for policy could not be loaded.

Installation:
<created virualenv>
pip3 install rasa-x --extra-index-url https://pypi.rasa.com/simple
pip3 install "dask[complete]"
pip3 install -U tqdm
pip3 install -U gym
python -m spacy download en_core_web_md
python -m spacy link en_core_web_md en


tensorflow v1.15.0 was installed with the rasa-x

I tried setting CUDA_VISIBLE_DEVICES env setting as mentioned in multiple stackoverflow and tensorflow Github (https://github.com/tensorflow/tensorflow/issues/16284), but it didn't work...

**Comment by btotharye** [comment]
I think that warning can be ignored, are you having any errors along with this warning?  Did you deactivate and re-activate your virtualenv after installing the pre-req's by chance?

**Comment by kvbulusu** [comment]
Issue is it gets stuck there ..I waited for 20hours before I killed it...I didnt deactivate/reactivate ...

**Comment by kvbulusu** [comment]
I uninstalled tensorflow that was installed as part of rasa-x installation and I compiled tensorflow without cuda/gpu support and installed it . Now able to continue. Closing this as this doesnt look like rasa issue.
