### ISSUE TITLE
dispatcher.utter_message issue

### ISSUE THREAD

**Issue by AbdessamadAz** [RasaHQ/rasa#4959]
**Rasa version: 1.5.1**

**Issue :**

Hi,
I'm facing a problem with a basic custom action that should return "Hello world!" text
I'm getting this :
server > Frame(fin=True, opcode=1, data=b'42["bot_uttered",{"attachment":{"type":"image","payload":{"src":"Hello world!"}}}]', rsv1=False, rsv2=False, rsv3=False)

Here is my custom action code :

`from rasa_sdk import Action, Tracker
from rasa_sdk.executor import CollectingDispatcher
from typing import Any, Text, Dict, List
from rasa_sdk.events import SlotSet

class MyCustomAction(Action) :

        def name(self) -> Text:
		return "action_test"
        def run(self, dispatcher: CollectingDispatcher,
			tracker: Tracker,
			domain: Dict[Text, Any]) -> List[Dict[Text, Any]]:
		message = "Hello world !"
		dispatcher.utter_message(message)
		return []`

And I get a blank image in my webChat since "type" : "image" in the uttered message.

Please help !

**Comment by AbdessamadAz** [comment]
Hi,
I'm facing a problem with a basic custom action that should return "Hello world!" text
I'm getting this :
`server > Frame(fin=True, opcode=1, data=b'42["bot_uttered",{"attachment":{"type":"image","payload":{"src":"Hello world!"}}}]', rsv1=False, rsv2=False, rsv3=False)`

Here is my custom action code :

`from rasa_sdk import Action, Tracker
from rasa_sdk.executor import CollectingDispatcher
from typing import Any, Text, Dict, List
from rasa_sdk.events import SlotSet

class RandomBlague(Action):
	def name(self) -> Text:
		return "action_random_blague"

	def run(self, dispatcher: CollectingDispatcher,
			tracker: Tracker,
			domain: Dict[Text, Any]) -> List[Dict[Text, Any]]:
        
		message = "Hello world !"
		dispatcher.utter_message(message)
		return []`

And I get a blank image in my webChat since "type" : "image" in the uttered message.

Please help !

P.S : I'm using Rasa 1.5.1

**Comment by sara-tagger** [comment]
Thanks for the question, our Github issue board is for **bugs and feature requests only,** though 😕
Please ask this question in the [forum✨](https://forum.rasa.com/c/rasa)

###### If you were describing a bug, please create a [report](https://github.com/RasaHQ/rasa/issues/new?labels=bug&template=bug_report.md) and fill out the template.
