### ISSUE TITLE
rasa interactive visualization cannot show chinese char at http://localhost:5006/visualization.html

### ISSUE THREAD

**Issue by HatuneMiku** [RasaHQ/rasa#4961]
**Rasa version**:
1.5.3
**Rasa SDK version** (if used & relevant):
1.5.1
**Rasa X version** (if used & relevant):
0.23.4
**Python version**:
3..7.5
**Operating system** (windows, osx, ...):
Windows 10 Pro
**Issue**:

`rasa interactive` visualization cannot show chinese char at http://localhost:5006/visualization.html .it shows like `����Ѫѹ����`.  

But it can shows right in `rasa visualize`, all chinese char works fine here. 

May be help:
#3650 
https://github.com/RasaHQ/rasa/issues/3650#issuecomment-497248591

**Comment by sara-tagger** [comment]
Thanks for raising this issue, @JustinaPetr will get back to you about it soon✨

###### Please also check out the [docs](https://rasa.com/docs/) and the [forum](https://forum.rasa.com/) in case your issue was raised there too 🤗

**Comment by JustinaPetr** [comment]
Hi @HatuneMiku . Apologies for my super late response? Are you still experiencing this issue?

**Comment by HatuneMiku** [comment]
@JustinaPetr  Yes, I still get this bug like "��¼Ѫѹ" with **rasa version 1.7.2** by `rasa interactive` visualization  at http://localhost:5006/visualization.html . And chinese char works fine in 'graph.html' by `rasa visualize`.

It's the same as before.
