### ISSUE TITLE
Update docs: deactivating forms

### ISSUE THREAD

**Issue by tabergma** [RasaHQ/rasa#4962]
Currently, the documentation says

> You can also deactivate the form directly during this validation step (in case the slot is filled with something that you are certain can’t be handled) by returning self.deactivate()

However, this will not work as `validate_slot` returns a dict. But, `self.deactivate()` returns a list of events. For more details see https://forum.rasa.com/t/cannot-deactivate-a-form/22352/2.

We should update the documentation and provide a guideline when to deactivate a form.

**Comment by kunwarshivam** [comment]
not stale
