### ISSUE TITLE
Make it easier to handle story names

### ISSUE THREAD

**Issue by JEM-Mosig** [RasaHQ/rasa#4963]
**Description of Problem**: The present implementation of rasa seems to make it very difficult to operate on story names. In particular, it is difficult to _count_ story names or change them.

This is primarily due to the fact that stories are represented in the `StoryGraph` object, which cannot distinguish between

*   a single story that contains one `OR` statement, and
*   two distinct stories that have the same name.

In addition, the `read_from_*` methods of the `StoryFileReader` are all static. Therefore, we cannot count how often any story name has appeared without introducing a global variable, which is bad practice.

The ability to count and deduplicate story names is very desirable for the story structure validation tool [https://github.com/RasaHQ/rasa/issues/4088](https://github.com/RasaHQ/rasa/issues/4088).

**Overview of the Solution**: I have no idea. This is a discussion issue.

**Definition of Done**:

*   [ ] We have decided how to handle the described problems

**Comment by tmbo** [comment]
To make this possible I guess we'd need more precise `StoryStep`'s, e.g. a subclass for an `ORStoryStep`? probably also good to keep a reference to the training data source line

**Comment by m-vdb** [comment]
@JEM-Mosig given that #4088 is closed without us ever tackling this ticket, should we simply close this? Or is there another use case that we would like to address?

**Comment by eibhleag** [comment]
@degiz Does this fit into any of the Rasa 2.0 work we're doing?

**Comment by degiz** [comment]
This was not discussed in the scope of 2.0, but sounds like something to keep in mind while working on a training data format!
I'll add this issue to the "Nice to have" section of training data format doc.

**Comment by JEM-Mosig** [comment]
@degiz Since the story-structure-tool is a first step towards solving the Q2 blocker of reviewing conversations, I think this should definitely be in Rasa 2.0. Sorry for not pushing for this earlier.

**Comment by JEM-Mosig** [comment]
@degiz is story name access easier now / can we close this?

**Comment by degiz** [comment]
I don't think we've changed anything to make the count easier 😄 Let's keep it open.
