### ISSUE TITLE
Installer broken ?

### ISSUE THREAD

**Issue by sokoow** [RasaHQ/rasa#4965]
Trying to install rasa from your quickstart guide on Ubuntu Bionic, and getting this:

```
pip3 install rasa-x==0.23.4 --extra-index-url https://pypi.rasa.com/simple

...

Collecting tensorflow~=1.15.0 (from rasa~=1.5.1->rasa-x==0.23.4)
  Could not find a version that satisfies the requirement tensorflow~=1.15.0 (from rasa~=1.5.1->rasa-x==0.23.4) (from versions: 0.12.1, 1.0.0, 1.0.1, 1.1.0rc0, 1.1.0rc1, 1.1.0rc2, 1.1.0, 1.2.0rc0, 1.2.0rc1, 1.2.0rc2, 1.2.0, 1.2.1, 1.3.0rc0, 1.3.0rc1, 1.3.0rc2, 1.3.0, 1.4.0rc0, 1.4.0rc1, 1.4.0, 1.4.1, 1.5.0rc0, 1.5.0rc1, 1.5.0, 1.5.1, 1.6.0rc0, 1.6.0rc1, 1.6.0, 1.7.0rc0, 1.7.0rc1, 1.7.0, 1.7.1, 1.8.0rc0, 1.8.0rc1, 1.8.0, 1.9.0rc0, 1.9.0rc1, 1.9.0rc2, 1.9.0, 1.10.0rc0, 1.10.0rc1, 1.10.0, 1.10.1, 1.11.0rc0, 1.11.0rc1, 1.11.0rc2, 1.11.0, 1.12.0rc0, 1.12.0rc1, 1.12.0rc2, 1.12.0, 1.12.2, 1.12.3, 1.13.0rc0, 1.13.0rc1, 1.13.0rc2, 1.13.1, 1.13.2, 1.14.0rc0, 1.14.0rc1, 1.14.0, 2.0.0a0, 2.0.0b0, 2.0.0b1)
No matching distribution found for tensorflow~=1.15.0 (from rasa~=1.5.1->rasa-x==0.23.4)
```

Seems like a dependency missing ?

**Comment by erohmensing** [comment]
did you first `pip install -U pip`? (or i guess perhaps`pip3 install -U pip3` )

**Comment by sokoow** [comment]
yep that was it, thanks

**Comment by harisbitsakou** [comment]
Hello! I am trying to install the package following the instructions and using the following command:

pip install rasa-x --extra-index-url https://pypi.rasa.com/simple

, but I keep errors while installing which prohibit the package to be installed. The errors are the following :
 Building wheel for httptools (setup.py) ... error ERROR: Command errored out with exit status 1:...
ERROR: Failed building wheel for httptools...
 ERROR: Failed building wheel for ujson...

Could you please, let me know what am I doing wrong? 
Thank you very much for your answer in advance!
