### ISSUE TITLE
Improve readability of confusion matrix plot

### ISSUE THREAD

**Issue by degiz** [RasaHQ/rasa#4967]
**Description of Problem**: Originally proposed by @Ghostvv in #3549

Confusion matrix is unreadable (at least for core), color boxes and numbers are not aligned, also numbers overlay: [<span class="image-wrap" style="">![](https://user-images.githubusercontent.com/2385290/70790460-66305e80-1d95-11ea-8658-ff6ffd33c5e7.jpg)</span>](https://user-images.githubusercontent.com/2385290/70790460-66305e80-1d95-11ea-8658-ff6ffd33c5e7.jpg)

**Overview of the Solution**: Come up with proposal on how to improve readability of the plot

**Definition of Done**:

*   [ ] Tests are added
*   [ ] Feature mentioned in the changlog

**Comment by sara-tagger** [comment]
Thanks for submitting this feature request 🚀@akelad will get back to you about it soon!✨

**Comment by erohmensing** [comment]
Oops I guess I haven't added you to the tagger yet, it doesn't know you're one of us 😃
