### ISSUE TITLE
Isolate Matplotlib dependency 

### ISSUE THREAD

**Issue by degiz** [RasaHQ/rasa#4969]
**Description of Problem**:
Currently Matplotlib is imported globally in:
- rasa/nlu/test.py
- rasa/core/test.py
- tests/core/conftest.py

So we load Matplotlib every time we import something from rasa.nlu.test or rasa.core.test, even though we don't plan to plot anything.

So it can be imported only in the few functions that actually need it. 
That would allow us:

- mock/test these methods easier if needed in the future
- improve loading time a bit, since we'll import one library less

**Overview of the Solution**:
Refactor current usage of Matplotlib

**Definition of Done**:
- [ ] Tests are added
- [ ] Feature mentioned in the changlog

**Comment by sara-tagger** [comment]
Thanks for submitting this feature request 🚀@tabergma will get back to you about it soon!✨

**Comment by sara-tagger** [comment]
Thanks for submitting this feature request 🚀@dakshvar22 will get back to you about it soon!✨

**Comment by MichaelMarien** [comment]
I can take this up if no one has.

**Comment by tmbo** [comment]
@MichaelMarien yes that would be grea :+1:

**Comment by sanjaykrishnanrs** [comment]
@tmbo I was looking around to contribute. Did a triage on this issue. Looks like this issue has been resolved in previous issue fixes on due course of time. So we can close this issue.
- Should I raise PR for Triage process done by me? (not sure is there a process of getting credit of triage :D )

**Comment by pranavdurai10** [comment]
@degiz is this still open for contribution? Would like to take it up and contribute.

**Comment by degiz** [comment]
@pranavdurai10 seems like we've already resolved this. Thanks for bringing this up! Closing the issue.
