### ISSUE TITLE
What is correct format to connect rasa with psql using tracker I have issue with dialect

### ISSUE THREAD

**Issue by akjhaa007** [RasaHQ/rasa#4973]
I follow this blog https://rasa.com/docs/rasa/api/tracker-stores/
need to know adjact format of dialect

**Comment by sara-tagger** [comment]
Thanks for the question, our Github issue board is for **bugs and feature requests only,** though 😕
Please ask this question in the [forum✨](https://forum.rasa.com/c/rasa)

###### If you were describing a bug, please create a [report](https://github.com/RasaHQ/rasa/issues/new?labels=bug&template=bug_report.md) and fill out the template.
