### ISSUE TITLE
getiing error with SQLTracker in dialect 

### ISSUE THREAD

**Issue by akjhaa007** [RasaHQ/rasa#4974]
**Description of Problem**:
I am trying to connect my psql db with rasa using this https://rasa.com/docs/rasa/api/tracker-stores/
have some blocker with 
type: what it should be for psql
dialect "what is correct formate for psql
url :"is it necessary if yes tell me the correct url format "
db: database_name with table?
driver: it should be as it is or different
**Blockers** (if relevant):

**Comment by erohmensing** [comment]
This is not an enhancement request, but rather a usage question -- please ask it in our [forum](forum.rasa.com).
