### ISSUE TITLE
docs don't describe `entities` section in domain

### ISSUE THREAD

**Issue by wochinge** [RasaHQ/rasa#4975]
In the domain you can / have to have a list of entities:

```
slots:
  ...
intents:
  ... 
entities:
- entity1
- entity2
```

There is no example of this in the Rasa docs.

**Comment by devdeca** [comment]
Hello,
Before adding it to docs I'd like to know how it changes the model or training behavior(or if it doesn't).

**Comment by wochinge** [comment]
@akelad  This is important, no?
