### ISSUE TITLE
rasa.core.channels.slack  - Exception when trying to ha ndle message.

### ISSUE THREAD

**Issue by alebeta90** [RasaHQ/rasa#4979]
**Rasa version**:
Rasa 1.5.3

**Rasa SDK version**
rasa-sdk:1.5.1

**Rasa X version**
rasa-x:0.23.4

**Python version**:
Python 3.6.9 (Running Rasa official Docker Image)

**Operating system** (windows, osx, ...):
CentOS 7 nodes for Docker Swarm Cluster

**Issue**:

In some point of our conversation(Slack Channel) after a ScheduleReminder action, our bot is asking two questions to the user, after the user reply this questions, the bot ask again(using FormAction) and the bot is not waiting for user's answer, instead it is getting last user reply and set the slot for that action. We used action to reset slots and it is not working neither. The bot keep asking the FormActions and setting the same slot/answer till it reach a question where it should have an user answer(not FormAction). This problem only happens when using Slack channel, if we use interactive learning in Rasa X it is working properly and the same with the Rasa X option to share the bot, it is possible to talk with the bot and everything is fine.

I had been asking in the forum, but no luck yet

Forum link: https://forum.rasa.com/t/usert-enter-random-message-and-continue-with-predifined-utter/21937

**Error (including full traceback)**:
```
2019-12-16 11:03:37 ERROR    rasa.core.channels.slack  - Exception when trying to ha
ndle message.
2019-12-16 11:03:37 ERROR    rasa.core.channels.slack  - 
Traceback (most recent call last):
  File "/build/lib/python3.6/site-packages/rasa/core/channels/slack.py", line 307, i
n process_message
    await on_new_message(user_msg)
  File "/usr/local/lib/python3.6/asyncio/coroutines.py", line 129, in throw
    return self.gen.throw(type, value, traceback)
  File "/build/lib/python3.6/site-packages/rasa/core/channels/channel.py", line 82, 
in handler
    await app.agent.handle_message(*args, **kwargs)
  File "/usr/local/lib/python3.6/asyncio/coroutines.py", line 129, in throw
    return self.gen.throw(type, value, traceback)
  File "/build/lib/python3.6/site-packages/rasa/core/agent.py", line 485, in handle_
message
    async with self.lock_store.lock(message.sender_id):
  File "/usr/local/lib/python3.6/asyncio/coroutines.py", line 129, in throw
    return self.gen.throw(type, value, traceback)
  File "/build/lib/python3.6/site-packages/async_generator/_util.py", line 34, in __
aenter__
    return await self._agen.asend(None)
  File "/build/lib/python3.6/site-packages/rasa/core/lock_store.py", line 115, in lo
ck
    conversation_id, ticket, wait_time_in_seconds
  File "/usr/local/lib/python3.6/asyncio/coroutines.py", line 129, in throw
    return self.gen.throw(type, value, traceback)
  File "/build/lib/python3.6/site-packages/rasa/core/lock_store.py", line 143, in _a
cquire_lock
    await asyncio.sleep(wait_time_in_seconds)
  File "/usr/local/lib/python3.6/asyncio/tasks.py", line 482, in sleep
    return (yield from future)
concurrent.futures._base.CancelledError
```

**Command or request that led to error**:
```
{"sender_id": "UMAAQ4QTB", "event": "user", "timestamp": 1576494212.3010159, "text":
 "ja", "parse_data": {"intent": {"name": "utter_positive_answer", "confidence": 0.8873927593231201}, "entities": [], "intent_ranking": [
{"name": "utter_positive_answer", "confidence": 0.8873927593231201}, {"name": "test_s3", "confidence": 0.008611131459474564}, {"name": "
utter_no_difference", "confidence": 0.008563085459172726}, {"name": "utter_im_thankful_for", "confidence": 0.008091296069324017}, {"name
": "utter_email", "confidence": 0.006594611797481775}, {"name": "utter_cant_be_glad", "confidence": 0.0063270037062466145}, {"name": "ut
ter_what_we_can_change", "confidence": 0.005936738569289446}, {"name": "test_s4", "confidence": 0.005273961462080479}, {"name": "utter_i
m_happy_if", "confidence": 0.005174669902771711}, {"name": "utter_nothing_positiv_self", "confidence": 0.005160031374543905}], "text": "
ja"}, "input_channel": "slack", "message_id": "8cbb2c45cc1a4bbc81eb38a1d87d068e", "metadata": {}}

```

This is the last user message, that is being used by as slot(though it is not an slot) later on by the bot.

**Content of configuration file (config.yml)** (if relevant):
```yml
language: de
pipeline: supervised_embeddings
policies:
- name: AugmentedMemoizationPolicy
- name: MappingPolicy
- name: FormPolicy
```

**Comment by sara-tagger** [comment]
Thanks for raising this issue, @rgstephens will get back to you about it soon✨

###### Please also check out the [docs](https://rasa.com/docs/) and the [forum](https://forum.rasa.com/) in case your issue was raised there too 🤗

**Comment by alebeta90** [comment]
Hi @rgstephens 

If you need more information to help debug this issue, please let me know.

thanks

**Comment by rgstephens** [comment]
I'm closing this to the forum. Would need more details to confirm an issue with the Slack channel.

**Comment by alebeta90** [comment]
Hi,

problem still persist, in the lates version of Rasa and Rasa X. Conversation had been tested using  Socket.io and it is working properly.

It seems to be isolated to Slack Channel how it handle the tracker?
