### ISSUE TITLE
Telegram KeyboardButton() update to access "get_location" and "get_contact" flags

### ISSUE THREAD

**Issue by GauravRoy48** [RasaHQ/rasa#4982]
**Description of Problem**:
 
Cannot add "request_contact" and "request_location" flags to the KeyboardButton() in **_rasa/rasa/core/channels/telegram.py_**
**Reference**: https://core.telegram.org/bots/api#keyboardbutton

**Overview of the Solution**:

Replace the following lines from line number **77**:

`

        elif button_type == "reply":
            button_list = []
            for bttn in buttons:
                if isinstance(bttn, list):
                    button_list.append([KeyboardButton(s["title"]) for s in bttn])
                else:
                    button_list.append([KeyboardButton(bttn["title"])])
            reply_markup = ReplyKeyboardMarkup(
                button_list, resize_keyboard=True, one_time_keyboard=True
            )
`

with the following lines:
`

        elif button_type == "reply":
            button_list = []
            for bttn in buttons:
                if isinstance(bttn, list):
                    for s in bttn:
                        location_flag = False
                        contact_flag = False
                        try:
                            location_flag = s["request_location"]
                        except Exception as e:
                            logger.error("request_location not defined. Using default value of False.")
                        try:
                            contact_flag = s["request_contact"]
                        except Exception as e:
                            logger.error("request_contact not defined. Using default value of False.")
                        button_list.append([KeyboardButton(s["title"],contact_flag,location_flag)])
                else:
                    location_flag = False
                    contact_flag = False
                    try:
                        location_flag = bttn["request_location"]
                    except Exception as e:
                        logger.error("request_location not defined. Using default value of False.")
                    try:
                        contact_flag = bttn["request_contact"]
                    except Exception as e:
                        logger.error("request_contact not defined. Using default value of False.")
                    button_list.append([KeyboardButton(bttn["title"],contact_flag,location_flag)])
            reply_markup = ReplyKeyboardMarkup(
                button_list, resize_keyboard=True, one_time_keyboard=True
            )
`

**Examples** (if relevant):

**Blockers** (if relevant):

**Definition of Done**:
Basic testing done.

**Comment by sara-tagger** [comment]
Thanks for submitting this feature request 🚀@JustinaPetr will get back to you about it soon!✨

**Comment by JustinaPetr** [comment]
Hi @GauravRoy48. Apologies on my super late response on this. Improvements on the connectors are always welcome from our community. Would you be up for opening a PR with your proposed improvements?

**Comment by GauravRoy48** [comment]
Yes sure, I'm up for it.

**Comment by JustinaPetr** [comment]
Awesome. I'll close the issue for now then :)
