### ISSUE TITLE
How do i get headers values passed to RASA

### ISSUE THREAD

**Issue by sanjaykhanssk** [RasaHQ/rasa#4987]
I building a app where the rasa will be microservice, that need to communicate to  my flask app , I need to keep the token in the headers so that I can pass headers from **frontend -> Rasa -> Flask.** 
so that ** , I need access the token passed to the headers of my rasa server**
like i need to access the token in some other file.

**Comment by sara-tagger** [comment]
Thanks for the question, our Github issue board is for **bugs and feature requests only,** though 😕
Please ask this question in the [forum✨](https://forum.rasa.com/c/rasa)

###### If you were describing a bug, please create a [report](https://github.com/RasaHQ/rasa/issues/new?labels=bug&template=bug_report.md) and fill out the template.
