### ISSUE TITLE
improve error message for Requested URL /webhooks/<channel>/webhook not found

### ISSUE THREAD

**Issue by erohmensing** [RasaHQ/rasa#4988]
If when a user changes the credentials.yml to add theirs, and they happen to overwrite the rasa credentials, talk to your bot will stop working. We should give a nicer error message that points the user to check their credentials when they get this traceback:
```
rasa-production_1 | [2019-12-18 03:49:11 +0000] [1] [ERROR] Exception occurred while handling uri: ‘http://rasa-production:5005/webhooks/rasa/webhook’
rasa-production_1 | Traceback (most recent call last):
rasa-production_1 | File “/build/lib/python3.6/site-packages/sanic/app.py”, line 918, in handle_request
rasa-production_1 | handler, args, kwargs, uri = self.router.get(request)
rasa-production_1 | File “/build/lib/python3.6/site-packages/sanic/router.py”, line 407, in get
rasa-production_1 | return self._get(request.path, request.method, “”)
rasa-production_1 | File “/build/lib/python3.6/site-packages/sanic/router.py”, line 470, in _get
rasa-production_1 | raise NotFound(“Requested URL {} not found”.format(url))
rasa-production_1 | sanic.exceptions.NotFound: Requested URL /webhooks/rasa/webhook not found
rasa-x_1 | ERROR:rasax.community.api.blueprints.stack:Failed to send message to Rasa Chat webhook. Error: 404, Not Found, body=‘b’Error: Requested URL /webhooks/rasa/webhook not found’’
```
Thread: https://forum.rasa.com/t/default-docker-compose-no-data-in-rasa-x/22575/4

Edit: we should do this on all the channels, and it lives in the connectors, so moved to rasa repository.

**Comment by melindaloubser1** [comment]
@erohmensing  this doesn't seem to be an issue when run in localmode - no rasa credentials, it still runs. Also not sure about `we should do this on all the channels, and it lives in the connectors` - meaning the connectors will all look for the rasa credentials?

**Comment by melindaloubser1** [comment]
@erohmensing just seeing this again - can you reproduce it still?

**Comment by mishra011** [comment]
I am having same issue. **Failed to send message to Rasa Chat webhook. Error: 401, message='Unauthorized', url=URL('http://rasa-production:5005/webhooks/rasa/webhook')**

**Comment by melindaloubser1** [comment]
@mishra011 what do your credentials look like?

**Comment by mishra011** [comment]
@melindaloubser1  my credentials.yml looks like following?

rasa:
  url: ${RASA_X_HOST}/api

**Comment by TyDunn** [comment]
@melindaloubser1 @erohmensing were you able to reproduce?

**Comment by melindaloubser1** [comment]
Checking again now, could not reproduce before

**Comment by TyDunn** [comment]
Then maybe close?

**Comment by melindaloubser1** [comment]
Yes I think so
