### ISSUE TITLE
Cannot disable CORS protection

### ISSUE THREAD

**Issue by juanmariareina** [RasaHQ/rasa#4997]
Hi, all!

We just trying to connect from our web portal (in our development enviroment) to our RASA (also in our development enviroment, not the same server)

Rasa is started as following:

rasa run -m models --enable-api --cors ["*"]

So, when we try to connect from our portal, the following error is shown:

Access to fetch at 'http://172.23.0.47:5005/conversations/0a6cf190-26a2-46b7-9f2c-ca00ba097d0c/messages' from origin 'http://localhost:8080' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.

**Comment by erohmensing** [comment]
Hi @juanmariareina, does it work if you remove the brackets?
```
rasa run -m models --enable-api --cors "*"
```

**Comment by juanmariareina** [comment]
Honestly, I don't understand what is happening. I did what you suggested, and it worked, but...
I had to restart server and now what I'm seeing is this:

rasa run -m models --enable-api --cors "*"
No chat connector configured, falling back to the REST input channel. To connect your bot to another channel, read the docs here: https://rasa.com/docs/rasa/user-guide/messaging-and-voice-channels

**Comment by juanmariareina** [comment]
Well, it works!

I'd swear I've tried with and without brackets, before open this issue. I've only have to fix the redis connection... Does it have something to do with my problem?

**Comment by erohmensing** [comment]
No idea, i don't think redis should interact with it at all 😄
