### ISSUE TITLE
Is https://rasa.com/docs/ available to edit?

### ISSUE THREAD

**Issue by Jason-2020** [RasaHQ/rasa#4999]
**Description of Problem**:
Is https://rasa.com/docs/ docs available to edit? I assume https://github.com/RasaHQ/rasa/tree/master/docs is not the one on the website.
 I just wasted couple of days trying to setup Rasa on Windows 10 machine. Everytime I hit some error, I've found some workarounds here and there but I believe this should be documented on official docs. For example, Rasa requires Nvidia Cuda? Then I downloaded latest Nvidia Cuda toolkit. But after downloading 2GB huge file I just realized it required old version of CUDA 10.0 etc..

**Comment by erohmensing** [comment]
> I assume https://github.com/RasaHQ/rasa/tree/master/docs is not the one on the website.

why do you assume that? That is where all the suggest edit links go, and indeed is what goes on the website. (well technically those docs go to the https://rasa.com/docs/rasa/master/ docs and the branch of the latest tag is the main page documentation, but you get the point)

**Comment by Jason-2020** [comment]
Okay. Is it possible to add "Edit this page on Github" button? It would be much easier to find relevant pages.

**Comment by erohmensing** [comment]
At the top of that page, there is a `Suggest Edits` button under the header.

**Comment by Jason-2020** [comment]
Oh I see. I'm blind :angry:

**Comment by erohmensing** [comment]
No problem 😄maybe we should make it bigger
