### ISSUE TITLE
Explain in documentation that lookup table names do not need to match entity name

### ISSUE THREAD

**Issue by ArjaanBuijk** [RasaHQ/rasa#5003]
For clarity, it is good to repeat in the lookup table description the same explanation as is given for the regex description:

```
The name doesn't define the entity nor the intent, it is just a human readable 
description for you to remember what this lookup is used for and is the title of 
the corresponding pattern feature.
```

**Comment by zoka123** [comment]
Yeah, this could be clarified a little bit in the docs, since the name itself doesn't really make Rasa realize these are lookup values for that specific entity
