### ISSUE TITLE
FormActions `run` is not async

### ISSUE THREAD

**Issue by tahamr83** [RasaHQ/rasa#5005]
**Rasa version**:
rasa==1.6.0
**Rasa SDK version** (if used & relevant):
rasa-sdk==1.6.0
**Rasa X version** (if used & relevant):

**Python version**:
3.6.6
**Operating system** (windows, osx, ...):

**Issue**:
Apparently the FormAction's run is not defined as an async function. Is that left out deliberately?

**Error (including full traceback)**:
```

```

**Command or request that led to error**:
```

```

**Content of configuration file (config.yml)** (if relevant):
```yml

```

**Content of domain file (domain.yml)** (if relevant):
```yml

```

**Comment by sara-tagger** [comment]
Thanks for the issue, @amn41 will get back to you about it soon!

###### You may find help in the [docs](https://rasa.com/docs/) and the [forum,](https://forum.rasa.com/) too 🤗

**Comment by alex-ubitec** [comment]
Any updates on this?

**Comment by erohmensing** [comment]
Fixed in https://github.com/RasaHQ/rasa-sdk/pull/142
