### ISSUE TITLE
Google Hangouts Chat connector

### ISSUE THREAD

**Issue by muelerma** [RasaHQ/rasa#5006]
**Description of Problem**:
Currently Rasa is lacking an out-of-the-box Google Hangouts Chat integration. A few requests have been made in the forum for this (see [here](https://forum.rasa.com/t/is-it-possible-for-rasa-to-integrate-with-facebook-workplace-and-google-hangouts/4766) and [here](https://forum.rasa.com/t/google-hangouts/11653)), and in general Hangouts Chat is quite popular for internal company communication, so there might be future users interested in this.

**Overview of the Solution**:
We implemented a custom connector to integrate Rasa bots into our company chat, which is capable of sending text as well as interactive cards to Hangouts Chat users, in rooms and direct messages. Bots can also react to being added to spaces. 
It is implemented much like the standard rest channel and works in synchronous mode (i.e. simple request -> response architecture). Input and output channel mainly extract relevant content from the requests and bring the response in the required format, respectively. Authentication against the Hangouts Chat API is optional, therefore the implementation is very lightweight and has few dependencies. Please see the [Hangouts docs](https://developers.google.com/hangouts/chat) for more information.

**Definition of Done**:
- [ ] Input and output channel implemented
- [ ] Tests are added
- [ ] Feature described the docs
- [ ] Feature mentioned in the changelog

**Comment by sara-tagger** [comment]
Thanks for submitting this feature request 🚀@akelad will get back to you about it soon!✨
