### ISSUE TITLE
Rasa and Rasa-x not installing on ubuntu

### ISSUE THREAD

**Issue by ArthurPieri** [RasaHQ/rasa#5014]
## System
Ubuntu 19.10
Processor Intel Core 15-3337U

## Command
Runing the command:
```sh
$ pip install rasa-x --extra-index-url https://pypi.rasa.com/simple
```
After runing normaly from some time, it gives the following error:

## Error
```py
Collecting tensorflow~=1.15.0 (from rasa)
  Could not find a version that satisfies the requirement tensorflow~=1.15.0 (from rasa) (from versions: 1.13.0rc1, 1.13.0rc2, 1.13.1, 1.13.2, 1.14.0rc0, 1.14.0rc1, 1.14.0, 2.0.0a0, 2.0.0b0, 2.0.0b1)
No matching distribution found for tensorflow~=1.15.0 (from rasa)
```

**Comment by erohmensing** [comment]
Please upgrade pip: `pip install -U pip`

**Comment by erohmensing** [comment]
@ArthurPieri did that fix it?

**Comment by ArthurPieri** [comment]
> @ArthurPieri did that fix it?

No, after upgrading pip it broke python on my computer, so I had to reinstall Ubuntu. Trying again in a few hours.

**Comment by erohmensing** [comment]
Okay. the pip version should be >= 19.0

**Comment by ArthurPieri** [comment]
So, I installed a VM with ubuntu 18.04, and now I think the problem is with pip, as the following images show:

![IMG_20191228_180554_948](https://user-images.githubusercontent.com/19278543/71549480-eca38d80-299c-11ea-8602-e3cc6b52cf99.jpg)
![IMG_20191228_180559_023](https://user-images.githubusercontent.com/19278543/71549481-eca38d80-299c-11ea-8f99-bddc03986ed5.jpg)

I tried running:
```sh
pip install -U pip 
and 
pip3 install -U pip 
and 
pip3 install -U pip3
```
And pip breaks everytime

**Comment by erohmensing** [comment]
Have you looked up this import error?  https://github.com/pypa/pip/issues/5599

**Comment by ArthurPieri** [comment]
No, I have not looked helped me fixing it, what I had to do was:
1. Uninstall python-pip
```sh
$ sudo apt remove pyhton-pip
```
2. Install Python3-pip
```sh
$ sudo apt install python3-pip
```
3. Upgrade pip using python3 -m
```sh
$ python3 -m pip install --user --upgrade pip
```
4. Install rasa using python3-m
```sh
$ python3 -m pip install --user rasa 
```

Thank you very much. I can use Rasa now!

**Comment by erohmensing** [comment]
Wow, a bit of a complicated road! I'm glad you got it working 😄 good work!
