### ISSUE TITLE
Wrong Mapping: Right intent but wrong entities

### ISSUE THREAD

**Issue by GTroxx55** [RasaHQ/rasa#5018]
Hey Guys,
So I am only using rasa_nlu, I have enough training examples approx 20 for each intent and entities. These examples are primarily the output of linux shell commands. My issue is that my model classifies the correct intent say "intent1" but maps it with different entity name though the entity value is correct.
For example:
suppose there are 2 intents "intent1" and "intent2" with respective entities "entity1" and "entity2" with values "1234" and "5432" respectively.
so the correct output should be
intent1:{entities:["entity1"="1234"]}              intent2:{entities:["entity2"="5432"]} 
but instead it comes out be
intent1:{entities:["entity1"="5432"] or intent1:{entities:["entity2"="1234"]}
How can I resolve this?
I have looked into domain.yaml  but that is for rasa core...furthermore can this be resolved by using custom component...
This is my pipeline
language: "en_core_web_md"
pipeline:
- name: "SpacyNLP"
- name: "SpacyTokenizer"
- name: "SpacyFeaturizer"
- name: "CRFEntityExtractor"
- name: "SklearnIntentClassifier"

**Comment by sara-tagger** [comment]
Thanks for the question, our Github issue board is for **bugs and feature requests only,** though 😕
Please ask this question in the [forum✨](https://forum.rasa.com/c/rasa)

###### If you were describing a bug, please create a [report](https://github.com/RasaHQ/rasa/issues/new?labels=bug&template=bug_report.md) and fill out the template.
