### ISSUE TITLE
Experienced exception while trying to serve

### ISSUE THREAD

**Issue by apt-x4869** [RasaHQ/rasa#5020]
After running my train_online.py file , I get the following Error

/usr/local/lib/python3.7/dist-packages/rasa_core/__init__.py:12: UserWarning: The 'rasa_core' package has been renamed. You should change your imports to use 'rasa.core' instead.
  UserWarning,
INFO:rasa.nlu.components:Added 'SpacyNLP' to component cache. Key 'SpacyNLP-en'.
WARNING:rasa.core.domain:Deprecated: Templates should not be strings anymore. Utterance template 'utter_greet' should contain either '- text: ' or '- custom: ' attribute to be a proper template.
WARNING:rasa.core.domain:Deprecated: Templates should not be strings anymore. Utterance template 'utter_goodbye' should contain either '- text: ' or '- custom: ' attribute to be a proper template.
WARNING:rasa.core.domain:Deprecated: Templates should not be strings anymore. Utterance template 'utter_goodbye' should contain either '- text: ' or '- custom: ' attribute to be a proper template.
WARNING:rasa.core.domain:Deprecated: Templates should not be strings anymore. Utterance template 'utter_ask_location' should contain either '- text: ' or '- custom: ' attribute to be a proper template.
WARNING:rasa.core.interpreter:Tried to create NLU interpreter from '<rasa_core.interpreter.RasaNLUInterpreter object at 0x7fcefb1f7050>', which is not possible.Using RegexInterpreter instead.
DEBUG:rasa.core.training.generator:Generated trackers will be deduplicated based on their unique last 5 states.
DEBUG:rasa.core.training.generator:Number of augmentation rounds is 3
DEBUG:rasa.core.training.generator:Starting data generation round 0 ... (with 1 trackers)
Processed Story Blocks: 100%|████████████████| 10/10 [00:00<00:00, 2516.53it/s, # trackers=1]
DEBUG:rasa.core.training.generator:Finished phase (3 training samples found).
DEBUG:rasa.core.training.generator:Data generation rounds finished.
DEBUG:rasa.core.training.generator:Found 0 unused checkpoints
DEBUG:rasa.core.training.generator:Starting augmentation round 0 ... (with 3 trackers)
Processed Story Blocks: 100%|████████████████| 10/10 [00:00<00:00, 1651.69it/s, # trackers=3]
DEBUG:rasa.core.training.generator:Finished phase (12 training samples found).
DEBUG:rasa.core.training.generator:Starting augmentation round 1 ... (with 12 trackers)
Processed Story Blocks: 100%|█████████████████| 10/10 [00:00<00:00, 904.22it/s, # trackers=6]
DEBUG:rasa.core.training.generator:Finished phase (27 training samples found).
DEBUG:rasa.core.training.generator:Starting augmentation round 2 ... (with 20 trackers)
Processed Story Blocks: 100%|█████████████████| 10/10 [00:00<00:00, 820.05it/s, # trackers=6]
DEBUG:rasa.core.training.generator:Finished phase (42 training samples found).
DEBUG:rasa.core.training.generator:Found 42 training trackers.
DEBUG:rasa.core.training.generator:Subsampled to 39 augmented training trackers.
DEBUG:rasa.core.training.generator:There are 3 original trackers.
DEBUG:rasa_core.agent:Agent trainer got kwargs: {}
DEBUG:rasa.core.featurizers:Creating states and action examples from collected trackers (by MaxHistoryTrackerFeaturizer(BinarySingleStateFeaturizer))...
Processed trackers: 100%|█████████████████████| 42/42 [00:00<00:00, 847.55it/s, # actions=39]
DEBUG:rasa.core.featurizers:Created 39 action examples.
2019-12-28 12:57:05.283193: I tensorflow/core/platform/cpu_feature_guard.cc:141] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
2019-12-28 12:57:05.304507: I tensorflow/core/platform/profile_utils/cpu_utils.cc:94] CPU Frequency: 2712000000 Hz
2019-12-28 12:57:05.305815: I tensorflow/compiler/xla/service/service.cc:150] XLA service 0x5960360 executing computations on platform Host. Devices:
2019-12-28 12:57:05.305853: I tensorflow/compiler/xla/service/service.cc:158]   StreamExecutor device (0): <undefined>, <undefined>
WARNING:tensorflow:From /usr/local/lib/python3.7/dist-packages/tensorflow/python/ops/resource_variable_ops.py:435: colocate_with (from tensorflow.python.framework.ops) is deprecated and will be removed in a future version.
Instructions for updating:
Colocations handled automatically by placer.
WARNING:tensorflow:From /usr/local/lib/python3.7/dist-packages/tensorflow/python/ops/resource_variable_ops.py:435: colocate_with (from tensorflow.python.framework.ops) is deprecated and will be removed in a future version.
Instructions for updating:
Colocations handled automatically by placer.
WARNING:tensorflow:From /usr/local/lib/python3.7/dist-packages/tensorflow/python/keras/backend.py:4010: calling dropout (from tensorflow.python.ops.nn_ops) with keep_prob is deprecated and will be removed in a future version.
Instructions for updating:
Please use `rate` instead of `keep_prob`. Rate should be set to `rate = 1 - keep_prob`.
WARNING:tensorflow:From /usr/local/lib/python3.7/dist-packages/tensorflow/python/keras/backend.py:4010: calling dropout (from tensorflow.python.ops.nn_ops) with keep_prob is deprecated and will be removed in a future version.
Instructions for updating:
Please use `rate` instead of `keep_prob`. Rate should be set to `rate = 1 - keep_prob`.
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
=================================================================
masking (Masking)            (None, 5, 17)             0         
_________________________________________________________________
lstm (LSTM)                  (None, 32)                6400      
_________________________________________________________________
dense (Dense)                (None, 12)                396       
_________________________________________________________________
activation (Activation)      (None, 12)                0         
=================================================================
Total params: 6,796
Trainable params: 6,796
Non-trainable params: 0
_________________________________________________________________
INFO:rasa.core.policies.keras_policy:Fitting model with 39 total samples and a validation split of 0.1
DEBUG:rasa.core.policies.policy:Parameters ignored by `model.fit(...)`: {'btach_size': 50, 'max_training_samples': 300}
WARNING:tensorflow:From /usr/local/lib/python3.7/dist-packages/tensorflow/python/ops/math_ops.py:3066: to_int32 (from tensorflow.python.ops.math_ops) is deprecated and will be removed in a future version.
Instructions for updating:
Use tf.cast instead.
WARNING:tensorflow:From /usr/local/lib/python3.7/dist-packages/tensorflow/python/ops/math_ops.py:3066: to_int32 (from tensorflow.python.ops.math_ops) is deprecated and will be removed in a future version.
Instructions for updating:
Use tf.cast instead.
Epoch 1/200
39/39 [==============================] - 0s 13ms/sample - loss: 2.5385 - acc: 0.0769
Epoch 2/200
39/39 [==============================] - 0s 178us/sample - loss: 2.4647 - acc: 0.2051
Epoch 3/200
39/39 [==============================] - 0s 174us/sample - loss: 2.4220 - acc: 0.2308
.
.
.
Epoch 195/200
39/39 [==============================] - 0s 184us/sample - loss: 0.3655 - acc: 0.9231
Epoch 196/200
39/39 [==============================] - 0s 177us/sample - loss: 0.3370 - acc: 0.9487
Epoch 197/200
39/39 [==============================] - 0s 208us/sample - loss: 0.3271 - acc: 0.9487
Epoch 198/200
39/39 [==============================] - 0s 272us/sample - loss: 0.3666 - acc: 0.8974
Epoch 199/200
39/39 [==============================] - 0s 174us/sample - loss: 0.3603 - acc: 0.9231
Epoch 200/200
39/39 [==============================] - 0s 170us/sample - loss: 0.3340 - acc: 0.9231
INFO:rasa.core.policies.keras_policy:Done fitting keras policy model
DEBUG:rasa.core.featurizers:Creating states and action examples from collected trackers (by MaxHistoryTrackerFeaturizer(SingleStateFeaturizer))...
Processed trackers: 100%|██████████████████████| 3/3 [00:00<00:00, 2118.34it/s, # actions=16]
DEBUG:rasa.core.featurizers:Created 16 action examples.
Processed actions: 16it [00:00, 11783.82it/s, # examples=16]
DEBUG:rasa.core.policies.memoization:Memorized 16 unique examples.
DEBUG:rasa.core.utils:Available web server routes: 
/conversations/<conversation_id>/messages          POST                           add_message
/conversations/<conversation_id>/tracker/events    POST                           append_event
/model/test/intents                                POST                           evaluate_intents
/model/test/stories                                POST                           evaluate_stories
/conversations/<conversation_id>/execute           POST                           execute_action
/domain                                            GET                            get_domain
/                                                  GET                            hello
/model                                             PUT                            load_model
/model/parse                                       POST                           parse
/conversations/<conversation_id>/predict           POST                           predict
/conversations/<conversation_id>/tracker/events    PUT                            replace_events
/conversations/<conversation_id>/story             GET                            retrieve_story
/conversations/<conversation_id>/tracker           GET                            retrieve_tracker
/status                                            GET                            status
/model/predict                                     POST                           tracker_predict
/model/train                                       POST                           train
/model                                             DELETE                         unload_model
/version                                           GET                            version
INFO:root:Enabling coroutine debugging. Loop id 160031312.
[2019-12-28 12:57:08 +0530] [9410] [ERROR] Experienced exception while trying to serve
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/sanic/app.py", line 1096, in run
    serve(**server_settings)
  File "/usr/local/lib/python3.7/dist-packages/sanic/server.py", line 742, in serve
    trigger_events(before_start, loop)
  File "/usr/local/lib/python3.7/dist-packages/sanic/server.py", line 604, in trigger_events
    loop.run_until_complete(result)
  File "uvloop/loop.pyx", line 1456, in uvloop.loop.Loop.run_until_complete
  File "/usr/local/lib/python3.7/dist-packages/rasa/core/training/interactive.py", line 1481, in train_agent_on_start
    args.get("config")[0],
TypeError: 'NoneType' object is not subscriptable
Traceback (most recent call last):
  File "2.py", line 36, in <module>
    run_weather_online(nlu_interpreter)
  File "2.py", line 29, in run_weather_online
    interactive.run_interactive_learning(agent)
  File "/usr/local/lib/python3.7/dist-packages/rasa/core/training/interactive.py", line 1555, in run_interactive_learning
    _serve_application(app, stories, finetune, skip_visualization)
  File "/usr/local/lib/python3.7/dist-packages/rasa/core/training/interactive.py", line 1434, in _serve_application
    app.run(host="0.0.0.0", port=DEFAULT_SERVER_PORT)
  File "/usr/local/lib/python3.7/dist-packages/sanic/app.py", line 1096, in run
    serve(**server_settings)
  File "/usr/local/lib/python3.7/dist-packages/sanic/server.py", line 742, in serve
    trigger_events(before_start, loop)
  File "/usr/local/lib/python3.7/dist-packages/sanic/server.py", line 604, in trigger_events
    loop.run_until_complete(result)
  File "uvloop/loop.pyx", line 1456, in uvloop.loop.Loop.run_until_complete
  File "/usr/local/lib/python3.7/dist-packages/rasa/core/training/interactive.py", line 1481, in train_agent_on_start
    args.get("config")[0],
TypeError: 'NoneType' object is not subscriptable

My file train_online.py looks like this:
from __future__ import absolute_import
from __future__ import division
from __future__ import print_function
from __future__ import unicode_literals
import asyncio

import logging

from rasa_core.agent import Agent
from rasa_core.policies.keras_policy import KerasPolicy
from rasa_core.policies.memoization import MemoizationPolicy
from rasa_core.interpreter import NaturalLanguageInterpreter
from rasa_core.training import interactive
from rasa.utils.endpoints import EndpointConfig
from rasa_core import config as policy_config

logger = logging.getLogger(__name__)

def run_weather_online(interpreter,
                          domain_file="weather_domain.yml",
                          training_data_file='data/stories.md'):
    policies2 = policy_config.load("config.yml")
    action_endpoint = "endpoint.yml"					  
    agent = Agent(domain_file,policies=policies2,interpreter=interpreter,action_endpoint=action_endpoint)
    				  
    data = asyncio.run(agent.load_data(training_data_file))			   
    agent.train(data)
    interactive.run_interactive_learning(agent)
    return agent

if __name__ == '__main__':
    logging.basicConfig(level="DEBUG")
    nlu_interpreter = NaturalLanguageInterpreter.create('./models/nlu/weathernlu')
    run_weather_online(nlu_interpreter)

**Comment by JulianGerhard21** [comment]
Hi @apt-x4869 ,

can you provide more information about the version of `rasa`, `rasa sdk` and your `OS` please? 

Regards
Julian

**Comment by apt-x4869** [comment]
> Hi @apt-x4869 ,
> 
> can you provide more information about the version of `rasa`, `rasa sdk` and your `OS` please?
> 
> Regards
> Julian




rasa==1.6
rasa_sdk=0.12.1
os== kali linux 2019.4
bot is not loading even when server is running
![Screenshot from 2019-12-28 20-26-16](https://user-images.githubusercontent.com/55894766/71545535-27fc8700-29b2-11ea-933b-a88287c88ed4.png)
train_online.py code:
![Screenshot from 2019-12-28 20-42-46](https://user-images.githubusercontent.com/55894766/71545564-99d4d080-29b2-11ea-8bbc-d480097631c5.png)

**Comment by sara-tagger** [comment]
Thanks for the question, our Github issue board is for **bugs and feature requests only,** though 😕
Please ask this question in the [forum✨](https://forum.rasa.com/c/rasa)

###### If you were describing a bug, please create a [report](https://github.com/RasaHQ/rasa/issues/new?labels=bug&template=bug_report.md) and fill out the template.
