### ISSUE TITLE
asyncio error

### ISSUE THREAD

**Issue by sarthak-sriw** [RasaHQ/rasa#5022]
hey while executing train_init.py i got following error

  from ._conv import register_converters as _register_converters
Processed Story Blocks: 100%|██████████████████████████████████████████| 10/10 [00:00<00:00, 1986.13it/s, # trackers=1]
Processed Story Blocks: 100%|██████████████████████████████████████████| 10/10 [00:00<00:00, 1004.21it/s, # trackers=3]
Processed Story Blocks: 100%|███████████████████████████████████████████| 10/10 [00:00<00:00, 665.40it/s, # trackers=6]
Processed Story Blocks: 100%|███████████████████████████████████████████| 10/10 [00:00<00:00, 666.96it/s, # trackers=6]
Traceback (most recent call last):
  File "train_init.py", line 22, in <module>
    data=loop.run_until_complete(agent.load_data(training_data_file))
  File "C:\Users\Sarthak\Anaconda3\lib\asyncio\base_events.py", line 447, in run_until_complete
    future = tasks.ensure_future(future, loop=self)
  File "C:\Users\Sarthak\Anaconda3\lib\asyncio\tasks.py", line 526, in ensure_future
    raise TypeError('An asyncio.Future, a coroutine or an awaitable is '
TypeError: An asyncio.Future, a coroutine or an awaitable is required

I am using windows 10 , python version 3.6.2, using all latest version of rasa

![Screenshot (67)](https://user-images.githubusercontent.com/53507883/71548858-5726ee80-29da-11ea-8968-5ec8943ba42f.png)

**Comment by AkshatJoshi2000** [comment]
The "async" function will notify python that it is a coroutine, which at the moment is missing from your code.

**Try this:**

`from __future__ import absolute_import, division, unicode_literals
import logging
import asyncio
from rasa_core.agent import Agent
from rasa_core.policies.keras_policy import KerasPolicy
from rasa_core.policies.memoization import MemoizationPolicy

training_data_file = './data/stories.md'
agent = Agent('domain.yml', policies = [MemoizationPolicy(), KerasPolicy(augmentation_factor = 50,
											      max_history = 5,							 
                                                                                              epochs = 1000, validation_split = 0.2)])

async def agent_run():
	training_set = agent.load_data(training_data_file)
	return training_set

if __name__ == '__main__':
	logging.basicConfig(level='INFO')
	model_path = './models/dialogue'
	loop = asyncio.get_event_loop()
	data = loop.run_until_complete(agent_run())
	agent.train(data)
	agent.persist(model_path)
`

**Comment by sara-tagger** [comment]
Thanks for the question, our Github issue board is for **bugs and feature requests only,** though 😕
Please ask this question in the [forum✨](https://forum.rasa.com/c/rasa)

###### If you were describing a bug, please create a [report](https://github.com/RasaHQ/rasa/issues/new?labels=bug&template=bug_report.md) and fill out the template.
