### ISSUE TITLE
rasa init --no-prompt gives the following error in windows 8.1

### ISSUE THREAD

**Issue by Dhiraj240** [RasaHQ/rasa#5028]
```
Traceback (most recent call last):
  File "c:\users\lenovo\appdata\local\programs\python\python36\Lib\runpy.py",
ne 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\users\lenovo\appdata\local\programs\python\python36\Lib\runpy.py",
ne 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\LENOVO\Desktop\rasaa\Scripts\rasa.exe\__main__.py", line 4,
<module>
  File "c:\users\lenovo\desktop\rasaa\lib\site-packages\rasa\__init__.py", li
8, in <module>
    from rasa.run import run
  File "c:\users\lenovo\desktop\rasaa\lib\site-packages\rasa\run.py", line 5,
 <module>
    from rasa.cli.utils import print_warning
  File "c:\users\lenovo\desktop\rasaa\lib\site-packages\rasa\cli\utils.py", l
 12, in <module>
    from typing import NoReturn
ImportError: cannot import name 'NoReturn'
```
python version : 3.6.0
OS: windows 8.1
rasa version: latest one installed using pip yesterday.

**Comment by erohmensing** [comment]
Please read the template:
`THIS INFORMATION IS MANDATORY - YOUR ISSUE WILL BE CLOSED IF IT IS MISSING`

version information seems quite pertinent to this issue. 

**Rasa version**:

**Rasa SDK version** (if used & relevant):

**Rasa X version** (if used & relevant):

**Python version**:

**Operating system** (windows, osx, ...):

**Comment by Dhiraj240** [comment]
python version : 3.6.0
OS: windows 8.1
rasa version: latest one installed using pip yesterday.

**Comment by erohmensing** [comment]
You can find your rasa version with `rasa --version`.

**Comment by rajnish-kumar-76** [comment]
I tried on Mac. I am also getting same error.
I pulled from github and built it just now. Pulled from master (Tree: 89e5a4c878)

Python version: 3.6.1
OS: mac 10.13.6
rasa version: rasa -V command fails with "ImportError: cannot import name 'NoReturn'"

**Comment by Dhiraj240** [comment]
@erohmensing Ahhh, even doing ```rasa --version``` shows the same above error.

**Comment by rajnish-kumar-76** [comment]
Go with Python 3.7 to overcome this issue.
python -V : Python 3.7.6
rasa --version : Rasa 1.6.0

** Don't try Python 3.8 because tensorflow if needed in your pipeline doesn't support Python 3.8 as of now.

@Dhiraj240  - Hope this helps you.

**Comment by nanduri1998** [comment]
Windows 10 doesn't support tensorflow on python 3.7. We are forced to use python 3.6. Any corrections for the same issue.

**Comment by rajnish-kumar-76** [comment]
> Windows 10 doesn't support tensorflow on python 3.7. We are forced to use python 3.6. Any corrections for the same issue.

Is Windows your prod environment or just the dev environment ?

**Comment by nanduri1998** [comment]
> > Windows 10 doesn't support tensorflow on python 3.7. We are forced to use python 3.6. Any corrections for the same issue.
> 
> Is Windows your prod environment or just the dev environment ?

Dev environment

**Comment by rajnish-kumar-76** [comment]
> > > Windows 10 doesn't support tensorflow on python 3.7. We are forced to use python 3.6. Any corrections for the same issue.
> > 
> > 
> > Is Windows your prod environment or just the dev environment ?
> 
> Dev environment

Then I guess it wouldn't be much of a problem to ask the developers to develop on Linux based VMs. This should resolve your issue by using Python 3.7

**Comment by nanduri1998** [comment]
> > > > Windows 10 doesn't support tensorflow on python 3.7. We are forced to use python 3.6. Any corrections for the same issue.
> > > 
> > > 
> > > Is Windows your prod environment or just the dev environment ?
> > 
> > 
> > Dev environment
> 
> Then I guess it wouldn't be much of a problem to ask the developers to develop on Linux based VMs. This should resolve your issue by using Python 3.7

I don't have a linux based system at my disposal. Is there any workaround for windows

**Comment by rajnish-kumar-76** [comment]
> > > > > Windows 10 doesn't support tensorflow on python 3.7. We are forced to use python 3.6. Any corrections for the same issue.
> > > > 
> > > > 
> > > > Is Windows your prod environment or just the dev environment ?
> > > 
> > > 
> > > Dev environment
> > 
> > 
> > Then I guess it wouldn't be much of a problem to ask the developers to develop on Linux based VMs. This should resolve your issue by using Python 3.7
> 
> I don't have a linux based system at my disposal. Is there any workaround for windows

Well. I don't work on windows so I can't help you on windows. What I can tell you is running a linux VM on windows doesn't take much effort. You can contact me separately in case you want to know how to.

**Comment by Dhiraj240** [comment]
@rajnish-kumar-76 using python 3.7 shows tensorflow error in windows 8.1. Which os you are using?
@erohmensing any solution ?
