### ISSUE TITLE
'Tracker' object has no attribute 'update'

### ISSUE THREAD

**Issue by ttlekich** [RasaHQ/rasa#5030]
**Rasa version**: 1.4.4

**Rasa SDK version** (if used & relevant): 1.4.0

**Rasa X version** (if used & relevant): N/A

**Python version**: 3.6.8

**Operating system** (windows, osx, ...): Ubuntu 18.04

**Issue**:
The [rasa documentation](https://rasa.com/docs/rasa/api/tracker/#rasa.core.trackers.DialogueStateTracker.update) lists an `update` method on the Tracker class, though I cannot seem to access it `tracker.update(<event>)` or see it in the source code: `rasa_sdk/interfaces.py`. Maybe I am just using the method incorrectly?

If I were to write this myself, would this just be an append onto the tracker's events list property?

**Error (including full traceback)**:
```
line 57, in submit
    tracker.update(new_event)
AttributeError: 'Tracker' object has no attribute 'update'

```

**Command or request that led to error**:
```
rasa run actions&
rasa shell -m models --endpoints endpoints.yml
```
then proceeded through a conversation that uses a form action. 

**Content of configuration file (config.yml)** (if relevant): N/A
```yml

```

**Content of domain file (domain.yml)** (if relevant): N/A
```yml

```

**Comment by erohmensing** [comment]
Sorry about that! understandably confusing -- that tracker is the rasa core tracker (tbh probably doesn't need its own autoclass documentation anymore). The tracker object you're looking for are in the SDK docs: https://rasa.com/docs/rasa/api/rasa-sdk/

**Comment by ttlekich** [comment]
Wow that was fast! Great, that all makes sense thank you!

**Comment by erohmensing** [comment]
Haha, no problem!
