### ISSUE TITLE
error while running rasa x

### ISSUE THREAD

**Issue by abhishekborse** [RasaHQ/rasa#5034]
**Rasa version**:    1.5.3      
**Rasa SDK version** (if used & relevant): 1.5.2      

**Rasa X version** (if used & relevant):   0.23.5     

**Python version**:  3.7.1
**Operating system** (windows, osx, ...): Ubuntu  18.04.1 LTS

**Issue**:
![Screenshot from 2020-01-04 11-50-59](https://user-images.githubusercontent.com/40940696/71760766-ce7fe500-2ee8-11ea-9f1e-a3dc0b29d1c8.png)

**Comment by erohmensing** [comment]
Hi there, this is a duplicate of another issue that we are currently in the midst of fixing. 

As a workaround, please install `sanic==19.9.0`.

**Comment by abhishekborse** [comment]
Thanks, It's working for now
