### ISSUE TITLE
Error while running command pip3 install rasa

### ISSUE THREAD

**Issue by abhishekborse** [RasaHQ/rasa#5036]
Rasa version: 1.5.3

Rasa SDK version (if used & relevant): 1.5.2

Rasa X version (if used & relevant): 0.23.5

Python version: 3.8.1

Operating system (windows, osx, ...): Ubuntu 18.04.1 LTS

Issue:
![Screenshot from 2020-01-04 12-15-50](https://user-images.githubusercontent.com/40940696/71761042-4996ca80-2eec-11ea-83ed-0b8fa97759c4.png)

**Comment by sara-tagger** [comment]
Thanks for raising this issue, @Ghostvv will get back to you about it soon✨

###### Please also check out the [docs](https://rasa.com/docs/) and the [forum](https://forum.rasa.com/) in case your issue was raised there too 🤗

**Comment by Ghostvv** [comment]
it looks like there was some problem during downloading tf probability

**Comment by abhishekborse** [comment]
it's working now thanks
