### ISSUE TITLE
Inconsistent requirements in Rasa 1.6.0

### ISSUE THREAD

**Issue by staticdev** [RasaHQ/rasa#5040]
**Rasa version**: 1.6.0

**Rasa SDK version** (if used & relevant):

**Rasa X version** (if used & relevant):

**Python version**: Python 3.7.5

**Operating system** (windows, osx, ...): Ubuntu 19.10

**Issue**: When I try to train my models I was getting a warning:
`/usr/lib/python3/dist-packages/requests/__init__.py:91: RequestsDependencyWarning: urllib3 (1.25.7) or chardet (3.0.4) doesn't match a supported version!`

I tried to solve that installing the newer version o requests 2.22.0 (which is in rasa's requirements.txt). When I do that I get: `ERROR: rasa 1.6.0 has requirement networkx~=2.3.0, but you'll have networkx 2.4 which is incompatible.`. That is odd, since rasa needs requests 2.22.0 which needs networkx 2.4. I think a quickfix would be just upgrading the requirements.txt from rasa to networkx 2.4.

**Logs**:
```
pip3 install --upgrade requests --user
Collecting requests
  Using cached https://files.pythonhosted.org/packages/51/bd/23c926cd341ea6b7dd0b2a00aba99ae0f828be89d72b2190f27c11d4b7fb/requests-2.22.0-py2.py3-none-any.whl
Requirement already satisfied, skipping upgrade: chardet<3.1.0,>=3.0.2 in /usr/lib/python3/dist-packages (from requests) (3.0.4)
Requirement already satisfied, skipping upgrade: idna<2.9,>=2.5 in /usr/lib/python3/dist-packages (from requests) (2.6)
Requirement already satisfied, skipping upgrade: urllib3!=1.25.0,!=1.25.1,<1.26,>=1.21.1 in /usr/local/lib/python3.7/dist-packages (from requests) (1.25.7)
Requirement already satisfied, skipping upgrade: certifi>=2017.4.17 in /usr/lib/python3/dist-packages (from requests) (2018.8.24)
ERROR: rasa 1.6.0 has requirement networkx~=2.3.0, but you'll have networkx 2.4 which is incompatible.
```

**Comment by staticdev** [comment]
Pull request #5041.

**Comment by sara-tagger** [comment]
Thanks for raising this issue, @JustinaPetr will get back to you about it soon✨

###### Please also check out the [docs](https://rasa.com/docs/) and the [forum](https://forum.rasa.com/) in case your issue was raised there too 🤗

**Comment by staticdev** [comment]
@JustinaPetr I had a problem with my first fork but I recreated the pull request (#5071). Can you get a reviewer for that? Thanks.
