### ISSUE TITLE
When Perform an intent evaluation Not support markdown format

### ISSUE THREAD

**Issue by MrRace** [RasaHQ/rasa#5042]
When doing the test of `http://localhost:5005/model/test/intents`  according to the [testModelIntent](https://rasa.com/docs/rasa/api/http-api/#operation/testModelIntent)：
![image](https://user-images.githubusercontent.com/10300313/71801399-c913cd80-3095-11ea-8f40-3d06a46f8ca1.png)
However,  it seems do  not support the  markdown format! 
My request is：
`curl -XPOST http://localhost:5005/model/test/intents -d '## intent:goodbye\n- goodbye\n\n''`
![image](https://user-images.githubusercontent.com/10300313/71801599-59521280-3096-11ea-91e6-43b5be2a4e8a.png)
What should I do to get the intent of  the query? Thanks a lot!
My Rasa version is `Rasa 1.6.0`

**Comment by sara-tagger** [comment]
Thanks for the issue, @rgstephens will get back to you about it soon!

###### You may find help in the [docs](https://rasa.com/docs/) and the [forum,](https://forum.rasa.com/) too 🤗

**Comment by rgstephens** [comment]
the `-d` option should be a filename with the markdown: `-d @intents.md`.

Please post questions in our forums at https://forum.rasa.com.
