### ISSUE TITLE
How to evaluate stories

### ISSUE THREAD

**Issue by MrRace** [RasaHQ/rasa#5043]
**Rasa version**: 
Rasa 1.5.3
**Python version**:
Python 3.6.8

**Operating system** (windows, osx, ...):
Centos 

**Issue**:
I want to Evaluate stories according to the [instruction](https://rasa.com/docs/rasa/api/http-api/#operation/testModelStories).
I use the `stories.md` to do the testing, my request is:
```
curl -XPOST http://localhost:5005/model/test/stories -d@stories.md
```
the `stories.md`  is the same file used to train Rasa model.

**Error (including full traceback)**:
```
{"version":"1.5.3","status":"failure","message":"An unexpected error occurred during evaluation. Error: division by zero","reason":"TestingError","details":{},"help":null,"code":500}
```
What should I do to get the correct response？ Thanks a lot!
![image](https://user-images.githubusercontent.com/10300313/71805200-958a7080-30a0-11ea-9486-4d14c4e90878.png)

**Comment by sara-tagger** [comment]
Thanks for raising this issue, @ArjaanBuijk will get back to you about it soon✨

###### Please also check out the [docs](https://rasa.com/docs/) and the [forum](https://forum.rasa.com/) in case your issue was raised there too 🤗
