### ISSUE TITLE
Spanish supported?

### ISSUE THREAD

**Issue by johnfelipe** [RasaHQ/rasa#5044]
I want to know if Spanish supported?

**Comment by sara-tagger** [comment]
Thanks for the question, our Github issue board is for **bugs and feature requests only,** though 😕
Please ask this question in the [forum✨](https://forum.rasa.com/c/rasa)

###### If you were describing a bug, please create a [report](https://github.com/RasaHQ/rasa/issues/new?labels=bug&template=bug_report.md) and fill out the template.
