### ISSUE TITLE
Heroku Deploy Error: No matching distribution found for tensorflow~=1.15.0 

### ISSUE THREAD

**Issue by canerbaran** [RasaHQ/rasa#5052]
**Rasa version**: 1.16.0

**Rasa SDK version** (if used & relevant):

**Rasa X version** (if used & relevant):

**Python version**: 3.7.5

**Operating system** (windows, osx, ...): OSx & Heroku

**Issue**: When I tried to deploy my RASA-chatbot on Heroku, I am getting an error during push due to TensorFlow version inconsistency.

**Error (including full traceback)**:
```
remote:          Could not find a version that satisfies the requirement tensorflow~=1.15.0 (from rasa->-r /tmp/build_eb547afa20c8e3e443b80d37cc63b6cd/requirements.txt (line 1)) (from versions: 1.13.0rc1, 1.13.0rc2, 1.13.1, 1.13.2, 1.14.0rc0, 1.14.0rc1, 1.14.0, 2.0.0a0, 2.0.0b0, 2.0.0b1)
remote:        No matching distribution found for tensorflow~=1.15.0 (from rasa->-r /tmp/build_eb547afa20c8e3e443b80d37cc63b6cd/requirements.txt (line 1))
remote:  !     Push rejected, failed to compile Python app.
remote: 
remote:  !     Push failed
remote: Verifying deploy...
remote: 
remote: !	Push rejected to tabip-chatbot.
remote: 
To https://git.heroku.com/tabip-chatbot.git
 ! [remote rejected] master -> master (pre-receive hook declined)
error: failed to push some refs to 'https://git.heroku.com/tabip-chatbot.git'
```

**Command or request that led to error**:
```
Inconsistency with TensorFlow version and pip version(on Heroku?).
```

**Content of configuration file (config.yml)** (if relevant):
```yml

```

**Content of domain file (domain.yml)** (if relevant):
```yml

```

**Comment by sara-tagger** [comment]
Thanks for the issue, @JustinaPetr will get back to you about it soon!

###### You may find help in the [docs](https://rasa.com/docs/) and the [forum,](https://forum.rasa.com/) too 🤗

**Comment by erohmensing** [comment]
Hi @canerbaran , what's your pip version? Have you already done `pip install -U pip`?

**Comment by canerbaran** [comment]
> Hi @canerbaran , what's your pip version? Have you already done `pip install -U pip`?
My pip version on local machine is 19.2.3.
On the other hand I am receiving this error during push to Heroku. I think it is not related to my local pip version

**Comment by canerbaran** [comment]
> Hi @canerbaran , what's your pip version? Have you already done `pip install -U pip`?

My pip version on local machine is 19.2.3.
On the other hand I am receiving this error during push to Heroku. I think it is not related to my local pip version

**Comment by erohmensing** [comment]
Yes, I think you're right, it is most likely the pip version on heroku. Maybe something like this would help? https://stackoverflow.com/questions/52706769/pipenv-trouble-on-macos-typeerror-module-object-is-not-callable/52821649#52821649

You want to make sure that whatever version heroku has running, it is > 19.0.

**Comment by John-Nagle** [comment]
I got that error under a fresh Python 3.8.1  virtual environment. Ubuntu 16.04 LTS desktop.  Do I need to go back to Python 3.7? Rasu seems to use an older version of Tensorflow.

```
(venv) john@Nagle-LTS:~/projects/sl/rasu$ virtualenv -p /usr/local/bin/Python3.8 venv
The path /usr/local/bin/Python3.8 (from --python=/usr/local/bin/Python3.8) does not exist
(venv) john@Nagle-LTS:~/projects/sl/rasu$ virtualenv -p /usr/local/bin/python3.8 venv
Already using interpreter /usr/local/bin/python3.8
Using base prefix '/usr/local'
New python executable in /home/john/projects/sl/rasu/venv/bin/python3.8
Also creating executable in /home/john/projects/sl/rasu/venv/bin/python
Installing setuptools, pip, wheel...
done.
(venv) john@Nagle-LTS:~/projects/sl/rasu$ source venv/bin/activate
(venv) john@Nagle-LTS:~/projects/sl/rasu$ pip install -U pip
Requirement already up-to-date: pip in ./venv/lib/python3.8/site-packages (19.3.1)
(venv) john@Nagle-LTS:~/projects/sl/rasu$ pip install rasa
Collecting rasa
  Using cached https://files.pythonhosted.org/packages/6e/b4/dad07c728501a12a7df62977ee1d17ed3551c2b1a0a8bc2e21575ef74557/rasa-1.6.1-py3-none-any.whl
Collecting PyJWT~=1.7
  Using cached https://files.pythonhosted.org/packages/87/8b/6a9f14b5f781697e51259d81657e6048fd31a113229cf346880bb7545565/PyJWT-1.7.1-py2.py3-none-any.whl
Collecting colorhash~=1.0
  Downloading https://files.pythonhosted.org/packages/0e/e1/50dbc513aa74e99eca4c47f2a8206711f0bec436fdddd95eebaf7eaaa1aa/colorhash-1.0.2-py2.py3-none-any.whl
Collecting twilio~=6.0
  Downloading https://files.pythonhosted.org/packages/27/eb/c7a4abc4ceabaf626fa5f7a59a15ad4f0c15465555c88b18ec1080313458/twilio-6.35.2.tar.gz (408kB)
     |████████████████████████████████| 409kB 1.7MB/s 
Collecting terminaltables~=3.1
  Using cached https://files.pythonhosted.org/packages/9b/c4/4a21174f32f8a7e1104798c445dacdc1d4df86f2f26722767034e4de4bff/terminaltables-3.1.0.tar.gz
Collecting sanic~=19.9.0
  Downloading https://files.pythonhosted.org/packages/b5/99/a0c18220d313cd6bc26728259f7719bd3f31ebb7c5d45015b6e3426174da/sanic-19.9.0-py3-none-any.whl (73kB)
     |████████████████████████████████| 81kB 2.8MB/s 
Collecting SQLAlchemy~=1.3.0
  Downloading https://files.pythonhosted.org/packages/17/7f/35879c73859368ad19a952b69ee780aa97fc30350dabd45fb948d6a4e3ea/SQLAlchemy-1.3.12.tar.gz (6.0MB)
     |████████████████████████████████| 6.0MB 1.0MB/s 
Collecting numpy~=1.16
  Using cached https://files.pythonhosted.org/packages/41/38/b278d96baebc6a4818cfd9c0fb6f0e62013d5b87374bcf0f14a0e9b83ed5/numpy-1.18.1-cp38-cp38-manylinux1_x86_64.whl
Collecting jsonschema~=3.0
  Downloading https://files.pythonhosted.org/packages/c5/8f/51e89ce52a085483359217bc72cdbf6e75ee595d5b1d4b5ade40c7e018b8/jsonschema-3.2.0-py2.py3-none-any.whl (56kB)
     |████████████████████████████████| 61kB 2.0MB/s 
Collecting gast==0.2.2
  Downloading https://files.pythonhosted.org/packages/4e/35/11749bf99b2d4e3cceb4d55ca22590b0d7c2c62b9de38ac4a4a7f4687421/gast-0.2.2.tar.gz
Collecting apscheduler~=3.0
  Downloading https://files.pythonhosted.org/packages/f3/34/9ef20ed473c4fd2c3df54ef77a27ae3fc7500b16b192add4720cab8b2c09/APScheduler-3.6.3-py2.py3-none-any.whl (58kB)
     |████████████████████████████████| 61kB 1.9MB/s 
Collecting pika~=1.0.0
  Downloading https://files.pythonhosted.org/packages/78/1a/28c98ee8b211be21d4a9f4ef1687c4d36f9302d47fcc28b81f9591abf6d8/pika-1.0.1-py2.py3-none-any.whl (148kB)
     |████████████████████████████████| 153kB 5.3MB/s 
Collecting scikit-learn~=0.20.0
  Using cached https://files.pythonhosted.org/packages/20/a0/5ec20d7e460d8ebde9ec5e40cda4339c5f546871c3a5bf9228f615b25618/scikit-learn-0.20.4.tar.gz
Collecting fbmessenger~=6.0
  Downloading https://files.pythonhosted.org/packages/bd/e9/646684226176782b9e3b7dd5b35d7ecfd1d13cba24ad2e33255079921aab/fbmessenger-6.0.0-py2.py3-none-any.whl
Collecting python-engineio>=3.9.3
  Downloading https://files.pythonhosted.org/packages/97/16/66b05477d6057238e2fc1f8cfb1dfd0b3adad1351c30ad20934f09db5891/python_engineio-3.11.2-py2.py3-none-any.whl (49kB)
     |████████████████████████████████| 51kB 1.6MB/s 
Collecting rasa-sdk~=1.6.0
  Downloading https://files.pythonhosted.org/packages/fb/9a/52121a69842e6df3a810e3ed3756ba7554261cb7bf5757d2f4e7622aab27/rasa_sdk-1.6.1-py2.py3-none-any.whl
Collecting requests>=2.20
  Using cached https://files.pythonhosted.org/packages/51/bd/23c926cd341ea6b7dd0b2a00aba99ae0f828be89d72b2190f27c11d4b7fb/requests-2.22.0-py2.py3-none-any.whl
Collecting colorclass~=2.2
  Downloading https://files.pythonhosted.org/packages/37/ea/ae8dbb956939d4392e6a7fdef87fda273854da1128edae016c4104240be8/colorclass-2.2.0.tar.gz
Collecting ruamel.yaml~=0.15.0
  Downloading https://files.pythonhosted.org/packages/9a/ee/55cd64bbff971c181e2d9e1c13aba9a27fd4cd2bee545dbe90c44427c757/ruamel.yaml-0.15.100.tar.gz (318kB)
     |████████████████████████████████| 327kB 6.8MB/s 
Collecting pytz~=2019.1
  Using cached https://files.pythonhosted.org/packages/e7/f9/f0b53f88060247251bf481fa6ea62cd0d25bf1b11a87888e53ce5b7c8ad2/pytz-2019.3-py2.py3-none-any.whl
Collecting sklearn-crfsuite~=0.3.6
  Downloading https://files.pythonhosted.org/packages/25/74/5b7befa513482e6dee1f3dd68171a6c9dfc14c0eaa00f885ffeba54fe9b0/sklearn_crfsuite-0.3.6-py2.py3-none-any.whl
Collecting matplotlib~=3.0
  Using cached https://files.pythonhosted.org/packages/53/6c/7b400d45f0ecd6703b2779a7dfda6578579a353748e1b43d8353cb7f5b7f/matplotlib-3.1.2-cp38-cp38-manylinux1_x86_64.whl
Collecting pymongo[srv,tls]~=3.8
  Using cached https://files.pythonhosted.org/packages/c3/0f/087858b27bb800b589c18791f735fe16b12f160c41616dfc670aae159165/pymongo-3.10.1-cp38-cp38-manylinux2014_x86_64.whl
Collecting multidict==4.6.1
  Downloading https://files.pythonhosted.org/packages/20/b3/4031c18ff3ecb72147d08ac9e72e6924ea7c784f221c6d4dbcd8bdb79a74/multidict-4.6.1-cp38-cp38-manylinux1_x86_64.whl (366kB)
     |████████████████████████████████| 368kB 5.4MB/s 
Collecting rocketchat-API~=0.6.0
  Downloading https://files.pythonhosted.org/packages/8e/e6/69e5d75ad687635c56a27a8529c471cf1a8593e071784c4d2727382cd5db/rocketchat_API-0.6.36-py3-none-any.whl
Collecting tqdm~=4.0
  Using cached https://files.pythonhosted.org/packages/72/c9/7fc20feac72e79032a7c8138fd0d395dc6d8812b5b9edf53c3afd0b31017/tqdm-4.41.1-py2.py3-none-any.whl
Collecting python-socketio>=4.3.1
  Using cached https://files.pythonhosted.org/packages/11/e0/71c90fbfc534108d0869ff5f92c16e4bc9b1347439b9022e815c03ff4193/python_socketio-4.4.0-py2.py3-none-any.whl
Requirement already satisfied: setuptools>=41.0.0 in ./venv/lib/python3.8/site-packages (from rasa) (45.0.0)
Collecting coloredlogs~=10.0
  Using cached https://files.pythonhosted.org/packages/08/0f/7877fc42fff0b9d70b6442df62d53b3868d3a6ad1b876bdb54335b30ff23/coloredlogs-10.0-py2.py3-none-any.whl
Collecting aiohttp~=3.5
  Downloading https://files.pythonhosted.org/packages/c2/f7/f0ad3dbace4762fef5d80aa4124b41bf218e4c4dd6d387a86cede707d9a4/aiohttp-3.6.2-py3-none-any.whl (441kB)
     |████████████████████████████████| 450kB 6.9MB/s 
Collecting scipy~=1.2
  Downloading https://files.pythonhosted.org/packages/f3/08/8bdcdcd149ea41b655956feb7c19ebf7e1f561738bd5570b6ae015daf411/scipy-1.4.1-cp38-cp38-manylinux1_x86_64.whl (26.0MB)
     |████████████████████████████████| 26.0MB 5.6MB/s 
Collecting slackclient~=1.3
  Downloading https://files.pythonhosted.org/packages/7c/2f/9b6db4c7686be3dc6b4244eaef4f37226a2ccca1a796516d4adcdfeefe56/slackclient-1.3.2.tar.gz
Collecting attrs>=18
  Using cached https://files.pythonhosted.org/packages/a2/db/4313ab3be961f7a763066401fb77f7748373b6094076ae2bda2806988af6/attrs-19.3.0-py2.py3-none-any.whl
Collecting boto3~=1.9
  Downloading https://files.pythonhosted.org/packages/10/d4/143cdfd6303739dfacd12cc166f7b45bbd75277c2674b051401f16c1a6fd/boto3-1.11.4-py2.py3-none-any.whl (128kB)
     |████████████████████████████████| 133kB 5.9MB/s 
Collecting redis~=3.3.5
  Downloading https://files.pythonhosted.org/packages/32/ae/28613a62eea0d53d3db3147f8715f90da07667e99baeedf1010eb400f8c0/redis-3.3.11-py2.py3-none-any.whl (66kB)
     |████████████████████████████████| 71kB 2.4MB/s 
Collecting jsonpickle~=1.1
  Using cached https://files.pythonhosted.org/packages/07/07/c157520a3ebd166c8c24c6ae0ecae7c3968eb4653ff0e5af369bb82f004d/jsonpickle-1.2-py2.py3-none-any.whl
Collecting python-dateutil~=2.8
  Downloading https://files.pythonhosted.org/packages/d4/70/d60450c3dd48ef87586924207ae8907090de0b306af2bce5d134d78615cb/python_dateutil-2.8.1-py2.py3-none-any.whl (227kB)
     |████████████████████████████████| 235kB 6.8MB/s 
Collecting packaging~=19.0
  Downloading https://files.pythonhosted.org/packages/cf/94/9672c2d4b126e74c4496c6b3c58a8b51d6419267be9e70660ba23374c875/packaging-19.2-py2.py3-none-any.whl
Collecting async-generator~=1.10
  Downloading https://files.pythonhosted.org/packages/71/52/39d20e03abd0ac9159c162ec24b93fbcaa111e8400308f2465432495ca2b/async_generator-1.10-py3-none-any.whl
Collecting tensorflow-probability~=0.7.0
  Using cached https://files.pythonhosted.org/packages/3e/3a/c10b6c22320531c774402ac7186d1b673374e2a9d12502cbc8d811e4601c/tensorflow_probability-0.7.0-py2.py3-none-any.whl
Collecting questionary>=1.1.0
  Downloading https://files.pythonhosted.org/packages/94/2a/2f874784637210ac5866635d2627b9171c717cdd8ab0aab1ce4382c91575/questionary-1.4.0-py3-none-any.whl
ERROR: Could not find a version that satisfies the requirement tensorflow~=1.15.0 (from rasa) (from versions: none)
ERROR: No matching distribution found for tensorflow~=1.15.0 (from rasa)
(venv) john@Nagle-LTS:~/projects/sl/rasu$ 
```

**Comment by John-Nagle** [comment]
Went back to Python 3.7. Tensorflow installed successfully. So this is a versioning problem.
On Python 3.7, I got the install error:

`ERROR: sanic-plugins-framework 0.8.2.post1 has requirement sanic<=19.6.3,>=0.8.3, but you'll have sanic 19.9.0 which is incompatible.`

Another versioning problem. Fortunately I don't need sanic.

**Comment by Anjani-1999** [comment]
Python app detected
-----> Installing python-3.6.12
-----> Installing pip 20.1.1, setuptools 47.1.1 and wheel 0.34.2
-----> Installing SQLite3
-----> Installing requirements with pip
       Collecting alembic==1.4.1
         Downloading alembic-1.4.1.tar.gz (1.1 MB)
       Collecting altair==4.1.0
         Downloading altair-4.1.0-py3-none-any.whl (727 kB)
       Collecting argon2-cffi==20.1.0
         Downloading argon2_cffi-20.1.0-cp35-abi3-manylinux1_x86_64.whl (97 kB)
       Collecting astor==0.8.1
         Downloading astor-0.8.1-py2.py3-none-any.whl (27 kB)
       Collecting async-generator==1.10
         Downloading async_generator-1.10-py3-none-any.whl (18 kB)
       Collecting atomicwrites==1.4.0
         Downloading atomicwrites-1.4.0-py2.py3-none-any.whl (6.8 kB)
       Collecting attrs==20.2.0
         Downloading attrs-20.2.0-py2.py3-none-any.whl (48 kB)
       Collecting azure-core==1.8.2
         Downloading azure_core-1.8.2-py2.py3-none-any.whl (122 kB)
       Collecting azure-storage-blob==12.5.0
         Downloading azure_storage_blob-12.5.0-py2.py3-none-any.whl (326 kB)
       Collecting backcall==0.2.0
         Downloading backcall-0.2.0-py2.py3-none-any.whl (11 kB)
       Collecting base58==2.0.1
         Downloading base58-2.0.1-py3-none-any.whl (4.3 kB)
       Collecting bleach==3.2.1
         Downloading bleach-3.2.1-py2.py3-none-any.whl (145 kB)
       Collecting blinker==1.4
         Downloading blinker-1.4.tar.gz (111 kB)
       Collecting blis==0.4.1
         Downloading blis-0.4.1-cp36-cp36m-manylinux1_x86_64.whl (3.7 MB)
       Collecting boto3==1.15.16
         Downloading boto3-1.15.16-py2.py3-none-any.whl (129 kB)
       Collecting botocore==1.18.16
         Downloading botocore-1.18.16-py2.py3-none-any.whl (6.7 MB)
       Collecting cachetools==4.1.1
         Downloading cachetools-4.1.1-py3-none-any.whl (10 kB)
       Collecting catalogue==1.0.0
         Downloading catalogue-1.0.0-py2.py3-none-any.whl (7.7 kB)
       Collecting catboost==0.24.2
         Downloading catboost-0.24.2-cp36-none-manylinux1_x86_64.whl (66.1 MB)
       Collecting certifi==2020.6.20
         Downloading certifi-2020.6.20-py2.py3-none-any.whl (156 kB)
       Collecting cffi==1.14.3
         Downloading cffi-1.14.3-cp36-cp36m-manylinux1_x86_64.whl (400 kB)
       Collecting chardet==3.0.4
         Downloading chardet-3.0.4-py2.py3-none-any.whl (133 kB)
       Collecting click==7.1.2
         Downloading click-7.1.2-py2.py3-none-any.whl (82 kB)
       Collecting cloudpickle==1.6.0
         Downloading cloudpickle-1.6.0-py3-none-any.whl (23 kB)
       Collecting colorama==0.4.4
         Downloading colorama-0.4.4-py2.py3-none-any.whl (16 kB)
       Collecting colorlover==0.3.0
         Downloading colorlover-0.3.0-py3-none-any.whl (8.9 kB)
       Collecting combo==0.1.1
         Downloading combo-0.1.1.tar.gz (37 kB)
       Collecting confuse==1.3.0
         Downloading confuse-1.3.0-py2.py3-none-any.whl (64 kB)
       Collecting cryptography==3.1.1
         Downloading cryptography-3.1.1-cp35-abi3-manylinux2010_x86_64.whl (2.6 MB)
       Collecting cufflinks==0.17.3
         Downloading cufflinks-0.17.3.tar.gz (81 kB)
       Collecting cycler==0.10.0
         Downloading cycler-0.10.0-py2.py3-none-any.whl (6.5 kB)
       Collecting cymem==2.0.3
         Downloading cymem-2.0.3-cp36-cp36m-manylinux1_x86_64.whl (32 kB)
       Collecting Cython==0.29.14
         Downloading Cython-0.29.14-cp36-cp36m-manylinux1_x86_64.whl (2.1 MB)
       Collecting databricks-cli==0.12.2
         Downloading databricks-cli-0.12.2.tar.gz (55 kB)
       Collecting datefinder==0.7.1
         Downloading datefinder-0.7.1-py2.py3-none-any.whl (10 kB)
       Collecting decorator==4.4.2
         Downloading decorator-4.4.2-py2.py3-none-any.whl (9.2 kB)
       Collecting defusedxml==0.6.0
         Downloading defusedxml-0.6.0-py2.py3-none-any.whl (23 kB)
       Collecting docker==4.3.1
         Downloading docker-4.3.1-py2.py3-none-any.whl (145 kB)
       Collecting entrypoints==0.3
         Downloading entrypoints-0.3-py2.py3-none-any.whl (11 kB)
       Collecting enum-compat==0.0.3
         Downloading enum_compat-0.0.3-py3-none-any.whl (1.3 kB)
       Collecting Flask==1.1.2
         Downloading Flask-1.1.2-py2.py3-none-any.whl (94 kB)
       Collecting funcy==1.15
         Downloading funcy-1.15-py2.py3-none-any.whl (32 kB)
       Collecting future==0.18.2
         Downloading future-0.18.2.tar.gz (829 kB)
       Collecting gensim==3.8.3
         Downloading gensim-3.8.3-cp36-cp36m-manylinux1_x86_64.whl (24.2 MB)
       Collecting gitdb==4.0.5
         Downloading gitdb-4.0.5-py3-none-any.whl (63 kB)
       Collecting GitPython==3.1.9
         Downloading GitPython-3.1.9-py3-none-any.whl (159 kB)
       Collecting gorilla==0.3.0
         Downloading gorilla-0.3.0-py2.py3-none-any.whl (11 kB)
       Collecting graphviz==0.14.2
         Downloading graphviz-0.14.2-py2.py3-none-any.whl (18 kB)
       Collecting htmlmin==0.1.12
         Downloading htmlmin-0.1.12.tar.gz (19 kB)
       Collecting idna==2.10
         Downloading idna-2.10-py2.py3-none-any.whl (58 kB)
       Collecting ImageHash==4.1.0
         Downloading ImageHash-4.1.0.tar.gz (291 kB)
       Collecting imbalanced-learn==0.7.0
         Downloading imbalanced_learn-0.7.0-py3-none-any.whl (167 kB)
       Collecting iniconfig==1.1.1
         Downloading iniconfig-1.1.1.tar.gz (8.1 kB)
         Installing build dependencies: started
         Installing build dependencies: finished with status 'done'
         Getting requirements to build wheel: started
         Getting requirements to build wheel: finished with status 'done'
           Preparing wheel metadata: started
           Preparing wheel metadata: finished with status 'done'
       ERROR: Could not find a version that satisfies the requirement ipython==7.18.1 (from -r /tmp/build_99c97e64_/requirements.txt (line 55)) (from versions: 0.10, 0.10.1, 0.10.2, 0.11, 0.12, 0.12.1, 0.13, 0.13.1, 0.13.2, 1.0.0, 1.1.0, 1.2.0, 1.2.1, 2.0.0, 2.1.0, 2.2.0, 2.3.0, 2.3.1, 2.4.0, 2.4.1, 3.0.0, 3.1.0, 3.2.0, 3.2.1, 3.2.2, 3.2.3, 4.0.0b1, 4.0.0, 4.0.1, 4.0.2, 4.0.3, 4.1.0rc1, 4.1.0rc2, 4.1.0, 4.1.1, 4.1.2, 4.2.0, 4.2.1, 5.0.0b1, 5.0.0b2, 5.0.0b3, 5.0.0b4, 5.0.0rc1, 5.0.0, 5.1.0, 5.2.0, 5.2.1, 5.2.2, 5.3.0, 5.4.0, 5.4.1, 5.5.0, 5.6.0, 5.7.0, 5.8.0, 5.9.0, 5.10.0, 6.0.0rc1, 6.0.0, 6.1.0, 6.2.0, 6.2.1, 6.3.0, 6.3.1, 6.4.0, 6.5.0, 7.0.0b1, 7.0.0rc1, 7.0.0, 7.0.1, 7.1.0, 7.1.1, 7.2.0, 7.3.0, 7.4.0, 7.5.0, 7.6.0, 7.6.1, 7.7.0, 7.8.0, 7.9.0, 7.10.0, 7.10.1, 7.10.2, 7.11.0, 7.11.1, 7.12.0, 7.13.0, 7.14.0, 7.15.0, 7.16.0, 7.16.1)
       ERROR: No matching distribution found for ipython==7.18.1 (from -r /tmp/build_99c97e64_/requirements.txt (line 55))
 !     Push rejected, failed to compile Python app.
 !     Push failed

**Comment by Anjani-1999** [comment]
please reolve this issue

**Comment by Anjani-1999** [comment]
ERROR: No matching distribution found for ipython==7.18.1 (from -r /tmp/build_99c97e64_/requirements.txt (line 55))

**Comment by musavveer** [comment]
Even I am getting the same error.
Please help me out resolving this issue.

**Comment by Chariskall** [comment]
Same problem here.

**Comment by Ahmed7fathi** [comment]
wow don't say this is a DeadEnd

**Comment by Vishal422** [comment]
Downloading alabaster-0.7.12-py2.py3-none-any.whl (14 kB)
       ERROR: Could not find a version that satisfies the requirement anaconda-client==1.7.2 (from -r /tmp/build_d3d39a48_/requirements.txt (line 3)) (from versions: 1.1.1, 1.2.2)
       ERROR: No matching distribution found for anaconda-client==1.7.2 (from -r /tmp/build_d3d39a48_/requirements.txt (line 3))
 !     Push rejected, failed to compile Python app.
 !     Push failed

**Comment by Polindem** [comment]
Having the same issue with anaconda-client==1.7.2...


ERROR: Could not find a version that satisfies the requirement anaconda-client==1.7.2 (from versions: 1.1.1, 1.2.2)
remote:        ERROR: No matching distribution found for anaconda-client==1.7.2
remote:  !     Push rejected, failed to compile Python app.
remote: 
remote:  !     Push failed

**Comment by Homo-de-futuro** [comment]
did you find a solution to this problem?

**Comment by John-Nagle** [comment]
Gave up on Rasa years ago. Sorry.
