### ISSUE TITLE
agent.persist(), TypeError: 'NoneType' object is not iterable.

### ISSUE THREAD

**Issue by WahabBhatti** [RasaHQ/rasa#5061]
if __name__ == '__main__':
    logging.basicConfig(level='INFO')
    
    training_data_file = './data/stories.md'
    model_path = './models/dialogue'

    agent = Agent('desktop/therapy/therapy_domain.yml',  policies=[MemoizationPolicy(max_history=5), KerasPolicy( epochs=500, batch_size=10)])

    agent.persist(model_path)

TypeError                                 Traceback (most recent call last)
<ipython-input-79-3e0c54ecc95b> in <module>
     12     #agent = Agent('desktop/therapy/therapy_domain.yml', policies = [MemoizationPolicy(max_history = 5), KerasPolicy(featurizer, epochs=500, batch_size=10)])
     13 
---> 14     agent.persist(model_path)

D:\Anaconda\lib\site-packages\rasa\core\agent.py in persist(self, model_path, dump_flattened_stories)
    800         self._clear_model_directory(model_path)
    801 
--> 802         self.policy_ensemble.persist(model_path, dump_flattened_stories)
    803         self.domain.persist(os.path.join(model_path, DEFAULT_DOMAIN_PATH))
    804         self.domain.persist_specification(model_path)

D:\Anaconda\lib\site-packages\rasa\core\policies\ensemble.py in persist(self, path, dump_flattened_stories)
    211         """Persists the policy to storage."""
    212 
--> 213         self._persist_metadata(path, dump_flattened_stories)
    214 
    215         for i, policy in enumerate(self.policies):

D:\Anaconda\lib\site-packages\rasa\core\policies\ensemble.py in _persist_metadata(self, path, dump_flattened_stories)
    186         policy_names = [utils.module_path_from_instance(p) for p in self.policies]
    187 
--> 188         training_events = self._training_events_from_trackers(self.training_trackers)
    189 
    190         action_fingerprints = self._create_action_fingerprints(training_events)

D:\Anaconda\lib\site-packages\rasa\core\policies\ensemble.py in _training_events_from_trackers(training_trackers)
     71         events_metadata = defaultdict(set)
     72 
---> 73         for t in training_trackers:
     74             tracker = t.init_copy()
     75             for event in t.events:

TypeError: 'NoneType' object is not iterable

**Comment by sara-tagger** [comment]
Thanks for the question, our Github issue board is for **bugs and feature requests only,** though 😕
Please ask this question in the [forum✨](https://forum.rasa.com/c/rasa)

###### If you were describing a bug, please create a [report](https://github.com/RasaHQ/rasa/issues/new?labels=bug&template=bug_report.md) and fill out the template.

**Comment by dipinsonwani** [comment]
I am facing the same issue
