### ISSUE TITLE
deploy documentation is missing

### ISSUE THREAD

**Issue by koaning** [RasaHQ/rasa#5062]
This might be more of a seo-thing, but it seems search engines are pointing to the wrong docs. It's that, or part of the docs seem missing. 

<img width="797" alt="image" src="https://user-images.githubusercontent.com/1019791/72247785-f90f2380-35f5-11ea-934c-367d98eb4959.png">

**Comment by koaning** [comment]
<img width="1485" alt="image" src="https://user-images.githubusercontent.com/1019791/72247887-278cfe80-35f6-11ea-84a7-3b904bf86693.png">

**Comment by erohmensing** [comment]
Thanks for pointing this out, I just changed the structure of this section and now none of them live at that website, will ask for a redirect 👍

**Comment by koaning** [comment]
This link: https://rasa.com/docs/rasa-x/deploy/ still gives an error. Just checked in private mode so it isn't cached. It takes time for a new deploy?

**Comment by erohmensing** [comment]
Fixed now right? Went live 41 mins ago

**Comment by koaning** [comment]
Yep. Confirmed :)
