### ISSUE TITLE
Extract featurization from CRFEntityExtractor

### ISSUE THREAD

**Issue by tabergma** [RasaHQ/rasa#5065]
**Description of Problem**:
The `CRFEntityExtractor` creates features on his own. The features cannot be reused.

**Overview of the Solution**:
Create a new featurizer that does the exact same featurization as the `CRFEntityExtractor`. Do not yet substitute the featurization part of the `CRFEntityExtractor` with the new component. 

(Needed as preparation for the new NLU architecture.)

**Definition of Done**:
- [ ] Tests are added
- [ ] Feature described the docs
- [ ] Feature mentioned in the changlog

**Comment by Ghostvv** [comment]
@tabergma that's done? Can we close it?
