### ISSUE TITLE
Getting error: UserWarning: Interpreter parsed an intent 'hey' that is not defined in the domain.   f"Interpreter parsed an intent '{intent}' "

### ISSUE THREAD

**Issue by mtrworld** [RasaHQ/rasa#5066]
I am getting following error while I am trying to test out a conversation.

UserWarning: Interpreter parsed an intent 'hey' that is not defined in the domain.
  f"Interpreter parsed an intent '{intent}' "

Here is the content of the nlu.md file

## intent:greet
- hey
- howdy
- hey there
- hello
- hi
- good morning
- good evening
- dear sir

As you can clearly see hey is defined under the intent greet.

Here is the entry from domain.yml
actions:
- action_search_restaurants
- utter_ask_cuisine
- utter_ask_howcanhelp
- utter_ask_location
- utter_default
- utter_goodbye
- utter_greet
entities:
- cuisine
- location
- people
- price
intents:
- restaurant_search
- greet
- affirm
- goodbye
- stop

I am not sure what I am doing wrong since the intents are clearly defined still I keep getting these errors. Please help.

**Comment by sara-tagger** [comment]
Thanks for the question, our Github issue board is for **bugs and feature requests only,** though 😕
Please ask this question in the [forum✨](https://forum.rasa.com/c/rasa)

###### If you were describing a bug, please create a [report](https://github.com/RasaHQ/rasa/issues/new?labels=bug&template=bug_report.md) and fill out the template.

**Comment by RaminParker** [comment]
I have the same problem. I am searching for at least 1 week to find a solution. I think it is a bug!!! Never had this warning in the previous rasa versions. Now I am working on RASA 1.6.1

**Comment by mtrworld** [comment]
Hi RaminParker,

I was able to resolve this issue . Try using
rasa train -vv -dump-stories --force

**Comment by mtrworld** [comment]
Hi RaminParker,

I was able to resolve this issue . Try using
rasa train -vv -dump-stories --force

**Comment by RaminParker** [comment]
Hey mtrworld

No, I am sorry to say that this doesn't work. Still have the same warnigns.

This is what I did:

Terminal 1:
`rasa train -vv -dump-stories --force`

Terminal 2:
`rasa run --endpoints endpoints.yml --credentials credentials.yml --cors "*"`

Terminal 3:
`rasa run actions --actions actions`

Terminal 4:
`livereload`

**Comment by smar10** [comment]
Same bug here ! 
Besides the warning, the model works perfectly.

**Comment by bvandijkman** [comment]
Same issue here.

**Comment by MohammadYosifSharaf** [comment]
I think this warning may refer to a problem in building the domain file, and the main cause of this may be a failed in rasa core training, you can check if I am correct when you check you Rasa log, you may see something  like:

"Core training was skipped because no valid domain file was found. Only an nlu-model was created.Please specify a valid domain using '--domain' argument or check if the provided domain file exists."


best wishs

**Comment by jk123vip** [comment]
Did you just train NLU model?

**Comment by vish0701** [comment]
I am getting the same issue. I am just using the NLU part of Rasa. And hence running only 
`rasa train nlu` command to train my model. My domain.yml file exists in the same folder from where I am running the command to invoke the rasa server (`rasa run --enable-api -m models/nlu-20200615-120152.tar.gz`)

**Comment by riyashah17** [comment]
@vish0701 I'm also doing the exact same thing and facing this same issue. I have specified all the intents in the domain.yml file. Were you able to solve this issue?

**Comment by gunjanraval** [comment]
The error is because the model is not able to find any responses for the intent, to solve in the domain.yml file add 'responses' something like this:

`responses:
  utter_greet:
  - text: Hey there! How may I help you
  - text: Hello there! How can I help you
  - text: Hi, How may I help you today`

Do the same for each utter intent you have

**Comment by anushkaparadkar** [comment]
@RaminParker Thanks! That worked for me

**Comment by AmirthaRajan** [comment]
I had the same issue

Thanks @mtrworld it worked for me

just did the below steps in addition to it

1. replace templates to responses in domain.yml

2. `rasa train -vv -dump-stories --force`

3. `rasa run actions # terminal 1`

4. `rasa shell # terminal 2`
