### ISSUE TITLE
examples/restaurantbot  Circuit breaker tripped

### ISSUE THREAD

**Issue by ncoder** [RasaHQ/rasa#5067]
**Rasa version**:
Rasa 1.6.1

Example is from git commit: 64f3927cf91f538c6e4cfd5f40debf6bb5c5d295

**Python version**:
Python 3.7.3

**Operating system** (windows, osx, ...):
osx

**Issue**:

simple demo restaurant bot trips the circuit breaker with a simple input:
"hello"
"hello"

There is a relevant closed issue here: https://github.com/RasaHQ/rasa/issues/2157

Please fix the example code and educate us on how to make correct stories that don't hit this issue.

**Error (including full traceback)**:
```
(rasa) restaurantbot $ rasa shell 
2020-01-13 10:47:32 INFO     root  - Starting Rasa server on http://localhost:5005
2020-01-13 10:47:37 INFO     absl  - Entry Point [tensor2tensor.envs.tic_tac_toe_env:TicTacToeEnv] registered with id [T2TEnv-TicTacToeEnv-v0]
2020-01-13 10:47:54 INFO     rasa.nlu.components  - Added 'SpacyNLP' to component cache. Key 'SpacyNLP-en'.
Bot loaded. Type a message and press enter (use '/stop' to exit): 
Your input ->  hello                                                                                                                                                       
how can I help you?
Your input ->  hello                                                                                                                                                       
2020-01-13 10:48:01 WARNING  rasa.core.processor  - Circuit breaker tripped. Stopped predicting more actions for sender 'default'.
I'm on it
I'm on it
what kind of cuisine would you like?
I'm on it
I'm on it
where?
I'm on it
I'm on it
what kind of cuisine would you like?
I'm on it
```

**Comment by sara-tagger** [comment]
Thanks for raising this issue, @TyDunn will get back to you about it soon✨

###### Please also check out the [docs](https://rasa.com/docs/) and the [forum](https://forum.rasa.com/) in case your issue was raised there too 🤗

**Comment by akelad** [comment]
Hey @ncoder this isn't a bug, there's no stories written designed to handle multiple `greet` intents in a row, so that flow may not work. This can be resolved by adding more stories where this happens, or changing the policy that handles this intent, or reducing the max history value
