### ISSUE TITLE
UserWarning: Interpreter parsed an intent ‘name:’ that is not defined in the domain

### ISSUE THREAD

**Issue by RaminParker** [RasaHQ/rasa#5074]
**Rasa version**: 1.6.1

**Rasa SDK version** (if used & relevant):1.6.0

**Rasa X version** (if used & relevant):

**Python version**: 3.6

**Operating system** (windows, osx, ...): Windows

**Issue**: 

Since I am not 100% sure if this is a bug or not, I apologize if I'm wrong. 

Although I have clearly defined my intents in the domain file, I get the following user warnings:

````
UserWarning: Interpreter parsed an intent 'name:' that is not defined in the domain.

UserWarning: Interpreter parsed an intent 'name_last:' that is not defined in the domain.

UserWarning: Interpreter parsed an intent 'street_name:' that is not defined in the domain.

UserWarning: Interpreter parsed an intent 'house_number:' that is not defined in the domain.
````

The full details are given in this forum post: [more details](https://forum.rasa.com/t/intent-not-defined-in-the-domain/23270)

The reason why I think it is useful to check wether this is a bug or not comes from this forum post where we discus the problem: [light bug in some formatting method](https://forum.rasa.com/t/unable-to-parse-intent-throws-error-rasa-lib-site-packages-rasa-core-processor-py-userwarning-interpreter-parsed-an-intent-hey-that-is-not-defined-in-the-domain-f-interpreter-parsed-an-intent-intent/23477)

**Comment by sara-tagger** [comment]
Thanks for the issue, @btotharye will get back to you about it soon!

###### You may find help in the [docs](https://rasa.com/docs/) and the [forum,](https://forum.rasa.com/) too 🤗

**Comment by btotharye** [comment]
Sorry for the late reply @RaminParker I'll take a look at this today and get back to you

**Comment by btotharye** [comment]
Haven't forgotten about you will get you something on this shortly, just been swamped

**Comment by btotharye** [comment]
just responded to the forum thread @RaminParker

**Comment by smar10** [comment]
Same bug here.
Besides the warning, the model works perfectly.

**Comment by RaminParker** [comment]
In my case, it seems like I solved the problem. The mistake was in the frontend. Please see here: [Link to forum post](https://forum.rasa.com/t/intent-not-defined-in-the-domain/23270/14)
