### ISSUE TITLE
Transform `additional_arguments` (ex-`kwargs`) to a custom class instance

### ISSUE THREAD

**Issue by alwx** [RasaHQ/rasa#5077]
**Description of Problem**:

[https://github.com/RasaHQ/rasa/pull/5063](https://github.com/RasaHQ/rasa/pull/5063) renames `kwargs` to `additional_arguments`. However, there is still one issue intentionally left unresolved: `dump_stories` argument in rasa.train seems redundant — it can easily be moved to `additional_arguments`, and there is no need to keep it separately. However, the better option is not only to move it there but also to make a custom class for `additional_arguments` in order to make it clear what specific arguments it can contain. It will also help to make the information about types of specific arguments explicit.

**Overview of the Solution**: A custom class for additional_arguments. In this case, the `extract_additional_arguments` function (`rasa/cli/train.py`) becomes no more than just a helper to construct an instance of a class (by the way, I'm not sure if this kind of helper is needed and cannot be replaced by a class constructor).

**Definition of Done**:

*   [ ] A class constructor is added
*   [ ] The usage of `additional_arguments` is updated
*   [ ] Tests are updated

**Comment by wochinge** [comment]
Perfect thanks!
