### ISSUE TITLE
Use only one pytest plugin for async operations

### ISSUE THREAD

**Issue by alwx** [RasaHQ/rasa#5088]
**Description of Problem**:

I introduced `pytest-asyncio` to fix the issue with some tests being not asynchronous ([https://github.com/RasaHQ/rasa/pull/5080](https://github.com/RasaHQ/rasa/pull/5080)). It does it job pretty well, but it partially duplicates the behavior of `pytest-sanic`, and we don't really need two libraries for async operations.

The reason why `pytest-asyncio` is needed in this specific case seems to be related to the fact that `responses` library makes async functions not asynchronous for some reason. We theoretically can introduce another hack — maybe our own decorator that makes them asynchronous again. The more proper way of solving this issue — send a pull request to `responses` library to fix the problem of async operations becoming non-async after you add a `@response.activate` decorator to them.

I am not sure if it makes sense at all, and maybe there is another way around, but we should definitely think of it to reduce the number of dependencies.

**Definition of Done**:

*   [ ] Existing tests pass
*   [ ] Only one library is used for async operations — either `pytest-sanic` or `pytest-asyncio`

**Comment by tmbo** [comment]
I don't think there is anything more we can do right now, we need the sanic test library but also the asyncio one for some of the async tests right?

**Comment by wochinge** [comment]
This is causing issues as Rasa X `async` tests fail due to `pytest-asyncio`. We should consolidate that immediately as related issues come up in Slack regularly.
