### ISSUE TITLE
Response before message is handled on facebook channel

### ISSUE THREAD

**Issue by tomasis98** [RasaHQ/rasa#5089]
**Rasa version**: 1.6.1
**Rasa SDK version**: 1.6.1
**Python version**: 3.6
**Operating system**: Mac OS
**Issue**:
We're facing the problem with sending response to Facebook on post webhook. In general, response on webhook should be send asap because Facebook starts sending requests repeatedly in case of not getting response in time.

The problem is in Sanic webhook architecture. In default, it doesn't have option to return response sooner than handle message. As we've found out, there are the cases, where handling messages takes several seconds. In these cases, executions pauses on message handling and response is not sent immediately.

We've come up with 2 possible solutions:
1. Advanced post_response middleware from [Sanic Plugins](https://pypi.org/project/Sanic-Plugins-Framework/) (Basic Sanic middleware is not called before response return.) 
2. [ensure_future](https://docs.python.org/3/library/asyncio-future.html#asyncio.ensure_future) (Not sure if it is good practice to execute async function without waiting)

In first case, we can't test it because Rasa doesn't offer option of passing plugin to Sanic server. If our approach is good, it might lead to future feature request.

In second case, we've tried code like this:
```python asyncio.ensure_future(handler.handle(request.json), loop=asyncio.get_event_loop())```
and it seems to be working with warning 
```Coroutine 'ensure_future' is not waited```

**Command or request that led to error**: [FB connector](https://github.com/RasaHQ/rasa/blob/master/rasa/core/channels/facebook.py#L336)
```python
        @fb_webhook.route("/webhook", methods=["POST"])
        async def webhook(request: Request) -> HTTPResponse:
            signature = request.headers.get("X-Hub-Signature") or ""
            if not self.validate_hub_signature(self.fb_secret, request.body, signature):
                logger.warning(
                    "Wrong fb secret! Make sure this matches the "
                    "secret in your facebook app settings"
                )
                return response.text("not validated")

            messenger = Messenger(self.fb_access_token, on_new_message)

            metadata = self.get_metadata(request)
            await messenger.handle(request.json, metadata)
            return response.text("success")
```

**Comment by cowjen01** [comment]
I would like to add that for now we've came up with a backup solution - simple Node.js server working as a gateway for all incoming requests. Right after the request is handled we response with ok status and forward the request to the Rasa Server API.

**Comment by sara-tagger** [comment]
Thanks for the issue, @JustinaPetr will get back to you about it soon!

###### You may find help in the [docs](https://rasa.com/docs/) and the [forum,](https://forum.rasa.com/) too 🤗
