### ISSUE TITLE
Multi-Intent and Login

### ISSUE THREAD

**Issue by greatsharma** [RasaHQ/rasa#5090]
4 months ago I asked [this](https://forum.rasa.com/t/why-seperate-data-for-multi-intent/15667) question at rasa forums regarding `multi-intent` and in reply I was told that the feature I am looking for is currently not available in rasa. I just want to know is it supported now? 

Also I am posting this question here but not in the forums because I am unable to login. On trying to login it says `You can't log in as GauravSharma from that IP address.` 

Please help how to login now and also my above question regarding multi-intent

**Comment by sara-tagger** [comment]
Thanks for raising this issue, @tabergma will get back to you about it soon✨

###### Please also check out the [docs](https://rasa.com/docs/) and the [forum](https://forum.rasa.com/) in case your issue was raised there too 🤗

**Comment by tabergma** [comment]
@greatsharma We still not support multi-intents. Our intent classifier predicts just one intent at a time.

I'll close this issue as it is question. You can still add a comment. Not sure how to help you with the login, if we come across a solution, we will let you know.
