### ISSUE TITLE
Training Data Issue

### ISSUE THREAD

**Issue by ahtesham12** [RasaHQ/rasa#5098]
I have training data error, , kindly give solution.
![training-data](https://user-images.githubusercontent.com/36069404/72777237-cce13d00-3bc9-11ea-89db-ff5a5d400c01.PNG)

**Comment by sara-tagger** [comment]
Thanks for the question, our Github issue board is for **bugs and feature requests only,** though 😕
Please ask this question in the [forum✨](https://forum.rasa.com/c/rasa)

###### If you were describing a bug, please create a [report](https://github.com/RasaHQ/rasa/issues/new?labels=bug&template=bug_report.md) and fill out the template.
