### ISSUE TITLE
link to local test with ngrok in docs is broken

### ISSUE THREAD

**Issue by JSchuurmans** [RasaHQ/rasa#5101]
link:  `ngrok <https://rasa.com/docs/rasa-x/get-feedback-from-test-users/#use-ngrok-for-local-testing>`

in file: [docs/user-guide/messaging-and-voice-channels.rst](https://github.com/RasaHQ/rasa/blob/master/docs/user-guide/messaging-and-voice-channels.rst)

is broken.

**Comment by sara-tagger** [comment]
Thanks for the issue, @Ghostvv will get back to you about it soon!

###### You may find help in the [docs](https://rasa.com/docs/) and the [forum,](https://forum.rasa.com/) too 🤗

**Comment by erohmensing** [comment]
Correctly links to ngrok now, thanks for pointing out
