### ISSUE TITLE
Rasa's install of old Tensorflow breaks "curl"

### ISSUE THREAD

**Issue by John-Nagle** [RasaHQ/rasa#5104]
Rasa 1.6.1

**Python version**:
3.7.6.

**Operating system** (windows, osx, ...):
Ubuntu 18.04 LTS

**Issue**:
Rasa's install of old Tensorflow breaks "curl", which breaks iDrive backups

Installing current Rasa installs obsolete Tensorflow 1.15. Tensorflow installs its own modded version of libcurl, turning on Google Cloud support. This messes up dependencies and means "curl", the command line program, cannot be installed. This, in turn, breaks the iDrive backup system because "curl" is missing.

This is mostly a Tensorflow problem, but because it's a Tensorflow problem in an older version, it's unlikely to be fixed from a bug report on Tensorflow. 

More details here, in Ubuntu forums.

Ref: https://ubuntuforums.org/showthread.php?t=2435412

**Error (including full traceback)**:
```

```

**Command or request that led to error**:
```

```

**Content of configuration file (config.yml)** (if relevant):
```yml

```

**Content of domain file (domain.yml)** (if relevant):
```yml

```

**Comment by sara-tagger** [comment]
Thanks for the issue, @JustinaPetr will get back to you about it soon!

###### You may find help in the [docs](https://rasa.com/docs/) and the [forum,](https://forum.rasa.com/) too 🤗

**Comment by tmbo** [comment]
we are working on upgrading to TF 2.0 #5127 #5087 

This will be closed as soon as that is released. until then I don't think there is anything we can do.
