### ISSUE TITLE
Hello, I am facing an issue with deprication of utter_attatchment function from the collecting dispatcher. I searched for the alternatives for this function. I could not find any alternative to this. Please suggest me any new update to this.

### ISSUE THREAD

**Issue by pudasainishushant** [RasaHQ/rasa#5105]

**Comment by sara-tagger** [comment]
Thanks for the question, our Github issue board is for **bugs and feature requests only,** though 😕
Please ask this question in the [forum✨](https://forum.rasa.com/c/rasa)

###### If you were describing a bug, please create a [report](https://github.com/RasaHQ/rasa/issues/new?labels=bug&template=bug_report.md) and fill out the template.
