### ISSUE TITLE
example/knowledgebasebot. There is no credential.yml, running on web socket is giving exception

### ISSUE THREAD

**Issue by Gurdershan** [RasaHQ/rasa#5114]
**Rasa version**:

**Rasa SDK version** (if used & relevant):

**Rasa X version** (if used & relevant):

**Python version**:

**Operating system** (windows, osx, ...):

**Issue**:

**Error (including full traceback)**:
```

```

**Command or request that led to error**:
```

```

**Content of configuration file (config.yml)** (if relevant):
```yml

```

**Content of domain file (domain.yml)** (if relevant):
```yml

```

**Comment by sara-tagger** [comment]
Thanks for raising this issue, @tmbo will get back to you about it soon✨

###### Please also check out the [docs](https://rasa.com/docs/) and the [forum](https://forum.rasa.com/) in case your issue was raised there too 🤗

**Comment by tmbo** [comment]
Please provide an issue description as well as a proper stacktrace if there is an error. I am sorry, but I need to close this as it is missing essential information.
