### ISSUE TITLE
Contribution for Elmo Featurizer

### ISSUE THREAD

**Issue by VarunNatraaj** [RasaHQ/rasa#5121]
**Description of Problem**:

Rasa is extremely powerful and comes packed with lots of features. Primarily the types of NLU training pipelines it has are wonderful. However, when I was training for a particular use case, I found that the available pipelines have some drawbacks.

1) **Supervised** - 
  Trains embeddings from scratch using a modified version of Starspace
  However this has a hard time generalising, especially if you have newer unseen words
2) **Pretrained conveRT/spacy** -
  These embeddings are good, but they are not really contextual. And so if there are some training samples that are slightly overlapping, the embeddings do not change depending on the context, causing the predictions to be skewed again.

**Overview of the Solution**:

The first step I looked to in terms of a solution was [Elmo](https://allennlp.org/elmo).

Elmo generates contextual word embeddings that vary depending on the surrounding context. This helps generating better embeddings, and thereby leading to better predictions and generalisation. In my experiments, I found it to give better accuracy, and therefore I wanted to make it a contribution so as to help other folks. This is my first Open Source contribution, so feel free to give me pointers or feedback :)

**Definition of Done**:
- [x] ElmoFeaturizer added
- [x] Tests are added

Please let me know how to proceed!

**Comment by dakshvar22** [comment]
Hi @VarunNatraaj , thanks for posting your observations.
ConveRT embeddings are definitely contextual and more suited for dialog related tasks. Can you share the actual numbers from your tests for different pipelines you tried? A few details(language, spelling errors, domain, etc.) about the dataset you have trained your assistant on will also be helpful.

Thanks

**Comment by VarunNatraaj** [comment]
Hello @dakshvar22 , thanks for replying. Let me check my stash for the data you asked for and get back :)

**Comment by VarunNatraaj** [comment]
Caught up in other experiments. Will probably be a while until I collect quantitative data. Closing this until then. Thanks!
