### ISSUE TITLE
Clean up issues which are not in a project board

### ISSUE THREAD

**Issue by wochinge** [RasaHQ/rasa#5128]
- [ ] move issues which are not in board to board or close
- [ ] automatize issue assignment to boards 

`no:project is:issue is:open`

**Comment by wochinge** [comment]
@tmbo What's the state of this? Anything we can do to help?

**Comment by tmbo** [comment]
no, but I'll block something next week monday - thanks for the reminder :+1:

**Comment by edmacovaz** [comment]
Is this issue still current or can I close it?

**Comment by tmbo** [comment]
yes can be closed
