### ISSUE TITLE
Bug in analytics service after rasa x upgrade

### ISSUE THREAD

**Issue by koszta5** [RasaHQ/rasa#5130]
After upgrading to current version of rasa x (0.24.2) I experienced the followning exception when startin rasa:
```
ERROR:rasax.community.services.event_service:Caught an exception while consuming events. Will retry in 5 s.
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/rasax/community/services/event_service.py", line 970, in continuously_consume
    consumer.consume()
  File "/usr/local/lib/python3.6/dist-packages/rasax/community/services/event_consumers/sqlite_consumer.py", line 37, in consume
    origin=DEFAULT_RASA_ENVIRONMENT,
  File "/usr/local/lib/python3.6/dist-packages/rasax/community/services/event_consumers/event_consumer.py", line 124, in log_event
    self.analytics_service.save_analytics(data, sender_id=event.conversation_id)
  File "/usr/local/lib/python3.6/dist-packages/rasax/community/services/analytics_service.py", line 333, in save_analytics
    self.update_session_data(event)
  File "/usr/local/lib/python3.6/dist-packages/rasax/community/services/analytics_service.py", line 343, in update_session_data
    or event_timestamp - latest_session.latest_event_time > SESSION_TIMEOUT
TypeError: unsupported operand type(s) for -: 'float' and 'NoneType'
```

I fixed it like this... 
line 343 in analytics_service.py
if (
>>            not latest_session **or not latest_session.latest_event_time**
            or event_name == Restarted.type_name
            or event_timestamp - latest_session.latest_event_time > SESSION_TIMEOUT
        ):

**Comment by sara-tagger** [comment]
Thanks for the issue, @TyDunn will get back to you about it soon!

###### You may find help in the [docs](https://rasa.com/docs/) and the [forum,](https://forum.rasa.com/) too 🤗

**Comment by wochinge** [comment]
How did you install Rasa X @koszta5 ?

**Comment by koszta5** [comment]
Here is my dockerfile:

FROM ubuntu:18.04
RUN echo "root:docker" | chpasswd
RUN apt-get --yes --force-yes update
RUN apt-get --yes --force-yes install sudo
RUN useradd -ms /bin/bash rasa
RUN echo "rasa:rasa" | chpasswd
RUN usermod -aG sudo rasa
RUN apt-get --yes --force-yes install net-tools
RUN apt-get --yes --force-yes install lsof
RUN apt-get --yes --force-yes install python3
RUN apt-get --yes --force-yes install python3-pip
RUN update-alternatives --install /usr/bin/python python /usr/bin/python3.6 1
RUN update-alternatives --install /usr/bin/pip pip /usr/bin/pip3 1
RUN pip install -U pip
RUN pip install rasa-x==0.24.4 --extra-index-url https://pypi.rasa.com/simple
RUN pip install google-auth==1.10.1
RUN pip install prompt-toolkit==2.0.10
RUN pip install questionary==1.4.0
RUN pip install SQLAlchemy==1.3.12
RUN pip install urllib3==1.25.7
RUN apt-get --yes --force-yes install vim
RUN apt-get --yes --force-yes install locales
RUN sed -i -e 's/# en_US.UTF-8 UTF-8/en_US.UTF-8 UTF-8/' /etc/locale.gen && \
    locale-gen
ENV LANG en_US.UTF-8
ENV LANGUAGE en_US:en
ENV LC_ALL en_US.UTF-8
RUN echo "export LC_ALL=en_US.UTF-8" >> ~/.bashrc
RUN echo "export LANG=en_US.UTF-8" >> ~/.bashrc
RUN pip install rasa[spacy]==1.6.1
RUN python -m spacy download en_core_web_md
RUN python -m spacy link en_core_web_md en

**Comment by koszta5** [comment]
I think the whole problem was just about mounting an older version of rasa model to this newly created container. Can you confirm that this would make sense?

**Comment by wochinge** [comment]
> I think the whole problem was just about mounting an older version of rasa model to this newly created container. Can you confirm that this would make sense?

Mhm, actually that does not make sense 🤔 Which database are you using and are you using the default Rasa X image?

**Comment by koszta5** [comment]
well not using the default image; as shown above I install rasa x in docker. By "database" you mean the backend? That would be just files - as that is the default

**Comment by wochinge** [comment]
> well not using the default image; as shown above I install rasa x in docker. By "database" you mean the backend? That would be just files - as that is the default

Ok, that means it's using the sqlite database.

We can definitely fix that in the code 👍 Not sure why this is happening, did you have any weird code or restarted the container in between weird time? Can you try to re-run the container with a `--force-recreate`.

**Comment by wochinge** [comment]
Thinks to remember for the solution:

- `_create_new_session` does not need a `commit` 
- `latest_event_time` should have a default value
