### ISSUE TITLE
Rasa Tutorial includes commands that don't work on Windows

### ISSUE THREAD

**Issue by chkoss** [RasaHQ/rasa#5132]
**Operating system** (windows, osx, ...):
Windows

**Issue**:
Some code snippets that are shown in the Tutorial (https://rasa.com/docs/rasa/user-guide/rasa-tutorial/) do not work in the Windows command line.

**Proposed solution**:
Wherever it says `cat`, e.g. `cat data/nlu.md`, mention that on Windows you should instead use `type`.

**Comment by sara-tagger** [comment]
Thanks for raising this issue, @akelad will get back to you about it soon✨

###### Please also check out the [docs](https://rasa.com/docs/) and the [forum](https://forum.rasa.com/) in case your issue was raised there too 🤗

**Comment by chkoss** [comment]
Closing this because the tutorial will be removed in the new docs anyways
