### ISSUE TITLE
Production Rasa Resource temporarily unavailable

### ISSUE THREAD

**Issue by rmiaouh** [RasaHQ/rasa#5133]
**Rasa version**:
1.5.1

**Python version**:
3.6.9

**Operating system** (windows, osx, ...):
Linux (ubuntu)

**Issue**:
In a production server, when i try to enable the api with this command line 

```rasa run --enable-api```

i got a rasa/tensorflow a ''Resource temporarily unavailable - Aborted''

**Error (including full traceback)**:
```
Entry Point [tensor2tensor.envs.tic_tac_toe_env:TicTacToeEnv] registered with id [T2TEnv-TicTacToeEnv-v0]
terminate called after throwing an instance of 'std::system_error'
what(): Resource temporarily unavailable
Aborted
```
Here you can see the error :  https://prnt.sc/qtf65k

**Command or request that led to error**:
```
rasa run --enable-api
```

I want to know if the bug come from Rasa , Tensorflow or A Production Server Limitation, if someone can help me :)

ty for all

**Comment by sara-tagger** [comment]
Thanks for the issue, @btotharye will get back to you about it soon!

###### You may find help in the [docs](https://rasa.com/docs/) and the [forum,](https://forum.rasa.com/) too 🤗

**Comment by btotharye** [comment]
@rmiaouh do you have anything else custom here or installed?  For me this worked fine, I just tested in a venv installed `rasa==1.5.1` and ran the `rasa run --enable-api` and did not see this issue.
