### ISSUE TITLE
Shell/Interactive Learning throws 'This event loop is already running'

### ISSUE THREAD

**Issue by kappa90** [RasaHQ/rasa#5146]
Trying to install Rasa Open Source, this happens just after clean installation, if I try to use the "shell" or "interactive" command:

2020-01-29 09:06:40 INFO     root  - Connecting to channel 'cmdline' which was specified by the '--connector' argument. Any other channels will be ignored. To connect to all given channels, omit the '--connector' argument.
2020-01-29 09:06:40 INFO     root  - Starting Rasa server on http://localhost:5005
2020-01-29 09:06:44 INFO     absl  - Entry Point [tensor2tensor.envs.tic_tac_toe_env:TicTacToeEnv] registered with id [T2TEnv-TicTacToeEnv-v0]
Bot loaded. Type a message and press enter (use '/stop' to exit):
2020-01-29 09:06:46 ERROR    asyncio  - Task exception was never retrieved
future: <Task finished coro=<configure_app.<locals>.run_cmdline_io() done, defined at c:\...\rasa\core\run.py:124> exception=RuntimeError('This event loop is already
running')>
Traceback (most recent call last):
  File "c:\...\rasa\core\run.py", line 128, in run_cmdline_io
    server_url=constants.DEFAULT_SERVER_FORMAT.format("http", port)
  File "c:\...\rasa\core\channels\console.py", line 131, in record_messages
    text = get_user_input(button_question)
  File "c:\...\rasa\core\channels\console.py", line 77, in get_user_input
    style=Style([("qmark", "#b373d6"), ("", "#b373d6")]),
  File "c:\...\questionary\question.py", line 45, in ask
    return self.unsafe_ask(patch_stdout)
  File "c:\...\questionary\question.py", line 59, in unsafe_ask
    return self.application.run()
  File "c:\...\prompt_toolkit\application\application.py", line 810, in run
    return loop.run_until_complete(self.run_async(pre_run=pre_run))
  File "c:\...\anaconda3\Lib\asyncio\base_events.py", line 560, in run_until_complete
    self.run_forever()
  File "c:\...\anaconda3\Lib\asyncio\base_events.py", line 515, in run_forever
    raise RuntimeError('This event loop is already running')
RuntimeError: This event loop is already running

If I type any message into the input, it does not do anything.

-------------------
Python 3.7.1, running through a Conda distribution

These are my installed packages (pip freeze)
absl-py==0.9.0
aiofiles==0.4.0
aiohttp==3.6.2
APScheduler==3.6.3
astor==0.8.1
async-generator==1.10
async-timeout==3.0.1
asyncio==3.4.3
attrs==19.3.0
boto3==1.11.9
botocore==1.14.9
bz2file==0.98
cachetools==4.0.0
certifi==2019.11.28
cffi==1.13.2
chardet==3.0.4
Click==7.0
cloudpickle==1.2.2
colorama==0.4.3
colorclass==2.2.0
coloredlogs==10.0
colorhash==1.0.2
ConfigArgParse==1.0
cryptography==2.8
cycler==0.10.0
decorator==4.4.1
dill==0.3.1.1
dnspython==1.16.0
docopt==0.6.2
docutils==0.15.2
dopamine-rl==3.0.1
fbmessenger==6.0.0
Flask==1.1.1
future==0.18.2
gast==0.2.2
gevent==1.4.0
gin-config==0.3.0
google-api-python-client==1.7.11
google-auth==1.11.0
google-auth-httplib2==0.0.3
google-pasta==0.1.8
googleapis-common-protos==1.51.0
greenlet==0.4.15
grpcio==1.26.0
gunicorn==20.0.4
gym==0.15.4
h11==0.8.1
h2==3.1.1
h5py==2.10.0
hpack==3.0.0
httpcore==0.3.0
httplib2==0.17.0
httptools==0.0.13
humanfriendly==4.18
hyperframe==5.2.0
idna==2.8
importlib-metadata==1.4.0
itsdangerous==1.1.0
Jinja2==2.11.0
jmespath==0.9.4
jsonpickle==1.2
jsonschema==3.2.0
Keras-Applications==1.0.8
Keras-Preprocessing==1.1.0
kfac==0.2.0
kiwisolver==1.1.0
Markdown==3.1.1
MarkupSafe==1.1.1
matplotlib==3.1.2
mattermostwrapper==2.1
mesh-tensorflow==0.1.9
mpmath==1.1.0
multidict==4.6.1
networkx==2.3
numpy==1.18.1
oauth2client==4.1.3
opencv-python==4.1.2.30
opt-einsum==3.1.0
packaging==19.2
pika==1.0.1
Pillow==7.0.0
promise==2.3
prompt-toolkit==3.0.3
protobuf==3.11.2
pyasn1==0.4.8
pyasn1-modules==0.2.8
pycparser==2.19
pydot==1.4.1
pyglet==1.3.2
PyJWT==1.7.1
pykwalify==1.7.0
pymongo==3.10.1
pyparsing==2.4.6
pypng==0.0.20
pyreadline==2.1
pyrsistent==0.15.7
python-crfsuite==0.9.6
python-dateutil==2.8.1
python-engineio==3.11.2
python-socketio==4.4.0
python-telegram-bot==11.1.0
pytz==2019.3
PyYAML==5.3
questionary==1.5.1
rasa==1.6.1
rasa-sdk==1.6.1
redis==3.3.11
requests==2.22.0
requests-async==0.5.0
requests-toolbelt==0.9.1
rfc3986==1.3.2
rocketchat-API==0.6.36
rsa==4.0
ruamel.yaml==0.15.100
s3transfer==0.3.2
sanic==19.9.0
Sanic-Cors==0.9.9.post1
sanic-jwt==1.4.0
Sanic-Plugins-Framework==0.8.2.post1
scikit-learn==0.20.4
scipy==1.4.1
six==1.14.0
sklearn-crfsuite==0.3.6
slackclient==1.3.2
SQLAlchemy==1.3.13
sympy==1.5.1
tabulate==0.8.6
tensor2tensor==1.14.1
tensorboard==1.15.0
tensorflow==1.15.2
tensorflow-datasets==2.0.0
tensorflow-estimator==1.15.1
tensorflow-gan==2.0.0
tensorflow-hub==0.7.0
tensorflow-metadata==0.21.1
tensorflow-probability==0.7.0
termcolor==1.1.0
terminaltables==3.1.0
tqdm==4.42.0
twilio==6.35.3
tzlocal==2.0.0
uritemplate==3.0.1
urllib3==1.25.8
wcwidth==0.1.8
webexteamssdk==1.2
websocket-client==0.54.0
websockets==8.1
Werkzeug==0.16.1
wrapt==1.11.2
yarl==1.4.2
zipp==2.1.0

**Comment by federicotdn** [comment]
Hey @kappa90, could you try that again but using 1.6.2?

**Comment by kappa90** [comment]
Seems to be fixed with 1.6.2, thanks!
