### ISSUE TITLE
Slack Integration

### ISSUE THREAD

**Issue by srinathgnath** [RasaHQ/rasa#5149]
Hello,

I'm working on a project where I need to integrate Slack with RASA chatbot. I did follow the steps as  "https://rasa.com/docs/rasa/user-guide/connectors/slack/".

I do see messages reaching ngrok, But don't see anything at RASA server and also no response has been sent. Please let me know if I'm missing something.

Thanks

**Comment by sara-tagger** [comment]
Thanks for the question, our Github issue board is for **bugs and feature requests only,** though 😕
Please ask this question in the [forum✨](https://forum.rasa.com/c/rasa)

###### If you were describing a bug, please create a [report](https://github.com/RasaHQ/rasa/issues/new?labels=bug&template=bug_report.md) and fill out the template.
