### ISSUE TITLE
tensorflow-cpu version dependency problem during initial installation of rasa

### ISSUE THREAD

**Issue by ChaitanyaBhole** [RasaHQ/rasa#5153]
I had problem installing rasa as per the instructions on this page:-
https://rasa.com/docs/rasa/user-guide/installation

Am I missing something?

**Comment by sara-tagger** [comment]
Thanks for the issue, @ArjaanBuijk will get back to you about it soon!

###### You may find help in the [docs](https://rasa.com/docs/) and the [forum,](https://forum.rasa.com/) too 🤗

**Comment by ArjaanBuijk** [comment]
@ChaitanyaBhole ,
Please post your question to the [forum,](https://forum.rasa.com/) with more details on the steps you took, the OS you are using, and ideally the output that shows your issue.
