### ISSUE TITLE
Start testing against the latest dependency versions

### ISSUE THREAD

**Issue by alwx** [RasaHQ/rasa#5156]
**Rasa version**: 1.7.0

**Issue**:
When users install `rasa` we allow a range of versions of dependencies to be installed (which is necessary and best practice) but we are not testing against the latest ones. So we are missing some essential alerting there.

We could also keep it like it is and run the setup.py version as a regular cron job in travis. This way we don't block development and still get the errors.

**Comment by tmbo** [comment]
I think we should revisit after switching to poetry, if we add additional tests for different dependency versions they should probably be nightly builds instead of PR based, otherwise we will get even worse build turnaround times.
