### ISSUE TITLE
Terminate called after throwing an instance of 'Xbyak::Error' 

### ISSUE THREAD

**Issue by SaiSatwik** [RasaHQ/rasa#5158]
I tried to install rasa in my ubuntu vm. Rasa installation was successful. But I was not able to execute rasa init or rasa train command. I am getting the following error. 
```
2020-01-30 09:54:24 INFO     rasa.core.policies.keras_policy  - Fitting model with 126 total samples and a validation split of 0.1
terminate called after throwing an instance of 'Xbyak::Error'
  what():  can't protect
```
I tried running rasa using docker too. There also after executing "docker run -v $(pwd):/app rasa/rasa init --no-prompt" command I am getting the same error.

**Comment by sara-tagger** [comment]
Thanks for the question, our Github issue board is for **bugs and feature requests only,** though 😕
Please ask this question in the [forum✨](https://forum.rasa.com/c/rasa)

###### If you were describing a bug, please create a [report](https://github.com/RasaHQ/rasa/issues/new?labels=bug&template=bug_report.md) and fill out the template.
