### ISSUE TITLE
Confidence level down after upgrading the Rasa version from 1.4.3 to 1.6.2

### ISSUE THREAD

**Issue by kapoorh** [RasaHQ/rasa#5163]
Hi,

Previously I was using Rasa 1.4.3 and it was giving good confidence level for the trained questions. But it was taking more than 1 hr  to train a model for approx 250 intents.

Now I created different environment with version 1.6.2, now the training time has been improved but the confidence level of trained question has been down and because of this Rasa is not responding with the proper answer.

I am using below config:

language: en
pipeline: supervised_embeddings
policies:
- name: AugmentedMemoizationPolicy
- name: MappingPolicy
- name: FormPolicy
- name: TwoStageFallbackPolicy
  nlu_threshold: 0.8
  core_threshold: 0.5
  fallback_core_action_name: action_did_not_understand
  fallback_nlu_action_name: action_did_not_understand
  deny_suggestion_intent_name: general_out_of_scope

Example: I trained for "what is the diff between drop and delete"

In the version 1.4.3 conf level is 0.99 while in 1.6.2 conf level is 0.63

Thanks and Regards
Harsh

**Comment by sara-tagger** [comment]
Thanks for the issue, @Ghostvv will get back to you about it soon!

###### You may find help in the [docs](https://rasa.com/docs/) and the [forum,](https://forum.rasa.com/) too 🤗

**Comment by Ghostvv** [comment]
This known behavior due to the fact that softmax confidences saturate with number of classes. We implemented renormalization in `rasa 1.7` version: https://github.com/RasaHQ/rasa/pull/4902

**Comment by kapoorh** [comment]
Thanks for the reply @Ghostvv !! 

Do you mean that this issue has been resolved in rasa 1.7 version? 

Thanks and Regards
Harsh

**Comment by Ghostvv** [comment]
Yes, it should be resolved. Could you please try `1.7` version

**Comment by kapoorh** [comment]
Hi,

I upgraded rasa with the below command:
 **pip install -U rasa --extra-index-url https://pypi.rasa.com/simple**

It installed successfully but below error came:
**ERROR: rasa-x 0.24.6 has requirement rasa~=1.6.1, but you'll have rasa 1.7.0 which is incompatible.**

So, I updated rasa-x with:
 pip install -U rasa-x --extra-index-url https://pypi.rasa.com/simple

It uninstalled 1.7 version and installed 1.6.2 to match the compatibility. Got below output:

Installing collected packages: networkx, rasa-sdk, rasa, rasa-x
  Attempting uninstall: networkx
    Found existing installation: networkx 2.4
    Uninstalling networkx-2.4:
      Successfully uninstalled networkx-2.4
  Attempting uninstall: rasa-sdk
    Found existing installation: rasa-sdk 1.7.0
    Uninstalling rasa-sdk-1.7.0:
      Successfully uninstalled rasa-sdk-1.7.0
  Attempting uninstall: rasa
    Found existing installation: rasa 1.7.0
    Uninstalling rasa-1.7.0:
      Successfully uninstalled rasa-1.7.0
  Attempting uninstall: rasa-x
    Found existing installation: rasa-x 0.24.6
    Uninstalling rasa-x-0.24.6:
      Successfully uninstalled rasa-x-0.24.6
Successfully installed networkx-2.3 rasa-1.6.2 rasa-sdk-1.6.1 rasa-x-0.24.7

Finally again 1.6.2 version is there.

**Comment by tmbo** [comment]
we will release a compatible rasa x version in the next days

**Comment by kapoorh** [comment]
And I hope with the new release the below open issue will also get resolved.
[#4768](https://github.com/RasaHQ/rasa/issues/4768)

**Comment by kapoorh** [comment]
Hi,

I have updated with the latest versions for both rasa and rasa-x. Now training time is good and conf has been improved but not that great. In most of the question its running TwoStageFallbackPolicy. Now for the straight forward questions its giving conf level around .78 and i have set 0.80 threshold. In the earlier version it was working perfectly with 0.99 or 0.98 conf level.

Thanks and Regards
Harsh

**Comment by Ghostvv** [comment]
The algorithm have changed. Would it work for you if you change threshold levels?
