### ISSUE TITLE
Allow spaces in response messages

### ISSUE THREAD

**Issue by AndiLeni** [RasaHQ/rasa#5167]
**Description of Problem**:
Spaces in the response templates are ignored. 
If multiple responses are sent from the actions.py script, they contain no space to separate the sentences.

Why is this feature needed? 
https://forum.rasa.com/t/response-message-should-contain-space/24029

**Overview of the Solution**:
F.e. make this work inside the domain.yml:
````
utter_test:
  - text: " This is an example. "
````

**Comment by sara-tagger** [comment]
Thanks for submitting this feature request 🚀@amn41 will get back to you about it soon!✨

**Comment by tmbo** [comment]
This seems to be more an issue of the output channel than our trimming. The channel should make sure that messages are properly separated (e.g. facebook does this by displaying them in separate speech bubbles). 

I don't think this is something that should be handled internally. If this is an issue with the commandline input / output channel, we should fix it there.
