### ISSUE TITLE
Remove deprecated model and pipeline options

### ISSUE THREAD

**Issue by tabergma** [RasaHQ/rasa#5178]
(Valid after Rasa 1.8.0 or Rasa 1.9.0 is out)

`EmbeddingIntentClassifier`, `KerasPolicy`, `EmbeddingPolicy` should not be used anymore. As they are already deprecated, remove them from the code base. 
Also we updated the model options. So far we were still replacing old options with new ones. Do not replace old options anymore and print an error instead.
We also deprecated the pipeline templates for NLU, e.g. `supervised_embeddings`. Remove those from the code base and don't forget to update example configs and tests.

**Overview of the Solution**:
- [x] Remove `EmbeddingIntentClassifier`
- [x] Remove `KerasPolicy`
- [x] Remove `EmbeddingPolicy`
- [x] Remove replacement of old options, print error instead
- [x] Remove pipeline templates
- [x] Update documentation
- [x] Remove `rasa_core` and `rasa_nlu` packages 

This is not a complete list. Once the issue is started to be worked on, the source code has to be checked again.

We can also remove all the things that are marked as deprecated.

**Comment by MichaelMarien** [comment]
I'd be happy to look at this.

**Comment by wochinge** [comment]
@MichaelMarien Thanks for showing initiative! Since we just did the deprecations in `1.8.0`, we should still wait a couple of versions before we entirely remove them. Please check out https://github.com/orgs/RasaHQ/projects/23 for other issues where you could help out 🙂

**Comment by MichaelMarien** [comment]
Makes sense! Thanks I'll take a look.
