### ISSUE TITLE
Allow use of slots as variables in stories

### ISSUE THREAD

**Issue by rgstephens** [RasaHQ/rasa#5192]
**Description of Problem**:
Would like to use slot values as variables in a story.

**Examples** (if relevant):
For example:

```
* how_to_get_started{"user_type": "new"}
  - utter_welcome_{user_type}
```

**Comment by amn41** [comment]
Why not use a custom action that uses the slot name?

**Comment by rgstephens** [comment]
The customer would prefer not to have to write a python function.

**Comment by amn41** [comment]
It doesn’t make sense to do this. 

1. There is a perfectly good way of achieving the same result. 
2. Introducing this would require adding a whole new concept to the training data format, which is a huge cost
3.  Stories are training data, not a programming language

**Comment by joejuzl** [comment]
Closing as per @amn41's comment.
