### ISSUE TITLE
Symlinks for training data

### ISSUE THREAD

**Issue by govertbuijs** [RasaHQ/rasa#5204]
**Rasa version**: 1.7.0

**Rasa SDK version** (if used & relevant): 1.7.0

**Rasa X version** (if used & relevant):

**Python version**: 3.7.3

**Operating system** (windows, osx, ...): Linux

**Error (including full traceback)**:``` ```

**Command or request that led to error**:``` ```

**Issue**: Rasa doesn't follow symlinks while importing training data.
I need to make agents for multiple languages with identical stories.
To prevent file duplication, it would be nice to use symlinks to a central file.

To fix this, ```followlinks=True``` needs to be added to the   
```_find_core_nlu_files_in_directory``` function in rasa/data.py, line 105.

Current : ```for root, _, files in os.walk(directory):```
Fix : ```for root, _, files in os.walk(directory, followlinks=True):```

**Comment by sara-tagger** [comment]
Thanks for the issue, @tmbo will get back to you about it soon!

###### You may find help in the [docs](https://rasa.com/docs/) and the [forum,](https://forum.rasa.com/) too 🤗

**Comment by tmbo** [comment]
@govertbuijs that sounds like a great addition, do you mind creating a PR for that?

**Comment by govertbuijs** [comment]
@tmbo 

I would love to do that.

Looking at the code i see 4 other instances of os.walk :
1. rasa/utils/io.py : list_directory()
2. rasa/core/domain.py : Domain.from_directory()
3. rasa/importers/multi_project.py : MultiProjectImporter._init_from_directory()
4. rasa/nlu/utils/__init__.py : is_model_dir()

Especially the first 3 seem good candidates to change as well.

**Comment by tmbo** [comment]
@govertbuijs sounds good let's change them :star:
