### ISSUE TITLE
Slack integration not working with Moodbot

### ISSUE THREAD

**Issue by zaidalvi** [RasaHQ/rasa#5206]
Hi guys. I have been trying to integrate Rasa moodbot with slack using tutorial the problem arises when the moodbot has to respond on slack. The bot works perfectly fine on socket.io and Rasa X but for some reason it does not respond on slack. This is my process:

rasa run (by default this goes to 5005)
ngrok http 5005
copy the first link in my endpoints file (http:-ngroklink-:5055/webook
rasa run on port 5002
ngrok http 5002
copy that link in event subscriptions
URL gets validated

When I try talking to my bot the terminal shows that the intents have been predicted without any errors but the bot response is not shown in the slack window.

<img width="1604" alt="console" src="https://user-images.githubusercontent.com/36755611/74101793-73808400-4b5f-11ea-8ddd-9cee97e8046b.png">

**Comment by sara-tagger** [comment]
Thanks for raising this issue, @wochinge will get back to you about it soon✨

###### Please also check out the [docs](https://rasa.com/docs/) and the [forum](https://forum.rasa.com/) in case your issue was raised there too 🤗

**Comment by wochinge** [comment]
Please ask questions in the [Rasa Forum](https://forum.rasa.com) @zaidalvi .
