### ISSUE TITLE
libprotobuf issue occurs will creates a new project using cli

### ISSUE THREAD

**Issue by iamadhihere** [RasaHQ/rasa#5208]
I have also  installed the protobuf-3.8.0 but it still throwing the same error

**`pip show protobuf`**

**Name: protobuf
Version: 3.8.0
Summary: Protocol Buffers
Home-page: https://developers.google.com/protocol-buffers/
Author: None
Author-email: None
License: 3-Clause BSD License
Location: /home/alertnet/Desktop/alertServer/lib/python3.6/site-packages
Requires: setuptools, six
Required-by: tensorflow, tensorflow-metadata, tensorflow-hub, tensorflow-datasets, tensorflow-cpu, tensorboard, googleapis-common-protos**

**/usr/local/bin/protoc --version**
libprotoc 3.8.0

**rasa init**
it throws following error
 
[libprotobuf FATAL google/protobuf/stubs/common.cc:61] This program requires version 3.8.0 of the Protocol Buffer runtime library, but the installed version is 2.6.1.  Please update your library.  If you compiled the program yourself, make sure that your headers are from the same version of Protocol Buffers as your link-time library.  (Version verification failed in "bazel-out/k8-opt/genfiles/tensorflow/core/framework/tensor_shape.pb.cc".)

terminate called after throwing an instance of 'google::protobuf::FatalException'
  what():  This program requires version 3.8.0 of the Protocol Buffer runtime library, but the installed version is 2.6.1.  Please update your library.  If you compiled the program yourself, make sure that your headers are from the same version of Protocol Buffers as your link-time library.  (Version verification failed in "bazel-out/k8-opt/genfiles/tensorflow/core/framework/tensor_shape.pb.cc".)
Aborted (core dumped)

**Comment by iamadhihere** [comment]
> I have also installed the protobuf-3.8.0 but it still throwing the same error
> 
> **`pip show protobuf`**
> 
> **Name: protobuf Version: 3.8.0 Summary: Protocol Buffers Home-page: https://developers.google.com/protocol-buffers/ Author: None Author-email: None License: 3-Clause BSD License Location: /home/alertnet/Desktop/alertServer/lib/python3.6/site-packages Requires: setuptools, six Required-by: tensorflow, tensorflow-metadata, tensorflow-hub, tensorflow-datasets, tensorflow-cpu, tensorboard, googleapis-common-protos**
> 
> **/usr/local/bin/protoc --version**
> libprotoc 3.8.0
> 
> **rasa init**
> it throws following error
> 
> [libprotobuf FATAL google/protobuf/stubs/common.cc:61] This program requires version 3.8.0 of the Protocol Buffer runtime library, but the installed version is 2.6.1. Please update your library. If you compiled the program yourself, make sure that your headers are from the same version of Protocol Buffers as your link-time library. (Version verification failed in "bazel-out/k8-opt/genfiles/tensorflow/core/framework/tensor_shape.pb.cc".)
> 
> terminate called after throwing an instance of 'google::protobuf::FatalException'
> what(): This program requires version 3.8.0 of the Protocol Buffer runtime library, but the installed version is 2.6.1. Please update your library. If you compiled the program yourself, make sure that your headers are from the same version of Protocol Buffers as your link-time library. (Version verification failed in "bazel-out/k8-opt/genfiles/tensorflow/core/framework/tensor_shape.pb.cc".)
> Aborted (core dumped)

After a long struggle, I got it by downgrade the rasa version: 1.5.0 uninstalling the tensorboard

**Comment by sara-tagger** [comment]
Thanks for the issue, @akelad will get back to you about it soon!

###### You may find help in the [docs](https://rasa.com/docs/) and the [forum,](https://forum.rasa.com/) too 🤗

**Comment by akelad** [comment]
@iamadhihere which rasa version were you on before?

**Comment by iamadhihere** [comment]
@akelad I have used 1.7.0

**Comment by akelad** [comment]
you could try uninstalling/reinstalling the package? in any case, i don't think this issue is rasa specific - you could try posting on their github page
