### ISSUE TITLE
Simplify Dockerfiles by using the same base image

### ISSUE THREAD

**Issue by alwx** [RasaHQ/rasa#5229]
We have several Dockerfiles in `docker` directory, but all of them just duplicate the main one (`./Dockerfile`) and add something small to it. 
The idea is to make one base image and use it for all the additional images.

It'll help to keep all Dockerfiles in sync, and will make the process of updating them much easier.

**Comment by m-vdb** [comment]
cc @tczekajlo I don't know if it's relevant to your work on dockerfiles 🤷

**Comment by tczekajlo** [comment]
I can adopt this issue, one issue less to create :D

**Comment by tczekajlo** [comment]
Resolved be https://github.com/RasaHQ/rasa/issues/7574
