### ISSUE TITLE
dependency seems to cause segmentation fault

### ISSUE THREAD

**Issue by erohmensing** [RasaHQ/rasa#5231]
I'm collecting issues where users have started recently seeing `segmentation fault`s here. For multiple it seems that installing `gym 0.15.3` or `0.15.4` fixed the issue, but some of them seemed to have needed to change the `sanic-plugins-framework` as well. It's worth noting that [this thread](https://forum.rasa.com/t/rasa-shell-segmentation-fault/24485/4?u=erohmensing) seems to indicate that the release of 0.15.6 could be causing the issue, but when I install all the dependencies on my Mac, I end up with gym 0.14.0. The issues seem to occur only on Ubuntu (maybe because it gets this newer version?), but on different versions and different platforms.

https://github.com/RasaHQ/rasa/issues/5196
https://github.com/RasaHQ/rasa/issues/5228
https://forum.rasa.com/t/segmentation-fault-core-dumped/4214 
https://forum.rasa.com/t/rasa-shell-segmentation-fault/24485/3
https://forum.rasa.com/t/odd-problem-of-rasa-train-segmentation-fault-core-dumped/24695/4
https://forum.rasa.com/t/issue-running-rasa-on-google-cloud-compute-engine-instance/24683

**Comment by Suniron** [comment]
Hello! Your post falls well because not able to install Rasa on my raspberry 4 4gb with Ubuntu (I created an exit for this problem), I tried to install it on a mini small laptop PC and the installation ended without error!
Only at launch I had an error:  `(core dumped) `. I can't launch.

**Comment by erohmensing** [comment]
@Suniron will you please create a forum post on the topic? It seems like it could be a different issue. Feel free to tag me in it there.

**Comment by Suniron** [comment]
I'm going to create a subject right now. Thanks for the advice.

**Comment by Suniron** [comment]
https://forum.rasa.com/t/ubuntu-18-04-64-bits-core-dumped-error-on-launch/24798 :1st_place_medal:

**Comment by erohmensing** [comment]
Original issue closed by #5248
