### ISSUE TITLE
Executing core from a systemd service make it crash

### ISSUE THREAD

**Issue by facureyes** [RasaHQ/rasa#5244]
**Rasa version**:1.7.0

**Python version**:3.7

**Operating system** :Ubuntu 18.04

**Issue**: Core service crashes when I try to talk to bot.
I have to services running on my server, as [this post](https://forum.rasa.com/t/how-to-run-rasa-as-service-in-linux/22588/4?) suggest. 
The core service works fine, but as soon as I talk to the bot the core service crashes.
If I execute the core from a regular terminal it all works fine. 

**Error (including full traceback)**:
```
Feb 14 14:47:33 instance-2 systemd[1]: chatbot_core.service: Main process exited, code=killed, status=11/SEGV
Feb 14 14:47:33 instance-2 systemd[1]: chatbot_core.service: Failed with result 'signal'.
```

**Comment by sara-tagger** [comment]
Thanks for the issue, @erohmensing will get back to you about it soon!

###### You may find help in the [docs](https://rasa.com/docs/) and the [forum,](https://forum.rasa.com/) too 🤗

**Comment by erohmensing** [comment]
@facureyes not quite sure what you mean by `core service` in this case. Are you using docker-compose to run multiple services? What does your deployment setup look like?

**Comment by facureyes** [comment]
Hi! **core service** is a systemd service that I created. The **chatbot_core.service** looks like this:

```
[Unit]
Description=Rasa-Core
After=multi-user.target

[Service]
Type=simple
WorkingDirectory=/home/ib/xx
ExecStart=/home/ib/miniconda3/envs/rasa1.7.0/bin/python3 -m rasa run --ssl-certificate fullchain.pem --ssl-keyfile privkey.pem -vv --port 5004 --cors '*' --enable-api --model /home/ib/xx/models/ --endpoints </home/ib/xx/endpoints.yml --credentials /home/ib/xx/credentials.yml
Group=daemon
```
If I copy and paste what is on ExecStart command and run it in a new terminal it works as it should be.
I am not using docker-compose, I just created 2 systemd services, one for execute rasa run actions (that one works fine) and this other 'chatbot_core' which has this error:

```
Feb 14 14:47:33 instance-2 systemd[1]: chatbot_core.service: Main process exited, code=killed, status=11/SEGV
Feb 14 14:47:33 instance-2 systemd[1]: chatbot_core.service: Failed with result 'signal'.
```

**Comment by erohmensing** [comment]
If you add `--debug` to the service command do you get any more information?
