### ISSUE TITLE
RasaX Install Error when execute task [backwards compatible credentials]

### ISSUE THREAD

**Issue by KStephenyang** [RasaHQ/rasa#5246]
**Rasa version**: 1.7.0

**Python version**: 3.6

**Operating system** (windows, osx, ...): Ubuntu 18.04

**Issue**:

When I install RasaX with below command code as Docker-Compose Quick Install tutorial, when execute task [backwards compatible credentials]，I met error "mv: cannot move 'credentials' to a subdirectory of itself, '/etc/rasa/credentials/credentials'".

**Error (including full traceback)**:

![d1f9a6a83f1a49a442c40d4093d45c4ac686a420](https://user-images.githubusercontent.com/12053663/74606851-d1d4d600-510e-11ea-96b5-fb1ab0f3c8d6.png)
![d15c02cd63ce6719e18d3fc5a5d1a6caef62c9c7](https://user-images.githubusercontent.com/12053663/74606853-d4373000-510e-11ea-9df2-e921a9b154ca.png)

**Command or request that led to error**:
```
$ curl -sSL -o install.sh https://storage.googleapis.com/rasa-x-releases/0.25.2/install.sh
$ sudo bash ./install.sh
```

**Content of configuration file (config.yml)** (if relevant):
```yml
rasa_x_playbook.yml
```

I fix the problem by command the task [backwards compatible credentials], and add a new task [Create the directory for the credentials(backwards compatible credentials)] as follows: 
![cd6e516cd425bab6e5ff01ef707a7b1e8013834d](https://user-images.githubusercontent.com/12053663/74606895-2aa46e80-510f-11ea-9efb-acac32dad75d.png)
![63f4ff7d137bb4db040ed706d8e69967b54f7274](https://user-images.githubusercontent.com/12053663/74606896-2d06c880-510f-11ea-923a-1ae831d23708.png)

I think this may be a potential bug, I hope this will help someone who have the same problem.

**Comment by kellog5** [comment]
I had the same issue ... believe it is a small bug in the rasa_x_playbook.yml file

I think the first reference to credentials is supposed to be the credentials.yml file and not the credentials directory.

In the rasa_x_playbook.yml file I replaced

 command: mv credentials {{RASA_HOME }} / credentials

with 

command: mv credentials.yml {{RASA_HOME }} / credentials

and it seemed to work.

**Comment by sara-tagger** [comment]
Thanks for the issue, @amn41 will get back to you about it soon!

###### You may find help in the [docs](https://rasa.com/docs/) and the [forum,](https://forum.rasa.com/) too 🤗
