### ISSUE TITLE
Modify the RasaX docs to emphasize that the ssh keypair should NOT be given a password.

### ISSUE THREAD

**Issue by ActuallyAcey** [RasaHQ/rasa#5247]
**Description of Problem**:

During the implementation of **Integrated Version Control** in RasaX, you are required to generate a pair of SSH keys like so:

`ssh-keygen -t rsa -b 4096 -f git-deploy-key`

In Ubuntu (and I presume most other OSes), the ssh-keygen tool asks if you would like to encrypt the keys with a passphrase. However, Github refuses your authentication attempts if the SSH keys are encrypted with a password, as later figured out on a call with Aleksandr. 
As such, it's **important that you don't add a password to your SSH keys when generating them.** It is very easy to run into this issue since one assumes, by default, that you SHOULD be adding passwords wherever prompted. 

**Overview of the Solution**:

Add in the documentation that until password-based decryption isn't implemented, no password should be given while generating SSH keys. 
**Examples** (if relevant):

https://rasa.com/docs/rasa-x/installation-and-setup/integrated-version-control/#generate-new-ssh-keys

**Blockers** (if relevant):

None

**Definition of Done**:

- [ ] Documentation is updated.

**Comment by sara-tagger** [comment]
Thanks for the issue, @koaning will get back to you about it soon!

###### You may find help in the [docs](https://rasa.com/docs/) and the [forum,](https://forum.rasa.com/) too 🤗

**Comment by koaning** [comment]
Hi @ActuallyAcey. 

today is my first day and I'll be happy to pick this one up. I just ran an experiment locally but I was able to clone a private repo just fine using a key-pair that has a passphrase on it. I'll check with a colleague to see if they can reproduce it. 

I'll gladly add a small notice that you don't need to add a passphrase but before suggesting that you **shouldn't** I just want to understand what is going wrong and where.

**Comment by koaning** [comment]
Yep. Verified. 

<img width="807" alt="image" src="https://user-images.githubusercontent.com/1019791/74719154-ca5b1d00-5233-11ea-867f-fe4ade33416c.png">

Docs will now look like this. Cool?

**Comment by koaning** [comment]
Ah. It seems my colleagues have beat me to it.

**Comment by ActuallyAcey** [comment]
Looks great, thanks.
