### ISSUE TITLE
Refactor Generator.generate()

### ISSUE THREAD

**Issue by wochinge** [RasaHQ/rasa#5249]
We should refactor this https://github.com/RasaHQ/rasa/blob/4211b92b029779b191c2ede67f12f8646accba79/rasa/core/training/generator.py#L192

The method is currently 208 lines long!

**Comment by wochinge** [comment]
@Ghostvv Should engineering or research do this?

**Comment by Ghostvv** [comment]
I already did it several times. Feel free to enjoy it yourself 😅

**Comment by Ghostvv** [comment]
It is for sure not a research task

**Comment by wochinge** [comment]
added it our board 👍
