### ISSUE TITLE
from rasa_sdk import Action, Tracker action_server_1  ModuleNotFoundError: No module named 'rasa_sdk'

### ISSUE THREAD

**Issue by sushilr007** [RasaHQ/rasa#5270]
**Rasa version**:1.2.7

**Rasa SDK version** (if used & relevant):
1.2.0
**Rasa X version** (if used & relevant):

**Python version**:3.6.5

**Operating system** (windows, osx, ...): Windows 10

**Issue**: When I am using docker-compose up command, I am getting an error from action file.

**Error (including full traceback)**: Starting rasa_1          ... done                                                                                        Starting action_server_1 ... done                                                                                        Attaching to rasa_1,action_server_1
action_server_1  | 2020-02-20 05:18:21 INFO     __main__  - Starting action endpoint server...
action_server_1  | 2020-02-20 05:18:21 ERROR    rasa_core_sdk.executor  - Failed to register package 'actions.actions'.
action_server_1  | Traceback (most recent call last):
action_server_1  |   File "/app/rasa_core_sdk/executor.py", line 174, in register_package
action_server_1  |     self._import_submodules(package)
action_server_1  |   File "/app/rasa_core_sdk/executor.py", line 168, in _import_submodules
action_server_1  |     results[full_name] = importlib.import_module(full_name)
action_server_1  |   File "/usr/local/lib/python3.6/importlib/__init__.py", line 126, in import_module
action_server_1  |     return _bootstrap._gcd_import(name[level:], package, level)
action_server_1  |   File "<frozen importlib._bootstrap>", line 994, in _gcd_import
action_server_1  |   File "<frozen importlib._bootstrap>", line 971, in _find_and_load
action_server_1  |   File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
action_server_1  |   File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
action_server_1  |   File "<frozen importlib._bootstrap_external>", line 678, in exec_module
action_server_1  |   File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
action_server_1  |   File "/app/actions/actions/actions.py", line 12, in <module>
action_server_1  |     from rasa_sdk import Action, Tracker
action_server_1  | ModuleNotFoundError: No module named 'rasa_sdk'
action_server_1  | 2020-02-20 05:18:21 INFO     __main__  - Action endpoint is up and running. on ('0.0.0.0', 5055)
rasa_1           | 2020-02-20 05:18:23 DEBUG    rasa.cli.utils  - Parameter 'credentials' not set. Using default location 'credentials.yml' instead.
rasa_1           | 2020-02-20 05:18:26 DEBUG    rasa.core.utils  - Available web server routes:
rasa_1           | /conversations/<conversation_id>/messages          POST                           add_message
rasa_1           | /conversations/<conversation_id>/tracker/events    POST                           append_events
rasa_1           | /webhooks/rasa                                     GET                            custom_webhook_RasaChatInput.health
rasa_1           | /webhooks/rasa/webhook                             POST                           custom_webhook_RasaChatInput.receive
rasa_1           | /webhooks/rest                                     GET                            custom_webhook_RestInput.health
rasa_1           | /webhooks/rest/webhook                             POST                           custom_webhook_RestInput.receive
rasa_1           | /model/test/intents                                POST                           evaluate_intents
rasa_1           | /model/test/stories                                POST                           evaluate_stories
rasa_1           | /conversations/<conversation_id>/execute           POST                           execute_action
rasa_1           | /domain                                            GET                            get_domain
rasa_1           | /                                                  GET                            hello
rasa_1           | /model                                             PUT                            load_model
rasa_1           | /model/parse                                       POST                           parse
rasa_1           | /conversations/<conversation_id>/predict           POST                           predict
rasa_1           | /conversations/<conversation_id>/tracker/events    PUT                            replace_events
rasa_1           | /conversations/<conversation_id>/story             GET                            retrieve_story
rasa_1           | /conversations/<conversation_id>/tracker           GET                            retrieve_tracker
rasa_1           | /status                                            GET                            status
rasa_1           | /model/predict                                     POST                           tracker_predict
rasa_1           | /model/train                                       POST                           train
rasa_1           | /model                                             DELETE                         unload_model
rasa_1           | /version                                           GET                            version
rasa_1           | 2020-02-20 05:18:26 INFO     root  - Starting Rasa server on http://localhost:5005
rasa_1           | 2020-02-20 05:18:26 INFO     root  - Enabling coroutine debugging. Loop id 94902768112504.
rasa_1           | 2020-02-20 05:18:26 DEBUG    rasa.model  - Extracted model to '/tmp/tmpew__97pb'.
rasa_1           | 2020-02-20 05:18:26 DEBUG    rasa.core.tracker_store  - Attempting to connect to database via 'sqlite:///events.db'.
rasa_1           | 2020-02-20 05:18:26 DEBUG    rasa.core.tracker_store  - Connection to SQL database 'events.db' successful.
rasa_1           | 2020-02-20 05:18:26 DEBUG    rasa.core.tracker_store  - Connected to SQLTrackerStore.
rasa_1           | 2020-02-20 05:18:26 DEBUG    rasa.model  - Extracted model to '/tmp/tmpavw4c95j'.
rasa_1           | 2020-02-20 05:18:26 DEBUG    pykwalify.compat  - Using yaml library: /usr/local/lib/python3.6/site-packages/ruamel/yaml/__init__.py
rasa_1           | 2020-02-20 05:18:30 WARNING  rasa.core.policies.ensemble  - Found policies ['FallbackPolicy', 'FallbackPolicy'] with same priority 4 in PolicyEnsemble. When personalizing priorities, be sure to give all policies different priorities. More information: https://rasa.com/docs/rasa/core/policies/
```

```

**Command or request that led to error**:  docker-compose up
```

```
**Content of domain file (docker-compose.yml)** (if relevant):
```yml
version: '3.0'
services:
  rasa:
    image: rasa/rasa:1.2.7-full
    ports:
      - 5005:5005
    volumes:
      - ./:/app
      - ./models:/app/models
      - ./config:/app/config
    command:
      - run
      - --cors
      - "*"
      - -m
      - models
      - --enable-api
      - --endpoints
      - endpoints.yml
      - --debug
  action_server:
    image: rasa/rasa_core_sdk:latest
    volumes:
      - ./actions:/app/actions/actions
```

**Comment by sara-tagger** [comment]
Thanks for raising this issue, @degiz will get back to you about it soon✨

###### Please also check out the [docs](https://rasa.com/docs/) and the [forum](https://forum.rasa.com/) in case your issue was raised there too 🤗

**Comment by bivas6** [comment]
@sushilr007 
Did you find a solution? I also experienced this error.

**Comment by degiz** [comment]
@sushilr007 @bivas6 

Sorry for the delay!

From what I can see you're using `rasa/rasa:1.2.7-full` as a base image for your action server.
Please consider using `rasa-sdk:1.10.0` as described [here](https://rasa.com/docs/rasa/user-guide/how-to-deploy/#deploying-your-action-server).
