### ISSUE TITLE
Unending loop in facility form while implementing episode 8 of masterclass

### ISSUE THREAD

**Issue by sidkgp** [RasaHQ/rasa#5284]
**Rasa version**: 1.7.0

**Rasa SDK version** (if used & relevant):NA

**Rasa X version** (if used & relevant):NA

**Python version**:3.7.3

**Operating system** (windows, osx, ...):osx

**Issue**:
See the below interaction (the first story went well, subsequent repetitions are stuck in the form). Also attaching the files changed
[rasa-infinite-loop.zip](https://github.com/RasaHQ/rasa/files/4234468/rasa-infinite-loop.zip)
 -
Your input ->  hi                                                                                  
? Hello! What can I help you find today?  1: Hospital (/inform{"facility_type": "xubh-q36u"})      
Please enter your zip code or city name to find local providers.
Your input ->  Kirkland                                                                            
? Here are 2 hospitals near you:  1: Evergreenhealth Medical Center (/inform{"facility_id":"500124"
})                                                                                                 
The address is 12040 Ne 128Th Street, Kirkland, WA 98034.
Your input ->  thanks                                                                              
My pleasure.
Your input ->  hi                                                                                  
? Hello! What can I help you find today?  1: Hospital (/inform{"facility_type": "xubh-q36u"})      
? Hello! What can I help you find today?  1: Hospital (/inform{"facility_type": "xubh-q36u"})      
? Hello! What can I help you find today?  1: Hospital (/inform{"facility_type": "xubh-q36u"})      
? Hello! What can I help you find today?  1: Hospital (/inform{"facility_type": "xubh-q36u"})      
? Hello! What can I help you find today?  1: Hospital (/inform{"facility_type": "xubh-q36u"})      
? Hello! What can I help you find today?  1: Hospital (/inform{"facility_type": "xubh-q36u"})      
? Hello! What can I help you find today?  3: Home Health Agency (/inform{"facility_type": "9wzi-peq
s"})                                                                                               
? Hello! What can I help you find today?  2: Nursing Home (/inform{"facility_type": "b27b-2uc7"})  
? Hello! What can I help you find today?  1: Hospital (/inform{"facility_type": "xubh-q36u"})      

Cancelled by user

**Error (including full traceback)**:
```
Your input ->  hi                                                                                  
? Hello! What can I help you find today?  1: Hospital (/inform{"facility_type": "xubh-q36u"})      
Please enter your zip code or city name to find local providers.
Your input ->  Kirkland                                                                            
? Here are 2 hospitals near you:  1: Evergreenhealth Medical Center (/inform{"facility_id":"500124"
})                                                                                                 
The address is 12040 Ne 128Th Street, Kirkland, WA 98034.
Your input ->  thanks                                                                              
My pleasure.
Your input ->  hi                                                                                  
? Hello! What can I help you find today?  1: Hospital (/inform{"facility_type": "xubh-q36u"})      
? Hello! What can I help you find today?  1: Hospital (/inform{"facility_type": "xubh-q36u"})      
? Hello! What can I help you find today?  1: Hospital (/inform{"facility_type": "xubh-q36u"})      
? Hello! What can I help you find today?  1: Hospital (/inform{"facility_type": "xubh-q36u"})      
? Hello! What can I help you find today?  1: Hospital (/inform{"facility_type": "xubh-q36u"})      
? Hello! What can I help you find today?  1: Hospital (/inform{"facility_type": "xubh-q36u"})      
? Hello! What can I help you find today?  3: Home Health Agency (/inform{"facility_type": "9wzi-peq
s"})                                                                                               
? Hello! What can I help you find today?  2: Nursing Home (/inform{"facility_type": "b27b-2uc7"})  
? Hello! What can I help you find today?  1: Hospital (/inform{"facility_type": "xubh-q36u"})      

Cancelled by user
```

**Command or request that led to error**:
```
rasa shell
```

**Content of configuration file (config.yml)** (if relevant):
```yml
# Configuration for Rasa NLU.
# https://rasa.com/docs/rasa/nlu/components/
language: "en"

pipeline:
- name: "WhitespaceTokenizer"
- name: "RegexFeaturizer"
- name: "CRFEntityExtractor"
- name: "EntitySynonymMapper"
- name: "CountVectorsFeaturizer"
- name: "EmbeddingIntentClassifier"

# Configuration for Rasa Core.
# https://rasa.com/docs/rasa/core/policies/
policies:
  - name: MemoizationPolicy
  - name: MappingPolicy
  - name: EmbeddingPolicy
  - name: FormPolicy
  - name: TwoStageFallbackPolicy
```

**Content of domain file (domain.yml)** (if relevant):
```yml
intents:
  - greet
  - goodbye
  - affirm
  - deny
  - mood_great
  - mood_unhappy
  - inform
  - search_provider
  - thanks
  - out_of_scope

entities:
- facility_type
- facility_id
- location

slots:
  facility_type:
    type: unfeaturized
  facility_address:
    type: unfeaturized
  facility_id:
    type: unfeaturized
  location:
    type: unfeaturized

forms:
- facility_form

actions:
- utter_noworries
- utter_greet
- utter_goodbye
- utter_ask_location
- utter_ask_facility_type
- find_facility_types
- find_healthcare_address
- utter_address

responses:
  utter_greet:
  - text: "Hi. What are you looking for?"
  - text: "Hey there! Please choose one of the healthcare facility options:"
  - text: "Hello! What can I help you find today?"

  utter_goodbye:
  - text: "Talk to you later!"
  - text: "Have a good day."
  - text: "Until next time!"

  utter_noworries:
  - text: "My pleasure."
  - text: "You are welcome!"

  utter_ask_facility_type:
  - text: "Choose one of the following to search for: hospital, nursing home, or home health agency."

  utter_ask_location:
  - text: "Please provide your city name."
  - text: "What is your current city?"
  - text: "Please provide your city name or zip code."
  - text: "Please enter your zip code or city name to find local providers."

  utter_address:
  - text: "The address is {facility_address}."

session_config:
  session_expiration_time: 60
  carry_over_slots_to_new_session: true

```

**Comment by sara-tagger** [comment]
Thanks for raising this issue, @dakshvar22 will get back to you about it soon✨

###### Please also check out the [docs](https://rasa.com/docs/) and the [forum](https://forum.rasa.com/) in case your issue was raised there too 🤗

**Comment by sidkgp** [comment]
thanks. @dakshvar22, let me know if you would like to chat offline about this.

**Comment by dakshvar22** [comment]
@sidkgp Is this still an issue with the latest version of Rasa?
