### ISSUE TITLE
Hello there , Is there any possible ways to create a dashboard using rasa framework like dashboard is based on client purpose based like CRM and all where client should able to create there own customized bot according to there wish . any suggestions on this will be helpful . Thanks in advance …

### ISSUE THREAD

**Issue by Beherasaptami** [RasaHQ/rasa#5285]

**Comment by sara-tagger** [comment]
Thanks for the question, our Github issue board is for **bugs and feature requests only,** though 😕
Please ask this question in the [forum✨](https://forum.rasa.com/c/rasa)

###### If you were describing a bug, please create a [report](https://github.com/RasaHQ/rasa/issues/new?labels=bug&template=bug_report.md) and fill out the template.

**Comment by mhmohona** [comment]
Hello @Beherasaptami! Have you found anything about this?

I have found this: https://github.com/jackdh/RasaTalk, but I want to make a dashboard without using  MongoDB and Docker. Confused if it is possible.
