### ISSUE TITLE
human handingover to bot

### ISSUE THREAD

**Issue by Beherasaptami** [RasaHQ/rasa#5288]
i want to know more regarding this like how i can integrate live chat once customer ask the bot to speak with agent any suggestion will be helpful on this Thanks

Reply
 Bookmark  Share  Flag  Reply

**Comment by sara-tagger** [comment]
Thanks for the question, our Github issue board is for **bugs and feature requests only,** though 😕
Please ask this question in the [forum✨](https://forum.rasa.com/c/rasa)

###### If you were describing a bug, please create a [report](https://github.com/RasaHQ/rasa/issues/new?labels=bug&template=bug_report.md) and fill out the template.
