### ISSUE TITLE
bulding a multichanel using same server and same port number using rasa for diffrent diffrent bot 

### ISSUE THREAD

**Issue by Beherasaptami** [RasaHQ/rasa#5289]
hello ,
  I have 2 bot one is like faq bot and another one is for event booking so is there any way where i can have only one bot instead of 2 like initial have 2 folder strucutre but i want to reduce it to one (means will be having only one bot which will take care of both faq and event booking bot ) , is there any way to segregate dataset of both the bot (like will be having diffrent data for diffrent bot but rest other thing will be same) any suggestion regarding this will be helpful for me …

**Comment by sara-tagger** [comment]
Thanks for the question, our Github issue board is for **bugs and feature requests only,** though 😕
Please ask this question in the [forum✨](https://forum.rasa.com/c/rasa)

###### If you were describing a bug, please create a [report](https://github.com/RasaHQ/rasa/issues/new?labels=bug&template=bug_report.md) and fill out the template.
