### ISSUE TITLE
how to resolve the error

### ISSUE THREAD

**Issue by MPARANTHAMAN** [RasaHQ/rasa#5299]
ERROR: rasa 1.0.9 has requirement requests~=2.22, but you'll have requests 2.21.0 which is incompatible.
ERROR: rasa-nlu 0.15.1 has requirement matplotlib~=2.2, but you'll have matplotlib 3.1.3 which is incompatible.
ERROR: rasa-nlu 0.15.1 has requirement packaging~=18.0, but you'll have packaging 19.2 which is incompatible.

**Comment by sara-tagger** [comment]
Thanks for the issue, @Ghostvv will get back to you about it soon!

###### You may find help in the [docs](https://rasa.com/docs/) and the [forum,](https://forum.rasa.com/) too 🤗

**Comment by VedantRG** [comment]
> ERROR: rasa 1.0.9 has requirement requests~=2.22, but you'll have requests 2.21.0 which is incompatible.
> ERROR: rasa-nlu 0.15.1 has requirement matplotlib~=2.2, but you'll have matplotlib 3.1.3 which is incompatible.
> ERROR: rasa-nlu 0.15.1 has requirement packaging~=18.0, but you'll have packaging 19.2 which is incompatible.

How was the issue resolved?
