### ISSUE TITLE
Get rid of pickle

### ISSUE THREAD

**Issue by tabergma** [RasaHQ/rasa#5303]
**Description of Problem**: As pickle is very python version dependent and makes models even more brittle than they already are, we should move to something more portable.

**Overview of the Solution**: We could use `json_pickle` and `json_unpickle` in `rasa.nlu.utils.io`.

Note: In `DIETClassifier` we have two data structures (`data_example` and `_label_data`) that have a combination of `numpy.array` and `scipy.sparse.coo_matrix`. Apparently, we cannot use `json_pickle` for those. However, storing `numpy.array` and `scipy.sparse.coo_matrix` on their own works. So, we need to split those data structures into two different parts.

**Comment by ricwo** [comment]
@tabergma has this caused any issues so far?

**Comment by tabergma** [comment]
Not sure. @tmbo might know some.

**Comment by alwx** [comment]
@tmbo is it still relevant?

**Comment by tmbo** [comment]
yes I'd say so. using pickle to store objects permanently isn't the suggested use case for multiple reasons (e.g. dependence on python version).
