### ISSUE TITLE
Update documentation on components and policies

### ISSUE THREAD

**Issue by tabergma** [RasaHQ/rasa#5308]
There are a couple of comments in https://github.com/RasaHQ/rasa/pull/5266 that are valid and still open. We should address those.

In general:
- add better descriptions to our model parameters, explain what they are and when to modify those
- have proper suggestions how to configure certain model parameters
- explain when to use what component and policy

**Comment by akelad** [comment]
Mention that you can still load in fast text vectors etc on the featurizer docs

**Comment by akelad** [comment]
The table for the features for the `LexicalSyntaxFeaturizer` does not look good

**Comment by tabergma** [comment]
Using language models like BERT, GPT-2: Should we add a warning of them being slow?

**Comment by tabergma** [comment]
@dakshvar22 Is training using language models like BERT, GPT-2 slower? Do you have any numbers?

**Comment by Ghostvv** [comment]
training is a bit slower, because it takes more time to featurize training data. More interesting is whether prediction is slower

**Comment by dakshvar22** [comment]
I tested with `rasa shell`. Once the components are loaded, the actual processing of a new message takes around 10 ms. Ofcourse that would change a bit depending the length of the input message.

**Comment by Ghostvv** [comment]
and without lm models?

**Comment by dakshvar22** [comment]
Parsing times with DIETClassifier + these featurizers - 
`CountVectorizer`(word level) : 20 ms
`ConveRTFeaturizer`: 30 ms
`LanguageModelFeaturizer`(BERT): 140 ms

**Comment by tabergma** [comment]
Outcome of our meeting:

@erohmensing and @ArjaanBuijk are working on a proposal for updating the "choosing a pipeline" page. The current page contains quite a lot of content: (1) what is a pipeline? (2) how does it work? (3) when to use what components? (4) deprecated content about pipeline templates. We want to simplify the page and maybe split it into multiple pages.

@tabergma is updating the "Components" page. We decided to not list the parameters twice. We will explain important parameters in more detail and explain when to update those and how they could influence the models performance. All the other parameters should be listed in a table with just a short description. We might consider making some parts of the components description collapsable.

**Comment by Ghostvv** [comment]
@koaning

**Comment by akelad** [comment]
@erohmensing @ArjaanBuijk where are you working on this proposal btw? Do we have an issue for it?

**Comment by koaning** [comment]
I have an idea. 

We can have diagrams for every pipeline step. I'll take DIET now as an example. 

Suppose that we have our mouse cursor ... 

<img width="1067" alt="image" src="https://user-images.githubusercontent.com/1019791/76421698-5af4cb00-63a4-11ea-943d-789ba36ba1c3.png">


Wouldn't it be great if then you'd see something like. 

<img width="1075" alt="image" src="https://user-images.githubusercontent.com/1019791/76421608-3862b200-63a4-11ea-8a8e-80b8214127f5.png">

**Comment by tabergma** [comment]
Closed via #5410 and #5456. Let's open new issues for further improvements.
