### ISSUE TITLE
Rasa X sorting randomly synonyms in nlu file

### ISSUE THREAD

**Issue by eric-bonfadini** [RasaHQ/rasa#5313]
**Rasa version**:
1.7.0

**Rasa SDK version** (if used & relevant):
1.7.0

**Rasa X version** (if used & relevant):
0.25.2

**Python version**:
3.6.7

**Operating system** (windows, osx, ...):
osx

**Issue**:
Whenever I annotate new data from Rasa-X (in NLU Training tab), the synonyms in my nlu.md gets sorted randomly (as far as I can tell) every time I save. 
This is quite annoying since I get a lot of unnecessary changes in my version control system.

Forum discussion: https://forum.rasa.com/t/rasa-x-sorting-randomly-synonyms-in-my-nlu-file/25065

**Error (including full traceback)**:

**Command or request that led to error**:

**Content of configuration file (config.yml)** (if relevant):

**Content of domain file (domain.yml)** (if relevant):

**Comment by sara-tagger** [comment]
Thanks for the issue, @rgstephens will get back to you about it soon!

###### You may find help in the [docs](https://rasa.com/docs/) and the [forum,](https://forum.rasa.com/) too 🤗

**Comment by erohmensing** [comment]
I am seeing the same, see the diff here: https://github.com/RasaHQ/rasa-demo/compare/Rasa-x-Feb-11th-20--3-52-30-pm-ella 

You can track the issue's progress here 👍

**Comment by erohmensing** [comment]
@ricwo do you think this is Rasa X backend or markdown writer? I think it's the db reorganizing things, most likely?

**Comment by ricwo** [comment]
yes, the insertion order of synonyms is not respected when the NLU file is dumped (we could just sort by ascending ID as we do for NLU examples)

**Comment by wochinge** [comment]
A fix will be released with the next patch release (or minor in case their is not another patch release)
