### ISSUE TITLE
Misaligned entity annotation warning although the .md file is correct

### ISSUE THREAD

**Issue by jehnes** [RasaHQ/rasa#5314]
**Rasa version**: Rasa 1.7.3

**Rasa SDK version** (if used & relevant): NA

**Rasa X version** (if used & relevant): NA

**Python version**: Python 3.7.6

**Operating system** (windows, osx, ...): linux (Ubuntu 18.04.4 LTS)

**Issue**:
During training I get the following user warning:
```
/home/jochen/anaconda3/envs/rasa/lib/python3.7/site-packages/rasa/utils/common.py:351: UserWarning: Misaligned entity annotation for 'c.' in sentence 'my status is c. what does it mean' with intent 'faq_pes_mean'. Make sure the start and end values of the annotated training examples end at token boundaries (e.g. don't include trailing whitespaces or punctuation).
  More info at https://rasa.com/docs/rasa/nlu/training-data-format/
```

In the .md file the sentence is written as 

```
- my status is [c](pes:C). what does it mean
```

and clearly does not include the '.' .

A quick search for the error message "Misaligned entity annotation" showed that it was generated by the function "_from_json_to_crf(..)" in cry_entity_extractor.py. That in turn suggests that the .md file is likely converted to .json first before it can be processed by this function. 
If I convert the .md file to .json using "rasa data convert nlu --data ./foo.md --out ./foo.json -f json", I get the following:

```
     {
        "intent": "faq_pes_mean",
        "entities": [
          {
            "start": 13,
            "end": 14,
            "value": "C",
            "entity": "pes"
          }
        ],
        "text": "my status is c. what does it mean"
      },
```

I assume that the end character (14) should be the same as the start character (13) as the entity is just one character ('c') and that for some reason the value for the end character is generated wrongly during the conversion from .md format to .json format and therefor the function _from_json_to_crf(..) wrongly assumes that the '.' is part of the entity and issues the warning above. 

**Error (including full traceback)**:

No error / crash, just a warning as explained above.

**Command or request that led to error**:
```
rasa train
```

**Content of configuration file (config.yml)** (if relevant):
```yml

```

**Content of domain file (domain.yml)** (if relevant):
```yml

```

**Comment by sara-tagger** [comment]
Thanks for raising this issue, @amn41 will get back to you about it soon✨

###### Please also check out the [docs](https://rasa.com/docs/) and the [forum](https://forum.rasa.com/) in case your issue was raised there too 🤗
