### ISSUE TITLE
Error running docker … init

### ISSUE THREAD

**Issue by mhjb** [RasaHQ/rasa#5335]
On Ubuntu 18.04.3 (LTS) x64  on DigitalOcean, I've run

`docker pull rasa`

then

`docker run -v $(pwd):/app rasa/rasa init --no-prompt`

and get the error

`docker: Error response from daemon: OCI runtime create failed: container_linux.go:345: starting container process caused "chdir to cwd (\"/app\") set in config.json failed: permission denied": unknown.
ERRO[0000] error waiting for container: context canceled`

Help please!

**Comment by mhjb** [comment]
I've pulled the latest rasa image and this appears to be fixed.

**Comment by mhjb** [comment]
I run `docker run -v $(pwd):/app rasa/rasa init --no-prompt`

There are a number of errors in the output: 
![image](https://user-images.githubusercontent.com/1380991/75636615-1f138480-5c85-11ea-9504-89d50c558435.png)

… and when I attempt to use rasa shell:
![image](https://user-images.githubusercontent.com/1380991/75636623-2aff4680-5c85-11ea-95ed-71971fbfb981.png)

**Comment by sara-tagger** [comment]
Thanks for the question, our Github issue board is for **bugs and feature requests only,** though 😕
Please ask this question in the [forum✨](https://forum.rasa.com/c/rasa)

###### If you were describing a bug, please create a [report](https://github.com/RasaHQ/rasa/issues/new?labels=bug&template=bug_report.md) and fill out the template.

**Comment by mhjb** [comment]
It did seem like a bug…
