### ISSUE TITLE
Rasa form not asking for slots the second time around

### ISSUE THREAD

**Issue by ali254** [RasaHQ/rasa#5343]
Hi,

I followed the tutorials to create forms however during a conversation the first time the user's intent gets actioned to a form, it will work fine and the bot will ask the questions related to the required slots and then submits the form. During the conversation if I try to start the form again it will not ask any questions for the required slots but will just give me the response of the form as noted in the submit section.

I have even added a story where I can process a form again but for some reason it never asks the slot questions the second time

**Comment by sara-tagger** [comment]
Thanks for the question, our Github issue board is for **bugs and feature requests only,** though 😕
Please ask this question in the [forum✨](https://forum.rasa.com/c/rasa)

###### If you were describing a bug, please create a [report](https://github.com/RasaHQ/rasa/issues/new?labels=bug&template=bug_report.md) and fill out the template.
