### ISSUE TITLE
Proposal: Move Form logic implementation from RasaSDK to Core

### ISSUE THREAD

**Issue by ayarulin** [RasaHQ/rasa#5357]
**Description of Problem**: 
Currently, Form logic handled by ActionServer, it is not ideal when using Rasa in the non-python environments as it requires to port Rasa SDK FormAction to make forms usable. It seems like a leak of core-related logic to an integration-related layer.

**Overview of the Solution**:
It may be better to have a declarative description of Form behavior in domain.yml — list of `required_slots` and `slot_mapping` rules, then leave to ActionServer only handle the `submit` (and optionally `slot_filling`/`validation`) actions as a usual CustomAction, with no need to describe the Form configuration

**Definition of Done**:
- [ ] Ability to have fully working Form without overusing of ActionServer

Does it make any sense for you guys?

**Comment by sara-tagger** [comment]
Thanks for the issue, @chkoss will get back to you about it soon!

###### You may find help in the [docs](https://rasa.com/docs/) and the [forum,](https://forum.rasa.com/) too 🤗

**Comment by Ghostvv** [comment]
You're right part of the core is inside sdk `FormAction`. The reason that it is there is that currently, there is no other way to implement it. We're working on the solution to make forms independent of action server

**Comment by ayarulin** [comment]
@Ghostvv thanks for the clarification, good to know there is some work is already going on about it

**Comment by akelad** [comment]
as of 2.0, this is done 🚀
