### ISSUE TITLE
automate code conventions

### ISSUE THREAD

**Issue by wochinge** [RasaHQ/rasa#5359]
We should automate as much as possible from our code conventions to 
- avoid having to check them manually during a PR
- increase awareness

Things we should/ could do:
- [ ] check if (public) functions / methods have docstrings in the right format
- [ ] enable code climate (we probably don't need all checks, so we have to find a configuration all team members agree on)
- [ ] add checks if type annotations were added (also missing return types)
- [ ] potentially others

Ideas: 
- [ ] lint `.rst` files for the length 80 characters
- [ ] check for missing newline at the end of file

**Comment by joejuzl** [comment]
I think we can close this as many of these checks have been added, and there are existing issues for further checks.
