### ISSUE TITLE
i am new to chatbot . after executing rasa init command i executed rasa shell where i am getting NLU model is loaded type the message to parse it, but when i type the message i am not getting any replay from bot.

### ISSUE THREAD

**Issue by snv1995** [RasaHQ/rasa#5367]

**Comment by snv1995** [comment]
![capture(1)](https://user-images.githubusercontent.com/27666222/75860854-81ee5280-5e22-11ea-8ed7-99c026bcdbd6.png)

**Comment by snv1995** [comment]
Help me in this..

**Comment by dcsan** [comment]
nlu is just to analyze inputs not reply. try `rasa shell`

also these kind of questions are better asked on the forum. this is for rasa engine questions, not so much rasa usage.
https://forum.rasa.com/

**Comment by sara-tagger** [comment]
Thanks for the issue, @JustinaPetr will get back to you about it soon!

###### You may find help in the [docs](https://rasa.com/docs/) and the [forum,](https://forum.rasa.com/) too 🤗
