### ISSUE TITLE
Inconsistency in initial project setup for actions running via rasa or via sdk

### ISSUE THREAD

**Issue by erohmensing** [RasaHQ/rasa#5368]
Currently, when running an action server with `rasa run actions`, the default looks in `actions.py` in the base of your project directory. `actions.py` is created there as part of the initial project. 

However, if you build in docker, the default place to find actions is in `actions/actions.py`. https://github.com/RasaHQ/rasa-sdk/blob/master/Dockerfile#L40

This makes it confusing -- when teaching the user to create custom actions in Docker, we have to tell them to create the new folder with an actions file, when `actions.py` already exists: https://rasa.com/docs/rasa/user-guide/how-to-deploy/#creating-a-custom-action

This seems to also have caused confusion here: https://github.com/RasaHQ/rasa-sdk/pull/140#issuecomment-586936047

We should make the default behavior consistent. I'm partial to having an `actions` folder as it's probably quite normal for a larger actions file to reference other files. However that will probably involve changing a decent amount of references in e.g. tutorials.

**Comment by akelad** [comment]
@erohmensing are you working on this atm? if not, please unassign

**Comment by tmbo** [comment]
I'd agree, let's change the default project (`rasa init`) as well as the examples to use an actions folder instead of a file. so the resulting structure should be:
```
moodbot/
├── domain.yml
├── actions/
│   ├── __init__.py
│   └── actions.py
├── ...
```
I think there might be a `__init__.py` at a rasa bots root directory by default (so in `moodbot`), I am not sure we need that one

**Comment by wochinge** [comment]
@erohmensing Imo this needs to go in before the RC next week. Do you have this on your radar or should our squad take this over?

**Comment by akelad** [comment]
i'm gonna speak for our team and say that we are slammed with customers + 2.0 docs at the moment, so it'd be nice if your squad takes it :)

**Comment by wochinge** [comment]
@alwx @tczekajlo is it ok for you if we take on this time critical task? Rick is also back onboard then, so I think we do this despite our decoupling commitment

**Comment by tczekajlo** [comment]
> @alwx @tczekajlo is it ok for you if we take on this time critical task? Rick is also back onboard then, so I think we do this despite our decoupling commitment

I'm ok with that, not sure If I'm the best person to do this if it's time-critical task though 😄

**Comment by wochinge** [comment]
It's time critical in a sense that it should be done until next week. I'll add it to our board.

**Comment by akelad** [comment]
reminder to update the CLI documentation and others on initial project setup
