### ISSUE TITLE
Tensorflow-text missing from install

### ISSUE THREAD

**Issue by DomAmato** [RasaHQ/rasa#5373]
**Rasa version**: 1.8.0

**Rasa SDK version** (if used & relevant): NR

**Rasa X version** (if used & relevant): NR

**Python version**: 3.6

**Operating system** (windows, osx, ...): Docker

**Issue**:
If I install the dependency then things will run as expected. I can train models and run the server etc... but it seems to be required for whatever reason yet not installed.

**Error (including full traceback)**:
```
 2020-03-04 21:49:41 DEBUG    rasa.core.lock_store  - Connected to lock store 'InMemoryLockStore'.
2020-03-04 21:49:41 DEBUG    rasa.model  - Extracted model to '/tmp/tmpkffevycq'.
2020-03-04 21:49:41 ERROR    rasa.core.agent  - Could not load model due to Not all required importable packages are installed. To 
use this pipeline, you need to install the missing dependencies. Please install the package(s) that contain the module(s): tensorflow_text. 
```

**Command or request that led to error**:
```
rasa run --debug
```

**Comment by dcsan** [comment]
i also had this issue

some other 1.8 upgrade glitches here:

https://forum.rasa.com/t/upgrading-to-v1-8/25391

**Comment by sara-tagger** [comment]
Thanks for the issue, @degiz will get back to you about it soon!

###### You may find help in the [docs](https://rasa.com/docs/) and the [forum,](https://forum.rasa.com/) too 🤗

**Comment by dakshvar22** [comment]
@DomAmato Looks like you are using `ConveRTTokenizer` and `ConveRTFeaturizer` in your NLU pipeline. Both these components use `tensorflow-text` as a dependency. To keep the framework lean we have `tensorflow-text` as an optional dependency which should only be installed when these components are to be used. You can install rasa with these additional deps with - `pip install rasa[convert]`

**Comment by Fhrozen** [comment]
I am not sure if someone else try to test `pip install rasa[convert]`, but I was trying to install latest Sara and found that  `pip install rasa[convert]` generates an error. 
```
ERROR: Could not find a version that satisfies the requirement tensorflow_text==2.1.0rc0; extra == "convert" or extra == "full" (from rasa[convert]~=1.9.0->-r requirements.txt (line 1)) (from versions: none)
ERROR: No matching distribution found for tensorflow_text==2.1.0rc0; extra == "convert" or extra == "full" (from rasa[convert]~=1.9.0->-r requirements.txt (line 1))
```
I was trying to check for `tensorflow_test` and it cannot be found.
I think that poetry lock is mistaken:
https://github.com/RasaHQ/rasa/blob/d8d226408f20cc2563c3aefbccef3e364a447666/poetry.lock#L3196
Here you have `tensorflow_test`, while https://github.com/RasaHQ/rasa/blob/d8d226408f20cc2563c3aefbccef3e364a447666/poetry.lock#L4741-L4750 
is based on tensorflow-test. Maybe this needs to check?

**Comment by parikshit-ai** [comment]
@dakshvar22  I have tried `pip install rasa[convert]` but I am getting following error ` ERROR: Could not find a version that satisfies the requirement tensorflow_text==2.1.0rc0; extra == "convert" or extra == "full" (from rasa[convert]) (from versions: none)
ERROR: No matching distribution found for tensorflow_text==2.1.0rc0; extra == "convert" or extra == "full" (from rasa[convert])`

**Comment by dakshvar22** [comment]
@parikshit-ai What OS are you on? `tensorflow-text` is not available for windows yet.

**Comment by parikshit-ai** [comment]
yes I am on windows I got it that is why now I am using wsl now its working fine

**Comment by swayson** [comment]
> 
> 
> yes I am on windows I got it that is why now I am using wsl now its working fine

IS there any solution for this issue? I am experiencing the same on Windows.

**Comment by dakshvar22** [comment]
@swayson Yes, we'll have to wait for a release for windows.
