### ISSUE TITLE
Rasa docs: Syntax error in "Tutorial: Building an Assistant"

### ISSUE THREAD

**Issue by visvamba** [RasaHQ/rasa#5374]
**Description of Problem**:

Under the **Business logic** subsection, there is an error in the return type definition for the ```slot_mappings``` method.

```python
def slot_mappings(self) -> Dict[Text: Union[Dict, List[Dict]]]:
```
The colon syntax is used for slices and not for type definitions. The method as written throws an error at runtime.

**Overview of the Solution**:

It should be corrected to the following:

```python
def slot_mappings(self) -> Dict[Text, Union[Dict, List[Dict]]]:
```
**Examples** (if relevant):

NR

**Blockers** (if relevant):

NR

**Definition of Done**:

Syntax error fixed.

**Comment by sara-tagger** [comment]
Thanks for raising this issue, @melindaloubser1 will get back to you about it soon✨

###### Please also check out the [docs](https://rasa.com/docs/) and the [forum](https://forum.rasa.com/) in case your issue was raised there too 🤗

**Comment by melindaloubser1** [comment]
Thanks for pointing that out! It should be fixed by https://github.com/RasaHQ/rasa/pull/5345
