### ISSUE TITLE
Using sanic workers impact rasa NLU

### ISSUE THREAD

**Issue by Asma-droid** [RasaHQ/rasa#5376]
Hi all,

I use Sanic_ workers=2\. The problem is when i parse an expression two different results are given. In fact, one concerns the previous model and obe concerns the new model.

**Comment by sara-tagger** [comment]
Thanks for the issue, @amn41 will get back to you about it soon!

###### You may find help in the [docs](https://rasa.com/docs/) and the [forum,](https://forum.rasa.com/) too 🤗

**Comment by amn41** [comment]
Hi , thanks for reporting an issue. Can I ask what the setup is? I’m assuming you are running a rasa server and POSTing data to it to train a model? Meanwhile you already have a model loaded, and now when you run with 2 threads, you get two predictions, one from the old model and one from the new. You mean when you send two requests in a row? 
Can you please share the exact command you use to run, train, and the output you get?

**Comment by Asma-droid** [comment]
Hi,

I have used docker compose so my image is as bellow:
version: '3.1'
services:
  rasa:
    image: rasa/rasa:1.7.4
    container_name: rasa
    networks: ['rasa-network']
    ports:
    - "5005:5005"
    environment:
      rasa_endpoint: "http://localhost:5005"
      SANIC_WORKERS: 2
    volumes:
    - "./models:/app/models"
    - "./config:/app/config"
    command: "run --enable-api --debug --credentials /app/config/credentials.yml --endpoints /app/config/endpoints.yml"

  redis:
    container_name: redis
    image: redis
    ports:
      - "6379:6379"
    networks: ['rasa-network']
    volumes:
      - ../data/redis:/data
    entrypoint: redis-server --appendonly yes
    restart: always

I have added in the endpoint.yml 

lock_store:
type: "redis"
url: localhost
port: 6379
password: None
db: 0

**Comment by zembunia** [comment]
Hello,
I faced a similar problem.
I have trained 2 models: model1.tar.gz and model2.tar.gz
If I start the HTTP server with the following command:
`rasa run --enable-api --model model1.tar.gz --port 5555`
I get the response to the server status request (`requests.get("http://localhost:5555/status").text`) as:
`{"model_file":"model1.tar.gz","fingerprint":{},"num_active_training_jobs":0}`
When I make parse requests I get the expected results from the trained model.
After I reload the other model with `requests.put("http://localhost:5555/model", json={"model_file": "model2.tar.gz})`, the status request gets:
`{"model_file":"model2.tar.gz","fingerprint":{},"num_active_training_jobs":0}`
And the parse requests get the expected results, this time for the second model.
So far, so good.
To run with two workers, I have the following endpoint.yml
`lock_store:
    type: "redis"
    url: localhost
    port: 6379
    db: 0`
And I ran a Redis server with default settings and I set the SANIC_WORKERS environment variable to 2.
And started the HTTP server with the following command:
`rasa run --enable-api --model model1.tar.gz --port 5555 --endpoints endpoint.yml`
In the process tree I can see 3 `rasa run` processes, one being the parent of the other two. And only the first child process listens at port 5555.
Now the status requests sometimes returns:
`{"model_file":"model1.tar.gz","fingerprint":{},"num_active_training_jobs":0}`
and sometimes returns:
`{"model_file":null,"fingerprint":{},"num_active_training_jobs":0}`
After some time I started to receive only one response:
`{"model_file":"model1.tar.gz","fingerprint":{},"num_active_training_jobs":0}`
I thought the model was loaded by all of the processes.
Then I reload the new model as I did before. This time, the status requests got either of the two responses, but the responses did not unify even after a long time.
Also the parse requests got answers either from the first model or from the second one.
I think the reload did not load the new model to all the servers.
This can be reproduced easily.
Is this how it should behave?
Thanks

**Comment by wochinge** [comment]
Unfortunately this is somewhat expected since Sanic workers are independent processes and Rasa Open Source currently doesn't handle the models in a process safe way at the moment when doing the `PUT` request you described. A potential workaround for this would be to use a [model server](https://rasa.com/docs/rasa/user-guide/configuring-http-api/#fetching-models-from-a-server) which Rasa Open Source can automatically pull the model from. 

I'm sorry that this behavior wasn't properly documented and hope that at least the workaround works for now. We will have to discuss this with the team how and when we tackle this, since this would probably involve a bigger refactoring.
