### ISSUE TITLE
formbot num_people/number confusing

### ISSUE THREAD

**Issue by erohmensing** [RasaHQ/rasa#5380]
right now, the form bot example has 2 ways of picking up the num_people slot, via two different entity extractors for the same information. If you want to then build off of it, it gets very confusing how that slot is actually being filled. I believe this was implemented because duckling is the preferred entity extractor for numbers, but we still wanted the example to work even if a user couldn't run duckling. 

Proposed solution:
create two formbot examples:
```
examples/formbot/duckling
examples/formbot/no_duckling
```
where one uses duckling and the other should not. each should have their own README instructions, and the `examples/formbot` README should explain that duckling is the recommended one and why, but to use the other if you can't run duckling.

**Comment by MadPr0grammer** [comment]
Hi @erohmensing !
I would like to take this if that's okay?
