### ISSUE TITLE
[Rasa X] Story editor error when type Korean language

### ISSUE THREAD

**Issue by RielKIM** [RasaHQ/rasa#5381]
**Rasa version**:
1.7.0-full (docker)
**Rasa SDK version** (if used & relevant):
1.7.0 (docker)
**Rasa X version** (if used & relevant):
0.25.2 (docker)
**Python version**:
3.6
**Operating system** (windows, osx, ...):
ubuntu 16.04
**Issue**:
Hi, guys I’m Korean. So sometimes I type a Korean character when I’m writing a story on story editor. The problem is suddenly to stop a editor. So I have to refresh the web page. Then all of updated contents are deleted.

So I see the console. I’ve found below error message.
How to fix it? Thanks.

**Error (including full traceback)**:
![image](https://user-images.githubusercontent.com/7589452/76094561-2b416e00-6006-11ea-92ee-25b41872c3fa.png)

**Comment by sara-tagger** [comment]
Thanks for the issue, @tmbo will get back to you about it soon!

###### You may find help in the [docs](https://rasa.com/docs/) and the [forum,](https://forum.rasa.com/) too 🤗

**Comment by akelad** [comment]
@RasaHQ/loop-engineers I think probably relevant to one of you?

**Comment by degiz** [comment]
Looks like that! I'm taking that into our inbox.

**Comment by RielKIM** [comment]
@degiz Hi~ Is there a plan to fix this issue? If you have a plan, Could you share to me?

**Comment by degiz** [comment]
@RielKIM not yet, unfortunately. 
We'll try to groom that next weeks though, I'll keep the issue updated.

**Comment by RielKIM** [comment]
Thanks @degiz.
I don't think this is an urgent problem.
However, I hope you will fix it if you have time. Because I think this issue is not only Korean.
Even though I didn't check it but I think it may be occured this issue for Japanese, Chinese and so on.
Thank you for your help.

**Comment by scd10** [comment]
I have the same problem here. Editor has no response when inputing Chinese, but copy and paste Chinese characters still work. 
Server OS: Centos 7 
Rasa: 1.9.5
Rasa-x: 0.27.2
Client browser: Chrome and Safari

**Comment by RielKIM** [comment]
@scd10 It's totally same with my issue. Korean also could be copy and past on editor but, typing is not working.

**Comment by doubleycn** [comment]
目前这个问题还是存在。
rasa --version
Rasa Version      :         2.8.9
Minimum Compatible Version: 2.8.9
Rasa SDK Version  :         2.8.2
Rasa X Version    :         0.42.3
Python Version    :         3.8.12
Operating System  :         Linux-3.10.0-693.el7.x86_64-x86_64-with-glibc2.17
