### ISSUE TITLE
Rasa X isn't showing images 

### ISSUE THREAD

**Issue by joicepreuss** [RasaHQ/rasa#5388]
**Rasa version**: 1.7.0

**Rasa X version** : 0.25.2

**Python version**: 3.7.5

**Operating system**: Ubuntu 18.04

**Issue**: When I'm trying to send images from actions.py to rasa-x, isn't showing the images.

```
from typing import Any, Text, Dict, List

from rasa_sdk import Action, Tracker
from rasa_sdk.executor import CollectingDispatcher


class ActionHelloWorld(Action):

    def name(self) -> Text:
        return "action_hello_world"

    def run(self, dispatcher: CollectingDispatcher,
            tracker: Tracker,
            domain: Dict[Text, Any]) -> List[Dict[Text, Any]]:

        dispatcher.utter_message(text="Hello World!")
        dispatcher.utter_message(image= 'https://dvtb78sd925mn.cloudfront.net/wp-content/uploads/2018/10/15110630/exemplo-marketing-de-relacionamento.png')
        
        return [] 
```

**Error**:
https://forum.rasa.com/t/return-image-from-actions-in-rasa-x/25643/3?u=joicepreuss

**Comment by sara-tagger** [comment]
Thanks for raising this issue, @erohmensing will get back to you about it soon✨

###### Please also check out the [docs](https://rasa.com/docs/) and the [forum](https://forum.rasa.com/) in case your issue was raised there too 🤗

**Comment by erohmensing** [comment]
Hi there @joicepreuss, how do you currently have rasa x deployed?

**Comment by joicepreuss** [comment]
> Hi there @joicepreuss, how do you currently have rasa x deployed?

I install with `pip install -U rasa-x --extra-index-url https://pypi.rasa.com/simple`

**Comment by erohmensing** [comment]
Sorry for the late response! Okay, so you are using it in local mode then. Let me try to reproduce this!
