### ISSUE TITLE
Wrong value of `model_id` in `message_log` table

### ISSUE THREAD

**Issue by zfallahnejad** [RasaHQ/rasa#5394]
rasa-x 0.24.7
rasa 1.6.1
rasa-sdk 1.6.1
Python 3.6.5
Operating system: Ubuntu

It's not a serious problem, but all of the values of `model_id` in `message_log` are equal to 1. All of these messages were not trained using a single model. I think this problem came from this line of `_create_log` function:
```
self.query(Model.id).filter(Model.project_id == project).first()
```
This line always takes the id of the first model(which is 1), while you should get the id of the last model.

**Comment by sara-tagger** [comment]
Thanks for raising this issue about Rasa X 🔧 @akelad will get back to you about it soon!

###### In the meantime, you may find some useful information in the [Rasa X docs](https://rasa.com/docs/rasa-x/) or by searching our [forum](https://forum.rasa.com/c/rasa-x) 😊

**Comment by akelad** [comment]
@ricwo seems like this is the line they're referring to: https://github.com/RasaHQ/rasa-x/blob/0.26.x/src/community/rasax/community/services/logs_service.py#L190

is this something we should fix or no?

**Comment by zfallahnejad** [comment]
Yes. I think you should change this line to take the last model not the first one.

**Comment by akelad** [comment]
sorry i was asking my team member for his thoughts as well

**Comment by ricwo** [comment]
yes, we should fix this 👍  but it shouldn't be the first or last model, should be whichever one is active at the time the message comes in

**Comment by Tawakalt** [comment]
Closing this as it's no longer relevant.
