### ISSUE TITLE
Getting errors when connecting to Git with rasa-x 0.26

### ISSUE THREAD

**Issue by tiz-lab** [RasaHQ/rasa#5398]
**Rasa version**: 1.8

**Rasa SDK version** (if used & relevant): 1.8

**Rasa X version** (if used & relevant): 0.26

**Python version**: 3.6

**Operating system** (windows, osx, ...): ubuntu

**Issue**: I updated rasa-x to 0.26, I followed the guide for connecting it to GitHub using the UI, I display all my data on my Rasa X UI, but I can't train a model. When I try it I get the following error:

**Error (including full traceback)**:
```
rasa-x_1           | INFO:rasax.community.services.integrated_version_control.git_service:Cloning git repository from URL 'git@github.com:tiz-lab/smartpdt-chatbot.git'.
rasa-x_1           | Job "GitService.run_background_synchronization (trigger: cron[minute='*'], next run at: 2020-03-10 12:53:00 UTC)" raised an exception
rasa-x_1           | Traceback (most recent call last):
rasa-x_1           |   File "/usr/local/lib/python3.6/site-packages/apscheduler/executors/base.py", line 125, in run_job
rasa-x_1           |     retval = job.func(*job.args, **job.kwargs)
rasa-x_1           |   File "/usr/local/lib/python3.6/site-packages/rasax/community/services/integrated_version_control/git_service.py", line 826, in run_background_synchronization
rasa-x_1           |     git_service.synchronize_project(force_data_injection)
rasa-x_1           |   File "uvloop/loop.pyx", line 1456, in uvloop.loop.Loop.run_until_complete
rasa-x_1           |   File "/usr/local/lib/python3.6/site-packages/rasax/community/services/integrated_version_control/git_service.py", line 674, in synchronize_project
rasa-x_1           |     self.clone()
rasa-x_1           |   File "/usr/local/lib/python3.6/site-packages/rasax/community/services/integrated_version_control/git_service.py", line 400, in clone
rasa-x_1           |     repository_url, target_path, env=environment, depth=1, no_single_branch=True
rasa-x_1           |   File "/usr/local/lib/python3.6/site-packages/git/repo/base.py", line 1017, in clone_from
rasa-x_1           |     return cls._clone(git, url, to_path, GitCmdObjectDB, progress, multi_options, **kwargs)
rasa-x_1           |   File "/usr/local/lib/python3.6/site-packages/git/repo/base.py", line 958, in _clone
rasa-x_1           |     finalize_process(proc, stderr=stderr)
rasa-x_1           |   File "/usr/local/lib/python3.6/site-packages/git/util.py", line 328, in finalize_process
rasa-x_1           |     proc.wait(**kwargs)
rasa-x_1           |   File "/usr/local/lib/python3.6/site-packages/git/cmd.py", line 408, in wait
rasa-x_1           |     raise GitCommandError(self.args, status, errstr)
rasa-x_1           | git.exc.GitCommandError: Cmd('git') failed due to: exit code(128)
rasa-x_1           |   cmdline: git clone --depth=1 --no-single-branch -v git@github.com:tiz-lab/smartpdt-chatbot.git /app/git/1
rasa-x_1           |   stderr: 'Cloning into '/app/git/1'...
rasa-x_1           | Could not create directory '/root/.ssh'.
rasa-x_1           | Warning: Permanently added 'github.com,140.82.118.3' (RSA) to the list of known hosts.
rasa-x_1           | git@github.com: Permission denied (publickey).
rasa-x_1           | fatal: Could not read from remote repository.
rasa-x_1           |
rasa-x_1           | Please make sure you have the correct access rights
rasa-x_1           | and the repository exists.

```

**Command or request that led to error**:
Train a model from Rasa X UI

**Comment by sara-tagger** [comment]
Thanks for the issue, @JustinaPetr will get back to you about it soon!

###### You may find help in the [docs](https://rasa.com/docs/) and the [forum,](https://forum.rasa.com/) too 🤗

**Comment by JustinaPetr** [comment]
Hey @tiz-lab when you configured connection to Github, did you ticked the box "Allow write access" to your deploy key?

**Comment by tiz-lab** [comment]
Hi @JustinaPetr , yes I did

**Comment by wochinge** [comment]
Hi @tiz-lab ,

- are you using a custom Rasa X image or the official one?
- What is the command to run the Rasa X container which you are using?

**Comment by tiz-lab** [comment]
Hi @wochinge ,

I'm using the official image. The command to run Rasa X is "docker-compose up".

**Comment by wochinge** [comment]
Did you connect a new repository with Rasa X 0.26 or did you already have a connected repository? Is the training data correctly shown in the UI or is the UI empty?

**Comment by tiz-lab** [comment]
I had a repository that was connected with my old version of Rasa X, then I updated Rasa X and tried to connect it to the same repository.
The UI was empty.
Btw, after I couldn't solve this problem, I tried to uninstall everything and start over with the installation, but now I'm struggling with problems and I'm not able to install any version of Rasa X.. The issue I'm facing right now is [this one](https://forum.rasa.com/t/fatal-password-authentication-failed-for-user-admin/23450/4). I also tried to contact support@rasa.com, but got no answer

**Comment by barun1997** [comment]
I'm having the same problem as @tiz-lab. The UI is just empty.

**Comment by wochinge** [comment]
@tiz-lab Can you please also share your `rasa-worker` logs when you try doing the training? I think the log above and the actual error are to different cases.

**Comment by wochinge** [comment]
@barun1997 Can you please describe your problem and which steps led to it?

**Comment by svshubham01** [comment]
I am also getting the same error cannot train the model, after clicking on Train a message pops up training started but nothing happens, in the Console, it says this `{“reasons”:[“Authorization header not present.”],“exception”:“Unauthorized”}`

**Comment by wochinge** [comment]
@svshubham01 @barun1997 @tiz-lab Can you please describe
- What deployment method you used
- Which steps led to the problem

and provide logs for `rasa-worker` and `rasa-x` ?

**Comment by svshubham01** [comment]
my issue is now solved, I ran out of memory, I upgraded the ram and it works fine.

Thanks
Shubham

**Comment by svshubham01** [comment]
@tiz-lab 
try executing this command
`curl --request POST --url http://<your IP or example.com>/api/projects/default/git_repositories?api_token=<your token> --header 'content-type: application/json' --data-binary @repository.json
`

**Comment by guardcolombia** [comment]
same error

**Comment by wochinge** [comment]
@guardcolombia Would you mind sharing logs, used versions, etc. ? Thanks 🙏

**Comment by pranavmakarand** [comment]
I am facing an issue . I have installed rasa x using the integrated control … I have followed the procedure given in docs. I have synced my git to the rasa x . It shows a green handle meaning sync successful. All the stories , responses, have been updated in rasax uI. when i chat with the bot it doesnt give a reponse. I checked console it is giving 2.76631f6e.chunk.js:2 POST http://206.189.143.250/api/conversations/0a8f146e2a8f44fa8015dc9ed8b278bd/messages?environment=production 404 (Not Found) . the link address gives this json error : {“reasons”:[“Authorization header not present.”],“exception”:“Unauthorized”}. I am stuck for 2 days please help!!

**Comment by wochinge** [comment]
@pranavmakarand Could you please create a new issue in case you haven't yet?

**Comment by webdev-rohit** [comment]
Hey, I'm trying to connect with Git using - curl --request POST --url http://<your IP or example.com>/api/projects/default/git_repositories?api_token=<your token> --header 'content-type: application/json' --data-binary @repository.json. I'm not able to connect to it though. It says - {"version":"1.0.1","status":"failure","message":"Could not read from remote repository.","reason":"RepositoryCreationFailed","details":"Given repository credentials don't provide write permissions to the repository. Please make sure the SSH key is correct and the administrator of the remote repository gave you the required permissions.","help":null,"code":401} , I have created a new repo with code pushed to it with proper directory structure, I don't know what is causing this issue. Also , while adding SSH key in Git platforms, you don't really get the 'Allow write access' checkbox nowadys, it used to be in earlier versions.

**Comment by webdev-rohit** [comment]
I'm getting 'Unable to access repository. Please check your credentials and try again.' when trying to connect my RASA X to my git
