### ISSUE TITLE
Tensorflow binary was not compiled to use:AVX2

### ISSUE THREAD

**Issue by srinathgnath** [RasaHQ/rasa#5409]
Hello,

I do see a message "Tensorflow binary was not compiled to use:AVX2" while initiate rasa. I'm running rasa on VM and avx is not enabled on it. Does it impact the performance, if not what would be the impact?

Attached the message screen print. 

![image](https://user-images.githubusercontent.com/35440448/76425913-ad23f500-6380-11ea-89b8-b20f0a403aa2.png)

![image](https://user-images.githubusercontent.com/35440448/76426754-d85b1400-6381-11ea-8255-7e09bfa281ae.png)

**Comment by sara-tagger** [comment]
Thanks for raising this issue, @rgstephens will get back to you about it soon✨

###### Please also check out the [docs](https://rasa.com/docs/) and the [forum](https://forum.rasa.com/) in case your issue was raised there too 🤗

**Comment by rgstephens** [comment]
Please use our forum to post questions - https://forum.rasa.com.

This warning means that TensorFlow could run faster on your system. To do this, you would need to compile TensorFlow from source.
