### ISSUE TITLE
Improve `rasa data split` folder structure

### ISSUE THREAD

**Issue by akelad** [RasaHQ/rasa#5415]
Right now if you run `rasa data split` and you have some ResponseSelector data in your training data, the file structure in `train_test_split` will look like this:

 nlg_test_data.md
 test_data.json
 train_data.json
 nlg_train_data.md

This is a bit confusing. Instead we should probably have `test` and `train` subfolders where the relevant files go into

**Comment by eibhleag** [comment]
IMO anything that deals with file ingestion / output probably belongs in @RasaHQ/loop-engineers because it's tightly coupled to Integrated Version Control. @TyDunn - thoughts?

**Comment by TyDunn** [comment]
@eibhleag This is Rasa Open Source issue. But you are right eventually it would affect IVC. Do you mean production squad (you tagged the loop squad)?

**Comment by eibhleag** [comment]
I do, whoops!

**Comment by simonm3** [comment]
Also the command line train expects a folder and test expects a file. This is inconsistent and means you have to move the files out of the train_test folder. Another reason to create separate train and test folders.
