### ISSUE TITLE
Implementing a confidence rate for rasa NLU intent detection 

### ISSUE THREAD

**Issue by lpschaub** [RasaHQ/rasa#5420]
**Description of Problem**:

**Overview of the Solution**:
I implemented a "threshold" argument -> a float between 0.0 and 0.9999.... 
It parses the confidence score of the IntentClassifier and it takes into account the intent classification result if and only if the confidence score is above the threshold. 

I also implemented a "forget" score -> total of user input that fall directly into "I don't know the intention" intent / total of user input. This way, you can have both the f1 score of the user input considered by the model and the proportion of input "intentionaly forgotten" by the model. 

Describe, without going too low into technical details,
what changes need to happen during implementation of this feature. -->
inherit the threshold param and the fraction forgotten inputs /total inputs
**Examples** (if relevant):

os.system(f'rasa test nlu -u {tts}{ficdir}/test_data.md --config ../config_supervised.yml --threshold 0.7 --out ../results2/{ficdir} --model ../models/{ficdir}.tar.gz')

  "micro avg": {
    "precision": 0.972972972972973,
    "recall": 0.972972972972973,
    "f1-score": 0.972972972972973,
    "support": 185
  },
  "macro avg": {
    "precision": 0.9734318555008209,
    "recall": 0.9731189960575267,
    "f1-score": 0.9725201549663185,
    "support": 185
  },
  "weighted avg": {
    "precision": 0.974095238095238,
    "recall": 0.972972972972973,
    "f1-score": 0.9726984358152821,
    "support": 185
  },
  "forgotten": 10
}

**Blockers** (if relevant):

**Definition of Done**:

**Comment by sara-tagger** [comment]
Thanks for submitting this feature request 🚀 @amn41 will get back to you about it soon! ✨

**Comment by amn41** [comment]
hi @lpschaub - thanks for this feature request. My gut reaction is that this logic should not be inside of NLU. We have [fallbacks](https://rasa.com/docs/rasa/core/fallback-actions/#id1) in core that handle this. If you are only using NLU, I'd go for implementing this logic in your own code that calls the NLU server

**Comment by lpschaub** [comment]
Hello thanks for your answer. 

I did implement it in my own fork. 
Only for rasa nlu test though. 

If anyone is interested I can share the code
