### ISSUE TITLE
Remove references to chatito from docs

### ISSUE THREAD

**Issue by akelad** [RasaHQ/rasa#5424]
We should remove the reference to chatitio from our training data format, because this does more bad than good. Instead we should mention Rasa X, learning from real conversations or similar

Relevant docs page: https://rasa.com/docs/rasa/nlu/training-data-format/#generating-more-entity-examples

**Comment by sekhar2017** [comment]
Yes I will. Please guide and move this to doing.

**Comment by akelad** [comment]
@sekhar2017 are you saying you want to work on this?

**Comment by sekhar2017** [comment]
Yes please .let me know furthur steps .

**Comment by akelad** [comment]
I think we'll take on this issue because we need to think about how we want to communicate that first. But feel free to pick any issue to work on from the [contributor board](https://github.com/orgs/RasaHQ/projects/23)

**Comment by erohmensing** [comment]
closed in #5494

**Comment by sekhar2017** [comment]
Ok .will do. Thankyou
