### ISSUE TITLE
Error: "password authentication failed for user admin"

### ISSUE THREAD

**Issue by tiz-lab** [RasaHQ/rasa#5425]
**Rasa version**: 1.8.1

**Rasa X version**: 0.26.1 

**Python version**: 3.6

**Operating system** (windows, osx, ...): Ubuntu 18

**Issue**:

I installed Rasa X on my new VM with Ubuntu 18, followed all the steps for the Quick Docker Installation, but when it comes to creating a user I get an error with my db credentials. If I run `sudo docker-compose up` I can see that the error is the one I put below.
However, I did nothing but following the steps in the guide which are:

$ curl -sSL -o install.sh https://storage.googleapis.com/rasa-x-releases/0.26.1/install.sh
$ sudo bash ./install.sh
$ cd /etc/rasa
$ sudo docker-compose up -d
$ sudo python rasa_x_commands.py create --update admin me <PASSWORD>

**Error (including full traceback)**:
```
db_1               | INFO  ==> ** Starting PostgreSQL setup **
db_1               | INFO  ==> Validating settings in POSTGRESQL_* env vars..
db_1               | INFO  ==> Initializing PostgreSQL database...
db_1               | INFO  ==> postgresql.conf file not detected. Generating it...
db_1               | INFO  ==> pg_hba.conf file not detected. Generating it...
db_1               | INFO  ==> Deploying PostgreSQL with persisted data...
db_1               | INFO  ==> Configuring replication parameters
db_1               | INFO  ==> Configuring fsync
db_1               | INFO  ==> Loading custom scripts...
db_1               | INFO  ==> Enabling remote connections
db_1               | INFO  ==> Stopping PostgreSQL...
db_1               |
db_1               | INFO  ==> ** PostgreSQL setup finished! **
db_1               | INFO  ==> ** Starting PostgreSQL **
db_1               | 2020-03-16 10:43:51.559 GMT [1] LOG:  listening on IPv4 address "0.0.0.0", port 5432
db_1               | 2020-03-16 10:43:51.559 GMT [1] LOG:  listening on IPv6 address "::", port 5432
db_1               | 2020-03-16 10:43:51.561 GMT [1] LOG:  listening on Unix socket "/tmp/.s.PGSQL.5432"
db_1               | 2020-03-16 10:43:51.581 GMT [151] LOG:  database system was shut down at 2020-03-15 19:12:19 GMT
db_1               | 2020-03-16 10:43:51.590 GMT [1] LOG:  database system is ready to accept connections
db_1               | 2020-03-16 10:43:58.922 GMT [158] FATAL:  password authentication failed for user "admin"
db_1               | 2020-03-16 10:43:58.922 GMT [158] DETAIL:  Password does not match for user "admin".
db_1               |    Connection matched pg_hba.conf line 1: "host     all             all             0.0.0.0/0               md5"
db_1               | 2020-03-16 10:43:59.169 GMT [159] FATAL:  password authentication failed for user "admin"
db_1               | 2020-03-16 10:43:59.169 GMT [159] DETAIL:  Password does not match for user "admin".
db_1               |    Connection matched pg_hba.conf line 1: "host     all             all             0.0.0.0/0               md5"
duckling_1         | no port specified, defaulting to port 8000
duckling_1         | Listening on http://0.0.0.0:8000

```

**Command or request that led to error**:
```
sudo docker-compose up
```

**Comment by sara-tagger** [comment]
Thanks for the issue, @wochinge will get back to you about it soon!

###### You may find help in the [docs](https://rasa.com/docs/) and the [forum,](https://forum.rasa.com/) too 🤗

**Comment by wochinge** [comment]
@tiz-lab Rasa X does not support multiple users besides from the user `me`. Rasa Enterprise can handle multiple users. 
So what your command should look like: `sudo python rasa_x_commands.py create --update admin me <your password>`.

However, it seems that Rasa X can't access your database. What's the output of `docker-compose logs rasa-x`?

**Comment by PaulContremoulin** [comment]
@wochinge I'm facing to the same issue, and this is RasaX that  can't access to the database, docker-compose logs rasa-x returns :
`FATAL:  password authentication failed for user "admin"`

**Comment by wochinge** [comment]
@PaulContremoulin Does the database password contain any weird characters (quotes, spaces)?

**Comment by PaulContremoulin** [comment]
No, password contains only alphabetic characters. I'm trying to launch the docker-compose on Windows, It's can be related to the issue ?

**Comment by wochinge** [comment]
> I'm trying to launch the docker-compose on Windows, It's can be related to the issue ?

mhm, could be 🤔
Does this guide help? https://forum.rasa.com/t/tool-guide-unofficial-rasax-quick-install-script-for-a-pure-windows-machine/25938

**Comment by amardeep2006** [comment]
I also faced this issue with docker-compose on Windows 10. The root cause in my case was not deleting db-volume from docker container.
On Day 1 : I created docker containers with Rasa 2 docker-compose files.
On Day 2 : I deleted all images and containers from Docker Dashboard but did not delete db-volume. I used a new .env file with fresh generated paswords.

Then i started seeing this error in logs 

```
 File "/usr/local/lib/python3.7/site-packages/psycopg2/__init__.py", line 127, in connect
conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
sqlalchemy.exc.OperationalError: (psycopg2.OperationalError) FATAL: password authentication failed for user "admin"
(Background on this error at: http://sqlalche.me/e/13/e3q8)
```

Solution : I had to delete db-volume from docker along with db container and run docker-compose. This rebuild the db container with new password.
Saw this thread during google search hence adding my solution to help others.

**Comment by chupachupbum** [comment]
> On Day 2 : I deleted all images and containers from Docker Dashboard but did not delete db-volume. I used a new .env file wi

I tried your method: I deleted db-volume and db container but it didn't help. Is there any extra steps? Or maybe can you explain with more details so I can see what did I do wrong?

**Comment by wochinge** [comment]
@chupachupbum Can you please create a new issue or ask in the [forum](https://forum.rasa.com)?
