### ISSUE TITLE
Upgrading Rasa Caused My Forms to Break

### ISSUE THREAD

**Issue by qfung** [RasaHQ/rasa#5431]
After upgrading Rasa, I replaced my current config file to the default one generated by ‘rasa init’, I also added the FormPolicy into the config, as I have several form actions in my bot, however I keep on getting this error message when I I try to train the bot: 

**You have defined a form action, but haven’t added the FormPolicy to your policy ensemble. Either remove all forms from your domain or exclude the FormPolicy from your policy configuration.**

It doesn’t matter if I remove the FormPolicy or not, training the bot will result in the same error message. I also copied the policies from Rasa’s formbot example, nothing worked!

Please help!!!

**Comment by sara-tagger** [comment]
Thanks for raising this issue, @wochinge will get back to you about it soon✨

###### Please also check out the [docs](https://rasa.com/docs/) and the [forum](https://forum.rasa.com/) in case your issue was raised there too 🤗
