### ISSUE TITLE
Tensorflow Error

### ISSUE THREAD

**Issue by qfung** [RasaHQ/rasa#5433]
After upgrading Rasa to 1.8.1 I can no loner use my forms. I keep on getting this error: 
`tensorflow/core/kernels/data/generator_dataset_op.cc:103] Error occurred when finalizing GeneratorDataset iterator: Cancelled: Operation was cancelled`

**Comment by sara-tagger** [comment]
Thanks for the issue, @amn41 will get back to you about it soon!

###### You may find help in the [docs](https://rasa.com/docs/) and the [forum,](https://forum.rasa.com/) too 🤗
