### ISSUE TITLE
Host additional static files for RasaX installation in the CDN along with the Docker Compose and Python scripts 

### ISSUE THREAD

**Issue by ActuallyAcey** [RasaHQ/rasa#5435]
**Description of Problem**:
In my writing of the [Windows quick-install script](https://forum.rasa.com/t/tool-guide-unofficial-rasax-quick-install-script-for-a-pure-windows-machine/25938/8) I've noticed that most of the project files needed to initially set up RasaX are completely static. 

![image](https://user-images.githubusercontent.com/44527014/76941832-b84bc780-6922-11ea-9aea-234858cbfe0e.png)

Copy-pasting the contents of these files, instead of having them just as quickly available for 
download as the **docker-compose.yml** and **rasa_x_commands.py** feels redundant. 

**Overview of the Solution**:

- Host the three files marked in the image and make them available for quickly downloading and pasting instead of writing these files in the CDN. 
- Make the copy-pasting method secondary and/or optional

**Definition of Done**:

- [ ] See above.

**Comment by sara-tagger** [comment]
Thanks for submitting this feature request 🚀 @rgstephens will get back to you about it soon! ✨

**Comment by rgstephens** [comment]
The `docker-compose.yml` and `rasa_x_commands.py` files are part of the distribution and should not be changed by the user. Whereas the files you reference are configuration files that are unique to each deployment.
