### ISSUE TITLE
Tensorboard logging: Use same timestamp as in model file

### ISSUE THREAD

**Issue by tabergma** [RasaHQ/rasa#5439]
When specifying a directory for tensorboard logging via the config file, training metrics are written to `<specified-directory>/<model-name>/<timestamp>`. The model itself is written to the model output directory. If no name is provided the model name includes a timestamp. However, the model file timestamp is different from the timestamp used in the tensorboard logging directory. It would be great if the same timestamp could be used here, so that you can easily see what logging folder belongs to what model.

**Comment by Ghostvv** [comment]
@tabergma this might be solved by using only `train_step` override?

**Comment by tabergma** [comment]
Let's see if we switch to `train_step`
