### ISSUE TITLE
Change user message text

### ISSUE THREAD

**Issue by Alexandru-Pirvu** [RasaHQ/rasa#5445]
Hello!

I have an issue finding the best spot to intervene in the rasa flow. My use case is that I want to alter the user's message text in a specific case, more exactly, when a certain entity is found. At first, it seemed that the logical place to do that was in a custom nlu component. And indeed, that's where one add information for future processing in the nlu pipeline. But as it turns out, the only thing that cannot be changed is the text of the message, and I think it is because of this line: https://github.com/RasaHQ/rasa/blob/f3a3fb7ab391482da5ae7f6f789f0a8c7d600f8b/rasa/core/processor.py#L458 if it would be `parse_data.text`, the situation would've been resolved
 Also, the log following also adds the received text instead of the changed one.

Dummy example: 
user says `hi`
nluComponent does
`if message.text == hi:
    message.text = "Hello"
`

This being the situation, I have some open questions:

1. Is it intended that you cannot change by all means the user text at this level?
2. Is there a better place to alter user input? It can be done in a custom policy, but it really feels wierd to alter the tracker.
3. Is there a way to implement a custom tracker? (maybe if there is no other evident solution, this would be a better workaround)

**Comment by amn41** [comment]
Hi @Alexandru-Pirvu, this is more of a usage question than a bug or feature request. So please ask in the forum so I can post an answer there. But general feedback is that this seems like a niche use case/workaround, because in general you don't get to choose what your users say to your assistant.

**Comment by Alexandru-Pirvu** [comment]
@amn41 Yes, I agree it is a niche use case, but you would be surprised how many niches cases some businesses requires.

Thank you for your quick response and suggestion. I will address the case on the forum :).
