### ISSUE TITLE
knowledgebasebot example not working

### ISSUE THREAD

**Issue by david-wb** [RasaHQ/rasa#5458]
**Rasa version**:
1.8.2

**Rasa SDK version** (if used & relevant):

**Rasa X version** (if used & relevant):

**Python version**:
3.6.10

**Operating system** (windows, osx, ...):
osx

**Issue**:

**Error (including full traceback)**:
```

```

**Command or request that led to error**:
```
Your input ->  Find mexican restaurants                                         
I could not find any objects of type 'restaurant'.
```

**Content of configuration file (config.yml)** (if relevant):
```yml

```

**Content of domain file (domain.yml)** (if relevant):
```yml

```

The knowledge base example doesn't seem to be working. It looks like the query to the in memory KB might be failing. Idea how I can resolve this?

**Comment by david-wb** [comment]
Moving `knowledge_base_data.json` into the data folder fixes the problem for me.

**Comment by sara-tagger** [comment]
Thanks for raising this issue, @wochinge will get back to you about it soon✨

###### Please also check out the [docs](https://rasa.com/docs/) and the [forum](https://forum.rasa.com/) in case your issue was raised there too 🤗
