### ISSUE TITLE
How to access the leagcy version of Rasa?

### ISSUE THREAD

**Issue by axchanda** [RasaHQ/rasa#5459]
The bracnhes in Rasa starts from 1.0, but I want to access rasa code before (0.x). How can I fork them or access them?

**Comment by sara-tagger** [comment]
Thanks for the question, our Github issue board is for **bugs and feature requests only,** though 😕
Please ask this question in the [forum✨](https://forum.rasa.com/c/rasa)

###### If you were describing a bug, please create a [report](https://github.com/RasaHQ/rasa/issues/new?labels=bug&template=bug_report.md) and fill out the template.

**Comment by sara-tagger** [comment]
Thanks for raising this issue, @closed will get back to you about it soon✨

###### Please also check out the [docs](https://rasa.com/docs/) and the [forum](https://forum.rasa.com/) in case your issue was raised there too 🤗
