### ISSUE TITLE
Custom output payloads inconsistent documentation

### ISSUE THREAD

**Issue by Flythe** [RasaHQ/rasa#5461]
**Rasa version**: 1.8.2

**Python version**: 3.6.9

**Operating system** (windows, osx, ...): Ubuntu 18.04

**Issue**: 

The Rasa documentation for [custom payloads](https://rasa.com/docs/rasa/core/domains/#custom-output-payloads) shows an example payload:

```yml
responses:
  utter_take_bet:
  - custom:
      blocks:
      - type: section
        text:
          text: "Make a bet on when the world will end:"
          type: mrkdwn
        accessory:
          type: datepicker
          initial_date: '2019-05-21'
          placeholder:
            type: plain_text
            text: Select a date
```

Using this example yields an empty response on an socket.io channel:

```javascript
["bot_uttered", null]
0: "bot_uttered"
1: null
```

I've traced this to the socket.io channel implementation at line [#107](https://github.com/RasaHQ/rasa/blob/1c627fe2dbf92d41cfa3a685b0b66e5d1b4367dc/rasa/core/channels/socketio.py#L107). At this point the json object looks like:

```json
{"blocks": [{"accessory": {"initial_date": "2019-05-21", "placeholder": {"text": "Select a date", "type": "plain_text"}, "type": "datepicker"}, "text": {"text": "Make a bet on when the world will end:", "type": "mrkdwn"}, "type": "section"}]}
```

The object is unpacked into the [socket.io emit function](https://github.com/miguelgrinberg/python-socketio/blob/913c68a3380434d357617b10e77753d51b896a27/socketio/asyncio_server.py#L86) which doesn't have a ```blocks``` parameter.

To get the custom response either the ```blocks``` item in the yaml example has to be changed to ```data``` (i.e. the name of the parameter in the emit function) or the json object should just be passed on into the emit function instead of being unpacked.

**Comment by sara-tagger** [comment]
Thanks for the issue, @alwx will get back to you about it soon!

###### You may find help in the [docs](https://rasa.com/docs/) and the [forum,](https://forum.rasa.com/) too 🤗

**Comment by erohmensing** [comment]
Hi @Flythe, it is specified that this payload is a slack payload:
```
For example, although date pickers are not a defined parameter in responses because they are not supported by most channels, a Slack date picker can be sent like so:
```
Notive that is says it is supported by slack and not most channels. This payload will not work in socket.io; that is why it is a custom payload.

**Comment by Flythe** [comment]
That specific example is said to be slack only. But the documentation also states that: 

> You can also send any arbitrary output to the output channel using the custom: key.

However, for the socket.io channel this will *only* work when the first key inside the custom key is ```data```. Like so:
```yml
- custom:
    data:
      - text: "test"
```

This could be stated more clearly in the documentation. Or the socket.io channel's [send_custom_json](https://github.com/RasaHQ/rasa/blob/1c627fe2dbf92d41cfa3a685b0b66e5d1b4367dc/rasa/core/channels/socketio.py#L100) function could be adjusted to not unpack the json_message variable.

**Comment by erohmensing** [comment]
I'd prefer to keep it the way that is is (need to wrap in data) to match the documentation [here](https://github.com/botfront/rasa-webchat#sending-a-message-with-custom-data). Would you like to contribute documentation to that point about how to send custom data? I think it should live on the socketio docs, as its not scalable to put information about all of the connectors on that domains page. in other words here: https://rasa.com/docs/rasa/user-guide/connectors/your-own-website/#websocket-channel

**Comment by erohmensing** [comment]
I guess an alternative contribution could be handling both -- i.e. look for the `data` param, and if it's not there, try to wrap it that way. You should also print a UserWarning to tell the user that they should wrap it in the `data` param after sending it through. What do you think?

**Comment by Flythe** [comment]
That sounds like a good solution, I'll put it on my backlog to contribute this change.

**Comment by erohmensing** [comment]
Awesome, we'd love your contribution.
