### ISSUE TITLE
Issue with the /status endpoint

### ISSUE THREAD

**Issue by KarthiAru** [RasaHQ/rasa#5462]
**Rasa version**: 1.8.2

**Rasa SDK version** (if used & relevant): 1.8.1

**Issue**:
- The model file name is missing.

This is the response for the `/status` endpoint
```
{
    "model_file": "models",
    "fingerprint": {
        "config": "99914b932bd37a50b983c5e7c90ae93b",
        "core-config": "8fc9bf270cf15c858b22265fd8b17ae7",
        "nlu-config": "779df72ac9336e87bcd83a533963a541",
        "domain": 1916639923646254355,
        "nlg": "e60b68c4194d3a27704d645acea499e9",
        "messages": 218516195060435727,
        "stories": 880215802099563704,
        "trained_at": 1584896189.260793,
        "version": "1.8.0"
    },
    "num_active_training_jobs": 0
}
```

**Comment by sara-tagger** [comment]
Thanks for raising this issue, @tabergma will get back to you about it soon✨

###### Please also check out the [docs](https://rasa.com/docs/) and the [forum](https://forum.rasa.com/) in case your issue was raised there too 🤗

**Comment by tabergma** [comment]
@wochinge We return `app.agent.path_to_model_archive` as model_file when calling the `/status` endpoint. Seems that it is not always set to the actual model file. Is that intended?

**Comment by KarthiAru** [comment]
@tabergma I had to add a trailing '/' after "models" in my Dockerfile to make it work.
For e.g. `ADD 20200405-093147.tar.gz models/`.

This is the current response.
```
{
    "model_file": "models/20200405-093147.tar.gz",
    "fingerprint": {
        "config": "99914b932bd37a50b983c5e7c90ae93b",
        "core-config": "0ed6741af8920f75c852b8872051884d",
        "nlu-config": "f18ebd6634cc200c46006af267a8874e",
        "domain": 1159394557507141038,
        "nlg": "e60b68c4194d3a27704d645acea499e9",
        "messages": 505871675226408304,
        "stories": 474258077560217513,
        "trained_at": 1586059313.1299760342,
        "version": "1.9.3"
    },
    "num_active_training_jobs": 0
}
```

**Comment by wochinge** [comment]
Makes sense 👍 I'll close this then
