### ISSUE TITLE
Add "has only 1 training example" UserWarning to CLI command "rasa data validate"

### ISSUE THREAD

**Issue by JulianGerhard21** [RasaHQ/rasa#5463]
**Description of Problem**:

Currently, the UserWarning `.../common.py:347: UserWarning: Entity <entity_name> has only 1 training examples! The minimum is 2, because of this the training may fail.` is printed after executing the training process, in most cases after the core has been trained.

I assume, that in most cases, either the user did not know, that training with only one sample may result in errors, or he accidently misnamed his entity. This results in cancelling the training process.

**Overview of the Solution**:

I suggest to add this observation to the list of observations in the CLI command `rasa data validate`.

**Definition of Done**:

*   [ ] Tests are added
*   [ ] Feature mentioned in the changlog

**Comment by sara-tagger** [comment]
Thanks for submitting this feature request 🚀 @JustinaPetr will get back to you about it soon! ✨
