### ISSUE TITLE
Update data format to support composite entities

### ISSUE THREAD

**Issue by tabergma** [RasaHQ/rasa#5465]
**Description of Problem**:
In a sentence like `I want to fly from Berlin to Amsterdam.` we not only want to annotate `Berlin` and `Amsterdam` as entities `city`, but also want to assign specific roles to them. `Berlin` should have the role `origin` and `Amsterdam` should have the role `destination`. With the current data format this is not doable. 

**Overview of the Solution**:
_Markdown_
We want to change the annotation format for entities:
`I want to fly from [Berlin]{"entity": "city", "role": "origin"} to [LA]{"entity": "city", "role": "destination", "synonym": "Los Angeles"}.` or
`Show me [red]{"entity": "colour", "group": 0} [balloons]{"entity": "item", "group": 0} and [black]{"entity": "colour", "group": 1} [shoes]{"entity": "item", "group": 1}.`

We will use `{}` to define entities that have roles/groups/synonyms. If you just have a simple entity without any role/group/synonym, the old format can still be used (`[Berlin](city)`). 
We will deprecate the old syntax for synonyms, e.g. `[LA](city:Los Angeles)`. Instead users should use `[LA]{"entity": "city", "synonym": "Los Angeles"}`. We should offer a script that converts the old format into the new format.

_JSON_
We simply add new keywords to the entity definition in the JSON format:
```
{
    "intent": "fly",
    "entities": [
        {
            "start": 19,
            "end": 25,
            "value": "Berlin",
            "entity": "city",
            "role": "from",          
        },
        {
            "start": 29,
            "end": 31,
            "value": "LA",
            "entity": "city",
            "role": "to",          
            "synonym": "Los Angeles",          
        }
    ],
    "text": "I want to fly from Berlin to LA."
},
```

**Definition of Done**:
- [ ] Tests are added
- [ ] New training data format is supported
- [ ] We have a script in place that converts the old format to the new format
- [ ] Documentation
- [ ] Changelog

**Comment by erohmensing** [comment]
@tabergma would there be a big argument for keeping in-line synonyms and not deprecating that completely? i.e. just leaving the separate
```
synonym:Los Angeles
- LA
```
format?

**Comment by tabergma** [comment]
No reason to remove this. We can keep this.
