### ISSUE TITLE
Add name to response selector output

### ISSUE THREAD

**Issue by jamesmf** [RasaHQ/rasa#5469]
**Description of Problem**:
The response selector returns the full response, but not the structured "type" of the response

**Overview of the Solution**:
Add the `type` of the response to the output (can be named anything meaningful).

**Examples** (if relevant):
```
"response_selector": {
        "default": {
            "response": {
                "type": "cats"
                "name": "I see you have a question about cats",
                "confidence": 0.775967896
            }
      }
```

In this example the `responses.md` contains a heading for `faq/cats` that says `"I see you have a question about cats"`.  The reason it would be helpful to have the structured name `/cats` in the response is so that it's easier to use that output elsewhere, instead of having to check for the whole string "I see you have a question about cats."

**Comment by erohmensing** [comment]
Hey @jamesmf! I believe this enhancement was just implemented last week 🙂 if you try out building the master version from source, you can let us know what you think. Or you can wait for the 1.9 release, which should come out this week!

https://github.com/RasaHQ/rasa/pull/5432

**Comment by jamesmf** [comment]
awesome!
