### ISSUE TITLE
forum.rasa.com has no reply for one year

### ISSUE THREAD

**Issue by hqsh** [RasaHQ/rasa#5470]
Sorry to ask a question here. But I found forum.rasa.com has no reply for 1 year.

I had a question to ask in RASA forum. And the system recommand 2 same question for me. However, I found both of them had no reply for about one year. May I beg some one to reply the questions?

The links of the same questions as mine are as follow:

https://forum.rasa.com/t/using-custom-nlu-and-rasa-core-by-replacing-rasa-nlu/5555

https://forum.rasa.com/t/how-to-use-my-own-nlu-module-completely-with-rasa-core/6364

Thank you!

**Comment by erohmensing** [comment]
Hi @hqsh, if you create a new post on the forum (instead of replying to an old post), someone will answer you 🙂 new questions have much more visibility and we try to answer new posts as they come in.

Github issues are only for bugs and feature requests -- please don't ask questions here.
