### ISSUE TITLE
deprecate EndpointConfig.request() method

### ISSUE THREAD

**Issue by erohmensing** [RasaHQ/rasa#5471]
from @degiz: In general, I'm not a big fan of EndpointConfig. On top of standard code it can only do auth and return json body (which already leads to bugs like RasaHQ/rasa#5322). Instead of implementing the check for different content types, I'd prefer to get rig of this method completely. As far as I can see it's a decoration around standard "request()", that also concatenates path with subpath. IMO the problems it brings overweight the good things.

**Comment by degiz** [comment]
Auth could be good enough reason to still have it though.. I'll check it again. 
Maybe just we need to make sure we're not using it in a wrong way.

**Comment by erohmensing** [comment]
Just thought I'd make an issue so that you could figure it out since you'd mentioned it multiple times 🙂
