### ISSUE TITLE
output_channel=latest doesn't work as expected 

### ISSUE THREAD

**Issue by ayarulin** [RasaHQ/rasa#5486]
I'm using HTTP API Inject an intent into a conversation with `output_channel` set to `latest`.

```bash
curl -X POST \
    --url 'http://localhost:5005/conversations/1/trigger_intent?output_channel=latest' \
    --header 'Content-Type: application/json' \
    --data '{ "name": "greet" }'
```

The first API call works as expected and output redirected to the latest conversation channel but the second one and all other subsequent calls lead to no output at all.

**Comment by sara-tagger** [comment]
Thanks for the issue, @amn41 will get back to you about it soon!

###### You may find help in the [docs](https://rasa.com/docs/) and the [forum,](https://forum.rasa.com/) too 🤗
