### ISSUE TITLE
Same incompatibility issue between Rasa & Rasa-X and low conf level in every release.

### ISSUE THREAD

**Issue by kapoorh** [RasaHQ/rasa#5487]
Hi,

This is an issue which I am continuously facing while updating the rasa version. earlier also I reported the same issue. I upgraded my rasa version to 1.8.0 on dev server and did testing, result was different then  version 1.4.3. So as per your suggestion I changed the confidence level from 0.80 to 0.65. and stabilized my chatbot use cases . That time also rasa new version was not compatible with rasa-x new version.
Now I tried to setup the same version 1.8.0 on my another environment but new versions have been released, so I updated with 1.8.2 and verified that most of the use cases are failing in 1.8.2, so I updated with 1.9.0 but new rasa-x 0.26.3 version again not compatible with rasa 1.9.0 new version.  I don't know which version I should follow?

1. Why most of the time in the first instance both rasa and rasa-x doesn't compatible with each other?
2. Why in every release we see volatility in confidence level? I can understand you change algorithm but still volatility should not be high. Its very difficult everytime to upgrade the new version and see less confidence level of the same use cases which were working fine in previous one.
3. Must have some commands or way to Install specific version of rasa.
4. How will we get to know which rasa-x version is compatible with rasa version?
5. How to check rasa-x installed version?

Please rectify these issues.

Thanks and Regards
Harsh

**Comment by sara-tagger** [comment]
Thanks for the issue, @dakshvar22 will get back to you about it soon!

###### You may find help in the [docs](https://rasa.com/docs/) and the [forum,](https://forum.rasa.com/) too 🤗

**Comment by tmbo** [comment]
Are you trying to install Rasa Open Source and Rasa X in the same python environment?

**Comment by Ghostvv** [comment]
do you see confidence levels decrease between `1.8.0` and `1.8.2`?

**Comment by kapoorh** [comment]
Yes, I am installing in the same environment.  I follow the below commands :

python3.6 -m venv rasa_env
source  rasa_env/bin/activate
sudo apt-get install python3.6-dev
pip install twisted 
pip install rasa-x --extra-index-url https://pypi.rasa.com/simple
pip install rasa[spacy]
python -m spacy download en_core_web_md
python -m spacy link en_core_web_md en
pip install rasa
pip install rasa[tensorflow]
pip install pandas

yes confidence level is low... thats why it's going into fallback policy. Many use cases are falling into the TwoStageFallBack policy.

**Comment by degiz** [comment]
Hey @kapoorh 

> How to check rasa-x installed version

you can use [this](https://rasa.com/docs/rasa-x/api/rasa-x-http-api/#operation/versions) endpoint for that.

> Why most of the time in the first instance both rasa and rasa-x doesn't compatible with each other

Could you please elaborate on this?

**Comment by kapoorh** [comment]
Hi @degiz ,

With the help of above commands I setup my environment. Then I saw the new released version of Rasa 1.9.0 so upgrade the same version with - pip install rasa --upgrade

But I got an error:

**ERROR: rasa-x 0.26.3 has requirement rasa<1.9,>=1.8.1, but you'll have rasa 1.9.0 which is incompatible.**
Installing collected packages: rasa
  Attempting uninstall: rasa
    Found existing installation: rasa 1.8.2
    Uninstalling rasa-1.8.2:
      Successfully uninstalled rasa-1.8.2
Successfully installed rasa-1.9.0

Thanks and Regards
Harsh

**Comment by degiz** [comment]
Hey @kapoorh 

Thanks, I see now.
As you've mentioned, you're installing pip package of `rasa-x` to the same env as `rasa`.

I suppose that then you're running `rasa-x` in a local mode after that. However, local mode is there mostly to enable the development.

`rasa-x` and `rasa` still share some code, and each release pushes the required version further. That's the reason you face incompatible version. 

We strongly [recommend](https://rasa.com/docs/rasa-x/installation-and-setup/docker-compose-script/) to use docker compose setup instead. In that case you won't be installing package for `rasa-x` at all, and containers will communicate via REST API, which we always keep backward compatible.

If you still want to keep trying to use local mode, then please use separate venv for both `rasa` and `rasa-x`.

**Comment by kapoorh** [comment]
Hi @degiz ,

Thanks for an update. But in this case I'll have to run both the services differently, right now I run only rasa-x and action service.  It automatically starts rasa.  

I have to do this without docker. Still if I do it with docker or without it should be compatible in both the scenarios.

1. When I start rasa-x with - "rasa x" then it doesn't point to the latest model, everytime I go to the Rasa X UI and make it active.
2. I have to install rasa 1.8.0, how can I?
3. Why conf level decreases with new version?

Please let me know about these.

Thanks and Regards
Harsh

**Comment by hello-code** [comment]
@kapoorh 

`pip install  rasa-x==0.26.3 --extra-index-url https://pypi.rasa.com/simple`
----------------------------
rasa                       1.8.3
rasa-sdk                1.9.0
rasa-x                    0.26.3

**Comment by kapoorh** [comment]
Hi @hello-code 

Thanks for a reply. Solved my problem.

Thanks everyone :)

Regards
Harsh
