### ISSUE TITLE
Validate Data documentation issue

### ISSUE THREAD

**Issue by rohithch21** [RasaHQ/rasa#5499]
**Rasa version**: 1.6.1

**Rasa SDK version** (if used & relevant):1.6.1

**Rasa X version** (if used & relevant):

**Python version**:3.6.9

**Operating system** (windows, osx, ...):ubuntu18.04

**Issue**:I am currently using the rasa nlu component alone. My application involves a third party user uploading their nlu.md file. I would like to validate it. I am using rasa=1.6.1 As per the documentation,it says Validator class has from_files() method [ [https://rasa.com/docs/rasa/user-guide/validate-files/](https://rasa.com/docs/rasa/user-guide/validate-files/) ], but thats not the case when I checked the rasaHQ github page Latest rasa validator.py [https://github.com/RasaHQ/rasa/blob/master/rasa/validator.py](https://github.com/RasaHQ/rasa/blob/master/rasa/validator.py)

**Error (including full traceback)**:

 Traceback (most recent call last):
 File "valid_rasa.py", line 9, in <module>
 validator = Validator.from_files(
 AttributeError: type object 'Validator' has no attribute 'from_files'

**Command or request that led to error**:

 import logging
 from rasa import utils
 from rasa.core.validator import Validator

 logger = logging.getLogger(__name__)

1.  utils.configure_colored_logging('DEBUG')

 validator = Validator.from_files(
 nlu_data='data/nlu.md'
 )

 validator.verify_all()

**Content of configuration file (config.yml)** (if relevant):

**Content of domain file (domain.yml)** (if relevant):

**Comment by sara-tagger** [comment]
Thanks for the issue, @wochinge will get back to you about it soon!

###### You may find help in the [docs](https://rasa.com/docs/) and the [forum,](https://forum.rasa.com/) too 🤗

**Comment by wochinge** [comment]
@rohithch21 Thanks for brining this up! The documentation seems to be outdated here.
Instead you have to use `Validator.from_importer` which expects an instance of the importer class (https://rasa.com/docs/rasa/api/training-data-importers/) . By the way, you can also use the command line interface to validate the data (`rasa data validate`)

**Comment by wochinge** [comment]
related to https://github.com/RasaHQ/rasa/issues/6070
