### ISSUE TITLE
issue while i am running rasa run actions

### ISSUE THREAD

**Issue by tanveerahmed668** [RasaHQ/rasa#5507]
**Rasa version   **:  1.7.0 

**Rasa SDK version** (if used & relevant):

**Rasa X version** (if used & relevant):

**Python version**:        3.7.4

**Operating system** (windows, osx, ...):

**Issue**:

**Error (including full traceback)**:
```
Issue :  while i am running rasa run actions,I am getting stuck on it,so please guide how to solve this error.
![rasa](https://user-images.githubusercontent.com/57387188/77666810-6ac8fd80-6fa7-11ea-86ce-cd1836c0a9a5.png)


```

**Command or request that led to error**:
```

```

**Content of configuration file (config.yml)** (if relevant):
```yml

```

**Content of domain file (domain.yml)** (if relevant):
```yml

```

**Comment by sara-tagger** [comment]
Thanks for the issue, @tttthomasssss will get back to you about it soon!

###### You may find help in the [docs](https://rasa.com/docs/) and the [forum,](https://forum.rasa.com/) too 🤗

**Comment by tttthomasssss** [comment]
HI @tanveerahmed668, thanks very much for your error report. Could you provide some more details w.r.t. the issue you are experiencing? For example, is the process just stuck forever or crashes at some point?
