### ISSUE TITLE
Newlines Issue

### ISSUE THREAD

**Issue by raktes** [RasaHQ/rasa#5521]
**Rasa version**:
Rasa 1.8.2

**Python version**:
Python 3.6

**Operating system** 
Kubuntu

**Issue**:
When using the Response Selector as described in the rasa [Documentation](https://rasa.com/docs/rasa/user-guide/building-assistants/#build-faq-assistant), Newlines (```\n```) set in the responses.md File don't work and are just displayed as ```\n```. It seems the Backslash itself is getting escaped so that the String send to a Messanger is actually ```\\n```, which is then getting rendered as ```\n```. I only tested this with the Telegram Channel and with ```rasa shell``` but it might very well be a Problem when using other Channels as well. In addition the same Problem seems to appear when I don't put Quotation Marks around an Utter in the domain.yml.

**Comment by sara-tagger** [comment]
Thanks for the issue, @chkoss will get back to you about it soon!

###### You may find help in the [docs](https://rasa.com/docs/) and the [forum,](https://forum.rasa.com/) too 🤗

**Comment by wochinge** [comment]
hey @raktes , not sure if you saw, but we added it to our todo list. Thanks for bringing it up!

**Comment by raktes** [comment]
Ok, thanks for the update.

**Comment by m-vdb** [comment]
This issue has been fixed with https://github.com/RasaHQ/rasa/pull/5868 ✅
