### ISSUE TITLE
API get null response

### ISSUE THREAD

**Issue by aaronysl** [RasaHQ/rasa#5524]
I always got null response after I trained nlu model
`"response_selector":{"default":{"response":{"name":null,"confidence":0.0},"ranking":[],"full_retrieval_intent":null}
`
intent prediction is correct, but no response actions.
Appreciate if someone help me with this!!

**Comment by aaronysl** [comment]
FYI, I use luis migrated model

**Comment by sara-tagger** [comment]
Thanks for the question, our Github issue board is for **bugs and feature requests only,** though 😕
Please ask this question in the [forum✨](https://forum.rasa.com/c/rasa)

###### If you were describing a bug, please create a [report](https://github.com/RasaHQ/rasa/issues/new?labels=bug&template=bug_report.md) and fill out the template.

**Comment by sara-tagger** [comment]
Thanks for raising this issue, @closed will get back to you about it soon✨

###### Please also check out the [docs](https://rasa.com/docs/) and the [forum](https://forum.rasa.com/) in case your issue was raised there too 🤗
