### ISSUE TITLE
Sara Image not Loading on Docs

### ISSUE THREAD

**Issue by koaning** [RasaHQ/rasa#5526]
Probably just a minor hosting issue, but figured I'd mention it here. 

![image](https://user-images.githubusercontent.com/1019791/77912838-95f76980-7293-11ea-9c7c-a591fe6a4424.png)

**Comment by erohmensing** [comment]
Weird, looks fine on mine, which browser are you on?

**Comment by akelad** [comment]
@koaning do you still have this issue? If yes, which browser? i can't reproduce it
