### ISSUE TITLE
Investigate memory leak during training

### ISSUE THREAD

**Issue by dakshvar22** [RasaHQ/rasa#5550]
**Description of Problem**:
We fixed a [memory leak problem during prediction](https://github.com/RasaHQ/rasa/pull/5529) where `tf.data.Dataset` was repeatedly being called leading to increasing memory usage.
We need to investigate whether similar problem occurs during training as well.
We may remove `tf.data.Dataset` completely if we are able to show that similar memory leak happens during training.
It could also be possible that the problem is with using `tf.data.Dataset.from_generators` API. We may be better off using something like `tf.data.Dataset.from_tensor_slices`.

**Comment by Ghostvv** [comment]
Since we might plan to move to using `train_step` function in keras. Let's postpone this issue

**Comment by Ghostvv** [comment]
@dakshvar22 I believe this issue can be closed with `train_step` PR?

**Comment by dakshvar22** [comment]
Yes!

**Comment by Ghostvv** [comment]
let's close it now then
