### ISSUE TITLE
add end to end stories to example bots

### ISSUE THREAD

**Issue by erohmensing** [RasaHQ/rasa#5553]
the example bots here https://github.com/RasaHQ/rasa/tree/master/examples

Should have a `tests/e2e.md` as well as a step in their READMEs about testing the assistant.

**Comment by Archish27** [comment]
@erohmensing I would like to pick this up :smile: 
Working on it

**Comment by erohmensing** [comment]
Awesome! looks like e2e tests are actually automatically added to `tests/conversation_tests.md`, so that should be the file name 👍

**Comment by wochinge** [comment]
@Archish27 Are you still working on this?

**Comment by Archish27** [comment]
@wochinge Yes working on it. Previously added examples in the older format. Currently adding with YAML format will be rolling out PR soon. You can assign this task

**Comment by wochinge** [comment]
Awesome - let me know if you need help 👍🏻
