### ISSUE TITLE
Ignore_entities can also prevent slots from being autofilled

### ISSUE THREAD

**Issue by MichaelMarien** [RasaHQ/rasa#5561]
**Description of Problem**:
Currently the ignore_entities flag does not prevent entities that autofill a featurized slot to influence the behavior of the core. 

**Overview of the Solution**:
Add a possible field in the domain file that per intent decide if the ignored features need to be auto-filled.

**Examples** (if relevant):
The feature is to some extent implemented in 
https://github.com/botfront/rasa-addons/blob/master/rasa_addons/nlu/components/entities_filter.py
and was mentioned in the original feature request for ignore_entities https://github.com/RasaHQ/rasa/issues/2316

**Definition of Done**:
- [ ] Tests are added
- [ ] Feature described the docs
- [ ] Feature mentioned in the changlog

Alternatively, if this feature is not to be implemented for good reasons, I think we should clarify the reasoning as a reference (if this is already done, apologies, I could not find it).

**Comment by sara-tagger** [comment]
Thanks for submitting this feature request 🚀 @tabergma will get back to you about it soon! ✨

**Comment by tabergma** [comment]
@akelad What do you think?

**Comment by akelad** [comment]
sorry this got lost in my notifications. i would lean towards not doing this at the moment - @MichaelMarien could you describe your use case for this?

**Comment by MichaelMarien** [comment]
Hi @akelad thanks for the response. Use case is the following. We have quite a big bot already running (50-100 intents, 20-30 entities, 1000s of original stories). Now we want to add a new entity with an associated categorical slot to include new functionality. 

The entity values of this new slot are very commonly used words (like car, road, etc ...) that we definitely expect users to use in a lot of flows. However, they are totally irrelevant in all flows expect the new ones and are of course not included in the older stories (as the entity/slot does not exist yet).

We are very worried that if we include this entity + slot, the behavior of the bot will break in our older flows because the memoization policy will fail. One solution could be to start adding stories were this entity is filled in, but does not influence the conversation and let the ML policies learn this. However, this is quite a lot of work (moreover this scenario will appear again) and might still give suboptimal results in the existing flows if the ML policy makes mistakes.

**Comment by akelad** [comment]
@wochinge

**Comment by Ghostvv** [comment]
should be possible to do it in custom slot filling action after it is implemented: https://github.com/RasaHQ/rasa/issues/6267

**Comment by MichaelMarien** [comment]
@Ghostvv thanks for linking to #6267, it definitely solves this (and way more) - looks like a very good and powerful new feature.

**Comment by akelad** [comment]
Vova I guess we can close this issue then right?
