### ISSUE TITLE
Problem to load Spacy model 

### ISSUE THREAD

**Issue by templth** [RasaHQ/rasa#5562]
Hello,

I'm trying to initialize a Rasa project following these steps:

```
$ python3 -m venv --system-site-packages ./venv
$ source ./venv/bin/activate
$ pip3 install rasa[spacy]~=1.9.3
$ rasa --version
Rasa 1.9.3
```

Everything seems to be installed correctly.

Now I tried to load a Spacy model and got this error:

```
$ python3 -m spacy download en_core_web_md
(...)/venv/bin/python3: No module named spacy
```

Thanks for your help!
Thierry

**Comment by sara-tagger** [comment]
Thanks for the question, our Github issue board is for **bugs and feature requests only,** though 😕
Please ask this question in the [forum✨](https://forum.rasa.com/c/rasa)

###### If you were describing a bug, please create a [report](https://github.com/RasaHQ/rasa/issues/new?labels=bug&template=bug_report.md) and fill out the template.

**Comment by sara-tagger** [comment]
Thanks for the issue, @closed will get back to you about it soon!

###### You may find help in the [docs](https://rasa.com/docs/) and the [forum,](https://forum.rasa.com/) too 🤗
