### ISSUE TITLE
Unable to install rasa/rasa-x

### ISSUE THREAD

**Issue by animenon** [RasaHQ/rasa#5567]
**Python version**:
3.8.0

**Operating system** (windows, osx, ...): MAC OS

**Issue**:

Unable to install rasa in Python 3.8.0

**Error (including full traceback)**:
![image](https://user-images.githubusercontent.com/6907950/78333924-60f75980-75a8-11ea-8b9f-fed1cbc21cdc.png)

**Command or request that led to error**:
```
pip install rasa-x --extra-index-url https://pypi.rasa.com/simple
```
**Alternate**

Command -

    pip3 install rasa

Error -

```
Collecting tensorflow-addons>=0.7.1 (from rasa)
  ERROR: Could not find a version that satisfies the requirement tensorflow-addons>=0.7.1 (from rasa) (from versions: none)
ERROR: No matching distribution found for tensorflow-addons>=0.7.1 (from rasa)

```

Rasa Doesn't work on Python 3.8?

**Comment by sara-tagger** [comment]
Thanks for the issue, @rctatman will get back to you about it soon!

###### You may find help in the [docs](https://rasa.com/docs/) and the [forum,](https://forum.rasa.com/) too 🤗

**Comment by dliedke** [comment]
Exactly same issue happening with Windows 10 and latest Python 3.8.2 (04/14/2020). Only Python 3.7.7 works fine.

**Comment by garmianov** [comment]
Same issue on Mac OS 10.15.5 and Python 3.8.2

**Comment by erohmensing** [comment]
You can see on the [installation page](https://rasa.com/docs/rasa/user-guide/installation/#) that Rasa Open source currently requires python 3.6 or 3.7. Rasa open source is a dependency of Rasa X, so this restriction extends to Rasa X.

**Comment by santhosh432** [comment]
> You can see on the [installation page](https://rasa.com/docs/rasa/user-guide/installation/#) that Rasa Open source currently requires python 3.6 or 3.7. Rasa open source is a dependency of Rasa X, so this restriction extends to Rasa X.

But it has shown that it supports 3.8

![image](https://user-images.githubusercontent.com/28806687/107028653-e0127b00-67d3-11eb-8822-d5b7d6afa332.png)

**Comment by erohmensing** [comment]
Yes, but when I made that comment in June of last year, it was a correct statement. Python 3.8 is supported as of Rasa 2.0.

**Comment by KheireddineAzzez** [comment]
The Button of GitHub Integration in Rasa-X UI it doesn't appear For me , I have installed Rasa x from pip install ..... ? what is the problem!
