### ISSUE TITLE
Rasa domain model

### ISSUE THREAD

**Issue by degiz** [RasaHQ/rasa#5572]
**Problem** Among frontend, Rasa X backend, Rasa and product owner / designers are many different names for the same thing. Reasons for that are

there is no domain model / ubiquitous language which we use some names are not optimal the code is not organized along an established domain model

**Goal** The ultimate goal is to have a single [Domain Model](https://en.wikipedia.org/wiki/Domain_model) among all repos/docs at Rasa.

**Implementation** This could be done in steps:

1.  Analyse current situation and come up with the Domain model
2.  Split the task and create separate issues for all repos (Rasa Open Source, SDK, Rasa X etc)

**Required code changes**

*   revisiting endpoints names.
*   rename classes in the code to reflect their meaning in the Rasa domain. Example: most (also developers new to Rasa) will understand what the term "conversation history" mean. But how many would know right away what 'tracker' means?

**Comment by tmbo** [comment]
I think there was already an issue from @wochinge for this one, can we link / replace that one?

**Comment by wochinge** [comment]
That's the issue I created a while back: https://github.com/RasaHQ/roadmap/issues/649 . I'll add the relevant parts to this issue and close it
