### ISSUE TITLE
Review existing `hacks` inside stories

### ISSUE THREAD

**Issue by degiz** [RasaHQ/rasa#5573]
Review features like:
- checkpoints
- `OR` statements
- `NOT` intents
- `ignore_entities`

This features are workarounds, but still simplify writing the stories.

@akelad will collect the use cases in one document so that we can review them and possibly find a better solution.

**Comment by akelad** [comment]
doc lives here: https://docs.google.com/document/d/1ytIjcZ09B52Se1Ta4Jk4b6G9k1OpxgYnxu0UfEPma3Y/edit#

**Comment by tmbo** [comment]
@akelad is there still something you want to do here or can we unassign you?

**Comment by akelad** [comment]
unassigned myself, i'm done with my part :D

**Comment by N-Olbert** [comment]
Is this an issue regarding the internal implementation of these 'hacks' or this more an investigation which of those features can be deprecated? Just curious if we should continue to use checkpoints in our stories or not...

**Comment by degiz** [comment]
hey @N-Olbert 

it's the second point from your question. We're thinking whether we can eliminate these hacks or no 😄 

> Just curious if we should continue to use checkpoints in our stories or not...

Currently both `OR` and `Checkpoint` made it into the new `2.0 YAML Format`, so you can still use it.

**Comment by m-vdb** [comment]
removing milestone because we have kept support for all of these hacks (confirmed by @degiz ) and we haven't found better alternative yet.

**Comment by akelad** [comment]
hm, there's definitely a lot of open points in that google doc - we're discussing this with Tom/Tobi on Monday morning

**Comment by wochinge** [comment]
@akelad Can this be closed?

**Comment by amn41** [comment]
Some version of this needs to exist in the backlog bc we should absolutely aim to get rid of all of those things.

**Comment by m-vdb** [comment]
@amn41 should it be somewhere other than Rasa Open Source backlog? (e.g. Product ice box)

**Comment by amn41** [comment]
yes that sounds good

**Comment by m-vdb** [comment]
Done
