### ISSUE TITLE
Make Retrieval Actions triggerable via slash command or equivalent

### ISSUE THREAD

**Issue by kevinthemself** [RasaHQ/rasa#5576]
**Description of Problem**:

Retrieval actions are really nice to use for simple FAQ stories, but for cases where a bot has a "menu" of FAQs to browse, or the bot requires need of triggering retrieval actions via buttons on-the-fly, retrieval actions are not capable of being triggered in the same way as normal intents via a slash command.

Another example is trying to trigger a retrieval action with a slash command – there's currently no way to do it with 100% accuracy, like other intents. Currently, in order to get that behavior, you'd have to use an example from the response selector training data as the payload of the button, which may not be ideal in some cases.

A more in-depth forum post is [here](https://forum.rasa.com/t/retrieval-actions-fallback-buttons-and-reverting-utterance/25312)

**Overview of the Solution**:

Allow for retrieval actions to be triggered via a directly predicted default action (like `/restart` or `/back`) with hard-coded entities/slots * example button payload: `/retrieval

 {"intent": "faq", "name": "help"} 

`

Would love to hear your thoughts.

**Comment by sara-tagger** [comment]
Thanks for submitting this feature request 🚀 @melindaloubser1 will get back to you about it soon! ✨

**Comment by sara-tagger** [comment]
Thanks for submitting this feature request 🚀 @TyDunn will get back to you about it soon! ✨

**Comment by melindaloubser1** [comment]
This doesn't address everything you've mentioned, but the full retrieval intent name was made available in the tracker in 1.9 - see https://github.com/RasaHQ/rasa/pull/5432.

**Comment by pixpack** [comment]
I'm working on this issue right now in my own bot. For now I've found a workaround solution to make both fallabacks work, but unfortunately you can't use buttons with / - prefixed intents. I'm slowly working towards a complete solution so I might share the code soon.

**Comment by ortsaCniveK** [comment]
@melindaloubser1 That should allow for me to use the `tracker.last_message` property for the fallback policy, though it would still be nice to be able to use the full `intent/response` name in some way

**Comment by melindaloubser1** [comment]
@ortsaCniveK you mean use `intent/response` name in a story?

**Comment by ortsaCniveK** [comment]
No, like using the intent/response name as a button payload.  I have some FAQ content I'd like to have available as help menus

**Comment by melindaloubser1** [comment]
For anyone who needs a workaround in the meantime, this approach works for just returning the response - so it's not the same as having the intent in the dialogue history.

Add an entity & slot for retrieval intent name, then use the slot in a custom action that manually calls the correct response selector utterance:

domain.yml
```
intents:
- trigger_response_selector
entities:
- retrieval_intent
slots:
  retrieval_intent:
    type: text
    influence_conversation: false
actions:
- action_trigger_response_selector
responses:
  utter_chitchat/ask_whatisrasa:
  - text: Rasa is xyz
  utter_options:
  - buttons:
      - title: install rasa
        payload: /install_rasa
      - title: get more info on rasa
        payload: /trigger_response_selector{"retrieval_intent":"chitchat/ask_whatisrasa"}
  ```
rules.yml
```
rules:
- rule: Trigger response selector from button payload
  steps:
  - intent: trigger_response_selector
  - action: action_trigger_response_selector
```

actions.py
```
class ActionTriggerResponseSelector(Action):
    """Returns the chitchat utterance dependent on the intent"""

    def name(self) -> Text:
        return "action_trigger_response_selector"

    def run(
        self,
        dispatcher: CollectingDispatcher,
        tracker: Tracker,
        domain: Dict[Text, Any],
    ) -> List[EventType]:
        retrieval_intent = tracker.get_slot("retrieval_intent")
        if retrieval_intent:
            dispatcher.utter_message(template = f"utter_{retrieval_intent}"

        return [SlotSet("retrieval_intent", None)]
   ```

**Comment by georgebrianb** [comment]
Hello, are there any updates on this matter?

**Comment by bradyneal** [comment]
Any chance there are plans to fix this soon?

**Comment by TyDunn** [comment]
@bradyneal I think we will struggle to get to it soon unfortunately. Maybe you would be willing to open a PR for it?

**Comment by bradyneal** [comment]
Gotcha 👍. Unlikely any time soon on my end either haha (just going to use Melinda's workaround)

**Comment by b-quachtran** [comment]
@TyDunn Do you know if this'll be in-scope for 3.1?

**Comment by TyDunn** [comment]
I'm not sure about the scope of 3.1 yet
