### ISSUE TITLE
Lookup table doesn't work with language without spaces.

### ISSUE THREAD

**Issue by tomgun132** [RasaHQ/rasa#5580]
**Rasa version:**
v1.9.3
**Python version:**
3.7
**Operating system:**
Windows

**Description of Problem**:
Lookup table doesn't work out-of-the box to language that doesn't have space to separate words in a sentence. I'm working on chatbot for Japanese language and if I want to use lookup table, I need to pre-process the training data, lookup tables, and the input to the chatbot to have spaces, then it works without problem. However, this is troublesome to use if I want to do interactive learning in windows shell since I need to open another python shell to tokenizes and add space to the input, then copy the output of the tokenizer to the interactive learning window. More info is in the forum thread that I created here: https://forum.rasa.com/t/lookup-table-for-language-that-has-no-space-to-separate-words/26874

**Overview of the Solution**:
According to the reply, lookup table needs to be processed with the tokenizer in the NLU pipeline before adding the table to the regex patterns. As I saw into the regex_featurizer code, the string that needs to be matched with the regex patterns need to already have spaces as well. Another possible solution is to have the NLU pipeline to check whether the training data has space or not and pass this information to regex featurizer to not add word boundaries to the regex pattern creation. 

**Blockers** (if relevant):
If the string that needs to be matched with regex pattern is given spaces, while the original string in the training data is left as it is, I wonder if it will make the featurizer fails to get the vector due to mismatching of entity start and end index with regex matcher, since the the entity index is created based on the original string with no spaces.

**Definition of Done**:
The lookup table feature works with language with no-spaces without needing any pre-processing in the training data, lookup tables, and the chatbot input.

This might not be relevant for some languages, but if it can be fixed, it might help other users with similar problem. I will look into the code when I have some free time, but I can't promise anything. Thank you

**Comment by sara-tagger** [comment]
Thanks for submitting this feature request 🚀 @tttthomasssss will get back to you about it soon! ✨

**Comment by sara-tagger** [comment]
Thanks for submitting this feature request 🚀 @tmbo will get back to you about it soon! ✨

**Comment by tttthomasssss** [comment]
Hi @tomgun132, thanks very much for submitting this issue as multilingual support is very important to us.

Let me know if you have the time to create a PR yourself for this as it would be a really cool feature to add.

**Comment by tomgun132** [comment]
Hi @tttthomasssss, Thanks for replying.

I've seen the code of `RegexFeaturizer` on how it process the lookup tables into regex patterns and how it matches the patterns to create feature vector out of the regex patterns. I one line that affect the process for Japanese language.

On `regex_featurizer.py`: https://github.com/RasaHQ/rasa/blob/master/rasa/nlu/featurizers/sparse_featurizer/regex_featurizer.py#L171. This line assumes that the pattern will have word boundaries surrounding the entities and it doesn't work with Japanese language or any language without spaces to separate words. Removing the `\b` will make it works for Japanese language, but I'm not sure for other languages. [Testing it here](https://regex101.com/) poses no problem for English, but I'm currently focusing on Japanese language first and after it's done, I will move on to English to see whether removing `\b` on generating regex pattern from lookup tables will affect English language.

**Comment by koernerfelicia** [comment]
Hi @tomgun132, this issue was actually corrected in version 2.2.0 by [this PR](https://github.com/RasaHQ/rasa/pull/7422).
