### ISSUE TITLE
ModuleNotFoundError: Cannot find class 'LexicalSyntacticFeaturizer' from global namespace. Please check that there is no typo in the class name and that you have imported the class into the global namespace.

### ISSUE THREAD

**Issue by Asma-droid** [RasaHQ/rasa#5581]
Hi all,

I have traied to use the latest rasa version (1.9.5) and i have obtained this error.

ModuleNotFoundError: Cannot find class 'LexicalSyntacticFeaturizer' from global namespace. Please check that there is no typo in the class name and that you have imported the class into the global namespace.

my config file is as follows 

language: fr

pipeline:
  - name: WhitespaceTokenizer
  - name: RegexFeaturizer
  - name: LexicalSyntacticFeaturizer
  - name: CountVectorsFeaturizer
  - name: CountVectorsFeaturizer
    analyzer: "char_wb"
    min_ngram: 1
    max_ngram: 4
  - name: DIETClassifier
    epochs: 100
  - name: EntitySynonymMapper
  - name: ResponseSelector
    epochs: 100

policies:
  - name: "MemoizationPolicy"
    max_history: 3
  - name: "FallbackPolicy"
    nlu_threshold: 0.7
    core_threshold: 0.7
  - name: MappingPolicy

**Comment by sara-tagger** [comment]
Thanks for raising this issue, @rgstephens will get back to you about it soon✨

###### Please also check out the [docs](https://rasa.com/docs/) and the [forum](https://forum.rasa.com/) in case your issue was raised there too 🤗

**Comment by sara-tagger** [comment]
Thanks for the issue, @dakshvar22 will get back to you about it soon!

###### You may find help in the [docs](https://rasa.com/docs/) and the [forum,](https://forum.rasa.com/) too 🤗

**Comment by dakshvar22** [comment]
@Asma-droid I can't replicate the error on my side with the same version of Rasa you mentioned. Can you try in a clean virtual environment and see if the issue persists?

**Comment by tmbo** [comment]
cant reproduce
