### ISSUE TITLE
rasa-production_1  | Could not fetch runtime config from server at 'http://rasa-x:5002/api/config?token=token_string'. Exiting.

### ISSUE THREAD

**Issue by mandaarp** [RasaHQ/rasa#5582]
**Rasa version**: 1.9.5

**Rasa SDK version** (if used & relevant):

**Rasa X version** (if used & relevant): 0.27.4

**Python version**: 3.7

**Operating system** (windows, osx, ...): osx

**Issue**:
1. Follow steps on https://rasa.com/docs/rasa-x/installation-and-setup/docker-compose-manual/
2. Launch Rasa X web page
3. Click on 'Models'
4. Observe following errors in docker-compse logs:
```
rasa-worker_1      | Starting Rasa X in production mode... 🚀
rasa-worker_1      | Could not fetch runtime config from server at 'http://rasa-x:5002/api/config?token=token_string'. Exiting.
rasa-production_1  | Starting Rasa X in production mode... 🚀
rasa-production_1  | Could not fetch runtime config from server at 'http://rasa-x:5002/api/config?token=token_string'. Exiting.
```
**Error (including full traceback)**:
```
rasa-worker_1      | Starting Rasa X in production mode... 🚀
rasa-worker_1      | Could not fetch runtime config from server at 'http://rasa-x:5002/api/config?token=token_string'. Exiting.
rasa-production_1  | Starting Rasa X in production mode... 🚀
rasa-production_1  | Could not fetch runtime config from server at 'http://rasa-x:5002/api/config?token=token_string'. Exiting.
rasa-worker_1      | 2020-04-06 01:50:13 DEBUG    rasa.cli.x  - Failed to get a proper response from remote server. Status Code: 401. Response: '{"reasons":["Authorization header not present."],"exception":"Unauthorized"}'
rasa-production_1  | 2020-04-06 01:50:13 DEBUG    rasa.cli.x  - Failed to get a proper response from remote server. Status Code: 401. Response: '{"reasons":["Authorization header not present."],"exception":"Unauthorized"}'

```

**Command or request that led to error**:
```
Browsing to http://localhost/models (models endpoint on Rasa X)
```

**Content of configuration file (config.yml)** (if relevant):
```yml

```

**Content of domain file (domain.yml)** (if relevant):
```yml

```
**Content of .env file
```
RASA_X_VERSION=0.27.4
RASA_VERSION=1.9.5
RASA_X_DEMO_VERSION=0.27.4
RASA_TOKEN="token_string"
RASA_X_TOKEN="token_string"
PASSWORD_SALT="token_string"
JWT_SECRET="token_string"
RABBITMQ_PASSWORD="rabbitmq-password"
DB_PASSWORD="postgres-password"
REDIS_PASSWORD="redis-password"
```

**Comment by sara-tagger** [comment]
Thanks for raising this issue, @wochinge will get back to you about it soon✨

###### Please also check out the [docs](https://rasa.com/docs/) and the [forum](https://forum.rasa.com/) in case your issue was raised there too 🤗

**Comment by sara-tagger** [comment]
Thanks for the issue, @Ghostvv will get back to you about it soon!

###### You may find help in the [docs](https://rasa.com/docs/) and the [forum,](https://forum.rasa.com/) too 🤗

**Comment by wochinge** [comment]
@mandaarp Mhm, that seems some tokens weren't set correctly. Did you specify `RASA_TOKEN` and `RASA_X_TOKEN` and configure the `environments.yml` correctly?

**Comment by mandaarp** [comment]
Here is my environments.yml file (per the posted documentation)...
```iml
rasa:
  production:
    url: http://rasa-production:5005
    token: ${RASA_TOKEN}
  worker:
    url: http://rasa-worker:5005
    token: ${RASA_TOKEN}
```

**Comment by wochinge** [comment]
Are `credentials` and `endpoints.yml` present and readable by Rasa X? 🤔  Best post the output of `ls -al` in the your Rasa X installation directory.

**Comment by mandaarp** [comment]
Here is the output of rasa x installation directory:
```
drwxr-xr-x  16 username  staff   512B Apr  9 17:23 ./
drwxr-xr-x   9 username  staff   288B Apr  9 10:54 ../
-rw-r--r--@  1 username  staff   6.0K Apr  9 17:19 .DS_Store
-rw-r--r--   1 username  staff   288B Apr  9 17:22 .env
drwxrwx---   2 username  staff    64B Apr  9 09:15 auth/
drwxrwx---   2 username  staff    64B Apr  9 09:15 certs/
drwxrwx---   2 username  staff    64B Apr  9 17:23 credentials/
-rwxrwx---   1 username  staff    32B Apr  9 17:22 credentials.yml*
drwxrwx---   3 username  staff    96B Apr  9 17:26 db/
-rwxrwx---   1 username  staff   4.1K Apr  2 04:47 docker-compose.yml*
-rwxrwx---   1 username  staff   628B Apr  9 17:23 endpoints.yml*
-rwxrwx---   1 username  staff   150B Apr  9 17:23 environments.yml*
drwxrwx---   2 username  staff    64B Apr  9 09:15 logs/
drwxrwx---   2 username  staff    64B Apr  9 09:15 models/
-rwxrwx---   1 username  staff   3.1K Apr  2 04:47 rasa_x_commands.py*
drwxrwx---   3 username  staff    96B Apr  9 17:24 terms/
```

**Comment by wochinge** [comment]
That actually looks 🤔 Can you please also share the `rasa-x` logs?

**Comment by manoj2270** [comment]
Hi, am also facing the same issue. is there any solution for this?
my rasa-x logs:

rasa-production_1  | Starting Rasa X in production mode... 🚀
rasa-production_1  | Could not fetch runtime config from server at 'http://rasa-x:5002/api/config?token=OIMZ9HoySJ+E0yNxFgjmkw=='. Exiting.
rasa-worker_1      | Starting Rasa X in production mode... 🚀
rasa-worker_1      | Could not fetch runtime config from server at 'http://rasa-x:5002/api/config?token=OIMZ9HoySJ+E0yNxFgjmkw=='. Exiting.
rasa_rasa-production_1 exited with code 1
rasa_rasa-worker_1 exited with code 1
nginx_1            | 192.168.99.1 - - [20/May/2020:09:31:56 +0000] "GET /api/projects/default/git_repositories/1/status HTTP/1.1" 200 223 "http://192.168.99.100/models" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/81.0.4044.138 Safari/537.36"
nginx_1            | 192.168.99.1 - - [20/May/2020:09:32:58 +0000] "GET /api/projects/default/git_repositories/1/status HTTP/1.1" 200 223 "http://192.168.99.100/models" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/81.0.4044.138 Safari/537.36"
nginx_1            | 192.168.99.1 - - [20/May/2020:09:34:01 +0000] "GET /api/projects/default/git_repositories/1/status HTTP/1.1" 200 223 "http://192.168.99.100/models" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/81.0.4044.138 Safari/537.36"
nginx_1            | 192.168.99.1 - - [20/May/2020:09:35:00 +0000] "GET /api/projects/default/git_repositories/1/status HTTP/1.1" 200 223 "http://192.168.99.100/models" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/81.0.4044.138 Safari/537.36"
nginx_1            | 192.168.99.1 - - [20/May/2020:09:36:01 +0000] "GET /api/projects/default/git_repositories/1/status HTTP/1.1" 200 223 "http://192.168.99.100/models" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/81.0.4044.138 Safari/537.36"
nginx_1            | 192.168.99.1 - - [20/May/2020:09:37:02 +0000] "GET /api/projects/default/git_repositories/1/status HTTP/1.1" 200 223 "http://192.168.99.100/models" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/81.0.4044.138 Safari/537.36"
rasa-worker_1      | Starting Rasa X in production mode... 🚀
rasa-worker_1      | Could not fetch runtime config from server at 'http://rasa-x:5002/api/config?token=OIMZ9HoySJ+E0yNxFgjmkw=='. Exiting.
rasa-production_1  | Starting Rasa X in production mode... 🚀
rasa-production_1  | Could not fetch runtime config from server at 'http://rasa-x:5002/api/config?token=OIMZ9HoySJ+E0yNxFgjmkw=='. Exiting.
rasa_rasa-worker_1 exited with code 1
rasa_rasa-production_1 exited with code 1
rasa-x_1           | Run time of job "track_project_status (trigger: interval[1:00:00], next run at: 2020-05-20 09:07:22 UTC)" was missed by 0:16:49.770518
nginx_1            | 192.168.99.1 - - [20/May/2020:09:38:03 +0000] "GET /api/projects/default/git_repositories/1/status HTTP/1.1" 200 223 "http://192.168.99.100/models" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/81.0.4044.138 Safari/537.36"
rasa-x_1           | Run time of job "GitService.run_background_synchronization (trigger: cron[minute='*'], next run at: 2020-05-20 09:40:00 UTC)" was missed by 0:00:01.242532
nginx_1            | 192.168.99.1 - - [20/May/2020:09:39:05 +0000] "GET /api/projects/default/git_repositories/1/status HTTP/1.1" 200 223 "http://192.168.99.100/models" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/81.0.4044.138 Safari/537.36"
nginx_1            | 192.168.99.1 - - [20/May/2020:09:40:07 +0000] "GET /api/projects/default/git_repositories/1/status HTTP/1.1" 200 223 "http://192.168.99.100/models" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/81.0.4044.138 Safari/537.36"
rasa-x_1           | Run time of job "GitService.run_background_synchronization (trigger: cron[minute='*'], next run at: 2020-05-20 09:41:00 UTC)" was missed by 0:00:01.224569
nginx_1            | 192.168.99.1 - - [20/May/2020:09:41:05 +0000] "GET /api/projects/default/git_repositories/1/status HTTP/1.1" 200 223 "http://192.168.99.100/models" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/81.0.4044.138 Safari/537.36"
nginx_1            | 192.168.99.1 - - [20/May/2020:09:41:38 +0000] "POST /api/projects/default/models/jobs HTTP/1.1" 500 220 "http://192.168.99.100/models" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/81.0.4044.138 Safari/537.36"
nginx_1            | 192.168.99.1 - - [20/May/2020:09:42:06 +0000] "GET /api/projects/default/git_repositories/1/status HTTP/1.1" 200 223 "http://192.168.99.100/models" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/81.0.4044.138 Safari/537.36"
rasa-production_1  | Starting Rasa X in production mode... 🚀
rasa-production_1  | Could not fetch runtime config from server at 'http://rasa-x:5002/api/config?token=OIMZ9HoySJ+E0yNxFgjmkw=='. Exiting.
rasa-worker_1      | Starting Rasa X in production mode... 🚀
rasa-worker_1      | Could not fetch runtime config from server at 'http://rasa-x:5002/api/config?token=OIMZ9HoySJ+E0yNxFgjmkw=='. Exiting.
rasa_rasa-production_1 exited with code 1
rasa_rasa-worker_1 exited with code 1
nginx_1            | 192.168.99.1 - - [20/May/2020:09:43:07 +0000] "GET /api/projects/default/git_repositories/1/status HTTP/1.1" 200 223 "http://192.168.99.100/models" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/81.0.4044.138 Safari/537.36"
nginx_1            | 192.168.99.1 - - [20/May/2020:09:44:08 +0000] "GET /api/projects/default/git_repositories/1/status HTTP/1.1" 200 222 "http://192.168.99.100/models" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/81.0.4044.138 Safari/537.36"
nginx_1            | 192.168.99.1 - - [20/May/2020:09:45:10 +0000] "GET /api/projects/default/git_repositories/1/status HTTP/1.1" 200 223 "http://192.168.99.100/models" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/81.0.4044.138 Safari/537.36"
nginx_1            | 192.168.99.1 - - [20/May/2020:09:46:09 +0000] "GET /api/projects/default/git_repositories/1/status HTTP/1.1" 200 222 "http://192.168.99.100/models" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/81.0.4044.138 Safari/537.36"
nginx_1            | 192.168.99.1 - - [20/May/2020:09:47:12 +0000] "GET /api/projects/default/git_repositories/1/status HTTP/1.1" 200 223 "http://192.168.99.100/models" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/81.0.4044.138 Safari/537.36"
nginx_1            | 192.168.99.1 - - [20/May/2020:09:48:11 +0000] "GET /api/projects/default/git_repositories/1/status HTTP/1.1" 200 223 "http://192.168.99.100/models" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/81.0.4044.138 Safari/537.36"
rasa-worker_1      | Starting Rasa X in production mode... 🚀
rasa-worker_1      | Could not fetch runtime config from server at 'http://rasa-x:5002/api/config?token=OIMZ9HoySJ+E0yNxFgjmkw=='. Exiting.
rasa_rasa-worker_1 exited with code 1
rasa-production_1  | Starting Rasa X in production mode... 🚀
rasa-production_1  | Could not fetch runtime config from server at 'http://rasa-x:5002/api/config?token=OIMZ9HoySJ+E0yNxFgjmkw=='. Exiting.
rasa_rasa-production_1 exited with code 1
rasa-worker_1      | Starting Rasa X in production mode... 🚀
rasa-worker_1      | Could not fetch runtime config from server at 'http://rasa-x:5002/api/config?token=OIMZ9HoySJ+E0yNxFgjmkw=='. Exiting.
rasa_rasa-worker_1 exited with code 1
rasa-production_1  | Starting Rasa X in production mode... 🚀
rasa-production_1  | Could not fetch runtime config from server at 'http://rasa-x:5002/api/config?token=OIMZ9HoySJ+E0yNxFgjmkw=='. Exiting.

**Comment by lqzmforer** [comment]
the same issue

**Comment by wochinge** [comment]
Weird, Rasa X keeps on restarting 🤔 Could you please set an environment variable `DEBUG_MODE` to `true` for Rasa X and check the logs again? Some crucial piece seems to be missing from the logs 🤔

**Comment by kad-klaasr** [comment]
Hi, also facing the same problem here. Using the newest docker compose file of rasa-x version 0.28.5 

after a while I get the same error messages:
`rasa-worker_1      | Starting Rasa X in production mode... 🚀
rasa-worker_1      | Could not fetch runtime config from server at 'http://rasa-x:5002/api/config?token=gq5kh1eP9LAh3B3rWLYq+g=='. Exiting.
rasa-production_1  | Starting Rasa X in production mode... 🚀
rasa-production_1  | Could not fetch runtime config from server at 'http://rasa-x:5002/api/config?token=gq5kh1eP9LAh3B3rWLYq+g=='. Exiting.`



Also when i click on "train" in the rasa-x UI I get the following error:
`rasa-x_1           | ERROR:rasax.community.api.blueprints.models:Cannot connect to host rasa-worker:5005 ssl:default [Connection refused]`

then in the UI it says "Nothing has changed" with a button "See latest model". When i click on that I get the following error: 
`rasa-x_1           | Exception occurred while handling uri: 'http://localhost/api/projects/default/models?limit=1&offset=0'
rasa-x_1           | Traceback (most recent call last):
rasa-x_1           |   File "/usr/local/lib/python3.7/site-packages/aiohttp/connector.py", line 936, in _wrap_create_connection
rasa-x_1           |     return await self._loop.create_connection(*args, **kwargs)  # type: ignore  # noqa
rasa-x_1           |   File "uvloop/loop.pyx", line 1974, in create_connection
rasa-x_1           |   File "uvloop/loop.pyx", line 1951, in uvloop.loop.Loop.create_connection
rasa-x_1           | ConnectionRefusedError: [Errno 111] Connection refused
rasa-x_1           |
rasa-x_1           | The above exception was the direct cause of the following exception:
rasa-x_1           |
rasa-x_1           | Traceback (most recent call last):
rasa-x_1           |   File "/usr/local/lib/python3.7/site-packages/sanic/app.py", line 976, in handle_request
rasa-x_1           |     response = await response
rasa-x_1           |   File "/usr/local/lib/python3.7/site-packages/rasax/community/api/decorators.py", line 205, in decorated_function
rasa-x_1           |     return await await_and_return_response(args, kwargs, request)
rasa-x_1           |   File "/usr/local/lib/python3.7/site-packages/rasax/community/api/decorators.py", line 135, in await_and_return_response
rasa-x_1           |     response = await response
rasa-x_1           |   File "/usr/local/lib/python3.7/site-packages/rasax/community/api/blueprints/models.py", line 47, in get_models
rasa-x_1           |     project_id, limit, offset, tag
rasa-x_1           |   File "/usr/local/lib/python3.7/site-packages/rasax/community/services/model_service.py", line 727, in get_models
rasa-x_1           |     minimum_compatible_version = await self.minimum_compatible_version()
rasa-x_1           |   File "/usr/local/lib/python3.7/site-packages/rasax/community/services/model_service.py", line 129, in minimum_compatible_version
rasa-x_1           |     info = await stack_service.version()
rasa-x_1           |   File "/usr/local/lib/python3.7/site-packages/rasax/community/services/stack_service.py", line 99, in version
rasa-x_1           |     timeout=timeout_in_seconds,
rasa-x_1           |   File "/usr/local/lib/python3.7/site-packages/aiohttp/client.py", line 483, in _request
rasa-x_1           |     timeout=real_timeout
rasa-x_1           |   File "/usr/local/lib/python3.7/site-packages/aiohttp/connector.py", line 523, in connect
rasa-x_1           |     proto = await self._create_connection(req, traces, timeout)
rasa-x_1           |   File "/usr/local/lib/python3.7/site-packages/aiohttp/connector.py", line 859, in _create_connection
rasa-x_1           |     req, traces, timeout)
rasa-x_1           |   File "/usr/local/lib/python3.7/site-packages/aiohttp/connector.py", line 1004, in _create_direct_connection
rasa-x_1           |     raise last_exc
rasa-x_1           |   File "/usr/local/lib/python3.7/site-packages/aiohttp/connector.py", line 986, in _create_direct_connection
rasa-x_1           |     req=req, client_error=client_error)
rasa-x_1           |   File "/usr/local/lib/python3.7/site-packages/aiohttp/connector.py", line 943, in _wrap_create_connection
rasa-x_1           |     raise client_error(req.connection_key, exc) from exc
rasa-x_1           | aiohttp.client_exceptions.ClientConnectorError: Cannot connect to host rasa-production:5005 ssl:default [Connection refused]`

**Comment by kad-klaasr** [comment]
I think i know what the problem is... I am using spacy and this needs to be run on the docker images on build:
```
$ pip install rasa[spacy]
$ python -m spacy download en_core_web_md
$ python -m spacy link en_core_web_md en
```
This should happen in a dockerFile but im still trying to get it to work....

**Comment by ArVar** [comment]
I have the same problem with identical output. I use the latest images and had the same setup as described by the author.
Which additional information do you need? Maybe I can provide them.

**Comment by wochinge** [comment]
> I use the latest images 

Do you mean with the `latest` tag? Could you please try with pinned versions? And which OS / deployment variant did you choose?

**Comment by kubhaniri** [comment]
I'm facing the same issue with identical output. I use the latest images and had the same setup as described by the author.
These are the version i used: 
RASA_X_VERSION=0.32.2
RASA_X_DEMO_VERSION=0.32.2
RASA_VERSION=1.10.12

**Comment by robynbitner** [comment]
I'm having the same issue. Any updates on how to fix it?

**Comment by liniribeiro** [comment]
I'm having the same issue.

**Comment by meghaggarwal** [comment]
Same issue...

**Comment by cianiandreadev** [comment]
I don't understand why this issue is closed.
Is this being fixed?
I have the same issue.

**Comment by wochinge** [comment]
Which Rasa X / Rasa Open Source versions are you using and how did you deploy? How much disk space does your machine have (should be at least 50 GiB)? @RasaHQ/practice-cdd Could you please have a look at this? 🙌🏻

**Comment by cianiandreadev** [comment]
Ho @wochinge ,

I am using the latetest of both
(Rasax: 0.38.1, rasa: 2.4.3, rasa-x-demo: 0.38.0)

Free space yes. Aroud 150GB, 16GB RAM

**Comment by cianiandreadev** [comment]
I finally solved the issue:
In my case I went in to the db volume and deleted everything.
That seems to have solved the issue.
I hope it helps someone else. 🙂

**Comment by chdorner** [comment]
I tried to reproduce with the following `.env`:

```
RASA_X_VERSION=0.39.0
RASA_VERSION=2.5.0
RASA_X_DEMO_VERSION=0.38.0
RASA_TOKEN=secret
RASA_X_TOKEN=secret
PASSWORD_SALT=secret
JWT_SECRET=secret
RABBITMQ_PASSWORD=secret
DB_PASSWORD=secret
REDIS_PASSWORD=secret
RASA_TELEMETRY_ENABLED=false
```

And I'm getting the same initial logs from `rasa-production` and `rasa-worker` (`Could not fetch runtime config from server at 'http://rasa-x:5002/api/config?token=secret'. Exiting.`).
However, once all containers are properly up and running everything is working fine.

Judging from @cianiandreadev's comment, it might have been that then `db` container wasn't able to start successfully, which would then lead to the Rasa X containers not coming up properly.

Can somebody who's currently experiencing this issue post the output of `docker-compose ps`?
