### ISSUE TITLE
Update release script to support pre-releases

### ISSUE THREAD

**Issue by tabergma** [RasaHQ/rasa#5583]
**Description of Problem**:
If you want to tag a pre-release the release script does not accept, for example, the version number `1.10.0a1`. It just supports `1.10.0-alpha1`. Also the release script deletes all changelog files and update the `CHANGELOG.rst` file. This should not happen on a pre-release. We want to keep those updates for the next minor release.

**Overview of the Solution**:
Add support for pre-release versions, such as `1.10.0a1`.
Skip updating the `CHANGELOG.rst` file for pre-releases.

**Comment by m-vdb** [comment]
@tabergma I'm taking a look at this one and I don't see what you mean by "it just supports 1.10.0-alpha1", because to me, it doesn't even support this:

https://github.com/RasaHQ/rasa/blob/c4d5302e3e9d6d4f442d15b42f1ad585f0d90d88/scripts/release.py#L33-L37

**Comment by tabergma** [comment]
When you execute `make release` it ask you for the next version
```
? What is the version number you want to release ('major', 'minor', 'patch' or valid version number)?
```
If you type in 1.10.0-alpha1, it will fail.

**Comment by m-vdb** [comment]
ok so it doesn't work at all for alpha. I was confused by what you wrote in the desc, because you said that "It just supports 1.10.0-alpha1"

**Comment by tabergma** [comment]
Sorry my bad. Yes, the version `1.10.0-alpha1` works, but `1.10.0a1` fails.

**Comment by m-vdb** [comment]
`1.10.0a1` is not following the [semver spec](https://semver.org/). But `1.10.0-a1` or `1.10.0-alpha1` would.

**Comment by tabergma** [comment]
Yes. However, the idea was to nevertheless support it. We could maybe just internally map `1.10.0a1` to `1.10.0-a1` or `1.10.0-alpha1` and print a warning for the user.

**Comment by m-vdb** [comment]
but why diverge from semver?

**Comment by tabergma** [comment]
@tmbo mentioned we should support it

**Comment by tabergma** [comment]
But we should definitely not just fail if a version number is not supported, but rather print a useful error message.

**Comment by m-vdb** [comment]
ok on that note we can definitely display what a valid version number looks like
