### ISSUE TITLE
Default message if action server throws an exception

### ISSUE THREAD

**Issue by IgNoRaNt23** [RasaHQ/rasa#5588]
Hi, when a custom action crashes unexpectedly the user is usually left alone with no response from the bot. While it is of course best to have a specific behaviour for every exception, some exceptions even surprise us the developers from time to time. It would be nice to have a general error text, that can be displayed to the user.

**Overview of the Solution**: Option 1: Add it somewhere here [https://github.com/RasaHQ/rasa/blob/88f94cad2813e4c02c0da4ec3060c4cf88d6c4d2/rasa/core/processor.py#L621](https://github.com/RasaHQ/rasa/blob/88f94cad2813e4c02c0da4ec3060c4cf88d6c4d2/rasa/core/processor.py#L621)

Option 2: Switch the starting point of any action from .run() to something like .start() with .start() looking like

`try: events = action.run() except ActionExecutionRejection as aer: raise aer except: dispatcher.utter_message("error-text") events = []

return events`

with "error-text" replaced by a domain-template.

I currently use a variant of option 2 as a temporary fix in my project and it works as expected. Made a CustomAction-baseclass inheriting from Action with .run() as above and everything that was named run() before is now execute().

**Examples** (if relevant): User: "bla bla" ** Action server exception ** Bot: "Sorry, but there's a technical problem. Please try ..."

**Definition of Done**:

*   [ ] Tests are added
*   [ ] Feature described the docs
*   [ ] Feature mentioned in the changlog

**Comment by sara-tagger** [comment]
Thanks for submitting this feature request 🚀 @tmbo will get back to you about it soon! ✨

**Comment by TyDunn** [comment]
@tmbo Is this still an issue?

**Comment by tmbo** [comment]
Yes, this is still an issue. Ideally, we establish a pattern like we have it for the web: e.g. if you browse to a non existant URL on a properly configured webserver, you get a nice little 404 page. If there is a server error, you'll get a notification about that as well. 

I think we need to address this from two angles:
- make sure the conversation is just "hanging" -> user gets some sort of response even if there is an error
- make sure we properly alert the developer / project team about that issue (console message, flag conversation in rasa x, ...)

**Comment by cliffweng** [comment]
hi any update on this? thanks!

**Comment by TyDunn** [comment]
Hi @cliffweng. We have not been able to get to this yet. Would you be interested in [making a contribution](https://rasa.com/community/contribute/) for this?
