### ISSUE TITLE
Throw a warning for ResponseSelector if intent classifier isn't present 

### ISSUE THREAD

**Issue by akelad** [RasaHQ/rasa#5604]
Right now you can train a model with just a ResponseSelector present in your pipeline, e.g.:

 pipeline:

*   name: WhitespaceTokenizer
*   name: RegexFeaturizer
*   name: LexicalSyntacticFeaturizer
*   name: CountVectorsFeaturizer
*   name: CountVectorsFeaturizer
     analyzer: char_wb
     min_ngram: 1
     max_ngram: 4
*   name: EntitySynonymMapper
*   name: ResponseSelector
     epochs: 100

but then when you run the bot, your intents are going to get classified as `None` and the bot won't know where to go next:

 2020-04-09 10:50:01 DEBUG rasa.core.processor - Received user message 'what is rasa x?' with intent '

 {'name': None, 'confidence': 0.0} 

' and entities '[]'

So we should throw a warning in the pipeline somewhere if a ResponseSelector is present without an intent classifier to avoid confusion (multiple people have come across this at this point)

**Comment by m-vdb** [comment]
@akelad what do you think of moving this to the "Contribute to Rasa" board? It sounds like it's a good candidate to me

**Comment by akelad** [comment]
sure, but it should probably also stay in the loop inbox in case no one ever gets to it

**Comment by m-vdb** [comment]
I think we want to avoid tickets staying in Inbox forever, it hinders triaging.

Do you know of direct feedback from customers / forum users who mention this being a problem? Trying to assess the priority a bit better

**Comment by akelad** [comment]
I can't remember who came across it, but I did and probably some other forum users also. It's definitely a weird experience, and something we should fix (but not like highest priority)
