### ISSUE TITLE
Bot is generating same output multiple times

### ISSUE THREAD

**Issue by somumu** [RasaHQ/rasa#5613]
Hello,
I am working on a multi lingual bot. I made english, hindi bot in older version of rasa. I am training the same bot for bengali and arabic language but on newer version(Rasa 1.9.5). 

For bengali and arabic bot I am facing an issue under which when I give an input to bot it prints same output multiple times. For resolving this issue I tried to make changes in stories.md file and also tried to make fresh story file using interactive learning but facing the same issue again and again. For example :
-----
Input : hello
Output : hey how r u
              hey how r u
              hey how r u
              hey how r u
hey how r u
-----
Bot flow is similar for other two i.e. english and hindi but not facing this issue there.  

Kindly help me to resolve the same. Any help would be appreciated.
Attaching and screenshot of the issue
Thank you !

**Rasa version**:
Rasa 1.9.5

**Python version**:
Python 3.6.7

**Operating system** (windows, osx, ...):
Ubuntu

**Issue**:
Bot is giving same output multiple times

```

**Comment by sara-tagger** [comment]
Thanks for the issue, @erohmensing will get back to you about it soon!

###### You may find help in the [docs](https://rasa.com/docs/) and the [forum,](https://forum.rasa.com/) too 🤗

**Comment by erohmensing** [comment]
Hi @somumu, this sounds less like a bug and more of a usage error. Please open a thread on the [forum](forum.rasa.com) and we'll be happy to help. In cases like this, its usually helpful to give the output of `rasa shell --debug` where the repetitive behavior is happening.
