### ISSUE TITLE
Not syncing with Rasa X

### ISSUE THREAD

**Issue by liorskaler** [RasaHQ/rasa#5615]
**Rasa version**: 1.9.5

**Rasa SDK version** (if used & relevant):

**Rasa X version** (if used & relevant): Lastest version

**Python version**:

**Operating system** (windows, osx, ...): OS Catalina Mac

**Issue**:

My NLU file is not updating in Rasa X properly.  I have an intent with many values in the file on github and in Rasa X this intent has zero values.  Why is it not updating? Thanks.

**Error (including full traceback)**:
```

```

**Command or request that led to error**:
```

```

**Content of configuration file (config.yml)** (if relevant):
```yml

```

**Content of domain file (domain.yml)** (if relevant):
```yml

```

**Comment by sara-tagger** [comment]
Thanks for the issue, @tabergma will get back to you about it soon!

###### You may find help in the [docs](https://rasa.com/docs/) and the [forum,](https://forum.rasa.com/) too 🤗

**Comment by degiz** [comment]
Hey @liorskaler, sorry to hear you have issues.

What's your current setup? How did you deploy Rasa X?

**Comment by liorskaler** [comment]
Hey @degiz, thanks for the reply. 

Deployed to an iphone app as a docker through a VPS server using the Kubernetes cluster and deploy script.

**Comment by degiz** [comment]
Hey @liorskaler 

I'd suppose you're trying to use the git integration and something doesn't work.

You need to make sure that you follow all the steps from [this](https://rasa.com/docs/rasa-x/installation-and-setup/integrated-version-control/) doc.

If that doesn't work, then please check the logs from "rasax" container. There must be something about the git integration.

**Comment by liorskaler** [comment]
Hey @degiz 

There is no errors on git integration in the logs, it has been integrated successfully but it is not automatically pulling the latest source as per the Rasa documentation.

**Comment by degiz** [comment]
@ricwo could you please suggest the best way to debug that?

**Comment by wochinge** [comment]
@liorskaler 
Can you please 

1. `exec` into the `rasa-x` pod (e.g. `kubectl exec -it ... `) and then
1. `cd git`
2. `ls git` 
3. `cd <directory which has the largest number`
4. And then share the output of `git status` with us?

Thanks! That would be a great help!

**Comment by liorskaler** [comment]
@wochinge It was great speaking with you today and thank you for figuring out the solution.  This issue is now closed.  Have a great day :)

**Comment by wochinge** [comment]
For others: The problem was that the Rasa project directory wasn't conform with the expected layout which e.g. `rasa init` generates. @TyDunn did you already create an issue that we implement automated checks and show warnings to the users?

**Comment by TyDunn** [comment]
@wochinge yes
