### ISSUE TITLE
Rasa X can't find files in subdirectory

### ISSUE THREAD

**Issue by tatianafrank** [RasaHQ/rasa#5624]
**Rasa version**:
1.9.5
**Rasa SDK version** (if used & relevant):

**Rasa X version** (if used & relevant):
0.27.4 
**Python version**:
3.7.0
**Operating system** (windows, osx, ...):
osx
**Issue**:
Ive got Rasa X running locally on Kuberneted and Ive hooked it up to my GIthub repo containing my rasa open source bot code but the data is not being downloaded to Rasa X. I think the issue is that the rasa code is located in a subdirectory not root. Do the files have to live in the root of the github repo for this to work?

**Error (including full traceback)**:
```

```

**Command or request that led to error**:
```

```

**Content of configuration file (config.yml)** (if relevant):
```yml

```

**Content of domain file (domain.yml)** (if relevant):
```yml

```

**Comment by sara-tagger** [comment]
Thanks for raising this issue, @TyDunn will get back to you about it soon✨

###### Please also check out the [docs](https://rasa.com/docs/) and the [forum](https://forum.rasa.com/) in case your issue was raised there too 🤗

**Comment by TyDunn** [comment]
Hi @tatianafrank. What are you intending to use Rasa X for given that you have deploy it on your Mac?

Yeah, in order to use Rasa X, your files need to conform to the default Rasa project layout: https://rasa.com/docs/rasa-x/installation-and-setup/integrated-version-control/#project-layout

**Comment by tatianafrank** [comment]
Thanks for the answer! It's deployed on my mac because I'm still researching if our company wants to use Rasa or not.

**Comment by TyDunn** [comment]
@tatianafrank Gotcha. It's pretty cool that you got it setup on a mac. We usually recommend setting it up in "server mode" (e.g. on a linux machine that is running all the time), so that Rasa X can always capture conversations with your users, and you can turn those conversations into training data

**Comment by tatianafrank** [comment]
I obviously don't think my mac is a production environment.. Im just doing research on the product as I stated in my previous comment...

**Comment by tatianafrank** [comment]
The reason my core files are in a subdirectory instead of root is because Im using poetry to package my code. If anyone can address that issue, which is the topic of this ticket, that would be really helpful.

**Comment by TyDunn** [comment]
Hi @tatianafrank. As I mentioned, at the moment we only support the standard project layout. Maybe you would be interested in hopping on a Zoom call, so I can learn better about how we can improve Rasa Open Source and Rasa X for you?
