### ISSUE TITLE
do not deprecate executeConversationAction in HTTP API

### ISSUE THREAD

**Issue by cristianmtr** [RasaHQ/rasa#5630]
**Description of Problem**:

I noticed in the documentation on the HTTP API that you are planning to deprecate the `executeConversationAction` endpoint.

[https://rasa.com/docs/rasa/api/http-api/#operation/executeConversationAction](https://rasa.com/docs/rasa/api/http-api/#operation/executeConversationAction)

**Overview of the Solution**:

Please consider maintaining this, as we use in several scenarios for our chatbot. Most importantly, it's required in order to pause and resume the bot, to handle human take-over periods.

**Definition of Done**:

Endpoint works as is for the future.

Adding @nbeuchat, as we work together.

**Comment by sara-tagger** [comment]
Thanks for submitting this feature request 🚀 @alwx will get back to you about it soon! ✨
