### ISSUE TITLE
make all event types descriptive in debug logs

### ISSUE THREAD

**Issue by erohmensing** [RasaHQ/rasa#5632]
Action 'feedback_form' ended with events '[BotUttered('This is my message'), 

 {"elements": null, "quick_replies": null, "buttons": null, "attachment": null, "image": null, "custom": null} 

, {}, 1586944499.440226), <rasa.core.events.SlotSet object at 0x1a37f2db90>, <rasa.core.events.Form object at 0x1a37f2d9d0>, <rasa.core.events.SlotSet object at 0x1a37f2d310>]'.

The `BotUttered` event here is actually helpful because it tells me what was output. however it would also be nice if i could see which slot was being set and to what, as well as whether a form was activated or deactivated, etc.

**Comment by melindaloubser1** [comment]
Bumping this up - the way most events are logged is not helpful for debugging:
```
Action 'some_custom_action' ended with events '[BotUttered('helpfully visible!', {"elements": null, "quick_replies": null, "buttons": null, "attachment": null, "image": null, "custom": {"text": "helpfully visible!", "type": "MESSAGE"}}, {}, 1636443226.5411195), <rasa.shared.core.events.SlotSet object at 0x7f478c273d90>, <rasa.shared.core.events.SlotSet object at 0x7f470a547970>, <rasa.shared.core.events.SlotSet object at 0x7f36572a4c70>, <rasa.shared.core.events.SlotSet object at 0x7f47872a4be0>, <rasa.shared.core.events.SlotSet object at 0x7f47e0632550>, <rasa.shared.core.events.ActiveLoop object at 0x7f890a598ee0>, <rasa.shared.core.events.SlotSet object at 0x7f120a598040>, <rasa.shared.core.events.SlotSet object at 0x7f460a56b3a0>]'.
```
