### ISSUE TITLE
Slash command does not work for multiple intents

### ISSUE THREAD

**Issue by msamogh** [RasaHQ/rasa#5634]
**Rasa version**: 1.6.2

**Rasa SDK version** (if used & relevant):

**Rasa X version** (if used & relevant):

**Python version**:

**Operating system** (windows, osx, ...):

**Issue**:
For instance, Rasa does not detect the entity mapping `{"city": "X"}` when I type`/greet+inform{"city": "X"}` into the shell. Instead, it asks me to mark the entities using `[value](type)` notation.

**Comment by erohmensing** [comment]
This sounds like interactive learning -- does it work as expected in `shell` and/or the REST channel? Also, hi!

**Comment by erohmensing** [comment]
and to clarify, does it not work with multiple intents at all, or just with entities attached? 🤔

**Comment by msamogh** [comment]
Yes, you're right. It works fine in shell. The problem is only in interactive learning.

> does it not work with multiple intents at all, or just with entities attached?
Just with entities attached. Once I label the entities once again, for instance, the intent-combination shows up fine in the tracker state.

And, hello there!
