### ISSUE TITLE
Need docs on Facebook Messenger response template keys 

### ISSUE THREAD

**Issue by ortsaCniveK** [RasaHQ/rasa#5640]
**Description of Problem**:
Had to add a Facebook messenger channel integration into a bot I spun up and found the Facebook Messenger docs lacking a bit especially on the special response template keys `quick_replies` and `elements`; I had to read through the Facebook channel source to figure out what was allowed/disallowed.

**Overview of the Solution**:
FB Messenger docs updated with additional response template information.

**Definition of Done**:
- [x] Facebook channel docs updated with caveats for default `buttons` option and explanation of omission if more than 3 buttons were passed.
- [x] Facebook channel docs updated with `quick_replies` description along with quick title character limitation mention
- [x] Facebook channel docs updated with `elements` description along with pointer to Messenger docs on allowed templates
- [x] Documentation update mentioned in the change log

**Comment by sara-tagger** [comment]
Thanks for submitting this feature request 🚀 @degiz will get back to you about it soon! ✨

**Comment by degiz** [comment]
Hey @ortsaCniveK 

Great that you could connect the bot the Facebook Messenger! 

Since you've just identified the issues with the current docs, maybe you can propose a PR with all the updated you've mentioned?

**Comment by ortsaCniveK** [comment]
Currently working on updating docs as well as doing some maintenance on that module.
