### ISSUE TITLE
Story's Tree Flow Bug

### ISSUE THREAD

**Issue by pandaxar** [RasaHQ/rasa#5642]
**Rasa version**: 1.9.5 **Rasa SDK version** (if used & relevant): 1.9.0 **Rasa X version** (if used & relevant): 0.27.4 **Python version**: 3.7.6 **Operating system** (windows, osx, ...): Windows 10 **Issue**: Looks like the longer the entity extracted the more Rasa X UI can't display the tree flow correctly [<span class="image-wrap" style="">![](https://user-images.githubusercontent.com/40818959/79398675-1e0a8e00-7f79-11ea-90bc-6ddca2ca6ef2.png)</span>](https://user-images.githubusercontent.com/40818959/79398675-1e0a8e00-7f79-11ea-90bc-6ddca2ca6ef2.png)

**Error (including full traceback)**:

**Command or request that led to error**:

**Content of configuration file (config.yml)** (if relevant):

**Content of domain file (domain.yml)** (if relevant):

**Comment by sara-tagger** [comment]
Thanks for raising this issue, @TyDunn will get back to you about it soon✨

###### Please also check out the [docs](https://rasa.com/docs/) and the [forum](https://forum.rasa.com/) in case your issue was raised there too 🤗

**Comment by TyDunn** [comment]
Hi @pandaxar. Thanks for reporting this bug. I am unable to reproduce this in Rasa X 0.27.4. Can you please share an example story that you find does this?

**Comment by pandaxar** [comment]
Hi @TyDunn , Gladly ! I think this an issue related to the front-end of Rasa X .So this issue is reproducible if you generate a story in Rasa X using form related stories like this one :  

## happy story periode_collecte_idees-Idea exist

* greet
  - action_fetch_period
  - slot{"period":"pre"}
  - utter_greet_user_pre
* affirm_idea
  - idea_form
  - form{"name": "idea_form"}     
  - form{"name": null}
* bye
  - utter_bye_user

story generated in Rasa X by clicking save story : 

## happy story periode_collecte_idees-Idea exist | RasaX
* greet
    - action_fetch_period
    - slot{"period":"pre"}
    - slot{"username":"adnan"}
    - utter_greet_user_pre
* affirm_idea
    - idea_form
    - form{"name":"idea_form"}
    - slot{"requested_slot":"detail"}
* inform{"detail":"organiser un evenement special"}
    - slot{"detail":"organiser un evenement special"}
    - idea_form
    - slot{"detail":"organiser un evenement special"}
    - slot{"requested_slot":"idea_s_client"}
* inform{"idea_s_client":"onshore"}
    - slot{"idea_s_client":"onshore"}
    - idea_form
    - slot{"idea_s_client":"onshore"}
    - slot{"requested_slot":"potential"}
* choose_potential{"potential":"Fort"}
    - slot{"potential":"Fort"}
    - idea_form
    - slot{"potential":"Fort"}
    - form{"name":null}
    - slot{"requested_slot":null}
* bye
    - utter_bye_user

![image](https://user-images.githubusercontent.com/40818959/79467597-d7a74480-7ff5-11ea-9297-6bf2477792fc.png)

So i'm thinking , the longer the generated story is (in case of a long form) , the Front-end Code fails to display the entirety of the expected Tree , if i'm not mistaken it's the 'g' tag with 'output' class in the html code ?

Best Regards

**Comment by TyDunn** [comment]
@pandaxar Thanks for the quick response and the example. I see what you are saying now and was able to reproduce the bug in Rasa X 0.24.7. I am placing it in the inbox of one of our engineering squads to squash 👍

**Comment by abhilasharoy** [comment]
@gausie Would you think this issue is for Enable or Practice-cdd?
