### ISSUE TITLE
Type error in facebook.py

### ISSUE THREAD

**Issue by wavymazy** [RasaHQ/rasa#5657]
Hi,

I tried deploying the bot with Facebook and one error appears when I start a form:

TypeError: pop() takes at most 1 argument (2 given) (in rasa/core/channels/facebook.py : line 229).

I did a workaround but I thought you guys might want to take a look at this.

Cheers.

**Comment by sara-tagger** [comment]
Thanks for raising this issue, @tabergma will get back to you about it soon✨

###### Please also check out the [docs](https://rasa.com/docs/) and the [forum](https://forum.rasa.com/) in case your issue was raised there too 🤗

**Comment by tabergma** [comment]
Thanks for raising the issue @wavymazy. What is your current workaround?

**Comment by wavymazy** [comment]
Hello,

Since the issue was that .pop("sender", {}) is expecting the json to be a dict, I just put in place a check to handle the case when it's a list.

    async def send_custom_json(
        self, recipient_id: Text, json_message: Dict[Text, Any], **kwargs: Any
    ) -> None:
        """Sends custom json data to the output."""

        if isinstance(json_message, list):
            if isinstance(json_message.pop(), list):
                recipient_id = json_message.pop().pop() or recipient_id
            else:
                recipient_id = json_message.pop().pop("id", None) or recipient_id
        else:
            if isinstance(json_message.pop("sender", {}), list):
                recipient_id = json_message.pop("sender", {}).pop("id") or recipient_id
            else:
                recipient_id = json_message.pop("sender", {}).pop("id", None) or recipient_id

        self.messenger_client.send(json_message, recipient_id, "RESPONSE")

**Comment by tabergma** [comment]
Great! As you already have a solution, do you want to contribute and create a PR?

**Comment by silvasara** [comment]
I am interested in working on this issue, is it still valid?

**Comment by tabergma** [comment]
@silvasara I think it is. Feel free to pick it up 🚀

**Comment by jppgomes** [comment]
Hello, I checked the missing tests for the correction, can I implement and send the pr? @tabergma

**Comment by ErickGiffoni** [comment]
Is this issue still a problem ?
I am with a group of developers here that might want to solve it !

**Comment by ancalita** [comment]
Solved by #9692 PR
