### ISSUE TITLE
action restart is not working

### ISSUE THREAD

**Issue by Matthewli623** [RasaHQ/rasa#5658]
**Rasa version**:Rasa 1.8.0

**Rasa SDK version** (if used & relevant):

**Rasa X version** (if used & relevant):

**Python version**:3.7

**Operating system** (windows, osx, ...):windows

**Issue**:Restart action is not working.when I type /restart ,there is an error .I have already added action_restart in actions.Thank you

**Error (including full traceback)**:
```
Bot loaded. Type a message and press enter (use '/stop' to exit): 
Your input ->  /restart                                                          
2020-04-17 10:25:16 WARNING  rasa.core.featurizers  - Feature 'intent_restart' could not be found in feature map.
2020-04-17 10:25:16.260847: W tensorflow/core/kernels/data/generator_dataset_op.cc:103] Error occurred when finalizing GeneratorDataset iterator: Cancelled: Operation was cancelled
2020-04-17 10:25:18 ERROR    rasa.core.processor  - Encountered an exception while running action 'action_restart'. Bot will continue, but the actions events are 
lost. Please check the logs of your action server for more information.
2020-04-17 10:25:18 WARNING  rasa.core.featurizers  - Feature 'intent_restart' could not be found in feature map.
2020-04-17 10:25:18 WARNING  rasa.core.featurizers  - Feature 'intent_restart' could not be found in feature map.
2020-04-17 10:25:18.330059: W tensorflow/core/kernels/data/generator_dataset_op.cc:103] Error occurred when finalizing GeneratorDataset iterator: Cancelled: Operation was cancelled
```
```

```
**Command or request that led to error**:
```
/restart
```

**Content of configuration file (config.yml)** (if relevant):
```yml
language: "en"

pipeline:
  - name: WhitespaceTokenizer
  - name: RegexFeaturizer
  - name: LexicalSyntacticFeaturizer
  - name: CountVectorsFeaturizer
  - name: CountVectorsFeaturizer
    analyzer: "char_wb"
    min_ngram: 1
    max_ngram: 4
  - name: DIETClassifier
  - name: EntitySynonymMapper
  - name: ResponseSelector

# Configuration for Rasa Core.
# https://rasa.com/docs/rasa/core/policies/
policies:
  - name: EmbeddingPolicy
  - name: TEDPolicy
    max_history: 5
    epochs: 100
  - name: "FallbackPolicy"
    nlu_threshold: 0.6
    core_threshold: 0.6
    fallback_action_name: "myfallback"
  - name: MappingPolicy
  - name: FormPolicy

```

**Content of domain file (domain.yml)** (if relevant):
```yml
intents:
  - greet
  - pathtorunway
  - readback
  - windspeed
  - fallback story
  - out_of_scope

actions:
  - requestdepature_action
  - repeatpath_action
  - requesttaxi_action
  - cleartakeoff_action
  - utter_requestdepature
  - utter_repeatpath
  - utter_requesttaxi
  - utter_cleartakeoff
  - update_point
  - myfallback
  - action_restart


entities:
  - holding_point
  - via_point
  - via_point2
  - callsign
  - runway
  - degree
  - knots
  - time

slots:
  holding_point:
    auto_fill: false
    type: text
  via_point:
    type: text
    auto_fill: false
  via_point2:
    type: text
    auto_fill: false
  callsign:
    type: text
    auto_fill: false
  runway:
    type: text
    auto_fill: false
  


responses:
  utter_requestdepature:
  - text: "Arci. "
  utter_repeatpath:
  - text: "Taxi {via_point}, Holding Point {holding_point}, {callsign}"

  utter_requesttaxi:
  - text: "{callsign}, Holding at {holding_point}, ready"

  utter_cleartakeoff:
  - text: "{runway}, {callsign}"

  utter_ask_holding_point:
  - text: "need more info(holding_point) only"
  utter_ask_via_point:
  - text: "need more info(via_point) only"
  utter_ask_callsign:
  - text: "need more info(callsign) only"
  utter_ask_runway:
  - text: "need more info(runway) only"

forms:
  - point_form

```

**Comment by sara-tagger** [comment]
Thanks for the issue, @tmbo will get back to you about it soon!

###### You may find help in the [docs](https://rasa.com/docs/) and the [forum,](https://forum.rasa.com/) too 🤗

**Comment by kiranbeethoju** [comment]
it is still an existing issue, action_restart is not working

**Comment by tmbo** [comment]
hey, is there any reason for `action_restart` to be in your actions list? (it might be causing this)

**Comment by tmbo** [comment]
oh, just saw that you are not the issue author. @kiranbeethoju do you mind sharing your configuration & domain?

**Comment by kiranbeethoju** [comment]
### Config.yml data

`language: en
pipeline:
- name: "WhitespaceTokenizer"
  intent_tokenization_flag: True
  intent_split_symbol: "_"
- name: "RegexFeaturizer"
- name: "CountVectorsFeaturizer"
- name: "DIETClassifier"
  epochs: 10
- name: "EntitySynonymMapper"
policies:
- name: MemoizationPolicy
  max_history: 3
- name: FormPolicy
- name: KerasPolicy
  epochs: 100
- name: MappingPolicy
- name: "FallbackPolicy"
  nlu_threshold: 0.25
  core_threshold: 0.25
  fallback_action_name: 'utter_fallback'
`

### domain.yml

intents:
- restart

entities:
- restart

actions:
- action_restart
-...more

**Comment by tmbo** [comment]
is there a reason `action_restart` is part of your actions list, did you customize it? would you mind removing it and checking if you are still experiencing the issue (just to check if it is related to it)

**Comment by kiranbeethoju** [comment]
If I remove action_restart from the domain.yml also I observed an error as action_restart is now found in actions.py! should I add something in actions.py file related to action_restart ?, let me check now and come back here :)

**Comment by kiranbeethoju** [comment]
`2020-11-12 12:11:53 ERROR    rasa_sdk.endpoint  - No registered action found for name 'action_restart'.
`

**Comment by TyDunn** [comment]
@kiranbeethoju This does not seem to be a bug. If you are still having problems, please post on the [Rasa forum](http://forum.rasa.com/) 👍
