### ISSUE TITLE
Rename DucklingHTTPExtractor to DucklingEntityExtractor

### ISSUE THREAD

**Issue by akelad** [RasaHQ/rasa#5661]
The duckling component is called `DucklingHTTPExtractor` for legacy reasons - it's hard to remember it's name and the case sensitivity makes it even more confusing. We should rename it to `DucklingEntityExtractor`

**Comment by fanzhimin0517** [comment]
我就是报错一直找不到相应的 class name，但是万万没想到也没有注意到会是这个情况。 嗐~
