### ISSUE TITLE
private telegram bot

### ISSUE THREAD

**Issue by unltdnetworx** [RasaHQ/rasa#5662]
**Description of Problem**:
At the moment everbody can find the chatbot and talk to it. This is okay, as long as nothing is controlled by the bot. Think of a voice-/chat-assistant for a smarthome. "Open the door..."

**Overview of the Solution**:
One should optionaly be able to filter the chat-ID of the bot and only give response, if the ID is already known. Maybe hardcoded in the credentials-file or over a password-question at the start of the bot.

**Examples**:
There is a so called "adapter" for the smarthome-system ioBroker. There you can connect a telegram-bot and at the first connection with the bot on a new device. You have to give it the password via typing "/passwd <passwordSavedInAdapter>". Then the ID and nicname of the user is stored in the database. If a message of another ID comes in, it is ignored.
[Github-repo of the adapter](https://github.com/iobroker-community-adapters/ioBroker.telegram)  as example:

**Definition of Done**:
- [ ] function is implemented
- [ ] Tests are added
- [ ] Feature described the docs
- [ ] Feature mentioned in the changlog

**Comment by sara-tagger** [comment]
Thanks for submitting this feature request 🚀 @Ghostvv will get back to you about it soon! ✨

**Comment by TyDunn** [comment]
Hi @unltdnetworx! I am going to close this issue because this is something you can achieve in Rasa Open Source today. You would process the first message you receive as the password, just like what that example you shared does 👍
