### ISSUE TITLE
After successfully running locally i tried to integrate with Telegram but not getting any response at chatting and it not showing any error. 

### ISSUE THREAD

**Issue by ravichaurasia** [RasaHQ/rasa#5664]

**Comment by ravichaurasia** [comment]
![Capture1](https://user-images.githubusercontent.com/25603907/79607010-26490180-8110-11ea-9797-2ba6059790de.PNG)
I was using ngrok for global running and followed every steps.
but still not getting any response in chat

**Comment by sara-tagger** [comment]
Thanks for the question, our Github issue board is for **bugs and feature requests only,** though 😕
Please ask this question in the [forum✨](https://forum.rasa.com/c/rasa)

###### If you were describing a bug, please create a [report](https://github.com/RasaHQ/rasa/issues/new?labels=bug&template=bug_report.md) and fill out the template.

**Comment by sara-tagger** [comment]
Thanks for the issue, @closed will get back to you about it soon!

###### You may find help in the [docs](https://rasa.com/docs/) and the [forum,](https://forum.rasa.com/) too 🤗
