### ISSUE TITLE
URL in documentation page is broken

### ISSUE THREAD

**Issue by abhayana24** [RasaHQ/rasa#5665]
Hello,

The link to **external-events-and-reminders** page is broken in the following page: https://rasa.com/docs/rasa/core/responses/#proactively-reaching-out-to-the-user-with-external-events

The **docs page on this topic** hyperlink refers to this page (https://rasa.com/docs/rasa/core/external-events-and-reminders) which is wrong, the correct page is (https://rasa.com/docs/rasa/core/reminders-and-external-events/)

Screenshot for reference:

![image](https://user-images.githubusercontent.com/7872601/79684582-4384e980-8250-11ea-8921-072373c3e3f0.png)

**Comment by amn41** [comment]
thanks @abhayana24 ! would you be open to creating a pull request to fix this?

**Comment by abhayana24** [comment]
Sure @amn41

**Comment by AMR-KELEG** [comment]
O/
This issue is already fixed.
Can we get the issue closed?
Thanks :smile:
