### ISSUE TITLE
Encountered invalid end-to-end format

### ISSUE THREAD

**Issue by tLabruna** [RasaHQ/rasa#5667]
**Rasa version**: 1.9.6

**Python version**: 3.6.9

**Operating system** (windows, osx, ...): windows

**Issue**: Cannot test my model because of an error in my stories, but they look good, and I've been using the same stories with no problems.

**Error (including full traceback)**:
```
Error in line 2: Encountered invalid end-to-end format for message time_remaining. Please visit the documentation page on end-to-end testing at https://rasa.com/docs/rasa/user-guide/testing-your-assitant/#end-to-end-testing/
```

**Command or request that led to error**:
```
rasa test
```

stories.md:

```
## time_remaining
* time_remaining
  - action_time_remaining

## current_dose
* current_dose
  - action_current_dose

## treatment_end
* treatment_end
  - action_treatment_end

## required_dose
* required_dose
  - action_required_dose
```

**Comment by pandaxar** [comment]
Hi , look at your **e2e stories** file not the stories.md file , and read the doc on how to test the model .

**Comment by tLabruna** [comment]
Hi, where do I find my e2e stories? I read the docs, I followed it for testing my model

**Comment by pandaxar** [comment]
I believe they reside in the tests folder that comes with rasa init ?

**Comment by sara-tagger** [comment]
Thanks for raising this issue, @alwx will get back to you about it soon✨

###### Please also check out the [docs](https://rasa.com/docs/) and the [forum](https://forum.rasa.com/) in case your issue was raised there too 🤗
