### ISSUE TITLE
Rasa Data validate should check channel-specific utterance limitations

### ISSUE THREAD

**Issue by kevinthemself** [RasaHQ/rasa#5668]
**Description of Problem**:

In reference to #5640, there are some limitations for channels like FB Messenger that are not seen until runtime. It would be nice to see those warnings when running `rasa data validate`.

**Overview of the Solution**:

Add response template checks for utterances that specify the `channel` property.

**Examples** (if relevant):

*   Messenger Button Title limit
*   Messenger Button Count limit
*   Messenger Quick Reply limit

**Definition of Done**:

*   [ ] Tests are added for channel specific utterances in `rasa data validate`
*   [ ] Channel specific utterances are checked for any existing limitations
*   [ ] Docs are updated
*   [ ] Changelog is updated

**Comment by ortsaCniveK** [comment]
This is contingent upon some updates I'm working on to improve mention of limitations, at least for FB Messenger specifically.

**Comment by sara-tagger** [comment]
Thanks for submitting this feature request 🚀 @degiz will get back to you about it soon! ✨

**Comment by degiz** [comment]
Thanks for working on this @ortsaCniveK 🚀 
Feel free to assign me to the PR once it's there!

**Comment by joejuzl** [comment]
@ortsaCniveK any update on this?
