### ISSUE TITLE
Improve documentation around `SessionStart` event

### ISSUE THREAD

**Issue by melindaloubser1** [RasaHQ/rasa#5675]
**Description of Problem**:

To make sure a new session is started each time `rasa shell` is run, `/session_start` must be sent as the first message manually. 
[The docs](https://rasa.com/docs/rasa/core/domains/#session-config) say 
```
a manual session start is triggered with the /session_start intent message.
```
But usually this is sent automatically by the channel, so on starting `rasa shell` the user will not see the same initial greeting/welcome message that they might in another channel. 

This was pointed out in 
https://github.com/RasaHQ/rasa/issues/5641

**Overview of the Solution**:
Add a note in the docs that `/session_start` needs to be entered manually in `rasa shell` to see the same behaviour as in another channel configured to send that payload. *Edit: Also note that **any** first user message sent will trigger `action_session_start` in shell. 

**Definition of Done**:
- [ ] Documentation updated

**Comment by ortsaCniveK** [comment]
I'd also reiterate that any user message will trigger a new session to start.  It's irrelevant what Rasa gets in the shell because action_session_start will be triggered each time.

**Comment by melindaloubser1** [comment]
That's true, will update it
