### ISSUE TITLE
Slack channel sends double images

### ISSUE THREAD

**Issue by 12gabriel3** [RasaHQ/rasa#5681]
In `rasa/core/channels/slack.py`, the method `send_image_url` sends the image link as text and as an image block to slack, which makes the message show two images, like this:

[<span class="image-wrap" style="">![](https://user-images.githubusercontent.com/16885097/79788682-6500d680-831f-11ea-9e21-6300a8f632be.png)</span>](https://user-images.githubusercontent.com/16885097/79788682-6500d680-831f-11ea-9e21-6300a8f632be.png)

I could easily fix this by instead of sending

`await self.client.chat_postMessage( channel=recipient, as_user=True, text=image, blocks=<span class="error">[image_block]</span>, )`

send an empty string as text (the text field is not even required by the slack API if the message has blocks) like this:

`await self.client.chat_postMessage( channel=recipient, as_user=True, text='', blocks=<span class="error">[image_block]</span>, )`

which makes the message look normal:

[<span class="image-wrap" style="">![](https://user-images.githubusercontent.com/16885097/79789372-73032700-8320-11ea-9702-ee2bb82b1d73.png)</span>](https://user-images.githubusercontent.com/16885097/79789372-73032700-8320-11ea-9702-ee2bb82b1d73.png)

Annoying problem and very easy fix. Hope I helped

**Comment by sara-tagger** [comment]
Thanks for the issue, @tttthomasssss will get back to you about it soon!

###### You may find help in the [docs](https://rasa.com/docs/) and the [forum,](https://forum.rasa.com/) too 🤗

**Comment by tttthomasssss** [comment]
Thanks very much for the bug report! Could you provide version numbers of the following things so we can locate the issue quickly (omit any if you don't have them installed):

* `rasa`
* `rasa-sdk`
* `rasa X`
* `python version`
* Your OS

**Comment by 12gabriel3** [comment]
Sorry for the late response, I abandoned this personal project for now, but here are the versions I used:

rasa 1.10.0
rasa-sdk 1.10.0
rasa X not used
python 3.7
Ubuntu 16.04.6 LTS

**Comment by robynbitner** [comment]
Is there any way to fix this without changing the source code?

**Comment by rohetoric** [comment]
Pls help in the above.
Is it a size issue? Do the images have to be of a specific length and width to support this?

**Comment by rohetoric** [comment]
This bug still exists. What is the solution that we can implement?

**Comment by robynbitner** [comment]
I have found a solution by sending an attachment with the following parameters instead of an image 

attachment = {
	'image_url': image_url,
	'text': ''
}
dispatcher.utter_message(attachment=attachment)

**Comment by rohetoric** [comment]
Hi @robynbitner,
Do we have to make the above edit in `actions.py` ? I am using Rasa 2.2.2

**Comment by 12gabriel3** [comment]
> Hi @robynbitner,
> Do we have to make the above edit in `actions.py` ? I am using Rasa 2.2.2

You make the change wherever you are using
```
dispatcher.utter_message(image=image_url)
```

Instead, you need to use 
```
attachment = {
'image_url': image_url,
'text': ''
}
dispatcher.utter_message(attachment=attachment)
```

Thanks for the workaround, @robynbitner 
Maybe one of us can make a pull request to fix this issue?

**Comment by rohetoric** [comment]
Hi @12gabriel3,
Thanks for the response. 
In Rasa 2.2.2, I am not able to see this line of code anywhere after `rasa init `, hence the above question.

**Comment by RamakrishnaChilaka** [comment]
Slack stopped accepting attachment through image_url..
