### ISSUE TITLE
rasa run --config

### ISSUE THREAD

**Issue by reactiveframes** [RasaHQ/rasa#5683]
With rasa-x I can run with a specific configuration for example:
rasa x --no-prompt -m example/models --data example/data --config example/config.yml --enable-api

This allows me to manage dependency injection across different rasa x services

But for some reason, there isn't any option to run rasa (rest) service with --config
for example:
rasa run --config ...  is invalid!

Am I missing something conceptually here? or is this a reasonable feature request?

**Comment by sara-tagger** [comment]
Thanks for submitting this feature request 🚀 @chkoss will get back to you about it soon! ✨

**Comment by chkoss** [comment]
It is already possible to run Rasa Open Source with a specific configuration. This requires two steps:
- Training a model. `rasa train` can take the arguments `--config`, --data` and `--domain`.
- Running Rasa using a trained model, e.g. with `rasa run`. By default, this uses the latest trained model, but you can specify another one via the `--model` argument.

Does this answer your question?

**Comment by chkoss** [comment]
Closing this because the requested feature already exists
