### ISSUE TITLE
Documentation: Changes to "Securing with SSL" Rasa X docs

### ISSUE THREAD

**Issue by tangochris** [RasaHQ/rasa#5689]
I'd like to suggest two changes to "[Docker-Compose Manual Install: Securing with SSL](https://rasa.com/docs/rasa-x/installation-and-setup/docker-compose-manual/#securing-with-ssl)".

1. Port 80 must be available or `sudo certbot certonly` will not work. Therefore, before that step, instruct user to turn off Rasa, i.e. `sudo docker-compose down`
2. After copying `privkey.pem` to `/etc/rasa/certs`, instruct user to grant read privileges to group, i.e. `sudo chmod 640 certs/privkey.pem`. This is discussed on the [forum](https://forum.rasa.com/t/rasa-x-in-http-rasa-in-https/23607/8).

**Comment by sara-tagger** [comment]
Thanks for submitting this feature request 🚀 @dakshvar22 will get back to you about it soon! ✨

**Comment by alwx** [comment]
Closing it because #3335 is merged already.
