### ISSUE TITLE
The virtual environment found seems to be broken | python poetry

### ISSUE THREAD

**Issue by kamaldeepoodles** [RasaHQ/rasa#5692]
I am following the following link to install RASA on my system: [https://github.com/RasaHQ/rasa][1]
But unfortunately while trying to install the dependencies or any of the following poetry commands which are written in Makefile,

    $poetry run
    $poetry install

 I am getting following error:

[![enter image description here][2]][2]

Seems like there is some issue in virtual environment setup but don't know how I can fix. Following is the stack trace:

    $ make install
    poetry run python -m pip install -U 'pip<20'
    The virtual environment found in /home/kamaldeep/.cache/pypoetry/virtualenvs/rasa-LHgLSZoI-py3.6 seems to be broken.
    Recreating virtualenv rasa-LHgLSZoI-py3.6 in /home/kamaldeep/.cache/pypoetry/virtualenvs/rasa-LHgLSZoI-py3.6
    
    [CalledProcessError]
    Command '['/home/kamaldeep/.cache/pypoetry/virtualenvs/rasa-LHgLSZoI-py3.6/bin/python', '-Im', 'ensurepip', '--upgrade', '--default-pip']' returned non-zero exit status 1.
    Makefile:43: recipe for target 'install' failed
    make: *** [install] Error 1

  [1]: https://github.com/RasaHQ/rasa
  [2]: https://i.stack.imgur.com/PYuiH.png

**Comment by sara-tagger** [comment]
Thanks for the question, our Github issue board is for **bugs and feature requests only,** though 😕
Please ask this question in the [forum✨](https://forum.rasa.com/c/rasa)

###### If you were describing a bug, please create a [report](https://github.com/RasaHQ/rasa/issues/new?labels=bug&template=bug_report.md) and fill out the template.

**Comment by sara-tagger** [comment]
Thanks for the issue, @closed will get back to you about it soon!

###### You may find help in the [docs](https://rasa.com/docs/) and the [forum,](https://forum.rasa.com/) too 🤗

**Comment by kamaldeepoodles** [comment]
In case if you get error of broken virtual environment like

    `The virtual environment found in /home/kamaldeep/.cache/pypoetry/virtualenvs/rasa-LHgLSZoI-py3.7 seems to be broken`

Then install venv in the respective python package like python3.6, python3.5. In my case, I am using python 3.7

    `sudo apt-get install python3.7-venv`

Other way is to disable virtual environment

    `poetry config virtualenvs.create false`
