### ISSUE TITLE
关于triggers

### ISSUE THREAD

**Issue by 1535966643** [RasaHQ/rasa#5695]
是不是rasa1.7以下的版本都没有"Proactively Reaching Out to the User with External Events"这个功能呢？如果有的话在哪里，我现在使用的是1.3.9
还有请问哪里我可以查看rasa 匹配的TensorFlow版本

**Comment by sara-tagger** [comment]
Thanks for the question, our Github issue board is for **bugs and feature requests only,** though 😕
Please ask this question in the [forum✨](https://forum.rasa.com/c/rasa)

###### If you were describing a bug, please create a [report](https://github.com/RasaHQ/rasa/issues/new?labels=bug&template=bug_report.md) and fill out the template.

**Comment by sara-tagger** [comment]
Thanks for raising this issue, @closed will get back to you about it soon✨

###### Please also check out the [docs](https://rasa.com/docs/) and the [forum](https://forum.rasa.com/) in case your issue was raised there too 🤗

**Comment by 1535966643** [comment]
thanks
  

 

 ------------------&nbsp;原始邮件&nbsp;------------------
  发件人:&nbsp;"Sara-tagger"<notifications@github.com&gt;;
 发送时间:&nbsp;2020年4月22日(星期三) 晚上8:00
 收件人:&nbsp;"RasaHQ/rasa"<rasa@noreply.github.com&gt;;
 抄送:&nbsp;"不羁的风"<1535966643@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
 主题:&nbsp;Re: [RasaHQ/rasa] 关于triggers (#5695)

 

 

 
Closed #5695.
