### ISSUE TITLE
Update the the tutorials page of  the doc to refer to the latest version of rasa.

### ISSUE THREAD

**Issue by MadPr0grammer** [RasaHQ/rasa#5700]
Current versions of rasa and python in the docker image of the tutorial page:
**Rasa version**: Rasa 1.1.5
**Python version**: 3.6.7

**Issue**:
The interactive [tutorial page](https://rasa.com/docs/rasa/user-guide/rasa-tutorial/) of the doc, runs an older version of rasa even if you are viewing the doc for the latest version. This is confusing for some people, and someone asked [this](https://forum.rasa.com/t/domain-yml-doesnt-match-getting-started-tutorial/27888?u=saurabh-m523) question on forum. We should update the docker image so that it runs the same version of rasa as the version of the docs.

**Comment by sara-tagger** [comment]
Thanks for the issue, @tabergma will get back to you about it soon!

###### You may find help in the [docs](https://rasa.com/docs/) and the [forum,](https://forum.rasa.com/) too 🤗

**Comment by melindaloubser1** [comment]
For some reason I can't link these PRs, so here they are 
https://github.com/RasaHQ/rasa/pull/5815
https://github.com/RasaHQ/docs-binder/pull/8
