### ISSUE TITLE
Add types to entity synonyms

### ISSUE THREAD

**Issue by jamesmf** [RasaHQ/rasa#5718]
**Description of Problem**: I don't see a way to scope synonyms by type. This is important in making calls to knowledge bases that are typed.

For instance, let's say I know how to recognize two entities types, `date.month` and `finance.term`. To make sure the extracted entity values match the way I need to look those things up in a knowledge base, I use an `EntitySynonymMapper`.

But the following example shows the current shortcoming:

 "The most recent report was from APR 2019" 
 ->

 { "end": ..., "entity": "date.month", "start": ..., "value": "April" } 

But then we'd want

 "The APR on that option is 4.3%" 
 ->

 { "end": ..., "entity": "finance.term", "start": ..., "value": "AppliedPercentageRate" } 

I don't think this is possible with the existing implementation, which would map "APR" to a single synonym, regardless of the type of the entity.

**Overview of the Solution**:

Allow the `EntitySynonymMapper` to be type aware. In `"entity_synonyms"` we could add in `types`.

**Examples** (if relevant):

 "entity_synonyms": [

 { "value": "April", "types": ["date.month"] "synonyms": ["APR", "04", "april"] } 

,

 { "value": "AppliedPercentageRate", "types": ["finance.term"] "synonyms": ["APR", "applied percentage rate"] } 

,

**Definition of Done**:

*   EntitySynonymMapper can enforce optional type checking
*   A single surface form like "APR" can map to separate synonyms based on extracted entity type.

**Comment by jamesmf** [comment]
I imagine this as being an optional, additional entry. So if you had an entry in your synonyms that didn't have a type on it, it would still work. And if you had a typed entry and an untyped entry in your synonyms, the untyped would catch all the types you didn't have explicit entries for.

**Comment by jamesmf** [comment]
Perhaps a more universal example is locations (in the U.S., states) colliding with short utterances
`"OK" + "location.statecode" -> "Oklahoma"`
vs
`"OK" + "confirmation" -> "Okay"`

**Comment by sara-tagger** [comment]
Thanks for submitting this feature request 🚀 @degiz will get back to you about it soon! ✨

**Comment by jamesmf** [comment]
Any thoughts on this? If it's desired functionality I could probably get a basic PR for it, but I don't want to implement it if it's unlikely to be supported

**Comment by jamesmf** [comment]
@degiz any thoughts?

**Comment by amn41** [comment]
is this what you need? https://forum.rasa.com/t/introducing-entity-roles-and-groups/28156

**Comment by jamesmf** [comment]
@amn41 I don't think it quite solves the problem (though it's very cool functionality, I was excited when I saw it in the release notes), but correct me if I'm wrong.

I think that even if I had two separate roles for my entities, the `EntitySynonymMapper` would still synonym-ize them the same way.

**Comment by amn41** [comment]
yes, you're quite right that it would. But you could build a custom synonym mapper component to do that part

**Comment by jamesmf** [comment]
Gotcha yeah. I was just thinking it would be cool to have that as an optional feature of the default `EntitySynonymMapper` instead of writing a custom component. 

I think it would be pretty easy to keep the same basic functionality by default, and just let the synonym mapper first check to see if the type of your entity matches the type of the synonym entry. If there's no type on it, it will process the example. If there is a type and it doesn't match, it'll leave the example alone.
