### ISSUE TITLE
How can i get user name from the conversation ?

### ISSUE THREAD

**Issue by Hamza28401214** [RasaHQ/rasa#5721]
Hi, 
what i want is to get the user-name during the conversation  ,the user-name is unknown for the model , for example ; 
-What's your name?
-my name is Don
here the bot should response by , -hi done.
But this name is not included in the training data, how to deal with that?

**Comment by monatis** [comment]
You need to include some training data with, for example, "## intent:introduce" and "- My name is [xxx](username)", "- I'm [xxx](username)", and "## intent:inform" and "- [xxx](username)". However, in the real world, you need to integrate an authentication mechanism and set user info as slots.

**Comment by Hamza28401214** [comment]
aha thank you so much for your help , i'll try with the authentication mechanism .

**Comment by sara-tagger** [comment]
Thanks for the issue, @erohmensing will get back to you about it soon!

###### You may find help in the [docs](https://rasa.com/docs/) and the [forum,](https://forum.rasa.com/) too 🤗

**Comment by erohmensing** [comment]
Thanks for the suggestion @monatis. @Hamza28401214 as this is not a bug report or a feature request, if you have further questions on the topic, please ask them on the [forum](forum.rasa.com).
