### ISSUE TITLE
Add possibility to specify validation dataset

### ISSUE THREAD

**Issue by tabergma** [RasaHQ/rasa#5747]
**Description of Problem**: Currently, it is only possible to take a random split from the training data as validation data via the `evaluate_on_number_of_examples` parameter. This is not ideal for research. If we want to train/test our models on public datasets that have a validation dataset given, we cannot use that dataset as validation dataset next to our training dataset. However, this is required to compare our results to others.

**Overview of the Solution**: It should be possible to provide a validation dataset. One possible solution would be to add a new CLI argument to `rasa train`, for example, `--validation`.

**Comment by lucasalvarezlacasa** [comment]
100% agree with this.

Was it ever provided?

**Comment by m-vdb** [comment]
Hi @lucasalvarezlacasa , no it wasn't. It was closed because at the time it was mostly an internal need that lost priority. If this is something you want to see, feel free to create an Improvement ticket in our Jira board: https://rasa-open-source.atlassian.net/browse/OSS
