### ISSUE TITLE
Provide to option to prevent an entity to ever influence rasa core predictions

### ISSUE THREAD

**Issue by nbeuchat** [RasaHQ/rasa#5751]
**Description of Problem**: Having an option to completely remove an entity from the rasa core prediction would be very helpful to avoid unexpected behaviors for rarely used entities or entities that should just never change the rasa core prediction.

The current recommendation in the documentation suggests adding or removing certain entities to specific intents which is unsatisfactory for entities that should _never_ influence the rasa core prediction. This mean that we need to add `ignore_entities: ...` to every single intent just to ignore a single entity everywhere.

The second recommendation is to add an unfeaturized slots with the same name which actually but this does not prevent the entity from being featurized for the next action prediction with the current intent.

Doc: [https://rasa.com/docs/rasa/core/domains/#ignoring-entities-for-certain-intents](https://rasa.com/docs/rasa/core/domains/#ignoring-entities-for-certain-intents)

We have had several cases where our production bot failed in the first message because a random entity was detected.

**Overview of the Solution**: it would be great to be able to configure within the `entities` section of the domain file if an entity will be used for prediction or not. This could look something like:

 entities:

*   phone-number
*   email
*   amount-of-money
*   source:
     ignore_for_predictions: true

For the prediction, I suppose these entities would just be filtered out completely from the featurizer.

**Definition of Done**:

*   [ ] Tests are added
*   [ ] Feature described the docs
*   [ ] Feature mentioned in the changlog

**Comment by MichaelMarien** [comment]
Should be easy to consolidate such extra attribute in the used_entities property of the intents in domain.py. Would happy to look at this.

**Comment by sara-tagger** [comment]
Thanks for submitting this feature request 🚀 @erohmensing will get back to you about it soon! ✨

**Comment by erohmensing** [comment]
Hey @nbeuchat, thanks for bringing this up. I think you make a good point about entity featurization causing unexpected behavior in bots. This is something we're aware of and want to fix properly. 

Ideally we'd do this by providing better default behavior (e.g. if it were to learn from the stories where entity featurization is actually affecting the prediction, or something of that nature) instead of adding more hacky parameters to the domain file. We're already considering this issue for our next major release (where we can change these defaults significantly).

**Comment by Ghostvv** [comment]
It is not a research issue, it is an engineering issue of adding fields to `domain.yml` and read it correctly.

**Comment by leenaborasahaj** [comment]
Hi. 
I am also facing the same issue. Any update on this?
If not how do I handle it with current release (2.3) or 2.2?

**Comment by melindaloubser1** [comment]
This was made possible in 3.1 - see https://github.com/RasaHQ/rasa/pull/10899
