### ISSUE TITLE
AttributeError: 'Question' object has no attribute 'skip_if'

### ISSUE THREAD

**Issue by sheggamharshith** [RasaHQ/rasa#5753]
To get started quickly, an initial project will be created.
If you need some help, check out the documentation at https://rasa.com/docs/rasa.

Traceback (most recent call last):
  File "/Users/harshithsheggam/Desktop/rasa/venv/bin/rasa", line 8, in <module>
    sys.exit(main())
  File "/Users/harshithsheggam/Desktop/rasa/venv/lib/python3.7/site-packages/rasa/__main__.py", line 91, in main
    cmdline_arguments.func(cmdline_arguments)
  File "/Users/harshithsheggam/Desktop/rasa/venv/lib/python3.7/site-packages/rasa/cli/scaffold.py", line 191, in run
    default=".",
AttributeError: 'Question' object has no attribute 'skip_if'

**Comment by sheggamharshith** [comment]
can any one help me with this I am using Mac

**Comment by sara-tagger** [comment]
Thanks for raising this issue, @TyDunn will get back to you about it soon✨

###### Please also check out the [docs](https://rasa.com/docs/) and the [forum](https://forum.rasa.com/) in case your issue was raised there too 🤗

**Comment by erohmensing** [comment]
@sheggamharshith please fill out the template with the versioning info we ask for when you report a bug. can you please report the output of 
```
pip list | grep rasa
```
and 
```
pip list | grep questionary
```

**Comment by sheggamharshith** [comment]
I have resolved the bug I have re-installed the rasa project file @erohmensing  and when I have tried the grep rasa the screen just freezed for a long Time  so I could not prompt the output of It
