### ISSUE TITLE
Documentation details about how to run an external Action Server

### ISSUE THREAD

**Issue by solyarisoftware** [RasaHQ/rasa#5763]
I propose this topic as feature request, but it's also a documentation issue, as lack of details in user guide paragraph: [https://rasa.com/docs/rasa/core/actions/#custom-actions](https://rasa.com/docs/rasa/core/actions/#custom-actions).

What specified in paragraph [Execute Actions in Other Code](https://rasa.com/docs/rasa/core/actions/#id8) is obscure to me, and details at the API documentation link Action Server are also unclear.

Is the endpoint a `externalActionServer:port/webhook` POST? I wish I had a detailed description of in/out parameters in [API details page](https://rasa.com/docs/rasa/api/action-server/#operation/call_action). Maybe a pseudo curl example of call to an external sever, with few different use cases (generic custom actions, form actions, NLG actions, using dockling.., etc,) could help a lot.

Besides, I'd also add a simple example of implementation of an external server, maybe to be inserted in [https://github.com/RasaHQ/rasa/tree/master/examples](https://github.com/RasaHQ/rasa/tree/master/examples), maybe something like the "formbot", realized awith an external action server built in node ![](/images/icons/emoticons/smile.png)

> Note: I guess there is a huge number of developers interested to use RASA but to build actions not built in Python but in other languages (e.g. Java and especially in nodejs), for obvious reasons (connection with legacy sw, previous made backend logics, etc.). I'd do all possible to break barriers for incoming developers in any not-python language, allowing them to enter the splendid RASA ecosystem ![](/images/icons/emoticons/smile.png)

**Comment by sara-tagger** [comment]
Thanks for submitting this feature request 🚀 @amn41 will get back to you about it soon! ✨

**Comment by akelad** [comment]
Hi @solyarisoftware, sorry we missed this issue. Agreed that the API documentation for the action server could be clearer. We will be working on this in the future, as well as generally making it easier for actions to be written in a language other than python (e.g. https://github.com/RasaHQ/rasa/issues/5357). Stay tuned for this in the next few months

**Comment by DinushikaSKMMM** [comment]
Hi @akelad

Can help me with this issue?
I have to run an external Action Server. Please help me.

**Comment by solyarisoftware** [comment]
Hi @DinushikaSKMMM, 

What's your issue exactly?

Now https://rasa.com/docs/rasa/pages/action-server-api API documentation describe a bit better than in past the POST payload :

```
{
  "next_action": "string",
  "sender_id": "string",
  "tracker": {
    "conversation_id": "default",
    "slots": [
      {
        "slot_name": "slot_value"
      }
    ],
    "latest_message": {
      "entities": [
        {
          "start": 0,
          "end": 0,
          "value": "string",
          "entity": "string",
          "confidence": 0
        }
      ],
      "intent": {
        "confidence": 0.6323,
        "name": "greet"
      },
      "intent_ranking": [
        {
          "confidence": 0.6323,
          "name": "greet"
        }
      ],
      "text": "Hello!"
    },
    "latest_event_time": 1537645578.314389,
    "followup_action": "string",
    "paused": false,
    "events": [
      {
        "event": "slot",
        "timestamp": 1559744410
      }
    ],
    "latest_input_channel": "rest",
    "latest_action_name": "action_listen",
    "latest_action": {
      "action_name": "string",
      "action_text": "string"
    },
    "active_loop": {
      "name": "restaurant_form"
    }
  },
  "domain": {
    "config": {
      "store_entities_as_slots": false
    },
    "intents": [
      {
        "property1": {
          "use_entities": true
        },
        "property2": {
          "use_entities": true
        }
      }
    ],
    "entities": [
      "person",
      "location"
    ],
    "slots": {
      "property1": {
        "auto_fill": true,
        "initial_value": "string",
        "type": "string",
        "values": [
          "string"
        ]
      },
      "property2": {
        "auto_fill": true,
        "initial_value": "string",
        "type": "string",
        "values": [
          "string"
        ]
      }
    },
    "responses": {
      "property1": {
        "text": "string"
      },
      "property2": {
        "text": "string"
      }
    },
    "actions": [
      "action_greet",
      "action_goodbye",
      "action_listen"
    ]
  }
}
```


---

In general: to @akelad, RASA team, 

Regarding the external action server,  is not fully clear the I/O interfaces life-cycle. 
Examples could help a lot! Especially for who want to develop an action server NOT build in Python.
My proposal is to supply few different common use cases, e.g.

- external form action 
- database data retrieval
- Question / answering
- NLG templating 
- etc. etc. 

BTW, do you have news (now in RASA 2..0) about API documentation remake?
IMMO, a clearer API documentation, not just about the Action Server but also regarding the RASA NLU and RASA Core. See by examples issues: 
- https://github.com/RasaHQ/rasa/issues/5768#event-3777903015 
- https://github.com/RasaHQ/rasa/issues/5749#issuecomment-667974484 
- https://github.com/RasaHQ/rasa/issues/4683#issuecomment-667657208

As Node.Js developer I would more than happy to contribute/collaborate about node system integration patterns etc.

----

"Business" suggestion:
Please do not underestimate the value to let accessible RASA platform outside the Python developers ecosystem! Facilitating system integration of great RASA, you will conquer another 50% of market share ;-)

Thanks
giorgio

**Comment by akelad** [comment]
> "Business" suggestion:
Please do not underestimate the value to let accessible RASA platform outside the Python developers ecosystem! Facilitating system integration of great RASA, you will conquer another 50% of market share ;-)

One of our goals of the 2.0 release was exactly that, to make it easier for non python developers to build action servers :) 

Thanks for your suggestions Giorgio, @erohmensing I'll let you comment on the action server/API docs suggestions

**Comment by llermaly** [comment]
yup. 

I created a nodejs simple server with the /webhook endpoint ready to receive rasa, then I configured it in endpoints.yml 

`action_endpoint:
  url: "http://localhost:3000/webhook"`

the action is triggered but the server is not hit, seems like is trying to use the actions.py file , documentation doesnt help 

do I need to set something in actions.py ? 
do I need to run the actions server command from rasa even if I'm launching my own server?

I'm trying my bot with rasa shell command by the way

thanks

**Comment by solyarisoftware** [comment]
Hi @llermaly 

I believe you have to run from command line:
```
rasa run actions
```

See also:
- https://rasa.com/docs/action-server/#other-action-servers
- https://rasa.com/docs/action-server/pages/action-server-api

let me know

giorgio

**Comment by llermaly** [comment]
thanks @solyarisoftware I ended up using actions.py , still dont know why my nodejs server didnt work

**Comment by goforbg** [comment]
@solyarisoftware saw your comments on a couple of threads at the forum and here, do you have a simple github repo of node js working with python? Would really appreciate your help!

**Comment by solyarisoftware** [comment]
hi @goforbg 
I currently don't have a nodejs repo integration example. 
I confess I passed using python as a main programming language to do NLP stuff.
 Nevertheless I please you / all RASA devs to support not Python languages.
 Maybe you can upvote my initial thread here.

**Comment by goforbg** [comment]
@solyarisoftware Aww that's sad 😭 I really just need an example of how it could work with Node JS
