### ISSUE TITLE
add missing attachment types to Facebook channel

### ISSUE THREAD

**Issue by K1mz** [RasaHQ/rasa#5766]
**Description of Problem**:
If a user sends a voice message to the bot using Facebook users messages text will be the attachments URL. This is not done for the other attachment types(image, video, and file).

**Solution**:
I have forked and done the same for the missing attachment types(image, video, and file).

Can I create a new PR for this?

**Comment by sara-tagger** [comment]
Thanks for submitting this feature request 🚀 @tttthomasssss will get back to you about it soon! ✨

**Comment by Archish27** [comment]
@K1mz Yes go ahead 👍

**Comment by wochinge** [comment]
fixed by https://github.com/RasaHQ/rasa/pull/5899
