### ISSUE TITLE
RasaX cert issue connecting to cloud Postgres DB

### ISSUE THREAD

**Issue by tatianafrank** [RasaHQ/rasa#5769]
**Rasa version**:1.9.5

**Rasa SDK version** (if used & relevant):

**Rasa X version** (if used & relevant):  0.27.4

**Python version**: rasa x docker image

**Operating system** (windows, osx, ...): rasa x docker image

**Issue**:
We’re trying to connect Rasa X to a could instance of postgres DB but getting this error. (The postgres instance is v10) It's asking for a cert but we don’t see a place to add the cert in the helm chart config.

**Error (including full traceback)**:

```
sqlalchemy.exc.OperationalError: (psycopg2.OperationalError) 
could not open certificate file "/root/.postgresql/postgresql.crt": 
Permission denied FATAL:  no pg_hba.conf entry for host "xxx.xxx.xxx.xxx", user 
".......", database ".....", SSL off
```

**Command or request that led to error**:
```

```

**Comment by sara-tagger** [comment]
Thanks for raising this issue, @tttthomasssss will get back to you about it soon✨

###### Please also check out the [docs](https://rasa.com/docs/) and the [forum](https://forum.rasa.com/) in case your issue was raised there too 🤗

**Comment by tatianafrank** [comment]
thanks @tttthomasssss

**Comment by tatianafrank** [comment]
just following up @tttthomasssss

**Comment by tttthomasssss** [comment]
Hi @tatianafrank - sorry for the delayed reply. We'll look into this shortly!

**Comment by m-vdb** [comment]
Hello @tatianafrank , by taking a closer look at your traceback `Permission denied FATAL:  no pg_hba.conf entry for host ...` tells me that it's possible that your cloud database is not properly configured to accept connections from Rasa X host. Is this something that you can double-check?

If this is something you already checked, could you provide details about how you setup the connection to your Postgres database in Rasa X? (without secrets / IPs of course)

**Comment by tglawless** [comment]
Connectivity to the database works, but a self-signed certificate is required.  For example, from a client machine...

```bash
$ PGSSLROOTCERT=/cert.crt psql "host=$PGHOST port=$PGPORT dbname=$PGDBNAME user=$PGUSERNAME sslmode=verify-full"
psql (12.2 (Debian 12.2-2.pgdg100+1))
SSL connection (protocol: TLSv1.2, cipher: ECDHE-RSA-AES256-GCM-SHA384, bits: 256, compression: off)
```

In this cases, the `cert.crt` file contains a self-signed certificate generated by the cloud provider.  How would be include this certificate in the Rasa X Helm chart?

**Comment by m-vdb** [comment]
I've taken a closer look at our code and the helm chart configuration, and I don't think this is something we support today. Am I right @wochinge ?

**Comment by wochinge** [comment]
I assume you specified the paths to the self-signed certificates via the `DB_URL` environment variable @tatianafrank ? Great job in figuring that out! I think at this point it's just a permissions error. The `rasa-x` image doesn't run as `root`. On Kubernetes the user is `1001`, but this depends a bit on your cluster configuration. 

In general this is not related to the Helm chart, but rather Rasa X itself.

**Comment by tglawless** [comment]
@wochinge The path to the certificate is specified using the `PGSSLROOTCERT` environment variable in the example above.

The Helm chart would need to be updated to allow us to mount a secret containing the certificate as well as define an environment variable containing the path of the mounted secret.  The path environment variable could be calculated or hard coded, but I don't see a way around a secret containing the certificate.

**Comment by tatianafrank** [comment]
@wochinge following up on the comment above (@tglawless and I are working on this together)

**Comment by wochinge** [comment]
> the Helm chart would need to be updated to allow us to mount a secret containing the certificate as well as define an environment variable containing the path of the mounted secret

Makes sense 👍 Defining the env variable is also possible, so we'd only need to add some values for extra volume mounts. Do you want to make the PR to the Helm chart (we can give you feedback / assistance) or should we handle it?

**Comment by erohmensing** [comment]
@m-vdb our helm charts contain support for arbitrary env vars and volume mounts, so i suppose we can close this?
