### ISSUE TITLE
ERROR

### ISSUE THREAD

**Issue by HarshitaSahai** [RasaHQ/rasa#5770]
ERROR: rasa-core 0.14.5 has requirement rasa-core-sdk~=0.14, but you'll have rasa-core-sdk 0.13.1 which is incompatible.

I have installed python 3.5  
Tried changing requirement with the latest version of rasa-core
 
Also having   ERROR: Failed building wheel for cytoolz this as well

**Comment by sara-tagger** [comment]
Thanks for raising this issue, @wochinge will get back to you about it soon✨

###### Please also check out the [docs](https://rasa.com/docs/) and the [forum](https://forum.rasa.com/) in case your issue was raised there too 🤗

**Comment by wochinge** [comment]
@HarshitaSahai `rasa-core` was deprecated about a year ago. I recommend migrating to the `rasa` package which unifies `rasa-core` and `rasa-nlu` and makes a lot of things way easier.
