### ISSUE TITLE
Requirement.txt

### ISSUE THREAD

**Issue by HarshitaSahai** [RasaHQ/rasa#5771]
I'm trying to implement https://github.com/RasaHQ/medicare_locator/blob/master/requirements.txt it shows different issues I was suggested by your team member to install rasa package I have done that now shall I not run the requirement file as the version specified here and one in the package are completely different?

Please help URGENT 
Thanks

**Comment by vishnupriyavr** [comment]
Hi @HarshitaSahai, Can you please help and provide more details on the below:
1. What were the issues that you were facing initially with requirements.txt?
2. Is it working fine now after installing rasa package, as suggested by the team member?

**Comment by HarshitaSahai** [comment]
def _load_tf_config(config: Dict[Text, Any]) -> Optional[tf.ConfigProto]:
AttributeError: module 'tensorflow' has no attribute 'ConfigProto'
make: *** [train-core] Error 1

The error is now showing the file which I'm currently using is not having the required attribute aa I think it must be designed using the previous version of TensorFlow.
What should I do now? Please help I have installed the latest package as suggested

**Comment by vishnupriyavr** [comment]
Hi @HarshitaSahai, the error you are getting is due to the usage of Tensor flow 2.x version, please install the tensorflow version as per requirements.txt, which is as below:
'''
tensorflow==1.12.0
'''

**Comment by HarshitaSahai** [comment]
So the problem in doing this is:
1. Python 3.7 : supports rasa but not tensorflow = 1.12.0
2. Python 3.5: supports tensorflow but not some packages in rasa. ( Using cached python_socketio-4.5.1-py2.py3-none-any.whl (51 kB))

Can you recommend the version I should use that will not lead to the error?

**Comment by sara-tagger** [comment]
Thanks for the issue, @TyDunn will get back to you about it soon!

###### You may find help in the [docs](https://rasa.com/docs/) and the [forum,](https://forum.rasa.com/) too 🤗

**Comment by TyDunn** [comment]
@HarshitaSahai The project is set up for `rasa-core-sdk~=0.13.1`, `rasa_core~=0.13.8`, and `rasa_nlu~=0.14.6`. Did you install these versions?

**Comment by HarshitaSahai** [comment]
I was advised to install rasa package did that and I guess it has installed the above mentioned (have checked they are present).
 Now I'm getting :
python3 -m rasa_core.train -d domain.yml -s data/core -o models/current/dialogue -c core_config.yml
Traceback (most recent call last):
  File "C:\Python35\lib\runpy.py", line 170, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\Python35\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Python35\lib\site-packages\rasa_core\train.py", line 6, in <module>
    from rasa_core import config, cli
  File "C:\Python35\lib\site-packages\rasa_core\config.py", line 3, in <module>
    from typing import Optional, Text, List
ImportError: cannot import name 'Text'
make: *** [train-core] Error 1

**Comment by TyDunn** [comment]
@HarshitaSahai When you say you installed Rasa Open Source, all you did was follow [these steps](https://github.com/RasaHQ/medicare_locator#-how-to-install-and-setup-medicare-locator)? Running `pip install -r requirements.txt` will install the versions I mentioned above

**Comment by HarshitaSahai** [comment]
Yes then I got the  error that this rasa version doesn't; support the json version and for some other packages as well so I installed the version specified by them 

## Setup py requirements
jsonpickle==1.0.0
six==1.11.0
redis==2.10.6
fakeredis==0.10.3
future==0.17.1
numpy~=1.16.0
typing==3.6.6
ruamel.yaml==0.15.85
requests~=2.2
tensorflow==1.12.0
h5py==2.7.1
apscheduler==3.5.1
tqdm==4.29.1
ConfigArgParse==0.13.0
networkx==2.2
pykwalify==1.7.0
coloredlogs==10.0
flask==1.0.2
flask_cors==3.0.7
scikit-learn==0.20.2
rasa_nlu~=0.14.6
colorhash==1.0.2
pika==0.12.0
jsonschema==2.6.0
packaging~=18.0
gevent==1.4
pytz==2018.9
rasa-core-sdk~=0.12.2
rasa_core~=0.13.8
pymongo==3.7.2
python-dateutil==2.7.5
spacy~=2.0.18
sklearn_crfsuite==0.3.6
keras-applications==1.0.6
keras-preprocessing==1.0.5


and it lead to above error in both 3.5 and 3.6

**Comment by HarshitaSahai** [comment]
Problem solved 
If anyone is facing the problem run using administrator as well as run the make command in make file and not the one shown in readme
