### ISSUE TITLE
Not getting response from Rasa when chat with FB messenger

### ISSUE THREAD

**Issue by Prasanthmv** [RasaHQ/rasa#5773]
I have done the setup as says in Facebook Messenger. But not getting the response in FB messenger when type Hi, Hello, etc?

Is there anything additional I need to do.please help

**Comment by vishnupriyavr** [comment]
Hi @Prasanthmv  Can you be more specific about what steps you have followed and which source documentation have you referred to while following the steps?

**Comment by Prasanthmv** [comment]
@vishnupriyavr  I have followed https://rasa.com/docs/rasa/user-guide/connectors/facebook-messenger/

exactly same steps I followed

**Comment by sara-tagger** [comment]
Thanks for the issue, @akelad will get back to you about it soon!

###### You may find help in the [docs](https://rasa.com/docs/) and the [forum,](https://forum.rasa.com/) too 🤗

**Comment by akelad** [comment]
Hi @Prasanthmv please fill out the issue template with the rasa version you're using etc. And can you post your logs from rasa as well?
