### ISSUE TITLE
rasa export only exports events since latest session_started event

### ISSUE THREAD

**Issue by erohmensing** [RasaHQ/rasa#5787]
**Rasa version**:
master (2de28adb36953996e5af7414ed9dd61534441231)

**Rasa X version** (if used & relevant):
0.28.1

**Issue**:
When exporting conversations from the tracker store, only the events since the latest session_started event are pulled. This is because by default, the SQLTrackerStore.retrieve() pulls events since the latest session_started event https://github.com/RasaHQ/rasa/blob/master/rasa/core/tracker_store.py#L876-L877

**Command or request that led to error**:
```
rasa export --conversation-ids <convo with sessions>
```

https://rasa-hq.slack.com/files/UF8DBRQ6M/F0137CW1HS6/image.png?origin_team=T0GHWFTS8&origin_channel=C36SS4N8M

**Comment by erohmensing** [comment]
I believe you can use rasa export with any tracker store, so ideally the parameter to retrieve the entire history (versus just the session) would be implemented on all tracker stores/on the base class

**Comment by wochinge** [comment]
@ricwo `medium` or `high`?
