### ISSUE TITLE
rasa recent bug in mitie ner

### ISSUE THREAD

**Issue by jjyock** [RasaHQ/rasa#5798]
**Rasa version**:Rasa 1.10.0

**Python version**:3.7.0

**Operating system** (windows, osx, ...): linux

**Issue**:
the MitieEntityExtractor can recognize the category but the start and end are always the total sentence.
the training
"entities": [
    {
      "entity": "disease",
      "value": "感冒了该吃什么药",
      "start": 0,
      "end": 8,
      "confidence": null,
      "extractor": "MitieEntityExtractor"
    }

**Error (including full traceback)**:
```

```

**Command or request that led to error**:
```

```
nlu.json

{
  "rasa_nlu_data": {
    "common_examples": [
      {
        "text": "感冒了该吃什么药",
        "intent": "medicine",
        "entities": [
          {
            "start": 0,
            "end": 2,
            "value": "感冒",
            "entity": "disease"
          }
        ]
      },
      {
        "text": "我便秘了，该吃什么药",
        "intent": "medicine",
        "entities": [
          {
            "start": 1,
            "end": 3,
            "value": "便秘",
            "entity": "disease"
          }
        ]
      }
    ]
  }
}

**Comment by sara-tagger** [comment]
Thanks for raising this issue, @wochinge will get back to you about it soon✨

###### Please also check out the [docs](https://rasa.com/docs/) and the [forum](https://forum.rasa.com/) in case your issue was raised there too 🤗

**Comment by jk123vip** [comment]
Got the same problem and don't know how to fix it ...

**Comment by wochinge** [comment]
Thanks, for bringing this up. Seems to be a bug. Do you want to fix it (I'd be available for help / feedback) or should we?

**Comment by jjyock** [comment]
> Thanks, for bringing this up. Seems to be a bug. Do you want to fix it (I'd be available for help / feedback) or should we?

yes, maybe I can help to fix this bug, Do you want me to help?

**Comment by jk123vip** [comment]
It seems that the problem is in python environment or some dependent packages, because after using anaconda environment reinstalled rasa, this bug went away.

**Comment by jjyock** [comment]
> It seems that the problem is in python environment or some dependent packages, because after using anaconda environment reinstalled rasa, this bug went away.

@jk123vip  you also met the same problem? thank you!

**Comment by wochinge** [comment]
Which mitie versions did you use and where did you install it from?

**Comment by jk123vip** [comment]
Try update your rasa to version 1.10.1
