### ISSUE TITLE
Response Selectors: multiline text as answer

### ISSUE THREAD

**Issue by solyarisoftware** [RasaHQ/rasa#5800]
Hi, that's a Response Selectors change request.

---

I would like to use Response Selector for a FAQ system where **answers are multiline texts**, not just a single lines.

Take this Q/A example, where question is:

> How to follow people on Twitter?

and the corresponding answer (real example from twitter.com FAQ):

>     1. Find a Tweet from the account you’d like to follow. 
>     2. Hover your mouse over their name.
>     3. Click the  **Follow**  button.
> 
>     OR 
> 
>     1. Navigate to a Tweet from the account you’d like to follow. 
>     2. Tap the  icon located at the top of the Tweet.
>     3. Tap  **Follow**  from the selection menu.

So far I can not manage well this multiline textual answer with `data/responses.md` Response Selector markdown format.  As far as I see I can just have 1 line for the answer.  

**Workaround**
The workaround I found is to insert `\n` char explicitly. So the mentioned case could be:

    (venv) $ cat data/responses.md

    ## ask languages
    * faq/ask_how_to_follow_people_on_twitter
      - 1. Find a Tweet from the account you’d like to follow.\n     2. Hover your mouse over their name.\n     3. Click the  **Follow**  button.\n \n     OR \n\n     1. Navigate to a Tweet from the account you’d like to follow.\n      2. Tap the  icon located at the top of the Tweet. \n     3. Tap  **Follow**  from the selection menu.

    ## ask blablabla
    * faq/ask_blablabla
      - blablabla\nblablabla\nblablabla

Pretty unreadable, isn't it? It "works" but I don't like that for many reasons:
 
* the answers on  `data/responses.md` file become unreadable!  
* I need to write a script that convert FAQs in markdawn substituting newline with `\n`s.
* using rasa cli commands  (`rasa shell`) conversation tests, I got the unreadable single line compacted texts :/

---

My 2 requests:

1. Can I have FAQ answers in responses.md that are composed by a multi-line text (reported "as" wrote in the markdown file, possibly avoiding to insert `'\n'`)?

2. What's the best way to manage Response Selectors answers in case of long texts answers (say  many lines of text ~ a page/paragraph)? 

   Change Request, It could be great if I could just mention **external texts path/filenames in responses file**; like this:

       
        ## answers in external text (.txt/.markdown format) file
        * faq/ask_topic_1
          - path/to/topic_1.txt

See also conversation in [RASA forum](https://forum.rasa.com/t/response-selectors-how-to-reply-multiline-texts/28412/2?u=solyarisoftware)

thanks<br>giorgio

**Comment by sara-tagger** [comment]
Thanks for submitting this feature request 🚀 @rctatman will get back to you about it soon! ✨

**Comment by wochinge** [comment]
@dakshvar22 This is fixed with Rasa Open Source 2.0
