### ISSUE TITLE
Do a reverse engineering for the Rasa visualize

### ISSUE THREAD

**Issue by ForgetThatNight** [RasaHQ/rasa#5804]
The "Rasa Visualize " can transform training data into graphs. Now our product manager has given me a requirement that transforms graphs into training data. The existing architecture should be able to meet this requirement, Is there any God who can offer us a plan

**Comment by sara-tagger** [comment]
Thanks for submitting this feature request 🚀 @akelad will get back to you about it soon! ✨

**Comment by akelad** [comment]
Hi @ForgetThatNight, this is not something that's part of the Rasa Open Source library (or will be in the near future), but there are external tools you can use to do this that integrate with Rasa:
* [Botsociety](https://botsociety.io/)
* [Botmock](https://botmock.com/)
