### ISSUE TITLE
Obfuscate passwords

### ISSUE THREAD

**Issue by rgstephens** [RasaHQ/rasa#5805]
Database passwords are written to the log when verbose logging is enabled.

**Rasa version**: 1.9.5

**Issue**:
Passwords should not be written in clear text to the log.

**Comment by akelad** [comment]
@rgstephens do you have details of where the passwords get logged? As in, at which stage of the start up?

**Comment by rgstephens** [comment]
Here's an example log message (I've replaced the password with asterisks):

```
DEBUG    rasa.core.tracker_store  - Attempting to connect to database via 'postgresql://admin:****************@db:5432/rasa'
```

**Comment by Yaminick** [comment]
This looks pretty simple, I can open a PR as a first contribution. Wondering if/how it makes sense to test for this?
