### ISSUE TITLE
Telegram Bot Urgent

### ISSUE THREAD

**Issue by HarshitaSahai** [RasaHQ/rasa#5807]
Created the server and bot as explained but bot not responding what to do? 
use commands such as /help /start

t.me/med360bot

**Comment by sara-tagger** [comment]
Thanks for the issue, @Ghostvv will get back to you about it soon!

###### You may find help in the [docs](https://rasa.com/docs/) and the [forum,](https://forum.rasa.com/) too 🤗

**Comment by erohmensing** [comment]
This is not a Rasa bug but a usage question, please ask it on our [forum](forum.rasa.com).
