### ISSUE TITLE
Unable train in rasa x UI

### ISSUE THREAD

**Issue by Wing-e7** [RasaHQ/rasa#5810]
**Rasa version**: 1.9.5

**Rasa SDK version** (if used & relevant):

**Rasa X version** : 0.28.0

**Python version**: 3.7

**Operating system** (windows, osx, ...): windows / anaconda virtual env

**Issue**: Unable to train model in rasa x 

**Error (including full traceback)**:
```
2020-05-13 20:21:18 ERROR    sanic.root  - Exception occurred while handling uri: 'http://localhost:5002/api/projects/default/models/jobs'
Traceback (most recent call last):
  File "c:\users\collegedunia\anaconda3\lib\site-packages\sanic\app.py", line 976, in handle_request
    response = await response
  File "c:\users\collegedunia\anaconda3\lib\site-packages\rasax\community\api\decorators.py", line 205, in decorated_function
    return await await_and_return_response(args, kwargs, request)
  File "c:\users\collegedunia\anaconda3\lib\site-packages\rasax\community\api\decorators.py", line 135, in await_and_return_response
    response = await response
  File "c:\users\collegedunia\anaconda3\lib\site-packages\rasax\community\api\blueprints\models.py", line 191, in train_model
    content = await stack_service.start_training_process()
  File "c:\users\collegedunia\anaconda3\lib\site-packages\rasax\community\services\stack_service.py", line 352, in start_training_process
    nlu_training_data = nlu_training_data.filter_training_examples(
AttributeError: 'TrainingData' object has no attribute 'filter_training_examples'
2020-05-13 20:21:45 ERROR    sanic.root  - Exception occurred while handling uri: 'http://localhost:5002/api/projects/default/models/jobs'
Traceback (most recent call last):
  File "c:\users\collegedunia\anaconda3\lib\site-packages\sanic\app.py", line 976, in handle_request
    response = await response
  File "c:\users\collegedunia\anaconda3\lib\site-packages\rasax\community\api\decorators.py", line 205, in decorated_function
    return await await_and_return_response(args, kwargs, request)
  File "c:\users\collegedunia\anaconda3\lib\site-packages\rasax\community\api\decorators.py", line 135, in await_and_return_response
    response = await response
  File "c:\users\collegedunia\anaconda3\lib\site-packages\rasax\community\api\blueprints\models.py", line 191, in train_model
    content = await stack_service.start_training_process()
  File "c:\users\collegedunia\anaconda3\lib\site-packages\rasax\community\services\stack_service.py", line 352, in start_training_process
    nlu_training_data = nlu_training_data.filter_training_examples(
AttributeError: 'TrainingData' object has no attribute 'filter_training_examples'
2020-05-13 20:25:31 ERROR    sanic.root  - Exception occurred while handling uri: 'http://localhost:5002/api/projects/default/models/jobs'
Traceback (most recent call last):
  File "c:\users\collegedunia\anaconda3\lib\site-packages\sanic\app.py", line 976, in handle_request
    response = await response
  File "c:\users\collegedunia\anaconda3\lib\site-packages\rasax\community\api\decorators.py", line 205, in decorated_function
    return await await_and_return_response(args, kwargs, request)
  File "c:\users\collegedunia\anaconda3\lib\site-packages\rasax\community\api\decorators.py", line 135, in await_and_return_response
    response = await response
  File "c:\users\collegedunia\anaconda3\lib\site-packages\rasax\community\api\blueprints\models.py", line 191, in train_model
    content = await stack_service.start_training_process()
  File "c:\users\collegedunia\anaconda3\lib\site-packages\rasax\community\services\stack_service.py", line 352, in start_training_process
    nlu_training_data = nlu_training_data.filter_training_examples(
AttributeError: 'TrainingData' object has no attribute 'filter_training_examples'
2020-05-13 20:25:42 ERROR    sanic.root  - Exception occurred while handling uri: 'http://localhost:5002/api/projects/default/models/jobs'
Traceback (most recent call last):
  File "c:\users\collegedunia\anaconda3\lib\site-packages\sanic\app.py", line 976, in handle_request
    response = await response
  File "c:\users\collegedunia\anaconda3\lib\site-packages\rasax\community\api\decorators.py", line 205, in decorated_function
    return await await_and_return_response(args, kwargs, request)
  File "c:\users\collegedunia\anaconda3\lib\site-packages\rasax\community\api\decorators.py", line 135, in await_and_return_response
    response = await response
  File "c:\users\collegedunia\anaconda3\lib\site-packages\rasax\community\api\blueprints\models.py", line 191, in train_model
    content = await stack_service.start_training_process()
  File "c:\users\collegedunia\anaconda3\lib\site-packages\rasax\community\services\stack_service.py", line 352, in start_training_process
    nlu_training_data = nlu_training_data.filter_training_examples(
AttributeError: 'TrainingData' object has no attribute 'filter_training_examples'
```

**Command or request that led to error**:
```
rasa x [ Tried to train the model after a successful conversation -- was also able to run a custom action ]
```

**Content of configuration file (config.yml)** (if relevant):
```yml
# Configuration for Rasa NLU.
# https://rasa.com/docs/rasa/nlu/components/
language: en
pipeline:
  - name: sentiment.SentimentAnalyzer
  - name: WhitespaceTokenizer
  - name: RegexFeaturizer
  - name: LexicalSyntacticFeaturizer
  - name: CountVectorsFeaturizer
  - name: CountVectorsFeaturizer
    analyzer: "char_wb"
    min_ngram: 1
    max_ngram: 4
  - name: DIETClassifier
    epochs: 100
  - name: EntitySynonymMapper
  - name: ResponseSelector
    epochs: 100

# Configuration for Rasa Core.
# https://rasa.com/docs/rasa/core/policies/
policies:
  - name: MemoizationPolicy
  - name: TEDPolicy
    max_history: 5
    epochs: 100
  - name: MappingPolicy
  - name: FormPolicy
```

**Comment by sara-tagger** [comment]
Thanks for raising this issue, @tmbo will get back to you about it soon✨

###### Please also check out the [docs](https://rasa.com/docs/) and the [forum](https://forum.rasa.com/) in case your issue was raised there too 🤗

**Comment by code-jam20** [comment]
Is this fixed? I am facing a similar issue.

**Comment by exairon** [comment]
> **Rasa version**: 1.9.5
> 
> **Rasa SDK version** (if used & relevant):
> 
> **Rasa X version** : 0.28.0
> 
> **Python version**: 3.7
> 
> **Operating system** (windows, osx, ...): windows / anaconda virtual env
> 
> **Issue**: Unable to train model in rasa x
> 
> **Error (including full traceback)**:
> 
> ```
> 2020-05-13 20:21:18 ERROR    sanic.root  - Exception occurred while handling uri: 'http://localhost:5002/api/projects/default/models/jobs'
> Traceback (most recent call last):
>   File "c:\users\collegedunia\anaconda3\lib\site-packages\sanic\app.py", line 976, in handle_request
>     response = await response
>   File "c:\users\collegedunia\anaconda3\lib\site-packages\rasax\community\api\decorators.py", line 205, in decorated_function
>     return await await_and_return_response(args, kwargs, request)
>   File "c:\users\collegedunia\anaconda3\lib\site-packages\rasax\community\api\decorators.py", line 135, in await_and_return_response
>     response = await response
>   File "c:\users\collegedunia\anaconda3\lib\site-packages\rasax\community\api\blueprints\models.py", line 191, in train_model
>     content = await stack_service.start_training_process()
>   File "c:\users\collegedunia\anaconda3\lib\site-packages\rasax\community\services\stack_service.py", line 352, in start_training_process
>     nlu_training_data = nlu_training_data.filter_training_examples(
> AttributeError: 'TrainingData' object has no attribute 'filter_training_examples'
> 2020-05-13 20:21:45 ERROR    sanic.root  - Exception occurred while handling uri: 'http://localhost:5002/api/projects/default/models/jobs'
> Traceback (most recent call last):
>   File "c:\users\collegedunia\anaconda3\lib\site-packages\sanic\app.py", line 976, in handle_request
>     response = await response
>   File "c:\users\collegedunia\anaconda3\lib\site-packages\rasax\community\api\decorators.py", line 205, in decorated_function
>     return await await_and_return_response(args, kwargs, request)
>   File "c:\users\collegedunia\anaconda3\lib\site-packages\rasax\community\api\decorators.py", line 135, in await_and_return_response
>     response = await response
>   File "c:\users\collegedunia\anaconda3\lib\site-packages\rasax\community\api\blueprints\models.py", line 191, in train_model
>     content = await stack_service.start_training_process()
>   File "c:\users\collegedunia\anaconda3\lib\site-packages\rasax\community\services\stack_service.py", line 352, in start_training_process
>     nlu_training_data = nlu_training_data.filter_training_examples(
> AttributeError: 'TrainingData' object has no attribute 'filter_training_examples'
> 2020-05-13 20:25:31 ERROR    sanic.root  - Exception occurred while handling uri: 'http://localhost:5002/api/projects/default/models/jobs'
> Traceback (most recent call last):
>   File "c:\users\collegedunia\anaconda3\lib\site-packages\sanic\app.py", line 976, in handle_request
>     response = await response
>   File "c:\users\collegedunia\anaconda3\lib\site-packages\rasax\community\api\decorators.py", line 205, in decorated_function
>     return await await_and_return_response(args, kwargs, request)
>   File "c:\users\collegedunia\anaconda3\lib\site-packages\rasax\community\api\decorators.py", line 135, in await_and_return_response
>     response = await response
>   File "c:\users\collegedunia\anaconda3\lib\site-packages\rasax\community\api\blueprints\models.py", line 191, in train_model
>     content = await stack_service.start_training_process()
>   File "c:\users\collegedunia\anaconda3\lib\site-packages\rasax\community\services\stack_service.py", line 352, in start_training_process
>     nlu_training_data = nlu_training_data.filter_training_examples(
> AttributeError: 'TrainingData' object has no attribute 'filter_training_examples'
> 2020-05-13 20:25:42 ERROR    sanic.root  - Exception occurred while handling uri: 'http://localhost:5002/api/projects/default/models/jobs'
> Traceback (most recent call last):
>   File "c:\users\collegedunia\anaconda3\lib\site-packages\sanic\app.py", line 976, in handle_request
>     response = await response
>   File "c:\users\collegedunia\anaconda3\lib\site-packages\rasax\community\api\decorators.py", line 205, in decorated_function
>     return await await_and_return_response(args, kwargs, request)
>   File "c:\users\collegedunia\anaconda3\lib\site-packages\rasax\community\api\decorators.py", line 135, in await_and_return_response
>     response = await response
>   File "c:\users\collegedunia\anaconda3\lib\site-packages\rasax\community\api\blueprints\models.py", line 191, in train_model
>     content = await stack_service.start_training_process()
>   File "c:\users\collegedunia\anaconda3\lib\site-packages\rasax\community\services\stack_service.py", line 352, in start_training_process
>     nlu_training_data = nlu_training_data.filter_training_examples(
> AttributeError: 'TrainingData' object has no attribute 'filter_training_examples'
> ```
> 
> **Command or request that led to error**:
> 
> ```
> rasa x [ Tried to train the model after a successful conversation -- was also able to run a custom action ]
> ```
> 
> **Content of configuration file (config.yml)** (if relevant):
> 
> ```yaml
> # Configuration for Rasa NLU.
> # https://rasa.com/docs/rasa/nlu/components/
> language: en
> pipeline:
>   - name: sentiment.SentimentAnalyzer
>   - name: WhitespaceTokenizer
>   - name: RegexFeaturizer
>   - name: LexicalSyntacticFeaturizer
>   - name: CountVectorsFeaturizer
>   - name: CountVectorsFeaturizer
>     analyzer: "char_wb"
>     min_ngram: 1
>     max_ngram: 4
>   - name: DIETClassifier
>     epochs: 100
>   - name: EntitySynonymMapper
>   - name: ResponseSelector
>     epochs: 100
> 
> # Configuration for Rasa Core.
> # https://rasa.com/docs/rasa/core/policies/
> policies:
>   - name: MemoizationPolicy
>   - name: TEDPolicy
>     max_history: 5
>     epochs: 100
>   - name: MappingPolicy
>   - name: FormPolicy
> ```

I think this error is because rasa and rasa-x are not compatible. Please check https://rasa.com/docs/rasa-x/changelog/compatibility-matrix/

**Comment by fatihtashan** [comment]
> **Rasa version**: 1.9.5
> 
> **Rasa SDK version** (if used & relevant):
> 
> **Rasa X version** : 0.28.0
> 
> **Python version**: 3.7
> 
> **Operating system** (windows, osx, ...): windows / anaconda virtual env
> 
> **Issue**: Unable to train model in rasa x
> 
> **Error (including full traceback)**:
> 
> ```
> 2020-05-13 20:21:18 ERROR    sanic.root  - Exception occurred while handling uri: 'http://localhost:5002/api/projects/default/models/jobs'
> Traceback (most recent call last):
>   File "c:\users\collegedunia\anaconda3\lib\site-packages\sanic\app.py", line 976, in handle_request
>     response = await response
>   File "c:\users\collegedunia\anaconda3\lib\site-packages\rasax\community\api\decorators.py", line 205, in decorated_function
>     return await await_and_return_response(args, kwargs, request)
>   File "c:\users\collegedunia\anaconda3\lib\site-packages\rasax\community\api\decorators.py", line 135, in await_and_return_response
>     response = await response
>   File "c:\users\collegedunia\anaconda3\lib\site-packages\rasax\community\api\blueprints\models.py", line 191, in train_model
>     content = await stack_service.start_training_process()
>   File "c:\users\collegedunia\anaconda3\lib\site-packages\rasax\community\services\stack_service.py", line 352, in start_training_process
>     nlu_training_data = nlu_training_data.filter_training_examples(
> AttributeError: 'TrainingData' object has no attribute 'filter_training_examples'
> 2020-05-13 20:21:45 ERROR    sanic.root  - Exception occurred while handling uri: 'http://localhost:5002/api/projects/default/models/jobs'
> Traceback (most recent call last):
>   File "c:\users\collegedunia\anaconda3\lib\site-packages\sanic\app.py", line 976, in handle_request
>     response = await response
>   File "c:\users\collegedunia\anaconda3\lib\site-packages\rasax\community\api\decorators.py", line 205, in decorated_function
>     return await await_and_return_response(args, kwargs, request)
>   File "c:\users\collegedunia\anaconda3\lib\site-packages\rasax\community\api\decorators.py", line 135, in await_and_return_response
>     response = await response
>   File "c:\users\collegedunia\anaconda3\lib\site-packages\rasax\community\api\blueprints\models.py", line 191, in train_model
>     content = await stack_service.start_training_process()
>   File "c:\users\collegedunia\anaconda3\lib\site-packages\rasax\community\services\stack_service.py", line 352, in start_training_process
>     nlu_training_data = nlu_training_data.filter_training_examples(
> AttributeError: 'TrainingData' object has no attribute 'filter_training_examples'
> 2020-05-13 20:25:31 ERROR    sanic.root  - Exception occurred while handling uri: 'http://localhost:5002/api/projects/default/models/jobs'
> Traceback (most recent call last):
>   File "c:\users\collegedunia\anaconda3\lib\site-packages\sanic\app.py", line 976, in handle_request
>     response = await response
>   File "c:\users\collegedunia\anaconda3\lib\site-packages\rasax\community\api\decorators.py", line 205, in decorated_function
>     return await await_and_return_response(args, kwargs, request)
>   File "c:\users\collegedunia\anaconda3\lib\site-packages\rasax\community\api\decorators.py", line 135, in await_and_return_response
>     response = await response
>   File "c:\users\collegedunia\anaconda3\lib\site-packages\rasax\community\api\blueprints\models.py", line 191, in train_model
>     content = await stack_service.start_training_process()
>   File "c:\users\collegedunia\anaconda3\lib\site-packages\rasax\community\services\stack_service.py", line 352, in start_training_process
>     nlu_training_data = nlu_training_data.filter_training_examples(
> AttributeError: 'TrainingData' object has no attribute 'filter_training_examples'
> 2020-05-13 20:25:42 ERROR    sanic.root  - Exception occurred while handling uri: 'http://localhost:5002/api/projects/default/models/jobs'
> Traceback (most recent call last):
>   File "c:\users\collegedunia\anaconda3\lib\site-packages\sanic\app.py", line 976, in handle_request
>     response = await response
>   File "c:\users\collegedunia\anaconda3\lib\site-packages\rasax\community\api\decorators.py", line 205, in decorated_function
>     return await await_and_return_response(args, kwargs, request)
>   File "c:\users\collegedunia\anaconda3\lib\site-packages\rasax\community\api\decorators.py", line 135, in await_and_return_response
>     response = await response
>   File "c:\users\collegedunia\anaconda3\lib\site-packages\rasax\community\api\blueprints\models.py", line 191, in train_model
>     content = await stack_service.start_training_process()
>   File "c:\users\collegedunia\anaconda3\lib\site-packages\rasax\community\services\stack_service.py", line 352, in start_training_process
>     nlu_training_data = nlu_training_data.filter_training_examples(
> AttributeError: 'TrainingData' object has no attribute 'filter_training_examples'
> ```
> 
> **Command or request that led to error**:
> 
> ```
> rasa x [ Tried to train the model after a successful conversation -- was also able to run a custom action ]
> ```
> 
> **Content of configuration file (config.yml)** (if relevant):
> 
> ```yaml
> # Configuration for Rasa NLU.
> # https://rasa.com/docs/rasa/nlu/components/
> language: en
> pipeline:
>   - name: sentiment.SentimentAnalyzer
>   - name: WhitespaceTokenizer
>   - name: RegexFeaturizer
>   - name: LexicalSyntacticFeaturizer
>   - name: CountVectorsFeaturizer
>   - name: CountVectorsFeaturizer
>     analyzer: "char_wb"
>     min_ngram: 1
>     max_ngram: 4
>   - name: DIETClassifier
>     epochs: 100
>   - name: EntitySynonymMapper
>   - name: ResponseSelector
>     epochs: 100
> 
> # Configuration for Rasa Core.
> # https://rasa.com/docs/rasa/core/policies/
> policies:
>   - name: MemoizationPolicy
>   - name: TEDPolicy
>     max_history: 5
>     epochs: 100
>   - name: MappingPolicy
>   - name: FormPolicy
> ```

I think this error is because rasa and rasa-x are not compatible. Please check https://rasa.com/docs/rasa-x/changelog/compatibility-matrix/
