### ISSUE TITLE
How to add feature on own

### ISSUE THREAD

**Issue by HarshitaSahai** [RasaHQ/rasa#5814]
Hey! So I have started with medicare_locator used the bot for features mentioned but now I want to add features per my requirement how do I do that where can I get the existing code or how can I start?

Thank you

**Comment by sara-tagger** [comment]
Thanks for submitting this feature request 🚀 @amn41 will get back to you about it soon! ✨

**Comment by alwx** [comment]
Closing it because our forum is the better place for questions.
