### ISSUE TITLE
Rasa-x load model (make active) api is missing? 

### ISSUE THREAD

**Issue by Ben-Mark** [RasaHQ/rasa#5819]
**Description of Problem**:
After training a model with rasa api, and loading it via another api to the rest service.
I need to upload/update that trained model in rasa-x.
Assuming I was able to upload that model to the rasa-x api (which isn't working , opened another ticket for it: https://github.com/RasaHQ/rasa/issues/5801) 
I still need to make it active, to load it. I can't seem to find any endpoint for that in the docs.

**Overview of the Solution**:
Create that api or correct me if it exists

**Examples** (if relevant):
similar to rasa rest load model api.

**Blockers** (if relevant):
the lack of this api

**Definition of Done**:
this api..

**Comment by sara-tagger** [comment]
Thanks for submitting this feature request 🚀 @melindaloubser1 will get back to you about it soon! ✨

**Comment by melindaloubser1** [comment]
I think you're looking for the `tag` endpoint  https://rasa.com/docs/rasa-x/api/rasa-x-http-api/#tag/Models/paths/~1projects~1{project_id}~1models~1{model}~1tags~1{tag}/put

**Comment by Ben-Mark** [comment]
Rasa-x tag model endpoint documentation:
```
This endpoint can be used to assign a tag to a Rasa model. The tag will be removed from any other model that might have it. The endpoint returns the assigned tag with status code 200.

path parameters:
- defaultProject ID
- stringModel name
- stringModel tag

```

I'm in guessing mode here,
Do I need to send a tag named 'activate'? to load the model in the rasa-x ui?

or how exactly do I use this endpoint?

**Comment by melindaloubser1** [comment]
Yes, you tag it as "production". Here's an example that would do this:
```
curl --request PUT \
  --url http://<address>/api/projects/default/models/<modelname>/tags/production \
  --header 'accept: application/json' \
  --header 'authorization: Bearer <bearer_token>' \
  --header 'content-type: application/json'
```
