### ISSUE TITLE
some problem with rasa x when using "correct this"

### ISSUE THREAD

**Issue by saxh** [RasaHQ/rasa#5826]
**Rasa version**:

Rasa Version     : 1.11.0a1
Rasa SDK Version : 1.10.0
Rasa X Version   : 0.28.2
Python Version   : 3.6.10

**Rasa SDK version** (if used & relevant):

**Rasa X version** (if used & relevant):

**Python version**:

**Operating system** (windows, osx, ...):

**Issue**:

before I click "correct this" , the slot  event which is in the red box is normal.
![image](https://user-images.githubusercontent.com/22788088/82017014-c31da100-96b4-11ea-8d7e-40fd6a312c33.png)
after I click "correct this",the slot event become redundant like this.
![image](https://user-images.githubusercontent.com/22788088/82017027-c9ac1880-96b4-11ea-9e7f-f2a1110ede5e.png)
what's the problem?

**Error (including full traceback)**:
```

```

**Command or request that led to error**:
```
rasa x
```

**Content of configuration file (config.yml)** (if relevant):
```yml

```

**Content of domain file (domain.yml)** (if relevant):
```yml

```

**Comment by sara-tagger** [comment]
Thanks for raising this issue, @TyDunn will get back to you about it soon✨

###### Please also check out the [docs](https://rasa.com/docs/) and the [forum](https://forum.rasa.com/) in case your issue was raised there too 🤗

**Comment by TyDunn** [comment]
Hi @saxh. I was able to verify this bug in Rasa 0.28.2. I will route it the engineering team to get it squashed. Thanks for reporting!
