### ISSUE TITLE
allow to configure virtual_host parameter for pika connector

### ISSUE THREAD

**Issue by cristianmtr** [RasaHQ/rasa#5833]
**Rasa version**: 1.9.5

**Rasa SDK version** (if used & relevant): rasa-sdk==1.9.0

**Rasa X version** (if used & relevant):

**Python version**: 3.6

**Operating system** (windows, osx, ...):

**Issue**:

Cannot configure the "virtual_host" parameter of Pika. 

We use a RabbitMQ service provided by CloudAMPQ. In order to connect there we need to specify an extra parameter, "virtual_host". Atm, Rasa doesn't read this from the endpoints file. I thus get an error when trying to connect. It works if I debug your code and manually change that parameter. 

**Error (including full traceback)**:
```

```

**Command or request that led to error**:
```

```

**Content of configuration file (config.yml)** (if relevant):
```yml

```

**Content of domain file (domain.yml)** (if relevant):
```yml

```

**Comment by sara-tagger** [comment]
Thanks for the issue, @melindaloubser1 will get back to you about it soon!

###### You may find help in the [docs](https://rasa.com/docs/) and the [forum,](https://forum.rasa.com/) too 🤗

**Comment by federicotdn** [comment]
Hey @cristianmtr, you can try an alternative, setting the `url` key to your complete AMQP URL containing all the information necessary:
```yml
event_broker:
  type: pika
  url: amqp://user:pass@host:10000/vhost
  queues: ...
```

**Comment by cristianmtr** [comment]
Hey. Completely missed your answer. This was indeed what I did as well, and it worked.
