### ISSUE TITLE
After connecting to a reposity, Rasa X UI is still empty

### ISSUE THREAD

**Issue by xianjianbo** [RasaHQ/rasa#5842]
**Rasa version**: 1.8.1

**Rasa SDK version** (if used & relevant):1.8.1

**Rasa X version** (if used & relevant):28.3

**Python version**:3.6

**Operating system** (windows, osx, ...):Ubuntu 16.4

**Issue**: After connecting to my github reposity, Rasa X UI is also empty, no data in NLU data, Stories, Domain, although the Status in UI shows : "You are up to date with the Git server".

**Error (including full traceback)**:
```

```

**Command or request that led to error**:
```

```

**Content of configuration file (config.yml)** (if relevant):
```yml

```

**Content of domain file (domain.yml)** (if relevant):
```yml

```

**Comment by sara-tagger** [comment]
Thanks for the issue, @rgstephens will get back to you about it soon!

###### You may find help in the [docs](https://rasa.com/docs/) and the [forum,](https://forum.rasa.com/) too 🤗

**Comment by gonhonoria** [comment]
i have the same issue
Rasa SDK version (if used & relevant):1.10

Rasa X version (if used & relevant):28.3

Python version:3.6

Operating system (windows, osx, ...):Ubuntu 18.4
