### ISSUE TITLE
ASR Support

### ISSUE THREAD

**Issue by murugancmi** [RasaHQ/rasa#585]
It support ASR ,It possible convert to speech to text like wit.ai

**Comment by tmbo** [comment]
We'd love to. Any ideas for a good speech to text system (open source would be best)? 

We might do one in the future as well, but atm we just don't have enough time to do that properly

**Comment by murugancmi** [comment]
Open source Speech to Text system https://cmusphinx.github.io/, If rasa support ASR its easy to use in Telephony world

**Comment by murugancmi** [comment]
Any Update about this  question

**Comment by wrathagom** [comment]
Thanks, I'm sure @tmbo will circle back around when the Rasa team has time for this or thinks it's a priority for them. Until then I've added the help wanted label. if you have the time it would be great to get a pull request started with this functionality.

I'm also assuming things will go easier if we can find a python bindings for the tool you linked or find a pure python solution.

**Comment by syntithenai** [comment]
https://github.com/syntithenai/opensnips
