### ISSUE TITLE
An error when taraining a model with rasa 1.10.0

### ISSUE THREAD

**Issue by Asma-droid** [RasaHQ/rasa#5862]
Hi all,

I try to use http API in order to train a rasa model with rasa version 1.10.0.

The training process has given an error. I think that's an error of timeout. Below the given error in the server side and the client side.

******Server**********
rasa             | Your Rasa model is trained and saved at '/app/models/20200519-140657.tar.gz'.
rasa             | Nothing changed. You can use the old model stored at '/app/models/20200519-140657.tar.gz'.
rasa             | Core stories/configuration did not change. No need to retrain Core model.
rasa             | Training NLU model...
rasa             | [2020-05-19 15:11:12 +0000] [1] [ERROR] Exception occurred while handling uri: 'http://localhost:5005/model/train'
rasa             | NoneType: None
rasa             | 2020-05-19 15:11:12 DEBUG    rasa.server  - Traceback (most recent call last):
rasa             |   File "/opt/venv/lib/python3.7/site-packages/rasa/server.py", line 808, in train
rasa             |     None, functools.partial(train_model, **info)
rasa             | concurrent.futures._base.CancelledError
rasa             |

*****Client*****
 body: 'Error: Response Timeout'

Note that sometimes the training process is well achieved and sometimes we obtain the error ( the data is the same as well as the parameters)

**Comment by sara-tagger** [comment]
Thanks for the issue, @JustinaPetr will get back to you about it soon!

###### You may find help in the [docs](https://rasa.com/docs/) and the [forum,](https://forum.rasa.com/) too 🤗

**Comment by Asma-droid** [comment]
Hi,

I would like to add that this issue is gonly enerated when we use the DietClassifier.

**Comment by JustinaPetr** [comment]
Hi @Asma-droid. I think this might be fixed in one of the latest releases of Rasa. Could you try running this with Rasa 1.10.2?

**Comment by Asma-droid** [comment]
hi @JustinaPetr  the probleme is also generated with rasa vesrion 1.10.2

rasa             | Training Core model...
rasa             | Core model training completed.
rasa             | Training NLU model...
rasa             | [2020-06-10 09:02:03 +0000] [1] [ERROR] Exception occurred while handling uri: 'http://localhost:5005/model/train'
rasa             | NoneType: None
rasa             | 2020-06-10 09:02:03 DEBUG    rasa.server  - Traceback (most recent call last):
rasa             |   File "/opt/venv/lib/python3.7/site-packages/rasa/server.py", line 809, in train
rasa             |     None, functools.partial(train_model, **info)
rasa             | concurrent.futures._base.CancelledError
rasa             |

**Comment by Asma-droid** [comment]
hello,

I would like to inform you that the issue still exist with version 2.0.0a1.

Th response of my docker-compose is :2020-07-23 09:38:36.967|rasa-ui|error|Error occurred while training. Rasa Server Response Code : 503;

The response of my GUI is: Error: Response Timeout

Any solution please ?
