### ISSUE TITLE
WhitespaceTokenizer removes characters like + - * /  , so entity recognition fails as tokenizer removes these

### ISSUE THREAD

**Issue by sibbsnb** [RasaHQ/rasa#5874]
**Rasa version**:
1.10.1

**Rasa SDK version** (if used & relevant):
1.10.1

**Rasa X version** (if used & relevant):

**Python version**:
3.7.3

**Operating system** (windows, osx, ...):
OSX

**Issue**:
WhitespaceTokenizer skips certain single digit characters like text = 300 + 20 , only 300 and 20 is returned.

Below regex filters those symbols:
 words = re.sub(
            # there is a space or an end of a string after it
            r"[^\w#@&]+(?=\s|$)|"
            # there is a space or beginning of a string before it
            # not followed by a number
            r"(\s|^)[^\w#@&]+(?=[^0-9\s])|"
            # not in between numbers and not . or @ or & or - or #
            # e.g. 10'000.00 or blabla@gmail.com
            # and not url characters
            r"(?<=[^0-9\s])[^\w._~:/?#\[\]()@!$&*+,;=-]+(?=[^0-9\s])",
            " ",
            text,
        ).split()

**Error (including full traceback)**:
```

```

**Command or request that led to error**:
```

```

**Content of configuration file (config.yml)** (if relevant):
```yml

```

**Content of domain file (domain.yml)** (if relevant):
```yml

```

**Comment by sara-tagger** [comment]
Thanks for the issue, @tabergma will get back to you about it soon!

###### You may find help in the [docs](https://rasa.com/docs/) and the [forum,](https://forum.rasa.com/) too 🤗

**Comment by tabergma** [comment]
@sibbsnb This is actually intended. If you don't want to remove those characters, please write your own custom tokenizer. You can simply copy the code from the [WhitespaceTokenizer](https://github.com/RasaHQ/rasa/blob/master/rasa/nlu/tokenizers/whitespace_tokenizer.py) and update the regex. For more information on how to write a custom component see the [documentation](https://rasa.com/docs/rasa/api/custom-nlu-components/#custom-nlu-components).

**Comment by sibbsnb** [comment]
Why can't we parametrize it? Default behavior can be same but user can override. Creating a new tokenizer is not a good idea. Now i ended up using spacy tokenizer which doesn't filter these but it  is heavier than WhitespaceTokenizer
