### ISSUE TITLE
Pop up doesnt go away

### ISSUE THREAD

**Issue by tatianafrank** [RasaHQ/rasa#5880]
Every time I go to /conversations I get the below popup and it never goes away even though I already have git integrated. 

<img width="976" alt="Screen Shot 2020-05-22 at 10 58 03 AM" src="https://user-images.githubusercontent.com/11413181/82681257-86edc180-9c1b-11ea-8210-5986274dfb2a.png">

Using the latest version of Rasa with Kubernetes setup

**Comment by sara-tagger** [comment]
Thanks for the issue, @tabergma will get back to you about it soon!

###### You may find help in the [docs](https://rasa.com/docs/) and the [forum,](https://forum.rasa.com/) too 🤗

**Comment by Saladdin** [comment]
Hey @tatianafrank, the onboarding modal you're referring to will be removed in the upcoming Rasa X release _(`@0.29`)_
