### ISSUE TITLE
Custom connector for Zipwhip SMS

### ISSUE THREAD

**Issue by kearnsw** [RasaHQ/rasa#5884]
**Description of Problem**:
Unable to easily run a bot using Zipwhip 

**Overview of the Solution**:
Create a Zipwhip custom connector

**Examples** (if relevant):
https://rasa.com/docs/rasa/user-guide/connectors/custom-connectors/

**Blockers** (if relevant):
No

**Definition of Done**:
- [ ] Tests are added
- [ ] Feature described the docs
- [ ] Feature mentioned in the changelog

**Comment by sara-tagger** [comment]
Thanks for submitting this feature request 🚀 @tttthomasssss will get back to you about it soon! ✨
