### ISSUE TITLE
Parameterized Actions

### ISSUE THREAD

**Issue by zucher** [RasaHQ/rasa#5893]
**Description of Problem**:
Actions have to be dedicated for a task, but in some cases we may have generic actions with a selector during definition.
https://forum.rasa.com/t/parameterized-action/28248

**Overview of the Solution**:
In order to enhance Action capability, I propose to add parameters into actions like for intent:

A same Action declaration will be able to receive specific elements without using slots. 
Those parameters are only valid for the current code.

example:

    * intent{ "bar": "foo" }
          - action_dummy{"id": "xxxxxx"}
          - action_on_location

Action API have to support a new "parameters" element in request such as:

    ...
    "tracker": {...
    },
    "parameters": {
       "id": "xxxxx"
    },
    ...

the 4th parameters in Action.run method have to be Optional, and the Executor.register_function have to allow 3 or 4 in order to assume retro compatibility.

**Definition of Done**:

- [ ] Tests are added
- [ ] Feature described the docs
- [ ] Feature mentioned in the changlog
- [ ] Action SDK updated

**Comment by amn41** [comment]
hi @zucher  - what's the reason not to just use slots for this?

**Comment by zucher** [comment]
You're right @amn41 , but slot is still valid during the session, but in the current case this is just for triggering a parameterized action, that mean we don't need to store this information in time. This also add unnecessary overflow. Linking this directly to action add more concistency.

**Comment by amn41** [comment]
I think there are already a couple of options to achieve this - either using a slot as a parameter, or using a base class with the specific actions as subclasses. 

Since this would add a lot of complexity to the story format, I dont think we should do it

**Comment by zucher** [comment]
Thank you @amn41 ,
could you detail a little the action base class solution. On our side we want to have a generic action treatment.

**Comment by amn41** [comment]
you could do something like:

```python
class BaseAction(object): 
    def __init__(self): 
        self.parameter = None 
    def run(self, tracker, domain, dispatcher): 
        print(self.parameter) 

class MyAction(BaseAction): 
    def __init__(self): 
        self.parameter = "hello" 

MyAction().run(None, None, None) # prints "hello"

```

**Comment by zucher** [comment]
Thank you for your reply @amn41 ,  you solution does not fit with our needs, we have to continue with the slot solution despite the session overhead.
