### ISSUE TITLE
Rasa-X http APIs inserting previously deleted data too.

### ISSUE THREAD

**Issue by rohitiec** [RasaHQ/rasa#5895]
**Rasa version**:1.7.0

**Rasa SDK version** (if used & relevant):

**Rasa X version** (if used & relevant): 0.25.2

**Python version**:

**Operating system** (windows, osx, ...) : Ubuntu 16.04

**Issue**:
I am using Rasa X's api /projects/{project_id}/data
Request-
{"entities":[],"text":"testings","intent":"testings","project_id":"default","team":"rasa"}
to add new intent with data
the new intent and utterance are successfully added 

but when i go to the command line and delete this intent 
and next i add another intent , The deleted intent is also being added in nlu.md file as well as domain.yml file

Same is happening with the add response api 
/api/templates
Request Payload:
{"text":"just testing to store response","template":"utter_testings"}

**Error (including full traceback)**:
```

```

**Command or request that led to error**:
```

```

**Content of configuration file (config.yml)** (if relevant):
```yml

```

**Content of domain file (domain.yml)** (if relevant):
```yml

```

**Comment by sara-tagger** [comment]
Thanks for the issue, @chkoss will get back to you about it soon!

###### You may find help in the [docs](https://rasa.com/docs/) and the [forum,](https://forum.rasa.com/) too 🤗

**Comment by chkoss** [comment]
Hi @rohitiec,
By "go to the command line and delete this intent" I assume you mean removing it from the `domain.yml` and/or the `nlu.md` files, right?

A running Rasa X instance doesn't automatically pick up changes to your local files.

So if you remove the intent there, it is still in the Rasa X database. You can see that if you send a `GET` request to `/projects/{project_id}/data?intent=testings`. If you then add another intent via the API, all the intents in your Rasa X database will get written into the nlu file, so the "deleted" one is back.

To actually delete the intent, you can do the following:
- Send a `GET` request to `/projects/{project_id}/data?intent=testings`. The response will contain a field `id`. This is the example_id you'll need for the following step.
- Send a `DELETE` request to `/projects/{project_id}/data/{example_id}` to delete the training example with that intent from the database.

Same for the responses, with `GET /templates?template=utter_testings` and `DELETE /templates/{template_id}`.
