### ISSUE TITLE
sanic.exceptions.NotFound: Requested URL /webhook not found

### ISSUE THREAD

**Issue by Akhil1278** [RasaHQ/rasa#5897]
![Screenshot (27)](https://user-images.githubusercontent.com/65960157/82915015-d589bb80-9f8d-11ea-8abf-eb3390f2d301.png)

**Rasa version**: Rasa 1.10.0

**Rasa SDK version** (if used & relevant): 

**Rasa X version** (if used & relevant):

**Python version**:3.68

**Operating system** (windows, osx, ...): windows

**Issue**:trying to implement forms in rasa but getting an error
sanic.exceptions.NotFound: Requested URL /webhook not found

**Error (including full traceback)**:
Exception occurred while handling uri: 'http://localhost:5005/webhook'
Traceback (most recent call last):
  File "c:\users\akhil\venv\lib\site-packages\sanic\app.py", line 940, in handle_request
    handler, args, kwargs, uri, name = self.router.get(request)
  File "c:\users\akhil\venv\lib\site-packages\sanic\router.py", line 411, in get
    return self._get(request.path, request.method, "")
  File "c:\users\akhil\venv\lib\site-packages\sanic\router.py", line 475, in _get
    raise NotFound("Requested URL {} not found".format(url))
sanic.exceptions.NotFound: Requested URL /webhook not found
2020-05-26 19:57:50 ERROR    rasa.core.processor  - Encountered an exception while running action 'gmail_form'. Bot will continue, but the actions events are lost. Please check the logs of your action server for more information.
```

```

**Command or request that led to error**:rasa shell
send gmail
```

```

**Content of configuration file (config.yml)** (if relevant):
```yml
# Configuration for Rasa NLU.
# https://rasa.com/docs/rasa/nlu/components/
language: en
pipeline:
  - name: WhitespaceTokenizer
  - name: RegexFeaturizer
  - name: LexicalSyntacticFeaturizer
  - name: CountVectorsFeaturizer
  - name: CountVectorsFeaturizer
    analyzer: "char_wb"
    min_ngram: 1
    max_ngram: 4
  - name: DIETClassifier
    epochs: 100
  - name: EntitySynonymMapper
  - name: ResponseSelector
    epochs: 100

# Configuration for Rasa Core.
# https://rasa.com/docs/rasa/core/policies/
policies:
  - name: MemoizationPolicy
  - name: TEDPolicy
    max_history: 5
    epochs: 100
  - name: MappingPolicy
  - name: FormPolicy

  - name: "FallbackPolicy"
    nlu_threshold: 0.9
    core_threshold: 0.4
    fallback_action_name: "action_default_fallback"

```

**Content of domain file (domain.yml)** (if relevant):
```yml
intents:
  - goodbye
  - deny
  - IITTP
  - IITTP_year
  - IITTP_branches
  - IITTP_hostels
  - IITTP_location
  - get_started
  - ask
  - yes
  - out_of_scope
  - my_email_is
  - my_password_is
  - r_email_is
  - my_subject_is
  - my_format_is
  - send_mail

slots:
  SenderMail:
    type: unfeaturized
  Password:
    type: unfeaturized
  RecipientMail:
    type: unfeaturized
  Subject:
    type: unfeaturized
  Format:
    type: unfeaturized

forms:
  - gmail_form


responses:

  utter_get_started:
  - text: "Hey! How can I help you?"
  
  utter_did_that_help:
  - text: "Did that help?"

  utter_do_you_need:
  - text: "Do you need more information?"

  utter_no:
  - text: "Great, carry on!"

  utter_goodbye:
  - text: "Bye"

  utter_IITTP : 
  - text: "The name of the IIT in AP is IIT Tirupati"

  utter_IITTP_year :
  - text: "It was established in 2015"
   
  utter_IITTP_location :
  - text: "IIT-Tirupati was initially functioned out of the campus of Chadalawada Group of Institutes in Tirupati, while the permanent building is coming up near Yerpedu located between Renigunta and Srikalahasti."
  
  utter_IITTP_hostels :
  - text: "The hostel facility for both boys and girls has been arranged at Transit Campus, Yerpedu, which is to be coming up as the permanent campus."

  utter_IITTP_branches :
  - text: "The institute flagged its beginning with the following 4 departments 
          1)Chemical Engineering (Started from Aug. 2018)

          2)Civil Engineering 
          3)Computer Science and Engineering
          4)Electrical Engineering
          5)Mechanical Engineering"

  utter_ask :
  - text: "Ask me"
  
  utter_yes :
  - text: "For more information please visit :https://iittp.ac.in/"
 
  utter_default :
  - text: "Sorry, I didn’t understand that.Please type again...."
  
  utter_ask_SenderMail :
  - text: "Please Provide me with your Email Address"

  utter_ask_Password :
  - text: "Password :" 

  utter_ask_RecipientMail :
  - text: "Please Provide me with Recipient's Email Address"

  utter_ask_Subject :
  - text: "Subject :"

  utter_ask_Format :
  - text: "Format :"
 
  utter_submit :
  - text: "Sending mail..."
 
session_config:
  session_expiration_time: 60
  carry_over_slots_to_new_session: true

```

**Comment by sara-tagger** [comment]
Thanks for raising this issue, @dakshvar22 will get back to you about it soon✨

###### Please also check out the [docs](https://rasa.com/docs/) and the [forum](https://forum.rasa.com/) in case your issue was raised there too 🤗

**Comment by ricwo** [comment]
hey @Akhil1278, it looks like you're trying to call a custom action via your action server. unless you've configured it otherwise, it normally runs under port `5055`. Could you edit your `endpoints.yml` and make sure it contains the following:
```yaml
action_endpoint:
  url: "http://localhost:5055/webhook"
```
Let me know how it goes!

**Comment by Akhil1278** [comment]
@ricwo  Yeah it is resolved..Thanks
