### ISSUE TITLE
Why am i not able to get entities that are not trained?

### ISSUE THREAD

**Issue by jainsaurav22** [RasaHQ/rasa#5910]
`
python nlu_model.py
Fitting 2 folds for each of 6 candidates, totalling 12 fits
[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.
[Parallel(n_jobs=1)]: Done  12 out of  12 | elapsed:    0.0s finished
{'intent': {'name': 'inform', 'confidence': 0.8173132669403216}, 'entities': [], 'intent_ranking': [{'name': 'inform', 'confidence': 0.8173132669403216}, {'name': 'goodbye', 'confidence': 0.11850990850694815}, {'name': 'greet', 'confidence': 0.06417682455273013}], 'text': 'I am planning my trip to Barcelona. What is the weather out there?'}

`
Here ihave trained my model with location Berlin. If the message contains Berlin, then the enitities are identified, why so?
Since we are using Spacy_md model, and i am adding a pipeline to it also, then why is the location not detcted as entities?

**Comment by sara-tagger** [comment]
Thanks for the question, our Github issue board is for **bugs and feature requests only,** though 😕
Please ask this question in the [forum✨](https://forum.rasa.com/c/rasa)

###### If you were describing a bug, please create a [report](https://github.com/RasaHQ/rasa/issues/new?labels=bug&template=bug_report.md) and fill out the template.

**Comment by sara-tagger** [comment]
Thanks for the issue, @closed will get back to you about it soon!

###### You may find help in the [docs](https://rasa.com/docs/) and the [forum,](https://forum.rasa.com/) too 🤗
