### ISSUE TITLE
MultiProjectImporter should ignore tests directory in imported projects

### ISSUE THREAD

**Issue by ortsaCniveK** [RasaHQ/rasa#5913]
**Description of Problem**:

I was in the process of testing out the `MultiProjectImporter` for use in my own projects (which I love), so I set up two nested directories using `rasa init`:

```log
├── actions.py
├── config.yml
├── data
│   ├── mood_1_nlu.md
│   └── mood_1_stories.md
├── domain.yml
├── models
│   └── 20200528-101144.tar.gz
├── projects
   └── Mood2Bot
       ├── config.yml
       ├── data
       │   ├── mood_2_nlu.md
       │   └── mood_2_stories.md
       ├── tests
       │   └── conversation_tests.md
       └── domain.yml
```
This lead to log messages like these:
```log
UserWarning: Found unknown intent 'bot_challenge: are you a bot?' on line 50. Please, make sure that all intents are listed in your domain yaml.
```
```log
2020-05-28 10:24:57 WARNING  rasa.core.featurizers  - Feature 'intent_bot_challenge: are you a bot?' could not be found in feature map.
```

I believe [this is the function](https://github.com/RasaHQ/rasa/blob/ff0848419d780b042bf2aa14f932fe1a2050f5ea/rasa/importers/multi_project.py#L96) causing this issue.

**Overview of the Solution**:

Ignore the `tests/` directory in an imported project, since this format is not for training, [as specified in the docs](https://rasa.com/docs/rasa/core/stories/#end-to-end-story-evaluation-format). Just as well, it promotes isolated, project-level conversation testing, [which seems to be the goal of this feature](https://rasa.com/docs/rasa/api/training-data-importers/#multiprojectimporter-experimental).

**Examples** (if relevant):

**Blockers** (if relevant):

**Definition of Done**:

- [x] Add test for `tests/` in imported project
- [x] Ignore `tests/` directory when walking the project directory
- [x] Document changes in change log

**Comment by sara-tagger** [comment]
Thanks for submitting this feature request 🚀 @Ghostvv will get back to you about it soon! ✨

**Comment by wochinge** [comment]
good catch, @ortsaCniveK 🎉 Do you wanna implement a fix for this? I'd be available for feedback and help. Otherwise we'd add it to our backlog.

**Comment by ortsaCniveK** [comment]
I can work on this!
