### ISSUE TITLE
Form doesn't deactivate on its own after being submitted

### ISSUE THREAD

**Issue by izio38** [RasaHQ/rasa#5914]
**Rasa version**: Rasa 1.10.1

**Rasa SDK version** (if used & relevant): 1.10.1

**Python version**: Python 3.7.6

**Operating system** (windows, osx, ...): Windows

**Issue**: A form doesn't deactivate on its own after being submitted

**Content of configuration file (config.yml)** (if relevant):
```yml
language: en
pipeline:
  - name: HFTransformersNLP
  - name: LanguageModelTokenizer
  - name: RegexFeaturizer
  - name: LanguageModelFeaturizer
  - name: EntitySynonymMapper
  - name: DIETClassifier
    epochs: 100

policies:
  - name: FallbackPolicy
  - name: MemoizationPolicy
  - name: FormPolicy
  - name: MappingPolicy
```

**Content of domain file (domain.yml)** (if relevant):
```yml
intents:
  - greet
  - bye
  - thankyou
  - request_repository:
      use_entities: []
  - inform_repository

entities:
  - repository
  - repository_name

slots:
  repository:
    type: unfeaturized
    auto_fill: false
  repository_language:
    type: unfeaturized
    auto_fill: false
  repository_name:
    type: unfeaturized
    auto_fill: false

responses:
  utter_greet:
    - text: "Hi, I am repository assistant, How can I help you ?"
  utter_bye:
    - text: Bye!
  utter_ask_repository_name:
    - text: "what repository should I look for?"
  utter_repository:
    - text: "All done !"
  utter_slots_values:
    - text: "I am going to run a repository search using the following parameters:\n
                - repository: {repository}\n"
  utter_ask_continue:
    - text: "do you want to continue?"
  utter_noworries:
    - text: "No worries"
  utter_submit:
    - text: "All done!"

forms:
  - repository_form

session_config:
  session_expiration_time: 60  # value in minutes
  carry_over_slots_to_new_session: true
```

You can check the repro case (sorry it's not minimal). To reproduce the issue type :
https://github.com/izio38/gitmaster-chatbot/tree/bug/form-doesnt-deactivate

```
I'm looking for a repo
--
Angular
--
I'm looking for a repo
```

On the 3rd entry, it's supposed to begin again, but no, the form stays activated hence looking for entity to extract.

**Comment by sara-tagger** [comment]
Thanks for raising this issue, @wochinge will get back to you about it soon✨

###### Please also check out the [docs](https://rasa.com/docs/) and the [forum](https://forum.rasa.com/) in case your issue was raised there too 🤗

**Comment by wochinge** [comment]
@izio38 Can you please share the content tracker after the point where the form should have been submitted? Thanks 🙏

**Comment by izio38** [comment]
I just gave you a repro case. I do not have the time to do this.

**Comment by wochinge** [comment]
@izio38 

>  I do not have the time to do this.

I completely understand that time is often short, but this applies on both sides. I'd really appreciate if we could work this out together.

Is `submit()` actually being called by the form?
