### ISSUE TITLE
rasa interactive asks for prediction too often

### ISSUE THREAD

**Issue by wochinge** [RasaHQ/rasa#5917]
`rasa interactive` calls `_validate_action` even if the last action was already `action_listen`.
This is currently not an issue, but is an issue with the new `RulePolicy`. I ran into it when doing https://github.com/RasaHQ/rasa/pull/5911 . 

To reproduce:
1. Send a message which causes the `FallbackPolicy` to be triggered (or `action_default_fallback`)
2. `_validate_action` will be called even if `ACTION_LISTEN` was already the last action. I think this might be related to conversation session events

With the rule policy at the current stage this leads to the problem that Rasa Open Source predicts `...` again

**Comment by rafaelteodosio** [comment]
I will work on this issue with my friend @joaoCeilandia .

**Comment by wochinge** [comment]
Amazing! Thanks @rafaelteodosio Please feel free to reach out if you need help / feedback!

**Comment by rafaelteodosio** [comment]
Hello @wochinge we can no longer reproduce this issue, may be someone has fixit, can you check that ?
