### ISSUE TITLE
Permission errors during export are not handled in interactive training

### ISSUE THREAD

**Issue by Dobatymo** [RasaHQ/rasa#5921]
**Rasa version**:1.10.0
**Python version**: 3.7.4
**Operating system**: Windows

**Issue**:
If writing the exported data from interactive training (stories, nlu, domain using "Export and quit") raises a PermissionError, the training data is lost. I will attach a pull request which catches the error and asks for user interaction.

PR: https://github.com/RasaHQ/rasa/pull/5922

**Comment by sara-tagger** [comment]
Thanks for the issue, @chkoss will get back to you about it soon!

###### You may find help in the [docs](https://rasa.com/docs/) and the [forum,](https://forum.rasa.com/) too 🤗

**Comment by wochinge** [comment]
@Dobatymo Why is the permission error happening in the first place?

**Comment by Dobatymo** [comment]
It mostly happens when multiple people are working on the same chatbot repository.
For example, Person A pulls changes from a github repo on a shared server and person B starts the interactive training. Then when exporting the stories the PermissionError is raised and all stories lost.

Then to fix, we would run chmod on the story/domain/nlu files and redo the training.

With my pull request, we can run chmod when we encounter the error and try exporting again, so we don't lose any training data.

**Comment by wochinge** [comment]
Phew. I think this is an error which is **very** specific to your use case and should be handled within your infrastructure and not within Rasa Open Source. 

E.g. you could make the files readable by the group and have all users be part of the same group.

**Comment by Dobatymo** [comment]
I already fixed the problem with a different set of permissions. But I still think handling PermissionErrors (and probably other kinds of OSErrors) is a useful and expected feature. When my text editor cannot save a file, I expect it to ask me to retry instead of crash.

**Comment by Dobatymo** [comment]
I changed to pull request to handle all OSErrors to catch other IO errors like full disk for example. I think these kind of errors should be handled need to be handled, as they would be with other text editors.

**Comment by wochinge** [comment]
Sorry @Dobatymo, the notifications for your previous message somehow slipped through the cracks. Will give your PR a review 👍
