### ISSUE TITLE
TypeError: create() missing 2 required positional arguments: 'language' and 'spacy_model_name'

### ISSUE THREAD

**Issue by Bharathi-A-7** [RasaHQ/rasa#5925]
I'm using the version 0.8.6 of Rasa_nlu .

And I'm getting the error " TypeError: create() missing 2 required positional arguments: 'language' and 'spacy_model_name' " in Anaconda Spyder when I run the following code

`import spacy
from rasa_nlu.training_data import load_data
from rasa_nlu.config import RasaNLUConfig
from rasa_nlu.model import Trainer

args = {"pipeline": "spacy_sklearn"}

config = RasaNLUConfig(cmdline_args=args)
trainer = Trainer(config)

training_data = load_data("./training_data.json")

interpreter = trainer.train(training_data)

print(interpreter.parse("I'm looking for a Mexican restaurant in the North of town"))
`

I guess the error is in the line ' trainer = Trainer(config) ' 

Can someone please help me resolve this issue ? 
I've been reading several forum posts with regard to running my Rasa nlu . And I've installed and uninstalled multiple versions of it , but , each one of them seem to cause a new error . 

Please help me run this piece of code on spyder.

Thanks

**Comment by sara-tagger** [comment]
Thanks for raising this issue, @rgstephens will get back to you about it soon✨

###### Please also check out the [docs](https://rasa.com/docs/) and the [forum](https://forum.rasa.com/) in case your issue was raised there too 🤗

**Comment by tmbo** [comment]
Is there a reason you are using such an old version of the library?

**Comment by Bharathi-A-7** [comment]
@tmbo I was using the latest version 0.15 but had many issues with it . And some of the forums posts had recommended using the version 0.8.6 . I've had one or more issues with each version . I don't know where I'm going wrong.

**Comment by tmbo** [comment]
The latest version is 1.10.1 (https://pypi.org/project/rasa/) - we merged rasa_nlu package into rasa over a year ago. `0.8.6` is over two years old, I am afraid we can't help you with that version as this issue most likely doesn't exist anymore in more recent versions.
