### ISSUE TITLE
E2E Implementation proposal

### ISSUE THREAD

**Issue by wochinge** [RasaHQ/rasa#5931]
**Resources**:
- https://docs.google.com/document/d/1VJWyqEkSUw5rLAfiCUGsp_nOINKvhavUsuW7I8XkeW8/edit
- https://github.com/RasaHQ/rasa/pull/5423

**Goals**:
- [ ] Understand scope / limits of current implementation
- [ ] Derive tasks for next steps
- [ ] Create a proposal for the implementation of the next steps

**Notes**:
- Fixing the training data is not as urgent. We could probably make it until we have decided on the final format for Rasa 2.0

**Comment by tmbo** [comment]
is this referring to https://docs.google.com/document/d/1VJWyqEkSUw5rLAfiCUGsp_nOINKvhavUsuW7I8XkeW8/edit ?

**Comment by wochinge** [comment]
Updated the description
