### ISSUE TITLE
RulePolicy: Warn about overlapping rules

### ISSUE THREAD

**Issue by wochinge** [RasaHQ/rasa#5932]
@Ghostvv 
> I'd like to remove longest matching rule, rules shouldn't overlap

**Current behavior**
In case multiple rules match the current state, the RulePolicy will use the longest matching rule.

**Desired behavior**
In case rules overlap the `RulePolicy` should
- print a warning &
- stop the training and exit

The `RulePolicy` should be trained before the other policies to be able to fail early.

What does "overlap" mean
* one rule is a subset of another one, regardless whether they predict the same action or not. E.g. rule A predicts `action_overlap` after two actions `action_1`, `action_2` while rule b predicts `action_overlap` after a preceding action `action_2`
* two rules match the same state but predict different actions
* stories and rules contradict

**Comment by Ghostvv** [comment]
I think we even emit hard error, and stop training until rules are fixed

**Comment by wochinge** [comment]
I see where you're going, but on the contrary we are currently not doing the same for conflicting stories. Actually we currently not even warn the user about conflicting stories 🙈

**Comment by Ghostvv** [comment]
without RulePolicy, it was tricky to do

**Comment by wochinge** [comment]
updated the PR description 👍

**Comment by wochinge** [comment]
Also train the RulePolicy first to fail early

**Comment by wochinge** [comment]
@Ghostvv Should I handle this or you?

**Comment by Ghostvv** [comment]
I can handle it as part of `RulePolicy` refactor
