### ISSUE TITLE
Documentation update: rasa init

### ISSUE THREAD

**Issue by ortsaCniveK** [RasaHQ/rasa#5952]
**Description of Problem**:

[`rasa init` documentation](https://rasa.com/docs/rasa/user-guide/command-line-interface/#create-a-new-project) is missing the newly added `tests/` directory to the resulting directory tree (shown below):

```log
├── actions.py
├── config.yml
├── credentials.yml
├── data
│   ├── nlu.md
│   └── stories.md
├── domain.yml
├── endpoints.yml
├── __init__.py
├── models
│   └── <timestamp>.tar.gz.tar.gz
└── tests
    └── conversation_tests.md
```

**Overview of the Solution**:

Update documentation to show up-to-date directory tree.

**Examples** (if relevant):

**Blockers** (if relevant):

**Definition of Done**:

- [ ] update documentation to match current `rasa init` behavior
- [ ] update changelog

**Comment by sara-tagger** [comment]
Thanks for submitting this feature request 🚀 @akelad will get back to you about it soon! ✨
