### ISSUE TITLE
Log warning if lookup tables are not used correctly

### ISSUE THREAD

**Issue by tabergma** [RasaHQ/rasa#5956]
**Description of Problem**:
Many of our users are using lookup tables. However, some of them are missing the note in the docs

> For lookup tables to be effective, there must be a few examples of matches in your training data. Otherwise the model will not learn to use the lookup table match features.

Users are wondering why lookup tables do not work. It might be helpful to log a warning if we cannot find any examples in the training data with entries from the lookup tables.

**Overview of the Solution**:
Log a warning if no examples are present with entries from the lookup table.

**Comment by saravananselvamohan** [comment]
Hi @tabergma. I am a newbie & I wish to work on this issue. From the study of description and source code, I came up with a plan of action to resolve this issue.
**Plan of Action** 
I am looking at rasa/nlu/extractors/regex_entity_extractor.py where I able to see the warning is raised for the discussed issue(If I am in the right path). Do we need to log the warning message at that place or we need to check other parameters in the code.
```
def train(
        self,
        training_data: TrainingData,
        config: Optional[RasaNLUModelConfig] = None,
        **kwargs: Any,
    ) -> None:
        self.patterns = pattern_utils.extract_patterns(
            training_data,
            use_lookup_tables=self.component_config["use_lookup_tables"],
            use_regexes=self.component_config["use_regexes"],
            use_only_entities=True,
        )
        if not self.patterns:
            rasa.shared.utils.io.raise_warning(
                "No lookup tables or regexes defined in the training data that have "
                "a name equal to any entity in the training data. In order for this "
                "component to work you need to define valid lookup tables or regexes "
                "in the training data."
            )

```

**Comment by tabergma** [comment]
@sagarvanave Sorry for the late reply, I was out of office. 

Thanks for taking over this issue! This issue is related to the `RegexFeaturizer` not the `RegexEntityExractor`. So you should look at [this method](https://github.com/RasaHQ/rasa/blob/master/rasa/nlu/featurizers/sparse_featurizer/regex_featurizer.py#L78). When we do not generate any features for all examples in the training data, we should log a warning. Does this help? Let me know if you have more questions.

**Comment by saravananselvamohan** [comment]
@tabergma. Thanks for the reply. In `RegexFeaturizer ` I able to see, we are getting `sequence_features, sentence_features`. So if both are none, we may log the warning. Does my understanding is right.

**Comment by tabergma** [comment]
If there are no `sequence_features`, `sentence_features` for all training examples, only then we should log the warning. So I would change the method to return a boolean value indicating whether features could be extracted or not. And then you could check in `train` if we could find any features. If not, you should log the warning.

**Comment by alwx** [comment]
@saravananselvamohan are you still working on this?

**Comment by saravananselvamohan** [comment]
@alwx It's a little bit difficult for me to fix the issue. If someone interested to work on this issue please assign it to them

**Comment by guilherme-mendes** [comment]
Hey there, I would like to know if someone is already working on this issue.

**Comment by guilherme-mendes** [comment]
Hi @tabergma, we thought about this solution and we would like to know if we are on the right path and if it would be a valid solution in `RegexFeaturizer` class at the `train` function.
```python
if training_data.lookup_tables is None or training_data.lookup_tables == []:
    rasa.shared.utils.io.raise_warning(
        "No lookup tables or regexes defined in the training data "
        "that have a name equal to any entity in the training data. "
        "In order for this component to work you need to define valid "
        "lookup tables or regexes in the training data."
    )
```

**Comment by iurisevero** [comment]
Hey, there. I'm working with @guilherme-mendes and @santosm46 on this issue and we realized that our first idea of the solution was very wrong, because of Rasa's version we're working on (a newbie mistake :/). 

So, after working on it at the right version, we achieve the following solution:
```python
valid_lookup_tables = self._add_lookup_table_regexes(
    training_data.lookup_tables
)
if not valid_lookup_tables:
    common_utils.raise_warning(
        "No lookup tables or regexes defined in the training data that have "
        "a name equal to any entity in the training data. In order for this "
        "component to work you need to define valid lookup tables or regexes "
        "in the training data."
    )
```

```python
def _add_lookup_table_regexes(
    self, lookup_tables: List[Dict[Text, Union[Text, List]]]
) -> bool:
    some_feature_found = False
    """appends the regex features from the lookup tables to self.known_patterns"""
    for table in lookup_tables:
        some_feature_found = True
        regex_pattern = self._generate_lookup_regex(table)
        lookup_regex = {"name": table["name"], "pattern": regex_pattern}
        self.known_patterns.append(lookup_regex)
    return some_feature_found
```

**Comment by wochinge** [comment]
Closing as this was fixed with Rasa Open Source 2
