### ISSUE TITLE
Add a lookup entity extractor

### ISSUE THREAD

**Issue by tabergma** [RasaHQ/rasa#5957]
**Description of Problem**:
Lookup tables are used to create additional features for our entity extractors. In order for the features (aka "the word is part of lookup table xyz, so it is likely that is has the entity xyz") to work, you need to have some examples in your training data with entires from the lookup table.

However, many users think that all entries in the lookup table are extracted as an entity right away. So, as soon as an entry from the lookup table is detected it is extracted as an entity. Many users on the forum struggling with this.

**Overview of the Solution**:
- Create a new component `LookupEntityExtractor` that takes a lookup table. It will extract exact matches of entries in the lookup table and marks them as certain entity. (What about plural/singular/etc. of words? Should we also consider those?)
- We should update the docs to clarify the difference between lookup tables and lookup entity extractor.

**Comment by erohmensing** [comment]
@tabergma this is an interesting idea -- i definitely think users are confused about this. Do you think a `RegexEntityExtractor` would similarly be helpful? I think some users have implemented it themselves already

**Comment by tabergma** [comment]
@erohmensing Good point 👍 `RegexFeaturizer` could cause a similar issue, might make sense to also add an extractor for it.

**Comment by koaning** [comment]
@JiteshGaikwad if case you're interested, we'd be interested in a PR relating to your work [here](https://github.com/JiteshGaikwad/LookupEntityExtractor/).

**Comment by JiteshGaikwad** [comment]
hey @koaning @tabergma @erohmensing  I have submitted the [PR](https://github.com/RasaHQ/rasa/pull/6183)
