### ISSUE TITLE
Rasa test core is too slow when stories.md has many data.

### ISSUE THREAD

**Issue by abeyn** [RasaHQ/rasa#5960]
**Rasa SDK version** 1.9.5:

**Python version**: 3.6.8

**Operating system** windows

**Issue**:

1. Fill in stories.md with 18MB data;
2. Run rasa test core;
3. Break in function _is_nlg_story_format.

In function **_is_nlg_story_format** rasa search string by regular expression **r"##\s*.*\n\*[^:]*\/.*\n\s*\t*\-.*"** 
in large stories.md file without success, because stories.md is not **NLU** file.

This function works too slow, because regular expression doesn't match any of a million lines.

Why should we test stories.md for **NLU** when we start "**rasa test core**"?

**Stack**:

```
_is_nlg_story_format()
guess_format()
is_nlu_file()
_find_core_nlu_files_in_directory()
get_core_nlu_files()
get_core_directory()
run_core_test()
main()

```

**Command or request that led to error**:
```
python -m rasa test core -s data\core\ --out results_core_train
```

**Comment by sara-tagger** [comment]
Thanks for the issue, @alwx will get back to you about it soon!

###### You may find help in the [docs](https://rasa.com/docs/) and the [forum,](https://forum.rasa.com/) too 🤗
