### ISSUE TITLE
I have the problem about memory when I running Inference for model rasa

### ISSUE THREAD

**Issue by hungptit123** [RasaHQ/rasa#5971]
I'm running rasa run to testing. But a long time I request much message. I meet problem about memory. Memory is increament 100MB with 6000 request message. I don't know Rasa save into Cache what??. I using tracker stories SQL to save story. I try to handle Tracker which will retrieval include conversation_id and Events. But problem it not here. 
So I don't know solve this problem.
I hope Rasa could explain about problem increament Memory by the time request to it.

**Comment by sara-tagger** [comment]
Thanks for raising this issue, @Ghostvv will get back to you about it soon✨

###### Please also check out the [docs](https://rasa.com/docs/) and the [forum](https://forum.rasa.com/) in case your issue was raised there too 🤗

**Comment by Ghostvv** [comment]
what version of rasa open source are you using?

**Comment by hungptit123** [comment]
I'm using rasa 1.9.0 and I'm using mutil worker sanic of rasa. I'm running 24 workers and I use tool to test request API to then I have problem memory increasement by the time. in processing load model, It take 20GB Mem CPU after load model finish, I start testing with tool Then I have this problem

**Comment by ricwo** [comment]
There was a memory leak which was [fixed](https://rasa.com/docs/rasa/changelog/#id51) in version 1.9.4. Please upgrade to at least that version.
