### ISSUE TITLE
NLU EVALUATION Feature request

### ISSUE THREAD

**Issue by Asma-droid** [RasaHQ/rasa#5988]
Hi all,

When computing the evaluation metrics, you have taken the argmax to choose the predicted intent. In the other side, you have to taken into consideration the NLU_threshold that is given in the pipeline.

Let us take an example:

*   Imagine that the NLU threshold is set to 0.7.
*   _Z_ is the real intent class of an expression _X_ .
*   Rasa predict the real intent class _Z_ of the expression _X_ with a probability of 0.4

--> The evaluation metrics and the reality will give contradictory results.

Best regards,

**Comment by sara-tagger** [comment]
Thanks for submitting this feature request 🚀 @koaning will get back to you about it soon! ✨

**Comment by twerkmeister** [comment]
Hi @Asma-droid, sorry for the long delay and thank you for submitting the issue. This sounds like a thing we should absolutely fix. 

Would you mind sharing your config with us? Do you mean you have a `FallbackClassifier` with a threshold of `0.7`? Also, what version of rasa did you use?
