### ISSUE TITLE
Internal bug: NLU files pass the rasa.data.is_story_data check

### ISSUE THREAD

**Issue by ortsaCniveK** [RasaHQ/rasa#5992]
**Rasa version**: 1.10.2 (master)

**Python version**: 3.7.5

**Operating system** (windows, osx, ...): Linux

**Issue**:
Markdown files (even in nlu format) still pass the is_story_file test (because of the loose regex in `rasa.data._contains_story_pattern`).

**Solution**:
- [x] Test `rasa.data.is_story_file` with NLU training data formats, assert they are not story files
- [x]  Make regex more specific and don't match on NLU training data formats

**Comment by sara-tagger** [comment]
Thanks for raising this issue, @alwx will get back to you about it soon✨

###### Please also check out the [docs](https://rasa.com/docs/) and the [forum](https://forum.rasa.com/) in case your issue was raised there too 🤗
