### ISSUE TITLE
[Documentation]Docs error in Rasa X docker connect deploy 

### ISSUE THREAD

**Issue by hernanbari** [RasaHQ/rasa#6003]
The documentation in [this section](https://rasa.com/docs/rasa-x/installation-and-setup/existing-deployment/#docker-compose-deployment) states that:

> Now, restart the RabbitMQ service with the sudo docker-compose restart rabbit command. Make sure you’ve allowed traffic to port 5672 in your VM firewall.

But it didn't work for me (`docker-compose ps` showed that the ports weren't open), so I checked docker [documentation](https://docs.docker.com/compose/reference/restart/):

> If you make changes to your docker-compose.yml configuration these changes are not reflected after running this command. For example, changes to environment variables (which are added after a container is built, but before the container’s command is executed) are not updated after restarting.

After I run `sudo docker-compose down` and `sudo docker-compose up`, I checked with `docker-compose ps` that the ports where open.

OS: MacOS, but I don't think is relevant Rasa version: latest Doc version: latest

**Comment by sara-tagger** [comment]
Thanks for raising this issue, @wochinge will get back to you about it soon✨

###### Please also check out the [docs](https://rasa.com/docs/) and the [forum](https://forum.rasa.com/) in case your issue was raised there too 🤗

**Comment by wochinge** [comment]
Thanks a lot @hernanbari ! We will update that asap 👍

**Comment by tczekajlo** [comment]
@joejuzl @TyDunn How is the issue related to the infrastructure? (that something contains Docker in the name doesn't mean that it's an infrastructure issue automatically :))

**Comment by joejuzl** [comment]
> @joejuzl @TyDunn How is the issue related to the infrastructure? (that something contains Docker in the name doesn't mean that it's an infrastructure issue automatically :))

Ooops sorry @tczekajlo. We miss-read and assumed there were docker-compose changes to be made. (We've been going through *a lot* of issues 😅 ).
