### ISSUE TITLE
Request to add flag or response message from Rasa Server

### ISSUE THREAD

**Issue by MuraliChandran** [RasaHQ/rasa#6011]
**Description of Problem**:
I am currently running two different process threads in C# using command prompt with commands
1)rasa run -m models --enable-api --cors '*' --debug
2)rasa run actions --debug
I am building a game, Where the second command relies on the first command to get results. 

**Overview of the Solution**:
When the root print a message in the command prompt "Rasa server is up and running". It needs to set a flag = true on the web server routes.

**What would a possible solution look like?**:
Its my suggestion creating a web server routes: Like /IsServerStarted. Once the "Rasa Server is up and running" the flag will communicate to web server routes and set the flag to True for that particular app.route. I can use http://localhost:5005/IsServerStarted to check the Rasa api is running or not and once its started and will continue the remaining sequential steps.

**Examples** (if relevant):

**Blockers** (if relevant):

**Definition of Done**:

**Comment by sara-tagger** [comment]
Thanks for submitting this feature request 🚀 @rctatman will get back to you about it soon! ✨

**Comment by wochinge** [comment]
Can't you use the `/health` or `/status` endpoint?
