### ISSUE TITLE
RulePolicy: Have one `validate_form` function instead of multiple ones

### ISSUE THREAD

**Issue by wochinge** [RasaHQ/rasa#6016]
**Current State**
As part of the `RulePolicy` we moved the `FormAction` to Rasa Open Source. The form logic is now inside Rasa Open Source. The slot validation can be overwritten by adding custom actions with the syntax `validate_<slot name>` ([see this part of the code](https://github.com/RasaHQ/rasa/blob/da148ae98cbd0c03c8c5a48161622f700e15ec22/rasa/core/actions/forms.py#L390)) . The custom validation function currently receives a temporary tracker which means it's the current conversation + any new `SlotSet` events. 

**Proposed Changes**
- [x] have one function `action_validate_<form_name` to validate everything. `action_validate_<form_name` can also be used to apply custom slot mappings. This means whatever slots they set, they set.
- [x] Change the temporary tracker which we send to this action so that it is clear which slots were extracted previously. This means we send `[*old_tracker_events, ActionExecuted(<form name>), - - [ ] extracted slots)
- [x] Currently we return a `ActionExecutedRejection` event if no new potential slot values were found (see [here](https://github.com/RasaHQ/rasa/blob/da148ae98cbd0c03c8c5a48161622f700e15ec22/rasa/core/actions/forms.py#L436)). As users can now implement their custom slot mappings as part of the `action_validate_<form_name` we need to change the logic. We now should return a `ActionExecutedRejection` when
  * no new slots were extracted **and**
  * `action_validate_<form_name` did neither return a `SlotSet` event nor a bot response

**Comment by wochinge** [comment]
@Ghostvv Just realized that this breaks if the user is adding more slots in the custom action (changing the type of mapping is fine, just an entirely new slot would break things). We can work around that by checking if the custom action returns `SlotSet(REQUESTED_SLOT, <some_slot_name>)`?

**Comment by Ghostvv** [comment]
entire new slot would break rejection logic?

**Comment by wochinge** [comment]
Because we `FormAction.request_next_slot` will check if all slots from the `SlotMapping` are set. In case they are all set, the form will be marked as done. The problem is that it could be the case that all slots from the slotmappings are filled, but the custom action wants to fill some others.

**Comment by Ghostvv** [comment]
so the problems with custom slot mappings? I propose to create a custom separate action that is run every time to get custom slot mappings as a temporary solution

**Comment by wochinge** [comment]
why not checking the `validate_<form_name>` returned `SlotSet(REQUESTED_SLOT, "xy")`?

**Comment by Ghostvv** [comment]
because it might set the other slot

**Comment by Ghostvv** [comment]
> Because we FormAction.request_next_slot will check if all slots from the SlotMapping are set. In case they are all set, the form will be marked as done. The problem is that it could be the case that all slots from the slotmappings are filled, but the custom action wants to fill some others.

this is regarding our discussion that there should be a custom action for required slots

**Comment by wochinge** [comment]
@Ghostvv 

What do you mean with the following? Which "other slot"?

> because it might set the other slot

**Comment by Ghostvv** [comment]
validate method is arbitrary. Users can return any event they want in there, then `required_slots` method can be conditioned on a tracker to modify next requested slot accordingly

**Comment by Ghostvv** [comment]
@wochinge we also need required slots to be defined through a custom action. is it part of this PR?

**Comment by wochinge** [comment]
Yeah, they can simply return a `SlotSet("requested_slot", "whatever slot they want")` event and we will listen to them.
