### ISSUE TITLE
Integrated model not found (created with rasa version 0.0.0)

### ISSUE THREAD

**Issue by andreinastase1010** [RasaHQ/rasa#6022]
**Rasa version**:Rasa 1.10.2

**Rasa SDK version** (if used & relevant):

**Rasa X version** (if used & relevant):0.26.3

**Python version**:3.6.9

**Operating system** (windows, osx, ...): Ubuntu 18.04

**Issue**: I integrated a model that was obtained through FastText and SpaCy (romanian language).
I followed this tutorial: https://medium.com/strai/build-a-rasa-nlu-chatbot-with-spacy-with-fasttext-240e192082bd
and I got the next error when I started rasa x with the new model copied in the models folder:
the model was trained with Rasa version 0.0.0.

**Error (including full traceback)**:You are using an outdated version of Rasa X (0.26.3).
A new version 0.29.1) is available.
Please follow these instructions to update:
https://rasa.com/docs/rasa-x/installation-and-setup/updating

Starting Rasa X in local mode... 🚀
/home/andrei/Documents/Andrei/Rasa/env/lib/python3.6/site-packages/rasa/core/training/dsl.py:431: UserWarning: Found unknown intent 'greet' on line 2. Please, make sure that all intents are listed in your domain yaml.
  docs=DOCS_URL_DOMAINS,
/home/andrei/Documents/Andrei/Rasa/env/lib/python3.6/site-packages/rasa/core/training/dsl.py:431: UserWarning: Found unknown intent 'mood_great' on line 4. Please, make sure that all intents are listed in your domain yaml.
  docs=DOCS_URL_DOMAINS,
/home/andrei/Documents/Andrei/Rasa/env/lib/python3.6/site-packages/rasa/core/training/dsl.py:431: UserWarning: Found unknown intent 'mood_unhappy' on line 4. Please, make sure that all intents are listed in your domain yaml.
  docs=DOCS_URL_DOMAINS,
/home/andrei/Documents/Andrei/Rasa/env/lib/python3.6/site-packages/rasa/core/training/dsl.py:431: UserWarning: Found unknown intent 'affirm' on line 7. Please, make sure that all intents are listed in your domain yaml.
  docs=DOCS_URL_DOMAINS,
/home/andrei/Documents/Andrei/Rasa/env/lib/python3.6/site-packages/rasa/core/training/dsl.py:431: UserWarning: Found unknown intent 'deny' on line 7. Please, make sure that all intents are listed in your domain yaml.
  docs=DOCS_URL_DOMAINS,
/home/andrei/Documents/Andrei/Rasa/env/lib/python3.6/site-packages/rasa/core/training/dsl.py:431: UserWarning: Found unknown intent 'goodbye' on line 2. Please, make sure that all intents are listed in your domain yaml.
  docs=DOCS_URL_DOMAINS,
/home/andrei/Documents/Andrei/Rasa/env/lib/python3.6/site-packages/rasa/core/training/dsl.py:431: UserWarning: Found unknown intent 'bot_challenge' on line 2. Please, make sure that all intents are listed in your domain yaml.
  docs=DOCS_URL_DOMAINS,
/home/andrei/Documents/Andrei/Rasa/env/lib/python3.6/site-packages/rasa/core/training/dsl.py:431: UserWarning: Found unknown intent 'greet' on line 3. Please, make sure that all intents are listed in your domain yaml.
  docs=DOCS_URL_DOMAINS,
/home/andrei/Documents/Andrei/Rasa/env/lib/python3.6/site-packages/rasa/core/training/dsl.py:431: UserWarning: Found unknown intent 'deny' on line 5. Please, make sure that all intents are listed in your domain yaml.
  docs=DOCS_URL_DOMAINS,
/home/andrei/Documents/Andrei/Rasa/env/lib/python3.6/site-packages/rasa/core/training/dsl.py:431: UserWarning: Found unknown intent 'goodbye' on line 7. Please, make sure that all intents are listed in your domain yaml.
  docs=DOCS_URL_DOMAINS,
/home/andrei/Documents/Andrei/Rasa/env/lib/python3.6/site-packages/rasa/core/training/dsl.py:431: UserWarning: Found unknown intent 'mood_wantToTravel' on line 4. Please, make sure that all intents are listed in your domain yaml.
  docs=DOCS_URL_DOMAINS,
/home/andrei/Documents/Andrei/Rasa/env/lib/python3.6/site-packages/rasa/core/training/dsl.py:431: UserWarning: Found unknown intent 'mood_tripPlace' on line 6. Please, make sure that all intents are listed in your domain yaml.
  docs=DOCS_URL_DOMAINS,
/home/andrei/Documents/Andrei/Rasa/env/lib/python3.6/site-packages/rasa/core/training/dsl.py:431: UserWarning: Found unknown intent 'mood_noOfPers' on line 9. Please, make sure that all intents are listed in your domain yaml.
  docs=DOCS_URL_DOMAINS,
/home/andrei/Documents/Andrei/Rasa/env/lib/python3.6/site-packages/rasa/core/training/dsl.py:431: UserWarning: Found unknown intent 'mood_departureDate' on line 11. Please, make sure that all intents are listed in your domain yaml.
  docs=DOCS_URL_DOMAINS,
/home/andrei/Documents/Andrei/Rasa/env/lib/python3.6/site-packages/rasa/core/training/dsl.py:431: UserWarning: Found unknown intent 'mood_tripDuration' on line 13. Please, make sure that all intents are listed in your domain yaml.
  docs=DOCS_URL_DOMAINS,
/home/andrei/Documents/Andrei/Rasa/env/lib/python3.6/site-packages/rasa/core/training/dsl.py:431: UserWarning: Found unknown intent 'mood_tripConfirmed' on line 16. Please, make sure that all intents are listed in your domain yaml.
  docs=DOCS_URL_DOMAINS,
/home/andrei/Documents/Andrei/Rasa/env/lib/python3.6/site-packages/rasa/core/training/dsl.py:431: UserWarning: Found unknown intent 'mood_wantToTravel' on line 5. Please, make sure that all intents are listed in your domain yaml.
  docs=DOCS_URL_DOMAINS,
/home/andrei/Documents/Andrei/Rasa/env/lib/python3.6/site-packages/rasa/core/training/dsl.py:431: UserWarning: Found unknown intent 'mood_tripPlace' on line 7. Please, make sure that all intents are listed in your domain yaml.
  docs=DOCS_URL_DOMAINS,
/home/andrei/Documents/Andrei/Rasa/env/lib/python3.6/site-packages/rasa/core/training/dsl.py:431: UserWarning: Found unknown intent 'mood_noOfPers' on line 10. Please, make sure that all intents are listed in your domain yaml.
  docs=DOCS_URL_DOMAINS,
/home/andrei/Documents/Andrei/Rasa/env/lib/python3.6/site-packages/rasa/core/training/dsl.py:431: UserWarning: Found unknown intent 'mood_departureDate' on line 12. Please, make sure that all intents are listed in your domain yaml.
  docs=DOCS_URL_DOMAINS,
/home/andrei/Documents/Andrei/Rasa/env/lib/python3.6/site-packages/rasa/core/training/dsl.py:431: UserWarning: Found unknown intent 'mood_tripDuration' on line 14. Please, make sure that all intents are listed in your domain yaml.
  docs=DOCS_URL_DOMAINS,
/home/andrei/Documents/Andrei/Rasa/env/lib/python3.6/site-packages/rasa/core/training/dsl.py:431: UserWarning: Found unknown intent 'mood_tripConfirmed' on line 17. Please, make sure that all intents are listed in your domain yaml.
  docs=DOCS_URL_DOMAINS,
**2020-06-13 14:24:13 ERROR    rasax.community.services.model_service  - Could not find model at path 'models/ro_model-0.0.0.tar.gz'.
Version of model ro_model-0.0.0.tar.gz version is not compatible. The model was trained with Rasa version 0.0.0 but the current Rasa requires a minimum version of 1.10.0. Please retrain your model with a more recent Rasa version.**

The server is running at http://localhost:5002/login?username=me&password=jMDBMlSOega5

2020-06-13 14:24:22.597484: E tensorflow/stream_executor/cuda/cuda_driver.cc:351] failed call to cuInit: CUDA_ERROR_NO_DEVICE: no CUDA-capable device is detected

```

```

**Command or request that led to error**:rasa x
```

```

**Content of configuration file (config.yml)** (if relevant):# Configuration for Rasa NLU.
# https://rasa.com/docs/rasa/nlu/components/
language: ro
pipeline:
- name: "SpacyNLP"
- name: "SpacyTokenizer"
- name: "SpacyFeaturizer"
- name: "RegexFeaturizer"
- name: "DucklingHTTPExtractor"
  # url of the running duckling server
  url: "http://localhost:5002"
  # dimensions to extract
  dimensions: ["time", "number", "amount-of-money", "distance", "duration", "email", "phone-number"]
  # allows you to configure the locale, by default the language is
  # used
  locale: "ro_RO"
  # if not set the default timezone of Duckling is going to be used
  # needed to calculate dates from relative expressions like "tomorrow"
  timezone: "Europe/Bucharest"
- name: "CRFEntityExtractor"
- name: "EntitySynonymMapper"
- name: "SklearnIntentClassifier"

# Configuration for Rasa Core.
# https://rasa.com/docs/rasa/core/policies/
policies:
  - name: MemoizationPolicy
  - name: KerasPolicy
    epochs: 50
    max_history: 6
  - name: MappingPolicy
  - name: "FormPolicy"
```yml

```

**Content of domain file (domain.yml)** (if relevant):
```yml

```

**Comment by sara-tagger** [comment]
Thanks for the issue, @koaning will get back to you about it soon!

###### You may find help in the [docs](https://rasa.com/docs/) and the [forum,](https://forum.rasa.com/) too 🤗

**Comment by doguaraci** [comment]
Having the same issue
