### ISSUE TITLE
Rasa X should have an interface for projects imported via MultiProjectImporter

### ISSUE THREAD

**Issue by kevinthemself** [RasaHQ/rasa#6025]
**Description of Problem**:

After adding a couple projects as imports, there’s no way to view the stories, the domains, or NLU training data. For imported projects this is potentially a huge issue as the domain in Rasa X does not match the resulting model's domain (which would ostensibly contain the complete domain); the same issue exists with training data.

[Relevant forum post](https://forum.rasa.com/t/rasa-x-doesnt-import-stories-from-imported-projects-with-the-multiprojectimporter-feature-request)

**Overview of the Solution**:

Import the projects into the Rasa X training data via the TrainingDataImporter interface and/or create a UI to display these projects' training data for iteration in Rasa X

**Examples** (if relevant):

**Blockers** (if relevant):

May require a change in how models are trained on Rasa X, in the event you wanted to train and test an imported project, but not the parent project.

**Definition of Done**:

*   [ ] Tests are added to train an individual, imported project, as well as the compiled model with all imported project training data in Rasa X
*   [ ] Training data is imported based on `config.yml`, not just based on a heuristic that looks for `rasa init` folder structure (which would also allow for custom training data importers to be used with Rasa X)
*   [ ] Rasa X displays imported training data from the specified projects in the `config.yml` of the root project and allows for edits and synchronization with Git repo
*   [ ] root-level or project-level models can be trained ad-hoc and added to trained model interface in Rasa X

**Comment by sara-tagger** [comment]
Thanks for submitting this feature request 🚀 @amn41 will get back to you about it soon! ✨

**Comment by amn41** [comment]
hi @ortsaCniveK , thanks for writing this up! I'm generally on board with this idea, and we will likely make moves in this direction. However there is a lot of complexity involved so might take some time.

**Comment by alexweidauer** [comment]
Thank you for raising this issue about Rasa X. We decided to stop supporting the Community Edition (free version) of ‘Rasa X’ (see more info here: https://rasa.com/blog/rasa-x-community-edition-changes/). That’s why we’ve closed your issue. We suggest that Rasa Enterprise customers raise the issue with our customer support team if they haven’t done so already.
