### ISSUE TITLE
[Documentation] Building an Action Server Image should mention changing start command

### ISSUE THREAD

**Issue by ortsaCniveK** [RasaHQ/rasa#6026]
**Rasa version**: 1.10.2

**Rasa SDK version** (if used & relevant): 1.10.0

**Rasa X version** (if used & relevant): 0.29.1

**Python version**: 3.7

**Operating system** (windows, osx, ...): Linux

**Issue**:
An issue I ran into when following the [documentation instructions to build my own action server image](https://rasa.com/docs/rasa/user-guide/how-to-deploy/#building-an-action-server-image) was that I was receiving errors due to the default `rasa/rasa-sdk` start command.  Developers should know that if they wanted to have a module with their actions code (as is mentioned in the preceding steps), they should change their start command to `rasa-sdk start --actions actions` or the like, since rasa/rasa-sdk will have the default `rasa-sdk start --actions actions.actions` start command.

Documentation should reflect the need for that change.

**Error (including full traceback)**:
```

```

**Command or request that led to error**:
```

```

**Content of configuration file (config.yml)** (if relevant):
```yml

```

**Content of domain file (domain.yml)** (if relevant):
```yml

```

**Comment by ortsaCniveK** [comment]
since this is a quick fix, I'll work on a quick one-line documentation update PR

**Comment by sara-tagger** [comment]
Thanks for raising this issue, @erohmensing will get back to you about it soon✨

###### Please also check out the [docs](https://rasa.com/docs/) and the [forum](https://forum.rasa.com/) in case your issue was raised there too 🤗

**Comment by ortsaCniveK** [comment]
Closing as the preceding steps should be sufficient, although another mention for those who aren't as docker-savvy may still be a good idea.
