### ISSUE TITLE
Rename `master` branch to a neutral term

### ISSUE THREAD

**Issue by wochinge** [RasaHQ/rasa#6028]
**Proposed Change**
To reflect the values of Rasa and our community, we should rename the `master` branch to a neutral term. [Other projects have undertaken similar efforts](https://www.zdnet.com/article/github-to-replace-master-with-alternative-term-to-avoid-slavery-references/).

**Useful source**
https://github.com/github/renaming

**Things to change**
- [ ] rename branch. Potential candidates are `main`, `default`
- [ ] adapt CI pipeline checks to test for this new branch name instead of `master`
- [ ] check codebase for problematic naming (such as `whitelisting`, `blacklisting`)
- [ ] adapt links in docs / changelog / readme to `master` tree
- [ ] adapt badges in `Readme.md` to use new branch name
- [ ] adapt required checks in GitHub settings to match new branch name
- [ ] ?? the docs currently refer to `master` as well as to the tagged version. Do we have to change something here?
- [ ] Any other candidates which we have to check?

**Things which should be fine**
- our Docker builds since they are running as part of the CI now (we are not longer using dockercloud)

**Comment by karen-pal** [comment]
Be advised that renaming the branch actually **deletes** it, so I'm pretty sure all the pull requests associated with the current main "master" **will get closed** if you do so! This has happened on other open source projects that took this step a little too impulsively.

I'm not sure you'll be able to associate them to the new branch easily, I guess you could script that with the github api though. 

Just throwing some ideas: Maybe it would help instead of renaming "master", create a (new) "main" branch, associate the "master" pull requests to that branch and then delete "master". It would need testing through, i get the feeling you will still [loose the discussions ongoing on said pull requests/reviews](https://help.github.com/en/github/collaborating-with-issues-and-pull-requests/changing-the-base-branch-of-a-pull-request) . 

![image](https://user-images.githubusercontent.com/55008020/85868753-16e5d480-b7a1-11ea-97ca-848eae84b9b3.png)

**Comment by wochinge** [comment]
Hey @karen-pal ,

thanks for your support and helpful insights! 🙏

**Comment by ricwo** [comment]
@wochinge mainly the choice of a new branch name - `main`, `default` - something else?

**Comment by wochinge** [comment]
Or `development` or `stable`?

**Comment by wochinge** [comment]
https://github.com/github/renaming

**Comment by wochinge** [comment]
I'd go with GitHub's default `main` + start with the SDK before moving on to Rasa Open Source. Ideally we'd get also a list of our important public repositories 
* Helm chart
* repos for GitHub Actions 
* our training data repos

**Comment by m-vdb** [comment]
I went ahead and submitted a [PR for `rasa-sdk`](https://github.com/RasaHQ/rasa-sdk/pull/391), with a plan for this particular repo in the description.

**Comment by m-vdb** [comment]
@wochinge what about doing the change on Rasa X before doing it on Rasa Open Source?

**Comment by wochinge** [comment]
what's the reasoning behind this? Fine for me as well - but the public repo has the higher risk of hurting others with the term than the Rasa X repo.

**Comment by wochinge** [comment]
@m-vdb This might be something which should also go in the community newsletter? (cc @EmmaWightman )

**Comment by m-vdb** [comment]
@wochinge I've already asked her on Slack :)

**Comment by m-vdb** [comment]
> what's the reasoning behind this? Fine for me as well - but the public repo has the higher risk of hurting others with the term than the Rasa X repo.

briefly:
- foresee eventual issues with Rasa Open Source
- Rasa X is one of our most active repositories
- go one step further: we're not only changing what's public, we're also changing internal repos, because it can impact our own team too

**Comment by wochinge** [comment]
I agree with 3) and see 2) as neutral. Re 1) I _think_ it makes sense. To be honest the only things I'm worried about is the publishing of the docs. Up to you where we continue 👍🏻

**Comment by m-vdb** [comment]
@wochinge @tczekajlo do any of you wants to do the changes in the [RasaHQ/rasa-x-helm](https://github.com/RasaHQ/rasa-x-helm) repo ?

**Comment by wochinge** [comment]
yes, on it

**Comment by m-vdb** [comment]
and same for GitHub action repos: do you want to take care of the renaming of the branch @wochinge?

**Comment by wochinge** [comment]
Helm is done - I'll do the actions as well

**Comment by wochinge** [comment]
https://github.com/RasaHQ/rasa-action-server-gha is done
https://github.com/RasaHQ/rasa-train-test-gha was already renamed but still updating some vocabulary + some old errors in the CI workflows

**Comment by wochinge** [comment]
@m-vdb How should we go about the other repos? I think [Sara](https://github.com/RasaHQ/rasa-demo) is probably the most important left + all our demo bots

**Comment by m-vdb** [comment]
@wochinge I think @erohmensing is already taking care of it (or will be soon). I think we can close this ticket now!

**Comment by m-vdb** [comment]
Thank you @wochinge for driving this change! 🙌🏻
