### ISSUE TITLE
Warning about intents not in domain is shown when sending a message to /model/parse while running rasa with an NLU-only model

### ISSUE THREAD

**Issue by chkoss** [RasaHQ/rasa#6032]
**Issue**:
When sending a message to /model/parse while running rasa with an NLU-only model, the following warning is shown for the recognised intent:
`UserWarning: Interpreter parsed an intent 'greet' which is not defined in the domain. Please make sure all intents are listed in the domain.
  More info at https://rasa.com/docs/rasa/core/domains/`

**Command or request that led to error**:
```
rasa train nlu
rasa run --enable-api -m models/nlu-20200616-181712.tar.gz
curl localhost:5005/model/parse -d '{"text":"hi"}
```

**Comment by muximuxi** [comment]
same error
