### ISSUE TITLE
Can't add regex using Rasa X

### ISSUE THREAD

**Issue by diego-vieira** [RasaHQ/rasa#6035]
Related issue https://github.com/RasaHQ/rasa/issues/6049

**Rasa X version**
0.29.1

**Operating system** (windows, osx, ...):
- macOS Catalina 10.15.5 
- Chrome 83.0.4103.97

**Issue**:
Can't edit regex field. Keeps flashing and deleting the input data.

edit: it works if you already have some regex, but not if your regex list is empty

**Video**:
https://www.loom.com/share/33e5cfe974214b229fa66fbe2f48c25b

**Comment by sara-tagger** [comment]
Thanks for raising this issue, @rctatman will get back to you about it soon✨

###### Please also check out the [docs](https://rasa.com/docs/) and the [forum](https://forum.rasa.com/) in case your issue was raised there too 🤗

**Comment by chkoss** [comment]
@diego-vieira Thanks for reporting this issue! We are aware of it and working on a fix (it should be fixed by https://github.com/RasaHQ/rasa-x/pull/3038).

**Comment by m-vdb** [comment]
@diego-vieira this is now fixed and will be released as part of `0.29.3` 🛺  (will be available shortly)

**Comment by p24Jordaan** [comment]
Hi! I'm having a similar problem now with Rasa X 0.32 . 
The regex UI is not updating from the nlu.md and I cannot add a new regex.
The console output of the site gives the error for  /api/projects/default/regexes/1 : "server responded with a status of 400 (Bad Request)" 
and 
/api/projects/default/regexes/60:1 :"server responded with a status of 404 (Not Found) " , and accessing it gives the message:
{"reasons":["Authorization header not present."],"exception":"Unauthorized"}

**Comment by m-vdb** [comment]
@p24Jordaan hi there! thanks for your feedback, could you open a new bug report for this and fill in the template? 🙏
