### ISSUE TITLE
Changelog URL redirect to the wrong URL

### ISSUE THREAD

**Issue by diego-vieira** [RasaHQ/rasa#6047]
Just got a notification about a new version from within Rasa X UI, when clicking `See what's new button` I was taken to https://rasa.com/docs/rasa-x/rasa-x-changelog

![image](https://user-images.githubusercontent.com/930792/85153762-78acb880-b24e-11ea-8708-859c8ba7ba13.png)

Which in turn redirected me to https://rasa.com/docs/rasa-x/changelog/rasa-x-changelog/* causing a 404 page.

**Comment by sara-tagger** [comment]
Thanks for the issue, @dakshvar22 will get back to you about it soon!

###### You may find help in the [docs](https://rasa.com/docs/) and the [forum,](https://forum.rasa.com/) too 🤗
