### ISSUE TITLE
Creating a new intent via Rasa X does not update the UI

### ISSUE THREAD

**Issue by diego-vieira** [RasaHQ/rasa#6048]
**Rasa version**:
1.10.3

**Rasa X version** (if used & relevant):
0.29.2

**Operating system** (windows, osx, ...):
- macOS Catalina 10.15.5
- Chrome 83.0.4103.106

**Issue**:
On NLU Inbox when creating a new intent and confirming, won't update the UI with the existing intent.

**Command or request that led to error**:
Video (no audio)<br>
https://www.loom.com/share/239f49f75b674dfebf9affb402f13b98<br>

```
1. Go to NLU Inbox
2. Make sure you have two or more items on the list
3. For the first item on the list, on the column `Predicted Intent and Confidence` choose `Create new intent`
4. Enter the new intent name (here I pressed enter to see if it would make any difference)
5. Once done that, `Mark as correct` by clicking the button
6. Notice that the item you marked as correct disappear, however, the next item will have the newly created intent instead of the predicted intent.
7. Even after clicking the X, the newly created intent replaced the predicted intent
```

**Comment by sara-tagger** [comment]
Thanks for the issue, @amn41 will get back to you about it soon!

###### You may find help in the [docs](https://rasa.com/docs/) and the [forum,](https://forum.rasa.com/) too 🤗
