### ISSUE TITLE
Editing an existing regex cause the UI to replace other regex from the list

### ISSUE THREAD

**Issue by diego-vieira** [RasaHQ/rasa#6049]
Related issue https://github.com/RasaHQ/rasa/issues/6035

**Rasa version**:
1.10.3

**Rasa X version** (if used & relevant):
0.29.2

**Operating system** (windows, osx, ...):
- macOS Catalina 10.15.5 
- Chrome 83.0.4103.97

**Issue**:
Creating a new regex, cause the UI to replace (only visual) other items. After you add the regex and reload the page, the new item is added and none is replaced, however, the UI should list all regex without replacing the old ones.

**Error (including full traceback)**:
Video (no audio)<br>
https://www.loom.com/share/7a4c09e116fd4e54b71348246e8b5d64<br>

On the video, here is a before and after my edit.

**Before**
- amazon_order_id
- mobile_number
- order_id
- phone_number

**After**
- amazon_order_id
- *my_test_regex* (shouldn't this be added to the end of the list?)
- mobile_number
- *amazon_order_id* (this used to be phone_number)
- order_id

However, if you refresh the list, all items are edited correctly and none is actually replaced.

```
1. Go to Training -> NLU data
2. Make sure you have at least 4 regex items on the list
3. Add a new regex and save
4. Notice that one of the regex on the list will be replaced with another from the list
```

**Comment by sara-tagger** [comment]
Thanks for the issue, @chkoss will get back to you about it soon!

###### You may find help in the [docs](https://rasa.com/docs/) and the [forum,](https://forum.rasa.com/) too 🤗

**Comment by chkoss** [comment]
@Saladdin Can you check if this is still an issue, please?
