### ISSUE TITLE
Add endpoint functionality for chat method in rasa.jupyter

### ISSUE THREAD

**Issue by mcminis1** [RasaHQ/rasa#6051]
**Description of Problem**:
As a jupyter notebook user I am unable to access my custom actions server using the jupyter python sdk.

**Overview of the Solution**:
This is trivial to implement using an additional kwarg in rasa.jupyter.chat for the endpoints file.

**Definition of Done**:
- [x] Feature described the docs

**Comment by mcminis1** [comment]
Proposed solution would be used as follows.
```python
from rasa.jupyter import chat
chat(model_path, endpoints)
```

**Comment by mcminis1** [comment]
with the chat method as:
```python
def chat(
    model_path: Optional[Text] = None,
    endpoints: Optional[Text] = None,
    agent: Optional["Agent"] = None,
    interpreter: Optional[NaturalLanguageInterpreter] = None,
) -> None:
```

**Comment by sara-tagger** [comment]
Thanks for submitting this feature request 🚀 @TyDunn will get back to you about it soon! ✨

**Comment by mcminis1** [comment]
corresponding PR:
https://github.com/RasaHQ/rasa/pull/6052

**Comment by mcminis1** [comment]
@TyDunn Any thoughts on this improvement? The PR is ready to go.

**Comment by TyDunn** [comment]
@mcminis1 I see @rgstephens needs to review it. That will be the next step 👍

**Comment by mcminis1** [comment]
@TyDunn looks like it got signoff. How does it get merged in?

**Comment by TyDunn** [comment]
@mcminis1 Now that @rgstephens has approved it and the PR has past checks, it's up to him to merge it

**Comment by mcminis1** [comment]
It's been 27 days since approval. Is that a normal wait time for a PR to get merged? @TyDunn

**Comment by wochinge** [comment]
fixed by https://github.com/RasaHQ/rasa/pull/6052
