### ISSUE TITLE
Introduce a mechanism for a "Rasa bot owner verification"

### ISSUE THREAD

**Issue by degiz** [RasaHQ/rasa#6061]
**Description**: Rasa Open Source should have a way to allow hosting platforms/bot registries (e.g. [Amazon Bot Registry](https://www.amazonregistry.com/bot/)) verify that the Rasa bot actually belongs to a certain owner.

Even though users could do the verification manually, there's a way to simplify the process. Should Rasa Open Source provide a standard "mechanism" to do that, the hosting/bot registry can pre-configure the verification and list Rasa as a supported bot framework.

**Overview of the Solution**: One of the ways to do that is to introduce:

*   New endpoint, say `/verify`, that simply returns `HTTP 200`
*   An additional token (set by configuration) that would allow to access only one new endpoint

Users will have to copy the access token to the registry, thus proving that they actually control the bot.

**Definition of Done**:

*   [ ] Tests are added
*   [ ] Feature described the docs
*   [ ] Feature mentioned in the changelog

**Comment by tmbo** [comment]
Can you explain how the automatic verification works?

**Comment by degiz** [comment]
@tmbo my understanding is the following:

- We, as Rasa company, communicate to the bot registry, that Rasa bots can be verified using `{HOST}`/verify?token=`{TOKEN}`
- Bot registry asks bot owners to provide the `{HOST}` and `{TOKEN}` (i.g. via the UI console), and eventually performs a request to the bot, expecting to get HTTP 200 back

**Comment by tmbo** [comment]
So `TOKEN` would be the same for all bots? Or how would we, `Rasa company`, know which tokens are valid?

**Comment by degiz** [comment]
> So TOKEN would be the same for all bots

My idea was that it's unique. I think it makes sense to specify this token in i.g. `credentials.yml`, we can either generate it on a first run, or let the user specify it.

**Comment by tmbo** [comment]
ah, I misunderstood the first point, the rasa.com domain won't be used to validate the token but just to respond with the endpoint Amazon needs to use to validate the bot.

that makes sense :+1:

**Comment by degiz** [comment]
Oh I see where the confusion comes from.
Since we don't host the bot, we can only confirm that a certain endpoint _can_ verify the bot. But we can't guarantee that.
