### ISSUE TITLE
OpenAPI-specification differs from implementation

### ISSUE THREAD

**Issue by N-Olbert** [RasaHQ/rasa#6062]
**Rasa version**: 1.10.3

**Python version**: 3.7

**Operating system** (windows, osx, ...): Windows 10 B1909

**Issue**:
The provided OpenAPI-Spec doesn't seem to match the current implementation. 
For example see the *Tracker"-Object: According to the spec it should contain a conversation_id, but it actually contains a sender_id. 

Spec: https://github.com/RasaHQ/rasa/blob/6d5a9b74465f89f6a3a8c6193d9c1daa94c3c096/docs/_static/spec/rasa.yml#L1166
Example request (from action server's POST): 
```
{
	"next_action": "action_listen",
	"sender_id": "Rasa",
	"tracker": {
		"sender_id": "Rasa",
		"slots": {},
		"latest_message": {
			"intent": {
				"name": "bot_challenge",
				"confidence": 0.8328844904899597
			},

```

**Comment by sara-tagger** [comment]
Thanks for the issue, @rctatman will get back to you about it soon!

###### You may find help in the [docs](https://rasa.com/docs/) and the [forum,](https://forum.rasa.com/) too 🤗

**Comment by delmendo** [comment]
https://github.com/RasaHQ/rasa/issues/4683  
https://forum.rasa.com/t/conversation-and-sender-id/21890/4 

I hope it consolidates down to conversation_id - since it seems to be tied to the conversation not the sender....

**Comment by N-Olbert** [comment]
> #4683
> https://forum.rasa.com/t/conversation-and-sender-id/21890/4
> 
> I hope it consolidates down to conversation_id - since it seems to be tied to the conversation not the sender....

I agree. They are the same. 

This is more kind of a doc bug, because a server/client stub wont work out of the box when the given OpenAPI is used. 
BTW conversation_id is not the only difference, there are more (for example there is always a version sent to the custom action server). The problem without a proper OpenAPI is that you dont know which values are safe to use and which are for internal usage only (and therefore can be changed in the next update).

**Comment by N-Olbert** [comment]
I dont think this should be marked as stale as it is still true
