### ISSUE TITLE
Adhere to new Github rules

### ISSUE THREAD

**Issue by doubleungoodkitsune** [RasaHQ/rasa#6069]
It's recommended to adhere to the new Github rules and regulations, please see the [migration docs](https://github.com/doubleungoodkitsune/newworldcode)

**Comment by sara-tagger** [comment]
Thanks for the issue, @koaning will get back to you about it soon!

###### You may find help in the [docs](https://rasa.com/docs/) and the [forum,](https://forum.rasa.com/) too 🤗

**Comment by yankee450** [comment]
Thanks

**Comment by koaning** [comment]
This is unappreciated spam.
