### ISSUE TITLE
Docs for data validation mention not existing methods

### ISSUE THREAD

**Issue by wochinge** [RasaHQ/rasa#6070]
[This page](https://rasa.com/docs/rasa/1.10.3/user-guide/validate-files/) in the docs mentions `verify_all`.

It actually doesn't exist in the code: [https://github.com/RasaHQ/rasa/blob/730fd0646a9bc267388d2bda981b4eeb8307c5b6/rasa/validator.py#L19](https://github.com/RasaHQ/rasa/blob/730fd0646a9bc267388d2bda981b4eeb8307c5b6/rasa/validator.py#L19)

**Comment by ortsaCniveK** [comment]
Looks like that behavior might be found under `verify_nlu()`, think this would be an easy fix to rename
