### ISSUE TITLE
Expose filename header in model training api

### ISSUE THREAD

**Issue by Ezhvsalate** [RasaHQ/rasa#6075]
**Rasa version**: Rasa 1.10.1

**Python version**: 3.6.9

**Operating system**: Ubuntu 18.04.3 LTS (Bionic Beaver)

**Issue**:

I train a model using HTTP [/model/train](https://rasa.com/docs/rasa/api/http-api/#operation/trainModel) API and want to get a trained model filename as response header as defined in docs.

Unfortunately it seems like I can't do this: browser doesn't see response 'filename' header. 
All I get are following:
```
HTTP/1.1 200 OK
Connection: keep-alive
Keep-Alive: 5
Access-Control-Allow-Origin: http://localhost:3000
Access-Control-Allow-Credentials: true
Access-Control-Allow-Headers: content-type
Access-Control-Max-Age: None
Access-Control-Allow-Methods: DELETE, GET, HEAD, OPTIONS, PATCH, POST, PUT
Vary: Origin
Content-Length: 0
```
Looks like this is issue about '[Access-Control-Expose-Headers](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Access-Control-Expose-Headers)'. Can we add 'filename' to exposed headers?

**Comment by sara-tagger** [comment]
Thanks for the issue, @melindaloubser1 will get back to you about it soon!

###### You may find help in the [docs](https://rasa.com/docs/) and the [forum,](https://forum.rasa.com/) too 🤗

**Comment by melindaloubser1** [comment]
Can you post the request you're making/how you're making it? I do see the filename header returned with the request below:

```
curl --request POST --url http://localhost:5005/model/train \ 
--output model.tar.gz   \
  --header 'content-type: application/json' \
  --data '{
  "domain": "intents:\n  - greet\n  - goodbye\n  - affirm\n  - deny\n  - mood_great\n  - mood_unhappy\n\nactions:\n  - utter_greet\n  - utter_cheer_up\n  - utter_did_that_help\n  - utter_happy\n  - utter_goodbye\n\ntemplates:\n  utter_greet:\n  - text: \"Hey! How are you?\"\n\n  utter_cheer_up:\n  - text: \"Here is something to cheer you up:\"\n    image: \"https://i.imgur.com/nGF1K8f.jpg\"\n\n  utter_did_that_help:\n  - text: \"Did that help you?\"\n\n  utter_happy:\n  - text: \"Great carry on!\"\n\n  utter_goodbye:\n  - text: \"Bye\"",
  "config": "language: en\npipeline: supervised_embeddings\npolicies:\n  - name: MemoizationPolicy\n  - name: KerasPolicy",
  "nlu": "## intent:greet\n- hey\n- hello\n- hi\n## intent:goodbye\n- bye\n- goodbye\n- have a nice day\n- see you\n## intent:affirm\n- yes\n- indeed\n## intent:deny\n- no\n- never\n## intent:mood_great\n- perfect\n- very good\n- great\n## intent:mood_unhappy\n- sad\n- not good\n- unhappy",
  "stories": "## happy path\n* greet\n\n  - utter_greet\n\n* mood_great\n\n  - utter_happy\n\n## sad path 1\n* greet\n\n  - utter_greet\n\n* mood_unhappy\n\n  - utter_cheer_up\n\n  - utter_did_that_help\n\n* affirm\n\n  - utter_happy\n\n## sad path 2\n* greet\n\n  - utter_greet\n\n* mood_unhappy\n\n  - utter_cheer_up\n\n  - utter_did_that_help\n\n* deny\n\n  - utter_goodbye\n\n## say goodbye\n* goodbye\n\n  - utter_goodbye",
  "force": false,
  "save_to_default_model_directory": true
}' --dump-header header.txt
```

**Comment by Ezhvsalate** [comment]
@melindaloubser1, sure, curl or other tool like that will see custom header. But for js code in browser it won't be accessible by default. Please check [this link](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Access-Control-Expose-Headers) for more info.

I have prepared a demo app [here](https://github.com/Ezhvsalate/rasa-expose-headers-demo), you can reproduce this yourself.

It starts a simple react app, containing one button which launches model training at http://localhost:5005 and prints to browser console available response's headers: 

![image](https://user-images.githubusercontent.com/23470773/86093583-deebd380-bab7-11ea-8b98-98b9b9f3abde.png)

Then add the line [here](https://github.com/RasaHQ/rasa/blob/a52ef66390abfdb445e7fa4f874435153ff960ad/rasa/server.py#L358) to configure sanic-cors:
```
 app.config.CORS_EXPOSE_HEADERS = '*'
```
After that much more info is available to browser:
![image](https://user-images.githubusercontent.com/23470773/86093783-34c07b80-bab8-11ea-9620-157cb1b8680b.png)

Or less broadly:
```
 app.config.CORS_EXPOSE_HEADERS = 'filename'
```
![image](https://user-images.githubusercontent.com/23470773/86093905-65081a00-bab8-11ea-9250-7d2d23579eff.png)

If one of options above is suitable for you I can create a PR.

**Comment by melindaloubser1** [comment]
Ok that makes sense! Yes, if you could open a PR for exposing just `filename` additionally that'd be great.

**Comment by Ezhvsalate** [comment]
@melindaloubser1 created a PR. Please check it when you have time.

**Comment by melindaloubser1** [comment]
@Ezhvsalate I don't think the commit you linked to is actually part of a PR, I left a comment on it
