### ISSUE TITLE
Rasa X - Show when was last pull

### ISSUE THREAD

**Issue by dv336699** [RasaHQ/rasa#6080]
When making changes using Rasa X we get a notification about the changes and date - which is great. 
 [<span class="image-wrap" style="">![](https://user-images.githubusercontent.com/930792/85913395-40980d80-b82c-11ea-9de7-fb515daf496e.png)</span>](https://user-images.githubusercontent.com/930792/85913395-40980d80-b82c-11ea-9de7-fb515daf496e.png)

However, when doing changes outside Rasa X, there is no indication of when was the last pull. It would be extremely helpful to know when was the last pull/changes made outside Rasa X. 
 [<span class="image-wrap" style="">![](https://user-images.githubusercontent.com/930792/85913432-ab494900-b82c-11ea-90c7-318174f40f19.png)</span>](https://user-images.githubusercontent.com/930792/85913432-ab494900-b82c-11ea-90c7-318174f40f19.png)

**Comment by amn41** [comment]
cc @edmacovaz

**Comment by sladyn98** [comment]
@amn41  is this something that is being actively worked on or can be contributed by the community, if yes I would like to give this one a shot.

**Comment by amn41** [comment]
hi @sladyn98 ! yes we are working on making the internals of integrated version control more transparent to users, so you get more insight into what's happening. 
Thanks for offering to give it a shot! Unfortunately we can't accept outside contributions to Rasa X  because it's not open source.

**Comment by alexweidauer** [comment]
Thank you for raising this issue about Rasa X. We decided to stop supporting the Community Edition (free version) of ‘Rasa X’ (see more info here: https://rasa.com/blog/rasa-x-community-edition-changes/). That’s why we’ve closed your issue. We suggest that Rasa Enterprise customers raise the issue with our customer support team if they haven’t done so already.
