### ISSUE TITLE
Data Privacy in Rasa NLU

### ISSUE THREAD

**Issue by developer543** [RasaHQ/rasa#6098]
I had a question regarding the security of Rasa NLU. I want my data to be private, and wanted to ensure that none of my data ever leaves my machine, connects to Rasa's servers (or any servers other than my own — running locally), and nothing goes to the cloud. I want my data to be private and local. Is this true of Rasa NLU?

**Comment by sara-tagger** [comment]
Thanks for submitting this feature request 🚀 @TyDunn will get back to you about it soon! ✨

**Comment by N-Olbert** [comment]
Yes. You probably need an internet connection to run `pip install rasa`, but afterwards you can disconnect your machine form the internet and use rasa completely offline.

See also: https://forum.rasa.com/t/rasa-offline/15272

**Comment by TyDunn** [comment]
@developer543 @N-Olbert is correct. None of your data will ever leave your machine. Rasa NLU will not connect to any other servers. Nothing will go to the cloud. Rasa NLU is open source and licensed under the Apache License, which you can see [here](https://github.com/RasaHQ/rasa/blob/master/LICENSE.txt)
