### ISSUE TITLE
Rasa X - Creating a new intent doesn't add to domain

### ISSUE THREAD

**Issue by diego-vieira** [RasaHQ/rasa#6100]
**Rasa X version** (if used & relevant):
0.29.2

**Error (including full traceback)**:
```
0. Make sure you have Git Server integrated with Rasa X.
1. Go to NLU Inbox
2. On the list of predictions, create a new Intent
3. Save and confirm
4. Push changes to Git Server
5. Notice that only nlu.md is updated (domain.yml should also be updated to include the new intent)
```
![image](https://user-images.githubusercontent.com/930792/86156061-46784200-bafd-11ea-8157-0bddf121c8a6.png)

**Comment by sara-tagger** [comment]
Thanks for the issue, @amn41 will get back to you about it soon!

###### You may find help in the [docs](https://rasa.com/docs/) and the [forum,](https://forum.rasa.com/) too 🤗
