### ISSUE TITLE
Fix misleading function names

### ISSUE THREAD

**Issue by chkoss** [RasaHQ/rasa#6101]
**Problem**
The `rasa.core` modules `nlg.generator`, `broker`, `interpreter`, `tracker_store` and `lock_store` all have a function `_load_from_module_string`. This function does **not** take a string as input argument though but an `EndpointConfig`.

**Solution**
Find a more descriptive name and rename the functions.

**Comment by karen-pal** [comment]
hey, could i take this task? I'd like to work on this.

**Comment by chkoss** [comment]
Of course, thank you! If this is your first contribution to Rasa, please check out our [code contributor guidelines](https://github.com/RasaHQ/rasa/blob/master/CONTRIBUTING.md#how-to-open-a-pr-and-contribute-code-to-rasa-open-source). Make sure to link this issue in your PR and let us know if anything is unclear :)

**Comment by karen-pal** [comment]
@chkoss Hmm I seem to be having problems with the CLA signature thing. I am the commiter Karen Palacio, not sure how to fix that.

**Comment by chkoss** [comment]
Maybe the email address that you used for the commit is not linked to your GitHub account? In the PR it says 
> **Karen Palacio** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://docs.github.com/en/github/committing-changes-to-your-project/why-are-my-commits-linked-to-the-wrong-user#commits-are-not-linked-to-any-user).

You can try to fix it by following the proposed steps in that link.

**Comment by karen-pal** [comment]
I have followed those steps. It added "karen-pal" as a commiter, instead of changing "Karen Palacio" to signed.

**Comment by chkoss** [comment]
Hm :/ Sorry for the trouble!

Here is another idea how to try and fix this: When I look at the `git log`, commit 1 (https://github.com/RasaHQ/rasa/pull/6152/commits/24926b98a33212b6b95e3ea7acd067e3d01863c1) was committed by a different email address than commit 2 (https://github.com/RasaHQ/rasa/pull/6152/commits/d54bacf04b5522a9111380c1e6de06ea456c0bab). Commit 2 seems to be associated with your GitHub account and is working fine. So it would probably help to change the email address of commit 1 to be the same as for commit 2.

Here are some instructions by GitHub on how to do that: https://docs.github.com/en/github/using-git/changing-author-info
So I hope it will work if you run that script with
```
OLD_EMAIL="kunan@steel-chewer.fibertel.com.ar"
CORRECT_NAME="Karen Palacio"
CORRECT_EMAIL="karen.palacio@kunan.com.ar"
```
