### ISSUE TITLE
Rasa test nlu produces wrong partitions on using the percentages argument

### ISSUE THREAD

**Issue by AMR-KELEG** [RasaHQ/rasa#6120]
**Rasa version**: rasa==1.10.4

**Python version**: Python 3.6.9

**Operating system** (windows, osx, ...): Ubuntu 18

**Issue**:
Currently `rasa test nlu` allows specifying percentages of the training dataset to be excluded while training using the `-P` flag. This isn't currently done correctly.
E.g: If the percentages were `-P 50 25` then you would expect that the number of training samples would be 500 and 250 if the original training dataset size was 1000 samples.
BUT, the way the function currently work will generate number of training samples of 500 and 125 samples.

https://github.com/RasaHQ/rasa/blob/4830308fcc21ba3c82f296e510ba7544fb5166d4/rasa/nlu/test.py#L1848-L1865

**Command or request that led to error**:
```
rasa test nlu -c config.yml config_dup.yml -r 1 -p 50 25
```

I am willing to submit a PR to solve this so kindly assign the issue to me.

Thanks

**Comment by sara-tagger** [comment]
Thanks for the issue, @koaning will get back to you about it soon!

###### You may find help in the [docs](https://rasa.com/docs/) and the [forum,](https://forum.rasa.com/) too 🤗

**Comment by koaning** [comment]
Just to check, are you using tensorboard in your runs?

**Comment by AMR-KELEG** [comment]
> Just to check, are you using tensorboard in your runs?

Nope.

**Comment by tabergma** [comment]
@AMR-KELEG Thanks for catching this! Seem like you are correct. And thanks for create a PR already. We will give it a review soon.
