### ISSUE TITLE
Slack proxy option support

### ISSUE THREAD

**Issue by rgstephens** [RasaHQ/rasa#6123]
**Description of Problem**:
The slack channel does not currently support the slack client [proxy](https://github.com/slackapi/python-slackclient#proxy) option. This was discussed on the [forum](https://forum.rasa.com/t/slack-connector-has-to-use-proxy-for-outgoing-requests-in-docker/30845).

**Overview of the Solution**:
Add the client library [proxy](https://github.com/slackapi/python-slackclient#proxy) option to the slack channel [here](https://github.com/RasaHQ/rasa/blob/4830308fcc21ba3c82f296e510ba7544fb5166d4/rasa/core/channels/slack.py#L26) and expose in the `credentials.yml`.

**Definition of Done**:
- [ ] Feature described the docs
- [ ] Feature mentioned in the changlog

**Comment by iamtofr** [comment]
So is there any more todo on my side ?
