### ISSUE TITLE
Changing response in domain throws error Detected mismatch in domain specification

### ISSUE THREAD

**Issue by tatianafrank** [RasaHQ/rasa#6124]
**Rasa version**: 1.9.5

**Rasa SDK version** (if used & relevant): 

**Rasa X version** (if used & relevant):

**Python version**: 3.7

**Operating system** (windows, osx, ...): osx

**Issue**:

Ive been changing a response to include custom json but whenever I make edits and re-train the model then run rasa shell, I get errors about a mismatched domain.

**Error (including full traceback)**:
```
  File ".../lib/python3.7/site-packages/rasa/core/domain.py", line 756, in compare_with_specification
    f"Domain specification has changed. "
rasa.core.domain.InvalidDomain: Domain specification has changed. You MUST retrain the policy. Detected mismatch in domain specification. The following states have been 
         - removed: slot_webex_device_3,slot_device_type_5 
         - added: 
```

**Command or request that led to error**:
```
rasa shell
```

**Content of configuration file (config.yml)** (if relevant):
```yml

```

**Content of domain file (domain.yml)** (if relevant):
```yml

```

**Comment by sara-tagger** [comment]
Thanks for the issue, @JustinaPetr will get back to you about it soon!

###### You may find help in the [docs](https://rasa.com/docs/) and the [forum,](https://forum.rasa.com/) too 🤗
