### ISSUE TITLE
Error happened when trying to save conversation tracker to ‘SQLTrackerStore’

### ISSUE THREAD

**Issue by hungptit123** [RasaHQ/rasa#6125]
I'm using Mutil Worker of rasa (setting 5 workers). When I run server, everything is fine. But after 1-2 days then I send message occur error. Error flow below this. I also try to setting connection timeout of sqlalchemy but it is same. I hope you can suggest solove problems.

trying to save conversation tracker to 'SQLTrackerStoreCustom'. Falling back to use the 'InMemoryTrackerStore'. Please investigate the following error: (pymysql.err.OperationalError) (2006, "MySQL server has gone away (TimeoutError(110, 'Connection timed out'))")
[SQL: SELECT events.id AS events_id, events.sender_id AS events_sender_id, events.type_name AS events_type_name, events.timestamp AS events_timestamp, events.intent_name AS events_intent_name, events.action_name AS events_action_name, events.data AS events_data 
FROM events 
WHERE events.sender_id = %(sender_id_1)s ORDER BY events.timestamp]
[parameters: {'sender_id_1': '20200618120550-29fc3835-4828-4788-9e14-e761d09c6ffa'}]

**Comment by sara-tagger** [comment]
Thanks for raising this issue, @rctatman will get back to you about it soon✨

###### Please also check out the [docs](https://rasa.com/docs/) and the [forum](https://forum.rasa.com/) in case your issue was raised there too 🤗

**Comment by ujjwal-deswal** [comment]
Did you get any solution to this? facing the same issue at my end.
