### ISSUE TITLE
Rasa Roles and Groups

### ISSUE THREAD

**Issue by developer543** [RasaHQ/rasa#6131]
I am pleased with the feature that enables me to add roles and groups to entities and want to use this feature in production. However, I am concerned given that it says that this feature is:

> The Entity Roles and Groups feature is currently experimental and might change or be removed in the future 🔬 

Can I still use this feature in production? If I have installed this version of RASA, is that okay to use this feature in production?

**Comment by sara-tagger** [comment]
Thanks for submitting this feature request 🚀 @dakshvar22 will get back to you about it soon! ✨

**Comment by dakshvar22** [comment]
Hi @developer543 We have received very positive feedback on the whole feature, which is highly indicative of the possibility that the feature will stay and not removed. We haven't made an official call on this yet. There are a couple of issues that users reported which we are planning to fix in the coming months. The issues are related to the model, so the interface(training data format etc.) shouldn't change much in the future.
