### ISSUE TITLE
Log number of examples during training

### ISSUE THREAD

**Issue by TyDunn** [RasaHQ/rasa#6134]
**Description of Problem**:

During training and debugging NLU models, it would be helpful to know the number of training examples per intent

**Overview of the Solution**:

Log the number of examples per intent along with the total number of intents when training

**Comment by ariella879** [comment]
I would like to work on this.

**Comment by TyDunn** [comment]
@ariella879 Great! Here is [guide on how to contribute](https://forum.rasa.com/t/how-to-make-a-code-contribution-to-rasa/11291). Let me know if you have any questions

**Comment by melindaloubser1** [comment]
Closed by #6250
