### ISSUE TITLE
Extract Long Multi-word Entities

### ISSUE THREAD

**Issue by developer543** [RasaHQ/rasa#6140]
I am working on building a chatbot that will allow for long multi-word entities to be extracted, like so:
`Search the web [this is a search query and could be very long and could include punctuation.]`
`On the internet, find [hello]`
As you can see, I want to extract multi-word entities that don't have similarities in text other than the context in which they appear. Looking at Issue [#797](https://github.com/RasaHQ/rasa/issues/797), I saw that it was recommended to use dependency parsing rather than the entity approach. I am unsure how to implement this in Rasa. Thank you!

**Comment by sara-tagger** [comment]
Thanks for submitting this feature request 🚀 @b-quachtran will get back to you about it soon! ✨

**Comment by developer543** [comment]
@b-quachtran just wanted to follow up

**Comment by developer543** [comment]
@b-quachtran I just wanted to follow up again in regards to this issue.

**Comment by b-quachtran** [comment]
Hi @developer543, the CRF entity extractor built into the DIET classifier works pretty well for handling context-based multi-word entity recognition. Have you had a chance to test the entity extraction results using one of the pre-built pipelines? (https://rasa.com/docs/rasa/nlu/choosing-a-pipeline/)

**Comment by developer543** [comment]
@b-quachtran. Just to clarify, should I just train this random wildcard free text entity as I would any other entity using DIET classifier?

I have tried doing this. For example, I'll train:
`Text [this is a text message and could be very long and could include punctuation.](text)`
`Send a message to my friend saying [hello there friend! I want to hang out.](text)`
and of course, even more training data. 

However, the problem that I'm running into is that the DIET classifier will extract bits and pieces of the text entity and store it as multiple text's. 

> Text my friend how are you today. I am typing a long long long sentence. This may get broken up into fragments.

And then the result would be that `you today. I` and `This` are extracted as two separate `text` entities. I want the ENTIRE " how are you today. I am typing a long long long sentence. This may get broken up into fragments" to be saved as a `text` entity.

Thank you!

**Comment by b-quachtran** [comment]
Hi @developer543, pulling a response to this question from the forum here: 

You have two options:

- write a bunch of regexes for text [X] [Y] , send [X] a message saying [y]
- create an NER model with Rasa

neither of these will catch 100% of cases. If you assume the user will stick to a few common phrasings, use regexes. If you want more flexibility, you’ll need to train a model, but you’ll need a fair bit of data to get this to work, and it’ll never be 100% accurate

**Comment by WickedTree** [comment]
Is there any intent (pun intended 😃 ) to implement this into rasa? Or should I just use regex.

**Comment by b-quachtran** [comment]
@WickedTree I'd recommend using regex for this
