### ISSUE TITLE
Incorrect rendering of multiple doc pages on the website

### ISSUE THREAD

**Issue by ChargedMonk** [RasaHQ/rasa#6141]
Pages like [Slots](https://rasa.com/docs/rasa/core/slots/), [Tracker Stores,](https://rasa.com/docs/rasa/api/tracker-stores/) [Components,](https://rasa.com/docs/rasa/nlu/components/) and [Events.](https://rasa.com/docs/rasa/api/events/) have rendering issues where some divs overlap the text thus making them a bit messy. Please find the attached image for reference.
![slots](https://user-images.githubusercontent.com/45848481/86520964-1d8ede80-be68-11ea-8302-a3716b1bf5f8.png)

**Comment by sara-tagger** [comment]
Thanks for raising this issue, @koaning will get back to you about it soon✨

###### Please also check out the [docs](https://rasa.com/docs/) and the [forum](https://forum.rasa.com/) in case your issue was raised there too 🤗

**Comment by koaning** [comment]
Thanks for raising the issue. We were aware of this and we're checking when this change was introduced so that we may understand what went wrong here.

**Comment by erohmensing** [comment]
Here's what it looked like at sphinx ~ 1.7, what we had before dependabot updates:
![image](https://user-images.githubusercontent.com/22333512/87056135-7f06d280-c205-11ea-822a-437832ad93e3.png)


Upgrading to 2.0, looks like this: 
![image](https://user-images.githubusercontent.com/22333512/87055250-621dcf80-c204-11ea-8999-6c8674873290.png)

2.1.2 is the same:
![image](https://user-images.githubusercontent.com/22333512/87055618-df494480-c204-11ea-81c6-ff55cdf810d3.png)

2.2.0 introduces the issue:
![image](https://user-images.githubusercontent.com/22333512/87055761-0d2e8900-c205-11ea-8a4a-98b27b9e5eaa.png)

which looks the same on our current version, 3.1.1.

**Comment by hellonearthis** [comment]
This is still an issue. 
Adding   margin-left: 5px;
To the div.body dd, div.body li, div.body p {}
Corrects the formatting.

If you have greasemonkey or tampermonkey installed on your browser you can run this script to patch the CSS like above.
`// ==UserScript==
// @name         Rasa
// @namespace    http://tampermonkey.net/
// @version      0.1
// @description  try to take over the world!
// @author       You
// @match        https://rasa.com/docs/rasa/*
// @grant        GM_addStyle
// ==/UserScript==

(function() {
    'use strict';
})();

GM_addStyle ( "div.body dd, div.body li, div.body p {  margin-left: 5px;  }" );`

**Comment by hellonearthis** [comment]
There seems to be another similar CSS issue with `dl.field-list>dt`
which has  `word-break: break-word;`  on and is making it look nasty. 
Should be anything but **break-word** like  `word-break: normal;`
https://rasa.com/docs/rasa/nlu/components/#hftransformersnlp  

![image](https://user-images.githubusercontent.com/121805/92636666-da4f6100-f32b-11ea-9b2f-4249c9a0863a.png)

Adding this to the Tampermonkey script about, patches it for now.
`GM_addStyle ( "dl.field-list>dt { word-break: normal;  }" );`

**Comment by erohmensing** [comment]
Thank you so much for the very specific suggestions!
