### ISSUE TITLE
Fix DynamoDB table name keyword

### ISSUE THREAD

**Issue by rgstephens** [RasaHQ/rasa#6155]
**Rasa version**: 1.10.x

**Issue**:
The [docs](https://rasa.com/docs/rasa/api/tracker-stores/#dynamotrackerstore) for DynamoDB show `tablename` as the keyword. Should be `table_name`.

**Comment by TyDunn** [comment]
@rgstephens We are closing this because it is fixed in the latest version of the Rasa Open Source docs
