### ISSUE TITLE
New docs: changelog generation

### ISSUE THREAD

**Issue by m-vdb** [RasaHQ/rasa#6170]
⬆️ Relates to https://github.com/RasaHQ/growth/issues/1436

We need to adapt the changelog generation with the new docs system. Here is how it currently works:
- contributors add changlog fragments in the [`changlog/` folder](https://github.com/RasaHQ/rasa/tree/master/changelog)
- when we do a release, [we run `towncrier`](https://github.com/RasaHQ/rasa/blob/b932c9fe1406443ff72997682ebaabae5afb8c83/scripts/release.py#L286-L290) that generates the `CHANGELOG.rst` file.
- this changelog is included in the docs via [this `rst file](https://github.com/RasaHQ/rasa/blob/master/docs/changelog.rst)

Ideally we simply change the format to `md` everywhere, adapt the templates, and include the md file directly in the docs site, like we do today. Looks doable with the current tools.

**Comment by tmbo** [comment]
Fixed as part of https://github.com/RasaHQ/rasa/pull/6043/commits/c8d2bcc72082c2cd1e10aa729f220b99016dc521
