### ISSUE TITLE
Sending Additional Data to Utterance

### ISSUE THREAD

**Issue by developer543** [RasaHQ/rasa#6180]
I have created/trained my Rasa assistant and am working on creating my own custom UI. Depending on the type of response my bot is sending, I want to change the color of my bot's response. For example, if my bot's response is an order confirmation, I want my bot's utterance to be green in my UI, whereas for other responses I would want my bot's utterance to be red. How would I send this addition data (through the socketio path) to change the color of my bot's response. Thanks!

**Comment by sara-tagger** [comment]
Thanks for the question, our Github issue board is for **bugs and feature requests only,** though 😕
Please ask this question in the [forum✨](https://forum.rasa.com/c/rasa)

###### If you were describing a bug, please create a [report](https://github.com/RasaHQ/rasa/issues/new?labels=bug&template=bug_report.md) and fill out the template.

**Comment by sara-tagger** [comment]
Thanks for submitting this feature request 🚀 @closed will get back to you about it soon! ✨
