### ISSUE TITLE
Write RulePolicy documentation

### ISSUE THREAD

**Issue by wochinge** [RasaHQ/rasa#6184]
Write the documentation for the RulePolicy
* [x] document rules usage
* [x] document new form usage
* [x] document slot mappings in domain
* [x] document when to use rules / stories
* [x] migration guide

**Comment by wochinge** [comment]
From the other issue:

> describe how to use custom required_slots flow. Validate action can return which next slot is requested and also can return SlotSet(REQUESTED_SLOT, None) indicating that a form should be deactivated
mention that external events that trigger smth should be defined as rule snippets

**Comment by wj-Mcat** [comment]
Can I have a try ？

**Comment by wochinge** [comment]
Hi @wj-Mcat ,

have you already been trying it out?
It's a rather big new feature and affects multiple parts of the documentation. Hence, I'd prefer to to handle it myself. If you want I can also tag you for feedback once I have a draft?

**Comment by wj-Mcat** [comment]
It's seems that I have to be much familiar with all of the Rasa. So, I think I should try the simpler part of rasa.

**Comment by wochinge** [comment]
@wj-Mcat You can see other open issues where we need help by contributors in this board https://github.com/orgs/RasaHQ/projects/23
