### ISSUE TITLE
Unable to install latest version to macos

### ISSUE THREAD

**Issue by boardmain** [RasaHQ/rasa#6187]
**Rasa version**: 
LATEST (1.10)

**Rasa SDK version** (if used & relevant):

**Rasa X version** (if used & relevant):

**Python version**: tried 3.7.4 3.7.7

**Operating system** (windows, osx, ...):
macos mojave

**Issue**:
unable to install rasa 
requirement failed

i tried several python version
in severeal venv but without success

**Error (including full traceback)**:
```
ERROR: Could not find a version that satisfies the requirement tensorflow<2.2,>=2.1 (from rasa) (from versions: 2.2.0rc3, 2.2.0rc4, 2.2.0, 2.3.0rc0, 2.3.0rc1)
ERROR: No matching distribution found for tensorflow<2.2,>=2.1 (from rasa)

```

**Comment by Tim-Abwao** [comment]
I'm experiencing this same issue on Linux Mint 20. 

Installing *rasa* in a new virtual environment:

```
ERROR: Could not find a version that satisfies the requirement tensorflow-addons<0.8.0,>=0.7.1 (from rasa) (from versions: 0.10.0)
ERROR: No matching distribution found for tensorflow-addons<0.8.0,>=0.7.1 (from rasa)
```
```
ERROR: Could not find a version that satisfies the requirement tensorflow<2.2,>=2.1 (from rasa) (from versions: 2.2.0rc1, 2.2.0rc2, 2.2.0rc3, 2.2.0rc4, 2.2.0, 2.3.0rc0, 2.3.0rc1)
ERROR: No matching distribution found for tensorflow<2.2,>=2.1 (from rasa)
```

**Comment by KuzyWoozy** [comment]
Seems to be a python version issue, it worked on my machine (debian buster) using python3.7 but failed with the same error on python3.8
Did you use venv to create the virtual environments? Can you confirm  the environment created was indeed python3.7? (invoke the virtual envionment and run 'python' in the terminal)

**Comment by Tim-Abwao** [comment]
You're probably right at @KuzyWoozy... I was trying to install rasa in Python 3.8.2

**Comment by KuzyWoozy** [comment]
@Tim-Abwao Is it working for you now?

**Comment by sara-tagger** [comment]
Thanks for raising this issue, @wochinge will get back to you about it soon✨

###### Please also check out the [docs](https://rasa.com/docs/) and the [forum](https://forum.rasa.com/) in case your issue was raised there too 🤗

**Comment by wochinge** [comment]
Rasa Open Source 2.0 will be 3.8 compatible, Rasa Open Source 1.10 isn't at the moment. Can you please try installing it with Python 3.7?

**Comment by wochinge** [comment]
Thanks @KuzyWoozy for helping out 🙏

**Comment by boardmain** [comment]
`
python3 --version
Python 3.7.4
python3 -m venv ./venv
source ./venv/bin/activate
pip3 install rasa
`

this way worked
