### ISSUE TITLE
New docs: Autoclass and automethod generation from code

### ISSUE THREAD

**Issue by m-vdb** [RasaHQ/rasa#6194]
⬆️ Relates to RasaHQ/growth#1436

Autoclass and automethod generation from code (http://localhost:3000/docs/api pages). They need to be generated from source, e.g. using https://pydoc-markdown.readthedocs.io/en/latest/

## Implementation proposal

The idea is to use `pydoc-markdown` to convert docstrings to markdown format. First, we need to make it possible to filter module members, because currently it's not supported. So we would have to fork the repo and update [the loader](https://github.com/NiklasRosenstein/pydoc-markdown/blob/develop/pydoc-markdown/src/pydoc_markdown/contrib/loaders/python.py). We also need to update [the markdown renderer here](https://github.com/NiklasRosenstein/pydoc-markdown/blob/develop/pydoc-markdown/src/pydoc_markdown/contrib/renderers/markdown.py#L213) to add an extra space between anchors and titles because it doesn't render properly in docusaurus. After we do this, here is how the setup could look like:

- In the pre-build phase, detect all sources that need to be included in the doc and generate md files using `pydoc-markdown` under the `docs/sources/` folder
- The generated markdown can be imported directly inside a document, using transclusion:
```mdx
---
id: tracker
sidebar_label: Tracker
title: Tracker
---
import TrackerRef from '../test.mdx';

<TrackerRef />
```

## Alternative implementation proposal

Generate the full documentation for the `rasa` module and store it under `docs/reference` or something like that. In the docs, we would mainly link to the reference. That would require two things:
- a revamp of some of the docs pages
- the ability for the [markdown renderer](https://github.com/NiklasRosenstein/pydoc-markdown/blob/develop/pydoc-markdown/src/pydoc_markdown/contrib/renderers/markdown.py) to render markdown in separate pages. It's doesn't seem supported at the moment
- like with the first solution, we also need to update [the markdown renderer here](https://github.com/NiklasRosenstein/pydoc-markdown/blob/develop/pydoc-markdown/src/pydoc_markdown/contrib/renderers/markdown.py#L213) to add an extra space between anchors and titles because it doesn't render properly in docusaurus.

**Comment by m-vdb** [comment]
@tmbo I made two implementation proposals here. I tend to have a preference for the second one because it seems more long-term, but I think it might take more time to do. Can you give me some feedback? Do you have another alternative in mind?

**Comment by m-vdb** [comment]
from @erohmensing 
> I think if we can do it automatically, it would be better to have the entire module autogenerated, we could store in under Python API or something like that. I’d be happy to take the revamp required for those — most of the places where we use this (tracker, events, etc) are actually rasa core and external user-facing sdk classes, so its more confusing the way we have it now IMO


and
> That being said our current docstrings are a mixed bag when it comes to usefulness :yum:

**Comment by lunelson** [comment]
I'd be curious to see what these docstrings look like when included directly in the document. I suspect there might be some style issues with pulling content written in another place in to the main and including it as inline raw markdown—particularly if it contains headings or anything beside simple paragraphs and lists. A couple of ideas:

1. It seems to me the inclusion could probably also be done with a remark plugin... @m-vdb you already created a similar one didn't you?
2. On the surface it sounds like a custom component would be useful here, as it's a bit like including a document within a document, so perhaps these should be styled as their own block and wrapped in an `<article>` or `<aside>`?

**Comment by m-vdb** [comment]
here is how it looks like when you generate the doc for a module: https://gist.github.com/m-vdb/32e4fde11db0d514d162323c6b2c1aaa

We could control the hierarchy of headings when we fork this repo though.

> It seems to me the inclusion could probably also be done with a remark plugin... @m-vdb you already created a similar one didn't you?

Yes it would be possible but I am not sure it would be required. The transclusion feature seems a bit more adapted (also, the remark plugins I used / created up until now are all based on code blocks, which wouldn't be the case here).

> On the surface this sounds like including a document within a document, so perhaps these should be styled as their own block in some way, and wrapped in an `<article>` or `<aside>`?

Yes that's also something to take into consideration.

💡 The more I think about this, the more I feel we shouldn't try to embed docstrings in the docs, but instead generate the whole API ref and link to it (that's what most libraries/frameworks/sdks do, if I'm not mistaken). So I'd go with the **Alternative implementation proposal**

**Comment by lunelson** [comment]
>The more I think about this, the more I feel we shouldn't try to embed docstrings in the docs, but instead generate the whole API ref and link to it

👍 Cool
