### ISSUE TITLE
Custom UI

### ISSUE THREAD

**Issue by developer543** [RasaHQ/rasa#6196]
I have created/trained my Rasa assistant and am working on creating my own custom UI. Depending on the type of response my bot is sending, I want to change the color of my bot’s response. For example, if my bot’s response is an order confirmation, I want my bot’s utterance to be green in my UI, whereas for other responses I would want my bot’s utterance to be red. How would I send this additional data (through the socketio path) to change the color of my bot’s response. Thanks!

**Comment by sara-tagger** [comment]
Thanks for submitting this feature request 🚀 @akelad will get back to you about it soon! ✨

**Comment by akelad** [comment]
Hi @developer543, please ask these kinds of questions in our community [forum](https://forum.rasa.com) and someone will get back to you there
