### ISSUE TITLE
Hi @developer543, please ask these kinds of questions in our community [forum](https://forum.rasa.com) and someone will get back to you there

### ISSUE THREAD

**Issue by developer543** [RasaHQ/rasa#6200]
Hi @developer543, please ask these kinds of questions in our community [forum](https://forum.rasa.com) and someone will get back to you there

_Originally posted by @akelad in https://github.com/RasaHQ/rasa/issues/6196#issuecomment-658041142_

I was told to post in GitHub on the community forums: https://forum.rasa.com/t/customized-ui/31222

**Comment by akelad** [comment]
^ Please avoid creating new issues for that, and simply comment on the original issue. I will get back to you on the forum post
