### ISSUE TITLE
Automatically open a PR against `main` when merging changes in the latest release branch

### ISSUE THREAD

**Issue by m-vdb** [RasaHQ/rasa#6207]
Cf. https://github.com/RasaHQ/rasa-x/issues/2960

**Comment by mprazz** [comment]
I am unsure we want this, as it gets quite noisy around release times :thinking: could we consider a slack bot that alerts us when there are unmerged changes in release branches older than x days, per example?

**Comment by mprazz** [comment]
@katethemate The workflow used in rasa x is here: https://github.com/RasaHQ/rasa-x/blob/main/.github/workflows/automatic-main-merger.yml
please tweak the one on rasax to close older PRs + do the same for rasa

**Comment by katethemate** [comment]
@mprazz It seems like there isn't an automatic-main-merger in rasa OSS? Should I copy paste[ the rasa x workflow](https://github.com/RasaHQ/rasa-x/blob/main/.github/workflows/automatic-main-merger.yml)?

**Comment by mprazz** [comment]
@katethemate yes, please do the same workflow for `rasa` as well :pray:
