### ISSUE TITLE
Refactor `TwoStageFallbackAction` to not revert fallback events

### ISSUE THREAD

**Issue by wochinge** [RasaHQ/rasa#6209]
The [TwoStageFallbackAction](https://github.com/RasaHQ/rasa/blob/6fb55a5d946af07a2733f6d879c78f1ae3b41dd9/rasa/core/actions/two_stage_fallback.py#L112) currently reverts any fallback events as soon as the user successfully rephrased / affirmed. Since the featurization of `forms` changed, this is no longer required. As soon as a form is successfully finished it will unfeaturize all events which were part of the form.

**Proposed Steps**

*   [ ] remove revert steps
*   [ ] adapt tests

**Comment by wochinge** [comment]
@Ghostvv This is not as easy as expected.

1) While the back-and forth during the fallback is unfeaturized due to `applied_events`, the form's happy path is still featurized. Means that we end up with a tracker like this after the user rephrased successfully:

<img width="681" alt="Screenshot 2020-08-10 at 22 58 10" src="https://user-images.githubusercontent.com/7667273/89830752-00cb8200-db5d-11ea-8971-3a6d12b16dae.png">

We'd need to change the intent **before** the form was triggered and also unfeaturize the whole form which is a huge hassle. I'd keep the current implementation. Wdyt?

**Comment by Ghostvv** [comment]
agree, let's put it on hold

**Comment by m-vdb** [comment]
@Ghostvv @wochinge is this still relevant in 2.0 or is it fixed by the RulePolicy?
