### ISSUE TITLE
UserWarning for missing utterance with NLG setup

### ISSUE THREAD

**Issue by andrew-mcmaster** [RasaHQ/rasa#6216]
**Rasa version**:
Multiple version over the last year-ish. Currently 1.10.7

**Rasa SDK version** (if used & relevant):
Not relevant

**Rasa X version** (if used & relevant):
Not relevant

**Python version**:
python 3.7.7

**Operating system** (windows, osx, ...):
Windows and linux

**Issue**:
Posted issue first on [forum ](https://forum.rasa.com/t/userwarning-for-utterance-with-nlg-server-setup/30711)was asked to post here.
If you remove the responses from the domain and just list the utterances in actions and use the NLG server to fetch the appropriate text from another server, the log file contains 3 warnings for each utterance in domain.

**Error (including full traceback)**:
```
Utterance 'utter_greet' is listed as an action in the domain file, but there is no matching utterance template. Please check your domain.
There is no template for the utterance action 'utter_greet'. The action is listed in your domains action list, but there is no template defined with this name. You should add a template with this key.
UserWarning: The action 'utter_greet' is used in the stories, but is not a valid utterance action. Please make sure the action is listed in your domain and there is a template defined with its name.
```

**Command or request that led to error**:
```
rasa data validate
&
rasa train
```

Reproduce
Create new blank rasa project. Remove responses from domain. Add NLG line to endpoints.yml. Run rasa data validate.
(current rasa version didn't create actions from init as a sidenote, adding the utter under action add two more warnings per missing template missing)

**Comment by sara-tagger** [comment]
Thanks for the issue, @tabergma will get back to you about it soon!

###### You may find help in the [docs](https://rasa.com/docs/) and the [forum,](https://forum.rasa.com/) too 🤗

**Comment by tabergma** [comment]
Thanks @andrew-mcmaster for raising the issue. Do you want to work on this issue yourself? Otherwise we will try to fix it as soon as possible.

**Comment by andrew-mcmaster** [comment]
@tabergma I not super skilled with python, I think I'll leave it with the pros haha

**Comment by timidri** [comment]
Is there any update on this issue?
