### ISSUE TITLE
asyncio.coroutine has been deprecated since Python 3.8 and will be removed in future.

### ISSUE THREAD

**Issue by tirkarthi** [RasaHQ/rasa#6223]
**Rasa version**: master branch
**Python version**: 3.8
**Issue**: asyncio.coroutine has been deprecated since Python 3.8 and will be removed in future.

```
tests/core/test_interactive.py
404:        interactive, "_get_training_trackers", asyncio.coroutine(get_training_trackers)
410:    monkeypatch.setattr(interactive, "_plot_trackers", asyncio.coroutine(plot_trackers))
```

**Comment by sara-tagger** [comment]
Thanks for the issue, @TyDunn will get back to you about it soon!

###### You may find help in the [docs](https://rasa.com/docs/) and the [forum,](https://forum.rasa.com/) too 🤗

**Comment by ricwo** [comment]
This is not an issue for now - the decorator is scheduled for removal in Python 3.10: https://github.com/python/cpython/blob/master/Doc/library/asyncio-task.rst#generator-based-coroutines
