### ISSUE TITLE
save RASA model in bucket s3 AWS

### ISSUE THREAD

**Issue by kchahid** [RasaHQ/rasa#6239]
Hi all, I have try different approach to SAVE automatically rasa model in aws s3 bucket but any of solution work for me
if any one can help for this case and thanks
P.s : i have read the doc but nothing about to save in s3 only about [rasa run remote-storage ...] https://rasa.com/docs/rasa/user-guide/cloud-storage/

**Comment by Dustyposa** [comment]
Have any code we can see？

**Comment by sara-tagger** [comment]
Thanks for raising this issue, @tttthomasssss will get back to you about it soon✨

###### Please also check out the [docs](https://rasa.com/docs/) and the [forum](https://forum.rasa.com/) in case your issue was raised there too 🤗

**Comment by kchahid** [comment]
so my probleme is : i wanna save model rasa automatically in s3 after the training like : rasa train --out [BUCKET S3] (i dont do that is only to explain)

i have set credentials in ~/.aws/ and in the config.yml (rasa config) […] bucket_name: “XXX” aws_region: “eu-west-1” storage: “aws” […] but i m not enbale to save model directly in s3 :/ 

@Dustyposa no cuz it s only a config file so i don t know how can i solve this probleme if anyone can help :/
And for the doc nothing about this

**Comment by Dustyposa** [comment]
I see the source code. That's look like don't support save model on remote storage. But you can load or use remote storage model to run server.
@kchahid 

And this feature sounds good.

**Comment by kchahid** [comment]
i have set a model in s3 and run it .... when i use the endpoint model/train the model save in the container and not in s3 !!
