### ISSUE TITLE
"Bad git executable" error message when starting Rasa x in local mode

### ISSUE THREAD

**Issue by InnoOmnia** [RasaHQ/rasa#6241]
**Rasa version**: 1.10.8

**Rasa SDK version** (if used & relevant):

**Rasa X version** (if used & relevant): 0.31.0

**Python version**: 3.7.7

**Operating system** (windows, osx, ...): Ubuntu 18.04

**Issue**:
Starting rasa x in local mode gives error message

**Error (including full traceback)**:
```
(rasabot+x) linttu@linttu-VirtualBox:~/rasa/rasabot+x$ rasa x
Traceback (most recent call last):
  File "/home/linttu/miniconda3/envs/rasabot+x/lib/python3.7/site-packages/git/__init__.py", line 83, in <module>
    refresh()
  File "/home/linttu/miniconda3/envs/rasabot+x/lib/python3.7/site-packages/git/__init__.py", line 73, in refresh
    if not Git.refresh(path=path):
  File "/home/linttu/miniconda3/envs/rasabot+x/lib/python3.7/site-packages/git/cmd.py", line 278, in refresh
    raise ImportError(err)
ImportError: Bad git executable.
The git executable must be specified in one of the following ways:
    - be included in your $PATH
    - be set via $GIT_PYTHON_GIT_EXECUTABLE
    - explicitly set via git.refresh()

All git commands will error until this is rectified.

This initial warning can be silenced or aggravated in the future by setting the
$GIT_PYTHON_REFRESH environment variable. Use one of the following values:
    - quiet|q|silence|s|none|n|0: for no warning or exception
    - warn|w|warning|1: for a printed warning
    - error|e|raise|r|2: for a raised exception

Example:
    export GIT_PYTHON_REFRESH=quiet


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/linttu/miniconda3/envs/rasabot+x/bin/rasa", line 8, in <module>
    sys.exit(main())
  File "/home/linttu/miniconda3/envs/rasabot+x/lib/python3.7/site-packages/rasa/__main__.py", line 92, in main
    cmdline_arguments.func(cmdline_arguments)
  File "/home/linttu/miniconda3/envs/rasabot+x/lib/python3.7/site-packages/rasa/cli/x.py", line 326, in rasa_x
    run_locally(args)
  File "/home/linttu/miniconda3/envs/rasabot+x/lib/python3.7/site-packages/rasa/cli/x.py", line 414, in run_locally
    from rasax.community import local  # pytype: disable=import-error
  File "/home/linttu/miniconda3/envs/rasabot+x/lib/python3.7/site-packages/rasax/community/local.py", line 25, in <module>
    import rasax.community.server as rasa_x_server
  File "/home/linttu/miniconda3/envs/rasabot+x/lib/python3.7/site-packages/rasax/community/server.py", line 4, in <module>
    from rasax.community.services.integrated_version_control.git_service import GitService
  File "/home/linttu/miniconda3/envs/rasabot+x/lib/python3.7/site-packages/rasax/community/services/integrated_version_control/git_service.py", line 10, in <module>
    from git import Repo, Reference, PushInfo, RemoteReference, Actor
  File "/home/linttu/miniconda3/envs/rasabot+x/lib/python3.7/site-packages/git/__init__.py", line 85, in <module>
    raise ImportError('Failed to initialize: {0}'.format(exc)) from exc
ImportError: Failed to initialize: Bad git executable.
The git executable must be specified in one of the following ways:
    - be included in your $PATH
    - be set via $GIT_PYTHON_GIT_EXECUTABLE
    - explicitly set via git.refresh()

All git commands will error until this is rectified.

This initial warning can be silenced or aggravated in the future by setting the
$GIT_PYTHON_REFRESH environment variable. Use one of the following values:
    - quiet|q|silence|s|none|n|0: for no warning or exception
    - warn|w|warning|1: for a printed warning
    - error|e|raise|r|2: for a raised exception

Example:
    export GIT_PYTHON_REFRESH=quiet
```

**Command or request that led to error**:
```
rasa x

```

**Content of configuration file (config.yml)** (if relevant):
```yml

```

**Content of domain file (domain.yml)** (if relevant):
```yml

```

**Comment by sara-tagger** [comment]
Thanks for the issue, @degiz will get back to you about it soon!

###### You may find help in the [docs](https://rasa.com/docs/) and the [forum,](https://forum.rasa.com/) too 🤗

**Comment by federicotdn** [comment]
@InnoOmnia what is the output of running `which git` in your terminal? How about `apt show git`?

**Comment by NR2506** [comment]
@federicotdn it's showing this details after pass this comment ### apt show git

(Rasa_ChatBot) naveen@naveen-Inspiron-5558:~/PycharmProjects/Rasa_ChatBot$ apt show git
Package: git
Version: 1:2.17.1-1ubuntu0.7
Priority: optional
Section: vcs
Origin: Ubuntu
Maintainer: Ubuntu Developers <ubuntu-devel-discuss@lists.ubuntu.com>
Original-Maintainer: Gerrit Pape <pape@smarden.org>
Bugs: https://bugs.launchpad.net/ubuntu/+filebug
Installed-Size: 32.3 MB
Provides: git-completion, git-core
Depends: libc6 (>= 2.16), libcurl3-gnutls (>= 7.16.2), libexpat1 (>= 2.0.1), libpcre3, zlib1g (>= 1:1.2.0), perl, liberror-perl, git-man (>> 1:2.17.1), git-man (<< 1:2.17.1-.)
Recommends: patch, less, ssh-client
Suggests: gettext-base, git-daemon-run | git-daemon-sysvinit, git-doc, git-el, git-email, git-gui, gitk, gitweb, git-cvs, git-mediawiki, git-svn
Breaks: bash-completion (<< 1:1.90-1), cogito (<= 0.18.2+), git-buildpackage (<< 0.6.5), git-core (<< 1:1.7.0.4-1.), gitosis (<< 0.2+20090917-7), gitpkg (<< 0.15), gitweb (<< 1:1.7.4~rc1), guilt (<< 0.33), openssh-client (<< 1:6.8), stgit (<< 0.15), stgit-contrib (<< 0.15)
Replaces: git-core (<< 1:1.7.0.4-1.), gitweb (<< 1:1.7.4~rc1)
Homepage: https://git-scm.com/
Task: cloud-image, server
Supported: 5y
Download-Size: 3,915 kB
APT-Sources: http://in.archive.ubuntu.com/ubuntu bionic-updates/main amd64 Packages
Description: fast, scalable, distributed revision control system
 Git is popular version control system designed to handle very large
 projects with speed and efficiency; it is used for many high profile
 open source projects, most notably the Linux kernel.
 .
 Git falls in the category of distributed source code management tools.
 Every Git working directory is a full-fledged repository with full
 revision tracking capabilities, not dependent on network access or a
 central server.
 .
 This package provides the git main components with minimal dependencies.
 Additional functionality, e.g. a graphical user interface and revision
 tree visualizer, tools for interoperating with other VCS's, or a web
 interface, is provided as separate git* packages.

N: There is 1 additional record. Please use the '-a' switch to see it

**Comment by NR2506** [comment]
@federicotdn what can I do for next....?

**Comment by InnoOmnia** [comment]
Here is my git output

base) linttu@linttu-VirtualBox:~$ which git
/usr/bin/git
(base) linttu@linttu-VirtualBox:~$ apt show git
Package: git
Version: 1:2.17.1-1ubuntu0.7
Priority: optional
Section: vcs
Origin: Ubuntu
Maintainer: Ubuntu Developers <ubuntu-devel-discuss@lists.ubuntu.com>
Original-Maintainer: Gerrit Pape <pape@smarden.org>
Bugs: https://bugs.launchpad.net/ubuntu/+filebug
Installed-Size: 32,3 MB
Provides: git-completion, git-core
Depends: libc6 (>= 2.16), libcurl3-gnutls (>= 7.16.2), libexpat1 (>= 2.0.1), libpcre3, zlib1g (>= 1:1.2.0), perl, liberror-perl, git-man (>> 1:2.17.1), git-man (<< 1:2.17.1-.)
Recommends: patch, less, ssh-client
Suggests: gettext-base, git-daemon-run | git-daemon-sysvinit, git-doc, git-el, git-email, git-gui, gitk, gitweb, git-cvs, git-mediawiki, git-svn
Breaks: bash-completion (<< 1:1.90-1), cogito (<= 0.18.2+), git-buildpackage (<< 0.6.5), git-core (<< 1:1.7.0.4-1.), gitosis (<< 0.2+20090917-7), gitpkg (<< 0.15), gitweb (<< 1:1.7.4~rc1), guilt (<< 0.33), openssh-client (<< 1:6.8), stgit (<< 0.15), stgit-contrib (<< 0.15)
Replaces: git-core (<< 1:1.7.0.4-1.), gitweb (<< 1:1.7.4~rc1)
Homepage: https://git-scm.com/
Task: cloud-image, server
Supported: 5y
Download-Size: 3 915 kB
APT-Manual-Installed: yes
APT-Sources: http://fi.archive.ubuntu.com/ubuntu bionic-updates/main amd64 Packages

**Comment by InnoOmnia** [comment]
This is my git output

(base) linttu@linttu-VirtualBox:~$ which git
/usr/bin/git
(base) linttu@linttu-VirtualBox:~$ apt show git
Package: git
Version: 1:2.17.1-1ubuntu0.7
Priority: optional
Section: vcs
Origin: Ubuntu
Maintainer: Ubuntu Developers <ubuntu-devel-discuss@lists.ubuntu.com>
Original-Maintainer: Gerrit Pape <pape@smarden.org>
Bugs: https://bugs.launchpad.net/ubuntu/+filebug
Installed-Size: 32,3 MB
Provides: git-completion, git-core
Depends: libc6 (>= 2.16), libcurl3-gnutls (>= 7.16.2), libexpat1 (>= 2.0.1), libpcre3, zlib1g (>= 1:1.2.0), perl, liberror-perl, git-man (>> 1:2.17.1), git-man (<< 1:2.17.1-.)
Recommends: patch, less, ssh-client
Suggests: gettext-base, git-daemon-run | git-daemon-sysvinit, git-doc, git-el, git-email, git-gui, gitk, gitweb, git-cvs, git-mediawiki, git-svn
Breaks: bash-completion (<< 1:1.90-1), cogito (<= 0.18.2+), git-buildpackage (<< 0.6.5), git-core (<< 1:1.7.0.4-1.), gitosis (<< 0.2+20090917-7), gitpkg (<< 0.15), gitweb (<< 1:1.7.4~rc1), guilt (<< 0.33), openssh-client (<< 1:6.8), stgit (<< 0.15), stgit-contrib (<< 0.15)
Replaces: git-core (<< 1:1.7.0.4-1.), gitweb (<< 1:1.7.4~rc1)
Homepage: https://git-scm.com/
Task: cloud-image, server
Supported: 5y
Download-Size: 3 915 kB
APT-Manual-Installed: yes
APT-Sources: http://fi.archive.ubuntu.com/ubuntu bionic-updates/main amd64 Packages
