### ISSUE TITLE
Caps in the rasa x project directory generate an uncaught error

### ISSUE THREAD

**Issue by pofenstein** [RasaHQ/rasa#6261]
**Rasa version**: 1.10.8

**Rasa X version**: 0.31.0

**Python version**: 3.7.3

**Operating system**: Debian 10

**Issue**:
With the docker-compose manual install for rasa x, when the name of the project folder contains caps (for instance /etc/rasaSJ/), everything appears to be working fine (no logs) but the rasa x ui is inaccessible, as if the port was closed/nothing listened to it.
The containers were automatically named in small letters (for instance rasasj_rasa-x_1), that's what made me change the folder name.

**Error (including full traceback)**:
The only error is ERR_CONNECTION_REFUSED in navigator.
Chrome : 
This site can’t be reached
website refused to connect.

**Command or request that led to error**:
```
sudo docker-compose up -d
```

**Comment by sara-tagger** [comment]
Thanks for raising this issue, @b-quachtran will get back to you about it soon✨

###### Please also check out the [docs](https://rasa.com/docs/) and the [forum](https://forum.rasa.com/) in case your issue was raised there too 🤗

**Comment by b-quachtran** [comment]
Hi! Thanks for reporting this. When you rename the folder to all lower case, is the UI accessible as normal?

**Comment by pofenstein** [comment]
Yes
