### ISSUE TITLE
Rasa is getting trained even if we have error in nlu.md file

### ISSUE THREAD

**Issue by dhapolapankaj** [RasaHQ/rasa#6264]
**Rasa version**:Rasa 1.10.8

**Rasa SDK version** (if used & relevant):

**Rasa X version** (if used & relevant):

**Python version**: 3.6.10 :: Anaconda, Inc.

**Operating system** (windows, osx, ...): Win10

**Issue**: rasa train command starts training even after we have some incorrect format in nlu.md file

**Error (including full traceback)**:
```

```

**Command or request that led to error**:
```
rasa train
```

**Content of configuration file (config.yml)** (if relevant):
```yml

```

**Content of domain file (domain.yml)** (if relevant):
```yml

```

There is no error, but there is a scenario where I wanted to identify an entity "name" from intent statement --> my name is Pankaj
I wasn't able to figure it out because it was a very simple task. 

It took me a huge time to identify the issue due to the huge size of file

```
## intent:user_provide_user_name
- my name is [Pankaj]{"entity":"user_name","value":"Pankaj")
```
Notice the right parenthesis at the end of the line, there should have been closing curly braces.

while performing rasa train, the nlu.md file should undergo a format validation. 

This way we could have save a lot of time.

**Comment by sara-tagger** [comment]
Thanks for raising this issue, @chkoss will get back to you about it soon✨

###### Please also check out the [docs](https://rasa.com/docs/) and the [forum](https://forum.rasa.com/) in case your issue was raised there too 🤗

**Comment by chkoss** [comment]
Hi, thanks for pointing this out.
There is already some format validation: if an entity dictionary is detected, it will be checked if it is valid json. However this doesn't help with your case where there is no entity dictionary detected in the first place.

We'll investigate potential solutions and probably introduce a warning that makes it easier to locate such a format error.

**Comment by wochinge** [comment]
Markdown is deprecated and will be removed in Rasa Open Source 3.0. We'll only handle bug fixes until then for Markdown.
