### ISSUE TITLE
UI of Rasa HTTP API docs is not user-friendly

### ISSUE THREAD

**Issue by howl-anderson** [RasaHQ/rasa#6265]
**Issue**:
This is the current UI of https://rasa.com/docs/rasa/api/http-api/#operation/testModelStories is

![image](https://user-images.githubusercontent.com/1263428/88256160-12073880-cced-11ea-9380-a0db39e3d307.png)

the content is:

```json
{
"actions": [
{}
],
"is_end_to_end_evaluation": true,
"precision": 1,
"f1": 0.9333333333333333,
"accuracy": 0.9,
"in_training_data_fraction": 0.8571428571428571,
"report": "# classification report\n                       precision    recall  f1-score   support\n        action_listen       1.00      1.00      1.00         3\n                greet       1.00      1.00      1.00         1\n               inform       1.00      1.00      1.00         2\n utter_ask_howcanhelp       1.00      1.00      1.00         1\n   utter_ask_location       1.00      1.00      1.00         1\n  utter_ask_numpeople       0.00      0.00      0.00         0\n          utter_on_it       1.00      0.50      0.67         2\n\n          avg / total       1.00      0.90      0.93        10"
}
```

It is evident that the UI is not user-friendly, people can not see the content by the bare eyes.

**Comment by sara-tagger** [comment]
Thanks for the issue, @tttthomasssss will get back to you about it soon!

###### You may find help in the [docs](https://rasa.com/docs/) and the [forum,](https://forum.rasa.com/) too 🤗
