### ISSUE TITLE
allow only RulePolicy retraining

### ISSUE THREAD

**Issue by Ghostvv** [RasaHQ/rasa#6268]
training `TEDPolicy` might take significant time, but users might want to only change rules, therefore add a check if anything changed in story training data and if not only retrain `RulePolicy` if rules have changed

Also, `RulePolicy` should be trained first.

**Comment by JEM-Mosig** [comment]
Might be relevant here: I'm creating a PR that lets us load stories only (right now you cannot load stories without rules). https://github.com/RasaHQ/rasa/issues/6973#issuecomment-706090125

**Comment by ancalita** [comment]
This is now resolved with the graph architecture revamp in 3.x.
