### ISSUE TITLE
Use context in NLU

### ISSUE THREAD

**Issue by ValeKnappich** [RasaHQ/rasa#6277]
I think it would be great if you could use the conversation context in the NLU model, eg in DIET. I believe that context is one of the most important aspects of language understanding in human-human conversation and is yet not considered in NLU (correct me if I'm wrong). 

In terms of rasa I could imagine to calculate a probability distribution over all intents and use that to influence the intent ranking by some degree. The task would be somewhat similar to TED, just predicting the most likely intents, instead of actions. I think it would be benefitial especially when the confidence is low to push it above threshold and do implicit affirmation or at least give suggestions that make sense in the context as in the TwoStageFallback.

This is more of a general topic, rather than a concrete feature request, but it would be awesome to hear some thoughts about it from people who are more sophisticated with rasa and NLP in general.

**Comment by sara-tagger** [comment]
Thanks for submitting this feature request 🚀 @tabergma will get back to you about it soon! ✨

**Comment by tabergma** [comment]
Hi @ValeKnappich, thanks for the issue. We are actually working towards what you are describing with our end-to-end learning. It will be part of Rasa 2.0 and you can read some more thoughts around it in the announcement [here](https://blog.rasa.com/whats-ahead-in-rasa-open-source-2-0/). The idea is basically that we directly go from the conversation history to the action prediction. Does that go into the direction you mentioned?

**Comment by ValeKnappich** [comment]
Hi @tabergma, thanks for the answer. That actually is more than I had in mind, sounds great! I read Alan Nichols article about that we should get rid of intents and was wondering how rasa would approach that. Very interesting.
