### ISSUE TITLE
Issue with Diet Classifier

### ISSUE THREAD

**Issue by Asma-droid** [RasaHQ/rasa#6282]
Hi all,

I would like to use Diet Classifier with rasa version 2.0.0a1 (docker container). If i put 100 epochs, there is no problem generated. If i put epochs equal to 200 or 200. I obtain this message.

?it/s]/opt/venv/lib/python3.7/site-packages/rasa/utils/tensorflow/model_data.py:389: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray

rasa             |   final_data[k].append(np.concatenate(np.array(v)))

**Comment by sara-tagger** [comment]
Thanks for raising this issue, @chkoss will get back to you about it soon✨

###### Please also check out the [docs](https://rasa.com/docs/) and the [forum](https://forum.rasa.com/) in case your issue was raised there too 🤗

**Comment by chkoss** [comment]
@tabergma Can you have a look what causes this warning, please?

I could reproduce the issue independent of the number of epochs. Simply running `rasa init --no-prompt` gave me the warning mentioned above plus the same warning at a different place:
```
/Users/christina/rasa/rasa/nlu/classifiers/diet_classifier.py:683: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray
  X_dense_sequence = np.array(X_dense_sequence)
```
