### ISSUE TITLE
>rasa run actions .........sanic.exceptions.NotFound: Requested URL / not found

### ISSUE THREAD

**Issue by sriram-r-b** [RasaHQ/rasa#6283]
**Rasa version**:  1.10.8

**Rasa SDK version** (if used & relevant):

**Rasa X version** (if used & relevant):

**Python version**: 3.7.7

**Operating system** (windows, osx, ...): windows 10  (2004)

**Issue**:
rasa run action raises an exception

**Error (including full traceback)**:
```

2020-07-28 06:59:59 INFO     rasa_sdk.endpoint  - Starting action endpoint server...
2020-07-28 06:59:59 INFO     rasa_sdk.endpoint  - Action endpoint is up and running on http://localhost:5055
Exception occurred while handling uri: 'http://localhost:5055/'
Traceback (most recent call last):
  File "d:\anaconda\mini\envs\myclone\lib\site-packages\sanic\app.py", line 940, in handle_request
    handler, args, kwargs, uri, name = self.router.get(request)
  File "d:\anaconda\mini\envs\myclone\lib\site-packages\sanic\router.py", line 411, in get
    return self._get(request.path, request.method, "")
  File "d:\anaconda\mini\envs\myclone\lib\site-packages\sanic\router.py", line 475, in _get
    raise NotFound("Requested URL {} not found".format(url))
sanic.exceptions.NotFound: Requested URL / not found
```

**Command or request that led to error**:
```
rasa run actions
```

**Content of configuration file (config.yml)** (if relevant):
```yml

```

**Content of domain file (domain.yml)** (if relevant):
```yml

```

**Comment by Dustyposa** [comment]
Have no path named "/", what do you want to do?
To validate that action server is runnning?

**Comment by sara-tagger** [comment]
Thanks for raising this issue, @rctatman will get back to you about it soon✨

###### Please also check out the [docs](https://rasa.com/docs/) and the [forum](https://forum.rasa.com/) in case your issue was raised there too 🤗

**Comment by erohmensing** [comment]
The correct path is `/webhook`. As shown [here](https://rasa.com/docs/rasa/core/actions/#custom-actions), the endpoints.yml url should look like: 

```
action_endpoint:
  url: "http://localhost:5055/webhook"
```

**Comment by hurun** [comment]
i met the same error.could anyone help?
