### ISSUE TITLE
Potential bugs relate to the end-to-end story generated from Rasa X

### ISSUE THREAD

**Issue by howl-anderson** [RasaHQ/rasa#6287]
**Rasa version**: 1.10.7

**Rasa X version** (if used & relevant): 0.31.0

**Issue**:

I am doing some localization experiments on "Knowledge Base Actions", I find some (potential) bugs.

### First issue (Maybe this is a bug or feature on purpose)
The end-to-end story generated from Rasa X using synonym instead of the original value.
What I input to the bot: "列出一些歌曲", in English it means: "list some songs for me", I have set up the synonym mapping from "歌曲" to "song" via:
```markdown
## synonym:song
- 歌曲
```
but the end-to-end story is:
```markdown
列出一些[song](object_type)
```
Maybe it's not obvious to English developer, but for someone who using other languages, the sentence becomes a little wired, the story is not very end-to-end. But after thinking it over, I think this maybe is a feature designed on purpose, since it simplified the NLU processing for testing. So, I just report it here.

### Second issue (it's a bug)
What I input to the bot: "第二个属于什么专辑", in English it means: "what's the album for the second song". "第二个" means "the second one", "专辑" means "album" in English. I have set up the synonym mapping from "第二个" to 2, from "专辑” to "album".

But the end-to-end story I got is:
```markdown
[2](mention)属于什么专辑[album](attribute)
```
the correct version should be:
```markdown
[2](mention)属于什么[album](attribute)
```

**Comment by sara-tagger** [comment]
Thanks for the issue, @chkoss will get back to you about it soon!

###### You may find help in the [docs](https://rasa.com/docs/) and the [forum,](https://forum.rasa.com/) too 🤗

**Comment by wochinge** [comment]
@Saladdin can you please have a look?

**Comment by Saladdin** [comment]
The issue should not happen anymore in Rasa X 0.33
