### ISSUE TITLE
command: `rasa init` still used old data format and policy in Rasa v2.0.0a1

### ISSUE THREAD

**Issue by howl-anderson** [RasaHQ/rasa#6303]
**Rasa version**: 2.0.0a1

**Issue**:

command: `rasa init` still used old data format and policy in Rasa v2.0.0a1

update the content created by rasa init from 1.x to 2.x will help lots of people who want to know what's new in 2.0

**Comment by sara-tagger** [comment]
Thanks for the issue, @b-quachtran will get back to you about it soon!

###### You may find help in the [docs](https://rasa.com/docs/) and the [forum,](https://forum.rasa.com/) too 🤗

**Comment by akelad** [comment]
@TyDunn is prod gonna handle this? CSE has been taking care of updating demo bots, and we overlooked this one I guess so we can tackle it (should be a v quick job)

@howl-anderson thanks a lot for pointing that out!

**Comment by TyDunn** [comment]
@akelad Not in the current sprint, so I think it would be best if y'all take it on
