### ISSUE TITLE
SSH url validation issue

### ISSUE THREAD

**Issue by Plurno** [RasaHQ/rasa#6304]
**Rasa version**: 1.10.0

**Rasa SDK version** (if used & relevant):

**Rasa X version** (if used & relevant): the issue happens in versions > 0.29.0

**Python version**: 3.7.7

**Operating system** (windows, osx, ...): Linux (dockerized rasa-x)

**Issue**:
When I type in my valid SSH url for my git server that is hosted on gitolite, I get a message saying 'Please provide valid values for the highlighted fields.'

It is referring to the SSH url field, which for my git server is formatted like git@xxx-xxx:xxx-xxx where the 'xxx’s are all just strings of a-z characters.  This SSH url works as intended for versions of rasa-x < 0.30.0

**Error (including full traceback)**:
It's not actually throwing an error.  The user interface just doesn't allow me to click 'verify connection' and I can't figure out how to trace the function that isn't verifying my url.

**Command or request that led to error**:
This is a UI issue that happens on the front end.  The error happens after I type my url into the 'SSH URL for repository' field.

**Content of configuration file (config.yml)** (if relevant):  not relevant
```yml

```

**Content of domain file (domain.yml)** (if relevant): not relevant
```yml

```

**Comment by sara-tagger** [comment]
Thanks for raising this issue, @degiz will get back to you about it soon✨

###### Please also check out the [docs](https://rasa.com/docs/) and the [forum](https://forum.rasa.com/) in case your issue was raised there too 🤗
