### ISSUE TITLE
Load Huggingface Transformers model using TFAutoModel

### ISSUE THREAD

**Issue by patricebechard** [RasaHQ/rasa#6307]
**Description of Problem**: I want to use models provided by the HuggingFace transformers library that are not available when using the HFTransformersNLP Component.

**Overview of the Solution**: Right now, models are loaded using a dictionary of architectures in `rasa/nlu/utils/hugging_face/registry.py`. Using the `AutoModel` and `AutoTokenizer` features from the `transformers` library, we can get rid of these limitations, as well as not having to define a `model_name` in the config file. We can only use the `model_weights` info to select the proper model and weights of the wanted tokenizers and featurizers.

**Examples** (if relevant): Docs for how to use the "auto" features is available [here](https://huggingface.co/transformers/model_doc/auto.html)

**Blockers** (if relevant):

**Definition of Done**:

*   [ ] Changes are made to files in `rasa/rasa/nlu/utils/hugging_face/`
*   [ ] Tests are added
*   [ ] Feature described the docs
*   [ ] Feature mentioned in the changelog

**Comment by sara-tagger** [comment]
Thanks for submitting this feature request 🚀 @JustinaPetr will get back to you about it soon! ✨

**Comment by ftarlaci** [comment]
Hi, 

Is there any update on this enhancement? I would also like to use some of HF models that are currently not available in the HFTransformersNLP Component. Thank you!

**Comment by dakshvar22** [comment]
The reason for not being able to use `AutoModel` and `AutoTokenizer` is because of a few implementation details on how `HFTransformersNLP` is interacting with the rest of the pipeline in Rasa Open Source. I would be curious to know what kind of models are you folks trying to use which are currently not supported.

**Comment by patricebechard** [comment]
Hi @dakshvar22,

We were interested in looking into french models (FlauBERT, CamemBERT) for our project. Pretrained weights for these models are not available through the normal `BertModel` provided by HuggingFace, which was the main blocker on our side. We did some experimentation with the multilingual models, but they tend not to perform really well compared to french-only models. Instead of enabling only these specific models within `HFTransformersNLP`, we figured it would be best to have a more general way of dealing with models from the `transformers` library.

**Comment by dakshvar22** [comment]
Thanks for the info @patricebechard . Are you looking at them for intent classification and entity recognition or some other tasks?
We recently changed the default model weights that `HFTransformersNLP` uses. We now use a [language agnostic model](https://tfhub.dev/google/LaBSE/1) which gives much better sentence representations. This change will be part of the upcoming 2.1 release. I'll encourage you to try that as well.

**Comment by Ghostvv** [comment]
@dakshvar22 if we cannot use auto model, shall we close the issue?

**Comment by dakshvar22** [comment]
The plan is to review this once we update the [transformers dependency](https://github.com/RasaHQ/research/issues/116). Once we are sure that it is not possible to use auto model with the latest dependencies as well, we should close this issue.

**Comment by Ghostvv** [comment]
shall we move it to blocked then?

**Comment by mleimeister** [comment]
@TyDunn Just to raise it to your awareness, I've started a side project to explore this. The current state is here: https://github.com/RasaHQ/rasa/pull/10624 

If I get to a point where it looks viable, I can check with Enable how this would play together with the scheduled TF/transformers upgrade.
