### ISSUE TITLE
Roles of several entities of the same sort in an utterance

### ISSUE THREAD

**Issue by robin-persson** [RasaHQ/rasa#632]
Hi!

Thanks for a great product, much appreciated and highly useful to me!

I'm wondering if it's possible / you have any plans to / you've been thinking of how to distinguish between several entities of the same sort in an utterance. This would be especially helpful with pre-trained entities such as numbers, dates, locations, etc.

For instance the roles 'to' and 'from' in 'i want to go from berlin to tokyo'.

I stumbled upon some [old(?) training data for wit](https://github.com/RasaHQ/rasa_nlu/blob/master/data/examples/wit/demo-flights.json) in your repository, that seems to be doing what I'm after, but I haven't been able to figure out if or how it works.

Thanks!
Robin

**Comment by amn41** [comment]
Hi Robin,

One way to do this is to use a [spacy dependency parse](https://demos.explosion.ai/displacy/?text=i%20want%20to%20go%20from%20berlin%20to%20tokyo&model=en&cpu=1&cph=1) 

for example, in this case you can pick the entity words and iterate over the parents until you find "from" or "to". This would work for both "from Berlin to Tokyo" and "to Tokyo from Beriln".

**Comment by robin-persson** [comment]
Thanks for your swift response!

If possible, I'd prefer to avoid getting my hands too dirty with a parser of a specific component. My ideal situation would be to annotate the training data, much like the data I stumbled upon.

Because of this, an idea I had myself was to train custom entities on their role. Then, when interpreting and there's an overlap with a builtin entity (be it a number, location or other) of the expected type, I've got the full entity in its role. Something like this:

```
{
  "rasa_nlu_data": {
    "common_examples": [
      {
        "entities": [
          {
            "start": 17, 
            "end": 23, 
            "value": "berlin", 
            "entity": "role:from"
          },
          {
            "start": 27, 
            "end": 32, 
            "value": "tokyo", 
            "entity": "role:to"
          },
        ], 
        "intent": "book_trip", 
        "text": "book a trip from berlin to tokyo"
      }
    ]
  }
}
```

Does this sound reasonable to you?

**Comment by wrathagom** [comment]
@robin-persson this is our approach. Or at least something very similar.

Have you had a chance to try it?

**Comment by robin-persson** [comment]
Hi @wrathagom no unfortunately no attempt yet. Not my top priority so may take a while and I'm still in the discussion phase in my own mind.

If I'd do with the spacy dependency parser, how do I hook it up with RASA? Would that be a new component in the processing pipeline?

**Comment by tmbo** [comment]
@robin-persson yes indeed. I think `spacy_entity_extractor.py` is a good starting point. It shows you how to access the spacy document within a component.
