### ISSUE TITLE
Suggest Edits no longer works for docs

### ISSUE THREAD

**Issue by N-Olbert** [RasaHQ/rasa#6324]
F. E. https://rasa.com/docs/rasa/core/retrieval-actions/ 
-> Click on SUGGEST EDITS
-> You will be redirected to https://github.com/RasaHQ/rasa/edit/master/docs/core/retrieval-actions.rst which doesn't exist anymore.

Probably related to the new doc system @m-vdb

**Comment by sara-tagger** [comment]
Thanks for raising this issue, @tttthomasssss will get back to you about it soon✨

###### Please also check out the [docs](https://rasa.com/docs/) and the [forum](https://forum.rasa.com/) in case your issue was raised there too 🤗

**Comment by m-vdb** [comment]
hello @N-Olbert thanks for reporting this. The new documentation system is not released at the moment, so you're still seeing the old documentation at https://rasa.com/docs/rasa/core/retrieval-actions/ . We do not have an easy way to support "suggest edits" in the old docs at the moment, so we have to keep it as it is. When the new docs system is fully in use, you'll be able to suggest edits again.

Sorry for the inconvenience. In the meantime, you can still suggest edits to documents [in this folder on master](https://github.com/RasaHQ/rasa/tree/master/docs/docs).
