### ISSUE TITLE
New docs: configure Algolia DocSearch

### ISSUE THREAD

**Issue by lunelson** [RasaHQ/rasa#6330]
Algolia DocSearch support is included implicitly in the package `@docusaurus/preset-classic`, but not active. It requires the `algolia` options object to be present in `docusaurus.config.js` as shown below.

This seems to be done either by submitting a PR against Algolia's public list of DocSearch indexes, or by submitting this form https://docsearch.algolia.com/apply/

Reference: [Connecting Algolia](https://v2.docusaurus.io/docs/search/#connecting-algolia).

```js
module.exports = {
  themeConfig: {
    algolia: {
      apiKey: 'YOUR_API_KEY',
      indexName: 'YOUR_INDEX_NAME',
      searchParameters: {}, // Optional (if provided by Algolia)
    },
  },
  themes: [
    ['@docusaurus/theme-search-algolia', {}],
  ],
};
```

**Comment by sara-tagger** [comment]
Thanks for the issue, @TyDunn will get back to you about it soon!

###### You may find help in the [docs](https://rasa.com/docs/) and the [forum,](https://forum.rasa.com/) too 🤗

**Comment by sara-tagger** [comment]
Thanks for raising this issue, @akelad will get back to you about it soon✨

###### Please also check out the [docs](https://rasa.com/docs/) and the [forum](https://forum.rasa.com/) in case your issue was raised there too 🤗

**Comment by lunelson** [comment]
@m-vdb getting this going for launch is a bit tricky, since apparently we have to apply for this at Algolia, and the service works on the basis of them crawling the existing site: however as long as we're still deploying under the `/next/` sub-directory there's no point in indexing it...

**Comment by m-vdb** [comment]
ok so this would have to be something we do post-launch. I think it's OK as it wasn't identified as release blocking.

Did we already decide to apply for DocSearch? I remember there were 2 possible solutions with Algolia.

**Comment by lunelson** [comment]
>Did we already decide to apply for DocSearch? I remember there were 2 possible solutions with Algolia

I'm still trying to figure this out with Algolia support. There's an existing (free) account, but the permissions on it are so limited that I can't do or see anything about our existing index (which I'm pretty sure is the one for rasa-x)

**Comment by akelad** [comment]
@lunelson out of curiosity who are you in touch with? just asking because we have a specific contact point with them - Sylvain Pace

**Comment by lunelson** [comment]
@akelad It's Sylvain, yes. He finally clued me in today to what was missing: the search is not configured through our account at Algolia (though it is listed there, in the sidebar); it is configured through [a JSON file](https://docsearch.algolia.com/docs/config-file/) in their public repo:

- [docsearch-configs/rasa.json at master · algolia/docsearch-configs](https://github.com/algolia/docsearch-configs/blob/master/configs/rasa.json)

This is of course out of date now, so we need to do a PR to remove that JSON and create two new ones, one for each of the new sites; however this can't be done until their `baseUrl` settings are final (without the `/next/` addition).

CC @m-vdb

**Comment by m-vdb** [comment]
@lunelson where would be a good place to document this setup? 😬

**Comment by lunelson** [comment]
@m-vdb if you create a Notion page for it, I'll add these points in. I can't tell where it should live....I guess in "Customer Success Engineering"?

**Comment by m-vdb** [comment]
🤔 I don't know either. For now, it might be easier to do that right in the code by writing a comment about this (in docusaurus config?)

**Comment by lunelson** [comment]
@m-vdb OK, we'll track the tasks here but make notes in the respective `docusaurus.config.js` files of `rasa` and `rasa-x` then. Do you want to set a specific date for removing the `/next/` subdirectory? If it happens just before launch it might mean they launch without search or with fresh search indexes that are not yet fully crawled

**Comment by lunelson** [comment]
Further update today: an alternative to building separate indexes for `rasa-opensource` vs `rasa-x`, is to build one index but [apply tags](https://docsearch.algolia.com/docs/config-file/#using-custom-tags)... TBC

**Comment by lunelson** [comment]
@m-vdb @fullpoint update:

After my last email with Sylvain Pace I've had no response. He last suggested a single index using different tags (as noted above) instead of three different indexes, but as far as I can tell this is an under-documented scenario.

Otherwise [the normal process of applying for an index is explained here](https://docsearch.algolia.com/docs/how-does-it-work), and I think we need one for each of:
- rasa.com/docs/rasa
- rasa.com/docs/rasa-x
- rasa.com/docs/action-server

Also, [our current (outdated) index is represented here](https://github.com/algolia/docsearch-configs/blob/master/configs/rasa.json), so a PR should be created on that repo to either modify or delete it. If modifying, please note:
- the config was never right, since it did not distinguish between rasa-oss and rasa-x; it would have to be duplicated and renamed as e.g. `rasa-x-legacy.json` and `rasa-legacy.json`, and configured to index those sites

**Comment by m-vdb** [comment]
@lunelson thanks for updating, I'm taking this on 👍

**Comment by m-vdb** [comment]
I've submitted a [PR to DocSearch](https://github.com/algolia/docsearch-configs/pull/2420) (already approved, that went fast 🤔 )

**Comment by lunelson** [comment]
@m-vdb yeah I'm slightly disappointed that they didn't comment at all...

As for the config: 

1. I'm not sure if we're going to be able to use the custom-tags with the API that's exposed by Docusaurus 🤔 and I was hoping to avoid having to dig further in to Algolia's library 😬 
2. if you check [Docusaurus' own config here](https://github.com/algolia/docsearch-configs/blob/master/configs/docusaurus-2.json), there are some points we might have missed, for example the sitemap links, and potentially the selector patterns will need more adjustment, and then there's a bunch of options I don't know about at all 🤷

**Comment by m-vdb** [comment]
ok thanks for pointing me towards it. I assume that the tags won't be an issue (modulo some tweaks). I'll continue on these

**Comment by m-vdb** [comment]
@lunelson 
1. Yes I think it will work, cf. the 3 draft PRs I prepared ⬆️ ⬆️ ⬆️ 
2. I've updated our config with [this second PR](https://github.com/algolia/docsearch-configs/pull/2422).

**Comment by akelad** [comment]
are we still waiting on updates from algolia for this?

**Comment by m-vdb** [comment]
Yes I sent a second email yesterday to follow-up. In the worst case, we'll disable the search bars for the launch. Hopefully it doesn't come to that 🤞

**Comment by TyDunn** [comment]
@m-vdb @akelad I can reach out to Paul-Louis Nech, the person who connected us to Sylvian, if we want to push a bit harder

**Comment by m-vdb** [comment]
@TyDunn that would be awesome. I'm forwarding you the email I sent Sylvain that way you would know what to exactly ask for

**Comment by akelad** [comment]
@m-vdb what's the issue? I don't think we should disable the search bars, that's gonna be a super annoying user experience (it already is a little)

**Comment by m-vdb** [comment]
we do not have the API key, and we cannot even test the search right now. I've prepared some draft PRs to update the config, but without access I cannot guarantee it works ^^. Ty reached out, hopefully we'll have an answer soon

**Comment by lunelson** [comment]
@m-vdb is it possible the API key is still the same one that was used in the search box of the legacy docs? Your PR was an update to the existing index configuration right?

**Comment by m-vdb** [comment]
yes it was simply an update. I actually didn't know that we had search configured through doc search before. I found the API key "1f9e0efb89e98543f6613a60f847b176" in the rasabaster theme, let me see if it "just works" 😅

**Comment by m-vdb** [comment]
@lunelson it seems to work, but I don't think that their crawler ran (as I mentioned in my email to them). Results are the old results. Let's wait for their reply

**Comment by akelad** [comment]
ehh @m-vdb should we be sharing that API key on a public repo? 😅

**Comment by akelad** [comment]
i've removed it from your comment, but perhaps we should request a new one from them just to be safe?

**Comment by m-vdb** [comment]
@akelad it's ok that's why I shared it (it's basically available when you scan the network calls...), there's no sensitive info there. Let's wait for their answers

**Comment by lunelson** [comment]
> I don't think that their crawler ran (as I mentioned in my email to them). Results are the old results. Let's wait for their reply

OK cool. I still think filling out the application form might trigger some action though 🤷

**Comment by m-vdb** [comment]
latest update:
- it works on Rasa ✅ 
- it works on Rasa SDK ✅ 
- for some reason it doesn't work on Rasa X 🔴 

Continuing the conversation with their support, we should get an answer today or tomorrow for Rasa X.

**Comment by tmbo** [comment]
@m-vdb anything we should / need to do before the rasa open source 2.0 release today?

**Comment by m-vdb** [comment]
@tmbo I'm still waiting for a reply from Algolia. We can go ahead with the release (search is currently disabled) and update master later when things are fixed on Algolia's side.

**Comment by tmbo** [comment]
ok sounds good, will move this to 2.1

**Comment by lunelson** [comment]
Update: [related issue here](https://github.com/RasaHQ/tabula/issues/34) concerning the OpenSearch Description XML file generated by Docusaurus' plugin
