### ISSUE TITLE
Time computation with Diet Classifier

### ISSUE THREAD

**Issue by Asma-droid** [RasaHQ/rasa#6332]
Hi all,

I want just to mentionned that Dieat Classifier is very very slow when training a model compared with the embeddingClassifier.
For the same data and with 300 epochs:

-embedding classifiers takes around 20 minutes
- Diet Classifier takes more than 24 hours.

Think you that is normal ??

**Comment by sara-tagger** [comment]
Thanks for raising this issue, @koaning will get back to you about it soon✨

###### Please also check out the [docs](https://rasa.com/docs/) and the [forum](https://forum.rasa.com/) in case your issue was raised there too 🤗

**Comment by koaning** [comment]
Would you share some more data? What version of Rasa/python and the size of your dataset? If you could share your `config.yml` we might also help. 

It does sound like something strange is happening.

**Comment by Asma-droid** [comment]
hi @koaning 

I am in rasa 1.0.8 with python 3.7.3 and i have 7280 lignes in my nlu.md

below is my config.yml

language: fr_core_news_md
/***********************************/
pipeline:
  - name: WhitespaceTokenizer
  - name: RegexFeaturizer
  - name: LexicalSyntacticFeaturizer
  - name: CountVectorsFeaturizer
  - name: CountVectorsFeaturizer
    analyzer: "char_wb"
    min_ngram: 1
    max_ngram: 4
  - name: DIETClassifier
    epochs: 300
  - name: EntitySynonymMapper

policies:
  - name: "MemoizationPolicy"
    max_history: 3
  - name: "FallbackPolicy"
    nlu_threshold: 0.7
    core_threshold: 0.7
  - name: MappingPolicy

/*********************/

I would also highlighted that Diet Classifier gives several False Positive 
![image](https://user-images.githubusercontent.com/55100050/89530842-7b0fa580-d7ef-11ea-8e40-025557f9938c.png)

**Comment by koaning** [comment]
I assume you meant 1.8.0 instead of 1.0.8. 

- I might recommend upgrading Rasa to 1.10. There have been some performance improvements after the initial release and these might certainly help.
- DIET, like any ML algorithm, is not going to be perfect. There's bound to be false positives and false negatives. Or are there significantly more false classifications compared to EmbeddingIntent model?
