### ISSUE TITLE
Events history can't be cleared and deffect server performance

### ISSUE THREAD

**Issue by baudzhou** [RasaHQ/rasa#6334]
**Description of Problem**:

I’m using an in memory tracker store. After many turns of conversation, rasa become slower and slower. Checked the log and then I find that every time rasa core extract all events and send to action server. Related logs following:
`2020-08-04 10:30:21 DEBUG    rasa.core.processor  - Logged UserUtterance - tracker now has 23242 events.`
`2020-08-04 10:30:21 DEBUG    rasa.core.processor  - Predicted next action 'form_xx' with confidence 1.00.
2020-08-04 10:30:21 DEBUG    rasa.core.actions.action  - Calling action endpoint to run action 'form_xx'.
/usr/local/miniconda3/lib/python3.6/site-packages/aiohttp/payload.py:228: ResourceWarning: Sending a large body directly with raw bytes might lock the event loop. You should probably pass an io.BytesIO object instead`
I checked action call data, and found that it’s very big.
**Overview of the Solution**:

I don't think that's a good idea to pass all events history to action server every time. The history is useless.
**Examples** (if relevant):

**Blockers** (if relevant):

**Definition of Done**:

**Comment by sara-tagger** [comment]
Thanks for submitting this feature request 🚀 @tmbo will get back to you about it soon! ✨

**Comment by tmbo** [comment]
Do you know how many turns that conversation has? Which version of Rasa are you using?

**Comment by baudzhou** [comment]
> Do you know how many turns that conversation has? Which version of Rasa are you using?

rasa 1.10
The events are stacked more and more. After about 10,000 truns, response time was 2 seconds.

**Comment by tmbo** [comment]
having a conversation with 10000 turns is pretty rare, so I am curious how you ended up with a conversation that is this long? 🤔

**Comment by baudzhou** [comment]
> having a conversation with 10000 turns is pretty rare, so I am curious how you ended up with a conversation that is this long? 🤔

It's not ONE conversation but many conversations some of which has multi turns from one sender.
We were doing performance test.
All of the history events are extracted when rasa core passing data to action server. Even "/restart" command is executed, events are still extracted.

**Comment by tmbo** [comment]
I am not sure I can follow, when Rasa sends the data to the action server it will only send events relevant for that specific conversation. Since a conversation is defined by its `sender_id` I am not yet sure why you'd end up with so many turns from different conversations. I'd say it is highly unlikely that a human user would send so many messages even if they are separated by restarts. if you are trying to simulate load on the server, it would make more sense to use different sender_ids, to simulate different conversations

**Comment by pbuszka** [comment]
The /restart event does not clear events history in tracker but just adds a special event at the end which is normally interpretated as logically discard everything what was before. So if you work on the same conversation id and make 1000 x /restart  you get 1 very long conversation with length of 1000x single covnersation. If you do performce testing it would be better to use a different covnersation id every time - ussually it is a more realistic scenario as well but it depends on your use case.

**Comment by wochinge** [comment]
We introduced [session configurations](https://rasa.com/docs/rasa/2.0.x/domain#session-configuration) a while ago which solve this problem. While the `InmemoryTrackerStore` still retrieves the entire history, you can use external tracker stores such as the `SQLTrackerStore` or `MongoDbStore` which only retrieve the history from the latest session.
