### ISSUE TITLE
New docs: "conversation patterns" page reworks

### ISSUE THREAD

**Issue by erohmensing** [RasaHQ/rasa#6335]
The Conversation Patterns pages were pulled from the Building Assisants tutorial. Each should get looked at and make sure that they make sense as content on their own. Some things to check: 

- These pages should be able to be followed independently from one another (one should not have had to have e.g. made the level 2 bot to implement a form) 
- Take note of where examples need to be replaced due to training data format (adding `TODO`s is fine) 
- Give pages more structure with more headers (e.g. the Business Logic) one currently has one, because it was only one section in Building Assistants 
- Add info about human handoff to Fallback and Handoffs (currently only references fallback)

**Comment by melindaloubser1** [comment]
Specifics found when starting on this:
- contextual conversations page will need to be rethought based on the rule policy. 
- unexpected input refers to faq/chitchat; not sure it's possible to totally remove this link because handling faqs is one thing, and using faqs in interjections is a different thing, but it definitely relies on the first.

**Comment by erohmensing** [comment]
> unexpected input refers to faq/chitchat; not sure it's possible to totally remove this link because handling faqs is one thing, and using faqs in interjections is a different thing, but it definitely relies on the first.

Makes sense! they can definitely link to one another -- I more meant that one shouldn't assume that the user already has FAQ/chitchat data when beginning to read the unexpected input page. In order to provide data for that they should see the chitchat/faq page

**Comment by melindaloubser1** [comment]
Closed by https://github.com/RasaHQ/rasa/pull/6373
