### ISSUE TITLE
New docs: legacy docs deployment + links

### ISSUE THREAD

**Issue by m-vdb** [RasaHQ/rasa#6339]
With the new docs system in place, we need a way to link to legacy docs.

### Current setup
1. Rasa docs are deployed on Netlify [here](https://app.netlify.com/sites/rasahq-docs-rasa). They are then embedded (via Netlify redirects) in the rasa.com website
2. Legacy docs (for 0.x) are deployed on Netlify [here](https://app.netlify.com/sites/priceless-jang-11b3ee/overview).
3. no updates are made to these docs anymore

### Proposal: New setup
1. Rasa 2.x docs are deployed on Netlify [here](https://app.netlify.com/sites/rasahq-docsv2-rasa). They **will** be embedded like the current docs, under rasa.com. At the moment they are available through a redirect from rasa.com/docs/rasa/next/
2. Rasa 1.x will be hosted at: _legacy-docs-v1.rasa.com/_
3. Rasa 0.x will be hosted at either:  _legacy-docs-v0.rasa.com/_

These would be setup via Netlify redirects. We can keep the deploy settings for 1.x docs because it will still be useful if we want to push docs on feature branches, but eventually we should remove it.

Last but not least, we will need to link to those docs:
- we can do it in the homepage, like we do now:
<img width="771" alt="Screenshot 2020-08-04 at 17 40 10" src="https://user-images.githubusercontent.com/1931615/89314116-8f319680-d679-11ea-8aca-a98d3cbc77f1.png">

- and/or we can add links to the legacy docs in the dropdown of versions:
<img width="431" alt="Screenshot 2020-08-04 at 17 40 59" src="https://user-images.githubusercontent.com/1931615/89314236-ab353800-d679-11ea-929e-1ea4e6d2048d.png">

**Comment by m-vdb** [comment]
cc @tmbo @lunelson I forgot to create the task at the time, so here it is, with a proposal in the desc!

**Comment by lunelson** [comment]
Yes I would suggest we make the following new subdomains:
```
legacy-docs-v0.rasa.com
legacy-docs-v1.rasa.com
```
...and then redirect the current `legacy-docs` to `legacy-docs-v0` with a splat and `301`

**Comment by tmbo** [comment]
Sounds good, let’s goooo 🚀

**Comment by m-vdb** [comment]
@lunelson I just saw that you added this to your board, but I was planning to make progress on this during the week. Can I steal this from you?

**Comment by lunelson** [comment]
@m-vdb yes, no problem 👍 !
