### ISSUE TITLE
Unable to recognize multiple entities of same type in a sentence without any separation symbol (or a single space)

### ISSUE THREAD

**Issue by praneethgb** [RasaHQ/rasa#6340]
test file for reference: https://github.com/RasaHQ/rasa/blob/2b12852ae04aa2d9de6bacdc5b44d1894295fb27/tests/nlu/extractors/test_extractor.py

(
            "Amsterdam Berlin and London",
            {
                "entity": ["city", "city", "O", "city"],
                "role": ["O", "O", "O", "O"],
                "group": ["O", "O", "O", "O"],
            },
            None,
            [
                {"entity": "city", "start": 0, "end": 16, "value": "Amsterdam Berlin"},
                {"entity": "city", "start": 21, "end": 27, "value": "London"},
            ],
        ),

expected should be : 
{"entity": "city", "start": 0, "end": 8, "value": "Amsterdam"},
{"entity": "city", "start": 9, "end": 16, "value": "Berlin"},
{"entity": "city", "start": 21, "end": 27, "value": "London"}

Because Amsterdam (U-city) and Berlin (U-city) are different city entities.

**Comment by praneethgb** [comment]
Hi @tabergma,

would be able to provide your inputs on this issue?

**Comment by sara-tagger** [comment]
Thanks for the issue, @tttthomasssss will get back to you about it soon!

###### You may find help in the [docs](https://rasa.com/docs/) and the [forum,](https://forum.rasa.com/) too 🤗

**Comment by tabergma** [comment]
@praneethgb This is expected behaviour. For more explanation see [this PR](https://github.com/RasaHQ/rasa/pull/6191) and the related [forum post](https://forum.rasa.com/t/unable-to-classify-multiple-examples-of-the-same-entity-please-help/28851).

**Comment by praneethgb** [comment]
Hi @tabergma , 

"Amsterdam Berlin" is not a city name. 

For Example: consider this use case, my ingredients are eggs(ingredients)  potato chips(ingredients) and milk(ingredients). My ASR output was 'my ingredients are eggs potato chips and milk'. 
When the DIET model is trained for NER, is trained to recognize them as eggs: U-ingredients, potato: B-ingredients, chips: L-ingredients, milk: U-ingredients.
So in postprocessing also we expect the eggs, milk and potato chips as three different ingredients entities (currently which is not happening, as eggs and potato chips, are merged in postprocessing by removing BILOU tags in https://github.com/RasaHQ/rasa/blob/master/rasa/nlu/classifiers/diet_classifier.py#L938 )

**Comment by tabergma** [comment]
@praneethgb Not sure I understand what you are suggesting. I know that "Amsterdam Berlin" is not a city and it is not ideal that we capture it as one entity. The problem is that if we don't merge entities with the same tag when they appear right next to each other, we would not be able to detect "San Fransisco", for example, it would always be detected as "San" and "Fransisco" - two independent entities. Which is also not ideal.
What is your idea to support both cases? Please keep in mind that not all users are using BILOU tagging. 
Also, if you add a comma in between your ingredients, everything should be extracted as expected. E.g. "my ingredients are eggs, lemon juice, and milk".

**Comment by AMR-KELEG** [comment]
I am starting to bump into similar issues with some queries so I am sharing my thoughts (I am not exposed enough to how BILOU tagging is used in DIET/ nlu data).
> @praneethgb Not sure I understand what you are suggesting. I know that "Amsterdam Berlin" is not a city and it is not ideal that we capture it as one entity. The problem is that if we don't merge entities with the same tag when they appear right next to each other, we would not be able to detect "San Fransisco", for example, it would always be detected as "San" and "Fransisco" - two independent entities. Which is also not ideal.

This might be a bit optimistic but this is how I think the model should behave:
Input | Correct/expected prediction |  Processed prediction (merging BILOU tags)
---|---|---
Amsterdam Berlin | `[Amsterdam](U-city) [Berlin](U-city)` | `[Amsterdam](city) [Berlin](city)`
San Fransisco | `[San](B-city) [Fransisco](L-city)` | `[San Fransisco](city)`

> What is your idea to support both cases? Please keep in mind that not all users are using BILOU tagging.

Yes, I myself still get confused by BILOU tagging but doing a mapping like the one shown above would be convenient to the users.

> Also, if you add a comma in between your ingredients, everything should be extracted as expected. E.g. "my ingredients are eggs, lemon juice, and milk".

We (as developers/ engineers/ researchers) can have our set of guidelines but it's sometimes frustrating to the users who interact with the chatbot to follow a certain format (or at least it would be better if we can support more ways of writing queries i.e: `eggs lemon juice and milk` and `eggs, lemon juice and milk` as long as doing so won't hurt the model's performance ).

**Comment by tabergma** [comment]
Yeah, I think we can update this for BILOU tagging, but I guess it will not be possible in case the model is trained without BILOU tagging. @praneethgb or @AMR-KELEG anyone of you willing to create a PR for this?

**Comment by AMR-KELEG** [comment]
> Yeah, I think we can update this for BILOU tagging, but I guess it will not be possible in case the model is trained without BILOU tagging. @praneethgb or @AMR-KELEG anyone of you willing to create a PR for this?

I will need to have a look first but yes I am willing to work on it.

**Comment by praneethgb** [comment]
> Also, if you add a comma in between your ingredients, everything should be extracted as expected. E.g. "my ingredients are eggs, lemon juice, and milk".

Also, If we use voice input, then comma won't be present in input at all from Automatic Speech Recognition models. 

> Yeah, I think we can update this for BILOU tagging, but I guess it will not be possible in case the model is trained without BILOU tagging

Yes.

**Comment by praneethgb** [comment]
Hi @tabergma, 

I've created PR: https://github.com/RasaHQ/rasa/pull/6423 to support this use case.
