### ISSUE TITLE
Nlu inbox not showing confidence score 

### ISSUE THREAD

**Issue by hernanbari** [RasaHQ/rasa#6341]
**Rasa version**:
RASA_VERSION=1.10.8

**Rasa X version** (if used & relevant):
RASA_X_VERSION=0.31.2

**Python version**:
3.7

**Operating system** (windows, osx, ...):
osx

**Issue**:
Hello, I’ve been migrating conversations from a non-rasa chatbot, using the http-api of rasa X. In particular, the endpoint [createEvent](https://rasa.com/docs/rasa-x/api/rasa-x-http-api/#operation/createEvent).

The confidence scores are shown correctly in the conversations tab, but they don't appear in the NLU Inbox, making it really hard to iterate. I'm not sure if there's a bug or I'm doing something wrong.

This is the payload of the request:
```
{'timestamp': 1596559986.547,
 'sender_id': '3082974311797704',
 'text': 'Emipropuesta1039',
 'event': 'user',
 'parse_data': {'entities': [],
  'intent': {'name': 'haveCode', 'confidence': 0.44105276465415955},
  'text': 'Emipropuesta1039',
  'is_flagged': False}}
```

Thanks!

**Error (including full traceback)**:
Conversation tab showing confidence score correctly:
![image](https://user-images.githubusercontent.com/5355602/89335757-d1090f80-d66e-11ea-8200-cbd40763907c.png)

NLU Inbox NOT SHOWING confidence score of ANY SENTENCE:
![image](https://user-images.githubusercontent.com/5355602/89335819-e7af6680-d66e-11ea-9498-16fdb265314f.png)

**Comment by sara-tagger** [comment]
Thanks for raising this issue, @melindaloubser1 will get back to you about it soon✨

###### Please also check out the [docs](https://rasa.com/docs/) and the [forum](https://forum.rasa.com/) in case your issue was raised there too 🤗

**Comment by hernanbari** [comment]
Two more pieces of information:
- Talking to the bot through the "Talk to your bot" chat correctly shows the confidence score in the Inbox
- The only two difference between the events in the `events` table of the db is that the message added through the talking has `message_id` and `input_channel` set, and the migrated does not:

### Talking
```
{
  "event": "user",
  "timestamp": 1596825845.3090084,
  "text": "termine en 2010",
  "parse_data": {
    "intent": {
      "name": "haveCode",
      "confidence": 0.9348964691162109
    },
    "entities": [
    ],
    "intent_ranking": [...],
    "text": "termine en 2010"
  },
  "input_channel": "rasa",
  "message_id": "429422f8c1df4491bc588677616949e0",
  "metadata": {}
}
```

### Migrated
```
{
  "event": "user",
  "timestamp": 1596818572.693,
  "text": "Attachment",
  "parse_data": {
    "entities": [],
    "intent": {
      "name": "acknowledge",
      "confidence": 0.9999896883964531
    },
    "text": "Attachment",
    "is_flagged": false
  },
  "input_channel": null,
  "message_id": null,
  "metadata": {}
}
```

**Comment by hernanbari** [comment]
More info: 
- Adding input channel does not change anything
- Posting to this endpoint `/projects/default/logs?q` correctly adds the score to the NLU inbox

So the hypothesis that it has something to do with the `message_id` is reinforced

**Comment by mjaycub** [comment]
Hey @hernanbari,

Thank you for raising this issue! I've been able to recreate this locally when the payload does not contain any entries in the `intent_ranking` array which we use to display the confidence for each respective intent in the dropdown menu.

We're looking into it now and I'll follow up when we have a fix!

**Comment by mjaycub** [comment]
Hi @hernanbari,

We looked into this to verify why this was happening.

The display of the confidence level for each intent depends on the values read from the `intent_ranking` array. When a message arrives, it should always have this array populated. Since your custom migration did not include this, you won't be able to see the intent confidence scores ranked on this screen. If you include this `intent_ranking` array in your future migrations, the display of the confidence score in the NLU Inbox should work as expected.

You are able to see the confidence on the conversation screen as this is taken from the `intent` object rather than the `intent_ranking` array.

I'm going to close this as this appears to be an issue with the migration not having the `intent_ranking` array included and populated.

**Comment by hernanbari** [comment]
Thank you, yes, I found the same.
