### ISSUE TITLE
Outstanding to-dos for new docs before 2.0

### ISSUE THREAD

**Issue by erohmensing** [RasaHQ/rasa#6347]
**Before the RC**:
Links:
- [x] Check all internal links are relative (this means that they will undergo linkchecking in `make docs`)
- [x] Check Rasa and Rasa X source code for links to rasa docs

Content:
- [x] Remove any incorrect/outdated content, references that recommend deprecated things
- [ ] Remove outdated references to `Core` as a concept - should be dialogue management
- [ ] Resolve any TODOs in the docs
- [x] Write SDK docs 
  - [x] Remove any unused plugins in SDK docs

2.0 Changes:
- [x] Check all examples of stories, nlu data, forms, e2e tests
  - these are auto-checked by Ci now: https://github.com/RasaHQ/rasa/pull/6449
  - [x] make sure e2e tests (however they are called) are included in the spec
- Updates to content: 
  - [x] `policies`, 
  - [x] `forms` 
  - [x] `nlu-training-data` 
  - [x] `training-data-format`
           - [x] Double check format specs are correct esp. for forms, rules and slots.
  - [x] docs on autoconfig

**Comment by melindaloubser1** [comment]
Adding one - Look for outdated references to Core

**Comment by erohmensing** [comment]
@melindaloubser1 want to make a separate issue for that? we should close this imo as i made issues for the rest

**Comment by melindaloubser1** [comment]
Ok sure
