### ISSUE TITLE
Tracker state is sent with no events to action server

### ISSUE THREAD

**Issue by omss24** [RasaHQ/rasa#6348]
**Rasa version**: 2.0.0a1

**Rasa SDK version** (if used & relevant):

**Rasa X version** (if used & relevant):

**Python version**:  3.7.8

**Operating system** (windows, osx, ...): Ubuntu running docker

**Issue**:
Traying to pass metadata to slots using `action_session_start`; the `events` key on the `tracker` data, on the action server request, is arriving empty.

I fixed it switching to version 1.10.10, same config but now the data POST has the `session_started` event with the metadata from the custom connector.

**Error (including full traceback)**:
```

```

**Command or request that led to error**:
```

```

**Content of configuration file (config.yml)** (if relevant):
```yml

```

**Content of domain file (domain.yml)** (if relevant):
```yml

```

**Comment by sara-tagger** [comment]
Thanks for raising this issue, @melindaloubser1 will get back to you about it soon✨

###### Please also check out the [docs](https://rasa.com/docs/) and the [forum](https://forum.rasa.com/) in case your issue was raised there too 🤗

**Comment by melindaloubser1** [comment]
What does your `action_session_start` look like? Can you show an example of what you mean?
