### ISSUE TITLE
New docs: add sitemap link to Google Search Console after ship

### ISSUE THREAD

**Issue by lunelson** [RasaHQ/rasa#6349]
When configured with [`@docusaurus/plugin-sitemap`](https://v2.docusaurus.io/docs/using-plugins/#docusaurusplugin-sitemap), Docusaurus generates a sitemap for all pages, respecting the `url` and `baseUrl` settings. Once these are final, the URL of the sitemap must be added to our Google Search Console for the rasa.com domain

**Comment by m-vdb** [comment]
> Once these are final

But we'll likely update things in the future. Google surely supports updates to sitemaps, right? In that case I guess we should do this around the 2.0.0rc1 version (first release candidate)

**Comment by lunelson** [comment]
Yeah that's the whole idea with sitemaps, google tracks the updates as well, but you declare in the map the rough frequency at which you expect content to change

**Comment by lunelson** [comment]
This is already in the current solution
