### ISSUE TITLE
Git connection

### ISSUE THREAD

**Issue by beremizsinistro** [RasaHQ/rasa#6360]
**Rasa version**: 1.10.10

**Rasa SDK version** (if used & relevant): 

**Rasa X version** (if used & relevant): 0.31.4

**Python version**:

**Operating system** (windows, osx, ...):

**Issue**: Server create in google cloud with docker-compose. After connecting with github. If you disconnect it from github. it shows that you are disconnected but when you try to connect it says you are already connected and you can't disconnect.

**Error (including full traceback)**:
```

```

**Command or request that led to error**:
```

```

**Content of configuration file (config.yml)** (if relevant):
```yml

```

**Content of domain file (domain.yml)** (if relevant):
```yml

```

**Comment by sara-tagger** [comment]
Thanks for the issue, @tabergma will get back to you about it soon!

###### You may find help in the [docs](https://rasa.com/docs/) and the [forum,](https://forum.rasa.com/) too 🤗
