### ISSUE TITLE
Change training data version warning to be a debug log

### ISSUE THREAD

**Issue by chkoss** [RasaHQ/rasa#6361]
In the new training data, you can put a `version` key in the files. If you don't do this, you will see warnings like:
`UserWarning: Training data file /Users/christina/rasa/rasa/cli/initial_project/domain.yml doesn't have a 'version' key. Rasa Open Source will read the file as a version '2.0' file.` (originating from [here](https://github.com/RasaHQ/rasa/blob/219baa461c066a199fb4fb10a123012ebc8182b3/rasa/validator.py#L294))

I'd suggest to not raise those warnings, but rather put them into a debug log.

My reasoning is this (see also the comments in this PR: https://github.com/RasaHQ/rasa/pull/6329#pullrequestreview-462397138):
Adding the version is not expected but rather an optional feature that people can use to get warned about incompatibilities with their Rasa Open Source version. (Or am I mistaken here?) The warnings seem to indicate that something is a problem, which is not the case.
Also, if we want to avoid that users see multiple warnings for each training data file when running `rasa init`, we would have to add a `version` key to the init project, too and manually maintain that to stay up to date.

**Comment by chkoss** [comment]
@degiz what do you think?

**Comment by degiz** [comment]
> It depends on how much we want to urge people to explicitly include a version

We want them to at least be aware of the format version. The reason is - once things don't work for them in the future, when the format changes, they will know where to start.

I like the idea that we define the `version` in example bots, because that's great to show the users that it's a good practice to have the `version key`.

> a warning when a version is provided and it's too high, a debug log when no version is provided.

it makes sense, so let's do that.
