### ISSUE TITLE
Parser should throw warning for deprecated entity annotation syntax

### ISSUE THREAD

**Issue by melindaloubser1** [RasaHQ/rasa#6365]
**Rasa version**: 2.0.0.a1

**Issue**:

The following syntax for entity annotation should lead to a deprecation warning, but it does not:

```
- My name is [Bob](name)
```

**Comment by degiz** [comment]
Oh, I think I remember now. I simply deprecated that! 😎 
That means, that we should raise an error now in case "the old" format is used and skip this training example!

**Comment by degiz** [comment]
@melindaloubser1 What's happening with this training example that you've provided?

**Comment by melindaloubser1** [comment]
Oh, nothing is happening to it if it shouldn't exist, just discovered it while working on the docs

**Comment by degiz** [comment]
Not even a warning? Then it's bad..

**Comment by melindaloubser1** [comment]
Sorry I misunderstood. I thought you meant "what is happening in the docs to this kind of example - are they getting changed?". But you're right, no warning.

**Comment by degiz** [comment]
Ok, as discussed in Slack, we're un-deprecating this syntax. 
@melindaloubser1 can I use this issue to add unit tests instead?

**Comment by melindaloubser1** [comment]
Go for it!

**Comment by degiz** [comment]
Changed my mind - I'll close this issue and just open a PR 😸
