### ISSUE TITLE
Can't exit a Form

### ISSUE THREAD

**Issue by ClaudioVictorSpinelli** [RasaHQ/rasa#6371]
**Rasa version**:
1.8

**Rasa SDK version** (if used & relevant):
1.8

**Rasa X version** (if used & relevant):

**Python version**:
3.7
**Operating system** (windows, osx, ...):
Windows 7
**Issue**:

I am using the proposed way to exit a form but FormPolicy always take precedence a never excecute ask_continue, i don`t know how to solve this:

## story
>checked_start

* intent x
    - form_x
    - form {“name”: “form_x”}
* chitchat
    - respond_chitchat
    - action_ask_continue
* deny
    -    utter_stop
    -    action_deactivate_form
    - form {“name”: null}

intent x comes from a mapping declared in domain.yml

when the user types something corresponding to the chitchat said intent is detected with confidence = 0.99

but then in all cases the FormPolicy returns that a form is active and the chosen action is always the form again.

name: MappingPolicy

name: “FormPolicy”

name: “TwoStageFallbackPolicy” nlu_threshold: 0.5 ambiguity_threshold: 0.1 core_threshold: 0.5 fallback_core_action_name: “custom_default_fallback” fallback_nlu_action_name: “custom_default_fallback” deny_suggestion_intent_name: “deny_suggestion”

What is wrong or what should I change? 

**Error (including full traceback)**:
```

```

**Command or request that led to error**:
```

```

**Content of configuration file (config.yml)** (if relevant):
```

My config is the following:

language: is pipeline:

name: WhitespaceTokenizer case_sensitive: false
name: LexicalSyntacticFeaturizer
name: CountVectorsFeaturizer analyzer: “char_wb” min_ngram: 1 max_ngram: 4
name: DIETClassifier batch_size: [64,128] epochs: 50
name: EntitySynonymMapper
name: “ResponseSelector”
policies:

name: MemoizationPolicy max_history: 5

name: TEDPolicy max_history: 5 epochs: 40 state_featurizer: LabelTokenizerSingleStateFeaturizer
```

**Content of domain file (domain.yml)** (if relevant):
```yml


```

**Comment by sara-tagger** [comment]
Thanks for the issue, @dakshvar22 will get back to you about it soon!

###### You may find help in the [docs](https://rasa.com/docs/) and the [forum,](https://forum.rasa.com/) too 🤗

**Comment by dakshvar22** [comment]
@ClaudioVictorSpinelli Do you still see the same problem with newer versions of Rasa Open Source?

**Comment by TyDunn** [comment]
@dakshvar22 @ClaudioVictorSpinelli We are closing this because of the lack of response
