### ISSUE TITLE
Add schema and writer for 2.0 Core data 

### ISSUE THREAD

**Issue by degiz** [RasaHQ/rasa#6374]
part of #6129

- Add YAML schema for the 2.0 YAML Core data
- Add a Core writer (will be used to convert MD to the 2.0 YAML)

**Comment by wochinge** [comment]
related: https://github.com/RasaHQ/rasa/issues/6378

**Comment by m-vdb** [comment]
@degiz is it looking like we're going to make it into 2.0.0a2? how can we help you?
