### ISSUE TITLE
Rasa Shell and Rasa x UI Getting Problem

### ISSUE THREAD

**Issue by Naveen-2506** [RasaHQ/rasa#6382]
**Rasa version**: 1.10.10

**Rasa SDK version** (if used & relevant): 1.10.2

**Rasa X version** (if used & relevant):  0.31.3

**Python version**: 3.6.9

**Operating system** (windows, osx, ...): Ubuntu 18.04.4 LTS

**Issue**:
Hi!
I'm facing the error in **rasa x-UI** and **rasa shell-local bot**

**rasa x**
rasa x actually works, but if I do some modification in domain file or other files, it's not modified properly. 
UI background Terminal showing some errors like this.....
![Screenshot from 2020-08-11 15-49-20](https://user-images.githubusercontent.com/47246354/89887873-b1349700-dbec-11ea-961f-1309323f84d8.png)

**rasa shell**
And then I pass the **rasa shell** comment to test my bot...
the bot was ready to get input and I give some input like "Hi"...
and output not coming from a bot and it's showing this error...
![Screenshot from 2020-08-11 16-13-24](https://user-images.githubusercontent.com/47246354/89888450-9dd5fb80-dbed-11ea-8add-83819587e70e.png)

anyone help to fix those errors...

**Comment by sara-tagger** [comment]
Thanks for the issue, @Ghostvv will get back to you about it soon!

###### You may find help in the [docs](https://rasa.com/docs/) and the [forum,](https://forum.rasa.com/) too 🤗

**Comment by federicotdn** [comment]
Hi @Naveen-2506, thanks for bringing this up. Does the same happen when you try with a project created using `rasa init --no-prompt`?

**Comment by Naveen-2506** [comment]
> Hi @Naveen-2506, thanks for bringing this up. Does the same happen when you try with a project created using `rasa init --no-prompt`?

nope, I'm just passing the comment ### rasa init to create a project...
is it any problem with this issue...?

**Comment by Naveen-2506** [comment]
@Ghostvv @federicotdn @sara-tagger @sheldon @tjpalmer  anyone gives me a solution for this error...
