### ISSUE TITLE
Rasa X - Using createEvent endpoint also adds to training data

### ISSUE THREAD

**Issue by hernanbari** [RasaHQ/rasa#6387]
**Rasa version**:
RASA_VERSION=1.10.8

**Rasa X version** (if used & relevant):
RASA_X_VERSION=0.31.2

**Python version**:
3.7

**Operating system** (windows, osx, ...):
osx

**Issue**:
Hello, I’ve been migrating conversations from a non-rasa chatbot, using the http-api of rasa X. In particular, the endpoint [createEvent](https://rasa.com/docs/rasa-x/api/rasa-x-http-api/#operation/createEvent).

Weirdly, using that endpoint also adds the message to the training data and the intents to the domain file. For example, it adds intents that aren't in the domain file but show up in the migrated conversations events.
I think this is a bug? Can some reproduce it to make sure?

**Comment by sara-tagger** [comment]
Thanks for raising this issue, @tttthomasssss will get back to you about it soon✨

###### Please also check out the [docs](https://rasa.com/docs/) and the [forum](https://forum.rasa.com/) in case your issue was raised there too 🤗
