### ISSUE TITLE
Ensure all data loading uses `TrainingDataImporter` interface

### ISSUE THREAD

**Issue by wochinge** [RasaHQ/rasa#6389]
There are still a couple of parts in the code which load training data without using the `TrainingDataImporter` interface.

*   All code which is loading training data should use the interface, so we can change the implementation in one place
*   Users currently can't use custom importers for this part.

An incomplete list:

*   `rasa test nlu` ([code](https://github.com/RasaHQ/rasa/blob/b15bfb54806f1b27169c2a49d3db54e8102c21e9/rasa/nlu/test.py#L1188))

**Comment by ortsaCniveK** [comment]
This is also superset of #5986

**Comment by ortsaCniveK** [comment]
Could we add a sub-task to this that exposes the TrainingDataImporter interface from the `rasa.importers` module?  It's cleaner to do:
`from rasa.importers import TrainingDataImporter`
compared with:
`from rasa.importers.importer import TrainingDataImporter`

Also, found some other locations:

* `rasa data convert` [(code)](https://github.com/RasaHQ/rasa/blob/06494203b6c722052bb7f5c7696408ac3c87da98/rasa/nlu/convert.py#L22)
* `rasa interactive` [(code)](https://github.com/RasaHQ/rasa/blob/be509cf30a2db80582790d7d02690dec1ed30d21/rasa/core/training/interactive.py#L1501)
* `rasa data split` [(code)](https://github.com/RasaHQ/rasa/blob/5eb86b36134dcd17fb16799df9c10c1ee600e533/rasa/cli/data.py#L153)
* `rasa.core.visualize` [(code)](https://github.com/RasaHQ/rasa/blob/0ddb5e083522c7c4cd6e244a22b25d664c18e4d0/rasa/core/visualize.py#L45)

**Comment by m-vdb** [comment]
thanks for jumping in @ortsaCniveK ! would you like to draft a PR for these changes?

**Comment by ortsaCniveK** [comment]
Sure, I can pitch in!
