### ISSUE TITLE
Language Support still refers to pipeline templates

### ISSUE THREAD

**Issue by tabergma** [RasaHQ/rasa#6395]
**Description of Problem**:
The [Language Support doc page](https://rasa.com/docs/rasa/nlu/language-support/) still references the pipeline templates. As the pipeline templates are deprecated, we should update the page and refer to concrete pipelines.

See also this [forum post](https://forum.rasa.com/t/new-language-support-docs-inconsistency/32477).

**Comment by erohmensing** [comment]
Should be fixed on master! https://github.com/RasaHQ/rasa/blob/master/docs/docs/tuning-your-model.mdx

**Comment by erohmensing** [comment]
No longer referenced on the [Language support](https://rasa.com/docs/rasa/next/language-support) page
