### ISSUE TITLE
Add CI to lint data examples in docs

### ISSUE THREAD

**Issue by erohmensing** [RasaHQ/rasa#6399]
We provide lots of examples of training data and domains in our documentation. It would be great to have CI that validates whether these examples are valid rasa format. We can use the existing rasa methods to validate this.

**Implementation:**

1. on the rendering side, docusaurus uses Prisme. And it looks possible to add a custom language (i’d suggesting “yaml-rasa”). So basically we would add a new language that has the same syntax as yaml.
2. on the CI side: it should be possible to detect codeblocks of a specific type. This is was we’re currently doing in our of our plugins. This way we can run tests that pass each codeblock of this type through the training data reader/linter.

**Comment by erohmensing** [comment]
@m-vdb would step 1 be something that you or @lunelson do? I am happy to take on step 2. I've seen this [come up quite a lot](https://rasa-hq.slack.com/archives/C36SS4N8M/p1597329286049800) during the alpha, so would love to have it around

**Comment by lunelson** [comment]
>would step 1 be something that you or @lunelson do?
@erohmensing yeah that sounds possible. Is the main concern here that you want to lint these things on build, or that you want to highlight them a different way, or that you just want to the code block to indicate that it's "rasa yaml" not just "yaml"?

**Comment by erohmensing** [comment]
Main concert is linting things on build to make sure they're valid! I don't know one adds a custom language, but for these purposes it could be just a subclass of the yaml one that behaves exactly the same, but is rasa yaml, and therefore needs to be linted in the CI. 

highlighting them in a different way could also be cool but is likely unnecessary 😄

**Comment by lunelson** [comment]
OK cool. The linting process sounds like something that could be added alongside the other build scripts that run in the `pre-build` step, as a node script that just extracts those codeblocks on the basis of regexes, wdyt @m-vdb ?

**Comment by m-vdb** [comment]
yes that's what I had in mind. In terms of prio, it doesn't strike me as something we need to do now (as opposed to after 2.0 release). WDYT @erohmensing ?

**Comment by erohmensing** [comment]
Mm, I think it'd be really good to have it for the 2.0 release. This would make sure that every example we give is actually valid, which is especially important when we're trying to tell users how to use a completely new training format for them.
