### ISSUE TITLE
LexicalSyntacticFeaturizer computes unnecessary operations !

### ISSUE THREAD

**Issue by sahinbatmaz** [RasaHQ/rasa#6406]
**Description of Problem**:

LexicalSyntacticFeaturizer computes unnecessary operations when creating features.

[https://github.com/RasaHQ/rasa/blob/master/rasa/nlu/featurizers/sparse_featurizer/lexical_syntactic_featurizer.py#L184](https://github.com/RasaHQ/rasa/blob/master/rasa/nlu/featurizers/sparse_featurizer/lexical_syntactic_featurizer.py#L184)

In the '_tokens_to_features' function, tokens are converted to appropriate features. However, when a window of features is given and there are common feature names among window elements, the same function is applied on the same token unnecessarily. The function is applied in the following line.

[https://github.com/RasaHQ/rasa/blob/master/rasa/nlu/featurizers/sparse_featurizer/lexical_syntactic_featurizer.py#L268](https://github.com/RasaHQ/rasa/blob/master/rasa/nlu/featurizers/sparse_featurizer/lexical_syntactic_featurizer.py#L268)

 value = self.function_dict<span class="error">[feature]</span>(token)

**Overview of the Solution**: In each sentence, keep a dictionary for tokens. If a function is applied on a token, keep the result in a dictionary. Probably using dictionary keys as a tuple of token text and given function would work. And the value will be the result.

Actually, there should not be a dictionary for each sentence. There could be one dictionary for all training data, since result will be same when the token text and the function are given.

This solution is somehow similar to Dynamic Programming in terms of keeping the result, and using it over and over when needed.

**Examples** : In my configuration file, I am a little bit greedy about this layer. My configuration looks like the following. The window size is 7 in the configuration.

*   name: LexicalSyntacticFeaturizer
     "features": [
     <span class="error">["low", "prefix5", "prefix2", "suffix5", "suffix3", "suffix2", "suffix1", "upper", "title", "digit",]</span>,
     <span class="error">["low", "prefix5", "prefix2", "suffix5", "suffix3", "suffix2", "suffix1", "upper", "title", "digit",]</span>,
     <span class="error">["low", "prefix5", "prefix2", "suffix5", "suffix3", "suffix2", "suffix1", "upper", "title", "digit",]</span>,
     <span class="error">["low", "prefix5", "prefix2", "suffix5", "suffix3", "suffix2", "suffix1", "upper", "title", "digit",]</span>,
     <span class="error">["low", "prefix5", "prefix2", "suffix5", "suffix3", "suffix2", "suffix1", "upper", "title", "digit",]</span>,
     <span class="error">["low", "prefix5", "prefix2", "suffix5", "suffix3", "suffix2", "suffix1", "upper", "title", "digit",]</span>,
     <span class="error">["low", "prefix5", "prefix2", "suffix5", "suffix3", "suffix2", "suffix1", "upper", "title", "digit",]</span>,
     ]

In my training dataset, there are 60k+ sentences. And this layer tooks around 26 minutes. When I set the window size as 1, the layer tooks around 4 minutes. Therefore, keeping the results of functions only in each sentence would improve my configuration from 26min to 4min. I think applying this operation to whole training data would let to less than 1 minute of layer processing time since words are common among sentences. (All operations in the configuration would be applied once for each token in the vocabulary.)

**Comment by sara-tagger** [comment]
Thanks for submitting this feature request 🚀 @melindaloubser1 will get back to you about it soon! ✨

**Comment by sahinbatmaz** [comment]
I have been thinking about the situation, in the question, I assumed that the bottleneck is processing the function on a token. I am also questioning this now. 

If it is the bottleneck, the proposed solution would work, if not, what can be the bottleneck?

For example, CountVectorizer layer takes around 2 minutes, so, LexicalSyntacticFeaturizer should also take similar duration.

**Comment by Ghostvv** [comment]
@alopez what is the status of this issue?
