### ISSUE TITLE
Openstack Swift object storage for models

### ISSUE THREAD

**Issue by Ezhvsalate** [RasaHQ/rasa#6407]
**Description of Problem**:
At current time [only three options](https://rasa.com/docs/rasa/user-guide/cloud-storage/) for Cloud Storage are available: AWS S3, GCS and Azure. 

**Overview of the Solution**:
I'd like to offer to add support for Openstack Swift storage.
[Openstack ](https://www.openstack.org/)is one of the most popular open source cloud solutions widely used in many oraganizations, so I think this feature will be in demand.

Please let me know if you like the idea. If so we will prepare a PR.

**Definition of Done**:
- [ ] Feature realized
- [ ] Tests are added
- [ ] Feature described the docs
- [ ] Feature mentioned in the changelog

**Comment by sara-tagger** [comment]
Thanks for submitting this feature request 🚀 @Ghostvv will get back to you about it soon! ✨

**Comment by wochinge** [comment]
hi @Ezhvsalate ,

thanks for your suggestion! We are currently discussing if this should be part of Rasa Open Source out-of-the-box or if it makes more sense to have it as an external library (similar as we are doing it for the [ali oss persistor here](https://github.com/RasaHQ/rasa/pull/6266)). Do you have any strong preferences about it?

**Comment by Ezhvsalate** [comment]
@wochinge I like the concept of modularity, but if you decide it should be in the main repository - also ok.

**Comment by wochinge** [comment]
@Ezhvsalate In line with the team I'd say it would be better to have this as separate library and then plug into Rasa Open Source as we are planning to do it for the ali oss persistor. Are you planning to do an implementation of it?

**Comment by Ezhvsalate** [comment]
@wochinge ok, I will implement that as a separate library after #6266 is merged.

**Comment by wochinge** [comment]
Amazing 👍 (cc @EmmaWightman )
