### ISSUE TITLE
Rename `Form` to `Loop` event

### ISSUE THREAD

**Issue by wochinge** [RasaHQ/rasa#6409]
As part of the `RulePolicy` refactoring, we introduced the concept of a `Loop` which represents conversation parts which are
* unfeaturized to ML policies
* which are driven by hardcoded rules / `if` and `else`s 

In contrast `Form`s to request information from the user and fill required slots.

This means every `Form` is a `Loop`, but not every `Loop` is a `Form`. E.g. the `TwoStageFallback` was implemented using the `Loop` concept but it's not a Form.

- [x] Rename the `Form` event to `Loop` event
- [x] make sure that old `Form` events can still be retrieved from the tracker stores
- [x] adapt Rasa X frontend
- [ ] ~adapt Rasa X backend `active_form`~ not required (the tests which involve this are commented out anyway)
- [x] [enable Rasa SDK to parse `active_loop` events](https://github.com/RasaHQ/rasa-sdk/pull/246)

**Comment by wochinge** [comment]
@mjaycub Do you know if there is any special handlings for Rasa Open Source `form` events in the frontend? `form` events are events like `user` or `bot`. Just a different type. I did a text search but couldn't find anything.

**Comment by wochinge** [comment]
Found these lines in the frontend, but that seems easy to handle: 
https://github.com/RasaHQ/rasa-x/blob/d7bc3df310f3804bbb87e9196857917ac776b17f/src/rasa-frontend/src/state/messages/reducer.ts#L81

**Comment by mjaycub** [comment]
@wochinge I can have a look tomorrow if you'd like, today is blocked up by IVC work

**Comment by wochinge** [comment]
That would be great. It's not critical but needs to be done for 2.0 compatibility.

**Comment by mjaycub** [comment]
@wochinge it doesn't look like we do anything special with `form` events, and we don't ever seem to use `active_form` at the moment. I think all we'll need to do is add a type for `LoopEvent` and make sure we update the `isEvent` check in `ConversationStoryViewer` ([here](https://github.com/RasaHQ/rasa-x/blob/6165b9e14854b419da4ef98646939588170de7e9/src/rasa-frontend/src/components/ConversationStoryViewer.tsx#L28)) to include a check for `loop`.

Will I open a PR with these changes?

**Comment by wochinge** [comment]
> Will I open a PR with these changes?

I don't know. Will you? 😄  I'd hold off a bit - could be that also rename `FormValidation`. I'll give you a heads up 👍

**Comment by mjaycub** [comment]
>  don't know. Will you? 😄

Haha, was just curious if you wanted to touch the frontend or if you wanted me to do it! 😄I can do it, just follow up when you thing it's time to do so 👍

**Comment by wochinge** [comment]
As part of the `Form` changes in Rasa X we also need to do the changes from renaming the `FormValidation` event (https://github.com/RasaHQ/rasa/issues/6463)

**Comment by mjaycub** [comment]
@wochinge @chkoss Since this issue is now closed, please keep me in the _loop_ as we will need to make some updates on the frontend if we rename!

**Comment by wochinge** [comment]
re-opening this. Doesn't make sense to close it at this stage 👍

**Comment by wochinge** [comment]
Feel free to wrap this up. Otherwise I can do it when I'm back.
