### ISSUE TITLE
Rasa X - Custom component should define "Trainable" property

### ISSUE THREAD

**Issue by hernanbari** [RasaHQ/rasa#6414]
**Description of Problem**: I created a custom extractor of entities, but rasa-x assumes they are from a “pre-trained model”. I guess it has something to do with the `rasa.nlu.constants.TRAINABLE_EXTRACTORS` variable. This means the entities can't be removed from the UI training data examples.

Rachael Tatman from the rasa team told me the following in the forum:

> Hi Hernan! It looks like this is a problem on our end. (Since an extractor in a custom component could be either pre trained or trainable and we currently don’t have a way to define which is which.) Would you mind filing an issue for this on GitHub?

**Overview of the Solution**: It should be possible to define if a custom component is pre-trained or not.

**Comment by sara-tagger** [comment]
Thanks for submitting this feature request 🚀 @erohmensing will get back to you about it soon! ✨

**Comment by TyDunn** [comment]
@wochinge Can you explain what change to Rasa X would be needed? Would a change to Rasa Open Source be required?

**Comment by wochinge** [comment]
Mhm, we'd need an index of entity types and whether they are trainable or not. Without having it checked in detail:
* Rasa Open Source needs to expose the information. I could imagine via model metadata (in the `.tar.gz`) or via API
* Rasa X needs to get the information + expose it via API to the frontend

**Comment by alexweidauer** [comment]
Thank you for raising this issue about Rasa X. We decided to stop supporting the Community Edition (free version) of ‘Rasa X’ (see more info here: https://rasa.com/blog/rasa-x-community-edition-changes/). That’s why we’ve closed your issue. We suggest that Rasa Enterprise customers raise the issue with our customer support team if they haven’t done so already.
