### ISSUE TITLE
New docs are not building on master after autodoc merge

### ISSUE THREAD

**Issue by m-vdb** [RasaHQ/rasa#6421]
Failing build: https://github.com/RasaHQ/rasa/runs/984998231?check_suite_focus=true

Seems to work locally after `make install install-docs`, but fails in CI.

**Comment by m-vdb** [comment]
worst-case: either revert or publish the docs from local.

**Comment by erohmensing** [comment]
@m-vdb i don't think commenting out autodoc is worst case -- not sure its ready yet anyway

**Comment by m-vdb** [comment]
I mean "worst case scenario, until we figure it out, we can disable autodoc". it's not that "worst"
