### ISSUE TITLE
Base Pipeline in Rasa Init with Rasa==2.0.0.a1 Comments Out `config.yml`

### ISSUE THREAD

**Issue by koaning** [RasaHQ/rasa#6424]
I'm playing around with Rasa==2.0.0.a1. This is what happens when you run `rasa init`. 

```
python -m rasa init
Welcome to Rasa! 🤖

To get started quickly, an initial project will be created.
If you need some help, check out the documentation at https://rasa.com/docs/rasa.
Now let's start! 👇🏽

? Please enter a path where the project will be created [default: current director
y] .
? Directory '/Users/vincent/Development/breakoutbot' is not empty. Continue?  Yes
Created project directory at '/Users/vincent/Development/breakoutbot'.
Finished creating project structure.
? Do you want to train an initial model? 💪🏽  Yes
Training an initial model...
The configuration for policies and pipeline was chosen automatically. It was written into the config file at './config.yml'.
Training NLU model...
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/Users/vincent/Development/breakoutbot/venv/lib/python3.7/site-packages/rasa/__main__.py", line 120, in <module>
    main()
  File "/Users/vincent/Development/breakoutbot/venv/lib/python3.7/site-packages/rasa/__main__.py", line 109, in main
    cmdline_arguments.func(cmdline_arguments)
  File "/Users/vincent/Development/breakoutbot/venv/lib/python3.7/site-packages/rasa/cli/scaffold.py", line 206, in run
    init_project(args, path)
  File "/Users/vincent/Development/breakoutbot/venv/lib/python3.7/site-packages/rasa/cli/scaffold.py", line 118, in init_project
    print_train_or_instructions(args, path)
  File "/Users/vincent/Development/breakoutbot/venv/lib/python3.7/site-packages/rasa/cli/scaffold.py", line 58, in print_train_or_instructions
    args.model = rasa.train(domain, config, training_files, output)
  File "/Users/vincent/Development/breakoutbot/venv/lib/python3.7/site-packages/rasa/train.py", line 58, in train
    nlu_additional_arguments=nlu_additional_arguments,
  File "uvloop/loop.pyx", line 1456, in uvloop.loop.Loop.run_until_complete
  File "/Users/vincent/Development/breakoutbot/venv/lib/python3.7/site-packages/rasa/train.py", line 114, in train_async
    nlu_additional_arguments=nlu_additional_arguments,
  File "/Users/vincent/Development/breakoutbot/venv/lib/python3.7/site-packages/rasa/train.py", line 207, in _train_async_internal
    old_model_zip_path=old_model,
  File "/Users/vincent/Development/breakoutbot/venv/lib/python3.7/site-packages/rasa/train.py", line 246, in _do_training
    additional_arguments=nlu_additional_arguments,
  File "/Users/vincent/Development/breakoutbot/venv/lib/python3.7/site-packages/rasa/train.py", line 541, in _train_nlu_with_validated_data
    **additional_arguments,
  File "/Users/vincent/Development/breakoutbot/venv/lib/python3.7/site-packages/rasa/nlu/train.py", line 75, in train
    trainer = Trainer(nlu_config, component_builder)
  File "/Users/vincent/Development/breakoutbot/venv/lib/python3.7/site-packages/rasa/nlu/model.py", line 142, in __init__
    components.validate_requirements(cfg.component_names)
  File "/Users/vincent/Development/breakoutbot/venv/lib/python3.7/site-packages/rasa/nlu/components.py", line 59, in validate_requirements
    f"Not all required importable packages are installed. "
Exception: Not all required importable packages are installed. To use this pipeline, you need to install the missing dependencies. Please install the package(s) that contain the module(s): spacy
```

When inspecting the `config.yml` I now see this; 

```yml
# Configuration for Rasa NLU.
# https://rasa.com/docs/rasa/nlu/components/
language: en

pipeline:
# # No configuration for the NLU pipeline was provided. The following default pipeline was used to train your model.
# # If you'd like to customize it, uncomment and adjust the pipeline.
# # See https://rasa.com/docs/rasa/nlu/choosing-a-pipeline/ for more information.
#   - name: SpacyNLP
#   - name: SpacyTokenizer
#   - name: SpacyFeaturizer
#   - name: RegexFeaturizer
#   - name: LexicalSyntacticFeaturizer
#   - name: CountVectorsFeaturizer
#   - name: CountVectorsFeaturizer
#     analyzer: char_wb
#     min_ngram: 1
#     max_ngram: 4
#   - name: DIETClassifier
#     epochs: 100
#   - name: EntitySynonymMapper
#   - name: ResponseSelector
#     epochs: 100

# Configuration for Rasa Core.
# https://rasa.com/docs/rasa/core/policies/
policies:
# # No configuration for policies was provided. The following default policies were used to train your model.
# # If you'd like to customize them, uncomment and adjust the policies.
# # See https://rasa.com/docs/rasa/core/policies/ for more information.
#   - name: MemoizationPolicy
#   - name: TEDPolicy
#     max_history: 5
#     epochs: 100
#   - name: MappingPolicy
#   - name: FormPolicy
```

This leaves me with the following;

1. It seems like we've introduce spacy to be part of the standard pipeline. If this is intentional then we should add it as a mandatory install when installing Rasa as opposed to an optional install. If it isn't intentional we should remove spaCy as a component from the standard pipeline. 
2. Do we want to comment out the `config.yml`? It's somewhat confusing to have a model commented out here while it is being used.

## Versions 

```
> rasa --version
Rasa Version     : 2.0.0a1
Rasa SDK Version : 2.0.0a1
Rasa X Version   : None
Python Version   : 3.7.7 (v3.7.7:d7c567b08f, Mar 10 2020, 02:56:16) 
Operating System : Darwin-19.3.0-x86_64-i386-64bit
Python Path      : /Users/vincent/Development/breakoutbot/venv/bin/python
```

**Comment by koaning** [comment]
One thing about the spaCy dependency as well. You might need to download a language model from spaCy as well if you'd like it to work. This can get the initial modelling pipeline to become somewhat heavy-weight.

**Comment by wochinge** [comment]
Thanks for checking out the alpha 👍 

1) is duplicate of https://github.com/RasaHQ/rasa/issues/6326
2) That's to indicate that it was injected by the auto config. Do you haev other ideas? And could you please rename the PR so it reflects that this only refers to part 2) ?

**Comment by koaning** [comment]
If it is injected by the auto config that's fine, but why add the comments? Commenting (be it `yml` or python) suggests to me that something has been turned off. I now see a config file where most of the settings seem turned off but is still able to generate a model during `rasa init`. That, at least to me, was confusing.

**Comment by wochinge** [comment]
What would be alternatives for you?
1) No comments at all: Confusing as the user doesn't know which config was used to train the model
2) Adding config without comments: We don't know if the config was suggested by Rasa Open Source or if they user supplied it. We need to know which one, as the former would mean we could replace it with better / other suggestions.

**Comment by koaning** [comment]
I might not have all the information that went into the decision making for the auto-config. But I wonder ... Why don't we have the auto-config generate a `config.yml` file? As in, the pipeline that is used to train the model when we run `rasa init`, why isn't that in the `config.yml` file that is generated?

**Comment by chkoss** [comment]
The main idea of the Suggested Config feature was that in the beginning users don't have to bother with the `config.yml`.

> If we already have an opinion of what the best pipeline is, why not place that as the configuration without commenting parts out?

This is what Tobias' point 2. in his last reply refers to. I'll try to explain it more:

If the Suggested Config feature would automatically generate a `config.yml` without commenting out the configuration, the generated file is indistinguishable from a `config.yml` that the user might have written themselves.
This would a problem when training new models later on: If the pipeline in the `config.yml` was provided by the user, we have to keep it and not overwrite it with any suggested configuration. But if the pipeline was automatically put there by the Suggested Config feature, we want to run this automation again every time a new model is trained (overwriting the result of the previous Suggested Config run), such that potential improvements to the suggested pipeline are automatically included.

Commenting the automatically suggested configuration out allows us to distinguish between these two cases.

> This sentence from the logs does suggest that we've got a working file that is generated.

Yes, and we do. The generated file works: With each `rasa train`, the Suggested Config is run again, so the training will automatically use our default pipeline (and write it into the `config.yml` as comments, overwriting the old comments).
