### ISSUE TITLE
ReminderScheduled gives “latest_input_channel”: null

### ISSUE THREAD

**Issue by slhhamed** [RasaHQ/rasa#6432]
**Rasa version**: V1.9.0 

**Rasa SDK version** (if used & relevant): V1.9.0 

**Python version**: 3.8

**Issue**:

I have a ReminderScheduled to start an intent on webchat (website) from the rasa logs and tracker, i can see clearly that everything works fine but i find out that it gives “latest_input_channel”: null , so no messages being shown on the webchat channel (socket.io)

**Error (including full traceback)**:
```
],
  "latest_input_channel": null,
  "active_form": {},
  "latest_action_name": "action_listen"
}
```

**Comment by sara-tagger** [comment]
Thanks for raising this issue, @Ghostvv will get back to you about it soon✨

###### Please also check out the [docs](https://rasa.com/docs/) and the [forum](https://forum.rasa.com/) in case your issue was raised there too 🤗
