### ISSUE TITLE
Exception: Not all required importable packages are installed. To use this pipeline, you need to install the missing dependencies. Please install the package(s) that contain the module(s): spacy

### ISSUE THREAD

**Issue by captionthis** [RasaHQ/rasa#6440]
**Rasa version**: 1.5.1

**Rasa SDK version** (if used & relevant): Latest Version of Rasa SDK

**Rasa X version** (if used & relevant): N/A

**Python version**: Python 3 (Specifically Python 3.7.5)

**Operating system** (windows, osx, ...): Windows

**Issue**: 
So I am receiving this error saying: Exception: Not all required importable packages are installed. To use this pipeline, you need to install the missing dependencies. Please install the package(s) that contain the module(s): spacy

The problem is I have installed, uninstalled, and reinstalled spacy multiple times using pip. I've also tried git cloning spacy to see if that would do anything but that doesn't seem to help at all either. 

I am currently using a virtual environment for my project where I am trying to install spacy.

I am following the Rasa Masterclass and I am currently on Episode 6 (using Rasa Masterclass GitHub: https://github.com/RasaHQ/rasa-masterclass/tree/master/episode6) and I believe the issue is coming from the config.yml file. The code for the config.yml file is pasted down below.

I would assume I am receiving the error I am getting because of the pretrained_embeddings_spacy.

Any help is appreciated. I'll try to respond as quickly as possible. 

Thank you!

**Error (including full traceback)**:
Exception: Not all required importable packages are installed. To use this pipeline, you need to install the missing dependencies. Please install the package(s) that contain the module(s): spacy

**Command or request that led to error**:
rasa train

**Content of configuration file (config.yml)** (if relevant):
language: en
pipeline: pretrained_embeddings_spacy

policies:
  - name: MemoizationPolicy
  - name: KerasPolicy
  - name: MappingPolicy

**Comment by sara-tagger** [comment]
Thanks for the issue, @degiz will get back to you about it soon!

###### You may find help in the [docs](https://rasa.com/docs/) and the [forum,](https://forum.rasa.com/) too 🤗

**Comment by Dustyposa** [comment]
You can try  with `python -m pip install spacy`

**Comment by captionthis** [comment]
> You can try with `python -m pip install spacy`

Thank you for the quick reply @Dustyposa! After running that command and running rasa train, it still seems to throw up the same error.

Error:
Exception: Not all required importable packages are installed. To use this pipeline, you need to install the missing dependencies. Please install the package(s) that contain the module(s): spacy

**Comment by captionthis** [comment]
If anything, I would be totally fine with using an alternative pipeline if anyone has any recommendations. I'm not totally familiar with rasa and their pipelines so if worse comes to worst and spacy doesn't work out, I'd be totally fine with choosing an alternative.
