### ISSUE TITLE
Release github action step failing on collection of Release Notes

### ISSUE THREAD

**Issue by mprazz** [RasaHQ/rasa#6442]
**Rasa version**: 2.0.0a2

**Issue**:
Alpha release build failed on the very last step, error was related to collecting release notes.
Full conversation [here](https://rasa-hq.slack.com/archives/C36SS4N8M/p1597740518216100).

**Error (including full traceback)**:
```

```

**Command or request that led to error**:
```

```

**Comment by mprazz** [comment]
Managed to find the error via email notifications!
![image](https://user-images.githubusercontent.com/23500620/90496952-c3f82000-e146-11ea-8700-547546e3f3a1.png)

**Comment by m-vdb** [comment]
From Tom:

> yes the release script doesn't run towncrier for alpha releases which means they do not appear in the changelog, which means the publish_gh_rekease_notes.py script failes since the changelog section it is trying to find does not exist
