### ISSUE TITLE
How to use SpacyNLP: Language(korean) not officially supported by spacy

### ISSUE THREAD

**Issue by JangDaehyuk** [RasaHQ/rasa#6448]
**Rasa version**:  1.10.7

**Rasa SDK version** (if used & relevant): 1.10.2

**Rasa X version** (if used & relevant): not use 

**Python version**: 3.6.10

**Operating system** (windows, osx, ...): Ubuntu 

**Issue**:

hi, **i want to use SpacyNLP**. My Language Korean is not supported by Spacy. but, spacy official document says that If some libraries are installed, they can be used. so, i can use mecab library with spacy.blank.

spacyNLP uses spacy.load method not blank method. i changed " def load_model " in "spacy_utils.py ".

The sentence below is the part of the code I modified. You can focus on ->.

return spacy.load(spacy_model_name, disable=[“parser”]) -> return spacy.blank(spacy_model_name)

Then the following error occurs:

Exception: Failed to load spacy language model for lang ‘ko’. Make sure you have downloaded the correct model (https://spacy.io/docs/usage/).

I think when I modify code to use spacynlp, there is a part that I need to modify more. I don’t know where it is.

![rasa_question_spacynlp](https://user-images.githubusercontent.com/49027524/90594553-a8b01200-e225-11ea-99c6-acede7e71378.png)

**Comment by sara-tagger** [comment]
Thanks for the issue, @tmbo will get back to you about it soon!

###### You may find help in the [docs](https://rasa.com/docs/) and the [forum,](https://forum.rasa.com/) too 🤗
