### ISSUE TITLE
Add to the TRAIN API the chance to train also based on files on local file system and not only from data passed through POST

### ISSUE THREAD

**Issue by gioppoluca** [RasaHQ/rasa#6450]
**Description of Problem**:
I've looked at them but I want rasa to work with files that I have already on the server (and could get changed from outside)
sending this command:
```
curl --location --request POST 'http://localhost:5005/model/train?token=thisismysecret' \
--header 'Content-Type: application/json' \
--data-raw '{"config": "language: en\r\npipeline:\r\n  - name: WhitespaceTokenizer\r\n  - name: LexicalSyntacticFeaturizer\r\n  - name: CountVectorsFeaturizer\r\n    token_pattern: (?u)\b\w+\b\r\n  - name: DucklingHTTPExtractor\r\n    url: http://duckling_server:8000\r\n    dimensions:\r\n      - number\r\n  - name: DIETClassifier\r\n    epochs: 100\r\n  - name: EntitySynonymMapper\r\n  - name: ResponseSelector\r\n    epochs: 100\r\npolicies:\r\n  - name: FallbackPolicy\r\n  - name: MemoizationPolicy\r\n  - name: FormPolicy\r\n  - name: MappingPolicy\r\n  - name: TEDPolicy\r\n    max_history: 5\r\n    epochs: 100  "}'
```
but get this error:
```
{
    "version": "1.10.10",
    "status": "failure",
    "message": "To train a Rasa model you need to specify at least one type of training data. Add nlu and/or stories to the request.",
    "reason": "BadRequest",
    "details": {
        "parameters": [
            "nlu",
            "stories"
        ],
        "in": "body"
    },
    "help": null,
    "code": 400
}
```
so even if the only required parameter is config it seems that rasa do not like to work on files it already has in the folders but pretend to receive a BIG json post that for me could be impractical
is there a way to force rasa to work with stuff it finds in the /app folder?
seems there is no way to reproduce the "-train" command

It seems that the server.py pretends to write the yaml or JSON content in temporary files and than train over those.

That is fine, but there is no options for using files in the rasa local file system as a common "--train" command thus the "training_files" array parameter get initialized with the tmp folder and not with the /app/data
any way to use the "importers" to have a workaround?

**Overview of the Solution**:
There could be an option for passing either a boolean that instruct the API to go on as now so expect the data in the post or go with the existing config and default data like the way that "--train" behave

The reason for this features is that we could have BIG files generated outside RASA and a shared FS between RASA and the other parts of the system and periodically files gets updated due to external processes and stories could become updated or chenged and we want to retrain the bot, but sometimes data could be too much (consider that now we need to generate a BIG JSON text to POST to the API and this could be a problem (apart from having to escape the YAML content and place it inside the JSON that is not so straightforward)

**Comment by sara-tagger** [comment]
Thanks for submitting this feature request 🚀 @tabergma will get back to you about it soon! ✨

**Comment by federicotdn** [comment]
Hi @gioppoluca, I think what you explained makes sense. Given all the options that are available for training (`rasa train --help`), which ones do you think the API should offer?

**Comment by gioppoluca** [comment]
Even if the simple train command could do since the main use case should at least be able to work in a configuration with default settings it could be useful to send (still optionally) --data, -c, -d, --out to give the option of managing locations that differ from the default.
Personally never user any of the various options but in this use case probably --augmentation could have some use; --fixed-model-name could also be useful unless the return of the train is a json with the model name.
In that case this option is useless since in the use case it is needed to reload the model in any case so once you have the new name there is already the API for doing that job and so having a fixed model name is not immediately useful (unless you are lazy and do not want to get the result of the return and use always the same reload command.
All the others do not seems to be immediately useful since the use case is a production like situation where you could have the training files changed from new data coming from the DB and you need to retrain the bot based on that data so having a debug should not too much useful.

**Comment by gioppoluca** [comment]
Any news on this?

**Comment by tabergma** [comment]
@gioppoluca Thanks for you input!

@federicotdn Should we add this to the production squad board?

**Comment by federicotdn** [comment]
We can add it but I don't think it will be tackled soon due to other existing priorities. @gioppoluca would you be interested in creating a PR for this feature?

**Comment by gioppoluca** [comment]
I can try to involve some colleagues in helping out

**Comment by wochinge** [comment]
Closing this as accessing arbitrary locations on the server file system would be security risk. Please consider opening a new issue for providing paths to training data / config to remote via query param or something similar.
