### ISSUE TITLE
Verify Rasa Open Source End-to-End behavior in Rasa X

### ISSUE THREAD

**Issue by wochinge** [RasaHQ/rasa#6455]
Rasa Open Source introduces a new feature for end-to-end user and bot utterances. It's an experimental feature which doesn't require support within Rasa X. However, we still need to verify that it doesn't break anything within Rasa X, e.g.

*   training
*   end-to-end utterances aren't added to the domain

**Comment by ricwo** [comment]
@alwx I'm on it now

**Comment by alexweidauer** [comment]
Thank you for raising this issue about Rasa X. We decided to stop supporting the Community Edition (free version) of ‘Rasa X’ (see more info here: https://rasa.com/blog/rasa-x-community-edition-changes/). That’s why we’ve closed your issue. We suggest that Rasa Enterprise customers raise the issue with our customer support team if they haven’t done so already.
