### ISSUE TITLE
DIET has problems with word embeddings !!

### ISSUE THREAD

**Issue by sahinbatmaz** [RasaHQ/rasa#6461]
**Rasa version**: 1.10.10

**Python version**: 3.7

**Operating system** (windows, osx, ...): Ubuntu

**Issue**: Adding word vectors in a layer before classifier is problematic in terms of memory. Word embeddings should be taken into memory in each batch. For example in SpacyFeaturizer, when word embeddings for all words for all data is loaded in the memory. This is a huge problem when the training dataset is large. The classifier model, DIET, must have an embedding layer that loads embeddings in each batch.

Additionally, DIET should have an embedding layer that can train vectors from scratch.

This embedding layer must be placed before the transformer layers. I dont really understand why there is an embedding layer after transformer layers.

**Comment by sara-tagger** [comment]
Thanks for raising this issue, @erohmensing will get back to you about it soon✨

###### Please also check out the [docs](https://rasa.com/docs/) and the [forum](https://forum.rasa.com/) in case your issue was raised there too 🤗

**Comment by Ghostvv** [comment]
> This embedding layer must be placed before the transformer layers.

there is an embedding layer before transformer, that effectively trains embeddings from scratch if you use `CountVectorsFeaturizer`

> The classifier model, DIET, must have an embedding layer that loads embeddings in each batch.

we are working on this enhancement

**Comment by sahinbatmaz** [comment]
> there is an embedding layer before transformer, that effectively trains embeddings from scratch if you use CountVectorsFeaturizer

You are right. I know that there is a dense layer after sparse features, but I didn't realize that the layer acts as an embedding layer.

> The classifier model, DIET, must have an embedding layer that loads embeddings in each batch.
we are working on this enhancement

I am looking forward for this feature. Thanks a lot.

**Comment by sahinbatmaz** [comment]
I have also another question. 
From my understanding, DIETClassifier process features like following;

```
Dense( Dense(SparseFeatures), DenseFeatures )
Transformer Layers
Embedding Layer for Label Classification
```

The Dense layer on SparseFeatures works as an embedding layer for tokens.

What is the meaning of the other Dense layer on top of Dense(SparseFeatures) and DenseFeatures ? 

And, if I want to remove this layer, I want to be able to remove it from config file, but the layer must exist for now.

Thanks.

**Comment by Ghostvv** [comment]
which one is the dense layer between transformer and concatenation on dense and sparse features?

**Comment by wochinge** [comment]
@Ghostvv Can this issue be closed?

**Comment by Ghostvv** [comment]
I don't know. Partial dataset loading for large data is not implemented yet
