### ISSUE TITLE
Document Keras-Policy as deprecated

### ISSUE THREAD

**Issue by N-Olbert** [RasaHQ/rasa#6462]
Rasa version: 1.10.10

Python version: 3.7

It is mentioned nowhere in the documentation that the kerase policy is deprecated, see https://rasa.com/docs/rasa/core/policies/#keras-policy 

Evaluating the keras policy leads to a deprecation message
![image](https://user-images.githubusercontent.com/45466413/90860752-de224000-e38a-11ea-88b6-48f053e72e0b.png)

Change was introduced by https://github.com/RasaHQ/rasa/pull/5255

**Comment by koaning** [comment]
We're redoing out docs for Rasa 2.0 and this is something that will be taken into account/fixed there. One thing I wonder, did you ge the `KerasPolicy` after running `rasa init`?

**Comment by N-Olbert** [comment]
> We're redoing out docs for Rasa 2.0 and this is something that will be taken into account/fixed there. One thing I wonder, did you ge the `KerasPolicy` after running `rasa init`?

No. I was plaing around with testing an assistant. Under https://rasa.com/docs/rasa/user-guide/testing-your-assistant/#comparing-core-configurations where it was stated that 
`To compare single policies create config files containing only one policy each. If you’re not sure which policies to compare, we’d recommend trying out the EmbeddingPolicy and the KerasPolicy to see which one works better for you.`, ofc.  this documentation is also deprecates, as EmbeddingPolicy is superseded by TEDPolicy.

I just was confused because v2.0 is already in an early alpha stage and the message indicates the KerasPolicy will be gone with v2.0.
