### ISSUE TITLE
Rename `FormValidation` event to something "loop" related

### ISSUE THREAD

**Issue by wochinge** [RasaHQ/rasa#6463]
Follow up from https://github.com/RasaHQ/rasa/issues/6409 and PR https://github.com/RasaHQ/rasa/pull/6439 .

Same as we re-named the `Form` event, we should also re-name the `FormValidation` event.

**Todos**
- [x] do the same for `FormValidation` as for `Form` in https://github.com/RasaHQ/rasa/pull/6439
- [x] do the same for `FormValidation` as for `Form` in the SDK (see thisPR https://github.com/RasaHQ/rasa-sdk/pull/246)

@Ghostvv @akelad Please fire away with naming suggestions. As we don't validate after a `Loop` was re-called after an unhappy path, it makes sense to call it something like `LoopExecutionAfterUnhappyPath`?

**Comment by wochinge** [comment]
@alwx Did you continue working on this? @akelad Do you have some new name suggestions? 👀

**Comment by Ghostvv** [comment]
if you look at `loops` they don't have validation idea inside them. so technically, Akela's suggestion `LoopExecutionAfterUnhappyPath` is correct 😅😇

**Comment by wochinge** [comment]
It was mine :-D Akela was `unhappy`. How about shortening it to `LoopUnhappyPath`? We might be able to drop this event anyway once we figured out the end-to-end problems for policy predictions.

**Comment by Ghostvv** [comment]
`LoopUnhappyPath` hm... smth about it is not intuitive, but cannot formulate what

**Comment by akelad** [comment]
yeah `LoopUnhappyPath` doesn't sound right. What's the reason for not calling it `LoopValidation` again? From what I understand the event gets added to the tracker as `FormValidation(False)` when the user "breaks out" of a form/loop right? `LoopUnhappyPath(False)` seems like that would be wrong 😅

**Comment by Ghostvv** [comment]
`FormValidation(False)` is added when a form is predicted after a user input that is the answer to a previous question:
```
- utter_ask_continue
* affirm
- FormValidation(False)
- q_form
```
but not here:
```
- utter_ask_continue
* inform
- q_form
```

**Comment by Ghostvv** [comment]
the problem that currently the implementation of the `Loop` doesn't have the notion of `validation`

**Comment by akelad** [comment]
yeah that part I know. 
> the problem that currently the implementation of the Loop doesn't have the notion of validation

as in, Loop doesn't, but Forms do right?

**Comment by Ghostvv** [comment]
yes

**Comment by akelad** [comment]
so why is the event needed for the Loop at all?

**Comment by Ghostvv** [comment]
because there is no form in tracker, rule policy, etc anymore. and this event will be added for loops as well, which a custom loop could use, however it wants

**Comment by akelad** [comment]
yeah but it does nothing for the Loop right now right? Kind of makes it hard to name it anything at all 😂

**Comment by wochinge** [comment]
Love the discussion 🎉 

> How about we keep it FormValidation for now, until we figure out tracker problems?

I suggest to do that. There are more important things to do the for the RC at the moment and the event name is not user facing which means we can still do this down the road.

**Comment by akelad** [comment]
haha yeah for sure, but doesn't hurt to keep the discussion going if someone has a genius idea

**Comment by wochinge** [comment]
So, what's the state on this? Happy to jump on a 5 minute call to resolve this. 

> What's the reason for not calling it LoopValidation again? From what I understand the event gets added to the tracker as FormValidation(False) when the user "breaks out" of a form/loop right? LoopUnhappyPath(False) seems like that would be wrong 😅

yes,  but it might be used in other cases in the future and that's why a general solution makes more sense imo.

**Comment by wochinge** [comment]
Ok @Ghostvv @akelad .
Sorry to push but this blocks Rasa Open Source and Rasa X:

Candidates:
- `LoopUnhappyPath`
- `LoopValidation`

Candidates I could also imagine:
- `LoopBreak` 
- `LoopExemption` 

I'll move forward implementing it using the name `LoopUnhappyPath` tomorrow in case we can't agree on another name by then.

**Comment by akelad** [comment]
What about `LoopInterruption`? but then I guess the event would be `LoopInterruption(True)` rather than `LoopInterruption(False)`? Otherwise it sounds wrong. If we don't wanna switch around the True/False parameters though I would prob just stick with `Validation`?

**Comment by wochinge** [comment]
I like `LoopInterruption`. Gonna use that  then. I can swap the `true/false` stuff when deprecating the `FormValidation` event. Let's hear if Vova has strong feelings against this tomorrow and then we use `LoopInterruption`

**Comment by Ghostvv** [comment]
this event is added before returning to the loop, and is used to notify the loop that it is called after interruption. maybe `LoopInterrupted(true)` then?

**Comment by akelad** [comment]
Yes that’s even better!
