### ISSUE TITLE
Fix `import_time` test

### ISSUE THREAD

**Issue by chkoss** [RasaHQ/rasa#6473]
There are two issues with the `import_time` test:
- The test is not executed by the CI, because the file is named `import_time.py` instead of `test_import_time.py`
- It fails: average import time is something around 0.7-1 s, while the test has `MAX_IMPORT_TIME_S = 0.3`

So probably we should adjust `MAX_IMPORT_TIME_S` to match reality - there is a comment saying that the 0.3 refer to running on a Travis VM.

**Comment by sara-tagger** [comment]
Thanks for the issue, @Ghostvv will get back to you about it soon!

###### You may find help in the [docs](https://rasa.com/docs/) and the [forum,](https://forum.rasa.com/) too 🤗

**Comment by sara-tagger** [comment]
Thanks for the issue, @melindaloubser1 will get back to you about it soon!

###### You may find help in the [docs](https://rasa.com/docs/) and the [forum,](https://forum.rasa.com/) too 🤗

**Comment by melindaloubser1** [comment]
@chkoss I'ma leave sara's tag up for now just so she doesn't tag again =)

**Comment by chkoss** [comment]
@melindaloubser1 This issue should be in the Production Inbox. For me it says "Projects: None", but that might just be because of missing board viewing permissions? If it's not in the board, can you please move it there?

**Comment by melindaloubser1** [comment]
No worries, it's in the right board =)

**Comment by m-vdb** [comment]
@federicotdn it looks like your were the one who created [this test](https://github.com/RasaHQ/rasa/blob/master/tests/import_time.py). Would it make sense for you to take this task over? It shouldn't be too hard to adapt the constant to make it work on GitHub VMs?

**Comment by federicotdn** [comment]
Given all the changes to Rasa OSS and our CI since October last year, this test is probably not relevant anymore. We could delete it even, or raise the max time to a much larger number.

**Comment by m-vdb** [comment]
do you know why we created the test in the first place?

**Comment by federicotdn** [comment]
It was around when we started looking into optimizing imports. If I remember we looked into that again recently (not me), but I am not sure what the output of that was.

**Comment by m-vdb** [comment]
Moving this to Future for now 👍
