### ISSUE TITLE
Update "migrate from" code to match any updates to training data formats

### ISSUE THREAD

**Issue by akelad** [RasaHQ/rasa#6474]
There have been a few changes/updates to some of (or maybe all of) the platforms we offer migrations from:
- [ ] Dialogflow
- [ ] wit.ai
- [ ] LUIS
- [x] IBM Watson (already ticked because we just have a docs page for this, and not an actual converter)

For Rasa 2.0 these should be updated both to convert to the new yaml training data (unsure if that's already done), and also to read any new training data formats from these platforms.

Things that need to be done: 
- [ ] investigate which platforms have made changes to their platform and/or training data format (i'm pretty sure both wit.ai + LUIS at least have)
- [ ] implement updates to our converters
- [ ] update the documentation

**Comment by TyDunn** [comment]
@akelad The @RasaHQ/production-engineers were asking if your team has bandwidth to take this on. Maybe it could be a joint effort? For example, someone on your team could handle investigate the changes to to other platforms and update the documentation, while someone on the production squad updates the converters

**Comment by akelad** [comment]
@RasaHQ/cseteam thoughts? I'm not so sure about bandwidth, there's a lot of docs stuff going on still as well.

**Comment by melindaloubser1** [comment]
I'm not so sure about bandwidth either tbh

**Comment by wochinge** [comment]
@TyDunn I think this is a @RasaHQ/loop-squad topic as it's related to the training data.

**Comment by TyDunn** [comment]
@wochinge The loop squad has a lot going on right now to make Rasa X compatible. If the production squad has bandwidth, then I think we should pick it up

**Comment by wochinge** [comment]
We moved this to 2.1 as no squad has the bandwidth for it. Do you have strong objections @akelad ? I know it's not ideal but the only alternative would be to push the release.

**Comment by TyDunn** [comment]
@wochinge [We agreed to this on Slack](https://rasa-hq.slack.com/archives/C7B08Q5FX/p1601283529042500)

**Comment by wochinge** [comment]
Ok, let's discuss these things on issues 👍

**Comment by TyDunn** [comment]
@RasaHQ/cseteam @RasaHQ/production-engineers @m-vdb  I split the work between squads. CSE will investigate what we need to do update the convertors and docs, so that production squad can make the necessary updates to the convertors. Before we ship, we will need one of the two teams to update the docs

**Comment by akelad** [comment]
@TyDunn should this issue be closed then since we have other issues?

**Comment by TyDunn** [comment]
@akelad Let's keep this as an umbrella ticket that we close once all three sub-issues are complete
