### ISSUE TITLE
Proposal to change training data format for ResponseSelector

### ISSUE THREAD

**Issue by dakshvar22** [RasaHQ/rasa#6480]
Currently, a simple assistant with one retrieval intent `chitchat` using the `ResponseSelector` has files like these - 

nlu.yml
```
- intent: chitchat/ask_name
  examples: |
    - What is your name?
    - May I know your name?
    - What do people call you?
    - Do you have a name for yourself?

- intent: chitchat/ask_weather
  examples: |
    - What's the weather like today?
    - Does it look sunny outside today?
    - Oh, do you mind checking the weather for me please?
    - I like sunny days in Berlin.
```

responses.yml
```
responses:
  chitchat/ask_name:
  - image: "https://i.imgur.com/zTvA58i.jpeg"
    text: hello, my name is retrieval bot.
  - text: Oh yeah, I am called the retrieval bot.

  chitchat/ask_weather:
  - text: Oh, it does look sunny right now in Berlin.
    image: "https://i.imgur.com/vwv7aHN.png"
  - text: I am not sure of the whole week but I can see the sun is out today.
```

domain.yaml
```
intents:
    - chitchat
actions:
    - respond_chitchat
```

You can define a rule to trigger the action in rules.yml
```
- rule: Response with a chitchat utterance whenever user indulges in some chitchat
  steps:
  - intent: chitchat
  - action: respond_chitchat
```

There are two additional concepts we introduce here - 
1. Special actions with the prefix `respond_`.
2. Response templates not using the same `utter_` prefix that any other template would use.

From an implementation standpoint, the above two points are not strictly necessary to enforce. So the training data could also look like - 

nlu.md
```
- intent: chitchat/ask_name
  examples: |
    - What is your name?
    - May I know your name?
    - What do people call you?
    - Do you have a name for yourself?

- intent: chitchat/ask_weather
  examples: |
    - What's the weather like today?
    - Does it look sunny outside today?
    - Oh, do you mind checking the weather for me please?
    - I like sunny days in Berlin.
```

responses.yaml - 
```
responses:
  utter_chitchat/ask_name:
  - image: "https://i.imgur.com/zTvA58i.jpeg"
    text: hello, my name is retrieval bot.
  - text: Oh yeah, I am called the retrieval bot.

  utter_chitchat/ask_weather:
  - text: Oh, it does look sunny right now in Berlin.
    image: "https://i.imgur.com/vwv7aHN.png"
  - text: I am not sure of the whole week but I can see the sun is out today.
```

domain.yaml
```
intents:
    - chitchat
actions:
    - utter_chitchat
```

rules.yml
```
- rule: Response with a chitchat utterance whenever user indulges in some chitchat
  steps:
  - intent: chitchat
  - action: utter_chitchat
```

We should choose the format which seems intuitive for the developers to work with.

**Comment by JulianGerhard21** [comment]
Hi @dakshvar22 ,

I would definitely welcome these changes. 

Of course, it often makes sense to **separate responsibilities** in a file-driven system - as happened for example in the separate markdown file. 

On the other hand, there is already a logic that deals with the **centralization** of content data (`domain.yml`), including intents, actions and responses. In my opinion it makes sense to include the ResponseSelector responses in the domain file, if only for the sake of clarity. I guess that especially for beginners it makes sense to be able to handle as many things as possible in one place - unless there is an absolute necessity for a separation.
The same applies to the transformation of the key `respond_` to `utter_` following the fact that there is already the convention that statements made by a bot are called `utterances`, e.g. in the `Form` logic.

Just my quick thoughts on this. Hope it helps.

Kind regards
Julian

**Comment by akelad** [comment]
> Should we move response templates of retrieval intents to domain file?

I thought that was already the case in the new yaml format?

> Should we rename retrieval actions to have the same utter_ prefix?

Yeah that probably makes sense

> Should we use utter_ prefix for the keys of response templates as well as the example in the issue shows?

Also yes

Adding the utter_chitchat to the actions list isn't actually necessary btw
```
intents:
    - chitchat
actions:
    - utter_chitchat
```

Overall I think these changes make sense.

**Comment by dakshvar22** [comment]
@akelad 
> I thought that was already the case in the new yaml format?
I thought so too, but it isn't implemented that way yet. The response templates in the domain file are not present in the NLU training data and vice-versa.

Thanks for the other comments! 👍

**Comment by akelad** [comment]
this is how it's designed here: https://www.notion.so/rasa/Training-data-format-80c786f1996f491dbda0e095debc85fe
so I guess it's currently actually not intended to go into the domain, but be it's own thing. cc @degiz

**Comment by rgstephens** [comment]
> Adding the utter_chitchat to the actions list isn't actually necessary btw

Then let's not recommend it

When I first started using Rasa, I found the domain.yml frustrating because if felt like I have to duplicate a lot of information that I've already provided in the training data.

Isn't it the case the I can put everything in a single file under 2.0 if that's my preference.

chitchat.yml:

```
rules:
- rule: Response with a chitchat utterance whenever user indulges in some chitchat
  steps:
  - intent: chitchat
  - action: utter_chitchat

nlu:
- intent: chitchat/ask_name
  examples: |
    - What is your name?
    - May I know your name?
    - What do people call you?
    - Do you have a name for yourself?

- intent: chitchat/ask_weather
  examples: |
    - What's the weather like today?
    - Does it look sunny outside today?
    - Oh, do you mind checking the weather for me please?
    - I like sunny days in Berlin.

responses:
  utter_chitchat/ask_name:
  - image: "https://i.imgur.com/zTvA58i.jpeg"
    text: hello, my name is retrieval bot.
  - text: Oh yeah, I am called the retrieval bot.

  utter_chitchat/ask_weather:
  - text: Oh, it does look sunny right now in Berlin.
    image: "https://i.imgur.com/vwv7aHN.png"
  - text: I am not sure of the whole week but I can see the sun is out today.
```
