### ISSUE TITLE
adjust suggested pipeline as soon as `tensorflow-text` supports Windows

### ISSUE THREAD

**Issue by chkoss** [RasaHQ/rasa#6482]
Once `tensorflow-text` supports Windows, we should
- add it as a dependency on Windows, too = remove [this marker](https://github.com/RasaHQ/rasa/blob/0c34ff75ff016509b472390adecbe5d0eec0140c/pyproject.toml#L170)
- change the autoconfiguration to suggest the same pipeline for Windows as for other operating systems = remove [this if-case](https://github.com/RasaHQ/rasa/blob/0c34ff75ff016509b472390adecbe5d0eec0140c/rasa/importers/autoconfig.py#L90)

Currently blocked by this issue: https://github.com/tensorflow/text/issues/44

**Comment by sara-tagger** [comment]
Thanks for submitting this feature request 🚀 @tabergma will get back to you about it soon! ✨

**Comment by sara-tagger** [comment]
Thanks for submitting this feature request 🚀 @JustinaPetr will get back to you about it soon! ✨

**Comment by chkoss** [comment]
Can't prevent Sara from tagging people... 😭 @JustinaPetr please ignore, it's a Production Team issue for the future.

**Comment by wochinge** [comment]
Closing this as we now have one config for all OSes which doesn't user convert.
