### ISSUE TITLE
Include version number in example bots' training data files

### ISSUE THREAD

**Issue by chkoss** [RasaHQ/rasa#6483]
We want to encourage users to include version numbers in their training data files, or at least be aware of the format version. This will help them debug if format changes in the future break things for them.

So, to provide a good example and follow our own best practices, it would be good to include the version in our example bots, too.

(see also the discussion in issue https://github.com/RasaHQ/rasa/issues/6361)

**Comment by chkoss** [comment]
@RasaHQ/cseteam That's probably an issue for you? Otherwise, just move it to one of the squad's boards.

**Comment by akelad** [comment]
hm, how are we going to make sure that's always kept up to date though?

**Comment by chkoss** [comment]
It only needs to be adjusted when the training data format changes and the training data of an example is adjusted, too. If the Rasa Open Source versions progress (e.g. 2.0.1 etc.) and the examples still say `version = 2.0.0` that's no problem and won't even raise a warning.

**Comment by akelad** [comment]
ok sounds good, we can do that

**Comment by akelad** [comment]
@RasaHQ/cseteam any volunteers? should be a quick one

**Comment by b-quachtran** [comment]
✋ I got it
