### ISSUE TITLE
Rename `templates` to `responses` in Rasa Open Source

### ISSUE THREAD

**Issue by chkoss** [RasaHQ/rasa#6484]
Rasa renamed the `templates` in the domain to `responses`.

In Rasa X, we've renamed all related functions, variables, API responses etc. accordingly (https://github.com/RasaHQ/rasa-x/issues/1945). We should do the same for Rasa Open Source.

**Comment by sara-tagger** [comment]
Thanks for the issue, @amn41 will get back to you about it soon!

###### You may find help in the [docs](https://rasa.com/docs/) and the [forum,](https://forum.rasa.com/) too 🤗

**Comment by sara-tagger** [comment]
Thanks for raising this issue, @erohmensing will get back to you about it soon✨

###### Please also check out the [docs](https://rasa.com/docs/) and the [forum](https://forum.rasa.com/) in case your issue was raised there too 🤗

**Comment by yennycheung** [comment]
@wochinge: I took a quick look at this. It seems like we need to do a lot of changes. Could I get your help next week to walk through the code base to get some hints on which part of it needs to be renamed?

**Comment by wochinge** [comment]
@yennycheung Sure! Just send me an invite!

**Comment by yennycheung** [comment]
@wochinge, thanks, will do when I get stuck! Meanwhile, I'm trying to narrow the changes down to some flows to make the tests pass.
