### ISSUE TITLE
Raise proper user warnings for backwards compatibility code

### ISSUE THREAD

**Issue by m-vdb** [RasaHQ/rasa#6487]
([Original slack thread](https://rasa-hq.slack.com/archives/C36SS4N8M/p1598437115179100))

Looking for "compatibility" in the codebase shows several examples of code that are still here for backwards compatibility purposes (until when?) but the users are not warned about them. If possible, we should introduced warnings for each of these communicate that they'll be removed in Rasa 3.0

List of things to address:
- [in rasa.model_testing](https://github.com/RasaHQ/rasa/blob/ac1197b3f80071bb213d4fa66d5d24b4fc01e30e/rasa/model_testing.py#L130-L131)
- [in rasa.model_training](https://github.com/RasaHQ/rasa/blob/ac1197b3f80071bb213d4fa66d5d24b4fc01e30e/rasa/model_training.py#L54-L55)
- [in rasa.cli.x](https://github.com/RasaHQ/rasa/blob/ac1197b3f80071bb213d4fa66d5d24b4fc01e30e/rasa/cli/x.py#L506-L515)
- [in rasa.core.utils](https://github.com/RasaHQ/rasa/blob/ac1197b3f80071bb213d4fa66d5d24b4fc01e30e/rasa/core/utils.py#L22)
- [in rasa.core.events](https://github.com/RasaHQ/rasa/blob/ac1197b3f80071bb213d4fa66d5d24b4fc01e30e/rasa/shared/core/events.py#L254-L261)

**Comment by wochinge** [comment]
@m-vdb I remember you did some changes for this - can this issue be closed?

**Comment by m-vdb** [comment]
no I haven't done anything for this. If you search "compatibility" in all the python files, you'll see examples of code that is backwards compatible, but it's not clear if some of these should actually be deprecated. My reasoning is that we can only keep backward compatibility for so long, so we might as well tell users things are deprecated as soon as we can? What do you think?

**Comment by wochinge** [comment]
Fully agree 👍🏻
