### ISSUE TITLE
rasa concurrency requests per second

### ISSUE THREAD

**Issue by govindegowda** [RasaHQ/rasa#6490]
Hi Team,

We were running performance test on chat bot, which make use of rasa as nlp. when we ran with 10 request per second error rate is 0% and gradually it increases when requests per seconds increases. Could you please let us know solution for below list of queries.  
Queries:
1. What is the min and max concurrent request per second rasa nlp can process.
2. Any solution to increase performance of rasa nlp.
3. Is their any rasa nlp limitations, and probable solutions.

regards,
Govinde Gowda CM

**Comment by sara-tagger** [comment]
Thanks for raising this issue, @akelad will get back to you about it soon✨

###### Please also check out the [docs](https://rasa.com/docs/) and the [forum](https://forum.rasa.com/) in case your issue was raised there too 🤗

**Comment by akelad** [comment]
Hi @govindegowda please ask these types of questions in our community [forum](https://forum.rasa.com) and someone will get back to you there.
