### ISSUE TITLE
different models for the same data

### ISSUE THREAD

**Issue by Asma-droid** [RasaHQ/rasa#6491]
Hi,

I would like to highlight a big difference between nlu models when the the first one tis rained with image dockers and rasa HTTP API (i.e. same data, same config, same domain) and the second one trained using command line.

When evaluation data the first model gives high performance
![image](https://user-images.githubusercontent.com/55100050/91314845-4754e980-e7b7-11ea-9e93-7456eb583068.png)

The second one gives 143 wrong prediction for 361 requested test intents.
 

Remark: I am using rasa version 1.10.8 but i still have the same remark for the other rasa version.

Any help please,

**Comment by sara-tagger** [comment]
Thanks for raising this issue, @amn41 will get back to you about it soon✨

###### Please also check out the [docs](https://rasa.com/docs/) and the [forum](https://forum.rasa.com/) in case your issue was raised there too 🤗
