### ISSUE TITLE
Categorical Slots cause "InvalidDomain" error if only the NLG Section changed.

### ISSUE THREAD

**Issue by AljoschaN** [RasaHQ/rasa#6495]
**Rasa version**: 
First seen on 1.10.3 then updated rasa and reproduced the error on version 1.10.11

**Rasa SDK version** (if used & relevant):

**Rasa X version** (if used & relevant):

**Python version**: 
3.7.6

**Operating system** (windows, osx, ...): 
osx

**Issue**: 
Rasa could not be started if ONLY the NLG Section (Templates) changed and if the domain contains categorical slots. 

To reproduce the issue do the following:
* Take any bot that uses categorical slots
* Train the bot so every model is up to date 
* test the bot -> the bot should work fine
* change a response text, save the domain file and enter ``` rasa train ```
* there should be a message displaying ```Data (nlg) for NLG templates section changed. Core stories/configuration did not change. Only the templates section has been changed. A new model with the updated templates will be created. NLU data/configuration did not change. No need to retrain NLU model.```
* everything should seem fine by now
* if you launch the rasa agent by entering ``` rasa run ``` the "invalid domain error" should appear as shown below
* if you force to retrain the core model the error disappears

**Error (including full traceback)**:

All the slots that are listed as states that have been apparently removed are the categorical slots.
I dont know whey the slots are named with the "_2" postfix, since their name in the domain file does not include the ending "_2 "
```
2020-08-25 15:25:22 ERROR    rasa.core.agent  - Could not load model due to Domain specification has changed. You MUST retrain the policy. Detected mismatch in domain specification. The following states have been
	 - removed: slot_kinder_unter_12_2,slot_stationaer_2,slot_kinderkrankengeld_anspruch_2,slot_attest_2,slot_sachsen_2,slot_haertefall_2,slot_kinderkrankengeld_berufstaetig_2,slot_alter_kind_2,slot_festgehalt_2,slot_partner_2,slot_chronisch_2,slot_schwanger_2,slot_begleitperson_2,slot_schwer_erkrankt_2,slot_kinderlos_2,slot_andere_person_haushalt_2,slot_versicherungsart_privat_2,slot_no_einmalzahlung_1,slot_haushaltzustaendig_2
	 - added:    .
Experienced exception while trying to serve
Traceback (most recent call last):
  File "/Users/aljoscha.niazi/venvs/basic_ml/lib/python3.7/site-packages/sanic/app.py", line 1167, in run
    serve(**server_settings)
  File "/Users/aljoscha.niazi/venvs/basic_ml/lib/python3.7/site-packages/sanic/server.py", line 892, in serve
    trigger_events(before_start, loop)
  File "/Users/aljoscha.niazi/venvs/basic_ml/lib/python3.7/site-packages/sanic/server.py", line 668, in trigger_events
    loop.run_until_complete(result)
  File "uvloop/loop.pyx", line 1456, in uvloop.loop.Loop.run_until_complete
  File "/Users/aljoscha.niazi/venvs/basic_ml/lib/python3.7/site-packages/rasa/core/run.py", line 257, in load_agent_on_start
    action_endpoint=endpoints.action,
  File "/Users/aljoscha.niazi/venvs/basic_ml/lib/python3.7/site-packages/rasa/core/agent.py", line 306, in load_agent
    remote_storage=remote_storage,
  File "/Users/aljoscha.niazi/venvs/basic_ml/lib/python3.7/site-packages/rasa/core/agent.py", line 973, in load_local_model
    path_to_model_archive=model_archive,
  File "/Users/aljoscha.niazi/venvs/basic_ml/lib/python3.7/site-packages/rasa/core/agent.py", line 432, in load
    domain.compare_with_specification(core_model)
  File "/Users/aljoscha.niazi/venvs/basic_ml/lib/python3.7/site-packages/rasa/core/domain.py", line 761, in compare_with_specification
    f"Domain specification has changed. "
rasa.core.domain.InvalidDomain: Domain specification has changed. You MUST retrain the policy. Detected mismatch in domain specification. The following states have been
	 - removed: slot_kinder_unter_12_2,slot_stationaer_2,slot_kinderkrankengeld_anspruch_2,slot_attest_2,slot_sachsen_2,slot_haertefall_2,slot_kinderkrankengeld_berufstaetig_2,slot_alter_kind_2,slot_festgehalt_2,slot_partner_2,slot_chronisch_2,slot_schwanger_2,slot_begleitperson_2,slot_schwer_erkrankt_2,slot_kinderlos_2,slot_andere_person_haushalt_2,slot_versicherungsart_privat_2,slot_no_einmalzahlung_1,slot_haushaltzustaendig_2
	 - added:
```

**Command or request that led to error**:

```
rasa run
```
displays the error. 

But i think 
```
rasa train
```
produces the error since the new domain file is either parsed incorrectly or saved incorrectly.

**Content of configuration file (config.yml)** (if relevant):
```yml

```

**Content of domain file (domain.yml)** (if relevant):
I would like to not show the domain file since it contains private info about 3rd party companies. Please contact me if you need the domain file to reproduce the error, i would then proceed to create a test domain file which reproduces the error.
```yml

```

**Comment by sara-tagger** [comment]
Thanks for raising this issue, @dakshvar22 will get back to you about it soon✨

###### Please also check out the [docs](https://rasa.com/docs/) and the [forum](https://forum.rasa.com/) in case your issue was raised there too 🤗
