### ISSUE TITLE
Add configurable prefixes to Redis Tracker and Lock stores

### ISSUE THREAD

**Issue by bjbredis** [RasaHQ/rasa#6498]
**Description of Problem**:
Currently Rasa does not allow using the same Redis instance for the TrackerStore and the LockStore because they use the same keys which overwrite each other or Rasa requires separate logical Redis DBs which most Redis services do not support multiple logical DBs (only `select 0` supported).
Related issues: 
- [#5813 Adding support for Redis Cluster mode to store both lock-store and tracker-store](https://github.com/RasaHQ/rasa/issues/5813)
- [#6227 RedisLockStore support for cluster mode ](https://github.com/RasaHQ/rasa/issues/6227)

**Overview of the Solution**:
Allow a new parameter in `endpoints.yml` to specify an alphanumeric prefix which is prepended to all keys for the given (Lock|Tracker)Store. The prefix should be optional for compatibility therefore the configurable prefix will be prepended as either `prefix:lock:<senderid` or `prefix:tracker:<senderid>`. The lock and tracker keys will not collide _and_ a given Redis instance can be used by more than one conversation tracker. 

**Definition of Done**:
- [y] ~Tests are added~ Existing tests provide sufficient coverage with minor changes.
- [y] Feature described the docs
- [y] Feature mentioned in the changlog

**Comment by sara-tagger** [comment]
Thanks for submitting this feature request 🚀 @koaning will get back to you about it soon! ✨

**Comment by alwx** [comment]
Closing because the PR is merged.
