### ISSUE TITLE
Channel-specific responses not working

### ISSUE THREAD

**Issue by tatianafrank** [RasaHQ/rasa#6519]
**Rasa version**: 1.10.9

**Rasa SDK version** (if used & relevant): 1.10.2

**Python version**: 3.7.3

**Operating system** (windows, osx, ...): testing locally on osx, production is linux

**Issue**:
I have a custom channel setup but when I make a request to that channel I get the default response instead. The custom channel code:

```
from rasa.core.channels.channel import RestInput, InputChannel, 
OutputChannel, UserMessage, CollectingOutputChannel
from rasa.utils.common import raise_warning
from sanic import Blueprint, response
from sanic.request import Request
from sanic.response import HTTPResponse
from typing import Any, Awaitable, Callable, Dict, List, Optional, Text

class SlackGatewayRestInput(InputChannel):
    @classmethod
    def name(cls) -> Text:
        return "slack-gateway"

@classmethod
def blueprint(
    self, on_new_message: Callable[[UserMessage], Awaitable[Any]]
) -> Blueprint:
    slack_webhook = Blueprint("slack_webhook", __name__)

    @slack_webhook.route("/", methods=["GET"])
    async def health(_: Request) -> HTTPResponse:
        return response.json({"status": "ok"})

    @slack_webhook.route("/webhook", methods=["POST"])
    async def receive(request: Request) -> HTTPResponse:
        req_json = request.json
        sender_id = req_json.get("sender", None)
        text = req_json.get("message", None)
        input_channel = req_json.get("input_channel") or self.name()
        metadata = req_json.get("metadata", None)

        collector = CollectingOutputChannel()

        try:
            await on_new_message(
                UserMessage(
                    text,
                    collector,
                    sender_id,
                    input_channel=input_channel,
                    metadata=metadata,
                )
            )
        except Exception:
            logger.exception(
                f"An exception occured while handling "
                f"user message '{text}'."
            )

        
        return response.json(collector.messages)

    return slack_webhook

```

Here is an example response yaml:

```
  utter_something:
  - text: This is the default response
  - text: This is the custom channel response
     channel: slack-gateway
```

Im making the request to /webhooks/slack-gateway/webhook

BTW I know there Rasa has its own slack integration channel – it doesnt meet our needs which is why we have this simple custom connector and our slack message processing in a separate service outside rasa.

**Comment by sara-tagger** [comment]
Thanks for the issue, @rctatman will get back to you about it soon!

###### You may find help in the [docs](https://rasa.com/docs/) and the [forum,](https://forum.rasa.com/) too 🤗

**Comment by Dustyposa** [comment]
Default channel can get any thing?

**Comment by tatianafrank** [comment]
I don't understand what you're asking. The default channel responds with `This is the default response` as you can see in the example above. Right now the custom channel webhook is return ing the default channel response instead of the custom channel response. Im pretty sure this is because `collector.messages` returns an empty array but it's supposed to store the channel responses to return.

**Comment by erohmensing** [comment]
@tatianafrank is the indentation as above? `channel` should be on the same level as `text`. YAML is finnicky -- if you copy paste what you provided into a yaml to json converter, you can see that the channel param disappears: https://www.convertjson.com/yaml-to-json.htm

If you remove the one space before it so that they are indented the same, channel is another parameter in the response dict.

**Comment by tatianafrank** [comment]
Yes the issue ended up being unrelated to formatting. The issue is that there is not enough documentation on how to create a custom channel. We had to spend a lot of time figuring out that we had to create a custom output channel with the channel name returned by the name method of the output channel.

**Comment by erohmensing** [comment]
Got it -- I'll make an issue for improving the documentation on that.

**Comment by stefanvantchev** [comment]
FYI ... this has not been resolved - the documentation remains the same, which has caused us to also spend quite some time.

**Comment by kormoczi** [comment]
Can somebody help me? Or @tatianafrank , can you describe your solution a little bit more?
I still receiving the default responses, and not the channel-specific ones...

**Comment by kormoczi** [comment]
OK, I am still not fully understand all the details, but I was able to get is work (although it will need more testing...).
The first part of the solution was to implement the output class, with the name method, returning the channel name (as @tatianafrank has mentioned).
The other part of the solution was to replace this line:
`collector = CollectingOutputChannel()`
to this:
`collector = MyCustomOutputChannel()`
