### ISSUE TITLE
Docs for 2.0.0a3 and implementation disagree on how forms are described in domain

### ISSUE THREAD

**Issue by federicotdn** [RasaHQ/rasa#6535]
Tested on Rasa 2.0.0a3.

There might be a problem with how forms are defined in the domain in Rasa 2.0.0. The [documentation](https://rasa.com/docs/rasa/next/forms#defining-a-form) shows the following example:
```yaml
forms:
  your_form:
    age:
    - type: from_entity
      entity: age
```

But if I try using that, it fails with:
```
2020-09-01 14:44:47 ERROR    pykwalify.core  - validation.invalid
2020-09-01 14:44:47 ERROR    pykwalify.core  -  --- All found errors ---
2020-09-01 14:44:47 ERROR    pykwalify.core  - ["Value '{'your_form': {'age': [{'type': 'from_entity', 'entity': 'age'}]}}' is not a list. Value path: '/forms'"]
```

However changing forms from a map to a list of objects works:
```yaml
forms:
- your_form:
    age:
    - type: from_entity
      entity: age
```

It is not clear if the implementation is correct, or the docs. The schema described by the docs is easier to handle and use programmatically.

**Comment by wochinge** [comment]
@federicotdn Do you want to keep it in the loop? ProdSquad worked on this as part of rules.

**Comment by federicotdn** [comment]
Not necessary! Feel free to move it.
