### ISSUE TITLE
Update RasaX Kafka event broker consumer code to support SSAL_PLAINTEXT protocol

### ISSUE THREAD

**Issue by HariTeneti** [RasaHQ/rasa#6539]
**Rasa version**: 1.9.6-full

**Rasa SDK version** (if used & relevant): 1.9.0

**Rasa X version** (if used & relevant): 0.27.7

**Python version**: Python3.6

**Operating system** (windows, osx, ...): CentOS Linux 7

**Issue**: RasaX Kafka event broker-consumer code is missing support for SASL_PLAINTEXT protocol whereas Rasa Core supports SASL_PLAINTEXT. Please update RasaX Kafka consumer code.

I tested with the following code and it works fine.
```
rasax\community\services\event_consumers\kafka_consumer.py

def _create_consumer(self) -> None:
	# noinspection PyPackageRequirements
	import kafka

	elif "sasl_plaintext" in self.security_protocol.lower():
	    self.consumer = kafka.KafkaConsumer(
		self.topic,
		bootstrap_servers=self.host,
		security_protocol="SASL_PLAINTEXT",
		sasl_mechanism="PLAIN",
		sasl_plain_username=self.sasl_username,
		sasl_plain_password=self.sasl_password,
		ssl_check_hostname=False,
	    )
```

**Error (including full traceback)**:
```
Please see the following link that I submitted for all logs and additional details.
https://forum.rasa.com/t/rasa-core-integration-issue-with-kafka-event-broker-error-nobrokersavailable/32678
```

**Command or request that led to error**:
```
RasaX is failing to connect to Kafka event broker with SSAL_PLAINTEXT protocol
```

**Content of configuration file (config.yml)** (if relevant):
```yml

```

**Content of domain file (domain.yml)** (if relevant):
```yml

```

**Comment by sara-tagger** [comment]
Thanks for the issue, @koaning will get back to you about it soon!

###### You may find help in the [docs](https://rasa.com/docs/) and the [forum,](https://forum.rasa.com/) too 🤗

**Comment by erohmensing** [comment]
Thanks so much for opening this issue! We just released 0.32.2, which includes this fix (it also fixes the lack of support for `SASL_SSL` due to a similar issue! See changelog: https://rasa.com/docs/rasa-x/changelog/rasa-x-changelog/#id1

**Comment by HariTeneti** [comment]
@erohmensing erohmensing
Thank you for updating RasaX to support SASL_PLAINTEXT protocol. **Really appreciate RASA TEAM for fixing this very quickly.**

The RasaX 0.32.2 now supports SASL_SSL and PLAINTEXT protocols but the Rasa Core is not updated to support  SASL_SSL and PLAINTEXT protocols. Is there any plan to update Rasa Core to support these protocols especially SASL_SSL protocol? So both RasaX and Rasa Core will be in sync for Kafka protocol support.

Please let me know if you want me to submit a new issue to fix Rasa Core.

Thanks

**Comment by erohmensing** [comment]
@HariTeneti that's a good point! Yes, please feel free to open a PR to implement that fix, we'd be happy to add it.

**Comment by HariTeneti** [comment]
@erohmensing Thank you. I've submitted an issue https://github.com/RasaHQ/rasa/issues/6677 . Hope it will be fixed soon.

**Comment by erohmensing** [comment]
Oh sorry, I thought you meant you wanted to contribute the fix, since it's open source. Are you interested in doing so?
