### ISSUE TITLE
Only changing response in domain breaks model

### ISSUE THREAD

**Issue by tatianafrank** [RasaHQ/rasa#6543]
**Rasa version**: 1.10.9

**Rasa SDK version** (if used & relevant): 1.10.2

**Python version**: 3.7.3

**Operating system** (windows, osx, ...): osx

**Issue**:

If I make a small change to a response in the domain.yml and then run `rasa train` then `rasa start` then I get the error below. I can usually fix it by deleting the old model and the one I just trained and running rasa train again. So basically if I want to change just a response then I need to delete the model before running train so that rasa picks up the change.

**Error (including full traceback)**:
```
Domain specification has changed. You MUST retrain the policy. Detected mismatch in domain specification. The following states have been 
         - removed: slot_webex_device_3, slot_requested_slot_3, slot_device_type_5, slot_has_outlook_pilot_2 
         - added:   

```

**Command or request that led to error**:
```

```

**Content of configuration file (config.yml)** (if relevant):
```yml

```

**Content of domain file (domain.yml)** (if relevant):
```yml

```

**Comment by sara-tagger** [comment]
Thanks for the issue, @JustinaPetr will get back to you about it soon!

###### You may find help in the [docs](https://rasa.com/docs/) and the [forum,](https://forum.rasa.com/) too 🤗

**Comment by JustinaPetr** [comment]
Hi @tatianafrank. Are you saving your models in a custom directory somewhere or are you going with the default `./models` directory?

**Comment by tatianafrank** [comment]
@JustinaPetr  Default ./models directory

**Comment by tomasis98** [comment]
Same problem here. Looks like categorical slots aren't correctly assigned to `self.input_states`.

**Comment by tatianafrank** [comment]
Can we get a fix for this? I have to spend a lot of time re-training the whole model every time I change a response. A workaround would be for us to set up NLG I suppose so that responses dont live in the domain file anymore but we havent had time to set that up yet.

**Comment by JustinaPetr** [comment]
@tatianafrank I'd like to replicate this issue. Do you have any categorical slots in your domain too?

One quick think I'd like you to try is to try testing your bot with the latest version of Rasa (1.10.12). Could you try creating a new virtual environment with this version of Rasa and testing your assistant?

**Comment by tatianafrank** [comment]
@JustinaPetr I upgraded rasa to 1.10.12 but im still seeing the same behavior. I made a small text change to one of the response templates then I ran rasa train which worked fine but then running rasa start throws the same error still:

```
 Domain specification has changed. You MUST retrain the policy. Detected mismatch in domain specification. The following states have been 
         - removed: slot_has_outlook_pilot_2,slot_webex_device_3,slot_requested_slot_3,slot_device_type_5 
         - added:    
```

**Comment by JustinaPetr** [comment]
Hi @tatianafrank Are you still having this issue? Also, just to double check - you start your assistant with `rasa shell` or a different command?

**Comment by tatianafrank** [comment]
rasa shell or rasa run @JustinaPetr

**Comment by tatianafrank** [comment]
bumping so the issue doesnt get marked as stale.

**Comment by tatianafrank** [comment]
@JustinaPetr

**Comment by JustinaPetr** [comment]
Hi @tatianafrank. Would it be possible to share your domain.yml file here? I would like to replicate this issue to really see what is happening. If sharing the domain is not possible here due to security reasons, would it be possible to send it over the email (the same as included in my github profile)?

**Comment by tatianafrank** [comment]
@JustinaPetr I emailed you, thanks!

**Comment by alwx** [comment]
@JustinaPetr @tatianafrank what's the status of this issue?
