### ISSUE TITLE
Change Context Path

### ISSUE THREAD

**Issue by NavinAsokan** [RasaHQ/rasa#6544]
**Description of Problem**: Short overview of the current situation. Rasa uses context path :- webhooks/slack/webhook We need to use a different context path altogether considering the above path cannot be used due to technical issues. We may need to use this like :- webhooks/XYZ/webhook and customize according to our request. Pls add this feature. IF there is any workaround , then please update on that as well.

[https://forum.rasa.com/t/change-context-path-rasa/33054](https://forum.rasa.com/t/change-context-path-rasa/33054)

**Comment by sara-tagger** [comment]
Thanks for submitting this feature request 🚀 @TyDunn will get back to you about it soon! ✨

**Comment by TyDunn** [comment]
Hi @NavinAsokan. Can you please add a description of your problem?

**Comment by NavinAsokan** [comment]
Hi,
We need to change the context path in our Rasa framework. As of now the
default path is webhooks/slack/webhook
<http://ma1-edwdbad-ldb02.corp.apple.com:5005/iris/webhooks/slack/webhook> .
We are unable to use this context path as one of the other team using this
framework used this for slack integration.
So we need to customize this context path .For example we need the
following path for slack integration webhooks/XYZ/webhook
There is no option in Rasa to have the context path customized. Please
create option for this.
Related forum topic:-
https://forum.rasa.com/t/change-context-path-rasa/33054/2?u=navin

Pls review

**Comment by TyDunn** [comment]
@NavinAsokan Since you have plan to make the change yourself, would you be willing to [contribute it to Rasa Open Source](https://forum.rasa.com/t/how-to-make-a-code-contribution-to-rasa/11291)? Tobias mentioned he would be willing to review the pull request

**Comment by NavinAsokan** [comment]
Hi,

I am in the process of testing the same. Will update if it goes through.
Kind regards
Navin

**Comment by TyDunn** [comment]
@NavinAsokan Are you still working on this?

**Comment by NavinAsokan** [comment]
Hi,

I updated the workaround in the same forum. Requested for enhancement
Navin
