### ISSUE TITLE
Restrict length of rules to one user turn 

### ISSUE THREAD

**Issue by erohmensing** [RasaHQ/rasa#6557]
**Description of Problem**:

The RulePolicy is meant to replace the Form, Mapping, and Fallback policies. It's not meant to hardcode a state machine. We want to make sure that users understand this and provide ample training data to their machine learning policy to make predictions incase of unseen conversation paths. 

**Overview of the Solution**:

We restrict the length of rules to one _user_ turn (i.e. there can still be multiple bot events, including e.g. a form being filled and its subsequent submission.

**Comment by wochinge** [comment]
How about a warning which can explicitly be disabled in the `RulePolicy` config? (should be `enabled: True` by default)

**Comment by Ghostvv** [comment]
in my opinion warning is not enough

**Comment by tmbo** [comment]
we shouldn't add undocumented options, either we think there is a use case for an option and describe that or there shouldn't be an option

**Comment by Ghostvv** [comment]
we'll add an option to docs, just not advertise it
