### ISSUE TITLE
rasa test core not working for stories in a folder

### ISSUE THREAD

**Issue by evgeniiaraz** [RasaHQ/rasa#6558]
**Rasa version**:
Current ```master```
**Rasa SDK version** (if used & relevant):
N/A
**Rasa X version** (if used & relevant):
N/A
**Python version**:

**Operating system** (windows, osx, ...):

**Issue**:
`rasa test core` doesn't work when the stories are in a subfolder, e.g., `rasa test core --stories data/core` on `rasa-demo`
In this case, it finds 0 test stories. 

(My suspicion is that it comes from `rasa.data.get_test_directory`)

**Error (including full traceback)**:
```

```

**Command or request that led to error**:
```
rasa test core --stories data/core
```

in ```rasa-demo```

**Content of configuration file (config.yml)** (if relevant):
```yml

```

**Content of domain file (domain.yml)** (if relevant):
```yml

```

**Comment by tmbo** [comment]
This is intentional, it was designed that way (I am not sure why but the conversation tests required a `test/` folder). In terms of backwards compatibility, I am not sure we should change this.

**Comment by evgeniiaraz** [comment]
Previously, you could test your model on the training set but now you can't :( 
And in that function which I changed the filters which are used for YAML and MD are different

**Comment by tmbo** [comment]
mhm interesting, it might be that it worked when specifying the directory and only the auto detection was looking for that specific folder. in that case I think you might be right and we should change it :+1:

**Comment by evgeniiaraz** [comment]
I think this issue is actually harder than I thought... 
what was the motivation for the test conversations to be only in the `test/` folder? it seems like it was for end-to-end test stories but then we're not checking whether it is in use_e2e mode
