### ISSUE TITLE
The path 'config.yml' does not exist. Please make sure to use the default location ('config.yml') or specify it with '--config'

### ISSUE THREAD

**Issue by ganesh3** [RasaHQ/rasa#6560]
**Rasa version**:

**Rasa SDK version** (if used & relevant):

**Rasa X version** (if used & relevant): 1.10.11

**Python version**: 3.8.5

**Operating system** (windows, osx, ...): Windows

**Issue**:
Installed RasaX from the website - https://rasa.com/docs/rasa-x/installation-and-setup/install/local-mode/

Executed following command:
pip install rasa-x --extra-index-url https://pypi.rasa.com/simple

**Error (including full traceback)**:
 Running the below command leads to error:
>rasa x
The path 'config.yml' does not exist. Please make sure to use the default location ('config.yml') or specify it with '--config'.

**Command or request that led to error**:
rasa x

**Content of configuration file (config.yml)** (if relevant):
```yml

First time setup so not sure where is it setup by default.

**Content of domain file (domain.yml)** (if relevant):
```yml

Not sure.

**Comment by sara-tagger** [comment]
Thanks for raising this issue, @JustinaPetr will get back to you about it soon✨

###### Please also check out the [docs](https://rasa.com/docs/) and the [forum](https://forum.rasa.com/) in case your issue was raised there too 🤗

**Comment by JustinaPetr** [comment]
Hi @ganesh3. To run run rasa x, you need a Rasa project in your working directory. Do you have an assistant you have built with Rasa? If not, you can run `rasa init` which will create an example rasa assistant for you called `moodbot`. Make sure you are in the directory which contains the files of the assistant and then once you run `rasa x` your assistant should be launched using Rasa X.

**Comment by ganesh3** [comment]
> 
> 
> Hi @ganesh3. To run run rasa x, you need a Rasa project in your working directory. Do you have an assistant you have built with Rasa? If not, you can run `rasa init` which will create an example rasa assistant for you called `moodbot`. Make sure you are in the directory which contains the files of the assistant and then once you run `rasa x` your assistant should be launched using Rasa X.

Thanks. This worked. Can this also be updated on the docs at below URL?
https://rasa.com/docs/rasa-x/installation-and-setup/install/local-mode/

Regards
Ganesh Bhat

**Comment by Zapnuse** [comment]
https://stackoverflow.com/questions/57491391/rasa-x-the-path-config-yml-does-not-exist-please-make-sure-to-use-the-default

i think you must try this
