### ISSUE TITLE
No response in slack when custom action runs for longer than 3 seconds

### ISSUE THREAD

**Issue by adityac07** [RasaHQ/rasa#6568]
**Rasa version**: 1.10.12

**Rasa SDK version** (if used & relevant): 1.10.2

**Rasa X version** (if used & relevant):

**Python version**: 3.7

**Operating system** (windows, osx, ...): macOS

**Issue**: I have a custom action which runs fine as long as it finishes below 3 seconds. As soon as I put in time.sleep(4), no response is returned to slack.

This can be reproduced as follows:

1.  create a custom action with dispatcher.utter_message("hi") as the only code running inside the run function
2.  put timer.sleep![](/images/icons/emoticons/error.png) (replace x with values from 1 to 4) before utter_message
3.  slack returns a response as long as x above is less than 3

**Error (including full traceback)**:

**Command or request that led to error**:

**Content of configuration file (config.yml)** (if relevant):

**Content of domain file (domain.yml)** (if relevant):

**Comment by melindaloubser1** [comment]
Is this action getting triggered by a slash command? If so, the three second timeout is configured on Slack's side - see https://api.slack.com/interactivity/slash-commands#responding_to_a_command. You can get around it by following the advice in this answer: https://stackoverflow.com/questions/34896954/how-to-avoid-slack-command-timeout-error#:~:text=3%20Answers&text=According%20to%20the%20Slack%20slash,any%20response%20to%20their%20command.

**Comment by adityac07** [comment]
It is not triggered by a slash command. I trigger it through a normal conversation with the bot
