### ISSUE TITLE
[TENSORFLOW] Training Out of memory problem

### ISSUE THREAD

**Issue by wavymazy** [RasaHQ/rasa#6581]
**Rasa version**: 1.10.0

**Rasa SDK version** (if used & relevant): 1.10.0

**Rasa X version** (if used & relevant): n/a

**Python version**: 3.6.9

**Operating system** (windows, osx, ...): UBUNTU 20.04

**Issue**: When training rasa, the Keras policy or TEDPolicy will use my GPU memory and after core training has finished my GPU memory will still be full, and will trigger an out of memory issue when I start training the NLU, either at sequence classification or DIET entity extraction.

Additional info:

*   I am using tensorflow 2.1.0
*   I am using a custom component to train NLU sequence classification that uses PyTorch.

Attempted solutions:

*   I tried setting Cuda visible devices to only show CPU, which works well for core training, but takes ages for the DIET entity extractor which also uses tensorflow.
*   It is impossible to change the tensorflow list of visible devices because, core training and nlu training are done in the same process.
*   Trying to flush memory after core training fails when I get to the DIET entity extractor.

**Error (including full traceback)**:

**Command or request that led to error**:

 rasa train

**Content of configuration file (config.yml)** (if relevant):

<pre># Configuration for Rasa NLU.

1.  [https://rasa.com/docs/rasa/nlu/components/](https://rasa.com/docs/rasa/nlu/components/)
     language: "en"
     pipeline:

*   name: "AutoTransformerNLPClassifier"
     model: bert-base-uncased
     model_type: bert
     epochs: 5
     seed: 776
     case_sensitive: False
     batch_size: 42
*   name: "AugmentedWhitespaceTokenizer"
*   name: RegexFeaturizer
*   name: LexicalSyntacticFeaturizer
*   name: DIETClassifier
     epochs: 30
     batch_size: 5
     entity_recognition: True
     intent_classification: False
*   name: "SmartEntitySynonymMapper"
*   name: "CustomDucklingHTTPExtractor"
     url: "http://0.0.0.0:8000"
     locale: "en"
     dimensions: <span class="error">["amount-of-money","time","number","duration","email","distance","quantity", "phone-number"]</span>

1.  Configuration for Rasa Core.
2.  [https://rasa.com/docs/rasa/core/policies/](https://rasa.com/docs/rasa/core/policies/)
     policies:

*   name: MappingPolicy
*   name: FormPolicy
*   name: TEDPolicy
     epochs: 5
     max_history: 5
*   name: FallbackPolicy
     nlu_threshold: 0.3
     core_threshold: 0.5
     fallback_action_name: 'action_default_fallback'</pre>

**Content of domain file (domain.yml)** (if relevant):

**Comment by sara-tagger** [comment]
Thanks for the issue, @rctatman will get back to you about it soon!

###### You may find help in the [docs](https://rasa.com/docs/) and the [forum,](https://forum.rasa.com/) too 🤗

**Comment by MusaAtlihan** [comment]
@wavymazy did have a chance to try with a different TensorFlow version (2.0.0 for example)? TF 2.1.0 had memory leakage problem as far as I can remember.

**Comment by Fatima-Gh** [comment]
I am running into the same issue but with Rasa 1.10.11 while trying Keras and TEDPolicy.

**Comment by Ghostvv** [comment]
@joejuzl I think it might be related to our OOM problems in `rasa test`

**Comment by twerkmeister** [comment]
@wavymazy @Fatima-Gh, Is this problem still existing for you on current versions of rasa and tensorflow?

**Comment by wavymazy** [comment]
Hi guys,

@twerkmeister I was able to find a solution that works but I am not sure if it is ideal. It's by setting set memory growth to 'True' `tf.config.experimental.set_memory_growth(gpu, True)`, before the training of the Keras/Tedpolicy.

@musa-atlihan I haven't tested with Tensorflow 2.0.0, So I cannot confirm if that would resolve the issue.
