### ISSUE TITLE
Rasa spliting algorithm does not give precise number of training samples.

### ISSUE THREAD

**Issue by duongkstn** [RasaHQ/rasa#6582]
**Description of Problem**: Some examples may be missed due to Rasa spliting algorithm.The issues is clearly depicted at [forum thread](https://forum.rasa.com/t/rasa-split-data-nlu-fails-which-algorithm-is-implemented/29259/5)

**Overview of the Solution**:  `rasa data split` does not give precise number of training samples. 
Say overall we have X samples (x<sub>1</sub> samples of label l<sub>1</sub>, x<sub>2</sub> samples of label l<sub>2</sub>, …) and `training-fraction` is 0.8. 
(Note: x<sub>1</sub> + x<sub>2</sub> + … = X).
In the [code of Rasa](https://github.com/RasaHQ/rasa/blob/1.10.0/rasa/nlu/training_data/training_data.py#L457) , number of training samples is A = int(0.8 * x<sub>1</sub>) + int(0.8 * x<sub>2</sub>) + …
Mathematically, A ≤ int(0.8 * X). 
So number of missing samples is int(0.8 * X) - A

**Comment by sara-tagger** [comment]
Thanks for submitting this feature request 🚀 @JustinaPetr will get back to you about it soon! ✨

**Comment by tabergma** [comment]
closed via #7095
