### ISSUE TITLE
`rasa data split nlu` no longer works

### ISSUE THREAD

**Issue by akelad** [RasaHQ/rasa#6588]
Part of #6475 

**Rasa version**: master

Running `rasa data split nlu` creates an empty `train_test_split` directory as of the 2.0 changes to the data format. It's supposed to generate `test_data` and `training_data` files (they used to be .json, but we should probably change that to be .yaml as well)

I tested this on the `formbot` and `responseselectorbot` examples, both with the same result.

Potentially related to this issue: https://github.com/RasaHQ/rasa/issues/6389

Whoever fixes it, please make sure to update the `CLI` documentation as well!

**Comment by m-vdb** [comment]
@akelad do you know why the default format was `json` in the first place?

**Comment by akelad** [comment]
it's archaic functionality from when json was the only format we had :D
