### ISSUE TITLE
Revisit example bots before RC

### ISSUE THREAD

**Issue by akelad** [RasaHQ/rasa#6597]
Before the RC, we need to make sure that all the example bots are:
- [x] written as rules/stories according to our docs recommendations
- [x] used as examples in our documentation. if they aren't, we should consider getting rid of them or adapt them to what we describe in the docs

**Comment by akelad** [comment]
@melindaloubser1 can you take this one on?

**Comment by melindaloubser1** [comment]
Yes

**Comment by akelad** [comment]
@b-quachtran did we check if e.g. the `rules` example bot is actually used anywhere?

**Comment by b-quachtran** [comment]
@akelad The rules doc has the example

`- intent: greet`
`- action: utter_greet`

that's in the rules example bot, but other than that no.

**Comment by akelad** [comment]
does it refer to the rules bot example? I'm perfectly happy keeping the bot around, but we should refer to it from the docs, otherwise it's kind of random to have it in the examples

**Comment by b-quachtran** [comment]
It does not, I'll get that updated today
