### ISSUE TITLE
Export data from interactive learning broken on master

### ISSUE THREAD

**Issue by tabergma** [RasaHQ/rasa#6603]
**Rasa version**: Rasa 2.0.0a4

**Issue**:
When running interactive learning exporting the stories and nlu training data as `yml` file does not work. The ending `yml` is not supported.

**Error (including full traceback)**:
```
? Export stories to (if file exists, this will append the stories) data/stories.yml

Please provide a valid export path for the stories, e.g. 'stories.md'.
```

**Command or request that led to error**:
```
rasa interactive
```

**Comment by RomuloSouza** [comment]
Hi, @aleronupe and I are interested in taking this issue and will start working on it

**Comment by alwx** [comment]
Fixed here: https://github.com/RasaHQ/rasa/pull/6914
