### ISSUE TITLE
Merging domains is broken if out_of_scope intent is defined by user / make default actions configurable

### ISSUE THREAD

**Issue by dakshvar22** [RasaHQ/rasa#6606]
**Rasa version**: master

**Issue**: The `out_of_scope` intent is added to the [list of default intents](https://github.com/RasaHQ/rasa/blame/master/rasa/core/constants.py#L46) and hence its omitted when the domain is fetched as a dict because of this [line](https://github.com/RasaHQ/rasa/blob/f62839e5cb0e8ecb8cb7d85ac0f8fb078035c8c8/rasa/core/domain.py#L857)
While merging multiple domains, the domains are [fetched as dicts](https://github.com/RasaHQ/rasa/blob/master/rasa/core/domain.py#L237) which would not contain `out_of_scope` intent even if the user has defined it in their domain.

@wochinge mentioned that `out_of_scope` intent was added to default intents because we need it for the `TwoStageFallbackAction` in order to know whether the user denied the suggestion. Currently there is no way to configure default actions and so the only way is to make certain things default. We could make the deny intent configurable, something like - 
```
forms:
- two_stage_fallback:
    deny_intent: "out_of_scope"
```

👉 [Slack thread](https://rasa-hq.slack.com/archives/C36SS4N8M/p1599581976115300)

**Comment by wochinge** [comment]
@melindaloubser1 @erohmensing What do you think of the suggestion for the config? Do you have other ideas?

**Comment by melindaloubser1** [comment]
If it was configurable, would that solve the problem with a user adding `out_of_scope` to their intent list?

**Comment by dakshvar22** [comment]
@melindaloubser1 It would if because of that we can remove `out_of_scope` from the [list of default intents](https://github.com/RasaHQ/rasa/blame/master/rasa/core/constants.py#L46). I am not sure if that would bring a different side effect. 😅

**Comment by wochinge** [comment]
@m-vdb @ricwo It would be awesome if one of you could have a look at this as I think it's relevant for the RC. There is also an out of GitHub [Slack thread ](https://rasa-hq.slack.com/archives/C36SS4N8M/p1599581976115300)about this 😬

**Comment by wochinge** [comment]
I think I need to complicate this further 🙈 
When we configure the `action_two_stage_fallback` below the `forms:` key in the domain, then we are configuring something as `form` which actually isn't a form but a `loop`. That's not great from a UX perspective 😬

**Comment by ricwo** [comment]
Can we just check whether `action_two_stage_fallback` is listed as a key under `forms`, and if that's the case, we don't skip it in this line? https://github.com/RasaHQ/rasa/blob/master/rasa/shared/core/domain.py#L839
