### ISSUE TITLE
Do not interpolate button payload

### ISSUE THREAD

**Issue by tabergma** [RasaHQ/rasa#6616]
**Rasa version**: Rasa 2.0.0a4

**Issue**: If you define buttons with some payload like the following in your domain file, Rasa tries to interpolate the button payload when you are interacting with the assistant. It interprets the part between `{}` as placeholder and tries to fill it. However, in this case it refers to some entities and there is not matching template.

 utter_ask_nearby_pois:

*   text: Are you looking for an apartment near specific surroundings?
     buttons:
*   title: "no"
     payload: '/inform {"nearby_pois": "none"} 

    '

*   title: "school"
     payload: '/inform {"nearby_pois": "school"} 

    '

*   title: "train station"
*   title: "office"
     payload: '/inform {"nearby_pois": "office"} 

    '

The bot works as expected it just prints an ERROR to the command line. So, the intent and entities are recognized correctly and the bot behaves as expected.

**Idea:** @erohmensing suggested the following:

> honestly i think it might be enough, just to not print the warning if the segment starts with `/`. it will still perform fine as you’ve shown, and if they actually do have a weird slot somehow named `"nearby_pois": "office"`, it will still fill it.

**Error (including full traceback)**:

 2020-09-09 10:39:07 ERROR rasa.core.nlg.interpolator - Failed to fill utterance template '/inform

 {"nearby_pois": "office"} 

'. Tried to replace '"nearby_pois": "office"' but could not find a value for it. There is no slot with this name nor did you pass the value explicitly when calling the template. Return template without filling the template.
 Traceback (most recent call last):
 File "/Users/tabergma/Repositories/rasa/rasa/core/nlg/interpolator.py", line 28, in interpolate_text
 text = text.format(values)
 KeyError: '"nearby_pois": "office"'

**Command or request that led to error**:

 rasa shell

**Comment by wochinge** [comment]
@erohmensing Didn't you fix this? Can I move this to CSE board
