### ISSUE TITLE
New docs: deployment keeps deleted files

### ISSUE THREAD

**Issue by m-vdb** [RasaHQ/rasa#6620]
Because of [the way we deploy](https://github.com/RasaHQ/rasa/blob/c3b5ccb326cbcac325bb4326c9b56ec4cb3a276f/scripts/push_docs_to_branch.sh#L35) the code to the `documentation` branch, we do not cleanup the deleted files. As a result, if we delete files from the `docs/docs/` folder or the `docs/src/` folder in `master`, they will still be present in the `documentation` branch. This leads to weird behaviour, like [this one](https://rasa-hq.slack.com/archives/C01585AN2NP/p1599660097000100) and could prevent us from deploying correctly (I had to do [this commit on the `documentation` branch](https://github.com/RasaHQ/rasa/commit/1768b57e3b898e129587768c23b1cc7b7c7bbca9) to quick-fix it).

Note: we'll have to apply the solution we find to `rasa`, `rasa-x` and `rasa-sdk` cc @tmbo @lunelson 

## Proposal

There are three different scenarii we need to handle:

1. Pushing to master
  - remove the content of `$TMP_DOCS_FOLDER/docs/` except for `$TMP_DOCS_FOLDER/docs/versioned_docs`, `$TMP_DOCS_FOLDER/docs/versioned_sidebars` and `$TMP_DOCS_FOLDER/docs/versions.js`
  - add everything to the `$TMP_DOCS_FOLDER/` folder
2. Creating a new version
  - do 1.
  - run `yarn new-version $NEW_VERSION`
3. Updating a version
  - `cp -R docs/docs/ $TMP_DOCS_FOLDER/versioned_docs/version-$EXISTING_VERSION/`
  - ⚠️  this is not really future proof and doesn't account for all the cases. For instance if we were to make significant updates to the documentation pages (creating new page, deleting some, updating the sidebar), these changes wouldn't work here. If we want to support this use case, there would be more work to do.

These changes would replace these lines:
https://github.com/RasaHQ/rasa/blob/348c4e8fae2eafe52674c4ed099464df111d735f/scripts/push_docs_to_branch.sh#L34-L56

**Comment by m-vdb** [comment]
@tmbo I realised that we can improve the current workflow to simplify the way docs are released. Currently, the docs are released when:
1. there is a push to master
2. a new version tag is pushed

The 1. is great, the 2. not so much. If we were to switch the behaviour to "there is a push on a release branch", then we'd be able to update docs without pushing version tags. I think it'd be easier from a dev/cse standpoint. The only thing that could be detrimental is that if there are too many updates happening in parallel (master + release branches), there could be race conditions (but theoretically, since different branches update different parts of the docs, the risk should be very low). What's your take on this?

**Comment by tmbo** [comment]
Yes I think that is something we can try :+1:
