### ISSUE TITLE
Migration script from IBM Watson to RASA is absent

### ISSUE THREAD

**Issue by umangnangal** [RasaHQ/rasa#6621]
I am seeing that the migration script from IBM Watson to RASA is missing from the RASA project as can be seen in the below documentation link.
https://rasa.com/docs/rasa/migrate-from/ibm-watson-to-rasa/

Recently, I came across such requirement and I am currently working on it.
Please assign this bug to me, I can raise a PR in some time.
Including @melindaloubser1 in the thread.
Related issue link : https://github.com/RasaHQ/rasa-x-demo/issues/28

**Comment by melindaloubser1** [comment]
Thanks for volunteering for this issue @umangnangal. I'm changing it to an enhancement since nothing is broken, only not implemented yet.

**Comment by umangnangal** [comment]
Sure @melindaloubser1 . Thanks for the pointers 🙂.

**Comment by melindaloubser1** [comment]
@umangnangal I see there's actually an existing issue for this, see here: 
https://github.com/RasaHQ/rasa/issues/1154
I'll close this issue in favour of that one since significant discussion has already taken place there.
