### ISSUE TITLE
Mark default action of `TwoStageFallbackPolicyAction` as deprecated

### ISSUE THREAD

**Issue by wochinge** [RasaHQ/rasa#6623]
Due to the introduction of the `RulePolicy` the `TwoStageFallbackPolicy` is deprecated. The `TwoStageFallbackPolicy` uses a couple of default actions:

- `action_revert_fallback_events`
- ~`action_default_ask_affirmation`~ (can be kept, used by new `TwoStageFallback`)
- ~`action_default_ask_rephrase`~ (can be kept, used by new `TwoStageFallback`)

We don't need them to deprecate them in the code as the policies which are using these actions are already deprecated. 

Todos:
- [x] update documentation for `default-actions` to reflect that the actions from above are deprecated
- [ ] Leave a comment in each of these actions in the code that they are deprecated and can be removed once the `TwoStageFallbackPolicy` is removed. 
- [ ] rename `two_stage_fallback` action to `action_two_stage_fallback `

**Comment by akelad** [comment]
I ticked the documentation part, because that's handled [here](https://github.com/RasaHQ/rasa/pull/6618)

**Comment by akelad** [comment]
should the two stage fallback action be called `two_stage_fallback_loop` btw? For forms we usually have `_form` at the end. Like e.g. in [Sara](https://github.com/RasaHQ/rasa-demo/blob/master/domain.yml#L599)

**Comment by wochinge** [comment]
I wouldn't do so. Why confuse the users with the `_loop` prefix? They don't need to know that it's a loop - there is no benefit for them in knowing that.

**Comment by akelad** [comment]
but then what is it? a magical unicorn? 😅

**Comment by wochinge** [comment]
It's the TwoStageFallback 😆 Also: in the user tests the whole `active_loop` thing seemed to rather confuse users. So if, I'd rather go with action but I think it's overdoing.

**Comment by akelad** [comment]
yeah i can see that re `active_loop` - but i would imagine `active_form` wasn't any less confusing lol. The whole concept of Loop vs Form I think is gonna be a problem. 

I just think that if we're making people write a rule for the two stage fallback, it's going to read `action: two_stage_fallback` - so why would it be anything other than an action/loop?

**Comment by wochinge** [comment]
Fair - so rename it to `action_two_stage_fallback`?

**Comment by akelad** [comment]
yeah that would be fine

**Comment by musa-atlihan** [comment]
Hey @wochinge , may I try to close this issue? I would like to work on this.

**Comment by m-vdb** [comment]
thanks for taking this on @musa-atlihan 🙏  We'll review your PR in the coming days

@wochinge just a sanity check: do we rase a deprecation warning saying that `TwoStageFallbackPolicy` will be removed in 3.0?

**Comment by wochinge** [comment]
yes of course! 

> We don't need them to deprecate them in the code as the policies which are using these actions are already deprecated.
