### ISSUE TITLE
RegexFeaturizer Multiprocessing / Multithreading

### ISSUE THREAD

**Issue by Mazyod** [RasaHQ/rasa#6625]
**Description of Problem**:

RegexFeaturizer is using a single CPU core, causing slow training instead of leveraging idle CPU cores. In our case, it is taking ~1 hour, which can easily become ~5 mins.

 10:30 AM 2020-09-10 07:30:16,812: Starting to train component RegexFeaturizer
 11:17 AM 2020-09-10 08:17:50,472: Finished training component.

**Overview of the Solution**:

RegexFeaturizer should parallelize the processing of training sentences based on the available CPU cores. This can either be achieved at the component level, or better yet as a generalized multiprocessing solution. I think it's a fair assumption that most developers will be running training on a relatively high spec machine with more than a single CPU core after all.

**Definition of Done**:

*   [ ] RegexFeaturizer parallelizes it's work across multiple cores (processes/thread)
*   [ ] Ability to configure the max parallelization (threads/processes)
*   [ ] Tests are added
*   [ ] Feature described the docs
*   [ ] Feature mentioned in the changelog

**Note** I'm interested in contributing a PR to solve this. I have multiple approaches in mind, however, it would be great if we could finalize the solution before the implementation.

**Comment by sara-tagger** [comment]
Thanks for submitting this feature request 🚀 @Ghostvv will get back to you about it soon! ✨

**Comment by tabergma** [comment]
@Mazyod May I ask how many regexes do you have that training takes that long? Never saw that someone mentioned this before. Or is it rather an issue with the size of your dataset? 

We are currently thinking of changing our data pipeline so that we don't load all the data at a time, which would allow us to load bigger datasets. Keeping that in mind, I guess it makes sense to add the multiprocessing at component level. What kind of ideas do you have in mind?

**Comment by Mazyod** [comment]
Thanks for the response @tabergma.

Our dataset contains roughly 30,000 training sentences for English (even more for other languages), and relatively few regexes features. We are currently in the R&D phase still, so perhaps we wouldn't need this many training sentences, or perhaps we need more for our use case. However, after preparing a high end VM to do the training, this was a clear bottleneck.

RE: Changing the Data Pipeline

This sounds perfect. If the problem is tackled from the work source (i.e. data that needs to be processed), it might even be possible to design the producer/consumer pattern such that distributed workers on different machines can be listening for work, and returning the result. I'm sure that won't be feasible for the tensorflow training phase, but the design is certainly exciting.

RE: Parallelization within Components

- The most rudimentary idea I had was to implement a simple producer/consumer pipeline within the component, using `Queue`, and have the work be done using Processes/Threads. I can elaborate more if required.
- The more exciting solution I was considering was to design the pipeline itself as a stream, much similar to the idea you presented. You have a producer that can "generate" tasks, taking care of back pressure, filling up a "work queue", which is processed by the Rasa pipeline using a pool of workers (be it threads, processes, or RPC machines). Each task is has a batch of work, enough to warrant the I/O operations needed to get it to a worker, and back.

#### Final Remarks

Definitely for a quick win, adding a multiprocess/multithreading pool within the component is a clear winner. I think we need to build it anyway (even if we will throw it away later when a better solution is implemented) due to the sheer amount of time it will save us.

**Comment by tabergma** [comment]
@dakshvar22 Tagging you here as you wanted to start on updating our data pipeline. What do you think?

**Comment by tabergma** [comment]
@Mazyod It will take some more time on our end until we get to changing the data pipeline. It is definetly planned, but we just cannot say when we will start working on it. Your ideas around parallelization within components sounds interesting. However, I am not sure whether we would like to add it to Rasa Open Source as a intermediate solution. Did you already start working on it?

**Comment by Mazyod** [comment]
> @Mazyod It will take some more time on our end until we get to changing the data pipeline. It is definetly planned, but we just cannot say when we will start working on it. Your ideas around parallelization within components sounds interesting. However, I am not sure whether we would like to add it to Rasa Open Source as a intermediate solution. Did you already start working on it?

Thanks for the reply!

I didn't start working on it yet. If it's not something of interest to be merged in rasa OSS, I'll implement something quick just for our needs then, that's fine for us.

**Comment by tabergma** [comment]
@tmbo Do you think this is something that we want to maintain in Rasa Open Source?

**Comment by koernerfelicia** [comment]
@tmbo not sure if you got back to Tanja on another channel, could you clarify this for me as well, please?

**Comment by tmbo** [comment]
I don't think Tanja and I talked about this. Not sure if @dakshvar22 already started working on the data pipeline

**Comment by Ghostvv** [comment]
@tmbo I think the question is what do you think about maintaining multiprocessing for `RegexFeaturizer`?

**Comment by koernerfelicia** [comment]
@TyDunn do you have thoughts on this?

**Comment by TyDunn** [comment]
@koernerfelicia It sounds like we don't support multiprocessing at the component level at all, yet? From my perspective, it sounds like Tanja had a reasonable approach:
> We are currently thinking of changing our data pipeline so that we don't load all the data at a time, which would allow us to load bigger datasets. Keeping that in mind, I guess it makes sense to add the multiprocessing at component level. What kind of ideas do you have in mind?

We add support for multiprocessing for `RegexFeaturizer`, after we have improved loading large datasets in our data pipeline, as part of adding multiprocessing at the component level
