### ISSUE TITLE
Custom Lock Store + Multiple Sanic Workers

### ISSUE THREAD

**Issue by joeriess** [RasaHQ/rasa#6629]
**Rasa version**: 1.10.3

**Rasa SDK version** (if used & relevant):

**Rasa X version** (if used & relevant):

**Python version**: 3.7

**Operating system** (windows, osx, ...): macOS

**Issue**:

In our application we use a custom lock store since we are using a cloud based Redis instance that communicates over TLS. When trying to run multiple Sanic workers we receive this warning:

```
Unable to assign desired number of Sanic workers 4 as no `RedisLockStore` endpoint configuration has been found.
```

[Digging deeper](https://github.com/RasaHQ/rasa/blob/master/rasa/core/utils.py#L546) I see there is a check to ensure the lock store type is `'redis'`.

Can we update the logic so it is something like this?:

```python
return lock_store is not None and lock_store.type != "in_memory"
```

Thank you in advance!

**Comment by sara-tagger** [comment]
Thanks for raising this issue, @tabergma will get back to you about it soon✨

###### Please also check out the [docs](https://rasa.com/docs/) and the [forum](https://forum.rasa.com/) in case your issue was raised there too 🤗

**Comment by tabergma** [comment]
@ricwo Can you please have a look. Thanks.

**Comment by ricwo** [comment]
@joeriess thanks for raising this issue. I agree with your suggestion, multiple sanic workers should be safe to use with an in-memory tracker store as well. do you want to create a PR for that?

**Comment by akelad** [comment]
addressed by https://github.com/RasaHQ/rasa/pull/7223/files
