### ISSUE TITLE
Fix doc vector average calculation (do not use spacy implementation)

### ISSUE THREAD

**Issue by tmbo** [RasaHQ/rasa#663]
- average takes words into account that don't have a word vector
- should rather only average over elements that have a non zero vector

https://github.com/explosion/spaCy/blob/master/spacy/tokens/doc.pyx#L276
https://github.com/RasaHQ/rasa_nlu/pull/92#issuecomment-340297739

**Comment by amn41** [comment]
also I think it should be an option to do max-pooling instead of taking the average

**Comment by znat** [comment]
"option" is the good word. One might also want to exclude stop words

**Comment by wrathagom** [comment]
@tmbo did #642 address this?

**Comment by tmbo** [comment]
No I think this is still the same.

**Comment by Ghostvv** [comment]
@tabergma can you implement it in the calculation of `cls` vector?

**Comment by tabergma** [comment]
Yeah, we need to replace/adapt the following line: https://github.com/RasaHQ/rasa/blob/master/rasa/nlu/featurizers/dense_featurizer/spacy_featurizer.py#L62

**Comment by Ghostvv** [comment]
let's do it as part of tf2 refactor, while it is still hot

**Comment by Ghostvv** [comment]
and because it is quite a braking change, so might as well brake all at once
