### ISSUE TITLE
Domain should be made available for `rasa train nlu` command if it's available

### ISSUE THREAD

**Issue by dakshvar22** [RasaHQ/rasa#6635]
Part of #6638

**Rasa version**: master

**Issue**:

When issuing the command `rasa train nlu`, `train_nlu` is invoked inside `rasa/train.py` which does not have access to the domain. Since `responses` key can be defined in the domain file as well which may be needed for the response selector training, the file importer should get access to the domain as well if its available. Once that's done `responses` will be sync'ed with the NLU training data which was added as part of https://github.com/RasaHQ/rasa/pull/6591.

Without this, currently running `rasa train nlu` with `ResponseSelector` in the pipeline will lead to warnings such as -
```
Your training data contains an example 'What is your name?...' for the chitchat/ask_name intent. You either need to add a response phrase or correct the intent for this example in your training data. If you intend to use Response Selector in the pipeline, the training may fail.
```
because these response templates were defined under the `responses` key in the domain file.

`rasa train` command works completely fine.

**Command or request that led to error**:
```
rasa train nlu
```

**Comment by wochinge** [comment]
fixed by https://github.com/RasaHQ/rasa/pull/6913
