### ISSUE TITLE
Running Validator without ignoring warnings will fail silently

### ISSUE THREAD

**Issue by ortsaCniveK** [RasaHQ/rasa#6652]
**Rasa version**: 2.0.0a4

**Rasa SDK version** (if used & relevant): 2.0.0a4

**Rasa X version** (if used & relevant): n/a

**Python version**: 3.8.2

**Operating system** (windows, osx, ...): Linux-5.4.0-45-generic-x86_64-with-glibc2.29

**Issue**:
Running `Validator.verify_nlu(ignore_warnings=False)` ([which I think needs to be renamed to `verify_all()` as I've mentioned here](https://github.com/RasaHQ/rasa/issues/6070#issuecomment-691393647)) will return False without providing logs (unless you enable debug logs.  It seems as though in the following functions:

- [`verify_intents()`](https://github.com/RasaHQ/rasa/blob/84db4cd5267c20ae755affa4ce2deaa3dc5b0185/rasa/validator.py#L52)
- [`verify_intents_in_stories()`](https://github.com/RasaHQ/rasa/blob/84db4cd5267c20ae755affa4ce2deaa3dc5b0185/rasa/validator.py#L122)
- [`verify_utterances()`](https://github.com/RasaHQ/rasa/blob/84db4cd5267c20ae755affa4ce2deaa3dc5b0185/rasa/validator.py#L144)
- [`verify_utterances_in_stories()`](https://github.com/RasaHQ/rasa/blob/84db4cd5267c20ae755affa4ce2deaa3dc5b0185/rasa/validator.py#L200)

`logger.debug` is used instead of `logger.warning` or `rasa.shared.utils.io.raise_warning`.  These are minor logs that are suppressed but nonetheless will still cause a silent failure, so I'm not sure if it's necessary to fail on these debug level issues.

**Error (including full traceback)**:
```
N/A
```

**Command or request that led to error**:
```
rasa data validate (in my case I was using the Validator class directly)
```

**Comment by sara-tagger** [comment]
Thanks for raising this issue, @melindaloubser1 will get back to you about it soon✨

###### Please also check out the [docs](https://rasa.com/docs/) and the [forum](https://forum.rasa.com/) in case your issue was raised there too 🤗
