### ISSUE TITLE
Batch Prediction API

### ISSUE THREAD

**Issue by sahinbatmaz** [RasaHQ/rasa#6654]
**Description of Problem**:

I am pointing my feature request in NLU part. '/model/parse' api produces results one by one.

To shorten the response time, a batch prediction can be used. Especially, classifier layers take the most of the time and these models are capable of predicting batches of data.

**Overview of the Solution**:

An additional function can be added to 'Component' class as 'process_batch'. It can take a list of text as input, and in the response it produces results for each.

Or, if the input of 'process' function is not only one message but a list of messages, the process function can produce outputs.

For these things, /model/parse api should be updated or a new api should be introduced.

**Comment by sara-tagger** [comment]
Thanks for submitting this feature request 🚀 @akelad will get back to you about it soon! ✨

**Comment by sahinbatmaz** [comment]
Any updates on this issue?

**Comment by dakshvar22** [comment]
@sahinbatmaz Thanks for suggesting this. Although, this makes sense from a technical perspective as it could speed up inference in some cases but not really for use cases Rasa Open Source focusses on.
What's your exact use case for doing batch inferencing in Rasa Open Source?

**Comment by youmaa** [comment]
Any updates? For a use case, in my case, I needed this to apply an interpretability model based on prediction probabilities

**Comment by akelad** [comment]
Could you elaborate a bit? As in, is it in the context of building a bot?

**Comment by akelad** [comment]
Could you elaborate a bit? As in, is it in the context of building a bot?

**Comment by youmaa** [comment]
@akelad sorry for the late reply
it's actually after building a bot, I wanna apply an interpretability model (LIME for example) and it needs to make batch prediction from a performance perspective

**Comment by Ghostvv** [comment]
It is not a research issue, I moved it to `Enable` board
