### ISSUE TITLE
Configuration with CRFEntityExtractor after DIET gives zero entity scores

### ISSUE THREAD

**Issue by MajaRolevski** [RasaHQ/rasa#6662]
**Rasa version**: 1.10.7

**Python version**: 3.7

**Operating system**: Ubuntu 18

**Issue**:  I am using DIET for intent classification and CRFEntityExtractor for entity extraction in a way shown in the configuration file - first component is DIET, after which CRFEntityExtractor comes. The training finishes properly, but after testing the model (rasa test nlu) I get all zero scores (precision, recall, f1 score) for all entities.

However, if I switch places of DIET and CRFEntityExtractor, so that CRFEntityExtractor comes first and after it DIET, everything works fine.

Could you please tell me why is this happening? Do you have some advice on how to order these two components?

Any help would be appreciated. 

**Content of configuration file (config.yml)**:
```
language: en
pipeline:
 - name: WhitespaceTokenizer
- name: "CountVectorsFeaturizer"
  analyzer: 'word'
- name: "CountVectorsFeaturizer"
  analyzer: char_wb
  min_ngram: 1
  max_ngram: 4
- name: "DIETClassifier"
  random_seed: 42
  intent_classification: True
  entity_recognition: False
  epochs: 10
  learning_rate: 0.0002
  embedding_dimension: 60
  number_of_transformer_layers: 1
  batch_size: 64
  hidden_layer_sizes:
  text: [256, 128]
-name: "CRFEntityExtractor"
  "BILOU_flag": True
  "features": 
    [
    [
        "prefix5",
        "prefix2",
        "suffix5",
        "suffix3",
        "suffix2",
        "digit"
    ],
    [
        "prefix5",
        "prefix2",
        "suffix5",
        "suffix3",
        "suffix2",
        "digit"
    ],
    [
        "bias",
        "prefix5",
        "prefix2",
        "suffix5",
        "suffix3",
        "suffix2",
        "digit"
    ],
    [
        "bias",
        "low",
        "prefix5",
        "prefix2",
        "suffix5",
        "suffix3",
        "suffix2",
        "title",
        "digit",
        "pattern"
    ],
    [
        "bias",
        "prefix5",
        "prefix2",
        "suffix5",
        "suffix3",
        "suffix2",
        "digit"
    ],
    [
        "prefix5",
        "prefix2",
        "suffix5",
        "suffix3",
        "suffix2",
        "digit"
    ],
    [
        "prefix5",
        "prefix2",
        "suffix5",
        "suffix3",
        "suffix2",
        "digit"
    ]
    ]
```

**Comment by sara-tagger** [comment]
Thanks for the issue, @erohmensing will get back to you about it soon!

###### You may find help in the [docs](https://rasa.com/docs/) and the [forum,](https://forum.rasa.com/) too 🤗

**Comment by tabergma** [comment]
@MajaRolevski Thanks for raising the issue. I have some problems reproducing the issue. I trained the `formbot` example (`examples/formbot`), which has some entities, with the config you shared via `rasa train nlu` and tested it afterwards with `rasa test nlu`. The `results/CRFEntityExtractor_report.json` file contains proper values for all metrics. 
Can you maybe share a minimal example whic his not working so that I can have a closer look? Thanks.

**Comment by Ghostvv** [comment]
@MajaRolevski did you manage to make it work? Otherwise would it be possible for you to share an example that illustrates this problem?

**Comment by MajaRolevski** [comment]
Dear @tabergma and @Ghostvv , thank you for your answers. Also, sorry for my delay. In the meantime, I managed to make it work. The problem was the number of epochs, which was too small for my dataset.
