### ISSUE TITLE
The button message is incorrectly interpreted in shell mode if text contains parentheses

### ISSUE THREAD

**Issue by tocosastalo** [RasaHQ/rasa#6664]
**Rasa version**: 1.10.11

**Python version**: 3.7.9

**Operating system**: Docker (linux)

**Issue**: The button with the text message containing the parentheses with text is incorrectly interpreted in `shell` mode. The text in parentheses is treated as a new message instead of a payload.

**Command or request that led to error**:

 rasa shell --debug

**Content of domain file (domain.yml)** (if relevant):

<pre> utter_detail:

*   text: 'What exactly are you interested?'
     buttons:
*   title: 'fo (xxxxxxxxxxx)'
     payload: '/greet'</pre>

**Example**

<pre>? What exactly are you interested? (Use arrow keys)
 » 1: fo (xxxxxxxxxxx) (/greet)

// selecting option
 ? What exactly are you interested? 1: fo (xxxxxxxxxxx) (/greet)

// debug message
 2020-09-14 16:41:18 DEBUG rasa.core.processor - Received user message 'xxxxxxxxxxx' with intent 
 '

 {'name': 'button_sending_documents_via_post_or_email', 'confidence': 0.5877927541732788} 

' and entities '[]'

// expected
 2020-09-14 16:41:18 DEBUG rasa.core.processor - Received user message '/greet' with intent 
 '

 {'name': 'greet', 'confidence': 1} 

' and entities '[]'</pre>

**Comment by sara-tagger** [comment]
Thanks for the issue, @b-quachtran will get back to you about it soon!

###### You may find help in the [docs](https://rasa.com/docs/) and the [forum,](https://forum.rasa.com/) too 🤗
