### ISSUE TITLE
Update Rasa Kafka event broker producer code to support SASL_SSL and PLAINTEXT protocols

### ISSUE THREAD

**Issue by HariTeneti** [RasaHQ/rasa#6677]
**Rasa version**: 1.10.12

**Rasa SDK version** (if used & relevant): 1.10.2

**Rasa X version** (if used & relevant): 0.32.2

**Python version**: Python 3.6

**Operating system** (windows, osx, ...): CentOS Linux 7

**Issue**:
RasaX supports SASL_SSL and PLAINTEXT protocols but not RASA. 

**Error (including full traceback)**:
```
No error. RasaX was recently updated to support SASL_PLAINTEXT and SASL_SSL (https://github.com/RasaHQ/rasa/issues/6539). Noticed some inconsistencies between RasaX and RasaCore for KAFKA Protocol support. RASA open-source code is missing support for SASL_SSL and PLAINTEXT protocols whereas RasaX supports these protocols. Usually, in a development environment, we would like to use PLAINTEXT Protocols and in production SASL_PLAINTEXT or SASL_SSL. 
```

**Command or request that led to error**:
```

```

**Content of configuration file (config.yml)** (if relevant):
```yml

```

**Content of domain file (domain.yml)** (if relevant):
```yml

```

**Comment by sara-tagger** [comment]
Thanks for the issue, @melindaloubser1 will get back to you about it soon!

###### You may find help in the [docs](https://rasa.com/docs/) and the [forum,](https://forum.rasa.com/) too 🤗

**Comment by melindaloubser1** [comment]
@HariTeneti It looks like Rasa supports `SSL` and `SASL_PLAINTEXT` -  https://github.com/RasaHQ/rasa/blob/d44f23ef2037c531190cbf653a6f5c15424e7bce/rasa/core/brokers/kafka.py#L51-L61

In your issue description, do you mean Rasa should also support `SASL_SSL` and regular `PLAINTEXT` ? That's what I gottfrom the title, but I wasn't sure based on the description
>RasaX supports SASL_SSL and PLAINTEXT protocols but not RASA.

**Comment by HariTeneti** [comment]
Yes, please update Rasa to support SASL_SSL and regular PLAINTEXT. Thank you.
