### ISSUE TITLE
RASA taking too long to run on Google Colab

### ISSUE THREAD

**Issue by aoduru** [RasaHQ/rasa#6679]
**Rasa version**: 

**Rasa SDK version** (if used & relevant):

**Rasa X version** (if used & relevant):

**Python version**: 3.7

**Operating system** (windows, osx, ...): MacOS

**Issue**:

**Error (including full traceback)**:
```
No error, RASA just times out on Google Colab
```

**Command or request that led to error**:
```
from rasa_nlu.training_data import load_data
from rasa_nlu.config import RasaNLUModelConfig
from rasa_nlu.model import Trainer

training_data = load_data('nlu.md')
pipeline = [{"name": "nlp_spacy"}, 
            {"name": "tokenizer_spacy"}, 
            {"name": "intent_featurizer_spacy"},  
            {"name": "intent_classifier_sklearn"}]
trainer = Trainer(RasaNLUModelConfig({"pipeline": pipeline}))
interpreter = trainer.train(training_data)
model_directory = trainer.persist('./projects/default/')
```

**Content of configuration file (config.yml)** (if relevant):
```yml

```

**Content of domain file (domain.yml)** (if relevant):
```yml

```

**Comment by sahinbatmaz** [comment]
On Google Colab, tensorflow version 2.3.0 or more is already installed.

Rasa 1.10.10 works on tensorflow 2.1.1, and does not work on 2.3.0 .

When you install rasa on Colab, it does not downgrade tensorflow.

You need to downgrade it manually with ` !pip install tensorflow==2.1.1 `.

**Comment by sahinbatmaz** [comment]
Additionally, Colab provides GPU but the provided CPU is very low. It only provides 1 or 2 CPUs which is very low. It might slow down operations around 10x times compared to 8-12 CPU cores.

**Comment by aoduru** [comment]
Also; when I run the following command to get rasa core:
`!pip install rasa_core;`

I get the RASA core version 0.14.5. How do I install rasa_core on Colab to get the 1.10.10 version?

**Comment by sara-tagger** [comment]
Thanks for the issue, @akelad will get back to you about it soon!

###### You may find help in the [docs](https://rasa.com/docs/) and the [forum,](https://forum.rasa.com/) too 🤗

**Comment by aoduru** [comment]
I fixed the previous problem by installing rasa instead of rasa_core and got the 1.10 version. The only problem is that I'm not quite sure how to change how I'm training the NLU model. The code I have is as follows:

`from rasa.core.policies.keras_policy import KerasPolicy
from rasa.core.agent import Agent

Agent()
agent = Agent('domain.yml', policies=[KerasPolicy()])
training_data = agent.load_data('stories.md')

agent.train(
      training_data,
      validation_split=0.0
)

agent.persist('models/dialogue')`

Now I'm getting the following TypeError:
`TypeError: 'coroutine' object is not iterable`

**Comment by akelad** [comment]
Hey @aoduru where did you get the code originally for google colab? That is a very old rasa verison. You can take a look at how to train a model [here](https://rasa.com/docs/rasa/jupyter-notebooks#train-a-model) via python code.
I'm going to close this issue as it's more of a usage question. If you need more help, please ask on our community [forum](https://forum.rasa.com)
