### ISSUE TITLE
NLU FallbackClassifier should have some measure of a confidence of fallback

### ISSUE THREAD

**Issue by Ghostvv** [RasaHQ/rasa#6685]
Right now, FallbackClassifier substitute intent with `nlu_fallback` with confidence `1`, however its confidence value should mimic the fact how confident we are that it is indeed fallback.

**Comment by melindaloubser1** [comment]
It could be inversely proportional to the confidence for the original predicted intent?

**Comment by Ghostvv** [comment]
by inversely do you mean `1-...`?

**Comment by Ghostvv** [comment]
I was thinking the same

**Comment by melindaloubser1** [comment]
Yep.

**Comment by koaning** [comment]
I'll keep this in mind for https://github.com/RasaHQ/rasa-nlu-examples/pull/50 too.

**Comment by Ghostvv** [comment]
@koaning but in your case you actually have confidence in your fasttextclassifier, no?

**Comment by koaning** [comment]
> @koaning but in your case you actually have confidence in your fasttextclassifier, no?

FastText does supply some numbers but they aren't properly added yet to the message. This is a reminder for me to make sure that before I merge that it is consistent with the implementation here.

**Comment by Ghostvv** [comment]
but I think it is independent, e.g. in nlu fallback classifier we have confidence, it is just `1`

**Comment by koaning** [comment]
Isn't this issue about changing that?

**Comment by Ghostvv** [comment]
I think there is some misunderstanding here. What I mean is that I don't see how changing this `1` will affect your custom component
