### ISSUE TITLE
the function: training_states_and_actions under class TrackerFeaturizer, does not return anything. 

### ISSUE THREAD

**Issue by victorbai2** [RasaHQ/rasa#6686]
**Rasa version**: 1.2.9

**Rasa SDK version** (if used & relevant):

**Rasa X version** (if used & relevant):

**Python version**:
3.7
**Operating system** (windows, osx, ...):
windows
**Issue**:
When I check the KerasPolicy in the code, and walk through the Class and functions, I found out that the function: training_states_and_actions under class TrackerFeaturizer, does not return anything. 

I just wonder that if it does not return anything, how kerasPolicy takes in the input training_data?

**Error (including full traceback)**:
```
NotImplementedError: Featurizer must have the capacity to encode trackers to feature vectors

```

<img width="381" alt="bug" src="https://user-images.githubusercontent.com/46184469/93319053-0134f800-f842-11ea-89bc-249de3f16f6d.PNG">

**Comment by sara-tagger** [comment]
Thanks for raising this issue, @JustinaPetr will get back to you about it soon✨

###### Please also check out the [docs](https://rasa.com/docs/) and the [forum](https://forum.rasa.com/) in case your issue was raised there too 🤗

**Comment by JustinaPetr** [comment]
Hi @victorbai2. Looks like you are using a very old version of Rasa. Is there a reason for that?
