### ISSUE TITLE
Expand custom slot type docs

### ISSUE THREAD

**Issue by JEM-Mosig** [RasaHQ/rasa#6692]
**Description of Problem**:
The docs on [custom slot types](https://rasa.com/docs/rasa/core/slots/#custom-slot-types) are somewhat misleading. 

**Overview of the Solution**:
It would be great to have
1. And explicit mention of the fact that you have to implement these slots separately, not as code in your custom actions script, and specify their module path in your domain.
2. Add an example of where to put that code (or better how to write a simple third party module for that), and
3. What the domain file should look like and what the new slot type is called there

**Definition of Done**:
- [ ] Feature described the docs

**Comment by JEM-Mosig** [comment]
Fede found out how to do this. 
1. Create an `addons.py` file (name arbitrary) in you bot's directory
2. In that file add the custom slot code
3. Refer to the custom slot in the domain as `type: addons.MyCustomSlotClassName`

**Comment by wochinge** [comment]
closed by https://github.com/RasaHQ/rasa/pull/7646
