### ISSUE TITLE
Story Structure validation should include a check against max number of predictable actions

### ISSUE THREAD

**Issue by kevinthemself** [RasaHQ/rasa#6695]
**Description of Problem**:

I've run into issues similar to <span class="error">[this| ]</span> whereby I've created stories with more than 10 actions after a given intent. While it was easy to find during runtime, I think that data validation scripts should catch any stories that train the model to queue up more than 10 actions after any given intent.

Perhaps they could give a warning (as they do during runtime) that a certain story will not work properly?

**Overview of the Solution**:

Add a check in the data validator to check for stories that have more than 10 predicted actions

**Examples** (if relevant):

This log which only appears during runtime:

 2020-09-14 02:58:26 WARNING rasa.core.processor - Circuit breaker tripped. Stopped predicting more actions for sender 'default'.

[This issue demonstrates it's an easy pitfall for users](https://github.com/RasaHQ/rasa/issues/2157)

[Additionally these forum posts have similar confusion](https://forum.rasa.com/search?q=Circuit%20Breaker%20tripped)

Something else I've noticed is that for myself I have stories that look like (I'm on Rasa 1.10.7):

<pre>## some story

*   trigger_10

*   utter_something_1
*   utter_something_2
*   utter_something_3
*   utter_something_4
*   utter_something_5
*   utter_something_6
*   utter_something_7
*   utter_something_8
*   utter_something_9
*   utter_something_10
*   utter_something_11 
*   utter_something_12</pre>

However, if I send any message (regardless of predicted intent), it will still queue up `utter_something_11` and `utter_something_12`. This story is mostly run with the `AugmentedMemoizationPolicy` (with a Max history of 10) based off the logs, but after the message, the `KerasPolicy` will take over.

**Blockers** (if relevant):

**Definition of Done**:

*   [ ] Add test to Rasa Validator class for story with more than 10 actions
*   [ ] Add story structure warning log for any story that exceeds the [MAX_NUMBER_OF_PREDICTIONS](https://github.com/RasaHQ/rasa/blob/2bba301212cc1fbb725628bdc0cf8d515e8fecd7/rasa/core/processor.py#L51) constant
*   [ ] story structure check is mentioned in documentation
*   [ ] story structure check is mentioned in the change log

**Comment by sara-tagger** [comment]
Thanks for submitting this feature request 🚀 @erohmensing will get back to you about it soon! ✨

**Comment by erohmensing** [comment]
@ortsaCniveK thanks for bringing this up, it sounds like a valuable addition. Would you like to contribute it?

**Comment by ortsaCniveK** [comment]
Sure!  I'm doing a bunch of Rasa contributions in the spirit of Hacktoberfest, so you'll see those soon :)

**Comment by erohmensing** [comment]
Awesome, I'll add it to the contributor board 🎸

**Comment by joejuzl** [comment]
Hi @ortsaCniveK, any progress with this?
