### ISSUE TITLE
rasax can not display multi dispatcher in an interactive, but rasa shell can display multi dispatcher result

### ISSUE THREAD

**Issue by rejae** [RasaHQ/rasa#6696]
**Rasa version**:1.10.9

**Rasa SDK version** (if used & relevant):

**Rasa X version** (if used & relevant):0.32.2 & 0.32.0 both test

**Python version**:3.7.7

**Operating system** (windows, osx, ...): windows

**Issue**:
rasax can not display multi dispatcher in an interactive, but rasa shell can display multi dispatcher result
but my proceduer is going well

**Error (including full traceback)**:
```

```

**Command or request that led to error**:
```

```

**Content of configuration file (config.yml)** (if relevant):
```yml

```

**Content of domain file (domain.yml)** (if relevant):
```yml

```

**Comment by rejae** [comment]
hi, I don't provide config, domain etc, files because I do test in offical examples, I write twice code in an simple action, and do test in rasa x, and get only first dispatcher, can someone help me figure out what happend in rasa x
class ActionGreet(Action):
    def name(self) -> Text:
        return "action_greet"

    def run(self,
            dispatcher: CollectingDispatcher,
            tracker: Tracker,
            domain: Dict[Text, Any]):
        dispatcher.utter_message("11111111111111")
        dispatcher.utter_message("22222222222222")
        return []

**Comment by sara-tagger** [comment]
Thanks for raising this issue, @JustinaPetr will get back to you about it soon✨

###### Please also check out the [docs](https://rasa.com/docs/) and the [forum](https://forum.rasa.com/) in case your issue was raised there too 🤗

**Comment by JustinaPetr** [comment]
Hi @rejae. I can't reproduce the issue. Can you confirm that the custom action server is running and could you check the logs for any errors with your custom action?

**Comment by rejae** [comment]
I get the first dispatcher message '1111111111111111111', but '222222222222222222' is  not shown. 
I  run rasa x --debug, found the two utter_message info  as follow:

`DEBUG:rasax.community.services.event_service:Saving event from origin 'production' to event service:
{"sender_id": "4135613702cb47dbaa92da0973c237cf", "event": "bot", "timestamp": 1600661392.78481, "text": "11111111111111", "data": {"elements": null, "quick_replies": null, "buttons": null, "attachment": null, "image": null, "custom
": null}, "metadata": {}}
DEBUG:rasax.community.database.utils:Turned SQLite foreign key enforcement on.
DEBUG:rasax.community.database.utils:Turned on SQLite WAL mode.
DEBUG:rasax.community.services.analytics_service:Saving to AnalyticsService:
{"sender_id": "4135613702cb47dbaa92da0973c237cf", "event": "bot", "timestamp": 1600661392.78481, "text": "11111111111111", "data": {"elements": null, "quick_replies": null, "buttons": null, "attachment": null, "image": null, "custom
": null}, "metadata": {}}
DEBUG:rasax.community.database.utils:Turned SQLite foreign key enforcement on.
DEBUG:rasax.community.database.utils:Turned on SQLite WAL mode.
DEBUG:rasax.community.services.event_service:Saving event from origin 'production' to event service:
{"sender_id": "4135613702cb47dbaa92da0973c237cf", "event": "bot", "timestamp": 1600661392.78481, "text": "22222222222222", "data": {"elements": null, "quick_replies": null, "buttons": null, "attachment": null, "image": null, "custom
": null}, "metadata": {}}
DEBUG:rasax.community.database.utils:Turned SQLite foreign key enforcement on.
DEBUG:rasax.community.database.utils:Turned on SQLite WAL mode.
WARNING:rasax.community.services.event_consumers.event_consumer:Saving event failed due to an 'IntegrityError'. This means that the event is already stored in the database. The event data was '{"sender_id": "4135613702cb47dbaa92da09
73c237cf", "event": "bot", "timestamp": 1600661392.78481, "text": "22222222222222", "data": {"elements": null, "quick_replies": null, "buttons": null, "attachment": null, "image": null, "custom": null}, "metadata": {}}'. (sqlite3.In
tegrityError) UNIQUE constraint failed: conversation_event.conversation_id, conversation_event.timestamp, conversation_event.type_name
[SQL: INSERT INTO conversation_event (conversation_id, type_name, timestamp, intent_name, action_name, slot_name, slot_value, policy, is_flagged, data, evaluation, rasa_environment) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)]
[parameters: ('4135613702cb47dbaa92da0973c237cf', 'bot', 1600661392.78481, None, None, None, None, None, 0, '{"sender_id": "4135613702cb47dbaa92da0973c237cf", "event": "bot", "timestamp": 1600661392.78481, "text": "22222222222222",
"data": {"elements": null, "quick_replies": null, "buttons": null, "attachment": null, "image": null, "custom": null}, "metadata": {}}', None, 'production')]
`

**Comment by JustinaPetr** [comment]
I think this might be a windows related problem @rejae . To confirm that, would you be able to run your assistant in a VM?
