### ISSUE TITLE
InvalidUsage(“Failed when parsing body as json”) when trying to train

### ISSUE THREAD

**Issue by mrcartier** [RasaHQ/rasa#6705]
**Rasa version**: 1.10.11

**Python version**: 3.6.9

**Operating system**: Ubuntu 18.04

**Issue**: unable to train using json data

**Error (including full traceback)**:

 <span class="error">[2020-09-17 14:53:23 +0000]</span> <span class="error">[3651]</span> <span class="error">[ERROR]</span> Exception occurred while handling uri: 'http://localhost:5005/model/train'
 Traceback (most recent call last):
 File "/home/cartier/Documents/rasa/lib/python3.6/site-packages/sanic/request.py", line 173, in load_json
 self.parsed_json = loads(self.body)
 ValueError: Expected object or value

 During handling of the above exception, another exception occurred:

 Traceback (most recent call last):
 File "/home/cartier/Documents/rasa/lib/python3.6/site-packages/sanic/app.py", line 976, in handle_request
 response = await response
 File "/usr/lib/python3.6/asyncio/coroutines.py", line 110, in __next__
 return self.gen.send(None)
 File "/home/cartier/Documents/rasa/lib/python3.6/site-packages/rasa/server.py", line 180, in decorated
 result = await result
 File "/usr/lib/python3.6/asyncio/coroutines.py", line 110, in __next__
 return self.gen.send(None)
 File "/home/cartier/Documents/rasa/lib/python3.6/site-packages/rasa/server.py", line 757, in train
 rjs = request.json
 File "/home/cartier/Documents/rasa/lib/python3.6/site-packages/sanic/request.py", line 167, in json
 self.load_json()
 File "/home/cartier/Documents/rasa/lib/python3.6/site-packages/sanic/request.py", line 177, in load_json
 raise InvalidUsage("Failed when parsing body as json")
 sanic.exceptions.InvalidUsage: Failed when parsing body as json

**Command or request that led to error**:

 r = requests.post('http://localhost:5005/model/train', data=test_json)

 test_json = {
 "rasa_nlu_data": {
 "common_examples": [

 { "intent": "sad", "text": "I am not happy with the service" } 

,

 { "intent": "praise", "text": "You're a genius" } 

 ],
 "regex_features": [],
 "lookup_tables": [],
 "entity_synonyms": []
 }
 }

*   *   *   when I attempt to using empty json it's the same error ***

 test_json = {
 "rasa_nlu_data": 

 { "common_examples": [], "regex_features" : [], "lookup_tables" : [], "entity_synonyms": [] } 

 }

The json format is taken from the [docs found here](https://rasa.com/docs/rasa/nlu/training-data-format/) so as best I can tell it's valid...

**Comment by sara-tagger** [comment]
Thanks for the issue, @tabergma will get back to you about it soon!

###### You may find help in the [docs](https://rasa.com/docs/) and the [forum,](https://forum.rasa.com/) too 🤗

**Comment by tabergma** [comment]
@mrcartier Please take a look at the [API spec](https://rasa.com/docs/rasa/pages/http-api#operation/trainModel). Can you try using the example given there? Is it working?

**Comment by mrcartier** [comment]
Hey @tabergma just tried & It's the same error. At first it kept telling me that false was undefined from `"force": false,
"save_to_default_model_directory": true` but when I changed it to `"force": False,` the error came back. I also made false into a string `"force": "false",` just to see if it would work but the error remains.

**Comment by tabergma** [comment]
Can you please take a look at [this froum thread](https://forum.rasa.com/t/error-in-http-post-requests-restfulapi/12625/7) and check if it helps?

**Comment by mrcartier** [comment]
The response I got was `{"version":"1.10.12","status":"failure","message":"The training request is missing the required key `config`.","reason":"BadRequest","details":{"parameter":"config","in":"body"},"help":null,"code":400}`. 

I guess they were using an earlier rasa version because that forum [links to an article](https://towardsdatascience.com/a-beginners-guide-to-rasa-nlu-for-intent-classification-and-named-entity-recognition-a4f0f76b2a96) originally dated 6/28/19. According to the article you should be able to obtain a json result indicating the intent and confidence level? So I tried to put backslashes (`\`) in my original json requests but I could never get it valid with all the brackets/braces...

**Comment by tabergma** [comment]
Does it work if you run the following steps?

1. `rasa init --no-prompt`
2. `rasa run --enable-api --cors *`
3. in a separate terminal window: `curl localhost:5005/model/parse -d "{\"text\":\"hello\"}"`

**Comment by mrcartier** [comment]
Yes that's successful. I get `{"text":"\/hello","intent":{"name":"hello","confidence":1.0},"intent_ranking":[{"name":"hello","confidence":1.0}],"entities":[]}`. The previous attempts came from using the requests library so do you think that's the issue (converting cURL command to python request) or is there more to it...

**Comment by mrcartier** [comment]
just for the bot. No reply since 9/30/20....
