### ISSUE TITLE
Port back patch "remove bilou tag prefix from role and group labels" to Rasa 1.x

### ISSUE THREAD

**Issue by howl-anderson** [RasaHQ/rasa#6707]
**Rasa version**: 1.10.12

**Issue**: extract entities with roles and groups failed since there is a bug related to the BILOU tag scheme.

patch "remove bilou tag prefix from role and group labels" (commit id: 3ede6f650cd19c542a0f18291338944d2d41205d) by @tabergma 14 days ago fixed this bug in 2.x, but this bug still exists in 1.x (at least  v1.10.12), so please port back the patch to 1.x

**Comment by sara-tagger** [comment]
Thanks for raising this issue, @JustinaPetr will get back to you about it soon✨

###### Please also check out the [docs](https://rasa.com/docs/) and the [forum](https://forum.rasa.com/) in case your issue was raised there too 🤗
