### ISSUE TITLE
Tutorial Link not working in Readme.md

### ISSUE THREAD

**Issue by yashrajjain726** [RasaHQ/rasa#6708]
The link provided in the rasa readme.md file for the tutorial part is not working.

**Comment by sara-tagger** [comment]
Thanks for the issue, @tmbo will get back to you about it soon!

###### You may find help in the [docs](https://rasa.com/docs/) and the [forum,](https://forum.rasa.com/) too 🤗

**Comment by tmbo** [comment]
Thanks a lot for reporting this - we are currently rolling out our new docs - should be fixed 🙂
