### ISSUE TITLE
Entity detection in End to End testing fails when multiple entity extractors both extract the same entity

### ISSUE THREAD

**Issue by Plurno** [RasaHQ/rasa#6712]
**Rasa version**: 1.10.9 **Rasa SDK version** (if used & relevant):

**Rasa X version** (if used & relevant):

**Python version**: 3.7.7 **Operating system** (windows, osx, ...): Debian GNU/Linux 10 (buster) **Issue**: Here is an example of an End to End test that I put in my tests/conversation_tests.md file.

1.  1.  Foreign language story

*   greet: hi

*   action_greet
*   rewind

*   ask_book: Are there any books in <span class="error">[french]</span>(foreign_language)?

*   utter_ask_book

When I run rasa test, I get the following result in results/failed_stores.md:

1.  1.  Foreign language story

*   greet: hi

*   action_greet
*   rewind

*   ask_book: Are there any books in <span class="error">[french]</span>(foreign_language)? \

*   utter_ask_book

I think what’s happening is that I have two entity extractors (DIETClassifier and CRFEntityExtractor) that are both independently finding the ‘french’ foreign_language entity, so it gets duplicated when the test is run. It's not a huge deal, but it's impacting my CI/CD pipeline a bit.

Thanks

**Error (including full traceback)**:

 No runtime error, just a failed line in a failed_stories.md

**Command or request that led to error**:

 rasa test

**Content of configuration file (config.yml)** (if relevant):

**Content of domain file (domain.yml)** (if relevant):

**Comment by sara-tagger** [comment]
Thanks for the issue, @erohmensing will get back to you about it soon!

###### You may find help in the [docs](https://rasa.com/docs/) and the [forum,](https://forum.rasa.com/) too 🤗

**Comment by samsucik** [comment]
Hi @Plurno, could you share your config file (or at least the relevant parts of it)? If you suspect that this is due to 2 extractors extracting the same entity, have you tried disabling one of them (let's say Duckling)? Do you intentionally use both for the `foreign_language` entity? I hope I'll be better able to help once I know more :-)

**Comment by carlosmeds** [comment]
Hi there! I had the same issue here and I kind solved it disabling CRFEntityExtractor. I think it has something to do with @samsucik comment.
