### ISSUE TITLE
Rasa not added to path

### ISSUE THREAD

**Issue by Ierezell** [RasaHQ/rasa#6726]
Rasa Version : 2.0.0rc1
Rasa SDK Version : 2.0.0rc1
Rasa X Version : None
Python Version : 3.8.5 (default, Sep  5 2020, 10:50:12) 
Operating System : Linux-5.8.10-zen1-1-zen-x86_64-with-glibc2.2.5
Python Path : /usr/bin/python

**Issue**: Rasa is not added to path, thus all the command rasa xxx are not found 
**Error (including full traceback)**:
```
rasa xxx -> zsh: command not found: rasa
```

**Command or request that led to error**:
```
rasa xxx
```

**More informations** : I've seen that I would be able to install rasa with python 3.8 sce it's written in the docs. 
So I did install rasa without problems (and without venv with tensorflow 2.3.0) on my laptop (archlinux kernel zen 5.8.10).

It's a minor problem since I can still use `python -m rasa xxx` to launch the desired commands. 
However, it would be nice to have rasa in path when installing without venv so one could launch rasa commands

**Comment by sara-tagger** [comment]
Thanks for raising this issue, @amn41 will get back to you about it soon✨

###### Please also check out the [docs](https://rasa.com/docs/) and the [forum](https://forum.rasa.com/) in case your issue was raised there too 🤗

**Comment by itcuihao** [comment]
@Ierezell Confirm your python library path. such as '/Users/****/Library/Python/3.8/bin'  need to join path. 
`export PATH=$PATH:/Users/****/Library/Python/3.8/bin`
