### ISSUE TITLE
Rasa data validation not updated for new ResponseSelector format

### ISSUE THREAD

**Issue by b-quachtran** [RasaHQ/rasa#6728]
**Rasa version**: 2.0.0rc1

**Rasa SDK version** (if used & relevant):

**Rasa X version** (if used & relevant):

**Python version**:

**Operating system** (windows, osx, ...):

**Issue**:

The new ResponseSelector format (#6591) breaks Rasa data validation command since the new format does not require response selector actions (e.g. `utter_chitchat`) to be added to the domain file. 

**Error (including full traceback)**:
```
UserWarning: The action 'utter_faq' is used in the stories, but is not a valid utterance action. Please make sure the action is listed in your domain and there is a template defined with its name.
  More info at https://rasa.com/docs/rasa/actions#utterance-actions
Project validation completed with errors.
```

**Command or request that led to error**:
```
rasa data validate
```

**Content of configuration file (config.yml)** (if relevant):
```yml

```

**Content of domain file (domain.yml)** (if relevant):
```yml

```

**Comment by m-vdb** [comment]
I'll take a look at this one this week
