### ISSUE TITLE
Run training fingerprinting via the CLI

### ISSUE THREAD

**Issue by b-quachtran** [RasaHQ/rasa#6729]
**Description of Problem**:

Request to be able to create `fingerprint.json` file via the CLI without having to run `rasa train`. Feature will make it easier to run CI checks against Rasa assistant code changes. 

**Overview of the Solution**:

Exposing a CLI command to generate `fingerprint.json`, something along the lines of `rasa fingerprint` or `rasa train --fingerprint`

**Examples** (if relevant):

**Blockers** (if relevant):

**Definition of Done**:

**Comment by TyDunn** [comment]
@tmbo Is this something we could include in 2.0? [NIB has been asking for this for a while](https://rasa-hq.slack.com/archives/C0148JNFXLG/p1592267651000100), and I think something like it makes sense. The workflow for checking if a model needs to be trained is cumbersome right now because you have to diff check the config, training data, domain file, and Rasa version today

**Comment by tmbo** [comment]
yes I think this should be easy enough to add and I'd agree this does seem useful.

**Comment by m-vdb** [comment]
decided to add this to 2.1 milestone, as it's a new feature and shouldn't be release blocking for 2.0

**Comment by b-quachtran** [comment]
@TyDunn Is there any update on this? The same customer is asking about this feature again, but it looks like it's been pushed to the 2.2 milestone.

**Comment by TyDunn** [comment]
@b-quachtran There wre quite a bit of improvements we need to make smoothen out friction caused by 2.0, so we decided to do that in 2.1 before we adding new functionality in 2.2

**Comment by wochinge** [comment]
@b-quachtran How about something like `rasa train --dry-run` which would give you a different status code in case the model needs re-training?

**Comment by b-quachtran** [comment]
@wochinge Yes, that would be exactly what they're looking for 😄

**Comment by wochinge** [comment]
Ok, so they have access to previously trained models when running `rasa train --dry-run`?

**Comment by b-quachtran** [comment]
Yeah, they have previously trained models stored in S3 and are able to download that for dry runs.
