### ISSUE TITLE
Multiple users wondered what the |  symbol is for in the NLU training data format

### ISSUE THREAD

**Issue by abhilasharoy** [RasaHQ/rasa#6734]
During the Rasa 2.0 user tests, multiple users wondered what the | symbol in the NLU data format is for, and if its necessary

**Comment by abhilasharoy** [comment]
@degiz @wochinge what do you think we could do about this?

**Comment by degiz** [comment]
I think we need to clarify that somewhere in the docs. Not sure if there's a better solution, since we don't want to change that.

**Comment by wochinge** [comment]
Removing this from the production squad board

**Comment by tmbo** [comment]
is there something on this we want to do right now? I think this sounds like some docs improvements we can make after tomorrows release

**Comment by wochinge** [comment]
I think at this stage we can't do anything other than documentation. This was one of the major feedback points so we should do it asap after the release (also not great that this slipped through 😞 )

**Comment by tmbo** [comment]
this didn't quite slip through, we discussed this multiple times but came to the conclusion that adding an explanation in the docs and making sure all the examples is the only thing we can do (as well as making the error messages readable, which we did)

**Comment by wochinge** [comment]
ok 🙌  I think we should document our efforts  / discussions in the issue in the future.

**Comment by tmbo** [comment]
indeed ❤️

**Comment by wochinge** [comment]
@degiz Do we wanna do something about the docs now or should I close it?

**Comment by degiz** [comment]
@wochinge Opened a PR for that!
