### ISSUE TITLE
Fallback classifier should be part of the default pipeline

### ISSUE THREAD

**Issue by abhilasharoy** [RasaHQ/rasa#6736]
During the Rasa 2.0 user tests one insight was that Fallback classifier should be part of the default pipeline

**Comment by sara-tagger** [comment]
Thanks for raising this issue, @koaning will get back to you about it soon✨

###### Please also check out the [docs](https://rasa.com/docs/) and the [forum](https://forum.rasa.com/) in case your issue was raised there too 🤗

**Comment by m-vdb** [comment]
@Ghostvv @wochinge do you have any insights on this? Is this something that we want to do? Or is it something we should document better? (it comes from a user feedback)

**Comment by Ghostvv** [comment]
I'd say it should be a part of default pipeline, but we need to find a more or less general threshold for it

**Comment by wochinge** [comment]
@Ghostvv ? What threshold would you suggest? I'd opt to keep the same one as we had in Rasa 1.x (`0.3`)

**Comment by wochinge** [comment]
do https://github.com/RasaHQ/rasa/issues/6810 as part of this

**Comment by Ghostvv** [comment]
yes, default from 1.x sounds good
