### ISSUE TITLE
There are a lot of tensorflow warnings when starting rasa

### ISSUE THREAD

**Issue by abhilasharoy** [RasaHQ/rasa#6737]
A general insight from the Rasa 2.0 user tests

Tobias wrote in the user feedback doc:
> high prio in my opinion (might be already done 🤔)

**Comment by sara-tagger** [comment]
Thanks for raising this issue, @tttthomasssss will get back to you about it soon✨

###### Please also check out the [docs](https://rasa.com/docs/) and the [forum](https://forum.rasa.com/) in case your issue was raised there too 🤗

**Comment by wochinge** [comment]
@erohmensing Can you please add @abhilasharoy to the Rasa team so sara-tagger remains silent?

**Comment by alwx** [comment]
Doesn't seem to be a case any longer (tried it with `2.0.0rc3`). Could you confirm it with `2.0.0rc3`, @abhilasharoy or @wochinge?

**Comment by wochinge** [comment]
@dakshvar22 did you already fix this?

**Comment by dakshvar22** [comment]
Do we have the exact tensorflow warnings that came up in the user tests? if they were related to `tensorflow-addons` being not supported completely by the `tensorflow` version, then that should already be fixed when we updated the version of `tensorflow-addons`.

**Comment by wochinge** [comment]
Checking with rc3

**Comment by wochinge** [comment]
I can confirm the warnings are fixed 👍
