### ISSUE TITLE
make intent names, response names, and action names case-insensitive

### ISSUE THREAD

**Issue by erohmensing** [RasaHQ/rasa#6750]
**Description of Problem**:

When developing in Rasa Open Source or Rasa X, its a very common occurrence that a user might, when writing a story, accidentally mistype the casing of an intent or action.

When using Rasa Open Source, you'll get a log when the training fails thaat says `<mistyped action>` is not a registered action for this domain. However in rasa x, your training fails and you're not sure why. This feels like it can be avoided altogether with case-insensitivity, but could also be improved in different ways

**Overview of the Solution**:

There are a few ways to improve this workflow I think:

1.  Make the names of these case-insensitive, so that when you reference them in the stories you only need to remember the name. this could also apply to slots and names of forms as well – basically anything you need to reference from the domain file in stories. This would help avoid unnecessary errors in both rasa open source and rasa x.

1.  Make it easier in rasa x to get an overview of your stories, intents, and actions (and slots and forms?) while you're writing stories. Ideas:

*   autocomplete typing with names of things from the domain file (this seems hard)
*   maybe e.g. some sort of split screen with the story writer and the domain so that you can easily reference it. maybe you could also just click on names from the domain to use them in your story
     <g-emoji class="g-emoji" alias="smile" fallback-src="https://github.githubassets.com/images/icons/emoji/unicode/1f604.png">
     😄 
     </g-emoji> This would help avoid unnecessary errors in rasa x.

1.  Pass along the error message into Rasa X. We could do this for every error, or we could raise a certain class of errors for certain failures, and only pass those on/display them, if we only want to print errors that the (possibly business) user can feasibly fix (UserWarnings for example, versus logger exceptions?) This would help avoid unnecessary errors in rasa x.

**Comment by wochinge** [comment]
I'm not so much a fan of 1. I love 2 and 3. Especially 3 seems like some low hanging 🥝

**Comment by erohmensing** [comment]
What qualms do you have against 1? Do you think there is a real use case for people distinguishing their intents based on uppercase vs lowercase characters? I think 2 and 3 are helpful to the workflow regardless, but 1 seems like a big win for simple issues that users run into a lot. 

Maybe we can see what errors this issue raises and check sentry to see how common it is.
