### ISSUE TITLE
Mention the State of Telemetry during `rasa init`. 

### ISSUE THREAD

**Issue by koaning** [RasaHQ/rasa#6759]
**Description of Problem**:

Users should be well aware of the new telemetry. In particular when a user runs `rasa init` it feels like they need to be, at the very least, reminded.

## Current Flow

Currently there is no mention of telemetry.

 (venv) ➜ rasa init
 Welcome to Rasa! 🤖
 To get started quickly, an initial project will be created.
 If you need some help, check out the documentation at [https://rasa.com/docs/rasa](https://rasa.com/docs/rasa).
 Now let's start! 👇🏽
 ? Please enter a path where the project will be created <span class="error">[default: current directory]</span> folder-name
 ? Path '.folder-name' does not exist 🧐. Create path? Yes
 Created project directory at '/Users/vincent/Development/breakout-bot-s01/.omgomgomg'.
 Finished creating project structure.
 ? Do you want to train an initial model? 💪🏽 No
 No problem 👍🏼. You can also train a model later by going to the project directory and running 'rasa train'.

## Proposed Flow

We might add the following statement to a user who does not have telemetry on.

 Just so you know! You can share anonymous statistics with us. 
 It will help us make Rasa better. To do this run; 

 rasa telemetry enable

We might add the following statement to a user who does.

 Just so you know! You're currently sharing anonymous statistics with us. 
 It helps us make Rasa better. Thanks! If you don't want to share data, run; 

 rasa telemetry disable

**Comment by mbslet** [comment]
Hey there, @Henrike100, @lucasdutraf, and I would like to know if someone is already working on this issue. :D
