### ISSUE TITLE
external- and anchor- linkchecking for docs

### ISSUE THREAD

**Issue by erohmensing** [RasaHQ/rasa#6763]
On our previous docs, we did more linkchecking than we now do: 
- external links are currently not checked (this most commonly previously caused issues linking from rasa to rasa x and vice versa, but also there are some links that if they go dead, we won't catch it for a long time) 
- anchors for internal links are not checked (previously these were done with explicit, movable references). This means that if content moves or even the title of a header is changed, links from another page won't resolve -- you'll get to the right page but not to the right content. 

I think it makes the most sense to check the anchors upon merge, as anything internal should always resolve. The external did cause a few builds to break due to non-rasa websites being down in the past, so it might be a good thing to run that check e.g. nightly instead. This also gives us time to update one repo's reference to another if the second moves, before things start failing immediately.

**Comment by m-vdb** [comment]
A quick search yielded two plugins that could be helpful for us: [remark-validate-links](https://github.com/remarkjs/remark-validate-links) (validate links to headers) and [remark-lint-no-dead-urls](https://github.com/davidtheclark/remark-lint-no-dead-urls). They will definitely need some tweaking.
