### ISSUE TITLE
Filter more information from Sentry error reporting

### ISSUE THREAD

**Issue by m-vdb** [RasaHQ/rasa#6768]
Current Sentry errors are sent to the [#product-engineering-alerts](https://rasa-hq.slack.com/archives/C01585AN2NP) channel. By checking some of the error reports:

- stacktraces include full disk path (for example, clicking on "Full" in [this issue](https://sentry.io/organizations/rasahq/issues/1909338082/?project=2801673&query=is%3Aunresolved&statsPeriod=14d)). We might want to only include stacktrace only in rasa / rasa_sdk codepath
- do we want to mask URLs like in [this issue](https://sentry.io/organizations/rasahq/issues/1909549373/?project=2801673&referrer=slack)?
- open question: are there things we want to wrap up regarding sentry filtering _before_ we released 2.0 in order to reduce the noise on issues we get? Or do we have enough control over these issues from Sentry UI?

**Comment by m-vdb** [comment]
@tmbo I think we can close this, right?

**Comment by tmbo** [comment]
yes I think we are good to go for the release, I have a couple more thoughts on what we might be able to do to reduce the amount of errors further, but I think we are ready to go for 2.0
