### ISSUE TITLE
Change tag color in Rasa X

### ISSUE THREAD

**Issue by andrew-mcmaster** [RasaHQ/rasa#6771]
**Description of Problem**: Would like to be able to choose tag color from Rasa X during creation and change after creation.

**Overview of the Solution**: If there was an edit button/icon beside each tag in the tags list on Rasa X it could trigger the tag name to be an input field or popup with another field to include a simple field with hex code with optional small box to show color.

**Examples** (if relevant):

**Blockers** (if relevant):

**Definition of Done**:

**Comment by sara-tagger** [comment]
Thanks for submitting this feature request 🚀 @akelad will get back to you about it soon! ✨

**Comment by akelad** [comment]
@abhilasharoy @TyDunn thoughts?

**Comment by TyDunn** [comment]
@edmacovaz is thinking through similar things at the moment

**Comment by edmacovaz** [comment]
I'm just learning about how colors for tags work at the moment. 

I could see this being useful but I'm not sure how soon we would get to it. And I'm also unsure whether we would go straight to custom colours from the Rasa X UI or maybe just give people a list to choose from—hex colors seem straight forward to some people, but most people don't get them. So I'd like to avoid building a color picker...

**Comment by edmacovaz** [comment]
Also, from what I understand the color codes are set from the front end and saved in the backend at the moment, so apparently you can define custom colors throgh the API already.

**Comment by andrew-mcmaster** [comment]
The [api docs](https://rasa.com/docs/rasa-x/pages/http-api#operation/postTags) did not seem to straightforwardly say you could update just the color of  an existing tag (at least my interpretation). 

> ID of an already existing tag. If this property is present, then **all other properties will be ignored**, and this ID will be the one assigned to the conversation

currently it also requires a conversation id in the params of the request. I was just thinking a PUT request to /tags instead of /conversations/{conversation_id}/tags would make sense. Even for creation of new tags (not sure how it's done behind the scenese). 

When we add tags through X at the moment, if you add a bunch it seems to have a set list of a few through the spectrum but after some period of time it goes back to the start of that list, which is green I think. So if you add one every now and then it is looking like they would all be the same color anyway which feels a little like why bother. I could be wrong and that is just a coincidence though. 

At the moment we have a client who we are training to use X so they can add more content themselves, they are non-techinical and getting them to use an api is pretty much out.

As a user myself I would see wanting an easier way to deal with tags, I think tags are a good feature and like using them, and having a personal/team color pattern for different types of tags was the first thought in my mind when adding them. I understand there is a lot going on though with the new 2.0 and get it might not be a priority or something that makes sense from the Rasa side.

**Comment by TyDunn** [comment]
> When we add tags through X at the moment, if you add a bunch it seems to have a set list of a few through the spectrum but after some period of time it goes back to the start of that list, which is green I think. So if you add one every now and then it is looking like they would all be the same color anyway which feels a little like why bother. I could be wrong and that is just a coincidence though.

@edmacovaz I have noticed this unequal distribution of the color of tags too. I think it is something worth investigating

**Comment by edmacovaz** [comment]
@TyDunn That behaviour sounds like I bug, I would expect we would want to continue cycling through to have an even distribution among the colours. I'll investigate.

**Comment by Kadrian** [comment]
I can confirm that the cycling through the colors as discussed above is working now as expected – there shouldn't be just one color at some point – but the core of this issue – `to be able to choose tag color from Rasa X during creation and change after creation.` is still not done. Is this still something we'd want to do if we have the cycling?

**Comment by edmacovaz** [comment]
@Kadrian This is something we may want to do in the future, but isn't currently planned, so we should leave this open to keep this request documented.

**Comment by alexweidauer** [comment]
Thank you for raising this issue about Rasa X. We decided to stop supporting the Community Edition (free version) of ‘Rasa X’ (see more info here: https://rasa.com/blog/rasa-x-community-edition-changes/). That’s why we’ve closed your issue. We suggest that Rasa Enterprise customers raise the issue with our customer support team if they haven’t done so already.
