### ISSUE TITLE
Legacy Documentation: Search functionality is broken

### ISSUE THREAD

**Issue by fpfuetsch** [RasaHQ/rasa#6774]
**Rasa version**: 1.10.14

**Issue**:
The search bar in the legacy documentation is broken. When I search e.g. for "Slots" or "Forms" I don't get any results. The search recommendations that are available neither do work, since the links are broken.
https://legacy-docs-v1.rasa.com/

**Error (including full traceback)**:
/

**Command or request that led to error**:
use search bar

**Comment by sara-tagger** [comment]
Thanks for the issue, @tttthomasssss will get back to you about it soon!

###### You may find help in the [docs](https://rasa.com/docs/) and the [forum,](https://forum.rasa.com/) too 🤗
