### ISSUE TITLE
finish old content check in docs

### ISSUE THREAD

**Issue by erohmensing** [RasaHQ/rasa#6775]
- [x] Nlu data format 
- [x] responses?
- [x] domain.mdx (There are outstanding TODOs here, and the unfeaturized_slot PR also updates this page)
- [x] event-brokers.mdx
- [x] fallback-handoff.mdx
- [x] forms.mdx (have looked through it, changes also coming in from unfeaturized_slot PR)
- [x] generating-nlu-data.mdx
- [x] glossary.mdx (maybe check the notes entered next to Rasa NLU and Rasa Core)
- [x] how-to-deploy.mdx
- [x] http-api.mdx
- [x] installation.mdx
- [x] introduction.mdx
- [x] jupyter-notebooks.mdx
- [x] lock-stores.mdx
- [x] messaging-and-voice-channels.mdx (and all the channels associated with it)
- [x] migrate-from.mdx (and all the pages associated with it) 
- [x] migration-guide.mdx
- [x] model-configuration.mdx
- [x] the `docker` subfolder

**Comment by akelad** [comment]
@akelad update this

**Comment by akelad** [comment]
@melindaloubser1 @b-quachtran, if you have some time, could you take on a few of these? The idea is just to go through the page and see if there's any outdated information on them, it's entirely possible that a lot of them don't need any edits.

**Comment by melindaloubser1** [comment]
Sure, I'm already working on NLU data format, and I'll see how many others I can get through today

**Comment by b-quachtran** [comment]
@melindaloubser1 Sounds good, although I probably won't be able to get to this until early next week

**Comment by melindaloubser1** [comment]
You can work on the `outdated_content_check` branch if you'd like.

**Comment by tmbo** [comment]
@melindaloubser1 @erohmensing whats up with this issue? anything that needs to be done before the 2.0 release today?

**Comment by akelad** [comment]
hm, not sure what happened with Ben's section of this, but we want to merge Melinda's two PRs mentioned for sure. The rest won't make it I guess

**Comment by tmbo** [comment]
I'll remove this issue then, please add the prs separately to the milestone

**Comment by erohmensing** [comment]
closed in #6945, #6947, #6951
