### ISSUE TITLE
Rasa X domain path

### ISSUE THREAD

**Issue by gck25** [RasaHQ/rasa#6784]
At the moment, within the rasa X CLI, it is possible to define the paths for the model, data and configuration file using `~~m`, `~~-data` and `-c`, respectively. There is no such option for the domain file. The only option is to create a domain.yml in the directory where the `rasa x` command is called. Otherwise, the following error is thrown:

 This directory is not a valid Rasa project. 
 Use 'rasa init' to create a new Rasa project or switch to a valid 
 Rasa project directory (see [http://rasa.com/docs/rasa/user-guide/rasa-tutorial/#create-a-new-project](http://rasa.com/docs/rasa/user-guide/rasa-tutorial/#create-a-new-project)).

I would appreciate it if someone could make this change, as it would be very helpful for my use case and would make the framework more flexible for other users ![](/images/icons/emoticons/smile.png)

**Comment by sara-tagger** [comment]
Thanks for raising this issue, @melindaloubser1 will get back to you about it soon✨

###### Please also check out the [docs](https://rasa.com/docs/) and the [forum](https://forum.rasa.com/) in case your issue was raised there too 🤗

**Comment by melindaloubser1** [comment]
Since in server mode, git integration requires a set repository structure, localmode reflects that. Could you describe the use case for this/why you need the domain to be at a different path?

**Comment by hotzenklotz** [comment]
If have the exact the same issue. Please make the `domain` configurable, as with the other parameters. @tmbo Pretty please :-)

As for why:
1. Projects grow and evolve. There was no Rasa standard project layout when we first started with some projects. 
2. All my config files are in a directory called`configs`: `<rasa_root>/configs/<{domain.yaml}, {config.yaml}, {endpoints.yaml}>`. Keeps it nice and organized. Just like all training data files are collect under `<rasa_root>/data`.

I would also ask that the error message becomes more descriptive. It could list all the violations of the assume file locations, e.g: 
```
This directory is not a valid Rasa project. <...>
- Expect to find domain file at: ./domain.yaml
- Expect to find config file at: ./config.yaml
```

**Comment by wochinge** [comment]
@TyDunn I think if we do this, then this should also work for apply to Integrated Version Control. What do you think?

**Comment by TyDunn** [comment]
@wochinge I think so, that way you do not have to change the structure of your assistant as you move from local to server mode

**Comment by wochinge** [comment]
yep. I think that would make something like a config file necessary which defines the project layout. Or we specify it in the connection dialogue for Integrated Version Control and command line parameters for local Rasa X?

**Comment by TyDunn** [comment]
Immediate reaction: I like the idea of a project layout config file. That way you could specify behavior for where Rasa X writes new intents, stories, responses, etc.

**Comment by randywreed** [comment]
Any progress on this. I encounted this today as well. I have a separate responses.yml and domain.yml and thus need to be able to specify a domain directory.

**Comment by wochinge** [comment]
@randywreed As workaround: You can just put the domain in the `data` folder (or in one of the sub directories) and it should work

**Comment by alexweidauer** [comment]
Thank you for raising this issue about Rasa X. We decided to stop supporting the Community Edition (free version) of ‘Rasa X’ (see more info here: https://rasa.com/blog/rasa-x-community-edition-changes/). That’s why we’ve closed your issue. We suggest that Rasa Enterprise customers raise the issue with our customer support team if they haven’t done so already.
