### ISSUE TITLE
the pip package for rasa=2.0.0rc1 points to the wrong tfmodule

### ISSUE THREAD

**Issue by laurencejennings** [RasaHQ/rasa#6786]
**Rasa version**:
rasa2.0.0rc1
**Rasa SDK version** (if used & relevant):

**Rasa X version** (if used & relevant):

**Python version**:
3.8
**Operating system** (windows, osx, ...):
linux
**Issue**:
When installing rasa with ```pip install rasa==2.0.0rc1``` the `nlu/tokenizers/convert_tokenizer.py` file contains the wrong path for tf-hub-module: http://models.poly-ai.com/convert/v1/model.tar.gz'```

**Error (including full traceback)**:
```
2020-09-24 17:46:34 INFO     absl  - Downloading TF-Hub Module 'http://models.poly-ai.com/convert/v1/model.tar.gz'.
```

**Command or request that led to error**:
```
rasa train
```

I solved this by changing the file mentioned above with the same path as the version which is in the current github repo: 
```
TF_HUB_MODULE_URL = "https://github.com/PolyAI-LDN/polyai-models/releases/download/v1.0/model.tar.gz"
```

I'm not sure if this is the place for issues with the pip package, but I thought people who had this issue might find the solution helpful

**Comment by sara-tagger** [comment]
Thanks for the issue, @JustinaPetr will get back to you about it soon!

###### You may find help in the [docs](https://rasa.com/docs/) and the [forum,](https://forum.rasa.com/) too 🤗

**Comment by erohmensing** [comment]
Thanks for reporting, this was fixed [here](https://github.com/RasaHQ/rasa/pull/6743). If you download `2.0.0rc2` that should fix it!

**Comment by erohmensing** [comment]
PS this is definitely the place for issues with the pip package
