### ISSUE TITLE
error in the documentation for chitchat-faqs.mdx

### ISSUE THREAD

**Issue by laurencejennings** [RasaHQ/rasa#6787]
**Rasa version**: 2.0.0rc1

**Rasa SDK version** (if used & relevant):

**Rasa X version** (if used & relevant):

**Python version**: 3.8

**Operating system** (windows, osx, ...): linux

**Issue**: following the code on `chitchat-faqs.mdx`, `respond_chitchat` results in a missing action when training the model 

**Error (including full traceback)**:
```
NameError: Cannot access action 'respond_chitchat', as that name is not a registered action for this domain. Available actions are: 
	 - action_listen
	 - action_restart
	 - action_session_start
	 - action_default_fallback
	 - action_deactivate_loop
	 - action_revert_fallback_events
	 - action_default_ask_affirmation
	 - action_default_ask_rephrase
	 - two_stage_fallback
	 - action_back
	 - ...
	 - utter_chitchat
	 - utter_cheer_up
	 - utter_chitchat/ask_name
	 - utter_chitchat/motivation
	 - utter_did_that_help
	 - utter_goodbye
	 - utter_greet
	 - utter_happy
	 - utter_iamabot

```

**Command or request that led to error**:
```
rasa train
```

I could solve this by changing `respond_chitchat` to `utter_chitchat`

**Comment by sara-tagger** [comment]
Thanks for raising this issue, @b-quachtran will get back to you about it soon✨

###### Please also check out the [docs](https://rasa.com/docs/) and the [forum](https://forum.rasa.com/) in case your issue was raised there too 🤗
