### ISSUE TITLE
Local Rasa X - Twilio | improperly formatted XML response?

### ISSUE THREAD

**Issue by kmcmearty** [RasaHQ/rasa#6788]
**Rasa version**: 1.10.14

**Rasa SDK version** (if used & relevant):

**Rasa X version** (if used & relevant): 0.32.2

**Python version**: 3.7.6

**Operating system** (windows, osx, ...): Ubuntu 18.04

**Issue**:
Running Rasa X in local mode and using Ngrok to expose to twilio. Using twilio to text Rasa. I believe the XML response back from Rasa is being improperly formatted so Twilio will not return the Rasa response to my cellphone.  

**Error (including full traceback)**:

**Rasa X debug log**
![Screenshot from 2020-09-20 14-49-16](https://user-images.githubusercontent.com/10493854/94207126-ef340480-fe94-11ea-856f-1e4a369b3650.png)

**Twilio Error**
![image](https://user-images.githubusercontent.com/10493854/94206729-2229c880-fe94-11ea-8642-45b11e30f7c0.png)

**Twilio Error Explanation**
![image](https://user-images.githubusercontent.com/10493854/94206752-2fdf4e00-fe94-11ea-8424-4248fc10829d.png)

**Ngrok POST 200 OK**
![image](https://user-images.githubusercontent.com/10493854/94206788-438ab480-fe94-11ea-95fc-65f1840f06b8.png)

**Command or request that led to error**:
```
Sent text message to Twilio number to retrieve response from Rasa.
or
curl -g -X POST --data '{"message":"hello"}' --header "Content-Type:application/json" https://82e71aecb917.ngrok.io/webhooks/twilio/webhook

```

**Content of configuration file (config.yml)** (if relevant):
```yml

```

**Content of domain file (domain.yml)** (if relevant):
```yml

```

**Comment by sara-tagger** [comment]
Thanks for raising this issue, @rgstephens will get back to you about it soon✨

###### Please also check out the [docs](https://rasa.com/docs/) and the [forum](https://forum.rasa.com/) in case your issue was raised there too 🤗
