### ISSUE TITLE
NLU converter not supporting external synonym files

### ISSUE THREAD

**Issue by b-quachtran** [RasaHQ/rasa#6791]
NLU converter tool not working for externally defined synonym files

**Rasa version**: 2.0.0rc2
**Issue**:

NLU converter doesn't work for externally defined synonym files, e.g.:
`## synonym:plates`
`data/nlu/synonyms/plates.txt`

**Comment by degiz** [comment]
Hey @b-quachtran 

That was fixed even before `2.0.0rc1` and still seems working fine for me. 
The only problem I can think of is that user has to run `rasa data convert` from a dir that can still access external synonym file using the relative path.

**Comment by degiz** [comment]
Oh wait no, that were lookup tables fixed.

**Comment by b-quachtran** [comment]
Technically no, but it worked with 1.X and a customer is asking about it with 2.0.

**Comment by degiz** [comment]
Not sure if we want to support migration from a feature that we never officially supported 😄 
@akelad wdyt?

**Comment by akelad** [comment]
wow i did not know this was a thing haha. I mean, if we allowed this to work (intentionally or not) in 1.x then the migration script should cover it.

**Comment by degiz** [comment]
@b-quachtran I've checked the code - we don't support synonyms from an external file in Markdown.
Probably you can come back to the customer and tell them, that their synonyms are not in use.

**Comment by b-quachtran** [comment]
@degiz Thanks for checking this! I should've checked as well instead of assuming it was working for them 🙈
