### ISSUE TITLE
A bug with language supporting detection function of component

### ISSUE THREAD

**Issue by howl-anderson** [RasaHQ/rasa#6802]
**Rasa version**: 2.0.0rc1

**Issue**:

If a new component has such language supporting settings:

```python
supported_language_list = ["en", "xx"]
not_supported_language_list = None  # which is the default value
```
it will not work correctly since the `can_handle_language` function not implemented incorrectly:

```python
        language_list = cls.supported_language_list or []
        not_supported_language_list = cls.not_supported_language_list or []

        return language in language_list or language not in not_supported_language_list
```

since `not_supported_language_list` will be `[]` in our example, so `language not in not_supported_language_list` will always be true no matter what's the value of `language`. Finally when `cls.not_supported_language_list` is None then all language will be supported which is not we wanted.

I will submit a PR to fix it.

**Comment by sara-tagger** [comment]
Thanks for the issue, @erohmensing will get back to you about it soon!

###### You may find help in the [docs](https://rasa.com/docs/) and the [forum,](https://forum.rasa.com/) too 🤗

**Comment by erohmensing** [comment]
Thanks for the initiative toward fixing this!

**Comment by howl-anderson** [comment]
Since #6803 already merged, it fixed the issue, so I will close it now.
