### ISSUE TITLE
/status endpoint does not report correct model

### ISSUE THREAD

**Issue by ricwo** [RasaHQ/rasa#6807]
**Issue**:

1.  When the server is initialised with a local model, the Agent's attribute `path_to_model_archive` will have a value. This attribute is not updated if the server is configured to pull models from other servers, meaning even if the model changes, the server continues to report an outdated `path_to_model_archive`.

1.  The `/status` endpoint has `"model_file": app.agent.path_to_model_archive or app.agent.model_directory`. When the server is not initialised with a local model and configured to pull a model from another server, `path_to_model_archive` is `None`, and `model_directory` will be point to a temporary directory where the model has been unpacked. This is not meaningful.

**Suggestion**:

When pulling a model from another server, check for a response header `model-name`. This `model-name` can be used to save the archive as (to a temp directory), and update the `path_to_model_archive` attribute.

**Comment by MarthaDs** [comment]
Hi, I'm working on this issue, is that alright?
