### ISSUE TITLE
Remove the ConveRT component

### ISSUE THREAD

**Issue by howl-anderson** [RasaHQ/rasa#6811]
News from https://github.com/PolyAI-LDN/polyai-models#convert.

> After much consideration, the PolyAI team has decided to take down the ConveRT models from the public domain.
> 
> Over the course of last year, we have been very excited to see ConveRT gaining a huge amount of traction in various communities - that was something we didn't expect when we first released it. However, with the amount of business growing and the shift of our team's priorities, we no longer have the resources to responsibly maintain or provide support for these models.
> 
> PolyAI is working to create end-to-end voice assistants. If you're interested in helping us, check out our careers page at polyai.com/careers. On the other hand, if you are interested in knowing how our solutions can help you transform your contact center, please get in touch at contact@polyai.com.

Since PolyAI team removed all the model files, no one can download models anymore, ConveRT component will be not useable for the user,  so we need to remove the ConveRT component from Rasa too.

**Comment by sara-tagger** [comment]
Thanks for the issue, @melindaloubser1 will get back to you about it soon!

###### You may find help in the [docs](https://rasa.com/docs/) and the [forum,](https://forum.rasa.com/) too 🤗

**Comment by melindaloubser1** [comment]
Hi @howl-anderson, we're aware of this issue and looking at options. Please see this issue: https://github.com/RasaHQ/rasa/issues/6810

Closing as a duplicate for now.
