### ISSUE TITLE
Rewrite Telegram channel with a different library

### ISSUE THREAD

**Issue by akelad** [RasaHQ/rasa#6814]
**Description of Problem**:
The current package `python-telegram-bot` uses a vendored package of urllib3, which hasn't been updated since 2017 and therefore has some security vulnerabilities. See issue for details: https://github.com/python-telegram-bot/python-telegram-bot/issues/2097

**Overview of the Solution**:
We should rewrite the telegram channel to use this package instead: https://github.com/eternnoir/pyTelegramBotAPI

**Comment by wochinge** [comment]
closed by https://github.com/RasaHQ/rasa/pull/6889/files
