### ISSUE TITLE
Automatically migrate MappingPolicy + FallbackPolicies

### ISSUE THREAD

**Issue by wochinge** [RasaHQ/rasa#6820]
**This issue may be split in three parts**

**Motivation**
* [this feedback](https://www.notion.so/rasa/Feedback-on-2-0-4574eaacc0764967ac0b8b82fbc72904#e17d53c4dbb44ba1844b412b8ebaa782)
* there is actually no need to manually migrate `FallbackPolicy`, `TwoStageFallbackPolicy` or `MappingPolicy`. We can migrate all of them automatically. 

**Ideas**
* check out the migration guide and automate it as part of some CLI command (`rasa data convert`?)
* ? 

**Definition of Done**
- [ ] Feature implemented
- [ ] Migration guide updated

**Comment by wochinge** [comment]
@degiz Do you think we integrate it into `rasa data convert`? There is no `rasa migrate`, right?

**Comment by wochinge** [comment]
It might not be possible to migrate the `TwoStageFallbackPolicy` automatically as users might have customized the `deny_suggestion_intent_name` intent and we can't migrate custom actions of theirs which are using this intent.

**Comment by degiz** [comment]
> There is no rasa migrate, right?

We were talking about possibly introducing `rasa migrate`, but wanted to use it to migrate the whole project from to `2.0`. So back then, when we only wanted to convert training data, we didn't do that.

Now, if you have an idea of how to do that, that makes sense! But Do you think we can do that before next week?

**Comment by wochinge** [comment]
I mean it's just for these polices above. We can't migrate the whole thing (e.g. forms).
The alternative based on the feedback would be add a default rule for the two-stage-fallback but I don't think this is ideal as it's not transparent and users might wanna change the rule for the two stage fallback somehow. 

We could also do a `rasa data convert config` which would be a bit more selective than introducing a `rasa migrate`.

> But Do you think we can do that before next week?

It's blocking feedback and directly relevant to our okrs (smooth transition). I think it's definitely doable with a bit of force.

cc @m-vdb @tmbo Wdyt?

**Comment by m-vdb** [comment]
> It might not be possible to migrate the TwoStageFallbackPolicy automatically as users might have customized the deny_suggestion_intent_name intent and we can't migrate custom actions of theirs which are using this intent.

If we can get a command that simplifies the migration for a good share of users that's great. What about something along those lines:
1. show a very visible warning about the fact that the rule is missing (can we detect it?)
2. have a command that converts the config to 2.0 format
3. have users run this command themselves (it is not run automatically)

That way it's not _too_ smart and doesn't try to automatically migrate. But it's still simple enough for users.

I am not sure it's a good idea to name it `migrate` because the command will currently only migrate one thing (whereas users could expect `migrate` to migrate everything).

Regarding prioritization: definitely in line with this quarter prios. I'm afraid we won't have time to ship it but we could try, and worst case ship it in a patch right after (2.0.1)? But I think we do not have other alternative at this point, right?

**Comment by wochinge** [comment]
> show a very visible warning about the fact that the rule is missing (can we detect it?)

I think we can't reliable detect it. What we could do is a check to see if the `FallbackClassifier` and a story / rule handles the `nlu_fallback` intent. It wouldn't be great performance wise as we'd have to go through O(n) stories (worst case scenario) to validate this.

> I am not sure it's a good idea to name it migrate because the command will currently only migrate one thing (whereas users could expect migrate to migrate everything).

This could also integrate the training data conversion. However, time and implementation wise a `rasa data convert config` is quicker as we can just focus on making one thing work.

>  I'm afraid we won't have time to ship it but we could try

I'll think about it and then give an estimate. I also think we have no alternative 👍

**Comment by m-vdb** [comment]
@wochinge if you have a short implementation plan and we can split it, i'm happy to help

**Comment by wochinge** [comment]
On it 👍

**Comment by wochinge** [comment]
@m-vdb @ricwo @alwx Did an [implementation proposal ](https://www.notion.so/rasa/Automatically-migrate-MappingPolicy-FallbackPolicies-ee231ccab0bd4857b204ff4ff3069356).

It's splittable in 4 tasks, but probably doesn't make sense that more than 2 people work on it. I think it's realistic that we can get out something working by tomorrow evening and then review on Friday and merge?

**Comment by wochinge** [comment]
should we a parameter for the version which is migrated to the command? I'd say we can skip this for now and then add it in later versions

**Comment by m-vdb** [comment]
works for me

**Comment by wochinge** [comment]
@Ghostvv @ricwo @m-vdb @b-quachtran 
We currently have [this check](https://github.com/RasaHQ/rasa/blob/f1055d18b46071312259057a23c80ce5506e158f/rasa/core/policies/ensemble.py#L469) to ensure that the `RulePolicy` cannot be used in conjunction with `MappingPolicy`, `FallbackPolicy` or `TwoStageFallbackPolicy`. I'd vote for relaxing this and converting this to a warning. The problem is that with the current check it's not possible to migrate a 1.x bot step by step. As a user I'd personally would have the following workflow:
1. Migrate one policy
2. Train
3. Test
4. Migrate next policy

This is currently not possible due to our check. This makes it hard for users to find out where in the process of the migration a potential error happened. What do you think?

**Comment by b-quachtran** [comment]
I like the idea of relaxing it to a warning, at least for 2.0, while users are migrating from 1.X.
