### ISSUE TITLE
Partial dataset loading

### ISSUE THREAD

**Issue by tabergma** [RasaHQ/rasa#6836]
**Description of Problem**:
If you want to train your assistant on a large dataset, it might happen that you run into memory issues as the complete dataset is loaded into memory and featurized. 

related to https://github.com/RasaHQ/rasa/issues/1621

**Overview of the Solution**:
No concrete solution yet. But ideally we would not load all the data at once but load them partly, so that not all data is loaded into memory and featurized at the same time.

Things to keep in mind:
- `CountVectorsFeaturizer` needs to build up a vocabulary. We could either use predefined vocabulary or we need to pass all the data once to build full vocabulary from all the data
- if we want to support continue training, than it makes sense to create placeholders for unseen words in `CountVectorsFeaturizer` vocabulary (https://rasa-hq.slack.com/archives/C8LEHMTAM/p1601390370106100?thread_ts=1601389639.104600&cid=C8LEHMTAM)

**Comment by tabergma** [comment]
Let's collect ideas in the following [document](https://docs.google.com/document/d/1dwKfdju5ZqhOQtURLF3-eU3PdxvdlyXafPHE_0sLPzI/edit?usp=sharing).

**Comment by Ghostvv** [comment]
@tabergma shouldn't it be rather in research projects? I don't think it is feasible in one sprint

**Comment by tabergma** [comment]
True, it is not. But it is also not a research project. We could also leave it in the column "smaller projects" and just add the smaller issues related to this issues to the "in progress" column etc.

**Comment by Ghostvv** [comment]
I'd move it to research projects board for simplicity of boards. I'd say it has the spirit of a project

**Comment by Ghostvv** [comment]
Actually, I'd move all `Small Projects` to research projects board

**Comment by tabergma** [comment]
According to my test runs in https://github.com/RasaHQ/rasa/issues/7120, we should be at least able to load the Advising and the MultiWOZ training dataset into memory and perform tokenization. As the Ubuntu corpus is not yet converted we cannot make any statement on this kind of dataset.

Things we would need to do:
- [ ] Create a new interface for the NLU components, e.g. `prepare_training`, `train_chunk`, `persist_chunk`, that is needed to handle the partial dataset training. The interface can be left empty for now.
- [ ] Creating NLU components should take the domain as an optional parameter.
- [ ] We should make sure to not load the training data multiple times before actually reading and processing it. This takes up a lot of time if the dataset is very large.
- [ ] Create a method that divides the training data into smaller chunks. Each chunk should be a good representative of the complete dataset. See document for details.
- [ ] Implement the method `prepare_training` on all featurizers, classifiers, and entity extractors. Most of the components can leave it empty.
- [ ] Implement the method `train_chunk` on all featurizers, classifiers, and entity extractors. Make sure to raise an error when `train_chunk` on components is called that cannot handle training in chunks, e.g. `CRFEntityExtractor` (see documents for details).
- [ ] Implement the method `persist_chunk` on all featurizers, classifiers, and entity extractors. 
- [ ] When create `DialogueStateTrackers` from stories, make sure to write down the `DialogueStateTrackers` to disk as soon as it is completed/finished.
- [ ] Create a new interface for policies, e.g. `train_chunk`. Leave it empty for now.
- [ ] Implement the method `train_chunk` for every policy. Make sure to raise an error if the policy does not support training in chunks.
- [ ] Create a method `train_chunk` on the `Agent` that calls the `train_chunk` methods of the policies and makes sure that policies are trained after each other. 
- [ ] Create a new command line tool called `rasa train chunks` that will train the given dataset in chunks. Users should also be able to call `rasa train core chunks` and `rasa train nlu chunks`.

**Comment by TyDunn** [comment]
@Ghostvv This is still assigned to Tanja. Is someone else picking this up now?

**Comment by Ghostvv** [comment]
@TyDunn yes - me

**Comment by Ghostvv** [comment]
blocked by https://github.com/RasaHQ/rasa/issues/7947

**Comment by Ghostvv** [comment]
We decided to merge NLU and core independently:
In order to merge NLU, we need to:
- [ ] implement train_on_chunk for KeywordIntentClassifier https://github.com/RasaHQ/rasa/issues/8298
- [ ] implement chunking in `SpacyNLP` and `HuggingfaceNLP`
- [ ] add validation dataset in DIET

**Comment by Ghostvv** [comment]
core:
- [x] implement persist method in trackers https://github.com/RasaHQ/rasa/issues/7395
- [ ] persist trackers during generation
- [ ] implement `rasa train core --number-of-chunks`
- [ ] train chunk for core featurizers
- [ ] train on chunk for policies

**Comment by twerkmeister** [comment]
I closed this as it is subsumed by #8595 (support training on big datasets). Please open again if it was still needed
