### ISSUE TITLE
ConveRT model removed from public domain

### ISSUE THREAD

**Issue by tatianafrank** [RasaHQ/rasa#6842]
According to this https://github.com/PolyAI-LDN/polyai-models the model has been removed. Due to this our model has been failing to train since the TF HUB MODULE URL no longer exists.

**Comment by sara-tagger** [comment]
Thanks for the issue, @rgstephens will get back to you about it soon!

###### You may find help in the [docs](https://rasa.com/docs/) and the [forum,](https://forum.rasa.com/) too 🤗

**Comment by rgstephens** [comment]
Hi Tatiana, I'm closing this as a duplicate of #6806. We're actively working on a resolution.
