### ISSUE TITLE
Reduce readings of training data files during training

### ISSUE THREAD

**Issue by degiz** [RasaHQ/rasa#6896]
**Rasa version**: 2.0.0rc3

As mentioned in the [forum](https://forum.rasa.com/t/rasa-2-reads-many-many-times-the-data/35325), Rasa Open Source reads training data file and Domain more than once during training, whilst the files don't change.
Even though that doesn't slow down things, it produces confusing logs and not optimal usage of resources anyway.
We should reduce the reading of the training data files.

**Comment by wochinge** [comment]
fixed by https://github.com/RasaHQ/rasa/pull/6938
