### ISSUE TITLE
Rasa 2.0 version bug in windows

### ISSUE THREAD

**Issue by matthewkos** [RasaHQ/rasa#6926]
**Rasa version**:
2.0.0rc4
**Rasa SDK version** (if used & relevant):
2.0.0rc4
**Rasa X version** (if used & relevant):
NA
**Python version**:
3.7.9
**Operating system** (windows, osx, ...):
windows 10
**Issue**:
sys.version in windows 10 does not contain \n
please fix by 

**Error (including full traceback)**:
```
Traceback (most recent call last):
  File "e:\env\anaconda\envs\rasa\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "e:\env\anaconda\envs\rasa\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "E:\Env\Anaconda\envs\rasa\Scripts\rasa.exe\__main__.py", line 7, in <module>
  File "e:\env\anaconda\envs\rasa\lib\site-packages\rasa\__main__.py", line 118, in main
    print_version()
  File "e:\env\anaconda\envs\rasa\lib\site-packages\rasa\__main__.py", line 78, in print_version
    python_version, os_info = sys.version.split("\n")
ValueError: not enough values to unpack (expected 2, got 1)
```

**Command or request that led to error**:
```
rasa --version
```

**Content of configuration file (config.yml)** (if relevant):
```yml

```

**Content of domain file (domain.yml)** (if relevant):
```yml

```

**Comment by sara-tagger** [comment]
Thanks for the issue, @tttthomasssss will get back to you about it soon!

###### You may find help in the [docs](https://rasa.com/docs/) and the [forum,](https://forum.rasa.com/) too 🤗

**Comment by manada-jwheat** [comment]
I can second this error

Rasa version:
2.0.0 release
Rasa SDK version (if used & relevant):
2.0.0 release
Rasa X version (if used & relevant):
NA
Python version:
3.8
Operating system (windows, osx, ...):
Windows 10 / Using an anaconda environment

**Comment by koaning** [comment]
Ah my bad. I should've adressed it a while ago. I've added a PR for it!

**Comment by wochinge** [comment]
fixed by https://github.com/RasaHQ/rasa/pull/7023
