### ISSUE TITLE
domain.yml doesn't have a 'version' key

### ISSUE THREAD

**Issue by petasis** [RasaHQ/rasa#6927]
**Rasa version**: 2.0.0rc4

**Python version**: 3.8.5

**Operating system** (Linux):

**Issue**:
There is a warning when loading models: Training data file /tmp/tmpik18pxdo/core/domain.yml doesn't have a 'version' key. Rasa Open Source will read the file as a version '2.0' file. See https://rasa.com/docs/rasa.

However, my domain file has "version: 2.0" on top.

**Error (including full traceback)**:
```
Training data file /tmp/tmpik18pxdo/core/domain.yml doesn't have a 'version' key. Rasa Open Source will read the file as a version '2.0' file. See https://rasa.com/docs/rasa.
```

**Command or request that led to error**:
```
rasa shell
```

**Content of configuration file (config.yml)** (if relevant):
```yml

```

**Content of domain file (domain.yml)** (if relevant):
```yml
version: "2.0"
```

**Comment by sara-tagger** [comment]
Thanks for raising this issue, @tmbo will get back to you about it soon✨

###### Please also check out the [docs](https://rasa.com/docs/) and the [forum](https://forum.rasa.com/) in case your issue was raised there too 🤗

**Comment by Henrike100** [comment]
Hi, is anyone working on this issue? I would like to try to solve it.

**Comment by Henrike100** [comment]
@petasis are you still getting the same error?

I analyzed this function: https://github.com/RasaHQ/rasa/blob/d610aecdf9a6cbda3700b994b8c9bc6466c0ffb3/rasa/shared/core/domain.py#L147 and found nothing that could cause the error.

Could the problem be the python version?

**Comment by BShaq** [comment]
Is this issue already solved? I'm still getting this error..

**Comment by alwx** [comment]
Closing it due to inactivity. Please, reopen if you're still facing this problem.
