### ISSUE TITLE
Responsive Prototyper

### ISSUE THREAD

**Issue by alwx** [RasaHQ/rasa#6932]
**Description of Problem**:
Prototyper is not responsive yet. We decided to skip making it responsive because docs themselves are not completely responsive, and because it might be a significant effort — not all the components of `rasa-ui` are responsive, and making Prototyper responsive means updating some of them.

So the idea of this task is to focus on responsiveness of "Prototype your assistant" page in our docs.

See more: https://github.com/RasaHQ/rasa/pull/6821

**Comment by wochinge** [comment]
depriotized
