### ISSUE TITLE
[Rasa Interactive] Suggested file paths needs to be updated from yml to md

### ISSUE THREAD

**Issue by mprazz** [RasaHQ/rasa#6935]
**Rasa version**:
Built from source on 2.0.x branch

**Python version**: 3.7.9

**Operating system** (windows, osx, ...): OSX

**Issue**:
[These defaults](https://github.com/RasaHQ/rasa/blob/80223251645fe09b930be5945974a845ff46e1d8/rasa/core/training/interactive.py#L78-L83) need updating from `.yml` to `.md`, otherwise users will get an invalid path by entering the defaults
![image](https://user-images.githubusercontent.com/23500620/95202355-7fe9d900-07e1-11eb-9c70-bad6f4f81ecb.png)

**Comment by tmbo** [comment]
@mprazz is someone already working on this? otherwise I'll create a PR

**Comment by tmbo** [comment]
(it's also the other way around, the defaults are correct and the validation needs to be adapted. but then at the same time the dumping actually needs to use the yaml format instead of the markdown one)

**Comment by mprazz** [comment]
I don't think anyone is on this @tmbo

**Comment by degiz** [comment]
@tmbo @mprazz I fixed it yesterday as a part of https://github.com/RasaHQ/rasa/pull/6914

**Comment by tmbo** [comment]
great work 🚀
