### ISSUE TITLE
Add more flexibility to (or a way to deactivate) automatic slot filling with unique entity mappings

### ISSUE THREAD

**Issue by NetBKarine** [RasaHQ/rasa#6958]
**Description of Problem**:

Recently you added a feature (#6757) to fill slots from anywhere in the form if an entity is unambiguously associated with it in slot mappings, even replacing the old value if the slot was already set. We really appreciate this feature, it makes some dialogue patterns a lot easier to implement, but there are situations where we don't want that, like:

1.  When we have a list entity and the user actually wants to append or remove one or more values

*   Ordering pizza, the user could say "I forgot bacon" or "remove the bacon from the toppings" and the other toppings would be erased and replaced by "bacon". We could block most of these with well defined intents and a `not_intent` parameter, but then the form would reject, and to support it would be complex, because it would be a digression from the form.

1.  If the new value is invalidated by the validation action but we'd like to keep the old value instead of erasing both

*   In a banking app, the user could say: "can you make it 4000$ instead" - bot: "Sorry the amount has to be under 3000$" - user: "ok, never mind"... But we lost the first amount.

1.  If the slot is filled with an entity that can easily be falsely recognized in other sentences

*   let's say we have only one slot associated with a number entity, if users say "one" in another sentence, the slot is automatically incorrectly filled (this can happen really often in French as we have only one word for "a/an" and "one", and it might be difficult to distinguish correct cases only with the intent).

As it is, there is no way to deactivate this behaviour; we can't access the old slot value in the validation action of the form because it is already replaced in the tracker or even know easily that the slot was replaced (technically we can go through events to find the previous slot_set for this value if there is one but it is very cumbersome and unclean, and it's more of a workaround/hack than a real solution).

**Overview of the Solution**:

A. In my opinion, the best solution would be that the pre-validation/default form slot events be somehow applied _after_ the call to the validation action, so that the old values be simply accessible with `tracker.get_slot` while the new extracted values are in the events (this might be possible with the temporary tracker that is created for validation, but if not, any solution making both the new and old values accessible is good). This way we could compare the values, and keep the one we want or merge them in the way we want if there is an exceptional case.

B. A less satisfying solution would be to at least have an option to deactivate this behaviour for a slot. It could be that the `auto_fill` flag also applies to this behaviour, but since these are two different features, it probably should be a new parameter to the `from_entity` mapping. This new parameter could allow for more options: fill anytime, pre-fill but not replace, concatenate, never fill except when asked...

Ideally, both solutions would be applied (with at least a boolean flag to deactivate the behaviour for solution B), because solution A makes most exceptions feasible while still using the feature and not having to check for extra entities ourselves or using digressions for common cases, but solution B makes the third case easily avoidable.

**Definition of Done**:

*   [ ] Tests are added
*   [ ] Feature described the docs
*   [ ] Feature mentioned in the changelog

**Comment by sara-tagger** [comment]
Thanks for submitting this feature request 🚀 @rctatman will get back to you about it soon! ✨

**Comment by akelad** [comment]
@wochinge @Ghostvv any thoughts on this?

**Comment by Ghostvv** [comment]
I agree that we need to easily access old slot values in validate action, and new slot set events (added by the form action before validate) shouldn't change `tracker.slots`

**Comment by Ghostvv** [comment]
not sure about adding a flag, but if it is really useful and simplifies validate action, than we can add it as well

**Comment by wochinge** [comment]
> so that the old values be simply accessible with tracker.get_slot while the new extracted values are in the events (this might be possible with the temporary tracker that is created for validation, but if not, any solution making both the new and old values accessible is good).

I see your point. We explicitly made it this way as most users want to validate the new slot values. How about adding a helper to the Rasa SDK which extracts the previous slot values?

**Comment by NetBKarine** [comment]
> > so that the old values be simply accessible with tracker.get_slot while the new extracted values are in the events (this might be possible with the temporary tracker that is created for validation, but if not, any solution making both the new and old values accessible is good).
> 
> I see your point. We explicitly made it this way as most users want to validate the new slot values. How about adding a helper to the Rasa SDK which extracts the previous slot values?

@wochinge It would still be a bit weird to have to explicitly get and re-set the old value, (it seems more instinctive that the previous value would be kept automatically if validation rejects a new one), but I think it would be a satisfying solution for usability.

**Comment by Ghostvv** [comment]
@wochinge I think we reset old slots with new candidates because it was the easiest way to pass the new values through temporary tracker, but I agree with @NetBKarine that it'd be more intuitive to not override old values

**Comment by wochinge** [comment]
Mhm, I think we can implement your logic without breaking existing behavior by simply appending (but not applying) the new `SlotSet` events for temporary tracker which we send to the SDK. Your validation method in `FormValidationAction` would still need to return a `SlotSet` event which sets the slot the old value though 🤔
