### ISSUE TITLE
Update Slack Connector to new Slack Events API

### ISSUE THREAD

**Issue by b-quachtran** [RasaHQ/rasa#6961]
Slack has updated their Events API (documented [here](https://api.slack.com/changelog/2020-09-15-events-api-truncate-authed-users#what)) and have deprecated their previous API format. 

While existing Slack apps can opt-out of the update until February 24th, 2021, Slack apps created after September 29th will only use the new Events API that breaks compatibility with the Slack Connector. 

The primary change is that `auth_users` has been removed from the API and replaced with `authorizations`. E.g.:
```
 "authorizations": [
        {
            "enterprise_id": "E12345",
            "team_id": "T12345",
            "user_id": "U12345",
            "is_bot": false,
        }
  ],
```

 The connector will need to be updated to properly use this new field

**Comment by anuragdtnomy** [comment]
i am still having the same issue.
"for uid_to_remove in uids_to_remove:
TypeError: 'NoneType' object is not iterable
"

**Comment by aravindkota** [comment]
When is this change going to be available for us. Waiting for your response and solution for this issue.

Any help is appreciated

**Comment by anuragdtnomy** [comment]
can you please undo the changes as every thing was working fine before 10 days.
still having the same issue
"for uid_to_remove in uids_to_remove:
TypeError: 'NoneType' object is not iterable.

**Comment by b-quachtran** [comment]
Hi @anuragdtnomy @aravindkota, the PR with the fix has been merged into master and is awaiting release with the next patch.

**Comment by SindhuMohana** [comment]
Hello , Please can you update by when will the fix be available ?
