### ISSUE TITLE
Additions to information collected by telemetry

### ISSUE THREAD

**Issue by dakshvar22** [RasaHQ/rasa#6963]
**Description of Problem**:

1.  Number of examples defined for retrieval intents is not tracked by telemetry.
2.  Would be great if we can also track the performance of all ML components like `CRFEntityExtractor`, `DIETClassifier`, `ResponseSelector` and core policies like `TED`

**Overview of the Solution**: (1) is straightforward since we already track number of intent and entity examples. Information for (2) is also available while doing evaluation. We just need to add it to our telemetry.

**Comment by Henrike100** [comment]
Hi, is anyone working on this issue? I would like to try to solve it.

**Comment by m-vdb** [comment]
thanks for proposing your help @Henrike100 🙏 this issue might prove a bit hard to tackle for someone not part of the Rasa team, as telemetry is an internal tool, and testing any update to the code might prove a bit difficult

**Comment by Henrike100** [comment]
Well, I think I solved part 1 of the problem.

If I'm correct, I have to change this function:
https://github.com/RasaHQ/rasa/blob/2dca916c8e0b7d16e35a11ed3f7e854d15dd5196/rasa/telemetry.py#L650

and I have to do something similar to:
https://github.com/RasaHQ/rasa/blob/2dca916c8e0b7d16e35a11ed3f7e854d15dd5196/rasa/telemetry.py#L684

but with nlu_data.retrieval_intents

If I'm wrong, please correct me.
However, I did not understand part 2 of the problem. If someone from Rasa can explain to me what needs to be done, I would be grateful.
