### ISSUE TITLE
Send potential `ActionExecutionRejected` after form validation

### ISSUE THREAD

**Issue by wochinge** [RasaHQ/rasa#6977]
The `FormAction` currently returns an `ActionExecutionRejected` event in case there were no slot candidates extracted (see [here](https://github.com/RasaHQ/rasa/blob/6764365ed8f1104d938d77c489f5ea9fcfe00e6f/rasa/core/actions/forms.py#L452)).
The problem is that with Rasa Open Source 2.0 users can extract custom slots in their custom `validate` action. In case they only extract slots manually, it currently throws a `ActionExecutionRejected`. Instead it should run the custom validate function and decide then whether a `ActionExecutionRejected` event should be returned.

Notes by @Ghostvv 
> we need to think how custom vs default validation works and how to notify form through custom validation action

**Comment by ArjaanBuijk** [comment]
I tried to use ActionExecutionRejected for implementing some logic, but got stuck because it is not possible to set slots at the same time. It would be a good enhancement I think to allow to set slots.
