### ISSUE TITLE
Validate if all actions appear in the domain

### ISSUE THREAD

**Issue by MichaelMarien** [RasaHQ/rasa#6987]
**Description of Problem**: Currently the **verify_utterances_in_stories** method of the [https://github.com/RasaHQ/rasa/blob/master/rasa/validator.py](https://github.com/RasaHQ/rasa/blob/master/rasa/validator.py) class is only checking if all utterances that appear in the stories are defined in the domain.

**Overview of the Solution**: I suggest to extend this check to all actions. Error should be thrown if actions are used in stories that do no appear in the domain. If agreed upon, I'm happy to make a PRQ.

**Definition of Done**:

*   [ ] Tests are added
*   [ ] Feature described the docs
*   [ ] Feature mentioned in the changlog

**Comment by sara-tagger** [comment]
Thanks for submitting this feature request 🚀 @koaning will get back to you about it soon! ✨
