### ISSUE TITLE
chinese whitespace bug?

### ISSUE THREAD

**Issue by w7lau** [RasaHQ/rasa#6988]
python 3.7.8
rasa 2.0.0rc4
windows 10

config.xml

version: "2.0"
language: zh
pipeline:
  - name: "SpacyNLP"
    model: "zh_core_web_md"
  - name: SpacyTokenizer
  - name: SpacyFeaturizer
  - name: DIETClassifier
    epochs: 300
  - name: RegexEntityExtractor
  - name: RegexFeaturizer 
- name: ResponseSelector
    epochs: 400
    scale_loss: false
  
policies:
  - name: AugmentedMemoizationPolicy
  - name: TEDPolicy
    epochs: 300
  - name: "RulePolicy"
    core_fallback_threshold: 0.3
    core_fallback_action_name: action_greet
    enable_fallback_prediction: true
    restrict_rules: true
    check_for_contradictions: true

nlu.xml:
version: "2.0"
nlu:
- intent: ask_something
  examples: |
    - 我要买[男](user_sex)的东西

when I input 我要买男的东西 , it can't get the entity ,if I change the examples to 我要买[男](user_sex) 的东西 , input 我要买男的东西 can't get this intent, but 我要买男 的东西 can work, my config error or a bug?

**Comment by sara-tagger** [comment]
Thanks for the issue, @tttthomasssss will get back to you about it soon!

###### You may find help in the [docs](https://rasa.com/docs/) and the [forum,](https://forum.rasa.com/) too 🤗

**Comment by matthewkos** [comment]
I encounter the same problem, my solution:
```
    def get_emoji_regex():
        return re.compile(
            "["
            "\U0001F600-\U0001F64F"  # emoticons
            "\U0001F300-\U0001F5FF"  # symbols & pictographs
            "\U0001F680-\U0001F6FF"  # transport & map symbols
            "\U0001F1E0-\U0001F1FF"  # flags (iOS)
            "\U00002702-\U000027B0"
            #"\U000024C2-\U0001F251"  # CJK is included
            "\u200d"  # zero width joiner
            "\u200c"  # zero width non-joiner
            "]+",
            flags=re.UNICODE,
        )
```
comment out that line as I did in whitespace_tokenizer

A better way is to write a custom tokenizer for the Chinese tokenization as I did

**Comment by w7lau** [comment]
> I encounter the same problem, my solution:
> 
> ```
>     def get_emoji_regex():
>         return re.compile(
>             "["
>             "\U0001F600-\U0001F64F"  # emoticons
>             "\U0001F300-\U0001F5FF"  # symbols & pictographs
>             "\U0001F680-\U0001F6FF"  # transport & map symbols
>             "\U0001F1E0-\U0001F1FF"  # flags (iOS)
>             "\U00002702-\U000027B0"
>             #"\U000024C2-\U0001F251"  # CJK is included
>             "\u200d"  # zero width joiner
>             "\u200c"  # zero width non-joiner
>             "]+",
>             flags=re.UNICODE,
>         )
> ```
> 
> comment out that line as I did in whitespace_tokenizer
> 
> A better way is to write a custom tokenizer for the Chinese tokenization as I did

I saw the document say whitespace_tokenizer dosen't support Chinese?

**Comment by joejuzl** [comment]
Closing as whitespace_tokenizer dosen't support Chinese and a custom component is preferrable.
