### ISSUE TITLE
Investigate migrations from other platforms to 2.0

### ISSUE THREAD

**Issue by TyDunn** [RasaHQ/rasa#6991]
Part of this umbrella ticket: https://github.com/RasaHQ/rasa/issues/6474

There have been a few changes/updates to some of the platforms we offer migrations:
- [ ] Dialogflow
- [ ] LUIS
- [ ] wit.ai
 
We need to determine if there are any updates we need to make to:
- convert to the new yaml training data
- read any new training data formats from Dialoglfow

Then, we will be able to implement any updates to convertors and update the docs.

The outcome of this ticket is to update these tickets to reflect what we need to do to:
- [update convertors](https://github.com/RasaHQ/rasa/issues/6993)
- [update docs](https://github.com/RasaHQ/rasa/issues/6994)

**Comment by wochinge** [comment]
closed by @alwx PRs
