### ISSUE TITLE
Rasa interactive will not save .yml files 

### ISSUE THREAD

**Issue by Misara** [RasaHQ/rasa#6997]
**Rasa version**:
Rasa Version     : 2.0.0rc2

**Rasa SDK version** (if used & relevant):
Rasa SDK Version : 2.0.0

**Rasa X version** (if used & relevant):
Rasa X Version   : 0.32.2

**Python version**:
Python Version   : 3.7.7

**Operating system** (windows, osx, ...):
OSX

**Issue**:
When using the rasa interactive cli, it will not save the resulting data as a .yml file despite suggesting the default file path and a .yml extension. It says the path is not valid. When I change the file extension to .md, it saves successfully.
<img width="721" alt="Screen Shot 2020-10-12 at 2 53 19 PM" src="https://user-images.githubusercontent.com/13578856/95794227-419a6100-0c9c-11eb-904a-1ec113ba58ff.png">
<img width="718" alt="Screen Shot 2020-10-12 at 3 06 13 PM" src="https://user-images.githubusercontent.com/13578856/95794372-91792800-0c9c-11eb-8965-b5de13f580af.png">
<img width="713" alt="Screen Shot 2020-10-12 at 3 06 26 PM" src="https://user-images.githubusercontent.com/13578856/95794375-93db8200-0c9c-11eb-899c-5b0be782e684.png">

**Command or request that led to error**:
```
rasa interactive
....usage of rasa interactive.....
Export & Quit
```

**Comment by amn41** [comment]
hi @Misara ! this was a bug in the rc which you are running. If you update to the release `rasa==2.0.0` this issue is resolved :)

**Comment by sara-tagger** [comment]
Thanks for the issue, @rctatman will get back to you about it soon!

###### You may find help in the [docs](https://rasa.com/docs/) and the [forum,](https://forum.rasa.com/) too 🤗
