### ISSUE TITLE
Allow rasa-x to be installed on Python 3.8

### ISSUE THREAD

**Issue by kunalbhagawati** [RasaHQ/rasa#7007]
**Rasa-x seems to only be supported for Python: '>=3.6,<3.8'**:
Given that Rasa 2 is released and is supported on Python 3.8, rasa-x should be supported likewise.

**Examples**:
```
(.venv) kunal@[code/rasa-assistant/] ➤  python --version                                                                                                                                ±[●][rasa_2]
Python 3.8.2
(.venv) kunal@[code/rasa-assistant/] ➤  pip install rasa-x --extra-index-url https://pypi.rasa.com/simple                                                                               ±[●][rasa_2]
Looking in indexes: https://pypi.org/simple, https://pypi.rasa.com/simple
Collecting rasa-x
  Downloading https://pypi.rasa.com/api/package/rasa-x/rasa_x-0.32.2-py3-none-any.whl (1.9 MB)
     |████████████████████████████████| 1.9 MB 342 kB/s 
ERROR: Package 'rasa-x' requires a different Python: 3.8.2 not in '>=3.6,<3.8'
```

**Definition of Done**:
`pip install rasa-x --extra-index-url https://pypi.rasa.com/simple` should install for `Python 3.8.2`

**Comment by sara-tagger** [comment]
Thanks for submitting this feature request 🚀 @akelad will get back to you about it soon! ✨

**Comment by akelad** [comment]
@wochinge is that planned for the upcoming release?

**Comment by wochinge** [comment]
Yes, 3.8 compatibility is part of the 0.33 release which is currently in QA. So you can expected a suitable version end of this week / beginning of next week @kunalbhagawati

**Comment by kunalbhagawati** [comment]
Thanks team, this really helps us out. 👍

**Comment by santhosh432** [comment]
thanks
