### ISSUE TITLE
Module imported twice

### ISSUE THREAD

**Issue by sureshdsk** [RasaHQ/rasa#7009]
https://github.com/RasaHQ/rasa/blob/ed58e43944789f0468c198889c9231de38251417/rasa/core/run.py#L99-L99
https://github.com/RasaHQ/rasa/blob/ed58e43944789f0468c198889c9231de38251417/rasa/core/run.py#L170-L170

module server is already imported at the top.

**Comment by sara-tagger** [comment]
Thanks for the issue, @amn41 will get back to you about it soon!

###### You may find help in the [docs](https://rasa.com/docs/) and the [forum,](https://forum.rasa.com/) too 🤗

**Comment by wochinge** [comment]
closed because negligible
