### ISSUE TITLE
ActionExecuted class imported twice

### ISSUE THREAD

**Issue by sureshdsk** [RasaHQ/rasa#7015]
https://github.com/RasaHQ/rasa/blob/8aea0d05fa9467cb3e78a08d6b183895b1faccf7/rasa/shared/importers/importer.py#L446-L446

ActionExecuted is already imported at the top level

**Comment by sara-tagger** [comment]
Thanks for raising this issue, @amn41 will get back to you about it soon✨

###### Please also check out the [docs](https://rasa.com/docs/) and the [forum](https://forum.rasa.com/) in case your issue was raised there too 🤗

**Comment by alwx** [comment]
Closing because the PR was merged. Thanks!
