### ISSUE TITLE
Module imported but unused

### ISSUE THREAD

**Issue by sureshdsk** [RasaHQ/rasa#7041]
## Description
A module has been imported but is not used anywhere in the file. Unused imports should be removed.

## Occurrences

- Unused YAMLStoryReader imported from rasa.shared.core.training_data.story_reader.yaml_story_reader https://github.com/RasaHQ/rasa/blob/de2f1ac1739cc05f4ab6d582a0feb626c0eaa636/rasa/core/training/interactive.py#L793-L795
- Unused common imported from rasa.utils as common_utils https://github.com/RasaHQ/rasa/blob/de2f1ac1739cc05f4ab6d582a0feb626c0eaa636/rasa/server.py#L30-L30
- Unused rasa.cli.utils imported as cli_utils https://github.com/RasaHQ/rasa/blob/de2f1ac1739cc05f4ab6d582a0feb626c0eaa636/rasa/core/exporter.py#L8-L8
- Unused common imported from rasa.utils as common_utils https://github.com/RasaHQ/rasa/blob/de2f1ac1739cc05f4ab6d582a0feb626c0eaa636/rasa/core/policies/mapping_policy.py#L9-L9
- Unused YamlValidationException imported from rasa.shared.utils.validation https://github.com/RasaHQ/rasa/blob/de2f1ac1739cc05f4ab6d582a0feb626c0eaa636/rasa/shared/core/domain.py#L26-L26
- Unused Path imported from pathlib https://github.com/RasaHQ/rasa/blob/de2f1ac1739cc05f4ab6d582a0feb626c0eaa636/rasa/shared/importers/autoconfig.py#L5-L5

**Comment by sara-tagger** [comment]
Thanks for raising this issue, @rctatman will get back to you about it soon✨

###### Please also check out the [docs](https://rasa.com/docs/) and the [forum](https://forum.rasa.com/) in case your issue was raised there too 🤗

**Comment by wochinge** [comment]
we've fixed that by enabling the flake8 test for this
