### ISSUE TITLE
POST /model/test/intents can't deal with a model as URL

### ISSUE THREAD

**Issue by degiz** [RasaHQ/rasa#7051]
**Rasa version**: 2.0.0

When Rasa X is used to evaluate intents, it sends a `POST /model/test/intents ` request to Rasa Open Source with a URL opf the model as a `model` parameter. Example:

Rasa X: `PUT /api/projects/default/evaluations/20201019-130643` leads to Rasa Open Source: `POST /model/test/intents` with `model=[http://localhost:5002/api/projects/default/models/tags/evaluation](http://localhost:5002/api/projects/default/models/tags/evaluation)`.

Rasa Open Source cannot process that request atm, because it treats the `model` as a local filepath, or ignores the `model` parameter completely and tries to fetch the model from the model server defined in `enpoinsts.yml`.

We need to enable Rasa Open Source to process the `model` parameter correctly when it's a valid URL. However, it's tricky because Rasa X uses authorization.

**Comment by mjaycub** [comment]
@RasaHQ/enable-squad since this is on the Rasa Open Source side and deals with the model lifecycle, this seems like a better issue for your Inbox, do you agree?

**Comment by wochinge** [comment]
We can have a look 👍🏻  From looking at the code (haven't tried it out) I can't see how this would happen though 🤔
