### ISSUE TITLE
Custom Config.env pass from the commandline to set env variables.

### ISSUE THREAD

**Issue by Ajju2211** [RasaHQ/rasa#7054]
**Description of Problem & solution**:

While running the rasa run command I want to set the env variables because ,
If I am working on the local machine then I need to run the config.env.py script to set the environment variables.
And on the deployment I could not pass it in the docker because security issues.
So I want to pass them through the env variables setup on the cloud server setup.
Its not a problem to set env in the cloud server dashboard.
But its really a problem everytime to set the new env variables on the local machine.

It should be so easy to setup the config.env.py during running the rasa run command itself.

```
rasa run --env-set PATH_TO_ENV_FILE.yml or .py
```
```
rasa run --env-set DB_PASSWORD=password
Like this if it there then it becomes easy to set during the rasa run command itself.
And also in the credentials.yml we can pass the ENV variable instead of direct value.

**Comment by sara-tagger** [comment]
Thanks for submitting this feature request 🚀 @amn41 will get back to you about it soon! ✨

**Comment by amn41** [comment]
hi @Ajju2211 - thanks for creatign an issue. 

Just so i understand, what's the problem with writing a bash script? e.g.

```
export DB_PASSWORD=password
rasa run
```

then saving this as e.g. `run_rasa.sh` and running that script?

**Comment by Ajju2211** [comment]
But I have to git ignore the env file because it contains some sensitive information.

**Comment by amn41** [comment]
in the issue description you say you are looking for a solution that works on your local machine. You can store the sensitive information in your bash script (`run_rasa.sh`) and you can gitignore it because it doesn't have to leave your machine.

**Comment by Ajju2211** [comment]
In credentials.yml also we are passing some secrets, in place of secrets if we can pass FB_SECRET env variable then it is better.
So that we can hide my secret values.
I don't know credentials.yml support env variables.
Instead of running bash script its better to have a .env  file and passing it in the rasa run command.

And one more problem is that everyone doesn't have linux and windows sub linux support so its again probleme.
So setting the environment variable using python **dot-env** is better.
So if their is a dot-env setup through rasa then its better.

**Comment by amn41** [comment]
thanks @Ajju2211 - I see where you're coming from, but I don't see this as a sufficiently compelling use case that we should add a feature for it. The way I see it, there are good-enough solutions that you can already use to address these problems, and adding more configuration options to Rasa creates more room for bugs, so I'd like to avoid that.
