### ISSUE TITLE
POST `/model/test/intents` endpoint fails

### ISSUE THREAD

**Issue by kalkbrennerei** [RasaHQ/rasa#7063]
**Rasa version**: 2.0.0

**Python version**: 3.7

**Operating system** (windows, osx, ...): osx

**Issue**:
Calling POST `/model/test/intents` endpoint from `rasa x` with correct `model` path and body causes `500 Internal Server Error`

**Error (including full traceback)**:
```
{
    "version": "2.0.0",
    "status": "failure",
    "message": "An unexpected error occurred during evaluation. Error: Unknown data format for file '/var/folders/7y/mgv9hfvs45l75j9mn_5gxv2h0000gr/T/tmp93blnen6.md'.",
    "reason": "TestingError",
    "details": {},
    "help": null,
    "code": 500
}

2020-10-19 15:48:44 ERROR    rasa.server  - Traceback (most recent call last):
  File "/Users/rasa/.pyenv/versions/3.7.6/envs/rasa_376/lib/python3.7/site-packages/rasa/server.py", line 891, in evaluate_intents
    evaluation = run_evaluation(data_path, nlu_model, disable_plotting=True)
  File "/Users/rasa/.pyenv/versions/3.7.6/envs/rasa_376/lib/python3.7/site-packages/rasa/nlu/test.py", line 1476, in run_evaluation
    data_path, interpreter.model_metadata.language
  File "/Users/rasa/.pyenv/versions/3.7.6/envs/rasa_376/lib/python3.7/site-packages/rasa/shared/nlu/training_data/loading.py", line 60, in load_data
    data_sets = [_load(f, language) for f in files]
  File "/Users/rasa/.pyenv/versions/3.7.6/envs/rasa_376/lib/python3.7/site-packages/rasa/shared/nlu/training_data/loading.py", line 60, in <listcomp>
    data_sets = [_load(f, language) for f in files]
  File "/Users/rasa/.pyenv/versions/3.7.6/envs/rasa_376/lib/python3.7/site-packages/rasa/shared/nlu/training_data/loading.py", line 107, in _load
    raise ValueError(f"Unknown data format for file '{filename}'.")
ValueError: Unknown data format for file '/var/folders/7y/mgv9hfvs45l75j9mn_5gxv2h0000gr/T/tmp93blnen6.md'.

2020-10-19 15:48:44 ERROR    rasa.server  - An unexpected error occurred during evaluation. Error: Unknown data format for file '/var/folders/7y/mgv9hfvs45l75j9mn_5gxv2h0000gr/T/tmp93blnen6.md'.
```

**Command or request that led to error**:
```
POST localhost:5002/model/test/intents?model=20201014-170303.tar.gz
```

**Comment by kalkbrennerei** [comment]
my findings so far:

the request body I provided is in JSON format (which I get when calling from `rasa x`). It seems like the support for JSON was removed in 2.0

**Comment by wochinge** [comment]
@federicotdn @degiz Can one of you please confirm? Do we need to update the API spec then?

**Comment by degiz** [comment]
I can definitely confirm that, since we've been debugging this issue together with @kalkbrennerei 

I'd rather fix this problem that just update the spec.

**Comment by wochinge** [comment]
@degiz @kalkbrennerei Could it be that the issue is that [this](https://github.com/RasaHQ/rasa/blob/aec8e57425dae174c401f2add3f7dd428f6c5977/rasa/server.py#L1150) stores the file as `.md` while we send a `json`?

**Comment by wochinge** [comment]
@kalkbrennerei What's the state of this issue? can it be closed?

**Comment by kalkbrennerei** [comment]
Ohhhh, I think the description is still up to date... But I also didn't work on it 😬 I just tried to run it again with rasa 2.2.7 and it's the same. It's not scale squad related so I will unassign...

**Comment by rgstephens** [comment]
I've just run into this also with 2.2

**Comment by rgstephens** [comment]
This is a report from another system. In this case the return status is 200.

```sh
curl -X POST -d '{"model":"20210121-211252.tar.gz"}' http://localhost:5010/model/test/intents -v
* About to connect() to localhost port 5010 (#0)
*   Trying 127.0.0.1...
* Connected to localhost (127.0.0.1) port 5010 (#0)
> POST /model/test/intents HTTP/1.1
> User-Agent: curl/7.29.0
> Host: localhost:5010
> Accept: */*
> Content-Length: 34
> Content-Type: application/x-www-form-urlencoded
> 
* upload completely sent off: 34 out of 34 bytes
< HTTP/1.1 200 OK
< Access-Control-Expose-Headers: filename
< Access-Control-Allow-Credentials: true
< Content-Length: 88
< Content-Type: application/json
< Connection: keep-alive
< Keep-Alive: 5
< 
* Connection #0 to host localhost left intact
{"intent_evaluation":null,"entity_evaluation":null,"response_selection_evaluation":null}
```

**Comment by alwx** [comment]
@rgstephens could you please share more details about the project and model that was used in the first case? Did it contain any `.md` files?  I tried to reproduce it with a new project, and got this:

```
(base) ➜  ~ curl -X POST -d '{"model":"20210208-160756.tar.gz"}' http://localhost:5005/model/test/intents -v
Note: Unnecessary use of -X or --request, POST is already inferred.
*   Trying 127.0.0.1...
* TCP_NODELAY set
* Connected to localhost (127.0.0.1) port 5005 (#0)
> POST /model/test/intents HTTP/1.1
> Host: localhost:5005
> User-Agent: curl/7.64.1
> Accept: */*
> Content-Length: 34
> Content-Type: application/x-www-form-urlencoded
>
* upload completely sent off: 34 out of 34 bytes
< HTTP/1.1 200 OK
< Access-Control-Expose-Headers: filename
< Access-Control-Allow-Credentials: true
< Content-Length: 88
< Content-Type: application/json
< Connection: keep-alive
< Keep-Alive: 5
<
* Connection #0 to host localhost left intact
{"intent_evaluation":null,"entity_evaluation":null,"response_selection_evaluation":null}
```

**Comment by jeffreyhochgesang** [comment]
@alwx 

Here are the details for the model @rgstephens mentioned. This was trained from the the helpdesk assistant example, but It's also happening with models we've trained from the ground up.

![rasa_model_structure](https://user-images.githubusercontent.com/78817599/107409632-36780600-6ac1-11eb-9a4b-eacc5fdc685a.png)

**Comment by akelad** [comment]
@alwx helpdesk assistant example meaning: https://github.com/RasaHQ/helpdesk-assistant

**Comment by alwx** [comment]
Tested it with both https://github.com/RasaHQ/helpdesk-assistant and the project created with `rasa init` — the result is two PRs for both Rasa and Rasa X :)

**Comment by jeffreyhochgesang** [comment]
Thanks @alwx! I'll test and report back when we get that new version.
