### ISSUE TITLE
UnsupportedModelError could be made clearer.

### ISSUE THREAD

**Issue by koaning** [RasaHQ/rasa#7069]
I was using Rasa 1.10 to load in a Rasa 2.0 model. This was accidental on my part, but the error message seems to assume that you're loading in an "older" model. It is also throw when you're loading in a newer model.

Here's the error I got. 

```
UnsupportedModelError: The model version is too old to be loaded by this Rasa NLU instance. Either retrain the model, or run with an older version. Model version: 1.10.3 Instance version: 2.0.0
```

Would anybody oppose if we change it to; 

```
UnsupportedModelError: The model was trained using Rasa 1.10.3 and does not match your Rasa installation (2.0.0). This means that you probably want to retrain your model to ensure that the versions match up again. 
```

I'll gladly pick it up when I get a green light.

**Comment by TyDunn** [comment]
@koaning @alwx and I discussed that this makes sense, so I think you can go ahead 👍
