### ISSUE TITLE
UserWarning: Intent 'nlu_fallback' has only 1 training examples! Minimum is 2, training may fail.

### ISSUE THREAD

**Issue by tatianafrank** [RasaHQ/rasa#7076]
**Rasa version**: 2.0

**Rasa SDK version** (if used & relevant):

**Rasa X version** (if used & relevant):

**Python version**: 3.7.0

**Operating system** (windows, osx, ...): osx

**Issue**:
Invalid warning in rasa shell about nlu_fallback

**Error (including full traceback)**:
```
UserWarning: Intent 'nlu_fallback' has only 1 training examples! Minimum is 2, training may fail.
```

**Command or request that led to error**:
```
rasa shell
```

**Content of configuration file (config.yml)** (if relevant):
```yml

```

**Content of domain file (domain.yml)** (if relevant):
```yml

```

**Comment by sara-tagger** [comment]
Thanks for the issue, @rgstephens will get back to you about it soon!

###### You may find help in the [docs](https://rasa.com/docs/) and the [forum,](https://forum.rasa.com/) too 🤗

**Comment by akelad** [comment]
I was just able to reproduce this with the `examples/rules` bot as well, it seems to happen for any intent that is listed in the domain, but doesn't have nlu training examples. That shouldn't happen, it's perfectly fine to list an intent in the domain, but not have training examples for it.

Result from `rasa train` when running on `examples/rules` with version 2.0.2:

```
(rasa-poetry) akela@BERMB00007 rules % rasa train
2020-10-23 11:11:50 INFO     rasa.model  - Data (version) for Core model section changed.
2020-10-23 11:11:50 INFO     rasa.model  - Data (nlu-config) for NLU model section changed.
Training NLU model...
2020-10-23 11:11:51 INFO     rasa.shared.nlu.training_data.training_data  - Training data stats:
2020-10-23 11:11:51 INFO     rasa.shared.nlu.training_data.training_data  - Number of intent examples: 286 (15 distinct intents)

2020-10-23 11:11:51 INFO     rasa.shared.nlu.training_data.training_data  -   Found intents: 'ask_possibilities', 'inform', 'thankyou', 'greet', 'faq', 'request_restaurant', 'explain', 'nlu_fallback', 'bot_challenge', 'stop', 'deny', 'affirm', 'activate_q_form', 'switch_faq', 'chitchat'
2020-10-23 11:11:51 INFO     rasa.shared.nlu.training_data.training_data  - Number of response examples: 0 (0 distinct responses)
2020-10-23 11:11:51 INFO     rasa.shared.nlu.training_data.training_data  - Number of entity examples: 130 (3 distinct entities)
2020-10-23 11:11:51 INFO     rasa.shared.nlu.training_data.training_data  -   Found entity types: 'cuisine', 'seating', 'feedback'
/Users/akela/Documents/rasa-new/rasa/shared/utils/io.py:93: UserWarning: Intent 'activate_q_form' has only 1 training examples! Minimum is 2, training may fail.
/Users/akela/Documents/rasa-new/rasa/shared/utils/io.py:93: UserWarning: Intent 'ask_possibilities' has only 1 training examples! Minimum is 2, training may fail.
/Users/akela/Documents/rasa-new/rasa/shared/utils/io.py:93: UserWarning: Intent 'explain' has only 1 training examples! Minimum is 2, training may fail.
/Users/akela/Documents/rasa-new/rasa/shared/utils/io.py:93: UserWarning: Intent 'faq' has only 1 training examples! Minimum is 2, training may fail.
/Users/akela/Documents/rasa-new/rasa/shared/utils/io.py:93: UserWarning: Intent 'nlu_fallback' has only 1 training examples! Minimum is 2, training may fail.
/Users/akela/Documents/rasa-new/rasa/shared/utils/io.py:93: UserWarning: Intent 'switch_faq' has only 1 training examples! Minimum is 2, training may fail.
```

**Comment by xinru1414** [comment]
I have a similar issue here but caused by a different command

**Rasa Version**: 2.0.2
**Rasa SDK Version** : 2.0.0
**Rasa X Version**: 0.33.0
**Python Version**: 3.7.7
**Operating System**: MacOS

**Issue**: invalid warning using nlu_fallback intent triggered by FallbackClassifier
**Command or request that led to error**: [Rasa fallback-handoff Guide](https://rasa.com/docs/rasa/fallback-handoff)
**Content of configuration file**:
   - name: FallbackClassifier
     threshold: 0.3
     ambiguity_threshold: 0.1

**Specifics**:
I followed [this guide](https://rasa.com/docs/rasa/fallback-handoff) to handle fallbacks (under section "Fallbacks" --> NLU Fallback"). Basically the guide listed three things to do: 

1.  Use FallbackClassifier
2. Define utter_please_rephrase
3. Create NLU fallback rule

I did exactly those three things. It does not say we need to define a nlu_fallback intent in the nlu.yml file with several examples (hence I didn't define it).

**Comment by boryslawskamaria** [comment]
Hi, I have the exact same problem, is there any way to resolve this?

**Comment by boryslawskamaria** [comment]
hi, one more thing: I created a repo in which I set up a mini bot that exhibits the aforementioned problem. Feel free to download it and have a look https://github.com/boryslawskamaria/chatbots/tree/main/minibot_fallback_test 

The error I keep getting is always github/chatbots/.env/lib/python3.6/site-packages/rasa/shared/utils/io.py:93: UserWarning: Intent 'nlu_fallback' has only 1 training examples! Minimum is 2, training may fail.

**Comment by akelad** [comment]
@boryslawskamaria you can ignore the warning, it's a warning that shouldn't come up. We will work on removing it at some point

**Comment by joejuzl** [comment]
@ancalita Do you think your PR https://github.com/RasaHQ/rasa/pull/8349 also fixes this issue?

**Comment by ancalita** [comment]
Yes, PR #8349 solves the original issue flagged by the first user.

**Comment by joejuzl** [comment]
> Yes, PR #8349 solves the original issue flagged by the first user.
Great!
