### ISSUE TITLE
Chinese or other non-whitespace(maybe) language to use regex ,such as lookup tables

### ISSUE THREAD

**Issue by w7lau** [RasaHQ/rasa#7091]
https://github.com/RasaHQ/rasa/blob/6fbee0dbd67abeccb5544b4f3d53d26f636c5c0c/rasa/nlu/extractors/regex_entity_extractor.py#L89
change to
`matches = re.finditer(pattern["pattern"].replace('\\b',''), message.get(TEXT), flags=flags)`

https://github.com/RasaHQ/rasa/blob/6fbee0dbd67abeccb5544b4f3d53d26f636c5c0c/rasa/nlu/featurizers/sparse_featurizer/regex_featurizer.py#L131
change to
`matches = re.finditer(pattern["pattern"].replace('\\b',''), message.get(TEXT), flags=flags)`

I test in windows 10,python 3.7.6,rasa 2.0.2
maybe when get the config language=='zh' can ues this?

**Comment by sara-tagger** [comment]
Thanks for submitting this feature request 🚀 @TyDunn will get back to you about it soon! ✨

**Comment by tabergma** [comment]
@w7lau Thanks for raising the issue! I think you might be right and we should add the word boundary to the regex for non-whitespace tokenized language, such as Chinese. 

I think we should modify the code in https://github.com/RasaHQ/rasa/blob/master/rasa/nlu/utils/pattern_utils.py. We could maybe pass on the language and modify the regex depending on the language given. 

@w7lau Do you have an example sentence and regex to test the behaviour? Do you want to submit a PR for this?

**Comment by w7lau** [comment]
> @w7lau Thanks for raising the issue! I think you might be right and we should not add the word boundary to the regex for non-whitespace tokenized language, such as Chinese.
> 
> I think we should modify the code in https://github.com/RasaHQ/rasa/blob/master/rasa/nlu/utils/pattern_utils.py. We could maybe pass on the language and modify the regex depending on the language given.
> 
> @w7lau Do you have an example sentence and regex to test the behaviour? Do you want to submit a PR for this?

Ok，I will try to do this.

**Comment by tabergma** [comment]
@w7lau Great! Let me know if you need help.

**Comment by w7lau** [comment]
@tjpalmer Is example correct like https://github.com/w7lau/rasa-Chinese-test ?
And the pr at https://github.com/RasaHQ/rasa/pull/7107 
But I don't know why the pr checks is failed...

**Comment by wochinge** [comment]
fixed by https://github.com/RasaHQ/rasa/pull/7422
