### ISSUE TITLE
Update action_session_start customisation code sample in Default Actions docs

### ISSUE THREAD

**Issue by digitalWestie** [RasaHQ/rasa#7094]
**Description of Problem**:

I’m using Rasa 2.0, and have an actions server set up with a custom action working correctly. I wanted to try customising the `action_session_start` action, however, using the code sample in the docs for [Default Actions](https://rasa.com/docs/rasa/default-actions#customization) I get errors about EventType being undefined.

I describe the issue in detail in this forum post: https://forum.rasa.com/t/are-2-0-docs-obsolete-for-customising-action-session-start/36219

**Overview of the Solution**:

Unless I've missed something big, it seems to me the code sample is for a previous version of Rasa?

I have a new code sample here that follows the same logic and works:

https://forum.rasa.com/t/are-2-0-docs-obsolete-for-customising-action-session-start/36219/2?u=digitalwestie

**Definition of Done**:
- [ ] Code sample is updated in docs

**Comment by sara-tagger** [comment]
Thanks for submitting this feature request 🚀 @tabergma will get back to you about it soon! ✨

**Comment by tmbo** [comment]
@digitalWestie do you mind creating a PR for this, I just ran into this as well

**Comment by digitalWestie** [comment]
@tmbo ok so that confirms it! Sure I'll send a PR.

**Comment by digitalWestie** [comment]
Here we go: https://github.com/RasaHQ/rasa/pull/7287
