### ISSUE TITLE
Need a way to inject a User request so that story can bypass some steps on certain steps in a story

### ISSUE THREAD

**Issue by sibbsnb** [RasaHQ/rasa#7101]
**Description of Problem**:
Currently there is no way to skip a User utterance using business logic other than using a code like below:
```python
@staticmethod
def start_story_events(story_intent):
    # type: (Text) -> List[Dict]
    return [ActionExecuted("action_listen")] + [UserUttered("/" + story_intent, {
        "intent": {"name": story_intent, "confidence": 1.0},
        "entities": {}
    })]
```

**Overview of the Solution**:
Have an inbuilt way of doing this rather than custom injection of user intent to the history

**Examples** (if relevant):
If i have a story like below:
```markdown
## story 1
*intent_1
   action_step1
*intent_2
   action_step2
*intent_3
  action_step3
```

If while executing step_2, during certain conditions, want to avoid a answer from User with intent_3 but want to proceed with action_step3

**Blockers** (if relevant):
Have a temporary work around

**Definition of Done**:
Have an inbuilt way of doing this within Rasa

**Comment by sara-tagger** [comment]
Thanks for submitting this feature request 🚀 @degiz will get back to you about it soon! ✨

**Comment by nbeuchat** [comment]
Couldn't you use a boolean slot for it? 

```
story 1
*intent_1
- action_step1
*intent_2
- action_step2
- slot{"my_slot": false}
*intent_3
- action_step3
```

```
story 2
*intent_1
- action_step1
*intent_2
- action_step2
- slot{"my_slot": true}
- action_step3
```

**Comment by degiz** [comment]
Hey @sibbsnb 

I'd second @nbeuchat solution here 🤔

**Comment by sibbsnb** [comment]
This is one of the examples where I want to jump to another story. Within same story you may be able to work around with slot, what if I want to jump to a completely different stories. 

I think Rasa needs a way to jump from one story to another in an easy way.

**Comment by nbeuchat** [comment]
You have a few other ways:
- Use a follow up actions within an action
- Use the new Rules policy in 2.0 to code your business logic in the rules (might actually work well with the above) 
- (never tried) Use a reminder with the intent you need with an immediate execution time (not sure if you can set the execution time right away)

**Comment by robotmentor88** [comment]
@nbeuchat can you give an example of follow up actions?

**Comment by wochinge** [comment]
Thanks @nbeuchat for helping out here 🙌🏻
