### ISSUE TITLE
Slot Validation is not working as expected

### ISSUE THREAD

**Issue by shreeraj04** [RasaHQ/rasa#7108]
Rasa version: 2.0.0

Python version:3.7.2

Operating system : Windows

Issue: Forms and slot validation is not happening, checked from the **RASA examples formbot** application as well 

![image](https://user-images.githubusercontent.com/15680777/97260122-50f3df80-1842-11eb-9c9a-feed30f57855.png)

As per the actions and validations cuisine doesn't has japanese, but the bot took the response, also the num of people given is -1 which took as a valid answer. 

![image](https://user-images.githubusercontent.com/15680777/97260231-88628c00-1842-11eb-8597-c40f93aa0140.png)

![image](https://user-images.githubusercontent.com/15680777/97260242-8ef10380-1842-11eb-877b-1d4024263491.png)

![image](https://user-images.githubusercontent.com/15680777/97260253-944e4e00-1842-11eb-9aa7-cfbb4ef80210.png)

![image](https://user-images.githubusercontent.com/15680777/97260271-9ca68900-1842-11eb-8dd3-f54dacab1720.png)

Above are the snapshots of the slots and the validation code from the rasa examples form bot. Please help in this.

**Comment by sara-tagger** [comment]
Thanks for raising this issue, @TyDunn will get back to you about it soon✨

###### Please also check out the [docs](https://rasa.com/docs/) and the [forum](https://forum.rasa.com/) in case your issue was raised there too 🤗

**Comment by melindaloubser1** [comment]
Looks like formbot was not updated to use `FormValidationAction` yet. I've opened a PR to update it here https://github.com/RasaHQ/rasa/pull/7112

**Comment by shreeraj04** [comment]
Yes, @melindaloubser1 formbot was not using FormValidationAction, also validate_formname was missing. I got to know from the latest documentation. Thanks for your response.
