### ISSUE TITLE
about load a new model when working on multi-processes

### ISSUE THREAD

**Issue by Sun-Qiming** [RasaHQ/rasa#7111]
**Rasa version**: 2.0.0

**Rasa SDK version** (if used & relevant): 2.0.0

**Rasa X version** (if used & relevant):

**Python version**: 3.7.4

**Operating system** (windows, osx, ...): ubuntu 16.04

**Issue**: I start a rasa server on multi-processes mode ( with number_of_workers = 3 of sanic ) , after that i call the interface /model to load a new model. I can see the code in rasa.server.py (line:1005) and it change the app.agent :

 app.agent = await _load_agent(
 model_path, model_server, remote_storage, endpoints, app.agent.lock_store
 )

In my opinion , it just change the model in the process which handle the request, but other process still work with the old model. (I verified that by a piece of test code to change a variable with sanic server, and have not test with a rasa model, but i think they are same.) Am i right ? If i'm right , how can i load a new model on that situation? Thank you . **Error (including full traceback)**:

**Command or request that led to error**:

**Content of configuration file (config.yml)** (if relevant):

**Content of domain file (domain.yml)** (if relevant):

**Comment by sara-tagger** [comment]
Thanks for raising this issue, @TyDunn will get back to you about it soon✨

###### Please also check out the [docs](https://rasa.com/docs/) and the [forum](https://forum.rasa.com/) in case your issue was raised there too 🤗

**Comment by ArjaanBuijk** [comment]
@Sun-Qiming ,

can you please provide the **exact steps** you took:
- to create your python environment (conda or something else, what python version, etc.)
- to install rasa
- the command you used to start the rasa server

**Comment by Sun-Qiming** [comment]
@ArjaanBuijk 
I didn't verify that in rasa (personal reason...) , but in my sample code with sanic. In rasa in think i will do it follow the steps below:
1 create my python environment by conda, and install rasa 2.0.0 with python=3.7.4
2 set environment variable 'SANIC_WORKERS' = 3 (>1) , let rasa server app (sanic) working with multi-processes
3 start rasa server with model1: rasa run  --enable-api  -m models/model1.tar.gz
4 change model to mode2 by call the interface :  /model  (https://rasa.com/docs/rasa/pages/http-api#operation/replaceModel) use model_file  
I just suspect that in step 4 it will only change the model to model2 in the process which handle the request, but the other sanic processes still work with model1 because of the code i list upon.
