### ISSUE TITLE
Make sure the e2e stories are printed correctly

### ISSUE THREAD

**Issue by Ghostvv** [RasaHQ/rasa#7130]
with e2e we brought one more complexity to stories. We need to make sure that e2e stories are printed correctly for tracker from real conversations. By correctly, I mean that `UserUttered` featurization flag and `ActionExecuted` `action_name` or `action_text` should be taken into account when printing stories

**Comment by wochinge** [comment]
seems @tabergma fixed large parts of the printing already. However, I didn't find any tests and a couple of edge cases weren't covered. There are also weird things regarding end-to-end **test** stories in the YAML writer which confuse me. My current assumption is that the implementation for end-to-end tests on master is buggy / broken.
