### ISSUE TITLE
Show retrieval intents & response keys in Interactive Learning

### ISSUE THREAD

**Issue by samsucik** [RasaHQ/rasa#7133]
**Description of Problem**: Currently, Interactive Learning doesn't communicate it properly to the user that `ResponseSelector`s are being used under the hood. See below, where only the base intent `chitchat` is shown and for the `utter_chitchat` utterance the response key isn't shown either: [<span class="image-wrap" style="">![](https://user-images.githubusercontent.com/7470182/97552257-f1294000-19cb-11eb-8168-feb255210032.png)</span>](https://user-images.githubusercontent.com/7470182/97552257-f1294000-19cb-11eb-8168-feb255210032.png) This is a blocker especially when using IL with the `--e2e` option, trying to generate test stories. But also more generally when checking how `ResponseSelector`s are doing their job. It has also confused a user, see [this forum post](https://forum.rasa.com/t/request-for-retrieval-based-configuration-or-github-demo-for-faq-and-chitchat-in-rasa-2-0/36236/3?u=sams).

**Overview of the Solution**: It would be good to have the full retrieval intent and response keys in the conversation history.

We should also address the confusion caused by IL's messages that do not contain the full intent or response key. E.g. `Your NLU model classified 'how are you?' with intent 'chitchat' and there are no entities, is this correct?` is confusing because the user thinks that Rasa didn't recognise the **retrieval intent** – the user doesn't know that Rasa first recognises the base intent (`chitchat` – that's what IL is asking about) and then (silently, without messages in IL) the full intent gets classified by a `ResponseSelector`. Same for the response: the user has to understand that IL is asking them to confirm `utter_chitchat` and **then** a `ResponseSelector` chooses the right response.

Perhaps we ourselves should be clear on what the role of IL is. Because if it's a tool to create test stories (which should include retrieval intents and response keys), then the question is why the user shouldn't be able to correct also the decisions of `ResponseSelector`s in IL.

**Comment by TyDunn** [comment]
We should also discuss if we should update interactive learning in Rasa X too

**Comment by dakshvar22** [comment]
Related to IL and retrieval intents, the exported story should not contain the response key along with the retrieval intent. This [forum post](https://forum.rasa.com/t/interactive-learning-new-story-containing-retrieval-intents/38740) shows that it does so right now.

**Comment by samsucik** [comment]
@dakshvar22 shouldn't it be that training stories don't contain response keys but test stories can (and should, if you wanna test response selectors)?

**Comment by alwx** [comment]
@dakshvar22 could you come back to this one?

**Comment by dakshvar22** [comment]
@samsucik That's correct. I think in that case we should refactor our training pipeline to clean up response keys if they are present in any story, but then preserve them during test. What do you think?
However, I am not sure if folks add stories to test data using interactive learning. My impression is that they would generally add it to training data.

**Comment by samsucik** [comment]
@dakshvar22 I agree that some refactoring may be needed, though I thought this was more about IL code...

> clean up response keys if they are present in any story

What exactly do you mean here? Simply ignoring response keys in stories when loading them for training? Somehow cleaning the story files and deleting response keys from them? Something else? 🙂 

IL for test stories: I don't have hard data. I understand your intuition and it's in line with how IL was originally meant, but I also see no reason why folks wouldn't use IL for generating test stories (and we're not discouraging it anywhere I think). There's now even the `--e2e` option which sounds like exactly for this purpose. Another thing is that developers sometimes use the same stories for training and testing -- if you're in an early stage, debugging your bot and you just need _some_ stories to test on.

To my, this issue is really more about IL because `rasa test` can already utilise stories with response keys in them (and `rasa train` should be able to ignore response keys in stories, though I have no idea whether this is really so 🤔 ). It is IL that lags behind in terms of good support for response selectors in general...
