### ISSUE TITLE
Rasa-X does not pull latest changes from git repo if an error occurred in injecting data earlier

### ISSUE THREAD

**Issue by saylee-m** [RasaHQ/rasa#7165]
**Rasa version**: 1.10.0

**Rasa SDK version** (if used & relevant):

**Rasa X version** (if used & relevant): 0.32.2

**Python version**:

**Operating system** (windows, osx, ...): Linux

**Issue**: I have connected Rasa X to a git repository. I know that if recent pushes in the git are not reflected in rasa X implies that there has been some issue in the data injection part. I did 'kubectl get logs' for the rasa-x pod to find that there was an issue with one of the story data formats. I corrected the format and pushed the changes to the git repo, however, Rasa X still gives the same error and does not pull the latest changes from the git.

Whenever this thing happens, I have to disconnect rasa X from the git repo, and connect it again to make it pull the latest changes.

**Comment by sara-tagger** [comment]
Thanks for raising this issue, @ArjaanBuijk will get back to you about it soon✨

###### Please also check out the [docs](https://rasa.com/docs/) and the [forum](https://forum.rasa.com/) in case your issue was raised there too 🤗

**Comment by benjenis** [comment]
Has this issue been resolved? Which pod should I check to view the errors/logs when Rasa X doesn't push to the git repo?

**Comment by otmarjr** [comment]
Hello @benjenis 

Well, at least from my recent experience, this issue seems to still be open - I've talked about it in the Rasa forum.

So far, I could detect the error only by inspecting the logs with: docker logs --tail 50 --follow --timestamps rasa_rasa-x_1

**Comment by alexweidauer** [comment]
Thank you for raising this issue about Rasa X. We decided to stop supporting the Community Edition (free version) of ‘Rasa X’ (see more info here: https://rasa.com/blog/rasa-x-community-edition-changes/). That’s why we’ve closed your issue. We suggest that Rasa Enterprise customers raise the issue with our customer support team if they haven’t done so already.
