### ISSUE TITLE
Use separate token content agnostic attention layer for role/groups

### ISSUE THREAD

**Issue by Ghostvv** [RasaHQ/rasa#7173]
currently the following 2 sentences are different from the point of view of roles/groups classifier

*   I need a flight from <span class="error">[Pittsburgh]</span> {"entity": "city", "role": "from"} 

     to <span class="error">[Detroit]</span>

     {"entity": "city", "role": "to"} 

     on <span class="error">[May 24]</span>(date).

*   I need a flight from <span class="error">[Chicago]</span> {"entity": "city", "role": "from"} 

     to <span class="error">[Pittsburgh]</span>

     {"entity": "city", "role": "to"} 

     on <span class="error">[May 14]</span>(date)

Which often leads to classifier to overfit to particular city to be either `from` or `to` because nlu data doesn't contain all possible combinations of cities and various roles.

In `roles-attn`, I decoupled roles/groups classifier from main entity/intent transformer and substitute token inputs on dense numerical level that have entity tags with dense vector of their entity tag. These creates such an input to roles/groups classifier that the sentences above are exactly identical.

In order to verify whether it makes sense to merge into master we need to perform experiments to compare mistakes

**Comment by JEM-Mosig** [comment]
To test this, I'm manually building a dataset with entity roles and groups, as it appears that there is none publicly available.
