### ISSUE TITLE
Two-stage fallback resets all slots on successful rephrase

### ISSUE THREAD

**Issue by Devocado** [RasaHQ/rasa#7176]
**Rasa version**: 2.0.x

**Python version**: 3.8.2

**Operating system** : Ubuntu 20.04

**Issue**: Two-stage fallback resets all slots on successful rephrase

**Error (including full traceback)**:
All slots are reset when successfully rephrasing a message after triggering a two-stage fallback

The full debug output can be found [here](https://github.com/Devocado/rasa-two-stage-fallback-test/blob/master/debuglog.txt)

**Command or request that led to error**:
This bug can be reproduced with this [example assistant](https://github.com/Devocado/rasa-two-stage-fallback-test)

Steps to reproduce:

- Start the assistant
- Enter 'Hi' or 'hello' to start a conversation
- Provide the information requested, a name, a number for age, and a colour
- When the assistant asks 'what can I do for you?' enter
```
/nlu_fallback
```
to trigger an nlu fallback (just for the sake of simplicity; with so few intents it is tricky to trigger it with an ordinary message)

- The assistant will ask "did you mean 'nlu_fallback'?". Select 'No'
- The assistant will ask you to rephrase your message. This time enter something along the lines of "tell me a joke" to trigger the tell_joke intent

The assistant will answer, using the name slot. However the slot will be empty, and will output 'None' where the name should be.

Running in debug mode will reveal that all of the slots are empty at this point

**Comment by sara-tagger** [comment]
Thanks for the issue, @tabergma will get back to you about it soon!

###### You may find help in the [docs](https://rasa.com/docs/) and the [forum,](https://forum.rasa.com/) too 🤗

**Comment by Ghostvv** [comment]
thank you for detailed report and for creating a repo for small example 🚀
We'll take a look at what is going on

**Comment by Ghostvv** [comment]
there is a bug. 
`action_two_stage_fallback` reverts 2 `UserUttered`, however the last `tell me a joke` is part of the form, so instead of reverting `tell me a joke` and `nlu_fallback`, it reverts `nlu_fallback` and `hi` (the only 2 “real” user uttered in applied events). Since `action_two_stage_fallback` is a loop, it always should revert 1 user uttered (the one that triggered it)
