### ISSUE TITLE
Sync file changes with Rasa X dashbaord

### ISSUE THREAD

**Issue by fandy** [RasaHQ/rasa#7177]
**Description of Problem**:
We're forced to use _either_ our preferred code editor or the Rasa X interface to edit training data.

**Overview of the Solution**:
Sync any file changes (e.g. to rules.yml, config.yml) to Rasa X, without requiring a server restart each time.

**Comment by sara-tagger** [comment]
Thanks for submitting this feature request 🚀 @samsucik will get back to you about it soon! ✨

**Comment by TyDunn** [comment]
Hi @fandy. Can you explain why you are forced to use either our preferred code editor or the Rasa X interface to edit training data? You should be able to follow branch-based development with [Integrated Version Control](https://rasa.com/docs/rasa-x/installation-and-setup/deploy#integrated-version-control) syncing the files between Rasa X and your remote Git repo (i.e. edit part of the assistant on a Git branch in your preferred code editor and edit another part of your assistant on a different Git branch in Rasa X)
