### ISSUE TITLE
Use consistent indenting in Rasa X

### ISSUE THREAD

**Issue by fandy** [RasaHQ/rasa#7178]
**Description of Problem**:
The Rasa X code editor requires you to spam spaces instead of using tabs because it's not smart enough to have consistent indenting. That'll give you an error when saving (good), but it's not easy to tell at first glance it's your indenting (bad). This makes it easy to prefer your local editor, which is inconvenient because changes aren't synced (https://github.com/RasaHQ/rasa/issues/7177), so you must restart the server each time.

**Overview of the Solution**:
Detect and use consistent indenting.

**Comment by sara-tagger** [comment]
Thanks for submitting this feature request 🚀 @dakshvar22 will get back to you about it soon! ✨

**Comment by chdorner** [comment]
Similar to #7416, closing this.
