### ISSUE TITLE
CI builds are cancelled "randomly"

### ISSUE THREAD

**Issue by m-vdb** [RasaHQ/rasa#7180]
It comes from the fact that we're using the action `rokroskar/workflow-run-cleanup-action` (both in `rasa` and `rasa-x`). I saw it happened last on [this PR's checks](https://github.com/RasaHQ/rasa/pull/7179/checks?check_run_id=1352247080).

> Looking at the way we automatically cancel older builds for Rasa X branches, I think I found out why sometimes builds are cancelled without no apparent reason. [The action we use](https://github.com/rokroskar/workflow-run-cleanup-action/blob/master/entrypoint.sh) does not filter out on the commit sha, which exposes us to race conditions. I’ve found [another action](https://github.com/styfle/cancel-workflow-action) that does it more cautiously. And we also have this workflow (who uses another action) that cancels builds every 15min, so that could explain what we sometimes experience.
[Original Slack message](https://rasa-hq.slack.com/archives/C36SS4N8M/p1603982459210700).

**Proposed solution**
Use another action like [styfle/cancel-workflow-action](https://github.com/styfle/cancel-workflow-action)

cc @tmbo @tczekajlo @mprazz

**Comment by tmbo** [comment]
👍
