### ISSUE TITLE
RASA 2.0 HTTP API unclear documentation

### ISSUE THREAD

**Issue by solyarisoftware** [RasaHQ/rasa#7189]
Hi all

*   I'd like to interface the RASA platform via HTTP APIs, but I found a lot of unclear points.
*   As a nodejs developer I want to integrate RASA inside a no python environment, so I would need a clear API interface.

Here the HTTP API documentation web pages available at rasa.com:

*   [https://rasa.com/docs/rasa/http-api](https://rasa.com/docs/rasa/http-api)
*   [https://rasa.com/docs/rasa/pages/http-api](https://rasa.com/docs/rasa/pages/http-api)
*   [https://rasa.com/docs/rasa/pages/action-server-api](https://rasa.com/docs/rasa/pages/action-server-api)

But all that documentation is not very clear.

See also my old posts/comments for more details:

*   [https://github.com/RasaHQ/rasa/issues/5763](https://github.com/RasaHQ/rasa/issues/5763)
*   [How can I get a conversation_id so I run an Action via POST from an App](https://forum.rasa.com/t/how-can-i-get-a-conversation-id-so-i-run-an-action-via-post-from-an-app/19987/9?u=solyarisoftware)
*   [https://github.com/RasaHQ/rasa/issues/5768#event-3777903015](https://github.com/RasaHQ/rasa/issues/5768#event-3777903015)
*   [https://github.com/RasaHQ/rasa/issues/5749#issuecomment-667974484](https://github.com/RasaHQ/rasa/issues/5749#issuecomment-667974484)
*   [https://github.com/RasaHQ/rasa/issues/4683#issuecomment-667657208](https://github.com/RasaHQ/rasa/issues/4683#issuecomment-667657208)

Maybe now the action server endpoint data are better documented, but what is missing is maybe:

*   a general introduction on "how to" use RASA HTTP API
*   for the RASA NLU part
*   for the full RASA core integration
*   including the action server backend integration.

As proposed in the github issue 5763 above linked, maybe a full documentation rework need, with a special eye on not-python ecosystem of developer. BTW, my side I'm available to contribute maybe to test the nodejs interface, etc.

Thanks giorgio

**Comment by sara-tagger** [comment]
Thanks for submitting this feature request 🚀 @melindaloubser1 will get back to you about it soon! ✨

**Comment by melindaloubser1** [comment]
Hey @solyarisoftware , based on this and your comments on other issues, it sounds like you have a lot of specific things in mind that could make the docs on the API's clearer. Since a docs rework is quite broad and hard to define (what would qualify as "done"? e.g. there was a rework for Rasa 2.0, but this didn't address all the enhancements you're suggesting), can I ask that you rather open issues for specific improvements you'd like to see made? That makes it easier for contributors to pick up, leading to improvements being made faster.
E.g. you could open an issue for creating a "how to use the HTTP API page" with suggestions for the points it should cover.

**Comment by solyarisoftware** [comment]
Hi Melinda, 
yes, honestly it's a vast topic, and yes I proposed some minor improvements here and there. 

In my opinion what is really missing is the "big picture" overall architecture and API entrypoints. Thinked for non pythoners (who want to integrate RASA "backend" engine inside a bigger system made in Nodejs, Java or .NET (arghh) application.

1. I propose to share the architecture in MACRO components/boxes 
- Reply to common questions: 
  - How can I interface RASA 2 API just as intent classifier (ex "NLU")
  -  How can I interface RASA 2 API as end-to-end backend chatbox using the full path (stories)
  - How can I made action server integration (webhook API detailed description)

2. Please specify API interface with flat curl examples (where possible) / I'd avoid obscure graphical web pages with hidden sections...).
 
Let me know if I can help with more details.
BTW, 
- I opened this post also in the RASA forum without any answer.
- I'd prefer to maintain open this detailed issue instead of open yet another issue, just to avoid the issue number rise :-)

Thanks
giorgio

**Comment by akelad** [comment]
about your request for a diagram: are you thinking something along the lines of this?

**Comment by solyarisoftware** [comment]
Hi Akela,

the updated doc https://rasa.com/docs/rasa/arch-overview is a good start. 
From the **HTTP API interface** point of view, that split makes sense to me (quoting from the above page): 
> The two primary components are Natural Language Understanding (NLU) and dialogue management.


So, focusing by example on the run-time phase, I'd propose something super clear with the help of some box-diagrams like:

```
                                  |                     |
                                  |    +-----------+    |
                                  |    |           |    |
                                  |    |           |    |
         +---------+              |    |           |    |
         |         |              |    |           |    |
         | channel | (1)          |    |           |    |
         |         +------  HTTP API--->           |    |
         |         <------  json--+----+           |    |
user ---->         |              |    |           |    |
         |         |              |    |           |    |
         |         |              |    |   RASA    |    |
user ---->         |              |    |   server  |    |                            +------------+
         |         |              |    |           |    |                            |            |
         |         |              |    |           |    |          +----------+      |            |
user ---->         |              |    |           | (3)           |          |      |            |
         |         | (2)          |    |           | HTTP webhook  |          |      |            |
         |         +-------  HTTP API-->           +--------------->  Action  +------>  Backend   |
         |         <-------  json-+----+           <-json----------+  Server  <------+  Platform  |
         |         |              |    |           |    |          |          |      |            |
         |         |              |    |           |    |          |          |      |            |
         +---------+              |    |           |    |          +----------+      |            |
                                  |    |           |    |                            |            |
                                  |    +-----------+    |                            |            |
                                  |                     |                            +------------+
                                  |                     |
                                  |                     |

```

where I'd emphasis 3 componente pointed out in the diagram:

(1) Intents classification API ("NLU")

  ```bash
  curl localhost:5005/model/parse -d '{"text":"hello"}'
  ```

(2) Conversations API (Dialog management) 

  ```bash
  curl -s localhost:5005/webhooks/rest/webhook -d '{ "sender": "Giorgio", "message": "hi" }'
  ```

(3) Custom Action Server webhook API
With detailed examples for special cases a Forms.

---

See also https://github.com/RasaHQ/rasa/issues/5749#issuecomment-667974484

thanks
giorgio

**Comment by XiaoLiuAI** [comment]
@solyarisoftware Hello, I am also looking for a better explanation for http api. I would like to use customized nlu and rasa core, but I haven't found a way to create session using rasa core endpoints directly. And all the tracker api need session ids. Do you have any idea?

**Comment by solyarisoftware** [comment]
Hi @XiaoLiuAI 

Yes, the `session id` doesn't related RASA engines. It's just a unique identifier of the conversation with a user. It's the `user id`.   It's maybe related to your application logic or frontend hub of your choice. By example, in for a Telegram bot, you can use the telegram `chat_id`. 

- see my old comment: 
   https://forum.rasa.com/t/how-can-i-get-a-conversation-id-so-i-run-an-action-via-post-from-an-app/19987/9?u=solyarisoftware
- and issue closed: https://github.com/RasaHQ/rasa/issues/4683

I hope this helps.

> BTW, If you agree that HTTP API clarification deserve more attention, please put a thumb up on my original post here.
