### ISSUE TITLE
RASA X 0.33 error on Windows 10 EOFError: Ran out of input

### ISSUE THREAD

**Issue by amardeep2006** [RasaHQ/rasa#7191]
**Rasa version**:
2.0.2
**Rasa SDK version** (if used & relevant):
na
**Rasa X version** (if used & relevant):
0.33
**Python version**:
3.6.8
**Operating system** (windows, osx, ...):
Windows 10 - 1809
**Issue**:
Rasa x is not able to load model trained by rasa. This is a fresh project created by rasa init and rasa train.

**What I have already tried and did not work :**  
Created one virtual environment . Installed only RASA in it. Used the same for training model.
Created separate virtual environment for RASA X. Used this virtual environment to launch rasa x.

**Error (including full traceback)**:
```
error logs: Starting Rasa X in local mode… ?? Traceback (most recent call last): File “c:\comp\myc-rpa-conversation-rasa2assisstant-api\venvx\lib\site-packages\rasa\cli\x.py”, line 454, in run_locally args, project_path, args.data, token=rasa_x_token, config_path=config_path File “c:\comp\myc-rpa-conversation-rasa2assisstant-api\venvx\lib\site-packages\rasax\community\local.py”, line 233, in main _start_event_service() File “c:\comp\myc-rpa-conversation-rasa2assisstant-api\venvx\lib\site-packages\rasax\community\local.py”, line 139, in _start_event_service fn=_event_service, args=(LOCAL_ENDPOINTS_PATH,), daemon=True File “c:\comp\myc-rpa-conversation-rasa2assisstant-api\venvx\lib\site-packages\rasax\community\utils\common.py”, line 855, in run_in_process p.start() File “C:\comp\Python\Python36\lib\multiprocessing\process.py”, line 105, in start self._popen = self._Popen(self) File “C:\comp\Python\Python36\lib\multiprocessing\context.py”, line 322, in _Popen return Popen(process_obj) File “C:\comp\Python\Python36\lib\multiprocessing\popen_spawn_win32.py”, line 65, in init reduction.dump(process_obj, to_child) File “C:\comp\Python\Python36\lib\multiprocessing\reduction.py”, line 60, in dump ForkingPickler(file, protocol).dump(obj) File “C:\comp\Python\Python36\lib\multiprocessing\connection.py”, line 939, in reduce_pipe_connection dh = reduction.DupHandle(conn.fileno(), access) File “C:\comp\Python\Python36\lib\multiprocessing\connection.py”, line 170, in fileno self._check_closed() File “C:\comp\Python\Python36\lib\multiprocessing\connection.py”, line 136, in _check_closed raise OSError(“handle is closed”) OSError: handle is closed

Sorry, something went wrong (see error above). Make sure to start Rasa X with valid data and valid domain and config files. Please, also check any warnings that popped up. If you need help fixing the issue visit our forum: https://forum.rasa.com/. Traceback (most recent call last): File “”, line 1, in File “C:\comp\Python\Python36\lib\multiprocessing\spawn.py”, line 105, in spawn_main exitcode = _main(fd) File “C:\comp\Python\Python36\lib\multiprocessing\spawn.py”, line 115, in _main self = reduction.pickle.load(from_parent) EOFError: Ran out of input
```

**Command or request that led to error**:
```
rasa x
```

**Content of configuration file (config.yml)** (if relevant):
```yml

```

**Content of domain file (domain.yml)** (if relevant):
```yml

```

**Comment by sara-tagger** [comment]
Thanks for raising this issue, @ArjaanBuijk will get back to you about it soon✨

###### Please also check out the [docs](https://rasa.com/docs/) and the [forum](https://forum.rasa.com/) in case your issue was raised there too 🤗

**Comment by kearnsw** [comment]
I've been able to reproduce this issue in both Python 3.8 (latest) and Python 3.7 (latest) on Mac OS 10.15.6.

**Comment by amardeep2006** [comment]
Tested today with new release. The issue is still present with RASA X 0.34.0 and RASA 2.1.2 combination.

**Comment by koaning** [comment]
I am also seeing this with these versions; 

```
> rasa --version
Rasa Version     : 2.2.2
Rasa SDK Version : 2.2.0
Rasa X Version   : 0.34.0
Python Version   : 3.7.7
Operating System : Darwin-19.3.0-x86_64-i386-64bit
Python Path      : /Users/vincent/Development/breakoutbot/venv/bin/python3.7
```

**Comment by desmarchris** [comment]
@amardeep2006 this is a bug with the way we disable our telemetry. If you run `rasa telemetry enable` before running rasa x, it should work. Disabling telemetry using `rasa telemetry disable` appears to cause this error

**Comment by m-vdb** [comment]
It will be likely done as part of [this ticket](https://github.com/RasaHQ/rasa-x/issues/3724)

**Comment by amardeep2006** [comment]
> @amardeep2006 this is a bug with the way we disable our telemetry. If you run `rasa telemetry enable` before running rasa x, it should work. Disabling telemetry using `rasa telemetry disable` appears to cause this error

I have tested after enabling telemetry and rasa X started after that without any issues

**Comment by mjaycub** [comment]
Closing as will be fixed within ticket we are tracking in Rasa X repo - https://github.com/RasaHQ/rasa-x/issues/3724
