### ISSUE TITLE
Shell error "Failed to fill utterance template, There is no slot with this name nor did you pass the value explicitly when calling the template. Return template without filling the template" 

### ISSUE THREAD

**Issue by tatianafrank** [RasaHQ/rasa#7194]
**Rasa version**: 2.0 **Rasa SDK version** (if used & relevant):

**Rasa X version** (if used & relevant):

**Python version**: 3.7 **Operating system** (windows, osx, ...): osx **Issue**: Im seeing errors in Rasa Shell claiming about a response template I have containing buttons. The template looks like this:

 utter_ask_device_type:

*   text: Devices
     buttons:
*   title: Mac
     payload: /inform {"device_type":"mac"}
*   title: PC
     payload: /inform {"device_type":"pc"}
*   title: Linux
     payload: /inform {"device_type":"linux"}
*   title: iOS
     payload: /inform {"device_type":"ios"}
*   title: Android
     payload: /inform {"device_type":"android"}

And my slot looks like this

 slots:
 device_type:
 type: text
 influence_conversation: false

**Error (including full traceback)**:

 2020-11-05 14:04:33 ERROR rasa.core.nlg.interpolator - Failed to fill utterance template '/inform

 {"device_type":"pc"} 

'. Tried to replace '"device_type":"pc"' but could not find a value for it. There is no slot with this name nor did you pass the value explicitly when calling the template. Return template without filling the template. 
 Traceback (most recent call last):
 File "/Users/nbm/Library/Caches/pypoetry/virtualenvs/w3-digital-assistant-rasa-core-V6FNUaHk-py3.7/lib/python3.7/site-packages/rasa/core/nlg/interpolator.py", line 28, in interpolate_text
 text = text.format(values)
 KeyError: '"device_type":"pc"'
 2020-11-05 14:04:33 ERROR rasa.core.nlg.interpolator - Failed to fill utterance template '/inform

 {"device_type":"linux"} 

'. Tried to replace '"device_type":"linux"' but could not find a value for it. There is no slot with this name nor did you pass the value explicitly when calling the template. Return template without filling the template. 
 Traceback (most recent call last):
 File "/Users/nbm/Library/Caches/pypoetry/virtualenvs/w3-digital-assistant-rasa-core-V6FNUaHk-py3.7/lib/python3.7/site-packages/rasa/core/nlg/interpolator.py", line 28, in interpolate_text
 text = text.format(values)
 KeyError: '"device_type":"linux"'
 2020-11-05 14:04:33 ERROR rasa.core.nlg.interpolator - Failed to fill utterance template '/inform

 {"device_type":"ios"} 

'. Tried to replace '"device_type":"ios"' but could not find a value for it. There is no slot with this name nor did you pass the value explicitly when calling the template. Return template without filling the template. 
 Traceback (most recent call last):
 File "/Users/nbm/Library/Caches/pypoetry/virtualenvs/w3-digital-assistant-rasa-core-V6FNUaHk-py3.7/lib/python3.7/site-packages/rasa/core/nlg/interpolator.py", line 28, in interpolate_text
 text = text.format(values)
 KeyError: '"device_type":"ios"'
 2020-11-05 14:04:33 ERROR rasa.core.nlg.interpolator - Failed to fill utterance template '/inform

 {"device_type":"android"} 

'. Tried to replace '"device_type":"android"' but could not find a value for it. There is no slot with this name nor did you pass the value explicitly when calling the template. Return template without filling the template.

**Command or request that led to error**:

 rasa shell

**Content of configuration file (config.yml)** (if relevant):

**Content of domain file (domain.yml)** (if relevant):

**Comment by sara-tagger** [comment]
Thanks for the issue, @dakshvar22 will get back to you about it soon!

###### You may find help in the [docs](https://rasa.com/docs/) and the [forum,](https://forum.rasa.com/) too 🤗

**Comment by samsucik** [comment]
Hi @tatianafrank, thanks for reporting this! Looks to be the same as [this one](https://github.com/RasaHQ/helpdesk-assistant/issues/38) and I think @erohmensing will look into fixing it :-)

**Comment by rgstephens** [comment]
You can workaround this issue with double curly braces:

```
      payload: /inform{{"device_type":"mac"}}
```

**Comment by tatianafrank** [comment]
@rgstephens thanks for your response! Is this the permanent solution or are you guys working on a fix to the rasa code? Just wondering if we should hold off on using this workaround if a proper fix is coming in the next release.

**Comment by rgstephens** [comment]
The PR you see above your post shows the code change to fix this.

**Comment by tatianafrank** [comment]
Thanks
