### ISSUE TITLE
jaeger tracing / open telemetry

### ISSUE THREAD

**Issue by listaction** [RasaHQ/rasa#7196]
hi Rasa team, Do you have plans to either expose the "app" created as part of the Sanic Server creation process / provide some options to supply an open tracing configuration like the following ?

Its important for observing rasa in production environments. If there is a way to instrument it - please share, if not please consider adding it as its fairly low effort.

Example

 from sanic import Sanic
 from sanic import response as res
 from jaeger_client import Config
 from sanic_opentracing import SanicTracing

 app = Sanic(__name__)

 @app.route("/")
 async def test(req):
 return res.text("I\'m a teapot", status=418)

 def initialize_tracer():
 config = Config(
 config={ # usually read from some yaml config
 'sampler': 

 { 'type': 'const', 'param': 1, } 

,
 'logging': True,
 },
 service_name='your-app-name',
 validate=True,
 )
 return config.initialize_tracer()
 tracing = SanicTracing(tracer=initialize_tracer, trace_all_requests=True, app=app)

 if __name__ == '__main__':
 app.run(host="0.0.0.0", port=8000)

**Defintion of done**

*   [ ] Review 2.8 prototype
*   [ ] Consider if [https://github.com/RasaHQ/rasa/issues/6319](https://github.com/RasaHQ/rasa/issues/6319) should be in scope
*   [ ] Draft implementation proposal
*   [ ] Get feedback from CSE
*   [ ] Get feedback from infrastructure
*   [ ] Determine scope for v1
*   [ ] Create issues for implementation

**Comment by sara-tagger** [comment]
Thanks for submitting this feature request 🚀 @b-quachtran will get back to you about it soon! ✨

**Comment by akelad** [comment]
@rgstephens

**Comment by rgstephens** [comment]
Yes, there's currently work on this which you can find in the Rasa [open-telemetry](https://github.com/RasaHQ/rasa/tree/open-telemetry) branch and there's also an example action server in the Sara/Rasa Demo bot also in an [open-telemetry](https://github.com/RasaHQ/rasa-demo/tree/open-telemetry) branch.

I hope to post more about this work in the coming weeks. In the mean time, there's also a Rasa 2.0.2 docker image [stephens/rasa-otel](https://hub.docker.com/r/stephens/rasa-otel). It currently uses OpenTracing/Jaeger but I will be switching this to OpenTelemetry soon.

Here's an example Jaeger screenshot of a trace including action server call:

<img width="965" alt="exampleJaegerTrace" src="https://user-images.githubusercontent.com/846052/98398288-9324da00-2015-11eb-84ac-ca0a4794ce84.png">

**Comment by listaction** [comment]
could you describe how to run the container ? `docker run  stephens/rasa-otel:latest` throws a bunch of permission errors.

**Comment by rgstephens** [comment]
You should be using it as part of either the standard [docker-compose](https://rasa.com/docs/rasa-x/installation-and-setup/install/docker-compose) setup either of the Kubernetes based installs - [quick start](https://rasa.com/docs/rasa-x/installation-and-setup/install/quick-install-script) which uses k3s or [helm](https://rasa.com/docs/rasa-x/installation-and-setup/install/helm-chart).

You can also do a local python setup by pulling the rasa git [repo](https://github.com/RasaHQ/rasa), switch to the `open-telemetry` branch and run locally.

**Comment by wochinge** [comment]
cc @TyDunn

**Comment by JustinDroege** [comment]
Hello. How is the status and if is already implemented, is there any documentation?

**Comment by rgstephens** [comment]
I think we should be looking at a hooks mechanism for this feature similar to the discussion on the [message queue encrypt/decrypt](https://github.com/RasaHQ/rasa-x/issues/4511).

**Comment by rgstephens** [comment]
Would be good to add accepting of injected context from front end

**Comment by rgstephens** [comment]
I built an updated [image](https://hub.docker.com/r/stephens/rasa-otel) of `2.8.1` with OpenTracing/Jaeger and also sanic-prometheus. If anyone used the older image, the `endpoints.yml` values have changed. See the image readme for details and a description of how to enable the `/metrics` endpoint in your `endpoints.yml`.

**Comment by z-bodikova** [comment]
Hey @TyDunn and @joejuzl - just FYI: this work is something that one of our customers is really keen on. I'll drop more information in the Slack channel.

**Comment by hsm207** [comment]
Another customer is also keen on this

**Comment by zfallahnejad** [comment]
Any update on this issue?

**Comment by fagurto** [comment]
Hi rasa team , just wondering , is this still a working progress ??

**Comment by m-vdb** [comment]
Closing as this is now part of Rasa Pro.

**Comment by gb-kriss** [comment]
Hi All, we are using RASA opensource on k8s, any info or point of direction how can it be instrumented to k8s
https://hub.docker.com/r/stephens/rasa-otel
