### ISSUE TITLE
Auto update in the existing template after train 

### ISSUE THREAD

**Issue by Dinesh-gowdam-2610** [RasaHQ/rasa#7201]
**Rasa version**: 1.10.12

**Rasa SDK version** (if used & relevant):1.10.2

**Rasa X version** (if used & relevant):

**Python version**: 3.7.6

**Operating system** (windows, osx, ...): windows 10

**Issue**:
Automatic content updation in the existing template.I need the solution for it If the user gives input which is not related to the intent the bot responds automatically to the user.

I have tried a fallback policy method which bot responses as a single response. I like to be as an automated one.

Is there any possibility to do that.?

Thanks in advance

**Comment by sara-tagger** [comment]
Thanks for raising this issue, @erohmensing will get back to you about it soon✨

###### Please also check out the [docs](https://rasa.com/docs/) and the [forum](https://forum.rasa.com/) in case your issue was raised there too 🤗

**Comment by erohmensing** [comment]
Hi @Dinesh-gowdam-2610 , this sounds like a question around implementation, not a bug. Please reach out on our [forum](forum.rasa.com) for implementation help, and if you think there is a bug, please fill out the template with information to reproduce the behavior. Thanks!
