### ISSUE TITLE
Rasa interactive duplicates some slot events

### ISSUE THREAD

**Issue by tatianafrank** [RasaHQ/rasa#7212]
**Rasa version**: 2.0.0

**Rasa SDK version** (if used & relevant):

**Rasa X version** (if used & relevant):

**Python version**: 3.7.0

**Operating system** (windows, osx, ...): osx

**Issue**:

When using rasa interactive cli to generate training stories, some slot set events are duplicated in the generated stories like this:

*   story: interactive_story_2
     steps:
*   intent: find_restaurant
*   action: restaurant_form
*   active_loop: restaurant_form
*   slot_was_set:
*   requested_slot: cuisine
*   slot_was_set:
*   cuisine: french
*   slot_was_set:
*   cuisine: french
*   slot_was_set:
*   requested_slot: num_people
*   intent: inform
     entities:
*   num_people: '2'
*   slot_was_set:
*   num_people: '2'
*   action: action_deactivate_loop
*   active_loop: null
*   slot_was_set:
*   requested_slot: null
*   action: utter_french_indian_other

**Error (including full traceback)**: No error, just duplicated slot events in the generated training stories.

**Command or request that led to error**:

 rasa interactive

**Content of configuration file (config.yml)** (if relevant):

**Content of domain file (domain.yml)** (if relevant):

**Comment by sara-tagger** [comment]
Thanks for the issue, @amn41 will get back to you about it soon!

###### You may find help in the [docs](https://rasa.com/docs/) and the [forum,](https://forum.rasa.com/) too 🤗

**Comment by metal3d** [comment]
Have the same issue #7476

**Comment by zegabr** [comment]
https://rasa.com/docs/rasa/playground The example on the playground page have the same issue. 
![rasabug](https://user-images.githubusercontent.com/20018825/129462536-2809c043-30ce-4164-913e-a55ef920671d.png)

**Comment by zegabr** [comment]
> https://rasa.com/docs/rasa/playground The example on the playground page have the same issue.
> ![rasabug](https://user-images.githubusercontent.com/20018825/129462536-2809c043-30ce-4164-913e-a55ef920671d.png)

when rinning interactive mode, this happens:
![rasabug](https://user-images.githubusercontent.com/20018825/129462595-8dddfb9b-0d74-4dcc-9659-2e3742b60143.png)
The form asks for the email also after it is given, but automatically overrides the extracted entity with the complete user input
