### ISSUE TITLE
Typo in documentation for Defining a Two-Stage Fallback rule

### ISSUE THREAD

**Issue by prathameshThakur** [RasaHQ/rasa#7237]
Need an update in the documentation of Rasa Open Source ([here](https://rasa.com/docs/rasa/fallback-handoff#3-defining-a-two-stage-fallback-rule))
![doc-error](https://user-images.githubusercontent.com/56729180/98723174-0c2a8580-23b8-11eb-97ee-c246e9ed8249.png)
In the above code snap the step of a rule is set with `active_loop: two_stage_fallback`, but there is no default action naming `two_stage_fallback`

**Comment by prathameshThakur** [comment]
Hey,
I would like to contribute to fixing these issues!
Can I get assigned for this?

**Comment by sara-tagger** [comment]
Thanks for raising this issue, @melindaloubser1 will get back to you about it soon✨

###### Please also check out the [docs](https://rasa.com/docs/) and the [forum](https://forum.rasa.com/) in case your issue was raised there too 🤗

**Comment by melindaloubser1** [comment]
Hey  @prathameshThakur thanks for pointing this out! You're right, it should be `action_two_stage_fallback`. Feel free to open a PR to fix it and tag me in it.

**Comment by prathameshThakur** [comment]
Hey @melindaloubser1, I have made a pull request.
Can you please review it!
