### ISSUE TITLE
Add __repr__ to Token object

### ISSUE THREAD

**Issue by koaning** [RasaHQ/rasa#7250]
When I'm debugging what is happening in a pipeline I usually have a look and print the `Message`.

It might look something like;

<pre>> message.as_dict_nlu()
 {'entities': [],
 'intent': 

 {'confidence': 0.8422146439552307, 'id': 5464168520135895892, 'name': 'are_you_real'} 

,
 'intent_ranking': [

 {'confidence': 0.8422146439552307, 'id': 5464168520135895892, 'name': 'are_you_real'} 

,

 {'confidence': 0.04479081928730011, 'id': -5724794541682903534, 'name': 'how_made'} 

,

 {'confidence': 0.021328529343008995, 'id': -6505008832162321521, 'name': 'how_are_you'} 

,

 {'confidence': 0.019935669377446175, 'id': 522343063256866795, 'name': 'what_can_you_do'} 

,

 {'confidence': 0.013976013287901878, 'id': 7022544970669495622, 'name': 'languages'} 

,

 {'confidence': 0.013974795117974281, 'id': -279316034893973609, 'name': 'weather'} 

,

 {'confidence': 0.013861254788935184, 'id': -3284643768121576930, 'name': 'what_time'} 

,

 {'confidence': 0.013021928258240223, 'id': -938916847167484283, 'name': 'who_made_you'} 

,

 {'confidence': 0.011181396432220936, 'id': 2425092467132022535, 'name': 'birthday'} 

,

 {'confidence': 0.005714914295822382, 'id': 4373745406320874474, 'name': 'restaurant'} 

],
 'intent_tokens': [<rasa.nlu.tokenizers.tokenizer.token object at 0x7fdc606328d0>
 ],
 'text': 'are you a real person',
 'text_tokens': [
 <rasa.nlu.tokenizers.tokenizer.token object at 0x7fdc880b1350>
 ,

 <rasa.nlu.tokenizers.tokenizer.token object at 0x7fdc6057ff90>
 ,

 <rasa.nlu.tokenizers.tokenizer.token object at 0x7fdc6057fed0>
 ,

 <rasa.nlu.tokenizers.tokenizer.token object at 0x7fdc6057ff50>
 ,

 <rasa.nlu.tokenizers.tokenizer.token object at 0x7fdc6057ff10>
 ]}
 </rasa.nlu.tokenizers.tokenizer.token>
 </rasa.nlu.tokenizers.tokenizer.token>
 </rasa.nlu.tokenizers.tokenizer.token>
 </rasa.nlu.tokenizers.tokenizer.token>
 </rasa.nlu.tokenizers.tokenizer.token>
 </rasa.nlu.tokenizers.tokenizer.token></pre>

Would anybody be opposed if I add a `__repr__` to the `Token` such that you can see the actual text of the token? It should make it easier to inspect/debug.

@tabergma any objections?

**Comment by koaning** [comment]
I might want to do something similar to `rasa.shared.nlu.training_data.features.Features`. It might make sense to share the information on the shape of the underlying numpy arrays. 

![image](https://user-images.githubusercontent.com/1019791/98918176-97e20600-24cd-11eb-9cb9-e8c391cf5565.png)

**Comment by tabergma** [comment]
Good idea 💯

**Comment by pedro-prp** [comment]
Hi, is this issue open to the community?

**Comment by pedro-prp** [comment]
I saw that a problem still exists, @koaning are you still working on it? If no, I would try to solve it

**Comment by koaning** [comment]
There's a PR for it but unfortunately it cannot get merged due to a style check.

**Comment by ErickGiffoni** [comment]
I think we can close this issue, since it was solved in #9631
