### ISSUE TITLE
Make confidence histograms easier to read

### ISSUE THREAD

**Issue by amn41** [RasaHQ/rasa#7257]
**Description of Problem**:

`rasa test` currently produces a histogram of confidence values for both correct and incorrect predictions. 

![image](https://user-images.githubusercontent.com/5114084/98939168-eea50b00-24e0-11eb-9cb3-6e66236bf837.png)

IMO something like this would be easier to read, e.g.:

<img width="394" alt="image" src="https://user-images.githubusercontent.com/5114084/98939257-0da39d00-24e1-11eb-9008-ac6bef3eac12.png">

**Definition of Done**:
- [ ] Tests are passing
- [ ] Example images are updated in the docs
- [ ] Feature mentioned in the changlog

**Comment by UTkzhang** [comment]
Hey, our team would like to take a look at this task and work on getting a PR up. We are university students looking to contribute as part of a course.

**Comment by eanile** [comment]
> Hey, our team would like to take a look at this task and work on getting a PR up. We are university students looking to contribute as part of a course.

+1

**Comment by lymburn** [comment]
> Hey, our team would like to take a look at this task and work on getting a PR up. We are university students looking to contribute as part of a course.

+1

**Comment by shadow-blade-X** [comment]
> Hey, our team would like to take a look at this task and work on getting a PR up. We are university students looking to contribute as part of a course.

+1

**Comment by UTkzhang** [comment]
@amn41

**Comment by amn41** [comment]
sounds great! thanks for getting involved, this would be a great contribution :)

**Comment by UTkzhang** [comment]
@amn41  could you assign it to us under doing in the contributor board please :)

**Comment by UTkzhang** [comment]
our pr is also up: https://github.com/RasaHQ/rasa/pull/7404

**Comment by UTkzhang** [comment]
@amn41 sorry, could any maintainer help us add this issue to the board and assign it to us ? Thanks!
