### ISSUE TITLE
Add documentation on how to deploy an action server

### ISSUE THREAD

**Issue by tmbo** [RasaHQ/rasa#7261]
Currently, there is no documentation explaining how to deploy an action server using docker. The only documentation we have focuses on `rasa run actions`.

**Comment by PedroLucasCM** [comment]
Hey guys, me and @antoniotoineto saw this issue and verified if there was a way do deploy an action server using docker and there is. So we think the issue is resolved and therefore should be closed.

**Comment by antoniotoineto** [comment]
Yes! We saw that this documentation can be found in this [link](https://rasa.com/docs/action-server/deploy-action-server/#automating-your-action-server-image-builds)

**Comment by rgstephens** [comment]
This is documented [here](https://rasa.com/docs/rasa/docker/building-in-docker/#adding-custom-actions) and you can see working docker builds of action servers in the example bots ([financial-demo](https://github.com/RasaHQ/financial-demo/blob/main/Dockerfile), [rasa-demo](https://github.com/RasaHQ/rasa-demo/blob/main/Dockerfile)). There's also the GitHub action to build the image [here](https://github.com/RasaHQ/rasa-action-server-gha).
