### ISSUE TITLE
Implement prepare_partial_training on NLU components

### ISSUE THREAD

**Issue by tabergma** [RasaHQ/rasa#7274]
related to #6836

Before the NLU components can be trained in chunks some of them need to be prepared. Each component should extract all information from the `TrainingData` needed inside the `prepare_partial_training` method, so that it can be used for partial training later on. 

For example:
- `CountVectorsFeaturizer` needs to build up a vocabulary from the complete training data. The training data should be tokenized already.
- `RegexFeaturizer` should build up the regexes from the regexes and lookup tables present in the training data.
- `RegexEntityExtractor` should build up the regexes from the regexes and lookup tables present in the training data.
- `EntitySynonymMapper` should build up the synonyms from the synonyms present in the training data.

Note: They might be more components that need to implement this method. Make sure to check all of them.

**Note**: This feature should branch off from `partial-dataset-loading` and should be squashed and merged back into that branch.

**Comment by tabergma** [comment]
@Ghostvv As we spoke about this issue this morning. I guess it might make sense to tackle this together with the implementation of `trian_chunk` for the featurizers. I'll take over one of the other issues instead. Let me know if you think otherwise.

**Comment by Ghostvv** [comment]
@tabergma it seems to me that `Component.prepare_partial_training` is not called anywhere. As part of this issue, should I only implement this method in all subclasses, or also call it in appropriate place?

**Comment by tabergma** [comment]
it will be called once [this PR](https://github.com/RasaHQ/rasa/pull/7298) gets approved, unfortunately still waiting for a review
