### ISSUE TITLE
Change DucklingEntityExtractor to use async

### ISSUE THREAD

**Issue by akelad** [RasaHQ/rasa#7275]
**Description of Problem**: DucklingEntityExtractor still uses the requests package, instead of asyncio. This means that part of the NLU pipeline might slow things down a bit, especially when dealing with a lot of requests.

**Overview of the Solution**: We should switch it to asyncio instead, @wochinge said that that would mean a change to the `Component` interface as well.

**Comment by wochinge** [comment]
@tabergma Any thoughts about this? I stumbled across multiple interfaces recently which are currently not `async` but might be worth adapting.

**Comment by tabergma** [comment]
@wochinge Why would we need to change the interface of `Component`?

**Comment by wochinge** [comment]
Currently `DucklingEntityExtractor` uses `requests` to send requests (see [here](https://github.com/RasaHQ/rasa/blob/34ee64572af4ba89e764cde46911242292addab8/rasa/nlu/extractors/duckling_entity_extractor.py#L132)). To make use of the event loop and `asyncio` we'd replace this with `aio-http`. This would mean that `def _duckling_parse` would become `async def _duckling_parse`. This in turn would make it necessary to change `def process` to `async def process` . And that in turn would make it required to change the interface of `Component` (unless you want to work with `isinstance` checks 😬 )

**Comment by tabergma** [comment]
As long as we make sure that the order of the components processing the messages is the same and that we actually wait for one component to finish before the next one can start processing, we should be fine.

**Comment by kaustuk** [comment]
Hi @wochinge @akelad is this still relevant and open for the community? 

I would like to work on this.

**Comment by wochinge** [comment]
Hi @kaustuk,

thanks for double checking with us before implementing the change! We are having pretty advanced plans to revamp how we process things during prediction time in Rasa Open Source 3.0. This will change the interface severely so I'd suggest to hold off with the change for the moment. Does that sound alright?

**Comment by kaustuk** [comment]
Hi @wochinge, thanks for the reply. Yeah, that makes sense to wait for Rasa Open Source 3.0 since the interface and all would be changed.
