### ISSUE TITLE
Implement `train_chunk` for all nlu featurizers

### ISSUE THREAD

**Issue by tabergma** [RasaHQ/rasa#7277]
related to #6836

For partial dataset loading we want to featurize only a part of the data at a time. Implement the method `train_chunk` for all featurizers. The method will get a `TrainingDataChunk` that contains a list of messages, a subset of all training data.

Most likely you can just call the normal `train` method for the given examples.

**Note**: This feature should branch off from `partial-dataset-loading` and should be squashed and merged back into that branch.

**Comment by wj-Mcat** [comment]
This is not been linked with any pull request, can I have a try to implement it?

**Comment by tabergma** [comment]
@wj-Mcat Thanks for your interest in this! As this is part of a larger project that we are still defining, we cannot open up this issue to the community. Sorry. Take a look at https://github.com/orgs/RasaHQ/projects/23 for open issues that you can work on.

**Comment by Ghostvv** [comment]
@tabergma is it core or nlu featurizers? or both?

**Comment by tabergma** [comment]
we should have a separate issue for core, so just NLU.
