### ISSUE TITLE
checkpoint_model ignores best model if just one metric stays the same

### ISSUE THREAD

**Issue by Xwaler** [RasaHQ/rasa#7286]
This issue concerns the checkpoint_model parameter in every trainable component (DietClassifier, ResponseSelector, RulePolicy, etc...)
In order to save a model that has improved in every metric except one that has staled (can even stale at 1.00 accuracy !), the _does_model_improve function could compare with a superior or equal sign rather than superior strict.

https://github.com/RasaHQ/rasa/blob/0ccfa20ef72f7f6d4e4e1f3e0bf88d8568bfcb7e/rasa/utils/tensorflow/models.py#L483
```
all_improved = all(
            [
                float(current_results[key]) >= self.best_metrics_so_far[key]
                for key in self.best_metrics_so_far.keys()
            ]
        )
```

**Comment by sara-tagger** [comment]
Thanks for the issue, @alopez will get back to you about it soon!

###### You may find help in the [docs](https://rasa.com/docs/) and the [forum,](https://forum.rasa.com/) too 🤗
