### ISSUE TITLE
Rasa train retrains both NLU and Core even if only the rules are changed

### ISSUE THREAD

**Issue by nbeuchat** [RasaHQ/rasa#7290]
**Rasa version**: 2.0.6 

**Python version**: 3.7.9

**Operating system** (windows, osx, ...): Ubuntu

**Issue**: 
`rasa train` retrains both the NLU and Core when I only modify rules and the NLU training data has not changed at all. The domain and config have not changed either. 

**Command or request that led to error**:
```
rasa train
```

**Comment by sara-tagger** [comment]
Thanks for raising this issue, @ArjaanBuijk will get back to you about it soon✨

###### Please also check out the [docs](https://rasa.com/docs/) and the [forum](https://forum.rasa.com/) in case your issue was raised there too 🤗

**Comment by joejuzl** [comment]
Hi @nbeuchat, I can't replicate this... 
Can you confirm this is still a bug? And if so provide some example config/data?
