### ISSUE TITLE
Consistent usage of log levels

### ISSUE THREAD

**Issue by tmbo** [RasaHQ/rasa#7295]
**Description of Problem**: It is unclear which log level should be used for which purpose when building a bot. More often than not, one will notice that either there is to much information in an output log or to little while developing a bot.

The python guidelines on log levels ([https://docs.python.org/3/howto/logging.html#when-to-use-logging](https://docs.python.org/3/howto/logging.html#when-to-use-logging)) can serve as an orientation. We do have two common diagnostic cases needed by different users: debugging a bot (e.g. action failed to execute) VS debugging underlying machine learning machinery (e.g. wrong featurization).

**Overview of the Solution**: All log levels should have a definition of when we expect a user to use them, e.g. during local development we'd expect a user to use log level `debug`. Of course the user can use a different log level, but this should guide us which information should be logged at which severity. This is mainly focused on `rasa run`.

Situations we should clarify the log level for:

*   developing and tweaking ML components/policies: TRACE
*   local development of a bot: DEBUG
*   running a server in production: INFO / WARNING / ERROR

This would require us to add an additional log level (`TRACE`) with lower severity than `DEBUG`. E.g. we would log something like

 2020-11-15 14:20:30 DEBUG rasa.core.policies.rule_policy - Current tracker state:
 <span class="error">[state 1]</span> user intent: affirm | previous action name: action_listen

using trace.

**Comment by wochinge** [comment]
Great push! 👍 

I think we should also considering [structlog](https://www.structlog.org/en/stable/index.html) when running in production. That makes it easier to monitor Rasa (X) deployments via ELK etc. In local mode plain text logs might be more user friendly. However, `structlog` could also be interesting in this case as it would allow for quick filtering for certain things (e.g. output of ML components)

**Comment by tmbo** [comment]
oh interesting, I do see the appeal for automated monitoring but as you said not quite practical for local debugging - at least not everywhere. 

would love to hear @tczekajlo opinion on the structured logging + elk part

**Comment by tczekajlo** [comment]
I'd love to see structured logging for rasa running in a container. Current logging basically is useless without additional configuration/parser for ELK.

Also, I think it would be great if rasa has `auto` mode for logging - if `tty` is available display logging that is more user-friendly.

**Comment by tmbo** [comment]
what information would we log if we'd use something like the mentioned `structlog` to work with ELK? e.g. are there default attributes we should log or is it completely up to us?

**Comment by tczekajlo** [comment]
> what information would we log if we'd use something like the mentioned `structlog` to work with ELK? e.g. are there default attributes we should log or is it completely up to us?

It's up to us. If we would use JSON format as well there are `ts` and `msg` fields. Here is a short blogpost about structured logs in the Kubernetes https://kubernetes.io/blog/2020/09/04/kubernetes-1-19-introducing-structured-logs/ (might brings some ideas)

**Comment by wochinge** [comment]
> what information would we log if we'd use something like the mentioned structlog 

An idea would be to log similar things as @rgstephens is logging in his OpenTelemetry changes 🤔

**Comment by rgstephens** [comment]
> What information would we log

Wouldn't we replace all existing std logger module calls with structlog?

> This would require us to add an additional log level (`TRACE`) with lower severity than `DEBUG`.

The trace level would also be useful for troubleshooting lock store, event broker and any other areas that could generate a large number of log messages. I currently hesitate to add logging to these areas but a trace level would be useful for this.

> Logging & OpenTracing/Telemetry

Switching to structured logging would fit well with tracing. The structured logs would be attached to spans. There's an example of that with OpenTracing [here](https://opentracing.io/guides/python/spans/#granularity-spans-vs-logs). [Elastic](https://www.elastic.co/guide/en/apm/agent/python/current/log-correlation.html) and [Datadog](https://docs.datadoghq.com/tracing/connect_logs_and_traces/python/) both provide examples of integrating stuctlog with their proprietary tracing systems.

**Comment by JEM-Mosig** [comment]
This just came up in another issue where the debug log of RulePolicy slows things down for the customer with ~1000 events per tracker. Apparently, most customers run their bot in production with the debug flag on. I suspect we'll never convince customers to stop this, so better reduce the debug output and create a new secret debug flag that only Rasa internals know about (and people who study the code base).

**Comment by rgstephens** [comment]
I don't think any changes should be made to reduce the debug messages. There are good options for handling large volumes of log messages efficiently.
