### ISSUE TITLE
Rasa x saves stories into rules.yml file

### ISSUE THREAD

**Issue by sparklie3** [RasaHQ/rasa#7300]
Rasa Version     : 2.0.2
Rasa SDK Version : 2.0.0
Rasa X Version   : 0.33.2
Python Version   : 3.8.5
Operating System : Linux-4.19.128-microsoft-standard-x86_64-with-glibc2.29

**Issue**: Rasa x saves stores into rules.yml file. 

**Error (including full traceback)**:
```
None. You only notice it because I see stories in the rules.yml file. 
```

**Command or request that led to error**:
```
NA
```

**Content of configuration file (config.yml)** (if relevant):
```yml
NA
```

**Content of domain file (domain.yml)** (if relevant):
```yml
NA
```

**Comment by TyDunn** [comment]
@sparklie3 Thanks for submitting this bug report! The original forum thread can be found [here](https://forum.rasa.com/t/is-it-normal-for-rasa-x-to-save-stories-to-go-into-rules-yml-file-instead-of-stories-yml/37062/3)

**Comment by TyDunn** [comment]
@federicotdn Can we close this issue since the fix was merged?

**Comment by federicotdn** [comment]
Yes :+1:
