### ISSUE TITLE
'RedisTrackerStore' object has no attribute 'prefix'

### ISSUE THREAD

**Issue by ducminh-phan** [RasaHQ/rasa#7306]
**Rasa version**: 2.1.0

**Python version**: 3.7.9

**Operating system** (windows, osx, ...): 

**Issue**: 

An error occurred when using `tracker_store` of type `redis`.

**Error (including full traceback)**:
```
2020-11-18 08:22:25 ERROR    rasa.core.tracker_store  - Error happened when trying to save conversation tracker to 'RedisTrackerStore'. Falling back to use the 'InMemoryTrackerStore'. Please investigate the following error: 'RedisTrackerStore' object has no attribute 'prefix'.
```

Looks like the issue comes from this line: https://github.com/RasaHQ/rasa/blob/384b078b74e7f365f9262d80977a30615d6ecb3f/rasa/core/tracker_store.py#L349

It should be `self.key_prefix` instead of `self.prefix`.

**Comment by sara-tagger** [comment]
Thanks for the issue, @erohmensing will get back to you about it soon!

###### You may find help in the [docs](https://rasa.com/docs/) and the [forum,](https://forum.rasa.com/) too 🤗

**Comment by erohmensing** [comment]
Thanks @ducminh-phan for pointing this out. Do you want to open a PR against `2.1.x` to contibute this fix?

**Comment by ducminh-phan** [comment]
> Thanks @ducminh-phan for pointing this out. Do you want to open a PR against `2.1.x` to contibute this fix?

Sure, I will try to fix the issue and open a PR then.

**Comment by erohmensing** [comment]
Awesome 🚀
