### ISSUE TITLE
BotFramework Channel uses shared authentication cache

### ISSUE THREAD

**Issue by hotzenklotz** [RasaHQ/rasa#7309]
**Rasa version**: master

**Python version**: 3.7

**Operating system** (windows, osx, ...): all

**Issue**: The MS BotFramework channel uses one shared OAuth key cache for all instances: [https://github.com/RasaHQ/rasa/blob/master/rasa/core/channels/botframework.py#L50](https://github.com/RasaHQ/rasa/blob/master/rasa/core/channels/botframework.py#L50)

This fails if you create several instances of the Botframework class.

**Comment by sara-tagger** [comment]
Thanks for raising this issue, @samsucik will get back to you about it soon✨

###### Please also check out the [docs](https://rasa.com/docs/) and the [forum](https://forum.rasa.com/) in case your issue was raised there too 🤗

**Comment by m-vdb** [comment]
@tmbo are you planning to work on this issue or should I move it to Enable's board?

**Comment by tmbo** [comment]
prob won't get to this any time soon, moved it to enable inbox :+1:

**Comment by hotzenklotz** [comment]
@stale You probably want to fix this and not close it only because the devs have not yet addressed the issue ;-)
