### ISSUE TITLE
ERROR: No matching distribution found for tensorflow~=1.13.0 (from rasa_core)

### ISSUE THREAD

**Issue by susajsnair** [RasaHQ/rasa#7312]
I am trying to install `pip3 install rasa_core` in virtual environment and getting following error.

`ERROR: Could not find a version that satisfies the requirement tensorflow~=1.13.0 (from rasa_core) (from versions: 2.2.0rc1, 2.2.0rc2, 2.2.0rc3, 2.2.0rc4, 2.2.0, 2.2.1, 2.3.0rc0, 2.3.0rc1, 2.3.0rc2, 2.3.0, 2.3.1, 2.4.0rc0, 2.4.0rc1, 2.4.0rc2)
ERROR: No matching distribution found for tensorflow~=1.13.0 (from rasa_core)`

Rasa Version     : 2.0.2
Rasa SDK Version : 2.1.2
Rasa X Version   : 0.33.2
Python Version   : 3.8.5
OS : Ubuntu 20.04

![Screenshot from 2020-11-19 18-06-24](https://user-images.githubusercontent.com/31278089/99667157-fb51d200-2a91-11eb-9682-59c90ec115bf.png)

**Comment by sara-tagger** [comment]
Thanks for raising this issue, @alopez will get back to you about it soon✨

###### Please also check out the [docs](https://rasa.com/docs/) and the [forum](https://forum.rasa.com/) in case your issue was raised there too 🤗

**Comment by kiranbeethoju** [comment]
You can fix by using virtualenv.
create new virtualenv using virtualenv lib in Linux, or `conda create -n newEnvName`
then activate your virtualenv 
then install only below two files with pip3 rest all will be taken care by system..

```
rasa~=2.0.0

rasa-sdk~=2.0.0
```

**Comment by susajsnair** [comment]
@kiranbeethoju please read it again, i have already `rasa` and `rasa sdk` in my env, but i am unable to intall `rasa_core`.

All i want to access `from rasa_core.interpreter import RasaNLUInterpreter` in my actions.py

**Comment by joejuzl** [comment]
`rasa_core` is no longer a supported package, it is now part of `rasa` so you can access all required modules from there.
