### ISSUE TITLE
models created by rasa train in cmdline doesn't show up in Rasa X local machine

### ISSUE THREAD

**Issue by sparklie3** [RasaHQ/rasa#7319]
Rasa Version : 2.0.2 Rasa SDK Version : 2.0.0 Rasa X Version : 0.33.2 Python Version : 3.8.5 Operating System : Linux-4.19.128-microsoft-standard-x86_64-with-glibc2.29

**Issue**: models created by rasa train in cmdline doesn't show up in Rasa X local machine If you run `rasa train` and create a model, that model is saved in the /models folder but doesn't appear in the Rasa X UI in models. You have to create the model via Rasa X UI to be able to activate it in Rasa X.

For example, I have /models/20201117-145118.tar.gz in my folder, but the Rasa X UI only shows 20201117-144744 as the latest version and I don't know how to get Rasa X to display these. Ctrl + C and restarting Rasa X doesn't pick up the models in the /model folder.

**Error (including full traceback)**:

 NA

**Command or request that led to error**:

 NA

**Content of configuration file (config.yml)** (if relevant):

<pre>NA</pre>

**Content of domain file (domain.yml)** (if relevant):

<pre>NA</pre>

**Comment by sara-tagger** [comment]
Thanks for raising this issue, @koaning will get back to you about it soon✨

###### Please also check out the [docs](https://rasa.com/docs/) and the [forum](https://forum.rasa.com/) in case your issue was raised there too 🤗

**Comment by alinazhanguwo** [comment]
hit the same issue. also, the model trained with local Rasa X doesn't write into local folder models/

**Comment by koaning** [comment]
Have you tried refreshing the browser?
