### ISSUE TITLE
Feature Request -  upload model to S3 after training is done

### ISSUE THREAD

**Issue by mbukovy** [RasaHQ/rasa#7326]
**Description of Problem**: According to this [https://rasa.com/docs/rasa/model-storage](https://rasa.com/docs/rasa/model-storage) it is possible to use AWS S3 as a model storage. Loading from S3 bucket works fine, but we're missing upload right after training.

**Overview of the Solution**: There should be a possibility to upload the model to S3 (or other clouds eventually) instead of saving it into models/ folder on disc when training is done. I would expect this to be automatic when AWS credentials are set (if I want to load the model from S3, I want to save into it as well), but there could also be some separated switch. Expected behavior - when training is finished (by `rasa train` command or `POST /model/train` endpoint), model is being sent into S3 automatically instead of saved to the disc.

My forum thread [https://forum.rasa.com/t/aws-upload-to-s3-after-training/37156](https://forum.rasa.com/t/aws-upload-to-s3-after-training/37156)

**Definition of Done**: TBD

**Comment by sara-tagger** [comment]
Thanks for submitting this feature request 🚀 @kalkbrennerei will get back to you about it soon! ✨

**Comment by koep** [comment]
Great idea, would love to see this!

**Comment by Polarisation** [comment]
This is how it used to work in Rasa NLU v0.x. Now I'm upgrading to Rasa Open Source, I noticed this is missing.

Saving to disk isn't a good open when deploying a Docker container.

**Comment by dingusagar** [comment]
good feature to have. anyone working on this?

**Comment by ishan1608** [comment]
I am using AWS lambda to run the API for an admin panel which is supposed to be used to train and deploy models (according to our criteria).
S3 is running on a server on which I don't have any control.
If I provide a callback_url AWS's API gateway doesn't allow a payload of more than 10 MB.
So that is not working for us.
Uploading to S3 would solve this problem for us.

Any updates on whether this is planned to be implemented or not?

**Comment by rgstephens** [comment]
@ishan1608 See the example GitHub action workflow [here](https://github.com/RasaHQ/financial-demo/blob/7627cebef1571d55855b886cf4ac20459af9566c/.github/workflows/cicd.yml#L21)

**Comment by vbs123456** [comment]
is this feature available? saving model to aws s3, as i see this issue being closed.

**Comment by m-vdb** [comment]
@vbs123456 we moved this ticket to Jira here: https://rasa-open-source.atlassian.net/browse/OSS-142. This feature is not available.

**Comment by vbs123456** [comment]
Thanks for update :)
