### ISSUE TITLE
Implement Command-Line interface for finetuning models

### ISSUE THREAD

**Issue by wochinge** [RasaHQ/rasa#7328]
Implement the command-line interface for https://github.com/RasaHQ/rasa/issues/6971.

- [x] Implement parsing of `rasa train --finetune --model <path to model to finetune>`
  * `--finetune` is `False` by default
  * `--model` is optional. In case it's not given, Rasa Open Source will try to use the latest model from the `models` directory
- [x] track in telemetry event if `--finetune` was used
- [x] pass necessary information down to the training of the core model and the NLU model

**Comment by wochinge** [comment]
@dakshvar22 Two ideas
* How about using something like `rasa train --finetune <model path>`? Not sure if we can make it work if users don't specify `model path` (e.g. if they want to use the latest model), but we can at least try? 
* Do we need a parameter to quickly override the epochs? E.g. something like `--epoch-fraction`? It seems annoying to me to require two equal configs or change it in between. It also seems to be nicer for the usage with the auto config feature .

**Comment by dakshvar22** [comment]
@wochinge
1. I like the idea if we are able to make it work without users having to specify the model path as well.
2. I like that idea from a UX perspective but I am not sure if a single `epoch-fraction` works well for all components(`DIET`, `ResponseSelector` etc.). I would still say let's add it, if it works it is very useful indeed.

**Comment by wochinge** [comment]
Ok 👍 What should we choose as default for the epoch fraction? We can always add a third argument for the entity epoch fraction in case we see that users are running into issues. We could e.g. have a logic like this then:
```
intent_epoch_fraction = args.epoch_fraction
entity_epoch_fraction = args.epoch_fraction
if args.entity_epoch_fraction:
   entity_epoch_fraction = args.entity_epoch_fraction

```

**Comment by dakshvar22** [comment]
Setting a default here is tricky since we don't know how much amount of data got added. Do we currently/ Should we store the number of data points a particular component was trained on? If yes, then we would know how much extra data each component received and set a default for the epoch fraction inside the component.

Otherwise, we should only use this parameter if the user defined a value for it in the CLI.
