### ISSUE TITLE
tracker.sender_id always returns `default` in custom actions

### ISSUE THREAD

**Issue by nbeuchat** [RasaHQ/rasa#7338]
**Rasa version**: 2.1.0

**Rasa SDK version**: 2.1.1

**Python version**: 3.7.9

**Operating system**: Ubuntu

**Issue**:
In all of my custom actions, `tracker.sender_id` now always returns `default` instead of the actual sender id. We are heavily using this sender id as user identifiers in our database which currently fails as a result. 

Note that I am using Facebook Messenger and in the Rasa core, the `sender_id` is correctly set.

**Error (including full traceback)**:
No error is thrown

**Command or request that led to error**:
```
rasa run actions --action actions --debug
```

**Comment by nbeuchat** [comment]
Hi @joejuzl thanks for checking! I see where the issue lies now. Happy to provide a fix, looking into this now.

**Comment by nbeuchat** [comment]
@wochinge I am looking at the `_run_action` from the `MessageProcessor`. I see that you added the temporary tracker that copies from the original one. However, `tracker.copy()` does not copy the `sender_id` because of how `init_copy` initializes the sender id:

```
    def init_copy(self) -> "DialogueStateTracker":
        """Creates a new state tracker with the same initial values."""

        return DialogueStateTracker(
            DEFAULT_SENDER_ID,  # problematic line
           ...
```

In order to fix this, I see two options:

- Set the `sender_id` on the `temporary_tracker`
- Modify the behavior of `DialogueStateTracker.copy` or `DialogueStateTracker.init_copy` so that they also copy the sender id. However, I do not have enough overview on the whole Rasa ecosystem to understand how that would effect other parts of Rasa. 

What do you think would be the best approach? 

Thanks for your inputs! Happy to do a PR afterwards :-)

**Comment by wochinge** [comment]
> Modify the behavior of DialogueStateTracker.copy or DialogueStateTracker.init_copy so that they also copy the sender id. However, I do not have enough overview on the whole Rasa ecosystem to understand how that would effect other parts of Rasa.

That sounds perfect! 👍 I checked the code base and it should actually fix a couple of other locations which use `init_copy` 🙈  Feel free to request review from me then 👍

**Comment by nbeuchat** [comment]
Perfect, will work on it today!

**Comment by wochinge** [comment]
Please target `2.1.x` for your PR. Then we can ship a patch release asap.

**Comment by thanhnv15119** [comment]
I try to update rasa 2.1.3 and also my rasa sdk 2.1.2 but still get this bug. This happens in rasa docker hub images also. Did this release? I'm so stuck at here :(

**Comment by dabonde** [comment]
> I try to update rasa 2.1.3 and also my rasa sdk 2.1.2 but still get this bug. This happens in rasa docker hub images also. Did this release? I'm so stuck at here :(

I also tried doing this the day it appeared to have released. Same problem. I spent a while trying to figure out if I was somehow using an old version, or if I was reading the git commits wrong and it had not yet released. Came up empty. Thought I'd shelve that part of my work for a bit and come back to re-test. 

So yes, has this fix been released? And in what version?

**Comment by wochinge** [comment]
The fix was released released in Rasa Open Source 2.1.1 (cc @nbeuchat )

**Comment by Chatzimina** [comment]
Hello, 

did you manage to find a solution for this? I am using the latest version of Rasa. I am sending in my Rasa webhook the "sender" value but when I try to get the sender using 

      tracker.current_state()['sender_id'] 

the result is "default" .

Thank you

**Comment by gdet** [comment]
Hello,

did you manage to find a solution for this? I am using the latest version of Rasa. I am sending in my Rasa webhook the "sender" value but when I try to get the sender using

  tracker.current_state()['sender_id'] 
the result is "default" .

Thank you

**Comment by nbeuchat** [comment]
@gdet which channel are you using? We fixed this issue in this PR #7341. Not sure if that's the same issue?

**Comment by gdet** [comment]
Hello,

I am trying to connect RASA to flutter and I am using the configuration of the website ("your own website"). I am posting the json data through Flutter http.post. Should I create a different channel?

**Comment by gdet** [comment]
Hello again,

So I had these versions:

Rasa Version     : 2.3.4
Rasa SDK Version : 2.3.1
Python Version   : 3.7.3

And I upgraded Rasa and now it is working. The version I have now for  rasa is  version 2.4.0

Thank you

**Comment by abhishek-teams** [comment]
Hello, I'm also facing the same issue with the following rasa version.

Rasa Version:         2.8.5
Minimum Compatible Version: 2.8.0
Rasa SDK Version:         2.8.2
Python Version:         3.8.10

Can anyone please help me out with that?

I really appreciate any help that can be provided.

**Comment by shari-amalgamrx** [comment]
@abhishek-teams . I was facing this issue because of my post request. Instead of sending 
{ 
 "sender": "user_id",
 }

I was sending 
{
"user": "user_id"
}

Not sure if thats what is causing an issue for you as well.

**Comment by abhishek-teams** [comment]
@shari-amalgamrx no I'm also using the same 
{
        'message': message,
        'sender': user_id
}
but still I'm getting "default"

**Comment by abhishek-teams** [comment]
@shari-amalgamrx Thanks for the help I was doing the same mistake now it works.

**Comment by meghna43** [comment]
I am facing same issue on "version": "3.5.10"
Can anyone please help me out with that?
