### ISSUE TITLE
Rasa X (local mode) removes version data in domain.yml when launched

### ISSUE THREAD

**Issue by ftarlaci** [RasaHQ/rasa#7343]
**Rasa version**: 2.0.2

**Rasa SDK version** 2.0.0

**Rasa X version** : 0.33.2

**Python version**: 3.7.9

**Operating system** Mac OS

**Issue**: When launching Rasa X from the terminal, `domain.yml` file changes, and the version data `version: "2.0"` from the domain file is removed. 

**Error (including full traceback)**:
```

```

**Command or request that led to error**: 
```
rasa x
```

**Content of configuration file (config.yml)** (if relevant):
```yml

```

**Content of domain file (domain.yml)** (if relevant):
```yml

```

**Comment by sara-tagger** [comment]
Thanks for the issue, @tmbo will get back to you about it soon!

###### You may find help in the [docs](https://rasa.com/docs/) and the [forum,](https://forum.rasa.com/) too 🤗

**Comment by tmbo** [comment]
mhm I don't think that is intended. @degiz do you know why this might be happening?

**Comment by degiz** [comment]
That's a bug inside `RasaX` indeed. Thanks for reporting that @ftarlaci !!
