### ISSUE TITLE
Checkout a custom branch of training data repo for model regression tests

### ISSUE THREAD

**Issue by dakshvar22** [RasaHQ/rasa#7357]
**Description of Problem**:
Currently, the model regression tests checks out the `master` branch of the training data [repo](https://github.com/RasaHQ/training-data/). This is sometimes limiting if we want to try running a custom configuration on a dataset as that custom configuration is not present on the `master` branch and we wouldn't want to place it there as well because the scheduled model regression tests uses that branch.

**Overview of the Solution**:
It looks like the repository is checked out [here](https://github.com/RasaHQ/training-data/). Adding an extra step where a custom branch of the training data repo is checked out and users can change it in their PR(temporarily) will allow for this.

**Comment by dakshvar22** [comment]
@tczekajlo Is this feasible?

**Comment by tczekajlo** [comment]
@dakshvar22 Yes, it should be feasible 😄

**Comment by dakshvar22** [comment]
@tczekajlo Awesome, looking forward to being able to use it. I think that would help the research team automate a lot of custom pipeline tests without having to even bring up any GCP instances manually!
