### ISSUE TITLE
Allow metadata key for nlu data other than intents (synonyms, regexes, etc.)

### ISSUE THREAD

**Issue by nbeuchat** [RasaHQ/rasa#7361]
**Description of Problem**: In Rasa 2.x, we can now add `metadata` to intents for custom NLU pipeline components. It would be great to have this flexibility for other NLU data such as synonyms.

I am currently building a custom synonym mapper that allows you to specify for which entity a synonym should be applied (which greatly helps for normalization). Think about having a synonym for "manchester" which could be either the city of "Manchester" or the football club of "Manchester United". In order to specify for which entity a given synonym list should be applied, I would like to add `metadata` at the synonym level.

I would use something like (I admit, I have no clue about football, just googled the examples above!):

 nlu:

*   synonym: Manchester United
     metadata:
*   include_entities:
*   football_club
     examples: |
*   manchester FC
*   manchester
*   The Red Devils
*   ManUnited
*   The United
*   The Reds
*   MUFC

Currently, the schema validation does not allow that to happen (and I suppose further processing down the line)

 YamlValidationException: Failed to validate 'data/nlu/synonyms.yml'. Please make sure the file is correct and all mandatory parameters are specified. Here are the errors found during validation:
 in data/nlu/synonyms.yml:3:
 Key 'synonym' was not defined. Path: '/nlu/0'

For my use case, I need it for the synonyms but I believe we should have the flexibility to use `metadata` for any NLU training data type to allow full flexibility for custom NLU components. Restricting synonyms to specific entities is just an example but we could also think about adding a flag for using fuzzy matching or not on a subset of synonyms.

**Overview of the Solution**: I am not very familiar with the internals of the training data validation and loading but I believe the following steps would be needed:

1.  Add `metadata` key to the schema validation file for the `synonym`, `regex`, `

*   type: "map"
     mapping:
     synonym:
     type: "str"
     metadata: *metadata_anchor
     examples: *examples_anchor
     ...

1.  Update the `TrainingData` class so that metadata (and duplicates) are passed into the `entity_synonyms` attribute
2.  Make the check and merge of duplicate synonyms within the `EntitySynonymMapper` instead of `TrainingData` so that other classes can use the full dataset
3.  Potentially other changes in the `TrainingData`/`EntitySynonymMapper`/other classes that I am not aware of

What are your thoughts on the above? My feeling is that it would provide much more flexibility for advanced users who create their own pipeline components and also allow easier addition of new pipeline components in Rasa NLU.

**Comment by sara-tagger** [comment]
Thanks for submitting this feature request 🚀 @joejuzl will get back to you about it soon! ✨

**Comment by m-vdb** [comment]
@joejuzl can you triage this issue, and if it makes sense, move it to Enable's inbox?
