### ISSUE TITLE
Optional arguments to rasa data convert are not optional

### ISSUE THREAD

**Issue by kaiogu** [RasaHQ/rasa#7362]
**Rasa version**:
2.0.6
**Rasa SDK version** (if used & relevant):

**Rasa X version** (if used & relevant):

**Python version**:
3.8.0
**Operating system** (windows, osx, ...):
ubuntu 18.04
**Issue**:
Arguments stated to be optional by the `rasa data convert xxx` help are not actually optional.

**Error (including full traceback)**:
```
❯ rasa data convert nlu
usage: rasa data convert nlu [-h] [-v] [-vv] [--quiet] -f {json,md,yaml} --data DATA --out OUT [-l LANGUAGE]
rasa data convert nlu: error: the following arguments are required: -f/--format, --data, --out
```
Contrast this with the help of the same command in which these arguments are stated to be optional and to have defaults:
```
❯ rasa data convert nlu --help
usage: rasa data convert nlu [-h] [-v] [-vv] [--quiet] -f {json,md,yaml} --data DATA --out OUT [-l LANGUAGE]

optional arguments:
  -h, --help            show this help message and exit
  -f {json,md,yaml}, --format {json,md,yaml}
                        Output format the training data should be converted into. Note: currently training data can be
                        converted to 'yaml' format only from 'md' format (default: yaml)
  --data DATA           Path to the file or directory containing Rasa NLU data. (default: data)
  --out OUT             File (for `json` and `md`) or existing path (for `yaml`) where to save training data in Rasa
                        format. (default: converted_data)
  -l LANGUAGE, --language LANGUAGE
                        Language of data. (default: en)
```

**Command or request that led to error**:
```
❯ rasa data convert nlu
❯ rasa data convert nlg
❯ rasa data convert core
```

**Content of configuration file (config.yml)** (if relevant):
```yml

```

**Content of domain file (domain.yml)** (if relevant):
```yml

```

**Definition of Done**
For all `rasa data convert` commands:
- [ ] set `required=False` (or don't set it) if a default was provided

**Comment by sara-tagger** [comment]
Thanks for the issue, @amn41 will get back to you about it soon!

###### You may find help in the [docs](https://rasa.com/docs/) and the [forum,](https://forum.rasa.com/) too 🤗

**Comment by wochinge** [comment]
The issue is that we mark things as `required` but give them defaults at the same type. Argparse treats everything with a default as `required=False` as optional but then still fails if not provided 🤦🏻
