### ISSUE TITLE
Slack Welcome message

### ISSUE THREAD

**Issue by koszta5** [RasaHQ/rasa#7366]
**Description of Problem**:
It is a generally accepted chatbot design pattern that chatbot should greet its users / give some options when the user first accesses it
https://botmywork.com/blog/chatbot-welcome-message/

**Overview of the Solution**:
When a user switches a slack window to direct messaging with the bot, bot would be informed about it and can react if it chooses so

**Examples** (if relevant):
N/A

**Blockers** (if relevant):
N/A

**Definition of Done**:
- [✅] Feature described the docs
- [✅ ] Feature mentioned in the changlog

**Comment by sara-tagger** [comment]
Thanks for submitting this feature request 🚀 @akelad will get back to you about it soon! ✨

**Comment by akelad** [comment]
@erohmensing do you know if this is possible in slack?

**Comment by koszta5** [comment]
@akelad i have already created a PR for this piece of code - sorry my bad I guess I should have linked it here 
https://github.com/RasaHQ/rasa/pull/7368
Basically this feature request was just a placeholder so that I could refer to it from my PR. Please let me know if I messed up the process in some way

**Comment by akelad** [comment]
I just added a reference to the issue in your PR :)
