### ISSUE TITLE
Rasa X Token with plus (+) symbol causes authorization error Docker Compose method

### ISSUE THREAD

**Issue by amardeep2006** [RasaHQ/rasa#7370]
**Rasa version**:
RASA version 2.0.3
**Rasa SDK version** (if used & relevant):

**Rasa X version** (if used & relevant):
0.32.2 
**Python version**:
3.6.8
**Operating system** (windows, osx, ...):
Windows 10 via Docker Compose method
**Issue**:
Rasa X server cannot reach rasa worker and rasa worker cannot fetch config from rasa x.

This issue is cause if there was + symbol is token generated by openssl.
Example : EWqzovCplp7L+9zqYmgBBg==

**Error (including full traceback)**:
```
Starting Rasa X in production mode… :rocket:

Could not fetch runtime config from server at ‘http://rasa-x:5002/api/config?token=EWqzovCplp7L+9zqYmgBBg==’. Exiting.

2020-11-04 14:07:55 DEBUG rasa.cli.x - Failed to get a proper response from remote server. Status Code: 401. Response: ‘{“reasons”:[“Authorization header not present.”],“exception”:“Unauthorized”}’

2020-11-04 14:08:00 DEBUG rasa.cli.x - Failed to get a proper response from remote server. Status Code: 401. Response: ‘{“reasons”:[“Authorization header not present.”],“exception”:“Unauthorized”}’
```

**Command or request that led to error**:
```

```

**Content of configuration file (config.yml)** (if relevant):
```yml

```

**Content of domain file (domain.yml)** (if relevant):
```yml

```

**Comment by sara-tagger** [comment]
Thanks for raising this issue, @tttthomasssss will get back to you about it soon✨

###### Please also check out the [docs](https://rasa.com/docs/) and the [forum](https://forum.rasa.com/) in case your issue was raised there too 🤗

**Comment by datafile4** [comment]
I faced the same problem. 
RASA_X_VERSION=0.38.1
RASA_VERSION=2.4.3
