### ISSUE TITLE
Command given in migration guide does not exist

### ISSUE THREAD

**Issue by kaiogu** [RasaHQ/rasa#7372]
**Rasa version**:
2.0.6
**Python version**:
3.8
**Operating system** (windows, osx, ...):
ubuntu 18.04
**Issue**:
Command given in Migration Guide (1.10 to 2.0, Response selectors section) does not work.
```
rasa data convert responses --data {SOURCE_DIR} --out={TARGET_DIR}
```

**Error (including full traceback)**:
```
usage: rasa data convert [-h] [-v] [-vv] [--quiet] {nlu,nlg,core,config} ...
rasa data convert: error: invalid choice: 'responses' (choose from 'nlu', 'nlg', 'core', 'config')
```

**Command or request that led to error**:
```
rasa data convert responses

```
This is probably only an error in the docs :)

**Comment by wochinge** [comment]
@kaiogu Could you please try with Rasa 2.1? This command was just added then (cc @m-vdb )

**Comment by kaiogu** [comment]
@wochinge Yeah I just figured that out myself and came here to close the issue 😅 

I was looking in the 2.1 docs and hadn't realized that there would be changes in the migration to an older version.
