### ISSUE TITLE
document how to connect to external NLU

### ISSUE THREAD

**Issue by wochinge** [RasaHQ/rasa#7376]
While it's still supported by the code, [this](https://legacy-docs.rasa.com/docs/core/server/#connecting-rasa-nlu) is currently not documented.
This came up in [this forum post](https://forum.rasa.com/t/using-custom-nlu-with-rasa-x/21100/4).

**Comment by akelad** [comment]
@erohmensing I know we were discussing this recently, I can't remember the details of the conversation though. Does it make sense for @melindaloubser1 to look into whether this still works properly and add some docs on it?

**Comment by melindaloubser1** [comment]
Sure I can do that, I remember using that some time ago
