### ISSUE TITLE
Ignore comments in YAML files

### ISSUE THREAD

**Issue by kaiogu** [RasaHQ/rasa#7377]
**Rasa version**: 2.1.1 **Python version**: 3.8.0 **Operating system** (windows, osx, ...): ubuntu **Issue**: Comments in yaml training files raise UserWarning. According to the error message the commented out training examples are skipped, but if yaml is the new supported training data format, valid yaml comments should be safely ignored, without a warning.

**Error (including full traceback)**:

 /path/to/rasa/shared/utils/io.py:93: UserWarning: Issue found while processing 'data/nlu.yml': The item 'goodbye' contains an example that doesn't start with a '-' symbol: # - ciao
 This training example will be skipped.

**Command or request that led to error**:

 rasa train

relevant nlu training file section looks like this:

<pre>- intent: goodbye
 examples: |

*   tchüss

1.  - ciao</pre>

**Comment by sara-tagger** [comment]
Thanks for raising this issue, @koaning will get back to you about it soon✨

###### Please also check out the [docs](https://rasa.com/docs/) and the [forum](https://forum.rasa.com/) in case your issue was raised there too 🤗

**Comment by koaning** [comment]
Ah yeah. This is where yaml syntax gets tricky. Technically you've not provided a comment. 

![image](https://user-images.githubusercontent.com/1019791/100718585-cf9ce900-33bb-11eb-943f-6b9d137ff8c1.png)

The bar character is telling yaml to accept the following lines as if it is a text blob. More info [here](https://stackoverflow.com/questions/15540635/what-is-the-use-of-the-pipe-symbol-in-yaml). With that in mind this is a feature, not a bug, of the YAML syntax. 

That said, @erohmensing I *think* that we currently don't accept Yaml files like this? 

```yaml
- intent: goodbye
  examples: 
    - tchüss
    # - ciao
```

Is there a reason for that? There might be a nice feature here to not need the bar. That way comments could be used.

**Comment by kaiogu** [comment]
Good ol' It's a feature got me again :)

So you are parsing the contents of `examples` as a big string separately. What is confusing is that the contents of the string look just like valid yaml.

 I would also be interested in knowing the reason for not just using regular lists.

**Comment by erohmensing** [comment]
I believe there was a conscious decision not to accept yaml lists, but I'm not sure -- @degiz is the 2.0 yaml expert 🤓

**Comment by kisalrandy** [comment]
same issue here .. any solution?

**Comment by degiz** [comment]
> I would also be interested in knowing the reason for not just using regular lists.

One of the reasons I remember is the fact that words like `True`, `False` are interpreted as a boolean value, so that one won't be able to have a training example with a string `True` in a list.

We decided to explicitly use a string to avoid this and other possible issues.

**Comment by wochinge** [comment]
@TyDunn Do we want to do this?
