### ISSUE TITLE
Channel-specific responses for REST channel with using input_channel in post request

### ISSUE THREAD

**Issue by lilidol** [RasaHQ/rasa#7384]
**Description of Problem**: Our problem is simular to the [topic ](https://forum.rasa.com/t/channel-specific-utterances-not-working-using-rest-channel-and-set-the-input-channel-in-post-request/31648/1) **Overview of the Solution**: We would like to use one channel like Rest and have possibilities set other input_channel in body of user-message for getting channel-specific utterances.

**Examples** (if relevant): A company prefers rest protocol for interactions between systems. But sources of messages is different, with different options for displaying. eg IVR, sms, social media etc We wouldn't like to implement a lot of channels with simular code. It will be very comfortable, if we could set different input_channels (sources) in message of post request body and get different channel-specific utterances for them

**Comment by sara-tagger** [comment]
Thanks for submitting this feature request 🚀 @dakshvar22 will get back to you about it soon! ✨

**Comment by dakshvar22** [comment]
@degiz Can you please take a look at this?
