### ISSUE TITLE
Update TrainingData and TrainingDataChunk

### ISSUE THREAD

**Issue by tabergma** [RasaHQ/rasa#7393]
related to #6836 

Reorganize `TrainingData` and `TrainingDataChunk`. Currently `TrainingDataChunk` is a subclass of `TrainingData`. However, `TrainingDataChunk` should not make use of all the functionality available in `TrainingData`. Also `TrainingDataChunk` should not have responses set. It should just have `training_examples`.

Switch the inheritance (e.g. `TrainingDataChunk` is subclass of `TrainingData`) and ideally rename `TrainingData` to `FullTrainingData` (or something similar). Don't forget to add a deprecation warning for `TrainingData` as this is a public interface.

**Comment by Ghostvv** [comment]
@tabergma do you have an idea to figure out which methods are shared and which are not? E.g. which should go into super class and which should stay in `FullTrainingData`?

**Comment by tabergma** [comment]
Actually not sure about that. I guess I would go with trail and error.

**Comment by Ghostvv** [comment]
@dakshvar22 maybe you remember? 🙏

**Comment by dakshvar22** [comment]
@Ghostvv I mainly used them in this [PR](https://github.com/RasaHQ/rasa/pull/7352/files). Ones that I can remember and were useful were lazy properties like `intents`, etc. and utility methods like `filter_training_examples` and `split_nlu_examples`.
