### ISSUE TITLE
Add support for JSON to YML nlu conversion

### ISSUE THREAD

**Issue by koszta5** [RasaHQ/rasa#7401]
**Description of Problem**: Currently by looking into rasa.nlu -> convert.py only 2 supported formats are JSON and MD; but YML format seems to be the new default for everything in newer versions. Since some tools like chatito ([https://rodrigopivi.github.io/Chatito/](https://rodrigopivi.github.io/Chatito/)) generate JSON; it is beneficial to have support for 2YML conversion in rasa

**Overview of the Solution**: The code is already there - just add it to conversion script

**Comment by sara-tagger** [comment]
Thanks for submitting this feature request 🚀 @alopez will get back to you about it soon! ✨

**Comment by ancalita** [comment]
@koszta5 There is currently support for converting JSON to YML by using `rasa data convert nlu` [command](https://rasa.com/docs/rasa/command-line-interface#rasa-data-convert-nlu).
