### ISSUE TITLE
Docker image of Rasa X not getting pulled which installing via One Line Deploy Script

### ISSUE THREAD

**Issue by gaushh** [RasaHQ/rasa#7403]
**Rasa version**:

**Rasa SDK version** (if used & relevant):

**Rasa X version** (if used & relevant): 0.33.2

**Python version**:

**Operating system** (windows, osx, ...): ubuntu 18.04

**Issue**:

in ec2 instance, all pods except rasa-app pod get created successfully. 

**Error (including full traceback)**:
```
      on running command `kubectl describe pods rasa-app-pod-name`
```
![imagepullbackoff](https://user-images.githubusercontent.com/52091771/100514367-1b704800-319a-11eb-87cb-3ba10dbd0cba.PNG)

All the pods seem to work fine when Rasa X is set or 0.33.0 in an environment variable.

**Command or request that led to error**:
```
`curl -s get-rasa-x.rasa.com | sudo bash`
```

**Content of configuration file (config.yml)** (if relevant):
```yml

```

**Content of domain file (domain.yml)** (if relevant):
```yml

```

**Comment by sara-tagger** [comment]
Thanks for raising this issue, @JustinaPetr will get back to you about it soon✨

###### Please also check out the [docs](https://rasa.com/docs/) and the [forum](https://forum.rasa.com/) in case your issue was raised there too 🤗

**Comment by TyDunn** [comment]
@gaushh Please reopen this if you are still running into this issue in the latest version of Rasa X
