### ISSUE TITLE
IntentTEDPolicy: Add a parameter `tolerance` to configuration

### ISSUE THREAD

**Issue by dakshvar22** [RasaHQ/rasa#7412]
**Description of Problem**:

If we look at the distribution of similarity values predicted by `IntentTED` for a single intent, it would look something like this -

![distribution_plot](https://user-images.githubusercontent.com/8708249/100598446-bc8b0a00-3324-11eb-8546-ae8b49faa8a5.png)

The blue bars show similarity values predicted for all input trackers where the intent `install_rasa` was the positive label.
The orange bars show similarity values predicted for all input trackers where the intent `install_rasa` was the negative label.
 
Currently, the threshold is taken as the minimum value from all blue bars denoted by the red vertical line. We want this threshold value to be slightly more "flexible" which can account for cases where the threshold value and the actual predicted value at inference are extremely close. For e.g., the threshold can be - `0.11325` and the predicted value can be - `0.11322`. Such close cases did come up while evaluating the assistant on 3 different assistants and hence resulted in extra user turns flagged by `IntentTEDPolicy`.

**Overview of the Solution**:
- [ ] Add a parameter `tolerance` which can be either a floating point in `[0,1]` or one of `low`, `medium` and `high`. The idea is that depending on the value of `tolerance`, we slide the red vertical line further to the left to reduce the number of user events that the `IntentTEDPolicy` flags. Specifically, the floating point `tolerance` value would be the percentage of negative training examples that would still not be flagged. E.g. if `tolerance=0.30`, then 30% of the area of the negative-example bars (orange) would be to the right of the red line. What floating point numbers should be assigned to the `low`, `medium`, and `high` categories should be determined in a separate issue

**Blockers**:
Should be tackled after https://github.com/RasaHQ/rasa/issues/8439

**Comment by Ghostvv** [comment]
@dakshvar22 this is blocked, since it looks like it doesn't make sense to work on it until `IntentTED` is merged?

**Comment by dakshvar22** [comment]
It's one of the issues of the larger `IntentTEDPolicy` [issue](https://github.com/RasaHQ/research/issues/122). So, it needs to be picked up again once the work on it resumes. I'll un-assign myself from this for now as I don't see that happening at least in the next sprint.
