### ISSUE TITLE
Wrong credentials after installing RASA X (Docker-Compose)

### ISSUE THREAD

**Issue by konandavy** [RasaHQ/rasa#7414]
**Rasa X version**: 0.33.2

**Python version**: 3.6

**Operating system** (windows, osx, ...): Windows but im using ubunto 16.04 on a Google cloud P. Virtual machine

**Issue**: I did everything from the masterclass 9 about setting up rasa X using docker. When I go launch rasa x and put the password it says wrong credentials. I updated my password still the same issue.

**Error (including full traceback)**:
```

```

**Command or request that led to error**:
```

```

**Content of configuration file (config.yml)** (if relevant):
```yml

```

**Content of domain file (domain.yml)** (if relevant):
```yml

```

**Comment by sara-tagger** [comment]
Thanks for the issue, @ArjaanBuijk will get back to you about it soon!

###### You may find help in the [docs](https://rasa.com/docs/) and the [forum,](https://forum.rasa.com/) too 🤗

**Comment by wochinge** [comment]
@ArjaanBuijk Can you please have a look?

**Comment by ArjaanBuijk** [comment]
@konandavy ,
What is the command you use to update your password, and does it seem to finish correctly?

Can you turn on debug mode, and check the logs of the Rasa X container?

**Comment by tczekajlo** [comment]
I'm closing it because of a lack of additional information.
