### ISSUE TITLE
Lookup table doesn't support Chinese and other un-whitespace-splittable languages correctly

### ISSUE THREAD

**Issue by howl-anderson** [RasaHQ/rasa#7421]
**Rasa version**: 2.1.1

**Python version**: 3.7.6

**Operating system** (windows, osx, ...): Ubuntu 18.04.5 LTS

**Issue**:
When the user provides a lookup table, such as: 

```text
上海
北京
```

It will turn to the regex expression `(\\b上海\\b|\\b北京\\b)` eventually. 

Unfortunately, Chinese and other un-whitespace-splittable languages usually don't have whitespace inside the text, so `\\b` usually doesn't match.

### Indeed it works when there is a whitespace inside
```python
result = list(re.finditer("(\\b上海\\b|\\b北京\\b)", "明天 上海 的天气", flags=0))
result
```
it returns:
```text
[<_sre.SRE_Match object; span=(3, 5), match='上海'>]
```

### But it doesn't work when there is no whitespace inside
```python
result = list(re.finditer("(\\b上海\\b|\\b北京\\b)", "明天上海的天气", flags=0))
result
```
it returns:
```text
[]
```

I will submit a PR to fix this.

**Comment by sara-tagger** [comment]
Thanks for raising this issue, @wochinge will get back to you about it soon✨

###### Please also check out the [docs](https://rasa.com/docs/) and the [forum](https://forum.rasa.com/) in case your issue was raised there too 🤗

**Comment by wochinge** [comment]
fixed by https://github.com/RasaHQ/rasa/pull/7422

Thanks @howl-anderson 🚀
