### ISSUE TITLE
Prepare for Messenger API updates on December 16 2020

### ISSUE THREAD

**Issue by amn41** [RasaHQ/rasa#7432]
**Description of Problem**:

Received the following information from Facebook:

Documentation is [here](https://developers.facebook.com/docs/messenger-platform/europe-updates)

> As part of our continuing efforts to comply with new privacy rules in Europe, we’ll be making updates that will impact some developers and businesses that use our Messenger API. We are sharing these API updates with you so your team can prepare for them as soon as possible and provide guidance for your customers. What’s changing? Beginning December 16, 2020, several Messenger API features will be unavailable for developers and businesses in Europe, and for people in Europe who connect with businesses globally. Examples of some features that will no longer be available via Messenger API include: Some templates (e.g. Airline, Receipt) and audio/video attachments Persistent menu One-Time Notification Some templates and buttons on web (e.g. Generic, Button) There will be no impact on people’s experiences using only text and quick replies, whether automated or live agent driven. The following features will continue to be available: Sending and receiving text messages and images Get Started button Ice breakers and quick replies Generic template, button template, and media template on Android and iOS only URL button, postback button, call button on Android and iOS only Private replies, m.me links and the Message Us plugin Webview What this means for you: APIs and UI components of the Messenger platform listed above will be unavailable to businesses in Europe in all chats, and to global businesses in chats with people in Europe. Before these changes go live on December 16, we encourage you to update your experiences that could be affected by these changes – such as those powering Pages in Europe or Pages that receive a significant volume of messages from people in Europe – to use available features instead. For more details on what is changing, please refer to this developer documentation page.

**Overview of the Solution**: TBD, but we'll definitely have to update docs and potentially defaults.

**Definition of Done**:

*   [ ] Feature described the docs
*   [ ] Feature mentioned in the changlog

**Comment by nbeuchat** [comment]
If you need an unhappy Messenger API user to discuss that topic, ping me! 😂

**Comment by wochinge** [comment]
@akelad anything you know of which we still have to do?

**Comment by akelad** [comment]
I don't think anything was done for this?
