### ISSUE TITLE
KeyError: 'e2e' for SAVE_IN_E2E = server_args["e2e"] || File python3.7/site-packages/rasa/core/training/interactive.py", line 1691, in run_interactive_learning

### ISSUE THREAD

**Issue by Yattus** [RasaHQ/rasa#7433]
When I run: `python train_online.py`, I get this error:

Traceback (most recent call last):
  File "train_online.py", line 44, in <module>
    interactive.run_interactive_learning(agent)
  File "/home/alassane/Code/JimBot/chatbot-app/env/lib/python3.7/site-packages/rasa/core/training/interactive.py", line 1691, in run_interactive_learning
    SAVE_IN_E2E = server_args["e2e"]
KeyError: 'e2e'

**File train_online.py** content:
`
from __future__ import absolute_import
from __future__ import division
from __future__ import print_function
from __future__ import unicode_literals

import logging
import asyncio
from rasa.core import utils, config
from rasa.nlu import config as nlu_config
from rasa.core.train import train
from rasa.core.training import interactive
from rasa.core.interpreter import RasaNLUInterpreter
from rasa.core.utils import read_endpoints_from_path

logger = logging.getLogger(__name__)

def train_agent():
    endpoints = read_endpoints_from_path("endpoints.yml")
    #  policies = config.load("config_supervised.yml")
    #  interpreter = RasaNLUInterpreter("./models/nlu/jady/")
    #  interpreter=interpreter,
    loop = asyncio.get_event_loop()
    return loop.run_until_complete(
        train(domain_file="jady_domain.yml",
              training_resource='./data/stories_jady.yml',
              output_path="models/dialog",
              endpoints=endpoints,
              policy_config="config_supervised.yml"
              )
        )

if __name__ == '__main__':
    #  rasa.utils.configure_colored_logging(loglevel="INFO")
    logger.info("This example does not include NLU data."
                "Please specify the desired intent with a preceding '/', e.g."
                "'/greet' .")
    log = logging.getLogger('Alassane')
    log.setLevel(logging.DEBUG)

    agent = train_agent()
    interactive.run_interactive_learning(agent)
`

**Comment by sara-tagger** [comment]
Thanks for raising this issue, @amn41 will get back to you about it soon✨

###### Please also check out the [docs](https://rasa.com/docs/) and the [forum](https://forum.rasa.com/) in case your issue was raised there too 🤗

**Comment by TyDunn** [comment]
@Yattus Can you share some more details on what the problem is?
