### ISSUE TITLE
 asyncio  - Task exception was never retrieved

### ISSUE THREAD

**Issue by pawarashmitha** [RasaHQ/rasa#7437]
im using python 3.7 

 ERROR    asyncio  - Task exception was never retrieved
future: <Task finished coro=<configure_app.<locals>.run_cmdline_io() done, defined at d:\rasa\example\rasa\lib\site-packages\rasa\core\run.py:132> exception=ClientResponseError(RequestInfo(url=URL('http://localhost:5005/webhooks/rest/webhook?stream=true&token='), method='POST', headers=<CIMultiDictProxy('Host': 'localhost:5005', 'Accept': '*/*', 'Accept-Encoding': 'gzip, deflate', 'User-Agent': 'Python/3.7 aiohttp/3.6.2', 'Content-Length': '63', 'Content-Type': 'application/json')>, real_url=URL('http://localhost:5005/webhooks/rest/webhook?stream=true&token=')), (), status=404, message='Not Found', headers=<CIMultiDictProxy('Connection': 'keep-alive', 'Keep-Alive': '5', 'Access-Control-Expose-Headers': 'filename', 'Access-Control-Allow-Credentials': 'true', 'Content-Length': '53', 'Content-Type': 'text/plain; charset=utf-8')>)>
Traceback (most recent call last):
  File "d:\rasa\example\rasa\lib\site-packages\rasa\core\run.py", line 138, in run_cmdline_io
    sender_id=conversation_id,
  File "d:\rasa\example\rasa\lib\site-packages\rasa\core\channels\console.py", line 182, in record_messages
    async for response in bot_responses:
  File "d:\rasa\example\rasa\lib\site-packages\rasa\core\channels\console.py", line 135, in send_message_receive_stream
    async with session.post(url, json=payload, raise_for_status=True) as resp:
  File "d:\rasa\example\rasa\lib\site-packages\aiohttp\client.py", line 1012, in __aenter__
    self._resp = await self._coro
  File "d:\rasa\example\rasa\lib\site-packages\aiohttp\client.py", line 588, in _request
    resp.raise_for_status()
  File "d:\rasa\example\rasa\lib\site-packages\aiohttp\client_reqrep.py", line 946, in raise_for_status
    headers=self.headers)
aiohttp.client_exceptions.ClientResponseError: 404, message='Not Found', url=URL('http://localhost:5005/webhooks/rest/webhook?stream=true&token=')

**Comment by sara-tagger** [comment]
Thanks for the issue, @TyDunn will get back to you about it soon!

###### You may find help in the [docs](https://rasa.com/docs/) and the [forum,](https://forum.rasa.com/) too 🤗

**Comment by gstaxy** [comment]
I am running into the exact same issue with the same message, even on a brand new project launched with rasa init and trained once using Python 3.7.9 / Rasa  2.1.2.

**Comment by gstaxy** [comment]
I had the exact same error. After trying a few solutions, it ended up being a problem with Docker starting up automatically when I was booting my computer. Turned it off, rebooted, and problem fixed.

**Comment by TyDunn** [comment]
@pawarashmitha Does what @gstaxy describes also resolve your issue?

**Comment by alwx** [comment]
Closing this one because there is a similar one: https://github.com/RasaHQ/rasa/issues/7828

**Comment by afeefalokaishied** [comment]
use try/catch

try:
  // your code
except expression:
  return 500
