### ISSUE TITLE
make it easier to find supported python versions

### ISSUE THREAD

**Issue by amn41** [RasaHQ/rasa#7441]
**Description of Problem**:
The place I know to find our supported versions is in our [CI setup](https://github.com/RasaHQ/rasa/blob/master/.github/workflows/continous-integration.yml#L191). This should be mentioned in the installation page of the docs. 

**Definition of Done**:
- [ ] Docs updated, ideally with supported versions read dynamically from the codebase

**Comment by wochinge** [comment]
What about the labels the readme @amn41 plus also the pypi page?

**Comment by amn41** [comment]
works!
