### ISSUE TITLE
rasa x --help: wrong information

### ISSUE THREAD

**Issue by kaiogu** [RasaHQ/rasa#7445]
**Rasa version**:
```
❯ rasa --version
Rasa Version     : 2.1.2
Rasa SDK Version : 2.1.2
Rasa X Version   : 0.34.0
Python Version   : 3.8.0
Operating System : Linux-4.15.0-124-generic-x86_64-with-glibc2.10
```
**Issue**:
Starting rasa x with no `--endpoints` option still makes rasa talk to my action server.
rasa x --help informs me that the default for '--endpoints' is None.

So the default seems to actually be a 'endpoints.yml' file

**Comment by sara-tagger** [comment]
Thanks for the issue, @tmbo will get back to you about it soon!

###### You may find help in the [docs](https://rasa.com/docs/) and the [forum,](https://forum.rasa.com/) too 🤗

**Comment by erohmensing** [comment]
Good point @kaiogu! Would you like to contribute a PR to fix this?

**Comment by kaiogu** [comment]
@erohmensing Sure, I'll give it a try after the weekend.

**Comment by kaiogu** [comment]
This is most probably not the solution you want for issue #7445 , I opened just to start a discussion.
Even though the default _is_ `None`, the `endpoints.yml` file gets loaded by default in a number of occasions.
In my case, it was in `_get_credentials_and_endpoints_paths()` in `rasa/cli/x.py` which got called by` start_rasa_for_local_rasa_x()` in the same file. There are a number of occurences like this where endpoints is loaded without beeing passed in as a parameter.
This does not seem to be a critical issue, it just might confuse some people. More thought and effort would be needed to fix this properly.
