### ISSUE TITLE
Interactive story counter doesn't update

### ISSUE THREAD

**Issue by aleronupe** [RasaHQ/rasa#7462]
**Rasa version**: 2.1.1

**Python version**: Python 3.7.9

**Operating system** (windows, osx, ...): Linux

**Issue**: The number of each interactive story generated does not update between executions of the `rasa interactive ` command, because the counter used at ` _write_stories_to_file` function at `rasa/training/interactive.py` does not recognize previous interactive stories generated.

**Error (including full traceback)**:

[<span class="image-wrap" style="">![](https://user-images.githubusercontent.com/37146204/101261832-ac09d380-3718-11eb-9d4d-00526a205df5.png)</span>](https://user-images.githubusercontent.com/37146204/101261832-ac09d380-3718-11eb-9d4d-00526a205df5.png)

**Command or request that led to error**:

 rasa interactive

**Comment by sara-tagger** [comment]
Thanks for raising this issue, @kalkbrennerei will get back to you about it soon✨

###### Please also check out the [docs](https://rasa.com/docs/) and the [forum](https://forum.rasa.com/) in case your issue was raised there too 🤗

**Comment by kalkbrennerei** [comment]
Hi @aleronupe! Thanks for bringing this up and also for the details! ✨

**Comment by rafaelteodosio** [comment]
Hi, I would like to know if someone is already working on this issue and if it still relevant
