### ISSUE TITLE
Form extracts other slots for entities that were already "used up" by the requested slot

### ISSUE THREAD

**Issue by nbeuchat** [RasaHQ/rasa#7467]
**Rasa version**: 2.1.1

**Rasa SDK version**: 2.1.1

**Python version**: 3.7.9

**Operating system**: Ubuntu

**Issue**: When two slots use the same entity in their slot mapping, both are extracted because of the `extract_other_slots` method of the `FormAction`. The problem I am encountering is that a single entity can lead to two slots being filled with the same value. This is problematic for generic entities like `number` from Duckling.

For example, I have a `number_bedrooms` and a `lease_length` slots to be filled. When requested the `lease_length` slot, users often answer with a single number like _2_ (ie: meaning 2 months if we ask about the lease length). However, both `validate_lease_length` and `validate_number_bedrooms` will be triggered.

In this case, a value of _2_ is valid for both fields. We can work around that by checking which slot was being requested. However, my feeling is that an entity mapping the requested slot should not be used to fill other slots.

As a side note, I think the documentation does not cover implicitly extracting other slots. I learned about it while debugging ![](/images/icons/emoticons/wink.png)

**Command or request that led to error**: When `requested_slot = lease_length`, user enter the text: `2`

**Content of domain file (domain.yml)**:

<pre>forms:
 form_preferences:
 lease_length:

*   entity: duration
     type: from_entity
*   entity: number
     type: from_entity
     number_bedrooms:
*   entity: bedrooms_count
     type: from_entity
*   entity: number
     type: from_entity
     ...</pre>

**Comment by sara-tagger** [comment]
Thanks for the issue, @joejuzl will get back to you about it soon!

###### You may find help in the [docs](https://rasa.com/docs/) and the [forum,](https://forum.rasa.com/) too 🤗

**Comment by joejuzl** [comment]
Hi @nbeuchat 

Just to clarify, you have:

- a form with two slots filled from the same entity
- a custom `FormValidationAction` with `validate_` methods for each slot
- and when one of the slots is requested by the form, and the user provides input, both validate methods get called?

I can't seem to replicate this.

Also the [docs](https://rasa.com/docs/rasa/forms#validating-form-input) say:
> By default Rasa Open Source only validates if any slot was filled after requesting a slot.

So this would be unintended behaviour...

**Comment by nbeuchat** [comment]
Hi @joejuzl, thanks for your answer and apologies for my late reply. 

> Just to clarify, you have:
> 
> - a form with two slots filled from the same entity
> - a custom FormValidationAction with validate_ methods for each slot
> - and when one of the slots is requested by the form, and the user provides input, both validate methods get called?
That's right! 

I tested again today and I still have this issue. I am asking about the `lease_length` for which I answer with the message: _12_ 

This message is parsed as:

```
{
    "text": "12",
    "intent": {
        "id": 3646831439835479699,
        "name": "inform",
        "confidence": 0.996927619
    },
    "entities": [
        {
            "start": 0,
            "end": 2,
            "text": "12",
            "value": 12,
            "confidence": 1.0,
            "additional_info": {
                "value": 12,
                "type": "value"
            },
            "entity": "number",
            "extractor": "DucklingEntityExtractor"
        }
    ],
```

The `validate_lease_length` is correctly called but the `validate_target_price` is also called. I need to look into it more as it only happens for this specific slot (while others also have the same entity mapping). I'll try to come up with a reproducible example.

**Comment by nbeuchat** [comment]
@wochinge this bug is actually worse than I initially thought :-/ It creates very strange side effects like slots that were already filled being emptied or filled with a wrong value. 

I thought I could use a workaround by simply checking `tracker.get_slot(REQUESTED_SLOT) == my_slot_name` in the validation function of that slot and having a different logic there. The logic works fine but getting this slot back to its original value does not work. 

The problem is that the tracker has already set the slot to its new value, even before validation!

If I put a breakpoint within the validation function of the slot that we are not asking for, I see that `tracker.slots` and `tracker.current_slot_values` already hold the new slot value. If I return `{}` or `None`, it still overrides whatever I had in my slot before. 

My thought that I could at least return the "old" value like 
```
return {"number_bedrooms": tracker.get_slot("number_bedrooms")}
```
but it has already been set to the value that the user answered for the `lease_length`.

**Comment by nbeuchat** [comment]
You get stories like this:
```
  - slot_was_set:
    - preferences_target_price: '3600'
  - slot_was_set:
    - requested_slot: preferences_move_in_date
  - slot_was_set:
    - preferences_move_in_date:
        min: '2021-02-09'
        max: null
  - slot_was_set:
    - preferences_target_price: '2021-03-01T00:00:00.000-05:00'  # this was not validated 
  - slot_was_set:
    - requested_slot: preferences_lease_length
```

Although `validate_preferences_target_price` returned `None`! 

In the `validate_preferences_target_price`, I see:

```
pprint(tracker.current_slot_values())
{
 'preferences_move_in_date': '2021-03-01T00:00:00.000-05:00',
 'preferences_target_price': '2021-03-01T00:00:00.000-05:00',  # this should not be there already as it has not been validated yet
...


pprint(tracker.slots_to_validate())
{'preferences_move_in_date': '2021-03-01T00:00:00.000-05:00',
 'preferences_target_price': '2021-03-01T00:00:00.000-05:00'}  # that's expected as we want to validate it
```

**Comment by nbeuchat** [comment]
@wochinge Could you please point me to the part of the code where I could try to fix that? Our forms are completely broken because of this so I need to fix this urgently. Thank you!

**Comment by nbeuchat** [comment]
I found a workaround for this but it's not super nice. Basically, if I am validating a slot that is _not_ requested and that nothing is found, I return the last value of that slot that I can find in the tracker (so I need to iterate the tracker backward until I find the second time that slot event is set, as the last one is set before validation). 

I'm using this to get the previous value:
```
def get_previous_slot_value_from_tracker(tracker: Tracker, slot: Text) -> Optional[Any]:
    is_first = True
    for event in reversed(tracker.events):
        if event["event"] == "slot" and event["name"] == slot:
            if is_first:
                is_first = False
            else:
                return event["value"]
        if event["event"] == "session_started":
            return None
```

Not that great but that does the job for now! :-)

**Comment by wochinge** [comment]
> If I put a breakpoint within the validation function of the slot that we are not asking for, I see that tracker.slots and tracker.current_slot_values already hold the new slot value. If I return {} or None, it still overrides whatever I had in my slot before.

Mhm, we should add a helper function to the SDK which let's you retrieve the old value quickly 👍🏻 

> Not that great but that does the job for now! :-)

Yep, that's what I would have suggested 💯 

@Ghostvv As you've implemented this originally: I agree with @nbeuchat that it's weird that slot candidates for non-requested slots can reset slots which have already been set (the line doing this is [this one](https://github.com/RasaHQ/rasa/blob/015e36a9823c55fd8cb82982e3af5ee2fafec491/rasa/core/actions/forms.py#L473)) - what was the use case behind this back then when implementing it?

In my opinion we should do something like this:
* keep on extracting other slots
* If not requested slots are validated and set to `None` we reset it's value not to `None`, but it's previous value

**Comment by nbeuchat** [comment]
> Mhm, we should add a helper function to the SDK which let's you retrieve the old value quickly 👍🏻

That'd be quite handy! 

> In my opinion we should do something like this:
> 
> - keep on extracting other slots
> - If not requested slots are validated and set to None we reset it's value not to None, but it's previous value

That'd be awesome! What would be also great is to have the option of customizing which entity type (or intent) should match for extra slots. If I take the example of budget question, it is fine to extract the budget using just numbers if we are requesting this slot. However, I would only fill the budget when requesting another slot if it is an `amount-of-money` entity or `budget` entity (as retrieved by DIET).

**Comment by wochinge** [comment]
> that would be also great is to have the option of customizing which entity type (or intent) should match for extra slots. 

Nice suggestion! Wondering if this doesn't add too much complexity to the domain file and might be rather handled in a custom action 🤔 How would you encode that information in the `domian.yml`?

**Comment by nbeuchat** [comment]
> Nice suggestion! Wondering if this doesn't add too much complexity to the domain file and might be rather handled in a custom action thinking How would you encode that information in the domian.yml?

Good point! 

I guess the issue with the custom action is that we might need to know why the extra slot was extracted (ie: because of which entity/intent) in order to determine if we accept or reject it. 

```
forms:
  restaurant_form:
    cuisine:
      - type: from_entity
        entity: cuisine
    num_people:
      - type: from_entity
        entity: number
        extract_from_others: false
      - type: from_entity
        entity: people_count
        extract_from_others: true
```
With `extract_from_others` being `true` by default (I guess). I'm not great at naming things but something like that would be explicit and allow you to fine-tune which entities/intents are "global" and which are specific to the question asked. 

Also, I think it should be made very clear what the default behavior is somewhere in the docs. It was a bit of a surprise discovery that this cool feature existed for me ;-)

**Comment by wochinge** [comment]
> I guess the issue with the custom action is that we might need to know why the extra slot was extracted

Hm, that would be resolvable by a helper in the SDK which looks at the event itself, no? I like your `extract_from_others` suggestion! @samsucik @ArjaanBuijk What do you think?

**Comment by samsucik** [comment]
I agree that the current behaviour is not 100% intuitive, though, frankly, I think that the biggest issue is the [lack of] documentation, not the feature itself.

This being said, I agree with the concept of `extract_from_others`. But I'd go back to
> If not requested slots are validated and set to `None` we reset its value not to `None`, but it's previous value

I would make this configurable. I wouldn't dare to change this behaviour globally. Why? Users sometimes (often?) don't answer the question the form asks, but rather add something or correct their answer to the previous question. By not updating the slot when the new value is invalid, we decide to take the user's update/correction/continuation less seriously and I don't think it's right.

What would a configurable way be in my mind? Well, having something like `extract_from_others`, but with three possible values: `always`, `valid_only`, `never`. This may sound terrible to @wochinge because we're replacing bool values with obscure strings, but we could also map `always`<->`true` and `never`<->`false` 🤔

**Comment by wochinge** [comment]
I actually find the string more explicit and hence preferable :-D Just for my understanding:
* `valid_only` -> that's like the current behavior but instead of setting to `None` we would set it to the previous value?
* `never`: What @nbeuchat needs
* `always`: That's the current behavior?

**Comment by samsucik** [comment]
@wochinge exactly 🙂

**Comment by ArjaanBuijk** [comment]
I like it a lot as well to introduce an `extract_from_others = [valid_only, never, always] `

**Comment by wavymazy** [comment]
Encountered the same issue described by @nbeuchat, a while a go, but since the use case the company was working on was very specific I fixed it by going through custom actions. 
That being said I also really like the concept of `extract_from_others` for each slot mapping in the domain file !

**Comment by DiWang4data** [comment]
i want to ask when i set some form entity,how can i reset the to None

**Comment by dgradwell-ams** [comment]
Was there no resolution to this? I am having somewhat the same problem.  I have two slots:

a. fullName
b. emailOrPhone

1. User enters name for (a)
2. User enters something that is interpreted as a name (perhaps a malformed email) for (b)
3. Input from (2) overwrites what the user put in (a) and continues asking for (b)

I've confirmed that this is happening in the `FormAction` in **core** in `extract_other_slots` and I have not been able to come up with an elegant way to stop it from happening.

**Comment by dgradwell-ams** [comment]
OK, I just noticed this: https://github.com/RasaHQ/rasa/blob/main/examples/formbot/domain.yml#L53
This seems like an undocumented way to declare slot mappings under the slot definitions rather than the form, if I'm not mistaken. I may play around with this to see if it works.
