### ISSUE TITLE
Support for Python 3.9

### ISSUE THREAD

**Issue by staticdev** [RasaHQ/rasa#7473]
**Description of Problem**: Python 3.9 is the current stable version of Python.

**Overview of the Solution**: add official support.

**Examples** (if relevant): -

**Blockers** (if relevant): -

**Definition of Done**:
- [ ] Run current tests on 3.9
- [ ] Feature described the docs
- [ ] Feature mentioned in the changelog

**Comment by sara-tagger** [comment]
Thanks for submitting this feature request 🚀 @melindaloubser1 will get back to you about it soon! ✨

**Comment by melindaloubser1** [comment]
Python 3.9 support will only be added once [tensorflow](https://github.com/tensorflow/tensorflow/issues/44485) and other libraries support it in a standard release.

**Comment by melindaloubser1** [comment]
I'm closing it for now because it will go stale after a while; feel free to reopen once dependencies support 3.9

**Comment by staticdev** [comment]
@WorkAlexGahr I think there was no Tensorflow release yet after latest fix for 3.9. But I also think would be adequate to leave this open to have it planned since it is now getting very close.

**Comment by matteoredaelli** [comment]
Hello Any news? About tensoflow I read from https://www.tensorflow.org/install/pip :   "Python 3.9 support requires TensorFlow 2.5 or later. "

Regards
Matteo

**Comment by staticdev** [comment]
@wochinge can you reopen that for us?

**Comment by wochinge** [comment]
We have [this issue](https://github.com/RasaHQ/rasa/issues/8762) for it now 👍🏻 There are currently some bugs in TensorFlow which prevent us from upgrading. We'll probably add 3.9 support in Rasa Open Source 3.0
