### ISSUE TITLE
Investigate NLU Interpreters with Regards to spaCy

### ISSUE THREAD

**Issue by koaning** [RasaHQ/rasa#7481]
A bug on [rasalit](https://github.com/RasaHQ/rasalit/issues/28) prompted me to investigate how our interpreters work. 

It seems there are two methods of retrieving an interpreter. 

```python
from rasa.cli.utils import get_validated_path
from rasa.model import get_model, get_model_subdirectories
from rasa.nlu.model import Interpreter

def load_interpreter_a(model_dir, model):
    path_str = str(pathlib.Path(model_dir) / model)
    model = get_validated_path(path_str, "model")
    model_path = get_model(model)
    _, nlu_model = get_model_subdirectories(model_path)
    return Interpreter.load(nlu_model)


from rasa.core.interpreter import RasaNLUInterpreter

def load_interpreter_b(model_dir, model):
    path_str = str(pathlib.Path(model_dir) / model)
    model = get_validated_path(path_str, "model")
    model_path = get_model(model)
    _, nlu_model = get_model_subdirectories(model_path)
    return RasaNLUInterpreter(nlu_model)
```

It seems that we have an `Interpreter` and a `RasaNLUInterpreter`. It's not 100% clear to me what the difference is but after trying it out I noticed that the former will cause an error if a SpacyEntityExtractor is used. It would be good to investigate the subtle difference and document it properly for two reasons. 

1. We have *a lot* of interpreters at this point and there might be some consolidation possible. If nothing else the difference should be made clear in the docstring. 
2. I might need to rewrite [a tutorial](https://blog.rasa.com/evaluating-rasa-nlu-models-in-jupyter/) before other community members hit their head.

**Comment by tabergma** [comment]
Related Slack thread: https://rasa-hq.slack.com/archives/C8LEHMTAM/p1607430725036700

**Comment by JEM-Mosig** [comment]
Should this really be classified as a bug?

**Comment by tabergma** [comment]
@JEM-Mosig As far as I understood @koaning the `SpacyEntityExtractor` does not work during prediction in some scenarios. In that case it would be a bug. @koaning can you maybe describe in more detail in what kind of situations the `SpacyEntityExtractor` does not work and maybe give a minimal example to reproduce the error? Thanks.

**Comment by Ghostvv** [comment]
I don't think its is the research issue, I moved it to `Production` board

**Comment by wochinge** [comment]
> can you maybe describe in more detail in what kind of situations the SpacyEntityExtractor does not work and maybe give a minimal example to reproduce the error? T

@koaning Could you please elaborate on Tanja's questions? Would be very helpful for addressing this.

**Comment by koaning** [comment]
I tried again and I could not reproduce anymore. So I'm closing this issue.
