### ISSUE TITLE
Add Team ID to Metadata for Slack Channel

### ISSUE THREAD

**Issue by kearnsw** [RasaHQ/rasa#7487]
**Description of Problem**: The current slack channel does not extract the team id from the slack event into the UserMessage metadata.

First, it is currently not possible to know from which workspace a request is coming. This is an issue when it is required by any custom code in the action server.

Second, I think this also raises a larger issue that the sender_id as currently defined may not be unique across multiple workspaces. As discussed in [this forum post](https://forum.rasa.com/t/how-to-pass-metadata-in-post-request-and-then-extract-it/15092/2), we may need to update the sender_id to be a concatenation of the user_id and the team_id.

**Overview of the Solution**: The initial pull request will address the first issue of adding the team_id to the metadata using the get_metadata function of the slack channel. **The solution to the second issue of the uniqueness of the sender_id requires further discussion.**

**Comment by sara-tagger** [comment]
Thanks for submitting this feature request 🚀 @joejuzl will get back to you about it soon! ✨
