### ISSUE TITLE
Add note in documentation that JWT authentication is only for the HTTP API 

### ISSUE THREAD

**Issue by b-quachtran** [RasaHQ/rasa#7489]
**Description of Problem**:

Add note in documentation that JWT authentication is only for the HTTP API and not for any of the channel connectors

**Definition of Done**:

- [ ] Feature described the docs

**Comment by akelad** [comment]
@b-quachtran do you plan on doing this still?

**Comment by b-quachtran** [comment]
Sorry forgot to follow up about this, but yes I'm planning on taking this on
