### ISSUE TITLE
How to add Spacy Japanese model into Rasa Docker

### ISSUE THREAD

**Issue by jnoelvictorino** [RasaHQ/rasa#7492]
**Description of Problem**:
I want to add the Spacy Japanese pre-trained model into Rasa Docker. 
I already posted in the [forum](https://forum.rasa.com/t/how-to-add-spacy-ja-model-into-rasa-docker/37637) a few days ago.
I also followed the suggestion on how to extend the Rasa Docker image from this [thread](https://forum.rasa.com/t/extending-rasa-docker-for-a-new-spacy-language-model/34350). But the Docker image size is too big ~2.39GB.

**Overview of the Solution**:

Instead of extending `rasa/rasa:2.1.2-spacy-en`, I cloned this repository to build a new image.
Then, I updated two files and added `./docker/Dockerfile_pretrained_embeddings_spacy_en_ja`:
- `pyproject.toml` to update `spacy` to `2.3.2`
- `poetry.lock`

**Definition of Done**:
- [ ] Include Japanese pipeline
- [ ] Feature described into the docs
- [ ] Validation if there are any possible solutions or this is the best way to extend the base image to include another pretrained model

**Comment by sara-tagger** [comment]
Thanks for submitting this feature request 🚀 @tabergma will get back to you about it soon! ✨

**Comment by wochinge** [comment]
I came back to you in the forum @jnoelvictorino
