### ISSUE TITLE
Docs are not clear about SocketIO connection

### ISSUE THREAD

**Issue by gijswobben** [RasaHQ/rasa#7508]
**Description of Problem**: The docs are not very clear on how to use SocketIO. They state:

> Restart your Rasa X or Rasa Open Source server to make the new channel endpoint available to receive messages. You can then send messages to [http://:/socketio](http://:/socketio), replacing the host and port with the appropriate values from your running Rasa X or Rasa Open Source server.

However, you should connect the SocketIO client on `http://<host>:<port>/` (without `socketio`). Furthermore there is no description in the docs for how to use the events to create a session.

**Overview of the Solution**: Fix the error in the docs (as mentioned above) and add information about the events (and flow of events):

*   `session_request`
*   `session_confirm`

**Comment by sara-tagger** [comment]
Thanks for submitting this feature request 🚀 @rctatman will get back to you about it soon! ✨
