### ISSUE TITLE
Rasa `make install` fails

### ISSUE THREAD

**Issue by JEM-Mosig** [RasaHQ/rasa#7511]
**Rasa version**:
Latest master (I cannot install), commit fb09c6b13d386a3805f4b385a63995127dec961e

**Rasa SDK version** (if used & relevant):

**Rasa X version** (if used & relevant):

**Python version**:
3.7.0

**Operating system** (windows, osx, ...):
Operating System : Linux-4.15.0-126-generic-x86_64-with-glibc2.10 (Ubuntu)

**Issue**:
Rasa installation fails.

**Error (including full traceback)**:
```
(temp) jem-mosig:rasa/ (master) $ make install                          [12:50:32]
poetry run python -m pip install -U pip
Requirement already satisfied: pip in /home/jem-mosig/miniconda3/envs/temp/lib/python3.7/site-packages (20.3.1)
poetry install
The lock file might not be compatible with the current version of Poetry.
Upgrade Poetry to ensure the lock file is read properly or, alternatively, regenerate the lock file with the `poetry lock` command.
Installing dependencies from lock file
Warning: The lock file is not up to date with the latest changes in pyproject.toml. You may be getting outdated dependencies. Run update to update them.

[SolverProblemError]
The current project's Python requirement (3.7.0) is not compatible with some of the required packages Python requirement:
  - dataclasses requires Python >=3.6, <3.7

Because no versions of transformers match >=2.4,<2.11.0 || >2.11.0,<2.12
 and transformers (2.11.0) depends on dataclasses (*), transformers (>=2.4,<2.12) requires dataclasses (*).
Because dataclasses (0.8) requires Python >=3.6, <3.7
 and no versions of dataclasses match !=0.8, dataclasses is forbidden.
Thus, transformers is forbidden.
So, because rasa depends on transformers (>=2.4,<2.12), version solving failed.
Makefile:54: recipe for target 'install' failed
make: *** [install] Error 1
```

**Command or request that led to error**:
```
make install
```

**Comment by samsucik** [comment]
I also get this error (using Python 3.8.5).

**Comment by JEM-Mosig** [comment]
@samsucik It looks like we have to upgrade poetry now. So `pip install -U poetry`. After that, I still get the error above with python 3.8.5, but not with 3.8.0. In the latter case the installation fails due to SSL or connection errors.

**Comment by JEM-Mosig** [comment]
Now it's also there for 3.8.0 :exploding_head:

**Comment by JEM-Mosig** [comment]
Ah, actually something reset my poetry version to the outdated one. So its just the ConnectionError now.

**Comment by JEM-Mosig** [comment]
Now it works. No idea why. I installed poetry with conda this time, but also pulled master.
