### ISSUE TITLE
Enforce type annotations in the CI

### ISSUE THREAD

**Issue by joejuzl** [RasaHQ/rasa#7513]
Type annotations on method definitions are part of our code conventions.
We are seeing lots of PR review comments suggesting adding type annotations.
We should add it to the CI so it is automated.
This will reduce PR review burden, and help maintain our code quality.

Thoughts:
- Could be done either using `mypy` or `pylint`
- Should only be run on code diffs so we can incorporate it incrementally.

**Comment by tczekajlo** [comment]
I'm not sure if the issue should be in the infra board cc @m-vdb @mprazz

**Comment by wochinge** [comment]
* `--disallow-untyped-calls`: 50 issues
* `--disallow-untyped-defs`: 299 issues
* `--disallow-incomplete-defs`: 247 issues

**Comment by joejuzl** [comment]
@wochinge can this be closed now? Or are there more to enforce still?
