### ISSUE TITLE
Don't allow finetuning core with previously unseen labels that were in the domain.

### ISSUE THREAD

**Issue by joejuzl** [RasaHQ/rasa#7519]
**Rasa version**: 2.2

**Issue**:

**Steps to reproduce:**

*   We have labels that are in the domain but not in any stories.
*   We run `rasa train core`
*   We add a story with one of the aforementioned labels.
*   We run `rasa train core --finetune`

**Expected result:** Exit gracefully.

**Actual result:** Allows the model to be finetuned.

**Comment by dakshvar22** [comment]
@m-vdb I think this issue is very much a feature related issue and should stay in Enable's inbox?
