### ISSUE TITLE
Slack channel silently dropping long-running custom actions.

### ISSUE THREAD

**Issue by nathan-chappell** [RasaHQ/rasa#7525]
**Rasa version**: 2.2.0a1

**Rasa SDK version** (if used & relevant): Not relevant

**Rasa X version** (if used & relevant): Not used

**Python version**: 3.8.6

**Operating system** (windows, osx, ...): Linux-4.15.0-47-generic-x86_64-with-glibc2.2.5

**Issue**: I have a custom action that takes some time to complete. It takes long enough that slack will close its connection with the rasa server, and send a retry request. When this happens, the action fails silently.

**Error (including full traceback)**: The only clue as to the error comes from opening up the debugger in the middle of the server, e.g. calling `breakpoint()` [here](https://github.com/RasaHQ/rasa/blob/28f3ad70b3006147150223b9f1c347a3a0c2e5e3/rasa/core/channels/slack.py#L525). Then, if you wait a moment, then try to step over the `return await self.process_message(...`, you will get a stack trace and a line which reads:

 asyncio.exceptions.CancelledError

**Command or request that led to error**: Described above.

**Content of configuration file (config.yml)** (if relevant): Not relevant - other than having a slack channel configured.

**Content of domain file (domain.yml)** (if relevant): Not relevant

**NOTE** I have a fix, and intend to discuss further issues not directly related to this in comments to my PR.

**Comment by sara-tagger** [comment]
Thanks for the issue, @samsucik will get back to you about it soon!

###### You may find help in the [docs](https://rasa.com/docs/) and the [forum,](https://forum.rasa.com/) too 🤗

**Comment by wochinge** [comment]
@samsucik Could you validate this problem?

**Comment by samsucik** [comment]
@wochinge in all honesty I'm quite busy and want to close some existing issues & projects first... Do you think that someone else could have a look?

**Comment by wochinge** [comment]
Mhm, you can ask in the product-support channel but I guess everyone is busy atm.

**Comment by melindaloubser1** [comment]
@nathan-chappell  re. 
>I have a fix, and intend to discuss further issues not directly related to this in comments to my PR.
what is your fix? Is it something that would be generally applicable, or was it only for a specific use case?

**Comment by nathan-chappell** [comment]
@melindaloubser1 Yea, I put in a PR a few months ago, with a (perhaps lengthy) discussion of the issue.  Bottom line is that there is an `await` in the code that shouldn't be there, there should just be the creation of a task on the event loop.  It's debatable whether or not this is really a Rasa issue, as basically one connection is closing an unrelated connection, throwing a silent error.

https://github.com/RasaHQ/rasa/pull/7526/files

**Comment by melindaloubser1** [comment]
Thanks for the link - looks like no one noticed the PR so far, sorry about that.
