### ISSUE TITLE
data schema linting enhancement

### ISSUE THREAD

**Issue by wj-Mcat** [RasaHQ/rasa#7530]
**Description of Problem**: After reading the source code, I find that many data schema in rasa is `Dict`, which is not familier with developer also in developing. So, that there is a lot of `constants` defination. Eg:

<pre>return {
 "sender_id": self.sender_id,
 "slots": self.current_slot_values(),
 "latest_message": self.latest_message.parse_data,
 "latest_event_time": latest_event_time,
 FOLLOWUP_ACTION: self.followup_action,
 "paused": self.is_paused(),
 "events": _events,
 "latest_input_channel": self.get_latest_input_channel(),
 ACTIVE_LOOP: self.active_loop,
 "latest_action": self.latest_action,
 "latest_action_name": self.latest_action_name,
 }</pre>

**Overview of the Solution**: `dataclasses` is a great tools that can wrap a class to dict type, which run well in rasa. And this is good for developer to detect attribute during code with rasa, and it will be more rubost too. It's my cons, thanks for your review.

**Examples** (if relevant):

<pre>@dataclass
 class CurrentState:
 sender_id: Text
 slots: List<span class="error">[Slot]</span>
 last_message: Message
 last_event_time: datetime
 events: List<span class="error">[Event]</span>
 ...</pre>

OK, I think it will be a great feature for rasa if supported.

**Comment by wj-Mcat** [comment]
There are a lot of `type-less` definition in rasa, I wonder it will be harder when the rasa is stronger.

**Comment by sara-tagger** [comment]
Thanks for submitting this feature request 🚀 @tabergma will get back to you about it soon! ✨
