### ISSUE TITLE
Encoding issues on entity values when parsing nlu json data to md using rasa cli

### ISSUE THREAD

**Issue by JBrettas** [RasaHQ/rasa#7541]
**Rasa version**: 2.1.2

**Python version**: 3.8.5

**Operating system** (windows, osx, ...): Windows 10

**Issue**: I am currently working on brazilian portuguese data that presents instances as this:

 {
 "text": "qto custa o cartao de vcs?",
 "intent": "cartao_valor",
 "attention_case": false,
 "entities": [

 { "raw": "cartao", "value": "Cartão", "entity": "payment_method", "start": 12, "end": 18, "synth": "FALSE" } 

 ]
 }

I tried then using the following rasa cli command line (I tried different values for the language parameter but with no effect):

`rasa data convert nlu -f md --data=./data/nlu.json --out=./data/nlu_converted.md -l pt`

I get a generated file with the same instance represented as:

1.  1.  cartao_valor

*   qto custa o <span class="error">[cartao]</span> {"entity": "payment_method", "value": "Cart\u00e3o"} 

     de vcs?

It seems that every normalized value/synonym with special characters like 'ç', 'ã' or 'é' had its encoding not preserved during the parsing proccess.

**Error (including full traceback)**:

1.  no error were presented besides the output with encoding issues

**Command or request that led to error**:

 rasa data convert nlu -f md --data=./data/nlu.json --out=./data/nlu_converted.md -l pt

**Comment by sara-tagger** [comment]
Thanks for raising this issue, @tmbo will get back to you about it soon✨

###### Please also check out the [docs](https://rasa.com/docs/) and the [forum](https://forum.rasa.com/) in case your issue was raised there too 🤗
