### ISSUE TITLE
Profile TF Graph

### ISSUE THREAD

**Issue by dakshvar22** [RasaHQ/rasa#7556]
Training TED on end to end stories increases the training time of TED quite considerably. Things to try -

*   [ ] We should use TF Profiler to investigate which layers are exactly the bottleneck layers.
*   [ ] Check if setting number of transformer layers to 0 for `TEXT` and `ACTION_TEXT` helps to speed it up.

**Comment by Ghostvv** [comment]
we hope that RasaHQ/rasa#7438 will enable us to do that

**Comment by Ghostvv** [comment]
DIET also needs to be profiled
