### ISSUE TITLE
Fallback and rules does not works in case of dynamic form implementation if form is active

### ISSUE THREAD

**Issue by kaustuk** [RasaHQ/rasa#7557]
**Rasa version**: 2.1.3

**Rasa SDK version** (if used & relevant): 2.1.2

**Rasa X version** (if used & relevant): 0.34.0

**Python version**: 3.7.9

**Operating system** (windows, osx, ...): Darwin-19.6.0-x86_64-i386-64bit

**Issue**:

So basically the issue is if we have Fallback and rules for some intent in bot and we have implemented the a dynamic form (i.e overwrite `required_slots` method and adding some required slot base on some condition met) in this case if the fallback/rules is triggered when form is active then this rules and fallback action/utterance will not be triggered.
**P.S**: Also attaching the tar of the bot which can help in reproduce it [rasa_init_bot.tar.gz](https://github.com/RasaHQ/rasa/files/5696868/rasa_init_bot.tar.gz)

**Step to reproduce the error**:
1. Download above tar in local
2. Run `rasa train`
3. Wait for model is trained. After model is trained we will explore 2 cases

**Case 1**: Fail case if dynamic form is implemented
1. Bring rasa action server: `rasa run actions`
2. Bring rasa shell: `rasa shell`
3. Interact with bot as follow screenshot: 
<img width="835" alt="Screenshot 2020-12-15 at 21 32 24" src="https://user-images.githubusercontent.com/16715570/102239588-07a83e00-3f1d-11eb-9d48-71a0ec7311c7.png">

4. Here the action `action_test_1` is not being triggered

**Case 2**: Normal case without dynamic form implemented
1. comment the `required_slots` function in `actions/actions.py` file
2. Bring rasa action server up again: `rasa run actions`
3. Bring rasa shell: `rasa shell`
4. Interact with bot as follow screenshot: 
<img width="743" alt="Screenshot 2020-12-15 at 21 35 17" src="https://user-images.githubusercontent.com/16715570/102240027-6ec5f280-3f1d-11eb-8c94-f64b5db0f6a1.png">

5. Here the action `action_test_1` being triggered

**Comment by kaustuk** [comment]
Once we figure up this is the bug. I would like to work on this. I have figured out the solution for it we can discuss it once bug is confirm

**Comment by sara-tagger** [comment]
Thanks for raising this issue, @kalkbrennerei will get back to you about it soon✨

###### Please also check out the [docs](https://rasa.com/docs/) and the [forum](https://forum.rasa.com/) in case your issue was raised there too 🤗

**Comment by nbeuchat** [comment]
@kaustuk We have the same issue and I have opened a bug report on Rasa SDK: https://github.com/RasaHQ/rasa-sdk/issues/370
@wochinge is already on it :muscle: :rocket:

**Comment by wochinge** [comment]
Thanks for bringing this up @kaustuk . Both issues seem to be the same thing 👍🏻
