### ISSUE TITLE
Allow rules to be explicitely not applied at the start of a conversation with conversation_start: false

### ISSUE THREAD

**Issue by nbeuchat** [RasaHQ/rasa#7569]
**Description of Problem**: When a rule with `conversation_start: true` is set, it can be conflicting with rules that are intended to be applied anywhere except at the beginning of a conversation. The issue is that the second rule cannot be explicitly set to not be applied at the beginning of a conversation and hence results in a conflict when checked for conflicts.

**Overview of the Solution**: Ensure that rules with `conversation_start: false` are **not** applied at the beginning of a conversation. Therefore, the stories/rules validation would also consider them as not conflicting.

**Examples**: These two rules should be able to deal with the same intent at the start and at other points in the conversation.

 _Rule 1: start_ 

*   rule: Search at the start of conversation
     conversation_start: true
     steps:
*   intent: ask_search
*   action: action_greet
*   action: action_introduce_form_preferences
     wait_for_user_input: false

 _Rule 2: anywhere else_ 

*   rule: Activate preferences form when searching
     conversation_start: false
     condition:
*   slot_was_set:
*   preferences_filled: null
     steps:
*   intent: ask_search
*   action: action_introduce_form_preferences
     wait_for_user_input: false

See the conversation here as well: [https://github.com/RasaHQ/rasa/issues/7552#issuecomment-746362538](https://github.com/RasaHQ/rasa/issues/7552#issuecomment-746362538)

**Definition of Done**:

*   [ ] Tests are added
*   [ ] Feature described the docs
*   [ ] Feature mentioned in the changlog

**Comment by Ghostvv** [comment]
we need to distinguish between `conversation_start: false` and nothing (`conversation_start: null`) when reading rules, before it can be implemented in the `RulePolicy`
