### ISSUE TITLE
No response for the consecutive user utterance

### ISSUE THREAD

**Issue by shreeraj04** [RasaHQ/rasa#7598]
RASA Version: 2.3.1

Python version: 3.7.2

**Operating system** (windows, osx, ...): Windows Server 2012 R2 Standard

**Issue**:
Below is the training data in yaml format:
nlu:
  - intent: greet
    examples: |-
      - hey
      - hello
      - hi
      - hello there
      - good morning
      - hey there
      - let's go
      - hey dude
      - goodmorning
      - goodevening
      - good afternoon
  - intent: goodbye
    examples: |-
      - good afternoon
      - cu
      - good by
      - cee you later
       - good night
      - have a nice day
      - see you around
      - bye bye
      - see you later
  - intent: mood_great
    examples: |-
      - perfect
      - great
      - amazing
      - I am going to save the world
      - super stoked
      - extremely good
      - so so perfect
      - so good
      - so perfect
  - intent: affirm
    examples: |-
      - yes
      - y
      - indeed
      - of course
      - that sounds good
      - correct
  - intent: deny
    examples: |-
      - no
      - n
      - never
      - I don't think so
      - don't like that
      - no way
      - not really
  - intent: mood_unhappy
    examples: |-
      - my day was horrible
      - I am sad
      - I don't feel very well
      - I am disappointed
      - super sad
      - I'm so sad
      - sad
      - very sad
      - unhappy
      - not good
      - not very good
  - intent: ocm
    examples: |-
      - what is ocm
      - explain ocm
      - omni channel management
      - omni channel manager
      - can you tell me about OCM
      - OCM
  - intent: ask_tetherfi
    examples: |-
      - I want to know about tetherfi
      - tetherfi
      - can you tell me about tetherfi
      - please tell me about tetherfi
      - what is tetherfi?
  - intent: ask_tetherfi_openings
    examples: |-
      - I am looking for job in the company
      - Is there any openings in company
      - job offers
      - current openings
      - looking for a job in the company
      - looking for work in the company
      - any opening in your company for web development?
      - any opening in your company for developers?
stories:
  - story: happy path
    steps:
      - intent: greet
      - action: utter_greet
      - intent: mood_great
      - action: utter_happy
  - story: ask ocm
    steps:
      - intent: ocm
      - action: utter_ocm
      - intent: greet
      - action: utter_greet
  - story: sad path
    steps:
      - intent: greet
      - action: utter_greet
      - intent: mood_unhappy
      - action: utter_cheer_up
      - intent: affirm
      - action: utter_happy
  - story: job offeres
    steps:
      - intent: ask_tetherfi_openings
      - action: utter_openings
      - intent: greet
      - action: utter_greet
  - story: tetherfi opening
    steps:
      - intent: greet
      - action: utter_greet
      - intent: ask_tetherfi
      - action: utter_tetherfi
      - intent: ask_tetherfi_openings
      - action: utter_openings
responses:
  utter_greet:
    - text: Hey! How are you?
  utter_goodbye:
    - text: Bye
  utter_happy:
    - text: Great, carry on!
  utter_cheer_up:
    - text: If you are happy I am also happy.
  utter_did_that_help:
    - text: Did that help you?
  utter_tetherfi:
    - text: Tetherfi is leading company in telecommunication field based out of
        Singapore. We have branches in Singapore, India, Sri Lanka, US and
        Australia
  utter_openings:
    - text: Yes, we do have few openings in C#, JAVA, Python, ML/AI. We don't see the
        number of experience, instead we see how well you know the concepts.
        Email your resume at careers@tetherfi.com . All the best!!
  utter_ocm:
    - text: OCM is one of our main product where all the configuration of other
        products with respect to the agent and supervisor can be made
language: en
pipeline: 
- name: WhitespaceTokenizer
policies:
  - name: MemoizationPolicy
  - name: TEDPolicy
    max_history: 5
    epochs: 10
intents:
  - greet
  - goodbye
  - mood_great
  - affirm
  - deny
  - mood_unhappy
  - ocm
  - ask_tetherfi
  - ask_tetherfi_openings

After training the data, I ran "Rasa shell" where i could get the response for any input only once. Consecutive requests will not give any response. Not sure where is the issue.

![image](https://user-images.githubusercontent.com/15680777/102618032-15013a80-4160-11eb-8aae-75487824c130.png)

![image](https://user-images.githubusercontent.com/15680777/102618069-21859300-4160-11eb-9aa5-18ab97cad338.png)

Please let me know if any issues in my training data or how to resolve. Thanks

**Comment by shreeraj04** [comment]
When i parse the same data I get the intent ranking
![image](https://user-images.githubusercontent.com/15680777/102620838-aecae680-4164-11eb-8ced-170a308baf19.png)

But the response template is null
![image](https://user-images.githubusercontent.com/15680777/102620864-b8ece500-4164-11eb-8123-8820abb19120.png)

**Comment by sara-tagger** [comment]
Thanks for the issue, @mvielkind will get back to you about it soon!

###### You may find help in the [docs](https://rasa.com/docs/) and the [forum,](https://forum.rasa.com/) too 🤗

**Comment by wochinge** [comment]
Please ask questions in the [forum](https://forum.rasa.com). It seems as you didn't provide a valid configuration for the NLU pipeline.
