### ISSUE TITLE
Run all time-absorbing unit tests in a separate job

### ISSUE THREAD

**Issue by tczekajlo** [RasaHQ/rasa#7618]
All unit tests that require more time (e.g. train model) should be run as a separate job in order to short time that we need to pass all tests. All unit tests that require more time (e.g. they train a model) should be run in a separate job in order to short waiting time to pass tests.

@mprazz Can we identify all unit tests that are time-absorbing?

**Comment by mprazz** [comment]
I'm not sure I fully understand the logic of what we want to do here 🤔  Even if we isolate the longer tests in their own job, we still need to wait for them to complete in order to merge PRs. Or are we considering re-runs as time-consuming (same argument as we made for separating jobs in `rasa-x`)?

**Comment by tczekajlo** [comment]
> I'm not sure I fully understand the logic of what we want to do here 🤔 Even if we isolate the longer tests in their own job, we still need to wait for them to complete in order to merge PRs. Or are we considering re-runs as time-consuming (same argument as we made for separating jobs in `rasa-x`)?

The problem that I'm trying to address by the issue is "what to do with all tests that take time". One of the ideas is to run them separately as a scheduled workflow, but first, we'd have to identify all time-absorbing tests and be sure that we can run them separately. 

It's also a raw idea, I'm open to other suggestions/ideas.

**Comment by mprazz** [comment]
According to the meeting we had this week, it seems the tests that take long are the ones that train models. Leaving this issue on hold for now while we figure out more details on the training times like we spoke about during the meeting.

**Comment by tczekajlo** [comment]
It was addressed in the different issue.
