### ISSUE TITLE
Auto-fill not respected by FormAction

### ISSUE THREAD

**Issue by kearnsw** [RasaHQ/rasa#7624]
**Rasa version**: 2.2.2

**Python version**: 3.6

**OS**: Mac

**Issue**:

*   The form action `extract_other_slots` is not respecting the `auto_fill` property of the slots in the domain file. So they are being overwritten.

There is a bug report on the forum here and also here: [https://forum.rasa.com/t/slots-overwritten-in-forms-with-duckling-entities/38197/5](https://forum.rasa.com/t/slots-overwritten-in-forms-with-duckling-entities/38197/5)

I was able to resolve the issue through a modification of this function. Will open a pull request.

**Comment by sara-tagger** [comment]
Thanks for raising this issue, @m-vdb will get back to you about it soon✨

###### Please also check out the [docs](https://rasa.com/docs/) and the [forum](https://forum.rasa.com/) in case your issue was raised there too 🤗

**Comment by m-vdb** [comment]
👋🏻 hey @kearnsw thanks for your bug report. I see that you've created a branch on your fork a few weeks back. Do you still plan on opening a PR?

**Comment by kearnsw** [comment]
@m-vdb , yes the pull request is #7625.
