### ISSUE TITLE
Typos in documentation

### ISSUE THREAD

**Issue by alexyuwen** [RasaHQ/rasa#7627]
I don't know if this is the right place to raise this issue, but I noticed two errors in the Rasa docs where it explains the `buttons` parameter of the dispatcher's `utter_message` method (link below).  For one, `message` is misspelled as `messsage`.  Also, the code block is missing a close parentheses at the very end.  So, the corrected example would be:
```
dispatcher.utter_message(buttons = [
                {"payload": "/affirm", "title": "Yes"},
                {"payload": "/deny", "title": "No"},
            ])
```

https://rasa.com/docs/action-server/sdk-dispatcher/#collectingdispatcherutter_message

**Comment by sara-tagger** [comment]
Thanks for raising this issue, @alopez will get back to you about it soon✨

###### Please also check out the [docs](https://rasa.com/docs/) and the [forum](https://forum.rasa.com/) in case your issue was raised there too 🤗

**Comment by zyberg2091** [comment]
can i solve this issue?

**Comment by melindaloubser1** [comment]
thanks for reporting! It's fixed in this PR on rasa SDK (there's also a linked issue there, which is why I'm closing this one): https://github.com/RasaHQ/rasa-sdk/issues/379
