### ISSUE TITLE
Rasa X - forever no response when chatting

### ISSUE THREAD

**Issue by laopisai** [RasaHQ/rasa#7629]
**Rasa version**: 2.1.2

**Rasa SDK version** (if used & relevant):

**Rasa X version** (if used & relevant): 0.34.0

**Python version**: 3.8.5

**Operating system** (windows, osx, ...): Ubuntu 20.04

**Issue**: When chatting to bot via Rasa X, the interface forever showing three dots.

I tried to deploy Rasa X manually using docker-compose and also using the provided install.sh. Both ends with the same result The initial training data is generated using `rasa init`

Firefox Network Monitor shows that rasa x continuously calling

 GET | [http://playground/api/conversations/02d64d82716744deb6f90bd7d1c7218c?format=full_conversation&since=0&environment=production](http://playground/api/conversations/02d64d82716744deb6f90bd7d1c7218c?format=full_conversation&since=0&environment=production)

with the following response payload

 {"sender_id":"02d64d82716744deb6f90bd7d1c7218c","slots":{},"latest_message":{"intent":{},"entities":[],"text":null,"message_id":null,"metadata":{}},"latest_event_time":null,"followup_action":"action_listen","paused":false,"events":[],"latest_input_channel":null,"active_loop":{},"latest_action":{},"latest_action_name":null}

When I chat via the share link the payload is instead

 {"version":"0.34.0","status":"failure","message":"Client for conversation_id 'e6a9cb7c226a457f87233236f7fae74d' could not be found","reason":"ClientNotFound","details":{},"help":null,"code":404}

**Error (including full traceback)**: No obvious error observed but in rasa-production's log, it shows that the intent classification is working

 rasa-production_1 | 2020-12-23 08:09:03 DEBUG rasa.core.tracker_store - Can't retrieve tracker matching sender id 'fd50491a3ec94694ad59bc5da3d92847' from SQL storage. Returning `None` instead.
 rasa-production_1 | 2020-12-23 08:09:03 DEBUG rasa.core.tracker_store - Can't retrieve tracker matching sender id 'fd50491a3ec94694ad59bc5da3d92847' from SQL storage. Returning `None` instead.
 rasa-production_1 | 2020-12-23 08:09:03 DEBUG rasa.core.tracker_store - Tracker with sender_id 'fd50491a3ec94694ad59bc5da3d92847' stored to database
 rasa-production_1 | 2020-12-23 08:09:03 DEBUG rasa.core.processor - Starting a new session for conversation ID 'fd50491a3ec94694ad59bc5da3d92847'.
 rasa-production_1 | 2020-12-23 08:09:03 DEBUG rasa.core.processor - Policy prediction ended with events '[]'.
 rasa-production_1 | 2020-12-23 08:09:03 DEBUG rasa.core.processor - Action 'action_session_start' ended with events '<span class="error">[
 <rasa.shared.core.events.sessionstarted object at 0x7f046c3412d0>
  , 
  <rasa.shared.core.events.actionexecuted object at 0x7f046c145390>
   ]
  </rasa.shared.core.events.actionexecuted>
 </rasa.shared.core.events.sessionstarted></span>'.
 rasa-production_1 | 2020-12-23 08:09:03 DEBUG rasa.core.lock_store - Issuing ticket for conversation 'fd50491a3ec94694ad59bc5da3d92847'.
 rasa-production_1 | 2020-12-23 08:09:03 DEBUG rasa.core.lock_store - Acquiring lock for conversation 'fd50491a3ec94694ad59bc5da3d92847'.
 rasa-production_1 | 2020-12-23 08:09:03 DEBUG rasa.core.lock_store - Acquired lock for conversation 'fd50491a3ec94694ad59bc5da3d92847'.
 rasa-production_1 | 2020-12-23 08:09:03 DEBUG rasa.core.tracker_store - Can't retrieve tracker matching sender id 'fd50491a3ec94694ad59bc5da3d92847' from SQL storage. Returning `None` instead.
 rasa-production_1 | 2020-12-23 08:09:03 DEBUG rasa.core.tracker_store - Can't retrieve tracker matching sender id 'fd50491a3ec94694ad59bc5da3d92847' from SQL storage. Returning `None` instead.
 rasa-production_1 | 2020-12-23 08:09:03 DEBUG rasa.core.tracker_store - Tracker with sender_id 'fd50491a3ec94694ad59bc5da3d92847' stored to database
 rasa-production_1 | 2020-12-23 08:09:03 DEBUG rasa.core.tracker_store - Can't retrieve tracker matching sender id 'fd50491a3ec94694ad59bc5da3d92847' from SQL storage. Returning `None` instead.
 rasa-production_1 | 2020-12-23 08:09:03 DEBUG rasa.core.tracker_store - Tracker with sender_id 'fd50491a3ec94694ad59bc5da3d92847' stored to database
 rasa-production_1 | 2020-12-23 08:09:03 DEBUG rasa.core.lock_store - Deleted lock for conversation 'fd50491a3ec94694ad59bc5da3d92847'.
 rasa-production_1 | 2020-12-23 08:09:07 DEBUG rasa.core.channels.rasa_chat - Fetched JWT public key from URL 'http://rasa-x:5002/api/version' for algorithm 'RS256':
 rasa-production_1 | ----~~BEGIN PUBLIC KEY~~----
 rasa-production_1 | REMOVED
 rasa-production_1 | REMOVED
 rasa-production_1 | REMOVED
 rasa-production_1 | REMOVED
 rasa-production_1 | REMOVED
 rasa-production_1 | REMOVED
 rasa-production_1 | REMOVED
 rasa-production_1 | ----~~END PUBLIC KEY~~----
 rasa-production_1 | 
 rasa-production_1 | 2020-12-23 08:09:07 DEBUG rasa.core.lock_store - Issuing ticket for conversation 'fd50491a3ec94694ad59bc5da3d92847'.
 rasa-production_1 | 2020-12-23 08:09:07 DEBUG rasa.core.lock_store - Acquiring lock for conversation 'fd50491a3ec94694ad59bc5da3d92847'.
 rasa-production_1 | 2020-12-23 08:09:07 DEBUG rasa.core.lock_store - Acquired lock for conversation 'fd50491a3ec94694ad59bc5da3d92847'.
 rasa-production_1 | 2020-12-23 08:09:07 DEBUG rasa.core.tracker_store - Recreating tracker from sender id 'fd50491a3ec94694ad59bc5da3d92847'
 rasa-production_1 | 2020-12-23 08:09:07 DEBUG rasa.nlu.classifiers.diet_classifier - There is no trained model for 'ResponseSelector': The component is either not trained or didn't receive enough training data.
 rasa-production_1 | 2020-12-23 08:09:07 DEBUG rasa.nlu.selectors.response_selector - Adding following selector key to message property: default
 rasa-production_1 | 2020-12-23 08:09:07 DEBUG rasa.core.processor - Received user message 'hi' with intent '

 {'id': 9049028199040845406, 'name': 'greet', 'confidence': 0.999953031539917} 

' and entities '[]'
 rasa-production_1 | 2020-12-23 08:09:07 DEBUG rasa.core.processor - Logged UserUtterance - tracker now has 3 events.
 rasa-production_1 | 2020-12-23 08:09:07 DEBUG rasa.core.policies.memoization - Current tracker state:
 rasa-production_1 | <span class="error">[state 1]</span> user intent: greet | previous action name: action_listen
 rasa-production_1 | 2020-12-23 08:09:07 DEBUG rasa.core.policies.memoization - There is a memorised next action 'utter_greet'
 rasa-production_1 | 2020-12-23 08:09:07 DEBUG rasa.core.policies.rule_policy - Current tracker state:
 rasa-production_1 | <span class="error">[state 1]</span> user intent: greet | previous action name: action_listen
 rasa-production_1 | 2020-12-23 08:09:07 DEBUG rasa.core.policies.rule_policy - There is no applicable rule.
 rasa-production_1 | 2020-12-23 08:09:07 DEBUG rasa.core.policies.ensemble - Predicted next action using policy_0_MemoizationPolicy.
 rasa-production_1 | 2020-12-23 08:09:07 DEBUG rasa.core.processor - Predicted next action 'utter_greet' with confidence 1.00.
 rasa-production_1 | 2020-12-23 08:09:07 DEBUG rasa.core.processor - Policy prediction ended with events '[]'.
 rasa-production_1 | 2020-12-23 08:09:07 DEBUG rasa.core.processor - Action 'utter_greet' ended with events '[BotUttered('Hey! How are you?', 

 {"elements": null, "quick_replies": null, "buttons": null, "attachment": null, "image": null, "custom": null} 

, 

 {"template_name": "utter_greet"} 

, 1608710947.453702)]'.
 rasa-production_1 | 2020-12-23 08:09:07 DEBUG rasa.core.policies.memoization - Current tracker state:
 rasa-production_1 | <span class="error">[state 1]</span> user intent: greet | previous action name: action_listen
 rasa-production_1 | <span class="error">[state 2]</span> user intent: greet | previous action name: utter_greet
 rasa-production_1 | 2020-12-23 08:09:07 DEBUG rasa.core.policies.memoization - There is a memorised next action 'action_listen'
 rasa-production_1 | 2020-12-23 08:09:07 DEBUG rasa.core.policies.rule_policy - Current tracker state:
 rasa-production_1 | <span class="error">[state 1]</span> user intent: greet | previous action name: action_listen
 rasa-production_1 | <span class="error">[state 2]</span> user intent: greet | previous action name: utter_greet
 rasa-production_1 | 2020-12-23 08:09:07 DEBUG rasa.core.policies.rule_policy - There is no applicable rule.
 rasa-production_1 | 2020-12-23 08:09:07 DEBUG rasa.core.policies.ensemble - Predicted next action using policy_0_MemoizationPolicy.
 rasa-production_1 | 2020-12-23 08:09:07 DEBUG rasa.core.processor - Predicted next action 'action_listen' with confidence 1.00.
 rasa-production_1 | 2020-12-23 08:09:07 DEBUG rasa.core.processor - Policy prediction ended with events '[]'.
 rasa-production_1 | 2020-12-23 08:09:07 DEBUG rasa.core.processor - Action 'action_listen' ended with events '[]'.
 rasa-production_1 | 2020-12-23 08:09:07 DEBUG rasa.core.tracker_store - Recreating tracker from sender id 'fd50491a3ec94694ad59bc5da3d92847'
 rasa-production_1 | 2020-12-23 08:09:07 DEBUG rasa.core.tracker_store - Tracker with sender_id 'fd50491a3ec94694ad59bc5da3d92847' stored to database
 rasa-production_1 | 2020-12-23 08:09:07 DEBUG rasa.core.lock_store - Deleted lock for conversation 'fd50491a3ec94694ad59bc5da3d92847'.

**Command or request that led to error**:

 Talking to the bot

**Content of configuration file (config.yml)** (if relevant): default as generated by `rasa init`

**Content of domain file (domain.yml)** (if relevant): default as generated by `rasa init`

**Comment by sara-tagger** [comment]
Thanks for the issue, @alopez will get back to you about it soon!

###### You may find help in the [docs](https://rasa.com/docs/) and the [forum,](https://forum.rasa.com/) too 🤗

**Comment by JessiBrix** [comment]
I have the same problem on Ubuntu 18.04 with Rasa X 0.35.0 and Rasa 2.2.5, I used the quick-install script. I can't use my chatbot..

**Comment by LeaFish** [comment]
I had the same problem. I've tried to switch over many versions, but there's still no change. Local mode works. In addition, I try to use the webhooks interface, but the conversation content still can't be saved, but the local mode can. We hope to announce the solution as soon as possible.RASA_X_VERSION=0.35.0，RASA_VERSION=2.2.4，RASA_SDK_VERSION=2.2.0

**Comment by ptrkdy** [comment]
I'm having the same issue, I noticed that the rasa-production_1 container hands off the conversation to rabbit via the pika event to exchange "rasa-exchange" on host "rabbit" and then nothing seems to come back and the chat UI stalls with the triple dot return.

`rasa-production_1  | 2021-02-03 01:32:22 DEBUG    rasa.core.brokers.pika  - Published Pika events to exchange 'rasa-exchange' on host 'rabbit':`

This is all stock docker-compose from the rasa X docs. Everything seems to work until you start to talk to the bot, then no reply. Any update would be appreciated! Thx

**Comment by tczekajlo** [comment]
@edmacovaz How this issue is related to the infrastructure?

**Comment by edmacovaz** [comment]
@tczekajlo I think this is another mistake on my part, I'll send it to enable 👍🏻

**Comment by sarhugo** [comment]
I'm having the same issue when installed Rasa 1.10.x and Rasa X 0.32.x via docker on ubuntu 20.04

**Comment by sarhugo** [comment]
I found what was the problem in my case, I share the solution in case it helps:

endpoints.yml format was wrong. _Queues should now be specified as a list in the endpoints.yml event broker config under a new key queues_. (from rasa version 1.9 changelog)

```yaml
event_broker:
  type: "pika"
  url: ${RABBITMQ_HOST}
  username: ${RABBITMQ_USERNAME}
  password: ${RABBITMQ_PASSWORD}
  queues:
  - ${RABBITMQ_QUEUE}
```

**Comment by pankajbsn** [comment]
I am having same issue with the latest version as of 09-sept-2021. Any plans of resolving this issue. Rasa x is unusable because of this. I tried quick install, helm install. But no help.

**Comment by nuosishizi** [comment]
Yes, I can’t train the robot

> 我在 2021 年 9 月 9 日的最新版本中遇到了同样的问题。解决此问题的任何计划。因此，Rasa x 无法使用。我试过快速安装，掌舵安装。但没有帮助。
