### ISSUE TITLE
rasa data validate error, schema issue

### ISSUE THREAD

**Issue by rgstephens** [RasaHQ/rasa#7632]
`rasa data validate` fails on the Sara/rasa-demo `config.yml` with the error: `You have provided an invalid key `token_pattern` for component 'CountVectorsFeaturizer' in your pipeline. Valid options for 'CountVectorsFeaturizer' are:`

Sara uses `token_pattern` [here](https://github.com/RasaHQ/rasa-demo/blob/338aafeb1c54dc6d1b431fcc5022f466941acaee/config.yml#L8).

The [docs](https://rasa.com/docs/rasa/components/#countvectorsfeaturizer) do not state that `CountVectorsFeaturizer` supports `token_pattern` but it looks like this is supported in the [code](https://github.com/RasaHQ/rasa/blob/b555a5d49bb4d5787fa9e18aa8bc1783cb62a1a2/rasa/nlu/featurizers/sparse_featurizer/count_vectors_featurizer.py#L818).

**Rasa version**: 2.2.2

**Comment by koernerfelicia** [comment]
Hi @rgstephens, we decided not to expose this parameter as we're trying to keep tokenization-related parameters in the tokenizers. The Sara parameters are actually the default for `"analyzer":"word"`. I'll make a new issue on the Sara repo to change this.

**Comment by adamfeher64** [comment]
similar error throws on command `rasa train` on docker image `rasa/rasa:2.4.0-full` but instead of `token_pattern` its `model_confidence`.

**Comment by koernerfelicia** [comment]
@adamfeher64 can you share your config file?
