### ISSUE TITLE
Having trouble creating a new project

### ISSUE THREAD

**Issue by xettrisomeman** [RasaHQ/rasa#7633]
**Rasa version**:2.2.2

**Rasa SDK version** : 2.2.0

**Python version**: 3.8.0

**Operating system** :windows 

**Issue**: ```AttributeError: module 'tensorflow.python.keras.utils.tf_utils' has no attribute 'smart_cond' ```

**Comment by sara-tagger** [comment]
Thanks for the issue, @yennycheung will get back to you about it soon!

###### You may find help in the [docs](https://rasa.com/docs/) and the [forum,](https://forum.rasa.com/) too 🤗

**Comment by melindaloubser1** [comment]
what version of tensorflow do you have installed?

**Comment by xettrisomeman** [comment]
> 
> 
> what version of tensorflow do you have installed? this sounds like #7634 which is due to using too low a tensorflow version

> I have the latest tensorflow(2.4.0) version, but the error is still showing when i try to create a new project .

**Comment by melindaloubser1** [comment]
In that case it might be too high a version - the required version is listed here https://github.com/RasaHQ/rasa/blob/b555a5d49bb4d5787fa9e18aa8bc1783cb62a1a2/pyproject.toml#L114
so up to 2.3. It  might be something else, but worth trying.

**Comment by syw2014** [comment]
Have the same error,
Rasa Version     : 2.2.2
Rasa SDK Version : 2.2.0
Rasa X Version   : None
Python Version   : 3.6.5
Operating System : Linux-5.8.0-34-generic-x86_64-with-debian-bullseye-sid
Tensorflow-GPU:2.4.0
---------
Why I install tf2.4 because tf2.3 can not run with cuda on my 3060ti, so i have to install the latest version

**Comment by wochinge** [comment]
Closing as TensorFlow 2.4 is currently not supported.
