### ISSUE TITLE
AttributeError: module 'tensorflow._api.v1.config' has no attribute 'list_physical_devices' after running rasa init

### ISSUE THREAD

**Issue by Mathias-Godwin** [RasaHQ/rasa#7634]
Rasa version:2.2.2

Rasa SDK version : 2.2.0

Python version: 3.7.9

Operating system :windows

**error**:
c:\users\gwinivac\.conda\envs\chatboty\lib\importlib\_bootstrap.py:219: RuntimeWarning: greenlet.greenlet size changed, may indicate binary incompatibility. Expected 144 from C header, got 152 from PyObject
  return f(*args, **kwds)
c:\users\gwinivac\.conda\envs\chatboty\lib\importlib\_bootstrap.py:219: RuntimeWarning: greenlet.greenlet size changed, may indicate binary incompatibility. Expected 144 from C header, got 152 from PyObject
  return f(*args, **kwds)
c:\users\gwinivac\.conda\envs\chatboty\lib\importlib\_bootstrap.py:219: RuntimeWarning: greenlet.greenlet size changed, may indicate binary incompatibility. Expected 144 from C header, got 152 from PyObject
  return f(*args, **kwds)
c:\users\gwinivac\.conda\envs\chatboty\lib\importlib\_bootstrap.py:219: RuntimeWarning: greenlet.greenlet size changed, may indicate binary incompatibility. Expected 144 from C header, got 152 from PyObject
  return f(*args, **kwds)
Traceback (most recent call last):
  File "c:\users\gwinivac\.conda\envs\chatboty\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\users\gwinivac\.conda\envs\chatboty\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\Gwinivac\.conda\envs\chatboty\Scripts\rasa.exe\__main__.py", line 7, in <module>
  File "c:\users\gwinivac\.conda\envs\chatboty\lib\site-packages\rasa\__main__.py", line 115, in main
    rasa.telemetry.initialize_error_reporting()
  File "c:\users\gwinivac\.conda\envs\chatboty\lib\site-packages\rasa\telemetry.py", line 230, in decorated
    return f(*args, **kwargs)
  File "c:\users\gwinivac\.conda\envs\chatboty\lib\site-packages\rasa\telemetry.py", line 651, in initialize_error_reporting
    default_context = _default_context_fields()
  File "c:\users\gwinivac\.conda\envs\chatboty\lib\site-packages\rasa\telemetry.py", line 480, in _default_context_fields
    "gpu": len(tf.config.list_physical_devices("GPU")),
  File "c:\users\gwinivac\.conda\envs\chatboty\lib\site-packages\tensorflow_core\python\util\module_wrapper.py", line 193, in __getattr__
    attr = getattr(self._tfmw_wrapped_module, name)
AttributeError: module 'tensorflow._api.v1.config' has no attribute 'list_physical_devices'

**Comment by sara-tagger** [comment]
Thanks for the issue, @b-quachtran will get back to you about it soon!

###### You may find help in the [docs](https://rasa.com/docs/) and the [forum,](https://forum.rasa.com/) too 🤗

**Comment by Mathias-Godwin** [comment]
> Thanks for the issue, @b-quachtran will get back to you about it soon!
> 
> ###### You may find help in the [docs](https://rasa.com/docs/) and the [forum,](https://forum.rasa.com/) too 🤗

I've got a wrap around that, what I did was:
1. i figured out that the attribute has been moved to "tensorflow._api.v1.config.experiment"
2. I edit the "__init__.py" by : 
      from tensorflow._api.v1.config import experiment
      list_physical_devices = experiment.list_physical_devices
3. then I saved it and Viola! it worked (for Tesorflow version==1.15.0)

**Comment by melindaloubser1** [comment]
I think the underlying issue here is your tensorflow version - you should have tensorflow 2 since https://github.com/RasaHQ/rasa/pull/5266

**Comment by siddheshm14** [comment]
> > Thanks for the issue, @b-quachtran will get back to you about it soon!
> > ###### You may find help in the [docs](https://rasa.com/docs/) and the [forum,](https://forum.rasa.com/) too 🤗
> 
> I've got a wrap around that, what I did was:
> 
> 1. i figured out that the attribute has been moved to "tensorflow._api.v1.config.experiment"
> 2. I edit the "**init**.py" by :
>    from tensorflow._api.v1.config import experiment
>    list_physical_devices = experiment.list_physical_devices
> 3. then I saved it and Viola! it worked (for Tesorflow version==1.15.0)

**Comment by siddheshm14** [comment]
Can you tell me which init.py file was changed, I mean in which folder init.py was changed I am not able to get solve this issue
