### ISSUE TITLE
Rasa Telegram Webhook doesnt accept command line certificate

### ISSUE THREAD

**Issue by vulcantheterrible** [RasaHQ/rasa#7637]
**Rasa version**:
2.2.2

**Rasa SDK version** (if used & relevant):
2.2.0

**Rasa X version** (if used & relevant):

**Python version**:
3.7.3

**Operating system** (windows, osx, ...):
Linux-4.19.0-13-cloud-amd64-x86_64-with-debian-10.7

**Issue**:

The telegram webhook doesnt seem to have an ssl option in the credentials.yml configuration and doesn't accept ssl cert parameters on the command line. 

I generate my own SSL cert like so:
`
    openssl req \
        -newkey rsa:2048 \
        -sha256 \
        -nodes \
        -keyout $CERT_PATH.key \
        -x509 \
        -days 365 \
        -out \
        $CERT_PATH.pem \
        -subj "/C=SG/ST=Singapore/L=Singapore/O=MyCompany/CN=$PUBLIC_IP"
`

I launch the rasa server like so:
`
rasa run --ssl-certificate $CERT_PATH.pem --ssl-keyfile $CERT_PATH.key -p 8443
`

Notice the SSL parameter up there

If I look for status from Telegram for the webhook I get this: 

curl https://api.telegram.org/bot$BOT_TOKEN/getWebhookInfo
```
{"ok":true,"result":{"url":"https://<my_ip>:<my_port>/webhooks/telegram/webhook","has_custom_certificate":false,"pending_update_count":0,"last_error_date":1609035063,"last_error_message":"Connection refused","max_connections":40,"ip_address":"<my_ip>"}}
```

Notice **has_custom_certificate = false**

**Error (including full traceback)**:
There is no relevant error in the log. But when I curl for webhook info from Telegram, it reports an SSL error:

curl https://api.telegram.org/bot$BOT_TOKEN/getWebhookInfo
```
{"ok":true,"result":{"url":"https://<my_ip>:<my_port>/webhooks/telegram/webhook","has_custom_certificate":false,"pending_update_count":13,"last_error_date":1609034814,"last_error_message":"SSL error {error:1416F086:SSL routines:tls_process_server_certificate:certificate verify failed}","max_connections":40,"ip_address":40,"ip_address":"<my_ip>"}}
```

**Command or request that led to error**:

A normal run of rasa causes the error above. 
However, if I run curl with the setWebHook explicitly after Rasa is launched, the webhook works correctly then on.

So if I do this, henceforth rasa runs fine: 
```
    curl https://api.telegram.org/bot$BOT_TOKEN/setWebhook \
        -F "url=https://$PUBLIC_IP:8443/webhooks/telegram/webhook" \
        -F "certificate=@$CERT_PATH.pem"
```

callng the getWebHookinfo command gives me **"has_custom_certificate":true** and it all works fine there on.

**Content of configuration file (config.yml)** (if relevant):
My config (credentials.yml) looks like this for telegram:

```yml
telegram:
  access_token: "my_access_token"
  verify: "my_bot"
  webhook_url: "https://<my_ip>:<my_port>/webhooks/telegram/webhook"
```

**Content of domain file (domain.yml)** (if relevant):
```yml

```

**Comment by sara-tagger** [comment]
Thanks for raising this issue, @b-quachtran will get back to you about it soon✨

###### Please also check out the [docs](https://rasa.com/docs/) and the [forum](https://forum.rasa.com/) in case your issue was raised there too 🤗

**Comment by b-quachtran** [comment]
Hi @vulcantheterrible, thanks for bringing this up! The Telegram channel connector doesn't have certificate support at the moment but I've created a feature enhancement request for this in the meantime: https://github.com/RasaHQ/rasa/issues/7649.
