### ISSUE TITLE
quick jump from rasa shell to rasa interactive

### ISSUE THREAD

**Issue by shubhvachher** [RasaHQ/rasa#7641]
**Description of Problem**:

During testing with `rasa shell` when you encounter a problem it would be easy to have a quick `\interactive` command (like `\stop` is) to jump into the `rasa interactive` mode with the actions taken by the bot after the last user input being re-run but in interactive mode.

**Blockers** (if relevant):

Well, `rasa interactive` generally retrains the model. So, that needs to be flagged OFF or run with the same model run when using `rasa shell` (maybe from the same path, or by keeping a copy in temp? ALSO, remember to delete any temp files created, Rasa isn't great at that for moments when people use the `ctrl-c` keyboard interrupt, as is OFTEN used in `rasa shell`).

**Definition of Done**:

**Comment by shubhvachher** [comment]
Starting up `rasa interactive` and going through the intital stages of setup till the main problem area is a huge obstruction to using the tool. Being able to `rasa shell` and jump into `interactive` could help with that case as well.

*An important design condition (imo) is* : When going from shell to interactive, we need to clarify from which user input we should start the "debugging process". This can be a simple arrow key selector like those already implemented in `rasa interactive` intent selection, or response selection using buttons on command line, for example.

**Comment by sara-tagger** [comment]
Thanks for submitting this feature request 🚀 @kalkbrennerei will get back to you about it soon! ✨

**Comment by amn41** [comment]
hi @shubham3582  - you can already do this in Rasa X, btw. Go to the ['Talk to your bot' screen](https://rasa.com/docs/rasa-x/user-guide/share-assistant#talk-to-your-bot) and use the pencil icon to switch between chatting and interactive learning. 

>  When going from shell to interactive, we need to clarify from which user input we should start the "debugging process"

I think this is much easier in a UI, hence why Rasa X is probably the better place for this.
