### ISSUE TITLE
How to extract extra slots in rasa 2.2 other than those asked in domain

### ISSUE THREAD

**Issue by LEAGUEDORA** [RasaHQ/rasa#7643]
**Rasa version**:  2.2

**Rasa SDK version** (if used & relevant):

**Rasa X version** (if used & relevant):

**Python version**:3.7.9

**Operating system** (windows, osx, ...): win 10

**Issue**:

Not asking other slots other than those asked in domain

**Error (including full traceback)**:
```

```

**Command or request that led to error**:
```

```

**Content of configuration file (config.yml)** (if relevant):
```yml

```

**Content of domain file (domain.yml)** (if relevant):
```yml

```

**Comment by sara-tagger** [comment]
Thanks for the issue, @dakshvar22 will get back to you about it soon!

###### You may find help in the [docs](https://rasa.com/docs/) and the [forum,](https://forum.rasa.com/) too 🤗

**Comment by LEAGUEDORA** [comment]
@sara-tagger  why is no one responding to this issue

**Comment by TyDunn** [comment]
Hi @LEAGUEDORA. Can you please try asking this on the [Rasa forum](http://forum.rasa.com/)? It would help if you could provide more of a description of your problem and maybe even an example when you do :)
