### ISSUE TITLE
training takes too long on Rasa 2.2.2

### ISSUE THREAD

**Issue by iszainab** [RasaHQ/rasa#7657]
Training a model on RASA 2.2.2 takes way too long, it takes (a little more than ) 20 minutes to only initialise the training. This is a huge downside, could someone please look into this.
It did not take this long on RASA 1.10 with the exact same training data.

**Comment by wochinge** [comment]
@iszainab Can you please add more details about used environment (CPUs, GPUs, RAM, etc.) and the amount of training data you're using + the used model configuration?

**Comment by Ghostvv** [comment]
@wochinge it might not be research issue. It might be related to https://github.com/RasaHQ/rasa/issues/7272

**Comment by Ghostvv** [comment]
>  it takes (a little more than ) 20 minutes to only initialise the training.

@iszainab could you please add more details? It would be helpful if you could provide a place between the debug log statements that take so much time

**Comment by wochinge** [comment]
Closing this as a duplicate of https://github.com/RasaHQ/rasa/issues/7272 .
