### ISSUE TITLE
Failed to send message to Rasa Chat webhook. Error: 401, message='Unauthorized', url=URL('http://rasa-production:5005/webhooks/rasa/webhook')

### ISSUE THREAD

**Issue by mishra011** [RasaHQ/rasa#7675]
**Rasa version**: 2.1.3

**Rasa SDK version** (if used & relevant):

**Rasa X version** (if used & relevant): 0.34.0

**Python version**: 3.7

**Operating system** (windows, osx, ...): linux

**Issue**: I deployed rasa x using docker, I followed all the step , but when i use custom image for rasa, rasa x interactive mode is not responing

**Error (including full traceback)**:

 rasa-production_1 | 2021-01-03 14:49:28 DEBUG rasa.core.channels.rasa_chat - Fetched JWT public key from URL 'http://rasa-x:5002/api/version' for algorithm 'RS256':
 rasa-production_1 | ----~~BEGIN PUBLIC KEY~~----
 rasa-production_1 | MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEA1zvdP96WVSaqb+yXClxZ
 rasa-production_1 | cRazJWz/PX1NvOdfuudQijL6YRlOeKLYkKwrXWCqTmiD1H0IQLquKbDiNQtMYO4/
 rasa-production_1 | QBzKZ66gJp6RTyy9tSQwpLWXNVFnH5fAs4UZRgC603+YzXdohNYHDmnou3j/T7bT
 rasa-production_1 | fIMOQPIGKjEE+9Asvqb0ygcGuHRB4/GJbGU2gM4Y8oOURk8oWRZPFsNES/9CoWBO
 rasa-production_1 | L13WXwQPLbEHZ0hc64BBO/G6xXiPvkua9A0NyjJN4OYJfr+Y8jm7TbzyLkLtXBHN
 rasa-production_1 | IXK4FUdVJgZykozry4Ps0TOdN+6lL++ogfJHFnh7W8Wd9N+Trrm3VY6LxaHFctz7
 rasa-production_1 | oQIDAQAB
 rasa-production_1 | ----~~END PUBLIC KEY~~----
 rasa-production_1 | 
 rasa-production_1 | 2021-01-03 14:49:28 ERROR rasa.core.channels.rasa_chat - Failed to decode bearer token.
 rasa-production_1 | Traceback (most recent call last):
 rasa-production_1 | File "/opt/venv/lib/python3.7/site-packages/jwt/api_jws.py", line 219, in _verify_signature
 rasa-production_1 | alg_obj = self._algorithms<span class="error">[alg]</span>
 rasa-production_1 | KeyError: 'RS256'
 rasa-production_1 | 
 rasa-production_1 | During handling of the above exception, another exception occurred:
 rasa-production_1 | 
 rasa-production_1 | Traceback (most recent call last):
 rasa-production_1 | File "/opt/venv/lib/python3.7/site-packages/rasa/core/channels/rasa_chat.py", line 87, in _decode_bearer_token
 rasa-production_1 | return self._decode_jwt(bearer_token)
 rasa-production_1 | File "/opt/venv/lib/python3.7/site-packages/rasa/core/channels/rasa_chat.py", line 78, in _decode_jwt
 rasa-production_1 | authorization_header_value, self.jwt_key, algorithms=self.jwt_algorithm
 rasa-production_1 | File "/opt/venv/lib/python3.7/site-packages/jwt/api_jwt.py", line 92, in decode
 rasa-production_1 | jwt, key=key, algorithms=algorithms, options=options, **kwargs
 rasa-production_1 | File "/opt/venv/lib/python3.7/site-packages/jwt/api_jws.py", line 156, in decode
 rasa-production_1 | key, algorithms)
 rasa-production_1 | File "/opt/venv/lib/python3.7/site-packages/jwt/api_jws.py", line 226, in _verify_signature
 rasa-production_1 | raise InvalidAlgorithmError('Algorithm not supported')
 rasa-production_1 | jwt.exceptions.InvalidAlgorithmError: Algorithm not supported
 rasa-x_1 | ERROR:rasax.community.api.blueprints.stack:Failed to send message to Rasa Chat webhook. Error: 401, message='Unauthorized', url=URL('http://rasa-production:5005/webhooks/rasa/webhook')
 rasa-x_1 | <span class="error">[2021-01-03 14:49:28 +0000]</span> - (sanic.access)<span class="error">[INFO]</span><span class="error">[172.23.0.11:59488]</span>: POST [http://localhost/api/conversations/9173c8899db04a6b83edb63f92ad6aec/messages?environment=production](http://localhost/api/conversations/9173c8899db04a6b83edb63f92ad6aec/messages?environment=production) 404 176
 nginx_1 | 172.23.0.1 - - <span class="error">[03/Jan/2021:14:49:28 +0000]</span> "POST /api/conversations/9173c8899db04a6b83edb63f92ad6aec/messages?environment=production HTTP/1.1" 404 176 "http://localhost:9010/interactive" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.88 Safari/537.36"
 rasa-x_1 | <span class="error">[2021-01-03 14:49:28 +0000]</span> - (sanic.access)<span class="error">[INFO]</span><span class="error">[172.23.0.11:59506]</span>: GET [http://localhost/api/conversations/9173c8899db04a6b83edb63f92ad6aec?test_story=false](http://localhost/api/conversations/9173c8899db04a6b83edb63f92ad6aec?test_story=false) 200 105
 nginx_1 | 172.23.0.1 - - <span class="error">[03/Jan/2021:14:49:28 +0000]</span> "GET /api/conversations/9173c8899db04a6b83edb63f92ad6aec?test_story=false HTTP/1.1" 200 105 "http://localhost:9010/interactive" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.88 Safari/537.36"
 rasa-x_1 | <span class="error">[2021-01-03 14:49:28 +0000]</span> - (sanic.access)<span class="error">[INFO]</span><span class="error">[172.23.0.11:59508]</span>: GET [http://localhost/api/conversations/9173c8899db04a6b83edb63f92ad6aec?test_story=true](http://localhost/api/conversations/9173c8899db04a6b83edb63f92ad6aec?test_story=true) 200 105
 nginx_1 | 172.23.0.1 - - <span class="error">[03/Jan/2021:14:49:28 +0000]</span> "GET /api/conversations/9173c8899db04a6b83edb63f92ad6aec?test_story=true HTTP/1.1" 200 105 "http://localhost:9010/interactive" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.88 Safari/537.36"
 db-migration_1 | <span class="error">[2021-01-03 14:49:29 +0000]</span> - (sanic.access)<span class="error">[INFO]</span><span class="error">[127.0.0.1:44132]</span>: GET [http://localhost:8000/health](http://localhost:8000/health) 200 56
 rasa-x_1 | <span class="error">[2021-01-03 14:49:29 +0000]</span> - (sanic.access)<span class="error">[INFO]</span><span class="error">[172.23.0.11:59512]</span>: GET [http://localhost/api/conversations/9173c8899db04a6b83edb63f92ad6aec?format=full_conversation&since=1609685360.881648&environment=production](http://localhost/api/conversations/9173c8899db04a6b83edb63f92ad6aec?format=full_conversation&since=1609685360.881648&environment=production) 200 324
 nginx_1 | 172.23.0.1 - - <span class="error">[03/Jan/2021:14:49:29 +0000]</span> "GET /api/conversations/9173c8899db04a6b83edb63f92ad6aec?format=full_conversation&since=1609685360.881648&environment=production HTTP/1.1" 200 324 "http://localhost:9010/interactive" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.88 Safari/537.36"
 rasa-worker_1 | 2021-01-03 14:49:29 DEBUG rasa.core.agent - Requesting model from server [http://rasa-x:5002/api/projects/default/models/tags/production](http://rasa-x:5002/api/projects/default/models/tags/production)...
 rasa-x_1 | <span class="error">[2021-01-03 14:49:29 +0000]</span> - (sanic.access)<span class="error">[INFO]</span><span class="error">[172.23.0.9:56314]</span>: GET [http://rasa-x:5002/api/projects/default/models/tags/production?token=5BqcNAI6Icc9oau](http://rasa-x:5002/api/projects/default/models/tags/production?token=5BqcNAI6Icc9oau) 204 0
 rasa-worker_1 | 2021-01-03 14:49:29 DEBUG rasa.core.agent - Model server returned 204 status code, indicating that no new model is available. Current fingerprint: 6b40120155833f4a8d40af7e4ab04de9
 rasa-worker_1 | 2021-01-03 14:49:29 DEBUG rasa.core.agent - No new model found at URL [http://rasa-x:5002/api/projects/default/models/tags/production](http://rasa-x:5002/api/projects/default/models/tags/production)
 rasa-production_1 | 2021-01-03 14:49:29 DEBUG rasa.core.agent - Requesting model from server [http://rasa-x:5002/api/projects/default/models/tags/production](http://rasa-x:5002/api/projects/default/models/tags/production)...
 rasa-x_1 | <span class="error">[2021-01-03 14:49:29 +0000]</span> - (sanic.access)<span class="error">[INFO]</span><span class="error">[172.23.0.8:34518]</span>: GET [http://rasa-x:5002/api/projects/default/models/tags/production?token=5BqcNAI6Icc9oau](http://rasa-x:5002/api/projects/default/models/tags/production?token=5BqcNAI6Icc9oau) 204 0
 rasa-production_1 | 2021-01-03 14:49:29 DEBUG rasa.core.agent - Model server returned 204 status code, indicating that no new model is available. Current fingerprint: 6b40120155833f4a8d40af7e4ab04de9
 rasa-production_1 | 2021-01-03 14:49:29 DEBUG rasa.core.agent - No new model found at URL [http://rasa-x:5002/api/projects/default/models/tags/production](http://rasa-x:5002/api/projects/default/models/tags/production)
 rasa-x_1 | <span class="error">[2021-01-03 14:49:32 +0000]</span> - (sanic.access)<span class="error">[INFO]</span><span class="error">[172.23.0.11:59518]</span>: GET [http://localhost/api/conversations/9173c8899db04a6b83edb63f92ad6aec?format=full_conversation&since=1609685360.881648&environment=production](http://localhost/api/conversations/9173c8899db04a6b83edb63f92ad6aec?format=full_conversation&since=1609685360.881648&environment=production) 200 324
 nginx_

**Command or request that led to error**:

**Content of configuration file (config.yml)** (if relevant):

**Content of domain file (domain.yml)** (if relevant):

**Comment by sara-tagger** [comment]
Thanks for the issue, @rctatman will get back to you about it soon!

###### You may find help in the [docs](https://rasa.com/docs/) and the [forum,](https://forum.rasa.com/) too 🤗

**Comment by ArjaanBuijk** [comment]
@mishra011 ,
These versions of Rasa X & Rasa are not compatible. 

Please check out the  [compatibility matrix](https://rasa.com/docs/rasa-x/changelog/compatibility-matrix)

Right now, this is a good combination:
- Rasa x: 0.34.0
- Rasa: 2.1.3
- Rasa SDK: 2.1.2

**Comment by mishra011** [comment]
@ArjaanBuijk pardon my typo, but I uses the same versions as you have mentioned. Then I got these errors.

**Comment by mishra011** [comment]
@ArjaanBuijk the things is when I use docker image of rasa2.1.3 it works but I ran it with my own image that is almost similar to rasa 2.1.3. For any version of rasa-x , if I try to run it with my custom rasa image there is some issue.
