### ISSUE TITLE
Rasa X "share your bot" link generation fails when a description for the bot is provided.

### ISSUE THREAD

**Issue by ftarlaci** [RasaHQ/rasa#7679]
**Rasa version**: 2.1.2

**Rasa SDK version** (if used & relevant):

**Rasa X version** (if used & relevant): 0.34

**Python version**: 3.8

**Operating system** (windows, osx, ...): Mac OS 

**Issue**: I have deployed a bot on AWS using docker. It works properly when I use it myself. However, when I try to generate a link to share with testers on the Rasa X UI, the link generation nondeterministically fails, clicking on the "generate link" button results in various api errors in the dev tools of the browser (Chrome). I noticed that when I provide textual details in the "description" box on the "generate link" window, the link is not generated. However, when I don't provide anything in the text box, it generates the link. I tried clearing cache, stopping restarting the docker server and aws instance, but the behavior continues. This seems to be a bug. 

**Error (including full traceback)**:
```
NA
```

**Command or request that led to error**:
```

```

**Content of configuration file (config.yml)** (if relevant):
```yml

```

**Content of domain file (domain.yml)** (if relevant):
```yml

```

**Comment by sara-tagger** [comment]
Thanks for the issue, @samsucik will get back to you about it soon!

###### You may find help in the [docs](https://rasa.com/docs/) and the [forum,](https://forum.rasa.com/) too 🤗

**Comment by dav-92** [comment]
The description field seems to be limited to 255 characters, when I tried it with less or no characters generating a link works
(Rasa x local mode)

**Comment by mprazz** [comment]
Closing this issue in favor of its [internal counterpart](https://github.com/RasaHQ/rasa-x/issues/4420)
