### ISSUE TITLE
Add integration tests for Postgres, Rabbit, Redis

### ISSUE THREAD

**Issue by wochinge** [RasaHQ/rasa#7680]
## Proposal

Rasa Open Source has multiple integrations with external services, such as databases or event brokers. While it's very hard to test against all of them (e.g. integration tests for all input channels), we should add least have integration tests for the most important ones (e.g. the ones which are used by Rasa X), namely:
* `SQLTrackerStore` with Postgres
* `RedisLockStore`
* `PikaEventBroker` 

### Workflow
- In the `continous-integration.yml` workflow, add a new job called `integration-tests`
- This job will [setup 3 services](https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions#jobsjob_idservices) using Docker images: `postgres` ([more info](https://docs.github.com/en/actions/guides/creating-postgresql-service-containers)), `redis` ([more info](https://docs.github.com/en/actions/guides/creating-redis-service-containers)) and `rabbitmq` ([more info](https://github.community/t/test-the-rabbitmq-service-with-pika-library-in-github-actions/116599/5))
- Then, this job will run all the integration tests via pytest (we'll need to ignore these tests from the unit and functional tests)
- This job will be required to pass via branch protection, and will prevent releases in case of failure

### Folder structure
- under the `tests/` folder, create an `integration_tests/` folder, where all integration tests will live
- I'd follow the same folder structure than other tests (e.g. replicate the tree structure of the codebase), and create a `conftest.py` file that will contain constants and fixtures for every services

### Seeding the tests
We'll need to write at least one test for each service. Here are simple use cases that we can start with:
- Postgres: `SQLTrackerStore` initialisation with a `login_db` (success + failure paths)
- Redis: `RedisLockStore`, actually we can move [all the tests](https://github.com/RasaHQ/rasa/blob/master/tests/core/test_lock_store.py)  here and make sure they pass without the mocked library
- RabbitMQ: `PikaEventBroker` initialisation + connection

⬆️ if you have any idea on how we can reduce the scope of these, please LMK

**Comment by kaustuk** [comment]
@wochinge is this open for community? If yes can you give me some pointer on what exactly is being expected and what needs to be done. I would like to contribute if possible.

**Comment by wochinge** [comment]
Hey @kaustuk , thanks for the initiative! I'll pull in @tczekajlo and @mprazz from our infrastructure team who'd usually implement / coordinate this within our team.

**Comment by m-vdb** [comment]
I have a use case that I want to test on Postgres: the `SQLTrackerStore` used with the [`login_db` parameter](https://github.com/RasaHQ/rasa/blob/c1b5df37b19380540706fe061a85277e9a3d9bc0/rasa/core/tracker_store.py#L837-L838). I'm happy to start the setup of Postgres integration tests. @mprazz @tczekajlo WDYT? I can come up with a short implementation proposal for this.

**Comment by wochinge** [comment]
@m-vdb We also have a call today related Rasa Open Source testing where we could also discuss this item (it's not only about test performance / fragility but also new tests)

**Comment by wochinge** [comment]
@kaustuk Thanks again for your initiative, but we decided to do this ourselves as it's a large effort which requires setting up the CI and adding a lot of missing tests for these components. I highly appreciate your initiative - have you checked out the issue in the [contributor board](https://github.com/orgs/RasaHQ/projects/23)?

**Comment by tczekajlo** [comment]
> I have a use case that I want to test on Postgres: the `SQLTrackerStore` used with the [`login_db` parameter](https://github.com/RasaHQ/rasa/blob/c1b5df37b19380540706fe061a85277e9a3d9bc0/rasa/core/tracker_store.py#L837-L838). I'm happy to start the setup of Postgres integration tests. @mprazz @tczekajlo WDYT? I can come up with a short implementation proposal for this.

Sure, go ahead with it. Thanks a lot 🙌🏻

**Comment by m-vdb** [comment]
@tczekajlo @mprazz @RasaHQ/enable-squad I wrote down a short implementation proposal in this issue description (yes I hijacked Tobias' issue). Can you give me some feedback on it? Anything I'm missing?

**Comment by wochinge** [comment]
Sounds good to me! 👍🏻

**Comment by joejuzl** [comment]
Some thoughts:
- It would be great if there was an easy way to run this locally e.g. with docker-compose. 
- Should we think about naming (cc @mprazz) we will now have a lot of things called "integration tests"
- Does this have any overlap with our current oracle tests? Currently we run a subset of our unit tests with Oracle. It would be great if we could run all our tests with any supported database. (locally and on the CI). Also see [this](https://github.com/RasaHQ/rasa-x/issues/4027).

**Comment by m-vdb** [comment]
- sounds good; can we do that separately?
- I'll let Mariana weigh in
- Aren't Oracle tests for Rasa X?

**Comment by joejuzl** [comment]
> Aren't Oracle tests for Rasa X? 🤔 do you mean if there are some of these tests that should actually run in the Rasa OSS repo?
Aha yes, my mistake - which means we only run the unit tests for sqlite! (arguably the most different dbs). As we support oracle and postgres too,  I think we should test with them.

**Comment by m-vdb** [comment]
Maybe this can be treated as the next iteration?

**Comment by tczekajlo** [comment]
> This job will setup 3 services using Docker images: postgres (more info), redis (more info) and rabbitmq (more info)

I think we can use docker-compose to run a container with DB, it'll be possible to run it locally as well

**Comment by mprazz** [comment]
Thank you for the work so far everybody! 🔥 
Some thoughts on my side:
- Re local runs : I'd definitely like to see these tests being ran locally as well, but I agree it can be done after the CI implementation
- Re naming : I'd usually name these `intergration tests` as they do test our integration, and as far as I know we don't really have integration tests on `rasa`'s side? Please do correct me if I'm wrong 🙏 
- I absolutely agree we should have at least initialization and basic connection with these external DBs (not sure we can really reduce the scope and still maintain coverage 🤔  -- but then again these seem like very basic test cases)

Keep in mind I'm not as familiar with the automation on `rasa`'s side as I am with the ones on `rasa-x`'s side, so some of my comments may be a bit off 😅

**Comment by wochinge** [comment]
> (not sure we can really reduce the scope and still maintain coverage 

I think we can have a huge effect on product quality by at least testing the basic uses case. From my intuition Pareto applies and 80% of issues are care caused by 20% of the use cases.
