### ISSUE TITLE
I need a Albert in LanguageModelFeature

### ISSUE THREAD

**Issue by sajjjadayobi** [RasaHQ/rasa#7682]
the Bert Model is very heavy for my project, I have to use Albert instead of Bert
have you any suggestions for me?
or how can I create a custom component for this?
           extend from LanguageModelFeature or HFTransfromers?

**Comment by sara-tagger** [comment]
Thanks for submitting this feature request 🚀 @m-vdb will get back to you about it soon! ✨

**Comment by dakshvar22** [comment]
@sajjjadayobi Thanks for the request. What's the memory requirement that you are working with?
`LanguageModelFeaturizer` does support `DistilBert`. You can try that as well.
Otherwise the custom component should extend `LanguageModelFeaturizer`.

**Comment by sajjjadayobi** [comment]
thanks @dakshvar22 I know that LanguageModelFeaturizer does support DistilBert,
my language is Persian(Farsi) and I have to use distilbert-base-multilingual-cased that its size is about 900 MB
I have an Albert model that trained in my language with about 80 MB of size, I want to use it 

is this ok? for using in the pipeline instead of `LanguageModelFeaturizer`

```python
    from rasa.nlu.featurizers.dense_featurizer.lm_featurizer import LanguageModelFeaturizer
    from transformers import TFAlbertModel
    from transformers import AlbertTokenizer

    class AlbertFeaturizer(LanguageModelFeaturizer):
        def _load_model_metadata(self) -> None:
            self.model_name = 'albert'
            self.model_weights = 'albert-base-v2'
            self.tokenizer = AlbertTokenizer.from_pretrained(self.model_weights)
            self.model = TFAlbertModel.from_pretrained(self.model_weights)
            self.max_model_sequence_length = 512
            self.pad_token_id = self.tokenizer.unk_token_id
```
