### ISSUE TITLE
The format for exporting "any" type slots (in JSON or list) through migration or interactive learning blocks any subsequent training

### ISSUE THREAD

**Issue by ganeshviyer** [RasaHQ/rasa#7683]
**Rasa version**: 2.2.2

**Rasa SDK version** (if used & relevant): 2.2

**Rasa X version** (if used & relevant): not relevant here

**Python version**: 3.7.9

**Operating system** (windows, osx, ...): Mac OS Big Sur 11.1

**Issue**: If any of the slots of type "any" are in JSON or in list format, the format in YAML through which the slot values are exported through the automated migration (from 1.x to 2.x) or through Interactive Learning, fails any subsequent training.

The JSON or the list value of the slot is converted to a YAML tree structure that looks something like this under the `slot_was_set` node in stories. The slot `SLOT_NAME` in the example below is used as a JSON during the conversations by custom actions.

*   action: previous_action
*   slot_was_set:
*   SLOT_NAME:
     SLOT_KEY_1:
     slot_property_1: <value>
     slot_property_2: <value>
     slot_property_list_3:
*   slot_property_3_1: <value>
     slot_property_3_2: <value>
*   slot_property_3_1: <value>
     slot_property_3_2: <value>
*   slot_property_3_1: <value>
     slot_property_3_2: <value>
*   slot_property_3_1: <value>
     slot_property_3_2: <value>
     SLOT_KEY_2
     ...

The issue is described in detail here - [https://forum.rasa.com/t/the-slot-type-any-does-not-seem-to-work-correctly/38674](https://forum.rasa.com/t/the-slot-type-any-does-not-seem-to-work-correctly/38674)

**Error (including full traceback)**: The errors I get look like

 Value 'ordereddict([('SLOT_NAME', ordereddict([('SLOT_KEY_1', ordereddict([('slot_property_1, '<value>'), ('slot_property_2', '<value>'), ('slot_property_list_3', [ordereddict(<span class="error">[('slot_property_3_1', '
 <value>
  '), ('slot_property_3_2', '
  <value>
   ')]
  </value>
 </value></span>), ordereddict(<span class="error">[('slot_property_3_1', '
 <value>
  '), ('slot_property_3_2', '
  <value>
   ')]
  </value>
 </value></span>), ordereddict(<span class="error">[('slot_property_3_1', '
 <value>
  '), ('slot_property_3_2', '
  <value>
   ')]
  </value>
 </value></span>), ordereddict(<span class="error">[('slot_property_3_1', '
 <value>
  '), ('slot_property_3_2', '
  <value>
   ')]
  </value>
 </value></span>))]))...' is not of type 'str'. Path: '/stories/5/steps/8/slot_was_set/0'

I get a version of the above error, each for type 'text', 'list', 'bool'.

**Command or request that led to error**:

 rasa train

or

 rasa data convert core -f yaml --data=./data/stories --out=./data/stories

**Comment by sara-tagger** [comment]
Thanks for raising this issue, @desmarchris will get back to you about it soon✨

###### Please also check out the [docs](https://rasa.com/docs/) and the [forum](https://forum.rasa.com/) in case your issue was raised there too 🤗

**Comment by samsucik** [comment]
Just note that IL should be changed so as not to export slots of type `any` in stories. The migration scripts can be fixed in two ways: Either they preserve those slots in stories (but in a way that doesn't break training), or we go more intrusive and delete those slots while converting markdown to YAML (personally, I would avoid the 2nd option as I think users can have such slots in their stories for legit reasons).

**Comment by ganeshviyer** [comment]
Any update on this?  There are quite a few stories that I have and manually cleaning up the migration scripts and any subsequent exports to stories from IL, is going to be quite cumbersome.
