### ISSUE TITLE
Edited message on telegram raises an exception

### ISSUE THREAD

**Issue by tranchitella** [RasaHQ/rasa#7686]
**Rasa version**: 2.0.0

**Python version**: 3.8

**Operating system**: Ubuntu 20.04.1 LTS

**Issue**: If a user edits a message over Telegram, the Rasa server raises an exception and returns an error in response to the Telegram webhook. From that point, the chatbot stops to work.

Already reported here, but closed because of missing activity: [https://github.com/RasaHQ/rasa/issues/5654](https://github.com/RasaHQ/rasa/issues/5654)

**Error (including full traceback)**:

 Jan 6 10:57:26 ip-10-50-188-7 rasa<span class="error">[215589]</span>: Traceback (most recent call last):
 Jan 6 10:57:26 ip-10-50-188-7 rasa<span class="error">[215589]</span>: File "/home/ubuntu/rasa-libya/venv/lib/python3.8/site-packages/sanic/app.py", line 938, in handle_request
 Jan 6 10:57:26 ip-10-50-188-7 rasa<span class="error">[215589]</span>: response = await response
 Jan 6 10:57:26 ip-10-50-188-7 rasa<span class="error">[215589]</span>: File "/home/ubuntu/rasa-libya/venv/lib/python3.8/site-packages/rasa/core/channels/telegram.py", line 217, in message
 Jan 6 10:57:26 ip-10-50-188-7 rasa<span class="error">[215589]</span>: if self._is_user_message(msg):
 Jan 6 10:57:26 ip-10-50-188-7 rasa<span class="error">[215589]</span>: File "/home/ubuntu/rasa-libya/venv/lib/python3.8/site-packages/rasa/core/channels/telegram.py", line 177, in _is_user_message
 Jan 6 10:57:26 ip-10-50-188-7 rasa<span class="error">[215589]</span>: return message.text is not None
 Jan 6 10:57:26 ip-10-50-188-7 rasa<span class="error">[215589]</span>: AttributeError: 'NoneType' object has no attribute 'text'

**Command or request that led to error**: Edit a message in Telegram

**Comment by tranchitella** [comment]
PR: https://github.com/RasaHQ/rasa/pull/7687

**Comment by sara-tagger** [comment]
Thanks for raising this issue, @desmarchris will get back to you about it soon✨

###### Please also check out the [docs](https://rasa.com/docs/) and the [forum](https://forum.rasa.com/) in case your issue was raised there too 🤗

**Comment by superDPgg** [comment]
I have the same problem for telegram！
