### ISSUE TITLE
Raise "conflicting rules/stories" error message before training the TEDPolicy model

### ISSUE THREAD

**Issue by humcasma** [RasaHQ/rasa#7691]
**Description of Problem**:
If there are conflicting rules and/or stories, an error message "InvalidRule: Contradicting rules or stories found" is raised. But this only happens after the core models, including the TEDPolicy model, are trained, which can take long. 
I would suggest moving the check for invalid rules/stories before the TEDPolicy model is trained.

**Definition of done**:
- [ ] Change the default config to put the rule policy first

**Comment by sara-tagger** [comment]
Thanks for submitting this feature request 🚀 @amn41 will get back to you about it soon! ✨

**Comment by joejuzl** [comment]
@JEM-Mosig any idea whether this is possible? Or is it required to have a trained policy before checking for conflicts with rules?

**Comment by TyDunn** [comment]
@JEM-Mosig Following up about this. Is this possible?
