### ISSUE TITLE
Support Default Slot Mappings

### ISSUE THREAD

**Issue by rgstephens** [RasaHQ/rasa#7708]
**Description of Problem**: The slot mapping section for a form can get very long and it's not unusually for many forms to use the same slots with identical mapping rules. A single slot can require 10 or more lines of yml which need to be duplicated for several forms resulting in a lot of duplication.

<pre>forms:
 restaurant_form:
 cuisine:

*   type: from_intent
     entity: like_greek
*   type: from_intent
     entity: like_indian
*   type: from_intent
     entity: like_italian
*   type: from_entity
     entity: cuisine
*   type: from_entity
     intent: affirm
     value: italian</pre>

**Overview of the Solution**: Allow default slot mapping definitions in the slot section. The form section could list only the slot name if it wants the default or it can specify slot mappings if it wants to override the defaults.

**Examples** (if relevant):

<pre>slots:
 cuisine:
 type: text
 mapping:

*   type: from_intent
     entity: like_greek
*   type: from_intent
     entity: like_indian
*   type: from_intent
     entity: like_italian
*   type: from_entity
     entity: cuisine
*   type: from_entity
     intent: affirm
     value: italian

forms:
 restaurant_form:

*   cuisine</pre>

**Definition of Done**:

*   [ ] Tests are added
*   [ ] Feature described the docs
*   [ ] Feature mentioned in the changlog

**Comment by domsammut** [comment]
This would be a great enhancement and consolidate business logic.

**Comment by ancalita** [comment]
As it is now possible to declare all slot mappings (including specific active_loop conditions in the slot mapping) under slots section in 3.x and forms' `required_slots` is now a list of slot names, closing this ticket for now. If you want to improve or request enhancements for current 3.x slot mappings, please open new tickets 🙏🏻 

PS: Doing some tidying up of open issues 😄
