### ISSUE TITLE
Form switching fails when requested_slot is the same in both forms

### ISSUE THREAD

**Issue by desmarchris** [RasaHQ/rasa#7710]
https://rasa-hq.slack.com/archives/C7FCS16SD/p1608240711266000

**Rasa version**: 2.1.2

**Rasa SDK version** (if used & relevant): 2.1.2

**Python version**: 3.8.6

**Operating system** (windows, osx, ...): osx

**Issue**:
When switching between two forms, if the `requested_slot` is the same in the new and old form, the bot returns an empty response rather than switching to the new form

The issue can be reproduced by pulling [this commit](https://github.com/RasaHQ/retail-demo/tree/4bbd4109a5d7d3fce09fb43a5e8b9a1cfcee3d80) from the retail-demo, and then try:

```bash
Your input ->  order status
I can help you find the status of your order. What's your email address so I can find the order?
Your input ->  return
Your input ->
```

The expected conversation must be:
```bash
Your input ->  order status
I can help you find the status of your order. What's your email address so I can find the order?
Your input ->  return
Let's start that return. To help find your order, can you please provide your email address?
Your input ->
```

**Comment by TyDunn** [comment]
@ArjaanBuijk Can this be closed?
