### ISSUE TITLE
Documentation checks - retry if a link is not reachable 

### ISSUE THREAD

**Issue by tczekajlo** [RasaHQ/rasa#7718]
One of the checks in the Publish Documentation workflow checks if links in the docs are still reachable, but sometimes it happens that one of the links didn't respond on time, in such a scenario the workflow will finish with failure. 

Things to improve:
- increase the timeout for connection
- retry if a connection failed

**Comment by HotThoughts** [comment]
I looked [publish documentation workflow](https://github.com/RasaHQ/rasa/blob/master/.github/workflows/documentation.yml). Not sure about which check is reaching links. Do you have an idea?

**Comment by tczekajlo** [comment]
> I looked [publish documentation workflow](https://github.com/RasaHQ/rasa/blob/master/.github/workflows/documentation.yml). Not sure about which check is reaching links. @tczekajlo Do you have an idea?

Everything is in the Makefile, the `test-docs` section.

**Comment by HotThoughts** [comment]
The test-docs workflow from CI uses the command `remark --frail docs/*.mdx docs/*/*.mdx` (see [here](https://github.com/RasaHQ/rasa/blob/5549b07d70a39819bf793017de3badd7ea903bc6/docs/package.json#L24)) We can look at the [remark cli ](https://github.com/remarkjs/remark/tree/main/packages/remark-cli)for timeout or retry option. If remark does not have the option, we can certainly separate the test-docs workflow from CI.
