### ISSUE TITLE
support spaCy 2.3.0+

### ISSUE THREAD

**Issue by Aspirinkb** [RasaHQ/rasa#7724]
**Description of Problem**:

The latest rasa(2.2.5) needs spacy < 2.3.0, but there only Chinese models after 2.3.0 in spacy.
**Overview of the Solution**:

Upgrading rasa to support spacy 2.3.0+, so that one can use spacy official Chinese language model.
**Examples** (if relevant):

spaCy official Chinese language model: https://spacy.io/models/zh
**Blockers** (if relevant):

Chinese language.
**Definition of Done**:

**Comment by sara-tagger** [comment]
Thanks for submitting this feature request 🚀 @tttthomasssss will get back to you about it soon! ✨

**Comment by koaning** [comment]
I'm picking this up as part of our upgrade to spaCy 3.0. Note that this should make all available Chinese models available in Rasa too!

**Comment by Aspirinkb** [comment]
Nice to see the upgrade~

**Comment by Ghostvv** [comment]
@koaning should this issue be closed in favor of https://github.com/RasaHQ/rasa/issues/6906?

**Comment by koaning** [comment]
I was thinking of closing this issue once the PR was merged but sure. The ball is already rolling so I'm fine with removing this one.
