### ISSUE TITLE
How to pass slots to Custom Action

### ISSUE THREAD

**Issue by sfahad1414** [RasaHQ/rasa#7729]
Story
* intent5
    - slot{"http_action_config": "get_intent5"}
    - http_action

I need to get the slot value from story to custom action based on value certain API will be invoked but when I try to access slot in custom i get None

**Comment by desmarchris** [comment]
Hey @sfahad1414 thanks for the post! We typically reserve GitHub issues for bug reports and feature requests. Do you mind reposting in our forum? Here's the link: https://forum.rasa.com/
