### ISSUE TITLE
Rasa Actions Quick Restart Bug

### ISSUE THREAD

**Issue by ghost** [RasaHQ/rasa#7733]
**Rasa version**: Rasa Version : 2.2.2

**Rasa SDK version** (if used & relevant): Rasa SDK Version : 2.2.0

**Rasa X version** (if used & relevant): Rasa X Version : None

**Python version**: Python Version : 3.7.3 Python Path : /home/admin/.venv/bin/python3.7

**Operating system** (windows, osx, ...): Operating System : Linux-4.19.0-13-cloud-amd64-x86_64-with-debian-10.7

**Issue**:

If Rasa actions is restarted rapidly, the old connection remains in a TIME_WAIT mode which causes unpredictable behavior

 tcp 0 0 0.0.0.0:5055 0.0.0.0:* LISTEN 5235/python3.7 
 tcp 0 0 127.0.0.1:60180 127.0.0.1:5055 TIME_WAIT -

This basically just needs an SO_REUSEADDR set on the listening socket

**Error (including full traceback)**: No error. Just doesnt work!

**Command or request that led to error**: rasa actions

**Content of configuration file (config.yml)** (if relevant):

**Content of domain file (domain.yml)** (if relevant):

**Comment by sara-tagger** [comment]
Thanks for raising this issue, @rctatman will get back to you about it soon✨

###### Please also check out the [docs](https://rasa.com/docs/) and the [forum](https://forum.rasa.com/) in case your issue was raised there too 🤗
