### ISSUE TITLE
Add full integration tests to CI

### ISSUE THREAD

**Issue by wochinge** [RasaHQ/rasa#7734]
**Description of Problem**: We currently don't have full end-to-end tests for Rasa Open Source which tests the whole setup of

*   receiving a message
*   respond to the message
*   integration with action server
*   forwarding messages via the `EventBroker`
*   storing any conversation events in the `TrackerStore`

**Overview of the Solution**: The integration tests should ideally be as close as possible to a Rasa X production setup, which means using

*   Postgres as `TrackerStore`
*   a `RedisLockStore` as lockstore
*   `RabbitMQ` as `EventBroker`

**Definition of Done**:

*   [ ] Tests are added
*   [ ] Tests can be executed locally (or it's described how to do so)
*   [ ] Tests are executed as part of the CI

**Comment by m-vdb** [comment]
Closing for now
