### ISSUE TITLE
Wrong default config comments

### ISSUE THREAD

**Issue by adai183** [RasaHQ/rasa#7735]
https://github.com/RasaHQ/rasa/blob/395f768d91d3fc8a63f68fb4e4c3dd159b0904d6/rasa/cli/initial_project/config.yml#L13

Shouldn't there be a `ConveRTFeaturizer` instead of a duplicated `CountVectorsFeaturizer`. 
As far as I understood DIET uses both sparse and dense vector features.

**Comment by erohmensing** [comment]
No, the default pipeline has two CountVectorsFeaturizers, one for word-level embeddings and one for character-level embeddings. The ConvertFeaturizer was originally in the pipeline, but became unavailable when the model was pulled by its hosts, so we moved to a more stable default config that does not depend on other pretrained models.

**Comment by adai183** [comment]
Thanks a lot for the super-fast response. Although I am having a hard time understanding a version of the DIET Architecture without pretrained embedding,

**Comment by erohmensing** [comment]
That unfortunately I can't help you with 😅 we keep github for bugs and enhancements, but I encourage you to ask your question on the forum and maybe tag Vincent to help you out!
