### ISSUE TITLE
`rasa test` should search for test files recursively in all sub-directories, not just under `tests/`

### ISSUE THREAD

**Issue by koernerfelicia** [RasaHQ/rasa#7763]
**Rasa version**:
2.2.4
**Python version**:
3.7.2
**Operating system** (windows, osx, ...):
OSX

**Issue**:
`rasa test` looks recursively for files prefixed with `test_`, but only in subdirectories of `tests/`. It should look recursively in all subdirectories.
`rasa test core` seems to look for these files in any subdirectory.

**Command or request that led to error**:
```
rasa test
```

**Comment by koernerfelicia** [comment]
@kalkbrennerei finally got around to making this. Could you add some comments if you have any? Thank you!

from our Slack discussion:
Lu:"I think rasa test and rasa test core are both using test.py::run_core_test internally but with different args"

**Comment by kalkbrennerei** [comment]
thanks @koernerfelicia! I think I have nothing to add  😃
but maybe I can mention [this PR](https://github.com/RasaHQ/rasa/pull/7483) here. I think we decided to only accept test story files with `test_` prefix, so with the fix of your issue the linked PR will become irrelevant if I'm not mistaken

**Comment by wochinge** [comment]
I'll close my PR as well. @kalkbrennerei Do you know any specific reasons for the decisions or where we could find that?

**Comment by kalkbrennerei** [comment]
@wochinge I think for 2.0 we wanted to enable the users to structure their projects the way they want to, so without restricting them to have a/only one `tests` folder. And therefore the tests must have the `tests_` prefix. But it also doesn't seem ideal to me that this is causing friction to the users... This [Thread](https://rasa-hq.slack.com/archives/C7B08Q5FX/p1597403645425900) seems to have a discussion about it, but not sure of the actual conclusion.

**Comment by b-quachtran** [comment]
@alwx FYI, there's a bug where `rasa test` change where it doesn't look for test files inside any directories in `.`.  Created an issue for this here: https://github.com/RasaHQ/rasa/issues/8322
