### ISSUE TITLE
Rasa X, NLU is provided in markdown instead of yaml

### ISSUE THREAD

**Issue by georgebrianb** [RasaHQ/rasa#7766]
**Rasa version**: 2.2.5

**Rasa SDK version** (if used & relevant): 2.2.0

**Rasa X version** (if used & relevant): 0.35.0

**Python version**: 3.7.9

**Operating system** (windows, osx, ...): Linux-5.8.0-38-generic-x86_64-with-Ubuntu-20.04-focal

**Issue**:  The NLU that Rasa X generates is in nlu.md instead of nlu.yml

![image](https://user-images.githubusercontent.com/32679117/105334092-2914dd80-5bdf-11eb-980d-f46646cbe007.png)

![image](https://user-images.githubusercontent.com/32679117/105334071-21553900-5bdf-11eb-8273-1e1786b9bd38.png)

I was expecting it to be in the yaml format, this is not happening for the other data files (stories, domain, rules)

**Comment by sara-tagger** [comment]
Thanks for the issue, @b-quachtran will get back to you about it soon!

###### You may find help in the [docs](https://rasa.com/docs/) and the [forum,](https://forum.rasa.com/) too 🤗

**Comment by georgebrianb** [comment]
Awesome, I wasn't using the feature, but if someone needs it, would be cool to get fixed, thanks for the help guys! 
Have a great one!

**Comment by wochinge** [comment]
@b-quachtran Can you please come back to @georgebrianb ?

**Comment by b-quachtran** [comment]
@georgebrianb Thanks for bringing this issue to our attention, the Rasa team is taking a look at this bug and you can track the status here as it gets fixed.

**Comment by mprazz** [comment]
This one is no longer an issue :) Closing!
