### ISSUE TITLE
Pika Broker Causing Multiprocessing Error

### ISSUE THREAD

**Issue by b-quachtran** [RasaHQ/rasa#7772]
**Rasa version**:
1.10.18

**Rasa SDK version** (if used & relevant):

**Rasa X version** (if used & relevant):
0.32.2

**Python version**:

**Operating system** (windows, osx, ...):

**Issue**:
Multiprocessing library is throwing an error with the Pika connector 

**Error (including full traceback)**:
![image (3)](https://user-images.githubusercontent.com/65514514/105419028-e957f100-5bf2-11eb-8df4-a3e32e6b4f0e.png)

**Command or request that led to error**:
```

```

**Content of configuration file (config.yml)** (if relevant):
```yml

```

**Content of domain file (domain.yml)** (if relevant):
```yml

```

# Enable-Squad Issues Updates

* We agreed upon that back porting the new 2.x implementation as done in this PR is a stretch of semantic versioning, but valid in this case as the new implementation is battle tested with 2.0
* Definition of Done: 
  - [ ] Fix is back ported and tested
  - [ ] Micro with fix is shipped

**Comment by b-quachtran** [comment]
@alwx FYI, this appears to only be happening when SANIC_WORKERS is set to >1.

**Comment by wochinge** [comment]
We agreed upon that back porting the new 2.x implementation as done in [this PR](https://github.com/RasaHQ/rasa/pull/7754) is a stretch of semantic versioning, but valid in this case as the new implementation is battle tested with 2.0
