### ISSUE TITLE
Support user messages from transports other than HTTP(S)

### ISSUE THREAD

**Issue by veigaribo** [RasaHQ/rasa#7789]
First of all I'd like to say that this is my first kind of contribution to the project, so it's quite possible for me to have not understood something.

**Description of Problem**:

I would like for my Rasa bot to be able to receive user messages from AMQP, through a messaging system, and not from HTTP(S) with webhooks. But, currently, from what I've checked, that is basically impossible.

My suggestion would be a way to create Custom Connectors that work without relying on Sanic routes.

**Overview of the Solution**:

Actually, it's almost possible to do such a thing now. The only thing we would need to do would be to give the `InputChannel`'s `blueprint` method access to the Sanic `app` object, so that it could register a listener for when the server is ready, and even get access to the event loop that way (that is necessary because, if one tries to call the `handler` / `on_new_message` callback before the Sanic server has been initialized, an error could be raised, since the `app` object will possibly have `None` as the `agent` attribute. Also access to the server's event loop is important to enable proper scheduling with the messages coming from the new non-HTTP(S) channel).

The problem I see is that, currently, the `InputChannel` is way too tied with HTTP(S). The function that creates them is even called `create_http_input_channels`.

So, for the end goal, what I have in mind is:

*   We would probably need to rename the `create_http_input_channels` function, I don't see why it wouldn't be used for other types of channels;
*   We would need to give to either the current `InputChannel` objects or to objects of a newly created class the opportunity to run code after the `app.agent` has been defined (i.e. right after server initialization), while still giving access to the `handler` / `on_new_message` callback. That is what is lacking in the current `InputChannel` implementation, as it assumes the callback will only be called once the server has started, which, in our new case, would not be necessarily true (messages could be received before the server has started).

Another alternative, I suppose, would be to stop using the `agent` from the Sanic `app` object, and instead get it from some other way, so that the callback that is given to the `blueprint` method may be called before the `app.agent` has been set. I haven't looked very much into that possibility, though.

**Examples**:

I have implemented this example: [https://github.com/Veigaribo/example-rasa-amqp-connector/blob/master/connectors/amqp.py](https://github.com/Veigaribo/example-rasa-amqp-connector/blob/master/connectors/amqp.py)

That would work if the Sanic `app` object was passed as an argument to the `blueprint` method.

By the way, about that repository, be warned that cloning its submodules will currently not work. That shouldn't be necessary to experiment, though.

**Definition of Done**:

*   [ ] Tests are added
*   [ ] Feature described in the docs
*   [ ] Feature mentioned in the changelog

**Comment by sara-tagger** [comment]
Thanks for submitting this feature request 🚀 @samsucik will get back to you about it soon! ✨

**Comment by wochinge** [comment]
I really like the detail of your enhancement request! Thanks a lot @Veigaribo! I think this would be a great addition. A quick fix would be to start a separate thread in the `InputChannel` which then calls `on_new_message`, but I agree that the `app` solutino would be cleaner 👍🏻 

Do you have other protocols than AMQP in mind? I'd like to avoid that we design this with a too narrow scope.

**Comment by Veigaribo** [comment]
> Do you have other protocols than AMQP in mind? I'd like to avoid that we design this with a too narrow scope.

Actually, by providing a generic way to use the `on_new_message` callback, my goal is that it could work with any protocol (and not just protocol) after a bit of code. AMQP is just my personal case xd

> I agree that the app solutino would be cleaner 👍🏻

So, elaborating a bit on that, I imagined two main ways we could let the `InputChannel` run code after the `app` has started:

1. We could simply provide an `on_agent_ready` method that the `InputChannel` may override, and then call that method with the `on_new_message` as one of the parameters once the server has started; (this way the implementer has no knowledge of the underlying `app` stuff)
2. Or we could create a new method, e.g. `register`, whose purpose by default will be to call the `blueprint` method and apply it to the `app` (basically what the current `register` function of the `channel` module does). The user, however, would be able to override it and add a listener to the Sanic server, maybe not even calling the blueprint at all. (much lower level)

To me, the first solution seems cleaner, but the second one has its advantages too...

**Comment by wochinge** [comment]
I agree on your pros and cons. I'd make the `app` available to the `on_agent_ready` method though (useres can e.g. get the event loop from it or customize more).
