### ISSUE TITLE
Make Rasa support GPU Nvidia RTX 30 series

### ISSUE THREAD

**Issue by vietinfo** [RasaHQ/rasa#7793]
Rasa version: 2.2.6
Rasa SDK version: 2.2.0
Rasa X version: 0.35.0
Python version: 3.8.5
Operating system: Ubuntu Server 20.04
CPU: AMD Ryzen 9 5900x
GPU: Nvidia RTX 3070 8GB
**Issue**:
Tensorflow in this GPU not support cuda 10.1( support cuda 11.0 ), but rasa only run in cuda 10.1. i'm try to install cuda 11.0 but no thing work

**Comment by sara-tagger** [comment]
Thanks for raising this issue, @rctatman will get back to you about it soon✨

###### Please also check out the [docs](https://rasa.com/docs/) and the [forum](https://forum.rasa.com/) in case your issue was raised there too 🤗

**Comment by koernerfelicia** [comment]
Hi @vietinfo, this is because TensorFlow 2.3 does not support CUDA 11. We are looking into updating our TensorFlow dependency to >2.3 (see the issue linked above).
