### ISSUE TITLE
Add `trivy` issues to project board

### ISSUE THREAD

**Issue by wochinge** [RasaHQ/rasa#7798]
**Description of Problem**:
Trivy automatically creates issues for security vulnerabilities (see [here](https://github.com/RasaHQ/rasa/issues?q=is%3Aopen+is%3Aissue+label%3Atool%3Atrivy)). These are currently not added to a squad board and hence tend to get lost.

**Definition of Done**:
- [ ] New trivy issues are automatically added to a project board
- [ ] Trivy doesn't create duplicate issues (@wochinge once fixed that but it somehow got back in)

**Comment by tczekajlo** [comment]
Closed in the favor of #4515 - the issue is going to be addressed there
