### ISSUE TITLE
Setup integration tests for third-party channels

### ISSUE THREAD

**Issue by wochinge** [RasaHQ/rasa#7804]
**Description of Problem:** There are currently only few integration tests for the channels (e.g. for REST), but no integration tests for third party channels (e.g. Telegram, Facebook, Slack, etc.).

**Overview of the Solution:**

*   As we have to use APIs I could imagine that the tests are a bit flakey by nature. Hence, it might be a good idea to not run them as part of pull requests but e.g. on a daily schedule
*   I imagine something like a `pytest` test class which we can extend and 
      *   specify how a message is sent to the third party
    *   specify how we test the correct response was received by the third party
    *   allows specifying the credentials for the channel (which end up in `credentials.yml`)

**Definition of Done**

*   [ ] We have a CI job which regularly (either on PR or on schedule) tests our integration with third-party channels
*   [ ] We have a framework for a test which tests sending a message to the third party and makes sure Rasa Open Source sends back the expected response to the third party (e.g. Facebook)
*   [ ] the CI job can easily be extended when new channels are added to Rasa Open Source
*   [ ] We are notified if an integration breaks (e.g. on PR or via Slack notification in case of scheduled runs)
*   [ ] It's documented how to add a new test for an integration

This issue is not for adding integration tests for all channels. This is handled in further issues (see parent issue)

**Comment by wochinge** [comment]
@RasaHQ/infrastructure I think this is a good task to collaborate on, what do you think? (cc @RasaHQ/enable-squad )

**Comment by mprazz** [comment]
Possibly correlated with [this issue](https://github.com/RasaHQ/rasa-x/issues/3547)? (could make sense to tackle both at the same time at the very least)

**Comment by tczekajlo** [comment]
@wochinge @mprazz anyone else :D  Cool, do we wanna have a document or a call where we can discuss what is needed and determine the first steps?

**Comment by HotThoughts** [comment]
🙋🏻‍♀️

**Comment by wochinge** [comment]
@tczekajlo At least for us the integration tests for tracker store, etc. are more of a priority. If you already want to get started, I'd be happy to have a call / document but in my opinion we can also do this as a next step after doing the other integration tests. What do you think?

**Comment by tczekajlo** [comment]
> @tczekajlo At least for us the integration tests for tracker store, etc. are more of a priority. If you already want to get started, I'd be happy to have a call / document but in my opinion we can also do this as a next step after doing the other integration tests. What do you think?

@wochinge I just wanted to get a sense of what is a priority for the enable squad in order to make planning a bit easier 😄 . I think your replied answers all my questions. First, we'll focus on the integration tests (https://github.com/RasaHQ/rasa/issues/7680) 🚀  Thanks a lot 🙌🏻

**Comment by mprazz** [comment]
@wochinge after some discussion with the infra squad, we got to the conclusion that none of us has a definite answer to how we can implement these tests (nor the time to look into it), and that definitely seems to be the next step here. On the other hand, if the Enable Squad has prioritized these tests and has the time to conduct the investigation required here, feel free to do so. We'd be happy to consult once you have some implementation proposal for these 😊 Feel free to ping me if you need anything!

**Comment by wochinge** [comment]
It's currently not in our OKRs so I don't expect any work on it to happen in this cycle. Let's do a meeting once this becomes a priority again 👍🏻

**Comment by mihai-satmarean** [comment]
great product people, what is the status of this? we could really use it with the mattermost bot based on https://github.com/RasaHQ/helpdesk-assistant/issues/59

**Comment by m-vdb** [comment]
thanks for your interest @mihai-satmarean ! We haven't currently made plans to address this issue. Is it something you'd like to work on if you were given a bit of guidance? Usually to implement improvements for channels it's better to have people with hands-on experience with said channel.

**Comment by mihai-satmarean** [comment]
@m-vdb Thanks for the reply! Yes, I would very much like to help if a bit of guidance is given. Waiting for your proposal on how to get this moved.

**Comment by m-vdb** [comment]
Closing as work on this ticket is represented by other issues
