### ISSUE TITLE
Add integration tests for Mattermost Channel

### ISSUE THREAD

**Issue by wochinge** [RasaHQ/rasa#7809]
**Description of Problem**: We should add integration tests for our `Mattermost` channel which test the entire roundtrip of sending a message, processing it via Rasa Open Source and receiving the bot's response.

**Overview of the Solution**: TBD

**Blockers** This task is dependent on [https://github.com/RasaHQ/rasa/issues/7804](https://github.com/RasaHQ/rasa/issues/7804).

**Definition of Done**:

*   [ ] Tests are added

**Comment by mihai-satmarean** [comment]
This would really be useful for our bot based on https://github.com/RasaHQ/helpdesk-assistant, where we have this ticket: #https://github.com/RasaHQ/helpdesk-assistant/issues/59
