### ISSUE TITLE
Automatically update to the latest trained model when running Rasa X

### ISSUE THREAD

**Issue by jameshenderson12** [RasaHQ/rasa#7818]
**Description of Problem**:
I find that, particularly, when I make amendments to a chatbot through the CLI the latest trained model is not automatically selected when I subsequently run `rasa x`. Consequently, I need to manually go to the Models tab and select the latest model. I understand that it is important to be able to select different models to use, but it would be more efficient in terms of a workflow if the latest one could be automatically selected already.

I don't know if this is just for me (or it should be created as a bug rather than feature request) so apologies and feel free to disregard.

**Overview of the Solution**:
It would be great when, after training with Rasa on the CLI (and running `rasa train`) that when a subsequent `rasa x` command is given that it loads the Rasa X interface with the latest trained model as the one pre-selected for use.

**Examples** (if relevant):
N/A

**Blockers** (if relevant):
N/A

**Definition of Done**:
- [ ] Changes made to a Rasa chatbot through the CLI
- [ ] Run `rasa train` to generate a new model through the CLI
- [ ] Run `rasa x` to open up Rasa X interface
- [ ] Navigate to the Models tab
- [ ] See the latest trained model (listed at the top) as the one selected for use.

**Comment by sara-tagger** [comment]
Thanks for submitting this feature request 🚀 @rctatman will get back to you about it soon! ✨

**Comment by melindaloubser1** [comment]
@jameshenderson12 The reason it keeps the previously tagged model is because the model tags are saved in the rasa.db database.  It only looks for the latest one on first startup, when there are no tags (as you've discovered).
So not a bug =) I think whether or not this is preferred behaviour will depend on the developer, so not sure it makes sense to make it a default behaviour. Let's see if anyone else chips in.

**Comment by jameshenderson12** [comment]
Thanks for your response @melindaloubser1. I'm pleased this isn't just something happening to me (so I'm not losing the plot!) and glad I didn't list this as a bug when it isn't. You make a good point about the preferred behaviour of developers so happy to wait and see what others think.

Perhaps it says more about my own workflow not being inefficient but I found it easier/quicker to make changes in editing directly in an editor (I've been using Atom) but using the Rasa X interface to review. Maybe I should stick to testing the chatbot in the CLI but I do like using the more graphical interface to get a truer feel/representation.

Is there a sense of a preferred workflow by Rasa developers (i.e. developing using CLI vs. Rasa X)? I appreciate this might be a question for the wider Rasa community but I am keen to learn of others' ideal setups for efficient developing.

**Comment by melindaloubser1** [comment]
It definitely makes sense that some things are easier in a code editor. 

Rasa X is intended for reviewing/annotating/etc chiefly once a bot is in production, or being made available for more than one user during testing, meaning it wouldn't be deployed in localmode at all, but on a server, and the newest model would most likely be uploaded & tagged via a CI/CD pipeline. For this reason,  how you use Rasa X for local development is up to what works for you, while there are more specific recommended workflows for server mode.

Personally, when I'm building  a bot I'm only using Rasa X in localmode to e.g. check that something displays right, or for a quick way to demo something. I develop in a code editor, or in a deployed (server) Rasa X for reviewing/annotating.

**Comment by jameshenderson12** [comment]
Thanks @melindaloubser1, I really appreciate your comments and taking the time to reply.
