### ISSUE TITLE
GitHub Actions: Deprecated short SHA

### ISSUE THREAD

**Issue by m-vdb** [RasaHQ/rasa#7826]
> On February 15th, GitHub Actions will remove support for referencing actions using the shortened version of a git commit SHA. This may cause some workflows in your repository to break. To fix these workflows, you will need to update the action reference to use the full commit SHA.
> 
> For example, if your workflow references actions/checkout@5a4ac90, you should change it to actions/checkout@5a4ac9002d0be2fb38bd78e4b4dbde5606d7042f. You can find the full commit SHA in the referenced action's repository.
> 
> This change is being made to align product functionality with our published security guidance which can be found at https://docs.github.com/en/actions/learn-github-actions/security-hardening-for-github-actions#using-third-party-actions

**Comment by m-vdb** [comment]
@tczekajlo @HotThoughts I don't know if it's already on your radar, but I thought I'd create the ticket for you! I've added it to your squad's inbox

**Comment by tczekajlo** [comment]
@m-vdb it's already on our radar :D https://github.com/RasaHQ/rasa-x/issues/4333 :D

**Comment by m-vdb** [comment]
arf my bad, closing this one then 💯
