### ISSUE TITLE
Notify team when scheduled model regression test fails

### ISSUE THREAD

**Issue by dakshvar22** [RasaHQ/rasa#7834]
**Description of Problem**:
Currently, when the scheduled model regression tests, any one of the configuration can silently fail on a dataset. Model training can fail because of various reasons like OOM, invalid configuration, etc. We need to manually go to the metabase dashboard and check if all configurations reported back a result for the last run.

**Overview of the Solution**:
It would be great if a message is delivered to a slack channel whenever any of the configuration fails during a scheduled run.
Note that this is only for scheduled runs and not for runs that are triggered by someone on a PR.

**Comment by tczekajlo** [comment]
@dakshvar22 Which channel should we use to set messages to?

**Comment by dakshvar22** [comment]
#product-research channel would be good.
