### ISSUE TITLE
Chatapi (Whatsapp) Custom Connector

### ISSUE THREAD

**Issue by jackabouaad** [RasaHQ/rasa#7841]
**Description of Problem**:
According to their website, "Chat API is a multifunctional API for Whatsapp. It is the most stable tool for business and programmers today, which can be integrated into any customer accounting system, send messages, notify users, and much more. Today Chat API works with more than 3 000 companies and programmers around the world and handles more than one billion user requests per month!"
Even though Rasa supports custom connectors, one that connects to Chatapi hasn't been developed yet.

**Overview of the Solution**:
My suggestion is to write a custom connector that connects to Chatapi (Whatsapp) webhook and send utterances to the sendMessage endpoint.

**Examples** (if relevant):
I will upload some soon...

**Definition of Done**:
What's done so far?
- [X] Initial webhook blueprint (InputChannel) and sendMessage call (OutputChannel) + Config in credentials.yml:
```
chatapi:
    base_url: "https://api.chat-api.com"
    instance_id: "<your instance id>"
    access_token: "<your access token>"
```
- [ ] Implementing remaining Chatapi endpoints to OutputChannel
- [ ] Refactoring Chatapi main class and helpers
- [ ] Writing test cases for the connector
- [ ] Feature described the docs
- [ ] Feature mentioned in the changelog

**Comment by sara-tagger** [comment]
Thanks for submitting this feature request 🚀 @melindaloubser1 will get back to you about it soon! ✨

**Comment by melindaloubser1** [comment]
@jackabouaad thanks for the PR! Usually with custom connectors, we recommend hosting it in a separate repository since there are many potential custom connectors, and including them in the Rasa codebase means they have to be maintained as part of the package. The ones that are included are  generally the most common channels.

@TyDunn Not sure in this case  - do you think this belongs in Rasa, or separately?

**Comment by TyDunn** [comment]
@melindaloubser1 I agree with you

@jackabouaad As with all channels, I think need to see stronger interest from the community before we consider adding this channel to the main Rasa Open Source codebase. A demo of bot that uses this channel could go a long way I think. The best demos I have seen are often a GitHub repo with a README that clearly explains how to try it out. This makes it easy for Rasa developers to fork / clone. Then, you can create a post about it on the Rasa forum and link to the repo

**Comment by jackabouaad** [comment]
Alright, I'll surely do so!

I apologize for my inexperience self and thank you for the info!

**Comment by melindaloubser1** [comment]
No problem, it's great that you're contributing =)
