### ISSUE TITLE
Add cosine similarity to Rasa X

### ISSUE THREAD

**Issue by jackabouaad** [RasaHQ/rasa#7842]
**Description of Problem**: At this stage, Rasa X helps you load training data and tag them using the Graphical User Interface. The problem is that such a way of loading data can prove to be challenging at a later stage if, while training the model, the developer notices that some intents are actually really close to each other which might increase the confusion rate between the two.

**Overview of the Solution**: Add a feature to Rasa X where developers interactively receive the highest cosine similarity rate between the sentence they're entering and say 5 sentences with the highest similarity score from other intents.

**Examples** (if relevant): I am not that experienced with front-end development so I'd need one who's more knowledgable to help me create such a prototype scenario.

**Definition of Done**: What needs to be there to consider this feature as done?

*   [ ] Develop the feature
*   [ ] Add unit test
*   [ ] Profile the feature (optimize if needed)
*   [ ] Feature described the docs
*   [ ] Feature mentioned in the changelog

**Comment by sara-tagger** [comment]
Thanks for submitting this feature request 🚀 @TyDunn will get back to you about it soon! ✨

**Comment by TyDunn** [comment]
Hi @jackabouaad. Thanks for sharing this idea! We are actually working on something quite *similar* to this right now. Would you be willing to give us feedback on it once it is ready? cc @abhilasharoy @koernerfelicia

**Comment by jackabouaad** [comment]
Of course @TyDunn!
I'd even love to help out with the development of such a feature!

**Comment by mjaycub** [comment]
@TyDunn @abhilasharoy does it make sense to move this ticket into CDD backlog?

**Comment by alexweidauer** [comment]
Thank you for raising this issue about Rasa X. We decided to stop supporting the Community Edition (free version) of ‘Rasa X’ (see more info here: https://rasa.com/blog/rasa-x-community-edition-changes/). That’s why we’ve closed your issue. We suggest that Rasa Enterprise customers raise the issue with our customer support team if they haven’t done so already.
