### ISSUE TITLE
Prediction failed due to the order of entities 

### ISSUE THREAD

**Issue by onejae** [RasaHQ/rasa#7850]
**Rasa version**:2.2.7

**Rasa SDK version** (if used & relevant):2.2.0

**Rasa X version** (if used & relevant):

**Python version**: 3.6.9

**Operating system** (windows, osx, ...): wsl2 on windows10

**Issue**: Right after executing 'rasa shell --debug' , I entered a message into prompt. It sometimes worked as I expected, but sometimes didn't. Once it works, it never fails in the same shell. However after re-launching the shell('rasa shell --debug') It could possibly be failed with log 'There is no memorised next action'. the percentage of success is 50% I guess. I tried it more than 20 times.

Here is the difference in the log

when succeed :

> <span class="error">[state 1]</span> user intent: search_vodaod_by_date | user entities: **('program_keyword', 'episode_number')** | previous action name: action_listen | slots: 

 {'episode_number': (1.0,), 'program_keyword': (1.0,)} 

when failed

> <span class="error">[state 1]</span> user intent: search_vodaod_by_date | user entities: **('episode_number', 'program_keyword')** | previous action name: action_listen | slots: 

 {'episode_number': (1.0,), 'program_keyword': (1.0,)} 

The only difference between those two is the order of entities mentioned in the log.

I tested the same message again with different entity order in stories.yml, and I found the order in stories.yml affects the prediction result. It worked when the order from logs matches with the order from stories.yml.

**Error (including full traceback)**:

**Command or request that led to error**:

**Content of configuration file (config.yml)** (if relevant):

**Content of domain file (domain.yml)** (if relevant):

**Comment by sara-tagger** [comment]
Thanks for the issue, @yennycheung will get back to you about it soon!

###### You may find help in the [docs](https://rasa.com/docs/) and the [forum,](https://forum.rasa.com/) too 🤗
