### ISSUE TITLE
Adding Sender Actions to Facebook channel

### ISSUE THREAD

**Issue by talhashaikh5** [RasaHQ/rasa#7858]
**Description of Problem**:
Right now there is no feature in facebook channel which will mark messages as **seen** and there is no "**typing**" status also.

![Typing Status](https://scontent-del1-1.xx.fbcdn.net/v/t39.2365-6/13480169_570751053131489_689799179_n.png?_nc_cat=111&ccb=2&_nc_sid=ad8a9d&_nc_ohc=5xYkezbTboAAX-mozBz&_nc_ht=scontent-del1-1.xx&oh=c25346391c57238bf4d09a55ed752259&oe=603EA864 "Typing Status")

**Overview of the Solution**:
I would like to add this feature in facebook channel. Right now rasa is using [fbmessenger ](http://https://github.com/rehabstudio/fbmessenger/ "this sdk ") in facebook channel. There is a feature to add Sender Action using [fbmessenger](http://https://github.com/rehabstudio/fbmessenger/ "fbmessenger") sdk

**Definition of Done**:
When messages are marked as **seen** and we can see **typing** status we can say this has been implemented

**Comment by sara-tagger** [comment]
Thanks for submitting this feature request 🚀 @tttthomasssss will get back to you about it soon! ✨

**Comment by tttthomasssss** [comment]
Hey @talhashaikh5 👋  - thanks very much for the issue.

Do you propose to implement this yourself?

**Comment by talhashaikh05** [comment]
@tttthomasssss Yes, I am implementing it I will raise a PR within 24 hours.

**Comment by talhashaikh5** [comment]
This has been already implemented in rasa 2.2.3, I was using rasa 1.10
