### ISSUE TITLE
Add case sensitivity toggle for all featurizers 

### ISSUE THREAD

**Issue by erohmensing** [RasaHQ/rasa#7866]
**Description of Problem**:

Case (in)sensitivity used to be handled by the WhitespaceTokenizer, which meant that in a pipeline that included this component the decision was made before it reached any featurizers. If `case_sensitive: False` was chosen, there was no way for a featurizer to process it differently.

This behavior was moved from the tokenizers to the featurizers since it is up to the featurizers how to assign vectors to given tokens. However, it was only added to the RegexFeaturizer, not all featurizers, so this behavior is not configurable for all of them. The CountVectorsFeaturizer is configurable, but under a different parameter, `lowercase`.

**Overview of the Solution**:

add a `case_sensitive` option to all featurizers, including regulating/deprecating the existing `lowercase` option on CountVectorsFeaturizer to match the others

**Comment by desmarchris** [comment]
@erohmensing same with this one, are you still working on it or want someone else to pick it up?

**Comment by erohmensing** [comment]
Someone else can pick it up! (lol at how late this response is, i'm sorry)
