### ISSUE TITLE
Rasa x not able to load all sentences in NLU inbox

### ISSUE THREAD

**Issue by Horizon733** [RasaHQ/rasa#7878]
**Rasa version**:

**Rasa SDK version** : 2.1.2

**Rasa X version** : 0.34

**Python version**: 3.7.6

**Operating system** (windows, osx, ...): Ubuntu

**Issue**:
While using Rasa X the NLU inbox is filled with 122 sentences but when I scroll to view more so that I can add in Nlu file it is not able to load. I am using Azure Virtual Machine with ubuntu. I have added screenshots for the same. I waited like half an hour and still, it is not able to load data. Since, after testing we needed Nlu data to get stored in nlu.yml. So, please look at this bug as soon as possible

![image](https://user-images.githubusercontent.com/57827233/106752669-bb41ca80-6650-11eb-9586-093bc7d051cc.png)

**Error (including full traceback)**:
```
No errors
```

**Command or request that led to error**:
```
rasa x --rasa-x-port 8002
```

**Content of configuration file (config.yml)** (if relevant):
```yml

```

**Content of domain file (domain.yml)** (if relevant):
```yml

```

**Comment by sara-tagger** [comment]
Thanks for raising this issue, @desmarchris will get back to you about it soon✨

###### Please also check out the [docs](https://rasa.com/docs/) and the [forum](https://forum.rasa.com/) in case your issue was raised there too 🤗

**Comment by yennycheung** [comment]
Is https://github.com/RasaHQ/rasa-x/issues/3182 the same issue?

**Comment by mjaycub** [comment]
Tracking this issue in a similar ticket in the Rasa X repo - https://github.com/RasaHQ/rasa-x/issues/3182

**Comment by mjaycub** [comment]
Closing as fixed in #4472 and will be shipped in the next release
