### ISSUE TITLE
Thnx

### ISSUE THREAD

**Issue by pritamdeshpande1985** [RasaHQ/rasa#7880]
**Description of Problem**:

**Overview of the Solution**:

**Examples** (if relevant):

**Blockers** (if relevant):

**Definition of Done**:

**Comment by sara-tagger** [comment]
Thanks for submitting this feature request 🚀 @wochinge will get back to you about it soon! ✨

**Comment by wochinge** [comment]
@pritamdeshpande1985 Closing this issue as it's empty.
