### ISSUE TITLE
Expose RabbitMQ Exchange as a Configurable Parameter

### ISSUE THREAD

**Issue by b-quachtran** [RasaHQ/rasa#7889]
**Overview of the Solution**:

Expose `RABBITMQ_EXCHANGE` as a configurable parameter in the endpoints.yml file for the Pika broker. 

**Definition of Done**:
- [ ] Tests are added
- [ ] Feature described the docs
- [ ] Feature mentioned in the changelog

**Comment by kaustuk** [comment]
Hi @b-quachtran I have already raised this issue. Here is the link of it https://github.com/RasaHQ/rasa/issues/7848
