### ISSUE TITLE
Behavior of list slots is inconsistent

### ISSUE THREAD

**Issue by alexyuwen** [RasaHQ/rasa#7896]
Suppose I have a slot of type list, and within a form, the slot is defined to extract entity values. In such cases, I have noticed that if a single entity value is extracted, the slot returns not a list containing that element, but rather the element itself. This is frustrating, since in my validation action where I validate each entity extracted, I need to separately consider the cases where a single vs. multiple entities were extracted.

Furthermore, if the slot is defined to extract values from multiple entities, and if the user utterance contains 1 instance of each of the 2 entities, then the slot only captures the entity that’s used first in the slot mapping definition in the domain.

You can find the original discussion here: [https://forum.rasa.com/t/why-do-slots-of-type-list-not-return-singleton-lists/39810/2](https://forum.rasa.com/t/why-do-slots-of-type-list-not-return-singleton-lists/39810/2)

(I have borrowed some language above from @samsucik).

**Comment by sara-tagger** [comment]
Thanks for raising this issue, @yennycheung will get back to you about it soon✨

###### Please also check out the [docs](https://rasa.com/docs/) and the [forum](https://forum.rasa.com/) in case your issue was raised there too 🤗

**Comment by ancalita** [comment]
@alexyuwen I believe this was fixed in rasa `2.6.2` (see here [changelog entry](https://rasa.com/docs/rasa/changelog/#bugfixes-39)).
