### ISSUE TITLE
Cannot terminate rasa action server and rasa run using “Ctrl + c” or “Ctrl + Pause” in command prompt

### ISSUE THREAD

**Issue by rasaworkshop** [RasaHQ/rasa#7901]
**Rasa version**: Rasa :2.2.0 **Rasa SDK version** (if used & relevant): Rasa sdk:2.2.0 **Rasa X version** (if used & relevant): Rasa X : 0.37 **Python version**: Python : 3.7.9 **Operating system** (windows, osx, ...): OS:RHEL 7 centos **Issue**: I have a Minimum viable bot that I run using rasa x command . I am able to terminate rasa x command ctrl+c But once I use enable-api flag to connect it web socket ctrl +c stops the server and bot but it doesn't return back to $ symbol hence goes to a hang state everytime. This was never a issue in Rasa 1.9 version with above OS conf .I am facing them after I trialed on 2.2.0 version.

Sometimes after a very long time it says Task impending in red and terminated but most of time how much ever you wait it doesn't comes out of hanged state .

**Command or request that led to error**:

rasa x --enable-api --cors "*"

**Error (including full traceback)**

[<span class="image-wrap" style="">![](https://user-images.githubusercontent.com/65162825/107179894-a2913600-69fd-11eb-8a7a-4e2445202c4f.png)</span>](https://user-images.githubusercontent.com/65162825/107179894-a2913600-69fd-11eb-8a7a-4e2445202c4f.png)

**Comment by rasaworkshop** [comment]
I found that on press of ctrl +c python3.7 process isn't killed rasa process are not kill though netstat -tanp shows no rasa core or rasa x running .Once I kill manually python3.7 the process hanged comes back to normal

**Comment by sara-tagger** [comment]
Thanks for the issue, @alopez will get back to you about it soon!

###### You may find help in the [docs](https://rasa.com/docs/) and the [forum,](https://forum.rasa.com/) too 🤗

**Comment by LionelBino** [comment]
This bug affect to me too

**Comment by parashar-lonewolf** [comment]
docker ps   # to list all dockers unleashed
docker stop [name of docker container]
and the rasa/rasa x will terminate
