### ISSUE TITLE
Users have to implement their own get_metadata not explicit enough in the docs

### ISSUE THREAD

**Issue by PROrock** [RasaHQ/rasa#7905]
**Description of Problem**:
In the docs https://rasa.com/docs/rasa/connectors/custom-connectors/ there is described, what is needed if you want to pass some metadata into a Rasa connector. However, IMHO it is written a bit misleading in a way, it seems you just have to send the metadata field in your JSON and it will be automatically available in the NLU/action server. But that is not the case, since currently no prepackaged Rasa channel, which reads this field. See overwrites of get_metadata function https://github.com/RasaHQ/rasa/blob/main/rasa/core/channels/channel.py#L144
  
Here's an example, that I'm not the only person, who finds it a bit misleading/surprising https://forum.rasa.com/t/how-to-pass-metadata-in-post-request-and-then-extract-it/15092/10

**Overview of the Solution**:
I think we should add some note to clarify this somewhere near these two sentences:
https://github.com/RasaHQ/rasa/blame/main/docs/docs/connectors/custom-connectors.mdx#L35
>If you need to use extra information from your front end in your custom actions, you can add this information in the metadata dict of your user message. This information will accompany the user message through the rasa server into the action server when applicable, where you can find it stored in the tracker. 

The note can look something like this:
>  (assuming you overwrote the function get_metadata)

**Definition of Done**:
- [ ] Docs are changed so this is more clear

**Comment by sara-tagger** [comment]
Thanks for submitting this feature request 🚀 @Imod7 will get back to you about it soon! ✨

**Comment by PROrock** [comment]
Hi again, I can see you've already added it to the documentation. I can see these two new lines:

> The InputChannel class's default implementation of get_metadata ignores all metadata. To extract metadata in a custom connector, implement the get_metadata method. 
So thanks for including it in the docs :-)
