### ISSUE TITLE
Add tests for histogram plotting

### ISSUE THREAD

**Issue by dakshvar22** [RasaHQ/rasa#7912]
**Description of Problem**:
Currently there are no tests for histogram plotting inside `rasa/utils/plotting.py`(`def plot_histogram`). These should be added, specifically related to the logic of creation of bins.

**Overview of the Solution**:
Tests for the above function

**Comment by ericoBandeira** [comment]
Hi, has this issue been solved?

**Comment by JEM-Mosig** [comment]
@ericoBandeira I was just about to pick it up. Do you want to do it?

**Comment by ericoBandeira** [comment]
@JEM-Mosig I would like to solve this issue! thank you so much

**Comment by JEM-Mosig** [comment]
@ericoBandeira Ok, great! Go ahead :) You can assign me to review your PR when you're ready.

**Comment by santosm46** [comment]
Hello! I'm working with @ericoBandeira and I have a question, where should the test be created? as `def plot_histogram` returns None, I think it has to be at `rasa/utils/test.py` where there is a function calling plot_curve from rasa.utils.plotting, it returns None such as plot_histogram.

**Comment by JEM-Mosig** [comment]
@santosm46 @ericoBandeira The test should be in a new `tests/utils/test_plotting.py` file. I'd recommend splitting the `plot_histogram` function into two parts: One (set of) function(s) that computes the bin specification and one function that does the matplotlib stuff. The function(s) that compute the bin specs are the ones that need tests.

**Comment by JEM-Mosig** [comment]
@santosm46 @ericoBandeira How is this coming along?

**Comment by santosm46** [comment]
Hi @JEM-Mosig
We're no longer working on this issue, thanks for the attention. Anyone can feel free to work on it.

**Comment by JEM-Mosig** [comment]
Oh, ok. I'll pick it up then.

**Comment by JEM-Mosig** [comment]
Looking into it, I just notice that the plot is missing some data (cutoffs are wrong). E.g. for:
```
[[1., 3., 8.], [2., 3., 3.]]
```
Will fix this with this issue, too.
