### ISSUE TITLE
Retrieve conversation tracker does not return previous sessions with include_events=ALL

### ISSUE THREAD

**Issue by nbeuchat** [RasaHQ/rasa#7913]
**Rasa version**: 2.2.9

**Rasa SDK version** (if used & relevant): 2.2.0

**Rasa X version** (if used & relevant): N/A

**Python version**: 3.7.9

**Operating system** (windows, osx, ...): Ubuntu

**Issue**: When using the [Retrieve conversation tracker endpoint](https://rasa.com/docs/rasa/pages/http-api#operation/getConversationTracker), I cannot retrieve events that happened before the last session started event even though I used `include_events=ALL` as a query parameter. When using the `until` query parameter, it also does not include events before the last session started event.

How can I retrieve stories from older sessions? Right now I need to go to the database directly to do that.

**Command or request that led to error**:

GET `protocole`://`url`/conversations/`sender_id`/story?token=`token`&include_events=ALL

**Comment by sara-tagger** [comment]
Thanks for the issue, @erohmensing will get back to you about it soon!

###### You may find help in the [docs](https://rasa.com/docs/) and the [forum,](https://forum.rasa.com/) too 🤗

**Comment by erohmensing** [comment]
Hi @nbeuchat, sorry for the late response. Can you provide info about which tracker store you are using?

**Comment by nbeuchat** [comment]
Sure! We are using a PostgreSQL tracker store.

**Comment by erohmensing** [comment]
Thanks so much! Also, it looks like you're actually using the [retrieve an end-to-end story](https://rasa.com/docs/rasa/pages/http-api#operation/getConversationStory) endpoint, which ends in `/story` (this is not the one you linked to) 

If you want to use the get conversation tracker endpoint, it should end in `tracker` and the `include_events=ALL` should be correct. 

If you want to get the conversation as an end-to-end story as you currenly are doing, but want to include events from all sessions, you should use the query param `all_sessions=true`. I agree though that the behavior of `until` on that endpoint not including earlier events is a bit confusing!

**Comment by nbeuchat** [comment]
Arf yes, you are right, I mixed up both endpoints! 

> If you want to use the get conversation tracker endpoint, it should end in /tracker and the include_events=ALL should be correct.

Unfortunately, the issue described is still there. When I try to retrieve the whole tracker as JSON using the `/tracker` endpoint and the `include_events=ALL` parameter, it does not return earlier events. 

For the `all_sessions=true`, I have issues testing it at the moment because of another issue (#8114)
