### ISSUE TITLE
Implementation proposal: IntentTEDPolicy

### ISSUE THREAD

**Issue by TyDunn** [RasaHQ/rasa#7914]
[Slack thread](https://rasa-hq.slack.com/archives/C36SS4N8M/p1612803658029400?thread_ts=1610748702.073800&cid=C36SS4N8M)

**Definition of done**
- [x] Meeting between two enable squad members to figure out open questions
- [x] Read / discuss / align with research on [scope document](https://docs.google.com/document/d/1kjZD59NtnvAkxSfu6sjLzgDucTQT8LJhdfZnILCDVcE/edit)
- [ ] Draft implementation proposal and get feedback from others
- [ ] Ensure @RasaHQ/practice-cdd is involved in the implementation proposal re: incorporating this into Rasa X / Enterprise (cc @yennycheung)
- [ ] Determine what research (@dakshvar22 and others) can start implementing before we are able to get to it
- [ ] Complete O3KR1: Create 1 shared implementation proposal between Research and Engineering

**Comment by wochinge** [comment]
1. Do an Enable squad meeting
 - come up with next steps
 - brainstorm ideas for the implementation (should this be in Rasa Open Source, how do we make this information accessible to Rasa X, etc.)

**Comment by dakshvar22** [comment]
@wochinge @joejuzl  Lmk if you folks are planning to jump on a call to discuss the implementation proposal. I am happy to join as well.

**Comment by joejuzl** [comment]
Thanks @dakshvar22, the first step will be meeting just within our squad so we can figure out our processes and next steps. We will reach out to you after, once we've figure that out.

**Comment by wochinge** [comment]
[A list of different approaches with their pros and cons](https://www.notion.so/rasa/IntentTedPolicy-Approaches-c4801eb7a3d84a8bab7094a9efdefd9b)

**Comment by edmacovaz** [comment]
@TyDunn @wochinge I've had a look through the document and added a comment, but it would be useful to know if there's any particular feedback/comments from me that would be helpful.
