### ISSUE TITLE
Tokenizers: Punctuation and Stopwords

### ISSUE THREAD

**Issue by koaning** [RasaHQ/rasa#7917]
I got a question during the Rasa Summit workshop about punctuation and stopwords. A user had a pipeline that somehow picked up that `"Who are you?"` and `"Who are you?????"` were two completely different intents. I was not able to dive deep into the specific example but the user noticed that punctuation was not ignored by the spaCy tokenizer. This got me thinking about stopwords in general, and punctuation specifically. 

I believe our `CountvectorFeaturizer` is currently set up to ignore punctuation, but it's explained on [sklearn docs](https://scikit-learn.org/stable/modules/generated/sklearn.feature_extraction.text.CountVectorizer.html), not on our own docs. This is great for sparse features, but dense features may still be generated for punctuation. 

So a few questions: 

- Would we want to be able to configure our tokenizers to allow for stopword lists in general? 
- Would we want to be able to configure our tokenizers to remove punctuation specifically? 
- Should we update our docs with a note that our CountVectorizer removes punctuation unless configured not to do so?

**Comment by alopez** [comment]
@koaning is this something you want to look into?

**Comment by koaning** [comment]
I can add a component in NLU examples that attempts to remove stopwords before it is passed to a tokenizer. 

@alopez or are you referring to the docs change? I can do both, mainly checking to see if you agree this would be a good docs-change.

**Comment by QuanZ9** [comment]
@koaning is this still on your radar? we have similar issues with stopwords. do you know what's the difference between adding a preprocessing component and removing stopwords inside a tokenizer? I plan to try the latter but would love to get some suggestions from someone with more insights.

**Comment by koaning** [comment]
I'm contemplating adding a component to [rasa-nlu-examples](https://github.com/RasaHQ/rasa-nlu-examples) that removes stopwords before they are processed by a tokeniser. I haven't found the time for it yet, but the issue for the component is [here](https://github.com/RasaHQ/rasa-nlu-examples/issues/59).

One thing deserves mentioning. Since making this issue I've also realized that stopwords are [a much harder problem than I initially anticipated](https://koaning.io/til/2021-08-06-stopwords/).

**Comment by koaning** [comment]
I ended up making an implementation today, viewable at [this PR](https://github.com/RasaHQ/rasa-nlu-examples/pull/142). 

@alopez from my end this can already be a custom solution for folks who are really stuck on the stopwords. That means that 2/3 questions are answered which leaves me to the documentation. 

I could add a sentence to the docs that make it clear that our CountVectorFeaturizer ignores punctuation. Once that's in, I'd argue this issue is taken care of. Any objections to this?

**Comment by koaning** [comment]
Scratch that! 

To quote [the sklearn docs](https://scikit-learn.org/stable/modules/generated/sklearn.feature_extraction.text.CountVectorizer.html): 

> **token_pattern**: Regular expression denoting what constitutes a “token”, only used if `analyzer == 'word'`. The default regexp select tokens of 2 or more alphanumeric characters (punctuation is completely ignored and always treated as a token separator).

The effect is caused by the tokeniser in scikit-learn. In scikit-learn, the tokeniser works from inside of the countvectoriser. In our case, the punctuation is handled by the tokeniser outside of the counvectoriser. 

All in all. I think we can close this issue.

**Comment by koaning** [comment]
To anybody interested, the experimental stopwords removal component is documented [here](https://rasahq.github.io/rasa-nlu-examples/docs/meta/stopwords/).
