### ISSUE TITLE
Docs and `rasa data validate` do not recognise response selector format.

### ISSUE THREAD

**Issue by koaning** [RasaHQ/rasa#7918]
Our docs currently explain that responses for response selection need to be added to the [domain.yml file](https://rasa.com/docs/rasa/chitchat-faqs/#5-defining-the-responses). I did this, but got errors when running: `rasa data validate`.

I then found [this issue on our forum](https://forum.rasa.com/t/retrieval-intents-throws-errors-in-rasa-data-validate/37186) which prompted me to move the responses to my `nlu.yml` file. I confirmed that our [sara demo also currently does this](https://github.com/RasaHQ/rasa-demo/blob/master/data/nlu/responses/responses.yml). After doing this I was able to run `rasa train; rasa shell` and everything seems to run just fine. But! The `rasa data validate` command still fails.

This is the error that I currently see;

> rasa data validate 2021-02-09 16:02:10 INFO rasa.validator - Validating intents... 2021-02-09 16:02:10 INFO rasa.validator - Validating uniqueness of intents and stories... /Users/vincent/Development/rasa-form-examples/venv/lib/python3.7/site-packages/rasa/shared/utils/io.py:93: UserWarning: The example 'good afternoon' was found labeled with multiple different intents in the training data. Each annotated message should only appear with one intent. You should fix that conflict The example is labeled with: goodbye, greet. 2021-02-09 16:02:10 INFO rasa.validator - Validating utterances... /Users/vincent/Development/rasa-form-examples/venv/lib/python3.7/site-packages/rasa/shared/utils/io.py:93: UserWarning: There is no template for the utterance action 'utter_chitchat'. The action is listed in your domains action list, but there is no template defined with this name. You should add a template with this key. More info at [https://rasa.com/docs/rasa/actions#utterance-actions](https://rasa.com/docs/rasa/actions#utterance-actions) Project validation completed with errors.

The first error in this log is fine, it's the second error that is making the validation fail with errors.

These are my Rasa versions.

rasa --version Rasa Version : 2.2.7 Rasa SDK Version : 2.2.0 Rasa X Version : 0.35.0 Python Version : 3.7.7 Operating System : Darwin-19.3.0-x86_64-i386-64bit

To make it easy to reproduce and out what might be going wrong I've hosted the project on [here](https://github.com/RasaHQ/rasa-form-examples). The example is in the folder with the response selection.

Just to check @JustinaPetr, didn't you also notice this?

**Comment by JustinaPetr** [comment]
@koaning Yes, I noticed that after doing a workshop, unfortunately. In general, if I follow the docs `rasa train` works, but it throws a warning regarding the `utter_chitchat` being included into the domain.yml but no response defined
