### ISSUE TITLE
DucklingEntityExtractor: Connection sharing / pooling

### ISSUE THREAD

**Issue by Mazyod** [RasaHQ/rasa#7919]
**Description of Problem**: We are using DucklingEntityExtractor at a high rate, and it is generating lots of logs as such:

 rasa_worker_1 | 2021-02-09 15:21:46,376: [http://duckling:8000](http://duckling:8000) "POST /parse HTTP/1.1" 200 None
 rasa_worker_1 | 2021-02-09 15:21:46,427: Starting new HTTP connection (1): duckling:8000
 rasa_worker_1 | 2021-02-09 15:21:46,430: [http://duckling:8000](http://duckling:8000) "POST /parse HTTP/1.1" 200 None
 ...

One might say the issue is with the logging level, but finding such logs is a concern in terms of how efficient the code is.

**Overview of the Solution**: We figured we could write a custom components that behaves the same way as rasa.DucklingEntityExtractor, but it would have a `requests.Session` to share the connection across multiple calls and such, instead of the repeated setup/teardown that's happening now.

**Definition of Done**:

*   [ ] Implement connection pooling/sharing with timeout for DucklingEntityExtractor
*   [ ] Tests are added
*   [ ] Feature mentioned in the changelog

**Comment by Mazyod** [comment]
Example to show difference between using `Session` vs `request` directly:

```python
>>> session.get('https://www.google.com')
DEBUG:urllib3.connectionpool:https://www.google.com:443 "GET / HTTP/1.1" 200 None
<Response [200]>
>>> requests.get('https://www.google.com')
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): www.google.com:443
DEBUG:urllib3.connectionpool:https://www.google.com:443 "GET / HTTP/1.1" 200 None
<Response [200]>
```

**Comment by sara-tagger** [comment]
Thanks for submitting this feature request 🚀 @Ghostvv will get back to you about it soon! ✨

**Comment by scguang301** [comment]
endpoint use http request,  now each request  need create tcp connect,  this is slow。 this can use connect pool  to  quickly。
