### ISSUE TITLE
Delete multiple instances of data at one time in Rasa X interface

### ISSUE THREAD

**Issue by jameshenderson12** [RasaHQ/rasa#7930]
**Description of Problem**: Primarly, as a bit of a time-saver, it would be great if the Rasa X interface could support deleting multiple NLU data items in one go (in addition to currently allowing to delete items individually). Currently, there have been a few ocassions where I have wanted to, for example, remove more than 1 'Story' or 'Response' at a time and it appears that currently this is only achievable on a one-by-one basis in the Rasa X GUI.

**Overview of the Solution**: On each or any of the pages, "NLU data", "Responses", "Stories", "Rules", it could add to the user experience and potentially the development efficiency, if there was a feature to delete multiple data items/instances in addition to the existing 'delete' icon to remove items individually. If possible, it would be good if the user was prompted to clarify if they wish to delete the selected items so that they have a chance to change their mind. Otherwise, it could significantly change their project if they delete a lot of their work unintentionally.

**Definition of Done**:

*   [ ] Add feature to "NLU data", "Responses", "Stories" and "Rules" pages to enable the user to select and delete multiple instances of data at one time.
*   [ ] Set a prompt to clarify if the user if the user is sure they want to delete the multiple items
*   [ ] Tests carried out to see that the function performs as described/intended
*   [ ] Add feature description to any relevant support docs
*   [ ] Have feature mentioned in the changelog

**Comment by sara-tagger** [comment]
Thanks for submitting this feature request 🚀 @rgstephens will get back to you about it soon! ✨

**Comment by rgstephens** [comment]
@jameshenderson12 Thanks for the suggestion. Adding this as an enhancement request.

**Comment by alexweidauer** [comment]
Thank you for raising this issue about Rasa X. We decided to stop supporting the Community Edition (free version) of ‘Rasa X’ (see more info here: https://rasa.com/blog/rasa-x-community-edition-changes/). That’s why we’ve closed your issue. We suggest that Rasa Enterprise customers raise the issue with our customer support team if they haven’t done so already.
