### ISSUE TITLE
Issues because of non unique sender_id 

### ISSUE THREAD

**Issue by amardeep2006** [RasaHQ/rasa#7941]
**Rasa version**: 2.2.9

**Rasa SDK version** (if used & relevant):

**Rasa X version** (if used & relevant): 0.35.1

**Python version**:3.6.8

**Operating system** (windows, osx, ...): Windows 10

**Issue**: I recently used a chatbot widget which uses REST channel to talk to rasa server. The widget had hardcoded sender_id .
This causes multiple issues :
1. The responses gets jumbled up if multiple concurrent users start using the widgets .
2. All the events on rasa database gets logged under hardcoded sender_id , sender_id is stored as conversation_id as well. 
3. If I see from RASA X UI there is just one conversation and all the conversation transcripts are logged under it.

I feel Rasa should not rely on sender_id for conversation_id and maintaining sessions . Rather it should generate unique conversation_id for a particular session.

Workaround : I made the sender_id unique by generating is every time chatbot widget loads but Rasa server should be able to handle this issue .

**Error (including full traceback)**:
```

```

**Command or request that led to error**:
```

```

**Content of configuration file (config.yml)** (if relevant):
```yml

```

**Content of domain file (domain.yml)** (if relevant):
```yml

```

**Comment by sara-tagger** [comment]
Thanks for the issue, @yennycheung will get back to you about it soon!

###### You may find help in the [docs](https://rasa.com/docs/) and the [forum,](https://forum.rasa.com/) too 🤗

**Comment by mjaycub** [comment]
@chdorner this seems like it also involves some discussion and ofc backend work, wdyt?

**Comment by chdorner** [comment]
Hi @amardeep2006, I think the issue here is that the `sender_id` is hardcoded and contains the same value for every user using the widget. It should be an identifier for a given end-user, which will then in turn show the conversations correctly in Rasa X.
