### ISSUE TITLE
Investigate yaml schema validation

### ISSUE THREAD

**Issue by wochinge** [RasaHQ/rasa#7954]
**Description of Problem**:
When we read YAML training data files, we validate them against a schema. [This is currently taking a lot of time](https://github.com/RasaHQ/rasa/issues/7892#issuecomment-778302866). Skipping this step e.g. brings down the training data reading times from 18 minutes to 8 minutes.

**Overview of the Solution**:
* is there a faster library? 
* Can we accelerate our current library?
* Should we add a flag to the CI to disable the schema validation?

**Definition of Done**:
- [ ] Propose next steps to speed up the YAML schema validation

**Comment by wochinge** [comment]
related https://github.com/RasaHQ/rasa/issues/7977

We should also double check if the [schema extension here](https://github.com/RasaHQ/rasa/blob/b1fc73f3f238905ddd55f50e75bb494b8e9188d9/rasa/shared/utils/validation.py#L154) is needed or can be accelerated

**Comment by joejuzl** [comment]
See: https://json-schema-everywhere.github.io/yaml#:~:text=While%20YAML%20has%20advanced%20features,supported%20choice%20for%20YAML%20validation.

**Comment by gausie** [comment]
We should consider using jsonschema (and making the schemas public)

**Comment by alwx** [comment]
We decided to drop this one because the performance is good already and because we have more important stuff to work on.
