### ISSUE TITLE
pipenv dependency resolution failure

### ISSUE THREAD

**Issue by sjpritchard** [RasaHQ/rasa#7962]
**Rasa version**: 2.3.0 **Rasa SDK version** (if used & relevant): **Rasa X version** (if used & relevant): **Python version**: 3.8.6 **Operating system** (windows, osx, ...): Ubuntu 20.10 **pipenv version**: 2020.11.15 **Issue**: Rasa installation with pipenv fails.

Steps:

pipenv --three pipenv install rasa

**Error (including full traceback)**:

➜ rasatest pipenv install rasa Installing rasa... Adding rasa to Pipfile's <span class="error">[packages]</span>... 
 <g-emoji class="g-emoji" alias="heavy_check_mark" fallback-src="https://github.githubassets.com/images/icons/emoji/unicode/2714.png">
 ✔ 
 </g-emoji> Installation Succeeded Pipfile.lock not found, creating... Locking <span class="error">[dev-packages]</span> dependencies... Locking <span class="error">[packages]</span> dependencies... Building requirements... Resolving dependencies... ✘ Locking Failed! <span class="error">[ResolutionFailure]</span>: File "/usr/local/lib/python3.8/dist-packages/pipenv/resolver.py", line 741, in _main <span class="error">[ResolutionFailure]</span>: resolve_packages(pre, clear, verbose, system, write, requirements_dir, packages, dev) <span class="error">[ResolutionFailure]</span>: File "/usr/local/lib/python3.8/dist-packages/pipenv/resolver.py", line 702, in resolve_packages <span class="error">[ResolutionFailure]</span>: results, resolver = resolve( <span class="error">[ResolutionFailure]</span>: File "/usr/local/lib/python3.8/dist-packages/pipenv/resolver.py", line 684, in resolve <span class="error">[ResolutionFailure]</span>: return resolve_deps( <span class="error">[ResolutionFailure]</span>: File "/usr/local/lib/python3.8/dist-packages/pipenv/utils.py", line 1395, in resolve_deps <span class="error">[ResolutionFailure]</span>: results, hashes, markers_lookup, resolver, skipped = actually_resolve_deps( <span class="error">[ResolutionFailure]</span>: File "/usr/local/lib/python3.8/dist-packages/pipenv/utils.py", line 1108, in actually_resolve_deps <span class="error">[ResolutionFailure]</span>: resolver.resolve() <span class="error">[ResolutionFailure]</span>: File "/usr/local/lib/python3.8/dist-packages/pipenv/utils.py", line 833, in resolve <span class="error">[ResolutionFailure]</span>: raise ResolutionFailure(message=str(e)) <span class="error">[pipenv.exceptions.ResolutionFailure]</span>: Warning: Your dependencies could not be resolved. You likely have a mismatch in your sub-dependencies. First try clearing your dependency cache with $ pipenv lock -~~clear, then try the original command again. Alternatively, you can use $ pipenv install --skip-lock to bypass this mechanism, then run $ pipenv graph to inspect the situation. Hint: try $ pipenv lock --pre if it is a pre-release dependency. ERROR: Could not find a version that matches multidict<5.0,<6.0,>=4.5,>=4.6,>=5.0 (from rasa==2.3.0~~>~~r /tmp/pipenvopk766uprequirements/pipenv-ezic02dd-constraints.txt (line 2)) Tried: 1.0.1, 1.0.2, 1.0.3, 1.1.0, 1.2.0, 1.2.1, 1.2.2, 2.0.0, 2.0.1, 2.1.0, 2.1.1, 2.1.2, 2.1.3, 2.1.4, 2.1.5, 2.1.6, 3.0.0, 3.1.0, 3.1.1, 3.1.3, 3.2.0, 3.3.0, 3.3.1, 3.3.2, 4.0.0, 4.1.0, 4.2.0, 4.3.0, 4.3.1, 4.4.0, 4.4.1, 4.4.2, 4.5.0, 4.5.1, 4.5.2, 4.6.0, 4.6.0, 4.6.1, 4.6.1, 4.7.0, 4.7.1, 4.7.1, 4.7.2, 4.7.2, 4.7.3, 4.7.3, 4.7.4, 4.7.4, 4.7.5, 4.7.5, 4.7.6, 4.7.6, 5.0.0, 5.0.0, 5.0.1, 5.0.1, 5.0.2, 5.0.2, 5.1.0, 5.1.0 Skipped pre-versions: 1.0.0a0, 1.1.0b1, 1.1.0b2, 1.1.0b4, 1.1.0b5, 1.1.0b6, 1.1.0b7, 1.1.0b8, 3.1.3a0, 3.1.4a1, 3.1.4a2, 3.1.4a3, 3.2.0a3, 3.2.1a0, 4.4.0a0, 4.4.0a1, 4.4.0a2, 4.4.0a3, 4.4.0a4, 4.4.0a5, 4.4.0a6, 4.4.0a7, 4.4.0a8, 4.4.0a9, 4.4.0a10, 4.4.0a11, 4.4.0a12, 4.4.0a13, 4.4.0a14, 4.4.0a15, 4.4.0a16, 4.4.0a17, 4.4.0a18, 4.4.0a19, 4.4.0a20, 4.4.0a21, 4.4.0a22, 4.4.0a23, 4.4.0a24, 4.4.0a25, 4.4.0a26, 4.4.0a27, 4.4.0a28, 4.4.0a29, 4.4.0a30, 4.4.0a31, 4.4.0a32, 4.4.0a33, 4.4.0a34, 4.4.0a35, 4.4.0a36, 4.4.0a37, 4.4.0a38, 4.4.0a39, 4.4.0a40, 4.4.0a42, 4.6.0a2, 4.6.0a2, 4.6.0a3, 4.6.0a3 There are incompatible versions in the resolved dependencies: multidict<5.0,>=4.5 (from aiohttp==3.6.3~~>rasa==2.3.0->~~r /tmp/pipenvopk766uprequirements/pipenv-ezic02dd-constraints.txt (line 2)) multidict<5.0,>=4.6 (from rasa==2.3.0~~>~~r /tmp/pipenvopk766uprequirements/pipenv-ezic02dd-constraints.txt (line 2)) multidict<6.0,>=5.0 (from sanic==20.12.1~~>rasa==2.3.0->-r /tmp/pipenvopk766uprequirements/pipenv-ezic02dd-constraints.txt (line 2))

**Command or request that led to error**:

pipenv install rasa

Updated Pipfile with workaround described at: [https://github.com/RasaHQ/rasa/issues/7124#issuecomment-725427948](https://github.com/RasaHQ/rasa/issues/7124#issuecomment-725427948) which resulted in a different dependency resolution error:

<span class="error">[packages]</span> regex = "==2020.9.27" sanic = "<19.12.3" scikit-learn ="<0.24.0" rasa = "*"

➜ rasatest pipenv install rasa Installing rasa... Adding rasa to Pipfile's <span class="error">[packages]</span>... 
 <g-emoji class="g-emoji" alias="heavy_check_mark" fallback-src="https://github.githubassets.com/images/icons/emoji/unicode/2714.png">
 ✔ 
 </g-emoji> Installation Succeeded Pipfile.lock not found, creating... Locking <span class="error">[dev-packages]</span> dependencies... Locking <span class="error">[packages]</span> dependencies... Building requirements... Resolving dependencies... ✘ Locking Failed! <span class="error">[ResolutionFailure]</span>: File "/usr/local/lib/python3.8/dist-packages/pipenv/resolver.py", line 741, in _main <span class="error">[ResolutionFailure]</span>: resolve_packages(pre, clear, verbose, system, write, requirements_dir, packages, dev) <span class="error">[ResolutionFailure]</span>: File "/usr/local/lib/python3.8/dist-packages/pipenv/resolver.py", line 702, in resolve_packages <span class="error">[ResolutionFailure]</span>: results, resolver = resolve( <span class="error">[ResolutionFailure]</span>: File "/usr/local/lib/python3.8/dist-packages/pipenv/resolver.py", line 684, in resolve <span class="error">[ResolutionFailure]</span>: return resolve_deps( <span class="error">[ResolutionFailure]</span>: File "/usr/local/lib/python3.8/dist-packages/pipenv/utils.py", line 1395, in resolve_deps <span class="error">[ResolutionFailure]</span>: results, hashes, markers_lookup, resolver, skipped = actually_resolve_deps( <span class="error">[ResolutionFailure]</span>: File "/usr/local/lib/python3.8/dist-packages/pipenv/utils.py", line 1108, in actually_resolve_deps <span class="error">[ResolutionFailure]</span>: resolver.resolve() <span class="error">[ResolutionFailure]</span>: File "/usr/local/lib/python3.8/dist-packages/pipenv/utils.py", line 833, in resolve <span class="error">[ResolutionFailure]</span>: raise ResolutionFailure(message=str(e)) <span class="error">[pipenv.exceptions.ResolutionFailure]</span>: Warning: Your dependencies could not be resolved. You likely have a mismatch in your sub-dependencies. First try clearing your dependency cache with $ pipenv lock -~~clear, then try the original command again. Alternatively, you can use $ pipenv install --skip-lock to bypass this mechanism, then run $ pipenv graph to inspect the situation. Hint: try $ pipenv lock --pre if it is a pre-release dependency. ERROR: Could not find a version that matches python-engineio<3.14,>=3.11,>=4 (from rasa==2.3.0~~>~~r /tmp/pipenvzjelhfjvrequirements/pipenv-13sv44g9-constraints.txt (line 2)) Tried: 0.1.0, 0.2.0, 0.3.0, 0.3.1, 0.4.0, 0.5.0, 0.5.1, 0.6.0, 0.6.1, 0.6.2, 0.6.3, 0.6.4, 0.6.5, 0.6.6, 0.6.7, 0.6.8, 0.6.9, 0.7.0, 0.7.1, 0.7.2, 0.8.0, 0.8.1, 0.8.2, 0.8.3, 0.8.4, 0.8.5, 0.8.6, 0.8.7, 0.8.8, 0.9.0, 0.9.1, 0.9.2, 1.0.0, 1.0.1, 1.0.2, 1.0.3, 1.0.4, 1.1.0, 1.1.1, 1.1.2, 1.2.0, 1.2.1, 1.2.2, 1.2.3, 1.2.4, 1.3.0, 1.3.1, 1.3.2, 1.4.0, 1.5.0, 1.5.1, 1.5.2, 1.5.3, 1.5.4, 1.6.0, 1.6.1, 1.7.0, 1.7.0, 2.0.0, 2.0.0, 2.0.1, 2.0.1, 2.0.2, 2.0.2, 2.0.3, 2.0.3, 2.0.4, 2.0.4, 2.1.0, 2.1.0, 2.1.1, 2.1.1, 2.2.0, 2.2.0, 2.3.0, 2.3.0, 2.3.1, 2.3.1, 2.3.2, 2.3.2, 3.0.0, 3.0.0, 3.1.0, 3.1.0, 3.1.1, 3.1.1, 3.1.2, 3.1.2, 3.2.0, 3.2.0, 3.2.1, 3.2.1, 3.2.2, 3.2.2, 3.2.3, 3.2.3, 3.3.0, 3.3.0, 3.3.1, 3.3.1, 3.3.2, 3.3.2, 3.4.0, 3.4.0, 3.4.1, 3.4.1, 3.4.2, 3.4.2, 3.4.3, 3.4.3, 3.4.4, 3.4.4, 3.5.0, 3.5.0, 3.5.1, 3.5.1, 3.5.2, 3.5.2, 3.6.0, 3.6.0, 3.7.0, 3.7.0, 3.8.0, 3.8.0, 3.8.1, 3.8.1, 3.8.2, 3.8.2, 3.8.2.post1, 3.8.2.post1, 3.9.0, 3.9.0, 3.9.1, 3.9.1, 3.9.2, 3.9.2, 3.9.3, 3.9.3, 3.10.0, 3.10.0, 3.11.0, 3.11.0, 3.11.1, 3.11.1, 3.11.2, 3.11.2, 3.12.0, 3.12.0, 3.12.1, 3.12.1, 3.13.0, 3.13.0, 3.13.1, 3.13.1, 3.13.2, 3.13.2, 3.14.0, 3.14.0, 3.14.1, 3.14.1, 3.14.2, 3.14.2, 4.0.0, 4.0.0 There are incompatible versions in the resolved dependencies: python-engineio<3.14,>=3.11 (from rasa==2.3.0~~>~~r /tmp/pipenvzjelhfjvrequirements/pipenv-13sv44g9-constraints.txt (line 2)) python-engineio>=4 (from python-socketio==5.0.4~~>rasa==2.3.0->-r /tmp/pipenvzjelhfjvrequirements/pipenv-13sv44g9-constraints.txt (line 2))

**Comment by sara-tagger** [comment]
Thanks for the issue, @samsucik will get back to you about it soon!

###### You may find help in the [docs](https://rasa.com/docs/) and the [forum,](https://forum.rasa.com/) too 🤗

**Comment by sjpritchard** [comment]
Tried installing instead with virtualenv and pip 21.0.1, and received the following errors:
```
ERROR: tensorflow 2.3.2 has requirement gast==0.3.3, but you'll have gast 0.4.0 which is incompatible.
ERROR: sanic 20.12.2 has requirement multidict<6.0,>=5.0, but you'll have multidict 4.7.6 which is incompatible.
ERROR: sanic-jwt 1.6.0 has requirement pyjwt==2.0.0, but you'll have pyjwt 2.0.1 which is incompatible.
ERROR: aiohttp 3.6.3 has requirement chardet<4.0,>=2.0, but you'll have chardet 4.0.0 which is incompatible.
ERROR: python-socketio 5.0.4 has requirement python-engineio>=4, but you'll have python-engineio 3.13.2 which is incompatible.
```

**Comment by 8bit-code** [comment]
Having the same issue @sara-tagger (OSX, Win & Ubuntu).

**Comment by alwx** [comment]
@8bit-code what's the version of Rasa you use?

**Comment by lobiCode** [comment]
I also have the same issue. RASA==2.6.0

**Comment by rodrigocaus** [comment]
I also have the same issue.
Same as @lobiCode, using rasa 2.6.2

**Comment by asmaier** [comment]
With Rasa 2.4.3 the issue

```
There are incompatible versions in the resolved dependencies:
  python-engineio<3.14,>=3.11 (from rasa==2.3.0->-r /tmp/pipenvzjelhfjvrequirements/pipenv-13sv44g9-constraints.txt (line 2))
  python-engineio>=4 (from python-socketio==5.0.4->rasa==2.3.0->-r /tmp/pipenvzjelhfjvrequirements/pipenv-13sv44g9-constraints.txt (line 2))
```
  
  still exists. The workaround from https://github.com/RasaHQ/rasa/issues/7124#issuecomment-725427948 doesn't work for 2.4.3, but it does work for 2.5.x and 2.6.x . So it seems one has to upgrade Rasa to 2.5.x or 2.6.x, if you use pipenv.
