### ISSUE TITLE
RasaX SchemaError: responses with custom dictionary throw SchemaError

### ISSUE THREAD

**Issue by JulianGerhard21** [RasaHQ/rasa#7966]
**Rasa version**: 2.2.10

**Rasa SDK version** (if used & relevant): 2.2.10

**Rasa X version** (if used & relevant): 0.35.1

**Python version**: 3.6

**Operating system** (windows, osx, ...): Ubuntu 18.04 (Docker)

**Issue**: 

Assuming the following response format in `domain.yml` (imagine there are way more entries):

```
  utter_ask_topic:
    - custom:
        email: nan
        feedback_utterance: utter_ask_topic
        is_feedback: true
        phone: nan
        text: utter_ask_topic
        url: nan
```

I want to connect the AI lying in a repository to Rasa X running as a manual docker setup. After doing this, the following error occurs:

**Error (including full traceback)**:
```
rasa-x_1            |   rasa.shared.utils.io.raise_warning(
rasa-x_1            | Job "run_background_synchronization (trigger: cron[minute='*'], next run at: 2021-02-16 12:57:00 UTC)" raised an exception
rasa-x_1            | Traceback (most recent call last):
rasa-x_1            |   File "/usr/local/lib/python3.8/dist-packages/rasa/shared/utils/validation.py", line 160, in validate_yaml_schema
rasa-x_1            |     c.validate(raise_exception=True)
rasa-x_1            |   File "/usr/local/lib/python3.8/dist-packages/pykwalify/core.py", line 166, in validate
rasa-x_1            |     raise SchemaError(u"Schema validation failed:\n - {error_msg}.".format(
rasa-x_1            | pykwalify.errors.SchemaError: <SchemaError: error code 2: Schema validation failed:
rasa-x_1            |  - Value '[ordereddict([('text', 'utter_ask_topic')]), ordereddict([('url', 'nan')]), ordereddict([('email', 'nan')]), ordereddict([('phone', 'nan')]), ordereddict([('is_feedback', True)]), ordereddict([('feedback_utterance', 'utter_ask_topic')])]' is not a dict. Value path: '/responses/utter_ask_topic/0/custom'.
```

Indeed, if I open the Rasa X Frontend, everything *except* the content of `domain.yml` is displayed. 

Now if I run the function `def validate_yaml_schema(yaml_file_content: Text, schema_path: Text) -> None:` locally, using the same configuration as rasa itsself uses, no `SchemaError` is thrown.

**Content of domain file (domain.yml)** (if relevant):
```yml
responses:
  utter_ask_topic:
    -
      custom:
        email: nan
        feedback_utterance: utter_ask_topic
        is_feedback: true
        phone: nan
        text: utter_ask_topic
        url: nan
```

I tried `rasa data validate` aswell - no errors.

Any ideas on that?

**Comment by sara-tagger** [comment]
Thanks for the issue, @erohmensing will get back to you about it soon!

###### You may find help in the [docs](https://rasa.com/docs/) and the [forum,](https://forum.rasa.com/) too 🤗

**Comment by JulianGerhard21** [comment]
Hi @erohmensing ,

I've also tried it with `rasa==2.3.1` as both worker and production images for `rasa x` with the same result.

Kind regards
Julian

**Comment by JulianGerhard21** [comment]
Hi,

issue has been resolved. Actually, an old file called `domain_old.yml` existed in the same directory and caused the issue. 

Kind regards
Julian

**Comment by erohmensing** [comment]
Oh! I was in the process of writing a message to try to look into this, I'm glad you've figured it out 😄
