### ISSUE TITLE
Research Team Slack Channel notification on Model Regression Test Performance Drops

### ISSUE THREAD

**Issue by kedz** [RasaHQ/rasa#7971]
**Description of Problem**:

Our NLU models are tested weekly on some standard evaluation datasets ([and soon we will also test policy models](https://github.com/RasaHQ/rasa/issues/7835#)).
While the results of these tests are logged and [can be viewed in metabase](https://metabase.rasa.com/dashboard/166) it would be nice if the research team was automatically notified in slack when a model drops in performance. This would help us make sure we don't unintentionally roll out changes that break our models.

This was originally discussed during the implementation of the NLU model regression tests however it was not implemented because training on GPUs introduces some indeterminism in the order that floating point ops are done which can lead to small but not meaningful differences in performance, even when model configs and dataset were unchanged.  [As of Tensorflow 2.3, however, we can run the GPUs in a deterministic mode](https://github.com/NVIDIA/framework-determinism#stock-tensorflow-version-23), so provided we properly set random seeds, we should be able to implement this automatic warning feature.

**Overview of the Solution**:

Regression tests will need to export the following environment variable: `TF_DETERMINISTIC_OPS=1` before calling rasa train/test ([here for example](https://github.com/RasaHQ/rasa/blob/f4af88f0c165c8898b6924b0cbdb0984b8117e63/.github/workflows/ci-model-regression-on-schedule.yml#L174)) and ensure that all model configs ([specified here](https://github.com/RasaHQ/training-data/tree/main/configs)) have their random seeds set (it looks like this is already done). This should then enable consistent outputs when nothing touching the models or datasets has changed. Notification could be implemented similarly to [this PR](https://github.com/RasaHQ/rasa/issues/7834#).

**Comment by sara-tagger** [comment]
Thanks for submitting this feature request 🚀 @TyDunn will get back to you about it soon! ✨

**Comment by sara-tagger** [comment]
Thanks for submitting this feature request 🚀 @joejuzl will get back to you about it soon! ✨

**Comment by HotThoughts** [comment]
Hi Chris, do you mean the tests performance for the *schduled* Model Regression Test? Just want to confirm because we have two Model Regression Test workflow.

**Comment by kedz** [comment]
@HotThoughts yes just the scheduled tests should trigger an alert.
