### ISSUE TITLE
While activating a form, slot will be set by role after requested slot is set which lead to redundance

### ISSUE THREAD

**Issue by Liangda-w** [RasaHQ/rasa#7973]
**Rasa version**: 2.1.1

**Rasa SDK version** (if used & relevant): 2.1.2

**Rasa X version** (if used & relevant):

**Python version**: 3.8.3

**Operating system** (windows, osx, ...): Windows-10-10.0.19041-SP0

**Issue**: When I activate a form with inform intent and want to set the first requested slot with role, it’s not working. More specific, this slot will be set after the requested_slot is set, so bot will ask again for this slot.

For example the form is activated with this utterance: `I want to order a [blue](req_color) sofa for [4]{"entity": "custom_number", "role": "req_size_num_persons"} people`, it give the following action history, this utterance will be validated twice and `req_size_num_persons` slot is set in the second validation. However, the next `requested_slot `is still `req_size_num_persons`, so the form ask again for the `req_size_num_persons`, even though this slot is already set. Also, the next message from user to set the slot `req_size_num_persons` will be fully ignored.

This problem happens only with slots which should be extracted from roles. 
For other slots which are extracted from entities, there is no problem.

```
Tracker slots : {'appoint_time': None, 'req_color': 'blue', 'req_feet': None, 'req_is_placed_at_wall': None, 'req_material': None, 'req_price': None, 'req_price_ma
x': None, 'req_price_min': None, 'req_shape': None, 'req_size': None, 'req_size_depth': None, 'req_size_height': None, 'req_size_length': None, 'req_size_num_perso
ns': None, 'req_size_width': None, 'req_sleep_function': None, 'req_stuffing': None, 'req_style': None, 'req_wood': None, 'requested_slot': None}
Validations : [{'event': 'slot', 'timestamp': None, 'name': 'req_color', 'value': 'blue'}]
ask next: req_size_num_persons
Tracker slots : {'appoint_time': None, 'req_color': 'blue', 'req_feet': None, 'req_is_placed_at_wall': None, 'req_material': None, 'req_price': None, 'req_price_ma
x': None, 'req_price_min': None, 'req_shape': None, 'req_size': None, 'req_size_depth': None, 'req_size_height': None, 'req_size_length': None, 'req_size_num_perso
ns': '4', 'req_size_width': None, 'req_sleep_function': None, 'req_stuffing': None, 'req_style': None, 'req_wood': None, 'requested_slot': None}
Validations : [{'event': 'slot', 'timestamp': None, 'name': 'req_size_num_persons', 'value': '4'}, {'event': 'slot', 'timestamp': None, 'name': 'req_color', 'value
': 'blue'}]
ask next: req_size
```

**Custom Action**:
```
class ValidateCouchRequirementsForm(FormValidationAction):

    internal_tracker = {}

    def name(self) -> Text:
        return "validate_couch_requirements_form"

    async def run(
            self, dispatcher: CollectingDispatcher, tracker: Tracker, domain: Dict
    ) -> List[EventType]:
        vals = await super().run(dispatcher, tracker, domain)
        # Dynamically set which and how many slots should be asked for
        required_slots =  ["req_size_num_persons"] + ValidateCouchRequirementsForm.get_req_size_slots(tracker) \
                          + ["req_color", "req_sleep_function", "req_is_placed_at_wall", "req_shape",
                             "req_material", "req_stuffing", "req_style"] + \
                          ValidateCouchRequirementsForm.get_price_slots(tracker)
        print("Tracker slots : {}".format(tracker.slots))
        print("Validations : {}".format(vals))
        for slot_name in required_slots:
            if tracker.slots.get(slot_name) is None or [val for val in vals
                        if (val["name"]==slot_name and val["value"]==None)]:
                # The slot is not filled yet. Request the user to fill this slot next.
                print("ask next: " + slot_name)
                return [SlotSet("requested_slot", slot_name)] + vals

        # All slots are filled.
        return [SlotSet("requested_slot", None)] + vals
```

**Error (including full traceback)**: No error

**Content of domain file (domain.yml)** (if relevant): 
```yml
entities:
  - custom_number:
      roles:
        - req_size_num_persons
        - req_size
        - req_size_length
        - req_size_width
        - req_price
        - req_price_max
        - req_price_min    
....

slots:
  req_size_num_persons:
     type: float
     max_value: 12
     min_value: 1
     influence_conversation: false
```

**Comment by sara-tagger** [comment]
Thanks for the issue, @samsucik will get back to you about it soon!

###### You may find help in the [docs](https://rasa.com/docs/) and the [forum,](https://forum.rasa.com/) too 🤗

**Comment by samsucik** [comment]
Hi @Liangda-w, I think the issue may not have anything to do with roles. Just eyeballing the custom implementation of `run()`, it occurs to me that you're trying to achieve what is already written in [`FormValidationAction`](https://github.com/RasaHQ/rasa-sdk/blob/50e83e84a979b4542e1ec6ec0476ba8e8a0f11b2/rasa_sdk/forms.py#L688). Ideally, you shouldn't need to override `run()`, only `required_slots()` (see [here](https://rasa.com/docs/rasa/forms#dynamic-form-behavior)). For more insights into the peculiarities of `FormValidationAction`, I also recommend [this forum thread](). And as for the utterance getting validated twice, I think it may be due to this call 🤔 
```python
await super().run(dispatcher, tracker, domain)
```

Could you try to implement the logic just by overriding `required_slots()` (and writing custom extractor functions as necessary)? If that doesn't solve the issue, we'll have to dig deeper 🙂 

*Finally, could you post this as a question in the forum? GitHub issues are meant more for bugs or feature requests and right now it seems like this bit is primarily a question.*

**Comment by Liangda-w** [comment]
Hi @samsucik, sorry for my late reply. You suggestion did solved my issue! Thank you so much😃
