### ISSUE TITLE
Rasa core agent not working

### ISSUE THREAD

**Issue by pradeepthota-ai** [RasaHQ/rasa#7976]
**Rasa version**: 0.12.3

**Rasa SDK version** (if used & relevant):

**Rasa X version** (if used & relevant):

**Python version**:

**Operating system** (windows, osx, ...): colab(windows)

**Issue**:--------------------------------------------------------------------------- ContextualVersionConflict Traceback (most recent call last) in () ----> 1 from rasa_core.agent import Agent 2 3 4 agent = Agent('domain.yml') 5 agent.visualize("stories.md", "story_graph.png", max_history=10)

6 frames /usr/local/lib/python3.6/dist-packages/pkg_resources/**init**.py in resolve(self, requirements, env, installer, replace_conflicting, extras) 775 # Oops, the "best" so far conflicts with a dependency 776 dependent_req = required_by<span class="error">[req]</span> --> 777 raise VersionConflict(dist, req).with_context(dependent_req) 778 779 # push the new requirements onto the stack

ContextualVersionConflict: (tzlocal 1.5.1 (/usr/local/lib/python3.6/dist-packages), Requirement.parse('tzlocal~=2.0'),

 {'APScheduler'})

 **Error (including full traceback)**:

 **Command or request that led to error**: ContextualVersionConflict: (tzlocal 1.5.1 (/usr/local/lib/python3.6/dist-packages), Requirement.parse('tzlocal~=2.0'), {'APScheduler'} 

)

**Content of configuration file (config.yml)** (if relevant):

**Content of domain file (domain.yml)** (if relevant):

**Comment by sara-tagger** [comment]
Thanks for the issue, @TyDunn will get back to you about it soon!

###### You may find help in the [docs](https://rasa.com/docs/) and the [forum,](https://forum.rasa.com/) too 🤗

**Comment by TyDunn** [comment]
Hi @pradeepthota-ai This is a very old version of Rasa. Can I ask why you are using it?

**Comment by pradeepthota-ai** [comment]
> Hi @pradeepthota-ai. This is a very old version of Rasa. Can I ask why you are using it?

Hi @TyDunn im trying build chatbot with help of Cobal notebook, if you have any latest version of colab with RASA please send me the link, and thanks in advance.

**Comment by TyDunn** [comment]
@koaning Can you help @pradeepmvn find the best place to get started? He would like to use a colab notebook or similar if possible

**Comment by jlrpuma** [comment]
Do you guys have any updates on this? I'm getting the same error using rasa 2.3.0

**Operating system:** Colab (Google Colaboratory)

`!pip install rasa==2.3.0`

I'm getting the error when i try to run:
_(the purpose of this code is execute rasa asynchronously)_
```
import os
import rasa
import nest_asyncio

nest_asyncio.apply()

print("event loop ready")
```
The error that im getting is: 

ContextualVersionConflict: (tzlocal 1.5.1 (/usr/local/lib/python3.6/dist-packages), Requirement.parse('tzlocal~=2.0'), {'APScheduler'})

**Comment by OthmanSerraj** [comment]
I'm new to rasa, i have a "ContextualVersionConflict" problemes, could you help me, here is the code:

from rasa_core.policies import FallbackPolicy, MemoizationPolicy,KerasPolicy
from rasa.core.agent import Agent #getting stuck here


agent = Agent('domain.yml', policies=[MemoizationPolicy(), KerasPolicy()])


training_data = agent.load_data('stories.md')

agent.train(
    training_data,
    validation_split=0.0,
    epochs=200
)

agent.persist('models/dialogue')

=> Error:

ContextualVersionConflict                 Traceback (most recent call last)
<ipython-input-65-0e7fc14bbe9c> in <module>
      1 # Import the policies and agent
      2 from rasa_core.policies import FallbackPolicy, MemoizationPolicy,KerasPolicy
----> 3 from rasa.core.agent import Agent
      4 
      5 # Initialize the model with 'domain.yml'

6 frames
/usr/local/lib/python3.7/dist-packages/rasa/core/agent.py in <module>
     13 import rasa
     14 import rasa.utils
---> 15 from rasa.core import jobs, training
     16 from rasa.core.channels.channel import OutputChannel, UserMessage
     17 from rasa.core.constants import DEFAULT_REQUEST_TIMEOUT

/usr/local/lib/python3.7/dist-packages/rasa/core/jobs.py in <module>
      2 import logging
      3 
----> 4 from apscheduler.schedulers.asyncio import AsyncIOScheduler
      5 from pytz import UnknownTimeZoneError, utc
      6 import rasa.shared.utils.io

/usr/local/lib/python3.7/dist-packages/apscheduler/__init__.py in <module>
      2 
      3 try:
----> 4     release = get_distribution('APScheduler').version.split('-')[0]
      5 except DistributionNotFound:
      6     release = '3.5.0'

/usr/local/lib/python3.7/dist-packages/pkg_resources/__init__.py in get_distribution(dist)
    464         dist = Requirement.parse(dist)
    465     if isinstance(dist, Requirement):
--> 466         dist = get_provider(dist)
    467     if not isinstance(dist, Distribution):
    468         raise TypeError("Expected string, Requirement, or Distribution", dist)

/usr/local/lib/python3.7/dist-packages/pkg_resources/__init__.py in get_provider(moduleOrReq)
    340     """Return an IResourceProvider for the named module or requirement"""
    341     if isinstance(moduleOrReq, Requirement):
--> 342         return working_set.find(moduleOrReq) or require(str(moduleOrReq))[0]
    343     try:
    344         module = sys.modules[moduleOrReq]

/usr/local/lib/python3.7/dist-packages/pkg_resources/__init__.py in require(self, *requirements)
    884         included, even if they were already activated in this working set.
    885         """
--> 886         needed = self.resolve(parse_requirements(requirements))
    887 
    888         for dist in needed:

/usr/local/lib/python3.7/dist-packages/pkg_resources/__init__.py in resolve(self, requirements, env, installer, replace_conflicting, extras)
    775                 # Oops, the "best" so far conflicts with a dependency
    776                 dependent_req = required_by[req]
--> 777                 raise VersionConflict(dist, req).with_context(dependent_req)
    778 
    779             # push the new requirements onto the stack

ContextualVersionConflict: (tzlocal 1.5.1 (/usr/local/lib/python3.7/dist-packages), Requirement.parse('tzlocal~=2.0'), {'APScheduler'})


Versions:

Name: rasa-nlu => Version: 0.15.1

Name: rasa-core => Version: 0.14.5
