### ISSUE TITLE
Not getting any response for some requests when large number of concurrent users use rasa server

### ISSUE THREAD

**Issue by udit-pandey** [RasaHQ/rasa#7979]
**Rasa version**:2.1.2

**Rasa SDK version**:2.1.2

**Python version**:3.7.9

**Operating system**:amazon linux 2

**Issue**:When making multiple concurrent http requests to [http://localhost:5005/webhooks/rest/webhook](http://localhost:5005/webhooks/rest/webhook), I am receiving None as response for some of the requests. However, when consecutive requests are sent, I get the desired responses.

I am using rasa open source and have deployed a rasa trained model locally ([http://localhost:5005/webhooks/rest/webhook](http://localhost:5005/webhooks/rest/webhook)). I am load testing it to check number of concurrent users the server can handle. I started with 5 users till 50 with 12 sequential requests per user. I get no response from server when number of users are large (failures(None responses) are random. sometime there are failures and other times there are no failures even for 10 users(more failures on larger number of users)). The response time is also large (for 5 users, it is around 2secs and increases with number of users). There are no errors printed in logs whatsoever when I run this server in debug mode.

To get more clarification on where the issue lies, I did an experiment. I created multiple processes and shared an agent created using rasa sdk among these processes. I get response within 1sec even for 100 concurrent users (each process depicts a user). I did another experiment where I started rasa agent within an http server (using fastapi) and started hitting that with concurrent users with 12 requests per user. Again, as the number of users increased, I got no response for some of my requests. I believe some requests are not processed by the agent/server and are thus dropped. I printed the responses given by this server and they are equal to the requests for which i got a response successfully. There are failed requests which did not even reach my agent. So, whatever this issue is, it is there on rasa http server too.

Here's a link to initial discussion on rasa forum: [Simulateous http requests on rasa server returns None](https://forum.rasa.com/t/simulateous-http-requests-on-rasa-server-returns-none/39975/5)

**Comment by sara-tagger** [comment]
Thanks for the issue, @tttthomasssss will get back to you about it soon!

###### You may find help in the [docs](https://rasa.com/docs/) and the [forum,](https://forum.rasa.com/) too 🤗

**Comment by tttthomasssss** [comment]
Thanks very much for submitting this issue - we'll look into it!

**Comment by rgstephens** [comment]
What does your target deployment environment look like?  For scalable environments, we have a supported [Kubernetes/Helm](https://rasa.com/docs/rasa-x/installation-and-setup/install/helm-chart/) deployment which can also be tested in smaller environments with the [k3s setup](https://rasa.com/docs/rasa-x/installation-and-setup/install/quick-install-script).

**Comment by udit-pandey** [comment]
Right now, I am running the server as a container on docker. Will update soon on the suggested deployment @rgstephens

**Comment by manmustbecool** [comment]
this problem also happens on rasa 1.10.26. if one user has many concurrent requests, some requests will return empty results

**Comment by udit-pandey** [comment]
@manmustbecool 
Currently, Rasa does not handle concurrent users gracefully. I believe its more of a problem with sanic server instead of Rasa. There are two ways you can handle this:
1. Create an HPA k8s deployment with sticky sessions implemented so that your chat services are auto-scaled with increase in number of users and at the same time, requests from a particular user goes to one particular service only.
2. Use a platform like [kairon](https://kairon.digite.com/bots) which handles all of this for you. You just need to focus on creating a bot and leave bot mangement, deployment, monitoring aspects to kairon.
PS: This is an open source project and I am a part time contributor to it.
