### ISSUE TITLE
Rasa X installation taking long<

### ISSUE THREAD

**Issue by Abhilash3836** [RasaHQ/rasa#7987]
[Rasa X installation taking   ##long<]
<img width="960" alt="rasa issue" src="https://user-images.githubusercontent.com/47052944/108327933-0089fe80-71f2-11eb-9aff-0d2b42cabbb1.png">

windows10 64bit
Rasa Version : 2.3.0 
Rasa SDK Version : 2.3.1 
Python Version : 3.7.6 
pip  Version : 21.0.1

**Comment by sara-tagger** [comment]
Thanks for raising this issue, @alopez will get back to you about it soon✨

###### Please also check out the [docs](https://rasa.com/docs/) and the [forum](https://forum.rasa.com/) in case your issue was raised there too 🤗

**Comment by HotThoughts** [comment]
Hey, have you found a solution to solve the issue? It is a `pip` issue. Please see the discussion [here](https://stackoverflow.com/questions/65806524/pip-install-rasa-x-takes-forever/65812957#65812957).
