### ISSUE TITLE
SocketIO not confirming session_request in v2.3.x

### ISSUE THREAD

**Issue by SirBenedick** [RasaHQ/rasa#7997]
**Rasa version**: 2.3.x

**Python version**: 3.7.8

**Issue**: SocketIO not confirming session_request in v2.3.x

Hi,

There seems to be a bug( or undocumented change) in rasa v2.3.0 and v2.3.1\. When trying to connect to a rasa project via sockets there is no session_confirmation send back from the server to the client.

What did I do:

1.  New python environment with python 3.7.8 and pip 21.0.1
2.  pip install rasa
3.  rasa init
4.  changed credentials.yml to allow socketio with “user_uttered” and “bot_uttered” set as events
5.  rasa run --cors “*” --debug
6.  used the webchat/botfront code snippet to test (GitHub - botfront/rasa-webchat: A feature-rich chat widget for Rasa and Botfront 1)

The webchat-widget is able to create a socket connection to rasa, but rasa does not respond to the “session_request” event.

I tested different rasa versions. Rasa 2.3.1 and 2.3.0 seem to have the problem. Every version before that works just as expected. (<=2.2.10).

For now, I will be using v2.2.10 until this is fixed, or did I miss any documented changes?

Ben

PS: I deleted the bug template since it does not apply to this bug. I originally asked the question on the rasa forum [here](https://forum.rasa.com/t/bug-socketio-not-confirming-session-request-in-v2-3-x/40331) The problem might be related to an update to the python-socketio library [source](https://forum.rasa.com/t/bug-socketio-not-confirming-session-request-in-v2-3-x/40331/2?u=ben10)

**Comment by akelad** [comment]
Thanks, @desmarchris and @b-quachtran will look into this to figure out whether it's the socket library.

**Comment by erohmensing** [comment]
@SirBenedick can you also provide your webchat definition, so we know what version of that code its using?

**Comment by SirBenedick** [comment]
> @SirBenedick can you also provide your webchat definition, so we know what version of that code its using?

Sure, its exactly the example code from [here](https://github.com/botfront/rasa-webchat), with a modified socketUrl. I did not explicitly define the version to be used, I am assuming it is 1.0.0.
The exact same Webchat works with rasa versions <=2.2.10

```
<html>
<head>
<script>!(function () {
  let e = document.createElement("script"),
    t = document.head || document.getElementsByTagName("head")[0];
  (e.src =
    "https://cdn.jsdelivr.net/npm/rasa-webchat/lib/index.js"),
    (e.async = !0),
    (e.onload = () => {
      window.WebChat.default(
        {
          customData: { language: "en" },
          socketUrl: "http://localhost:5005",
          // add other props here
        },
        null
      );
    }),
    t.insertBefore(e, t.firstChild);
})();
</script>
</head>
<body></body>
</html>
```

**Comment by rgstephens** [comment]
It looks to me like rasa-webchat should upgrade to the latest socket.io library. I opened an issue [there](https://github.com/botfront/rasa-webchat/issues/344).
