### ISSUE TITLE
rasa x (local) connect to github gets 404 error 

### ISSUE THREAD

**Issue by randywreed** [RasaHQ/rasa#8021]
**Rasa version**: 2.3.0

**Rasa SDK version** (if used & relevant):2.3.1

**Rasa X version** (if used & relevant): 0.36.0

**Python version**:3.6.8

**Operating system** (windows, osx, ...): Linux-5.4.78-2-pve-x86_64-with-centos-7.6.1810-Core

**Issue**: following the instruction for connecting rasa x to my github repo. When I run the curl command I get a 404 error.
**Error (including full traceback)**:
```
About to connect() to ovzve25-68.appstate.edu port 5002 (#0) *> Trying 152.10.25.68…
Connected to ovzve25-68.appstate.edu (152.10.25.68) port 5002 (#0) POST /api/projects/default/git_repositories?api_token=***************************** HTTP/1.1
User-Agent: curl/7.29.0
Host: ovzve25-68.appstate.edu:5002
Accept: /
Content-Type: application/json
Content-Length: 3611
Expect: 100-continue
< HTTP/1.1 100 Continue
< HTTP/1.1 404 Not Found
< Content-Length: 10
< Content-Type: text/plain; charset=utf-8
< Connection: keep-alive
< Keep-Alive: 5
HTTP error before end of send, stop sending
Closing connection 0
Not found.
```

**Command or request that led to error**:
```
curl --request POST \
–url http://ovzve25-68.appstate.edu:5002/api/projects/default/git_repositories?api_tokenxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx2 \
–header ‘Content-Type: application/json’
–data-binary @repository.json
–verbose
```
**Content of repository.json**
```
{
“repository_url”: “git@github.com:randywreed/rasa_kritik_check.git”,
“target_branch”: “main”,
“ssh_key”: "-----BEGIN RSA PRIVATE KEY-----
MIIJKQIBA…
QkEqzYBT
-----END RSA PRIVATE KEY----- ",
“is_target_branch_protected”: false
}
```
**Content of configuration file (config.yml)** (if relevant):
```yml
see attached
```

**Content of domain file (domain.yml)** (if relevant):
```yml
see attached
[config_and_domain_files.zip](https://github.com/RasaHQ/rasa/files/6026824/config_and_domain_files.zip)


```

**Comment by sara-tagger** [comment]
Thanks for the issue, @mvielkind will get back to you about it soon!

###### You may find help in the [docs](https://rasa.com/docs/) and the [forum,](https://forum.rasa.com/) too 🤗

**Comment by randywreed** [comment]
Integrated version control not supported in RasaX local. [https://rasa.com/docs/rasa-x/installation-and-setup/deploy/
](https://rasa.com/docs/rasa-x/installation-and-setup/deploy/)
submitting feature request [https://github.com/RasaHQ/rasa/issues/8076](https://github.com/RasaHQ/rasa/issues/8076)
