### ISSUE TITLE
Remove experimental label for `rasa data validate stories`

### ISSUE THREAD

**Issue by TyDunn** [RasaHQ/rasa#8024]
@JEM-Mosig and I agree that `rasa data validate stories` is a core part of `test` step of CDD, where you make sure that there are no conflicts in your stories before automated tests in a CI pipeline, and we should remove the experimental feature designation in the Rasa Open Source docs

https://rasa.com/docs/rasa/command-line-interface#rasa-data-validate

**Definition of done**
- [x] Remove experimental warning in docs
- [x] ~Remove the warning in the code~
- [x] Update the experimental feature table in Notion

**Comment by pranavdurai10** [comment]
@TyDunn @JEM-Mosig is this still open for contribution? If so, can I take over?

**Comment by TyDunn** [comment]
@pranavdurai10 Yes 👍

**Comment by alopez** [comment]
assignee: @aeshky 
reviewer: @koernerfelicia

**Comment by aeshky** [comment]
**Working branch:** [`remove_exp_label`](https://github.com/RasaHQ/rasa/tree/remove_exp_label).
**Note:** I could not find a warning in the code associated with `rasa data validate stories`.
**Pull request:** https://github.com/RasaHQ/rasa/pull/9194
