### ISSUE TITLE
Load label data in batches to avoid OOM for many `actions_or_text` in e2e

### ISSUE THREAD

**Issue by koernerfelicia** [RasaHQ/rasa#8025]
related to #6836

With e2e training and testing, the number of items in `actions_or_text` has grown considerably. This leads to memory issues due to large tensors.

To prevent this we need to:
- [ ] Load label data in batches for **train**, using some heuristic to create the batches.
- [ ] Load label data in batches for **test**

**Comment by dakshvar22** [comment]
The code for this exists on `batch_labels` branch and also merged with the larger branch of training core in chunks (`policy-train-in-chunk-experiments`). This issue should be closed for now as it is done for the prototype used to run experiments.
