### ISSUE TITLE
Unable to connect to external rabbitMQ amqps host

### ISSUE THREAD

**Issue by nakshathru** [RasaHQ/rasa#8042]
_Rasa version_ : 2.3.1

 _Rasa X version_ (if used & relevant): 0.36.0

 _Python version_ : 3.8

 _Operating system_ (windows, osx, ...): Linux

 _Issue_ : I'm trying to deploy Rasa using Rasa-X into EKS cluster. I'm using a Amazon MQ (rabbitMQ) service which provides amqps endpoint. But rasa-production and rasa-worker pods are failing to connect to MQ service. But I can see a single connection in RabbitMQ portal with queue as 'rasa_production_events'. So one of the service is able to connect. Rasa-X working normally, but when I start training model, it's failing due to not getting connected to the queue.

 _Error (including full traceback)_ :

 2021-02-24 14:26:21 INFO root - Starting Rasa server on [http://localhost:5005](http://localhost:5005)
 2021-02-24 14:26:21 DEBUG rasa.core.utils - Using the default number of Sanic workers (1).
 2021-02-24 14:26:21 DEBUG urllib3.connectionpool - Starting new HTTPS connection (1): api.segment.io:443
 2021-02-24 14:26:21 DEBUG urllib3.connectionpool - [https://api.segment.io:443](https://api.segment.io:443) "POST /v1/track HTTP/1.1" 200 21
 2021-02-24 14:26:21 INFO root - Enabling coroutine debugging. Loop id 83705424.
 2021-02-24 14:26:21 DEBUG root - Could not load interpreter from 'None'.
 2021-02-24 14:26:21 INFO rasa.core.brokers.pika - Connecting to RabbitMQ ...
 2021-02-24 14:26:21 DEBUG rasa.core.brokers.pika - Connecting to 'amqps://123456789.mq.us-east-1.amazonaws.com' failed with error 'ACCESS_REFUSED - Login was refused using authentication mechanism PLAIN. For details see the broker logfile.'. Trying again.

**Comment by sara-tagger** [comment]
Thanks for the issue, @tttthomasssss will get back to you about it soon!

###### You may find help in the [docs](https://rasa.com/docs/) and the [forum,](https://forum.rasa.com/) too 🤗

**Comment by kaustuk** [comment]
Hi @nakshathru I also faced similar issue. I am not sure if this is the right solution or not. But it works for me. Here is the solution. This is what you need to provide in **endpoints.yaml** file. 

```yaml
    event_broker:
      type: "pika"
      url: "amqps://username:password@123456789.mq.us-east-1.amazonaws.com:5671"
      username: ""
      password: ""
      port: 5671
      exchange_name: "default_exchange"
      queues:
      - queue_1
```

So here basically username and password would be taken from url itself. Also note that this works only when you give **username and password value as empty(not in url but other one)**  

Let me know if you face any issue with this approach. 

But yeah I also feel that this is not good approach to do, that is to have username and password present in code or deployment file.

**Comment by nakshathru** [comment]
Hi @kaustuk 
 I almost deleted my amazon MQ instance since it wasn't useful. Thanks for the response and it totally worked.
Yes, it is really weird that, Rasa is not accepting username and password via the values.yml file but Rasa-X is accepting it.
Also this hack exposes credentials in log file if debug mode is on.

**Comment by kaustuk** [comment]
@nakshathru Let's not close this issue. Keep it open so right solution(without hack) can be figured and implemented

**Comment by tttthomasssss** [comment]
Thanks very much for submitting the issue @nakshathru - and thank you for pointing out a workaround @kaustuk. 

I agree, it makes sense to keep this on the books so we can have a closer look at whats going on!

**Comment by nakshathru** [comment]
@tttthomasssss I created a PR for fixing this issue. Can you review the changes ? 
https://github.com/RasaHQ/rasa/pull/8057

**Comment by m-vdb** [comment]
Closing as it was addressed with https://github.com/RasaHQ/rasa/pull/8057
