### ISSUE TITLE
Rasa-X thinks a slot does not exist even though it manages to fill it

### ISSUE THREAD

**Issue by shorouq-z** [RasaHQ/rasa#8055]
**Rasa version**:
2.3.1 
**Rasa SDK version** (if used & relevant):
2.3.1
**Rasa X version** (if used & relevant):
0.36.0
**Python version**:
3.7
**Operating system** (windows, osx, ...):
macOS Big Sur
**Issue**:

In Rasa-X, I can clearly see that it was also filled when getting the error message telling me the slot actually does not exist. After that, rasa tries to fill it again, so my action class method `action_ask_some_form_whatever` runs again. 

1. This slot exists in the domain. 
2. The slot is also an entity and has training data 
3. Rasa-X manages to classify the entity and fill it without me adding payload for buttons 

> slot{"whatever":"C"}
> 
> slot{"requested_slot":"whatever"}
> 

**Error (including full traceback)**:
```
2021-02-26 10:51:22 ERROR    rasa.shared.core.trackers  - Tried to set non existent slot 'whatever'. Make sure you added all your slots to your domain file.

```

**Comment by snek93** [comment]
I would like to add a quick update. I just manually created a story for how I want the assistant to behave in regards to filling this particular slot. Now I no longer get that error message. However, this is still a problem if you want to create a new story using the UI instead of writing it manually.

**Comment by sara-tagger** [comment]
Thanks for raising this issue, @JustinaPetr will get back to you about it soon✨

###### Please also check out the [docs](https://rasa.com/docs/) and the [forum](https://forum.rasa.com/) in case your issue was raised there too 🤗

**Comment by JustinaPetr** [comment]
Thank you @snek93 . Will have a look at what's going on here :)

**Comment by muximuxi** [comment]
I had  some error like yours, maybe you can try rasa interactive use you data , then save the nlu.yml, domain.yml and stories, and use these data training the rasa model again, then it work, and have no error like that

**Comment by Vazerthon** [comment]
Hi @shorouq-z, are you still experiencing this issue?
If you are, can you please provide a detailed step-by-step guide that we can follow to reproduce it? Or, if at all possible, a minimal repo would be really helpful.

Thank you!

**Comment by shorouq-z** [comment]
@Vazerthon This was quite some months ago. If it comes up again, I can provide a small repo to replicate the error.

**Comment by chdorner** [comment]
Thanks @shorouq-z! Feel free to reopen this or a new issue if you encounter this again.
