### ISSUE TITLE
`test_import_time` takes a lot of time

### ISSUE THREAD

**Issue by alwx** [RasaHQ/rasa#8056]
**Rasa version**: 2.3.1 (used `main` branch, commit hash: `2574c46e9576607a7b8de39f823ff3e5c01a475c`)

**Rasa SDK version** (if used & relevant): 2.3.1

**Rasa X version** (if used & relevant):

**Python version**: 3.7 / 3.8

**Operating system** (windows, osx, ...): MacOS / Windows

**Issue**:
`tests/import_time.py::test_import_time` takes about 1.5-2 minutes on my machine (slower on Windows), and it's one of the most time-consuming tests we have. Partially it's because we run this measurement 15 times and get an average time it takes to import Rasa after 15 attempts.
I doubt it's needed. First of all, we might consider limiting the number of measurements. But even if we don't want to, we need to think of how we actually use this number.

See more details about time measurements: https://docs.google.com/spreadsheets/d/1tDRD0vWaLW91W1wPj5h__dwXuXioRt9aBPYyF1n4MjI/edit#gid=57091041 

**Definition of done**:
- Set up a separate job
- Check if it's required
- Fix it

**Command or request that led to error**:
```
pytest tests/import_time.py::test_import_time
```

**Comment by wochinge** [comment]
related https://github.com/RasaHQ/rasa/issues/6473

**Comment by Mazyod** [comment]
Importing rasa is very slow, it would be great if the import speed is fixed instead. Even my project's tests are slow because it imports Rasa at the start of each run.

**Comment by wochinge** [comment]
@Mazyod Thanks for your input. Import time was recently fixed on `main`. Will be released with 2.5.0
