### ISSUE TITLE
Some CLI commands are unexpectedly slow

### ISSUE THREAD

**Issue by alwx** [RasaHQ/rasa#8058]
**Rasa version**: 2.3.1 (used `main` branch, commit hash: `2574c46e9576607a7b8de39f823ff3e5c01a475c`)

**Rasa SDK version** (if used & relevant): 2.3.1

**Rasa X version** (if used & relevant):

**Python version**: 3.7 / 3.8

**Operating system** (windows, osx, ...): MacOS / Windows

**Issue**:
We made an investigation of how long it takes to execute tests, and one of the conclusions that can certainly be made is that some CLI tests are unexpectedly slow.
Several examples:
- `tests/cli/test_rasa_train.py::test_train_help`, `tests/cli/test_rasa_train.py::test_train_nlu_help` and other similar commands often take 5 seconds. But all of them are just some simple commands that only print some help information.
- `tests/cli/test_cli.py::test_cli_start` might take up to 20 seconds on Windows (it just executes `rasa --help` and should be really fast)
- it seems to affect other commands as well. However, we decided to handle other cases separately.

Here you can find more information about the time it takes to execute CLI tests: https://gist.github.com/alwx/fc3334473b046231f1ed35b0bd6e30e3

See more details about time measurements: https://docs.google.com/spreadsheets/d/1tDRD0vWaLW91W1wPj5h__dwXuXioRt9aBPYyF1n4MjI/edit#gid=57091041 

**Definition of done**:
- `--help` commands run in less than 1s

**Command or request that led to error**:
```
pytest tests/cli
```

**Comment by joejuzl** [comment]
Is this still relevant after https://github.com/RasaHQ/rasa/pull/8141 ?

**Comment by TyDunn** [comment]
@alwx can we close this?

**Comment by alwx** [comment]
@TyDunn yes, seems like it can be closed.
