### ISSUE TITLE
Support NATS alongside the HTTP API

### ISSUE THREAD

**Issue by kamyarghajar** [RasaHQ/rasa#8068]
**Description of Problem**: For too many concurrent requests, when using RASA as a micro-service, many HTTP API calls and consequently opening many tcp sockets is not efficient.

**Overview of the Solution**: [NATS](https://nats.io/) is a high performance messaging system that can work with a pub/sub architecture. Supporting the NATS subscriber in RASA helps optimizing the performance of the system and gain higher throughputs from RASA.

**Comment by sara-tagger** [comment]
Thanks for submitting this feature request 🚀 @melindaloubser1 will get back to you about it soon! ✨

**Comment by TyDunn** [comment]
Hi @KamyarGhajar. Can you help me understand how and why you are using Rasa a microservice?

**Comment by KamyarGhajar** [comment]
Hi @TyDunn . We use Rasa NLU as a sequence tagger and intent classifier in our services. In a micro-service architecture using a restful api is not that efficient you know specially when in a Kubernetes cloud solution with several Rasa pods running alongside each other.
