### ISSUE TITLE
Fix Custom Action to Ask For the Next Slot Documentation

### ISSUE THREAD

**Issue by malamasn** [RasaHQ/rasa#8069]
There is a minor but important typo in Custom Action to Ask For the Next Slot documentation [here](https://rasa.com/docs/rasa/forms#using-a-custom-action-to-ask-for-the-next-slot). It states we can use ```action_ask_<form_name>__<slot_name>``` but this doesn't work and after experimenting with it I found out it should be ```action_ask_<form_name>_<slot_name>```.

**Comment by sara-tagger** [comment]
Thanks for raising this issue, @JustinaPetr will get back to you about it soon✨

###### Please also check out the [docs](https://rasa.com/docs/) and the [forum](https://forum.rasa.com/) in case your issue was raised there too 🤗

**Comment by JustinaPetr** [comment]
Hi @malamasn . Would you be interested in opening a pull request for this? Would be a great way to contribute to Rasa Open Source :)
