### ISSUE TITLE
[matrix] connector

### ISSUE THREAD

**Issue by ravenous** [RasaHQ/rasa#8072]
**Description of Problem**: <span class="error">[matrix]</span> is an open standard for secure, decentralised, real-time communication. API Spec - [https://matrix.org/docs/spec/client_server/r0.6.1](https://matrix.org/docs/spec/client_server/r0.6.1) Python client library - [https://github.com/poljar/matrix-nio](https://github.com/poljar/matrix-nio)

**Overview of the Solution**: The matrix connector must supports connecting to any matrix server and sending and receiving almost all supported events, including in end-to-end encrypted rooms. A minimal configuration credentials.yml :

matrix:

1.  Required mxid: "@username:matrix.org" password: "mypassword"
2.  Optional homeserver: "[https://matrix.org](https://matrix.org)" enable_encryption: false nick: "RasaBot" # The nick will be set on startup

**Comment by sara-tagger** [comment]
Thanks for submitting this feature request 🚀 @joejuzl will get back to you about it soon! ✨

**Comment by joejuzl** [comment]
Thanks for the suggestion @ravenous. 
We try to keep Rasa Open Source lightweight by minimising the number of third-party integrations in the codebase. 
However this would be great as a separate library! Fancy taking it on?
I'm happy to help with any questions.
