### ISSUE TITLE
support integrated version control in Rasa X local version

### ISSUE THREAD

**Issue by randywreed** [RasaHQ/rasa#8076]
**Description of Problem**:
currently integrated version control is not supported in local version. However, the use of git repositories is essential during testing prior to deployment which is what the local mode is ideally suited for. Also, low volume bots may be set up using rasa x local mode and integrated version control would make maintenance and updating easier.

**Overview of the Solution**:
Rasa X local would replicate the feature on Rasa X server.

**Definition of Done**:

**Comment by amn41** [comment]
hi @randywreed  ! Local mode writes all your project data back to your filesystem, so you can just use git to push and pull changes as you would for any other software project.

**Comment by randywreed** [comment]
@amn41  while this is true, having RasaX integrate changes to the model requires a restart of the rasax local server. This brings the bot down. This is an unnecessary delay that integration into RasaX would prevent.

**Comment by amn41** [comment]
those are separate things, though. 
* Integrated version control pushes changes to your trainign data / domain file etc back to your remote git server (e.g. github). 
* to incorporate those changes into your assistant (locally or elsewhere), you have to train a new model and activate it. In Rasa X local mode, you can hit the train button and then activate your model in the models page, no need to restart.

**Comment by TyDunn** [comment]
Please reopen if there are more questions
