### ISSUE TITLE
Have a fail handler incase NLG service is down

### ISSUE THREAD

**Issue by kaustuk** [RasaHQ/rasa#8088]
**Description of Problem**:

Rasa support a NLG server for getting utterances for bot to reply. But having said that NLG is separate server there might be cases when NLG server is down or it throws non 2xx status code. In these failed cases currently rasa response with empty messages. But handling this empty response from client side might not be possible in all the channels

**Overview of the Solution**:

Not sure about the solution. But ideally rasa should provide some kind hook which developer can use to handle this failed cases rather than sending the empty responses to client.

**Definition of Done**:

*   [ ] Tests are added
*   [ ] Feature described the docs
*   [ ] Feature mentioned in the changelog

**Comment by sara-tagger** [comment]
Thanks for submitting this feature request 🚀 @dakshvar22 will get back to you about it soon! ✨
