### ISSUE TITLE
Payload in button can be masked with title

### ISSUE THREAD

**Issue by Horizon733** [RasaHQ/rasa#8089]
**Rasa version**: 2.1.2

**Rasa SDK version** (if used & relevant): 2.3.1

**Rasa X version** (if used & relevant): 0.34

**Python version**: 3.7.5

**Operating system** (windows, osx, ...): ubuntu

**Issue**: For buttons, can we mask payload with title so that user doesn't feel bad since to make things easier we devs add intent, entities, slots in payload and it might be bad to show user these stuffs when they click on a button. So, can this feature added to the connectors?
I hope this gets add

**Error (including full traceback)**:
```
No error
```

**Command or request that led to error**:
```

```

**Content of configuration file (config.yml)** (if relevant):
```yml

```

**Content of domain file (domain.yml)** (if relevant):
```yml

```

**Comment by sara-tagger** [comment]
Thanks for raising this issue, @erohmensing will get back to you about it soon✨

###### Please also check out the [docs](https://rasa.com/docs/) and the [forum](https://forum.rasa.com/) in case your issue was raised there too 🤗

**Comment by erohmensing** [comment]
Hi @Horizon733, how the button input is rendered depends on the frontend code of the channel you have connected, not Rasa code. If you connect to e.g. Slack, Facebook Messenger, or a supported web widget, you'll notice that all of these are implemented in the way you've described. 

P.S. in the future, if you'd like something to be added, please open an enhancement request, not a bug report :)
