### ISSUE TITLE
Refactor `prototyper.jsx`

### ISSUE THREAD

**Issue by alwx** [RasaHQ/rasa#8113]
**Description of Problem**: A file named `docs/themes/theme-custom/theme/Prototyper/prototyper.jsx` was written a while ago, and should definitely be refactored.

1.  the name of this component has changed since we introduced it, and it's now called `Playground` — this change should be reflected
2.  we can reduce dependencies (see @gausie's idea here: [https://github.com/RasaHQ/rasa/pull/8109#pullrequestreview-604039453](https://github.com/RasaHQ/rasa/pull/8109#pullrequestreview-604039453))
3.  we can also rewrite it in TypeScript to make more type safe
4.  the Rasa Playground frontend component is not yet merged (
     <g-emoji class="g-emoji" alias="sweat_smile" fallback-src="https://github.githubassets.com/images/icons/emoji/unicode/1f605.png">
     😅 
     </g-emoji>): [https://github.com/RasaHQ/rasa-x/pull/3215](https://github.com/RasaHQ/rasa-x/pull/3215)

**Comment by ericoBandeira** [comment]
Hi, I'm interested in this problem, I'm going to solve it ok?
