### ISSUE TITLE
Conversation Resume

### ISSUE THREAD

**Issue by kearnsw** [RasaHQ/rasa#8119]
Currently, Rasa is ignoring all messages once the conversation is paused. Is it possible to modify the following lines in order to allow for another built-in intent to resume the conversation rather than only supporting restarting the conversation? Otherwise, this requires a fairly technical workaround that may not be approachable for most users.

[https://github.com/RasaHQ/rasa/blob/6d2581d076ff4c9af7078595496c31f96ac66595/rasa/core/processor.py#L608](https://github.com/RasaHQ/rasa/blob/6d2581d076ff4c9af7078595496c31f96ac66595/rasa/core/processor.py#L608) [https://github.com/RasaHQ/rasa/blob/6d2581d076ff4c9af7078595496c31f96ac66595/rasa/core/processor.py#L609](https://github.com/RasaHQ/rasa/blob/6d2581d076ff4c9af7078595496c31f96ac66595/rasa/core/processor.py#L609)

Here is one post on the forum referencing this problem, but there have been many more. [https://forum.rasa.com/t/pause-and-resume-on-rasa-forms/40805/2](https://forum.rasa.com/t/pause-and-resume-on-rasa-forms/40805/2)

**Comment by amn41** [comment]
can you use [this event](https://rasa.com/docs/rasa/2.0.x/reference/rasa/shared/core/events#conversationresumed-objects) ?

**Comment by kearnsw** [comment]
So, that does work by sending POST request to `http://<host>:5005/conversations/test/tracker/events` with the following payload: 

```
{
    "event": "resume"
}
```

This is an API-based solution that I've used in the past, however, the documentation is unclear (so maybe that's where the change should occur?). One place this is evident is on the event page linked above where it currently only shows the class name, `ConversationPaused`, but the API requires the `type_name`, "paused". Overall, I still think a built-in resume intent would be beneficial to reduce friction for new users. Another suggestion would be to include a configurable HumanHandoff channel within Rasa OSS. Let me know what you think would be the best approach and I'm happy to contribute.

**Comment by amn41** [comment]
taggin @melindaloubser1 for an opinion :)

**Comment by melindaloubser1** [comment]
I also think a built in intent that triggers a `resume` event would be helpful.
On the docs side, they could be cross-referenced better, but the API type names of events are available on the action server docs:
https://rasa.com/docs/action-server/events#resume
