### ISSUE TITLE
Version of socketio package causes blocking bug – workaround is manual downgrade

### ISSUE THREAD

**Issue by jkolyer** [RasaHQ/rasa#8136]
**Rasa version**: 2.3.4 **Rasa SDK version** (if used & relevant): 2.3.1 **Rasa X version** (if used & relevant):

**Python version**: 3.8.5 **Operating system** (windows, osx, ...): Linux-4.19.121-linuxkit-x86_64-with-glibc2.29 (docker on osx) **Issue**: Running rasa server on docker and making a websockets call from host. There is a blocking bug in python-socketio v5.0.0.

The bug in that package is an inconsistent name change to the `generate_id` method in `base_manager.py`. It is defined as `_generate_id`, but was not updated in base_manager.py. The bug is apparently fixed in v5.0.4, based on inspection of source code in that package.

Upgrading socketio package manually to 5.0.4 produces this error message in rasa: `ERROR: rasa 2.3.4 has requirement python-engineio<3.14,>=3.11, but you'll have python-engineio 4.0.0 which is incompatible.`

This problem doesn't occur on the rasa server running on the osx host.

python-engineio 3.13.2 python-socketio 4.6.1

When I use these versions on the docker instance, the problem is fixed.

**Error (including full traceback)**:

message async handler error Traceback (most recent call last): File "/opt/venv/lib/python3.8/site-packages/engineio/asyncio_server.py", line 423, in _trigger_event ret = await self.handlers<span class="error">[event]</span>(*args) File "/opt/venv/lib/python3.8/site-packages/socketio/asyncio_server.py", line 524, in _handle_eio_message await self._handle_connect(eio_sid, pkt.namespace) File "/opt/venv/lib/python3.8/site-packages/socketio/asyncio_server.py", line 408, in _handle_connect sid = self.manager.connect(eio_sid, namespace) File "/opt/venv/lib/python3.8/site-packages/socketio/base_manager.py", line 46, in connect sid = self.server.eio.generate_id() AttributeError: 'AsyncServer' object has no attribute 'generate_id'

**Command or request that led to error**: `socketio.connect(url)`

Rasa started from command line with this: `rasa run --enable-api --cors "*" --debug --endpoints endpoints.yml --credentials credentials.yml`

*   ** (Related) Content of configuration file (credentials.yml)**:

<pre>socketio:
 user_message_evt: user_utterance
 bot_message_evt: bot_utterance
 session_persistence: true</pre>

**Content of domain file (domain.yml)** (if relevant):

**Comment by sara-tagger** [comment]
Thanks for raising this issue, @JustinaPetr will get back to you about it soon✨

###### Please also check out the [docs](https://rasa.com/docs/) and the [forum](https://forum.rasa.com/) in case your issue was raised there too 🤗

**Comment by Horizon733** [comment]
I am also getting the same issue, actually, mine is not working with web chat too. Like it's neither showing me chat widget nor any error in the browser console.
