### ISSUE TITLE
Rule starting with action-intent pair wrongly contradicts stories

### ISSUE THREAD

**Issue by samsucik** [RasaHQ/rasa#8176]
**Rasa version**: 2.3.4 (`main`)

**Python version**: 3.8.5

**Operating system** (windows, osx, ...): OSX

**Issue**:
I want to write a rule that basically conditions on an intent `i3` IF that intent follows after a particular action `utter_1` (see the training rules below). Unfortunately, such rule (very non-intuitively) also predicts `action_listen` after `utter_1`. Hence, if I have a training story that contains a different action after `utter_1`, it creates a contradiction (see the training stories below). Note that having two stories in which `utter_1` is followed once by an intent and the other time by an action works fine -- because the conversation history is different for these two cases. But as soon as I create the mentioned rule, things break.

**Suggested solution:**
See [this Slack thread](https://rasa-hq.slack.com/archives/C8LEHMTAM/p1615466129437400) for more context and a discussion that led to this suggestion. Basically, if there is a rule that starts with an action followed by an intent and another action, we'll assume that it is only the last action that the user really meant to predict with the rule. Therefore, IF the predicted `action_listen` (which the user most likely doesn't know about) contradicts a story, we remove this particular rule (only the one that predicts the `action_listen`) from `RulePolicy`'s lookup and proceed (possibly also raising a warning).

**Error (including full traceback)**:
```
InvalidRule:
Contradicting rules or stories found 🚨

- the prediction of the action 'utter_2' in story 'action after action' is contradicting with rule(s) 'conditioned on action' which predicted action 'action_listen'.
Please update your stories and rules so that they don't contradict each other.
You can find more information about the usage of rules at https://rasa.com/docs/rasa/rules.
```

**Command or request that led to error**:
```
rasa train core --augmentation 0
```

**Content of configuration file (config.yml)** (if relevant):
```yml
language: en
policies:
  - name: RulePolicy
  - name: TEDPolicy
    epochs: 1
```

**Content of domain file (domain.yml)** (if relevant):
```yml
intents:
- i1
- i2
- i3
- i4
actions:
- utter_1
- utter_2
- utter_3
```

**Training data**:
```yml
stories:
- story: action after action
  steps:
  - intent: i1
  - action: utter_1
  - action: utter_2 # action goes after utter_1
- story: intent after action
  steps:
  - intent: i2
  - action: utter_1
  - intent: i3
  - action: utter_2 # intent goes after utter_1 because of different history
  - intent: i4
  - action: utter_3
rules:
- rule: conditioned on action
  steps:
  - action: utter_1
  - intent: i3 # this intent is preceded by an implicit action_listen, which break things
  - action: utter_2

**Comment by Ghostvv** [comment]
@koernerfelicia are you working on this one?

**Comment by koernerfelicia** [comment]
Yep!
