### ISSUE TITLE
Rasa x problem decoding in portuguese language

### ISSUE THREAD

**Issue by CatarinaSMorais** [RasaHQ/rasa#8201]
Rasa Version : 2.3.0 Rasa SDK Version : 2.3.1 Rasa X Version : 0.37.0 Python Version : 3.7.6 Operating System : Windows-10

**Issue**:

when running rasa x in my project in portuguese get the above error, can you help? I can train the model, run it and deploy it to an rest channel, the only thing that doens't work is rasa x I tested rasa x with the sample rasa init and trained model and it works fine

**Error (including full traceback)**:

when running rasa x in my project in portuguese get the above error, can you help? I can train the model, run it and deploy it to an rest channel, the only thing that doens't work is rasa x I tested rasa x with the sample rasa init and trained model and it works fine

**Command or request that led to error**:

rasa x

**Content of configuration file (config.yml)** (if relevant):

<pre># Configuration for Rasa NLU.

1\. [https://rasa.com/docs/rasa/nlu/components/](https://rasa.com/docs/rasa/nlu/components/)([https://rasa.com/docs/rasa/nlu/components/)([https://rasa.com/docs/rasa/nlu/components/](https://rasa.com/docs/rasa/nlu/components/](https://rasa.com/docs/rasa/nlu/components/)([https://rasa.com/docs/rasa/nlu/components/](https://rasa.com/docs/rasa/nlu/components/)))
 language: pt
 pipeline:

*   name: SpacyNLP
     model: "pt_core_news_lg"
*   name: SpacyTokenizer
*   name: SpacyFeaturizer
*   name: RegexFeaturizer
*   name: RegexFeaturizer
*   name: LexicalSyntacticFeaturizer
*   name: CountVectorsFeaturizer
*   name: CountVectorsFeaturizer
     analyzer: char_wb
     min_ngram: 1
     max_ngram: 4
*   name: DIETClassifier
     epochs: 100
*   name: EntitySynonymMapper
*   name: ResponseSelector
     epochs: 100
     retrieval_intent: faq 
     scale_loss: false
*   name: ResponseSelector
     epochs: 100
     retrieval_intent: chitchat 
     scale_loss: false
*   name: FallbackClassifier
     threshold: 0.7
     ambiguity_threshold: 0.1

1\. Configuration for Rasa Core.
 2\. [https://rasa.com/docs/rasa/core/policies/](https://rasa.com/docs/rasa/core/policies/)([https://rasa.com/docs/rasa/core/policies/)([https://rasa.com/docs/rasa/core/policies/](https://rasa.com/docs/rasa/core/policies/](https://rasa.com/docs/rasa/core/policies/)([https://rasa.com/docs/rasa/core/policies/](https://rasa.com/docs/rasa/core/policies/)))

policies:

*   name: TEDPolicy
     max_history: 10
     epochs: 20
     batch_size:
*   32
*   64
*   max_history: 6
     name: AugmentedMemoizationPolicy
*   name: RulePolicy
     core_fallback_threshold: 0.3
     core_fallback_action_name: "action_default_fallback"
     enable_fallback_prediction: True

</pre>

**Content of domain file (domain.yml)** (if relevant):

**Comment by sara-tagger** [comment]
Thanks for raising this issue, @rctatman will get back to you about it soon✨

###### Please also check out the [docs](https://rasa.com/docs/) and the [forum](https://forum.rasa.com/) in case your issue was raised there too 🤗

**Comment by CatarinaSMorais** [comment]
@rctatman in advance, using an down grade of versions to the following it works
Rasa X | Rasa Open Source | Rasa SDK
0.32.2 | 1.10.14 | 1.10.2

We need help because we have bots to go to production

**Comment by CatarinaSMorais** [comment]
It only works , in rasa 2.0,  if i remove the following chars:
á, à, ã, õ, é. í, ú , ç, ê

**Comment by mjaycub** [comment]
@TyDunn does this belong in CDD Inbox? If so, does it go into the backlog?

**Comment by CatarinaSMorais** [comment]
@rctatman no news so far?
