### ISSUE TITLE
UnicodeDecodeError: 'charmap' codec can't decode byte 0x9d in position 7835: character maps to <undefined>

### ISSUE THREAD

**Issue by adamfeher64** [RasaHQ/rasa#8215]
Rasa version: 2.4.0
```rasa data validate``` throws error shown in title of this issue because of that.

Solution:
https://github.com/RasaHQ/rasa/blob/2dd3fe96ee1d6d4f31cb00f3a118c115bec4a3ce/rasa/shared/utils/io.py#L417
line 431 should be 
```with open(file_path, encoding="utf8") as file:```
instead of 
```with open(file_path) as file:```
please fix that ASAP.

**Comment by sara-tagger** [comment]
Thanks for raising this issue, @TyDunn will get back to you about it soon✨

###### Please also check out the [docs](https://rasa.com/docs/) and the [forum](https://forum.rasa.com/) in case your issue was raised there too 🤗

**Comment by TyDunn** [comment]
@adamfeher64 Does this happen every single time you run `rasa data validate`?

**Comment by ChrisRahme** [comment]
I have the same issue after updating to 2.4.0.

More info here:
https://forum.rasa.com/t/charmap-codec-cant-decode-byte-0x81-after-2-4-0-update/41569

**Comment by wochinge** [comment]
@adam-meya @ChrisRahme Could you please share a file which I can use to reproduce the error? I did a pull request [here](https://github.com/RasaHQ/rasa/pull/8286) but would like to add a test to the code base so ensure we don't have regression in the future. Thank you 🙌🏻

**Comment by ChrisRahme** [comment]
Sure, here are some files in the attached ZIP.
[Examples.zip](https://github.com/RasaHQ/rasa/files/6196008/Examples.zip)

**Comment by ChrisRahme** [comment]
In this ZIP, there are the `rasa init` files in which I just added a multilingual intent that leads to utter_greet.
[testbot.zip](https://github.com/RasaHQ/rasa/files/6196154/testbot.zip)

Steps:
- Ran `rasa init` in an empty folder
- Added `internet_problem` intent in `nlu.yml` with Arabic & Armenian languages
- Added the intent in `domain.yml`
- Added `Internet problem rule` in `rules.yml`, which links `utter_greet` to `internet_problem`
- Ran `rasa train` which yields to following error:
```
File "E:\Program Files\Python\Python38\lib\encodings\cp1252.py", line 23, in decode
    return codecs.charmap_decode(input,self.errors,decoding_table)[0]
UnicodeDecodeError: 'charmap' codec can't decode byte 0x81 in position 3173: character maps to <undefined>
```

**Comment by wochinge** [comment]
Mhm, I couldn't reproduce due to Windows. Windows has different default encoding 💡

**Comment by ChrisRahme** [comment]
I confirm. I installed Rasa 2.4.1 on Ubuntu and copied my files. It works there.

Is it still planned to fix it or should we keep using Linux?

**Comment by wochinge** [comment]
Haha, no worries @ChrisRahme . I created a pull request [here](https://github.com/RasaHQ/rasa/pull/8286) which will fix this for Windows users 😄 Thanks to your example we also have a regression test for this now 🙌🏻

**Comment by wochinge** [comment]
@ChrisRahme I am currently releasing Rasa Open Source 2.4.2 which will contain the fix.
