### ISSUE TITLE
Allow 'rasa data validate' to be sent a list of data paths instead of just one

### ISSUE THREAD

**Issue by martasls** [RasaHQ/rasa#8221]
**Description of Problem**:
Data for nlu and stories might be in different directories. When using the 'rasa data validate' command we can only pass one path which results in some data being ignored in the event of it not being stored in the same directory. 

**Overview of the Solution**:
Change --data type to allow more than one path to be passed.

**Comment by martasls** [comment]
I can work on it.

**Comment by sara-tagger** [comment]
Thanks for submitting this feature request 🚀 @ArjaanBuijk will get back to you about it soon! ✨

**Comment by ArjaanBuijk** [comment]
@martasls ,
That would be great!

You can make the `--data` command line option the same as for the `rasa train` command:
```bash
rasa train --help

usage: rasa train ... [--data DATA [DATA ...]] ...

optional arguments:
  --data DATA [DATA ...]
                        Paths to the Core and NLU data files. (default:
                        ['data'])

```

**Comment by martasls** [comment]
@ArjaanBuijk 
Hi Arjaan! Thanks for getting back to me! Yup, that's exactly what I've done [here](https://github.com/martasls/rasa/blob/change-validate-data-type/rasa/cli/arguments/default_arguments.py). Is there anything else that needs to be changed? I checked for references to "--data" in the docs and couldn't find anything that would need a change but I could be overlooking something. Thanks a lot in advance!

**Comment by ArjaanBuijk** [comment]
@martasls ,
Nice!
Can you please create a PR as described [here](https://github.com/RasaHQ/rasa/blob/main/CONTRIBUTING.md)?

You can assign me as the initial reviewer, and I will ask others to review as well if needed.
