### ISSUE TITLE
`dispatcher.utter_message(template=...)` no longer works in a custom action

### ISSUE THREAD

**Issue by yennycheung** [RasaHQ/rasa#8223]
**Rasa version**: 2.4.0

**Rasa SDK version** (if used & relevant): 2.4.0

**Rasa X version** (if used & relevant):

**Python version**:

**Operating system** (windows, osx, ...):

**Issue**: 
`dispatcher.utter_message(template=...)` no longer works in a custom action. Nothing is uttered by the bot. This is related to the changes introduced in https://github.com/RasaHQ/rasa/pull/6964.

**Error (including full traceback)**:
The debug logs between Rasa 2.2 & 2.4 look the same, up to this point, after the custom action executed:
```
# rasa 2.2
2021-03-15 16:01:13 DEBUG    rasa.core.processor  - Action 'action_show_balance' ended with events '[BotUttered('Your bank account balance is $49691.97.', {"elements": null, "quick_replies": null, "buttons": null, "attachment": null, "image": null, "custom": null}, {"template_name": "utter_account_balance", "init_account_balance": "49691.97"}, 1615838473.6100328)]'.
# rasa 2.4
2021-03-15 15:54:31 DEBUG    rasa.core.processor  - Action 'action_show_balance' ended with events '[BotUttered('None', {"elements": null, "quick_replies": null, "buttons": null, "attachment": null, "image": null, "custom": null}, {"template": "utter_account_balance", "init_account_balance": "52946.23"}, 1615838071.5593858)]'.
```

**Command or request that led to error**:
```

```

**Content of configuration file (config.yml)** (if relevant):
```yml

```

**Content of domain file (domain.yml)** (if relevant):
```yml

```

**Comment by yennycheung** [comment]
Reported by @ArjaanBuijk and by this forum post: https://forum.rasa.com/t/dispatcher-utter-message-template-not-passing-text-attribute-to-slack-postmessage-in-rasa-2-4-0/41224

**Comment by yennycheung** [comment]
I'm trying to set up form bot to test the changes.

**Comment by yennycheung** [comment]
@wochinge my question on the SDK. How are people using it now? Do they fork it and customize it? If so, I think we can include both fields and comment that if they use the older OSS version, they should use `template`?

**Comment by wochinge** [comment]
> my question on the SDK. How are people using it now? Do they fork it and customize it? If so, I think we can include both fields and comment that if they use the older OSS version, they should use template?

They either use our rasa-sdk or they write their own in their own language (as I e.g. did [here](https://github.com/wochinge/go-rasa-sdk). Forking and customizing the Python one over a long time period is not a thing. I mean they should ideally do the same as we will do in our Python SDK and send both the `template` and `response` key for a while to be compatible with older and newer Rasa Open Source versions. Does that make sense?

**Comment by yennycheung** [comment]
> They either use our rasa-sdk or they write their own in their own language (as I e.g. did [here](https://github.com/wochinge/go-rasa-sdk). Forking and customizing the Python one over a long time period is not a thing. I mean they should ideally do the same as we will do in our Python SDK and send both the `template` and `response` key for a while to be compatible with older and newer Rasa Open Source versions. Does that make sense?

It does. Got it. How do I manually test the sdk?

**Comment by wochinge** [comment]
See [here](https://rasa.com/docs/action-server/running-action-server). You run rasa using `rasa run` and with the action server specified in `endpoints.yml`. You run the action server via `rasa run actions`

**Comment by JEM-Mosig** [comment]
Got the same issue on WSL Ubuntu, but it looks like a solution is on track :)
