### ISSUE TITLE
Error is not shown

### ISSUE THREAD

**Issue by tide90** [RasaHQ/rasa#8230]
Hey, if I customize a component and there inside the process() is an error the error is not shown, via

`rasa shell --debug ` I just get:

`2021-03-18 10:11:23 ERROR asyncio - Task exception was never retrieved future: <Task finished coro=<configure_app.<locals>.run_cmdline_io() done, defined at c:\users\chris\anaconda3\envs\rasa\lib\site-packages\rasa\core\run.py:132> exception=TimeoutError()>`

This makes debugging really hard as I cannot see wheremy error is traced.

How can I retrieve the traceback of the error?

**Comment by sara-tagger** [comment]
Thanks for submitting this feature request 🚀 @TyDunn will get back to you about it soon! ✨

**Comment by tide90** [comment]
@TyDunn 
It would be really nice to know how to debug rasa!

Using rasa shell -debug does not show the traceback and the errror but only the message 'COuld not load model due to...' but not exactly where and which line.

Rasa is always making it difficult...
