### ISSUE TITLE
Rasa Action servers makes everything slow

### ISSUE THREAD

**Issue by tide90** [RasaHQ/rasa#8235]
Hey,  I just test rasa with a minimal and default  example on the same laptop. Chatting over shell or a UI is rather slow, because of the action server I think. So without using any advanced stuff or model you get a large latency by just using the server.

In v1 of rasa before the action server this was not the case (if I remember correctly).

Is there a way to avoid this or just not using the action server and using just the plain actions.py?

**Comment by sara-tagger** [comment]
Thanks for submitting this feature request 🚀 @ArjaanBuijk will get back to you about it soon! ✨

**Comment by ArjaanBuijk** [comment]
@tide90 ,
Thanks for reporting this.

Can you please post details of your experience, including the rasa version and your test bot, to the [rasa community forum](https://forum.rasa.com/)?

Feel free to tag me in your forum post and I will try to help you find the cause.

**Comment by Frank-Sin99** [comment]
@ArjaanBuijk  I just recognized that without anything and just sending an query to the action server and back takes about 2 second  for. Just used one of the example on the github example folder. SO It think it just the http request which takes so long, but why and how can you make it faster?

So it would be nice if someone could clarify or maybe it is too trivial and wonder why no one else hat this issue...
