### ISSUE TITLE
mypy: Fix `[has-type]`

### ISSUE THREAD

**Issue by wochinge** [RasaHQ/rasa#8241]
[Maxime recently enabled `mypy` support for the first couple of issues](https://github.com/RasaHQ/rasa/pull/6511). In our current setup we ignore certain typing issues as there are currently too many to tackle them all at once. 

We should instead tackle them step by step. [Related issue](https://github.com/RasaHQ/rasa/issues/7513). [Parent issue](https://github.com/RasaHQ/rasa/issues/8243).

Current number of issues with this type: 9

**Definition of Done**:
- [x] enable `mypy` checks for `[has-type]`
- [x] all existing  `[has-type]` issues are fixed

**Comment by ancalita** [comment]
@wochinge to double-check, here I just need to remove `has-type` from [this assignment ](https://github.com/RasaHQ/rasa/blob/4f13dfced73478974636e3cc95ba8b86bc2a6b50/setup.cfg#L51) and run `make types` to check for issues ( + fix these issues)?

**Comment by wochinge** [comment]
yep 👍🏻
