### ISSUE TITLE
mypy: Fix `return` issues

### ISSUE THREAD

**Issue by wochinge** [RasaHQ/rasa#8242]
[Maxime recently enabled `mypy` support for the first couple of issues](https://github.com/RasaHQ/rasa/pull/6511). In our current setup we ignore certain typing issues as there are currently too many to tackle them all at once. 

We should instead tackle them step by step. [Related issue](https://github.com/RasaHQ/rasa/issues/7513). [Parent issue](https://github.com/RasaHQ/rasa/issues/8243).

Current number of issues with this type: 18

**Definition of Done**:
- [ ] enable `mypy` checks for `return`
- [ ] all existing `return` issues are fixed

**Comment by joejuzl** [comment]
`Found 98 errors in 40 files (checked 262 source files)` 😱

**Comment by wochinge** [comment]
Oh dear. I can help and we do divide and conquer?

**Comment by joejuzl** [comment]
I'll do a first pass, and see how time consuming it - then maybe we can divide some of the more complex areas.

**Comment by joejuzl** [comment]
I've got it down to 54 errors. These are the files that are left:

rasa/shared/nlu/training_data/message.py
rasa/utils/tensorflow/model_data_utils.py
rasa/utils/tensorflow/models.py
rasa/shared/nlu/training_data/formats/rasa_yaml.py
rasa/nlu/components.py
rasa/shared/core/training_data/structures.py
rasa/shared/importers/importer.py
rasa/shared/core/generator.py
rasa/core/nlg/callback.py
rasa/nlu/model.py
rasa/shared/core/training_data/story_reader/yaml_story_reader.py
rasa/nlu/test.py
rasa/core/featurizers/tracker_featurizers.py
rasa/shared/core/training_data/story_writer/yaml_story_writer.py
rasa/nlu/selectors/response_selector.py
rasa/nlu/featurizers/sparse_featurizer/lexical_syntactic_featurizer.py
rasa/core/test.py
rasa/core/policies/rule_policy.py
rasa/core/policies/form_policy.py
rasa/core/actions/forms.py
rasa/server.py
rasa/core/training/interactive.py
rasa/utils/tensorflow/environment.py

If you want to give me a hand, you could have a look at the first half? (i.e. to `yaml_story_reader.py`)
Some of them are a bit tricky btw 😄

**Comment by joejuzl** [comment]
branch is `8242-mypy_return_issues`, but probably makes sense to do it on a different branch for now.

**Comment by wochinge** [comment]
I'm doing my changes on this PR https://github.com/RasaHQ/rasa/pull/9054 (fixed `message` and `model_data_utils` so far)
