### ISSUE TITLE
Enable `mypy` checks for all error codes

### ISSUE THREAD

**Issue by wochinge** [RasaHQ/rasa#8243]
[Maxime recently enabled `mypy` support for the first couple of issues](https://github.com/RasaHQ/rasa/pull/6511). In our current setup we ignore certain typing issues as there are currently too many to tackle them all at once. 

We should instead tackle them step by step. [Parent issue](https://github.com/RasaHQ/rasa/issues/7513).
This is the parent issue to make sure we tackle of the categories.

**Definition of Done**:
- [ ] enable `mypy` checks for for all error codes
- [ ] issues are fixed

**Comment by TyDunn** [comment]
@wochinge are there more error codes besides the ones referenced in this issue?

**Comment by wochinge** [comment]
Yep, a whole bunch:

```
disable_error_code = arg-type, assignment, var-annotated, return-value, union-attr,
    override, operator, attr-defined, index, misc, return, has-type, func-returns-value
```

**Comment by wochinge** [comment]
- `argtype`: 346 issues
- `assignment`: 164 issues
- `var-annotated`: 62 issues
- `return-value`: 97 issues
- `union-attr`: 91 issues
- `override`: 43 issues
- `operator`: 44 issues
- `attr-defined`: 53 issues
- `index`: 39 issues
- ` misc`: 90 issues
- `func-returns-value`: 2 issues

**Comment by wochinge** [comment]
Starting with the index one

**Comment by m-vdb** [comment]
@wochinge can we have the list of different errors and who's handling in the description of the issue instead of a comment below? I think it's easier for collaboration 😄

**Comment by m-vdb** [comment]
Also another thought @wochinge , it's possible that some of the remaining errors are not easy to fix and require some revamping (I remember hitting some issues with data structures). We might want to flag them (disable them locally and open follow-up ticket) and do them after the revamp. Just a thought 🤔

**Comment by wochinge** [comment]
Created issues for each error code.
