### ISSUE TITLE
I have written terraform script to launch RASA X on AWS with just one click.

### ISSUE THREAD

**Issue by rohitg00** [RasaHQ/rasa#8245]
**Description of Problem**:

**No documentation is present for above mentioned issue:**
Actually, This is really big feature need for rasa docs that's why many developer struggle for launching infrastructure with rasa x installed. We have to come with something which can help developers to launch infrastructure in one click with rasa x installed and handover direct website for rasa x as Public IP DNS.

**Overview of the Solution**:

Hence, I have written a terraform script by which we can launch RASA X on top of AWS with 100 GB EBS Storage which will help with public DNS to work on RASA X to developers. Also, script contains rasa x version 31.5 release installation. We can update time to time as per our need.

**Examples** (if relevant):

I'll request with my repo link. Once issue is seem.

**Blockers** (if relevant):

**Definition of Done**:
 What needs to be there to consider this feature as done?
- Tests are added
-  Feature described the docs

**Comment by sara-tagger** [comment]
Thanks for submitting this feature request 🚀 @desmarchris will get back to you about it soon! ✨

**Comment by ArjaanBuijk** [comment]
@rohitg00 ,
That is really interesting. Would you be able to share a link to your git repo?

**Comment by rohitg00** [comment]
Sure, How can I contribute? @ArjaanBuijk

**Comment by rohitg00** [comment]
Check out this link for more details: [RASA-X-Terraform](https://github.com/rohitg00/rasa-x-infra-terraform)
@ArjaanBuijk @sara-tagger @desmarchris

**Comment by rohitg00** [comment]
Any update on above discussion?

**Comment by rohitg00** [comment]
Any update?

**Comment by tczekajlo** [comment]
@rohitg00 Thanks a lot for sharing your work and your repository.

It looks interesting, but our quality standards related to IaaC and code that we host in our repositories do not allow for including it in the rasa repository. 

cc @RasaHQ/infrastructure-squad
