### ISSUE TITLE
Preserve `session_started_metadata` slot on `action_restart`

### ISSUE THREAD

**Issue by Gazler** [RasaHQ/rasa#8255]
**Description of Problem**: We have developed a custom channel connector, that relies on the metadata to route messages back to the correct users when actions are submitted. This is working really well as we can lookup the metadata fields during an action and use them as appropriate.

However, when a user triggers the restart intent, and `action_restart` is triggered, all the slots are reset, including the `session_started_metadata.

**Overview of the Solution**:

I am aware that the above can be solved with a custom restart action, however I am wondering if this feature would have value in the core. When calling `action_restart`, reset the slots, but restore `session_started_metadata` to its previous value.

**Comment by sara-tagger** [comment]
Thanks for submitting this feature request 🚀 @ArjaanBuijk will get back to you about it soon! ✨
