### ISSUE TITLE
add tests for e2e ted

### ISSUE THREAD

**Issue by Ghostvv** [RasaHQ/rasa#8273]
TED and e2e TED differ from each other based on the training data it is trained on. We need to add tests for TEDPolicy trained on pure e2e, mixed e2e, e2e with/without entities.

**Comment by joejuzl** [comment]
I think that it's important that tests are written by the same developers who write the code that the tests are testing.
So I would propose this is handled by the research team - of course enable squad would be able to assist as much as needed.
