### ISSUE TITLE
Rasa X sentences are not updating after making changes to responses on GitHub

### ISSUE THREAD

**Issue by aparnarai25** [RasaHQ/rasa#8282]
**Rasa version**: 2.3.4

**Rasa SDK version** (if used & relevant): -

**Rasa X version** (if used & relevant): 3.7.1

**Python version**: -

**Operating system** (windows, osx, ...): -

**Issue**: Rasa X sentences are not updating after making changes to responses on GitHub

**Error (including full traceback)**: I did many changes in responses using GitHub, these changes are being used by our chat bot, but if I see the sentences from Rasa X they didn't update there. For example:

Bot version of utter_greet_is_eligible: [<span class="image-wrap" style="">![](https://user-images.githubusercontent.com/71128276/112160691-6c57f080-8c10-11eb-8d4a-5258808c714a.png)</span>](https://user-images.githubusercontent.com/71128276/112160691-6c57f080-8c10-11eb-8d4a-5258808c714a.png)

Rasa X version of utter_greet_is_eligible: [<span class="image-wrap" style="">![](https://user-images.githubusercontent.com/71128276/112160758-7da0fd00-8c10-11eb-8942-9d0ecbe2d67f.png)</span>](https://user-images.githubusercontent.com/71128276/112160758-7da0fd00-8c10-11eb-8942-9d0ecbe2d67f.png)

**Command or request that led to error**: making changes to responses on GitHub

**Content of configuration file (config.yml)** (if relevant): -

**Content of domain file (domain.yml)** (if relevant): - [<span class="image-wrap" style="">![](https://user-images.githubusercontent.com/71128276/112161294-04ee7080-8c11-11eb-96b8-e95d00ffb9ab.png)</span>](https://user-images.githubusercontent.com/71128276/112161294-04ee7080-8c11-11eb-96b8-e95d00ffb9ab.png) [<span class="image-wrap" style="">![](https://user-images.githubusercontent.com/71128276/112161298-061f9d80-8c11-11eb-9aa1-aa620a251668.png)</span>](https://user-images.githubusercontent.com/71128276/112161298-061f9d80-8c11-11eb-9aa1-aa620a251668.png)

**Comment by sara-tagger** [comment]
Thanks for raising this issue, @amn41 will get back to you about it soon✨

###### Please also check out the [docs](https://rasa.com/docs/) and the [forum](https://forum.rasa.com/) in case your issue was raised there too 🤗

**Comment by amn41** [comment]
hi @aparnarai25 - are you using Rasa X in local mode or server mode? If server mode, does the [integrated version control](https://rasa.com/docs/rasa-x/installation-and-setup/deploy#connect-a-git-repository) panel show an error or anything?

**Comment by aparnarai25** [comment]
Hi @amn41 - I am using Rasa X in server mode, docker compose approach on EC2. Version control is green no warning or error.

**Comment by alexweidauer** [comment]
Thank you for raising this issue about Rasa X. We decided to stop supporting the Community Edition (free version) of ‘Rasa X’ (see more info here: https://rasa.com/blog/rasa-x-community-edition-changes/). That’s why we’ve closed your issue. We suggest that Rasa Enterprise customers raise the issue with our customer support team if they haven’t done so already.
