### ISSUE TITLE
Quotes (") character appear as &quot; in the docs

### ISSUE THREAD

**Issue by Imod7** [RasaHQ/rasa#8288]
**Issue**: **Quotes** (character ' " ') appear as `"` in the docs.

**Error found**:

*   In the [docs](https://rasa.com/docs/rasa/reference/rasa/shared/core/events#format_message), in the `format_message` function, quotes appear as `"` as shown below : `I am from <span class="error">[Berlin]</span> {"entity": "city"}

.` which corresponds to [this](https://github.com/RasaHQ/rasa/blob/8258c5500108110525aef16fa20ee0f47f435b1e/rasa/shared/core/events.py#L91) code where quotes appear ok.

*   In the same page of the docs, in `split_events`, it also appears here : ` {"action_name" - "action_session_start"}

, True )`

*   Also, in page [trackers](https://rasa.com/docs/rasa/reference/rasa/shared/core/trackers)

**Comment by Imod7** [comment]
Hello @TyDunn 👋🏽 Is it possible for you to assign this ticket to a specific team/board because I can only assign issues to the enable squad. Thank you so much in advance!

**Comment by BA1RY** [comment]
Hi I would like to work on this 😄

**Comment by Imod7** [comment]
Hey @BA1RY thank you for offering to work on this! 👏🏽 Please feel free to handle this issue and maybe open a PR with your suggested solution!

**Comment by jppgomes** [comment]
this happens because it is used where the field is for text and not html, should the pr be done for the branch documentation?
@lmod7
