### ISSUE TITLE
Channel specific response for custom connector with alexa does not work

### ISSUE THREAD

**Issue by floramarleen** [RasaHQ/rasa#8297]
**Rasa version**: 2.4.0

**Rasa SDK version**: 2.4.0

**Python version**: 3.8.5

**Operating system**: Windows

**Issue**: I connected my rasa open source bot to alexa by following the instruction given here: [https://blog.rasa.com/connect-your-rasa-ai-assistant-to-amazon-alexa/](https://blog.rasa.com/connect-your-rasa-ai-assistant-to-amazon-alexa/). It works all fine except of the channel specific responses. It gives the output of the non channel specific responses and just ignores the ones I created.

Here is my alexa_connector.py:

import logging import json from sanic import Blueprint, response from sanic.request import Request from sanic.response import HTTPResponse #from typing import Text, Optional, List, Dict, Any from typing import Text, Dict, Any, Optional, Callable, Awaitable, NoReturn

import rasa.utils.endpoints from rasa.core.channels.channel import UserMessage, OutputChannel from rasa.core.channels.channel import InputChannel from rasa.core.channels.channel import CollectingOutputChannel

logger = logging.getLogger(**name**)

class AlexaConnector(InputChannel): """A custom http input channel for Alexa. You can find more information on custom connectors in the Rasa docs: [https://rasa.com/docs/rasa/user-guide/connectors/custom-connectors/](https://rasa.com/docs/rasa/user-guide/connectors/custom-connectors/) """

@classmethod #def name(cls): def name(cls) -> Text: return "alexa_assistant"

1.  Sanic blueprint for handling input. The on_new_message
2.  function pass the received message to Rasa Core
3.  after you have parsed it def blueprint(self, on_new_message):

alexa_webhook = Blueprint("alexa_webhook", **name**)

1.  required route: use to check if connector is live @alexa_webhook.route("/", methods=<span class="error">["GET"]</span>) async def health(request): return response.json( {"status": "ok"}

)

1.  required route: defines @alexa_webhook.route("/webhook", methods=<span class="error">["POST"]</span>) async def receive(request):

1.  get the json request sent by Alexa payload = request.json

1.  check to see if the user is trying to launch the skill intenttype = payload<span class="error">["request"]</span><span class="error">["type"]</span>

1.  if the user is starting the skill, let them know it worked & what to do next if intenttype == "LaunchRequest": message = "Hello! Welcome to the Privacy Bot. You can start by saying 'hi'." session = "false" else:

1.  get the Alexa-detected intent intent = payload<span class="error">["request"]</span><span class="error">["intent"]</span><span class="error">["name"]</span>

1.  makes sure the user isn't trying to end the skill if intent == "AMAZON.StopIntent": session = "true" message = "Talk to you later" else:

1.  get the user-provided text from the slot named "text" text = payload<span class="error">["request"]</span><span class="error">["intent"]</span><span class="error">["slots"]</span><span class="error">["text"]</span><span class="error">["value"]</span>

1.  initialize output channel out = CollectingOutputChannel()

1.  send the user message to Rasa & wait for the

1.  response to be sent back await on_new_message(UserMessage(text, out))

1.  extract the text from Rasa's response responses = [m<span class="error">["text"]</span> for m in out.messages] #message = responses<span class="error">[0]</span> #give more than the first response message="" for res in responses: message=message+str(res)

    <ins>" \n" #message = str(responses<span class="error">[0]</span>)</ins>

    " "+str(responses<span class="error">[1]</span>) session = "false"

1.  Send the response generated by Rasa back to Alexa to

1.  pass on to the user. For more information, refer to the

1.  Alexa Skills Kit Request and Response JSON Reference:

1.  [https://developer.amazon.com/en-US/docs/alexa/custom-skills/request-and-response-json-reference.html](https://developer.amazon.com/en-US/docs/alexa/custom-skills/request-and-response-json-reference.html) r = { "version": "1.0", "sessionAttributes": {"status": "test"}

, "response": { "outputSpeech":

 { "type": "PlainText", "text": message, "playBehavior": "REPLACE_ENQUEUED", } 

, "reprompt":

 Unknown macro: 

 { "outputSpeech"} 

, "shouldEndSession": session, }, }

return response.json(r)

return alexa_webhook

**Content of domain file (domain.yml)** (if relevant):

*   text: "Test Welcome" channel: "alexa_assistant"
*   text: "Welcome, how can I help you?"

**Comment by sara-tagger** [comment]
Thanks for the issue, @ArjaanBuijk will get back to you about it soon!

###### You may find help in the [docs](https://rasa.com/docs/) and the [forum,](https://forum.rasa.com/) too 🤗

**Comment by floramarleen** [comment]
Are there any news about this issue?
