### ISSUE TITLE
 implement chunking in SpacyNLP and HuggingfaceNLP

### ISSUE THREAD

**Issue by Ghostvv** [RasaHQ/rasa#8301]
part of https://github.com/RasaHQ/rasa/issues/6836

`SpacyNLP` loads spacy library and creates docs with dense features, which stay in the memory for the whole dataset. `SpacyNLP` should support adding these docs to `TrainingDataChunk` which creates a clash with the fact that tokenization is performed on `TrainingDataFull`. I think `SpacyNLP` should be run twice, first extracting only spacy tokens for spacy tokenizer on `TrainingDataFull` then to add docs with dense features on `TrainingDataChunk`

similar thing should be done for `HuggingfaceNLP` though it's not clear whether this class is still used since it is deprecated

Note: This feature should branch off from partial_dataset_loading and should be squashed and merged back into that branch.

**Comment by koernerfelicia** [comment]
`LMFeaturizer` basically does what `HFNLP` did

**Comment by Ghostvv** [comment]
@koernerfelicia I thought so. can we remove the contents of `HFNLP`? and only leave the deprecation warning as it is done in `LMTokenizer`? cc @dakshvar22

**Comment by koernerfelicia** [comment]
Hm, Daksh should answer this, if I'm remembering right this is what I had initially done but then Daksh or Tanja had a reason to keep the contents..
