### ISSUE TITLE
 implement train_on_chunk for`RegexEntityExtractor`

### ISSUE THREAD

**Issue by Ghostvv** [RasaHQ/rasa#8304]
part of https://github.com/RasaHQ/rasa/issues/6836

should go into `partial-dataset-loading` branch.

In this branch, we implemented `train_on_chunk` for `DIETClassifier` which inherits from `EntityExtractor` which has `train_on_chunks` method. Therefore, `RegexEntityExtractor` should also implement it

Note: This feature should branch off from partial_dataset_loading and should be squashed and merged back into that branch.

**Comment by koernerfelicia** [comment]
Closing because training is covered in `prepare_partial_training` (slack thread [here](https://rasa-hq.slack.com/archives/C8LEHMTAM/p1617124051225400))
