### ISSUE TITLE
Error in is_entity_extractor_present() in rasa/nlu/test.py

### ISSUE THREAD

**Issue by govertbuijs** [RasaHQ/rasa#8325]
**Rasa version**: Rasa 1.10.23, but code also seems unchanged in master 

**Python version**: 3.7.9

**Operating system** (windows, osx, ...): Linux

**Issue**:
_is_entity_extractor_present_() checks if the return of _get_entity_extractors_() is not an empty list.
But _get_entity_extractors_() returns a set, so the the comparison is always True.

**Command or request that led to error**:
```
rasa test nlu 
```

**Comment by sara-tagger** [comment]
Thanks for raising this issue, @koernerfelicia will get back to you about it soon✨

###### Please also check out the [docs](https://rasa.com/docs/) and the [forum](https://forum.rasa.com/) in case your issue was raised there too 🤗

**Comment by koernerfelicia** [comment]
@govertbuijs, thanks for raising this! This does indeed look like a bug.
