### ISSUE TITLE
Message before action only appears when action_listen is triggered

### ISSUE THREAD

**Issue by randywreed** [RasaHQ/rasa#8326]
**Rasa version**:2.3.3

**Rasa SDK version** (if used & relevant):2.3.1

**Rasa X version** (if used & relevant):0.36.0

**Python version**:3.7.3

**Operating system** (windows, osx, ...):Ubuntu 18.04

**Issue**:  if an utterance is issued before a lengthy action (something like, "this will take a while, please wait." the message will not appear until after the action has completed (defeating the purpose of the wait warning). This does not work for either Rasa Shell or RasaX.

However, I have found that if I issue an intermediate action (say one that generates another message (i.e. "thanks for waiting, this will just be a minute") in Rasa shell, the intermediate action will cause the intial utterance to display but the utterance created by the intermediate action does not. In RasaX the intermediate action has no effect.

Here's a chart that hopefully makes this more clear:

Rasa Shell

intent: greet
intent: utter_greet
intent: show_problem
action: utter_problem - says “please wait” does not display
action: action_delay - when complete the above utterance and the actions result displays simultaneously

Rasa Shell with intermediate action

intent: greet
action: utter_greet
intent: show_problem
action: utter_problem - This says “please wait” it does not display
action: action_utter - This issues an utter_message and causes the above utterance to display
action: action_delay - this is the delay action, after it finishes the result of this action and the one above now display

Rasa X - both examples work the same and nothing displays until the final action completes

I've create a git hub repo that demonstrates this problem: [rasa action delay error ](https://github.com/randywreed/rasa_action_delay)

**Error (including full traceback)**:
```

```

**Command or request that led to error**:
```

```

**Content of configuration file (config.yml)** (if relevant):
```yml

```

**Content of domain file (domain.yml)** (if relevant):
```yml

```

**Comment by sara-tagger** [comment]
Thanks for the issue, @koaning will get back to you about it soon!

###### You may find help in the [docs](https://rasa.com/docs/) and the [forum,](https://forum.rasa.com/) too 🤗

**Comment by rgstephens** [comment]
Please post questions in the [forum](https://forum.rasa.com). I will close this issue and you and post any follow-up questions there.

You can't making blocking or long running action server calls. For these cases, you should issue your response about it taking a while and the long running function should invoke an [external event](https://rasa.com/docs/rasa/reaching-out-to-user/#external-events) to continue the conversation.
