### ISSUE TITLE
Rasa Train NoReturn Error in Python 3.7.0

### ISSUE THREAD

**Issue by b-quachtran** [RasaHQ/rasa#8336]
**Rasa version**:
2.4.2

**Python version**:
3.7.0

**Operating system** (windows, osx, ...):

**Issue**:
`rasa train` throws an error because of the NoReturn. 

**Error (including full traceback)**:
```
    raise TypeError(f"Plain {arg} is not valid as type argument")
TypeError: Plain typing.NoReturn is not valid as type argument
```

**Command or request that led to error**:
```
rasa train
```

**Comment by sarahwangsdu** [comment]
should be version problem, the version request is larger than >=3.7.2
