### ISSUE TITLE
Incompatibility of aiohttp version between rasa v.2.4.3 and GQL v3

### ISSUE THREAD

**Issue by Matthieu-Tinycoaching** [RasaHQ/rasa#8347]
**Description of Problem**:
When using external graphQL API within action server in python, I need to install the library `GQL v3` (https://github.com/graphql-python/gql) to handle asynchronous graphQL call to the API. However, `GQL v3` requires `aiohttp v3.7.4` while `rasa v2.4.3` requires `aiohttp<3.7,>=3.6` leading to the following `pip install `error:

`rasa 2.4.3 requires aiohttp<3.7,>=3.6, but you have aiohttp 3.7.4.post0 which is incompatible.`

**Overview of the Solution**:
Would there be a way to upgrade the `aiohttp version to v3.7.4` in `rasa v2.4.3` while keeps functionning normally?

**Comment by sara-tagger** [comment]
Thanks for submitting this feature request 🚀 @desmarchris will get back to you about it soon! ✨

**Comment by desmarchris** [comment]
hey @Matthieu-Tinycoaching, do you mind trying a PR that makes this update?

**Comment by Matthieu-Tinycoaching** [comment]
Hi @desmarchris I am new to both versioning and Rasa but still ready to improve. But how could I figure out this incompatibility?

**Comment by Matthieu-Tinycoaching** [comment]
Hi @desmarchris that's strange because if I look into `poetry.lock` file ni rasa github account:

```
[[package]]
name = "aiohttp"
version = "3.7.4"
description = "Async http client/server framework (asyncio)"
category = "main"
optional = false
python-versions = ">=3.6"
```

However, when installing rasa the version of `aiohttp` is not `3.7.4` but `3.6.x`

Any idea?

**Comment by desmarchris** [comment]
@Matthieu-Tinycoaching ah looks like someone bumped it up in our `main` branch already. That means it should be included in one of the next releases!

**Comment by joejuzl** [comment]
Closing as the aiohttp version range is now `>=3.6,<3.8,!=3.7.4.post0` which should be compatible.

@Matthieu-Tinycoaching if you still have issues with dependencies, https://forum.rasa.com/ would be a good place to ask.
