### ISSUE TITLE
Custom ActionSessionStart returns twice same message

### ISSUE THREAD

**Issue by Matthieu-Tinycoaching** [RasaHQ/rasa#8348]
**Rasa version**: 2.4.3

**Rasa SDK version** (if used & relevant): 2.4.1

**Python version**: 3.8.8

**Operating system** (windows, osx, ...): Linux-5.4.0-65-generic-x86_64-with-glibc2.10

**Issue**: Hi,

I tried to customize the `ActionSessionStart` class in order to bot to send the first message to user when triggering `/session_start` following the below code:

class ActionSessionStart(Action): def name(self) -> Text: return "action_session_start"

@staticmethod def fetch_slots(tracker: Tracker) -> List<span class="error">[EventType]</span>: """Collect slots that contain the user's name and phone number."""

slots = [] for key in ("name", "phone_number"): value = tracker.get_slot(key) if value is not None: slots.append(SlotSet(key=key, value=value)) return slots

async def run( self, dispatcher: CollectingDispatcher, tracker: Tracker, domain: Dict<span class="error">[Text, Any]</span> ) -> List[Dict<span class="error">[Text, Any]</span>]:

1.  the session should begin with a `session_started` event events = <span class="error">[SessionStarted()]</span>

dispatcher.utter_message(text="Bonjour Matthieu, bienvenu dans cette nouvelle session en ma compagnie !")

1.  an `action_listen` should be added at the end as a user message follows events.append(ActionExecuted("action_listen"))

return events

However, when launching rasa shell and initiating with` /session_start` payload I got twice the user message: `Bonjour Matthieu, bienvenu dans cette nouvelle session en ma compagnie !`

Please find below the detailed response following `/session_start` obtained with the `--debug` flag:

Your input -> /session_start 2021-03-30 14:50:07 DEBUG rasa.core.lock_store - Issuing ticket for conversation '630849e4545949c0b480cf329024f5f9'. 2021-03-30 14:50:07 DEBUG rasa.core.lock_store - Acquiring lock for conversation '630849e4545949c0b480cf329024f5f9'. 2021-03-30 14:50:07 DEBUG rasa.core.lock_store - Acquired lock for conversation '630849e4545949c0b480cf329024f5f9'. 2021-03-30 14:50:07 DEBUG rasa.core.tracker_store - Could not find tracker for conversation ID '630849e4545949c0b480cf329024f5f9'. 2021-03-30 14:50:07 DEBUG rasa.core.processor - Starting a new session for conversation ID '630849e4545949c0b480cf329024f5f9'. 2021-03-30 14:50:07 DEBUG rasa.core.actions.action - Calling action endpoint to run action 'action_session_start'. 2021-03-30 14:50:07 DEBUG rasa.core.processor - Policy prediction ended with events '[]'. 2021-03-30 14:50:07 DEBUG rasa.core.processor - Action 'action_session_start' ended with events '[BotUttered('Bonjour Matthieu, bienvenu dans cette nouvelle session en ma compagnie !',

 {"elements": null, "quick_replies": null, "buttons": null, "attachment": null, "image": null, "custom": null} 

,

 {"utter_action": "utter_session_start", "name": "Matthieu"} 

, 1617108607.4718068), <rasa.shared.core.events.SessionStarted object at 0x7f46b06b9730>, ActionExecuted(action: action_listen, policy: None, confidence: None)]'. 2021-03-30 14:50:07 DEBUG rasa.core.processor - Current slot values: name: None location: None email: None session_ready: None requested_slot: None session_started_metadata: None 2021-03-30 14:50:07 DEBUG rasa.core.processor - Received user message '/session_start' with intent '

 {'name': 'session_start', 'confidence': 1.0} 

' and entities '[]' 2021-03-30 14:50:07 DEBUG rasa.core.processor - Logged UserUtterance - tracker now has 5 events. 2021-03-30 14:50:07 DEBUG rasa.core.policies.memoization - Current tracker state: <span class="error">[state 1]</span> user intent: session_start | previous action name: action_listen 2021-03-30 14:50:07 DEBUG rasa.core.policies.memoization - There is no memorised next action 2021-03-30 14:50:07 DEBUG rasa.core.policies.rule_policy - Current tracker state: <span class="error">[state 1]</span> user text: /session_start | previous action name: action_listen 2021-03-30 14:50:07 DEBUG rasa.core.policies.rule_policy - There is no applicable rule. 2021-03-30 14:50:07 DEBUG rasa.core.policies.rule_policy - Predicted default action 'action_session_start'. 2021-03-30 14:50:07 DEBUG rasa.core.policies.ensemble - Made prediction using user intent. 2021-03-30 14:50:07 DEBUG rasa.core.policies.ensemble - Added `DefinePrevUserUtteredFeaturization(False)` event. 2021-03-30 14:50:07 DEBUG rasa.core.policies.ensemble - Predicted next action using policy_2_RulePolicy. 2021-03-30 14:50:07 DEBUG rasa.core.processor - Predicted next action 'action_session_start' with confidence 1.00\. 2021-03-30 14:50:07 DEBUG rasa.core.actions.action - Calling action endpoint to run action 'action_session_start'. 2021-03-30 14:50:07 DEBUG rasa.core.processor - Policy prediction ended with events '[ <rasa.shared.core.events.defineprevuserutteredfeaturization object at 0x7f46b072c8b0> ] </rasa.shared.core.events.defineprevuserutteredfeaturization>'. 2021-03-30 14:50:07 DEBUG rasa.core.processor - Action 'action_session_start' ended with events '[BotUttered('Bonjour Matthieu, bienvenu dans cette nouvelle session en ma compagnie !',

 {"elements": null, "quick_replies": null, "buttons": null, "attachment": null, "image": null, "custom": null} 

,

 {"utter_action": "utter_session_start", "name": "Matthieu"} 

, 1617108607.479607), <rasa.shared.core.events.SessionStarted object at 0x7f46b06c1bb0>, ActionExecuted(action: action_listen, policy: None, confidence: None)]'. 2021-03-30 14:50:07 DEBUG rasa.core.processor - Current slot values: name: None location: None email: None session_ready: None requested_slot: None session_started_metadata: None 2021-03-30 14:50:07 DEBUG rasa.core.lock_store - Deleted lock for conversation '630849e4545949c0b480cf329024f5f9'. Bonjour Matthieu, bienvenu dans cette nouvelle session en ma compagnie ! Bonjour Matthieu, bienvenu dans cette nouvelle session en ma compagnie !

Following analyis at [https://forum.rasa.com/t/custom-actionsessionstart-returns-twice-same-message/41838](https://forum.rasa.com/t/custom-actionsessionstart-returns-twice-same-message/41838), it seems that `action_session_start` is called two times: once at the beginning of the session and once after respond to the `/session_start` NLU input.

Would you see a way to deal with this problem (as not interpreting /session_start with rasa nlu or other…), since like the documentation says overriding the action_session_start could be used to start the conversation with a bot message… but not with duplicated message?

Thanks!

**Comment by joejuzl** [comment]
Hi @Matthieu-Tinycoaching - can you update to the latest version of Rasa and check this is still an issue?

**Comment by Matthieu-Tinycoaching** [comment]
Hi @joejuzl  I upgraded the rasa version to 2.6 and still got the same issue.

**Comment by wochinge** [comment]
This part `{"utter_action": "utter_session_start", "name": "Matthieu"}` in the logs seems a bit weird. Are you sure that your code from the issue is the actual custom action code which is running @Matthieu-Tinycoaching?  I'd expect a slightly differrent `dispatch.utter_message` call than the one which you shared.

**Comment by Matthieu-Tinycoaching** [comment]
Hi @wochinge, 

Please find below the last custome code which is running:

```
    async def run(
      self, dispatcher: CollectingDispatcher, tracker: Tracker, domain: Dict[Text, Any]
    ) -> List[Dict[Text, Any]]:

        # the session should begin with a `session_started` event
        events = [SessionStarted()]
             
        ## Send a message to user when starting
        dispatcher.utter_message(response="utter_session_start", name="Matthieu")

        # an `action_listen` should be added at the end as a user message follows
        events.append(ActionExecuted("action_listen"))

        return events
```

With `utter_session_start` defined in the responses of `domain.yml `file:

```
responses:
  utter_session_start:
      - text: "Bonjour {name}, bienvenu dans cette nouvelle session en ma compagnie !"
```
These are really few modifications compared to the initial code and the problem still stay the same.
