### ISSUE TITLE
the file of form.py may has little some errors

### ISSUE THREAD

**Issue by liuzhiyong01** [RasaHQ/rasa#8359]
**Rasa version**:
2.4

**Rasa SDK version** (if used & relevant): 
no

**Rasa X version** (if used & relevant):
no

**Python version**:
3.8

**Operating system** (windows, osx, ...):
osx

**Issue**:
In the form.py file, the function of entity_is_desired may has little errors

![image](https://user-images.githubusercontent.com/13724286/113378789-72856400-93aa-11eb-89fd-3dfd15c9cfcc.png)
this condition is always true

**Error (including full traceback)**:
```
no
```

**Command or request that led to error**:
```
no
```

**Content of configuration file (config.yml)** (if relevant):
```yml
no
```

**Content of domain file (domain.yml)** (if relevant):
```yml
no
```

**Comment by sara-tagger** [comment]
Thanks for raising this issue, @erohmensing will get back to you about it soon✨

###### Please also check out the [docs](https://rasa.com/docs/) and the [forum](https://forum.rasa.com/) in case your issue was raised there too 🤗

**Comment by erohmensing** [comment]
Hi there, I've looked, and this doesn't seem to be the code from rasa 2.4 or from the `main` branch. Can you add more information to where you found this?

**Comment by liuzhiyong01** [comment]
sorry, I have checked my code, this is not a problem, my falut!

**Comment by liuzhiyong01** [comment]
> Hi there, I've looked, and this doesn't seem to be the code from rasa 2.4 or from the `main` branch. Can you add more information to where you found this?

sorry, I have checked my code, this is not a problem, my fault, I will close this issue
