### ISSUE TITLE
RASA form gets reset before It completes the form

### ISSUE THREAD

**Issue by woja6494** [RasaHQ/rasa#8366]
**Rasa version**: 1.10.9

**Rasa SDK version** (if used & relevant): 1.10.3

**Rasa X version** (if used & relevant):

**Python version**: 3.6.9

**Operating system** (windows, osx, ...): Windows, Red Hat Enterprise Linux Server release 7.9(docker)

**Issue**:
I'm using gunicorn and rasa_sdk to run a rasa model. While I'm running RASA form (after taking 1 or 2 inputs), debug console is saying "there is no form activated" and fallback policy is triggered with input after the debug console statement. Seems like tracker state is lost also during the process. But this is only happening when I used rasa_sdk with gunicorn. RASA shell with same model file works totally fine.

**Error (including full traceback)**:
```

```

**Command or request that led to error**:
```

```

**Content of configuration file (config.yml)** (if relevant):
```yml

```

**Content of domain file (domain.yml)** (if relevant):
```yml

```

**Comment by sara-tagger** [comment]
Thanks for raising this issue, @kalkbrennerei will get back to you about it soon✨

###### Please also check out the [docs](https://rasa.com/docs/) and the [forum](https://forum.rasa.com/) in case your issue was raised there too 🤗

**Comment by woja6494** [comment]
any updates?

**Comment by joejuzl** [comment]
Hi @woja6494 , if you are still having trouble with this the forum would be a better place to get help: https://forum.rasa.com/ 
If it turns out to be a bug, you can re-open this issue.
