### ISSUE TITLE
`DialogueStateTracker` class has a `_merge_slots` method that is never used

### ISSUE THREAD

**Issue by amn41** [RasaHQ/rasa#8367]
**Description of Problem**:

The `DialogueStateTracker` class has a [method](https://github.com/RasaHQ/rasa/blob/d32c57c044d072ee8f05dd2a5c0312d0dff7a452/rasa/shared/core/trackers.py#L856) which is never called in the codebase

**Definition of Done**:

- [ ] Remove unused code (or add a comment explaining if it somehow turns out to be necessary)
- [ ] Feature mentioned in the changelog

**Comment by joejuzl** [comment]
fixed by https://github.com/RasaHQ/rasa/pull/8428
