### ISSUE TITLE
Flaky `test_cli_start_is_fast` test

### ISSUE THREAD

**Issue by alwx** [RasaHQ/rasa#8396]
**Rasa version**: 2.4.2

**Python version**: 3.7 & 3.8

**Operating system** (windows, osx, ...): Linux 

**Issue**:
`test_cli_start_is_fast` sometimes fails when running on CI.

```
# tensorflow is slow -> can't get imported when running basic CLI commands
>       result.stderr.no_fnmatch_line("*tensorflow.python.eager")
E       Failed: nomatch: '*tensorflow.python.eager'
E           and: 'import time: self [us] | cumulative | imported package'
E           and: 'import time:       104 |        104 | zipimport'
E           and: 'import time:       807 |        807 | _frozen_importlib_external'
E           and: 'import time:       105 |        105 |     _codecs'
...
```

Examples:
- https://github.com/RasaHQ/rasa/runs/2230855356?check_suite_focus=true
- https://github.com/RasaHQ/rasa/runs/2227422768?check_suite_focus=true

**Comment by wochinge** [comment]
How did you find these failing checks @alwx ? I checked both runs and they failed correctly. I've commented in the PR with the solution: https://github.com/RasaHQ/rasa/pull/7584/files#r611545880

**Comment by alwx** [comment]
It seems like it's my mistake then. If they fail correctly then this one can simply be closed.

**Comment by wochinge** [comment]
Coolio - did you look at metabase for identifying the flakey tests or how did you go about it?

**Comment by wochinge** [comment]
@alwx ?
