### ISSUE TITLE
Test Documentation stage failure

### ISSUE THREAD

**Issue by alwx** [RasaHQ/rasa#8397]
**Rasa version**: 2.4.2

**Python version**: 3.7 & 3.8

**Operating system** (windows, osx, ...): Linux 

**Issue**:
```
Run fountainhead/action-wait-for-check@4699210ccc66e2a13260803fadbb77085421b891
Retrieving check runs named Test Documentation on RasaHQ/rasa@treat-list-custom-json-facebook...
Error: No commit found for SHA: treat-list-custom-json-facebook
```
(https://github.com/RasaHQ/rasa/pull/8332/checks?check_run_id=2219807602)

```
Run fountainhead/action-wait-for-check@4699210ccc66e2a13260803fadbb77085421b891
Retrieving check runs named Test Documentation on RasaHQ/rasa@watson-emulate...
Error: No commit found for SHA: watson-emulate
```
(https://github.com/RasaHQ/rasa/runs/2246047514?check_suite_focus=true)

**Comment by HotThoughts** [comment]
Fixed in https://github.com/RasaHQ/rasa/pull/8401. Left a comment there to encourage the contributor to update the branch.
