### ISSUE TITLE
IntentTEDPolicy: Adapt `rasa interactive`

### ISSUE THREAD

**Issue by wochinge** [RasaHQ/rasa#8421]
**Description of Problem**:
When there is an unlikely intent, `IntentTEDPolicy` predicts an `action_unlikely_intent` to indicate the unlikely intent. This could be confusing to the user as they don't know where this action is coming from.

**Overview of the Solution**:
When the model predicted this action as part of `rasa interactive` we want to give them additional explanation why this action was predicted. Users can then choose to confirm / deny the action prediction as usual but it doesn't really matter as running this action doesn't have any implications.

[See more information in the implementation proposal.](https://www.notion.so/rasa/Implementation-Proposal-IntentTedPolicy-f16c3eb785964b1ca1249d508f6dc234#b491aa7f877b4db7a8629af1029d288c)

**Blockers** (if relevant):
- [x] Implemented `IntentTEDPolicy`
- [x] https://github.com/RasaHQ/rasa/issues/8417

**Definition of Done**:
- [ ] Interactive displays the explanation for the prediction of `action_unlikely_intent` to the user.
- [ ] somebody from CSE double checked the UX of the explanation

**Comment by alwx** [comment]
@RasaHQ/cseteam there are multiple ways of how we can do that. What do you think would be the correct message for this case?
