### ISSUE TITLE
Exception: Failed to load TED policy model.

### ISSUE THREAD

**Issue by Timodhau** [RasaHQ/rasa#8425]
I trained a model with 2 intents and 2 answers, my config is default one.  When i am trying to load the model after training i get:

Exception: Failed to load TED policy model. Path '/tmp/tmp7oxp3g_7/core/policy_1_TEDPolicy' doesn't exist.

**Comment by sara-tagger** [comment]
Thanks for the issue, @TyDunn will get back to you about it soon!

###### You may find help in the [docs](https://rasa.com/docs/) and the [forum,](https://forum.rasa.com/) too 🤗

**Comment by TyDunn** [comment]
Hi @Timodhau. It's better to ask questions like this on the [Rasa forum](https://forum.rasa.com/), but we can discuss here since you have already posted. Does training work with the assistant that is set up after you run `rasa init`?

**Comment by Timodhau** [comment]
Yes it works.

**Comment by TyDunn** [comment]
What version of Rasa Open Source are you using? Can you please share your domain, NLU training data, and any stories / rules?

**Comment by Timodhau** [comment]
rasa 2.0.2

domain:
session_config:
  session_expiration_time: 60
  carry_over_slots_to_new_session: true
intents:
- affirm
- deny
- info_test
responses:
  utter_ask_psytest:
  - text: Do you want to do a short test?
  utter_info_test:
  - text: It is a test of 20 logical questions. Just give me your answer after my
      question. Do we start?

nlut td:
version: "2.0"
nlu:
- intent: affirm
  examples: |
    - yes
    - y
    - indeed
    - of course
    - that sounds good
    - correct
- intent: deny
  examples: |
    - no
    - n
    - never
    - I don't think so
    - don't like that
    - no way
    - not really
- intent: info_test
  examples: |
    - what is this test about?
    - what test is it?
    - what should i do?

another strange thing is that a rule in rasa x is in my file stories:
version: "2.0"
rules:
- rule: give information about test
  steps:
  - intent: info_test
  - action: utter_info_test

**Comment by TyDunn** [comment]
Since you do not have any stories, does it work if you remove the TED policy from your config, train a model, and then load it?

**Comment by Timodhau** [comment]
I used the default one, there is nothing inside my config file, what should i put instead?

**Comment by TyDunn** [comment]
@Timodhau You can adjust he default config like so:

```
# Configuration for Rasa NLU.
# https://rasa.com/docs/rasa/nlu/components/
language: en

pipeline:
# # No configuration for the NLU pipeline was provided. The following default pipeline was used to train your model.
# # If you'd like to customize it, uncomment and adjust the pipeline.
# # See https://rasa.com/docs/rasa/tuning-your-model for more information.
#   - name: WhitespaceTokenizer
#   - name: RegexFeaturizer
#   - name: LexicalSyntacticFeaturizer
#   - name: CountVectorsFeaturizer
#   - name: CountVectorsFeaturizer
#     analyzer: char_wb
#     min_ngram: 1
#     max_ngram: 4
#   - name: DIETClassifier
#     epochs: 100
#   - name: EntitySynonymMapper
#   - name: ResponseSelector
#     epochs: 100
#   - name: FallbackClassifier
#     threshold: 0.3
#     ambiguity_threshold: 0.1

# Configuration for Rasa Core.
# https://rasa.com/docs/rasa/core/policies/
policies:
- name: RulePolicy
```

**Comment by Timodhau** [comment]
just tried it and yes it worked
