### ISSUE TITLE
IntentTEDPolicy: Evaluate and document learnings

### ISSUE THREAD

**Issue by dakshvar22** [RasaHQ/rasa#8440]
**Description of Problem**:
We need to objectively understand where `IntentTEDPolicy` is useful.

**Overview of the Solution**:
Use conversation logs from Sara or a STAR bot and play with the policy to understand the scenarios in which the policy is actually useful. For example - 

1. What's the limit of the policy while trying to surface conversations not represented by training stories?
2. Can the policy surface conversations where NLU makes a mistake because of contextual complexity?
3. How does `tolerance` parameter affect the usage of the policy?

The above list is just a sample. More of such questions should be objectively studied, documented internally and also in our open source docs.

**Blockers** (if relevant):
Hard blocker: Policy should be implemented as part of https://github.com/RasaHQ/rasa/issues/8439
Soft Blocker: https://github.com/RasaHQ/rasa/issues/7412

**Definition of Done**:
- [x] Conversations from at least 2 assistants are studied for at least 3 conversation patterns
- [x] Learnings are documented in Rasa Open Source docs

**Comment by kedz** [comment]
Internal write up of this exploration can be found [here](https://www.notion.so/rasa/IntentTED-Use-Case-Exploration-eb67c3a238f14ae1a3b9a37780751f95).
