### ISSUE TITLE
TypeError: name() takes 0 positional arguments but 1 was given r

### ISSUE THREAD

**Issue by Gourav-infobiz** [RasaHQ/rasa#8449]
Rasa version: 2.4.x

Python version: 3.7.0

rasa_server_1    |   File "/opt/venv/lib/python3.8/site-packages/rasa/core/channels/channel.py", line 89, in register
rasa_server_1    |     p = urljoin(route, channel.url_prefix())
rasa_server_1    |   File "/opt/venv/lib/python3.8/site-packages/rasa/core/channels/channel.py", line 108, in url_prefix
rasa_server_1    |     return self.name()
rasa_server_1    | TypeError: name() takes 0 positional arguments but 1 was given
r

**Comment by sara-tagger** [comment]
Thanks for raising this issue, @wochinge will get back to you about it soon✨

###### Please also check out the [docs](https://rasa.com/docs/) and the [forum](https://forum.rasa.com/) in case your issue was raised there too 🤗

**Comment by wochinge** [comment]
@Gourav-infobiz Did you implement a custom channel? Could you please share your `credentials.yml` here (without passwords please :-))

**Comment by Gourav-infobiz** [comment]
> @Gourav-infobiz Did you implement a custom channel? Could you please share your `credentials.yml` here (without passwords please :-))


![Uploading image.png…]()

**Comment by Gourav-infobiz** [comment]
![image](https://user-images.githubusercontent.com/70999585/114555058-f978ed00-9c84-11eb-8ac6-8327abd1645d.png)

**Comment by Gourav-infobiz** [comment]
> @Gourav-infobiz Did you implement a custom channel? Could you please share your `credentials.yml` here (without passwords please :-))

Please find the attachment above.

**Comment by wochinge** [comment]
@Gourav-infobiz I only see the screenshot. To me this looks like an implementation error in the custom connector. In that case the [Rasa forum](https://forum.rasa.com) is the better place to discuss the implementation of this as its not a bug in Rasa Open Source itself.
