### ISSUE TITLE
Non expressive variable name on `interactive.py`

### ISSUE THREAD

**Issue by rafaelteodosio** [RasaHQ/rasa#8453]
**Issue**:  On file `...\core\training\interactive.py` in the line `839`  has a variable with a non expressive name `i`. 

**Overview of the Solution:**:
Change the name from `i` to something like `interactive_story_counter`.

**Comment by sara-tagger** [comment]
Thanks for raising this issue, @joejuzl will get back to you about it soon✨

###### Please also check out the [docs](https://rasa.com/docs/) and the [forum](https://forum.rasa.com/) in case your issue was raised there too 🤗
