### ISSUE TITLE
Non expressive variable name on `transformer.py` 

### ISSUE THREAD

**Issue by joaoCeilandia** [RasaHQ/rasa#8461]
**Description of Problem**:
Issue: On file `...\utils\tensorflow\transformer.py` in the line `566` has a variable with a non expressive name `i`.

**Overview of the Solution**:
Change the name from `i` to something more expressive.

**Comment by sara-tagger** [comment]
Thanks for submitting this feature request 🚀 @melindaloubser1 will get back to you about it soon! ✨

**Comment by melindaloubser1** [comment]
https://github.com/RasaHQ/rasa/blob/c6142ebf833a5fac7d26dee9fff757b390091cb0/rasa/utils/tensorflow/transformer.py#L565-L567

What would you change it to?

**Comment by melindaloubser1** [comment]
Since you already opened a PR to fix https://github.com/RasaHQ/rasa/issues/8453, you could add a fix there for this too
