### ISSUE TITLE
Non expressive variable name on `domain.py`

### ISSUE THREAD

**Issue by joaoCeilandia** [RasaHQ/rasa#8463]
**Description of Problem**:
Issue: On file `...\shared\core\domain.py` in the line `250` and `252` has two variables with non expressive names `a` and `b`.

**Overview of the Solution**:
Change the name from `a` and `b` to something more expressive.

**Comment by sara-tagger** [comment]
Thanks for submitting this feature request 🚀 @JustinaPetr will get back to you about it soon! ✨
