### ISSUE TITLE
Vulnerability GitHub issues created by trivy are created in duplicate

### ISSUE THREAD

**Issue by m-vdb** [RasaHQ/rasa#8474]
See issues here: https://github.com/RasaHQ/rasa/issues?q=is%3Aissue+author%3Aapp%2Fgithub-actions+label%3Atool%3Atrivy+is%3Aclosed

Additionally, it'd be nice to add them automatically to Enable's project board

**Comment by m-vdb** [comment]
Fixed the behaviour in this PR on Tobias' fork: https://github.com/wochinge/gitrivy/pull/3

@wochinge what did you want to talk about regarding this issue?

**Comment by wochinge** [comment]
Thanks for the PR, @m-vdb ! I was wondering if it even makes sense to keep maintaining this. How about switching to https://github.com/aquasecurity/trivy-action and then implement the few extra lines for the issue creation? We'll need customization to add it to boards anyway. Seems to give us more flexibility + it's easier to maintain

**Comment by m-vdb** [comment]
I agree it'd be better re composability and maintainability.

> implement the few extra lines for the issue creation

It might prove difficult to implement the "create or update" behaviour. But I think we can do without (and only create an issue if there is none matching the labels)

> We'll need customization to add it to boards anyway

Tempted to implement this in another workflow, because it could benefit some use cases (e.g. you have a workflow that listens to issue creation + label changes and adds the issue to a project if it's not already added to a project, following a config)

**Comment by m-vdb** [comment]
@wochinge after I did some research, I don't think it makes too much sense to change the action we rely on. Maybe we can make the forked action part of `RasaHQ` org to relieve the pressure for you. While there are many actions out there, none was really a drop-in replacement for the things we wanted to do. we can continue the discussion on the PR if you want

**Comment by wochinge** [comment]
good for me as it is then 👍🏻
