### ISSUE TITLE
Training issue

### ISSUE THREAD

**Issue by Jinay09** [RasaHQ/rasa#8486]
Hi, I'm creating a chatbot for assessment but the issue is that when I try to train the data it doesn't remember previous training.

**Comment by sara-tagger** [comment]
Thanks for raising this issue, @b-quachtran will get back to you about it soon✨

###### Please also check out the [docs](https://rasa.com/docs/) and the [forum](https://forum.rasa.com/) in case your issue was raised there too 🤗

**Comment by TyDunn** [comment]
Hi @Jinay09. If this still an issue, can you please try providing more details and ask your question on the Rasa forum?
