### ISSUE TITLE
Architecture prototype: Try the prototype with realistic data sets

### ISSUE THREAD

**Issue by joejuzl** [RasaHQ/rasa#8488]
**Description of Problem**:
Once we have the prototype training and predicting we need to know it actually works properly with realistic data (Sara bot).

**Overview of the Solution**:
We should try training on some realistic data sets and check predictions work accordingly.
It should also be able to handle large amounts of data.

**Blockers** (if relevant):
#8412 

**Definition of Done**:
- [ ] Training completes as fast as 2.0
- [ ] Predictions are correct and are as fast as 2.0

**Comment by wochinge** [comment]
(I had to remove all rules as Sara seams to contain conflicting rules which lead to a failed training)

**Training**:
* `rasa train` on `main`: 	40m11.933s
* `prototype`:

**Prediction Time**
I did 1000 predictions:

* `rasa` on `main` :
* `prototype`:
