### ISSUE TITLE
Enable flake8 code `E501`

### ISSUE THREAD

**Issue by wochinge** [RasaHQ/rasa#8490]
**Description of Problem**:
[We currently ignore Flake E501 warnings for too long lines.
](https://github.com/RasaHQ/rasa/blob/3bc3cf4dedc901241e4aba72c741b5c7a6e5c1d1/setup.cfg#L28)

**Overview of the Solution**:
* exclude `E501` from ignore test
* fix too long lines issues from `make lint`

**Definition of Done**:
- [ ] `E501` is no longer ignored
- [ ] the CI passes

**Comment by iurisevero** [comment]
Hey there. I would like to work on this issue if it's available :)

**Comment by wochinge** [comment]
sounds good! Thanks for your support @iurisevero
