### ISSUE TITLE
Case insensitive entity labeling

### ISSUE THREAD

**Issue by akelad** [RasaHQ/rasa#850]
At the moment, entity labels are case sensitive:

e.g. `"entity":"origin"` and `"entity":"Origin"` are two different entities

We should make this case insensitive

**Comment by wrathagom** [comment]
@tmbo @amn41 this one is up to you all.

**Comment by amn41** [comment]
this makes total sense and we should do it.

NB for anyone reading this this means that e.g. `"origin": "San Francisco"` and `"Origin": "San Francisco"` are identical. 

This has nothing to do with the capitalisation of the entity *value* (e.g. San Francisco vs san francisco)

**Comment by akelad** [comment]
Just had another thought about this. We need to watch out with this - so for the `ner_crf` module this makes complete sense. But I saw that for example `ner_spacy` has the entity `ORDINAL`, whereas `ner_duckling` has the entity `ordinal`. In that case we'd probably want to be able to distinguish between the two.

**Comment by wrathagom** [comment]
@tmbo @amn41 did this one make it in at some point?

**Comment by tmbo** [comment]
I mean you can still distinguish between them because the extractor is part of the result. 

But no, not implemented yet.

**Comment by RanaMostafaAbdElMohsen** [comment]
Hi @akelad 
Can I work on this issue?

**Comment by erohmensing** [comment]
@Ghostvv  this has been taken care of, right?

**Comment by Ghostvv** [comment]
yes, there are options in several components to make them case insensitive
