### ISSUE TITLE
Crypto dependency is not installed on 1.10.x

### ISSUE THREAD

**Issue by sarhugo** [RasaHQ/rasa#8509]
**Rasa version**: 1.10.x

**Rasa SDK version** (if used & relevant):

**Rasa X version** (if used & relevant):

**Python version**: 3.7

**Operating system** (windows, osx, ...): linux

**Issue**: 

This fix https://github.com/RasaHQ/rasa/commit/d7731faa0172824b07bd47b20d861dab03a68beb should also be included on the 1.10.x branch of Rasa, the missing algorith error also happen there.

**Error (including full traceback)**:
```

```

**Command or request that led to error**:
```

```

**Content of configuration file (config.yml)** (if relevant):
```yml

```

**Content of domain file (domain.yml)** (if relevant):
```yml

```

**Comment by sarhugo** [comment]
Adding `cryptography = ">=3.2.1"` to the `[tool.poetry.dependencies]` section at pyproject.toml solved the issue

**Comment by sara-tagger** [comment]
Thanks for the issue, @degiz will get back to you about it soon!

###### You may find help in the [docs](https://rasa.com/docs/) and the [forum,](https://forum.rasa.com/) too 🤗
