### ISSUE TITLE
TrackerStore: MySQLTimeout after 8 hours (`MySQL server has gone away`)

### ISSUE THREAD

**Issue by wochinge** [RasaHQ/rasa#8515]
**Issue**: MySQL automatically closes idle connections after 8 hours by default.

**Solution** Do as described <span class="error">[here]</span>(MySQL server has gone away) and to enable the `create_engine.pool_recycle `.

**Error (including full traceback)**:

MySQLdb._exceptions.OperationalError: (2006, 'MySQL server has gone away') The above exception was the direct cause of the following exception: Traceback (most recent call last): File "/usr/local/lib/python3.6/asyncio/coroutines.py", line 126, in send return self.gen.send(value) File "/usr/local/lib/python3.6/site-packages/socketio/asyncio_server.py", line 438, in _handle_event_internal r = await server._trigger_event(data<span class="error">[0]</span>, namespace, sid, **data<span class="error">[1:]</span>) File "/usr/local/lib/python3.6/asyncio/coroutines.py", line 110, in *next** return self.gen.send(None) File "/usr/local/lib/python3.6/site-packages/socketio/asyncio_server.py", line 466, in _trigger_event ret = await self.handlers<span class="error">[namespace]</span><span class="error">[event]</span>(**args) File "/usr/local/lib/python3.6/asyncio/coroutines.py", line 110, in *next** return self.gen.send(None) File "/usr/local/lib/python3.6/site-packages/rasa/core/channels/socketio.py", line 190, in handle_message await on_new_message(message) File "/usr/local/lib/python3.6/asyncio/coroutines.py", line 110, in **next** return self.gen.send(None) File "/usr/local/lib/python3.6/site-packages/rasa/core/channels/channel.py", line 81, in handler await app.agent.handle_message(**args, **kwargs) File "/usr/local/lib/python3.6/asyncio/coroutines.py", line 110, in *next** return self.gen.send(None) File "/usr/local/lib/python3.6/site-packages/rasa/core/agent.py", line 471, in handle_message return await processor.handle_message(message) File "/usr/local/lib/python3.6/asyncio/coroutines.py", line 110, in **next** return self.gen.send(None) File "/usr/local/lib/python3.6/site-packages/rasa/core/processor.py", line 80, in handle_message tracker = await self.log_message(message, should_save_tracker=False) File "/usr/local/lib/python3.6/asyncio/coroutines.py", line 110, in **next** return self.gen.send(None) File "/usr/local/lib/python3.6/site-packages/rasa/core/processor.py", line 150, in log_message tracker = self._get_tracker(message.sender_id) File "/usr/local/lib/python3.6/site-packages/rasa/core/processor.py", line 552, in _get_ 

**Command or request that led to error**:

rasa run

**Definition of Done**

*   [ ] Rasa Open Source automatically renews old connections to avoid a timeout

**Comment by m-vdb** [comment]
Closing as stale
