### ISSUE TITLE
Look up in RASA 2.0

### ISSUE THREAD

**Issue by Jinay09** [RasaHQ/rasa#8524]
Hi, I'm currently using RASA 2.0 version 

I want to add a look-up table for my chatbot
look-up for the country, name, and more.
Can you guide me?

**Comment by sara-tagger** [comment]
Thanks for raising this issue, @jupyterjazz will get back to you about it soon✨

###### Please also check out the [docs](https://rasa.com/docs/) and the [forum](https://forum.rasa.com/) in case your issue was raised there too 🤗

**Comment by koernerfelicia** [comment]
Hi @Jinay09, if you're not reporting a bug or making a feature request please ask these kinds of questions in the [forum](forum.rasa.com).

You can read more about lookup tables [here](https://rasa.com/docs/rasa/nlu-training-data/#lookup-tables). You can add a lookup table to your `nlu.yml` file, like so:
```
nlu:
- lookup: country
  examples: |
    - Afghanistan
    - Albania
    - Zambia
    - Zimbabwe
```

You'll also need to include the `RegexEntityExtractor` in your pipeline, and include at least two annotated examples with the entity you want to look up, for example:
```
- intent: location
  examples: |
    - I am from [Albania](location)
    - I come from [Afghanistan](location)
```
If you get stuck, please feel free to ask more questions in the forum!

**Comment by Jinay09** [comment]
Thank you for your response. @koernerfelicia
