### ISSUE TITLE
Implement code boundaries in CODEOWNERs file

### ISSUE THREAD

**Issue by wochinge** [RasaHQ/rasa#8525]
**Description of Problem**:
We recently split the codebase into Research / Engineering owned code: https://www.notion.so/rasa/Proposal-for-Engineering-Research-Code-boundaries-d292e938324b416db03b382503690839?d=a6365544-6866-4b9c-bffe-a8a40a3e7bec

**Overview of the Solution**:
Adapt the `CODEOWNERS` file to reflext the ownerships specified in the document.

**Definition of Done**:
- [x] CODEOWNERs file is updated.
- [x] Share message in channel that this is in place

**Comment by joejuzl** [comment]
I've moved this above the prio line as we should follow up on this to make use of all the work that went into the determining the boundaries.
