### ISSUE TITLE
Create plan for modules with mixed concerns

### ISSUE THREAD

**Issue by wochinge** [RasaHQ/rasa#8526]
**Description of Problem**: We recently split the codebase into Research / Engineering owned code: [https://www.notion.so/rasa/Proposal-for-Engineering-Research-Code-boundaries-d292e938324b416db03b382503690839?d=a6365544-6866-4b9c-bffe-a8a40a3e7bec](https://www.notion.so/rasa/Proposal-for-Engineering-Research-Code-boundaries-d292e938324b416db03b382503690839?d=a6365544-6866-4b9c-bffe-a8a40a3e7bec) . Some modules are handling too many concerns, e.g. the `Domain` which is handling both featurization but also represents training data. These modules are hence difficult to assign a specific codeowner to as both teams have big stakes in them.

**Overview of the Solution**: Probably enough to get an overview and a rough plan for the modules. The change might be done now or later as part of our Rasa Open Source 3.0 changes.

**Examples** (if relevant):

**Blockers** (if relevant):

**Definition of Done**:

*   [ ] we have a full list of modules which should be split
*   [ ] we have a rough plan for each module how we split it
*   [ ] we shared this plan with research

**Comment by m-vdb** [comment]
Closing as stale
