### ISSUE TITLE
Variables with a non expressive name and refactoring method.

### ISSUE THREAD

**Issue by jppgomes** [RasaHQ/rasa#8527]
Description of Problem:
on the files:

rasa/shared/core/domain.py
has some variables with a non expressive name and refactoring method.

Overview of the Solution:
Changing variables that are just letters to names that express exactly what the variable represents.

**Comment by sara-tagger** [comment]
Thanks for raising this issue, @Ghostvv will get back to you about it soon✨

###### Please also check out the [docs](https://rasa.com/docs/) and the [forum](https://forum.rasa.com/) in case your issue was raised there too 🤗

**Comment by Ghostvv** [comment]
can you give an example?
