### ISSUE TITLE
Wrong link in Rasa Contribute page

### ISSUE THREAD

**Issue by iurisevero** [RasaHQ/rasa#8539]
**Issue**:
On [Rasa Contribute page](https://rasa.com/community/contribute/), at the "Like to write code?" tab, the link to [Rasa Docs](https://rasa.com/docs/) is wrong. It is redirecting the user to the [Report a Bug](https://github.com/RasaHQ/rasa/issues/new/choose) instead.

**Error (including full traceback)**:
![image](https://user-images.githubusercontent.com/42645264/115975044-df1df980-a537-11eb-9284-8038fc71480a.png)

In the bottom left corner of the image, you can see that the link added is https://github.com/RasaHQ/rasa/issues/new/choose instead of https://rasa.com/docs/

**Comment by iurisevero** [comment]
I don't know if this issue should've been open here, but I didn't find another place where I could've done that, so.... 😅

**Comment by Ayushsunny** [comment]
Hello @virtualroot may I make PR for this issue?

**Comment by sara-tagger** [comment]
Thanks for raising this issue, @mvielkind will get back to you about it soon✨

###### Please also check out the [docs](https://rasa.com/docs/) and the [forum](https://forum.rasa.com/) in case your issue was raised there too 🤗

**Comment by TyDunn** [comment]
@lunelson are you able to update this?

**Comment by lunelson** [comment]
I think this is intentional, but I agree it's a bit confusing: opening a new issue is actually the right way to contribute to the docs, but maybe @karen-white has some thoughts on what this should say?

**Comment by karen-white** [comment]
@lunelson How about, "[Open a Feature Request issue](https://github.com/RasaHQ/rasa/issues/new/choose) to suggest new code examples for the [Rasa docs](https://rasa.com/docs)"

**Comment by TyDunn** [comment]
Another thought: keep the language the same but link [here](https://github.com/RasaHQ/rasa/tree/main/docs/docs)

**Comment by lunelson** [comment]
@karen-white I think that's an elegant solution—PR is up for review
