### ISSUE TITLE
Adding "user" to a story will result an error

### ISSUE THREAD

**Issue by zfallahnejad** [RasaHQ/rasa#8540]
**Rasa version**:0.38.1 **Rasa SDK version**:2.4.1 **Rasa X version** :2.4.3 **Python version**:3.8.5 **Operating system** (windows, osx, ...): ubuntu

I read about end-to-end (e2e) learning in this [here](https://blog.rasa.com/were-a-step-closer-to-getting-rid-of-intents/). I have a bot and I wanted to add a story containing the user keyword to it. Something like this:

*   story: story name steps:
*   intent: ...
*   action: utter_...
*   user: “hi”
*   action: utter_...

Exactly like the example mentioned in the link, but with my intent and action. When I try to add this story in Rasa X panel, it does not accept it and I see the following error in the log.

rasa-x_1 | <span class="error">[2021-04-25 05:14:00 +0000]</span> <span class="error">[41]</span> <span class="error">[ERROR]</span> Exception occurred while handling uri: '[http://172.16.17.63/api/stories/110](http://172.16.17.63/api/stories/110)' rasa-x_1 | Traceback (most recent call last): rasa-x_1 | File "/usr/local/lib/python3.8/dist-packages/sanic/app.py", line 973, in handle_request rasa-x_1 | response = await response rasa-x_1 | File "/usr/local/lib/python3.8/dist-packages/rasax/community/api/decorators.py", line 216, in decorated_function rasa-x_1 | return await await_and_return_response(args, kwargs, request) rasa-x_1 | File "/usr/local/lib/python3.8/dist-packages/rasax/community/api/decorators.py", line 146, in await_and_return_response rasa-x_1 | response = await response rasa-x_1 | File "/usr/local/lib/python3.8/dist-packages/rasax/community/api/decorators.py", line 53, in decorated_function rasa-x_1 | return await f(request, user=user, *args, **kwargs) rasa-x_1 | File "/usr/local/lib/python3.8/dist-packages/rasax/community/api/blueprints/core/stories.py", line 315, in modify_story rasa-x_1 | updated_story = await StoryService.from_request(request).update_story( rasa-x_1 | File "/usr/local/lib/python3.8/dist-packages/rasax/community/services/story_service.py", line 928, in update_story rasa-x_1 | await self.add_domain_items_for_story( rasa-x_1 | File "/usr/local/lib/python3.8/dist-packages/rasax/community/services/story_service.py", line 835, in add_domain_items_for_story rasa-x_1 | await self._add_story_items_to_domain(project_id, username, story_events) rasa-x_1 | File "/usr/local/lib/python3.8/dist-packages/rasax/community/services/story_service.py", line 857, in _add_story_items_to_domain rasa-x_1 | domain_service.add_items_to_domain( rasa-x_1 | File "/usr/local/lib/python3.8/dist-packages/rasax/community/services/domain_service.py", line 822, in add_items_to_domain rasa-x_1 | self._add_intents_to_domain(domain, project_id, intents, origin) rasa-x_1 | File "/usr/local/lib/python3.8/dist-packages/rasax/community/services/domain_service.py", line 753, in _add_intents_to_domain rasa-x_1 | set(intents) - self._get_retrieval_intents(intents) - domain_intents rasa-x_1 | File "/usr/local/lib/python3.8/dist-packages/rasax/community/services/domain_service.py", line 742, in _get_retrieval_intents rasa-x_1 | return set(<span class="error">[i for i in intents if RESPONSE_IDENTIFIER_DELIMITER in i]</span>) rasa-x_1 | File "/usr/local/lib/python3.8/dist-packages/rasax/community/services/domain_service.py", line 742, in rasa-x_1 | return set(<span class="error">[i for i in intents if RESPONSE_IDENTIFIER_DELIMITER in i]</span>) rasa-x_1 | TypeError: argument of type 'NoneType' is not iterable

Deleting the user keyword solves the problem and the story is valid without it. I only see this error when I use the user keyword in the story.

**Comment by Dustyposa** [comment]
Change char `“` to `"`, have a try, like below：
```yaml
- story: story name
  steps:
  - intent: ...
  - action: utter_...
  - user: "hi"
  - action: utter_...
 ```

**Comment by zfallahnejad** [comment]
I'm facing the same issue whether I use `“` or `"` or neither of them.

**Comment by sara-tagger** [comment]
Thanks for raising this issue, @desmarchris will get back to you about it soon✨

###### Please also check out the [docs](https://rasa.com/docs/) and the [forum](https://forum.rasa.com/) in case your issue was raised there too 🤗

**Comment by alexweidauer** [comment]
Thank you for raising this issue about Rasa X. We decided to stop supporting the Community Edition (free version) of ‘Rasa X’ (see more info here: https://rasa.com/blog/rasa-x-community-edition-changes/). That’s why we’ve closed your issue. We suggest that Rasa Enterprise customers raise the issue with our customer support team if they haven’t done so already.
