### ISSUE TITLE
AttributeError: ‘NoneType’ object has no attribute ‘startswith’

### ISSUE THREAD

**Issue by scolarometer** [RasaHQ/rasa#8553]
I have set up rasa(1.10.2) and created a chatbot however when I access rasa x(0.32.) the payload buttons does not work. I tried rasa x --debug but it gives the error:

**rasa.core.channels.channel - An exception occured while handling user message ‘None’. if message.text.startswith(INTENT_MESSAGE_PREFIX): AttributeError: ‘NoneType’ object has no attribute 'startswith’**

The error is same if I use Rasa Chatroom. If I use rasa shell --debug everything works well without the error. I believe the error occurs when I click on a payload button in rasa x or in chatroom. In rasa x no responds is given other than **action listen** but if I enter the **nlu** question directly the bot replies in rasa x. I have tried to change the slot type or even remove it but still the bot always show **action listen** when a payload button is clicked

**Comment by sara-tagger** [comment]
Thanks for raising this issue, @rctatman will get back to you about it soon✨

###### Please also check out the [docs](https://rasa.com/docs/) and the [forum](https://forum.rasa.com/) in case your issue was raised there too 🤗
