### ISSUE TITLE
Support IAM authentication tokens for DB access

### ISSUE THREAD

**Issue by rgstephens** [RasaHQ/rasa#8554]
**Description of Problem**: For some use cases, there is a requirement that AWS RDS db access is done via regularly changing IAM tokens.

Could we possibly request a feature that would create a flag to pull authentication tokens during db connections? The code would look something like the examples on this documentation page: [https://docs.aws.amazon.com/AmazonRDS/latest/UserGuide/UsingWithRDS.IAMDBAuth.Connecting.Python.html](https://docs.aws.amazon.com/AmazonRDS/latest/UserGuide/UsingWithRDS.IAMDBAuth.Connecting.Python.html)

**Overview of the Solution**: Using sqlalchemy it may be possible to accomplish this as described [here](https://stackoverflow.com/questions/57562372/how-to-handle-ever-changing-password-in-sqlalchemypsycopg2)

**Comment by desmarchris** [comment]
@TyDunn could we get someone's opinion on doing this from engineering?

**Comment by TyDunn** [comment]
I moved this to Fabric squad cc @federicotdn

**Comment by alexweidauer** [comment]
Thank you for raising this issue about Rasa X. We decided to stop supporting the Community Edition (free version) of ‘Rasa X’ (see more info here: https://rasa.com/blog/rasa-x-community-edition-changes/). That’s why we’ve closed your issue. We suggest that Rasa Enterprise customers raise the issue with our customer support team if they haven’t done so already.
