### ISSUE TITLE
Support training on big datasets

### ISSUE THREAD

**Issue by twerkmeister** [RasaHQ/rasa#8595]
### Description of Problem

*   With big datasets we run into memory and computation time issues 
      *   multiwoz: 113,000 conversation turns, 8500 e2e stories
    *   ubuntu: 470,000 conversation turns, 75000 e2e stories
    *   advising: 269,000 conversation turns, 24500 e2e stories

### Status as of May 2021

There have been several attempts to tackle this issue:

*   training on chunks for NLU #8306 ([ideas doc](https://docs.google.com/document/d/1dwKfdju5ZqhOQtURLF3-eU3PdxvdlyXafPHE_0sLPzI/edit#heading=h.zcr9tisapqd4))
*   streamed training for NLU #8518
*   training on chunks for core [branch](https://github.com/RasaHQ/rasa/tree/partial-dataset-loading-core) with the draft [PR](https://github.com/RasaHQ/rasa/pull/8353) for it. **Note**: The branch currently has these [issues](https://github.com/RasaHQ/rasa/pull/8353#issuecomment-855813786) and cannot be adopted as the solution before they are addressed.
*   there have been improvements in the recent Rasa 3.0 prototypes in how tracker stores are featurized (benchmarking still outstanding #8593 )

These approaches haven't been finished yet, or haven't directly addressed the biggest bottleneck right now, which seems to be core training. According to this [forum post](https://forum.rasa.com/t/end-to-end-training-experimental/38158/21) 400 stories lead to out of memory for 12GB (GPU?) memory. Also, 400-500 stories seems to have been max for research so far, but potentially that wasn't with maxed out memory ([slack thread](https://rasa-hq.slack.com/archives/C01HHMR4X8S/p1620129515150400?thread_ts=1620127856.148000&cid=C01HHMR4X8S)). Part of #8593 is figuring out how much memory is consumed where in the core e2e training. This will help us decide which parts of the existing proposals to use to tackle this issue.

 _Product view of current status_ 

*   Goal: Support training on big datasets #8595
*   There are three problems that we need to work on to make this happen: 
      *   GPU memory issues (#8734)
    *   CPU memory issues (#8803)
    *   Slow preprocessing (#8803)

### Status as of July 2021

*   prototypes to address main memory, gpu memory, and processing time issues have been combined and tested in [8595-combined-e2e-fixes](https://github.com/RasaHQ/rasa/tree/8595-combined-e2e-fixes)
*   Issues for turning the fixes into production code: 
      *   #9019
    *   #9020
    *   #9021
    *   #9022
*   Dataset related issues 
      *   #9023
    *   #9024
*   other 
      *   #9025

**Definition of Done**: End2end training for the following corpora can be run on one of our cloud gpu servers:

*   <span class="error">[x]</span> multiwoz
*   [ ] Ubuntu
*   [ ] advising

**Comment by TyDunn** [comment]
We are also working on #8734 as part of this as well
