### ISSUE TITLE
Build a multi task assistant for validation of IntentTED

### ISSUE THREAD

**Issue by dakshvar22** [RasaHQ/rasa#8596]
According to the milestones we set for shipping `IntentTEDPolicy`, we want to validate the implementation by reliably detecting 3 conversation patterns that IntentTEDPolicy can flag. We need to build a simple demonstrable assistant for this.

What can be done?

We have already built several single task assistants for STAR tasks. We can merge two assistants built for a similar domain like `plane_search`, `plane_book` and create a new assistant. Naturally, the multi-task dialogues will involve task switching which the assistant should handle and IntentTED can help build multi-task stories. So, the simplest and probably fastest way to build this assistant would be to merge the stories, domains, intents from each assistant into one without modifying them. We should still deduplicate intents across the two assistants. The built assistant can use a mix of stories and rules but shouldn't be an assistant built only with rules.

Time estimation:
1 week

**Comment by tttthomasssss** [comment]
@dakshvar22 @JEM-Mosig does this require a code review such as any other issue?

**Comment by dakshvar22** [comment]
@tttthomasssss Nope, not required.

**Comment by dakshvar22** [comment]
@JEM-Mosig Could you please add a link to the repo where the assistant lives and then close this issue?

**Comment by JEM-Mosig** [comment]
Bot lives here: https://github.com/RasaHQ/STAR-bots/tree/johannes/assistants/super_airline_bot
