### ISSUE TITLE
DIETClassifier can't classify the entity “city” trained by lookup tables

### ISSUE THREAD

**Issue by kikiwang23** [RasaHQ/rasa#8604]
![image](https://user-images.githubusercontent.com/36537267/117022028-79e1b980-ad2a-11eb-9982-450407b3b7e1.png)
![image](https://user-images.githubusercontent.com/36537267/117022114-8cf48980-ad2a-11eb-9256-8c8fe13adf36.png)
![image](https://user-images.githubusercontent.com/36537267/117023072-579c6b80-ad2b-11eb-8ba3-d6279b729783.png)

my pipelines are as shown, the RegexEntityExtractor can classify the "city" written in the lookup tables, but DIETClassifier just can't,
anybody knows why? I really appreciate your help,thank you!

**Comment by sara-tagger** [comment]
Thanks for the issue, @desmarchris will get back to you about it soon!

###### You may find help in the [docs](https://rasa.com/docs/) and the [forum,](https://forum.rasa.com/) too 🤗

**Comment by desmarchris** [comment]
@kikiwang23 can you try again with enabling the [RegexFeaturizer](https://rasa.com/docs/rasa/components#regexfeaturizer)?

**Comment by TyDunn** [comment]
Please reopen if this is still an issue. Questions like this should be directed to the Rasa Forum in the future
