### ISSUE TITLE
Add error information in interface of RASA X

### ISSUE THREAD

**Issue by gioppoluca** [RasaHQ/rasa#8613]
**Description of Problem**: Using RASA X in the docker compose approach. When there is an error in model training we only get the red notice saying "there is an error". Now we have to enter the containers, look for logs, could be on the rasa-worker, on rasa-x on ... whatever. Is difficult to solve the problem since there is no error message to act upon

**Overview of the Solution**: Add the error mesage to the notice window

**Examples** (if relevant): If you have an error in the model (you forgot to write a response that you use in the story) rasa-worker has the error clearly expressed, but nothing get in RASAX, The same error should be exposed in web notice.

**Blockers** (if relevant): not relevant

**Definition of Done**: Just added in the notice should be enough (no documentation needed for this)

**Comment by sara-tagger** [comment]
Thanks for submitting this feature request 🚀 @tttthomasssss will get back to you about it soon! ✨
