### ISSUE TITLE
New Training Data APIs required

### ISSUE THREAD

**Issue by talhashaikh5** [RasaHQ/rasa#8619]
**Description of Problem**:

Need a GET/POST API in Rasa HTTP APIs for getting the training data. It will be really helpful if we can get the entire curd operation on training data of rasa like List intents, update intents, create intents, List Stories, Update stories, etc

**Overview of the Solution**:

Need to add these New apis in RASA HTTP APIs

**Examples** (if relevant):

**Blockers** (if relevant):

**Definition of Done**:

**Comment by sara-tagger** [comment]
Thanks for submitting this feature request 🚀 @samsucik will get back to you about it soon! ✨

**Comment by samsucik** [comment]
Hey @talhashaikh5, could you explain in more detail what's the use case, what is the problem that you can't solve without these APIs? Especially regarding _updating_ the domain & stories (i.e. the POST APIs).

**Comment by talhashaikh5** [comment]
Every time I don't want to go into the server or Github and update training data. There is an API to retrain the model but no API for updating training data

**Comment by samsucik** [comment]
I see. So, I think the APIs might be added in the future, but it's not a current priority as far as I know -- partly because right now we encourage users to manage their data via Rasa X.
