### ISSUE TITLE
Rasa X - Correcting action in Interactive Learning leads to invalid story beeing generated

### ISSUE THREAD

**Issue by dav-92** [RasaHQ/rasa#8622]
_Rasa version_ : 2.5.1

 _Rasa SDK version_ (if used & relevant):

 _Rasa X version_ (if used & relevant): 0.39.3 local mode (also happened with 0.37.x)

 _Python version_ : 3.8.5

 _Operating system_ (windows, osx, ...): Windows 10

 _Issue_ : When correcting a predicted action in rasa x interactive mode the generated story in the "story till now" window becomes invalid that means:

-the order of intents/actions may be wrong -some intents/actions may be missing

Before correcting the action the generated story is correct.

Example:

Before correcting action:

 version: "2.0"
 stories:

*   story: Story from Conversation ID db098d8a4d0744dc99d13a8122702bca
     steps:
*   intent: wants_consultation
*   action: utter_ask_contact_info
*   slot_was_set:
*   company: My Company AG
*   intent: inform
     entities:
*   company: My Company AG
*   action: utter_ask_name
*   intent: why
*   action: utter_explain_company
*   action: utter_ask_phone

After correcting "utter_explain_company" to -"utter_explain_name" -"utter_ask_name" -"action_listen"

the generated story changes to:

 version: "2.0"
 stories:

*   story: Story from Conversation ID 2eee1f1679fd4dc1b4109133cb56ca3c
     steps:
*   slot_was_set:
*   company: My Company AG
*   intent: wants_consultation
*   slot_was_set:
*   company: My Company AG
*   action: utter_explain_name
*   action: utter_ask_name

 _Error (including full traceback)_ :

 WARNING:rasax.community.services.event_consumers.event_consumer:Saving event failed due to an 'IntegrityError'. This means that the event is already stored in the database. The event data was '

 {"sender_id": "db098d8a4d0744dc99d13a8122702bca", "event": "action", "timestamp": 1620318095.8199723, "name": "action_listen", "policy": null, "confidence": null, "action_text": null, "hide_rule_turn": false} 

'. (sqlite3.IntegrityError) UNIQUE constraint failed: conversation_event.conversation_id, conversation_event.timestamp, conversation_event.type_name
 <span class="error">[SQL: INSERT INTO conversation_event (conversation_id, type_name, timestamp, intent_name, action_name, slot_name, slot_value, policy, is_flagged, data, evaluation, rasa_environment) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)]</span>
 [parameters: ('db098d8a4d0744dc99d13a8122702bca', 'action', 1620318095.8199723, None, 'action_listen', None, None, None, 0, '

 {"sender_id": "db098d8a4d0744dc99d13a8122702bca", "event": "action", "timestamp": 1620318095.8199723, "name": "action_listen", "policy": null, "confidence": null, "action_text": null, "hide_rule_turn": false} 

', None, 'production')]
 (Background on this error at: [http://sqlalche.me/e/13/gkpj](http://sqlalche.me/e/13/gkpj))
 WARNING:rasax.community.services.event_consumers.event_consumer:Saving event failed due to an 'IntegrityError'. This means that the event is already stored in the database. The event data was '

 {"sender_id": "db098d8a4d0744dc99d13a8122702bca", "event": "action", "timestamp": 1620318183.4182446, "name": "action_listen", "policy": "policy_1_TEDPolicy", "confidence": 0.9989607930183411, "action_text": null, "hide_rule_turn": false} 

'. (sqlite3.IntegrityError) UNIQUE constraint failed: conversation_event.conversation_id, conversation_event.timestamp, conversation_event.type_name
 <span class="error">[SQL: INSERT INTO conversation_event (conversation_id, type_name, timestamp, intent_name, action_name, slot_name, slot_value, policy, is_flagged, data, evaluation, rasa_environment) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)]</span>
 [parameters: ('db098d8a4d0744dc99d13a8122702bca', 'action', 1620318183.4182446, None, 'action_listen', None, None, 'TEDPolicy', 0, '

 {"sender_id": "db098d8a4d0744dc99d13a8122702bca", "event": "action", "timestamp": 1620318183.4182446, "name": "action_listen", "policy": "policy_1_TEDPolicy", "confidence": 0.9989607930183411, "action_text": null, "hide_rule_turn": false} 

', None, 'production')]
 (Background on this error at: [http://sqlalche.me/e/13/gkpj](http://sqlalche.me/e/13/gkpj))
 WARNING:rasax.community.services.event_consumers.event_consumer:Saving event failed due to an 'IntegrityError'. This means that the event is already stored in the database. The event data was '

 {"sender_id": "2eee1f1679fd4dc1b4109133cb56ca3c", "event": "action", "timestamp": 1620318236.194421, "name": "action_listen", "policy": null, "confidence": null, "action_text": null, "hide_rule_turn": false} 

'. (sqlite3.IntegrityError) UNIQUE constraint failed: conversation_event.conversation_id, conversation_event.timestamp, conversation_event.type_name
 <span class="error">[SQL: INSERT INTO conversation_event (conversation_id, type_name, timestamp, intent_name, action_name, slot_name, slot_value, policy, is_flagged, data, evaluation, rasa_environment) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)]</span>
 [parameters: ('2eee1f1679fd4dc1b4109133cb56ca3c', 'action', 1620318236.194421, None, 'action_listen', None, None, None, 0, '

 {"sender_id": "2eee1f1679fd4dc1b4109133cb56ca3c", "event": "action", "timestamp": 1620318236.194421, "name": "action_listen", "policy": null, "confidence": null, "action_text": null, "hide_rule_turn": false} 

', None, 'production')]
 (Background on this error at: [http://sqlalche.me/e/13/gkpj](http://sqlalche.me/e/13/gkpj))
 WARNING:rasax.community.services.event_consumers.event_consumer:Saving event failed due to an 'IntegrityError'. This means that the event is already stored in the database. The event data was '{"sender_id": "2eee1f1679fd4dc1b4109133cb56ca3c", "event": "action", "timestamp": 1620318236.194421, "metadata": 

 {"rasa_x_flagged": false, "rasa_x_id": 5} 

, "name": "utter_ask_contact_info", "policy": "policy_1_TEDPolicy", "confidence": 0.9911773800849911, "action_text": null, "hide_rule_turn": false}'. (sqlite3.IntegrityError) UNIQUE constraint failed: conversation_event.conversation_id, conversation_event.timestamp, conversation_event.type_name
 <span class="error">[SQL: INSERT INTO conversation_event (conversation_id, type_name, timestamp, intent_name, action_name, slot_name, slot_value, policy, is_flagged, data, evaluation, rasa_environment) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)]</span>
 [parameters: ('2eee1f1679fd4dc1b4109133cb56ca3c', 'action', 1620318236.194421, None, 'utter_ask_contact_info', None, None, 'TEDPolicy', 0, '{"sender_id": "2eee1f1679fd4dc1b4109133cb56ca3c", "event": "action", "timestamp": 1620318236.194421, "metadata": 

 {"rasa_x_flagged": false, "rasa_x_id ... (3 characters truncated) ... 5} 

, "name": "utter_ask_contact_info", "policy": "policy_1_TEDPolicy", "confidence": 0.9911773800849911, "action_text": null, "hide_rule_turn": false}', None, 'production')]
 (Background on this error at: [http://sqlalche.me/e/13/gkpj](http://sqlalche.me/e/13/gkpj))
 WARNING:rasax.community.services.event_consumers.event_consumer:Saving event failed due to an 'IntegrityError'. This means that the event is already stored in the database. The event data was '{"sender_id": "2eee1f1679fd4dc1b4109133cb56ca3c", "event": "action", "timestamp": 1620318236.194421, "metadata": 

 {"rasa_x_flagged": false, "rasa_x_id": 7} 

, "name": "action_listen", "policy": "policy_1_TEDPolicy", "confidence": 0.9999288320541381, "action_text": null, "hide_rule_turn": false}'. (sqlite3.IntegrityError) UNIQUE constraint failed: conversation_event.conversation_id, conversation_event.timestamp, conversation_event.type_name
 <span class="error">[SQL: INSERT INTO conversation_event (conversation_id, type_name, timestamp, intent_name, action_name, slot_name, slot_value, policy, is_flagged, data, evaluation, rasa_environment) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)]</span>
 [parameters: ('2eee1f1679fd4dc1b4109133cb56ca3c', 'action', 1620318236.194421, None, 'action_listen', None, None, 'TEDPolicy', 0, '{"sender_id": "2eee1f1679fd4dc1b4109133cb56ca3c", "event": "action", "timestamp": 1620318236.194421, "metadata": 

 {"rasa_x_flagged": false, "rasa_x_id": 7} 

, "name": "action_listen", "policy": "policy_1_TEDPolicy", "confidence": 0.9999288320541381, "action_text": null, "hide_rule_turn": false}', None, 'production')]
 (Background on this error at: [http://sqlalche.me/e/13/gkpj](http://sqlalche.me/e/13/gkpj))
 WARNING:rasax.community.services.event_consumers.event_consumer:Saving event failed due to an 'IntegrityError'. This means that the event is already stored in the database. The event data was '{"sender_id": "2eee1f1679fd4dc1b4109133cb56ca3c", "event": "user", "timestamp": 1620318236.194421, "metadata": 

 {"rasa_x_flagged": false, "rasa_x_id": 8} 

, "text": "My Company AG", "parse_data": {"intent": 

 {"id": -5842810685277495392, "name": "inform", "confidence": 0.999996423721313} 

, "entities": [

 {"entity": "company", "start": 0, "end": 13, "confidence_entity": 0.997032880783081, "value": "My Company AG", "extractor": "DIETClassifier"} 

], "text": "My Company AG", "message_id": "30c117868a7b4b95b8cad211645737c2", "metadata": {}, "intent_ranking": [

 {"id": -5842810685277495392, "name": "inform", "confidence": 0.999996423721313} 

, 

 {"id": -2131487487650428980, "name": "correct", "confidence": 1.5381261846414407e-06} 

, 

 {"id": 9066109354076387037, "name": "why", "confidence": 7.616353627781791e-07} 

, 

 {"id": -3339746004478828891, "name": "thank_you", "confidence": 7.482214527954056e-07} 

, 

 {"id": 1738506447962185965, "name": "are_we_done", "confidence": 4.346431126123207e-07} 

, 

 {"id": 898522335346646757, "name": "faq", "confidence": 6.053959822338584e-08} 

, 

 {"id": 6756371094859008286, "name": "wants_consultation", "confidence": 3.175036766833727e-08} 

]}, "input_channel": "rasa", "message_id": "30c117868a7b4b95b8cad211645737c2"}'. (sqlite3.IntegrityError) UNIQUE constraint failed: conversation_event.conversation_id, conversation_event.timestamp, conversation_event.type_name
 <span class="error">[SQL: INSERT INTO conversation_event (conversation_id, type_name, timestamp, intent_name, action_name, slot_name, slot_value, policy, is_flagged, data, evaluation, rasa_environment) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)]</span>
 [parameters: ('2eee1f1679fd4dc1b4109133cb56ca3c', 'user', 1620318236.194421, 'inform', None, None, None, None, 0, '{"sender_id": "2eee1f1679fd4dc1b4109133cb56ca3c", "event": "user", "timestamp": 1620318236.194421, "metadata": 

 {"rasa_x_flagged": false, "rasa_x_id": ... (932 characters truncated) ... 286, "name": "wants_consultation", "confidence": 3.175036766833727e-08} 

]}, "input_channel": "rasa", "message_id": "30c117868a7b4b95b8cad211645737c2"}', None, 'production')]
 (Background on this error at: [http://sqlalche.me/e/13/gkpj](http://sqlalche.me/e/13/gkpj))
 WARNING:rasax.community.services.event_consumers.event_consumer:Saving event failed due to an 'IntegrityError'. This means that the event is already stored in the database. The event data was '{"sender_id": "2eee1f1679fd4dc1b4109133cb56ca3c", "event": "action", "timestamp": 1620318236.194421, "metadata": 

 {"rasa_x_flagged": false, "rasa_x_id": 11} 

, "name": "utter_ask_name", "policy": "policy_1_TEDPolicy", "confidence": 0.9952055215835571, "action_text": null, "hide_rule_turn": false}'. (sqlite3.IntegrityError) UNIQUE constraint failed: conversation_event.conversation_id, conversation_event.timestamp, conversation_event.type_name
 <span class="error">[SQL: INSERT INTO conversation_event (conversation_id, type_name, timestamp, intent_name, action_name, slot_name, slot_value, policy, is_flagged, data, evaluation, rasa_environment) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)]</span>
 [parameters: ('2eee1f1679fd4dc1b4109133cb56ca3c', 'action', 1620318236.194421, None, 'utter_ask_name', None, None, 'TEDPolicy', 0, '{"sender_id": "2eee1f1679fd4dc1b4109133cb56ca3c", "event": "action", "timestamp": 1620318236.194421, "metadata": 

 {"rasa_x_flagged": false, "rasa_x_id": 11} 

, "name": "utter_ask_name", "policy": "policy_1_TEDPolicy", "confidence": 0.9952055215835571, "action_text": null, "hide_rule_turn": false}', None, 'production')]
 (Background on this error at: [http://sqlalche.me/e/13/gkpj](http://sqlalche.me/e/13/gkpj))
 WARNING:rasax.community.services.event_consumers.event_consumer:Saving event failed due to an 'IntegrityError'. This means that the event is already stored in the database. The event data was '{"sender_id": "2eee1f1679fd4dc1b4109133cb56ca3c", "event": "bot", "timestamp": 1620318236.194421, "metadata": 

 {"utter_action": "utter_ask_name", "rasa_x_flagged": false, "rasa_x_id": 12} 

, "text": "Was ist der Name des Ansprechpartners?", "data": {"elements": null, "quick_replies": null, "buttons": null, "attachment": null, "image": null, "custom": null}}'. (sqlite3.IntegrityError) UNIQUE constraint failed: conversation_event.conversation_id, conversation_event.timestamp, conversation_event.type_name
 <span class="error">[SQL: INSERT INTO conversation_event (conversation_id, type_name, timestamp, intent_name, action_name, slot_name, slot_value, policy, is_flagged, data, evaluation, rasa_environment) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)]</span>
 <span class="error">[parameters: ('2eee1f1679fd4dc1b4109133cb56ca3c', 'bot', 1620318236.194421, None, None, None, None, None, 0, '{"sender_id": "2eee1f1679fd4dc1b4109133cb56ca3c", "event": "bot", "timestamp": 1620318236.194421, "metadata": {"utter_action": "utter_ask_name", "ras ... (58 characters truncated) ... r Name des Ansprechpartners?", "data": {"elements": null, "quick_replies": null, "buttons": null, "attachment": null, "image": null, "custom": null}}', None, 'production')]</span>
 (Background on this error at: [http://sqlalche.me/e/13/gkpj](http://sqlalche.me/e/13/gkpj))
 WARNING:rasax.community.services.event_consumers.event_consumer:Saving event failed due to an 'IntegrityError'. This means that the event is already stored in the database. The event data was '{"sender_id": "2eee1f1679fd4dc1b4109133cb56ca3c", "event": "user_featurization", "timestamp": 1620318236.194421, "metadata": 

 {"rasa_x_flagged": false, "rasa_x_id": 10} 

, "use_text_for_featurization": false}'. (sqlite3.IntegrityError) UNIQUE constraint failed: conversation_event.conversation_id, conversation_event.timestamp, conversation_event.type_name
 <span class="error">[SQL: INSERT INTO conversation_event (conversation_id, type_name, timestamp, intent_name, action_name, slot_name, slot_value, policy, is_flagged, data, evaluation, rasa_environment) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)]</span>
 [parameters: ('2eee1f1679fd4dc1b4109133cb56ca3c', 'user_featurization', 1620318236.194421, None, None, None, None, None, 0, '{"sender_id": "2eee1f1679fd4dc1b4109133cb56ca3c", "event": "user_featurization", "timestamp": 1620318236.194421, "metadata": 

 {"rasa_x_flagged": false, "rasa_x_id": 10} 

, "use_text_for_featurization": false}', None, 'production')]
 (Background on this error at: [http://sqlalche.me/e/13/gkpj](http://sqlalche.me/e/13/gkpj))
 WARNING:rasax.community.services.event_consumers.event_consumer:Saving event failed due to an 'IntegrityError'. This means that the event is already stored in the database. The event data was '{"sender_id": "2eee1f1679fd4dc1b4109133cb56ca3c", "event": "action", "timestamp": 1620318236.194421, "metadata": 

 {"rasa_x_flagged": false, "rasa_x_id": 13} 

, "name": "action_listen", "policy": "policy_1_TEDPolicy", "confidence": 0.9998888969421381, "action_text": null, "hide_rule_turn": false}'. (sqlite3.IntegrityError) UNIQUE constraint failed: conversation_event.conversation_id, conversation_event.timestamp, conversation_event.type_name
 <span class="error">[SQL: INSERT INTO conversation_event (conversation_id, type_name, timestamp, intent_name, action_name, slot_name, slot_value, policy, is_flagged, data, evaluation, rasa_environment) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)]</span>
 [parameters: ('2eee1f1679fd4dc1b4109133cb56ca3c', 'action', 1620318236.194421, None, 'action_listen', None, None, 'TEDPolicy', 0, '{"sender_id": "2eee1f1679fd4dc1b4109133cb56ca3c", "event": "action", "timestamp": 1620318236.194421, "metadata": 

 {"rasa_x_flagged": false, "rasa_x_id": 13} 

, "name": "action_listen", "policy": "policy_1_TEDPolicy", "confidence": 0.9998888969421381, "action_text": null, "hide_rule_turn": false}', None, 'production')]
 (Background on this error at: [http://sqlalche.me/e/13/gkpj](http://sqlalche.me/e/13/gkpj))
 WARNING:rasax.community.services.event_consumers.event_consumer:Saving event failed due to an 'IntegrityError'. This means that the event is already stored in the database. The event data was '{"sender_id": "2eee1f1679fd4dc1b4109133cb56ca3c", "event": "user", "timestamp": 1620318236.194421, "metadata": 

 {"rasa_x_flagged": false, "rasa_x_id": 14} 

, "text": "warum?", "parse_data": {"intent": 

 {"id": 9066109354076387037, "name": "why", "confidence": 0.9998337030410761} 

, "entities": [], "text": "warum?", "message_id": "c2848cee174f452490f28256643022f9", "metadata": {}, "intent_ranking": [

 {"id": 9066109354076387037, "name": "why", "confidence": 0.9998337030410761} 

, 

 {"id": 1738506447962185965, "name": "are_we_done", "confidence": 0.000146308899275} 

, 

 {"id": -3339746004478828891, "name": "thank_you", "confidence": 7.202406777651049e-06} 

, 

 {"id": 898522335346646757, "name": "faq", "confidence": 5.361795047065243e-06} 

, 

 {"id": -2131487487650428980, "name": "correct", "confidence": 2.570336619100999e-06} 

, 

 {"id": 6756371094859008286, "name": "wants_consultation", "confidence": 2.462720203766366e-06} 

, 

 {"id": -5842810685277495392, "name": "inform", "confidence": 2.375314352320856e-06} 

]}, "input_channel": "rasa", "message_id": "c2848cee174f452490f28256643022f9"}'. (sqlite3.IntegrityError) UNIQUE constraint failed: conversation_event.conversation_id, conversation_event.timestamp, conversation_event.type_name
 <span class="error">[SQL: INSERT INTO conversation_event (conversation_id, type_name, timestamp, intent_name, action_name, slot_name, slot_value, policy, is_flagged, data, evaluation, rasa_environment) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)]</span>
 [parameters: ('2eee1f1679fd4dc1b4109133cb56ca3c', 'user', 1620318236.194421, 'why', None, None, None, None, 0, '{"sender_id": "2eee1f1679fd4dc1b4109133cb56ca3c", "event": "user", "timestamp": 1620318236.194421, "metadata": 

 {"rasa_x_flagged": false, "rasa_x_id": ... (771 characters truncated) ... 810685277495392, "name": "inform", "confidence": 2.375314352320856e-06} 

]}, "input_channel": "rasa", "message_id": "c2848cee174f452490f28256643022f9"}', None, 'production')]
 (Background on this error at: [http://sqlalche.me/e/13/gkpj](http://sqlalche.me/e/13/gkpj))

 _Command or request that led to error_ :

 _Content of configuration file (config.yml)_ (if relevant):

 _Content of domain file (domain.yml)_ (if relevant):

**Comment by sara-tagger** [comment]
Thanks for the issue, @desmarchris will get back to you about it soon!

###### You may find help in the [docs](https://rasa.com/docs/) and the [forum,](https://forum.rasa.com/) too 🤗

**Comment by dav-92** [comment]
Just tired it on an ubuntu machine using the quick-install script.
The problem is the same, this makes rasa x interactive learning for generating new stories pretty much unusable at the moment :(

**Comment by desmarchris** [comment]
hey @dav-92 I'm not able to replicate this... can you send a zip of your bot? perhaps it's something with the training data that's causing the error. Also, can you comment on what the expected story you were trying to get to after correcting that action? Is it this?

```
version: "2.0"
stories:
- story: Story from Conversation ID db098d8a4d0744dc99d13a8122702bca
  steps:
  - intent: wants_consultation
  - action: utter_ask_contact_info
  - slot_was_set:
    - company: My Company AG
  - intent: inform
    entities:
    - company: My Company AG
  - action: utter_ask_name
  - intent: why
  - action: utter_explain_name
  - action: utter_ask_name
```

**Comment by dav-92** [comment]
Yes, this would be the desired story.
I just tried it again, same problem after correcting an action.
This time, even before correcting, the generated stories would sometimes be in the wrong order (but nothing missing).
And there are lots of integrity errors in the log.

[chatbot.zip](https://github.com/RasaHQ/rasa/files/6443067/chatbot.zip)
