### ISSUE TITLE
Add integration tests for SDK

### ISSUE THREAD

**Issue by wochinge** [RasaHQ/rasa#8634]
**Description of Problem**:
We are currently not able to catch incompatibilities with the SDK early on as there are no integration tests. The only way to catch problems is manual testing. This would have prevented issues like this https://github.com/RasaHQ/rasa/pull/8239/files

**Overview of the Solution**:
Add integration tests which cover at least
* running a custom action
* running a form

**Definition of Done**:
- [ ] We have integration tests for the SDK which run as part of the CI

**Comment by wochinge** [comment]
@erohmensing I think this would be extremely helpful .

**Comment by mprazz** [comment]
[Moved to JIRA](https://rasahq.atlassian.net/browse/QA-25)
