### ISSUE TITLE
Reconsider training data `version` usage

### ISSUE THREAD

**Issue by wochinge** [RasaHQ/rasa#8635]
**Description of Problem**:

*   The misalignment between Rasa Open Source version and `version` key in the training data is currently confusing to users ([example](https://github.com/RasaHQ/rasa/issues/7327)). Users expect that `version` in the training data equals the used Rasa Open Source version.
*   Do we actually need the version key or can we use the Rasa Open Source version to for changes to the training data
*   If we keep the `version` thing in the training data: In which cases do we increment the latest training data version? This should be made explict and documented.

**Definition of Done**:

*   [ ] Start and conclude a discussion with all stakeholders on this (Enable, Rasa X teams)

**Comment by carlad** [comment]
This misalignment has been addressed in **3.0** with these merged PRs
- https://github.com/RasaHQ/rasa/pull/10186
- https://github.com/RasaHQ/rasa/pull/10352
- https://github.com/RasaHQ/rasa/pull/10356
and this PR which is yet to be merged:
- https://github.com/RasaHQ/rasa/pull/10343
