### ISSUE TITLE
Why Rasa installation have so much versions for dependencies

### ISSUE THREAD

**Issue by sudhir512kj** [RasaHQ/rasa#8640]
It is too much frustrating whenever i am running any RASA Project it always give at least 1 or 2 version errors.

**Comment by sara-tagger** [comment]
Thanks for the issue, @joejuzl will get back to you about it soon!

###### You may find help in the [docs](https://rasa.com/docs/) and the [forum,](https://forum.rasa.com/) too 🤗

**Comment by sudhir512kj** [comment]
@joejuzl  Whenever I try to start a rasa project, I found so many dependencies version issues, for example there is a dependency which needs different versions for 2 or more other dependencies which are dependent on the first one. It is not good. Please provide any suitable solution. I am using Anaconda for python libraries with Python 3.8. Or You can provide any latest Rasa based template which have all the dependencies listed with correct version.

**Comment by joejuzl** [comment]
Hi @sudhir512kj are you installing rasa into a fresh (i.e. no packages installed) environment? If so can you please post the error messages you are seeing?

**Comment by TyDunn** [comment]
Please reopen if this still an issue. Questions like this are best asked on the Rasa Forum in the future
