### ISSUE TITLE
Introduce LINE Connector

### ISSUE THREAD

**Issue by ridwanhady** [RasaHQ/rasa#8643]
**Description of Problem**:

[LINE](https://line.me/en/) is a Japan-based, cross-platform mobile messenger app that being popular in their own country, korea, and SEA country like Indonesia. According to [Statista](https://www.statista.com/topics/1999/line/#dossierSummary) by 2020, LINE have about 84 Million Users. Line also offers their own chatbot sdk for developer to develop their chatbot ideas. I think its good to make LINE as one of the connector provided by Rasa.

**Overview of the Solution**:

Introduce new connectors for LINE, under the `core.channel`

**Definition of Done**:

*   [ ] Feature Tested
*   [ ] Feature described the docs
*   [ ] Feature mentioned in the changelog

**Comment by sara-tagger** [comment]
Thanks for submitting this feature request 🚀 @tttthomasssss will get back to you about it soon! ✨

**Comment by tttthomasssss** [comment]
Hey @rid1hady 👋  - thanks very much for raising this issue!

I am not familiar with LINE, but its certainly good to know that there is interest in the community about having this in our connectors!

We'll report back when there are updates!

**Comment by jakkritz** [comment]
I’m currently developing this connector. Now I’m having issue where the api call takes longer (about 3 seconds) the dispatcher won’t utter message. Anyone could point me to the right direction would be appreciated.

**Comment by rid1hady** [comment]
@jakkritz Glad to hear that, actually I also developing the connector, but as of right now its only limited to handling text and flex message type, since thats my current requirement...

Also can I see your code, maybe we can work on this together.

**Comment by jakkritz** [comment]
> @jakkritz Glad to hear that, actually I also developing the connector, but as of right now its only limited to handling text and flex message type, since thats my current requirement...
> 
> Also can I see your code, maybe we can work on this together.

Great to hear. Let me clean things up and I’ll add you to my repo. Thanks

**Comment by jakkritz** [comment]
> > @jakkritz Glad to hear that, actually I also developing the connector, but as of right now its only limited to handling text and flex message type, since thats my current requirement...
> > Also can I see your code, maybe we can work on this together.
> 
> Great to hear. Let me clean things up and I’ll add you to my repo. Thanks

@rid1hady I've added you to the repo already. Anyone wants to join, please leave your username here. Thanks

**Comment by rid1hady** [comment]
@jakkritz Thanks, I'll check maybe next week, I have a packed schedule for this week

**Comment by hanifabd** [comment]
@jakkritz could i join to your repo? i got problem in custom action. my connectors didn't want receive message from custom action. thank you. here is my id `hanifabd`

**Comment by halloju** [comment]
@jakkritz I'm currently developing this connector. Can I join your repo？
my id: `halloju`

**Comment by DatboiiPuntai** [comment]
@jakkritz A Line connector is just what I need for a project of mine. Can I see your repo?

**Comment by jakkritz** [comment]
> DatboiiPuntai

It's been awhile since I worked on it. I just added you to the repo.

**Comment by jakkritz** [comment]
> halloju

sorry, just saw this. Let me add you to the repo.

**Comment by wonhyeongseo** [comment]
Is this connector development ongoing? If so @jakkritz may you please add me?

**Comment by wonhyeongseo** [comment]
Is this connector development ongoing? If so @jakkritz may you please add me?

**Comment by jakkritz** [comment]
> Is this connector development ongoing? If so @jakkritz may you please add me?

Unfortunately no, but I added you already.

**Comment by devilhyt** [comment]
@jakkritz I'm currently developing this connector. Can I see your repo?

**Comment by jakkritz** [comment]
> @jakkritz I'm currently developing this connector. Can I see your repo?

added

**Comment by socool** [comment]
@jakkritz Can i see your repo may be i can help?

**Comment by jakkritz** [comment]
> @jakkritz Can i see your repo may be i can help?

added, thanks
