### ISSUE TITLE
RASA- ImportError: cannot import name 'json' from 'engineio'

### ISSUE THREAD

**Issue by Jinay09** [RasaHQ/rasa#8647]
**Rasa 2.3**:

Python 3.8 Operating system linux: Issue: ImportError: cannot import name 'json' from 'engineio'

**Comment by zfallahnejad** [comment]
python 3.8.5
pip install rasa==2.4.3

I have the same issue.

**Comment by tttthomasssss** [comment]
Hey @Jinay09 and @zfallahnejad 👋  - thanks for submitting +1-ing this issue. 

Could you please add a full trace of the error?

**Comment by zfallahnejad** [comment]
Hey @tttthomasssss 
These are my steps:
1. create a virtual enviroment:
```
python3 -m venv env
source env/bin/activate
```
2. install rasa
```
pip install rasa==2.4.3    
```
3. The following line will produce this error.
```
from rasa.shared.core.training_data.story_reader.yaml_story_reader import YAMLStoryReader
```
