### ISSUE TITLE
CallbackInput 

### ISSUE THREAD

**Issue by mightym** [RasaHQ/rasa#8651]
**Rasa version**: 2.6.0

**Python version**: 3.7

**Operating system**: Docker

**Issue**:

Hey everyone, sadly my question in the rasa forum got marked as spam (was my second question overall)
So I'm trying it here:

I have a docker container running rasa 2.6.0-full and which is available via its REST API via `http://rasa:5005/webhooks/rest/webhook` .
When I do a POST request on that endpoint I get a response of my bot like expected. 
In my `credentials.yml` I have defined the callback url for my bot:
```
callback:
  url: "http://django:8000/core/bot-callback/"
```
I can reach that endpoint from my rasa container. But every time I do a POST request on `http://rasa:5005/webhooks/rest/webhook` I'm not getting any request on the defined CallbackInput .
I also tried this example https://github.com/RasaHQ/rasa/tree/main/examples/reminderbot and having the same issue. 
Is there anything I'm missing? Like do you need an action server running to get the callback/is the callback only called via custom actions? In my demo project I'm currently don't having any actions. Just bare questions and replies (which work fine via the POST api endpoint, but I'd like to have an async callback :-/)

**Comment by Dustyposa** [comment]
you should post this address:
```bash
curl -XPOST http://localhost:5005/webhooks/callback/webhook \
   -d '{"sender": "tester", "message": "hello"}' \
   -H "Content-type: application/json"
```
Detail in [here](https://github.com/RasaHQ/rasa/blob/main/examples/reminderbot/README.md)

**Comment by sara-tagger** [comment]
Thanks for the issue, @b-quachtran will get back to you about it soon!

###### You may find help in the [docs](https://rasa.com/docs/) and the [forum,](https://forum.rasa.com/) too 🤗

**Comment by mightym** [comment]
@Dustyposa ooooh thats the subtle difference there. Sorry now that I know that the docs seem to be more obvious https://rasa.com/docs/rasa/connectors/your-own-website/#callbackinput
Thanks a lot for your help, this was confusing me :)
