### ISSUE TITLE
Flakey CI test: Windows Install Dependencies

### ISSUE THREAD

**Issue by ancalita** [RasaHQ/rasa#8656]
**Error Information**:
Install Dependencies step fails because of:
```
Failures
 - wget - wget not installed. The package was not found with the source(s) listed.
 Source(s): 'https://chocolatey.org/api/v2/'
```
or 
```
Failures
 - wget (exited 1) - wget not installed. An error occurred during installation:
 The remote server returned an error: (503) Server Unavailable. Service Unavailable
```
**Job Run URL examples**:
https://github.com/RasaHQ/rasa/runs/2398486330
https://github.com/RasaHQ/rasa/runs/2398489491
https://github.com/RasaHQ/rasa/runs/2398501858
https://github.com/RasaHQ/rasa/runs/2398501696
https://github.com/RasaHQ/rasa/runs/2398501910
https://github.com/RasaHQ/rasa/runs/2398501877
https://github.com/RasaHQ/rasa/runs/2398503568
https://github.com/RasaHQ/rasa/runs/2398503531
https://github.com/RasaHQ/rasa/runs/2398503597

**Definition of Done**:
- [ ] apply fix so that tests run deterministic

**Comment by tczekajlo** [comment]
It looks like an issue with external service.

```
wget not installed. An error occurred during installation:
 The remote server returned an error: (503) Server Unavailable. Service Unavailable
```

**Comment by HotThoughts** [comment]
Duplicates? https://github.com/RasaHQ/rasa/issues/8398

**Comment by tczekajlo** [comment]
Yes, looks like the same issue. @HotThoughts I think we can close one of them.
