### ISSUE TITLE
Flakey CI test: UnicodeEncodeError

### ISSUE THREAD

**Issue by ancalita** [RasaHQ/rasa#8659]
**Error Information**:

UnicodeEncodeError: 'charmap' codec can't encode characters in position 75-84: character maps to 

**Job run URL examples**: [https://github.com/RasaHQ/rasa/runs/2435785078](https://github.com/RasaHQ/rasa/runs/2435785078) [https://github.com/RasaHQ/rasa/runs/2455684160](https://github.com/RasaHQ/rasa/runs/2455684160)

**Definition of Done**:

*   [ ] the error appears to be triggered in [`pytest_timeout.py`](https://github.com/pytest-dev/pytest-timeout/blob/1a35f94298c1260500907bd674b75cf59df0c949/pytest_timeout.py#L417) when [writing](https://github.com/pytest-dev/pytest-timeout/blob/1a35f94298c1260500907bd674b75cf59df0c949/pytest_timeout.py#L460) `stderr`to stream. My initial thoughts are that the actual problem here is the timeout, while the `UnicodeEncodeError` is something that should be fixed in the `pytest-timeout` dependency.
*   [ ] investigate further and create issue for fix

**Comment by tayfun** [comment]
I haven't seen this error happen much lately, but I don't have reliable data and github doesn't make it easy to search test failure logs.

<img width="615" alt="Screenshot 2021-12-24 at 14 08 28" src="https://user-images.githubusercontent.com/55836/147358108-b4cb8373-7bbe-4f91-aff8-d38c610536a6.png">
