### ISSUE TITLE
Flakey CI test: psutil.NoSuchProcess

### ISSUE THREAD

**Issue by ancalita** [RasaHQ/rasa#8664]
**Error Information**:
```
E           psutil.NoSuchProcess: psutil.NoSuchProcess process no longer exists (pid=1404)
```

**Job run URL examples**:
https://github.com/RasaHQ/rasa/runs/2553372534

**Definition of Done**:
- [ ] apply fix so that tests run deterministic

**Comment by wochinge** [comment]
hopefully fixed by https://github.com/RasaHQ/rasa/pull/8495
