### ISSUE TITLE
Training core using --pecentages only produces one model when only one config is specified

### ISSUE THREAD

**Issue by dav-92** [RasaHQ/rasa#8673]
**Description of Problem**:

Training a policy using varying amounts of data is not only helpful when comparing different policy configurations as described [here](https://rasa.com/docs/rasa/testing-your-assistant#comparing-policy-configurations) but also when using just one configuration. Using this command without specifiying multiple configurations only produces one model so it seems that in this case the --percentages argument is ignored.

**Overview of the Solution**:

Using the --percentages argument should result in multiple models being trained no matter if only one config is specified. Possible solution mentioned here: [https://forum.rasa.com/t/evaluation-of-dialog-policy/43425/4](https://forum.rasa.com/t/evaluation-of-dialog-policy/43425/4)

**Comment by sara-tagger** [comment]
Thanks for submitting this feature request 🚀 @TyDunn will get back to you about it soon! ✨
