### ISSUE TITLE
Can rasa support multiple GPU distribution training?

### ISSUE THREAD

**Issue by gmftbyGMFTBY** [RasaHQ/rasa#8686]
**Description of Problem**:

In order to obtain the good performance of the rasa nlu model, we use the chatito to augment training data for the rasa.
However, we notice that it still cost us about 8 hours on single GPU to train it.
So I wonder that it is possible to use the multiple GPU distribution training in rasa.
If it is, how to do it.
If not, can you give me some other ways to speed up the training procedure?

**Overview of the Solution**:

**Examples** (if relevant):

**Blockers** (if relevant):

**Definition of Done**:

**Comment by m-vdb** [comment]
Hi @gmftbyGMFTBY and thank you for your question! There are a couple of things to unpack here:
- we haven't tried multi GPU training for any of our components as it's usually never required
- using a lot of synthetic data from tools like Chatito is usually a sign that a lot of rule based variations of NLU messages were created, causing the training time to explode

I'll link [the response from our product manager on the forum](https://forum.rasa.com/t/how-to-use-chatito/24675/3?u=m-vdb) for more information on why we think using Chatito is not the best option.

I'll close this ticket as it should be more of a discussion, and the forum is better suited for that. If I haven't answered your question yet, could you ask again [on the forum](https://forum.rasa.com/)? I am sure other users have had a similar question 😄

**Comment by lsyin** [comment]
when diet model can support multi gpus?

**Comment by adamwojt** [comment]
Could this be at least documented, that there is no way to distribute across multiple GPUs for DietClassiffier ? Looks like there is lot of issues opened and then closed on both GitHub and Rasa forum without any conclusive answer.
