### ISSUE TITLE
Spike for test stories

### ISSUE THREAD

**Issue by TyDunn** [RasaHQ/rasa#8691]
**Definition of done**

Over the course of a one week sprint, complete as much of the following:
- [x] Investigate all context provided in product backlog item
- [x] Determine how we might allow test stories to execute actions
- [x] Determine how we might mock context, so that an action server is not required
- [x] Determine how we might address the bug and smaller enhancement issues
- [x] Work with product management to create a scope for what we should tackle

More details in the [product backlog item](https://www.notion.so/rasa/Spike-for-test-stories-02eb4e666aa442349415b2cf7a15a956)

**Comment by alwx** [comment]
Here is a document with discussion and investigation: https://www.notion.so/rasa/Test-stories-investigation-65530e05e03c4a59ac1cac4e5455d2dd
