### ISSUE TITLE
Telemetry usage on Segment is growing linearly: is it a bug or is it normal?

### ISSUE THREAD

**Issue by m-vdb** [RasaHQ/rasa#8694]
2 possible explanations:

- a bug: we’re not able to keep tracking ids properly, or not in the majority of cases. Another way to see it would be to look at how many of these events are sent via CI, that could explain the steady growth as well.
- nothing: it’s normal growth and people try out rasa. They are still counted as users even if they do only 1 event.

**Definition of Done:**
- [x] Find out if it's a bug or if it's expected
- [ ] Cause determined and explained

**Comment by wochinge** [comment]
related to https://github.com/RasaHQ/rasa/issues/8574

**Comment by ancalita** [comment]
Initial findings:

- The events with highest unique count are Server Started, Training Started and Training Completed.
- Month-on-month view showed steady count for all 3 events in April and May.
- In June, the count for Server Started doubled (from 56k events to 121k events) - while for the other 2 events, the count remained steady. The full view is [here](https://metabase.rasa.com/question#eyJkYXRhc2V0X3F1ZXJ5Ijp7InR5cGUiOiJxdWVyeSIsInF1ZXJ5Ijp7InNvdXJjZS10YWJsZSI6MTkzMSwiYWdncmVnYXRpb24iOltbImRpc3RpbmN0IixbImZpZWxkLWlkIiwxNTU0MF1dXSwiYnJlYWtvdXQiOltbImRhdGV0aW1lLWZpZWxkIixbImZpZWxkLWlkIiwxNTU0Nl0sIm1vbnRoIl0sWyJmaWVsZC1pZCIsMTU1MzddXSwiZmlsdGVyIjpbImFuZCIsWyI9IixbImZpZWxkLWlkIiwxNTUzN10sIlRyYWluaW5nIFN0YXJ0ZWQiLCJUcmFpbmluZyBDb21wbGV0ZWQiLCJTZXJ2ZXIgU3RhcnRlZCJdLFsiYmV0d2VlbiIsWyJmaWVsZC1pZCIsMTU1NDZdLCIyMDIxLTA0LTAxIiwiMjAyMS0wNy0wOCJdXX0sImRhdGFiYXNlIjoyfSwiZGlzcGxheSI6ImxpbmUiLCJ2aXN1YWxpemF0aW9uX3NldHRpbmdzIjp7fX0=).
- In June, out of these 121k events: 62,966 were 2.6.1 version -> out of these, 62,388 were Python 3.8.5 version -> out of these, 62,375 were Linux: view is [here](https://metabase.rasa.com/question#eyJkYXRhc2V0X3F1ZXJ5Ijp7InR5cGUiOiJxdWVyeSIsInF1ZXJ5Ijp7InNvdXJjZS10YWJsZSI6MTkzMSwiYWdncmVnYXRpb24iOltbImRpc3RpbmN0IixbImZpZWxkLWlkIiwxNTU0MF1dXSwiYnJlYWtvdXQiOltbImRhdGV0aW1lLWZpZWxkIixbImZpZWxkLWlkIiwxNTU0Nl0sIm1vbnRoIl0sWyJmaWVsZC1pZCIsMTU1MzddLFsiZmllbGQtaWQiLDE1NTQxXSxbImZpZWxkLWlkIiwxNTU1M10sWyJmaWVsZC1pZCIsMTU1NTZdXSwiZmlsdGVyIjpbImFuZCIsWyI9IixbImZpZWxkLWlkIiwxNTUzN10sIlNlcnZlciBTdGFydGVkIl0sWyJiZXR3ZWVuIixbImZpZWxkLWlkIiwxNTU0Nl0sIjIwMjEtMDYtMDEiLCIyMDIxLTA2LTMwIl1dLCJvcmRlci1ieSI6W1siZGVzYyIsWyJhZ2dyZWdhdGlvbiIsMF1dXX0sImRhdGFiYXNlIjoyfSwiZGlzcGxheSI6InRhYmxlIiwidmlzdWFsaXphdGlvbl9zZXR0aW5ncyI6e30sIm9yaWdpbmFsX2NhcmRfaWQiOm51bGx9).
- [All the Linux, Python 3.8.5, rasa 2.6.1 `Server Started` events](https://metabase.rasa.com/question#eyJkYXRhc2V0X3F1ZXJ5Ijp7InR5cGUiOiJxdWVyeSIsInF1ZXJ5Ijp7InNvdXJjZS10YWJsZSI6MTkzMSwiYWdncmVnYXRpb24iOltbImRpc3RpbmN0IixbImZpZWxkLWlkIiwxNTU0MF1dXSwiYnJlYWtvdXQiOltbImRhdGV0aW1lLWZpZWxkIixbImZpZWxkLWlkIiwxNTU0Nl0sIm1vbnRoIl0sWyJmaWVsZC1pZCIsMTU1MzddLFsiZmllbGQtaWQiLDE1NTQxXSxbImZpZWxkLWlkIiwxNTU1M10sWyJmaWVsZC1pZCIsMTU1NTZdLFsiZmllbGQtaWQiLDE1NTQzXV0sImZpbHRlciI6WyJhbmQiLFsiPSIsWyJmaWVsZC1pZCIsMTU1MzddLCJTZXJ2ZXIgU3RhcnRlZCJdLFsiYmV0d2VlbiIsWyJmaWVsZC1pZCIsMTU1NDZdLCIyMDIxLTA2LTAxIiwiMjAyMS0wNi0zMCJdLFsiPSIsWyJmaWVsZC1pZCIsMTU1NDFdLCIzLjguNSJdLFsiPSIsWyJmaWVsZC1pZCIsMTU1NTNdLCJMaW51eCJdLFsiPSIsWyJmaWVsZC1pZCIsMTU1NTZdLCIyLjYuMSJdXSwib3JkZXItYnkiOltbImRlc2MiLFsiYWdncmVnYXRpb24iLDBdXV19LCJkYXRhYmFzZSI6Mn0sImRpc3BsYXkiOiJ0YWJsZSIsInZpc3VhbGl6YXRpb25fc2V0dGluZ3MiOnt9LCJvcmlnaW5hbF9jYXJkX2lkIjpudWxsfQ==) have unique user IDs and context CI is false.
- Out of the above group, 62,351 have [Docker false](https://metabase.rasa.com/question#eyJkYXRhc2V0X3F1ZXJ5Ijp7ImRhdGFiYXNlIjoyLCJxdWVyeSI6eyJzb3VyY2UtdGFibGUiOjE5MzEsImFnZ3JlZ2F0aW9uIjpbWyJkaXN0aW5jdCIsWyJmaWVsZC1pZCIsMTU1NDBdXV0sImJyZWFrb3V0IjpbWyJkYXRldGltZS1maWVsZCIsWyJmaWVsZC1pZCIsMTU1NDZdLCJtb250aCJdLFsiZmllbGQtaWQiLDE1NTM3XSxbImZpZWxkLWlkIiwxNTU0MV0sWyJmaWVsZC1pZCIsMTU1NTNdLFsiZmllbGQtaWQiLDE1NTU2XSxbImZpZWxkLWlkIiwxNTU0M10sWyJmaWVsZC1pZCIsMTU1NDhdXSwiZmlsdGVyIjpbImFuZCIsWyI9IixbImZpZWxkLWlkIiwxNTUzN10sIlNlcnZlciBTdGFydGVkIl0sWyJiZXR3ZWVuIixbImZpZWxkLWlkIiwxNTU0Nl0sIjIwMjEtMDYtMDEiLCIyMDIxLTA2LTMwIl0sWyI9IixbImZpZWxkLWlkIiwxNTU0MV0sIjMuOC41Il0sWyI9IixbImZpZWxkLWlkIiwxNTU1M10sIkxpbnV4Il0sWyI9IixbImZpZWxkLWlkIiwxNTU1Nl0sIjIuNi4xIl1dLCJvcmRlci1ieSI6W1siZGVzYyIsWyJhZ2dyZWdhdGlvbiIsMF1dXX0sInR5cGUiOiJxdWVyeSJ9LCJkaXNwbGF5IjoidGFibGUiLCJ2aXN1YWxpemF0aW9uX3NldHRpbmdzIjp7fSwib3JpZ2luYWxfY2FyZF9pZCI6bnVsbH0=).
- Also `Project` is blank for 62,367 `Server Started` events on Linux, rasa 2.6.1, Python 3.8.5.
- All the Linux, Python 3.8.5, rasa 2.6.1 `Server Started` events also have this OS version (AWS Linux): [4.14.225-168.357.amzn2.x86_64](https://metabase.rasa.com/question#eyJkYXRhc2V0X3F1ZXJ5Ijp7ImRhdGFiYXNlIjoyLCJxdWVyeSI6eyJzb3VyY2UtdGFibGUiOjE5MzEsImFnZ3JlZ2F0aW9uIjpbWyJkaXN0aW5jdCIsWyJmaWVsZC1pZCIsMTU1NDBdXV0sImZpbHRlciI6WyJhbmQiLFsiPSIsWyJmaWVsZC1pZCIsMTU1NTNdLCJMaW51eCJdLFsiPSIsWyJmaWVsZC1pZCIsMTU1MzddLCJTZXJ2ZXIgU3RhcnRlZCJdLFsiPSIsWyJmaWVsZC1pZCIsMTU1NDFdLCIzLjguNSJdLFsiPSIsWyJmaWVsZC1pZCIsMTU1NTZdLCIyLjYuMSJdXSwiYnJlYWtvdXQiOltbImRhdGV0aW1lLWZpZWxkIixbImZpZWxkLWlkIiwxNTU0Nl0sIm1vbnRoIl0sWyJmaWVsZC1pZCIsMTU1NDVdLFsiZmllbGQtaWQiLDE1NTQzXV0sIm9yZGVyLWJ5IjpbWyJhc2MiLFsiZGF0ZXRpbWUtZmllbGQiLFsiZmllbGQtaWQiLDE1NTQ2XSwibW9udGgiXV1dfSwidHlwZSI6InF1ZXJ5In0sImRpc3BsYXkiOiJiYXIiLCJkaXNwbGF5SXNMb2NrZWQiOnRydWUsInZpc3VhbGl6YXRpb25fc2V0dGluZ3MiOnsidGFibGUucGl2b3QiOmZhbHNlLCJncmFwaC5kaW1lbnNpb25zIjpbInRpbWVzdGFtcCIsImNvbnRleHRfb3NfdmVyc2lvbiJdLCJncmFwaC5tZXRyaWNzIjpbImNvdW50Il0sInN0YWNrYWJsZS5zdGFja190eXBlIjoic3RhY2tlZCJ9LCJvcmlnaW5hbF9jYXJkX2lkIjpudWxsfQ==)

**Comment by ancalita** [comment]
Added [follow-up issue](https://github.com/RasaHQ/rasa/issues/9100) to the Enable inbox to be looked into the near future.
