### ISSUE TITLE
Running trainer with docker exits without any log or error and nothing happens

### ISSUE THREAD

**Issue by danaamiri** [RasaHQ/rasa#8699]
**Rasa version**: docker image => rasa/rasa:2.6.1-full

**Operating system** (windows, osx, ...): Ubuntu 18.04 **Issue**: I want to run rasa model trainer in my project with docker container. after running the train command with docker, it waits for 3 seconds and exits from docker process without any errors or logs. FIY in my local machine, training without docker works properly.

There are almost 5 cores of CPU and 6.5 GB of memory is available.

**Error (including full traceback)**:

**Command or request that led to error**:

docker run -v $(pwd):/app --user root rasa/rasa:2.6.1-full train --domain data

**Content of configuration file (config.yml)** (if relevant):

<pre>language: en
 pipeline:

*   name: WhitespaceTokenizer
*   name: RegexFeaturizer
*   name: LexicalSyntacticFeaturizer
*   name: CountVectorsFeaturizer
*   name: CountVectorsFeaturizer
     analyzer: char_wb
     min_ngram: 1
     max_ngram: 4
*   name: DIETClassifier
     model_confidence: linear_norm
     constrain_similarities: True
     epochs: 5
     ranking_length: 5

1\. - name: DucklingEntityExtractor
 2\. url: [http://localhost:8000](http://localhost:8000)([http://localhost:8000](http://localhost:8000))
 3\. dimensions:
 4\. - email

*   name: EntitySynonymMapper
*   name: ResponseSelector
     retrieval_intent: out_of_scope
     scale_loss: false
     epochs: 5
*   name: ResponseSelector
     retrieval_intent: faq
     scale_loss: false
     epochs: 5
*   name: ResponseSelector
     retrieval_intent: chitchat
     scale_loss: false
     epochs: 5
*   name: FallbackClassifier
     threshold: 0.7

policies:

*   name: TEDPolicy
     max_history: 10
     epochs: 5
     batch_size:
*   32
*   64
*   max_history: 6
     name: AugmentedMemoizationPolicy
*   name: RulePolicy
     core_fallback_threshold: 0.3
     core_fallback_action_name: "action_default_fallback"
     enable_fallback_prediction: True
     </pre>

**Content of domain file (domain.yml)** (if relevant):

<pre>there are multiple domain.yml files in the data folder that passes to the --domain flag</pre>

**Comment by Dustyposa** [comment]
Could you show your `data dir` structure? 
Likes 2+ `domain.yml` in data.

**Comment by sara-tagger** [comment]
Thanks for the issue, @amn41 will get back to you about it soon!

###### You may find help in the [docs](https://rasa.com/docs/) and the [forum,](https://forum.rasa.com/) too 🤗

**Comment by m-vdb** [comment]
Closing as stale
