### ISSUE TITLE
Use carousal from custom action for fb messenger and telegram

### ISSUE THREAD

**Issue by vivek22122014** [RasaHQ/rasa#8720]
**Description of Problem**: I'm trying to implement carousal for bot reply but getting json dict in response at telegram or fb messenger for rasa bot

**Overview of the Solution**: send carousel format msg from rasa

**Examples** (if relevant):

**Blockers** (if relevant):

**Definition of Done**:

**Comment by sara-tagger** [comment]
Thanks for submitting this feature request 🚀 @degiz will get back to you about it soon! ✨

**Comment by degiz** [comment]
Hey @vivek22122014 

Great that you're working on that! 👍 Do you have the implementation available somewhere already?
