### ISSUE TITLE
Rasa Open Source 3.0 action plan

### ISSUE THREAD

**Issue by TyDunn** [RasaHQ/rasa#8721]
**Definition of done**
- [x] [Rasa Open Source 3.0 possibilities](https://www.notion.so/rasa/6c938622fad448c09f58ac8212ffca29?v=f92815336b8f48ddbcf85bbcdb4c77b7) list created
- [x] Timeline for getting to a finalised action plan agreed on
- [x] Structure of the action plan document established
- [x] Issues for next steps with action plan created

*Ideas of potential action plan next steps*
- [x] Survey for `Reach 100% approval on action plan for the Rasa Open Source 3.0 release which includes items which should go in, timelines and owners` created
- [ ] Survey results gathered on first iteration by June 11th
- [ ] Survey results gathered on second iteration by June 25th
- [ ] Determine if any more spikes / prototypes / investigations are needed for other 3.0 possibilities (like `architecture revamp` prototype and `test stories` spike)
- [x] Create Notion page with timeline for development and release
- [x] Align on what 3.0 possibilities require a major release
- [x] Deprio obvious not in scope 3.0 possibilities

**Comment by m-vdb** [comment]
Survey is out, and we're in a pretty good shape in the plan. I'm closing this ticket 🎉
