### ISSUE TITLE
Investigate difference in loading time estimates for multiwoz

### ISSUE THREAD

**Issue by TyDunn** [RasaHQ/rasa#8733]
@twerkmeister mentioned it was taking a really long time to load multiwoz before training, yet I believe we thought we had [decreased the loading time to 10-20 minutes](https://github.com/RasaHQ/rasa/issues/7272#issuecomment-799561639) in March

**Defintion of done**
- [x] Figure out why there is a discrepancy
- [x] Determine which estimate is actually correct
- [ ] Decide if we should create a regression test for this
- [ ] Create issue for improving loading time if needed

**Comment by twerkmeister** [comment]
So the loading time for the data itself is indeed at <20 minutes for multiwoz - but then there's a lot more time for the preprocessing of the data until the training starts. Looks like the architecture prototype changes improve that a bit:

On main, almost 2 hours until gpu training starts and immediately crashes:
![multiwoz-main-3-spacy](https://user-images.githubusercontent.com/1107341/119221956-350f9e00-baf2-11eb-899b-1f5006ba8162.png)

with the tracker featurization from the arcitecture prototype, gpu training starts after ~1h 20m and crashes:
![multiwoz-tracker-lookup-1-spacy](https://user-images.githubusercontent.com/1107341/119221972-52dd0300-baf2-11eb-8e95-653628ae2a05.png)

I think that's still high, and I am convinced there must be some things that can be done to get this down to a reasonable time. It's not really large data we are dealing with after all...

With the loading time for the yml itself, I would probably still recommend implementing the env var change that had been in discussion before and that cuts off another good chunk of the loading time. 20 min is still too long if you want to make changes to preprocessing etc that might need a larger dataset to test things.

**Comment by TyDunn** [comment]
@twerkmeister Good to know it's more than just loading time. Feel free to edit this issue and use it for the improving preprocessing issue we discussed creating earlier, or you can just reference and close this one cc @m-vdb

**Comment by TyDunn** [comment]
@twerkmeister I added the issue for e2e large dataset featurization memory and cpu improvements to the inbox for refinement today. Did you also create an issue for improving preprocessing?
