### ISSUE TITLE
GPU memory problems

### ISSUE THREAD

**Issue by TyDunn** [RasaHQ/rasa#8734]
[GPU memory problems](https://github.com/RasaHQ/rasa/issues/8593#issuecomment-842320003)

**Definition of done**
- [x] Look into prototype solution #8357
- [x] Determine what still needs to be done, if anything
- [x] Figure out what it would take to make it production ready
- [x] Ensure that this solution still fits after the architecture revamp
- [x] Create issue(s) for making it production ready in new architecture

**Comment by twerkmeister** [comment]
The current status of this is in #8746. It is still pending review, but I think it is overall in a good state. One topic that I am aware of that might still need some thought to increase consistency of the code:  https://github.com/RasaHQ/rasa/pull/8746#issuecomment-856709688 

I have done testing with several configurations and the PR solves the problem of memory issues plus speeds up the training.
Using this PR we are able to train on 100% of multiwoz stories whereas previously we ran out of memory for ~12% of them. Also, with respect to speed, running a training on 6% of stories an epoch on main took 120s on main vs 40s on this branch with a reasonable set of hyperparameters.

This solution would not interfere with the architecture revamp as it is contained within a single policy.

**Comment by b-quachtran** [comment]
@TyDunn Do you know if these optimizations have been released in a 2.X OSS version?

**Comment by TyDunn** [comment]
@b-quachtran This was for end-to-end. We only built a prototype and no code was shipped
