### ISSUE TITLE
Conflicting condition on `required_slots`  between rasa open source and rasa X

### ISSUE THREAD

**Issue by hakrac** [RasaHQ/rasa#8736]
_Rasa version_ : 2.6.0

 _Rasa X version_ : 0.39.3

 _Python version_ : 3.9

 _Operating system_ : Ubuntu 20.04 <span class="error">[rasa running in k8s v1.20.1]</span>

I am using the helm rasa-x chart for my deployment of rasa , rasa x and the rasa action server

 _Issue_ : When switching to rasa version 2.6.0 rasa requires `required_slots` to be of type dict while rasa x won't pull from git when `required_slots` is not a list.

 _Error (including full traceback)_ : Error from rasa open source worker log when `required_slots' is a list

/opt/venv/lib/python3.8/site-packages/rasa/shared/utils/io.py:97: UserWarning: Loading domain from '/tmp/tmpqn9y77_1/data.yml' failed. Us ing empty domain. Error: 'The slots for form 'form_questionnaire' were specified as '<class 'list'>'. They need to be specified as dictio nary. Please see [https://rasa.com/docs/rasa/forms](https://rasa.com/docs/rasa/forms) for more information.'

Error from rasa x log when `required_slots` is a dictionary:

return await self._force_inject_latest_remote_changes() File "/usr/local/lib/python3.8/dist-packages/rasax/community/services/integrated_version_control/git_service.py", line 1219, in _force_ inject_latest_remote_changes await self._inject_data() File "/usr/local/lib/python3.8/dist-packages/rasax/community/services/integrated_version_control/git_service.py", line 1191, in _inject _data await rasax.community.initialise.inject_files_from_disk( File "/usr/local/lib/python3.8/dist-packages/rasax/community/initialise.py", line 352, in inject_files_from_disk inject_domain( File "/usr/local/lib/python3.8/dist-packages/rasax/community/initialise.py", line 206, in inject_domain raise InjectionError(f"Could not inject domain. Details:\n

 {e} 

") rasax.community.initialise.InjectionError: Could not inject domain. Details: The slot mappings for slot 'required_slots' in form 'form_add_micturition' have type '<class 'dict'>'. It is required to provide a list o f slot mappings. Please see [https://rasa.com/docs/rasa/forms](https://rasa.com/docs/rasa/forms) for more information.

 _The relevant form_ :

<pre> form_questionnaire:
 required_slots:
 disease:

*   entity: disease
     type: from_entity</pre>

**Comment by sara-tagger** [comment]
Thanks for raising this issue, @b-quachtran will get back to you about it soon✨

###### Please also check out the [docs](https://rasa.com/docs/) and the [forum](https://forum.rasa.com/) in case your issue was raised there too 🤗

**Comment by alexweidauer** [comment]
Thank you for raising this issue about Rasa X. We decided to stop supporting the Community Edition (free version) of ‘Rasa X’ (see more info here: https://rasa.com/blog/rasa-x-community-edition-changes/). That’s why we’ve closed your issue. We suggest that Rasa Enterprise customers raise the issue with our customer support team if they haven’t done so already.
