### ISSUE TITLE
remove adding extra buffer in regex and count vectors featurizers

### ISSUE THREAD

**Issue by jupyterjazz** [RasaHQ/rasa#8749]
this is for issue #8232

As we know, some of our sparse featurizers allocate an extra buffer for additional features that appear during incremental training. To implement #8232 we need to change this behaviour. Two featurizers that we should change are `CountVectorsFeaturizer` and `RegexFeaturizer`. 

Change the `CountVectorsFeaturizer` and `RegexFeaturizer` so that they: 

- [ ] don't allocate an extra buffer
- [ ] append new features to the existing vocabulary

**Comment by kedz** [comment]
unassigned myself since this issue has already got two PRs according to @jupyterjazz.
