### ISSUE TITLE
Get sparse feature sizes

### ISSUE THREAD

**Issue by jupyterjazz** [RasaHQ/rasa#8750]
In order to [dynamically change sparse layers](https://github.com/RasaHQ/rasa/issues/8232), we should be able to split a combined feature input into features that come from separate featurizers. The reason behind this is that new features will be appended to the corresponding splits and not to the combined representation. That's why we need to know the size of each sparse feature.

`feature_sizes` collection will have a following structure: `Dict[Text, Dict[Text, List[int]]]`
It will be a dictionary of attributes that have sparse features(e.g. `text`, `response`… we are excluding `label` at this point) to the dictionary of different kinds of features(e.g. `sequence`/`sentence`) to the list of feature sizes of different featurizers.

The collection should be created in the `DIETClassifier` class during the `_create_model_data` call and it should be assigned to the `DIETClassifier` class as an attribute.

`feature_sizes` should be persisted after training and loaded during fine-tuning. We will need to compare persisted `feature_sizes` to the current `feature_sizes` to find out if there are any `DenseForSparse` layers to be updated.

Things to be done:

- [ ] get `feature_sizes` of current data
- [ ] persist `feature_sizes`
- [ ] load persisted `feature_sizes`

**Comment by tttthomasssss** [comment]
@samsucik assigned as reviewer.
