### ISSUE TITLE
Adjusting DenseForSparse layer size

### ISSUE THREAD

**Issue by jupyterjazz** [RasaHQ/rasa#8751]
After completing #8749 and #8750, in order to [dynamically change sparse layers during fine-tuning](https://github.com/RasaHQ/rasa/issues/8232), we will need to adjust the `DenseForSparse` layer size in case there are any new sparse features. 

This functionality will be implemented in the `DIET`class. We will compare persisted `feature_sizes` to the current `feature_sizes` to find out if there are any `DenseForSparse` layers to be updated. After updating the layers, we will compile the whole model, update data signatures, create a `RasaModelData` object from a data example and activate new layers by fitting the model on the `RasaModelData` object. 

Things to be done:

- [ ] call `adjust_layers` from `DIETClassifier` during fine-tuning
- [ ] find out which `DenseForSparse` layers should be updated
- [ ] adjust each of them
- [ ] compile the model
- [ ] update data signatures
- [ ] activate new layers

**Comment by tttthomasssss** [comment]
@ka-bu assigned as reviewer.
