### ISSUE TITLE
Categorical slots mapped to __other__ internally but represented as the the original found value in interactive learning

### ISSUE THREAD

**Issue by plattenschieber** [RasaHQ/rasa#8755]
**Description of Problem**: When using a categorical slot, all values not explicitly defined will be mapped to the default value `__other__`. Even though it's mapped internally to `__other__`, `slot_was_set` is represented as the found value in interactive learning (`rasa interactive`). The same applies in the Rasa X conversations screen and Talk to your Bot screen.

**Overview of the Solution**: Not yet elaborated

**Examples** : Consider the `domain.yaml` below. I stumbled upon this issue, when I got a totally wrong answer based on `slot_was_set = wrong_risk_level`. I wondered why `slot_was_set` could be anything else, than `low`, `medium` or `high`, as it's type is set to `categorical`. @hsm207 pointed out, that the TED Policy jumped in and predicted the answer based on the default slot `__other__`.

So you would be presented with a `slot_was_set = wrong_risk_level != __other__`

<span class="error">[domain.yaml]</span> ... slots: risk_level: type: categorical values:

*   low
*   medium
*   high

**Blockers** (if relevant): Not, that I know of

**Definition of Done**:

*   [ ] Tests are added
*   [ ] Feature described the docs
*   [ ] Feature mentioned in the changelog
*   [ ] `__other__` used in `slot_was_set` representations when finding a non matching categorical slot

**Comment by sara-tagger** [comment]
Thanks for submitting this feature request 🚀 @koernerfelicia will get back to you about it soon! ✨

**Comment by koernerfelicia** [comment]
@plattenschieber thanks for submitting the issue! It looks like this has already been routed to the correct place :)

**Comment by melindaloubser1** [comment]
Started looking into this:

It is desirable to maintain the "original" value of the slot in the tracker - for example, if whenever the __other__ category was hit, you wanted to send the new value somewhere in a custom action, or refer to the raw value downstream. 

It is only the representation in the dumped story that should, ideally, change to match the featurization behind the scenes. 

Although it's most noticeable with categorical slots, it's also relevant for other slot types that influence the conversation, for example text slots where the exact value is irrelevant to featurization; only the existence of some value matters.

**Comment by melindaloubser1** [comment]
@wochinge wdyt of this?
I can imagine changing this behavior only for interactive learning somewhere [here](https://github.com/RasaHQ/rasa/blob/fe7cbf3f271abe1e97c0145f7e7c13f83becd28d/rasa/core/training/interactive.py#L794-L844) but it seems like a bigger question about how to represent the value of featurized slots.

**Comment by wochinge** [comment]
Mhm, not sure if it makes sense to change how it's written to disk. E.g. for end-to-end conversation tests it could be interesting to work with categorical slots which were set to sth else.

What about printing a warning when dumping stories which contain categorical slot values which fall into `__other__`? Or we could add a YAML comment about the featurization to each slot, for example:

```yaml
- story: my story
  steps:
  - slot_was_set:
    - name: "XY"  # featurized as __other__
```

**Comment by melindaloubser1** [comment]
I think adding the comment would be clearest, since it's something you should notice when reading through story files

**Comment by rgstephens** [comment]
For categorical slots, would be good to provide an option for categorical slots that will not change the slot value when there is an attempt to set the slot to a value that isn't explicitly defined.
