### ISSUE TITLE
`TEDPolicy` crashes due to an empty tensor when `active_loop: some_form` is in the training data, but `some_form` is not defined in the domain

### ISSUE THREAD

**Issue by koernerfelicia** [RasaHQ/rasa#8759]
**Rasa version**: 2.6.2

**Python version**: 3.8.7

**Operating system** (windows, osx, ...): OSX

**Issue**: This issue is one of two* created from this user issue [here](https://github.com/RasaHQ/rasa/issues/8729).

It seems if `active_loop: some_form` is specified in a story but `some_form` is not specified in the domain, `TEDPolicy` crashes due to an empty tensor. We should probably handle this more gracefully.

*The [other issue](https://github.com/RasaHQ/rasa/issues/8760) is to warn the user if they have not defined the form but included `active_loop: some_form` in their stories. (see user issue for more info)

**Definition of Done**:

*   [ ] Relationship between `rasa data validate` and `rasa train` revisited with Enable

**Comment by wochinge** [comment]
@TyDunn Should we move this enable as the other part of #8760 ?
