### ISSUE TITLE
Add support to Python 3.9

### ISSUE THREAD

**Issue by m-vdb** [RasaHQ/rasa#8762]
[Python 3.9](https://www.python.org/downloads/release/python-390/) was released on October 5, 2020.

To be able to add support for this version, we'll need rasa's dependencies to also support it. [Tensorflow seems to now support it](https://github.com/tensorflow/tensorflow/issues/44485), but we need to check that the various tensorflow extensions and other dependencies support it.

The draft PR: https://github.com/RasaHQ/rasa/pull/10002

**Definition of Done**
- [x] Update rasa-sdk to support Python 3.9
- [x] https://github.com/RasaHQ/rasa/issues/10119 closed
- [x] Make sure our dependencies support Python 3.9
- [x] Update the CI
- [x] Update developer environments
- [ ] Merge https://github.com/RasaHQ/rasa/pull/10002
- [ ] Close https://github.com/RasaHQ/rasa/issues/10115
- [ ] Close https://github.com/RasaHQ/rasa/issues/10110
- [ ] ~Add 3.9 classifier to pyproject.toml like https://github.com/RasaHQ/rasa/pull/10405~

**Comment by alwx** [comment]
Closing it because of this one: https://github.com/RasaHQ/rasa/issues/10119

**Comment by m-vdb** [comment]
@alwx should we treat the Python 3.9 separated to upgrading `transformers`? There's an obvious dependency between the two, but upgrading to Python 3.9 needs work on its own (which you already started doing). If you agree, I'd keep this issue open to track it in our backlog

**Comment by alwx** [comment]
The draft PR: https://github.com/RasaHQ/rasa/pull/10002
