### ISSUE TITLE
3.0 Action Plan: Determine the responsibilities

### ISSUE THREAD

**Issue by joejuzl** [RasaHQ/rasa#8764]
**Description of Problem**:
As part of #8721 we need to determine and document the responsibilities of the plan owner.
This will define how the plan is managed and updated.

Creating the plan will be covered by #8763

Some notes from the brainstorm:
- Define how things are updated
- Define how estimations are gathered
- List expectations & accountability

**Blockers**:
- #8763

**Definition of Done**:
- [x] Responsibilities written
- [x] Shared with squad
- [ ] Added to the action plan document

**Comment by m-vdb** [comment]
First draft here: https://www.notion.so/rasa/Draft-Roles-responsiblities-3-0-action-plan-58190ea410294b948249b1e0eef5520c

**Comment by TyDunn** [comment]
@m-vdb Can you please close this if you feel it is done?

**Comment by m-vdb** [comment]
I've updated the page, closing this ✅
