### ISSUE TITLE
Add training scores to integration tests

### ISSUE THREAD

**Issue by JEM-Mosig** [RasaHQ/rasa#8768]
**Description of Problem**:
Right now, integration tests only report test scores. Thus, we don't see if the model had actually converged. This originates from [this issue](https://github.com/RasaHQ/rasa/issues/8678). [Slack Thread](https://rasa-hq.slack.com/archives/C01H2UCNP2T/p1622204690104300).

**Overview of the Solution**:
Add a `poetry run rasa test nlu --quiet -u ${DATASET_DIR}/$DATASET/${TRAIN_DIR} ...`  to the `ci_model_regression.yml` and the `ci-model-regression-on-schedule.yml`. Make sure the results are properly recorded and added to metabase when appropriate. If we have tests for policies by then, too, then these should also report training scores.

**Definition of Done**:
* [ ] Model regression tests on GitHub report training scores in addition to test scores (on-demand and weekly)
* [ ] Training scores are also tracked on MetaBase

**Comment by tmbo** [comment]
I'll move this to the future column

**Comment by andreoid** [comment]
Moved this enhancement request to JIRA: INFRA-36
