### ISSUE TITLE
Record convergence time in regression tests.

### ISSUE THREAD

**Issue by JEM-Mosig** [RasaHQ/rasa#8769]
**Description of Problem**:
It would be good to know how quickly our models converge when we run regression tests on GitHub. For this, we need to record the [training scores](https://github.com/RasaHQ/rasa/issues/8768) of the final model to see if it converges at all, but also at what point it has reach its peak performance (this issue). (original [issue](https://github.com/RasaHQ/rasa/issues/8678))

**Overview of the Solution**:
Add the `tensorboard_log_directory` parameter to all models in [all configs](https://github.com/RasaHQ/training-data/tree/main/configs). Then extract the convergence data from the tensorboard logs and calculate at which step the model has reached or exceeded its final performance twice. 

**Definition of Done**:
* [ ] Model regression tests (on-demand and weekly) on GitHub report point of convergence for all scores
* [ ] Convergence points are also tracked on MetaBase

**Comment by JEM-Mosig** [comment]
Some code to extract data from tensorboard logs:
```
from typing import List, Optional
from tensorboard.backend.event_processing.event_accumulator import EventAccumulator, SCALARS

ea = EventAccumulator(
    "/home/jem-mosig/projects/rasa/johannes/init-bot/tensorboard/DIET/train",
    size_guidance={
        SCALARS: 0
    }
)

ea.Reload()

print(ea.Tags().get("scalars"))

data = [
    [event.step, event.value]
    for event in ea.Scalars("epoch_i_acc")
]
# print(ea.Scalars("epoch_i_acc"))  # "epoch_i_acc"

print(data)

def nth_time_value_was_reached(
    data: List[List[float]],
    n: int = 1,
    target_value: Optional[float] = None
) -> int:
    result_step = 0
    times = 0
    if target_value is None:
        target_value = data[-1][1]
    for step, value in data:
        if value >= target_value:
            result_step = step
            times += 1
        if times == n:
            break
    return result_step

print(f"1: {nth_time_value_was_reached(data)} of {data[-1][0]}")
print(f"2: {nth_time_value_was_reached(data, 2)} of {data[-1][0]}")
```

**Comment by tmbo** [comment]
I'll move it to future, we won't get to this any time soon.

**Comment by andreoid** [comment]
Replaced by JIRA ticket: INFRA-37
