### ISSUE TITLE
Docker Compose Manual Installation: Wrong file url

### ISSUE THREAD

**Issue by dudanogueira** [RasaHQ/rasa#8783]
**Issue**:
The url path for the docker compose manual installation is wrong, rendering a non workable deployment:

Link: [doc link](https://rasa.com/docs/rasa-x/installation-and-setup/install/docker-compose#3-download)

where it reads, for linux:

Also download the Nginx configuration files:

```
mkdir nginx-config-files
wget -qO nginx-config-files/nginx.conf https://storage.googleapis.com/rasa-x-releases/0.40.1/nginx-config-files/nginx-config-files/nginx.conf
wget -qO nginx-config-files/ssl.conf.template https://storage.googleapis.com/rasa-x-releases/0.40.1/nginx-config-files/nginx-config-files/ssl.conf.template
wget -qO nginx-config-files/rasax.nginx.template https://storage.googleapis.com/rasa-x-releases/0.40.1/nginx-config-files/nginx-config-files/rasax.nginx.template

```

the nginx-config-files is duplicated. it should be:

```
mkdir nginx-config-files
wget -qO nginx-config-files/nginx.conf https://storage.googleapis.com/rasa-x-releases/0.40.1/nginx-config-files/nginx.conf
wget -qO nginx-config-files/ssl.conf.template https://storage.googleapis.com/rasa-x-releases/0.40.1/nginx-config-files/ssl.conf.template
wget -qO nginx-config-files/rasax.nginx.template https://storage.googleapis.com/rasa-x-releases/0.40.1/nginx-config-files/rasax.nginx.template

```

Thanks for this awesome project!

Sorry if this is the wrong place to point this. I tried looking for the docs at this repo, but couldn't find.

**Comment by sara-tagger** [comment]
Thanks for the issue, @hsm207 will get back to you about it soon!

###### You may find help in the [docs](https://rasa.com/docs/) and the [forum,](https://forum.rasa.com/) too 🤗

**Comment by hsm207** [comment]
Thanks for raising this issue. We've made a PR to update the links.
