### ISSUE TITLE
Refactor IntentMaxHistoryTrackerFeaturizer Tests

### ISSUE THREAD

**Issue by kedz** [RasaHQ/rasa#8798]
**Description of Problem**:

`tests/core/featurizers/test_tracker_featurizer.py` could be refactored to reduce the amount of duplicate test code.

For instance, there is a great deal of duplication across the three `TrackerFeaturizer` subclasses (`FullDialougeTrackerFeaturizer`, `MaxHistoryTrackerFeaturizer`, and `IntentMaxHistoryTrackerFeaturizer`) which largely implement the same api.

Many comments and suggests have been made about this in the course of the original `IntentMaxHistoryTrackerFeaturizer` [feature PR](https://github.com/RasaHQ/rasa/pull/8570). While not implying all comments need to be followed, listing them here for easy access/understanding:

*   Helper classes/fixtures could be used to construct Inputs (trackers) and expected outputs which currently are written out and take up quite a bit of space ([link](https://github.com/RasaHQ/rasa/pull/8570#issuecomment-850239745))

*   Fixtures should go in `tests/core/conftest.py` ([link](https://github.com/RasaHQ/rasa/pull/8570#discussion_r636009185))

*   When writing out expected states/features is unavoidable, it would be helpful if the dictionary keys were written out in chronological order ([link](https://github.com/RasaHQ/rasa/pull/8570#discussion_r643741057))

*   The tests could use comments for explaining expected behavior since that is not documented anywhere ([link](https://github.com/RasaHQ/rasa/pull/8570#issuecomment-849902790))

*   Some tests could be combined with parametrizing ([link](https://github.com/RasaHQ/rasa/pull/8570#discussion_r643982397) and [link](https://github.com/RasaHQ/rasa/pull/8570#discussion_r643994186))

*   Separate tests for methods using the same underlying private methods could be removed if tested the private methods directly. ([link](https://github.com/RasaHQ/rasa/pull/8570#discussion_r643990393))

*   tests of label ids should get the ids from a domain object and not hard code them ([link](https://github.com/RasaHQ/rasa/pull/8570#discussion_r643408543))

**Definition of Done**:

*   [ ] Tests are refactored and lines of code reduced.

**Comment by alopez** [comment]
@kedz this looks like part of the IntentTED project; should it go in that backlog? Or is this a more general / optional thing?

**Comment by kedz** [comment]
@alopez Yes sorry should be backlog for IntentTED.

**Comment by TyDunn** [comment]
@JEM-Mosig Are you still working on this?
