### ISSUE TITLE
Investigate 3.0 deprecation warnings

### ISSUE THREAD

**Issue by TyDunn** [RasaHQ/rasa#8814]
We need more information to estimate the effort required to [Follow through on CLI / CI deprecation warnings in 3.0](https://www.notion.so/rasa/Follow-through-on-CLI-CI-deprecation-warnings-in-3-0-f1605e6cf6d948f0a913a7623fa4c191)

**Definition of done**

- [x] Look into deprecation warnings
- [x] Determine the number of warnings
- [x] Create one or multiple issues (multiple warnings can be grouped in one issue - each issue should have adequate size)

**Comment by TyDunn** [comment]
There are a total of 35 deprecation & future warnings that need to be actioned for 3.0 - these are documented [here](https://docs.google.com/spreadsheets/d/1PAgf1oEbefxc652KDRLMqcu9bqsKHaiFzJguW2s1P2U/edit?usp=sharing), highlighted in yellow.

**Comment by ancalita** [comment]
15 Github issues were submitted in Enable and Research inboxes.
