### ISSUE TITLE
GET request handling for telegram channel

### ISSUE THREAD

**Issue by ancalita** [RasaHQ/rasa#8818]
**Goal** Improve the way GET request is handled [here.](https://github.com/RasaHQ/rasa/blob/d4d606b12370d440d9f9ed3f9e4d8e2a23b959b8/rasa/core/channels/telegram.py#L277)

**Definition of Done**

*   [ ] align with Enable on implementation proposal
*   [ ] implement enhancement
*   [ ] add tests
*   [ ] update docs
*   [ ] add changelog

**Comment by Archish27** [comment]
@ancalita I would like to work on this. 

Do I have to refactor? Can explain once? 

Like what I understand currently the way it is written doesn't help in readability can be broken down into classes. 

Correct me if I am wrong :)

**Comment by ancalita** [comment]
Hi @Archish27 thank you for expressing interest in this issue 💯 
The issue actually does not involve refactoring, it should be an enhancement of how the GET request method is handled in [L277](https://github.com/RasaHQ/rasa/blob/d4d606b12370d440d9f9ed3f9e4d8e2a23b959b8/rasa/core/channels/telegram.py#L277). At the moment it returns a [Sanic `Blueprint` object](https://sanic.readthedocs.io/en/v20.3.0/sanic/blueprints.html).

If you have any thoughts of how best to implement this enhancement, please write up a plan and share with me and then the team can review.
