### ISSUE TITLE
Fix Rasa OSS changelog formatting for issue #7420 in Rasa 2.3.0 Improvements section

### ISSUE THREAD

**Issue by PROrock** [RasaHQ/rasa#8842]
**Description of Problem**:

The Rasa OSS changelog is broken for a few lines/blocks starting from [https://rasa.com/docs/rasa/changelog#improvements-3](https://rasa.com/docs/rasa/changelog#improvements-3) under the mentioned issue #7420\. Preferred to fix this, so the page is really readable as intended.

**Overview of the Solution**:

Fix the formatting (probably some missing or extra quotes or stuff like that).

**Examples** (if relevant):

[https://rasa.com/docs/rasa/changelog#improvements-3](https://rasa.com/docs/rasa/changelog#improvements-3)

**Blockers** (if relevant):

Not blocking anyone. Low priority (but should be quick to fix, ideal for a new Rasa contributors <span class="error">[!/images/icons/emoticons/wink.png!| /images/icons/emoticons/wink.png]</span> ).

**Definition of Done**:

*   [ ] Changelog properly formatted for issue #7420

**Comment by degiz** [comment]
@RasaHQ/enable-squad

**Comment by TyDunn** [comment]
Thanks for the ping! You can also just throw it in our inbox by adding it to the `Enable` project board

**Comment by PROrock** [comment]
Hi, any update on this?

**Comment by TyDunn** [comment]
We have not got to it yet. The team is hyper-focused on 3.0 atm. This seems like a quick win we can pick up after that though, or if someone in the community could pick it up, that would be great :)

**Comment by wochinge** [comment]
@PROrock Would you mind fixing it? Happy to review your PR for it 🙌🏻

**Comment by PROrock** [comment]
Hi Tobias,
I'm not so dedicated or don't want to help the Rasa OSS so much, that I would spend my personal free time on this, sorry.
I'll at least stop pushing/reminding this and will hope that someone will fix it in the future, if not, no hard feelings I understand.
Thank you both for your responses and have a nice day :-)
