### ISSUE TITLE
problem with logic of rasa'rule

### ISSUE THREAD

**Issue by duongkstn** [RasaHQ/rasa#8846]
**Rasa version**: 2.5.0

**Rasa SDK version** (if used & relevant): 2.6.0

**Rasa X version** (if used & relevant):

**Python version**: 3.7.9

**Operating system** (windows, osx, ...): Ubuntu 18.04

**Issue**: Rasa did not the output what I want in the conversation. Check the `rule.yml` file below and here is my expected conversation:

*   user: X
*   rasa: Ok, now you are at Y
*   user: other
*   rasa: Nothing here

But in fact, when I entered "X", rasa did not reply anything. To reproduce result:

*   run `rasa train -c config.yml -d domain.yml --out models/ --augmentation 0 --data data/` .
*   run `rasa run actions` and `rasa shell --debug` in two seperate terminals.

In my understanding, rasa should executes in following steps:

*   Recognize user message 'X' as `intent_x` intent
*   Go to `action_goto_Y`
*   Assign Slot `goto = Y` (`return <span class="error"><span class="error">[SlotSet("goto", "Y")]</span></span>`)
*   Since the slot `goto = Y`, the condition of `rule: goto Y` is met, so rasa outputs action `utter_wentto_Y`
*   ...
*   ...

Did my understanding go wrong ? please explain to me clearly . Thanks a lot ~

**Error (including full traceback)**:

**Command or request that led to error**:

**Content of configuration file (config.yml)** (if relevant):

<pre>language: en
 pipeline:

*   name: WhitespaceTokenizer
     token_pattern: (?u)\b\w+\b
*   name: CountVectorsFeaturizer
*   name: DIETClassifier
     number_of_transformer_layers: 1
     number_of_attention_heads: 1
     epochs: 100
     policies:
*   name: RulePolicy
     restrict_rules: true
     check_for_contradictions: true
     </pre>

**Content of domain file (domain.yml)** (if relevant):

<pre>version: '2.0'
 config:
 store_entities_as_slots: true
 session_config:
 session_expiration_time: 480
 carry_over_slots_to_new_session: true
 intents:

*   intent_X
*   intent_other
     slots:
     goto:
     type: addons.my_custom_slots.goto
     influence_conversation: true
     actions:
*   action_goto_Y
*   utter_wentto_Y
     responses:
     utter_wentto_Y:
*   text: "Ok, now you are at Y"
     utter_other:
*   text: "Nothing here"</pre>

**Content of Slot file (addons/my_custom_slots.py)** (if relevant):

<pre>from rasa.shared.core.slots import Slot

class goto(Slot):
 def feature_dimensionality(self):
 return 2

 def as_feature(self):
 r = <span class="error">[0.0]</span> * self.feature_dimensionality()
 if self.value:
 if self.value == "Y":
 r<span class="error">[0]</span> = 1.0
 else:
 r<span class="error">[1]</span> = 1.0
 return r</pre>

**Content of Rule file (data/rules/rule.yml)** (if relevant):

<pre>version: "2.0"
 rules:

*   rule: my_rule
     steps:
*   intent: intent_X
*   action: action_goto_Y
     wait_for_user_input: false

*   rule: goto Y
     condition:
*   slot_was_set:
*   goto: Y
     steps:
*   action: utter_wentto_Y
*   intent: intent_other
*   action: utter_other</pre>

**Content of NLU file (data/nlu/nlu.yml)** (if relevant):

<pre>version: "2.0"
 nlu:

*   intent: intent_X
     examples: |
*   X
*   XX
*   XXX
*   intent: intent_other
     examples: |
*   other
*   others
     </pre>

**Content of action file (actions/actions.py)** (if relevant):

<pre>from typing import List, Text
 from rasa_sdk import Action, Tracker
 from rasa_sdk.types import DomainDict
 from rasa_sdk.executor import CollectingDispatcher
 from rasa_sdk.events import (
 SlotSet,
 EventType,
 )

class ActionGoToY(Action):
 def name(self) -> Text:
 return "action_goto_Y"

 def run(
 self,
 dispatcher: CollectingDispatcher,
 tracker: Tracker,
 domain: DomainDict,
 ) -> List<span class="error">[EventType]</span>:
 return <span class="error">[SlotSet("goto", "Y")]</span></pre>

**Comment by sara-tagger** [comment]
Thanks for the issue, @erohmensing will get back to you about it soon!

###### You may find help in the [docs](https://rasa.com/docs/) and the [forum,](https://forum.rasa.com/) too 🤗
