### ISSUE TITLE
Improve `RulePolicy` prediction timings

### ISSUE THREAD

**Issue by wochinge** [RasaHQ/rasa#8850]
**Description of Problem**: `RulePolicy` predictions are slow. This is especially noticeable during training [when we check for contradictions](https://github.com/RasaHQ/rasa/blob/8b50a96a8482179478a00f0beef7c25935988787/rasa/core/policies/rule_policy.py#L801). The reason for this is that we call `_rule_key_to_state` a lot [when checking if a rule is applicable](https://github.com/RasaHQ/rasa/blob/8b50a96a8482179478a00f0beef7c25935988787/rasa/core/policies/rule_policy.py#L855). For each time we are doing this we are loading the json which is encoding the rule.

This is a followup from [this issue](https://github.com/RasaHQ/rasa/issues/8295).

**Examples** (if relevant):

*   You can find a profiling of contradiction check [here](https://drive.google.com/file/d/154vW5bufikVcjXfrmqDDdA3A4PmXIeEt/view?usp=sharing) (viewable with tools like [snakeviz](https://jiffyclub.github.io/snakeviz/)).
*   quick fix was done here: [https://github.com/RasaHQ/rasa/pull/8851](https://github.com/RasaHQ/rasa/pull/8851)

**Definition of Done**:

*   [ ] Determine a quicker way to encode / load the rule states (e.g. by unwrapping the jsons just once or use a faster mechanism to load the jsons)

**Comment by danielenricocahall** [comment]
Now that caching has been added as an enhancement, could another possible solution be using a more performance optimized JSON library (e.g; [orjson](https://github.com/ijl/orjson), [rapidjson](https://pypi.org/project/python-rapidjson/))? And/or would it make sense to make the cache size configurable? Similar issue has been raised [here](https://github.com/RasaHQ/rasa/issues/10703 )
