### ISSUE TITLE
Add TED only config to regression tests

### ISSUE THREAD

**Issue by kedz** [RasaHQ/rasa#8852]
**Description of Problem**: Currently we run regression tests of TED only in combination with Rule, Memo, or AugMemo policies. We should also run it on TED in isolation.

**Overview of the Solution**: Add `ted.yml` file to `configs/en/core` in the `training-data` repo with the following:

<pre>language: en
 policies:

*   name: TEDPolicy
     max_history: 5
     epochs: 100
     random_seed: 42
     constrain_similarities: True</pre>

Additionally, add the following line to the config mapping in `dataset_config_mapping.json` in `training-data` repo:

<pre> "core": 

 { "TED": "ted.yml", #<--- add this line to core config mappings "Rules": "rules.yml", "Rules + Memo": "rules_memo.yml", "Rules + AugMemo": "rules_augmemo.yml", "Rules + TED": "rules_ted.yml", "Rules + Memo + TED": "rules_memo_ted.yml", "Rules + AugMemo + TED": "rules_augmemo_ted.yml" } 

</pre>

**Definition of Done**:

*   [ ] TED only config added
*   [ ] `dataset_config_mapping.json` updated
*   [ ] Verify TED only config runs successfully in regression tests

**Comment by tttthomasssss** [comment]
@TyDunn Can we get your input on this issue w.r.t. prioritisation?

**Comment by samsucik** [comment]
To do: Expand the definition of done to include establishing a way of actually running a TED-only config with bots that include forms (see my above comment).

**Comment by TyDunn** [comment]
@tttthomasssss Here I think it is up to research to help me understand how important this is. If it is important we do it now,  then we can prioritise it. If it can wait, then we will wait to prioritize it

**Comment by tttthomasssss** [comment]
imho we can deprio it for now - any objections @kedz & @samsucik?

**Comment by samsucik** [comment]
@tttthomasssss no objections but I think @kedz knows much more than I about the importance of this issue.

**Comment by kedz** [comment]
No objections, @tttthomasssss. This was desired to make validating UnexpecTEDIntentPolicy easier, but that is no longer an issue. TED is part of several other configs for regression tests so I'm not losing any sleep about this.
