### ISSUE TITLE
Create a script to run IntentTED on conversation logs

### ISSUE THREAD

**Issue by kedz** [RasaHQ/rasa#8853]
**Description of Problem**:
We would like to be able to run a trained IntentTED model on historical conversations logged in a tracker store or Rasa X instance from the command line. A lightweight way of doing this before we commit to integrating this more tightly into the cli or rasa x would be to have a script that:

- pulls trackers from a tracker store 
- writes them to YAML stories locally `my_logs.yml`
- calls `rasa test core -s my_logs.yml --results my_logs_results`

Developers could then inspect the `failed_test_stories.yml` (eventually `warnings.yml`) files in the results directory to see stories where IntentTED predicted an `action_unlikely_intent` and triage them accordingly (e.g. turn into a training story).

We would need to determine:
 - what criteria are used to pull trackers (e.g. date range, rasa x labels)
 - Figure out where the script would live since its not part of the rasa os cli. 
 - Determine if its better to download trackers from tracker store or Rasa X.
 
 additional discussion can be found in the comments on this notion [here](https://www.notion.so/rasa/Tracking-Q2-O2-KR2-a4e26d7a1458478c81f92482be6af896#9c5e9c6c753143ed892b574209500217).

**Definition of Done** (Updated):

Script does the following:
- [ ] Conversations are fetched from tracker store.
- [ ] Conversations can be filtered on a date range.
- [ ] `rasa test` is run on these conversations with output being stored in usual output files of `rasa test`.
- [ ] Has proper documentation on usage.

**Comment by TyDunn** [comment]
@alwx Do you think it makes more sense to grab historical conversations logged in a tracker store or the Rasa X db?

**Comment by dakshvar22** [comment]
Needs `rasa test` to factor in `IntentTEDPolicy`'s predictions (https://github.com/RasaHQ/rasa/issues/8422)

**Comment by wochinge** [comment]
> We would like to be able to run a trained IntentTED 

> Developers could then inspect

The use case doesn't seem clear to me. Are we building this so Research can evaluate the IntentTED policy or are we building this for Rasa Open Source users? What are the plans for this in the future - will we re-use that or is it something which we can throw away after evaluating `IntentTED` on it?

**Comment by dakshvar22** [comment]
The primary use case is an intermediate solution for developers to be able to run `IntentTED` on real conversations until Rasa X has support for `IntentTED`. Moreover, building support for `IntentTED` inside Rasa X will require us to understand different annotation workflows users can go through and this script is the first step of it - Being able to run real conversations through an assistant trained with `IntentTED` (even if those conversations were processed by a model pipeline not containing `IntentTEDPolicy` in it).
Evaluating `IntentTED` is a secondary use case.

Based on the above, do you have suggestions on where this could script could live? We can put it as a standalone script in `rasa-nlu-examples` repo or `rasalit` repo (None of them fit the nature of the script perfectly but at least these repos are known to our developers)

**Comment by wochinge** [comment]
Ok 👍🏻 Then I'd vote for going through the tracker store as that works for both Rasa X and Rasa Open Source users. 

We could even just have it as a gist.

**Comment by dakshvar22** [comment]
Sounds good. Idk why I never thought of a gist 😅 Thanks for the input! 🙏

**Comment by ArjaanBuijk** [comment]
What about making it part of the scorecard script [score.py](https://github.com/RasaHQ/customer-scorecard/blob/main/scripts/score.py) ?

Given concerns about a lot of false warnings, maybe behind a command line option.

**Comment by TyDunn** [comment]
@ArjaanBuijk I was thinking about incorporating it into the scorecard as well. I think that is the likely next step before incorporating it into Rasa Enterprise

**Comment by rudolfix** [comment]
hello @kedz is this script already available somewhere?

**Comment by TyDunn** [comment]
I believe @alwx is working on the script right now

**Comment by alwx** [comment]
The script lives here: https://gist.github.com/alwx/b426b7b573ff963c85c65ea6466528d7
