### ISSUE TITLE
Please make a docs on Discord channel to use rasa x bot 

### ISSUE THREAD

**Issue by shreesha345** [RasaHQ/rasa#8861]
**I am really finding a way to connect my rasa x bot to discord bot please make a document on the discord channel to integrate with
it please make it .**

**Comment by sara-tagger** [comment]
Thanks for submitting this feature request 🚀 @jupyterjazz will get back to you about it soon! ✨

**Comment by jupyterjazz** [comment]
let's continue here
https://forum.rasa.com/t/how-to-connect-rasa-to-discord-bot/44519
