### ISSUE TITLE
Upgrad tensorflow dependency from Tensorflow 2.3.2 to Tensorflow 2.5.0

### ISSUE THREAD

**Issue by PranitModak** [RasaHQ/rasa#8865]
**Description of Problem**:
 Current version of tensorflow(2.3.2) being used in Rasa 2.7.0 is having some vulnerabilities
 due to which we are unable to implement it. Manually upgrading tensorfow to 2.5.0, causes issue as tensorflow.python.keras.engine.training.py does not have function enable_multi_worker in the latest version of tensorflow.

**Overview of the Solution**:
 Either omit the dependency on the function enable_multi_worker while training a model or increase tensorflow version dependency to 2.5.0.

**Examples** (if relevant):

**Blockers** (if relevant):

**Definition of Done**:

- [ ]           Upgraded dependency to Tensorflow 2.5.0
- [ ]           Remove use of @training.enable_multi_worker in  https://github.com/RasaHQ/rasa/blob/main/rasa/utils/tensorflow/temp_keras_modules.py

**Comment by sara-tagger** [comment]
Thanks for submitting this feature request 🚀 @aeshky will get back to you about it soon! ✨

**Comment by alopez** [comment]
@koernerfelicia I believe you are already looking into this in https://github.com/RasaHQ/rasa/issues/8700.

**Comment by koernerfelicia** [comment]
@alopez , yep closing this as a duplicate of https://github.com/RasaHQ/rasa/issues/7619 and https://github.com/RasaHQ/rasa/issues/8700
