### ISSUE TITLE
3.0 Deprecation Warnings: Remove deprecated featurizers

### ISSUE THREAD

**Issue by ancalita** [RasaHQ/rasa#8879]
**Background**
These warnings were found in:
- rasa.core.featurizers.single_state_featurizer.py:L382, L410
```
"f""'{self.__class__.__name__}' is deprecated and ""
f""will be removed in Rasa Open Source 3.0.0. ""
f""It is recommended to use the '{SingleStateFeaturizer.__name__}' instead."""
```
- rasa.nlu.utils.hugging_face.hf_transformers.py:L66
```
"f""'{self.__class__.__name__}' is deprecated and ""
f""will be removed in the future. ""
 f""It is recommended to use the '{LanguageModelFeaturizer.__name__}' instead."""
```

**Definition of Done**:
- [x] resolve warnings in 3.0 version
- [x]  Removed the deprecated featurizers from the codebase.
- [x] Added a changelog entry for 3.0 saying we've removed the previously deprecated featurizers
- [x] Removed the references in the docs

**Comment by kedz** [comment]
Since tokenization and featurization tests are tightly coupled, I'm removing `rasa/nlu/utils/hugging_face/hf_transformers.py` as part of https://github.com/RasaHQ/rasa/pull/9120/ .
