### ISSUE TITLE
3.0 Deprecation Warnings: Remove Policy deprecations

### ISSUE THREAD

**Issue by ancalita** [RasaHQ/rasa#8880]
**Background**
These warnings were found in:
- rasa.core.policies.fallback.py:L66
```
"f""'{self.__class__.__name__}' is deprecated and will be removed ""
""in the future. It is recommended to use the 'RulePolicy' instead."""
```
- rasa.core.policies.form_policy.py:L51
```
"f""'{FormPolicy.__name__}' is deprecated and will be removed in ""
 ""in the future. It is recommended to use the 'RulePolicy' instead."""
```
- rasa.core.policies.mapping_policy.py:L49
```
"f""'{MappingPolicy.__name__}' is deprecated and will be removed in ""
""the future. It is recommended to use the 'RulePolicy' instead."""
```
- rasa.core.policies.memoization.py:L87
```
"f""Please configure the max history in your configuration file, ""
f""currently 'max_history' is set to old default value of ""
f""'{max_history}'. If you want to have infinite max history ""
f""set it to 'None' explicitly. We will change the default value of ""
 f""'max_history' in the future to 'None'."","
```
- rasa.core.policies.sklearn_policy.py:L124
```
"f""'{SklearnPolicy.__name__}' is deprecated and will be removed in ""
""the future. It is recommended to use the 'TEDPolicy' instead."""
```

**Definition of Done**
- [ ] resolve warnings in 3.0 version
- [ ] Removed the deprecated policies from the codebase.
- [ ] Added a changelog entry for 3.0 saying we've removed the previously deprecated policies
- [ ] Removed the references in the docs

**Comment by kedz** [comment]
@ancalita @JEM-Mosig TwoStageFallbackPolicy is listed as deprecated in our [docs page](https://rasa.com/docs/rasa/policies#two-stage-fallback-policy), but does not have a deprecation warning. Should we also remove it from the code base along with these other deprecated policies?

**Comment by kedz** [comment]
Also it turns out `TwoStageFallbackPolicy` is a subclass of `FallbackPolicy` so I guess it has to go.

**Comment by TyDunn** [comment]
> Is this an oversight?

I'd guess it was or maybe since it was subclass of `FallbackPolicy`, someone did not think it was necessary
