### ISSUE TITLE
3.0 Deprecation Warning: Remove deprecated tokenizers

### ISSUE THREAD

**Issue by ancalita** [RasaHQ/rasa#8881]
**Background**
This warning was found in:
- rasa.nlu.tokenizers.convert_tokenizer:L27
- rasa.nlu.tokenizers.lm_tokenizer.py:L21
```
"f""'{self.__class__.__name__}' is deprecated and ""
f""will be removed in the future. ""
f""It is recommended to use the '{WhitespaceTokenizer.__name__}' or ""
f""another {Tokenizer.__name__} instead."","
```

**Definition of Done**
- [x] resolve warnings in 3.0 version
- [x] Removed the deprecated tokenizers from the codebase.
- [x] Added a changelog entry for 3.0 saying we've removed the previously deprecated tokenizers
- [x] Removed the references in the docs

**Comment by samsucik** [comment]
Are we actually removing these tokenisers in 3.0? 🤔

**Comment by kedz** [comment]
Also removing deprecated featurization related to the `LanguageModelTokenizer` originally from this issue https://github.com/RasaHQ/rasa/issues/8879 :

   -  `rasa.nlu.utils.hugging_face.hf_transformers.py`
