### ISSUE TITLE
3.0 Deprecation Warning: Remove deprecated `Message` method

### ISSUE THREAD

**Issue by ancalita** [RasaHQ/rasa#8883]
**Background**
This warning was found in:
- rasa.shared.nlu.training_data.message.py:L188
```
"""`get_combined_intent_response_key` is deprecated and ""
""will be removed in Rasa 3.0.0. ""
""Please use `get_full_intent` instead."""
```

**Definition of Done**
- [ ] resolve warning in 3.0 version
- [x] Removed the method from the codebase.
- [x] Added a changelog entry for 3.0 saying we've removed the previously deprecated method.
- [x] Removed the references in the docs

**Comment by samsucik** [comment]
Can this be done right now? For 3.0 stuff, do we simply target `main`?

In any case, since the deprecated method doesn't appear anywhere in our Rasa Open Source tests or docs, the definition of done can be, I think, as simple as:
1. Removed the method from the codebase.

**Comment by ancalita** [comment]
> Can this be done right now? For 3.0 stuff, do we simply target main?

I think all deprecations will be part of the prep work that can be done after the `2.8.` release, targeting `main` - @m-vdb correct me if I'm wrong about the timeline?

**Comment by m-vdb** [comment]
yep 👍🏻
