### ISSUE TITLE
[CI] Random selection of a team member is not working.

### ISSUE THREAD

**Issue by HotThoughts** [RasaHQ/rasa#8893]
Fix the error in the `Select a member from managers team randomly` step

https://github.com/RasaHQ/rasa/runs/2759366368?check_suite_focus=true

```
jq: error (at <stdin>:1): Cannot index string with string "login"
```

**Comment by dakshvar22** [comment]
We recently introduced a change in our internal team processes and as a result of that we don't want to randomly assign these issues to a team member. Would it be possible to completely get rid of that step? 🙂

**Comment by HotThoughts** [comment]
@dakshvar22 So you want to just create the issue and send the slack message. If this is the case, definitely we can remove the Random selection of a team member step.

**Comment by dakshvar22** [comment]
Yes, so just to be clear 🙂  :

1. Create an issue
2. Add relevant tags
3. Send the slack message
4. Add the issue to the research project inbox.

**Comment by HotThoughts** [comment]
@dakshvar22 Thanks for the clarity. 🙇‍♀️  I can work on this next week as I am on vacation this week.

**Comment by dakshvar22** [comment]
For sure! Please enjoy your vacation! Didn't mean to disturb you mid-vacation. 🙂
