### ISSUE TITLE
Skip evaluation if no labels are found

### ISSUE THREAD

**Issue by koernerfelicia** [RasaHQ/rasa#8894]
**Rasa version**: 2.7.0 **Python version**: 3.8.7 **Operating system** (windows, osx, ...): OSX

**Issue**: When no labels are found [here](https://github.com/RasaHQ/rasa/blob/main/rasa/model_testing.py#L364-L366), the warning message indicates that evaluation will be skipped. However, we do not check for the empty return values from this function, and continue to process them (for example writing a story report [here](https://github.com/RasaHQ/rasa/blob/main/rasa/core/test.py#L908-L925), though there are other places).

**Error**: There's no error as such, except potential confusion, and side effects from continuing with empty values, like [this](https://github.com/RasaHQ/rasa/issues/8812).

**Comment by TyDunn** [comment]
@koernerfelicia In what cases are there no labels?

**Comment by koernerfelicia** [comment]
I just ran into this for the case where you have no entities. Not sure if here is another case, gut says no
