### ISSUE TITLE
Evaluation of story to give separate entities and intent scores.

### ISSUE THREAD

**Issue by pdan93** [RasaHQ/rasa#8919]
Currently, if you run `rasa test` on some test stories you get the results in a `story_report.json` with the averages over all the scores. If you have entities annotated in the test stories, those results are included in the final average score.

It would help if we would get the average score for the intent classification and the entity recognition separate as well.

So for example instead of having just the "micro avg", "macro avg", "weighted avg" scores, we would also get "micro entity avg", "macro entity avg", "weighted entity avg" and "micro intent avg", "macro intent avg", "weighted intent avg"

**Comment by sara-tagger** [comment]
Thanks for submitting this feature request 🚀 @aeshky will get back to you about it soon! ✨
