### ISSUE TITLE
Disable Sara tagger for contributor PRs, it's now taken care of by CODEOWNERs files

### ISSUE THREAD

**Issue by wochinge** [RasaHQ/rasa#8920]
**Description of Problem**:
* Follow up for https://github.com/RasaHQ/rasa/issues/8525 . 
* [Related Slack thread](https://rasa-hq.slack.com/archives/C36SS4N8M/p1624268662044200?thread_ts=1617783559.338900&cid=C36SS4N8M)

Now that we've implemented the [CODEOWNERs file](https://github.com/RasaHQ/rasa/pull/8891) we no longer need Sara tagger to tag people for review. As discussed in Slack Enable should now triage the open source PRs. 

**Overview over solution**
* We should consider edge cases where users change the docs only or when they only change tests.

**Blockers** (if relevant):
- https://github.com/RasaHQ/rasa/issues/8525

**Definition of Done**:
- [ ] Sara tagger no longer tags people for review in community PRs against the Rasa Open Source repository

**Comment by m-vdb** [comment]
Thanks a lot @ArjaanBuijk 🙏🏻
