### ISSUE TITLE
rasa-x installation issue

### ISSUE THREAD

**Issue by mishra011** [RasaHQ/rasa#8948]
**Rasa version**: 2.7.1

**Rasa SDK version** (if used & relevant):

**Rasa X version** (if used & relevant):

**Python version**: 3.7

**Operating system** (windows, osx, ...): Ubuntu 20.04

**Issue**:

**Error (including full traceback)**:
```

INFO: This is taking longer than usual. You might need to provide the dependency resolver with stricter constraints to reduce runtime. If you want to abort this run, you can press Ctrl + C to do so. To improve how pip performs, tell us what happened here: https://pip.pypa.io/surveys/backtracking
  Downloading httptools-0.1.1-cp37-cp37m-manylinux1_x86_64.whl (217 kB)
  Downloading httptools-0.1.0-cp37-cp37m-manylinux1_x86_64.whl (217 kB)
  Downloading httptools-0.0.13.tar.gz (104 kB)
  Downloading httptools-0.0.12.tar.gz (103 kB)
  Downloading httptools-0.0.11.tar.gz (99 kB)
INFO: pip is looking at multiple versions of httptools to determine which version is compatible with other requirements. This could take a while.
  
```

**Command or request that led to error**:
```
pip3 install rasa-x --extra-index-url https://pypi.rasa.com/simple
```

**Content of configuration file (config.yml)** (if relevant):
```yml

```

**Content of domain file (domain.yml)** (if relevant):
```yml

```

**Comment by sara-tagger** [comment]
Thanks for raising this issue, @amn41 will get back to you about it soon✨

###### Please also check out the [docs](https://rasa.com/docs/) and the [forum](https://forum.rasa.com/) in case your issue was raised there too 🤗

**Comment by tmbo** [comment]
There are not enough details to reproduce this issue. I will close this until we have more information.
