### ISSUE TITLE
Investigate possibly incorrect epoch value in `_check_evaluation_setting`

### ISSUE THREAD

**Issue by koernerfelicia** [RasaHQ/rasa#8952]
According to [this issue](https://github.com/RasaHQ/rasa/pull/8944), there may be a bug in `_check_evaluation_setting` in which an incorrect value for `EPOCH` is used.

**Definition of Done**
- [ ] verify whether we can reproduce
- [ ] if so, fix the bug (If the value is wrong, I believe this should be a quick fix, so propose making this issue investigate *and* fix)

**Comment by koernerfelicia** [comment]
@alopez (would normally tag Ty, but since he's out, and you're moderating). I know I'm not in today's refinement meeting, but would be happy to look into this one this upcoming sprint, as if it is a bug it would be one I introduced with [this issue](https://github.com/RasaHQ/rasa/issues/7286), meaning I have context etc. to look into it. I think it should be a quick one.

**Comment by alopez** [comment]
@dakshvar22 primary assignee
@ka-bu reviewer

**Comment by TomV** [comment]
@koernerfelicia  - either an incorrect value for EPOCH is being used (value = 1), or the function is being called in the wrong context (inside a loop rather than before or after it.)  I'm *guessing* it's being called in the wrong place.

Just a suggestion for whoever takes this up. :-)

**Comment by dakshvar22** [comment]
Fixed with https://github.com/RasaHQ/rasa/pull/9182 and should be available in the next patch release of `2.8`
