### ISSUE TITLE
Rasa-X installation issue with pip

### ISSUE THREAD

**Issue by rhazra-003** [RasaHQ/rasa#8968]
**Rasa version**: 2.3.1

**Rasa SDK version** (if used & relevant): 2.3.1

**Rasa X version** (if used & relevant):

**Python version**: 3.7.4

**Operating system** (windows, osx, ...): Windows-10-10.0.19041-SP0

**Issue**:

Rasa-X taking taking more than an hour to install and still not getting installed

**Error (including full traceback)**:

![pip_issue](https://user-images.githubusercontent.com/56204207/123535062-44ac8300-d73f-11eb-8073-d581f6a84f11.png)

**Command or request that led to error**:

pip3 install rasa-x --extra-index-url https://pypi.rasa.com/simple

Other commands were not working as well

**Comment by mmansoornano** [comment]
This is due to pip:

1. pip install --upgrade pip==20.2
2. pip -V to make sure the right version is installed
3. pip install -U rasa-x --extra-index-url https://pypi.rasa.com/simple

OR

pip install --use-deprecated=legacy-resolver --user rasa-x --extra-index-url https://pypi.rasa.com/simple

**Comment by rhazra-003** [comment]
I have tried all the above mentioned things. Issue is still not resolved.

**Comment by mmansoornano** [comment]
Still taking long time? Or is there any different issue?

**Comment by sara-tagger** [comment]
Thanks for the issue, @desmarchris will get back to you about it soon!

###### You may find help in the [docs](https://rasa.com/docs/) and the [forum,](https://forum.rasa.com/) too 🤗

**Comment by rhazra-003** [comment]
> Still taking long time? Or is there any different issue?

Yeah same issue. Taking a long time.

**Comment by desmarchris** [comment]
@rhazra-003 can you share the traceback / any logs you're seeing when you install with the commands above?

**Comment by rhazra-003** [comment]
This is all what I am getting that I have shared earlier in the screenshot.

**Comment by desmarchris** [comment]
if you are still seeing those same logs, I don't think the commands above worked for your environment or another python environment overrides what you downgraded. Can you try with a fresh virtual environment?

**Comment by rhazra-003** [comment]
I have repeated the procedure in a new conda env. But same issue was there as well.

**Comment by JBOE22175** [comment]
I have exactly the same problem when installing on Windows. Hoping for a solution.

**Comment by rhazra-003** [comment]
Hi @desmarchris , any solution?

**Comment by yzidoun** [comment]
Anybody found a solution for that problem, still can not install rasax

**Comment by tmbo** [comment]
Native installation on windows isn't a supported environment for the current Rasa X release. I'd recommend using docker instead for a reliable installation on windows.
