### ISSUE TITLE
Use an active config.yml file (not commented out)  on new project (`rasa init`) 

### ISSUE THREAD

**Issue by TomV** [RasaHQ/rasa#8976]
**Description of Problem**: Currently, when a new rasa project is initiated with `rasa init`, the config file has no "live" settings, just commented out values that are actually set elsewhere.

This does not make sense to me – there should be one source of truth for configuration settings, it can be single file or a folder with multiple files, but it needs to be a single, central location. Having a single `config.yml` (or a `config` folder) be the single the source of truth for configuration settings would best conform to the [Rule of Least Surprise](https://homepage.cs.uri.edu/~thenry/resources/unix_art/ch11s01.html)

As described in #8975 , the current default values create several UserWarnings. Most of these UserWarnings can be eliminated by updating the config.yml file to values that better match the expectations of the various transformers (DIETClassifier ResponseSelector and TEDPolicy)

However, just uncommenting the config.yml file does not do the job.

**Overview of the Solution**: The solution is to uncomment the config.yml file, and ensure that the settings it contains to not create errors or UserWarnings, when running core rasa commands.

**Examples** (if relevant): The frustrations that happen when running commands on a new rasa project are documented in #8946

**Blockers** (if relevant): Not aware of any blockers, might require a change to the workflow for any changes to individual components that are currently relying their own default values, if those conflict with the settings in the generated `config.yml` file. (They would need to do a pull request to update the config.yml file.)

This starts to make a good case for a config folder rather than a single config file, so that individual components can have their configuration settings in a separate file.

Note: I created #8946 with a proposed value for the default config.yml template.

**Definition of Done**: Creating a new rasa project and running core rasa commands should not emit any errors or UserWarnings.

*   [ ] Tests are added
*   [ ] `.../rasa/cli/initial_project/config.yml` is no longer fully commented out, but generates a clean, live config.yml file in the new project
*   [ ] Feature described the docs
*   [ ] Docs updated to reflect that config.yml IS now the source of truth for all relevant settings, and will override any default settings for a particular component.
*   [ ] Feature mentioned in the changelog

**Comment by sara-tagger** [comment]
Thanks for submitting this feature request 🚀 @alopez will get back to you about it soon! ✨

**Comment by TomV** [comment]
Based on the documentation found here: https://rasa.com/docs/rasa/model-configuration#suggested-config
This is a bigger mess than I originally assessed. 

Specifically, the docs state: 

> You can leave the pipeline and/or policies key out of your configuration file. When you run rasa train, the Suggested Config feature will select a default configuration for the missing key(s) to train the model.

Again this seems wrong to me as an approach.   If the configuration settings are being suggested, they can go in a separate `confg_suggestions.yml` file, that is not used to set any values during run-time.

Just for reference and context, here's the other important part of the documentation that, to me, seems like a "less than best" practice, and probably needs to be re-thought: 
>If you like, you can then un-comment the suggested configuration for one or both of the keys and make modifications. Note that this will disable automatic suggestions for this key when training again. As long as you leave the configuration commented out and don't specify any configuration for a key yourself, a default configuration will be suggested whenever you train a new model.

I'm not sure my suggestions are the right path, but I do believe the current approach needs to re-thought.

**Comment by samsucik** [comment]
I don't know why this belongs to Research and not to Enable. In any case, I personally would make this a discussion issue where we discuss how to make sure that our default configs don't lead to warnings.

**Comment by samsucik** [comment]
Btw initial internal discussion is [here](https://rasa-hq.slack.com/archives/CL3GUUUQ1/p1624549678130300).
