### ISSUE TITLE
Separate logger attached to each Agent

### ISSUE THREAD

**Issue by blenderskool** [RasaHQ/rasa#8991]
**Description of Problem**: Multiple RASA agents when loaded using `Agent.load()` in `rasa.core.agent` seem to share a common logger. It works fine when a single agent is running, but when we load multiple agents in the same program running asynchronously, it's hard to determine which agent logged what. I can't find any issue and forum post similar to this or any suitable workaround for this problem.

**Overview of the Solution**: Addition of an optional `logger` parameter in `Agent.load()` that would be the logger instance used by the agent instead of the shared logger when specified. This would make it easy to figure out which agent logged what. I'm not sure how many changes this would require in the code, but this seemed like a viable approach.

**Definition of Done**:

*   [ ] Tests are added
*   [ ] Feature described the docs
*   [ ] Feature mentioned in the changelog

**Comment by sara-tagger** [comment]
Thanks for submitting this feature request 🚀 @LTY4 will get back to you about it soon! ✨
