### ISSUE TITLE
Add debug output to `rasa test` stories `failed_test_stories.yml`

### ISSUE THREAD

**Issue by rgstephens** [RasaHQ/rasa#9013]
**Description of Problem**: If you run `rasa test` the `failed_test_stories.yml` shows the intent or dialogue point of failure. To diagnose the failure, `rasa shell --debug` can be used to manually walk thru the failed test and see the detailed model & dialogue prediction.

**Overview of the Solution**: Instead of manually running `rasa shell -~~debug` it would be helpful to have an option (`~~-debug`?) that writes the detailed nlu & dialogue messages to the `failed_test_stories.yml` like you would see in the shell debug.

**Comment by TyDunn** [comment]
@alwx this is interesting re: test stories improvements in 3.0

**Comment by rgstephens** [comment]
Any updates on this issue?
