### ISSUE TITLE
Rasa X nlu exports .md file instead of .yml

### ISSUE THREAD

**Issue by randywreed** [RasaHQ/rasa#9014]
**Rasa version**:2.7.1

**Rasa SDK version** (if used & relevant): 2.7.0

**Rasa X version** (if used & relevant):0.37 (local)

**Python version**: 3.6.8

**Operating system** (windows, osx, ...): Centos

**Issue**: When exporting nlu data from rasa-x, the file produced is a markdown file, rather than a yaml file. Give that the nature of this on a local machine is have a backup, it seems odd that it would not save it as the current format. I can only think this is probably an artifact from previous versions that hasn't been updated. 

**Error (including full traceback)**:
```
Rasa-x -> nlu training data -> export
```

**Command or request that led to error**:
```

```

**Content of configuration file (config.yml)** (if relevant):
```yml

```

**Content of domain file (domain.yml)** (if relevant):
```yml

```

**Comment by sara-tagger** [comment]
Thanks for the issue, @koaning will get back to you about it soon!

###### You may find help in the [docs](https://rasa.com/docs/) and the [forum,](https://forum.rasa.com/) too 🤗

**Comment by chdorner** [comment]
Hi @randywreed, we've released a fix for this in 0.39.0. The downloaded file format now depends on the original file and it defaults to YAML.
