### ISSUE TITLE
Rasa-X formatting on mobile phone

### ISSUE THREAD

**Issue by randywreed** [RasaHQ/rasa#9015]
_Rasa version_ :2.7.1

 _Rasa SDK version_ (if used & relevant):

 _Rasa X version_ (if used & relevant):0.39

 _Python version_ :3.6.8

 _Operating system_ (windows, osx, ...):android

 _Issue_ : when accessing rasa-x (guest tester) on a mobile phone, the keyboard will cover the bot response. See this video for an example: [<span class="error">[https://user-images.githubusercontent.com/86683479/124123323-31eac480-da45-11eb-9d40-773d11bb34b2.mp4|| https://user-images.githubusercontent.com/86683479/124123323-31eac480-da45-11eb-9d40-773d11bb34b2.mp4%7C]</span> [https://user-images.githubusercontent.com/86683479/124123323-31eac480-da45-11eb-9d40-773d11bb34b2.mp4](https://user-images.githubusercontent.com/86683479/124123323-31eac480-da45-11eb-9d40-773d11bb34b2.mp4)]

 _Error (including full traceback)_ :

 _Command or request that led to error_ :

 _Content of configuration file (config.yml)_ (if relevant):

 _Content of domain file (domain.yml)_ (if relevant):

**Comment by sara-tagger** [comment]
Thanks for the issue, @jupyterjazz will get back to you about it soon!

###### You may find help in the [docs](https://rasa.com/docs/) and the [forum,](https://forum.rasa.com/) too 🤗

**Comment by m-vdb** [comment]
Closing per https://forum.rasa.com/t/changes-to-the-rasa-x-community-edition-free-version/53650
