### ISSUE TITLE
Finish e2e GPU memory fix

### ISSUE THREAD

**Issue by twerkmeister** [RasaHQ/rasa#9019]
[The prototypical GPU memory fix](https://github.com/RasaHQ/rasa/pull/8746) has been tested and solves the problem that the GPU runs out of memory for large action sets in e2e scenarios.

Implementation issue for #8734

To make it production ready, the following things need to be addressed / Definition of done:

*   [ ] code quality (comments, minor refactorings / renaming)
*   [ ] tests are added for not running into memory problems again
*   [ ] `label_batch_size` should be turned into a boolean variable `balanced_sampling_negative_labels` to remove unnecessary complexity in the interplay between `label_batch_size` and `number_of_negative_examples`
*   [ ] Sampling inside DotProductLossLayer should be unique as well using [uniform_candidate_sampler](https://www.tensorflow.org/api_docs/python/tf/random/uniform_candidate_sampler)

**Comment by m-vdb** [comment]
closing as stale
