### ISSUE TITLE
mypy: Fix `index` 

### ISSUE THREAD

**Issue by twerkmeister** [RasaHQ/rasa#9048]
[Maxime recently enabled `mypy` support for the first couple of issues](https://github.com/RasaHQ/rasa/pull/6511). In our current setup we ignore certain typing issues as there are currently too many to tackle them all at once. 

We should instead tackle them step by step. [Related issue](https://github.com/RasaHQ/rasa/issues/7513). [Parent issue](https://github.com/RasaHQ/rasa/issues/8243).

Current number of issues with this type: 36

**Definition of Done**:
- [ ] enable `mypy` checks for `index`
- [ ] all existing `index` issues are fixed

**Comment by wochinge** [comment]
closed by https://github.com/RasaHQ/rasa/pull/9043
