### ISSUE TITLE
Rasa X delete story intents during conversation (also in UI)

### ISSUE THREAD

**Issue by dadebulba** [RasaHQ/rasa#9059]
_Rasa version_ :

 _Rasa SDK version_ (if used & relevant): 2.7.x

 _Rasa X version_ (if used & relevant): 0.41.x

 _Python version_ : 3.8.x

 _Operating system_ (windows, osx, ...): Ubuntu 18.04

 _Issue_ :

when the user intent is matched with a custom action or a form, the user intent disappears from the UI and from the story.

In the following video, you can see that for sample faq like “tasse” the intent is preserved, while for form actions like “ammissioni” the intents disappear. Also, sometimes, the intent activating the form disappear, so I'm unable to see the user input activating which form and do a proper bot learning.

 _Error (including full traceback)_ :

See this video about the issue: [<span class="error">[https://youtu.be/nYs_qLht-KQ|| https://youtu.be/nYs_qLht-KQ%7C]</span> [https://youtu.be/nYs_qLht-KQ](https://youtu.be/nYs_qLht-KQ)]

 _Forum link_ I asked on forum and they suggested to open a bug report: [<span class="error">[https://forum.rasa.com/t/intents-are-not-registered-on-custom-actions/45424|| https://forum.rasa.com/t/intents-are-not-registered-on-custom-actions/45424%7C]</span> [https://forum.rasa.com/t/intents-are-not-registered-on-custom-actions/45424](https://forum.rasa.com/t/intents-are-not-registered-on-custom-actions/45424)]

 _Source Code_ : [<span class="error">[https://github.com/dadebulba/rasa-bot|| https://github.com/dadebulba/rasa-bot%7C]</span> [https://github.com/dadebulba/rasa-bot](https://github.com/dadebulba/rasa-bot)]

**Comment by sara-tagger** [comment]
Thanks for raising this issue, @koaning will get back to you about it soon✨

###### Please also check out the [docs](https://rasa.com/docs/) and the [forum](https://forum.rasa.com/) in case your issue was raised there too 🤗

**Comment by dadebulba** [comment]
I solved the issue by doing a revert of my commits history, most probably it was related to my code. Anyway, the behavior of removing intents from history and from the UI was quite strange. I don't know if you want to investigate further this bug

**Comment by alexweidauer** [comment]
Thank you for raising this issue about Rasa X. We decided to stop supporting the Community Edition (free version) of ‘Rasa X’ (see more info here: https://rasa.com/blog/rasa-x-community-edition-changes/). That’s why we’ve closed your issue. We suggest that Rasa Enterprise customers raise the issue with our customer support team if they haven’t done so already.
