### ISSUE TITLE
lookup file text in rasa 2.0

### ISSUE THREAD

**Issue by Tamabcxyz** [RasaHQ/rasa#9061]
In nlu.yml file your can format like this:

*   lookup: dn examples: | 
      *   location of file text

dn: is entities hope for help ^^

**Comment by Tamabcxyz** [comment]
hyphen(-) lookup: dn
  examples: |
   hyphen(-) location of file text

**Comment by sara-tagger** [comment]
Thanks for submitting this feature request 🚀 @rctatman will get back to you about it soon! ✨

**Comment by TyDunn** [comment]
@Tamabcxyz What is the problem you are facing?

**Comment by Tamabcxyz** [comment]
No, I don't have any problem. I just support how to config "lookup" a file has extended ".txt" on rasa 2.0. Because I don't see config lookup ".txt" file on rasa document.

**Comment by TyDunn** [comment]
@Tamabcxyz Okay. Let me try rephrasing my question:

1. What is the current way you have to do it?
2. What is the way you would like to be able to do it?
