### ISSUE TITLE
Support spaCy 3.1

### ISSUE THREAD

**Issue by koaning** [RasaHQ/rasa#9068]
SpaCy 3.1 [just got released](https://explosion.ai/blog/spacy-v3-1) and it supports a few new languages and features. It'd make sense for us to update for Rasa 3.0.

**Comment by koaning** [comment]
Related: https://github.com/RasaHQ/rasa/issues/8882

**Comment by TyDunn** [comment]
@koaning are you working on this?

**Comment by koaning** [comment]
It's on my todo. I figured with all the Rasa 3.0 stuff that's happening it was low priority and best delayed but I can pick it up at a moments notice.

**Comment by TyDunn** [comment]
So you would do it as part of 3.0 or no? We should factor it into the action plan, if you intend to it to be in the release

**Comment by koaning** [comment]
Ah, pardon! I should've been more explicit. Yes! 

Let's put it into the release, it shouldn't be too much work. I might be able to wrap it up tomorrow. 

Just to confirm, I can push to master, or should I push to one of the 3.0 branches?

**Comment by TyDunn** [comment]
I think you can just push to `main` but let's double check with @m-vdb

**Comment by m-vdb** [comment]
yes, push to `main`!
