### ISSUE TITLE
Add test to ensure no warnings from default config.

### ISSUE THREAD

**Issue by joejuzl** [RasaHQ/rasa#9078]
The default config should not cause warnings.
Add a test to confirm no warnings are created from the default `rasa init` when training or loading a model.

**Definition of done**
- [ ] Ensure that the default config has no warnings for training and loading a trained model
- [ ] Add a test to ensure no warnings from default config

**Comment by TyDunn** [comment]
As part of this, we should ensure that [Warning related to constrain_similarities shouldn't come up for a new rasa init project since auto-configuration already uses constrain_similarities=True afaik.](https://github.com/RasaHQ/rasa/issues/8945#issuecomment-876400843)

**Comment by joejuzl** [comment]
This is blocked by a warning that will be removed in #8880 (in `MemoizationPolicy`)
