### ISSUE TITLE
Illegal instruction (core dumped) on load/train model

### ISSUE THREAD

**Issue by C4rb0ngit** [RasaHQ/rasa#9081]
**Rasa version**: 2.7.1

Python version**:3.8.10

**Operating system** (windows, osx, ...): ubuntu 20.4 lts (vm)

**Issue**: On loading / training a rasa model it exits with following error

**Error (including full traceback)**: Illegal instruction (core dumped)

**Command or request that led to error**:

**Comment by sara-tagger** [comment]
Thanks for the issue, @desmarchris will get back to you about it soon!

###### You may find help in the [docs](https://rasa.com/docs/) and the [forum,](https://forum.rasa.com/) too 🤗

**Comment by desmarchris** [comment]
@C4rb0ngit can you please post the full traceback?

**Comment by TyDunn** [comment]
Please provide more information and reopen the issue if this is still a problem
