### ISSUE TITLE
Ensure that `UnexpecTEDIntentPolicy` can be run on past conversations from a Rasa Open Source only deployment

### ISSUE THREAD

**Issue by TyDunn** [RasaHQ/rasa#9084]
We have started with [this initial script](https://github.com/RasaHQ/rasa-x/pull/5571) but need to follow through with it.

**Definition of done**
- [ ] Script for applying `unexpectedintentpolicy` to conversations in a Rasa Open Source only deployment
- [ ] Script for applying `unexpectedintentpolicy` to conversations in a Rasa X deployment
- [ ] GitHub gist(s) published and linked in the docs

**Comment by alwx** [comment]
The script is here: https://gist.github.com/alwx/b426b7b573ff963c85c65ea6466528d7

**Comment by m-vdb** [comment]
Link to PR: https://github.com/RasaHQ/rasa-x/pull/5571
