### ISSUE TITLE
`UnexpecTEDIntentPolicy`: Modify standalone script to generate results for multiple tolerance values

### ISSUE THREAD

**Issue by dakshvar22** [RasaHQ/rasa#9128]
**Description of Problem**:
Currently, the [standalone script](https://github.com/RasaHQ/rasa/issues/9084) that is being created does not vary the [`tolerance` parameter](https://rasa.com/docs/rasa/policies#prediction-of-action_unlikely_intent) across a range to show its effect on output warnings. Since we suggest tuning the tolerance parameter when reviewing conversations, it would be easier to do so with the standalone script itself.

**Overview of the Solution**:
Run `rasa test` inside the standalone script not just for one value of `tolerance` specified in the config of the trained model but multiple times for a range of values. This ideally does not need to train a new model everytime. For each unique value of `tolerance` do this:

1. Unpack the model package
2. Modify the configuration of `UnexpecTEDIntentPolicy` to set the `tolerance` parameter to the required value.
3. Pack the model again
4. Run `rasa test`.
5. Store the output in a separate folder.

The user should also be able to specify the minimum tolerance value and maximum tolerance value as command line args.

**Definition of Done**:
- [x] Command line args added
- [x] `rasa test` runs for multiple values of `tolerance` parameter without retraining the model again.

**Comment by kedz** [comment]
A [PR](https://github.com/RasaHQ/rasa-x/pull/5858#event-5165516722) with an updated script which sweeps the tolerance parameter as described above has been been merged into @alwx 's branch off the rasa-x repo. We just need to update the gist and this issue is closed.

**Comment by kedz** [comment]
The [gist](https://gist.github.com/alwx/b426b7b573ff963c85c65ea6466528d7) that is linked in the docs has been updated to reflect the merged PR for doing a tolerance parameter sweep.
