### ISSUE TITLE
Deprecation: gelu activation has been migrated to core TensorFlow, and will be deprecated in Addons 0.13.

### ISSUE THREAD

**Issue by joejuzl** [RasaHQ/rasa#9129]
While working on #9078 I encountered a warning while training from the default project:
```
DeprecationWarning('gelu activation has been migrated to core TensorFlow, and will be deprecated in Addons 0.13.')
```

For some reason this does not show when running it through the CLI, it maybe suppressed.
However this should be fixed and is also blocking the tests where I assert programmatically that there are no warnings.

** Definition of Done **
- [ ] Deprecation warning no longer occurs while training default project

**Comment by alopez** [comment]
@samsucik will this be resolved by the 2.5 upgrade?
@joejuzl how urgently do you need this to be solved?

**Comment by samsucik** [comment]
@alopez yes, but with the entire TF 2.5 thing potentially taking long to be closed off, we might tick this one off separately. Afaik it's just about replacing `tfa.activations.gelu` with `tf.nn.gelu` in the code 🙂

**Comment by alopez** [comment]
assignee: @koernerfelicia 
reviewer: @kedz

**Comment by koernerfelicia** [comment]
Turns out we can't fix this before we've updated our `tensorflow` version, `gelu` was moved from `addons` to `core` in `tensorflow 2.4.0` (see [here](https://github.com/tensorflow/addons/issues/2252))

**Comment by koernerfelicia** [comment]
@joejuzl in the meantime: where exactly are you seeing these warnings? It seems a bit weird bc I thought [this PR](https://github.com/RasaHQ/rasa/pull/8718) suppresses tf warnings in pytest.. Unless you're running the tests from the command line?

**Comment by joejuzl** [comment]
@koernerfelicia I see them when running train programmatically (`rasa.cli.train.run_training`) and capturing warnings using `with pytest.warns`.
It looks like that PR to suppress them is in the `Makefile` so I guess just affects the CI tests?
However it is weird that these warnings don't make it to the CLI when running from there...
