### ISSUE TITLE
Rasa X deployment issues on Debian 10

### ISSUE THREAD

**Issue by georgebrianb** [RasaHQ/rasa#9174]
**Rasa version**: - 

**Rasa SDK version** (if used & relevant): -

**Rasa X version** (if used & relevant): Deploying according to docs - I suppose it's latest version

**Python version**: 3.7.3

**Operating system** (windows, osx, ...): Debian 10

**Issue**: I have tried deploying Rasa X according to the documentation (https://rasa.com/docs/rasa-x/installation-and-setup/installation-guide/)

I'm at my fourth try and the installation gets stuck at "Deploying Rasa X..." 

**Error (including full traceback)**:
Checking the kubernetes pods, it looks like there's a CrashLoopBackOff error on rasa-nginx.
Further checking of the rasa-event-service pod shows the following:

```
bitnami@debian:~$ kubectl logs rasa-event-service-6fc8c56697-6rjt7
Unable to get database revision heads.
DB revision(s) do not match migration scripts revision(s):
DB revision: None
Migration scripts revision: ['652500998f3e']
Database revision does not match migrations' latest, trying again in 4 seconds.
Unable to get database revision heads.
DB revision(s) do not match migration scripts revision(s):
DB revision: None
Migration scripts revision: ['652500998f3e']
Database revision does not match migrations' latest, trying again in 4 seconds.
Unable to get database revision heads.
DB revision(s) do not match migration scripts revision(s):
```

**Command or request that led to error**:
```
curl -s get-rasa-x.rasa.com | sudo bash
```

**Content of configuration file (config.yml)** (if relevant):
```yml

```

**Content of domain file (domain.yml)** (if relevant):
```yml

```

This is the first install of the software on this VM.
The VM is on an ESx.
I have triple checked and I meet all the hardware requirements. There were no previous installs on it. It's a fresh VM.

**Comment by georgebrianb** [comment]
Up!

**Comment by sara-tagger** [comment]
Thanks for raising this issue, @erohmensing will get back to you about it soon✨

###### Please also check out the [docs](https://rasa.com/docs/) and the [forum](https://forum.rasa.com/) in case your issue was raised there too 🤗

**Comment by georgebrianb** [comment]
Any news @erohmensing? :)

**Comment by erohmensing** [comment]
Hi @georgeloring , those logs from the event service are fine -- they are just noting that the event service is waiting for database migrations to finish before starting the server. 

Could you post the error related to the CrashLoopBackoff in rasa-nginx?
