### ISSUE TITLE
Rasa 3.0 Architecture Revamp: ModelStorage

### ISSUE THREAD

**Issue by joejuzl** [RasaHQ/rasa#9177]
**Background**:
Context [here](https://www.notion.so/rasa/Rasa-Open-Source-3-0-Architecture-Implementation-Proposal-51ab90b05c41435ca98189a101676a1e).

**Description**:
This ticket covers implementing what is needed for graph components to persist and load data.

- `ModelStorage`: Allows components to write and read data. Packs and unpacks a model.
- `Resource`: A reference to a saveable or loadable place. Passed between components.

**Definition of Done**:
- [ ] Entities are implemented.
- [ ] Entities are unittested.
- [ ] Entities are functionally tested using test components.

**Comment by wochinge** [comment]
closed by https://github.com/RasaHQ/rasa/pull/9233
