### ISSUE TITLE
Rasa 3.0 Architecture Revamp: Caching and fingerprinting

### ISSUE THREAD

**Issue by joejuzl** [RasaHQ/rasa#9178]
**Background**:
Context [here](https://www.notion.so/rasa/Rasa-Open-Source-3-0-Architecture-Implementation-Proposal-51ab90b05c41435ca98189a101676a1e).

**Description**:
This covers the elements that allow graphs to fingerprint and cache their outputs.
This does not cover the pruning of the graph after a fingerprint run.

- `Cache`: Interface for the cache.
- `LocalCache`: Local disk implementation of `Cache`
- `FingerprintCalculator`: Calculates node run fingerprints.
- `GraphFingerprintComponent`: Replaces a `GraphComponent` during a fingerprint run.
- `CachedComponent`: Replaces a `GraphComponent` so as to use a cached output.
- `Cacheable`: Interface for `GraphComponent` output which is cacheable.
- `GraphComponentTrainingOuput`:  Interface for `GraphComponent` output which is fingerprintable.
- `CachingHook`: Implementation of `GraphNodeHook` that enables caching during a training run.

**Definition of Done**:
- [ ] Entities are implemented.
- [ ] Entities are unittested.
- [ ] Entities are functionally tested using test components.

**Comment by wochinge** [comment]
implemented `Cache` / `LocalCache` (didn't use an interface for now as we don't have other subclasses atm) and `Cacheable` on `3.0-architecture-revamp/9178/caching`. Will probably focus on integrating the `ModelStorage` with your branch tomorrow before continuing the cache stuff (somewhat builds on `ModelStorage`)
