### ISSUE TITLE
Create a migration guide for moving config from 2.8 to 3.0.

### ISSUE THREAD

**Issue by kedz** [RasaHQ/rasa#9186]
**Description of Problem**:
3.0 will be the first release with a bunch of deprecated tokenizer, featurizer, and policy components removed. We should create a migration guide section for 2.8 -> 3.0 with before and after configs showing how to get equivalent behavior with the current 3.0 components and config.

**Overview of the Solution**:
The following components have migration guide sections:
 - Policies
   - FormPolicy
   - MappingPolicy
   - FallbackPolicy
   - TwoStageFallbackPolicy
   - SklearnPolicy 
 - Featurizers
   - HFTransformersNLP
 - Tokenizers
   - LanguageModelTokenzier
   - ConveRTTokenizer

**Examples** (if relevant):
See examples of earlier migration guides [here](https://rasa.com/docs/rasa/migration-guide#rasa-27-to-28).

**Blockers** (if relevant):
We have not yet finalized what 3.0 configs look like.

**Definition of Done**:
- [ ] Migration guide sections are added to docs pages.
- [ ] Maybe we should break this into smaller issues?
- [ ] Does CSE have to review any changes we make to docs?
- [ ] Can we copy the migration guides for when these items were deprecated?
- [ ] Does this issue involve testing the migrations or is it just docs updates? likely just docs update
- [ ] Can we coordinate this as part of 3.0 action plan?

**Comment by kedz** [comment]
This issue was created based on a discussion [here](https://github.com/RasaHQ/rasa/pull/9120#discussion_r674032130).

**Comment by samsucik** [comment]
As far as I can see, this is mostly about taking parts of the minor-version migration steps (e.g. 2.1.0->2.2.0) already written in the migration guide, and compiling a chunk that will be part of the major-version migration guide (2.x->3.0)? I guess there shouldn't exist anything that we now removed that wasn't already deprecated and accompanied with existing migration guide content...

**Comment by alopez** [comment]
Covered by this part of the 3.0 plan:
https://www.notion.so/rasa/Ensure-documentation-of-manual-steps-for-2-x-3-x-migration-550b58ca620f4b2082ef255507d32fe7
