### ISSUE TITLE
Adding Instagram channel support

### ISSUE THREAD

**Issue by Horizon733** [RasaHQ/rasa#9197]
**Description of Problem**:

Right now, Instagram has launched support for Instagram API and we can use messaging inside it. So, why not add this feature of connection since it is free and almost similar to Facebook.

**Overview of the Solution**:

A connector that can send the following messages:

*   Text
*   Image
*   Video
*   Generic template(Carousels)
*   Quick reply
*   Stickers (currently: heart)
*   React on message
*   Send a message when commented on any post So currently, I am developing this connector and have achieved Text, Image, Quick Reply, and stickers messages. Below are some snapshots I took.

**Examples** (if relevant):

*   Image and Text Messages: [<span class="image-wrap" style="">![](https://user-images.githubusercontent.com/57827233/126890832-476fae0e-0c02-4ca0-87af-047080b2a54d.png)</span>](https://user-images.githubusercontent.com/57827233/126890832-476fae0e-0c02-4ca0-87af-047080b2a54d.png)
*   Quick Reply: [<span class="image-wrap" style="">![](https://user-images.githubusercontent.com/57827233/126890847-f03dae26-57a1-49ca-82b0-3f0d7ed8bfb8.png)</span>](https://user-images.githubusercontent.com/57827233/126890847-f03dae26-57a1-49ca-82b0-3f0d7ed8bfb8.png)
*   Sticker message [<span class="image-wrap" style="">![](https://user-images.githubusercontent.com/57827233/126890850-dc39829a-74d6-41ec-8ef7-33a92c0af94e.png)</span>](https://user-images.githubusercontent.com/57827233/126890850-dc39829a-74d6-41ec-8ef7-33a92c0af94e.png)

**Definition of Done**:

Let me know the procedure for finalizing. Also, this page is in test mode so if the team want to test this let me know will do the needful

**Comment by sara-tagger** [comment]
Thanks for submitting this feature request 🚀 @mvielkind will get back to you about it soon! ✨
