### ISSUE TITLE
Domain._initialize_forms takes in only dict, but calling function may pass in a list, causing an error.

### ISSUE THREAD

**Issue by ivanmkc** [RasaHQ/rasa#9198]
Domian.*init* takes a List for `forms` parameter but passes it to `_initialize_forms` which cannot take a list.

[https://github.com/RasaHQ/rasa/blob/08bf76bd70cc58784556e69c60b03570149f1119/rasa/shared/core/domain.py#L604| https://github.com/RasaHQ/rasa/blob/08bf76bd70cc58784556e69c60b03570149f1119/rasa/shared/core/domain.py#L604]

**Comment by sara-tagger** [comment]
Thanks for raising this issue, @amn41 will get back to you about it soon✨

###### Please also check out the [docs](https://rasa.com/docs/) and the [forum](https://forum.rasa.com/) in case your issue was raised there too 🤗

**Comment by m-vdb** [comment]
Closing as stale
