### ISSUE TITLE
Building docker image of Rasa failed with MacBook Air M1

### ISSUE THREAD

**Issue by williammo** [RasaHQ/rasa#9199]
**Rasa version**: 2.8.1 **Rasa SDK version** (if used & relevant): NA **Rasa X version** (if used & relevant): NA **Python version**: Python 3.8.2 **Operating system** (windows, osx, ...): macOS 11.4 (Apple M1) **Issue**: Building docker image failed with macOS 11.4 (Apple M1). Docker version 20.10.7, build f0df350.

**Error (including full traceback)**:

## (venv) moyun@192 rasa % make build-docker export IMAGE_NAME=rasa && 

 docker buildx use default && 
 docker buildx bake -f docker/docker-bake.hcl base && 
 docker buildx bake -f docker/docker-bake.hcl base-poetry && 
 docker buildx bake -f docker/docker-bake.hcl base-builder && 
 docker buildx bake -f docker/docker-bake.hcl default <span class="error">[+]</span> Building 4.4s (11/11) FINISHED => <span class="error">[internal]</span> load build definition from Dockerfile.base 0.0s => => transferring dockerfile: 792B 0.0s => <span class="error">[internal]</span> load .dockerignore 0.0s => => transferring context: 34B 0.0s => <span class="error">[internal]</span> load metadata for docker.io/library/ubuntu:20.04 4.3s => <span class="error">[auth]</span> library/ubuntu:pull token for registry-1.docker.io 0.0s => <span class="error">[1/5]</span> FROM docker.io/library/ubuntu:20.04@sha256:b3e2e47d016c08b3396b5ebe06ab0b711c34e7f37b98c9d37abe794b71cea0a2 0.0s => CACHED <span class="error">[2/5]</span> RUN apt-get update -qq && apt-get install -y --no-install-recommends python3 python3-venv python3-pip python3-dev libpq-dev curl && apt-get autoremove -y 0.0s => CACHED <span class="error">[3/5]</span> RUN apt-get update && apt-get dist-upgrade -y --no-install-recommends 0.0s => CACHED <span class="error">[4/5]</span> RUN update-alternatives --install /usr/bin/python python /usr/bin/python3 100 && update-alternatives --install /usr/bin/pip pip /usr/bin/pip3 100 0.0s => CACHED <span class="error">[5/5]</span> RUN useradd -rm -d /app -s /sbin/nologin -g root -u 1001 rasa && groupadd -g 1001 rasa 0.0s => exporting to image 0.0s => => exporting layers 0.0s => => writing image sha256:f86a981ce65875efab385e6fdf9ab304279dc0ec1ca8246005c189b1648a5d9c 0.0s => => naming to docker.io/library/rasa:base-localdev 0.0s => exporting cache 0.0s => => preparing build cache for export 0.0s <span class="error">[+]</span> Building 4.5s (4/4) FINISHED => <span class="error">[internal]</span> load build definition from Dockerfile.base-poetry 0.0s => => transferring dockerfile: 351B 0.0s => <span class="error">[internal]</span> load .dockerignore 0.0s => => transferring context: 34B 0.0s => ERROR <span class="error">[internal]</span> load metadata for docker.io/library/rasa:base-localdev 4.4s => <span class="error">[auth]</span> library/rasa:pull token for registry-1.docker.io 0.0s

> <span class="error">[internal]</span> load metadata for docker.io/library/rasa:base-localdev:

*   * *

error: failed to solve: rpc error: code = Unknown desc = failed to solve with frontend dockerfile.v0: failed to create LLB definition: pull access denied, repository does not exist or may require authorization: server message: insufficient_scope: authorization failed make: *** <span class="error">[build-docker]</span> Error 1

[<span class="image-wrap" style="">![](https://user-images.githubusercontent.com/6015713/126917272-b3c5800f-5003-4270-9a8c-775aa7448600.png)</span>](https://user-images.githubusercontent.com/6015713/126917272-b3c5800f-5003-4270-9a8c-775aa7448600.png)

**Command or request that led to error**:

make build-docker

**Content of configuration file (config.yml)** (if relevant):

<pre>NA</pre>

**Content of domain file (domain.yml)** (if relevant):

<pre>NA</pre>

**Comment by sara-tagger** [comment]
Thanks for the issue, @alopez will get back to you about it soon!

###### You may find help in the [docs](https://rasa.com/docs/) and the [forum,](https://forum.rasa.com/) too 🤗

**Comment by koaning** [comment]
In general the new M1 chips have issues with Tensorflow and Docker.

Can you confirm that you can; 

1. Run basic Python based docker containers locally? 
2. Run a Tensorflow container locally?

**Comment by rgstephens** [comment]
I think we're getting closer on this issue. Updates on this [forum thread](https://forum.rasa.com/t/apple-m1-illegal-hardware-instruction-using-any-rasa-command/37946/39)

**Comment by rgstephens** [comment]
I tried building `3.0.1` to see how far I would get.

## h5py

The first issue I ran into was with the `h5py` module on the M1. This [workaround](https://stackoverflow.com/a/67634217/893278) worked for me but it looks like poetry has no equivalent to the pip `--no-binary` option.  I was able to generate a pip `requirements.txt`, then added the `--no-binary` option to three lines in the file and the pip based install got me past the `h5py` failure.

```bash
brew install hdf5
export HDF5_DIR=/opt/homebrew/Cellar/hdf5/1.12.0_4
poetry export --without-hashes --format requirements.txt --output requirements.txt
# cached-property==1.5.2 --no-binary=h5py
# h5py==3.1.0 --no-binary=h5py
# numpy==1.19.5 --no-binary=h5py
python -m pip install --force-reinstall -r requirements.txt
```

## numpy / spacy

The next issue was `numpy`. Version 1.19.5 does not run on the M1 but 1.21 does work. There's a lengthy discussion about using earlier numpy release and spacy [here](https://github.com/explosion/spaCy/issues/7962) but I have not tried this. Unfortunately, 1.21 is not supported with TensorFlow 2.6 (but it is supported under 2.7).

**Comment by khalo-sa** [comment]
I managed to create an ARM-compatible Rasa Docker Image, and documented the steps here: https://github.com/khalo-sa/rasa-apple-silicon
