### ISSUE TITLE
Support for XLM-R in the HuggingFace pipeline.

### ISSUE THREAD

**Issue by akashzapr** [RasaHQ/rasa#9207]
**Description of Problem**: Hi,

We have been working on a chatbot with capabilities to interact with users in regional languages. For this, we felt XLM-R is a great model to use in the pipeline. However, the HuggingFace pipeline in RASA doesn't currently offer support for XLM-R. So, it would be great to have support for it.

**Overview of the Solution**: We've made a few changes to hugging_face package to include support for XLM-R. We've been using it for a couple of months now and it seems to work reasonably well.

**Blockers** (if relevant): We currently have a custom install script which we run while setting up the dev environment for our bots to use our custom RASA. It basically installs torch (for XLM-R), and transformers 3.0.0 (in our exploration, this was the only version of transformers that worked well with XLM-R and RASA), and uninstalls typing if it exists (seems to cause issues while training).

In order to make it a proper solution, it would certainly be better to integrate these into the poetry installation that happens in RASA. We would love to collaborate with you for this to get a better understanding of the impact of these changes.

**Definition of Done**: What needs to be there to consider this feature as done?

*   [ ] Modify the poetry dependencies.
*   [ ] Tests (Need help to figure out if we have any existing tests for the HF module, or if it's necessary at all.)
*   [ ] Doc changes.
*   [ ] Feature mentioned in the changelog

**Comment by sara-tagger** [comment]
Thanks for submitting this feature request 🚀 @mvielkind will get back to you about it soon! ✨
