### ISSUE TITLE
RedisLockStore don't tread safe 

### ISSUE THREAD

**Issue by DavidBeTea** [RasaHQ/rasa#9213]
Rasa Version     : 2.4.3
Rasa SDK Version : 2.4.1
Rasa X Version   : None
Python Version   : 3.7.10
Operating System : Linux-5.4.0-66-generic-x86_64-with-debian-buster-sid
Python Path      : /home/david/software/anaconda/bin/python

If I have two rasa server A,B 
user Tom send 2 msg, first sentence is call A server, second sentence call B server. 
```
 async def _acquire_lock(
        self, conversation_id: Text, ticket: int, wait_time_in_seconds: float
    ) -> TicketLock:
        logger.debug(f"Acquiring lock for conversation '{conversation_id}'.")
        while True:
            # fetch lock in every iteration because lock might no longer exist
            lock = self.get_lock(conversation_id)

            # exit loop if lock does not exist anymore (expired)
            if not lock:
                break

            # acquire lock if it isn't locked
            if not lock.is_locked(ticket):
                logger.debug(f"Acquired lock for conversation '{conversation_id}'.")
                return lock

            logger.debug(
                f"Failed to acquire lock for conversation ID '{conversation_id}'. "
                f"Retrying..."
            )

            # sleep and update lock
            await asyncio.sleep(wait_time_in_seconds)
            self.update_lock(conversation_id)

        raise LockError(
            f"Could not acquire lock for conversation_id '{conversation_id}'."
        )
```
in this code, if 2 sentence call the function "self.get_lock(conversation_id)" in the same time. 
and then, the wired things happen, they will "self.update_lock(conversation_id)", so the sentence order is not right. 

so, I think you guys don't using the rasa locker, can't make sure the sentence is in ordered in this code. 
Is that right?

**Comment by sara-tagger** [comment]
Thanks for the issue, @koernerfelicia will get back to you about it soon!

###### You may find help in the [docs](https://rasa.com/docs/) and the [forum,](https://forum.rasa.com/) too 🤗

**Comment by koernerfelicia** [comment]
Hi @DavidBeTea, this seems like a question rather than a bug or feature request -- would be great if you could ask these in the [forum](https://forum.rasa.com/) instead. `RedisLockStore` is indeed not thread-safe, but the scenario you described isn't realistic, a conversation with a model would be had with a single server (so Tom's utterance would only go to server A). If you have further questions about how `RedisLockStore` works, please ask them in the forum! Thank you :)
