### ISSUE TITLE
Wrap up `tensorflow-addons` PR #1935 CRF: Add scores for decoded tags to crf_decode

### ISSUE THREAD

**Issue by koernerfelicia** [RasaHQ/rasa#9232]
**Description of Problem**: We currently implement our own custom CRF code (see [here](https://github.com/RasaHQ/rasa/blob/main/rasa/utils/tensorflow/crf.py)) in order to be able to get scores for decoded entity tags. Tanja made a PR [here](https://github.com/tensorflow/addons/pull/1935) to merge this code into `tensorflow-addons`'s repository, but wasn't able to wrap it up before leaving.

**Overview of the Solution**: We should wrap up the PR and aim to get it merged, so that we can drop our custom implementation. This _may_ fix our performance issues with custom CRF code, which is currently blocking the upgrade to TF 2.5 (see discussion [here](https://github.com/RasaHQ/rasa/issues/7619) and [here](https://rasa-hq.slack.com/archives/C8LEHMTAM/p1627487435180200?thread_ts=1627459760.169600&cid=C8LEHMTAM)).

Dropping our custom implementation will mean we no longer have to maintain it and no longer have to worry about keeping it current with `tensorflow-addons`.

**Definition of Done**:

*   [ ] PR is brought up to speed with the current `tensorflow-addons` version
*   [ ] Comments from reviewers are addressed, incl. tests written
*   [ ] PR is merged
*   [ ] A new issue was created to drop our custom code and instead use the merged code from `tensorflow-addons`

**Comment by TyDunn** [comment]
@koernerfelicia we determined that this was not blocking the TF2.5 upgrade, correct?

**Comment by koernerfelicia** [comment]
@TyDunn yep.
