### ISSUE TITLE
Conflicting documentation regarding stories starting only with intents

### ISSUE THREAD

**Issue by sebcalbaza-kbc-be** [RasaHQ/rasa#9235]
**Rasa version**: 2.6.2

**Python version**: 3.7.10

**Issue**:

The checkpoints Note section from [https://rasa.com/docs/rasa/stories#checkpoints](https://rasa.com/docs/rasa/stories#checkpoints) suggests that stories can start only with an intent, but [https://rasa.com/docs/rasa/writing-stories#creating-logical-breaks-in-stories](https://rasa.com/docs/rasa/writing-stories#creating-logical-breaks-in-stories) examples contradict this.

**Comment by sara-tagger** [comment]
Thanks for the issue, @alopez will get back to you about it soon!

###### You may find help in the [docs](https://rasa.com/docs/) and the [forum,](https://forum.rasa.com/) too 🤗

**Comment by samsucik** [comment]
Sounds like a super-quick one to resolve -- I think only the note in the first linked docs page needs to change.
