### ISSUE TITLE
input values from MS Teams are not working

### ISSUE THREAD

**Issue by dx111ge** [RasaHQ/rasa#9240]
**Description of Problem**: I would like to use the input fields from MS teams adaptiveCards

**Overview of the Solution**: add the value dictionary (contains the fields and values) to the metadata

line 215 - botframework.py

@botframework_webhook.route("/webhook", methods=<span class="error">["POST"]</span>) async def webhook(request: Request) -> HTTPResponse: postdata = request.json metadata = self.get_metadata(request) if metadata is None: metadata =

 {'name' : None} 

metadata<span class="error">['name']</span>=postdata<span class="error">['from']</span><span class="error">['name']</span>

**if "value" in postdata: metadata.update(postdata<span class="error">["value"]</span>)**

metadata_with_attachments = self.add_attachments_to_metadata( postdata, metadata )

add the bold statement and it is done

**Comment by dx111ge** [comment]
if "value" in postdata:
        metadata.update(postdata["value"])

**Comment by sara-tagger** [comment]
Thanks for submitting this feature request 🚀 @JustinaPetr will get back to you about it soon! ✨

**Comment by dx111ge** [comment]
did not hear anything back
