### ISSUE TITLE
Automated evaluation pipeline for internal use

### ISSUE THREAD

**Issue by dakshvar22** [RasaHQ/rasa#9252]
**Description of Problem**:
We want to setup an automated pipeline for the research team to make progress on evaluating assistants.
You can find more details on the scope in this [notion doc](https://www.notion.so/rasa/Automated-pipeline-for-bot-evaluation-4cf999e5d270433399ab4e3156e211f4).
The GH issue is to track progress on the proposal.

**Overview of the Solution**:
There's one suggested inside the notion document but input from infra team will be highly appreciated.

**Note**: This is a big enabler for a couple of projects that the research team is planning to work on, namely validating E2E, so it would be helpful to take this up as soon as possible (of course without sacrificing anything else that the infrastructure team is already doing 😄 )

**Comment by virtualroot** [comment]
The proposal has a green light. 🟢 
https://github.com/RasaHQ/rasa-x/issues/5907
