### ISSUE TITLE
Generating secrets with openssl as recommened can create invalid tokens

### ISSUE THREAD

**Issue by peter-wimsey** [RasaHQ/rasa#9258]
**Rasa version**:

2.8.0-full

**Rasa X version**:

0.42.0

**Python version**:

3.8

**Operating system**:

GNU/Linux

**Issue**:

The [docs](https://rasa.com/docs/rasa-x/installation-and-setup/install/docker-compose/#docker-environment-file) suggest using `openssl` to create the secrets in the .env file. However, if `RASA_X_TOKEN` happens to contain a plus sign authorization will fail.

See [https://forum.rasa.com/t/rasa-x-does-not-connect-to-production-worker-hosts/24801/25](https://forum.rasa.com/t/rasa-x-does-not-connect-to-production-worker-hosts/24801/25)

**Error**:

rasa-worker_1 | Starting Rasa X in production mode... 
 <g-emoji class="g-emoji" alias="rocket" fallback-src="https://github.githubassets.com/images/icons/emoji/unicode/1f680.png">
 🚀 
 </g-emoji> rasa-worker_1 | Could not fetch runtime config from server at '[http://rasa-x:5002/api/config?token=IBll3C+0TIY4JoE0bSiHWQ==](http://rasa-x:5002/api/config?token=IBll3C+0TIY4JoE0bSiHWQ==)'. Exiting.

**Command or request that led to error**:

for s in RASA_TOKEN RASA_X_TOKEN PASSWORD_SALT JWT_SECRET RABBITMQ_PASSWORD DB_PASSWORD REDIS_PASSWORD do echo "$

 {s} 

=$(openssl rand -base64 16)" >> .env done

**Comment by sara-tagger** [comment]
Thanks for raising this issue, @JustinaPetr will get back to you about it soon✨

###### Please also check out the [docs](https://rasa.com/docs/) and the [forum](https://forum.rasa.com/) in case your issue was raised there too 🤗

**Comment by m-vdb** [comment]
Closing as stale
