### ISSUE TITLE
Adding support of telegram `parse_mode` argument

### ISSUE THREAD

**Issue by MikhaelSorkin** [RasaHQ/rasa#9260]
**Description of Problem**:

Today there is no native support of `parse_mode` argument for telegram channel. So if we need markdown in utters (e.g. for hyperlinks), we must use some workarounds with custom output payload([https://github.com/RasaHQ/rasa/issues/3750#issuecomment-506579280](https://github.com/RasaHQ/rasa/issues/3750#issuecomment-506579280))

This workaround solves the problem but makes harder to use another rasa features. As an example, buttons: We can't define parse_mode in `custom` section and define buttons near (because of [this logic](https://github.com/RasaHQ/rasa/blob/08bf76bd70cc58784556e69c60b03570149f1119/rasa/core/channels/channel.py#L228)):

<pre> utter_test:

*   custom:
     text: sample
     parse_mode: markdown
     buttons:
*   title: 'yes'
     payload: /yes_btn
*   title: 'no'
     payload: /no_btn</pre>

Instead, we need to define buttons in `custom` section via `reply_markup` - special telegram field that contains json <span class="error">[!/images/icons/emoticons/smile.png!| /images/icons/emoticons/smile.png]</span> :

<pre> utter_test:

*   custom:
     text: sample
     parse_mode: markdown
     reply_markup: '`"inline_keyboard": [[{{"text": "yes", "callback_data": "/yes_btn"`,
     `"text": "no", "callback_data": "/no_btn"`]]}}'</pre>

As a result we have complex and fragile utter definition.

Also, this workaround complicates utters usage in custom actions. We need to detect current input channel to invoke utter_message with correct arguments:

<pre>input_channel = tracker.get_latest_input_channel()
 if input_channel == "telegram":
 dispatcher.utter_message(json_message=create_custom_telegram_message(response_text, buttons))
 else:
 dispatcher.utter_message(text=response_text,
 buttons=[

 {"title": button.title, "payload": button.payload} 

 for button in buttons])</pre>

So, without native support there is no convient way to use `parse_mode` and buttons at the same time.

**Overview of the Solution**:

`parse_mode` in utter definition. (e.g. near variable `button_type`: [https://rasa.com/docs/rasa/connectors/telegram#supported-response-attachments](https://rasa.com/docs/rasa/connectors/telegram#supported-response-attachments))

**Examples** (if relevant):

**Blockers** (if relevant):

**Definition of Done**:

**Comment by sara-tagger** [comment]
Thanks for submitting this feature request 🚀 @alopez will get back to you about it soon! ✨
