### ISSUE TITLE
Explain `rasa test nlu --cross-validation` results better in documentation

### ISSUE THREAD

**Issue by melindaloubser1** [RasaHQ/rasa#9263]
**Description of Problem**: The output of `rasa test nlu` is explained in [these docs](https://rasa.com/docs/rasa/testing-your-assistant#intent-classifiers). However it doesn't distinguish between results from a split test set, vs. results from cross-validation. Confusingly, the reported average results at the end of cross validation **do not match** the output files, because they reflect an average of reported scores per fold, while the files reflect a recalculation of all metrics based on the individual predictions of each fold

**Overview of the Solution**: Add a section to the docs explaining the output of `rasa test nlu --cross-validation` and how the logged metrics vs. file metrics are calculated.

**Blockers** (if relevant): none

**Definition of Done**:

*   [ ] Documentation updated

**Comment by DARK-art108** [comment]
Can I work Upon this @melindaloubser1 ?

**Comment by melindaloubser1** [comment]
If you feel like you understand the problem and what needs to be documented then go for it! 😃
