### ISSUE TITLE
RASA X running issue: Make sure to start Rasa X with valid data and valid domain and config files

### ISSUE THREAD

**Issue by SmitTailor** [RasaHQ/rasa#9270]
![image](https://user-images.githubusercontent.com/88365586/128304443-07c817b4-2494-44fe-a769-35213651b2fa.png)
I am trying to installing **Rasa**. I run this command **rasa init**. It's working fine. But when I am trying to run this command **rasa x** it throws an error as shown in the above image(link). One solution I have found is to remove **domain_path=domain_path** from the **x.py** file which can be found in such a path: **C:\Users\Admin\anaconda3\envs\Myenv\Lib\site-packages\rasa\cli\x.py** . Even though the other solution I've heard is to downgrade the version of Python and pip. Versions are (Rasa Version: 2.8.1, Python Version:3.7, pip version: 20.2) But still, I can't get rid of it. If anybody has a solution, please help.

**Comment by sara-tagger** [comment]
Thanks for raising this issue, @mvielkind will get back to you about it soon✨

###### Please also check out the [docs](https://rasa.com/docs/) and the [forum](https://forum.rasa.com/) in case your issue was raised there too 🤗

**Comment by SmitTailor** [comment]
To solve this issue, please follow the below steps:

pip install rasa==2.8.1

check rasa --version

then install

pip install rasa-sdk==2.8.1

Install this version rasa-x==0.39.3

pip install rasa-x==0.39.3 --extra-index-url https://pypi.rasa.com/simple

Some know errors:

ImportError: cannot import name ‘RowProxy’ from ‘sqlalchemy.engine’ try running pip install SQLAlchemy==1.3.22 should fix it.)

And, if you get an error not being able to import yaml then run pip install pyyaml.
