### ISSUE TITLE
Implement `Recipe` to convert current config to `GraphSchema`

### ISSUE THREAD

**Issue by wochinge** [RasaHQ/rasa#9277]
**Overview of the Solution**:
Implement the `Recipe` class which converts the current config to a train and predict `GraphSchema` using the given CLI params. This component loads all the classes and uses the  `@DefaultV1.register(...)` decorator to create the graph structure from it.

See the [implementation proposal](https://www.notion.so/rasa/Rasa-Open-Source-3-0-Architecture-Implementation-Proposal-51ab90b05c41435ca98189a101676a1e) for further details.

**Blockers** (if relevant):
Existing components needs to be adapted to new graph interface.

**Definition of Done**:
- [ ] Recipe is tested with different configurations (default configuration, configurations with custom components / policies, auto configuration)
- [ ] `Recipe` interface is implemented
- [ ] all default Rasa Open Source components / policies are decorated with the `@DefaultV1.register(...)`
- [ ] the configuration is validated
    - Check pipeline is not empty
    - Checks only one tokenizer is present

**Comment by wochinge** [comment]
We could consider omitting Duckling (and other pretrained extractors) from the `train_graph` 🤔 See https://github.com/RasaHQ/rasa/issues/3389#issuecomment-887308951

**Comment by wochinge** [comment]
omit e2e featurization when we only train a core model

**Comment by m-vdb** [comment]
@wochinge and @joejuzl to split this issue

**Comment by wochinge** [comment]
Moved this back to `Backlog` as the core functionality is implemented but now have to until all things have been changed to be `GraphComponents` before wrapping this up
