### ISSUE TITLE
Create issues for new graph components for 3.0 revamp

### ISSUE THREAD

**Issue by TyDunn** [RasaHQ/rasa#9281]

**Comment by wochinge** [comment]
cc @TyDunn 

Crucial:
* [`NLUMessageConverter`](https://github.com/RasaHQ/rasa/issues/9326)
* [`NLUPredictionToHistoryAdder`](https://github.com/RasaHQ/rasa/issues/9327)
* [`RegexClassifier`](https://github.com/RasaHQ/rasa/issues/9328)
* [`ProjectProvider`](https://github.com/RasaHQ/rasa/issues/9329)
* [`NLUTrainingDataProvider`](https://github.com/RasaHQ/rasa/issues/9330)
* [`StoryGraphProvider`](https://github.com/RasaHQ/rasa/issues/9331)
* [`DomainProvider`](https://github.com/RasaHQ/rasa/issues/9332)
* [`DomainWithoutResponsesProvider`](https://github.com/RasaHQ/rasa/issues/9333)

Can be done a bit later:
* [`FineTuningValidator`](https://github.com/RasaHQ/rasa/issues/9335)
* [`ConfigValidator`](https://github.com/RasaHQ/rasa/issues/9336)
