### ISSUE TITLE
Luna

### ISSUE THREAD

**Issue by Lunawatkins** [RasaHQ/rasa#9295]
**Rasa version**:

**Rasa SDK version** (if used & relevant):

**Rasa X version** (if used & relevant):

**Python version**:

**Operating system** (windows, osx, ...):

**Issue**:

**Error (including full traceback)**:
```

```

**Command or request that led to error**:
```

```

**Content of configuration file (config.yml)** (if relevant):
```yml

```

**Content of domain file (domain.yml)** (if relevant):
```yml

```

**Comment by Lunawatkins** [comment]
Good

**Comment by sara-tagger** [comment]
Thanks for the issue, @jupyterjazz will get back to you about it soon!

###### You may find help in the [docs](https://rasa.com/docs/) and the [forum,](https://forum.rasa.com/) too 🤗

**Comment by jupyterjazz** [comment]
Hi @Lunawatkins,
can you please describe what kind of a bug you have or else I'm gonna close this issue.
