### ISSUE TITLE
Upgrade to Sanic 21.6.0

### ISSUE THREAD

**Issue by twerkmeister** [RasaHQ/rasa#9315]
**Description of Problem**: Sanic needs to be upgrade to address #9167\. Until recently the `pytest-sanic` dependency was blocking this upgrade. This block has been resolved.

The following is largely a list of things that needed to be done for upgrading sanic in `rasa-sdk`. As rasa oss is more complex, potentially other steps need to be taken as well.

**Definition of Done**:

*   [ ] `sanic` is upgraded to `^21.6.0`
*   [ ] `sanic-testing` is added as a dev dependency
*   [ ] `pytest-sanic` is upgraded to `^1.8.1`
*   [ ] `sanic-cors` is upgraded to `^1.0.0` (there's a naming conflict here as the new package name is upper cased - needed to delete the `sanic-cors` line by hand first when doing the upgrade in `rasa-sdk`. Why `sanic-cors` needs updating: [https://community.sanicframework.org/t/handle-request-exception-after-upgrading-from-20-9-1-to-21-3/835](https://community.sanicframework.org/t/handle-request-exception-after-upgrading-from-20-9-1-to-21-3/835)
*   [ ] `Sanic.test_mode = True` needs to be added in `tests/conftest.py`
*   [ ] `rasa-sdk` dependency is updated to a version that uses sanic 21.6.0 too (potentially the branch intermittently or a v 3.0 release candidate or sth like that)

**Comment by m-vdb** [comment]
This is now done
