### ISSUE TITLE
Installing Rasa-X with quick install script stucks in loop

### ISSUE THREAD

**Issue by checker21** [RasaHQ/rasa#9316]
_Rasa X version_ (if used & relevant): latest

 _Python version_ : Python 3.8.10

 _Operating system_ (windows, osx, ...): Ubuntu 20.04 LTS in multipass

 _Issue_ : Rasa-x installation with quick install script stucks in loop. Many pods fail to start. The reasons seems to be that the postgresql pod has no access to create a persistent store. This might be due to the non-root nature of the bitnami container. What to do?

 _Error (including full traceback)_ :

 !<span class="error">[Screenshot 2021-08-09 at 09 10 22]</span>([https://user-images.githubusercontent.com/1275995/128832471-f32389de-de7b-4208-b8b7-76b494088794.png](https://user-images.githubusercontent.com/1275995/128832471-f32389de-de7b-4208-b8b7-76b494088794.png))
 !<span class="error">[Screenshot 2021-08-09 at 09 12 13]</span>([https://user-images.githubusercontent.com/1275995/128832490-26aab24a-34a5-4c26-aa32-518bff8ca5af.png](https://user-images.githubusercontent.com/1275995/128832490-26aab24a-34a5-4c26-aa32-518bff8ca5af.png))

 _Command or request that led to error_ :

 curl -s get-rasa-x.rasa.com | sudo bash

**Comment by sara-tagger** [comment]
Thanks for raising this issue, @ArjaanBuijk will get back to you about it soon✨

###### Please also check out the [docs](https://rasa.com/docs/) and the [forum](https://forum.rasa.com/) in case your issue was raised there too 🤗

**Comment by arunbg** [comment]
```
NAME                                    READY   STATUS                  RESTARTS   AGE
rasa-app-75576cc449-2dmnk               1/1     Running                 0          14m
rasa-rabbit-0                           0/1     CrashLoopBackOff        7          14m
rasa-redis-master-0                     0/1     CrashLoopBackOff        7          14m
rasa-db-migration-service-0             0/1     ImagePullBackOff        0          14m
rasa-rasa-production-8588bdcb66-hqt78   0/1     Init:ImagePullBackOff   0          14m
rasa-postgresql-0                       0/1     CrashLoopBackOff        7          14m
rasa-nginx-7f4677647c-292g4             0/1     ImagePullBackOff        0          14m
rasa-rasa-worker-85c7b4476c-z2lh7       0/1     Init:ImagePullBackOff   0          14m
rasa-event-service-968bf56fb-6ccg9      0/1     Init:ImagePullBackOff   0          14m
rasa-rasa-x-5484cd6fbd-drgkm            0/1     ImagePullBackOff        0          14m
```
```
$ kubectl logs rasa-rabbit-0
touch: cannot touch '/opt/bitnami/rabbitmq/var/lib/rabbitmq/.start': Permission denied
```

Write permission issues causing crashes with Postgres, Redis and Rabbit images.

**Comment by m-vdb** [comment]
Closing as stale
