### ISSUE TITLE
How to add web urls to payload buttons?

### ISSUE THREAD

**Issue by praveenprv** [RasaHQ/rasa#9325]
Hi Team,

1. I have created payload buttons level navigation to my bot.
2. I wanted to add web urls to the buttons, as soon as the user clicks on the button the web page should open in the same web page instead of a new tab.

Thanks in advance

**Comment by sara-tagger** [comment]
Thanks for raising this issue, @aeshky will get back to you about it soon✨

###### Please also check out the [docs](https://rasa.com/docs/) and the [forum](https://forum.rasa.com/) in case your issue was raised there too 🤗

**Comment by wochinge** [comment]
Please ask questions in the [forum](https://forum.rasa.com)
