### ISSUE TITLE
implement `NLUMessageConverter`

### ISSUE THREAD

**Issue by wochinge** [RasaHQ/rasa#9326]
**Overview of the Solution**:
We need to implement the `NLUMessageConverter`. This component runs during inferences and takes a `UserMessage` object and converts it into a list of `Message` objects which can then be processed by our "NLU" components (tokenizer, featurizer, classifiers).

[This figure](https://www.notion.so/rasa/Rasa-Open-Source-3-0-Architecture-Implementation-Proposal-51ab90b05c41435ca98189a101676a1e#48704bc28dab486dad98e9ebd3ab9077) shows the component's position in the graph.

**Input to the component**
`Optional[UserMessage]` (the message might be `None` in case we are predicting actions after actions (in contrast to predicting the first action after a user message).

**Output:** 
A list of `Message` objects. The list has either length 1 (in case `UserMessage is not None`) or length 0 (in case `UserMessage is None`).

**Definition of Done**:
- [x] Component is implemented and unit tested

**Comment by ancalita** [comment]
@wochinge would this need a separate directory? or a module in dir `graph_components` is enough?

**Comment by wochinge** [comment]
yeah, how about making a `converts` package within `graph_components`?
