### ISSUE TITLE
implement `DomainProvider`

### ISSUE THREAD

**Issue by wochinge** [RasaHQ/rasa#9332]
**Overview of the Solution**:
We need to implement the `DomainProvider`. This component receives an instantiated `TrainingDataImporter` and returns the result of `importer.get_domain(...)` 

[This figure](https://www.notion.so/rasa/Rasa-Open-Source-3-0-Architecture-Implementation-Proposal-51ab90b05c41435ca98189a101676a1e#24ef56343a554fe88748651864fe9e77) shows the component's position in the graph.

**Input to the component**
- `TrainingDataImporter`

**Output:** 
* a `Domain` object

**Blockers**
* https://github.com/RasaHQ/rasa/pull/9184

**Definition of Done**:
- [x] Component is implemented and unit tested

**Comment by ancalita** [comment]
@wochinge to double-check - this component should be placed in `rasa/engine/training/components.py`?
Or should I wait for you to merge the tracker-generator PR and then I can create a module just for `DomainProvider` and place it in `rasa/components/providers`? I could prioritise the RulePolicy issue I have instead 🤔

**Comment by wochinge** [comment]
good question! @joejuzl I'd actually like to keep all these components out of the engine. Hence, I've created a new top level package with components [here](https://github.com/RasaHQ/rasa/pull/9361/files). What do you think?

**Comment by joejuzl** [comment]
> good question! @joejuzl I'd actually like to keep all these components out of the engine. Hence, I've created a new top level package with components here. What do you think?

Makes sense to me - although maybe `graph_components` dir name?

**Comment by wochinge** [comment]
sounds good 👍🏻 Will adapt my PR accordingly
