### ISSUE TITLE
implement `DomainWithoutResponsesProvider`

### ISSUE THREAD

**Issue by wochinge** [RasaHQ/rasa#9333]
**Overview of the Solution**:
We need to implement the `DomainWithoutResponsesProvider `. This provides domain but without responses. Used to avoid retraining policies when the response text changes.

[This figure](https://www.notion.so/rasa/Rasa-Open-Source-3-0-Architecture-Implementation-Proposal-51ab90b05c41435ca98189a101676a1e#24ef56343a554fe88748651864fe9e77) shows the component's position in the graph.

**Input to the component**
- a `Domain`

**Output:** 
* same `Domain` but with nuked `responses` (set to empty list)

**Definition of Done**:
- [ ] Component is implemented and unit tested

**Comment by Archish27** [comment]
@wochinge / @TyDunn Hey, can you please add me as member to the Rasa `notion.so`?

**Comment by wochinge** [comment]
Hi @Archish27 ,
Unfortunately we can't as this is our company's internal notion workspace.

**Comment by Archish27** [comment]
Ohh cool no worries, so can you let me know where this file should be placed?

Also, what does nuke responses mean?
Should `Domain` object be empty?

**Comment by wochinge** [comment]
@Archish27 Thanks for your initiative 🙌🏻 

This issue is part of an architecture revamp which we are currently undertaking with relatively tight deadlines. I'd suggest that you'd rather take one of the issues from the [contributor board](https://github.com/orgs/RasaHQ/projects/23).
