### ISSUE TITLE
Cut 2.8.x micro release to ship Rasa Chat Widget

### ISSUE THREAD

**Issue by TyDunn** [RasaHQ/rasa#9334]
**Defintion of done**
- [x] 2.8.x patch release shipped (with [this docs update](https://github.com/RasaHQ/rasa-x/pull/5669)) 
- [x] @m-vdb has notified marketing / dev rel [here](https://rasa-hq.slack.com/archives/C6CJ0BGBD/p1628769292022900)

**Comment by wochinge** [comment]
currently blocked as the change is not merged to 2.8.x but `main`

**Comment by wochinge** [comment]
https://rasa-hq.slack.com/archives/C7B08Q5FX/p1629391301050100
