### ISSUE TITLE
implement `ConfigValidator`

### ISSUE THREAD

**Issue by wochinge** [RasaHQ/rasa#9336]
**Overview of the Solution**:
We need to implement the `ConfigValidator `. This component receives the current training data as `TrainingDataImporter` and validates it against the current train graph schema (accessible via `ExecutionContext`). Implements the logic from [here](https://github.com/RasaHQ/rasa/blob/e0a6a4a0829f510fd33657c918192ebe3f5ba06e/rasa/nlu/components.py#L245).  

[This figure](https://www.notion.so/rasa/Rasa-Open-Source-3-0-Architecture-Implementation-Proposal-51ab90b05c41435ca98189a101676a1e#24ef56343a554fe88748651864fe9e77) shows the component's position in the graph.

**Update**:
- this should also check [this](https://github.com/RasaHQ/rasa/blob/9fdbca3a1e7b408fa2999d8e394520185c7a0fe0/rasa/core/policies/ensemble.py#L118)
- and [this](https://github.com/RasaHQ/rasa/blob/9fdbca3a1e7b408fa2999d8e394520185c7a0fe0/rasa/core/policies/ensemble.py#L247)
- consider checking all graph components which have a `validate_against_domain` to validate them against the domain (see [here](https://github.com/RasaHQ/rasa/pull/9576/files#r705073921))

**Input to the component**
- `TrainingDataImporter`

**Output:** 
* `none`
* raises exception in case config doesn't match training data

**Blockers**
* https://github.com/RasaHQ/rasa/pull/9184

**Definition of Done**:
- [ ] Component is implemented and unit tested

**Comment by ErickGiffoni** [comment]
Hello ! Is there anyone working on this issue ?

I’m with 2 other developers here and we’d like to contribute, if possible!

**Comment by wochinge** [comment]
Hi @ErickGiffoni . Thanks for your initiative 🙌🏻 

This issue is part of an architecture revamp which we are currently undertaking with relatively tight deadlines. I'd suggest that you'd rather take one of the issues from the [contributor board](https://github.com/orgs/RasaHQ/projects/23).

**Comment by ErickGiffoni** [comment]
> Hi @ErickGiffoni . Thanks for your initiative 🙌🏻
> 
> This issue is part of an architecture revamp which we are currently undertaking with relatively tight deadlines. I'd suggest that you'd rather take one of the issues from the [contributor board](https://github.com/orgs/RasaHQ/projects/23).

Thanks for your quick feedback!

Ok, we understand and we’ll search for other issues then ! Have a good one 🙌🏻
