### ISSUE TITLE
Implementation proposal for markers in 3.0

### ISSUE THREAD

**Issue by TyDunn** [RasaHQ/rasa#9341]
**Definition of done**
- [x] https://github.com/RasaHQ/rasa/issues/9280 completed
- [x] Research reviewed and aligned on scope
- [x] #sv-analytics reviewed and aligned on scope
- [x] Implementation proposal drafted
- [x] Implementation proposal reviewed by Enable squad
- [x] Issues created in inbox for implementation

**Comment by aeshky** [comment]
[Implementation proposal](https://www.notion.so/rasa/Success-Markers-Implementation-Proposal-79cb6f2b96584387aef6ab5c60db4b4c)
