### ISSUE TITLE
Adapt `RulePolicy` to new `GraphComponent` interface

### ISSUE THREAD

**Issue by joejuzl** [RasaHQ/rasa#9345]
**Overview of the Solution**:
Adapt the `RulePolicy` to the new `GraphComponent` interface.
See the [implementation proposal](https://www.notion.so/rasa/Rasa-Open-Source-3-0-Architecture-Implementation-Proposal-51ab90b05c41435ca98189a101676a1e) for further details.

* adapt `create` and `load` functions to new signatures
* implement `required_packages` and `supported_languages`
* adapt persistence
* add default param for `interpreter` so graph doesn't need to fill it (this is a workaround)
* adapt how config is passed into the component (and default config)

**Blockers**
- Adapt `MemoizationPolicy` #9344

**Definition of Done**:
- [ ] `RulePolicy` adapted to the new GraphComponent interface
- [ ] Unit tests are adapted to adaption of policy
- [ ] Other tests (integration tests, etc.) don't break (because they'd (for now) still use the old policy implementation)

**Comment by ancalita** [comment]
@joejuzl i see that that the Memoization Policy PR opened by Thomas is still in progress - should I branch off his branch and start working on this issue?

**Comment by joejuzl** [comment]
> @joejuzl i see that that the Memoization Policy PR opened by Thomas is still in progress - should I branch off his branch and start working on this issue

Is there another issue you can pick up in the meantime?

**Comment by ancalita** [comment]
> Is there another issue you can pick up in the meantime?

@joejuzl yup will start the `DomainProvider` & `NLUMessageConverter` ones.
