### ISSUE TITLE
rasa test nlu should not care if intents in stories are not the domain file

### ISSUE THREAD

**Issue by hsm207** [RasaHQ/rasa#9351]
**Description of Problem**:

Running `rasa test nlu` on a bot that has split domain e.g:

```
|-- domain
|   |-- domain1.yml
|   |-- domain2.yml
```

will print warnings about an intent being in a story but not part of the domain e.g.:

> /opt/venv/lib/python3.8/site-packages/rasa/shared/utils/io.py:97: UserWarning: Issue found in 'data/rules.yml': 
> Found intent 'greet' in stories which is not part of the domain.
>   More info at https://rasa.com/docs/rasa/stories
> /opt/venv/lib/python3.8/site-packages/rasa/shared/utils/io.py:97: UserWarning: Issue found in 'data/stories.yml': 
> Found intent 'greet' in stories which is not part of the domain.
>   More info at https://rasa.com/docs/rasa/stories
> /opt/venv/lib/python3.8/site-packages/rasa/shared/utils/io.py:97: UserWarning: Issue found in 'data/stories.yml': 
> Found intent 'mood_great' in stories which is not part of the domain.
>   More info at https://rasa.com/docs/rasa/stories
> /opt/venv/lib/python3.8/site-packages/rasa/shared/utils/io.py:97: UserWarning: Issue found in 'data/stories.yml': 
> Found intent 'mood_unhappy' in stories which is not part of the domain.
>   More info at https://rasa.com/docs/rasa/stories
> /opt/venv/lib/python3.8/site-packages/rasa/shared/utils/io.py:97: UserWarning: Issue found in 'data/stories.yml': 
> Found intent 'affirm' in stories which is not part of the domain.

The source of these warnings is the test data importer assuming that the domain is in a file named domain.yml in the root folder (see [here](https://github.com/RasaHQ/rasa/blob/819c339f3f5cdf32593cc725ff7d8f4a8253ea3a/rasa/cli/test.py#L184-L186)).

The nlu evaluation runs fine despite these warnings so these warnings might confuse users.

**Overview of the Solution**:

Add an option to `rasa test nlu` to specify the path to a domain file or folder. For example

`rasa test nlu --domain /path/to/domain/folder`

or suppress the user warnings when loading the data. For example:

```
    warnings.filterwarnings("ignore", category=UserWarning)
    test_data_importer = TrainingDataImporter.load_from_dict(
        training_data_paths=[data_path], domain_path=DEFAULT_DOMAIN_PATH,
    )
```

**Examples** (if relevant):

**Blockers** (if relevant):

**Definition of Done**:
- [ ] `rasa test nlu` should not care if intents in stories are not the domain file in 2.8 / 3.0
- [ ] add integration test
- [ ] Fixed merged into 2.8 and 3.0

**Comment by akelad** [comment]
@TyDunn is this gonna be addressed with 3.0 or still TBD? another customer just asked about this

**Comment by TyDunn** [comment]
It is not in scope as of right now, but we can talk about it. I'll bring it up higher in the inbox

**Comment by TyDunn** [comment]
The fix for this issue will need to be backported to the last minor of the previous major (i.e. Rasa Open Source 2.8)
