### ISSUE TITLE
Determine research questions and workshop slides for UnexpecTEDIntentPolicy

### ISSUE THREAD

**Issue by kedz** [RasaHQ/rasa#9367]
**Description of Problem**:
Based on the `UnexpecTEDIntentPolicy` [post-mortem](https://www.notion.so/rasa/Postmortem-UnexpecTED-Intent-Policy-e49088d0c31e4ea58b51aeb4af21bf20) we will likely try to do some educational workshops about how to use the new policy as well as some research questions we would like to ask developers after they have tried out `UnexpecTEDIntentPolicy`.  

Draft of the questionaire and slide outline is [here](https://docs.google.com/document/d/1uuYXuczAJt3AinyRiZd5qg1pmby82U75gvnK-XEky-w/edit?usp=sharing).

Definition of Done:

- [x] Create slides based on the outline agreed above.
- [x] Schedule a workshop with CSE.
- [x] Deliver the workshop (if it is scheduled within the same sprint).

**Comment by dakshvar22** [comment]
@TyDunn The next steps are fairly clear in the doc and me / Chris can work on this in one of the upcoming sprints. Our estimate was that we can tick the first two next steps in a sprint. Based on that, do you think we can prioritize it to be taken up next sprint?

**Comment by TyDunn** [comment]
@dakshvar22 Let's do it. CSE is aware and ready when we are :)

**Comment by dakshvar22** [comment]
@dakshvar22 To create the slides, @kedz as reviewer

**Comment by dakshvar22** [comment]
@kedz @TyDunn Got a bit delayed on this one but first draft of the slides is [here](https://docs.google.com/presentation/d/1uhjPjuHs2wMvmgGMIvkPmwWJjCWvQA0pIDydU9oT1rI/edit?usp=sharing). Please feel free to edit / add anything or add comments.

Next steps:
1. Finish the remaining todos in the slides (by 6th October)
2. Finalize the slides with @kedz @TyDunn  (by 8th October)
3. Schedule and deliver the workshop to CSE (by 14th October)

**Comment by TyDunn** [comment]
> Schedule and deliver the workshop to CSE

Dev Rel would like to be invited and included too

**Comment by TyDunn** [comment]
Closing because we delivered the workshop
