### ISSUE TITLE
Make story augmentation more efficient

### ISSUE THREAD

**Issue by melindaloubser1** [RasaHQ/rasa#9392]
**Description of Problem**:

The [generation code](https://github.com/RasaHQ/rasa/blob/53bd34647d0596a5e2b60b2f1e6b70abfde16a55/rasa/shared/core/generator.py#L357-L523) for augmentation of stories is hard to read and quite efficient.

Currently, augmentation takes an inordinately long time given a large number of stories (>1000) and a reasonable augmentation factor (>30 - the default is 50 so this is not that big).

**Overview of the Solution**: Refactor the generation code

**Examples** (if relevant): On a dataset with 5000 modular stories and no checkpoints, augementation cannot complete at all with an aug factor of 50 on a machine with 16GB of RAM.

**Definition of Done**:

*   [ ] Code refactored
*   [ ] Performance on large dataset tested
*   [ ] Augmentation approach described better in documentation
*   [ ] Feature mentioned in the changelog

**Comment by JEM-Mosig** [comment]
I had written a fix for this for 1.x and am porting this to 2.x now: https://github.com/RasaHQ/rasa/pull/9370
Does this resolve this issue?

**Comment by melindaloubser1** [comment]
I'm testing it out on the dataset I noticed the problem on, thanks!

**Comment by melindaloubser1** [comment]
I'm still trying it out, but from the changes it doesn't look like augmentation (the process) was touched at all - only AugMemo prediction. This issue is about the speed of generating stories according to the factor defined with  `--augmentation`, which I believe is relevant to multiple policies and occurs before any of them are involved.

**Comment by melindaloubser1** [comment]
The changes from that PR do in fact not change anything w.r.t. speed of loading trackers when using augmentation.
