### ISSUE TITLE
Add python version compatibility to doc

### ISSUE THREAD

**Issue by ankandrew** [RasaHQ/rasa#9393]
**Description of Problem**:

When visiting [installation](https://rasa.com/docs/rasa/installation) site in the doc, It currently says: `Install Python 3 (64-bit version) for Windows.` in [this](https://rasa.com/docs/rasa/installation#1-python-environment-setup) section.

**Overview of the Solution**:

I think it would be nice to add the minimum python version required **i.e. python 3.7**.

**Comment by sara-tagger** [comment]
Thanks for submitting this feature request 🚀 @ancalita will get back to you about it soon! ✨

**Comment by ancalita** [comment]
@ankandrew thank you for for the issue! 
At the moment, there is a mention of which versions are applicable in the first sentence in the [`Quick Installation`](https://rasa.com/docs/rasa/installation#quick-installation) section. But it should be clarified in the section you also mentioned. 

I've placed this in my team's queue to be prioritised accordingly.

**Comment by ankandrew** [comment]
@ancalita I somehow managed to skip that in [Quick Installation](https://rasa.com/docs/rasa/installation#quick-installation)! I would only remove the 3.6, it appears it is no [longer supported](https://github.com/RasaHQ/rasa/pull/9116).

**Comment by ankandrew** [comment]
It also depends on the 3.6.x version. Things like `typing.NoReturn` [were introduced](https://docs.python.org/3.6/library/typing.html#typing.NoReturn) on a later 3.6 version, and it is used in part of the code, like [here](https://github.com/RasaHQ/rasa/blob/a0d9cd06c15aa0a71d075ad5add4495e19b7698e/rasa/cli/run.py#L4). But I guess this doesn't matter as 3.6 is not supported.
