### ISSUE TITLE
Create issues for migrating featurizer components to 3.0

### ISSUE THREAD

**Issue by joejuzl** [RasaHQ/rasa#9411]
SpacyFeaturizer
MitieFeaturizer
RegexFeaturizer
LexicalSyntacticFeaturizer
CountVectorsFeaturizer
ConveRTFeaturizer
LanguageModelFeaturizer

**Comment by wochinge** [comment]
- [SpacyFeaturizer](https://github.com/RasaHQ/rasa/issues/9452)
- [MitieFeaturizer](https://github.com/RasaHQ/rasa/issues/9453)
- [RegexFeaturizer](https://github.com/RasaHQ/rasa/issues/9451)
- [LexicalSyntacticFeaturizer](https://github.com/RasaHQ/rasa/issues/9450)
- [CountVectorsFeaturizer](https://github.com/RasaHQ/rasa/issues/9449)
- [ConveRTFeaturizer](https://github.com/RasaHQ/rasa/issues/9454)
- [LanguageModelFeaturizer](https://github.com/RasaHQ/rasa/issues/9456)
