### ISSUE TITLE
Implement Spacy model provider graph component

### ISSUE THREAD

**Issue by joejuzl** [RasaHQ/rasa#9416]
TBD

**Comment by wochinge** [comment]
I suggest having a look at https://github.com/RasaHQ/rasa/pull/9443 and https://github.com/RasaHQ/rasa/pull/9444 to see how the loaded model is provided to dependant components

**Comment by joejuzl** [comment]
It turns out that `SpacyNLP` actual does processing of messages that is needed for `SpacyTokenizer` and `SpacyFeaturizer`. So we will need to split it into two components, one that provides the model, and one that does the pre-processing.

**Comment by joejuzl** [comment]
Further update: the spacy model is actually required by the `CountVectorFeaturizer` for it's OOV words, so we will stick to original plan of creating a spacy model provider.
