### ISSUE TITLE
3.0 Deprecations: Remove deprecation warnings from featurizers

### ISSUE THREAD

**Issue by ancalita** [RasaHQ/rasa#9432]
**Context**:
In preparation for the 3.0 release, we need to remove all deprecated code/warnings.

These deprecation warnings are being raised in:
- [`rasa/nlu/featurizers/sparse_featurizer/regex_featurizer.py`](https://github.com/RasaHQ/rasa/blob/7f0bb29b1a40e237931f6f431813e08654bea1fb/rasa/nlu/featurizers/sparse_featurizer/regex_featurizer.py#L72)
- [`rasa/nlu/featurizers/sparse_featurizer/count_vectors_featurizer.py`](https://github.com/RasaHQ/rasa/blob/7f0bb29b1a40e237931f6f431813e08654bea1fb/rasa/nlu/featurizers/sparse_featurizer/count_vectors_featurizer.py#L158)
- [`rasa/core/featurizers/tracker_featurizers.py:L216`](https://github.com/RasaHQ/rasa/blob/7f0bb29b1a40e237931f6f431813e08654bea1fb/rasa/core/featurizers/tracker_featurizers.py#L216)
- [`rasa/core/featurizers/tracker_featurizers.py:L246`](https://github.com/RasaHQ/rasa/blob/7f0bb29b1a40e237931f6f431813e08654bea1fb/rasa/core/featurizers/tracker_featurizers.py#L246)

**Definition of Done**
- [ ] all listed warnings above are resolved/removed
- [ ] @jupyterjazz assigned reviewer

**Comment by samsucik** [comment]
I think this is really only about removing the warnings from the code in the first 2 files (no docs changes or additional code changes). In the tracker featurisers, we have to remove the entire method that's been deprecated. Still, should be very quick.
