### ISSUE TITLE
Investigate runtime and memory changes due to TF 2.5

### ISSUE THREAD

**Issue by samsucik** [RasaHQ/rasa#9433]
**Definition of done**:
- Set up gcloud tests for accurately measuring runtimes on GPUs
- Compute runtimes for all datasets we use in model regression tests
- Add memory measurements
- Measure memory consumption for the above datasets
- @samsucik assigned reviewer

**Comment by koernerfelicia** [comment]
[This sheet](https://docs.google.com/spreadsheets/d/14rIvQLxEdp1PJDqhM65n0__THKhvS5f4XPLoWz8SWSs/edit#gid=393679539) now has stats for GPU runtime, CPU runtime, and memory usage (both CPU and GPU) for GPU runs. There are overview analyses in the updates [here](https://www.notion.so/rasa/Upgrade-Tensorflow-to-2-5-5c99a9caa23f42c78549f78fd9d5c630)

**Comment by koernerfelicia** [comment]
@samsucik I created followup issues above. I'd like to close this issue. Is there anything else I am missing from your pov?

**Comment by samsucik** [comment]
@koernerfelicia I appreciate creating the follow-up issues! All looks good to me but I wonder if the code/instructions used in running the tests (even if they're WIP) could be considered too. What do you think about creating a follow-up issue for that? We could aim to curate these tools, document them (only to the necessary extent) and store in the `research-experiments` repo.

**Comment by koernerfelicia** [comment]
Great point! I had this in my own TODOs but not formally tracked as an issue. Added now, will add a checkbox to the relevant followup issues to also document how those are carried out.

**Comment by samsucik** [comment]
Awesome, then, I think, this issue can be closed 🙂
