### ISSUE TITLE
Update workflows for community PRs

### ISSUE THREAD

**Issue by ancalita** [RasaHQ/rasa#9438]
**Context**:
This [community PR](https://github.com/RasaHQ/rasa/pull/8697) prompted a [CI run fail](https://github.com/RasaHQ/rasa/actions/runs/1158996710) which pointed that the workflow for community contributions needs to be updated.

**Definition of Done**:
 - [ ] community PR workflow is updated.

**Comment by HotThoughts** [comment]
Fixed https://github.com/RasaHQ/rasa/pull/9434
