### ISSUE TITLE
Let `RegexEntityExtractor` work without the dummy entity annotation

### ISSUE THREAD

**Issue by JEM-Mosig** [RasaHQ/rasa#9439]
**Description of Problem**: When we use RegexEntityExtractor we have to annotate at least one example of each entity in the training data. This is only necessary because of [this](https://github.com/RasaHQ/rasa/blob/2.8.x/rasa/nlu/extractors/regex_entity_extractor.py#L61) condition, and it is problematic when you want to use multiple entity extractors.

We recommend that "If you use multiple entity extractors, we advise that each extractor targets an exclusive set of entity types", but we don't actually allow this. You cannot distinguish in the annotation what entity extractor the annotation is for, so once you annotate the entity, DIET will try to extract it. But you also have to annotate an entity if you use RegexEntityExtractor because it should only pay attention to those lookup tables and entities whose names are also names of entities, but the code that checks this has no access to the domain and thus asks the training data, hence the required annotation.

**Overview of the Solution**: Make the domain (or entities in the domain) available [here](https://github.com/RasaHQ/rasa/blob/2.8.x/rasa/nlu/utils/pattern_utils.py#L27). That’ll require that Featurizers and Extractors get access to domain during train - which isn’t done there currently, but we do that for policies already.

**Definition of Done**:

*   [ ] RegexEntityExtractor works without any annotated entities (only the lookup table or regex is defined)

**Comment by samsucik** [comment]
@wochinge based on [this thread](https://rasa-hq.slack.com/archives/C021ZTVSY77/p1629714374319800?thread_ts=1629468371.294500&cid=C021ZTVSY77) what do you say to including this in the 3.0 milestone?

**Comment by samsucik** [comment]
Just to make the definition of done clearer for this one: As part of updating the relevant docs, we should change the bits [here](https://github.com/RasaHQ/rasa/blob/main/docs/docs/nlu-training-data.mdx) that talk about having to include at least _two_ training examples in order for the NLU model to pick up the entity. I haven't been able to find this rule anywhere in our code and I suspect that, in reality, anything with _one_ or more example is picked up.

**Comment by wochinge** [comment]
I'm hesitant to add anything to the milestone this late in the process. If so I'd add it to a "nice to have in 3.0" milestone.

**Comment by samsucik** [comment]
@wochinge I think having as a "nice to have" would be great. (You know the 3.0 milestone better, I myself am just trying to bump up this particular issue so it gets addressed soon.)

**Comment by wochinge** [comment]
@TyDunn What do you think? Should we create a nice to have milestone?
