### ISSUE TITLE
Document How Rasa's Training Time Improves When Trained On A GPU (or GPUs)

### ISSUE THREAD

**Issue by hsm207** [RasaHQ/rasa#9445]
**Description of Problem**:

It would be useful if we can experiment on how training time will improve under various datasets and model configuration (both NLU and Core) when training is done on a GPU and share our findings.

This can serve as a guideline for customers to plan on when to add GPU(s) to their deployment.

**Overview of the Solution**:

A document that describes how the training time improves when trained on a GPU under various scenarios (dataset size, model configuration, GPU, CPU, accuracy, etc).

**Examples** (if relevant):

*   [DAWNBench](https://dawn.cs.stanford.edu/benchmark/ImageNet/train.html)

**Blockers** (if relevant):

**Definition of Done**:

**Comment by TyDunn** [comment]
@hsm207 I believe @koaning has done some work around this (e.g. [this video](https://www.youtube.com/watch?v=T0TUaGsd0gc))

**Comment by Barmin93** [comment]
Cool idea, although as for now - multi GPU training doesn't work properly at current RASA version (3.2.1).
