### ISSUE TITLE
Add support for instagram as a channel

### ISSUE THREAD

**Issue by TyDunn** [RasaHQ/rasa#9446]
> [All Instagram business accounts can connect to Messenger API for Instagram as of August 16, 2021.](https://developers.facebook.com/docs/messenger-platform/instagram/)

A community member pointed this out to me [here](https://forum.rasa.com/t/instagram-integration-with-rasa/45461/3). I think it would be really cool to have an Instagram channel connector. This would be a great opportunity for someone in the community to contribute code. If someone is interested, this is how I'd get started:

1.  Read about [How to open a PR and contribute code to Rasa Open Source](https://rasa.com/community/code-contributor-guidelines#how-to-open-a-pr-and-contribute-code-to-rasa-open-source)
2.  Watch this video about [Building a Custom Communication Channel for Rasa](https://www.youtube.com/watch?v=kx1k1sdj0uY)
3.  Read about [Custom Connectors](https://rasa.com/docs/rasa/connectors/custom-connectors) in the docs
4.  Take inspiration from an existing channel like the [facebook messenger channel](https://github.com/RasaHQ/rasa/blob/main/rasa/core/channels/facebook.py)

**Comment by TyDunn** [comment]
@Horizon733 Awesome. Can you open a [pull request](https://rasa.com/community/code-contributor-guidelines#how-to-open-a-pr-and-contribute-code-to-rasa-open-source) with the code? We can then get some engineers to review what you have

**Comment by Horizon733** [comment]
> @Horizon733 Awesome. Can you open a [pull request](https://rasa.com/community/code-contributor-guidelines#how-to-open-a-pr-and-contribute-code-to-rasa-open-source) with the code? We can then get some engineers to review what you have

sure will do that right now

**Comment by Horizon733** [comment]
Hi, @TyDunn can you help me out in testing with Rasa repo since I tested it by adding it as custom channel and not inside rasa package. So, how to achieve it?
Quite new to this process

**Comment by TyDunn** [comment]
@Horizon733 No worries. [This link](https://rasa.com/community/code-contributor-guidelines#4-implement-your-code-contribution) will walk you through the steps of forking, cloning, etc. Your code contribution should look something like [this recent channel](https://github.com/RasaHQ/rasa/pull/8180) we added to Rasa Open Source

**Comment by Horizon733** [comment]
added draft pr to get started with
https://github.com/RasaHQ/rasa/pull/9594
