### ISSUE TITLE
Catch warning in CI for `linear` norm for better CI logs

### ISSUE THREAD

**Issue by wochinge** [RasaHQ/rasa#9447]
Multiple policy / classifier tests tests using the dropped `linear_norm` parameter. This emits an somewhat expected warning in the CI which add noise to the CI logs. To avoid this the warnings should be caught using `with pytest.warns`. 

See the related communication [here](https://github.com/RasaHQ/rasa/pull/8775#issuecomment-894883409).

**Comment by mleimeister** [comment]
@wochinge The current version of configs in `training-data` do not show any usage of `linear_norm` anymore. Can this issue be closed?

**Comment by wochinge** [comment]
Sure 👍🏻
