### ISSUE TITLE
Migrate `CountVectorsFeaturizer` to `GraphComponent` interface

### ISSUE THREAD

**Issue by wochinge** [RasaHQ/rasa#9449]
**Overview of the Solution**:
Adapt the `CountVectorsFeaturizer ` to the new `GraphComponent` interface.
See the [implementation proposal](https://www.notion.so/rasa/Rasa-Open-Source-3-0-Architecture-Implementation-Proposal-51ab90b05c41435ca98189a101676a1e) for further details.

* adapt `create` and `load` functions to new signatures
* implement `required_packages` and `supported_languages` 
* adapt persistence
* split `train` into `train` (trains the featurizer) and `process_training_data` (adds features to training data for subsequent classifiers etc.)
* support multiple messages in `process` (**make sure to handle empty messages**)

Blockers:
- https://github.com/RasaHQ/rasa/issues/9416

**Definition of Done**:
- [ ] CountVectorsFeaturizer adapted to the new GraphComponent interface
- [ ] Unit tests are adapted to adapted component
- [ ] Other tests (integration tests, etc.) don't break (because they'd (for now) still use the old component implementation)

**Comment by joejuzl** [comment]
Reminder: We need to adapt CountVectorsFeaturizer to always create a vocabulary for end-to-end even if there was no end-to-end training data
See: https://www.notion.so/rasa/Rasa-Open-Source-3-0-Architecture-Implementation-Proposal-51ab90b05c41435ca98189a101676a1e#8863a24281c64d6e8b9de161c9a8d7ee

**Comment by wochinge** [comment]
This is actually no longer needed as we changed it so that the "core" model is re-using the trained "nlu" featurizers

**Comment by aeshky** [comment]
>Blockers:
>Implement Spacy model provider graph component #9416

Is this actually blocked? 🤔
