### ISSUE TITLE
Migrate `LanguageModelFeaturizer` to GraphComponent interface

### ISSUE THREAD

**Issue by wochinge** [RasaHQ/rasa#9456]
**Overview of the Solution**:
Adapt the `LanguageModelFeaturizer ` to the new `GraphComponent ` interface.
See the [implementation proposal](https://www.notion.so/rasa/Rasa-Open-Source-3-0-Architecture-Implementation-Proposal-51ab90b05c41435ca98189a101676a1e) for further details.

* adapt `create` ~and `load`~ functions new signatures
* implement `required_packages` and `supported_languages` 
* ~adapt persistence~
* rename `train` to `process_training_data` (this featurizer only adds features but doesn't require training)
* support multiple messages in `process` (**make sure to handle empty messages**)

**Definition of Done**:
- [ ] LanguageModelFeaturizer adapted to the new GraphComponent interface
- [ ] Unit tests are adapted to adapted component
- [ ] Other tests (integration tests, etc.) don't break (because they'd (for now) still use the old component implementation)

**Comment by aeshky** [comment]
The `LanugageModelFeaturizer` doesn't currently have a `load` method. However, reading the [description](https://github.com/RasaHQ/rasa/blob/051b7077825d2379736be14c5e6bdfd87e0abd9e/rasa/nlu/featurizers/dense_featurizer/lm_featurizer.py#L46), the class is designed to always load a pretrained model. In this case, should I replace the existing `create` method with `load`, and then not create a `create` method?

**Comment by wochinge** [comment]
It's also okay to just adapt the `create` one as the default implementations of the `GraphComponent`s `load` just points to `create` (see [here](https://github.com/RasaHQ/rasa/blob/5bb331ff7ba75ad564478cbc71fd1a46bce5ee02/rasa/engine/graph.py#L181))

**Comment by aeshky** [comment]
[`GraphComponent`](https://github.com/RasaHQ/rasa/blob/5bb331ff7ba75ad564478cbc71fd1a46bce5ee02/rasa/engine/graph.py#L129) doesn't have a `name` method like the old [`Component`](https://github.com/RasaHQ/rasa/blob/5bb331ff7ba75ad564478cbc71fd1a46bce5ee02/rasa/nlu/components.py#L452). Do we want to add one?

**Comment by wochinge** [comment]
No, that's not needed

**Comment by aeshky** [comment]
The original ML featurizer doesn't have a persist method. Should I add one, given that we only load pretrained models?

**Comment by wochinge** [comment]
The featurizer doesn't need persisting, so you can omit the `persist` method. Only components which train themselves need a `persist` method

**Comment by wochinge** [comment]
closed by https://github.com/RasaHQ/rasa/pull/9586
