### ISSUE TITLE
A component to do fuzzy matching

### ISSUE THREAD

**Issue by hsm207** [RasaHQ/rasa#9472]
### What problem are you trying to solve?

I want synonyms to work even if there are typos in it.

For example, given:

 nlu:

*   synonym: credit
     examples: |
*   credit card account
*   credit account

If DIETClassifier extracts `credit acount`, I want it to be normalized to `credit`.

The current workaround is to add all typos to the examples:

 nlu:

*   synonym: credit
     examples: |
*   credit card account
*   credit account
*   credit acount

### What's your suggested solution?

A component that can match a value to the examples in a synonym based on stemming, misspellings, and partial matches and returns a score.

### Examples (if relevant)

 _No response_ 

### Is anything blocking this from being implemented? (if relevant)

 _No response_ 

### Definition of Done

A component that does fuzzy matching

**Comment by TyDunn** [comment]
@hsm207 I believe @koaning has done some work around this (e.g. [this video](https://www.youtube.com/watch?v=T0TUaGsd0gc))

**Comment by hsm207** [comment]
@koaning what was the [trick](https://youtu.be/T0TUaGsd0gc?t=260) you alluded to in the video?

**Comment by hsm207** [comment]
@TyDunn the work @koaning did was [taipo](https://github.com/RasaHQ/taipo). It does data augmentation but does not handle normalization.

**Comment by TyDunn** [comment]
That make sense. Thanks for letting me know! We have added this to the NLU optimisations product area
