### ISSUE TITLE
Migrate `CRFEntityExtractor` to `GraphComponent` interface

### ISSUE THREAD

**Issue by joejuzl** [RasaHQ/rasa#9506]
**Overview of the Solution**:
Adapt the `CRFEntityExtractor ` to the new `GraphComponent` interface.
See the [implementation proposal](https://www.notion.so/rasa/Rasa-Open-Source-3-0-Architecture-Implementation-Proposal-51ab90b05c41435ca98189a101676a1e) for further details.

* adapt `create` and `load` functions to new signatures.
* implement `required_packages` and `supported_languages`.
* adapt persistence.
* split `train` into `train` and `process_training_data` (process the training data for the next components in the pipeline).
* support multiple messages in `process` (**make sure to handle empty messages**).
* Inherit from both `GraphComponent` _and_ `EntityExtractorMixin` (instead of the old `EntityExtractor`).

**Process to avoiding breaking the CI**
Use the approach showcased in the [TEDPolicy migration](https://github.com/RasaHQ/rasa/pull/9306) to avoid breaking the test suite.
Main points:
* Rename old files with a prefix i.e. from `some_component.py` to `_some_component.py`.
* make the changes in the current file e.g. `some_component.py`.
* In `some_component.py` import the old component from `_some_component.py` and assign like `SomeComponent = SomeComponent`
* Rename the _new_ component in `_some_component.py` to `SomeComponentGraphComponent`
* Adapt the old unit tests, i.e. `test_some_component.py` to test `SomeComponentGraphComponent`.

**Definition of Done**:
- [x] `CRFEntityExtractor` adapted to the new `GraphComponent` interface.
- [x] Unit tests are adapted to adapted component.
- [x] Other tests (integration tests, etc.) don't break (because they'd (for now) still use the old component implementation).

**Comment by ancalita** [comment]
@joejuzl This component has a [`function_dict` attribute](https://github.com/RasaHQ/rasa/blob/c68d13a66a9cf27b7072e803790726b578bba6df/rasa/nlu/extractors/crf_entity_extractor.py#L106) that doesn't quite look like it should belong to default config. Should I create a separate private property or a static method that returns this dict?

**Comment by joejuzl** [comment]
> @joejuzl This component has a function_dict attribute that doesn't quite look like it should belong to default config. Should I create a separate private property or a static method that returns this dict?

It looks like it's not in `defaults` - it's just at class level.
