### ISSUE TITLE
Rasa X doesn't consider endpoints.yml nlu configuration.

### ISSUE THREAD

**Issue by pdan93** [RasaHQ/rasa#9511]
### Rasa Open Source version

latest

### Rasa SDK version

latest

### Rasa X version

latest

### Python version

3.8

### What operating system are you using?

Linux

### What happened?

If you write a custom interpreter configuration in the _nlu_ option in endpoints.yml, it should be loaded as the custom interpreter. That is indeed the case if you just run rasa normally or in shell. But when rasa-x is involved, it doesn't take it into account. From what I could see, it all ends up on this line [https://github.com/RasaHQ/rasa/blob/6e812a3dda89ab97acf90a06314aad32dca559ff/rasa/core/run.py#L250](https://github.com/RasaHQ/rasa/blob/6e812a3dda89ab97acf90a06314aad32dca559ff/rasa/core/run.py#L250) Since in rasa-x you don't just get one single model_path, it automatically goes into that Exception and then interpreter is just set to None.

### Command / Request

<pre>Just simply adding a custom interpreter in endpoints.yml and then running docker-compose normally over the normal distribution of rasa-x.</pre>

### Relevant log output

 _No response_

**Comment by m-vdb** [comment]
Closing as stale
