### ISSUE TITLE
Form execution rejected if slot is not extracted

### ISSUE THREAD

**Issue by Rasanoob** [RasaHQ/rasa#9520]
### Rasa Open Source version

2.6.x/2.7.x

### Python version

3.8

### What operating system are you using?

Linux

### What happened?

In a simple default form:

forms:
  test_form:
    required_slots:
      name:
        - type: from_text      
      weekday:
        - type: from_entity
          entity: weekday     

The bot does not ask again if entity is not recognized. Instead he rejects the form execution and changes to TED policy for next step

### Relevant log output

```shell
Which weekday is it?
Your input ->  hello
rasa.core.processor  - Received user message 'hello' with intent '{'id': 286870438279032377, 'name': 'greet', 'confidence': 0.9999989867210388}' and entities '[]'
rasa.core.policies.rule_policy  - There is no applicable rule.
rasa.core.policies.rule_policy  - Predicted loop 'test_form'.
rasa.core.policies.ensemble  - Made prediction using user intent.
rasa.core.policies.ensemble  - Added `DefinePrevUserUtteredFeaturization(False)` event.
rasa.core.policies.ensemble  - Predicted next action using policy_2_RulePolicy.
rasa.core.processor  - Predicted next action 'test_form' with confidence 1.00.
rasa.core.actions.forms  - Validating user input 'UserUttered(text: hello, intent: greet, use_text_for_featurization: False)'.
rasa.core.actions.forms  - Trying to extract requested slot 'weekday' ...
rasa.core.actions.forms  - Got mapping '{'type': 'from_entity', 'entity': 'weekday'}'
rasa.core.actions.forms  - Failed to extract requested slot 'weekday'
rasa.core.actions.forms  - Validating extracted slots: {}
rasa.core.policies.rule_policy  - There is no applicable rule.
rasa.core.policies.ensemble  - Execution of 'test_form' was rejected. Setting its confidence to 0.0 in all predictions.
rasa.core.policies.ensemble  - Made prediction using user intent.
rasa.core.policies.ensemble  - Added `DefinePrevUserUtteredFeaturization(False)` event.
rasa.core.policies.ensemble  - Predicted next action using policy_1_TEDPolicy.
rasa.core.processor  - Predicted next action 'utter_greet' with confidence 0.98.
```

**Comment by koernerfelicia** [comment]
Hi, this is the expected behaviour. You can read more about this [here](https://rasa.com/docs/rasa/forms/#writing-stories--rules-for-unhappy-form-paths).

> While a form is active, if a user's input does not fill the requested slot, the execution of the form action will be rejected i.e. the form will automatically raise an ActionExecutionRejection. These are the specific scenarios in which a form will raise an ActionExecutionRejection:
> 
> a slot was requested, but the user didn't fill the slot with their last message and you didn't define a custom action for validating slots or extracting slots.
> a slot was requested, but your custom action for validating slots or extracting slots didn't return any SlotSet events.

**Comment by koernerfelicia** [comment]
If you need more help setting up forms, and how to re-ask when slots aren't filled correctly, please ask in the forum! :)
