### ISSUE TITLE
action_session_start keeps getting triggered for no reason

### ISSUE THREAD

**Issue by mhdhdri** [RasaHQ/rasa#9530]
### Rasa Open Source version

2.8.0

### Rasa SDK version

2.8.0

### Rasa X version

 _No response_ 

### Python version

3.8

### What operating system are you using?

Linux

### What happened?

action_session_start keeps getting triggered for no reason in the middle of the conversation and ruins everything. According to the [documentation](https://rasa.com/docs/rasa/default-actions/#action_session_start), it shouldn't work like this. To reproduce, I've created a new project using rasa init, and the only thing I've added to it is MySQL tracker store. [<span class="image-wrap" style="">![](https://user-images.githubusercontent.com/13150376/132121808-c2640f61-ee6b-4409-9dcc-ac39d9a233c6.png)</span>](https://user-images.githubusercontent.com/13150376/132121808-c2640f61-ee6b-4409-9dcc-ac39d9a233c6.png)

Is this a bug? or I have misunderstood?

### Command / Request

 _No response_ 

### Relevant log output

 _No response_

**Comment by sara-tagger** [comment]
Thanks for raising this issue, @joejuzl will get back to you about it soon✨

###### Please also check out the [docs](https://rasa.com/docs/) and the [forum](https://forum.rasa.com/) in case your issue was raised there too 🤗

**Comment by m-vdb** [comment]
Closing as stale
