### ISSUE TITLE
rasa data validate should fail if conflicting slots are created in different domain files

### ISSUE THREAD

**Issue by hsm207** [RasaHQ/rasa#9555]
### What problem are you trying to solve?

Users may split the `domain.yml` into multiple files and have different teams work on different domain.

I want `rasa data validate` to check and fail if there are duplicate intents, conflicting slots, etc across the split domain files.

For example:

1. Run `rasa init`.
2. Copy `domain.yml` to `domain/domain1.yml`.
3. Delete `domian.yml`
4. Add the following slots in `domain/domain1.yml`:
![image](https://user-images.githubusercontent.com/2398765/132243210-3b9036bd-780b-4b60-8ba0-1066ee863ad1.png)
5. Create an empty file at `domain/domain2.yml` and write:
![image](https://user-images.githubusercontent.com/2398765/132243327-04c472b7-0302-4a49-bd7e-87062dc86a21.png)
6. Run  `rasa data validate -d domain/`.

The check will complete without errors

### What's your suggested solution?

`rasa data validate` consolidates all the domain files and then runs the yaml validation check.

**Definition of Done**

- [ ] `rasa data validate -d domain/` does not fail when conflicting/duplicate slots/intents/etc are found
- [ ] Add an integration test to ensure this works as expected
- [ ] Fixed merged into 2.8 and 3.0

**Comment by TyDunn** [comment]
The fix for this issue will need to be backported to the last minor of the previous major (i.e. Rasa Open Source 2.8)
