### ISSUE TITLE
recipe validation

### ISSUE THREAD

**Issue by ka-bu** [RasaHQ/rasa#9573]
### What problem are you trying to solve?

reintroduce sanity checks

### What's your suggested solution?

warnings/exceptions that now need to be raised by the recipe validation:

- ensemble.py
   - [x] warn if no rule policy is contained in ensemble 
     ```rasa.shared.utils.io.raise_warning(
                f"'{RulePolicy.__name__}' is not included in the model's "
                f"policy configuration. Default intents such as "
                f"'{USER_INTENT_RESTART}' and '{USER_INTENT_BACK}' will "
                f"not trigger actions '{ACTION_RESTART_NAME}' and "
                f"'{ACTION_BACK_NAME}'.",
                docs=DOCS_URL_DEFAULT_ACTIONS,
     ```
  - [x] warn if there are form names but no rule policy contained
     ```raise InvalidDomain(
                  "You have defined a form action, but have not added the "
                  f"'{RulePolicy.__name__}' to your policy ensemble. Either "
                  f"remove all forms from your domain or add the '{RulePolicy.__name__}' "
                  f"to your policy configuration."
              )
     ```
  - [x] warn if priorities are not unique
    ```rasa.shared.utils.io.raise_warning(
                    f"Found policies {v} with same priority {k} "
                    f"in PolicyEnsemble. When personalizing "
                    f"priorities, be sure to give all policies "
                    f"different priorities.",
                    docs=DOCS_URL_POLICIES,
                )
     ```

- rule policy: 
   - [x] assert that it's compatible with the domain (... nearly every component should have that?)
   - [x]  warn if rule based data exists but isn't used -- and if rule based data is expected but missing
   ``` consuming_rule_data = any(
        policy.supported_data()
        in [SupportedData.RULE_DATA, SupportedData.ML_AND_RULE_DATA]
        for policy in ensemble
    )
    contains_rule_tracker = any(
        tracker.is_rule_tracker for tracker in training_trackers
    )

    if consuming_rule_data and not contains_rule_tracker:
        rasa.shared.utils.io.raise_warning(
            f"Found a rule-based policy in your pipeline but "
            f"no rule-based training data. Please add rule-based "
            f"stories to your training data or "
            f"remove the rule-based policy (`{RulePolicy.__name__}`) from your "
            f"your pipeline.",
            docs=DOCS_URL_RULES,
        )
    elif not consuming_rule_data and contains_rule_tracker:
        rasa.shared.utils.io.raise_warning(
            f"Found rule-based training data but no policy supporting rule-based "
            f"data. Please add `{RulePolicy.__name__}` or another rule-supporting "
            f"policy to the `policies` section in `{DEFAULT_CONFIG_PATH}`.",
            docs=DOCS_URL_RULES,
        )
     ```

- featurizer
  - [x] validate compatability with tokenizer
  - [x] validate featurizers can be used together (names must be unique)
     - [ ]  follow-up task: check whether we can simplify the function application in `LexicalSyntacticFeaturizer` now (should not have to worry about non existing pos tokens anymore - unless "pos" tokens might still not be added by the `SpacyTokenizer`)

- every component
  - [x] needs to check whether all required components are contained on the path from input source to itself, e.g. the sklearn intent classifier requires a `DenseFeaturizer`, other classifiers require just any featurizer, ...
  - [ ] validation of config - GraphNode only fills in the default values but we do not detect e.g. typos this way
  - [x] check that language of training data data is supported / matches supported languages of components that need not be trained (e.g. ConveRT tests this - even though it doesn't train)
  

### Definition of Done

- [ ] unit tested

**Comment by wochinge** [comment]
>  assert that it's compatible with the domain (... nearly every component should have that?)

Done as part of https://github.com/RasaHQ/rasa/pull/9576

**Comment by ka-bu** [comment]
- ensemble / rule policy checks:  covered by DefaultV1ConfigValidator #9336 
- language: covered in validation.py 
- required components: #9677 
- compatability with tokenizer: implicitly covered by combination of config validator (not more than 1 tokenizer) and requested components

**Comment by wochinge** [comment]
💪🏻
