### ISSUE TITLE
Format for messages parsed by `RegexInterpreter` not explained in docs

### ISSUE THREAD

**Issue by ka-bu** [RasaHQ/rasa#9619]
### What problem are you trying to solve?

`RegexInterpreter` can be used to parse messages like `\<intent_name>@<confidence-value><dictionary of entities>` form the command line ([reference](https://github.com/RasaHQ/rasa/blob/2.8.x/rasa/shared/nlu/interpreter.py#L81)]. If it fails to parse something, it emits a user warning that references [this](https://rasa.com/docs/rasa/stories/) page, which doesn't seem to explain the format. 

### What's your suggested solution?

update the link used in the `interpreter.py` or add an explanation to the linked doc

### Definition of Done

- [ ] Update docs

**Comment by carlad** [comment]
@ka-bu @TyDunn A few questions:
> from the command line
 is for the `rasa train` cli command? or `rasa test`? It may not be relevant but I couldn't find anything in the cli docs (for `2.8`) which mentioned passing `messages` as an argument. Perhaps the messages are regex defined in the nlu yaml config as [regular expressions](https://rasa.com/docs/rasa/2.x/training-data-format#regular-expressions)?
If that's the case we could add an example to the docs that includes a regexp in the form described above (`\<intent_name>@<confidence-value><dictionary of entities>`), and update the link in the error message.
