### ISSUE TITLE
Categorical slot don't set option for values not explicitly defined

### ISSUE THREAD

**Issue by rgstephens** [RasaHQ/rasa#9627]
### What problem are you trying to solve?

When writing stories around categorical slots, I don't want to have to write stories for the default value `__other__` as well as stories for slot not set. Also don't want to deal with `__other__` value in stories when it should never happen for my use case.

### What's your suggested solution?

Provide an option for categorical slots that will not change the slot value when there is an attempt to set the slot to a value that isn't explicitly defined.

### Examples (if relevant)

 _No response_ 

### Is anything blocking this from being implemented? (if relevant)

 _No response_ 

### Definition of Done

 _No response_

**Comment by rgstephens** [comment]
Closing as a duplicate of #8755

**Comment by melindaloubser1** [comment]
I don't think this is a duplicate - #8755 is about representation of the `__other__` value in stories that come from interactive learning, this one is about changing the underlying behaviour of categorical slots.

**Comment by kedz** [comment]
@rgstephens Does @melindaloubser1 's suggestion of using a custom slot suffice for this issue for the time being? (priortizing research's inbox for the next sprint)

**Comment by rgstephens** [comment]
I agree with @melindaloubser1 that this is not a duplicate and the customers original request but I also don't think it's a high priority since this can be addressed via slot validation.
