### ISSUE TITLE
Redefine/replace utterance in custom action

### ISSUE THREAD

**Issue by georgebrianb** [RasaHQ/rasa#9632]
### What problem are you trying to solve?

Hey, so for my particular case, I validate user input inside a form (an e-mail) and if the input is not valid, the bot should inform the user and re-ask for the slot in case.

Right now, with a custom action like the one I will post below, I get the utterance specified with **dispatcher.utter_message(text="The e-mail you've entered is not part of the domain, please input an e-mail with the following format: [firstname.lastname@customdomain.com]")**, but besides that, it also utters the original utterance specified with "utter_ask_email"

### What's your suggested solution?

Add a way to replace an utterance inside a custom action. 
So one could either replace the original utterance, or one could specify that only the dispatcher message should be uttered to the user

### Examples (if relevant)

Sample expected conversation:

```
Bot: Hello, to get started please input your e-mail with the following format: [firstname.lastname@customdomain.com]
User: johndoe@not_customdomain.com
Bot: The e-mail johndoe@not_customdomain.com is not part of the domain, please input an e-mail with the following format: [firstname.lastname@customdomain.com]
User: johndoe@customdomain.com
Bot: Thank you
```

What happens when you try it right now:

```
Bot: Hello, to get started please input your e-mail with the following format: [firstname.lastname@customdomain.com]
User: johndoe@not_customdomain.com
Bot: The e-mail johndoe@not_customdomain.com is not part of the domain, please input an e-mail with the following format: [firstname.lastname@customdomain.com]
Bot: Hello, to get started please input your e-mail with the following format: [firstname.lastname@customdomain.com]  <<<-- unwanted utterance
User: johndoe@customdomain.com
Bot: Thank you

```
- rules.yml:

```
rules:
- rule: Activate mail_form
  steps: 
  - intent: greet
  - action: utter_greet 
  - action: mail_form
  - active_loop: mail_form
```
- Related domain.yml values:
```
utter_ask_email:
  - text: Hello, to get started please input your e-mail with the following format: [firstname.lastname@customdomain.com]
```

```
forms:
  mail_form:
    mail:
    - entity: mail
       type: from_entity
    confirm_mail:
    - type: from_text 
```

Validation code:

```
class ValidateMailForm(FormValidationAction):
    def name(self) -> Text:
        return "validate_manager_form"

    def validate_email(
        self,
        slot_value: Any,
        dispatcher: CollectingDispatcher,
        tracker: Tracker,
        domain: DomainDict,
    ) -> Dict[Text, Any]:
        regex = r'\b[A-Za-z0-9._%+-]+@customdomain\.com'
        mail = tracker.get_slot('email')
        if re.fullmatch(regex, email):
            return {"email":email}
        else: 
            dispatcher.utter_message(text="The e-mail you've entered is not part of the domain, please input an e-mail with the following format: [firstname.lastname@customdomain.com]")
            return {"email":None}
    
    def validate_confirm_mail(
        self,
        slot_value: Any,
        dispatcher: CollectingDispatcher,
        tracker: Tracker,
        domain: DomainDict,
    ) -> Dict[Text, Any]:
        if tracker.get_intent_of_latest_message() == "affirm":
            return {"confirm_mail":True, "mail": tracker.get_slot("mail")}
        if tracker.get_intent_of_latest_message() == "deny":
            return {"confirm_mail":None, "mail":None}
```

### My workaround
I added an extra utterance:

```
utter_no_mail:
- text: The e-mail {mail} is not part of the domain, please input an e-mail with the following format: [firstname.lastname@customdomain.com]
```

I then modified the utterance `utter_ask_mail` to a generic message:

From:
```
utter_ask_email:
  - text: Hello, to get started please input your e-mail with the following format: [firstname.lastname@customdomain.com]
```

To: 
```
utter_ask_mail:
- text: Please input your e-mail with the following format: [firstname.lastname@customdomain.com]
```

- This is an okay way to solve this, but it's still not ideal and I think the process can be improved

### Is anything blocking this from being implemented? (if relevant)

When setting a required slot to "None", the rasa core will try to fill it by asking for the slot again, using the `utter_slot_name` utterance. 
I don't know exactly how this could be implemented, but I do think it has a pretty good use  case and that it could be used by many.

### Definition of Done

Being able to use another utterance for setting a slot if validation was not confirmed.

**Comment by sara-tagger** [comment]
Thanks for submitting this feature request 🚀 @melindaloubser1 will get back to you about it soon! ✨

**Comment by hsm207** [comment]
This can be accomplished with this rule:

```
rules:
- rule: Activate mail_form
  steps: 
  - intent: greet
  - action: utter_greet
  - action: utter_enter_email
  - intent: inform_email # assume email can extract mail entity using regex
  - action: mail_form
  - active_loop: mail_form
 ```
Then, `utter_ask_mail` will be:

```
The e-mail {mail} is not part of the domain, please input an e-mail with the following format: [firstname.lastname@customdomain.com]
```
The way it works is:

1. `inform_email`  will extract the email and fill the mail slot with it.
2. If the mail slot is the correct format, the form gets deactivated
3. If the mail slot is not the correct format, then the bot will utter `utter_ask_mail`.

Notice that validation logic still happens inside the form.
