### ISSUE TITLE
Rasa.train hangs

### ISSUE THREAD

**Issue by greedydurian** [RasaHQ/rasa#9652]
### Rasa Open Source version

2.8.6

### Rasa SDK version

2.8.2

### Rasa X version

None

### Python version

3.8

### What operating system are you using?

Windows

### What happened?

Whenever I'm running Rasa in Jupyter notebook, the cell seems to be perpetually running/hangs. [<span class="image-wrap" style="">![](https://user-images.githubusercontent.com/57052760/133604032-7d2ea3c3-cb70-4f31-8d95-a2b287d67bdd.png)</span>](https://user-images.githubusercontent.com/57052760/133604032-7d2ea3c3-cb70-4f31-8d95-a2b287d67bdd.png)

### Command / Request

<pre>model_path = rasa.train(domain, config, <span class="error">[training]</span>, output)
 print(model_path)</pre>

### Relevant log output

 _No response_

**Comment by sara-tagger** [comment]
Thanks for the issue, @joejuzl will get back to you about it soon!

###### You may find help in the [docs](https://rasa.com/docs/) and the [forum,](https://forum.rasa.com/) too 🤗

**Comment by sourdurian** [comment]
Thank you! The notebook's been running for 12 hours and it's still running. I did go through some of the issues and I'm not sure if it's a memory problem like some users had. Any help will be appreciated. Thank you :)

**Comment by m-vdb** [comment]
Closing as stale
