### ISSUE TITLE
Success markers: validate markers config

### ISSUE THREAD

**Issue by aeshky** [RasaHQ/rasa#9659]
**Overview of solution:**
Implement a new function to validate the markers config file according to the set of conditions that we support.

The function can be named `validate_config`

It takes as input a markers config file in `yaml` and checks:
1) it is a valid yaml file.
2) the conditions described are ones that we support. 

If valid, it outputs true.
If invalid, throws an exception.  

See [implementation proposal](https://www.notion.so/rasa/Success-Markers-Implementation-Proposal-79cb6f2b96584387aef6ab5c60db4b4c) for project overview. 

**Definition of done:** 
- [x] new function implemented
- [x] new function tested

**Comment by m-vdb** [comment]
💡 @aeshky can you make sure to close issues instead of moving them to the "Done" column manually? The automation works this way: if you close the issue, it's automatically moved to "Done".

**Comment by aeshky** [comment]
@m-vdb 💯 will do.
