### ISSUE TITLE
Success markers: read config

### ISSUE THREAD

**Issue by aeshky** [RasaHQ/rasa#9664]
**Overview of solution:**
Implement a function to read the markers config file and produce an object containing the conditions. 

**Input:** yaml config file
**Output:** object containing conditions. 

See [implementation proposal](https://www.notion.so/rasa/Success-Markers-Implementation-Proposal-79cb6f2b96584387aef6ab5c60db4b4c) for project overview. 

**Definition of done:** 
- [x] function implemented 
- [x] function unit tested

**Comment by m-vdb** [comment]
💡 @aeshky can you make sure to close issues instead of moving them to the "Done" column manually? The automation works this way: if you close the issue, it's automatically moved to "Done".
