### ISSUE TITLE
convert from dialogflow not work

### ISSUE THREAD

**Issue by Armyanin** [RasaHQ/rasa#9669]
### Rasa Open Source version

2.8.6

### Rasa SDK version

2.8.2

### Rasa X version

 _No response_ 

### Python version

3.6

### What operating system are you using?

Linux

### What happened?

Dialog flow agent works great in Russian, but converter skip all intents

### Command / Request

<pre>(.env) <span class="error">[root@localhost rasa]</span># rasa train</pre>

### Relevant log output

<pre>The configuration for pipeline and policies was chosen automatically. It was written into the config file at 'config.yml'.
 /root/rasa/.env/lib64/python3.6/site-packages/rasa/shared/utils/io.py:97: UserWarning: No training examples found for dialogflow file data/bot/entities/OutstandingPeople.json!
 More info at [https://rasa.com/docs/rasa/migrate-from/google-dialogflow-to-rasa/](https://rasa.com/docs/rasa/migrate-from/google-dialogflow-to-rasa/)([https://rasa.com/docs/rasa/migrate-from/google-dialogflow-to-rasa/](https://rasa.com/docs/rasa/migrate-from/google-dialogflow-to-rasa/))
 /root/rasa/.env/lib64/python3.6/site-packages/rasa/shared/utils/io.py:97: UserWarning: No training examples found for dialogflow file data/bot/entities/Sevices.json!
 More info at [https://rasa.com/docs/rasa/migrate-from/google-dialogflow-to-rasa/](https://rasa.com/docs/rasa/migrate-from/google-dialogflow-to-rasa/)([https://rasa.com/docs/rasa/migrate-from/google-dialogflow-to-rasa/](https://rasa.com/docs/rasa/migrate-from/google-dialogflow-to-rasa/))
 /root/rasa/.env/lib64/python3.6/site-packages/rasa/shared/utils/io.py:97: UserWarning: No training examples found for dialogflow file data/bot/entities/Weight_class.json!
 ....
 all of entity
 /root/rasa/.env/lib64/python3.6/site-packages/rasa/shared/utils/io.py:97: UserWarning: No training examples found for dialogflow file data/bot/intents/Default Fallback Intent.json!
 More info at [https://rasa.com/docs/rasa/migrate-from/google-dialogflow-to-rasa/](https://rasa.com/docs/rasa/migrate-from/google-dialogflow-to-rasa/)([https://rasa.com/docs/rasa/migrate-from/google-dialogflow-to-rasa/](https://rasa.com/docs/rasa/migrate-from/google-dialogflow-to-rasa/))
 /root/rasa/.env/lib64/python3.6/site-packages/rasa/shared/utils/io.py:97: UserWarning: No training examples found for dialogflow file data/bot/intents/Default Welcome Intent.json!
 ....
 all of intents</pre>

Path 'data' doesn't contain valid NLU data in it. Please verify the data format. The NLU model training will be skipped now.

**Comment by sara-tagger** [comment]
Thanks for raising this issue, @hsm207 will get back to you about it soon✨

###### Please also check out the [docs](https://rasa.com/docs/) and the [forum](https://forum.rasa.com/) in case your issue was raised there too 🤗

**Comment by Armyanin** [comment]
@hsm207 ?

**Comment by Armyanin** [comment]
Any body here?
