### ISSUE TITLE
Untrained utterances giving very high confidence

### ISSUE THREAD

**Issue by PranitModak** [RasaHQ/rasa#9697]
### Rasa Open Source version

2.7.1

### Rasa SDK version

2.8.2

### Rasa X version

None

### Python version

3.7

### What operating system are you using?

Linux

### **Config File** 

language: en

pipeline:

*   name: "WhitespaceTokenizer"
*   name: "RegexFeaturizer"
*   name: "CountVectorsFeaturizer" analyzer: "word" min_ngram: 1 max_ngram: 1
*   name: "DIETClassifier" epochs: 300
*   name: FallbackClassifier threshold: 0.4 ambiguity_threshold: 0.1
*   name: "EntitySynonymMapper"

policies:

*   name: TEDPolicy max_history: 5 epochs: 200 batch_size: 50 max_training_samples: 300
*   name: MemoizationPolicy
*   name: RulePolicy

########################################################################################

### **Nlu File** 

version: '2.0' nlu:

*   intent: greetings_how_r_u examples: |

*   *   how are you getting on
    *   how is your day going
    *   how do you do
    *   how are you
*   intent: greetings_hello examples: |

*   *   hi bot
    *   hi there
    *   hey there
    *   hey bot
*   intent: hours_min examples: |

*   *   what is the time now
    *   What time is it?
    *   what is the time
    *   can you tell time
*   intent: month_date examples: |

*   *   what date is it
    *   what is the date today
    *   what is the current date

1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  Upon testing it with random gibberish utterances like ahdsghaasd lkjlhthrt kj2131kj

or even meaningful inputs like cricket station michael

All of these give result with _**greetings_hello**_ with confidence of _**0.99981**_ ... But none of these are trained for this intent. In RASA documentation it is mentioned [<span class="image-wrap" style="">![](https://user-images.githubusercontent.com/43670565/134369426-e2db5ed9-38fc-4ea3-8119-4935bfc210ec.png)</span>](https://user-images.githubusercontent.com/43670565/134369426-e2db5ed9-38fc-4ea3-8119-4935bfc210ec.png)

Please let us know if there is a fix for it. As in RASA forum multiple issues are logged but none with a fix.

[https://forum.rasa.com/t/nlu-detects-random-input-with-wrong-intent-and-high-confidence/620](https://forum.rasa.com/t/nlu-detects-random-input-with-wrong-intent-and-high-confidence/620) [https://forum.rasa.com/t/getting-high-intent-confidence-for-untrained-bot-utterances/47863](https://forum.rasa.com/t/getting-high-intent-confidence-for-untrained-bot-utterances/47863) [https://forum.rasa.com/t/nlu-classifies-unseen-utterances-to-a-random-intent-with-too-high-confidence/30920/3](https://forum.rasa.com/t/nlu-classifies-unseen-utterances-to-a-random-intent-with-too-high-confidence/30920/3)

### Command / Request

 _No response_ 

### Relevant log output

<pre>NLU model loaded. Type a message and press enter to parse it.
 Next message:
 hsfgkafkj
 {
 "text": "hsfgkafkj",
 "intent": 

 { "id": -8136514114303540795, "name": "greetings_hello", "confidence": 0.9997071623802185 } 

,
 "entities": [],
 "original_message": "hsfgkafkj",
 "jargons": "",
 "intent_ranking": [

 { "id": -8136514114303540795, "name": "greetings_hello", "confidence": 0.9997071623802185 } 

,

 { "id": 3423598827860960927, "name": "month_date", "confidence": 0.00025602238019928336 } 

,

 { "id": 6437568250573851262, "name": "greetings_how_r_u", "confidence": 3.497721263556741e-05 } 

,

 { "id": -2334321692795301928, "name": "hours_min", "confidence": 1.7791187474358594e-06 } 

 ]
 }

Next message:
 michael
 {
 "text": "michael",
 "intent": 

 { "id": -8136514114303540795, "name": "greetings_hello", "confidence": 0.9997071623802185 } 

,
 "entities": [],
 "original_message": "michael",
 "jargons": "",
 "intent_ranking": [

 { "id": -8136514114303540795, "name": "greetings_hello", "confidence": 0.9997071623802185 } 

,

 { "id": 3423598827860960927, "name": "month_date", "confidence": 0.00025602238019928336 } 

,

 { "id": 6437568250573851262, "name": "greetings_how_r_u", "confidence": 3.497721263556741e-05 } 

,

 { "id": -2334321692795301928, "name": "hours_min", "confidence": 1.7791187474358594e-06 } 

 ]
 }</pre>

**Comment by sara-tagger** [comment]
Thanks for raising this issue, @kedz will get back to you about it soon✨

###### Please also check out the [docs](https://rasa.com/docs/) and the [forum](https://forum.rasa.com/) in case your issue was raised there too 🤗

**Comment by kedz** [comment]
Thanks for the bug report @PranitModak ! I'm putting this into our issue inbox so we can determine its priority next week.

**Comment by kedz** [comment]
Note for inbox triaging: I was able to reproduce the reported behavior.
