### ISSUE TITLE
asyncio.exceptions.TimeoutError due to dependency problems

### ISSUE THREAD

**Issue by jsalbr** [RasaHQ/rasa#9703]
### Rasa Open Source version

2.8.7 (same with 2.8.0)

### Rasa SDK version

2.8.2

### Rasa X version

 _No response_ 

### Python version

3.8

### What operating system are you using?

Linux

### What happened?

I tried to transfer a running chatbot to a new machine, but got the error below. The reasons was a dependency problem.

Setting: newly created machine, Ubuntu 20.04, Python 3.8.10\. Then, in a blank venv, "pip install rasa<span class="error">[full]</span>".

Running rasa shell I got the following error:

ERROR asyncio - Task exception was never retrieved future: <Task finished name='Task-2' coro=<configure_app..run_cmdline_io() done, defined at /var/venv/rasa28/lib/python3.8/site-packages/rasa/core/run.py:131> exception=TimeoutError()> Traceback (most recent call last): File "/var/venv/rasa28/lib/python3.8/site-packages/rasa/core/run.py", line 135, in run_cmdline_io await console.record_messages( File "/var/venv/rasa28/lib/python3.8/site-packages/rasa/core/channels/console.py", line 182, in record_messages async for response in bot_responses: File "/var/venv/rasa28/lib/python3.8/site-packages/rasa/core/channels/console.py", line 137, in _send_message_receive_stream async for line in resp.content: File "/var/venv/rasa28/lib/python3.8/site-packages/aiohttp/streams.py", line 39, in **anext** rv = await self.read_func() File "/var/venv/rasa28/lib/python3.8/site-packages/aiohttp/streams.py", line 338, in readline await self._wait("readline") File "/var/venv/rasa28/lib/python3.8/site-packages/aiohttp/streams.py", line 306, in _wait await waiter File "/var/venv/rasa28/lib/python3.8/site-packages/aiohttp/helpers.py", line 656, in **exit** raise asyncio.TimeoutError from None asyncio.exceptions.TimeoutError

This problem was reported before several times in the rasa forum and on github, but there does not yet seem to be a solution. All solutions reported there did not work for me.

Since I had a machine with the same bot running, I was able to analyze the differences in the installed packages and track the problem in my case down to this solution: `pip install jsonpickle==1.4.2`

`pip install rasa<span class="error"><span class="error">[full]</span></span>` installed `jsonpickle==2.0.0` in my blank venv per default.

This error is incredibly hard to identify and it took me a complete day to solve it. It would be great, if `pip install rasa` was working out of the box. Hope, this reports helps to find a solution.

I use the following pipeline in the bot:

pipeline:

1.  No configuration for the NLU pipeline was provided. The following default pipeline was used to train your model.
2.  If you'd like to customize it, uncomment and adjust the pipeline.
3.  See [https://rasa.com/docs/rasa/tuning-your-model](https://rasa.com/docs/rasa/tuning-your-model) for more information.

*   name: WhitespaceTokenizer
*   name: LanguageModelFeaturizer

1.  Name of the language model to use model_name: "bert"

1.  Pre-Trained weights to be loaded model_weights: "rasa/LaBSE"

1.  An optional path to a specific directory to download and cache the pre-trained model weights.

1.  The `default` cache_dir is the same as [https://huggingface.co/transformers/serialization.html#cache-directory](https://huggingface.co/transformers/serialization.html#cache-directory) . #cache_dir: null

*   name: SklearnIntentClassifier
*   name: FallbackClassifier threshold: 0.4 ambiguity_threshold: 0.1

### Command / Request

 _No response_ 

### Relevant log output

 _No response_

**Comment by sara-tagger** [comment]
Thanks for raising this issue, @TyDunn will get back to you about it soon✨

###### Please also check out the [docs](https://rasa.com/docs/) and the [forum](https://forum.rasa.com/) in case your issue was raised there too 🤗

**Comment by jsalbr** [comment]
One addition: Same behaviour on Windows.
