### ISSUE TITLE
Cannot start rasa run actions

### ISSUE THREAD

**Issue by dengqiqi123** [RasaHQ/rasa#9717]
### Rasa Open Source version

1.0.3

### Rasa SDK version

1.0.0

### Rasa X version

 _No response_ 

### Python version

3.7

### What operating system are you using?

Windows

### What happened?

rasa_sdk.endpoint - Action endpoint is up and running. on ('0.0.0.0', 5055)

### Command / Request

<pre>rasa run actions</pre>

### Relevant log output

<pre>2021-09-26 14:05:17 INFO rasa_sdk.endpoint - Starting action endpoint server...
 2021-09-26 14:05:17 INFO rasa_sdk.executor - Registered function for 'action_hello_world'.</pre>

**Comment by sara-tagger** [comment]
Thanks for raising this issue, @jupyterjazz will get back to you about it soon✨

###### Please also check out the [docs](https://rasa.com/docs/) and the [forum](https://forum.rasa.com/) in case your issue was raised there too 🤗

**Comment by ceromero05** [comment]
test comment to see how this entry arrives into GH => Jira

**Comment by rasabot-exalate** [comment]
Christine Romero commented: 

test comment to see how this entry arrives into GH => Jira

**Comment by ceromero05** [comment]
another comment in Jira

**Comment by ceromero05** [comment]
test

**Comment by m-vdb** [comment]
Closing as stale
