### ISSUE TITLE
Investigate and address OOM for Windows + `test-nlu-predictors` on CI with TF 2.6

### ISSUE THREAD

**Issue by koernerfelicia** [RasaHQ/rasa#9734]
When we upgraded to TF 2.6, the `test-nlu-predictors` and `test-other-unit-tests` tests on Windows CI failed due to OOM. Since the upgrade is urgent, the  _temporary_  workaround was to lower JOBS to 1 for these tests (as opposed to 2), bringing the memory consumption below the limit of the runners.

We should investigate how to reduce the memory consumption of these tests, so that the tests for this configuration can be run in parallel again.

Please reach out to someone from Infra for support in using DataDog to investigate these.

*Definition of Done*

* [ ] fix is found such that [this change| https://github.com/RasaHQ/rasa/pull/9733] can be reverted

**Comment by markus-hinsche** [comment]
The following PRs will tackle this issue:
* https://github.com/RasaHQ/rasa/pull/11001
* https://github.com/RasaHQ/rasa/pull/10994
* https://github.com/RasaHQ/rasa/pull/10992
