### ISSUE TITLE
how  deal with  Keyword filtering?

### ISSUE THREAD

**Issue by levine2008** [RasaHQ/rasa#9738]
### What problem are you trying to solve?

how  deal with  Keyword filtering?

**Comment by levine2008** [comment]
@fungiboletus @sheldon @tjpalmer @alopez

**Comment by alopez** [comment]
@levine2008 this looks like a "how to?" question, which should be posted on the [forum](https://forum.rasa.com/). When asking questions, please supply as much concrete information as possible about the problem you're trying to solve (e.g. the input and output you expect) and you'll be much more likely to receive helpful answers.
