### ISSUE TITLE
rasa chat widget issues

### ISSUE THREAD

**Issue by georgebrianb** [RasaHQ/rasa#9739]
### Rasa Open Source version

2.8.1

### Python version

3.8

### What operating system are you using?

Linux

### What happened?

When adding the rasa chat widget to any page (static, wordpress site, doesn't matter) the classes added to increase the width and height of the chatbox, or the one to have it open by default, do not work.

What happens is that when I add the width/height labels, clicking the chat bubble will no longer expand the chatbox.
Also, the data-default-open does not work at all - it will not open the chatbox by default.

### Command / Request

```shell
Code added on page:


<div data-height={500} data-width={300} data-default-open  data-primary="#e58282" data-root-element-id="storybook-preview-wrapper" data-websocket-url="http://172.17.0.1/socket.io" id="rasa-chat-widget"></div>
<script src="https://unpkg.com/@rasahq/rasa-chat" type="application/javascript"></script>
```
Color of the chatbox is changed, but other attributes are not working as expected.

As specified above, this has been tested on Wordpress (adding the script to the footer/header of the website using "Install Headers and Footers" plugin) and on a static HTML file, adding the script both in the body and the footer/header sections. The script was not added in all places at once, I made sure to remove the script from one section when trying in another section.
```


### Relevant log output

_No response_

**Comment by hsm207** [comment]
What happens if you try this? Remember to update `data-websocket-url` to match your environment:

```html
<div id="rasa-chat-widget" data-websocket-url="http://localhost:5005/" data-default-open="true" data-height="500" data-width="1250"></div>
<script src="https://unpkg.com/@rasahq/rasa-chat" type="application/javascript"></script>
```
