### ISSUE TITLE
Rasa Chat widget - remove shadow toggle

### ISSUE THREAD

**Issue by georgebrianb** [RasaHQ/rasa#9740]
### What problem are you trying to solve?

Hi, when using rasa chat widget with darker backgrounds, there's some kind of shadow/blur around the bottom half of the bubble. 
It would be really helpful to have a toggle for that, as right now, on darker backgrounds it looks very bad, giving it a bad quality feeling:

Different backgrounds where this happens:
![image](https://user-images.githubusercontent.com/32679117/135246948-38e674a4-3a3f-4936-a6ca-1ab1144a2621.png)
![image](https://user-images.githubusercontent.com/32679117/135247285-9f84027b-27d4-4580-bccf-86746734e228.png)

Backgrounds where it doesn't happen or it doesn't look bad on:
![image](https://user-images.githubusercontent.com/32679117/135247255-ad84adfe-cee6-49ee-8c1b-414139060ec4.png)
![image](https://user-images.githubusercontent.com/32679117/135247421-de04dd99-50f8-4c28-becd-ead3e5cac2fe.png)

### What's your suggested solution?

Add a toggle to disable blur/shadow

### Definition of Done

A toggle that disables that blur/shadow.

**Comment by hsm207** [comment]
Have you tried configuring the `box-shadow` property of the widget using a CSS stylesheet?

**Comment by georgebrianb** [comment]
0 experience as web developer, didn't think of that. It works as expected. Although the feature would be good to have. This can be closed for now.

**Comment by georgebrianb** [comment]
After checking. This might not be the best workaround, as the class that has to be modified is changing its name depending on when the page has been reloaded.

The name of the class that sets the box-shadow property has randomly changing names similar to ".css-8jahf", the part after the dash being the one that changes.

So the toggle would be a nice addition to have. Although this is not a pressing issue.

**Comment by georgebrianb** [comment]
This is a good workaround. Until the toggle is added, I consider this solved. Thanks a lot!
