### ISSUE TITLE
Rasa chat widget - initialPayload feature? 

### ISSUE THREAD

**Issue by georgebrianb** [RasaHQ/rasa#9743]
### What problem are you trying to solve?

Given that many people were integrating rasa on their website using [this](https://github.com/botfront/rasa-webchat) widget, some of us are probably used to specifying the initial payload that gets sent when the user first opens the chat bubble.
The current rasa chat widget available [here](https://chat-widget-docs.rasa.com/?path=/docs/rasa-chat-widget--widget) completely lacks this feature (maybe I've missed it?).

### What's your suggested solution?

Add a property where the developer can specify the initial payload sent, exactly like in the botfront's chat widget. 

### Examples (if relevant)

It looks like this:
![image](https://user-images.githubusercontent.com/32679117/135255454-c0586b55-0087-4b36-81bd-fb0f36d2fa47.png)

### Is anything blocking this from being implemented? (if relevant)

Don't think so.
Must be thought well enough so it won't trigger when loading the page where the chatbox is, but when the chat bubble is clicked for the first time.

### Definition of Done

When a property with the name "initial-payload" or something similar can be set like this: `initial-payload="/start_conversation"` (or similar to this)

**Comment by sara-tagger** [comment]
Thanks for submitting this feature request 🚀 @b-quachtran will get back to you about it soon! ✨

**Comment by sorkinl** [comment]
Is there a separate repository with widget code? I would be happy to work on this issue.

**Comment by rgstephens** [comment]
@gausie I'm also running into this issue. Do you know if there are any plans to open source the widget?

**Comment by georgebrianb** [comment]
Would be cool to have the option of an open-source chatbox client
    On Wednesday, December 15, 2021, 03:48:58 AM GMT+2, Greg Stephens ***@***.***> wrote:  
 
 


@gausie I'm also running into this issue. Do you know if there are any plans to open source the widget?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by georgebrianb** [comment]
Would love to see an update on this! Thank you!

**Comment by amn41** [comment]
we just released `rasa-chat v0.1.2` which fixes this issue.
