### ISSUE TITLE
Create `SlotExtractionToHistoryAdder` graph component

### ISSUE THREAD

**Issue by ancalita** [RasaHQ/rasa#9745]
**Overview of the Solution**
This graph component `SlotExtractionToHistoryAdder` (better naming suggestions are welcome) would perform what currently is implemented in `MessageProcessor.handle_message()` to run default `action_extract_slots` after every user turn (on `global-slot-mappings-3.0` branch).

**Input to the component**: 
- `EndpointConfig` instance (i.e, the `action_endpoint`)
- `DialogueStateTracker` (from `NLUPredictionToHistoryAdder`?)
-  `Domain`
- `NaturalLanguageGenerator`
- `OutputChannel`

**Output of the component**: Updated tracker with events resulting from running `action_extract_slots`.

**Definition of Done**:
- [ ] Component is implemented and unit tested
- [ ] Create potential integration issue for testing the entire flow after the integration

**Comment by alwx** [comment]
Closing this one because we decided to split NLU and Core prediction. More details: https://github.com/RasaHQ/rasa/pull/9790#issuecomment-944153990
