### ISSUE TITLE
Fallback policy if the response selector has a lower confidence

### ISSUE THREAD

**Issue by DanielOlarte** [RasaHQ/rasa#9751]
### What problem are you trying to solve?

When we use a Response Selector for FAQ, sometimes Rasa gets the FAQ intent with a confidence of 1.0, but when, we check the internal confidence of the intents on the Response Selector, the confidences scores are very low (0.2, 0.3), which makes the bot answer incorrectly.

[https://forum.rasa.com/t/how-can-set-a-fallback-policy-if-the-response-selector-has-a-lower-confidence-level/40420](https://forum.rasa.com/t/how-can-set-a-fallback-policy-if-the-response-selector-has-a-lower-confidence-level/40420)

### What's your suggested solution?

Add a configuration setting on the Response Selector to set the confidence threshold for the responses and if none of the FAQs go over that threshold, go to the fallback policy (if available)

### Examples (if relevant)

 _No response_ 

### Is anything blocking this from being implemented? (if relevant)

 _No response_ 

### Definition of Done

 _No response_

**Comment by sara-tagger** [comment]
Thanks for submitting this feature request 🚀 @desmarchris will get back to you about it soon! ✨
