### ISSUE TITLE
Make rasa cli  have an option to turn off colors

### ISSUE THREAD

**Issue by hsm207** [RasaHQ/rasa#9757]
### What problem are you trying to solve?

I want to ran `rasa data validate` in my pipeline and print the results as a comment in a PR. I save the results in a file like this:

 rasa data validate --quiet 2>&1 | tee data-validate.log

The problem is that the ANSI code are saved as part of the output and it makes the results hard to read.

The workaround is to do this:

 rasa data validate --quiet 2>&1 | tee data-validate.log | \
 sed 's/\x1b[<span class="error">[0-9;]</span>*m//g' > \
 data-validate-no-color.log

### What's your suggested solution?

rasa data validate --no-colors

### Examples (if relevant)

 _No response_ 

### Is anything blocking this from being implemented? (if relevant)

No

### Definition of Done

`data-validate.log` from `rasa data validate --no-colors --quiet 2>&1 | tee data-validate.log` does not have ANSI color code.

**Comment by thiagohdaqw** [comment]
Hi there
Is this still relevant? I think i can work on it

**Comment by virtualroot** [comment]
Please consider using `NO_COLOR` envvar.

https://no-color.org/

**Comment by thiagohdaqw** [comment]
This is a good name for an envvar. It is also used in coloredlogs to disable colors. Thanks, @virtualroot!

https://coloredlogs.readthedocs.io/en/latest/api.html?highlight=no_color#environment-variables
