### ISSUE TITLE
`Validator` flags form `None` in rules/stories is not present in domain when running `rasa data validate`

### ISSUE THREAD

**Issue by ancalita** [RasaHQ/rasa#9758]
**Overview of the problem** If a rule such as the one in the below example is present in `rules.yml`, running `rasa data validate` will result in error `The form 'None' is used in the 'submit subscription' block, but it is not listed in the domain file. You should add it to your domain file!`

Rule example:

*   rule: submit subscription condition:
*   active_loop: subscription_form steps:
*   action: subscription_form
*   active_loop: null
*   slot_was_set:
*   requested_slot: null
*   action: utter_subscribed

**Definition of Done**

*   [ ] bug fix is implemented and unit tested

**Comment by rgstephens** [comment]
The helpdesk-assistant runs into this issue [here](https://github.com/RasaHQ/helpdesk-assistant/blob/2e9f2258c6648488bd02af86ea2803de5a9fde04/data/rules.yml#L27).

**Comment by alexrun** [comment]
Probably we should include a test case for this in the https://github.com/RasaHQ/rasa/blob/main/tests/test_validator.py file

**Comment by alexrun** [comment]
As seen in https://github.com/RasaHQ/rasa/issues/10447 this issue is still happening.

**Comment by ancalita** [comment]
Fixed in #10562, released in version `3.0.9`
