### ISSUE TITLE
Easier to find debug messages when debugging policies

### ISSUE THREAD

**Issue by desmarchris** [RasaHQ/rasa#9760]
### What problem are you trying to solve?

I find myself spending a lot of time sifting through debug logs in `rasa shell -vv` trying to find the right line for where things went wrong.

Also, I'm testing in the shell because my failed test stories just tell me _what_ was predicted, not _why_ .

### What's your suggested solution?

few different options:

*   more debug info in failed test story reports
*   bold / color differently the more important logs in `rasa shell -vv` (like what policy was eventually used)

### Examples (if relevant)

 _No response_ 

### Is anything blocking this from being implemented? (if relevant)

 _No response_ 

### Definition of Done

 _No response_

**Comment by erohmensing** [comment]
I wonder if it would be helpful to figure out what should be `INFO` versus `DEBUG`. The default could still be >=warning only, but in addition to `rasa shell --debug`, there could be something like `rasa shell --info` which could show only the basics like what message was received and how it was classified, and what action was chosen and the policy that chose that action 🤔
