### ISSUE TITLE
Setting Slots from Dropdown in RASA

### ISSUE THREAD

**Issue by olahsymbo** [RasaHQ/rasa#9761]
### Rasa Open Source version

2.7.0

### Rasa SDK version

2.7.0

### Rasa X version

 _No response_ 

### Python version

3.7

### What operating system are you using?

Linux

### What happened?

Trying to set slots from dropdown options in RASA. Currently I'm using the dropdown from this [Chatbot Widget](https://github.com/JiteshGaikwad/Chatbot-Widget)

However when i select the options from the webchat the slot is always set to `None`.

I have created slot in domain.yml,

slots: game_name: type: any

entities:

*   game_name

and also created an intent

*   intent: game_option examples: |
*   <span class="error">[Access Platc]</span>(game_name)
*   <span class="error">[Citk Platc]</span>(game_name)
*   <span class="error">[Diamond Platc]</span>(game_name)

and in stories.yml, I set this:

*   intent: game_option
*   slot_was_set:
*   game_name

I dont understand why it's still returning `None`

My response is from custom actions and looks like this:

class ActionListGames(Action): def name(self) -> Text: return "action_list_games"

def run(self, dispatcher: CollectingDispatcher, tracker: Tracker, domain: Dict<span class="error">[Text, Any]</span>) -> List[Dict<span class="error">[Text, Any]</span>]:

response_games = requests.get("[https://www.gamexn.com/api/v2/games](https://www.gamexn.com/api/v2/games)") processed_output = json.load(io.BytesIO(response_games.content))<span class="error">['data']</span><span class="error">['games']</span>

games = [ { "label": row<span class="error">['gameName']</span>, "value": "/game_option

 {"game_name": "" + row['gameCode'] + ""} 

" } for row in processed_output ] message =

 {"payload": "dropDown", "data": games} 

dispatcher.utter_message(text="Please select a game option:", json_message=message) return []

I dont know why its still returning None.

### Command / Request

 _No response_ 

### Relevant log output

 _No response_

**Comment by sara-tagger** [comment]
Thanks for raising this issue, @mvielkind will get back to you about it soon✨

###### Please also check out the [docs](https://rasa.com/docs/) and the [forum](https://forum.rasa.com/) in case your issue was raised there too 🤗

**Comment by olahsymbo100** [comment]
@sara-tagger do you have any update regarding this?

**Comment by m-vdb** [comment]
Closing as stale
