### ISSUE TITLE
Make changes to weizenbot to fit the new envisioned workflow

### ISSUE THREAD

**Issue by dakshvar22** [RasaHQ/rasa#9772]
### What problem are you trying to solve?

We changed the workflow for using weizenbot and the new workflow is written out [here](https://www.notion.so/rasa/Weizenbot-GPT-3-User-Simulation-for-SuperAirlineBot-600332a5607d4aff8ad0e583fffa22c4#3d4077c020214e1b8b0bdde09c979f71)

The weizenbot scripts for super-airline-bot should be tweaked to support the new workflow

### What's your suggested solution?

Change the weizenbot script to mock the conversation until the breaking point by not querying the OpenAI API but using the user messages from the conversation template and then carry out the complete conversation by actually querying the API.

**Comment by dakshvar22** [comment]
Here's the high level description of the approach I am taking:

The context stories are written out as E2E stories in rasa's yaml format. For example:

```
story: "context 1\nDoes delimiter work here?\nYes, but it's not super convenient tbh but nobody said it was easy."
  steps:
  - user: Hello book a flight?
  - bot: where would you like to book the flight from?
  - user: Washington
  - bot: How about this, does this sound good?
```

We effectively use the `story` key to write out the parts of the prompt which will change depending on the destination and arrival cities. An example prompt would look like:

```
USER wants to travel coming Monday.

USER wants to travel to San Francisco from Skopje.

USER wants to know what the weather will be like in San Francisco on Monday so that they don't travel in bad weather. So, USER can check the weather before booking the flight.

USER's name is John Doe.


A new conversation starts like this:
```

The preamble of the prompt which contains general instructions will still be inserted from the script:

```
This is a conversation between a USER and an AI assistant. The USER is trying to search for a flight between any European capital and US capitals. The USER tries to book the flight if it's preferable. The USER does a lot of things to confuse the assistant:
1. Be creative and construct complex queries for the assistant.
2. Comes up with complex ways to express their own name.
3. Comes up with different destination and arrival cities and complex ways to express them.

The USER may also deny the flight option because of various reasons:
1. The flight being too expensive, for example a business class flight
2. The flight may be too early in the morning or too late at night.
3. The flight may be too long.

The USER can also ask for the weather at the destination city and choose to not travel if the weather is not preferable, for example too hot or thunderstorms or rainy.
```

If we want to add more instructions to the prompt (for e.g. - situation of the user, behavioral characteristics of the user) , they should be added at the beginning of the context provided as part of the story.

It would have been ideal to use the `metadata` key to do this but [sadly it is not possible to do so](https://rasa-hq.slack.com/archives/C01HHMR4X8S/p1633337377099900).

Now inside the script, `gather_experiments` will read this file. The pseudo-code for it would look like this:

```
def gather_experiments():

   ....
   context_stories = read_context_stories(...)
   for story in context_stories:
        prompt_config = {"initial_prompt": story.block_name, "mock_events": story.events}
        goal, user_prompt, prompt_config = construct_prompt(
            prompt_generator, prompt_config
        ).  ### This is only needed to get the preamble of the prompt now, I think
        num_user_turns_to_mock = get_num_user_turns_to_mock(story)
        for num_conversations in range(m):
               ....
               prompt_config["num_user_turns_to_mock"] = num_user_turns_mock
               prompt_config["turns"] = 0
               user.set_metadata(**prompt_config)
```

`user_turn_callback` will look something like this:

```
def user_turn_callback(
        user_interface,
        conversation_id,
        goal_recorder,
        domain,
        tracker,
        new_events_and_slots,
    ):

    user_turn_number = user_interface.metadata["turns"]
    num_turns_to_mock = user_interface.metadata["num_user_turns_to_mock"]
    if user_turn_number < num_turns_mock:
         corresponding_user_event = get_user_event_at_turn(user_interface.metadata["mock_events"], user_turn_number)
         return corresponding_user_event.text
    else:
         <query api>

    user_interface.metadata["turns"] += 1
```

**Comment by koernerfelicia** [comment]
I'm a little confused by this part:
```
If we want to add more instructions to the prompt (for e.g. - situation of the user, behavioral characteristics of the user) , they should be added at the beginning of the context provided as part of the story.`
``
What do you mean added at the beginning of the context provided as part of the story? You mean it would have to go into the story key?

Also, I'm assuming this will work with stories grabbed from rasa X or something (provided they're in end to end format)?

**Comment by dakshvar22** [comment]
> What do you mean added at the beginning of the context provided as part of the story? You mean it would have to go into the story key?

> Also, I'm assuming this will work with stories grabbed from rasa X or something (provided they're in end to end format)? 

Do you mean the story generated on the side of the conversation screen? I think yes that should also work. However, I didn't want to adopt the intent-action pair style story format to define a context story because then that would prescribe an intent to user utterances. The only thing you'll have to do (in case you take a story from Rasa X) is construct the `story` key for it.

**Comment by koernerfelicia** [comment]
Ahh sorry I meant [this format](https://rasa.com/docs/rasa/testing-your-assistant/). I thought this was end to end testing but I think that's the wrong terminology.. We could ignore the intent, right? Then I could generate the stories by talking to the baseline bot (not that I always will, but just as an option) and export the stories as test stories, right? Or how would you envisage that part?

**Comment by dakshvar22** [comment]
Right, you can still do that. The script will take only the text of the `UserUttered` event coming from the parsed story. So, as long as that is present, the script should work. Does that seem fine?

**Comment by koernerfelicia** [comment]
Yes, perfect! Then that pretty much aligns with what I had sketched out in my head, as well.
