### ISSUE TITLE
Check slot names before training

### ISSUE THREAD

**Issue by mohammad-albarham** [RasaHQ/rasa#9813]
### What problem are you trying to solve?

When run the training it shows this error `ERROR    rasa.shared.core.trackers  - Tried to set non existent slot 'requesteds_slot'. Make sure you added all your slots to your domain file.`. This error states there is a typo on the slot or there is a non exist slot you want to set.

### What's your suggested solution?

So, It will be useful to check the slots name in `rules.yml` before training through any commons let's say through `rasa data validate` or a new command.

### Examples (if relevant)

```py  
- rule: Submit Registration form
    condition:
      # Condition that form is active.
      - active_loop: simple_reg_form
    steps:
      # Form is deactivated
      - action: simple_reg_form
      - active_loop: null
      - slot_was_set:
      # Here is the typo
          - required_slot: null
        # The actions we want to run when the form is submitted.
      - action: utter_submit
```

### Definition of Done

start training the model without any error that will interrupt the training.

**Comment by sara-tagger** [comment]
Thanks for submitting this feature request 🚀 @yennycheung will get back to you about it soon! ✨
