### ISSUE TITLE
Improve the E2E and non E2E bots with data from `conversation set A`

### ISSUE THREAD

**Issue by dakshvar22** [RasaHQ/rasa#9831]
- Use conversations labelled as `conv-set-A` to improve the respective bots.
- Numbers on the baseline performance of the bot will be given by https://github.com/RasaHQ/rasa/issues/9778
- Rules to improve the bot are documented here https://www.notion.so/rasa/A-dry-run-WIP-919147e17c56423ba550b9754a61a82b
- Developers can use the context stories used to produce `conv-set-A` to produce more conversations to test their improved versions of the bot.

Definition of Done:

- [x] Respective Rasa X instances ready with the improved bot.
- [x] Run one last user simulation round with GPT-3 involving all the context stories corresponding to `conv-set-A` and measure the performance of the bot. Use the same performance metrics that were used to measure the performance of the baseline bot.
- [x] Report statistics on training time (on the same google cloud machine), ~~memory footprint~~
- [x] Qualitative assessment of the process followed in improving the bot, i.e. - 
```
- "How easy is it to make my bot do what I want at any place in the dialogue" (is fixing it easy)
- "Do I need to fix much" (how well does the bot generalize to new situations)
- Anything else on how still the bot breaks
```

**Comment by JEM-Mosig** [comment]
Training Time: I'm running training of the bots on [this GCP machine](https://console.cloud.google.com/compute/instancesDetail/zones/europe-west1-b/instances/johannes-e2e-performance?project=rasa-research):
```
n1-highmem-4
Intel Haswell
1 x NVIDIA Tesla K80
64GB RAM
```
## intent-bot (r1)
* NLU: 18 min 40 s
* Core: 1 min 1 s
* Total: 19 min 59 s

## e2e-bot (r1)
* NLU: 4 min 3 s
* Core: 23 min 38 s
* Total: 27 min 52 s

**Comment by dakshvar22** [comment]
@JEM-Mosig I think for Core we should separate out the amount of time needed during "Processing Trackers" v/s the amount of time taken for actual training of the policy. I'm concerned that the above results does not reflect the fact that majority of the time when training Core for E2E bot goes in checkpoint processing.
Wdyt?

**Comment by JEM-Mosig** [comment]
Ah, good point. I'll run it again on Monday

**Comment by JEM-Mosig** [comment]
Ok, again. I tried to extract the individual training times from the log. We print all kinds of things in the debug log, but not what is being trained (even with --debug). So I used the time between "The provided batch size is a list, this data generator will use a linear increasing batch size." and "Core model training completed" to get the time for TED.

### intent-bot (r1)
* DIET: 18 min 43 s
* Not TED: 22 s
* TED: 1 min 2 s
* Total: 20 min 7 s

### e2e-bot (r1)
* DIET: 3 min 35 s
* Not TED: 13 min 56 s
* TED: 10 min 9 s
* Total: 27 min 40 s

**Comment by dakshvar22** [comment]
@JEM-Mosig Please add a link to the above comment to the research abstract and then we are good to close the issue.
