### ISSUE TITLE
Round of conversation collection with real user talking to improved bots

### ISSUE THREAD

**Issue by dakshvar22** [RasaHQ/rasa#9834]
Should be done after https://github.com/RasaHQ/rasa/issues/9831

The human sends the exact same messages to each bot and decides which bot did better if their responses differ. Ideally, the human doesn't know which bot is the one using e2e. If responses differ, both conversations are continued until conclusion

Definition of Done:
- [x] Talk to the two improved bots from the issue linked above. Use `conv-set-B` for inspiration on what can potentially break the bots. Number of conversations ~ 60
- [ ] Measure performance of the improved bots using the same performance metric used to measure the baseline bot. @JEM-Mosig to add it to a notion page
~~- [ ] Qualitative assessment on how the two bots break.~~ (transferred to https://github.com/RasaHQ/research/issues/234)

**Comment by koernerfelicia** [comment]
Un-assigning myself because I believe my part of this is done, please correct me if wrong!

**Comment by JEM-Mosig** [comment]
Result metrics of first round are here: https://www.notion.so/rasa/Performance-Measures-How-we-Compare-Assistants-18f685c61ba64c0fbacb467f8eaf9648#c0f7fc10080645f5817e7b6cbed9b94a
