### ISSUE TITLE
Readable Error message when there is an error in custom channels

### ISSUE THREAD

**Issue by LEAGUEDORA** [RasaHQ/rasa#9842]
### What problem are you trying to solve?

Hi!

Suppose I have a python code which is called `modified_telegram.py` which imports some constants from 'constants.py'. But due to any reason that `constants.py` threw an error, RASA explicitly shows **RASA Exception..... Failed to import ..... Check the spelling and correct class name of the package.**

So technically, the error message states that the error is in the name. But NO. Some other parent code is creating an issue. There is a traceback, but I suggest them a meaningful error

### What's your suggested solution?

I suggest RASA provide a meaningful message that the script `modified_telegram.py` has some issues registering with sanic. Please check the log

### Examples (if relevant)

 _No response_ 

### Is anything blocking this from being implemented? (if relevant)

 _No response_ 

### Definition of Done

The thing is said done when the developer gets an error message like "We are able to identify the package, But couldn't register with us, since there is something wrong in the file"

Thanks

**Comment by sara-tagger** [comment]
Thanks for submitting this feature request 🚀 @degiz will get back to you about it soon! ✨
