### ISSUE TITLE
tracker.get_slot returns None even tho slot value is set

### ISSUE THREAD

**Issue by usernamedidnotfi** [RasaHQ/rasa#9845]
### Rasa Open Source version

2.8.5

### Rasa SDK version

 _No response_ 

### Rasa X version

 _No response_ 

### Python version

3.8

### What operating system are you using?

Linux

### What happened?

I am running Rasa in Docker, along with MySQL as a TrackerStore + custom actions. Everything seems to be working fine, but there is an issue with slots. When I try to set slot, its set just for the very moment. Whenever after that, it returns None.

The slot name is listed in domain.yml, the model is trained. Based on the records in the database, the slot value was properly set. Any chance to fix this? Of course I can save the slot values to different table (with relation to conversation_id), but thats just a temporary solution...

[<span class="image-wrap" style="">![](https://user-images.githubusercontent.com/92303395/136772800-14e45b31-86c9-4b77-80d7-5b654a5997e4.png)</span>](https://user-images.githubusercontent.com/92303395/136772800-14e45b31-86c9-4b77-80d7-5b654a5997e4.png) [<span class="image-wrap" style="">![](https://user-images.githubusercontent.com/92303395/136772819-94a84a17-8c05-403e-97c5-b207b4cbe93f.png)</span>](https://user-images.githubusercontent.com/92303395/136772819-94a84a17-8c05-403e-97c5-b207b4cbe93f.png)

### Command / Request

 _No response_ 

### Relevant log output

 _No response_

**Comment by sara-tagger** [comment]
Thanks for raising this issue, @tttthomasssss will get back to you about it soon✨

###### Please also check out the [docs](https://rasa.com/docs/) and the [forum](https://forum.rasa.com/) in case your issue was raised there too 🤗

**Comment by usernamedidnotfi** [comment]
Hey @tttthomasssss - here it is.

Thanks a lot for your help.

version: "2.0"

intents:
  - EXTERNAL_reminder

responses:
  utter_what_can_do:
  - text: What can I do for you?
  utter_goodbye:
  - text: Bye

actions:
  - action_quiz

slots:
  current_step:
    type: any
    influence_conversation: false

session_config:
  session_expiration_time: 0
  carry_over_slots_to_new_session: true

**Comment by usernamedidnotfi** [comment]
@tttthomasssss Hey, any updates on this? Thanks!
