### ISSUE TITLE
Rasa x changes the order of the slots

### ISSUE THREAD

**Issue by PAIN-BARHAM** [RasaHQ/rasa#9847]
### Rasa Open Source version

2.8.1

### Rasa SDK version

2.8.1

### Rasa X version

0.39.3

### Python version

3.8

### What operating system are you using?

Linux

### What happened?

Rasa x changes the order of the slots for the form inside the domain file when calling `rasa x` through the command line.

### Command / Request

<pre>rasa x</pre>

### Relevant log output

 _No response_

**Comment by m-vdb** [comment]
Closing as stale
