### ISSUE TITLE
install rasa in macOS M1

### ISSUE THREAD

**Issue by nicoyang-21** [RasaHQ/rasa#9891]
### Rasa Open Source version

2.8

### Python version

3.8

### What operating system are you using?

OSX

### What happened?

I can not install rasa in my computer.

### Command / Request

```shell
pip install rasa
```

**Comment by sara-tagger** [comment]
Thanks for raising this issue, @erohmensing will get back to you about it soon✨

###### Please also check out the [docs](https://rasa.com/docs/) and the [forum](https://forum.rasa.com/) in case your issue was raised there too 🤗

**Comment by sxhysj** [comment]
Any updates on this?

**Comment by rgstephens** [comment]
Yes, see this [post](https://forum.rasa.com/t/an-unofficial-guide-to-installing-rasa-on-an-m1-macbook/51342) by @koaning
