### ISSUE TITLE
Slack channel - start new conversation per thread

### ISSUE THREAD

**Issue by srinivasupadhya** [RasaHQ/rasa#9918]
### What problem are you trying to solve?

Forum post: https://forum.rasa.com/t/slack-channel-start-new-conversation-per-thread/48549

For slack channel currently conversation id (`sender_id`) is set to slack user id.

This causes problems with concurrent conversations with same user across channels / threads

### What's your suggested solution?

Set conversation id as `user_id + _ + channel_id` if `use_threads` is false, `user_id + _ + channel_id + _ + thread_id` if its true.

### Is anything blocking this from being implemented? (if relevant)

This is causing slot values to be overwritten (mixed up) when user is having multiple conversations (threads in same channel) with `use_threads` true

### Definition of Done

Multiple threads on same channel should work as expected

**Comment by sara-tagger** [comment]
Thanks for submitting this feature request 🚀 @aeshky will get back to you about it soon! ✨

**Comment by srinivasupadhya** [comment]
#10086 raised for the same
