### ISSUE TITLE
Small Change to Docs to Make Hello World very fast

### ISSUE THREAD

**Issue by wljsc** [RasaHQ/rasa#9943]
### What problem are you trying to solve?

I am trying to make it very easy for a complete Rasa newbie achieve a successful "Hello World" in 5 minutes or less.

(Such a person would have to know how to use pip and have some experience typing commands at the unix command line)

The way to do this is to make a small change to a particular page of documentation (i.e. this page: [https://rasa.com/docs/rasa/playground/](https://rasa.com/docs/rasa/playground/))

If you want further context on how I stumbled into this issue please see [https://forum.rasa.com/t/rasa-init-deletes-playground-hello-world-fail-for-a-newbie/48139/5](https://forum.rasa.com/t/rasa-init-deletes-playground-hello-world-fail-for-a-newbie/48139/5)

### What's your suggested solution?

The solution is to make the following edit to this page:

[https://rasa.com/docs/rasa/playground/](https://rasa.com/docs/rasa/playground/)

The requested edit involves adding a brief passage (example provided below) under the heading "You have built your assistant! What’s next?"

Under that heading you will see a button called "Download project". Right under that you will see a hyperlink with the title "Install Rasa open source to keep building"

Immediately below that hyper link I propose adding this text. Edit as you see fit:

<<<<------ START OF SUGGESTED ADDITIONAL PASSAGE -------->>>>

After you have installed Rasa, invoked the Rasa environment, make sure you have the "Download Project" button. Once you do a file called project.zip will be downloaded on to your machine. Put that zip file in a folder dedicated to your Rasa project. Move project.zip into that folder. Unzip project.zip.

Finallly, at your unix prompt do the following:

unix% rasa train

A couple hundred lines of status type messages should fly by on your screen as Rasa trains itself on the training data. After about one to five minutes that training will finish and then you should type this at your unix terminal

unix% rasa shell

Your Rasa chatbot should fire up and you should see a text based prompt that says something like:

"Rasa server is up and running. Bot loaded. Type a message and press enter (use '/stop' to exit):"

At this point you are off to the races and you can begin chatting with your chat bot.

<<<<------ END OF SUGGESTED ADDITIONAL PASSAGE -------->>>>

Well that's it. Hope this is a helpful suggestion that will save time to the future me's of the world. (-:

### Examples (if relevant)

 _No response_ 

### Is anything blocking this from being implemented? (if relevant)

 _No response_ 

### Definition of Done

The definition of done is a piece of text added as described above. The exact words are not essential, but something conveying the same level of hand-holding would be wonderful.

Sure, you can find this stuff elsewhere in the docs, but I wasn't able to find it after over 1 hour of searching (as mentioned in my original post to the forum.)

**Comment by sara-tagger** [comment]
Thanks for submitting this feature request 🚀 @tttthomasssss will get back to you about it soon! ✨
