### ISSUE TITLE
Slack websocket channel connector

### ISSUE THREAD

**Issue by rrs45** [RasaHQ/rasa#9944]
### What problem are you trying to solve?

A lot of companies does not allow public facing URL endpoint due to security policies. This is hard blocker for using Rasa with Slack.

### What's your suggested solution?

There is a websocket API available in slack which would solve this problem. Please create Slack websocket channel connecter. Thanks!

Reference: [https://api.slack.com/apis/connections/socket](https://api.slack.com/apis/connections/socket)

### Examples (if relevant)

 _No response_ 

### Is anything blocking this from being implemented? (if relevant)

 _No response_ 

### Definition of Done

Create a channel connector for Slack socket API

**Comment by sirloon** [comment]
Hi, I was able to write [script](https://gist.github.com/sirloon/1b5d0b4c48ce39f79b69edb98b6d6964) combining a Rasa app with a Slack Bolt app. There's a lot of copy/paste, please forgive me ;) but I guess my point is using Bolt there's no need to implement websocket from scratch.

Bolt provides async clients which works nicely with Rasa, the idea is to connect the Rasa agent to an async Bolt handler and call `process_message()`. Not sure where to go from there, not sure what's the dev status of the PR as well.

I'm very new to Rasa and I'm not familiar with the design & architecture, though I saw some useful code, probably, from [SlackInput](https://github.com/RasaHQ/rasa/blob/d04290f371bf5494744e63508c5dc01f4f82d885/rasa/core/channels/slack.py#L121) used to extract and sanitize a Slack message before submitting it to Rasa, I guess this would a good starting point to move forward?

**Comment by rrs45** [comment]
@sirloon does it work without making the App accessible  over the internet? LOoks like it doesn't  and  hence  websockets for slack,  thanks

**Comment by sirloon** [comment]
@rrs45 yes it works without having an app accessible over Internet. I have a chatbot running within a corporate network and talking to slack through that websocket, it runs fine!
