### ISSUE TITLE
Follow up on Tensorflow's recommendation for investigating the slowdown

### ISSUE THREAD

**Issue by dakshvar22** [RasaHQ/rasa#9960]
We have an [ongoing conversation ](https://github.com/tensorflow/tensorflow/issues/51393) with TensorFlow where we are trying to debug the slowdown in certain TF operations that we have seen after upgrading to TF 2.6 . The tensorflow team has come back with a [recommendation](https://github.com/tensorflow/tensorflow/issues/51393#issuecomment-942599120) on what could help us get around the slowdown.

We have made some follow through on the recommendation by [running the model regression tests on **GPU** with the advised change](https://github.com/RasaHQ/rasa/pull/9867). The [initial findings](https://docs.google.com/spreadsheets/d/1sY6BZbygTHXzBm6VwVA6fxVwWnT3YS4LVBb9kyrUUWU/edit?usp=sharing) suggest that there is no significant difference in the training time and test time for the affected configs.

We wanted to run the same model regression tests on CPU but the training and test times that are reported in the model regression test workflow cannot be trusted because of [various reasons](https://rasa-hq.slack.com/archives/C01H2UCNP2T/p1628516013127400?thread_ts=1628513113.122100&cid=C01H2UCNP2T). An initial run done locally suggests that there could indeed be an improvement when pipelines are run on CPU. I ran `Sparse + DIET(seq) + ResponseSelector(t2t)` on Carbon bot data locally with and without the advised change. Here are the results I got:

<div class="table-wrap">
  | 2.8.x | Sparse + DIET(seq) + ResponseSelector(t2t) | Carbon Bot | 550s | | remove_gradient_tape | Sparse + DIET(seq) + ResponseSelector(t2t) | Carbon Bot | 430s | 
</div>

This suggests that the change probably results in an improvement but only on CPU. This needs to be further validated by running experiments on GCP instances so that we have trustable numbers on these.

For comparison to what we had before the upgrade, [this sheet](https://docs.google.com/spreadsheets/d/14rIvQLxEdp1PJDqhM65n0__THKhvS5f4XPLoWz8SWSs/edit?usp=sharing) has training and testing time numbers before and after the TF 2.6 upgrade.

The pipelines which have specifically taken a hit after the upgrade are the ones which include `DIETClassifier` with entity extraction, E2E `TEDpolicy` with entity extraction, or the ones containing the `LanguageModelFeaturizer`.

**Definition of Done:**

*   [x] Run experiments to get these numbers with and without the change for all configurations and datasets that we have been benchmarking on (combinations of NLU + config listed [here](https://github.com/RasaHQ/training-data/blob/main/dataset_config_mapping.json)):

*   *   Training time
    *   Testing time
    *   F1 scores (for intent classification, entity recognition and response selector as applicable)
*   [ ] Based on gathered numbers, followup on the [issue](https://github.com/tensorflow/tensorflow/issues/51393) on the TF repo to give them feedback on the recommendation.

**Comment by b-quachtran** [comment]
@dakshvar22 Do you know if Tensorflow had any insight into why the change resulted in improvements for CPU only? cc: @camattin

**Comment by dakshvar22** [comment]
Hey @b-quachtran Apologies for the delay in response. As far as I can see, we haven't shared the benchmarking numbers on GPU with them. Our contractor Markus was leading that investigation and I'm not sure why those numbers haven't been shared. Although, the concerned tensorflow folks have also been really silent on this and have not come back with responses in 4-5 months on our previous queries.
