### ISSUE TITLE
Custom actions for retrieval intents or sub-intents

### ISSUE THREAD

**Issue by Snorlaxcode** [RasaHQ/rasa#9986]
### What problem are you trying to solve?

Retrieval intents or sub-intents don't have an option to define custom actions. This impedes flexibility in terms of how sub-intents can be used. Importing from data files such as db, json and csv isn't possible. Greater manipulation or verification/conditional statements isnt possible either. Only manually written responses can be used.

When using FAQs, rasa automatically creates utter_faq response and even if I try to define it as a custom action, it is shows me that utter_faq response is not defined and doesn’t detect it in the action.py file.

### What's your suggested solution?

Allow writing custom actions for sub-intents instead of hardcoding the response method. Provide a default response utter_faq or similar but allow for it to be overwritten in actions.py file.

### Examples (if relevant)

 _No response_ 

### Is anything blocking this from being implemented? (if relevant)

No

### Definition of Done

When we are able to define a custom action for each sub-intent in the main intent. If required we can also define a few sub-intents in the response file sub intent.

**Comment by Polaris000** [comment]
@TyDunn could you get back to us on this?

**Comment by TyDunn** [comment]
@Polaris000 Retrieval intents are intended to be used for single turn FAQs. Can you or others in this thread help me understand the problem you are trying to solve with sub-intents?

**Comment by Polaris000** [comment]
Thanks for the reply @TyDunn . I see two use cases off the top of my head (@Snorlaxcode @kormoczi you guys can suggest any others).
- modifying wordings is easier when they are in custom actions. There's no need to train the model again.
- better logic can be handled, like fetching data from API's, or reading from csv's to fetch info for the user.

**Comment by TyDunn** [comment]
@Polaris000 What is the issue with using intents for this?

**Comment by TyDunn** [comment]
> modifying wordings is easier when they are in custom actions. There's no need to train the model again.
As of Rasa Open Source 3.0, when you update `responses`, the model does not retrain. You run `rasa train`, and it updates the response text without retraining the model

**Comment by Snorlaxcode** [comment]
@TyDunn As mentioned in the above text, while using retrieval intents the response method is hardcoded and created as utter_FAQ response which we're not allowed to change. I will elaborate on what @Polaris000 mentioned with reference to my use case, I have a few hundred FAQs in a project. I need to get response data off a secure client database. However, in the current situation, the responses cannot be extracted via API calls or SQL queries. It must be manually (or via script) copy-pasted or put in the domain file. 

The whole point of custom actions' flexibility is lost as I cannot manipulate my responses based on slot values with a loop or conditional as I can do with regular intents. I cannot have conditional statements based on slot values etc.

Another example is of an upcoming project where I need to fine-tune responses. Adding a line or removing in otherwise confusing intents depending on whether or not certain keywords are included. That can only be done by string manipulation which cannot be done with hardcoded responses in domain files. To explain with an example, in a legal chatbot, we may need intents of Marriage, Property Disputes, Corporate cases etc. Each of these might have subcases such as Marriage has alimony, child custody, divorce etc. Even Divorce might need subintents such as filing a divorce, changing terms of divorce, hiring lawyer for divorce etc. Hence, if you have plans of scaling it, it makes sense to support the minimum same functionality in 2nd level intents (retrieval intents) as you do in 1st level intents.
