### ISSUE TITLE
Rasa.com `Rasa on Udemy` link broken

### ISSUE THREAD

**Issue by rgstephens** [RasaHQ/rasa#9995]
### Rasa Open Source version

n/a

### Rasa SDK version

 _No response_ 

### Rasa X version

 _No response_ 

### Python version

3.7

### What operating system are you using?

OSX

### What happened?

The website `Resources > Rasa on Udemy` menu points at [https://info.rasa.com/rasa-courses/](https://info.rasa.com/rasa-courses/) which returns a 404.

### Command / Request

 _No response_ 

### Relevant log output

 _No response_

**Comment by itallogravina** [comment]
Hello, I would like to know if the document has been modified?

**Comment by virtualroot** [comment]
Fix https://github.com/RasaHQ/rasa-website/commit/3c9930e3b62b27d0f9eac3aa9b15a94a6c56e0ff
